{
  "hash": "f70be8e757961c168d729e9325716cb0",
  "result": {
    "markdown": "---\ntitle: \"Final Project Assignment#1: Daniel Hannon\"\nauthor: \"Daniel Hannon\"\ndescription: \"Project & Data Description\"\ndate: \"04-11-2023\"\nformat:\n  html:\n    df-print: paged\n    toc: true\n    code-copy: true\n    code-tools: true\n    css: styles.css\ncategories:\n  - final_Project_assignment_1\n  - final_project_data_description\neditor_options: \n  chunk_output_type: inline\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(ggplot2)\n\nknitr::opts_chunk$set(echo = TRUE)\n```\n:::\n\n\n## Part 1. Introduction {#describe-the-data-sets}\n\nMusic has always evolved alongside media and technology. From radio and cassets, to MTV and DVDs, to the present where streaming and internet music videos are the most common ways for people to enjoy their favorite artists. The dataset I am using connects these two mediums. It is a collection of data about songs on Spotify and the popularity of the most popular corresponding music video on Youtube. The data was collected on February 7th, 2023 using an API that interacted with both Spotify and YouTube. It was collected and edited by Kaggle users Salvatore Rastelli, Marco Guarisco, Marco Sallustio. It is in the public Domain and available for free download [here on Kaggle](https://www.kaggle.com/datasets/salvatorerastelli/spotify-and-youtube?resource=download) \n\n\nI plan to use this dataset to try to answer questions about whether there are certain elements of a song that make it more likely to be a popular music video. Do videos of singles perform better than album songs? Are more energetic songs more likely to be popular on Youtube? Are there any trends that can be seen for songs that have more Youtube views than Spotify streams? I plan to compare the attributes of the highest Streamed songs to the attributes of the most viewed music videos to see if there are certain qualities that perform better on each platform. \n\n## Part 2. Describe the data set(s) {#describe-the-data-sets-1}\n\nThis part contains both a coding and a storytelling component.\n\nEach case in the dataset is a song from Spotify. Each observation is made up of identification data (a unique id, the track name, artist, album, URL on Spotify), then a section on descriptive data about the how the song sounds with measures that Spotify tracks such as the \"dancability\" of the song along with attributes such as the energy, key, tempo, duration, etc. The last part of the observation is information about the most popular video on Youtube when the title of the song is searched. It has identification data for the video (URL, title, description, channel name, and whether or not it is the official music video) as well as popularity measures (views, likes, comments). The last column of the data is the total number of streams that song has on Spotify, and will serve as the baseline popularity of the song. For our purposes, we will filter all the identifiers of a song besides the Track name and Album type, leaving all of the song measures from Spotify, the official_video flag, and the Stream and View numbers to serve as our popularity measures. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nspotify_yt_original <- read.csv(\"DanielHannon_FinalProjectData/Spotify_Youtube.csv\")\n\n#remove all the unnecessary information columns, as well as likes and comments\n#for the purposes of this we will use views and Streams as our metrics of popularity because they are the most comparable \nspotify_yt_data <- spotify_yt_original %>%\n                  select( c(Track, Album_type, Danceability:Duration_ms, Views, official_video, Stream)) %>%\n                  filter(!is.na(Views) & !is.na(Stream)) \n#filter out any songs that don't have any data about views or streams\n\n# Original dataset has dims 20718 x 28\ndim(spotify_yt_data) # After removing NA datapoints dims are 19692 x 16\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 19692    16\n```\n:::\n\n```{.r .cell-code}\nspotify_yt_data %>%\n    select(Track) %>%\n    n_distinct(.)  #16993 unique tracks\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 16993\n```\n:::\n\n```{.r .cell-code}\nspotify_yt_original %>%\n  filter(grepl(\"El Ultimo Adiós - Varios\", Track)) #certain tracks featuring many artists are repeated because the tool that scraped for them took the top ten tracks from various artists. In this example  24 listings of the same song exist, but not all of them have the same Youtube video attached. They all contain the same name, and all of the song data is the same \n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"X\"],\"name\":[1],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Artist\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Url_spotify\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Track\"],\"name\":[4],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Album\"],\"name\":[5],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Album_type\"],\"name\":[6],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Uri\"],\"name\":[7],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Danceability\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Energy\"],\"name\":[9],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Key\"],\"name\":[10],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Loudness\"],\"name\":[11],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Speechiness\"],\"name\":[12],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Acousticness\"],\"name\":[13],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Instrumentalness\"],\"name\":[14],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Liveness\"],\"name\":[15],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Valence\"],\"name\":[16],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Tempo\"],\"name\":[17],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Duration_ms\"],\"name\":[18],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Url_youtube\"],\"name\":[19],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Title\"],\"name\":[20],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Channel\"],\"name\":[21],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Views\"],\"name\":[22],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Likes\"],\"name\":[23],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Comments\"],\"name\":[24],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Description\"],\"name\":[25],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Licensed\"],\"name\":[26],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"official_video\"],\"name\":[27],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Stream\"],\"name\":[28],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"759\",\"2\":\"Alejandro Sanz\",\"3\":\"https://open.spotify.com/artist/5sUrlPAHlS9NEirDB8SEbF\",\"4\":\"El Ultimo Adiós - Varios Artistas Version\",\"5\":\"El Ultimo Adiós\",\"6\":\"single\",\"7\":\"spotify:track:0tzixmHNQfE6S6SirSToxW\",\"8\":\"0.276\",\"9\":\"0.572\",\"10\":\"1\",\"11\":\"-7.818\",\"12\":\"0.0377\",\"13\":\"0.641\",\"14\":\"0\",\"15\":\"0.2\",\"16\":\"0.285\",\"17\":\"77.986\",\"18\":\"237467\",\"19\":\"https://www.youtube.com/watch?v=zxG1Yj1Si58\",\"20\":\"Varios Artistas Latinos - EL Ultimo Adios\",\"21\":\"Catheleya R\",\"22\":\"764831\",\"23\":\"5730\",\"24\":\"472\",\"25\":\"Video con varios artistas haciendole tributo a los afectados del 11 de Septiembre...\",\"26\":\"False\",\"27\":\"False\",\"28\":\"169769959\"},{\"1\":\"809\",\"2\":\"Christina Aguilera\",\"3\":\"https://open.spotify.com/artist/1l7ZsJRRS8wlW3WfJfPfNS\",\"4\":\"El Ultimo Adiós - Varios Artistas Version\",\"5\":\"El Ultimo Adiós\",\"6\":\"single\",\"7\":\"spotify:track:0tzixmHNQfE6S6SirSToxW\",\"8\":\"0.276\",\"9\":\"0.572\",\"10\":\"1\",\"11\":\"-7.818\",\"12\":\"0.0377\",\"13\":\"0.641\",\"14\":\"0\",\"15\":\"0.2\",\"16\":\"0.285\",\"17\":\"77.986\",\"18\":\"237467\",\"19\":\"https://www.youtube.com/watch?v=xzFhO4PaIbw\",\"20\":\"Christina Aguilera ft Varios Artistas - El Ultimo Adiós\",\"21\":\"jesus sanchez\",\"22\":\"8605\",\"23\":\"118\",\"24\":\"7\",\"25\":\"Tributo A Las Victimas Del 11 De Septiembre Del 2001. Ricky Martin, Alejandro Sanz, Thalía, Juan Luis Guerra, Gloria Estefan, Celia Cruz, Olga Tañon, Ricardo Montaner, Ana Gabriel, Jorge Hernandez, Los Tigres Del Norte, Alicia Villareal, Alejandro Fernández, Carlos Vives, Jaci Velasquez, Marco Antonio Solís, José José, Lucía Méndez, Jennifer Lopez, Emmanuele, Chayanne, Gilberto Santa Rosa, Paulina Rubio, Alberto \\\"Beto\\\" Zapata, La Ley, Ana Barbara, Carlos Ponce, Jon Secada, Shakira, Gian Marco, Luis Fonsi, Yuri, Miguel Bosé, Wilkins, Giselle, Melina Leon, Limi-t XXI, CHRISTINA AGUILERA, Josè Feliciano, José Luis Rodríguez\",\"26\":\"False\",\"27\":\"False\",\"28\":\"169769959\"},{\"1\":\"900\",\"2\":\"Alejandro Fernández\",\"3\":\"https://open.spotify.com/artist/6sq1yF0OZEWA4xoXVKW1L9\",\"4\":\"El Ultimo Adiós - Varios Artistas Version\",\"5\":\"El Ultimo Adiós\",\"6\":\"single\",\"7\":\"spotify:track:0tzixmHNQfE6S6SirSToxW\",\"8\":\"0.276\",\"9\":\"0.572\",\"10\":\"1\",\"11\":\"-7.818\",\"12\":\"0.0377\",\"13\":\"0.641\",\"14\":\"0\",\"15\":\"0.2\",\"16\":\"0.285\",\"17\":\"77.986\",\"18\":\"237467\",\"19\":\"https://www.youtube.com/watch?v=zxG1Yj1Si58\",\"20\":\"Varios Artistas Latinos - EL Ultimo Adios\",\"21\":\"Catheleya R\",\"22\":\"764831\",\"23\":\"5730\",\"24\":\"472\",\"25\":\"Video con varios artistas haciendole tributo a los afectados del 11 de Septiembre...\",\"26\":\"False\",\"27\":\"False\",\"28\":\"169769959\"},{\"1\":\"1148\",\"2\":\"Luis Fonsi\",\"3\":\"https://open.spotify.com/artist/4V8Sr092TqfHkfAA5fXXqG\",\"4\":\"El Ultimo Adiós - Varios Artistas Version\",\"5\":\"El Ultimo Adiós\",\"6\":\"single\",\"7\":\"spotify:track:0tzixmHNQfE6S6SirSToxW\",\"8\":\"0.276\",\"9\":\"0.572\",\"10\":\"1\",\"11\":\"-7.818\",\"12\":\"0.0377\",\"13\":\"0.641\",\"14\":\"0\",\"15\":\"0.2\",\"16\":\"0.285\",\"17\":\"77.986\",\"18\":\"237467\",\"19\":\"https://www.youtube.com/watch?v=z8ZFZD3fuJU\",\"20\":\"EL ULTIMO ADIOS Ricky Martin Alejandro Sanz Thalia Shakira Gloria Estefan Chayanne Celia Cruz Juan Luis Guerra Luis Fonsi Carlos Vives Ricardo Montaner Alejandro Frnandez   El Ultimo Adios\",\"21\":\"Liannishabana\",\"22\":\"129107\",\"23\":\"973\",\"24\":\"107\",\"25\":\"\",\"26\":\"False\",\"27\":\"False\",\"28\":\"169769959\"},{\"1\":\"1247\",\"2\":\"José José\",\"3\":\"https://open.spotify.com/artist/4mN0qcMxWX8oToqfDPM5yV\",\"4\":\"El Ultimo Adiós - Varios Artistas Version\",\"5\":\"El Ultimo Adiós\",\"6\":\"single\",\"7\":\"spotify:track:0tzixmHNQfE6S6SirSToxW\",\"8\":\"0.276\",\"9\":\"0.572\",\"10\":\"1\",\"11\":\"-7.818\",\"12\":\"0.0377\",\"13\":\"0.641\",\"14\":\"0\",\"15\":\"0.2\",\"16\":\"0.285\",\"17\":\"77.986\",\"18\":\"237467\",\"19\":\"https://www.youtube.com/watch?v=zxG1Yj1Si58\",\"20\":\"Varios Artistas Latinos - EL Ultimo Adios\",\"21\":\"Catheleya R\",\"22\":\"764831\",\"23\":\"5730\",\"24\":\"472\",\"25\":\"Video con varios artistas haciendole tributo a los afectados del 11 de Septiembre...\",\"26\":\"False\",\"27\":\"False\",\"28\":\"169769959\"},{\"1\":\"1257\",\"2\":\"Los Tigres Del Norte\",\"3\":\"https://open.spotify.com/artist/3hYtANQYrE6pd2PbtEyTIy\",\"4\":\"El Ultimo Adiós - Varios Artistas Version\",\"5\":\"El Ultimo Adiós\",\"6\":\"single\",\"7\":\"spotify:track:0tzixmHNQfE6S6SirSToxW\",\"8\":\"0.276\",\"9\":\"0.572\",\"10\":\"1\",\"11\":\"-7.818\",\"12\":\"0.0377\",\"13\":\"0.641\",\"14\":\"0\",\"15\":\"0.2\",\"16\":\"0.285\",\"17\":\"77.986\",\"18\":\"237467\",\"19\":\"https://www.youtube.com/watch?v=zxG1Yj1Si58\",\"20\":\"Varios Artistas Latinos - EL Ultimo Adios\",\"21\":\"Catheleya R\",\"22\":\"764831\",\"23\":\"5730\",\"24\":\"472\",\"25\":\"Video con varios artistas haciendole tributo a los afectados del 11 de Septiembre...\",\"26\":\"False\",\"27\":\"False\",\"28\":\"169769959\"},{\"1\":\"1297\",\"2\":\"Ricky Martin\",\"3\":\"https://open.spotify.com/artist/7slfeZO9LsJbWgpkIoXBUJ\",\"4\":\"El Ultimo Adiós - Varios Artistas Version\",\"5\":\"El Ultimo Adiós\",\"6\":\"single\",\"7\":\"spotify:track:0tzixmHNQfE6S6SirSToxW\",\"8\":\"0.276\",\"9\":\"0.572\",\"10\":\"1\",\"11\":\"-7.818\",\"12\":\"0.0377\",\"13\":\"0.641\",\"14\":\"0\",\"15\":\"0.2\",\"16\":\"0.285\",\"17\":\"77.986\",\"18\":\"237467\",\"19\":\"https://www.youtube.com/watch?v=zxG1Yj1Si58\",\"20\":\"Varios Artistas Latinos - EL Ultimo Adios\",\"21\":\"Catheleya R\",\"22\":\"764831\",\"23\":\"5730\",\"24\":\"472\",\"25\":\"Video con varios artistas haciendole tributo a los afectados del 11 de Septiembre...\",\"26\":\"False\",\"27\":\"False\",\"28\":\"169769959\"},{\"1\":\"1308\",\"2\":\"Jennifer Lopez\",\"3\":\"https://open.spotify.com/artist/2DlGxzQSjYe5N6G9nkYghR\",\"4\":\"El Ultimo Adiós - Varios Artistas Version\",\"5\":\"El Ultimo Adiós\",\"6\":\"single\",\"7\":\"spotify:track:0tzixmHNQfE6S6SirSToxW\",\"8\":\"0.276\",\"9\":\"0.572\",\"10\":\"1\",\"11\":\"-7.818\",\"12\":\"0.0377\",\"13\":\"0.641\",\"14\":\"0\",\"15\":\"0.2\",\"16\":\"0.285\",\"17\":\"77.986\",\"18\":\"237467\",\"19\":\"https://www.youtube.com/watch?v=zxG1Yj1Si58\",\"20\":\"Varios Artistas Latinos - EL Ultimo Adios\",\"21\":\"Catheleya R\",\"22\":\"764831\",\"23\":\"5730\",\"24\":\"472\",\"25\":\"Video con varios artistas haciendole tributo a los afectados del 11 de Septiembre...\",\"26\":\"False\",\"27\":\"False\",\"28\":\"169769959\"},{\"1\":\"1367\",\"2\":\"Marco Antonio Solís\",\"3\":\"https://open.spotify.com/artist/3tJnB0s6c3oXPq1SCCavnd\",\"4\":\"El Ultimo Adiós - Varios Artistas Version\",\"5\":\"El Ultimo Adiós\",\"6\":\"single\",\"7\":\"spotify:track:0tzixmHNQfE6S6SirSToxW\",\"8\":\"0.276\",\"9\":\"0.572\",\"10\":\"1\",\"11\":\"-7.818\",\"12\":\"0.0377\",\"13\":\"0.641\",\"14\":\"0\",\"15\":\"0.2\",\"16\":\"0.285\",\"17\":\"77.986\",\"18\":\"237467\",\"19\":\"https://www.youtube.com/watch?v=zxG1Yj1Si58\",\"20\":\"Varios Artistas Latinos - EL Ultimo Adios\",\"21\":\"Catheleya R\",\"22\":\"764831\",\"23\":\"5730\",\"24\":\"472\",\"25\":\"Video con varios artistas haciendole tributo a los afectados del 11 de Septiembre...\",\"26\":\"False\",\"27\":\"False\",\"28\":\"169769959\"},{\"1\":\"2316\",\"2\":\"Chayanne\",\"3\":\"https://open.spotify.com/artist/1JbemQ1fPt2YmSLjAFhPBv\",\"4\":\"El Ultimo Adiós - Varios Artistas Version\",\"5\":\"El Ultimo Adiós\",\"6\":\"single\",\"7\":\"spotify:track:0tzixmHNQfE6S6SirSToxW\",\"8\":\"0.276\",\"9\":\"0.572\",\"10\":\"1\",\"11\":\"-7.818\",\"12\":\"0.0377\",\"13\":\"0.641\",\"14\":\"0\",\"15\":\"0.2\",\"16\":\"0.285\",\"17\":\"77.986\",\"18\":\"237467\",\"19\":\"https://www.youtube.com/watch?v=z8ZFZD3fuJU\",\"20\":\"EL ULTIMO ADIOS Ricky Martin Alejandro Sanz Thalia Shakira Gloria Estefan Chayanne Celia Cruz Juan Luis Guerra Luis Fonsi Carlos Vives Ricardo Montaner Alejandro Frnandez   El Ultimo Adios\",\"21\":\"Liannishabana\",\"22\":\"129107\",\"23\":\"973\",\"24\":\"107\",\"25\":\"\",\"26\":\"False\",\"27\":\"False\",\"28\":\"169769959\"},{\"1\":\"2356\",\"2\":\"Ana Gabriel\",\"3\":\"https://open.spotify.com/artist/41ESHLayJ5sDKjAOv6cMhe\",\"4\":\"El Ultimo Adiós - Varios Artistas Version\",\"5\":\"El Ultimo Adiós\",\"6\":\"single\",\"7\":\"spotify:track:0tzixmHNQfE6S6SirSToxW\",\"8\":\"0.276\",\"9\":\"0.572\",\"10\":\"1\",\"11\":\"-7.818\",\"12\":\"0.0377\",\"13\":\"0.641\",\"14\":\"0\",\"15\":\"0.2\",\"16\":\"0.285\",\"17\":\"77.986\",\"18\":\"237467\",\"19\":\"https://www.youtube.com/watch?v=2iQmpE8ZjEs\",\"20\":\"Ana gabriel el ultimo Adios (JM)\",\"21\":\"J3ko Blogs\",\"22\":\"1437797\",\"23\":\"6786\",\"24\":\"109\",\"25\":\"el ultimo adiós año 1994 álbum ayer y hoy.\\\\ncon respeto ya admiración para la reina de México\\\\ny todos sus fans.\",\"26\":\"False\",\"27\":\"False\",\"28\":\"169769959\"},{\"1\":\"2726\",\"2\":\"José Feliciano\",\"3\":\"https://open.spotify.com/artist/7K78lVZ8XzkjfRSI7570FF\",\"4\":\"El Ultimo Adiós - Varios Artistas Version\",\"5\":\"El Ultimo Adiós\",\"6\":\"single\",\"7\":\"spotify:track:0tzixmHNQfE6S6SirSToxW\",\"8\":\"0.276\",\"9\":\"0.572\",\"10\":\"1\",\"11\":\"-7.818\",\"12\":\"0.0377\",\"13\":\"0.641\",\"14\":\"0\",\"15\":\"0.2\",\"16\":\"0.285\",\"17\":\"77.986\",\"18\":\"237467\",\"19\":\"https://www.youtube.com/watch?v=zxG1Yj1Si58\",\"20\":\"Varios Artistas Latinos - EL Ultimo Adios\",\"21\":\"Catheleya R\",\"22\":\"764832\",\"23\":\"5730\",\"24\":\"472\",\"25\":\"Video con varios artistas haciendole tributo a los afectados del 11 de Septiembre...\",\"26\":\"False\",\"27\":\"False\",\"28\":\"169769959\"},{\"1\":\"2895\",\"2\":\"Thalia\",\"3\":\"https://open.spotify.com/artist/23wEWD21D4TPYiJugoXmYb\",\"4\":\"El Ultimo Adiós - Varios Artistas Version\",\"5\":\"El Ultimo Adiós\",\"6\":\"single\",\"7\":\"spotify:track:0tzixmHNQfE6S6SirSToxW\",\"8\":\"0.276\",\"9\":\"0.572\",\"10\":\"1\",\"11\":\"-7.818\",\"12\":\"0.0377\",\"13\":\"0.641\",\"14\":\"0\",\"15\":\"0.2\",\"16\":\"0.285\",\"17\":\"77.986\",\"18\":\"237467\",\"19\":\"https://www.youtube.com/watch?v=VTs2X79HoS0\",\"20\":\"Thalía & Varios Artistas - El Ultimo Adiós (The Last Goodbye)\",\"21\":\"Thalia Remixes\",\"22\":\"1067\",\"23\":\"77\",\"24\":\"6\",\"25\":\"SIGUE A “Thalia” EN: \\\\nPágina web oficial: http://www.thalia.com \\\\nFacebook: http://www.facebook.com/Thalia\\\\nTwitter: http://www.twitter.com/thalia    \\\\nInstagram: http://www.instagram.com/thalia \\\\n\\\\nSIGUE A “DJ Edson” EN: \\\\nFacebook: https://www.facebook.com/djedsonremix\\\\nInstagram: http://www.instagram.com/djedsonbolivia\\\\nFacebook: https://www.facebook.com/djedsonbolivia\\\\nFacebook Thalía Fan Page: https://www.facebook.com/realthaliaofficial\\\\n\\\\n#Thalia #ElUltimoAdiós #TheLastGoodbye\",\"26\":\"False\",\"27\":\"False\",\"28\":\"169769959\"},{\"1\":\"3195\",\"2\":\"Miguel Bosé\",\"3\":\"https://open.spotify.com/artist/7mWCSSOYqm4E9mB7V4ot6S\",\"4\":\"El Ultimo Adiós - Varios Artistas Version\",\"5\":\"El Ultimo Adiós\",\"6\":\"single\",\"7\":\"spotify:track:0tzixmHNQfE6S6SirSToxW\",\"8\":\"0.276\",\"9\":\"0.572\",\"10\":\"1\",\"11\":\"-7.818\",\"12\":\"0.0377\",\"13\":\"0.641\",\"14\":\"0\",\"15\":\"0.2\",\"16\":\"0.285\",\"17\":\"77.986\",\"18\":\"237467\",\"19\":\"https://www.youtube.com/watch?v=zxG1Yj1Si58\",\"20\":\"Varios Artistas Latinos - EL Ultimo Adios\",\"21\":\"Catheleya R\",\"22\":\"764832\",\"23\":\"5730\",\"24\":\"472\",\"25\":\"Video con varios artistas haciendole tributo a los afectados del 11 de Septiembre...\",\"26\":\"False\",\"27\":\"False\",\"28\":\"169769959\"},{\"1\":\"3315\",\"2\":\"Gilberto Santa Rosa\",\"3\":\"https://open.spotify.com/artist/27vNK840zYq6IfDijHPsv1\",\"4\":\"El Ultimo Adiós - Varios Artistas Version\",\"5\":\"El Ultimo Adiós\",\"6\":\"single\",\"7\":\"spotify:track:0tzixmHNQfE6S6SirSToxW\",\"8\":\"0.276\",\"9\":\"0.572\",\"10\":\"1\",\"11\":\"-7.818\",\"12\":\"0.0377\",\"13\":\"0.641\",\"14\":\"0\",\"15\":\"0.2\",\"16\":\"0.285\",\"17\":\"77.986\",\"18\":\"237467\",\"19\":\"https://www.youtube.com/watch?v=zxG1Yj1Si58\",\"20\":\"Varios Artistas Latinos - EL Ultimo Adios\",\"21\":\"Catheleya R\",\"22\":\"764832\",\"23\":\"5730\",\"24\":\"472\",\"25\":\"Video con varios artistas haciendole tributo a los afectados del 11 de Septiembre...\",\"26\":\"False\",\"27\":\"False\",\"28\":\"169769959\"},{\"1\":\"3335\",\"2\":\"Ricardo Montaner\",\"3\":\"https://open.spotify.com/artist/4uoz4FUMvpeyGClFTTDBsD\",\"4\":\"El Ultimo Adiós - Varios Artistas Version\",\"5\":\"El Ultimo Adiós\",\"6\":\"single\",\"7\":\"spotify:track:0tzixmHNQfE6S6SirSToxW\",\"8\":\"0.276\",\"9\":\"0.572\",\"10\":\"1\",\"11\":\"-7.818\",\"12\":\"0.0377\",\"13\":\"0.641\",\"14\":\"0\",\"15\":\"0.2\",\"16\":\"0.285\",\"17\":\"77.986\",\"18\":\"237467\",\"19\":\"https://www.youtube.com/watch?v=z8ZFZD3fuJU\",\"20\":\"EL ULTIMO ADIOS Ricky Martin Alejandro Sanz Thalia Shakira Gloria Estefan Chayanne Celia Cruz Juan Luis Guerra Luis Fonsi Carlos Vives Ricardo Montaner Alejandro Frnandez   El Ultimo Adios\",\"21\":\"Liannishabana\",\"22\":\"129107\",\"23\":\"973\",\"24\":\"107\",\"25\":\"\",\"26\":\"False\",\"27\":\"False\",\"28\":\"169769959\"},{\"1\":\"4304\",\"2\":\"Paulina Rubio\",\"3\":\"https://open.spotify.com/artist/1d6dwipPrsFSJVmFTTdFSS\",\"4\":\"El Ultimo Adiós - Varios Artistas Version\",\"5\":\"El Ultimo Adiós\",\"6\":\"single\",\"7\":\"spotify:track:0tzixmHNQfE6S6SirSToxW\",\"8\":\"0.276\",\"9\":\"0.572\",\"10\":\"1\",\"11\":\"-7.818\",\"12\":\"0.0377\",\"13\":\"0.641\",\"14\":\"0\",\"15\":\"0.2\",\"16\":\"0.285\",\"17\":\"77.986\",\"18\":\"237467\",\"19\":\"https://www.youtube.com/watch?v=jNLU_A1d_60\",\"20\":\"Paulina Rubio - El Último Adiós\",\"21\":\"Paulina Rubio\",\"22\":\"58118240\",\"23\":\"239180\",\"24\":\"5664\",\"25\":\"Paulina Rubio - El Último Adiós\",\"26\":\"False\",\"27\":\"True\",\"28\":\"169769959\"},{\"1\":\"4882\",\"2\":\"Yuri\",\"3\":\"https://open.spotify.com/artist/4OgNARLQSC4yy7Dsa5cqxx\",\"4\":\"El Ultimo Adiós - Varios Artistas Version\",\"5\":\"El Ultimo Adiós\",\"6\":\"single\",\"7\":\"spotify:track:0tzixmHNQfE6S6SirSToxW\",\"8\":\"0.276\",\"9\":\"0.572\",\"10\":\"1\",\"11\":\"-7.818\",\"12\":\"0.0377\",\"13\":\"0.641\",\"14\":\"0\",\"15\":\"0.2\",\"16\":\"0.285\",\"17\":\"77.986\",\"18\":\"237467\",\"19\":\"https://www.youtube.com/watch?v=BX38njyi9dk\",\"20\":\"El Último Adiós (The Last Goodbye) Jaci Velasquez, Gloria Estefan, Yuri...\",\"21\":\"Jaci Velasquez Love Fans\",\"22\":\"286491\",\"23\":\"1466\",\"24\":\"278\",\"25\":\"Artistas interpretan la canción \\\"El Último Adiós\\\" en vivo, desde la Casa Blanca / Artists perform the song \\\"The Last Goodbye\\\" live from the White House.\\\\n\\\\nJaci Velasquez, Gloria Estefan, Yuri, Ricardo Montaner, Gian Marco Zignago, José José, Luis Fonsi, Ednita Nazario\",\"26\":\"False\",\"27\":\"False\",\"28\":\"169769959\"},{\"1\":\"5182\",\"2\":\"Gloria Estefan\",\"3\":\"https://open.spotify.com/artist/5IFCkqu9J6xdWeYMk5I889\",\"4\":\"El Ultimo Adiós - Varios Artistas Version\",\"5\":\"El Ultimo Adiós\",\"6\":\"single\",\"7\":\"spotify:track:0tzixmHNQfE6S6SirSToxW\",\"8\":\"0.276\",\"9\":\"0.572\",\"10\":\"1\",\"11\":\"-7.818\",\"12\":\"0.0377\",\"13\":\"0.641\",\"14\":\"0\",\"15\":\"0.2\",\"16\":\"0.285\",\"17\":\"77.986\",\"18\":\"237467\",\"19\":\"https://www.youtube.com/watch?v=BX38njyi9dk\",\"20\":\"El Último Adiós (The Last Goodbye) Jaci Velasquez, Gloria Estefan, Yuri...\",\"21\":\"Jaci Velasquez Love Fans\",\"22\":\"286491\",\"23\":\"1466\",\"24\":\"278\",\"25\":\"Artistas interpretan la canción \\\"El Último Adiós\\\" en vivo, desde la Casa Blanca / Artists perform the song \\\"The Last Goodbye\\\" live from the White House.\\\\n\\\\nJaci Velasquez, Gloria Estefan, Yuri, Ricardo Montaner, Gian Marco Zignago, José José, Luis Fonsi, Ednita Nazario\",\"26\":\"False\",\"27\":\"False\",\"28\":\"169769959\"},{\"1\":\"5672\",\"2\":\"Celia Cruz\",\"3\":\"https://open.spotify.com/artist/2weA6hhVqTIN2gSn9PUB9U\",\"4\":\"El Ultimo Adiós - Varios Artistas Version\",\"5\":\"El Ultimo Adiós\",\"6\":\"single\",\"7\":\"spotify:track:0tzixmHNQfE6S6SirSToxW\",\"8\":\"0.276\",\"9\":\"0.572\",\"10\":\"1\",\"11\":\"-7.818\",\"12\":\"0.0377\",\"13\":\"0.641\",\"14\":\"0\",\"15\":\"0.2\",\"16\":\"0.285\",\"17\":\"77.986\",\"18\":\"237467\",\"19\":\"https://www.youtube.com/watch?v=z8ZFZD3fuJU\",\"20\":\"EL ULTIMO ADIOS Ricky Martin Alejandro Sanz Thalia Shakira Gloria Estefan Chayanne Celia Cruz Juan Luis Guerra Luis Fonsi Carlos Vives Ricardo Montaner Alejandro Frnandez   El Ultimo Adios\",\"21\":\"Liannishabana\",\"22\":\"129108\",\"23\":\"973\",\"24\":\"107\",\"25\":\"\",\"26\":\"False\",\"27\":\"False\",\"28\":\"169769959\"},{\"1\":\"6261\",\"2\":\"La Ley\",\"3\":\"https://open.spotify.com/artist/1ZVoRDO29AlDXiMkRLMZSK\",\"4\":\"El Ultimo Adiós - Varios Artistas Version\",\"5\":\"El Ultimo Adiós\",\"6\":\"single\",\"7\":\"spotify:track:0tzixmHNQfE6S6SirSToxW\",\"8\":\"0.276\",\"9\":\"0.572\",\"10\":\"1\",\"11\":\"-7.818\",\"12\":\"0.0377\",\"13\":\"0.641\",\"14\":\"0\",\"15\":\"0.2\",\"16\":\"0.285\",\"17\":\"77.986\",\"18\":\"237467\",\"19\":\"https://www.youtube.com/watch?v=zxG1Yj1Si58\",\"20\":\"Varios Artistas Latinos - EL Ultimo Adios\",\"21\":\"Catheleya R\",\"22\":\"764832\",\"23\":\"5730\",\"24\":\"472\",\"25\":\"Video con varios artistas haciendole tributo a los afectados del 11 de Septiembre...\",\"26\":\"False\",\"27\":\"False\",\"28\":\"169769959\"},{\"1\":\"8167\",\"2\":\"Juan Luis Guerra 4.40\",\"3\":\"https://open.spotify.com/artist/3nlpTZci9O5W8RsNoNH559\",\"4\":\"El Ultimo Adiós - Varios Artistas Version\",\"5\":\"El Ultimo Adiós\",\"6\":\"single\",\"7\":\"spotify:track:0tzixmHNQfE6S6SirSToxW\",\"8\":\"0.276\",\"9\":\"0.572\",\"10\":\"1\",\"11\":\"-7.818\",\"12\":\"0.0377\",\"13\":\"0.641\",\"14\":\"0\",\"15\":\"0.2\",\"16\":\"0.285\",\"17\":\"77.986\",\"18\":\"237467\",\"19\":\"\",\"20\":\"\",\"21\":\"\",\"22\":\"NA\",\"23\":\"NA\",\"24\":\"NA\",\"25\":\"\",\"26\":\"\",\"27\":\"\",\"28\":\"169769959\"},{\"1\":\"8189\",\"2\":\"Carlos Vives\",\"3\":\"https://open.spotify.com/artist/4vhNDa5ycK0ST968ek7kRr\",\"4\":\"El Ultimo Adiós - Varios Artistas Version\",\"5\":\"El Ultimo Adiós\",\"6\":\"single\",\"7\":\"spotify:track:0tzixmHNQfE6S6SirSToxW\",\"8\":\"0.276\",\"9\":\"0.572\",\"10\":\"1\",\"11\":\"-7.818\",\"12\":\"0.0377\",\"13\":\"0.641\",\"14\":\"0\",\"15\":\"0.2\",\"16\":\"0.285\",\"17\":\"77.986\",\"18\":\"237467\",\"19\":\"https://www.youtube.com/watch?v=zxG1Yj1Si58\",\"20\":\"Varios Artistas Latinos - EL Ultimo Adios\",\"21\":\"Catheleya R\",\"22\":\"764832\",\"23\":\"5730\",\"24\":\"472\",\"25\":\"Video con varios artistas haciendole tributo a los afectados del 11 de Septiembre...\",\"26\":\"False\",\"27\":\"False\",\"28\":\"169769959\"},{\"1\":\"9076\",\"2\":\"Ana Bárbara\",\"3\":\"https://open.spotify.com/artist/43qxAkuKFB6fMNSeS5dO7Z\",\"4\":\"El Ultimo Adiós - Varios Artistas Version\",\"5\":\"El Ultimo Adiós\",\"6\":\"single\",\"7\":\"spotify:track:0tzixmHNQfE6S6SirSToxW\",\"8\":\"0.276\",\"9\":\"0.572\",\"10\":\"1\",\"11\":\"-7.818\",\"12\":\"0.0377\",\"13\":\"0.641\",\"14\":\"0\",\"15\":\"0.2\",\"16\":\"0.285\",\"17\":\"77.986\",\"18\":\"237467\",\"19\":\"https://www.youtube.com/watch?v=zxG1Yj1Si58\",\"20\":\"Varios Artistas Latinos - EL Ultimo Adios\",\"21\":\"Catheleya R\",\"22\":\"764832\",\"23\":\"5730\",\"24\":\"472\",\"25\":\"Video con varios artistas haciendole tributo a los afectados del 11 de Septiembre...\",\"26\":\"False\",\"27\":\"False\",\"28\":\"169769959\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\nRight now the data has a lot of repeat tracks, about 2.7 thousand, and a big part of tidying the data is going to be cleaning up the repeat tracks, without throwing away tracks that simply have the same name as another track.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#|label: remove duplicate tracks\nspotify_yt_data <- spotify_yt_data %>%\n        group_by(Duration_ms, Energy, Tempo, Danceability, Valence) %>%   #Group the songs that are duplicates\n        arrange(desc(Views))%>%           #We want to study the highest viewed video\n        slice(1) %>%                      #for each track so we slice one\n        ungroup()                         #Ungroup for further analysis \n\ndim(spotify_yt_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 17960    16\n```\n:::\n:::\n\nThe above code chunk shows how I remove all the repeated songs in the data set. I saw that tracks tat were scrapped twice had identical Spotify reported values. I wanted to make sure I was removing as many duplicates as possible without removing any non-duplicate songs that happen to have the same name as another song. I experimented with different values to group the data by and reported the dimensions of the corresponding data frame.\n\nValue Paired with Track | # of Observations\n----------------------- | -----------------\nNone (Track Alone)      | 16993\nStream                  | 18110   \nEnergy                  | 17961   \nDanceability            | 17959\nDuration                | 17961\nValence                 | 17961\nTempo                   | 17964\n\nHowever, I found When using Duration_ms, Valence, Danceability, Tempo and Energy without\ngrouping by track we get 17960 observations. The one difference is most likely in the case of Taki Taki (with Selena Gomez, Ozuna & Cardi B)\twhich is repeated with all the same values but with the track name Taki Taki (feat. Selena Gomez, Ozuna & Cardi B). The difference between feat. and with makes this register as two separate tracks when you group_by track. This song has enough views on it's YouTube video (39th most in the dataset) that it should not be counted twice, so we will group_by using Duration_ms, Valence, Danceability, Tempo and Energy without grouping by track.\n          \nI kept the track with the highest corresponding viewed YouTube video for any songs that were repeated. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nspotify_yt_data %>% \n        select(Track) %>%\n        summarytools::dfSummary(varnumbers = FALSE,\n                        plain.ascii  = FALSE, \n                        style        = \"grid\", \n                        graph.magnif = 0.50, \n                        valid.col    = FALSE)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Variable\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Stats / Values\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Freqs (% of Valid)\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Graph\"],\"name\":[4],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"text.graph\"],\"name\":[5],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Missing\"],\"name\":[6],\"type\":[\"chr\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"Track\\\\\\\\\\\\n[character]\",\"2\":\"1\\\\\\\\. Heaven\\\\\\\\\\\\n2\\\\\\\\. Angel\\\\\\\\\\\\n3\\\\\\\\. Home\\\\\\\\\\\\n4\\\\\\\\. Candy\\\\\\\\\\\\n5\\\\\\\\. Forever\\\\\\\\\\\\n6\\\\\\\\. Again\\\\\\\\\\\\n7\\\\\\\\. Alone\\\\\\\\\\\\n8\\\\\\\\. Body\\\\\\\\\\\\n9\\\\\\\\. Contigo\\\\\\\\\\\\n10\\\\\\\\. Crazy\\\\\\\\\\\\n[ 16979 others ]\",\"3\":\"\\\\\\\\    9 ( 0.1%)\\\\\\\\\\\\n\\\\\\\\    7 ( 0.0%)\\\\\\\\\\\\n\\\\\\\\    7 ( 0.0%)\\\\\\\\\\\\n\\\\\\\\    6 ( 0.0%)\\\\\\\\\\\\n\\\\\\\\    6 ( 0.0%)\\\\\\\\\\\\n\\\\\\\\    5 ( 0.0%)\\\\\\\\\\\\n\\\\\\\\    5 ( 0.0%)\\\\\\\\\\\\n\\\\\\\\    5 ( 0.0%)\\\\\\\\\\\\n\\\\\\\\    5 ( 0.0%)\\\\\\\\\\\\n\\\\\\\\    5 ( 0.0%)\\\\\\\\\\\\n\\\\\\\\17900 (99.7%)\",\"4\":\"<img style=\\\"border:none;background-color:transparent;padding:0;max-width:max-content;\\\" src=\\\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFcAAACIBAMAAABgjmqlAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5wUKExIYFTAbIgAAAG9JREFUWMPt0b0JgFAAA2FH0A38GcH9d7MR61Mh5MGl/oqDTNOY2xawWdyLiW1rFmcwsW3N4gwmtq1ZnMHEtjWLM5jYtmbxZ0xsW7M4g4ltaxZnMLFtzeIMJratWZzBxD54J1tvfJxg4t/41Smj7QLBOnWqVlnDkAAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMy0wNS0xMFQxOToxODoyNCswMDowMPJh2o8AAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjMtMDUtMTBUMTk6MTg6MjQrMDA6MDCDPGIzAAAAAElFTkSuQmCC\\\">\",\"5\":\"\\\\\\\\ \\\\n \\\\\\\\ \\\\n \\\\\\\\ \\\\n \\\\\\\\ \\\\n \\\\\\\\ \\\\n \\\\\\\\ \\\\n \\\\\\\\ \\\\n \\\\\\\\ \\\\n \\\\\\\\ \\\\n \\\\\\\\ \\\\nIIIIIIIIIIIIIIIIIII\",\"6\":\"0\\\\\\\\\\\\n(0.0%)\",\"_rn_\":\"1\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\n#This shows that there are still duplicate tracks, but these might be different songs with the same name\n\nspotify_yt_original %>%\n  filter(Track == \"Heaven\")  # Quick sanity check: Heaven is the most repeated track now, but upon inpsecting the data, the values are different enough that they all appear to be unique songs.\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"X\"],\"name\":[1],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Artist\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Url_spotify\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Track\"],\"name\":[4],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Album\"],\"name\":[5],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Album_type\"],\"name\":[6],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Uri\"],\"name\":[7],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Danceability\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Energy\"],\"name\":[9],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Key\"],\"name\":[10],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Loudness\"],\"name\":[11],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Speechiness\"],\"name\":[12],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Acousticness\"],\"name\":[13],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Instrumentalness\"],\"name\":[14],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Liveness\"],\"name\":[15],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Valence\"],\"name\":[16],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Tempo\"],\"name\":[17],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Duration_ms\"],\"name\":[18],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Url_youtube\"],\"name\":[19],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Title\"],\"name\":[20],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Channel\"],\"name\":[21],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Views\"],\"name\":[22],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Likes\"],\"name\":[23],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Comments\"],\"name\":[24],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Description\"],\"name\":[25],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Licensed\"],\"name\":[26],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"official_video\"],\"name\":[27],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Stream\"],\"name\":[28],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"1268\",\"2\":\"Bryan Adams\",\"3\":\"https://open.spotify.com/artist/3Z02hBLubJxuFJfhacLSDc\",\"4\":\"Heaven\",\"5\":\"Reckless (30th Anniversary / Deluxe Edition)\",\"6\":\"album\",\"7\":\"spotify:track:7Ewz6bJ97vUqk5HdkvguFQ\",\"8\":\"0.382\",\"9\":\"0.589\",\"10\":\"9\",\"11\":\"-7.315\",\"12\":\"0.0267\",\"13\":\"0.04650\",\"14\":\"0.00e+00\",\"15\":\"0.1220\",\"16\":\"0.3350\",\"17\":\"140.059\",\"18\":\"243360\",\"19\":\"https://www.youtube.com/watch?v=s6TtwR2Dbjg\",\"20\":\"Bryan Adams - Heaven\",\"21\":\"BryanAdamsVEVO\",\"22\":\"307689618\",\"23\":\"1933544\",\"24\":\"49849\",\"25\":\"REMASTERED IN HD!\\\\nGet the 30th anniversary edition of ‘Reckless’ now! \\\\nSuper Deluxe (2CD+DVD+Blu-Ray Pure Audio) - http://smarturl.it/BryAdmsSprDlx\\\\nDeluxe (2CD edition) - http://smarturl.it/BryAdmsDelux\\\\niTunes - http://smarturl.it/BrnAdmDlxiTunes\\\\nRemastered CD - http://smarturl.it/BryAdmsReckless\\\\nVinyl - http://smarturl.it/BryAdmVinyl\\\\n\\\\nhttp://bryanadams.com\\\\nhttp://twitter.com/BryanAdams\\\\nhttp://facebook.com/BryanAdamsOfficial\\\\n\\\\nMusic video by Bryan Adams performing Heaven. (C) 1984 A&M Records\\\\nBest of Bryan Adams: https://goo.gl/ZevZ9f\\\\nSubscribe here: https://goo.gl/wTdSXo\\\\n\\\\n#BryanAdams #Heaven #Remastered #Vevo #Rock #OfficialMusicVideo\",\"26\":\"True\",\"27\":\"True\",\"28\":\"434521044\"},{\"1\":\"2615\",\"2\":\"Dimitri Vegas & Like Mike\",\"3\":\"https://open.spotify.com/artist/73jBynjsVtofjRpdpRAJGk\",\"4\":\"Heaven\",\"5\":\"Heaven\",\"6\":\"single\",\"7\":\"spotify:track:6p8uRRGziFLcA3QDvWxEPM\",\"8\":\"0.716\",\"9\":\"0.853\",\"10\":\"9\",\"11\":\"-3.254\",\"12\":\"0.0300\",\"13\":\"0.00812\",\"14\":\"2.68e-04\",\"15\":\"0.1540\",\"16\":\"0.5930\",\"17\":\"124.014\",\"18\":\"178294\",\"19\":\"https://www.youtube.com/watch?v=nsNCK3EJpao\",\"20\":\"Dimitri Vegas & Like Mike | Live At Tomorrowland 2022 Mainstage (FULL SET HD)\",\"21\":\"Dimitri Vegas & Like Mike\",\"22\":\"3877674\",\"23\":\"50981\",\"24\":\"1627\",\"25\":\"Check out https://www.youtube.com/tomorrowland for more Tomorrowland live-sets!\\\\n\\\\nFollow the official Tomorrowland Spotify playlist:\\\\nhttp://tomorrowland.com/spotify\\\\n \\\\n\\\\nCheck out the full tracklist here:\\\\nhttps://1001.tl/1jtc0hxt\\\\n\\\\nDuring three weekends, the intense connection between the People of Tomorrow and the special union of positive energy across all borders brought magic and a worldwide reflection of light to the Holy Grounds. Relive the madness with the mainstage performance of Dimitri Vegas & Like Mike.\\\\n\\\\nFollow Dimitri Vegas & Like Mike on Spotify:\\\\nhttp://dimitrivegasandlikemike.com/spotify\\\\n\\\\nRelive the MADNESS with these exclusive Spotify playlists:\\\\nBringing The Madness Playlist:\\\\nhttp://dimitrivegasandlikemike.com/spotifymadness\\\\nThe Official Tomorrowland Playlist:\\\\nhttp://tomorrowland.com/spotify\\\\nThe Smash The House Radio Playlist:\\\\nhttp://smashthehouse.com/spotify\\\\n\\\\nSubscribe yourself for more Tomorrowland Music on: \\\\nhttps://www.youtube.com/user/SmashTheHouse\\\\n\\\\nFollow us on social media:\\\\nhttp://www.instagram.com/dimitrivegasandlikemike\\\\nhttp://www.instagram.com/dimitrivegas\\\\nhttp://www.instagram.com/likemike\\\\nhttp://www.facebook.com/dimitrivegasandlikemike\\\\nhttp://www.twitter.com/dimitrivegas\\\\nhttp://www.twitter.com/likemike\\\\nhttps://www.tiktok.com/@dimitrivegasandlikemike\\\\nhttp://www.soundcloud.com/dimitrivegasandlikemike\",\"26\":\"False\",\"27\":\"True\",\"28\":\"15516282\"},{\"1\":\"7538\",\"2\":\"Eiffel 65\",\"3\":\"https://open.spotify.com/artist/64rxQRJsLgZwHHyWKB8fiF\",\"4\":\"Heaven\",\"5\":\"Heaven\",\"6\":\"single\",\"7\":\"spotify:track:3O0BvODj1gS7BWkxDPTNxu\",\"8\":\"0.751\",\"9\":\"0.791\",\"10\":\"0\",\"11\":\"-6.170\",\"12\":\"0.0687\",\"13\":\"0.03240\",\"14\":\"0.00e+00\",\"15\":\"0.3000\",\"16\":\"0.6840\",\"17\":\"105.063\",\"18\":\"168000\",\"19\":\"https://www.youtube.com/watch?v=DZ8PfXOV1fU\",\"20\":\"Eiffel 65 - Too Much Of Heaven (Official Video with subtitles)\",\"21\":\"Bliss Corporation\",\"22\":\"10299170\",\"23\":\"49433\",\"24\":\"3369\",\"25\":\"Are you interested in Eiffel 65 news? Subscribe to the channel: http://bit.ly/1jVW9Sz\\\\n★ Buy \\\"Too Much Of Heaven\\\" On\\\\nItunes: http://apple.co/1LVxpna\\\\nGooglePlay: http://bit.ly/1Y2eqwu\\\\n\\\\n★ Listen:\\\\nSpotify: http://spoti.fi/1OBKjKI\\\\nDeezer: http://bit.ly/1OBKxBy\\\\n\\\\nToo Much of Heaven is the title of the third single of the Italian Eurodance band Eiffel 65, extracted from the debut album \\\"Europop\\\". For several weeks at the top of the worldwide sales charts.\\\\n\\\\n★ Stay connected with Bliss Corporation★\\\\nhttp://www.blisscorporation.com\\\\nhttp://www.facebook.com/blisscorporation\\\\nhttp://www.twitter.com/blissco\\\\nhttp://www.google.com/+blisscorporation\\\\nhttp://www.youtube.com/blisscorporation\\\\n\\\\nWelcome to the Official BlissCo YouTube home page!!\",\"26\":\"True\",\"27\":\"True\",\"28\":\"2523860\"},{\"1\":\"9412\",\"2\":\"I Monster\",\"3\":\"https://open.spotify.com/artist/1CcPlAmcnJjC4FnaPVzv2v\",\"4\":\"Heaven\",\"5\":\"Neveroddoreven\",\"6\":\"album\",\"7\":\"spotify:track:7cby7HBWWcjYUNOR2yUjiW\",\"8\":\"0.410\",\"9\":\"0.656\",\"10\":\"9\",\"11\":\"-6.970\",\"12\":\"0.0316\",\"13\":\"0.52300\",\"14\":\"3.42e-04\",\"15\":\"0.1030\",\"16\":\"0.0871\",\"17\":\"79.989\",\"18\":\"237440\",\"19\":\"https://www.youtube.com/watch?v=8oaapqgy_bI\",\"20\":\"I Monster - Heaven\",\"21\":\"DharmaRecordsUK\",\"22\":\"278604\",\"23\":\"3976\",\"24\":\"135\",\"25\":\"Brand new video for Heaven, already a hit in France, by rising French director Héloïse Haddad. The song has been featured in her brand new and very beautiful short film \\\"Je t'aime déception\\\". Here's the trailer: http://www.youtube.com/watch?v=RxHOMLIG2rg\\\\n\\\\nDownload from iTunes UK: https://itunes.apple.com/gb/album/neveroddoreven/id42085885?uo=4\\\\nDownload from iTunes US: https://itunes.apple.com/us/album/neveroddoreven/id42085885?uo=4\\\\nBuy CD from Amazon: http://www.amazon.co.uk/Neveroddoreven-I-Monster/dp/B000293NI0/ref=sr_1_1?s=music&ie=UTF8&qid=1382952493&sr=1-1&keywords=i+monster+neveroddoreven\",\"26\":\"True\",\"27\":\"True\",\"28\":\"5367157\"},{\"1\":\"13877\",\"2\":\"Boyce Avenue\",\"3\":\"https://open.spotify.com/artist/7CQwac16i1W5ej8YpuL3dv\",\"4\":\"Heaven\",\"5\":\"Cover Sessions, Vol. 2\",\"6\":\"album\",\"7\":\"spotify:track:2EKxmYmUdAVXlaHCnnW13o\",\"8\":\"0.619\",\"9\":\"0.280\",\"10\":\"8\",\"11\":\"-10.238\",\"12\":\"0.0317\",\"13\":\"0.73000\",\"14\":\"0.00e+00\",\"15\":\"0.1030\",\"16\":\"0.2920\",\"17\":\"129.948\",\"18\":\"250063\",\"19\":\"https://www.youtube.com/watch?v=E0wW9RwpG7M\",\"20\":\"Heaven - Bryan Adams (Boyce Avenue feat. Megan Nicole acoustic cover) on Spotify & Apple\",\"21\":\"Boyce Avenue\",\"22\":\"183027644\",\"23\":\"1000918\",\"24\":\"22706\",\"25\":\"Tickets + VIP Meet & Greets: http://smarturl.it/BATour\\\\nSpotify: http://smarturl.it/HeavenSpotifyBA\\\\nApple: http://smarturl.it/HeavenAppleBA\\\\niTunes: http://smarturl.it/HeaveniTunesBA\\\\nGoogle: http://smarturl.it/HeavenGoogle\\\\nAmazon: http://smarturl.it/HeavenAmazonBA\\\\n\\\\n- - - - - - - - - - - -\\\\n\\\\n🔔 Subscribe & make sure to enable all push notifications! 🔔\\\\n\\\\nWatch more of our videos:\\\\nAcoustic Covers: https://www.youtube.com/watch?v=u5fETRyn9Qk&list=PL0BD69368AB943C89&index=1\\\\nOriginal Music Videos: http://youtube.com/playlist?list=PLE592C5463BB7915E&playnext=1&index=2\\\\nCover Collaborations: http://youtube.com/playlist?list=PLB0A54526DAB9CF4E&playnext=1&index=2\\\\n\\\\n- - - - - - - - - - - -\\\\n\\\\nBoyce Avenue:\\\\nAlejandro Manzano (Lead Vocals, Guitar, Piano): http://instagram.com/alejandroluismanzano \\\\nFabian Manzano (Background Vocals, Guitar): http://instagram.com/fabianmanzano\\\\nDaniel Manzano (Background Vocals, Bass, Percussion): http://instagram.com/danielmanzano\\\\n\\\\nInstagram: http://instagram.com/boyceavenue\\\\nFacebook: http://facebook.com/boyceavenue\\\\nTwitter: http://twitter.com/boyceavenue\\\\nWebsite: http://boyceavenue.com\\\\n\\\\n- - - - - - - - - - - -\\\\n\\\\nBoyce Avenue feat. Megan Nicole cover \\\"Heaven\\\" by Bryan Adams\\\\n#BoyceAvenue #MeganNicole #Heaven #BryanAdams\\\\n\\\\n- - - - - - - - - - - -\\\\n\\\\nAudio Produced by Alejandro Manzano & Daniel Manzano\\\\nArrangement by Alejandro Manzano\\\\nRecorded & Engineered by Adam Barber\\\\nMixed & Mastered by Adam Barber\\\\nAdditional Mixing & Mastering by Alejandro Manzano & Daniel Manzano\\\\nVideo Produced by Daniel Manzano & Alejandro Manzano\",\"26\":\"True\",\"27\":\"True\",\"28\":\"55580140\"},{\"1\":\"14683\",\"2\":\"Julia Michaels\",\"3\":\"https://open.spotify.com/artist/0ZED1XzwlLHW4ZaG4lOT6m\",\"4\":\"Heaven\",\"5\":\"Broad Stories\",\"6\":\"compilation\",\"7\":\"spotify:track:5M5IB1cNzJqbWFEUK4a1MD\",\"8\":\"0.554\",\"9\":\"0.371\",\"10\":\"7\",\"11\":\"-9.104\",\"12\":\"0.0361\",\"13\":\"0.85500\",\"14\":\"0.00e+00\",\"15\":\"0.0838\",\"16\":\"0.2450\",\"17\":\"199.828\",\"18\":\"191813\",\"19\":\"https://www.youtube.com/watch?v=shHTYg-rOAg\",\"20\":\"Julia Michaels - Heaven\",\"21\":\"FiftyShadesVEVO\",\"22\":\"97041975\",\"23\":\"1058614\",\"24\":\"14607\",\"25\":\"Heaven (From Fifty Shades Freed (Original Motion Picture Soundtrack) / Official Video)\\\\nSong available on the Fifty Shades Freed Original Motion Picture Soundtrack\\\\nhttps://FiftyShadesFreed.lnk.to/heavenYD   \\\\n \\\\nFifty Shades Freed, in theaters February 9.\\\\nWatch the trailer, and book tickets now: http://unvrs.al/FSFTix  \\\\n \\\\nKeep up with Julia\\\\nhttps://twitter.com/imjmichaels  \\\\nhttps://www.instagram.com/imjmichaels  \\\\nhttps://www.facebook.com/juliamichaelsofficial\\\\n \\\\nDirected by Sophie Muller\\\\nProduced by Grant Jue\\\\nFor Wondros\\\\n \\\\nMusic video by Julia Michaels performing Heaven. © 2018 Universal Studios\\\\n\\\\nhttp://vevo.ly/p9Umdw\",\"26\":\"True\",\"27\":\"True\",\"28\":\"467011916\"},{\"1\":\"17538\",\"2\":\"Kane Brown\",\"3\":\"https://open.spotify.com/artist/3oSJ7TBVCWMDMiYjXNiCKE\",\"4\":\"Heaven\",\"5\":\"Kane Brown (Deluxe Edition)\",\"6\":\"album\",\"7\":\"spotify:track:1HXy5I3HTWq8OvxCn0z7G7\",\"8\":\"0.677\",\"9\":\"0.556\",\"10\":\"9\",\"11\":\"-6.544\",\"12\":\"0.0306\",\"13\":\"0.26300\",\"14\":\"0.00e+00\",\"15\":\"0.1050\",\"16\":\"0.5210\",\"17\":\"80.006\",\"18\":\"179507\",\"19\":\"https://www.youtube.com/watch?v=dRX0wDNK6S4\",\"20\":\"Kane Brown - Heaven\",\"21\":\"KaneBrownVEVO\",\"22\":\"520364745\",\"23\":\"2278175\",\"24\":\"52671\",\"25\":\"Get \\\"Heaven\\\" now on the Kane Brown Deluxe Edition: http://smarturl.it/kanebrowndeluxe\\\\nDirector: Alex Alvga\",\"26\":\"True\",\"27\":\"True\",\"28\":\"413970634\"},{\"1\":\"18767\",\"2\":\"Calum Scott\",\"3\":\"https://open.spotify.com/artist/6ydoSd3N2mwgwBHtF6K7eX\",\"4\":\"Heaven\",\"5\":\"Bridges\",\"6\":\"album\",\"7\":\"spotify:track:0Y1RDty5uEqseA1C4kqa4x\",\"8\":\"0.566\",\"9\":\"0.353\",\"10\":\"2\",\"11\":\"-7.624\",\"12\":\"0.0330\",\"13\":\"0.52000\",\"14\":\"0.00e+00\",\"15\":\"0.1100\",\"16\":\"0.3940\",\"17\":\"127.531\",\"18\":\"194141\",\"19\":\"https://www.youtube.com/watch?v=ddShTTQKao0\",\"20\":\"Calum Scott - Heaven (Official Video)\",\"21\":\"CalumScottVEVO\",\"22\":\"6704181\",\"23\":\"163180\",\"24\":\"3378\",\"25\":\"Watch the official video for Calum Scott's \\\"Heaven.\\\"\\\\n\\\\nStream // Download Calum Scott's new album, \\\"Bridges,\\\" now: https://CalumScott.lnk.to/BridgesID\\\\n\\\\nConnect with Calum Scott -\\\\nOfficial Mailing List: http://calumscott.lnk.to/mailinglistID\\\\nFacebook: https://CalumScott.lnk.to/facebookID\\\\nTwitter: https://CalumScott.lnk.to/twitterID\\\\nInstagram: https://CalumScott.lnk.to/instagramID\\\\nTikTok: https://CalumScott.lnk.to/tiktokID\\\\nSpotify: https://CalumScott.lnk.to/spotifyID\\\\nApple Music: https://CalumScott.lnk.to/applemusicID\\\\nSoundcloud: http://calumscott.lnk.to/soundcloudID\\\\nDeezer: https://CalumScott.lnk.to/deezerID\\\\nWebsite: http://www.calumscott.com\\\\n\\\\nHeaven Lyrics -\\\\n\\\\nI used to count the stars in the sky,\\\\nNow I count the ones in your eyes,\\\\nI used to think that my paradise,\\\\nWas somewhere waiting on the other side\\\\n\\\\nBut you,\\\\nTake me higher than I’ve been, \\\\nLaying hands on my skin,\\\\nIt’s true,\\\\nNothing compares to you\\\\n\\\\nSo tell me why,\\\\nWhat good is life,\\\\nIf we’re all just waiting to dance in the sky,\\\\nI’m already there,\\\\nHere in your eyes,\\\\nWe climb the gates every time that you lie down next to me,\\\\nI rest in peace,\\\\nThey say it’s better, but how could that be\\\\nIf everyone had a love like us,\\\\nThey wouldn’t call that place above, \\\\nHeaven\\\\n\\\\nWaking up to you feels like a pinch myself moment,\\\\nIf we’re only here for a while,\\\\nI wanna spend, all of it holding you,\\\\nTake me higher than I’ve been,\\\\nGot me questioning everything I knew,\\\\nCause nothing compares to you\\\\n\\\\nSo tell me why,\\\\nWhat good is life,\\\\nIf we’re all just waiting to dance in the sky,\\\\nI’m already there,\\\\nHere in your eyes,\\\\nWe climb the gates every time that you lie down next to me\\\\nI rest in peace,\\\\nThey say it’s better, but how could that be\\\\nIf everyone had a love like us,\\\\nThey wouldn’t call that place above, \\\\nHeaven\\\\n\\\\nNothing comes, \\\\nNothing comes, close to this, \\\\nLooking up,\\\\nLooking up, even if it exists,\\\\nMy heaven is on your lips\\\\n \\\\nSo tell me why,\\\\nWhat good is life,\\\\nIf we’re all just waiting to dance in the sky,\\\\nI’m already there,\\\\nHere in your eyes,\\\\nWe climb the gates every time that you lie down next to me,\\\\nI rest in peace,\\\\nThey say it’s better, but how could that be\\\\nIf everyone had a love like us\\\\nThey wouldn't call that place above\\\\nHeaven\\\\n\\\\n#CalumScott #Heaven #Bridges\\\\n\\\\nMusic video by Calum Scott performing Heaven. Capitol Records; © 2022 UMG Recordings, Inc.\\\\n\\\\nhttp://vevo.ly/32tmIb\",\"26\":\"True\",\"27\":\"True\",\"28\":\"19199245\"},{\"1\":\"19082\",\"2\":\"James Carter\",\"3\":\"https://open.spotify.com/artist/5344K3N7rx7kw1HjO8psuq\",\"4\":\"Heaven\",\"5\":\"Heaven\",\"6\":\"single\",\"7\":\"spotify:track:5gvEyl4OLhD6kJ3aZ43sd3\",\"8\":\"0.737\",\"9\":\"0.849\",\"10\":\"11\",\"11\":\"-6.071\",\"12\":\"0.0350\",\"13\":\"0.02010\",\"14\":\"7.21e-05\",\"15\":\"0.1320\",\"16\":\"0.6750\",\"17\":\"115.993\",\"18\":\"124655\",\"19\":\"https://www.youtube.com/watch?v=9a08VYjgFHY\",\"20\":\"James Carter - Heaven\",\"21\":\"James Carter\",\"22\":\"79942\",\"23\":\"1012\",\"24\":\"34\",\"25\":\"🔥 Listen on Spotify: https://jc.lnk.to/heaven\\\\n✅ Subscribe: https://jc.lnk.to/sub​\\\\n🔔 Turn on notifications to never miss a new upload!\\\\n\\\\nThe Official Audio for James Carter - Heaven\\\\n\\\\nFollow James Carter\\\\n➥ Spotify: https://jc.lnk.to/spotify​\\\\n➥ SoundCloud: https://soundcloud.com/jamescarteruk​\\\\n➥ Facebook: https://jc.lnk.to/facebook​\\\\n➥ Twitter: https://jc.lnk.to/twitter​\\\\n➥ Instagram: https://jc.lnk.to/instagram​\\\\n\\\\n#jamescarter​ #heaven #selected\",\"26\":\"False\",\"27\":\"True\",\"28\":\"22303596\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nAbove is a quick sanity check to see if any repeated track values are the same song scrapped twice, or different songs with the same title. My check showed the repeat tracks all have very different song statistic values. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n#|label: summary statistics on the dataset\nspotify_yt_data %>%\n  summarytools::dfSummary(varnumbers = FALSE,\n                        plain.ascii  = FALSE, \n                        style        = \"grid\", \n                        graph.magnif = 0.50, \n                        valid.col    = FALSE)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Variable\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Stats / Values\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Freqs (% of Valid)\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Graph\"],\"name\":[4],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"text.graph\"],\"name\":[5],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Missing\"],\"name\":[6],\"type\":[\"chr\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"Track\\\\\\\\\\\\n[character]\",\"2\":\"1\\\\\\\\. Heaven\\\\\\\\\\\\n2\\\\\\\\. Angel\\\\\\\\\\\\n3\\\\\\\\. Home\\\\\\\\\\\\n4\\\\\\\\. Candy\\\\\\\\\\\\n5\\\\\\\\. Forever\\\\\\\\\\\\n6\\\\\\\\. Again\\\\\\\\\\\\n7\\\\\\\\. Alone\\\\\\\\\\\\n8\\\\\\\\. Body\\\\\\\\\\\\n9\\\\\\\\. Contigo\\\\\\\\\\\\n10\\\\\\\\. Crazy\\\\\\\\\\\\n[ 16979 others ]\",\"3\":\"\\\\\\\\    9 ( 0.1%)\\\\\\\\\\\\n\\\\\\\\    7 ( 0.0%)\\\\\\\\\\\\n\\\\\\\\    7 ( 0.0%)\\\\\\\\\\\\n\\\\\\\\    6 ( 0.0%)\\\\\\\\\\\\n\\\\\\\\    6 ( 0.0%)\\\\\\\\\\\\n\\\\\\\\    5 ( 0.0%)\\\\\\\\\\\\n\\\\\\\\    5 ( 0.0%)\\\\\\\\\\\\n\\\\\\\\    5 ( 0.0%)\\\\\\\\\\\\n\\\\\\\\    5 ( 0.0%)\\\\\\\\\\\\n\\\\\\\\    5 ( 0.0%)\\\\\\\\\\\\n\\\\\\\\17900 (99.7%)\",\"4\":\"<img style=\\\"border:none;background-color:transparent;padding:0;max-width:max-content;\\\" src=\\\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFcAAACIBAMAAABgjmqlAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5wUKExIZYjcrtAAAAG9JREFUWMPt0b0JgFAAA2FH0A38GcH9d7MR61Mh5MGl/oqDTNOY2xawWdyLiW1rFmcwsW3N4gwmtq1ZnMHEtjWLM5jYtmbxZ0xsW7M4g4ltaxZnMLFtzeIMJratWZzBxD54J1tvfJxg4t/41Smj7QLBOnWqVlnDkAAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMy0wNS0xMFQxOToxODoyNSswMDowMFQW0TsAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjMtMDUtMTBUMTk6MTg6MjUrMDA6MDAlS2mHAAAAAElFTkSuQmCC\\\">\",\"5\":\"\\\\\\\\ \\\\n \\\\\\\\ \\\\n \\\\\\\\ \\\\n \\\\\\\\ \\\\n \\\\\\\\ \\\\n \\\\\\\\ \\\\n \\\\\\\\ \\\\n \\\\\\\\ \\\\n \\\\\\\\ \\\\n \\\\\\\\ \\\\nIIIIIIIIIIIIIIIIIII\",\"6\":\"0\\\\\\\\\\\\n(0.0%)\",\"_rn_\":\"1\"},{\"1\":\"Album_type\\\\\\\\\\\\n[character]\",\"2\":\"1\\\\\\\\. album\\\\\\\\\\\\n2\\\\\\\\. compilation\\\\\\\\\\\\n3\\\\\\\\. single\",\"3\":\"\\\\\\\\13366 (74.4%)\\\\\\\\\\\\n\\\\\\\\  628 ( 3.5%)\\\\\\\\\\\\n\\\\\\\\ 3966 (22.1%)\",\"4\":\"<img style=\\\"border:none;background-color:transparent;padding:0;max-width:max-content;\\\" src=\\\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAEQAAAAqBAMAAAD4w+CrAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5wUKExIZYjcrtAAAAEBJREFUOMtjYBhcQAkPgCpRNsYJjEaV4FVCROgK4gEwUxQJKlEeVUJu0AkKEjYFChRxK4ElhlElJCshInQHCwAAYwFv4omNN3AAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjMtMDUtMTBUMTk6MTg6MjUrMDA6MDBUFtE7AAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIzLTA1LTEwVDE5OjE4OjI1KzAwOjAwJUtphwAAAABJRU5ErkJggg==\\\">\",\"5\":\"IIIIIIIIIIIIII \\\\\\\\ \\\\n \\\\\\\\ \\\\nIIII\",\"6\":\"0\\\\\\\\\\\\n(0.0%)\",\"_rn_\":\"2\"},{\"1\":\"Danceability\\\\\\\\\\\\n[numeric]\",\"2\":\"Mean (sd) : 0.6 (0.2)\\\\\\\\\\\\nmin < med < max:\\\\\\\\\\\\n0 < 0.6 < 1\\\\\\\\\\\\nIQR (CV) : 0.2 (0.3)\",\"3\":\"896 distinct values\",\"4\":\"<img style=\\\"border:none;background-color:transparent;padding:0;max-width:max-content;\\\" src=\\\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFEAAAA7BAMAAADxzns5AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5wUKExIZYjcrtAAAAJ9JREFUSMft1V0OhCAMBGCPoJ7AHW7A3P9uy8+i6FZoNiRK1j6R9HuB0Okw9FOTWMBrPY9FaXidnGEIqCQNjW0pZ0AraW8g0zvVJW0z6d5IKT15ZFm6777JOKBnkpnkP8kwljrpUYcyRLMk47BlMsSoJGP37hLQytT9UbpoPEq/WQTpAvdLsrVMm6Uqs3QtSmDXPZXbpWWJ5SNRrSR7qDcP2MjpURFqIQAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMy0wNS0xMFQxOToxODoyNSswMDowMFQW0TsAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjMtMDUtMTBUMTk6MTg6MjUrMDA6MDAlS2mHAAAAAElFTkSuQmCC\\\">\",\"5\":\"\\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ : :\\\\\\\\\\\\n\\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ : : :\\\\\\\\\\\\n\\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ . : : : :\\\\\\\\\\\\n\\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ . : : : : :\\\\\\\\\\\\n\\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ . : : : : : : :\",\"6\":\"1\\\\\\\\\\\\n(0.0%)\",\"_rn_\":\"3\"},{\"1\":\"Energy\\\\\\\\\\\\n[numeric]\",\"2\":\"Mean (sd) : 0.6 (0.2)\\\\\\\\\\\\nmin < med < max:\\\\\\\\\\\\n0 < 0.7 < 1\\\\\\\\\\\\nIQR (CV) : 0.3 (0.3)\",\"3\":\"1255 distinct values\",\"4\":\"<img style=\\\"border:none;background-color:transparent;padding:0;max-width:max-content;\\\" src=\\\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFEAAAA7BAMAAADxzns5AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5wUKExIZYjcrtAAAAJ1JREFUSMfd1d0NwyAMBOCMkGaC9NiA23+3GghSfmq4h0oN8ROSPwkkDjNN49TLKaCu5qYEQtRk4LPkgiQBvLuSSTLyvzKf1JcLUGVgW2byU2l7i3IjN5cWDlXyKO3hidJiOrTMgdNk6j5JlrgrsnT7EvgqsV5k7Z4k7yXLdJUkNbmfb54sv95+annSLsFGPySJcOz6kkNIdKvKEeoDslPcgrWNC14AAAAldEVYdGRhdGU6Y3JlYXRlADIwMjMtMDUtMTBUMTk6MTg6MjUrMDA6MDBUFtE7AAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIzLTA1LTEwVDE5OjE4OjI1KzAwOjAwJUtphwAAAABJRU5ErkJggg==\\\">\",\"5\":\"\\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ : : .\\\\\\\\\\\\n\\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ : : : :\\\\\\\\\\\\n\\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ : : : : : .\\\\\\\\\\\\n\\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ . : : : : : :\\\\\\\\\\\\n. . : : : : : : : :\",\"6\":\"1\\\\\\\\\\\\n(0.0%)\",\"_rn_\":\"4\"},{\"1\":\"Key\\\\\\\\\\\\n[numeric]\",\"2\":\"Mean (sd) : 5.3 (3.6)\\\\\\\\\\\\nmin < med < max:\\\\\\\\\\\\n0 < 5 < 11\\\\\\\\\\\\nIQR (CV) : 6 (0.7)\",\"3\":\"12 distinct values\",\"4\":\"<img style=\\\"border:none;background-color:transparent;padding:0;max-width:max-content;\\\" src=\\\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFEAAAA7BAMAAADxzns5AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5wUKExIZYjcrtAAAAHlJREFUSMft0mEKgCAMBWCPUDtBrRv47n+3zGWmiA7CoPDhz2/TMY35TpjnRqZTbvaJTO+JktdcptVRoouk7AEViZIM9QqJP0jZo0aKuUviRSvxjiQ3ziXdKisS9jDiCW0pR6TvrJMYcsh+0v9EncSQQxYlNxPkF7IDfQfSMmFpEs4AAAAldEVYdGRhdGU6Y3JlYXRlADIwMjMtMDUtMTBUMTk6MTg6MjUrMDA6MDBUFtE7AAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIzLTA1LTEwVDE5OjE4OjI1KzAwOjAwJUtphwAAAABJRU5ErkJggg==\\\">\",\"5\":\":\\\\\\\\\\\\n: \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ .\\\\\\\\\\\\n: . \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ . \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ :\\\\\\\\\\\\n: : \\\\\\\\ \\\\\\\\ . : . : . : :\\\\\\\\\\\\n: : . : : : : : : :\",\"6\":\"1\\\\\\\\\\\\n(0.0%)\",\"_rn_\":\"5\"},{\"1\":\"Loudness\\\\\\\\\\\\n[numeric]\",\"2\":\"Mean (sd) : -7.7 (4.6)\\\\\\\\\\\\nmin < med < max:\\\\\\\\\\\\n-46.3 < -6.6 < 0.9\\\\\\\\\\\\nIQR (CV) : 3.9 (-0.6)\",\"3\":\"9143 distinct values\",\"4\":\"<img style=\\\"border:none;background-color:transparent;padding:0;max-width:max-content;\\\" src=\\\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFEAAAA7BAMAAADxzns5AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5wUKExIZYjcrtAAAAFZJREFUSMdjYBg6QBAXUFJSUgQzBAipVDY2HlU5qnJU5ahKSlRCChxiVEKMHVU5xFUKAWOcSJXGYGWjKnGrBAUmkSqNjY0IqQSZBjYQq0olgkCBYegAABAQmaazg1V5AAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIzLTA1LTEwVDE5OjE4OjI1KzAwOjAwVBbROwAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMy0wNS0xMFQxOToxODoyNSswMDowMCVLaYcAAAAASUVORK5CYII=\\\">\",\"5\":\"\\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ :\\\\\\\\\\\\n\\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ :\\\\\\\\\\\\n\\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ :\\\\\\\\\\\\n\\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ . :\\\\\\\\\\\\n\\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ . : : :\",\"6\":\"1\\\\\\\\\\\\n(0.0%)\",\"_rn_\":\"6\"},{\"1\":\"Speechiness\\\\\\\\\\\\n[numeric]\",\"2\":\"Mean (sd) : 0.1 (0.1)\\\\\\\\\\\\nmin < med < max:\\\\\\\\\\\\n0 < 0 < 1\\\\\\\\\\\\nIQR (CV) : 0.1 (1.1)\",\"3\":\"1264 distinct values\",\"4\":\"<img style=\\\"border:none;background-color:transparent;padding:0;max-width:max-content;\\\" src=\\\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFEAAAA7BAMAAADxzns5AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5wUKExIZYjcrtAAAAFpJREFUSMdjYBg6QElJkAAQgKpUNhpVOapyVOWoSkyVSorEqjQeVTmqkv4qlfCnUCSVysa0UIm3mkVRCcxMSsSqNMad8TBU4gwCTJUg52JzBEylEkGgwDB0AAD2JotTi/9vogAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMy0wNS0xMFQxOToxODoyNSswMDowMFQW0TsAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjMtMDUtMTBUMTk6MTg6MjUrMDA6MDAlS2mHAAAAAElFTkSuQmCC\\\">\",\"5\":\":\\\\\\\\\\\\n:\\\\\\\\\\\\n:\\\\\\\\\\\\n:\\\\\\\\\\\\n: : . .\",\"6\":\"1\\\\\\\\\\\\n(0.0%)\",\"_rn_\":\"7\"},{\"1\":\"Acousticness\\\\\\\\\\\\n[numeric]\",\"2\":\"Mean (sd) : 0.3 (0.3)\\\\\\\\\\\\nmin < med < max:\\\\\\\\\\\\n0 < 0.2 < 1\\\\\\\\\\\\nIQR (CV) : 0.4 (1)\",\"3\":\"3099 distinct values\",\"4\":\"<img style=\\\"border:none;background-color:transparent;padding:0;max-width:max-content;\\\" src=\\\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFEAAAA7BAMAAADxzns5AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5wUKExIZYjcrtAAAAHRJREFUSMft1csRgCAMBFBKECvQpQPSf2/+woh8AuMNzR7g8iaT5YIx4wSwjUwsnVepUqXKP0isvZK+JyG3j6Qj8QN5SPH5EylMTST5flmtlcm9VnmFXF7r5qPLkkdHfMZSkzeHPQ6SJZc8rx5JLyWaCXKEbGuWmq9rl/MkAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIzLTA1LTEwVDE5OjE4OjI1KzAwOjAwVBbROwAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMy0wNS0xMFQxOToxODoyNSswMDowMCVLaYcAAAAASUVORK5CYII=\\\">\",\"5\":\":\\\\\\\\\\\\n:\\\\\\\\\\\\n:\\\\\\\\\\\\n: : .\\\\\\\\\\\\n: : : : : . . . . .\",\"6\":\"1\\\\\\\\\\\\n(0.0%)\",\"_rn_\":\"8\"},{\"1\":\"Instrumentalness\\\\\\\\\\\\n[numeric]\",\"2\":\"Mean (sd) : 0.1 (0.2)\\\\\\\\\\\\nmin < med < max:\\\\\\\\\\\\n0 < 0 < 1\\\\\\\\\\\\nIQR (CV) : 0 (3.4)\",\"3\":\"3928 distinct values\",\"4\":\"<img style=\\\"border:none;background-color:transparent;padding:0;max-width:max-content;\\\" src=\\\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFEAAAA7BAMAAADxzns5AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5wUKExIZYjcrtAAAADdJREFUSMdjYBg6QElJkAAQgKpUNhpVOapyVOWoylGVoypHVQ4/lUqKeJQBGwowlUoEgQLD0AEA72iC0axeEekAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjMtMDUtMTBUMTk6MTg6MjUrMDA6MDBUFtE7AAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIzLTA1LTEwVDE5OjE4OjI1KzAwOjAwJUtphwAAAABJRU5ErkJggg==\\\">\",\"5\":\":\\\\\\\\\\\\n:\\\\\\\\\\\\n:\\\\\\\\\\\\n:\\\\\\\\\\\\n:\",\"6\":\"1\\\\\\\\\\\\n(0.0%)\",\"_rn_\":\"9\"},{\"1\":\"Liveness\\\\\\\\\\\\n[numeric]\",\"2\":\"Mean (sd) : 0.2 (0.2)\\\\\\\\\\\\nmin < med < max:\\\\\\\\\\\\n0 < 0.1 < 1\\\\\\\\\\\\nIQR (CV) : 0.1 (0.9)\",\"3\":\"1519 distinct values\",\"4\":\"<img style=\\\"border:none;background-color:transparent;padding:0;max-width:max-content;\\\" src=\\\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFEAAAA7BAMAAADxzns5AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5wUKExIZYjcrtAAAAHFJREFUSMft1cENgCAMBVBGsE4gnw3o/rvZmABGi/ZilNh/4PQS4PfQEMYJEQGRLjI1mfg9OcMs2aVLly6/JwGrTPnPUnrqraWD5NxdDCfJz0h9qJrUKygSsMqU91K7X5dSVrRK+VYNbedS33mXIkfICptKmBFHb1eTAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIzLTA1LTEwVDE5OjE4OjI1KzAwOjAwVBbROwAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMy0wNS0xMFQxOToxODoyNSswMDowMCVLaYcAAAAASUVORK5CYII=\\\">\",\"5\":\":\\\\\\\\\\\\n: .\\\\\\\\\\\\n: :\\\\\\\\\\\\n: : .\\\\\\\\\\\\n: : : : .\",\"6\":\"1\\\\\\\\\\\\n(0.0%)\",\"_rn_\":\"10\"},{\"1\":\"Valence\\\\\\\\\\\\n[numeric]\",\"2\":\"Mean (sd) : 0.5 (0.2)\\\\\\\\\\\\nmin < med < max:\\\\\\\\\\\\n0 < 0.5 < 1\\\\\\\\\\\\nIQR (CV) : 0.4 (0.5)\",\"3\":\"1284 distinct values\",\"4\":\"<img style=\\\"border:none;background-color:transparent;padding:0;max-width:max-content;\\\" src=\\\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFEAAAA7BAMAAADxzns5AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5wUKExIZYjcrtAAAAJpJREFUSMft010OhCAMBGCPoJxgnd6gc/+7bdHd8CfCm2KcJwJfSJO20zROljxAdjEfSwdRs8B6Ko04ilIX4bkU/Ul0SwpDuS25lVuRQCqt3Irc/+mVHt1bWhsLube0kCwlbyedb06PNKdHchvoRMavyZnXShvnTmnDPYjEJ0i/lHXJSAqvk2GBmpIPk9GqNaToK58j0cxfjpAv3BcLHpfUNqUAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjMtMDUtMTBUMTk6MTg6MjUrMDA6MDBUFtE7AAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIzLTA1LTEwVDE5OjE4OjI1KzAwOjAwJUtphwAAAABJRU5ErkJggg==\\\">\",\"5\":\"\\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ . . : : .\\\\\\\\\\\\n\\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ . : : : : : .\\\\\\\\\\\\n\\\\\\\\ \\\\\\\\ . : : : : : : : :\\\\\\\\\\\\n. : : : : : : : : :\\\\\\\\\\\\n: : : : : : : : : :\",\"6\":\"1\\\\\\\\\\\\n(0.0%)\",\"_rn_\":\"11\"},{\"1\":\"Tempo\\\\\\\\\\\\n[numeric]\",\"2\":\"Mean (sd) : 120.8 (29.6)\\\\\\\\\\\\nmin < med < max:\\\\\\\\\\\\n0 < 120 < 243.4\\\\\\\\\\\\nIQR (CV) : 43 (0.2)\",\"3\":\"14389 distinct values\",\"4\":\"<img style=\\\"border:none;background-color:transparent;padding:0;max-width:max-content;\\\" src=\\\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFEAAAA7BAMAAADxzns5AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5wUKExIZYjcrtAAAAGxJREFUSMdjYBg6QBAVCCkpKaEJCeBQaWxsNMhVAj2jSKRKY2Ogx4lUqWxsNKpyVOWwUQnKJcSpNDYeVUmMSpRCFK9KZeSIGlQqhcAFIlEqYSpGVdJGJSI5EVKJyPdUVQktIWAqlQgCBYahAwBiSbphKs1gAgAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMy0wNS0xMFQxOToxODoyNSswMDowMFQW0TsAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjMtMDUtMTBUMTk6MTg6MjUrMDA6MDAlS2mHAAAAAElFTkSuQmCC\\\">\",\"5\":\"\\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ : :\\\\\\\\\\\\n\\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ : : :\\\\\\\\\\\\n\\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ : : :\\\\\\\\\\\\n\\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ : : : :\\\\\\\\\\\\n\\\\\\\\ \\\\\\\\ \\\\\\\\ \\\\\\\\ . : : : : :\",\"6\":\"1\\\\\\\\\\\\n(0.0%)\",\"_rn_\":\"12\"},{\"1\":\"Duration_ms\\\\\\\\\\\\n[numeric]\",\"2\":\"Mean (sd) : 222126.9 (91197.7)\\\\\\\\\\\\nmin < med < max:\\\\\\\\\\\\n30985 < 213237 < 4676058\\\\\\\\\\\\nIQR (CV) : 70950 (0.4)\",\"3\":\"14097 distinct values\",\"4\":\"<img style=\\\"border:none;background-color:transparent;padding:0;max-width:max-content;\\\" src=\\\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFEAAAA7BAMAAADxzns5AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5wUKExIa+z56DgAAADFJREFUSMdjYBg6QElJSVEQLxCAqlQ2Nh5VOapyVOWoylGVoypHVY5YlUoEgQLD0AEArSOMcp3cqxcAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjMtMDUtMTBUMTk6MTg6MjYrMDA6MDBl/sumAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIzLTA1LTEwVDE5OjE4OjI2KzAwOjAwFKNzGgAAAABJRU5ErkJggg==\\\">\",\"5\":\":\\\\\\\\\\\\n:\\\\\\\\\\\\n:\\\\\\\\\\\\n:\\\\\\\\\\\\n:\",\"6\":\"1\\\\\\\\\\\\n(0.0%)\",\"_rn_\":\"13\"},{\"1\":\"Views\\\\\\\\\\\\n[numeric]\",\"2\":\"Mean (sd) : 90902081 (263896196)\\\\\\\\\\\\nmin < med < max:\\\\\\\\\\\\n26 < 14158464 < 8079649362\\\\\\\\\\\\nIQR (CV) : 66505747 (2.9)\",\"3\":\"17418 distinct values\",\"4\":\"<img style=\\\"border:none;background-color:transparent;padding:0;max-width:max-content;\\\" src=\\\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFEAAAA7BAMAAADxzns5AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5wUKExIa+z56DgAAADRJREFUSMdjYBg6QElJURA/EICqVDYeVTmqclTlqMpRlaMqR1UOP5WE2gIwlUoEgQLD0AEAVRKGAb6RaUsAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjMtMDUtMTBUMTk6MTg6MjYrMDA6MDBl/sumAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIzLTA1LTEwVDE5OjE4OjI2KzAwOjAwFKNzGgAAAABJRU5ErkJggg==\\\">\",\"5\":\":\\\\\\\\\\\\n:\\\\\\\\\\\\n:\\\\\\\\\\\\n:\\\\\\\\\\\\n:\",\"6\":\"0\\\\\\\\\\\\n(0.0%)\",\"_rn_\":\"14\"},{\"1\":\"official_video\\\\\\\\\\\\n[character]\",\"2\":\"1\\\\\\\\. False\\\\\\\\\\\\n2\\\\\\\\. True\",\"3\":\"\\\\\\\\ 3995 (22.2%)\\\\\\\\\\\\n\\\\\\\\13965 (77.8%)\",\"4\":\"<img style=\\\"border:none;background-color:transparent;padding:0;max-width:max-content;\\\" src=\\\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAEcAAAAfBAMAAABHQ822AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5wUKExIa+z56DgAAADVJREFUOMtjYBicQAkKFAWxAAGoImVjCBhVRAVFRIW4ID6AbhJWoIDmJqxgVBFpiogK8cEGAGtoXyDcmxPDAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIzLTA1LTEwVDE5OjE4OjI2KzAwOjAwZf7LpgAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMy0wNS0xMFQxOToxODoyNiswMDowMBSjcxoAAAAASUVORK5CYII=\\\">\",\"5\":\"IIII \\\\\\\\ \\\\nIIIIIIIIIIIIIII\",\"6\":\"0\\\\\\\\\\\\n(0.0%)\",\"_rn_\":\"15\"},{\"1\":\"Stream\\\\\\\\\\\\n[numeric]\",\"2\":\"Mean (sd) : 132462246 (238103725)\\\\\\\\\\\\nmin < med < max:\\\\\\\\\\\\n6574 < 48746287 < 3386520288\\\\\\\\\\\\nIQR (CV) : 118002305 (1.8)\",\"3\":\"17942 distinct values\",\"4\":\"<img style=\\\"border:none;background-color:transparent;padding:0;max-width:max-content;\\\" src=\\\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFEAAAA7BAMAAADxzns5AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5wUKExIa+z56DgAAAEFJREFUSMdjYBg6QElJURA/EICqVDYeVTmqclTlqMpRlaMqR1USqjkRKgmZSmuV+F2KrBKkFrdqmEolgkCBYegAAFWth58ip5gnAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIzLTA1LTEwVDE5OjE4OjI2KzAwOjAwZf7LpgAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMy0wNS0xMFQxOToxODoyNiswMDowMBSjcxoAAAAASUVORK5CYII=\\\">\",\"5\":\":\\\\\\\\\\\\n:\\\\\\\\\\\\n:\\\\\\\\\\\\n:\\\\\\\\\\\\n: .\",\"6\":\"0\\\\\\\\\\\\n(0.0%)\",\"_rn_\":\"16\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\nMost of the songs in the are from albums, but about 1/4 of them are singles. All of the music related analytics range from 0.0 to 1.0 with the exception of key, which has 12 total values. For the number of streams per song, the data is skewed by some high outliers, with the median of the data at around 50 million streams, but the mean is 137 million. Similarly the Youtube views have a median much lower than the mean, with a median of 14.7 million but a mean of 95 million.\n\n## 3. Visualization {#visualization}\n\nThe plan for data analyses and visualization is to compare how the different song attributes (Dancability, Energy, etc) correlate to higher or lower Youtube Views and Spotify streams by constructing a series of scatter plots for the attributes and color coding YouTube views to Spotify streams. Also a color coded Scatter plot with be used to compare Spotify streams and Youtube Views for Singles and Albums to see if there are any trends that make singles more likely to make popular videos.  \n\nThese specific analyses will help to show the correlation between the different variables the popularity metrics we have recorded in order to show any trends in what makes certain music videos for songs more popular than others.For example, if we can see that certain values for a given measure have very high stream numbers, but disproportionately low view numbers, then we can see a distinct pattern in the data. There is no timed data here, so there are no questions we can answer about changes in time.\n\nIn order to do all the bivariate analyses, we will need to tidy the data. The first step of this is to remove duplicate tracks, or the same track that has been added to the dataset twice by the API. To do this we can group the data by track name, and if the songs have the same values for the Spotify metrics, they are the same song and we can just take the most streamed version, or in the case they all have the same stream count, the observation with the most viewed Youtube video will be kept. Then the data will be pivoted longer to have Youtube Views and Spotify Streams on separate observations, doubling the number of rows, and maintaining the number of columns. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n#|label : Graph trends in engagement \nmeasures <- spotify_yt_data %>%\n      select(Danceability : Duration_ms) %>%\n      colnames()\n\nspotify_yt_long <- spotify_yt_data %>%\n      rename(\"Spotify\" = Stream, \"YouTube\"= Views) %>%\n      pivot_longer(c(Spotify, YouTube), names_to = \"Platform\", values_to = \"Count\")\n\nspotify_yt_long %>%\n      pivot_longer(measures, names_to = \"Measure\", values_to = \"Value\") %>%\n      ggplot(aes(y= Count, x= Value, shape = Platform)) + \n      scale_y_continuous(trans='log10') +\n      geom_point(alpha = 0.5, size = 0.5)+\n      geom_smooth(aes(color = Platform))+\n      theme_bw() +\n      facet_wrap(~Measure, scale = \"free\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Using an external vector in selections was deprecated in tidyselect 1.1.0.\nℹ Please use `all_of()` or `any_of()` instead.\n  # Was:\n  data %>% select(measures)\n\n  # Now:\n  data %>% select(all_of(measures))\n\nSee <https://tidyselect.r-lib.org/reference/faq-external-vector.html>.\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using method = 'gam' and formula = 'y ~ s(x, bs = \"cs\")'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 22 rows containing non-finite values (`stat_smooth()`).\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 22 rows containing missing values (`geom_point()`).\n```\n:::\n\n::: {.cell-output-display}\n![](DanielHannon_FinalProjectAssignment1_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\nAbove is the first set of analyses which looks at the difference between Spotify streams and YouTube views to see if there are elements of the song that lend it to having a higher view count or stream count. There are some high outliers, so to account for that the y-axis has been scaled to log space. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n#|label :  Graph difference in platform\nspotify_yt_data %>%\n  mutate(Difference = Views- Stream) %>%\n  pivot_longer(measures, names_to = \"Measure\", values_to = \"Value\") %>%\n  ggplot(aes(y= Difference, x= Value)) + \n  geom_point(alpha = 0.5, size = 0.5)+\n  scale_y_continuous(trans= \"log10\")+\n  geom_smooth()+\n  theme_bw() +\n  facet_wrap(~Measure, scale = \"free\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in self$trans$transform(x): NaNs produced\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Transformation introduced infinite values in continuous y-axis\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in self$trans$transform(x): NaNs produced\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Transformation introduced infinite values in continuous y-axis\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using method = 'gam' and formula = 'y ~ s(x, bs = \"cs\")'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 154451 rows containing non-finite values (`stat_smooth()`).\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 154451 rows containing missing values (`geom_point()`).\n```\n:::\n\n::: {.cell-output-display}\n![](DanielHannon_FinalProjectAssignment1_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\nThese similar looking graphs take each track and compute the difference between views and streams, and then checks over the same song elements to see if any of them show a trend.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspotify_yt_long %>%\n  group_by(Album_type, Platform) %>%\n  mutate(Mean = mean(Count), Median = median(Count), IQR = IQR(Count)) %>%\n  pivot_longer(c(Mean, Median, IQR), names_to = \"Measure\", values_to = \"Average\") %>%\n  select(Album_type, Measure, Average, Platform) %>%\n  ggplot(aes(x=Album_type, y= Average, fill= Platform))+\n    geom_bar(position= \"dodge\", stat= \"identity\")+\n    facet_wrap(~Measure, scale = \"fixed\") +\n    theme_bw()\n```\n\n::: {.cell-output-display}\n![](DanielHannon_FinalProjectAssignment1_files/figure-html/Graph engagements by album type-1.png){width=672}\n:::\n:::\n\nHere we have some graphs that show what type of album the track appeared on, and if that effected the number of Views or Streams a certain track received. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nspotify_yt_data %>%\n  mutate(Difference = Views - Stream) %>%\n  group_by(Album_type) %>%\n  mutate(Mean = mean(Difference), Median = median(Difference)) %>%\n  pivot_longer(c(Mean, Median), names_to = \"Measure\", values_to = \"Average\") %>%\n  select(Album_type, Measure, Average) %>%\n  ggplot(aes(x=Album_type, y= Average))+\n    geom_bar(position= \"dodge\", stat= \"identity\")+\n    facet_wrap(~Measure, scale = \"fixed\") +\n    theme_bw()\n```\n\n::: {.cell-output-display}\n![](DanielHannon_FinalProjectAssignment1_files/figure-html/Graph difference by album type-1.png){width=672}\n:::\n:::\n\n\n```",
    "supporting": [
      "DanielHannon_FinalProjectAssignment1_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}