{
  "hash": "146517e4e11afcd2e4532c5c883ae017",
  "result": {
    "markdown": "---\ntitle: \"Final Project Assignment: Sai Venkatesh\"\nauthor: \"Sai Venkatesh\"\ndescription: \"Analysis of Airplane Passenger Satisfaction Dataset\"\ndate: \"05/03/2023\"\nformat:\n  html:\n    df-print: paged\n    toc: true\n    code-copy: true\n    code-tools: true\n    css: styles.css\ncategories:\n  - final_Project_assignment_1\n  - final_project_data_description\neditor_options: \n  chunk_output_type: console\neditor: \n  markdown: \n    wrap: sentence\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(ggplot2)\nlibrary(lubridate)\nlibrary(cowplot)\nlibrary(DataExplorer)\nlibrary(plyr)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Part 1. Introduction {#describe-the-data-sets}\n\n#### Dataset Introduction:\n\nThe problem consists of Airplane Passenger Satisfaction data set.\n\nThe data set was taken from Kaggle.com (https://www.kaggle.com/datasets/).\nThe data set has information related to passengers and the aggregated data of surveys collected post service experience.\n\nThe data set consists of random sample of 120000+ individuals who travelled using their flights.\nThe on-time performance of the flights along with the passengers information is published in the csv file named 'airplane_passenger_satisfaction.\nThese passengers were later asked to provide their feedback on various parameters related to the flight along with their overall experience.\nThese collected details are made available in the report.\nIn the survey, the passengers were explicitly asked whether they were satisfied with their overall flight experience and that is captured in the data of survey report under the variable labelled 'Satisfaction'.\n\n#### What questions do you like to answer with this data set(s)?\n\nThis report explores the survey analysis based on customer satisfaction scores from 120000+ airline passengers.\nThis capability of leveraging the data and by determining the relative importance of each parameter with respect to the passenger satisfaction can mean the difference between winning over a new customer and losing an old loyal customer.\n\nThe report will explore the clean data through visualization in order to answer the general question:\n\n**`What is the impact of various parameters on customer satisfaction and what are the steps to be taken by the airline to improve customer satisfaction?`**\n\n## Part 2. Describe the data set(s) {#describe-the-data-sets-1}\n\nThe given data set is in csv format.\nThe command read.csv is used for importing the data set.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  airplaneDS <- read.csv(\"/Users/saivenkatesh/Downloads/airline_passenger_satisfaction.csv\", na.strings = c(\"\", \"NA\")) \n  nrow(airplaneDS)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 129880\n```\n:::\n\n```{.r .cell-code}\n  ncol(airplaneDS)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 24\n```\n:::\n\n```{.r .cell-code}\n  dim(airplaneDS)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 129880     24\n```\n:::\n\n```{.r .cell-code}\n  head(airplaneDS, n=3)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"ID\"],\"name\":[1],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Gender\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Age\"],\"name\":[3],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Customer.Type\"],\"name\":[4],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Type.of.Travel\"],\"name\":[5],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Class\"],\"name\":[6],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Flight.Distance\"],\"name\":[7],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Departure.Delay\"],\"name\":[8],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Arrival.Delay\"],\"name\":[9],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Departure.and.Arrival.Time.Convenience\"],\"name\":[10],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Ease.of.Online.Booking\"],\"name\":[11],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Check.in.Service\"],\"name\":[12],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Online.Boarding\"],\"name\":[13],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Gate.Location\"],\"name\":[14],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"On.board.Service\"],\"name\":[15],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Seat.Comfort\"],\"name\":[16],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Leg.Room.Service\"],\"name\":[17],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Cleanliness\"],\"name\":[18],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Food.and.Drink\"],\"name\":[19],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"In.flight.Service\"],\"name\":[20],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"In.flight.Wifi.Service\"],\"name\":[21],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"In.flight.Entertainment\"],\"name\":[22],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Baggage.Handling\"],\"name\":[23],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Satisfaction\"],\"name\":[24],\"type\":[\"chr\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"1\",\"2\":\"Male\",\"3\":\"48\",\"4\":\"First-time\",\"5\":\"Business\",\"6\":\"Business\",\"7\":\"821\",\"8\":\"2\",\"9\":\"5\",\"10\":\"3\",\"11\":\"3\",\"12\":\"4\",\"13\":\"3\",\"14\":\"3\",\"15\":\"3\",\"16\":\"5\",\"17\":\"2\",\"18\":\"5\",\"19\":\"5\",\"20\":\"5\",\"21\":\"3\",\"22\":\"5\",\"23\":\"5\",\"24\":\"Neutral or Dissatisfied\",\"_rn_\":\"1\"},{\"1\":\"2\",\"2\":\"Female\",\"3\":\"35\",\"4\":\"Returning\",\"5\":\"Business\",\"6\":\"Business\",\"7\":\"821\",\"8\":\"26\",\"9\":\"39\",\"10\":\"2\",\"11\":\"2\",\"12\":\"3\",\"13\":\"5\",\"14\":\"2\",\"15\":\"5\",\"16\":\"4\",\"17\":\"5\",\"18\":\"5\",\"19\":\"3\",\"20\":\"5\",\"21\":\"2\",\"22\":\"5\",\"23\":\"5\",\"24\":\"Satisfied\",\"_rn_\":\"2\"},{\"1\":\"3\",\"2\":\"Male\",\"3\":\"41\",\"4\":\"Returning\",\"5\":\"Business\",\"6\":\"Business\",\"7\":\"853\",\"8\":\"0\",\"9\":\"0\",\"10\":\"4\",\"11\":\"4\",\"12\":\"4\",\"13\":\"5\",\"14\":\"4\",\"15\":\"3\",\"16\":\"5\",\"17\":\"3\",\"18\":\"5\",\"19\":\"5\",\"20\":\"3\",\"21\":\"4\",\"22\":\"3\",\"23\":\"3\",\"24\":\"Satisfied\",\"_rn_\":\"3\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n• The number of rows in the data set is 129880.\n\n• The number of columns in the data set is 24.\n\nEach row of the data set consists of\n\n-   Unique passenger identifier\n-   Gender of the passenger (Female/Male)\n-   Age of the passenger\n-   Type of airline customer (First-time/Returning)\n-   Purpose of the flight (Business/Personal)\n-   Travel class in the airplane for the passenger seat\n-   Flight distance in miles\n-   Flight departure delay in minutes\n-   Flight arrival delay in minutes\n-   Satisfaction level with the convenience of the flight departure and arrival times from 1 (lowest) to 5 (highest) - 0 means \"not applicable\"\n-   Satisfaction level with the online booking experience from 1 (lowest) to 5 (highest) - 0 means \"not applicable\"\n-   Satisfaction level with the check-in service from 1 (lowest) to 5 (highest) - 0 means \"not applicable\"\n-   Satisfaction level with the online boarding experience from 1 (lowest) to 5 (highest) - 0 means \"not applicable\"\n-   Satisfaction level with the gate location in the airport from 1 (lowest) to 5 (highest) - 0 means \"not applicable\"\n-   Satisfaction level with the on-boarding service in the airport from 1 (lowest) to 5 (highest) - 0 means \"not applicable\"\n-   Satisfaction level with the comfort of the airplane seat from 1 (lowest) to 5 (highest) - 0 means \"not applicable\"\n-   Satisfaction level with the leg room of the airplane seat from 1 (lowest) to 5 (highest) - 0 means \"not applicable\"\n-   Satisfaction level with the cleanliness of the airplane from 1 (lowest) to 5 (highest) - 0 means \"not applicable\"\n-   Satisfaction level with the food and drinks on the airplane from 1 (lowest) to 5 (highest) - 0 means \"not applicable\"\n-   Satisfaction level with the in-flight service from 1 (lowest) to 5 (highest) - 0 means \"not applicable\"\n-   Satisfaction level with the in-flight Wifi service from 1 (lowest) to 5 (highest) - 0 means \"not applicable\"\n-   Satisfaction level with the in-flight entertainment from 1 (lowest) to 5 (highest) - 0 means \"not applicable\"\n-   Satisfaction level with the baggage handling from the airline from 1 (lowest) to 5 (highest) - 0 means \"not applicable\"\n-   Overall satisfaction level with the airline (Satisfied/Neutral or unsatisfied).\n\nEach row represents the survey details of one passenger and each column represents specific feature.\nThe head and tail functions are used to view the first and last few rows of the data set.\n\nThe data set contains variables separated by dots.\nAs variable separated by dots create ambiguity in programming language, we will use underscore separated naming convention.\nMoreover, underscore separated variables are faster to read.\nThe variables are hence separated by underscores for better understanding.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n    finalData <- airplaneDS\n    names(finalData)[names(finalData) == \"Customer.Type\"] <- \"Customer_Type\"\n    names(finalData)[names(finalData) == \"Type.of.Travel\"] <- \"Type_of_Travel\"\n    names(finalData)[names(finalData) == \"Flight.Distance\"] <- \"Flight_Distance\"\n    names(finalData)[names(finalData) == \"Departure.Delay\"] <- \"Departure_Delay\"\n    names(finalData)[names(finalData) == \"Arrival.Delay\"] <- \"Arrival_Delay\"\n    names(finalData)[names(finalData) == \"Departure.and.Arrival.Time.Convenience\"] <- \"Departure_and_Arrival_Time_Convenience\"\n    names(finalData)[names(finalData) == \"Ease.of.Online.Booking\"] <- \"Ease_of_Online_Booking\"\n    names(finalData)[names(finalData) == \"Check.in.Service\"] <- \"Check_in_Service\"\n    names(finalData)[names(finalData) == \"Online.Boarding\"] <- \"Online_Boarding\"\n    names(finalData)[names(finalData) == \"Gate.Location\"] <- \"Gate_Location\"\n    names(finalData)[names(finalData) == \"On.board.Service\"] <- \"On_board_Service\"\n    names(finalData)[names(finalData) == \"Seat.Comfort\"] <- \"Seat_Comfort\"\n    names(finalData)[names(finalData) == \"Leg.Room.Service\"] <- \"Leg_Room_Service\"\n    names(finalData)[names(finalData) == \"Food.and.Drink\"] <- \"Food_and_Drink\"\n    names(finalData)[names(finalData) == \"In.flight.Service\"] <- \"In_flight_Service\"\n    names(finalData)[names(finalData) == \"In.flight.Wifi.Service\"] <- \"In_flight_Wifi_Service\"\n    names(finalData)[names(finalData) == \"In.flight.Entertainment\"] <- \"In_flight_Entertainment\"\n    names(finalData)[names(finalData) == \"Baggage.Handling\"] <- \"Baggage_Handling\"\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n      str(finalData)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t129880 obs. of  24 variables:\n $ ID                                    : int  1 2 3 4 5 6 7 8 9 10 ...\n $ Gender                                : chr  \"Male\" \"Female\" \"Male\" \"Male\" ...\n $ Age                                   : int  48 35 41 50 49 43 43 60 50 38 ...\n $ Customer_Type                         : chr  \"First-time\" \"Returning\" \"Returning\" \"Returning\" ...\n $ Type_of_Travel                        : chr  \"Business\" \"Business\" \"Business\" \"Business\" ...\n $ Class                                 : chr  \"Business\" \"Business\" \"Business\" \"Business\" ...\n $ Flight_Distance                       : int  821 821 853 1905 3470 3788 1963 853 2607 2822 ...\n $ Departure_Delay                       : int  2 26 0 0 0 0 0 0 0 13 ...\n $ Arrival_Delay                         : int  5 39 0 0 1 0 0 3 0 0 ...\n $ Departure_and_Arrival_Time_Convenience: int  3 2 4 2 3 4 3 3 1 2 ...\n $ Ease_of_Online_Booking                : int  3 2 4 2 3 4 3 4 1 5 ...\n $ Check_in_Service                      : int  4 3 4 3 3 3 4 3 3 3 ...\n $ Online_Boarding                       : int  3 5 5 4 5 5 4 4 2 5 ...\n $ Gate_Location                         : int  3 2 4 2 3 4 3 4 1 2 ...\n $ On_board_Service                      : int  3 5 3 5 3 4 5 3 4 5 ...\n $ Seat_Comfort                          : int  5 4 5 5 4 4 5 4 3 4 ...\n $ Leg_Room_Service                      : int  2 5 3 5 4 4 5 4 4 5 ...\n $ Cleanliness                           : int  5 5 5 4 5 3 4 4 3 4 ...\n $ Food_and_Drink                        : int  5 3 5 4 4 3 5 4 3 2 ...\n $ In_flight_Service                     : int  5 5 3 5 3 4 5 3 4 5 ...\n $ In_flight_Wifi_Service                : int  3 2 4 2 3 4 3 4 4 2 ...\n $ In_flight_Entertainment               : int  5 5 3 5 3 4 5 3 4 5 ...\n $ Baggage_Handling                      : int  5 5 3 5 3 4 5 3 4 5 ...\n $ Satisfaction                          : chr  \"Neutral or Dissatisfied\" \"Satisfied\" \"Satisfied\" \"Satisfied\" ...\n```\n:::\n\n```{.r .cell-code}\n      summary(finalData)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       ID            Gender               Age        Customer_Type     \n Min.   :     1   Length:129880      Min.   : 7.00   Length:129880     \n 1st Qu.: 32471   Class :character   1st Qu.:27.00   Class :character  \n Median : 64940   Mode  :character   Median :40.00   Mode  :character  \n Mean   : 64940                      Mean   :39.43                     \n 3rd Qu.: 97410                      3rd Qu.:51.00                     \n Max.   :129880                      Max.   :85.00                     \n                                                                       \n Type_of_Travel        Class           Flight_Distance Departure_Delay  \n Length:129880      Length:129880      Min.   :  31    Min.   :   0.00  \n Class :character   Class :character   1st Qu.: 414    1st Qu.:   0.00  \n Mode  :character   Mode  :character   Median : 844    Median :   0.00  \n                                       Mean   :1190    Mean   :  14.71  \n                                       3rd Qu.:1744    3rd Qu.:  12.00  \n                                       Max.   :4983    Max.   :1592.00  \n                                                                        \n Arrival_Delay     Departure_and_Arrival_Time_Convenience\n Min.   :   0.00   Min.   :0.000                         \n 1st Qu.:   0.00   1st Qu.:2.000                         \n Median :   0.00   Median :3.000                         \n Mean   :  15.09   Mean   :3.058                         \n 3rd Qu.:  13.00   3rd Qu.:4.000                         \n Max.   :1584.00   Max.   :5.000                         \n NA's   :393                                             \n Ease_of_Online_Booking Check_in_Service Online_Boarding Gate_Location  \n Min.   :0.000          Min.   :0.000    Min.   :0.000   Min.   :0.000  \n 1st Qu.:2.000          1st Qu.:3.000    1st Qu.:2.000   1st Qu.:2.000  \n Median :3.000          Median :3.000    Median :3.000   Median :3.000  \n Mean   :2.757          Mean   :3.306    Mean   :3.253   Mean   :2.977  \n 3rd Qu.:4.000          3rd Qu.:4.000    3rd Qu.:4.000   3rd Qu.:4.000  \n Max.   :5.000          Max.   :5.000    Max.   :5.000   Max.   :5.000  \n                                                                        \n On_board_Service  Seat_Comfort   Leg_Room_Service  Cleanliness   \n Min.   :0.000    Min.   :0.000   Min.   :0.000    Min.   :0.000  \n 1st Qu.:2.000    1st Qu.:2.000   1st Qu.:2.000    1st Qu.:2.000  \n Median :4.000    Median :4.000   Median :4.000    Median :3.000  \n Mean   :3.383    Mean   :3.441   Mean   :3.351    Mean   :3.286  \n 3rd Qu.:4.000    3rd Qu.:5.000   3rd Qu.:4.000    3rd Qu.:4.000  \n Max.   :5.000    Max.   :5.000   Max.   :5.000    Max.   :5.000  \n                                                                  \n Food_and_Drink  In_flight_Service In_flight_Wifi_Service\n Min.   :0.000   Min.   :0.000     Min.   :0.000         \n 1st Qu.:2.000   1st Qu.:3.000     1st Qu.:2.000         \n Median :3.000   Median :4.000     Median :3.000         \n Mean   :3.205   Mean   :3.642     Mean   :2.729         \n 3rd Qu.:4.000   3rd Qu.:5.000     3rd Qu.:4.000         \n Max.   :5.000   Max.   :5.000     Max.   :5.000         \n                                                         \n In_flight_Entertainment Baggage_Handling Satisfaction      \n Min.   :0.000           Min.   :1.000    Length:129880     \n 1st Qu.:2.000           1st Qu.:3.000    Class :character  \n Median :4.000           Median :4.000    Mode  :character  \n Mean   :3.358           Mean   :3.632                      \n 3rd Qu.:4.000           3rd Qu.:5.000                      \n Max.   :5.000           Max.   :5.000                      \n                                                            \n```\n:::\n:::\n\n\nThe structure of the data was analysed using the str function and it found that there are no duplicate columns.\nFrom the result, it is observed that many of the features are categorical in nature with data type as Integer and character .\n\nThe summary of the data set is reviewed using the r function, summary.\nThe summarized data is checked for meaningful and useful data for insight generation.\nThe data set consists of id variable, a unique identifier for each passenger and 22 independent variables.\nThe feature ID can be ignored as it is not going to play a major factor for the score of the target variable, Satisfaction.\nThe Satisfaction variable is dependant variable.\nThe table above provides the summary of the dependant variable, Satisfaction and the other independent variables.\nThe details help to understand the central tendency and the spread of the variable.\n\n## Part 3. The Tentative Plan for Visualization {#the-tentative-plan-for-visualization}\n\n#### Specific Questions\n\nIn order to conclude on the general question, analysis will be done on the below set of specific questions which are:\n\n1.  What is the univariate analysis of the Dependant feature?\n\n2.  What are the proportions of passengers by Customer type, Travel Type and Class?\n\n3.  What is the impact of the feature age on satisfaction?\n\n4.  Are the features Arrival and Departure delay correlated?\n\n5.  What are the impacts of the Pre Departure Procedures on satisfaction?\n\n6.  What are the impacts of the In Flight Services on satisfaction?\n\n7.  What are the impacts of the In Flight Amenities on satisfaction?\n\nData Cleaning is a necessary step as missing data, duplicated date, abnormal or extreme values can affect the result.\n\n#### Duplicate Values Check\n\nThe data was checked for any duplicated values using R function anyDuplicated and was found that there are no duplicated values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  anyDuplicated(finalData)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0\n```\n:::\n:::\n\n\n#### Outliers Analysis:\n\nData always needs to be checked for outliers.\nWithout doing this, it is likely to introduce a bias that could distort the results of the study.\nMultiple box plot is plotted to compare the features available in the data set.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboxplot(finalData$Flight_Distance,\n        finalData$Departure_Delay,\n        finalData$Arrival_Delay, \n        main=\"Box plots of Flight Distance, Departure Delay, Arrival Delay\", \n        ylab=\"Standard scaler\", \n        col=\"orange\", \n        border=\"black\")\n```\n\n::: {.cell-output-display}\n![](SaiVenkatesh_FinalProjectAssignment_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nIt is observed that the features such as flight distance, Departure Delay in minutes and Arrival delay in minutes have outliers as seen in the below box plot.\n\n#### Check for Missing Values:\n\nMissing Value introduces vagueness and in turn affects the data interpretation in statistical data analysis.\nThe data was checked for missing values and it is found that there are missing and empty values in Arrival delay.\nIt should be treated prior to the analysis of data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  colSums(is.na(finalData)) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                                    ID                                 Gender \n                                     0                                      0 \n                                   Age                          Customer_Type \n                                     0                                      0 \n                        Type_of_Travel                                  Class \n                                     0                                      0 \n                       Flight_Distance                        Departure_Delay \n                                     0                                      0 \n                         Arrival_Delay Departure_and_Arrival_Time_Convenience \n                                   393                                      0 \n                Ease_of_Online_Booking                       Check_in_Service \n                                     0                                      0 \n                       Online_Boarding                          Gate_Location \n                                     0                                      0 \n                      On_board_Service                           Seat_Comfort \n                                     0                                      0 \n                      Leg_Room_Service                            Cleanliness \n                                     0                                      0 \n                        Food_and_Drink                      In_flight_Service \n                                     0                                      0 \n                In_flight_Wifi_Service                In_flight_Entertainment \n                                     0                                      0 \n                      Baggage_Handling                           Satisfaction \n                                     0                                      0 \n```\n:::\n:::\n\n\nBefore imputation and missing value treatment, the percentage of missing value was studied.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n    plot_missing(finalData)\n```\n\n::: {.cell-output-display}\n![](SaiVenkatesh_FinalProjectAssignment_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nOut of the total 129880 records, only 393 records of feature Arrival delay are missing/empty values.\nMoreover, variable arrival delay has outliers.\nHence arrival delay can be given least importance for further analysis of the data set.\nIncase of model evaluation, the entire column need not be dropped as the number of missing values is 0.3%.\nMissing values treatment can be done by omitting the 393 records as shown below and thereby the final analysis can be done on 129487 records.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n    final.filtered <- finalData %>% na.omit()\n    sum(is.na(final.filtered))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0\n```\n:::\n:::\n\n\n#### Variable Importance:\n\nAddition/Deletion Of Variables:\n\nAs the problem statement requires interpretation of individual predictor variables, adding or deleting variables will play an important factor in dealing with a troublesome variable. But, this data set has quite a good information for the first level analysis and visualization.\nHence there is no need to add or delete any variable.\n\nCategorizing the data based on the levels:\n\nThe categorical features are organized based on Satisfaction level from 1 (lowest) to 5 (highest) - 0 means \"not applicable\".\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  Qualities <- c('not applicable'=0, 'poor'=1, 'need improvement'=2,'acceptable'=3,'good'=4,'excellent'=5)\n  \n  final.filtered$Cleanliness= as.factor(final.filtered$Cleanliness)\n  final.filtered$Check_in_Service= as.factor(final.filtered$Check_in_Service)\n  final.filtered$Baggage_Handling= as.factor(final.filtered$Baggage_Handling)\n  final.filtered$On_board_Service= as.factor(final.filtered$On_board_Service)\n  final.filtered$Leg_Room_Service= as.factor(final.filtered$Leg_Room_Service)\n  final.filtered$Ease_of_Online_Booking= as.factor(final.filtered$Ease_of_Online_Booking)\n  final.filtered$In_flight_Wifi_Service= as.factor(final.filtered$In_flight_Wifi_Service)\n  final.filtered$In_flight_Entertainment= as.factor(final.filtered$In_flight_Entertainment)\n  final.filtered$Food_and_Drink= as.factor(final.filtered$Food_and_Drink)\n  final.filtered$Departure_and_Arrival_Time_Convenience= as.factor(final.filtered$Departure_and_Arrival_Time_Convenience)\n  final.filtered$Check_in_Service= as.factor(final.filtered$Check_in_Service)\n  final.filtered$In_flight_Service= as.factor(final.filtered$In_flight_Service)\n  final.filtered$Online_Boarding= as.factor(final.filtered$Online_Boarding)\n  final.filtered$Gate_Location= as.factor(final.filtered$Gate_Location)\n  final.filtered$Seat_Comfort= as.factor(final.filtered$Seat_Comfort)\n```\n:::\n\n\nThe final data set contains variables which follow proper naming conventions, missing values treated and few variables converted as factors.\n\n#### Insightful Visualization:\n\nThe summarized data is checked for meaningful and useful data for insight generation using different visualization methods.\n\nThe histograms help us to identify the pattern of the variables with the frequency.\nA good indication of how the data are spread out is obtained through the box plot.\nThe pie chart helps to understand the different segments of Data.\n\nThe Analysis through Data Visualization is carried out in 7 steps\n\n1.  Univariate Analysis of Dependent Variable, Satisfaction\n\n2.  Proportion of Customer type, Travel Type and Class of the passengers.\n\n3.  Impact of variables -- Age , Gender on Satisfaction\n\n4.  Variable importance of Departure Delay and Arrival Delay\n\n5.  Impact of Variables - Ease of Online booking, check in service, online boarding, gate location and onboard services.\n\n6.  Impact of variables -- In-Flight Service, In-flight WIFI, In-Flight entertainment.\n\n7.  Impact of variables -- Seat comfort, Cleanliness, Leg room services, Food and Drinks.\n\n##### Univariate Analysis of Dependent Variable, Satisfaction\n\nFrom the table of the target variable, it is found that both Neutral or Dissatisfied and Satisfied have almost equal probabilities with slightly more proportion of dissatisfied passengers.\nThe selection is more or less balanced.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  table(as.factor(final.filtered$Satisfaction))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nNeutral or Dissatisfied               Satisfied \n                  73225                   56262 \n```\n:::\n\n```{.r .cell-code}\n  sat <- table(as.factor(final.filtered$Satisfaction))\n  barplot(sat, main=\"Barchart of Satisfaction\",col=\"Orange\", ylab=\"Count\")\n```\n\n::: {.cell-output-display}\n![](SaiVenkatesh_FinalProjectAssignment_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n##### Proportion of Customer type, Travel Type and Class of the passengers\n\nOn a broader perspective, there are more passengers travelling for business reasons(89445 passengers) than personal reasons.\n\nThere are 61990 passengers (majority) who travelled in business class followed by 58117 in economy class and 9380 in economy plus class.\n\nLets say all the 56262 passengers (from above analysis) who are satisfied are returning passengers.\nStill, the remaining 105773 - 56262 = 49511 returning passengers show dissatisfied/neutral feeling which is a significant number of loyal customers.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  table(as.factor(final.filtered$Type_of_Travel))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nBusiness Personal \n   89445    40042 \n```\n:::\n\n```{.r .cell-code}\n  table(as.factor(final.filtered$Class))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n    Business      Economy Economy Plus \n       61990        58117         9380 \n```\n:::\n\n```{.r .cell-code}\n  table(as.factor(final.filtered$Customer_Type))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nFirst-time  Returning \n     23714     105773 \n```\n:::\n:::\n\n\n##### Impact of Gender and Age on Passenger Satisfaction:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  table(as.factor(final.filtered$Gender))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nFemale   Male \n 65703  63784 \n```\n:::\n\n```{.r .cell-code}\n  dAge <- ggplot(airplaneDS)+\n          aes(x=Age, fill=Satisfaction)+\n          geom_density(adjust=1L)+\n          scale_fill_hue()+\n          labs(title=\"Impact of Age on Satisfaction\")\n  \n  hAge <- ggplot(airplaneDS)+\n          aes(x=Age)+geom_histogram(bins=30L,fill =\"orange\", colour=\"black\")+\n          scale_fill_hue()+\n          labs(title=\"Histogram of Age\")\n  \n  plot_grid(dAge,hAge)\n```\n\n::: {.cell-output-display}\n![](SaiVenkatesh_FinalProjectAssignment_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\nThe proportion of male and female passengers travelling in the airline is almost equal.\n\nFrom the histogram of age and density plot of age with satisfaction, it is observed that the people between the age of 40 to 60 are more satisfied with respect to the overall plane experience.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  newdata_Age_gt60 <- subset(finalData, finalData$Age > 60, select = c(1:24))\n  table(as.factor(newdata_Age_gt60$In_flight_Entertainment))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   0    1    2    3    4    5 \n   1 1602 2055 2118 2340 1938 \n```\n:::\n\n```{.r .cell-code}\n  table(as.factor(newdata_Age_gt60$Food_and_Drink))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   0    1    2    3    4    5 \n   9 1491 2183 2249 2153 1969 \n```\n:::\n\n```{.r .cell-code}\n  table(as.factor(newdata_Age_gt60$Ease_of_Online_Booking))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   0    1    2    3    4    5 \n 471 1726 2538 2544 1775 1000 \n```\n:::\n\n```{.r .cell-code}\n  table(as.factor(newdata_Age_gt60$Check_in_Service))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   1    2    3    4    5 \n1437 1522 2703 2724 1668 \n```\n:::\n:::\n\n\nOn further analysis of 60+ age group, there are many passengers in 60+ age group who are not happy with Check in service and Ease of Online Booking. \n\n##### Variable importance of Departure Delay and Arrival Delay:\n\nThe scatter plot spread of Arrival Delay and Departure Delay shows that they are highly correlated.\nThey are linearly dependant on each other and it is natural for the arrival to get delayed by the same time as that of the delay in departure in major cases.\n\nAs both of them are highly correlated and Arrival Delay has missing values, Departure Delay variable alone can be taken into consideration for further analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  plot(final.filtered$Departure_Delay,final.filtered$Arrival_Delay,col=\"turquoise\")\n```\n\n::: {.cell-output-display}\n![](SaiVenkatesh_FinalProjectAssignment_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n##### Impact of Pre Departure Procedures -- Ease of Online booking, Check In Service, Online Boarding, Gate Location, Onboard Services:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  a<- ggplot(finalData) +\n      aes(x=finalData$Ease_of_Online_Booking) +\n      geom_histogram(bins=30L,fill =\"orange\", colour=\"black\") +\n      scale_fill_hue()+labs(title=\"Histogram of Ease of Online Booking\")\n\n  b<- ggplot(finalData)+\n      aes(x=finalData$Check_in_Service)+\n      geom_histogram(bins=30L,fill =\"orange\", colour=\"black\")+\n      scale_fill_hue()+labs(title=\"Histogram of Check in Service\")\n  \n  c<- ggplot(finalData)+\n      aes(x=finalData$Online_Boarding)+\n      geom_histogram(bins=30L,fill =\"orange\", colour=\"black\")+\n      scale_fill_hue()+labs(title=\"Histogram of Online Boarding\")\n  \n  d<- ggplot(finalData)+\n      aes(x=finalData$Gate_Location)+\n      geom_histogram(bins=30L,fill =\"orange\", colour=\"black\")+\n      scale_fill_hue()+labs(title=\"Histogram of Gate Location\")\n  \n  e<- ggplot(finalData)+\n      aes(x=finalData$On_board_Service)+\n      geom_histogram(bins=30L,fill =\"orange\", colour=\"black\")+\n      scale_fill_hue()+labs(title=\"Histogram of On board Service\")\n  \n  plot_grid(a)\n```\n\n::: {.cell-output-display}\n![](SaiVenkatesh_FinalProjectAssignment_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n\n```{.r .cell-code}\n  plot_grid(b,c)\n```\n\n::: {.cell-output-display}\n![](SaiVenkatesh_FinalProjectAssignment_files/figure-html/unnamed-chunk-16-2.png){width=672}\n:::\n\n```{.r .cell-code}\n  plot_grid(d,e)\n```\n\n::: {.cell-output-display}\n![](SaiVenkatesh_FinalProjectAssignment_files/figure-html/unnamed-chunk-16-3.png){width=672}\n:::\n:::\n\n\nFrom the histogram plots, Most of the passengers have good views on the Checkin services but not satisfied with Gate location and Ease of Online Booking.\n\nIt is recommended to Ease the online booking as more passengers find the booking process poor, not good and neural feeling towards it.\nOnline Boarding and On board Service have good satisfaction levels.\n\n##### Impact of In-Flight Service Variables -- Service, Entertainment and WIFI:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  lb <- c(\"not applicable\", \"poor\", \"need improvement\",\"acceptable\",\"good\",\"excellent\")\n  \n  a <- revalue(as.factor(final.filtered$In_flight_Service), replace=Qualities)\n  summary(final.filtered$In_flight_Service)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    0     1     2     3     4     5 \n    5  8838 14252 25232 47198 33962 \n```\n:::\n\n```{.r .cell-code}\n  slicesIn_flight_Service <- c(5,8838,14252,25232,47198,33962)\n  pie(slicesIn_flight_Service,labels = lb, main=\"In_flight_Service pie chart\")\n```\n\n::: {.cell-output-display}\n![](SaiVenkatesh_FinalProjectAssignment_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n\n```{.r .cell-code}\n  b <- revalue(as.factor(final.filtered$In_flight_Wifi_Service), replace=Qualities)\n  summary(final.filtered$In_flight_Wifi_Service)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    0     1     2     3     4     5 \n 3908 22250 32236 32087 24702 14304 \n```\n:::\n\n```{.r .cell-code}\n  slicesIn_flight_Wifi_Service <- c(3908,22250,32236,32087,24702,14304)\n  pie(slicesIn_flight_Wifi_Service,labels = lb, main=\"In_flight_Wifi_Service pie chart\")\n```\n\n::: {.cell-output-display}\n![](SaiVenkatesh_FinalProjectAssignment_files/figure-html/unnamed-chunk-17-2.png){width=672}\n:::\n\n```{.r .cell-code}\n  c <- revalue(as.factor(final.filtered$In_flight_Entertainment), replace=Qualities)\n  summary(final.filtered$In_flight_Entertainment)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    0     1     2     3     4     5 \n   18 15634 21897 23805 36682 31451 \n```\n:::\n\n```{.r .cell-code}\n  slicesIn_flight_Entertainment <- c(18,15634,21897,23805,36682,31451)\n  pie(slicesIn_flight_Entertainment,labels = lb, main=\"In_flight_Entertainment pie chart\")\n```\n\n::: {.cell-output-display}\n![](SaiVenkatesh_FinalProjectAssignment_files/figure-html/unnamed-chunk-17-3.png){width=672}\n:::\n:::\n\n\nThe in-flight wifi requires improvement as quite a good proportion of people are not satisfied.\nThe majority of the passengers are satisfied with the The in-flight Entertainment and The in-flight Services.\n\nOn further analysis, there are significant amount of both business and personal type of travel passengers who are not satisfied with the WIFI. There are more economy class passengers who are not happy with the in fight entertainment than the business class people.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  newdata_WIFI_poor_needImp <- subset(finalData, finalData$In_flight_Wifi_Service <=2, select = c(1:24))\n  table(as.factor(newdata_WIFI_poor_needImp$Type_of_Travel))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nBusiness Personal \n   38501    20063 \n```\n:::\n\n```{.r .cell-code}\n  table(as.factor(newdata_WIFI_poor_needImp$Class))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n    Business      Economy Economy Plus \n       27620        26811         4133 \n```\n:::\n\n```{.r .cell-code}\n  table(as.factor(newdata_WIFI_poor_needImp$Customer_Type))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nFirst-time  Returning \n     10666      47898 \n```\n:::\n\n```{.r .cell-code}\n  newdata_In_flight_Entertainment_poor_needImp <- subset(finalData, finalData$In_flight_Entertainment <=2, select = c(1:24))\n  table(as.factor(newdata_In_flight_Entertainment_poor_needImp$Type_of_Travel))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nBusiness Personal \n   22360    15301 \n```\n:::\n\n```{.r .cell-code}\n  table(as.factor(newdata_In_flight_Entertainment_poor_needImp$Class))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n    Business      Economy Economy Plus \n       12965        21346         3350 \n```\n:::\n\n```{.r .cell-code}\n  table(as.factor(newdata_In_flight_Entertainment_poor_needImp$Customer_Type))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nFirst-time  Returning \n      8984      28677 \n```\n:::\n\n```{.r .cell-code}\n  table(as.factor(finalData$Class))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n    Business      Economy Economy Plus \n       62160        58309         9411 \n```\n:::\n\n```{.r .cell-code}\n  newdata_In_flight_Service_poor_needImp <- subset(finalData, finalData$In_flight_Service <=2, select = c(1:24))\n  table(as.factor(newdata_In_flight_Service_poor_needImp$Type_of_Travel))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nBusiness Personal \n   15394     7781 \n```\n:::\n\n```{.r .cell-code}\n  table(as.factor(newdata_In_flight_Service_poor_needImp$Class))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n    Business      Economy Economy Plus \n        8794        12301         2080 \n```\n:::\n\n```{.r .cell-code}\n  table(as.factor(newdata_In_flight_Service_poor_needImp$Customer_Type))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nFirst-time  Returning \n      3319      19856 \n```\n:::\n:::\n\n\n##### Impact of In Flight Amenities variables -- Seat comfort, Cleanliness, Leg room services, Food and Drinks\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  lb <- c(\"not applicable\", \"poor\", \"need improvement\",\"acceptable\",\"good\",\"excellent\")\n  final.filtered$Seat_Comfort= as.factor(final.filtered$Seat_Comfort)\n  d <- revalue(as.factor(final.filtered$Seat_Comfort), replace=Qualities)\n  summary(final.filtered$Seat_Comfort)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    0     1     2     3     4     5 \n    1 15059 18462 23258 39651 33056 \n```\n:::\n\n```{.r .cell-code}\n  slicesa <- c(1,15059,18462,23258,39651,33056)\n  pie(slicesa,labels = lb, main=\"Seat Comfort pie chart\")\n```\n\n::: {.cell-output-display}\n![](SaiVenkatesh_FinalProjectAssignment_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n\n```{.r .cell-code}\n  final.filtered$Leg_Room_Service= as.factor(final.filtered$Leg_Room_Service)\n  \n  e <- revalue(as.factor(final.filtered$Leg_Room_Service), replace=Qualities)\n  summary(final.filtered$Leg_Room_Service)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    0     1     2     3     4     5 \n  596 12846 24469 24982 35779 30815 \n```\n:::\n\n```{.r .cell-code}\n  slicesb <- c(596,12846,24469 ,24982, 35779 ,30815 )\n  pie(slicesb,labels = lb, main=\"Leg Room Service pie chart\")\n```\n\n::: {.cell-output-display}\n![](SaiVenkatesh_FinalProjectAssignment_files/figure-html/unnamed-chunk-19-2.png){width=672}\n:::\n\n```{.r .cell-code}\n  final.filtered$Cleanliness= as.factor(final.filtered$Cleanliness)\n  \n  f <- revalue(as.factor(final.filtered$Cleanliness), replace=Qualities)\n  summary(final.filtered$Cleanliness)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    0     1     2     3     4     5 \n   14 16680 20049 30552 33871 28321 \n```\n:::\n\n```{.r .cell-code}\n  slicesc <- c(14, 16680, 20049 ,30552, 33871 ,28321 )\n  pie(slicesc,labels = lb, main=\"Cleanliness pie chart\")\n```\n\n::: {.cell-output-display}\n![](SaiVenkatesh_FinalProjectAssignment_files/figure-html/unnamed-chunk-19-3.png){width=672}\n:::\n\n```{.r .cell-code}\n  final.filtered$Food_and_Drink= as.factor(final.filtered$Food_and_Drink)\n  \n  g <- revalue(as.factor(final.filtered$Food_and_Drink), replace=Qualities)\n  summary(final.filtered$Food_and_Drink)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    0     1     2     3     4     5 \n  130 16010 27293 27712 30477 27865 \n```\n:::\n\n```{.r .cell-code}\n  slicesd <- c(130, 16010, 27293 ,27712, 30477 ,27865 )\n  pie(slicesd,labels = lb, main=\"Food and Drink pie chart\")\n```\n\n::: {.cell-output-display}\n![](SaiVenkatesh_FinalProjectAssignment_files/figure-html/unnamed-chunk-19-4.png){width=672}\n:::\n:::\n\n\nThe Cleanliness and Food and Drink requires improvement.\nThe majority of the passengers are satisfied with the Leg Room Service and The Seat Comfort.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  newdata_Food_Drink_poor_needImp <- subset(finalData, finalData$Food_and_Drink <=3, select = c(1:24))\n  table(as.factor(newdata_Food_Drink_poor_needImp$Type_of_Travel))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nBusiness Personal \n   47559    23801 \n```\n:::\n\n```{.r .cell-code}\n  table(as.factor(newdata_Food_Drink_poor_needImp$Class))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n    Business      Economy Economy Plus \n       32075        33894         5391 \n```\n:::\n\n```{.r .cell-code}\n  table(as.factor(newdata_Food_Drink_poor_needImp$Customer_Type))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nFirst-time  Returning \n     14062      57298 \n```\n:::\n:::\n\n\nWhen we analyse food and Drinks further, for food and drinks in 0-3 category, there are more business class , passengers travelling for business reasons  and more returning passengers who are not happy with the food and drink.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  newdata_Leg_Room_Service_poor_needImp <- subset(finalData, finalData$Leg_Room_Service <=2, select = c(1:24))\n\n  table(as.factor(newdata_Leg_Room_Service_poor_needImp$Type_of_Travel))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nBusiness Personal \n   23466    14567 \n```\n:::\n\n```{.r .cell-code}\n  table(as.factor(newdata_Leg_Room_Service_poor_needImp$Customer_Type))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nFirst-time  Returning \n      7886      30147 \n```\n:::\n\n```{.r .cell-code}\n  table(as.factor(newdata_Leg_Room_Service_poor_needImp$Class))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n    Business      Economy Economy Plus \n       13198        21300         3535 \n```\n:::\n:::\n\n\nWhen it comes to cleanliness and Leg room space, There are 20758 and 21300 passengers respectively in Economy class who show dissatisfaction/ neutral feeling.\n\n## Part 4. Conclusion and Recommendation\n\n-   The passenger satisfaction is more or less balanced from the Univariate Analysis of Dependent Variable, Satisfaction. The summary of satisfaction shows that 56262 passengers are satisfied, whereas, 73225 passengers are dissatisfied or show neutral response.\n-   The passengers travelling in economy class show more dissatisfaction towards the overall flight experience followed by the business class and economy plus class.\n-   It is observed that the proportion of customer type as Returning is more (105773 passengers). which means there are more loyal customers who show dissatisfaction or neutral feeling towards the overall flight experience.\n-   From the Age impact analysis on satisfaction, its observed that for the age group above 60 and below 40, the services will have to be improved to capture that age group of passengers.\n-   For Pre departure procedures - Ease of online booking and Gate location accessability have to be improved.\n-   Exploring the data set, more than 30 percent of economy class passengers (26811 & 21346 passengers of total 58309) had neutral or dissatisfied feeling due to inflight wifi and inflight entertainment.\n-   For In-flight Amenities - the Cleanliness and Food and Drink requires improvement.\n-   Based on the outliers, missing value analysis and scatter plot of the Arrival Delay vs Departure Delay, the feature Arrival Delay can be given least importance for analysis of the data set and evaluation.\n\nBased on the above analysis, the airline can take the below steps to win passengers:\n\n1.  As the majority of the passengers are loyal passengers who keep returning, pre filled data facilities can be used to ease the Pre departure procedures such that the passenger can fill in minimal data to improve the ease of booking.\n\n2.  As the economy class passengers and people aged below 40 and above 60 are not satisfied, specific coupons and mails with vouchers can be sent to win over the dissatisfied passengers.\n\n3.  Extra benefits like Miles points can be offered to the loyal passengers since a significant number of them are dissatisfied.\n\n4.  Returning passengers show more dissatisfaction towards food and drinks. It is recommended to give feedback form which is an easy way to collect opinions about the food and drink options and  to improve the business, products, services, and overall passenger satisfaction. Improvisation can be done based on the feedback forms and appropriate suggestions can be given to passengers during the time of booking  using AI, ML tools , for the returning passengers thereby improving  the Satisfaction rate with regarding to Ease of online booking and Food and Drink options.\n\n5.  It is recommended that the airline conduct regular cleaning services to ensure that the passengers have a pleasant flying experience.\n\n6.  When it comes to Cleanliness and leg room space, the economy class passengers show more dissatisfaction than other class of passengers. It is recommended to re-structure the leg room space of the Economy class passengers to increase the satisfaction rates in terms of leg room space. If not for leg room space as that would involve infrastructure cost and feasibility checks, steps can be taken to improve the cleanliness by enforcing rules and regulations.\n\n## Part 5. Bibliography\n\n+ R: A language and environment for statistical computing. - https://www.R-project.org/\n+ R Studio IDE. - https://posit.co/products/open-source/rstudio/\n+ Kaggle: Your Machine Learning and Data Science Community. - https://www.kaggle.com/datasets/",
    "supporting": [
      "SaiVenkatesh_FinalProjectAssignment_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}