{
  "hash": "3afd650d190553bf953a255d7baf45e2",
  "result": {
    "markdown": "---\ntitle: \"Challenge 2\"\nauthor: \"Poobigan Murugesan\"\ndescription: \"Data wrangling: using group() and summarise()\"\ndate: \"05/09/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_2\n  - railroads\n  - poobigan murugesan\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(dplyr)\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Challenge Overview\n\nToday's challenge is to\n\n1)  read in a data set, and describe the data using both words and any supporting information (e.g., tables, etc)\n2)  provide summary statistics for different interesting groups within the data, and interpret those statistics\n\n## Read in the Data\n\nRead in one (or more) of the following data sets, available in the `posts/_data` folder, using the correct R package and command.\n\n-   railroad\\*.csv or StateCounty2012.xls ⭐\n-   FAOstat\\*.csv or birds.csv ⭐⭐⭐\n-   hotel_bookings.csv ⭐⭐⭐⭐\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf<- read_csv(\"_data/railroad_2012_clean_county.csv\")\nprint(df,show_col_types=FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2,930 × 3\n   state county               total_employees\n   <chr> <chr>                          <dbl>\n 1 AE    APO                                2\n 2 AK    ANCHORAGE                          7\n 3 AK    FAIRBANKS NORTH STAR               2\n 4 AK    JUNEAU                             3\n 5 AK    MATANUSKA-SUSITNA                  2\n 6 AK    SITKA                              1\n 7 AK    SKAGWAY MUNICIPALITY              88\n 8 AL    AUTAUGA                          102\n 9 AL    BALDWIN                          143\n10 AL    BARBOUR                            1\n# ℹ 2,920 more rows\n```\n:::\n:::\n\n\n\n## Describe the data\n\nUsing a combination of words and results of R commands, can you provide a high level description of the data? Describe as efficiently as possible where/how the data was (likely) gathered, indicate the cases and variables (both the interpretation and any details you deem useful to the reader to fully understand your chosen data).\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2930    3\n```\n:::\n:::\n\nThe dataset consists of 2930 rows and 3 columns.\n\n\nBy using the 'str' function, we can obtain information about the data types, lengths, contents, and other relevant information pertaining to each column. The dataset is comprised of three distinct columns: 'State' (which is of character type), 'County' (also of character type), and 'Total Employees' (which is of numeric type). From the dataset, we can infer that it pertains to railroad employees from various states and counties.\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nspc_tbl_ [2,930 × 3] (S3: spec_tbl_df/tbl_df/tbl/data.frame)\n $ state          : chr [1:2930] \"AE\" \"AK\" \"AK\" \"AK\" ...\n $ county         : chr [1:2930] \"APO\" \"ANCHORAGE\" \"FAIRBANKS NORTH STAR\" \"JUNEAU\" ...\n $ total_employees: num [1:2930] 2 7 2 3 2 1 88 102 143 1 ...\n - attr(*, \"spec\")=\n  .. cols(\n  ..   state = col_character(),\n  ..   county = col_character(),\n  ..   total_employees = col_double()\n  .. )\n - attr(*, \"problems\")=<externalptr> \n```\n:::\n:::\n\n\n\n## Provide Grouped Summary Statistics\n\nConduct some exploratory data analysis, using dplyr commands such as `group_by()`, `select()`, `filter()`, and `summarise()`. Find the central tendency (mean, median, mode) and dispersion (standard deviation, mix/max/quantile) for different subgroups within the data set.\n\nNumber of unique states in the data\n\n::: {.cell}\n\n```{.r .cell-code}\ncount(distinct(select(df, state)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 1\n      n\n  <int>\n1    53\n```\n:::\n:::\n\nThe dataset contains information on the total number of railroad employees across 53 distinct states.\n\nWhich county has the maximum number of employees?\n\n::: {.cell}\n\n```{.r .cell-code}\ndf %>% summarise(employee_count = max(total_employees), maxCounty = county[which.max(total_employees)])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 2\n  employee_count maxCounty\n           <dbl> <chr>    \n1           8207 COOK     \n```\n:::\n:::\n\nThe county that has the highest count of railroad workers in this dataset is COOK, with a total of 8207 employees.\n\nWhich county has the minimum number of employees?\n\n::: {.cell}\n\n```{.r .cell-code}\ndf %>% summarize(employee_count = min(total_employees), minCounty = county[which(total_employees == min(total_employees))])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 145 × 2\n   employee_count minCounty\n            <dbl> <chr>    \n 1              1 SITKA    \n 2              1 BARBOUR  \n 3              1 HENRY    \n 4              1 APO      \n 5              1 NEWTON   \n 6              1 MONO     \n 7              1 BENT     \n 8              1 CHEYENNE \n 9              1 COSTILLA \n10              1 DOLORES  \n# ℹ 135 more rows\n```\n:::\n:::\n\nBased on the above output, we can determine that the minimum number of railroad employees in any county is 1, and there are a total of 145 counties with only one employee.\n\nGrouping railroad employees by state to figure out which states have the most railroad employees.\n\n::: {.cell}\n\n```{.r .cell-code}\ngroup <- df %>%\n  group_by(state) %>%\n  summarize(employees=sum(total_employees)) %>%\n  arrange(desc(employees))\ngroup\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 53 × 2\n   state employees\n   <chr>     <dbl>\n 1 TX        19839\n 2 IL        19131\n 3 NY        17050\n 4 NE        13176\n 5 CA        13137\n 6 PA        12769\n 7 OH         9056\n 8 GA         8605\n 9 IN         8537\n10 MO         8419\n# ℹ 43 more rows\n```\n:::\n:::\n\nBased on the results shown above, we can see that the state of Texas has the largest number of railroad employees, with a count of 19839 followed by Illinois and New York with 19131 and 17050 employees respectively. Also, from the dimensions of the group dataset we can conclude that there are 53 distinct states where people are employed to work railroads.\n\nGrouping the data by state and calculating the mean of total employees in each state based on the number of counties.\n\n::: {.cell}\n\n```{.r .cell-code}\ngroup <- df %>%\n  group_by(state) %>%\n  summarize(mean=mean(total_employees)) %>%\n  arrange(desc(mean))\ngroup\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 53 × 2\n   state  mean\n   <chr> <dbl>\n 1 DE     498.\n 2 NJ     397.\n 3 CT     324 \n 4 MA     282.\n 5 NY     280.\n 6 DC     279 \n 7 CA     239.\n 8 AZ     210.\n 9 PA     196.\n10 MD     196.\n# ℹ 43 more rows\n```\n:::\n:::\n\n\nBased on the results above, we can conclude that the state of DE has the highest average number of railroad employees per county, which is 498\n\n\nGrouping the data by state and calculating the median of total employees in each state based on the number of counties.\n\n::: {.cell}\n\n```{.r .cell-code}\ngroup <- df %>%\n  group_by(state) %>%\n  summarize(median=median(total_employees)) %>%\n  arrange(desc(median))\ngroup\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 53 × 2\n   state median\n   <chr>  <dbl>\n 1 NJ      296 \n 2 DC      279 \n 3 MA      271 \n 4 DE      158 \n 5 CT      125 \n 6 MD      108.\n 7 AZ       94 \n 8 PA       85 \n 9 NY       71 \n10 CA       61 \n# ℹ 43 more rows\n```\n:::\n:::\n\n\n\nMode - Extracting the state with highest number of counties with railroad employees.\n\n::: {.cell}\n\n```{.r .cell-code}\ndf %>%\n  group_by(state) %>%\n  summarize(counties = n()) %>%\n  arrange(desc(counties)) %>%\n  slice(1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 2\n  state counties\n  <chr>    <int>\n1 TX         221\n```\n:::\n:::\n\nThe result of this specific code shows that Texas (TX) has the highest number of counties with railroad employees, with a count of 221.\n\n\nExtracting information about railroad employees specifically from the counties in TX using a filter operation.\n\n::: {.cell}\n\n```{.r .cell-code}\ncounties_tx <-filter(df, state=='TX')\ncounties_tx\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 221 × 3\n   state county    total_employees\n   <chr> <chr>               <dbl>\n 1 TX    ANDERSON              241\n 2 TX    ANDREWS                 3\n 3 TX    ANGELINA               53\n 4 TX    ARANSAS                 6\n 5 TX    ARCHER                  8\n 6 TX    ARMSTRONG              12\n 7 TX    ATASCOSA               64\n 8 TX    AUSTIN                 35\n 9 TX    BAILEY                  5\n10 TX    BANDERA                15\n# ℹ 211 more rows\n```\n:::\n:::\n\nDouble-checking the number of counties in TX, the filter and count commands confirm that there are indeed 221 counties with railroad employees in TX as previously determined.\n\nGrouping the data by state and calculating the median of total employees in each state based on the number of counties.\n\n::: {.cell}\n\n```{.r .cell-code}\ngroup <- df %>%\n  group_by(state) %>%\n  summarize(std=sd(total_employees)) %>%\n  arrange(desc(std))\ngroup\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 53 × 2\n   state   std\n   <chr> <dbl>\n 1 IL     829.\n 2 DE     674.\n 3 NY     591.\n 4 CA     549.\n 5 CT     520.\n 6 NE     512.\n 7 FL     386.\n 8 TX     350.\n 9 VA     341.\n10 NJ     338.\n# ℹ 43 more rows\n```\n:::\n:::\n\n\nGrouping data by state and analyzing its summary\n\n::: {.cell}\n\n```{.r .cell-code}\ngroup <- df %>%\n  group_by(state)\n\nsummary(group)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    state              county          total_employees  \n Length:2930        Length:2930        Min.   :   1.00  \n Class :character   Class :character   1st Qu.:   7.00  \n Mode  :character   Mode  :character   Median :  21.00  \n                                       Mean   :  87.18  \n                                       3rd Qu.:  65.00  \n                                       Max.   :8207.00  \n```\n:::\n:::\n\nBased on the quartile distributions, we can conclude that many states have a low number of employees, indicating that the distribution of employees among states is not evenly distributed and is instead skewed.\n\n\n### Explain and Interpret\n\nI selected this specific group to analyze the distribution of railroad employees by state. The data shows that there are employees in 53 states, and the county with the highest number of employees is COOK in IL with 8207 employees, while 145 counties have only one railroad employee.\n\nWhen we grouped the data by state, we found that TX has the highest number of railroad employees with 19839, while AP has the lowest with only one employee. DE has the highest mean number of employees with 498 per county, and AP has the lowest mean number with only one employee. NJ has the highest median number of employees per county with 296. Additionally, we found that TX has the maximum number of entries, which is the mode of the number of counties with 221 counties.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}