{
  "hash": "1e9d7a74711f8d696dee9bb1f8a3fb92",
  "result": {
    "markdown": "---\ntitle: \"Challenge 2: Railroad Wrangling\"\nauthor: \"Daniel Hannon\"\ndesription: \"Desribed and Analyzed the Railroad dataset\"\ndate: \"03/07/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_2\n  - Daniel Hannon\n  - railroads\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nknitr::opts_chunk$set(echo = TRUE)\n```\n:::\n\n\n# Reading in the Data\n\n::: {.cell}\n\n```{.r .cell-code}\nrailroad_data <- readxl::read_excel(\"_data/StateCounty2012.xls\")\nslice(railroad_data, 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 6\n  `TOTAL RAILROAD EMPLOYMENT BY STATE AND COUNTY` ...2  ...3  ...4  ...5  ...6 \n  <chr>                                           <chr> <lgl> <chr> <lgl> <chr>\n1 CALENDAR YEAR 2012                              <NA>  NA    <NA>  NA    <NA> \n```\n:::\n:::\n\nLooking at the original spreadsheet, we can see based on the title that this data is about the number of railroad employees in the United states, categorized by state and county for the year 2012. The data does not start until line 3 and columns 2 and 4 contain no information, so we can read in the data, skip the first two rows and select out the empty columns.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrailroad_data <-readxl::read_excel(\"_data/StateCounty2012.xls\", skip= 3) %>%\n                select(STATE, COUNTY, TOTAL)\nhead(railroad_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 3\n  STATE     COUNTY               TOTAL\n  <chr>     <chr>                <dbl>\n1 AE        APO                      2\n2 AE Total1 <NA>                     2\n3 AK        ANCHORAGE                7\n4 AK        FAIRBANKS NORTH STAR     2\n5 AK        JUNEAU                   3\n6 AK        MATANUSKA-SUSITNA        2\n```\n:::\n:::\n\nWe can see that each observation is the number of railway workers for a given county in 2012. However, there also contains observations about the total for each state. These observations contain an N/A in the county space and use the word Total in the state column. We can filter these out to have a data frame for all the state totals and one for all the unique counties.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#A data frame of just totals\nstate_totals <- railroad_data %>%\n                filter(grepl(\"Total\", STATE)) %>%\n                select(!COUNTY)\n\n#A data frame of no totals \nremoved_state_totals <- railroad_data %>%\n                        filter(!grepl(\"Total\", STATE))\n\nstate_totals\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 54 × 2\n   STATE     TOTAL\n   <chr>     <dbl>\n 1 AE Total1     2\n 2 AK Total    103\n 3 AL Total   4257\n 4 AP Total1     1\n 5 AR Total   3871\n 6 AZ Total   3153\n 7 CA Total  13137\n 8 CO Total   3650\n 9 CT Total   2592\n10 DC Total    279\n# … with 44 more rows\n```\n:::\n\n```{.r .cell-code}\nhead(removed_state_totals)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 3\n  STATE COUNTY               TOTAL\n  <chr> <chr>                <dbl>\n1 AE    APO                      2\n2 AK    ANCHORAGE                7\n3 AK    FAIRBANKS NORTH STAR     2\n4 AK    JUNEAU                   3\n5 AK    MATANUSKA-SUSITNA        2\n6 AK    SITKA                    1\n```\n:::\n:::\n\nThe State totals should only have 50 observations, because there are only 50 states, but there is are 54. This is because Armed Forces Pacific, Armed Forces Europe, DC and the Grand Total are all saved in the frame. For the purposes of gaining insights about state totals specifically, these will be filtered out of the state_totals tibble before descriptive statistics are done. \n\n::: {.cell}\n\n```{.r .cell-code}\nstate_totals <- state_totals %>%\n                filter(!STATE %in% c(\"AE Total1\", \"AP Total1\", \"DC Total\", \"Grand Total\"))\n```\n:::\n\n# Summary Statistics \n\n### State level\n\nFirst lets look at the statistics of the state totals:\n\n::: {.cell}\n\n```{.r .cell-code}\nsummarize(state_totals, Mean = mean(TOTAL), Median = median(TOTAL), Minimum =min(TOTAL), Maximum = max(TOTAL), Std = sd(TOTAL), IQR= IQR(TOTAL))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 6\n   Mean Median Minimum Maximum   Std   IQR\n  <dbl>  <dbl>   <dbl>   <dbl> <dbl> <dbl>\n1  5103  3712.       4   19839 4777.  4953\n```\n:::\n:::\n\nThe totals for each state vary heavily, with a standard deviation of over 4.7 thousand compared to the mean of 5.1 thousand. It also looks like the values are skewed with a few very large states pulling the average up. This can be seen by the mean being almost half a standard deviation higher than the median, and can also be seen by the range of values going from 4 to 19839. In order to try to get a closer look at the county level, we can summarize over our other tibble. \n\n### County Level\n\n::: {.cell}\n\n```{.r .cell-code}\nsummarize(removed_state_totals, Mean = mean(TOTAL, na.rm =TRUE), Median = median(TOTAL, na.rm =TRUE), Minimum =min(TOTAL, na.rm =TRUE), Maximum = max(TOTAL, na.rm =TRUE), Std = sd(TOTAL, na.rm =TRUE), IQR= IQR(TOTAL, na.rm =TRUE))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 6\n   Mean Median Minimum Maximum   Std   IQR\n  <dbl>  <dbl>   <dbl>   <dbl> <dbl> <dbl>\n1  87.4     21       1    8207  284.    58\n```\n:::\n:::\n\n\nMuch like the State Total data, this data is highly varied and skewed. Again we can see that the mean is much higher than the mean, but in the case of this data the IQR is much smaller than the Standard Deviation. This also suggests that there are a few observations much higher than the average, and that these are skewing the data.\n\n\n::: {.cell warnings='false' messages='false'}\n\n```{.r .cell-code}\nremoved_state_totals %>% \n  group_by(STATE)%>%\n  select(TOTAL)%>%\n  summarize_all(mean, na.rm= TRUE) %>%\n  summarize(Mean = mean(TOTAL, na.rm =TRUE), Median = median(TOTAL, na.rm =TRUE), Minimum =min(TOTAL, na.rm =TRUE), Maximum = max(TOTAL, na.rm =TRUE), Std = sd(TOTAL, na.rm =TRUE), IQR= IQR(TOTAL, na.rm =TRUE))\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nAdding missing grouping variables: `STATE`\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 6\n   Mean Median Minimum Maximum   Std   IQR\n  <dbl>  <dbl>   <dbl>   <dbl> <dbl> <dbl>\n1  116.   63.8       1     662  128.  89.3\n```\n:::\n:::\n\nThe data above shows the descriptive statistics over the mean number of railroad employees per county per state. We can see that the range descreases, as the highest average number of workers per county in a state is 662, while the lowest is still 1. We can still see the skew from before, but it is less impactful with a lower standard deviation and a smaller gap between the median and mean. So while the average county has 87 workers according to the last summary, we can see that the average mean number of employees per county state wide is 115.\n",
    "supporting": [
      "DanielHannon_challenge2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}