{
  "hash": "533e8f8989dffacd84d6387a8d26da28",
  "result": {
    "markdown": "---\ntitle: \"Challenge 5\"\nauthor: \"Sai Venkatesh\"\ndescription: \"Introduction to Visualization\"\ndate: \"04/28/2023\"\nformat:\n  html:\n    toc: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_5\n  - railroads\n  - cereal\n  - air_bnb\n  - pathogen_cost\n  - australian_marriage\n  - public_schools\n  - usa_households\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(ggplot2)\nlibrary(readxl)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Challenge Overview\n\nToday's challenge is to:\n\n1)  read in a data set, and describe the data set using both words and any supporting information (e.g., tables, etc)\n2)  tidy data (as needed, including sanity checks)\n3)  mutate variables as needed (including sanity checks)\n4)  create at least two univariate visualizations\n   - try to make them \"publication\" ready\n   - Explain why you choose the specific graph type\n5)  Create at least one bivariate visualization\n   - try to make them \"publication\" ready\n   - Explain why you choose the specific graph type\n\n[R Graph Gallery](https://r-graph-gallery.com/) is a good starting point for thinking about what information is conveyed in standard graph types, and includes example R code.\n\n(be sure to only include the category tags for the data you use!)\n\n## Read in data\n\nRead in one (or more) of the following datasets, using the correct R package and command.\n\n-   cereal.csv ⭐\n-   Total_cost_for_top_15_pathogens_2018.xlsx ⭐\n-   Australian Marriage ⭐⭐ \n-   AB_NYC_2019.csv ⭐⭐⭐\n-   StateCounty2012.xls ⭐⭐⭐\n-   Public School Characteristics ⭐⭐⭐⭐ \n-   USA Households ⭐⭐⭐⭐⭐\n\n  We are reading the State County data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  state_county_data <- read_xls('_data/StateCounty2012.xls', skip=4,\n                col_names= c(\"STATE\", \"Removed\",  \"COUNTY\",\n                          \"Removed\", \"EMPLOYEES\"))\n  \n  state_county_data <- state_county_data %>%\n    select(STATE, COUNTY, EMPLOYEES) %>%\n    filter(!str_detect(STATE, \"Total\"))\n  \n  state_county_data <- state_county_data %>%\n    filter(!str_detect(STATE, \"Excludes\"))\n  \n  state_county_data <- state_county_data %>%\n    filter(!str_detect(STATE, \"designation\"))  \n  \n  state_county_data <- state_county_data %>%\n    mutate(COUNTY = ifelse(STATE==\"CANADA\", \"CANADA\", COUNTY))\n  \n  # The Dimensions \n  dim(state_county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2931    3\n```\n:::\n\n```{.r .cell-code}\n  # The Column Names \n  colnames(state_county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"STATE\"     \"COUNTY\"    \"EMPLOYEES\"\n```\n:::\n\n```{.r .cell-code}\n  head(state_county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 3\n  STATE COUNTY               EMPLOYEES\n  <chr> <chr>                    <dbl>\n1 AE    APO                          2\n2 AK    ANCHORAGE                    7\n3 AK    FAIRBANKS NORTH STAR         2\n4 AK    JUNEAU                       3\n5 AK    MATANUSKA-SUSITNA            2\n6 AK    SITKA                        1\n```\n:::\n\n```{.r .cell-code}\n  tail(state_county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 3\n  STATE  COUNTY     EMPLOYEES\n  <chr>  <chr>          <dbl>\n1 WY     SUBLETTE           3\n2 WY     SWEETWATER       196\n3 WY     UINTA             49\n4 WY     WASHAKIE          10\n5 WY     WESTON            37\n6 CANADA CANADA           662\n```\n:::\n\n```{.r .cell-code}\n  summary(state_county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    STATE              COUNTY            EMPLOYEES      \n Length:2931        Length:2931        Min.   :   1.00  \n Class :character   Class :character   1st Qu.:   7.00  \n Mode  :character   Mode  :character   Median :  21.00  \n                                       Mean   :  87.37  \n                                       3rd Qu.:  65.00  \n                                       Max.   :8207.00  \n```\n:::\n:::\n\n\n### Briefly describe the data\n\nThe data seems to be of the count of railroad employees split up across county and state in the United States.\nThere are a total of 2931 counties with employee count numbers with the max county having 8207 employees.\n\n\n## Tidy Data (as needed)\n\nWe have tidied up the data in the previous step.\n\n\nAre there any variables that require mutation to be usable in your analysis stream? For example, do you need to calculate new values in order to graph them? Can string values be represented numerically? Do you need to turn any variables into factors and reorder for ease of graphics and visualization?\n\nDocument your work here.\n\nWe are going to aggregate state employees count. This will be used in graphics below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  grouped_by_state <- state_county_data %>%\n    group_by(STATE) %>%\n    summarize(state_total = sum(EMPLOYEES), \n    state_counties = n_distinct(COUNTY)) %>%\n    select(STATE, state_total, state_counties) %>%\n    arrange(desc(state_total))\n  grouped_by_state\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 54 × 3\n   STATE state_total state_counties\n   <chr>       <dbl>          <int>\n 1 TX          19839            221\n 2 IL          19131            103\n 3 NY          17050             61\n 4 NE          13176             89\n 5 CA          13137             55\n 6 PA          12769             65\n 7 OH           9056             88\n 8 GA           8605            152\n 9 IN           8537             92\n10 MO           8419            115\n# … with 44 more rows\n```\n:::\n:::\n\n\n## Univariate Visualizations\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  ggplot(state_county_data, aes(EMPLOYEES)) +\n    geom_histogram(fill=\"red\")  +\n    theme_minimal() +\n    labs(title = \"Distribution of Employee Numbers of Counties\", y = \"Count\", x = \"County Employee Numbers\")\n```\n\n::: {.cell-output-display}\n![](SaiVenkateshChallenge5_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n\n```{.r .cell-code}\n  ggplot(grouped_by_state, aes(state_total)) +\n    geom_histogram(fill=\"blue\")  +\n    theme_minimal() +\n    labs(title = \"Distribution of Employee Numbers of States\", y = \"Count\", x = \"State Employee Numbers\")\n```\n\n::: {.cell-output-display}\n![](SaiVenkateshChallenge5_files/figure-html/unnamed-chunk-4-2.png){width=672}\n:::\n:::\n\n\n## Bivariate Visualization(s)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  ggplot(grouped_by_state, aes(state_total, state_counties)) +\n    geom_point()  +\n    theme_minimal() +\n    labs(title = \"State Counties vs Employee Numbers\", y = \"State Counties Number\", x = \"State Employees\")\n```\n\n::: {.cell-output-display}\n![](SaiVenkateshChallenge5_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::",
    "supporting": [
      "SaiVenkateshChallenge5_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}