{
  "hash": "9338b4bbcdc8801d86f23d8ee0840fc2",
  "result": {
    "markdown": "---\ntitle: \"Challenge 2: Finding the Cattle Dairy Value statistics for each country from 1961 - 2018\"\nauthor: \"Shantanu Patil\"\ndescription: \"Data wrangling and Data Sumarization to find statistics in data\"\ndate: \"03/01/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_2\n  - faostat\n  - faostat_cattle_diary\n  - Shantanu Patil\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Read in the Data\nI have selected faostat_cattle_diary dataset to do my analysis on.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Importing the faostat_cattle_diary dataset and reading them\nlibrary(readr)\ndata <-read_csv(\"_data/FAOSTAT_cattle_dairy.csv\")\n#Lets see the first 3 rows of the dataset\nhead(data, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 14\n  Domai…¹ Domain Area …² Area  Eleme…³ Element Item …⁴ Item  Year …⁵  Year Unit \n  <chr>   <chr>    <dbl> <chr>   <dbl> <chr>     <dbl> <chr>   <dbl> <dbl> <chr>\n1 QL      Lives…       2 Afgh…    5318 Milk A…     882 Milk…    1961  1961 Head \n2 QL      Lives…       2 Afgh…    5420 Yield       882 Milk…    1961  1961 hg/An\n3 QL      Lives…       2 Afgh…    5510 Produc…     882 Milk…    1961  1961 tonn…\n# … with 3 more variables: Value <dbl>, Flag <chr>, `Flag Description` <chr>,\n#   and abbreviated variable names ¹​`Domain Code`, ²​`Area Code`,\n#   ³​`Element Code`, ⁴​`Item Code`, ⁵​`Year Code`\n```\n:::\n:::\n\n\n## Describe the data\n\nUsing R commands I am exploring the data and coming up with the description from the data.\nThe dataset contains 14 column, 8 of which have character datatype and 6 have integer data type.\nHere are the Columns\n\nchr (8): Domain Code, Domain, Area, Element, Item, Unit, Flag, Flag Description\n\ndbl (6): Area Code, Element Code, Item Code, Year Code, Year, Value\n\nHere is the size of the Dataset ---  Rows: 36449 Columns: 14  \n\n\n### Checking the variation in data for each column\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Check the variation in data for each column\nsummary(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Domain Code           Domain            Area Code          Area          \n Length:36449       Length:36449       Min.   :   1.0   Length:36449      \n Class :character   Class :character   1st Qu.:  69.0   Class :character  \n Mode  :character   Mode  :character   Median : 141.0   Mode  :character  \n                                       Mean   : 775.2                     \n                                       3rd Qu.: 215.0                     \n                                       Max.   :5504.0                     \n                                                                          \n  Element Code    Element            Item Code       Item          \n Min.   :5318   Length:36449       Min.   :882   Length:36449      \n 1st Qu.:5318   Class :character   1st Qu.:882   Class :character  \n Median :5420   Mode  :character   Median :882   Mode  :character  \n Mean   :5416                      Mean   :882                     \n 3rd Qu.:5510                      3rd Qu.:882                     \n Max.   :5510                      Max.   :882                     \n                                                                   \n   Year Code         Year          Unit               Value          \n Min.   :1961   Min.   :1961   Length:36449       Min.   :        7  \n 1st Qu.:1976   1st Qu.:1976   Class :character   1st Qu.:     7849  \n Median :1991   Median :1991   Mode  :character   Median :    43266  \n Mean   :1990   Mean   :1990                      Mean   :  4410235  \n 3rd Qu.:2005   3rd Qu.:2005                      3rd Qu.:   700000  \n Max.   :2018   Max.   :2018                      Max.   :683217055  \n                                                  NA's   :74         \n     Flag           Flag Description  \n Length:36449       Length:36449      \n Class :character   Class :character  \n Mode  :character   Mode  :character  \n                                      \n                                      \n                                      \n                                      \n```\n:::\n:::\n\n\n## Provide Grouped Summary Statistics\n\nConducting  exploratory data analysis, using dplyr commands such as `group_by()`, `select()`, `filter()`, and `summarise()`.\n\nRemove columns with \"Item Code\" values as it has constant value 882\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#install.packages(\"dplyr\")\nlibrary(dplyr)\n#remove columns with \"Item Code\" values as it has contant value 882\ndata<-data%>%\n  select(-contains(\"Item Code\"))\n```\n:::\n\n\nGrouping by the Area and finding the mean_value\n\n::: {.cell}\n\n```{.r .cell-code}\ndata %>% \n  group_by(Area) %>% \n  summarise(mean_value = mean(Value))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 232 × 2\n   Area                mean_value\n   <chr>                    <dbl>\n 1 Afghanistan            903662.\n 2 Africa               18861019.\n 3 Albania                275446.\n 4 Algeria                599219.\n 5 American Samoa           3611.\n 6 Americas             56060267.\n 7 Angola                 164004.\n 8 Antigua and Barbuda      6402.\n 9 Argentina             3279105.\n10 Armenia                276119.\n# … with 222 more rows\n```\n:::\n:::\n\n\nTable output by selecting Columns \"Area\", \"Year\", and \"Value\".\n\n::: {.cell}\n\n```{.r .cell-code}\ndata %>% \n  select(Area, Year, Value)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 36,449 × 3\n   Area         Year  Value\n   <chr>       <dbl>  <dbl>\n 1 Afghanistan  1961 700000\n 2 Afghanistan  1961   5000\n 3 Afghanistan  1961 350000\n 4 Afghanistan  1962 700000\n 5 Afghanistan  1962   5000\n 6 Afghanistan  1962 350000\n 7 Afghanistan  1963 780000\n 8 Afghanistan  1963   5128\n 9 Afghanistan  1963 400000\n10 Afghanistan  1964 780000\n# … with 36,439 more rows\n```\n:::\n:::\n\n\nI wanted to check out how any data rows / points are available for Antigua and Barbuda in the year of 1975. There are 3 datapoints available.\n\n::: {.cell}\n\n```{.r .cell-code}\ndata %>% \n  filter(Area == \"Antigua and Barbuda\" , Year == 1975)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 13\n  Domain …¹ Domain Area …² Area  Eleme…³ Element Item  Year …⁴  Year Unit  Value\n  <chr>     <chr>    <dbl> <chr>   <dbl> <chr>   <chr>   <dbl> <dbl> <chr> <dbl>\n1 QL        Lives…       8 Anti…    5318 Milk A… Milk…    1975  1975 Head   3100\n2 QL        Lives…       8 Anti…    5420 Yield   Milk…    1975  1975 hg/An 10645\n3 QL        Lives…       8 Anti…    5510 Produc… Milk…    1975  1975 tonn…  3300\n# … with 2 more variables: Flag <chr>, `Flag Description` <chr>, and\n#   abbreviated variable names ¹​`Domain Code`, ²​`Area Code`, ³​`Element Code`,\n#   ⁴​`Year Code`\n```\n:::\n:::\n\n\n\n## Table Value Statistics\nFind the central tendency (mean, median, mode) and dispersion (standard deviation, mix/max/quantile) for Value within the data set.\n\n::: {.cell}\n\n```{.r .cell-code}\n#deleting the rows with Null values\ndata2 <- na.omit(data)\n# Find the central tendency (mean, median, mode) and dispersion (standard deviation, mix/max/quantile) for different subgroups within the data set.\ndata2%>%\n  group_by(Area)%>%\n  summarize(mean.Value = mean(Value, na.rm = TRUE), median.Value = median(Value, na.rm = TRUE), min.Value = min(Value, na.rm = TRUE), max.Value = max(Value, na.rm = TRUE), sd.Value = sd(Value, na.rm = TRUE), var.Value = var(Value, na.rm = TRUE), IQR.Value = IQR(Value, na.rm = TRUE))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 231 × 8\n   Area                mean.Va…¹ media…² min.V…³ max.V…⁴ sd.Va…⁵ var.V…⁶ IQR.V…⁷\n   <chr>                   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>\n 1 Afghanistan           873703.  5.56e5    3592  4.05e6  1.07e6 1.14e12  1.19e6\n 2 Africa              18861019.  1.51e7    4311  7.13e7  1.93e7 3.73e14  3.11e7\n 3 Albania                88480.  2.53e4    6350  3.24e5  9.90e4 9.81e 9  1.52e5\n 4 Algeria               277666.  1.92e5    6008  1.09e6  2.92e5 8.52e10  5.28e5\n 5 American Samoa          3652.  3.15e1      16  1.38e4  5.37e3 2.88e 7  7.98e3\n 6 Americas            56060267.  4.51e7   22342  1.84e8  5.50e7 3.03e15  9.12e7\n 7 Angola                164317.  1.57e5    4800  4.36e5  1.36e5 1.85e10  2.8 e5\n 8 Antigua and Barbuda     6414.  6.2 e3    2300  1.06e4  2.67e3 7.15e 6  5.64e3\n 9 Argentina            1242484.  5.80e4   16980  8.1 e6  1.40e6 1.95e12  2.37e6\n10 Armenia                47702.  1.95e4   14937  4.44e5  1.08e5 1.18e10  3.45e3\n# … with 221 more rows, and abbreviated variable names ¹​mean.Value,\n#   ²​median.Value, ³​min.Value, ⁴​max.Value, ⁵​sd.Value, ⁶​var.Value, ⁷​IQR.Value\n```\n:::\n:::\n\nI wanted to check out how any data rows / points are available for Antigua and Barbuda in the year of 1975. There are 3 datapoints available.\nSome Conclusion from seeing the data summary\n\n1. The Data is Collected from the year 1961 - 2018\n2. The Item Code column just has one value 882\n3. The Area Code varies from 1 - 5504\n4. The Element Code varies frojm 5318 - 5510\n5. The Value Column has a lot of variance\n\nI deleted the Item Code Column.\n\nI choose Area (Country) as a group because I wanted to see how does the Value of output of cattle and diary farms vary based on teh country they are located in. I think every country has a set of climatic condition, thus the value in tropical countries might be far greater than countries near north pole, I wanted to test this hypothesis.\n\nI found out the relationship is not linear, on seeing the data I realized that some countries might be the around the same  distance from equator or have same climatic conditions but still the mean value out put varies. Ex Afghanistan and Africa may have somewhat same climatic conditions but as afganisatn is located i the mountains the mean Value is much lower compared to Africa.\n\n\n",
    "supporting": [
      "ShantanuPatil_challenge2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}