{
  "hash": "e114f66352768770e7065f4743ecbf10",
  "result": {
    "markdown": "---\ntitle: \"Challenge 2\"\nauthor: \"Linda Humphrey\"\ndescription: \"Reading in data and creating a post\"\ndate: \"03/01/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_1: hotel_bookings.csv\n  - my name: Linda Humphrey\n  - dataset: hotel_bookings.csv\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(readxl)\nlibrary(lubridate)\nlibrary(psych)\nlibrary(DT)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Challenge Overview\n\nToday's challenge is to\n\n1)  read in a data set, and describe the data using both words and any supporting information (e.g., tables, etc)\n2)  provide summary statistics for different interesting groups within the data, and interpret those statistics\n\n## Read in the Data\n\nRead in one (or more) of the following data sets, available in the `posts/_data` folder, using the correct R package and command.\n\n-   railroad\\*.csv or StateCounty2012.xls ⭐\n-   FAOstat\\*.csv or birds.csv ⭐⭐⭐\n-   hotel_bookings.csv ⭐⭐⭐⭐\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Exploring hotel_bookings data\nlibrary(readr)\ndataset<- read_csv(\"~/Desktop/Dacss601_spring2023/posts/_data/hotel_bookings.csv\") \n\n#View data structure\n\nstr(dataset)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nspc_tbl_ [119,390 × 32] (S3: spec_tbl_df/tbl_df/tbl/data.frame)\n $ hotel                         : chr [1:119390] \"Resort Hotel\" \"Resort Hotel\" \"Resort Hotel\" \"Resort Hotel\" ...\n $ is_canceled                   : num [1:119390] 0 0 0 0 0 0 0 0 1 1 ...\n $ lead_time                     : num [1:119390] 342 737 7 13 14 14 0 9 85 75 ...\n $ arrival_date_year             : num [1:119390] 2015 2015 2015 2015 2015 ...\n $ arrival_date_month            : chr [1:119390] \"July\" \"July\" \"July\" \"July\" ...\n $ arrival_date_week_number      : num [1:119390] 27 27 27 27 27 27 27 27 27 27 ...\n $ arrival_date_day_of_month     : num [1:119390] 1 1 1 1 1 1 1 1 1 1 ...\n $ stays_in_weekend_nights       : num [1:119390] 0 0 0 0 0 0 0 0 0 0 ...\n $ stays_in_week_nights          : num [1:119390] 0 0 1 1 2 2 2 2 3 3 ...\n $ adults                        : num [1:119390] 2 2 1 1 2 2 2 2 2 2 ...\n $ children                      : num [1:119390] 0 0 0 0 0 0 0 0 0 0 ...\n $ babies                        : num [1:119390] 0 0 0 0 0 0 0 0 0 0 ...\n $ meal                          : chr [1:119390] \"BB\" \"BB\" \"BB\" \"BB\" ...\n $ country                       : chr [1:119390] \"PRT\" \"PRT\" \"GBR\" \"GBR\" ...\n $ market_segment                : chr [1:119390] \"Direct\" \"Direct\" \"Direct\" \"Corporate\" ...\n $ distribution_channel          : chr [1:119390] \"Direct\" \"Direct\" \"Direct\" \"Corporate\" ...\n $ is_repeated_guest             : num [1:119390] 0 0 0 0 0 0 0 0 0 0 ...\n $ previous_cancellations        : num [1:119390] 0 0 0 0 0 0 0 0 0 0 ...\n $ previous_bookings_not_canceled: num [1:119390] 0 0 0 0 0 0 0 0 0 0 ...\n $ reserved_room_type            : chr [1:119390] \"C\" \"C\" \"A\" \"A\" ...\n $ assigned_room_type            : chr [1:119390] \"C\" \"C\" \"C\" \"A\" ...\n $ booking_changes               : num [1:119390] 3 4 0 0 0 0 0 0 0 0 ...\n $ deposit_type                  : chr [1:119390] \"No Deposit\" \"No Deposit\" \"No Deposit\" \"No Deposit\" ...\n $ agent                         : chr [1:119390] \"NULL\" \"NULL\" \"NULL\" \"304\" ...\n $ company                       : chr [1:119390] \"NULL\" \"NULL\" \"NULL\" \"NULL\" ...\n $ days_in_waiting_list          : num [1:119390] 0 0 0 0 0 0 0 0 0 0 ...\n $ customer_type                 : chr [1:119390] \"Transient\" \"Transient\" \"Transient\" \"Transient\" ...\n $ adr                           : num [1:119390] 0 0 75 75 98 ...\n $ required_car_parking_spaces   : num [1:119390] 0 0 0 0 0 0 0 0 0 0 ...\n $ total_of_special_requests     : num [1:119390] 0 0 0 0 1 1 0 1 1 0 ...\n $ reservation_status            : chr [1:119390] \"Check-Out\" \"Check-Out\" \"Check-Out\" \"Check-Out\" ...\n $ reservation_status_date       : Date[1:119390], format: \"2015-07-01\" \"2015-07-01\" ...\n - attr(*, \"spec\")=\n  .. cols(\n  ..   hotel = col_character(),\n  ..   is_canceled = col_double(),\n  ..   lead_time = col_double(),\n  ..   arrival_date_year = col_double(),\n  ..   arrival_date_month = col_character(),\n  ..   arrival_date_week_number = col_double(),\n  ..   arrival_date_day_of_month = col_double(),\n  ..   stays_in_weekend_nights = col_double(),\n  ..   stays_in_week_nights = col_double(),\n  ..   adults = col_double(),\n  ..   children = col_double(),\n  ..   babies = col_double(),\n  ..   meal = col_character(),\n  ..   country = col_character(),\n  ..   market_segment = col_character(),\n  ..   distribution_channel = col_character(),\n  ..   is_repeated_guest = col_double(),\n  ..   previous_cancellations = col_double(),\n  ..   previous_bookings_not_canceled = col_double(),\n  ..   reserved_room_type = col_character(),\n  ..   assigned_room_type = col_character(),\n  ..   booking_changes = col_double(),\n  ..   deposit_type = col_character(),\n  ..   agent = col_character(),\n  ..   company = col_character(),\n  ..   days_in_waiting_list = col_double(),\n  ..   customer_type = col_character(),\n  ..   adr = col_double(),\n  ..   required_car_parking_spaces = col_double(),\n  ..   total_of_special_requests = col_double(),\n  ..   reservation_status = col_character(),\n  ..   reservation_status_date = col_date(format = \"\")\n  .. )\n - attr(*, \"problems\")=<externalptr> \n```\n:::\n:::\n\n\n\nAdd any comments or documentation as needed. More challenging data may require additional code chunks and documentation.\n\n## Describe the data\n\nUsing a combination of words and results of R commands, can you provide a high level description of the data? Describe as efficiently as possible where/how the data was (likely) gathered, indicate the cases and variables (both the interpretation and any details you deem useful to the reader to fully understand your chosen data).\n* Data gathered was an analysis of hotel bookings from 2015 to 2017\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readr)\ndataset<- read_csv(\"~/Desktop/Dacss601_spring2023/posts/_data/hotel_bookings.csv\") \n# Finding summary statistics for 'adults'\n\nsummary(dataset$adults)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  0.000   2.000   2.000   1.856   2.000  55.000 \n```\n:::\n:::\n\n*This data describes demand data for two different types of hotels, with 31 variables describing 40,060 observations and 79,330 observations.*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readr)\ndataset<- read_csv(\"~/Desktop/Dacss601_spring2023/posts/_data/hotel_bookings.csv\") \n# Calculating the summary of the dataset\n\nsummary(dataset)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    hotel            is_canceled       lead_time   arrival_date_year\n Length:119390      Min.   :0.0000   Min.   :  0   Min.   :2015     \n Class :character   1st Qu.:0.0000   1st Qu.: 18   1st Qu.:2016     \n Mode  :character   Median :0.0000   Median : 69   Median :2016     \n                    Mean   :0.3704   Mean   :104   Mean   :2016     \n                    3rd Qu.:1.0000   3rd Qu.:160   3rd Qu.:2017     \n                    Max.   :1.0000   Max.   :737   Max.   :2017     \n                                                                    \n arrival_date_month arrival_date_week_number arrival_date_day_of_month\n Length:119390      Min.   : 1.00            Min.   : 1.0             \n Class :character   1st Qu.:16.00            1st Qu.: 8.0             \n Mode  :character   Median :28.00            Median :16.0             \n                    Mean   :27.17            Mean   :15.8             \n                    3rd Qu.:38.00            3rd Qu.:23.0             \n                    Max.   :53.00            Max.   :31.0             \n                                                                      \n stays_in_weekend_nights stays_in_week_nights     adults      \n Min.   : 0.0000         Min.   : 0.0         Min.   : 0.000  \n 1st Qu.: 0.0000         1st Qu.: 1.0         1st Qu.: 2.000  \n Median : 1.0000         Median : 2.0         Median : 2.000  \n Mean   : 0.9276         Mean   : 2.5         Mean   : 1.856  \n 3rd Qu.: 2.0000         3rd Qu.: 3.0         3rd Qu.: 2.000  \n Max.   :19.0000         Max.   :50.0         Max.   :55.000  \n                                                              \n    children           babies              meal             country         \n Min.   : 0.0000   Min.   : 0.000000   Length:119390      Length:119390     \n 1st Qu.: 0.0000   1st Qu.: 0.000000   Class :character   Class :character  \n Median : 0.0000   Median : 0.000000   Mode  :character   Mode  :character  \n Mean   : 0.1039   Mean   : 0.007949                                        \n 3rd Qu.: 0.0000   3rd Qu.: 0.000000                                        \n Max.   :10.0000   Max.   :10.000000                                        \n NA's   :4                                                                  \n market_segment     distribution_channel is_repeated_guest\n Length:119390      Length:119390        Min.   :0.00000  \n Class :character   Class :character     1st Qu.:0.00000  \n Mode  :character   Mode  :character     Median :0.00000  \n                                         Mean   :0.03191  \n                                         3rd Qu.:0.00000  \n                                         Max.   :1.00000  \n                                                          \n previous_cancellations previous_bookings_not_canceled reserved_room_type\n Min.   : 0.00000       Min.   : 0.0000                Length:119390     \n 1st Qu.: 0.00000       1st Qu.: 0.0000                Class :character  \n Median : 0.00000       Median : 0.0000                Mode  :character  \n Mean   : 0.08712       Mean   : 0.1371                                  \n 3rd Qu.: 0.00000       3rd Qu.: 0.0000                                  \n Max.   :26.00000       Max.   :72.0000                                  \n                                                                         \n assigned_room_type booking_changes   deposit_type          agent          \n Length:119390      Min.   : 0.0000   Length:119390      Length:119390     \n Class :character   1st Qu.: 0.0000   Class :character   Class :character  \n Mode  :character   Median : 0.0000   Mode  :character   Mode  :character  \n                    Mean   : 0.2211                                        \n                    3rd Qu.: 0.0000                                        \n                    Max.   :21.0000                                        \n                                                                           \n   company          days_in_waiting_list customer_type           adr         \n Length:119390      Min.   :  0.000      Length:119390      Min.   :  -6.38  \n Class :character   1st Qu.:  0.000      Class :character   1st Qu.:  69.29  \n Mode  :character   Median :  0.000      Mode  :character   Median :  94.58  \n                    Mean   :  2.321                         Mean   : 101.83  \n                    3rd Qu.:  0.000                         3rd Qu.: 126.00  \n                    Max.   :391.000                         Max.   :5400.00  \n                                                                             \n required_car_parking_spaces total_of_special_requests reservation_status\n Min.   :0.00000             Min.   :0.0000            Length:119390     \n 1st Qu.:0.00000             1st Qu.:0.0000            Class :character  \n Median :0.00000             Median :0.0000            Mode  :character  \n Mean   :0.06252             Mean   :0.5714                              \n 3rd Qu.:0.00000             3rd Qu.:1.0000                              \n Max.   :8.00000             Max.   :5.0000                              \n                                                                         \n reservation_status_date\n Min.   :2014-10-17     \n 1st Qu.:2016-02-01     \n Median :2016-08-07     \n Mean   :2016-07-30     \n 3rd Qu.:2017-02-08     \n Max.   :2017-09-14     \n                        \n```\n:::\n:::\n\n*The above data is calculating summary of the Hotel_bookings dataset.*\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readr)\ndataset<- read_csv(\"~/Desktop/Dacss601_spring2023/posts/_data/hotel_bookings.csv\") \n# Calculating null value count for all columns\n\ncolSums(is.na(dataset))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                         hotel                    is_canceled \n                             0                              0 \n                     lead_time              arrival_date_year \n                             0                              0 \n            arrival_date_month       arrival_date_week_number \n                             0                              0 \n     arrival_date_day_of_month        stays_in_weekend_nights \n                             0                              0 \n          stays_in_week_nights                         adults \n                             0                              0 \n                      children                         babies \n                             4                              0 \n                          meal                        country \n                             0                              0 \n                market_segment           distribution_channel \n                             0                              0 \n             is_repeated_guest         previous_cancellations \n                             0                              0 \nprevious_bookings_not_canceled             reserved_room_type \n                             0                              0 \n            assigned_room_type                booking_changes \n                             0                              0 \n                  deposit_type                          agent \n                             0                              0 \n                       company           days_in_waiting_list \n                             0                              0 \n                 customer_type                            adr \n                             0                              0 \n   required_car_parking_spaces      total_of_special_requests \n                             0                              0 \n            reservation_status        reservation_status_date \n                             0                              0 \n```\n:::\n:::\n\n*The above data is calculating null value count for all columns.*\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readr)\ndataset<- read_csv(\"~/Desktop/Dacss601_spring2023/posts/_data/hotel_bookings.csv\") \n# Generating a table for the first 100 rows in the dataset.\n\nknitr::kable(head(dataset,n = 100), \"pandoc\")\n```\n\n::: {.cell-output-display}\nhotel           is_canceled   lead_time   arrival_date_year  arrival_date_month    arrival_date_week_number   arrival_date_day_of_month   stays_in_weekend_nights   stays_in_week_nights   adults   children   babies  meal   country   market_segment   distribution_channel    is_repeated_guest   previous_cancellations   previous_bookings_not_canceled  reserved_room_type   assigned_room_type    booking_changes  deposit_type   agent   company    days_in_waiting_list  customer_type         adr   required_car_parking_spaces   total_of_special_requests  reservation_status   reservation_status_date \n-------------  ------------  ----------  ------------------  -------------------  -------------------------  --------------------------  ------------------------  ---------------------  -------  ---------  -------  -----  --------  ---------------  ---------------------  ------------------  -----------------------  -------------------------------  -------------------  -------------------  ----------------  -------------  ------  --------  ---------------------  ----------------  -------  ----------------------------  --------------------------  -------------------  ------------------------\nResort Hotel              0         342                2015  July                                        27                           1                         0                      0        2          0        0  BB     PRT       Direct           Direct                                  0                        0                                0  C                    C                                   3  No Deposit     NULL    NULL                          0  Transient            0.00                             0                           0  Check-Out            2015-07-01              \nResort Hotel              0         737                2015  July                                        27                           1                         0                      0        2          0        0  BB     PRT       Direct           Direct                                  0                        0                                0  C                    C                                   4  No Deposit     NULL    NULL                          0  Transient            0.00                             0                           0  Check-Out            2015-07-01              \nResort Hotel              0           7                2015  July                                        27                           1                         0                      1        1          0        0  BB     GBR       Direct           Direct                                  0                        0                                0  A                    C                                   0  No Deposit     NULL    NULL                          0  Transient           75.00                             0                           0  Check-Out            2015-07-02              \nResort Hotel              0          13                2015  July                                        27                           1                         0                      1        1          0        0  BB     GBR       Corporate        Corporate                               0                        0                                0  A                    A                                   0  No Deposit     304     NULL                          0  Transient           75.00                             0                           0  Check-Out            2015-07-02              \nResort Hotel              0          14                2015  July                                        27                           1                         0                      2        2          0        0  BB     GBR       Online TA        TA/TO                                   0                        0                                0  A                    A                                   0  No Deposit     240     NULL                          0  Transient           98.00                             0                           1  Check-Out            2015-07-03              \nResort Hotel              0          14                2015  July                                        27                           1                         0                      2        2          0        0  BB     GBR       Online TA        TA/TO                                   0                        0                                0  A                    A                                   0  No Deposit     240     NULL                          0  Transient           98.00                             0                           1  Check-Out            2015-07-03              \nResort Hotel              0           0                2015  July                                        27                           1                         0                      2        2          0        0  BB     PRT       Direct           Direct                                  0                        0                                0  C                    C                                   0  No Deposit     NULL    NULL                          0  Transient          107.00                             0                           0  Check-Out            2015-07-03              \nResort Hotel              0           9                2015  July                                        27                           1                         0                      2        2          0        0  FB     PRT       Direct           Direct                                  0                        0                                0  C                    C                                   0  No Deposit     303     NULL                          0  Transient          103.00                             0                           1  Check-Out            2015-07-03              \nResort Hotel              1          85                2015  July                                        27                           1                         0                      3        2          0        0  BB     PRT       Online TA        TA/TO                                   0                        0                                0  A                    A                                   0  No Deposit     240     NULL                          0  Transient           82.00                             0                           1  Canceled             2015-05-06              \nResort Hotel              1          75                2015  July                                        27                           1                         0                      3        2          0        0  HB     PRT       Offline TA/TO    TA/TO                                   0                        0                                0  D                    D                                   0  No Deposit     15      NULL                          0  Transient          105.50                             0                           0  Canceled             2015-04-22              \nResort Hotel              1          23                2015  July                                        27                           1                         0                      4        2          0        0  BB     PRT       Online TA        TA/TO                                   0                        0                                0  E                    E                                   0  No Deposit     240     NULL                          0  Transient          123.00                             0                           0  Canceled             2015-06-23              \nResort Hotel              0          35                2015  July                                        27                           1                         0                      4        2          0        0  HB     PRT       Online TA        TA/TO                                   0                        0                                0  D                    D                                   0  No Deposit     240     NULL                          0  Transient          145.00                             0                           0  Check-Out            2015-07-05              \nResort Hotel              0          68                2015  July                                        27                           1                         0                      4        2          0        0  BB     USA       Online TA        TA/TO                                   0                        0                                0  D                    E                                   0  No Deposit     240     NULL                          0  Transient           97.00                             0                           3  Check-Out            2015-07-05              \nResort Hotel              0          18                2015  July                                        27                           1                         0                      4        2          1        0  HB     ESP       Online TA        TA/TO                                   0                        0                                0  G                    G                                   1  No Deposit     241     NULL                          0  Transient          154.77                             0                           1  Check-Out            2015-07-05              \nResort Hotel              0          37                2015  July                                        27                           1                         0                      4        2          0        0  BB     PRT       Online TA        TA/TO                                   0                        0                                0  E                    E                                   0  No Deposit     241     NULL                          0  Transient           94.71                             0                           0  Check-Out            2015-07-05              \nResort Hotel              0          68                2015  July                                        27                           1                         0                      4        2          0        0  BB     IRL       Online TA        TA/TO                                   0                        0                                0  D                    E                                   0  No Deposit     240     NULL                          0  Transient           97.00                             0                           3  Check-Out            2015-07-05              \nResort Hotel              0          37                2015  July                                        27                           1                         0                      4        2          0        0  BB     PRT       Offline TA/TO    TA/TO                                   0                        0                                0  E                    E                                   0  No Deposit     8       NULL                          0  Contract            97.50                             0                           0  Check-Out            2015-07-05              \nResort Hotel              0          12                2015  July                                        27                           1                         0                      1        2          0        0  BB     IRL       Online TA        TA/TO                                   0                        0                                0  A                    E                                   0  No Deposit     240     NULL                          0  Transient           88.20                             0                           0  Check-Out            2015-07-02              \nResort Hotel              0           0                2015  July                                        27                           1                         0                      1        2          0        0  BB     FRA       Corporate        Corporate                               0                        0                                0  A                    G                                   0  No Deposit     NULL    110                           0  Transient          107.42                             0                           0  Check-Out            2015-07-02              \nResort Hotel              0           7                2015  July                                        27                           1                         0                      4        2          0        0  BB     GBR       Direct           Direct                                  0                        0                                0  G                    G                                   0  No Deposit     250     NULL                          0  Transient          153.00                             0                           1  Check-Out            2015-07-05              \nResort Hotel              0          37                2015  July                                        27                           1                         1                      4        1          0        0  BB     GBR       Online TA        TA/TO                                   0                        0                                0  F                    F                                   0  No Deposit     241     NULL                          0  Transient           97.29                             0                           1  Check-Out            2015-07-06              \nResort Hotel              0          72                2015  July                                        27                           1                         2                      4        2          0        0  BB     PRT       Direct           Direct                                  0                        0                                0  A                    A                                   1  No Deposit     250     NULL                          0  Transient           84.67                             0                           1  Check-Out            2015-07-07              \nResort Hotel              0          72                2015  July                                        27                           1                         2                      4        2          0        0  BB     PRT       Direct           Direct                                  0                        0                                0  A                    A                                   1  No Deposit     250     NULL                          0  Transient           84.67                             0                           1  Check-Out            2015-07-07              \nResort Hotel              0          72                2015  July                                        27                           1                         2                      4        2          0        0  BB     PRT       Direct           Direct                                  0                        0                                0  D                    D                                   1  No Deposit     250     NULL                          0  Transient           99.67                             0                           1  Check-Out            2015-07-07              \nResort Hotel              0         127                2015  July                                        27                           1                         2                      5        2          0        0  HB     GBR       Offline TA/TO    TA/TO                                   0                        0                                0  D                    I                                   0  No Deposit     115     NULL                          0  Contract            94.95                             0                           1  Check-Out            2015-07-01              \nResort Hotel              0          78                2015  July                                        27                           1                         2                      5        2          0        0  BB     PRT       Offline TA/TO    TA/TO                                   0                        0                                0  D                    D                                   0  No Deposit     5       NULL                          0  Transient           63.60                             1                           0  Check-Out            2015-07-08              \nResort Hotel              0          48                2015  July                                        27                           1                         2                      5        2          0        0  BB     IRL       Offline TA/TO    TA/TO                                   0                        0                                0  D                    D                                   0  No Deposit     8       NULL                          0  Contract            79.50                             0                           0  Check-Out            2015-07-08              \nResort Hotel              1          60                2015  July                                        27                           1                         2                      5        2          0        0  BB     PRT       Online TA        TA/TO                                   0                        0                                0  E                    E                                   0  No Deposit     240     NULL                          0  Transient          107.00                             0                           2  Canceled             2015-05-11              \nResort Hotel              0          77                2015  July                                        27                           1                         2                      5        2          0        0  BB     PRT       Online TA        TA/TO                                   0                        0                                0  A                    A                                   0  No Deposit     240     NULL                          0  Transient           94.00                             0                           0  Check-Out            2015-07-08              \nResort Hotel              0          99                2015  July                                        27                           1                         2                      5        2          0        0  BB     PRT       Online TA        TA/TO                                   0                        0                                0  D                    D                                   0  No Deposit     240     NULL                          0  Transient           87.30                             1                           1  Check-Out            2015-07-08              \nResort Hotel              0         118                2015  July                                        27                           1                         4                     10        1          0        0  BB     NULL      Direct           Direct                                  0                        0                                0  A                    A                                   2  No Deposit     NULL    NULL                          0  Transient           62.00                             0                           2  Check-Out            2015-07-15              \nResort Hotel              0          95                2015  July                                        27                           1                         4                     11        2          0        0  BB     GBR       Offline TA/TO    TA/TO                                   0                        0                                0  D                    D                                   0  No Deposit     241     NULL                          0  Transient           63.86                             0                           0  Check-Out            2015-07-16              \nResort Hotel              1          96                2015  July                                        27                           1                         2                      8        2          0        0  BB     PRT       Direct           Direct                                  0                        0                                0  E                    E                                   0  No Deposit     NULL    NULL                          0  Transient          108.30                             0                           2  Canceled             2015-05-29              \nResort Hotel              0          69                2015  July                                        27                           2                         2                      4        2          0        0  BB     IRL       Offline TA/TO    TA/TO                                   0                        0                                0  A                    C                                   0  No Deposit     175     NULL                          0  Transient           65.50                             0                           0  Check-Out            2015-07-08              \nResort Hotel              1          45                2015  July                                        27                           2                         1                      3        3          0        0  BB     PRT       Online TA        TA/TO                                   0                        0                                0  D                    D                                   0  No Deposit     241     NULL                          0  Transient          108.80                             0                           1  Canceled             2015-05-19              \nResort Hotel              1          40                2015  July                                        27                           2                         1                      3        3          0        0  BB     PRT       Online TA        TA/TO                                   0                        0                                0  D                    D                                   0  No Deposit     241     NULL                          0  Transient          108.80                             0                           1  Canceled             2015-06-19              \nResort Hotel              0          15                2015  July                                        27                           2                         1                      3        2          0        0  BB     ESP       Online TA        TA/TO                                   0                        0                                0  A                    C                                   0  No Deposit     240     NULL                          0  Transient           98.00                             0                           0  Check-Out            2015-07-06              \nResort Hotel              0          36                2015  July                                        27                           2                         1                      3        3          0        0  BB     PRT       Online TA        TA/TO                                   0                        0                                0  D                    D                                   0  No Deposit     241     NULL                          0  Transient          108.80                             0                           1  Check-Out            2015-07-06              \nResort Hotel              1          43                2015  July                                        27                           2                         1                      3        3          0        0  BB     PRT       Online TA        TA/TO                                   0                        0                                0  D                    D                                   0  No Deposit     241     NULL                          0  Transient          108.80                             0                           0  Canceled             2015-05-23              \nResort Hotel              0          70                2015  July                                        27                           2                         2                      3        2          0        0  HB     ROU       Direct           Direct                                  0                        0                                0  E                    E                                   0  No Deposit     250     NULL                          0  Transient          137.00                             0                           1  Check-Out            2015-07-07              \nResort Hotel              1          45                2015  July                                        27                           2                         2                      3        2          0        0  BB     PRT       Online TA        TA/TO                                   0                        0                                0  G                    G                                   0  No Deposit     241     NULL                          0  Transient          117.81                             0                           0  Canceled             2015-05-18              \nResort Hotel              0          45                2015  July                                        27                           2                         2                      3        2          0        0  BB     IRL       Offline TA/TO    TA/TO                                   0                        0                                0  D                    D                                   0  No Deposit     8       NULL                          0  Contract            79.50                             0                           0  Check-Out            2015-07-07              \nResort Hotel              0          16                2015  July                                        27                           2                         2                      3        2          0        0  BB     ESP       Direct           Direct                                  0                        0                                0  F                    F                                   0  No Deposit     NULL    NULL                          0  Transient          123.00                             0                           0  Check-Out            2015-07-07              \nResort Hotel              0          70                2015  July                                        27                           2                         2                      3        2          0        0  HB     ROU       Direct           Direct                                  0                        0                                0  E                    E                                   0  No Deposit     250     NULL                          0  Transient          137.00                             0                           1  Check-Out            2015-07-07              \nResort Hotel              0         107                2015  July                                        27                           2                         2                      5        2          0        0  BB     PRT       Online TA        TA/TO                                   0                        0                                0  A                    A                                   0  No Deposit     240     NULL                          0  Transient          110.70                             0                           2  Check-Out            2015-07-09              \nResort Hotel              1          47                2015  July                                        27                           2                         2                      5        2          2        0  BB     PRT       Online TA        TA/TO                                   0                        0                                0  G                    G                                   0  No Deposit     240     NULL                          0  Transient          153.00                             0                           0  Canceled             2015-06-02              \nResort Hotel              0          96                2015  July                                        27                           2                         2                      5        2          0        0  BB     ESP       Offline TA/TO    TA/TO                                   0                        0                                0  A                    A                                   0  No Deposit     134     NULL                          0  Transient           58.95                             0                           1  Check-Out            2015-07-09              \nResort Hotel              0         113                2015  July                                        27                           2                         2                      5        2          0        0  BB     NOR       Offline TA/TO    TA/TO                                   0                        0                                0  E                    E                                   0  No Deposit     156     NULL                          0  Transient-Party     82.88                             0                           2  Check-Out            2015-07-09              \nResort Hotel              0          90                2015  July                                        27                           2                         2                      5        2          0        0  HB     GBR       Offline TA/TO    TA/TO                                   0                        0                                0  A                    B                                   1  No Deposit     243     NULL                          0  Contract            82.35                             0                           0  Check-Out            2015-07-09              \nResort Hotel              0          50                2015  July                                        27                           2                         2                      5        2          0        0  HB     IRL       Online TA        TA/TO                                   0                        0                                0  E                    F                                   1  No Deposit     241     NULL                          0  Transient          119.35                             0                           1  Check-Out            2015-07-09              \nResort Hotel              0         113                2015  July                                        27                           2                         2                      5        2          0        0  BB     NOR       Offline TA/TO    TA/TO                                   0                        0                                0  D                    D                                   0  No Deposit     156     NULL                          0  Transient-Party     67.58                             0                           2  Check-Out            2015-07-09              \nResort Hotel              0          93                2015  July                                        27                           2                         3                      8        2          0        0  BB     IRL       Offline TA/TO    TA/TO                                   0                        0                                0  A                    A                                   0  No Deposit     156     NULL                          0  Contract            56.01                             0                           0  Check-Out            2015-07-13              \nResort Hotel              0          76                2015  July                                        27                           2                         4                     10        2          0        0  BB     OMN       Offline TA/TO    TA/TO                                   0                        0                                0  D                    D                                   0  No Deposit     243     NULL                          0  Contract           110.70                             0                           0  Check-Out            2015-07-16              \nResort Hotel              0           3                2015  July                                        27                           2                         0                      1        2          0        0  BB     ESP       Online TA        TA/TO                                   0                        0                                0  A                    C                                   0  No Deposit     240     NULL                          0  Transient           88.20                             1                           0  Check-Out            2015-07-03              \nResort Hotel              0           1                2015  July                                        27                           2                         0                      1        2          0        0  BB     ARG       Online TA        TA/TO                                   0                        0                                0  H                    H                                   0  No Deposit     240     NULL                          0  Transient          147.00                             1                           0  Check-Out            2015-07-03              \nResort Hotel              0           1                2015  July                                        27                           2                         0                      1        2          2        0  BB     ESP       Direct           Direct                                  0                        0                                0  C                    C                                   0  No Deposit     NULL    NULL                          0  Transient          107.00                             1                           2  Check-Out            2015-07-03              \nResort Hotel              0           0                2015  July                                        27                           2                         0                      1        2          0        0  BB     PRT       Direct           Direct                                  0                        0                                0  H                    H                                   0  No Deposit     NULL    NULL                          0  Transient          147.00                             0                           0  Check-Out            2015-07-03              \nResort Hotel              0           0                2015  July                                        27                           2                         0                      1        2          0        0  BB     PRT       Online TA        TA/TO                                   0                        0                                0  A                    D                                   0  No Deposit     240     NULL                          0  Transient          117.90                             0                           2  Check-Out            2015-07-03              \nResort Hotel              0           0                2015  July                                        27                           2                         0                      1        2          0        0  BB     PRT       Direct           Direct                                  0                        0                                0  G                    G                                   0  No Deposit     NULL    NULL                          0  Transient          123.00                             0                           0  Check-Out            2015-07-03              \nResort Hotel              0          14                2015  July                                        27                           2                         0                      2        2          0        0  BB     USA       Online TA        TA/TO                                   0                        0                                0  A                    C                                   0  No Deposit     242     NULL                          0  Transient           98.00                             0                           1  Check-Out            2015-07-04              \nResort Hotel              0          10                2015  July                                        27                           2                         0                      2        2          0        0  BB     PRT       Online TA        TA/TO                                   0                        0                                0  G                    G                                   0  No Deposit     241     NULL                          0  Transient          117.81                             0                           0  Check-Out            2015-07-04              \nResort Hotel              0           5                2015  July                                        27                           2                         0                      2        2          0        0  BB     IRL       Online TA        TA/TO                                   0                        0                                0  E                    E                                   0  No Deposit     240     NULL                          0  Transient          135.00                             1                           2  Check-Out            2015-07-04              \nResort Hotel              0          17                2015  July                                        27                           2                         0                      3        2          0        0  BB     ESP       Direct           Direct                                  0                        0                                0  F                    F                                   0  No Deposit     250     NULL                          0  Transient          133.00                             0                           1  Check-Out            2015-07-05              \nResort Hotel              0          93                2015  July                                        27                           2                         0                      3        2          0        0  BB     IRL       Offline TA/TO    TA/TO                                   0                        0                                0  A                    C                                   0  No Deposit     115     NULL                          0  Contract            58.95                             0                           0  Check-Out            2015-07-05              \nResort Hotel              1           3                2015  July                                        27                           2                         0                      3        2          0        0  HB     PRT       Online TA        TA/TO                                   0                        0                                0  A                    A                                   0  No Deposit     240     NULL                          0  Transient          136.33                             0                           2  Canceled             2015-06-29              \nResort Hotel              0          10                2015  July                                        27                           3                         0                      2        2          2        0  BB     USA       Online TA        TA/TO                                   0                        0                                0  G                    H                                   0  No Deposit     240     NULL                          0  Transient          153.00                             1                           0  Check-Out            2015-07-05              \nResort Hotel              0           3                2015  July                                        27                           3                         0                      2        2          0        0  BB     ESP       Online TA        TA/TO                                   0                        0                                0  A                    C                                   0  No Deposit     240     NULL                          0  Transient          110.50                             0                           0  Check-Out            2015-07-05              \nResort Hotel              0          51                2015  July                                        27                           3                         0                      2        2          0        0  BB     POL       Online TA        TA/TO                                   0                        0                                0  D                    D                                   0  No Deposit     242     NULL                          0  Transient           97.00                             0                           0  Check-Out            2015-07-05              \nResort Hotel              1          71                2015  July                                        27                           3                         0                      2        3          0        0  BB     PRT       Offline TA/TO    TA/TO                                   0                        0                                0  A                    A                                   0  No Deposit     242     NULL                          0  Transient          110.30                             0                           2  Canceled             2015-06-16              \nResort Hotel              1          63                2015  July                                        27                           3                         0                      2        2          0        0  BB     PRT       Online TA        TA/TO                                   0                        0                                0  A                    A                                   0  No Deposit     240     NULL                          0  Transient           82.00                             0                           2  Canceled             2015-06-18              \nResort Hotel              1          62                2015  July                                        27                           3                         0                      2        2          0        0  BB     PRT       Online TA        TA/TO                                   0                        0                                0  D                    D                                   0  No Deposit     240     NULL                          0  Transient           97.00                             0                           1  Canceled             2015-07-03              \nResort Hotel              1         101                2015  July                                        27                           3                         0                      2        2          0        0  BB     PRT       Online TA        TA/TO                                   0                        0                                0  A                    A                                   0  No Deposit     240     NULL                          0  Transient           73.80                             0                           1  Canceled             2015-06-12              \nResort Hotel              0           2                2015  July                                        27                           3                         0                      2        2          0        0  HB     PRT       Offline TA/TO    TA/TO                                   0                        0                                0  A                    A                                   0  No Deposit     3       NULL                          0  Transient           91.50                             0                           0  Check-Out            2015-07-05              \nResort Hotel              0          15                2015  July                                        27                           3                         0                      2        2          0        0  BB     ESP       Online TA        TA/TO                                   0                        0                                0  A                    A                                   0  No Deposit     240     NULL                          0  Transient          114.50                             0                           0  Check-Out            2015-07-05              \nResort Hotel              1          51                2015  July                                        27                           3                         0                      2        3          0        0  BB     PRT       Online TA        TA/TO                                   0                        0                                0  A                    A                                   0  No Deposit     242     NULL                          0  Transient          110.30                             0                           0  Canceled             2015-06-09              \nResort Hotel              0           3                2015  July                                        27                           3                         1                      2        2          0        0  BB     ESP       Online TA        TA/TO                                   0                        0                                0  A                    A                                   0  No Deposit     240     NULL                          0  Transient           90.90                             1                           0  Check-Out            2015-07-06              \nResort Hotel              1          48                2015  July                                        27                           3                         1                      2        2          0        0  BB     PRT       Online TA        TA/TO                                   0                        0                                0  E                    E                                   0  No Deposit     240     NULL                          0  Transient          123.00                             0                           0  Canceled             2015-05-26              \nResort Hotel              0           2                2015  July                                        27                           3                         2                      2        1          0        0  BB     PRT       Online TA        TA/TO                                   0                        0                                0  A                    A                                   0  No Deposit     240     NULL                          0  Transient          122.00                             0                           0  Check-Out            2015-07-07              \nResort Hotel              0          72                2015  July                                        27                           3                         2                      2        2          0        0  BB     DEU       Offline TA/TO    TA/TO                                   0                        0                                0  A                    A                                   0  No Deposit     105     NULL                          0  Transient          110.70                             1                           0  Check-Out            2015-07-07              \nResort Hotel              0          81                2015  July                                        27                           3                         2                      6        3          0        0  BB     PRT       Offline TA/TO    TA/TO                                   0                        0                                0  D                    D                                   0  No Deposit     5       NULL                          0  Transient           85.86                             0                           0  Check-Out            2015-07-11              \nResort Hotel              0          99                2015  July                                        27                           3                         2                      7        2          0        0  BB     FRA       Offline TA/TO    TA/TO                                   0                        0                                0  A                    A                                   0  No Deposit     40      NULL                          0  Contract            58.95                             0                           0  Check-Out            2015-07-12              \nResort Hotel              1         368                2015  July                                        27                           3                         3                      7        2          0        0  BB     PRT       Offline TA/TO    TA/TO                                   0                        0                                0  A                    A                                   0  No Deposit     40      NULL                          0  Contract            55.68                             0                           0  Canceled             2015-05-19              \nResort Hotel              0         364                2015  July                                        27                           3                         3                      7        2          0        0  BB     GBR       Offline TA/TO    TA/TO                                   0                        0                                0  A                    A                                   0  No Deposit     40      NULL                          0  Contract            55.68                             0                           0  Check-Out            2015-07-13              \nResort Hotel              1          81                2015  July                                        27                           3                         3                      7        2          0        0  HB     PRT       Direct           Direct                                  0                        0                                0  A                    A                                   2  No Deposit     250     NULL                          0  Transient          124.00                             0                           1  Canceled             2015-06-09              \nResort Hotel              0          99                2015  July                                        27                           3                         3                      7        2          0        0  HB     GBR       Offline TA/TO    TA/TO                                   0                        0                                0  E                    E                                   0  No Deposit     115     NULL                          0  Contract           111.15                             0                           0  Check-Out            2015-07-13              \nResort Hotel              0         324                2015  July                                        27                           3                         4                     10        2          0        0  HB     GBR       Offline TA/TO    TA/TO                                   0                        0                                0  E                    E                                   0  No Deposit     40      NULL                          0  Contract           134.73                             0                           0  Check-Out            2015-07-17              \nResort Hotel              0          69                2015  July                                        27                           3                         4                     10        2          0        0  BB     GBR       Online TA        TA/TO                                   0                        0                                0  F                    F                                   1  No Deposit     241     NULL                          0  Transient           92.45                             0                           1  Check-Out            2015-07-17              \nResort Hotel              1          79                2015  July                                        27                           3                         6                     15        2          1        0  BB     PRT       Offline TA/TO    TA/TO                                   0                        0                                0  A                    A                                   0  No Deposit     242     NULL                          0  Transient          108.73                             0                           2  Canceled             2015-04-15              \nResort Hotel              0          12                2015  July                                        27                           3                         0                      1        2          0        0  BB     GBR       Online TA        TA/TO                                   0                        0                                0  A                    C                                   0  No Deposit     240     NULL                          0  Transient           73.80                             0                           0  Check-Out            2015-07-04              \nResort Hotel              0           9                2015  July                                        27                           3                         0                      1        2          0        0  BB     PRT       Online TA        TA/TO                                   0                        0                                0  A                    C                                   0  No Deposit     240     NULL                          0  Transient           98.00                             1                           2  Check-Out            2015-07-04              \nResort Hotel              0           1                2015  July                                        27                           3                         0                      1        2          0        0  BB     ESP       Online TA        TA/TO                                   0                        0                                0  A                    C                                   0  No Deposit     240     NULL                          0  Transient          131.00                             0                           1  Check-Out            2015-07-04              \nResort Hotel              0          21                2015  July                                        27                           3                         0                      1        2          0        0  BB     PRT       Online TA        TA/TO                                   0                        0                                0  E                    E                                   0  No Deposit     240     NULL                          0  Transient          123.00                             0                           0  Check-Out            2015-07-04              \nResort Hotel              0           9                2015  July                                        27                           3                         0                      1        2          0        0  BB     USA       Online TA        TA/TO                                   0                        0                                0  C                    C                                   0  No Deposit     241     NULL                          0  Transient           94.71                             0                           0  Check-Out            2015-07-04              \nResort Hotel              0         109                2015  July                                        27                           3                         0                      1        2          0        0  BB     BEL       Online TA        TA/TO                                   0                        0                                0  A                    A                                   0  No Deposit     240     NULL                          0  Transient          123.00                             0                           2  Check-Out            2015-07-04              \nResort Hotel              1         109                2015  July                                        27                           3                         0                      2        2          0        0  BB     PRT       Online TA        TA/TO                                   0                        0                                0  A                    A                                   0  No Deposit     240     NULL                          0  Transient          123.00                             0                           1  Canceled             2015-05-26              \nResort Hotel              1          72                2015  July                                        27                           3                         0                      2        2          0        0  BB     PRT       Online TA        TA/TO                                   0                        0                                0  A                    A                                   0  No Deposit     240     NULL                          0  Transient           73.80                             0                           1  Canceled             2015-06-29              \nResort Hotel              1          63                2015  July                                        27                           3                         2                      5        2          0        0  BB     PRT       Online TA        TA/TO                                   0                        0                                0  F                    F                                   0  No Deposit     242     NULL                          0  Transient          117.00                             0                           1  Canceled             2015-05-13              \nResort Hotel              0          63                2015  July                                        27                           3                         2                      5        3          0        0  HB     ESP       Offline TA/TO    TA/TO                                   0                        0                                0  E                    E                                   0  No Deposit     105     NULL                          0  Transient          196.54                             0                           1  Check-Out            2015-07-10              \nResort Hotel              0         101                2015  July                                        27                           3                         2                      5        2          1        0  BB     PRT       Online TA        TA/TO                                   0                        0                                0  D                    D                                   0  No Deposit     240     NULL                          0  Transient           99.30                             1                           2  Check-Out            2015-07-10              \nResort Hotel              0         102                2015  July                                        27                           3                         2                      5        2          0        0  BB     DEU       Direct           Direct                                  0                        0                                0  E                    E                                   0  No Deposit     250     NULL                          0  Transient           90.95                             0                           0  Check-Out            2015-07-10\n:::\n:::\n\n*The above table shows the first 100 rows in the dataset.*\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readr)\ndataset<- read_csv(\"~/Desktop/Dacss601_spring2023/posts/_data/hotel_bookings.csv\") \n# Finding summary statistics for 'children'\n\nsummary(dataset$children)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n 0.0000  0.0000  0.0000  0.1039  0.0000 10.0000       4 \n```\n:::\n:::\n\n*The above shows the summary statistics of children column.*\n\n## Provide Grouped Summary Statistics\n\nConduct some exploratory data analysis, using dplyr commands such as `group_by()`, `select()`, `filter()`, and `summarise()`. Find the central tendency (mean, median, mode) and dispersion (standard deviation, mix/max/quantile) for different subgroups within the data set.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readr)\ndataset<- read_csv(\"~/Desktop/Dacss601_spring2023/posts/_data/hotel_bookings.csv\") \n# To show the distribution of the data\nmulti.hist(dataset[,sapply(dataset, is.numeric)])\n```\n\n::: {.cell-output-display}\n![](LindaHumphrey_challenge_2_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n*From the above histograms, August is the busiest month, with the most bookings in 2016 and the second half of the year.*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readr)\ndataset<- read_csv(\"~/Desktop/Dacss601_spring2023/posts/_data/hotel_bookings.csv\")\n# Room Summary\nroom_summary <- dataset %>%\n  filter(is_canceled == 0) %>% \n  group_by(reserved_room_type) %>%\n  summarize(room_count = n()) %>% \n  arrange(-room_count)\n\nknitr::kable(room_summary)\n```\n\n::: {.cell-output-display}\n|reserved_room_type | room_count|\n|:------------------|----------:|\n|A                  |      52364|\n|D                  |      13099|\n|E                  |       4621|\n|F                  |       2017|\n|G                  |       1331|\n|B                  |        750|\n|C                  |        624|\n|H                  |        356|\n|L                  |          4|\n:::\n:::\n\n*A is the most popular type of room, so the corporation should increase its number of type A rooms.*\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readr)\ndataset<- read_csv(\"~/Desktop/Dacss601_spring2023/posts/_data/hotel_bookings.csv\")\nggplot(dataset,aes(reserved_room_type,fill = (hotel))) +\n  geom_bar(position = 'dodge') +\n  ylab(\"Number Of Bookings\") +\n  xlab(\"Room Type\") +\n  ggtitle(\"Room Type Preferred\") +\n  labs(fill = 'Hotel Type')\n```\n\n::: {.cell-output-display}\n![](LindaHumphrey_challenge_2_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n*As the City Hotel generates the majority of bookings (66% of all reservations each year), which is far more than the resort hotel, the corporation may design strategies accordingly.\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readr)\ndataset<- read_csv(\"~/Desktop/Dacss601_spring2023/posts/_data/hotel_bookings.csv\")\n\n# country with the most Guests\ndata_country <- dataset %>% group_by(country) %>%  summarise(booking_count = n()) %>% arrange(desc(booking_count))\ntop_n(data_country,10,booking_count) %>% \n  ggplot(.,aes(country, booking_count)) +\n  geom_bar(stat = \"identity\", width = 0.25, fill =\"blue\")\n```\n\n::: {.cell-output-display}\n![](LindaHumphrey_challenge_2_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n*Summary of country with the most guest, we can see PRT has the highest rate of guests.*\n\n### Explain and Interpret\n\nBe sure to explain why you choose a specific group. Comment on the interpretation of any interesting differences between groups that you uncover. This section can be integrated with the exploratory data analysis, just be sure it is included.\n*The hotels' ultimate goal is to boost their earnings, therefore they want to comprehend and concentrate on everything that can do so.The most important details are that the City Hotel receives the majority of reservations and generates the majority of money, and that PRT.A is the most popular type of room. This helps the customer plan for more guests, make the necessary preparations, and conduct effective marketing..*\n",
    "supporting": [
      "LindaHumphrey_challenge_2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}