{
  "hash": "a10129f494d2a6fa770e6e072dc9b734",
  "result": {
    "markdown": "---\ntitle: \"Describing Railroad Dataset: New England vs the Intermountain West Region\"\nauthor: \"Dirichi Umunna\"\ndescription: \"Data wrangling: using group() and summarise()\"\ndate: \"08/16/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_2\n  - railroads\n  - faostat\n  - hotel_bookings\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Challenge Overview\n\nThis blog post aims to provide a descriptive analysis of the \"railroad\" dataset, which contains information on railroad employees across different states in the United States. We start by importing the data and generating an overview description, as well as creating visualizations to explore the dataset further. The focus of our analysis is to compare the number of railroad workers in the New England area of the United States with those in the Intermountain West Region. New England comprises of six states, namely Maine, Vermont, New Hampshire, Massachusetts, Rhode Island, and Connecticut, while the Intermountain West Region comprises of five states, including Colorado, Montana, Wyoming, Utah, and Nevada. By comparing the number of employees between these regions, we can gain insight into potential differences and identify areas for further investigation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#installing packages\nlibrary(tidyverse)\nlibrary(summarytools)\nlibrary(ggplot2)\n\n#using the readr package\nlibrary(readr)\nrrdata <- read.csv(\"/Users/dirichiumunna/Documents/DACS601/GITHUB/dacss601_spring2023/posts/_data/railroad_2012_clean_county.csv\")\n```\n:::\n\n\n## Describing the Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndfSummary(rrdata)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nData Frame Summary  \nrrdata  \nDimensions: 2930 x 3  \nDuplicates: 0  \n\n-----------------------------------------------------------------------------------------------------------------\nNo   Variable          Stats / Values             Freqs (% of Valid)    Graph                Valid      Missing  \n---- ----------------- -------------------------- --------------------- -------------------- ---------- ---------\n1    state             1. TX                       221 ( 7.5%)          I                    2930       0        \n     [character]       2. GA                       152 ( 5.2%)          I                    (100.0%)   (0.0%)   \n                       3. KY                       119 ( 4.1%)                                                   \n                       4. MO                       115 ( 3.9%)                                                   \n                       5. IL                       103 ( 3.5%)                                                   \n                       6. IA                        99 ( 3.4%)                                                   \n                       7. KS                        95 ( 3.2%)                                                   \n                       8. NC                        94 ( 3.2%)                                                   \n                       9. IN                        92 ( 3.1%)                                                   \n                       10. VA                       92 ( 3.1%)                                                   \n                       [ 43 others ]              1748 (59.7%)          IIIIIIIIIII                              \n\n2    county            1. WASHINGTON                31 ( 1.1%)                               2930       0        \n     [character]       2. JEFFERSON                 26 ( 0.9%)                               (100.0%)   (0.0%)   \n                       3. FRANKLIN                  24 ( 0.8%)                                                   \n                       4. LINCOLN                   24 ( 0.8%)                                                   \n                       5. JACKSON                   22 ( 0.8%)                                                   \n                       6. MADISON                   19 ( 0.6%)                                                   \n                       7. MONTGOMERY                18 ( 0.6%)                                                   \n                       8. CLAY                      17 ( 0.6%)                                                   \n                       9. MARION                    17 ( 0.6%)                                                   \n                       10. MONROE                   17 ( 0.6%)                                                   \n                       [ 1699 others ]            2715 (92.7%)          IIIIIIIIIIIIIIIIII                       \n\n3    total_employees   Mean (sd) : 87.2 (283.6)   404 distinct values   :                    2930       0        \n     [integer]         min < med < max:                                 :                    (100.0%)   (0.0%)   \n                       1 < 21 < 8207                                    :                                        \n                       IQR (CV) : 58 (3.3)                              :                                        \n                                                                        :                                        \n-----------------------------------------------------------------------------------------------------------------\n```\n:::\n\n```{.r .cell-code}\nhead(rrdata)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  state               county total_employees\n1    AE                  APO               2\n2    AK            ANCHORAGE               7\n3    AK FAIRBANKS NORTH STAR               2\n4    AK               JUNEAU               3\n5    AK    MATANUSKA-SUSITNA               2\n6    AK                SITKA               1\n```\n:::\n\n```{.r .cell-code}\ncolnames(rrdata)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"state\"           \"county\"          \"total_employees\"\n```\n:::\n:::\n\n\nBased on the provided information, it is clear that the dataset contains only three variables and a total of 2930 observations. The column labels suggest that the data pertains to railroad workers across various counties in the United States.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#we start by getting the mean and median employees nationwide.\nsummary(rrdata$total_employees)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   1.00    7.00   21.00   87.18   65.00 8207.00 \n```\n:::\n\n```{.r .cell-code}\n#Total number of employees\nsum(rrdata$total_employee)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 255432\n```\n:::\n:::\n\n\nFrom the above exploration we can see that the employee total us 255432, with a mean of 87 and a median of 21\n\n## Further Data Exploration\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a vector of New England states\nnew_england_states <- c(\"ME\", \"NH\", \"VT\", \"MA\", \"RI\", \"CT\")\n#create dataframe\nnew_england_data <- rrdata %>% \n  filter(state %in% new_england_states)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#create a vector for the intermountain states\ninterm_states <- c(\"MT\", \"WY\", \"UT\", \"CO\", \"NM\", \"NV\")\n#create dataframe\ninterm_data <- rrdata %>% \n  filter(state %in% interm_states)\n```\n:::\n\n\nHere, we are trying to create new data frames that specifically isolates our regions of interest.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Compute summary statistics for the two regions\nsummary(new_england_data$total_employees)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n    2.0     9.0    44.0   119.4   113.0  1561.0 \n```\n:::\n\n```{.r .cell-code}\nsum(new_england_data$total_employee)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 7764\n```\n:::\n\n```{.r .cell-code}\nsummary(interm_data$total_employees)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   1.00    5.00   16.00   73.10   60.25  737.00 \n```\n:::\n\n```{.r .cell-code}\nsum(interm_data$total_employee)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 14474\n```\n:::\n:::\n\n\nThe new england area has a mean number of employees of 119, while the mean number of employees for the intermountain region is 73. This is against the national mean of 87.\n\n## Visualisation\n\nNext we stack the employee information in a visualization bar plot to highligh these differences.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create a data frame with total employees by region\nregion_data <- data.frame(\n  region = c(\"New England\", \"Intermountain\"),\n  total_employees = c(sum(new_england_data$total_employee), sum(interm_data$total_employee))\n)\n\n# create a stacked bar plot\nggplot(region_data, aes(x = \"\", y = total_employees, fill = region)) + \n  geom_bar(stat = \"identity\") + \n  labs(x = NULL, y = \"Total Employees\", fill = NULL) +\n  coord_polar(theta = \"y\")\n```\n\n::: {.cell-output-display}\n![](DirichiUmunna_Challenge2_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n## Conclusion\n\nThis study provides valuable insights into the railroad data for two distinct regions in the country, shedding light on the variations in the number of employees between these regions. While both regions have similar numbers of states, our analysis revealed that the Intermountain region has almost double the number of railroad employees compared to the New England region. These findings open up a pathway for further research to understand the underlying factors driving such regional disparities in the railroad industry. Possible explanations may include variations in economic conditions, industry regulations, or demographics. A deeper understanding of the reasons behind these differences can provide important insights for policymakers, industry leaders, and other stakeholders to make informed decisions about investment, resource allocation, and strategic planning for the railroad industry.\n",
    "supporting": [
      "DirichiUmunna_Challenge2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}