{
  "hash": "460cead0d47c98d3d5027cef84df5f43",
  "result": {
    "markdown": "---\ntitle: \"Challenge 1\"\nauthor: \"Abhinav Reddy Yadatha\"\ndescription: \"Reading in data and creating a post\"\ndate: \"02/26/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_1\n  - my name\n  - dataset\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Challenge Overview\n\nToday's challenge is to\n\n1)  read in a dataset, and\n\n2)  describe the dataset using both words and any supporting information (e.g., tables, etc)\n\n## Read in the Data\n\nRead in one (or more) of the following data sets, using the correct R package and command.\n\n-   railroad_2012_clean_county.csv ⭐\n-   birds.csv ⭐⭐\n-   FAOstat\\*.csv ⭐⭐\n-   wild_bird_data.xlsx ⭐⭐⭐\n-   StateCounty2012.xls ⭐⭐⭐⭐\n\nFind the `_data` folder, located inside the `posts` folder. Then you can read in the data, using either one of the `readr` standard tidy read commands, or a specialized package such as `readxl`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndataframe <- read_csv('_data/birds.csv', show_col_types = FALSE)\nhead(dataframe)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 14\n  Domai…¹ Domain Area …² Area  Eleme…³ Element Item …⁴ Item  Year …⁵  Year Unit \n  <chr>   <chr>    <dbl> <chr>   <dbl> <chr>     <dbl> <chr>   <dbl> <dbl> <chr>\n1 QA      Live …       2 Afgh…    5112 Stocks     1057 Chic…    1961  1961 1000…\n2 QA      Live …       2 Afgh…    5112 Stocks     1057 Chic…    1962  1962 1000…\n3 QA      Live …       2 Afgh…    5112 Stocks     1057 Chic…    1963  1963 1000…\n4 QA      Live …       2 Afgh…    5112 Stocks     1057 Chic…    1964  1964 1000…\n5 QA      Live …       2 Afgh…    5112 Stocks     1057 Chic…    1965  1965 1000…\n6 QA      Live …       2 Afgh…    5112 Stocks     1057 Chic…    1966  1966 1000…\n# … with 3 more variables: Value <dbl>, Flag <chr>, `Flag Description` <chr>,\n#   and abbreviated variable names ¹​`Domain Code`, ²​`Area Code`,\n#   ³​`Element Code`, ⁴​`Item Code`, ⁵​`Year Code`\n```\n:::\n:::\n\n\nAdd any comments or documentation as needed. More challenging data sets may require additional code chunks and documentation.\n\n## Describe the data\n\nUsing a combination of words and results of R commands, can you provide a high level description of the data? Describe as efficiently as possible where/how the data was (likely) gathered, indicate the cases and variables (both the interpretation and any details you deem useful to the reader to fully understand your chosen data).\n\nDescription : The dataset 'birds.csv' contains information about the population of wild birds like chicken, geese etc for a few countries anually from 1961 to 2018.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#| Displaying the first few rows.\nhead(dataframe)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 14\n  Domai…¹ Domain Area …² Area  Eleme…³ Element Item …⁴ Item  Year …⁵  Year Unit \n  <chr>   <chr>    <dbl> <chr>   <dbl> <chr>     <dbl> <chr>   <dbl> <dbl> <chr>\n1 QA      Live …       2 Afgh…    5112 Stocks     1057 Chic…    1961  1961 1000…\n2 QA      Live …       2 Afgh…    5112 Stocks     1057 Chic…    1962  1962 1000…\n3 QA      Live …       2 Afgh…    5112 Stocks     1057 Chic…    1963  1963 1000…\n4 QA      Live …       2 Afgh…    5112 Stocks     1057 Chic…    1964  1964 1000…\n5 QA      Live …       2 Afgh…    5112 Stocks     1057 Chic…    1965  1965 1000…\n6 QA      Live …       2 Afgh…    5112 Stocks     1057 Chic…    1966  1966 1000…\n# … with 3 more variables: Value <dbl>, Flag <chr>, `Flag Description` <chr>,\n#   and abbreviated variable names ¹​`Domain Code`, ²​`Area Code`,\n#   ³​`Element Code`, ⁴​`Item Code`, ⁵​`Year Code`\n```\n:::\n:::\n\n\nDisplaying the summary of the dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(summarytools)\ndfSummary(dataframe)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nData Frame Summary  \ndataframe  \nDimensions: 30977 x 14  \nDuplicates: 0  \n\n----------------------------------------------------------------------------------------------------------------------------\nNo   Variable           Stats / Values                   Freqs (% of Valid)      Graph                  Valid      Missing  \n---- ------------------ -------------------------------- ----------------------- ---------------------- ---------- ---------\n1    Domain Code        1. QA                            30977 (100.0%)          IIIIIIIIIIIIIIIIIIII   30977      0        \n     [character]                                                                                        (100.0%)   (0.0%)   \n\n2    Domain             1. Live Animals                  30977 (100.0%)          IIIIIIIIIIIIIIIIIIII   30977      0        \n     [character]                                                                                        (100.0%)   (0.0%)   \n\n3    Area Code          Mean (sd) : 1201.7 (2099.4)      248 distinct values     :                      30977      0        \n     [numeric]          min < med < max:                                         :                      (100.0%)   (0.0%)   \n                        1 < 156 < 5504                                           :                                          \n                        IQR (CV) : 152 (1.7)                                     :                 .                        \n                                                                                 :                 :                        \n\n4    Area               1. Africa                          290 ( 0.9%)                                  30977      0        \n     [character]        2. Asia                            290 ( 0.9%)                                  (100.0%)   (0.0%)   \n                        3. Eastern Asia                    290 ( 0.9%)                                                      \n                        4. Egypt                           290 ( 0.9%)                                                      \n                        5. Europe                          290 ( 0.9%)                                                      \n                        6. France                          290 ( 0.9%)                                                      \n                        7. Greece                          290 ( 0.9%)                                                      \n                        8. Myanmar                         290 ( 0.9%)                                                      \n                        9. Northern Africa                 290 ( 0.9%)                                                      \n                        10. South-eastern Asia             290 ( 0.9%)                                                      \n                        [ 238 others ]                   28077 (90.6%)           IIIIIIIIIIIIIIIIII                         \n\n5    Element Code       1 distinct value                 5112 : 30977 (100.0%)   IIIIIIIIIIIIIIIIIIII   30977      0        \n     [numeric]                                                                                          (100.0%)   (0.0%)   \n\n6    Element            1. Stocks                        30977 (100.0%)          IIIIIIIIIIIIIIIIIIII   30977      0        \n     [character]                                                                                        (100.0%)   (0.0%)   \n\n7    Item Code          Mean (sd) : 1066.5 (9)           1057 : 13074 (42.2%)    IIIIIIII               30977      0        \n     [numeric]          min < med < max:                 1068 :  6909 (22.3%)    IIII                   (100.0%)   (0.0%)   \n                        1057 < 1068 < 1083               1072 :  4136 (13.4%)    II                                         \n                        IQR (CV) : 15 (0)                1079 :  5693 (18.4%)    III                                        \n                                                         1083 :  1165 ( 3.8%)                                               \n\n8    Item               1. Chickens                      13074 (42.2%)           IIIIIIII               30977      0        \n     [character]        2. Ducks                          6909 (22.3%)           IIII                   (100.0%)   (0.0%)   \n                        3. Geese and guinea fowls         4136 (13.4%)           II                                         \n                        4. Pigeons, other birds           1165 ( 3.8%)                                                      \n                        5. Turkeys                        5693 (18.4%)           III                                        \n\n9    Year Code          Mean (sd) : 1990.6 (16.7)        58 distinct values      . . .   . :   : : :    30977      0        \n     [numeric]          min < med < max:                                         : : : . : : : : : :    (100.0%)   (0.0%)   \n                        1961 < 1992 < 2018                                       : : : : : : : : : :                        \n                        IQR (CV) : 29 (0)                                        : : : : : : : : : :                        \n                                                                                 : : : : : : : : : :                        \n\n10   Year               Mean (sd) : 1990.6 (16.7)        58 distinct values      . . .   . :   : : :    30977      0        \n     [numeric]          min < med < max:                                         : : : . : : : : : :    (100.0%)   (0.0%)   \n                        1961 < 1992 < 2018                                       : : : : : : : : : :                        \n                        IQR (CV) : 29 (0)                                        : : : : : : : : : :                        \n                                                                                 : : : : : : : : : :                        \n\n11   Unit               1. 1000 Head                     30977 (100.0%)          IIIIIIIIIIIIIIIIIIII   30977      0        \n     [character]                                                                                        (100.0%)   (0.0%)   \n\n12   Value              Mean (sd) : 99410.6 (720611.4)   11495 distinct values   :                      29941      1036     \n     [numeric]          min < med < max:                                         :                      (96.7%)    (3.3%)   \n                        0 < 1800 < 23707134                                      :                                          \n                        IQR (CV) : 15233 (7.2)                                   :                                          \n                                                                                 :                                          \n\n13   Flag               1. *                              1494 ( 7.4%)           I                      20204      10773    \n     [character]        2. A                              6488 (32.1%)           IIIIII                 (65.2%)    (34.8%)  \n                        3. F                             10007 (49.5%)           IIIIIIIII                                  \n                        4. Im                             1213 ( 6.0%)           I                                          \n                        5. M                              1002 ( 5.0%)                                                      \n\n14   Flag Description   1. Aggregate, may include of      6488 (20.9%)           IIII                   30977      0        \n     [character]        2. Data not available             1002 ( 3.2%)                                  (100.0%)   (0.0%)   \n                        3. FAO data based on imputat      1213 ( 3.9%)                                                      \n                        4. FAO estimate                  10007 (32.3%)           IIIIII                                     \n                        5. Official data                 10773 (34.8%)           IIIIII                                     \n                        6. Unofficial figure              1494 ( 4.8%)                                                      \n----------------------------------------------------------------------------------------------------------------------------\n```\n:::\n:::\n\n\nChecking the dimensions of the dataset:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(dataframe)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 30977    14\n```\n:::\n\n```{.r .cell-code}\n#| \n```\n:::\n\n\nIt can be observed that there are 30977 rows and 14 columns\n\nDisplaying the column names of the dataset :\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolnames(dataframe)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"Domain Code\"      \"Domain\"           \"Area Code\"        \"Area\"            \n [5] \"Element Code\"     \"Element\"          \"Item Code\"        \"Item\"            \n [9] \"Year Code\"        \"Year\"             \"Unit\"             \"Value\"           \n[13] \"Flag\"             \"Flag Description\"\n```\n:::\n\n```{.r .cell-code}\n#| The dataset has 14 coulmns describing various fields such as above.\n```\n:::\n\n\nNumber of unique years :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nunique_years <- dataframe%>% select(Year)%>% n_distinct(.)\nunique_years\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 58\n```\n:::\n:::\n\n\nIt can be observed that the dataset has the data for 58 unique years i.e 1961-2018\n\nNumber of unique wildbirds :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nunique_birds <- dataframe%>% select(Item)%>% n_distinct(.)\nunique_birds\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 5\n```\n:::\n:::\n\n\nIt can be observed that the dataset contains information about 5 different types of birds.\n\nNumber of unique Areas / countries:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nunique_areas <- dataframe%>% select(Area)%>% n_distinct(.)\nunique_areas\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 248\n```\n:::\n:::\n\n\nIt can be observed that the dataset contains information about 248 different areas / countires\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}