{
  "hash": "f01e1f82a50997e34a93af055c815536",
  "result": {
    "markdown": "---\ntitle: \"Challenge 1 Reading Birds\"\nauthor: \"Kekai Liu\"\ndesription: \"Reading in birds.csv\"\ndate: \"02/21/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_1\n  - birds\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Challenge Overview\n\nToday's challenge is to\n\n1)  read in a dataset, and\n\n2)  describe the dataset using both words and any supporting information (e.g., tables, etc)\n\n## Read in the Data\n\nRead in one (or more) of the following data sets, using the correct R package and command.\n\n-   railroad_2012_clean_county.csv ⭐\n-   birds.csv ⭐⭐\n-   FAOstat\\*.csv ⭐⭐\n-   wild_bird_data.xlsx ⭐⭐⭐\n-   StateCounty2012.xls ⭐⭐⭐⭐\n\nFind the `_data` folder, located inside the `posts` folder. Then you can read in the data, using either one of the `readr` standard tidy read commands, or a specialized package such as `readxl`.\n\nThe birds.csv file is read in using read_csv().\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbirds <- read_csv(\"_data/birds.csv\") #read in the data and assign it to birds\n```\n:::\n\n\nAdd any comments or documentation as needed. More challenging data sets may require additional code chunks and documentation.\n\n## Describe the data\n\nUsing a combination of words and results of R commands, can you provide a high level description of the data? Describe as efficiently as possible where/how the data was (likely) gathered, indicate the cases and variables (both the interpretation and any details you deem useful to the reader to fully understand your chosen data).\n\nThis dataset has 30,977 rows and 14 columns. The 30,977 rows represent 30,977 observations or cases, and the 14 columns represent 14 variables: Domain Code, Domain, Area Code, Area, Element Code, Element, Item Code, Item, Year Code, Year, Unit, Value, Flag, and Flag Description. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(birds) #produce a summary of the contents (dimensions, variables, variable types) of the data\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nspc_tbl_ [30,977 × 14] (S3: spec_tbl_df/tbl_df/tbl/data.frame)\n $ Domain Code     : chr [1:30977] \"QA\" \"QA\" \"QA\" \"QA\" ...\n $ Domain          : chr [1:30977] \"Live Animals\" \"Live Animals\" \"Live Animals\" \"Live Animals\" ...\n $ Area Code       : num [1:30977] 2 2 2 2 2 2 2 2 2 2 ...\n $ Area            : chr [1:30977] \"Afghanistan\" \"Afghanistan\" \"Afghanistan\" \"Afghanistan\" ...\n $ Element Code    : num [1:30977] 5112 5112 5112 5112 5112 ...\n $ Element         : chr [1:30977] \"Stocks\" \"Stocks\" \"Stocks\" \"Stocks\" ...\n $ Item Code       : num [1:30977] 1057 1057 1057 1057 1057 ...\n $ Item            : chr [1:30977] \"Chickens\" \"Chickens\" \"Chickens\" \"Chickens\" ...\n $ Year Code       : num [1:30977] 1961 1962 1963 1964 1965 ...\n $ Year            : num [1:30977] 1961 1962 1963 1964 1965 ...\n $ Unit            : chr [1:30977] \"1000 Head\" \"1000 Head\" \"1000 Head\" \"1000 Head\" ...\n $ Value           : num [1:30977] 4700 4900 5000 5300 5500 5800 6600 6290 6300 6000 ...\n $ Flag            : chr [1:30977] \"F\" \"F\" \"F\" \"F\" ...\n $ Flag Description: chr [1:30977] \"FAO estimate\" \"FAO estimate\" \"FAO estimate\" \"FAO estimate\" ...\n - attr(*, \"spec\")=\n  .. cols(\n  ..   `Domain Code` = col_character(),\n  ..   Domain = col_character(),\n  ..   `Area Code` = col_double(),\n  ..   Area = col_character(),\n  ..   `Element Code` = col_double(),\n  ..   Element = col_character(),\n  ..   `Item Code` = col_double(),\n  ..   Item = col_character(),\n  ..   `Year Code` = col_double(),\n  ..   Year = col_double(),\n  ..   Unit = col_character(),\n  ..   Value = col_double(),\n  ..   Flag = col_character(),\n  ..   `Flag Description` = col_character()\n  .. )\n - attr(*, \"problems\")=<externalptr> \n```\n:::\n:::\n\n\nThe dataset covers 1961-2018; earlier years have less cases than recent years. \n\n::: {.cell}\n\n```{.r .cell-code}\ntable((select(birds, Year))) #retrieve Year column from birds, calculate frequencies\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nYear\n1961 1962 1963 1964 1965 1966 1967 1968 1969 1970 1971 1972 1973 1974 1975 1976 \n 493  493  493  493  494  495  495  495  498  498  498  498  498  499  499  499 \n1977 1978 1979 1980 1981 1982 1983 1984 1985 1986 1987 1988 1989 1990 1991 1992 \n 498  498  497  496  498  498  495  498  499  499  500  502  503  512  514  569 \n1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004 2005 2006 2007 2008 \n 574  574  574  574  574  574  574  575  575  575  575  575  575  576  576  576 \n2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 \n 576  576  576  577  577  577  577  577  577  577 \n```\n:::\n:::\n\nThe Flag Description provides information on the sources of data. 6,488 cases are aggregate data, 1,002 cases do not have data available, 1,213 cases are FAO imputed data, 10,007 cases are FAO estimates, 10,773 cases are from official data, and 1,494 cases are unofficial figures.\n\n::: {.cell}\n\n```{.r .cell-code}\ntable((select(birds, \"Flag Description\"))) #retrieve \"Flag Description\" column from birds, calculate frequencies\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nFlag Description\nAggregate, may include official, semi-official, estimated or calculated data \n                                                                        6488 \n                                                          Data not available \n                                                                        1002 \n                                    FAO data based on imputation methodology \n                                                                        1213 \n                                                                FAO estimate \n                                                                       10007 \n                                                               Official data \n                                                                       10773 \n                                                           Unofficial figure \n                                                                        1494 \n```\n:::\n:::\n\nOf the 30,977 total cases, chickens comprised 13,074, ducks comprised 6,909, geese and guinea fowls comprised 4,136, pigeons and other birds comprised 1,165, and turkeys comprised 5,693.\n\n::: {.cell}\n\n```{.r .cell-code}\ntable((select(birds, Item))) #retrieve Item column from birds, calculate frequencies\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nItem\n              Chickens                  Ducks Geese and guinea fowls \n                 13074                   6909                   4136 \n  Pigeons, other birds                Turkeys \n                  1165                   5693 \n```\n:::\n:::\n\nThe data only covers live animals.\n\n::: {.cell}\n\n```{.r .cell-code}\ntable((select(birds, Domain)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nDomain\nLive Animals \n       30977 \n```\n:::\n:::\n\nThese are the ten areas with the most number of cases. This output shows that the data includes supranational cases: Africa, Asia, Eastern Asia, Europe). There are several areas with the most number of cases overall, 290.\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(sort(table((select(birds, Area))),decreasing=TRUE), n=10) #retrieve Area column from birds, calculate frequencies, sort in ascending order, display first ten\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nArea\n            Africa               Asia       Eastern Asia              Egypt \n               290                290                290                290 \n            Europe             France             Greece            Myanmar \n               290                290                290                290 \n   Northern Africa South-eastern Asia \n               290                290 \n```\n:::\n:::\n\nThese are the ten areas with the least number of cases. South Sudan and Sudan jointly have the least number of cases overall with only seven.\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(sort(table((select(birds, Area))),decreasing=FALSE), n=10) #retrieve Area column from birds, calculate frequencies, sort in descending order, display first ten\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nArea\n    South Sudan           Sudan      Montenegro      Luxembourg         Eritrea \n              7               7              13              19              26 \n       Ethiopia North Macedonia      Tajikistan           Aruba    Ethiopia PDR \n             26              27              27              29              32 \n```\n:::\n:::\n\nThe data contains cases from 248 unique areas.\n\n::: {.cell}\n\n```{.r .cell-code}\nnrow(unique(select(birds, Area))) #retrieve Area column from birds, identify unique Area values, calculate total number of unique Area values\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 248\n```\n:::\n:::\n\nHere is the five summary of the data. The smallest stock value is 0 units of 1000 Head, and the largest stock value is 23,707,134 units of 1000 Head. The mean or average across all cases is 99,411 units of 1000 Head.\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(select(birds, Value)) #retrieve Value column from birds, produce five number summary of Value\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     Value         \n Min.   :       0  \n 1st Qu.:     171  \n Median :    1800  \n Mean   :   99411  \n 3rd Qu.:   15404  \n Max.   :23707134  \n NA's   :1036      \n```\n:::\n:::\n\nThere are 1,036 cases with missing stock values.\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(is.na(select(birds, Value))) #retrieve Value column from birds, identify cases with missing values, total the number of cases with missing values\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1036\n```\n:::\n:::\n\nFrom this quick analysis, we can summarize this as a dataset of selected types of live bird stock measured in units of 1000 Head in 248 defined areas of the world in a calendar year. A case corresponds to the live stock of a type of bird in an area of the world in a calendar year.",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}