{
  "hash": "af60b730afbdd6071c5bc4761644a13b",
  "result": {
    "markdown": "---\ntitle: \"Final Project : Aditya Salveru\"\nauthor: \"Aditya Salveru\"\ndescription: \"Project & Data Description\"\ndate: \"05/22/2023\"\nformat:\n  html:\n    df-print: paged\n    toc: true\n    code-copy: true\n    code-tools: true\n    css: styles.css\ncategories:\n  - final_Project_assignment_1\n  - Behavioral Risk Factor Surveillance System (BRFSS)\neditor_options: \n  chunk_output_type: console\n---\n\n\n<!-- ## Important Formatting & Submission Notes: {#important-formatting-submission-notes} -->\n\n<!-- 1.  **Use this file as the template to work on: start your own writing from Section \"Part.1\"** -->\n\n<!-- 2.  **Please make the following changes to the above YAML header:** -->\n\n<!--     -   Change the \"title\" to \"Final Project Assignment#1: First Name Last Name\"; -->\n\n<!--     -   Change the \"author\" to your name; -->\n\n<!--     -   Change the \"date\" to the current date in the \"MM-DD-YYYY\" format; -->\n\n<!-- 3.  **Submission:** -->\n\n<!--     -   Delete the unnecessary sections (\"Overview\", \"Tasks\", \"Special Note\", and \"Evaluation\"). -->\n<!--     -   **In the posts folder of your local 601_Spring_2023 project, create a folder named \"FirstNameLastName_FinalProjectData\", and save your final project dataset(s) in this folder. DO NOT save the dataset(s) to the \\_data folder which stores the dataset(s) for challenges.** -->\n<!--     -   Render and submit the file to the blog post like a regular challenge. -->\n\n<!-- ## Overview of the Final Project {#overview-of-the-final-project} -->\n\n<!-- The goal is to tell a coherent and focused story with your data, which answers a question (or questions) that a researcher, or current or future employer, might want to have answered. The goal might be to understand a source of covariance, make a recommendation, or understand change over time. We don't expect you to reach a definitive conclusion in this analysis. Still, you are expected to tell a data-driven story using evidence to support the claims you are making on the basis of the exploratory analysis conducted over the past term. -->\n\n<!-- In this final project, statistical analyses **are not required**, but any students who wish to include these may do so. However, **your primary analysis should center around visualization rather than inferential statistics.** Many scientists only compute statistics after a careful process of exploratory data analysis and data visualization. Statistics are a way to gauge your certainty in your results - **NOT A WAY TO DISCOVER MEANINGFUL DATA PATTERNS**. **Do not run a multiple regression with numerous predictors and report which predictors are significant!!** -->\n\n<!-- ## Tasks of Assignment#1 {#Tasks-of-assignment1} -->\n\n<!-- This assignment is the first component of your final project. Together with the later assignments, it make up a short paper/report. In this assignment, you should introduce a dataset(s) and how you plan to present this dataset(s). This assignment should include the following components: -->\n\n<!-- 1.  **A clear description of the dataset(s) that you are using.** -->\n\n<!-- 2.  **What \"story\" do you want to present to the audience? In other words, what \"question(s)\" do you like to answer with this dataset(s)?** -->\n\n<!-- 3.  **The Plan for Further Analysis and Visualization.** -->\n\n<!-- We will have a special class meeting on April 12 to review and discuss students' proposed datasets for the final project. **If you want your project being discussed in the class, please submit this assignment before April 12.** -->\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(readr)\nlibrary(ggplot2)\nlibrary(cowplot)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Part 1. Introduction {#describe-the-data-sets}\n\nMy projects aims to analyze the heart disease data and explore the causes and general trends in the individuals with and without the heart disease. Particularly I am interested in finding the factors that contribute to the heart disease the most and early signs that might lead to a heart disease. I would also like to analyze the healthy habits that would keep the heart diseases away.\n\n\n### 1.  Dataset(s) Introduction:\n\nI have chosen the 2020 annual CDC survey data of 400k adults related to their health status collected by Behavioral Risk Factor Surveillance System (BRFSS). For people of the majority of racial groups in the US (African Americans, American Indians and Alaska Natives, and white people), heart disease is one of the leading causes of death, according to the CDC. In the field of medicine, it is crucial to identify and combat the causes that have the biggest influence on heart disease.\n\nThe Behavioral Risk Factor Surveillance System (BRFSS) is a collaborative project between all the states in the\nUnited States and participating US territories and the Centers for Disease Control and Prevention (CDC). The\nBRFSS is administered and supported by CDC's Population Health Surveillance Branch, under the Division of\nPopulation Health at CDC’s National Center for Chronic Disease Prevention and Health Promotion. The\nBRFSS is a system of ongoing health-related telephone surveys designed to collect data on health-related risk\nbehaviors, chronic health conditions, health-care access, and use of preventive services from the\nnon institutionalized adult population (≥ 18 years) residing in the United States and participating areas.\n\n\n\n### 2.  What questions do you like to answer with this dataset(s)?\n\n- How is heart disease related to physical attributes such as Gender, sleep time, BMI etc.\n    \n- Is there any particular group of people who are at high risk?\n\n- What changes should the high risk people incorporate to reduce the risk of heart disease.\n    \n\n## Part 2. Describe the data set(s) {#describe-the-data-sets-1}\n\n<!-- This part contains both a coding and a storytelling component. -->\n\n<!-- In the coding component, you should: -->\n\n1.  read the dataset;\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolumns = read.csv(\"/home/aditya/Desktop/HealthData/2020/2020-column-layout.csv\")\n\ncolumns$File_Width = sapply(1:nrow(columns), function(y) ifelse(y < nrow(columns),\n\tcolumns$Starting_Column[y + 1] - columns$Starting_Column[y], 1))\n\ncolumns = columns[columns$File_Width > 0,]\n\nresponses = read.fwf(\"/home/aditya/Desktop/HealthData/2020/LLCP2020.ASC \", widths = columns$File_Width, col.names = columns$Variable_Name)\n```\n:::\n\n\n<!-- ```{r} -->\n<!-- responses = read_csv('/home/aditya/Desktop/HealthData/2020/filtered.csv') -->\n<!-- ``` -->\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnrow(responses)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 401958\n```\n:::\n\n```{.r .cell-code}\nncol(responses)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 277\n```\n:::\n:::\n\n\n*   There are 401958 rows in the data set\n*   There are 277 columns in the data set\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresponses %>%\n  colnames() %>%\n  sort()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  [1] \"ACEDEPRS\"  \"ACEDIVRC\"  \"ACEDRINK\"  \"ACEDRUGS\"  \"ACEHURT1\"  \"ACEHVSEX\" \n  [7] \"ACEPRISN\"  \"ACEPUNCH\"  \"ACESWEAR\"  \"ACETOUCH\"  \"ACETTHEM\"  \"ADDEPEV3\" \n [13] \"ALCDAY5\"   \"ASTHMA3\"   \"ASTHNOW\"   \"AVEDRNK3\"  \"BIRTHSEX\"  \"BLDSTOL1\" \n [19] \"BLDSUGAR\"  \"BLIND\"     \"CADULT1\"   \"CAREGIV1\"  \"CASTHDX2\"  \"CASTHNO2\" \n [25] \"CCLGHOUS\"  \"CDASSIST\"  \"CDDISCUS\"  \"CDHELP\"    \"CDHOUSE\"   \"CDSOCIAL\" \n [31] \"CELLFON5\"  \"CELLSEX\"   \"CELPHONE\"  \"CHCCOPD2\"  \"CHCKDNY2\"  \"CHCOCNCR\" \n [37] \"CHCSCNCR\"  \"CHECKUP1\"  \"CHILDREN\"  \"CHKHEMO3\"  \"CIMEMLOS\"  \"CNCRAGE\"  \n [43] \"CNCRDIFF\"  \"CNCRTYP1\"  \"COLGHOUS\"  \"COLGSEX\"   \"COLNSCPY\"  \"COLNTEST\" \n [49] \"CPDEMO1B\"  \"CRGVALZD\"  \"CRGVEXPT\"  \"CRGVHOU1\"  \"CRGVHRS1\"  \"CRGVLNG1\" \n [55] \"CRGVPER1\"  \"CRGVPRB3\"  \"CRGVREL4\"  \"CSRVCLIN\"  \"CSRVCTL2\"  \"CSRVDEIN\" \n [61] \"CSRVDOC1\"  \"CSRVINSR\"  \"CSRVINST\"  \"CSRVPAIN\"  \"CSRVRTRN\"  \"CSRVSUM\"  \n [67] \"CSRVTRT3\"  \"CSTATE1\"   \"CTELENM1\"  \"CTELNUM1\"  \"CVDCRHD4\"  \"CVDINFR4\" \n [73] \"CVDSTRK3\"  \"DEAF\"      \"DECIDE\"    \"DIABAGE3\"  \"DIABEDU\"   \"DIABETE4\" \n [79] \"DIABEYE\"   \"DIFFALON\"  \"DIFFDRES\"  \"DIFFWALK\"  \"DISPCODE\"  \"DOCTDIAB\" \n [85] \"DRNK3GE5\"  \"DRNKANY5\"  \"DRNKDRI2\"  \"DROCDY3_\"  \"ECIGARET\"  \"ECIGNOW\"  \n [91] \"EDUCA\"     \"EMPLOY1\"   \"EXERANY2\"  \"EYEEXAM1\"  \"FALL12MN\"  \"FALLINJ4\" \n [97] \"FEETCHK\"   \"FEETCHK3\"  \"FLSHTMY3\"  \"FLUSHOT7\"  \"FMONTH\"    \"GENHLTH\"  \n[103] \"HADHYST2\"  \"HADMAM\"    \"HADPAP2\"   \"HAVARTH4\"  \"HAVECFS\"   \"HAVEHEPB\" \n[109] \"HAVEHEPC\"  \"HEIGHT3\"   \"HHADULT\"   \"HIVRISK5\"  \"HIVTST7\"   \"HIVTSTD3\" \n[115] \"HLTHCVR1\"  \"HLTHPLN1\"  \"HOWLONG\"   \"HPLSTTST\"  \"HPVADSHT\"  \"HPVADVC4\" \n[121] \"HPVTEST\"   \"HTIN4\"     \"HTM4\"      \"IDAY\"      \"IMFVPLA1\"  \"IMONTH\"   \n[127] \"INCOME2\"   \"INSULIN1\"  \"IYEAR\"     \"LADULT1\"   \"LANDLINE\"  \"LANDSEX\"  \n[133] \"LASTDEN4\"  \"LASTPAP2\"  \"LASTSMK2\"  \"LCSCTSCN\"  \"LCSFIRST\"  \"LCSLAST\"  \n[139] \"LCSNUMCG\"  \"LSTBLDS4\"  \"MARIJAN1\"  \"MARITAL\"   \"MAXDRNKS\"  \"MEDCOST\"  \n[145] \"MEDSHEPB\"  \"MENTHLTH\"  \"MSCODE\"    \"NUMADULT\"  \"NUMHHOL3\"  \"NUMMEN\"   \n[151] \"NUMPHON3\"  \"NUMWOMEN\"  \"PCDMDEC1\"  \"PCPSAAD3\"  \"PCPSADE1\"  \"PCPSADI1\" \n[157] \"PCPSARE1\"  \"PCPSARS1\"  \"PDIABTST\"  \"PERSDOC2\"  \"PHYSHLTH\"  \"PNEUVAC4\" \n[163] \"POORHLTH\"  \"PREDIAB1\"  \"PREGNANT\"  \"PRIRHEPC\"  \"PSATEST1\"  \"PSATIME\"  \n[169] \"PVTRESD1\"  \"PVTRESD3\"  \"QSTLANG\"   \"QSTVER\"    \"RCSGENDR\"  \"RCSRLTN2\" \n[175] \"RENTHOM1\"  \"RESPSLCT\"  \"RMVTETH4\"  \"RSNMRJN1\"  \"SAFETIME\"  \"SDNATEST\" \n[181] \"SEATBELT\"  \"SEXVAR\"    \"SHINGLE2\"  \"SIGMSCPY\"  \"SIGMTEST\"  \"SLEPTIM1\" \n[187] \"SMOKDAY2\"  \"SMOKE100\"  \"SOFEMALE\"  \"SOMALE\"    \"STATERE1\"  \"STOOLDNA\" \n[193] \"STOPSMK2\"  \"TETANUS1\"  \"TOLDCFS\"   \"TOLDHEPC\"  \"TRETHEPC\"  \"TRNSGNDR\" \n[199] \"USEMRJN2\"  \"USENOW3\"   \"VCLNTEST\"  \"VETERAN3\"  \"VIRCOLON\"  \"WEIGHT2\"  \n[205] \"WORKCFS\"   \"WTKG3\"     \"X_AGE_G\"   \"X_AGE65YR\" \"X_AGE80\"   \"X_AGEG5YR\"\n[211] \"X_AIDTST4\" \"X_ALTETH3\" \"X_ASTHMS1\" \"X_BMI5\"    \"X_BMI5CAT\" \"X_CASTHM1\"\n[217] \"X_CHISPNC\" \"X_CHLDCNT\" \"X_CLLCPWT\" \"X_CLNSCPY\" \"X_CPRACE\"  \"X_CRACE1\" \n[223] \"X_CRCREC1\" \"X_DENVST3\" \"X_DRDXAR2\" \"X_DRNKDRV\" \"X_DRNKWK1\" \"X_DUALCOR\"\n[229] \"X_DUALUSE\" \"X_EDUCAG\"  \"X_EXTETH3\" \"X_FLSHOT7\" \"X_HCVU651\" \"X_HISPANC\"\n[235] \"X_IMPRACE\" \"X_INCOMG\"  \"X_LLCPWT\"  \"X_LLCPWT2\" \"X_LTASTH1\" \"X_MAM5023\"\n[241] \"X_MENT14D\" \"X_METSTAT\" \"X_MICHD\"   \"X_MRACE1\"  \"X_PHYS14D\" \"X_PNEUMO3\"\n[247] \"X_PRACE1\"  \"X_PSU\"     \"X_RACE\"    \"X_RACEG21\" \"X_RACEGR3\" \"X_RACEPRV\"\n[253] \"X_RAWRAKE\" \"X_RFBING5\" \"X_RFBLDS4\" \"X_RFBMI5\"  \"X_RFDRHV7\" \"X_RFHLTH\" \n[259] \"X_RFMAM22\" \"X_RFPAP35\" \"X_RFPSA23\" \"X_RFSEAT2\" \"X_RFSEAT3\" \"X_RFSMOK3\"\n[265] \"X_SBONTIM\" \"X_SEX\"     \"X_SGMS10Y\" \"X_SGMSCPY\" \"X_SMOKER3\" \"X_STATE\"  \n[271] \"X_STOLDNA\" \"X_STRWT\"   \"X_STSTR\"   \"X_TOTINDA\" \"X_URBSTAT\" \"X_VIRCOLN\"\n[277] \"X_WT2RAKE\"\n```\n:::\n:::\n\n\n<!-- ```{r} -->\n<!-- # write_csv(responses, \"/home/aditya/Desktop/HealthData/2020/filtered.csv\") -->\n<!-- ``` -->\nOut of the 277 columns in the data set, for our study of the heart disease and the factors of the same, we use only a subset of all the columns in the dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresponses <- responses %>% \n  select(\n    X_SEX,\n    SLEPTIM1,\n    WEIGHT2,\n    HEIGHT3,\n    X_AGE80,\n    SMOKE100,\n    EXERANY2,\n    VETERAN3,\n    X_MICHD\n  )\n```\n:::\n\n\n<!-- ```{r} -->\n<!-- responses <- responses %>%  -->\n<!--   select( -->\n<!--     X_SEX, -->\n<!--     SLEPTIM1, -->\n<!--     WEIGHT2, -->\n<!--     HEIGHT3, -->\n<!--     X_AGE80, -->\n<!--     DIFFWALK, -->\n<!--     SMOKE100, -->\n<!--     EXERANY2, -->\n<!--     VETERAN3, -->\n<!--     X_LTASTH1, -->\n<!--     X_MICHD, -->\n<!--     CVDSTRK3, -->\n<!--     EMPLOY1, -->\n<!--     INCOME2, -->\n<!--     X_RACE -->\n<!--   ) -->\n<!-- ``` -->\nOut of around the three hundred columns, the following are the columns of interest:\n\n* X_SEX : The sex of the subject,\nPossible Values : 1(Male),2(Female)\n\n* SLEPTIM1 : On average, how many hours of sleep does the subject get in a 24-hour period?\nPossible Values : 1-24(Number of hours), 77(Not Sure), 99(Refused), Blank(Missing)\n\n* WEIGHT2 : About how much does the subject weigh without shoes in pounds\nPossible Values : 50 -776(Weight in pounds), 7777(Don't know), 9023-9352(Weight in KG without '9'), 9999 (Missing)\n\n* HEIGHT3 : About how tall is the subject without shoes\nPossible Values : 200 to 711(FeetInchInch format), 7777(Not Sure), 9061-9998(MeterCmCm format without leading '9'),9999(Missing)\n\n* X_AGE80 : Imputed Age value collapsed above 80\nPossible Values : 18-99\n\n\n* SMOKE100 : smoked at least 100 cigarettes in your entire life?\nPossible Values : 1(Yest), 2(No), 7(Not Sure), 9(Refused), Blank(Missing)\n\n* EXERANY2 : During the past month, other than your regular job, has the subject participated in any exercises\nsuch as running, calisthenics, golf, gardening, or walking for exercise?\nPossible Values : 1(Yes), 2(No), 7(Don't know, Not Sure)\n\n* VETERAN3 : ever served on active duty in the United States Armed Forces, either in the regular military or in a\nNational Guard or military reserve unit?\nPossible Values : 1(Yes), 2(No), 7(Don't know, Not Sure), 9(Refused), Blank(Missing)\n\n\n* X_MICHD : Ever reported having coronary heart disease (CHD) or myocardial infarction(MI)\nPossible Values : 1(Yes), 2(No), Blank(Missing)\n\n\n\n### Clean the Data\n\nThe raw data from the survey is not directly usable for our analysis. It need to be converted to a representation and units that will help us visualize the data and the trends.\n\n\nFirst, we will rename the column names so that they will make more sense and represent the features they refer to.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresponses <- responses %>%\n  rename(\n    Sex = X_SEX, \n    Age = X_AGE80,\n    SleepTime = SLEPTIM1,\n    Weight = WEIGHT2,\n    Height = HEIGHT3,\n    Veteran = VETERAN3,\n    Exercise = EXERANY2,\n    HeartDisease = X_MICHD,\n    Smoke = SMOKE100\n    ) \n  \ndata <- responses %>%\n    select(\n      Sex, \n      Age,\n      SleepTime,\n      Weight,\n      Height,\n      Veteran,\n      Exercise,\n      HeartDisease,\n      Smoke\n    )\n```\n:::\n\n\n\nThe raw Sex values are numerical where 1 represents male and 2 represents female. We would like to convert them into \"Male\" and \"Female\". There are other values which Sex column can take(Such as missing, refused etc.) we mark all of them as NA.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Convert the Sex to \"Male\" and \"Female\"\ndata <- data %>% \n  mutate(Sex = ifelse(Sex == 1, \"Male\", ifelse(Sex == 2,\"Female\",NA)))\n```\n:::\n\n\nThe height column has some values in Feet-Inch format and others in Meter-Centimeter format. We will clean it up and convert all of the values in Centimeters.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Convert the heights in Feet,Inches and Meter,Centimeter format to centimeters\ndata$Height <- replace_na(data$Height,0)\nconvert_height <- function(height) {\n  # if the height is invalid due to any reason, return NA\n  if(is.na(height) | height == 7777 | height == 9999){\n    return(NA)\n  } else if (height >= 1000 && height <= 9999) {\n    # Convert MeterCmCm format to centimeters\n    cms <- height %% 100\n    meters <- (height %/% 100) %% 10\n    centimeters <- (meters * 100) + cms\n    return(centimeters)\n  } else if (height >= 200 && height <= 711) {\n    # Convert FeetInchInch format to centimeters\n    inches <- height %% 100\n    feet <- height %/% 100\n    centimeters <- (feet * 30.48) + (inches * 2.54)\n    return(centimeters)\n  } else {\n    return(NA)\n  }\n}\n\ndata$Height <- sapply(data$Height, convert_height)\n```\n:::\n\n\nThe weight also has values in both Pounds and Kgs, we clean it up  and convert all the values into Kgs.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Convert the Weights in different formats to Kgs\n\nconvert_weight <- function(weight) {\n  # if the height is invalid due to any reason, return NA\n  if(is.na(weight) | weight == 7777 | weight == 9999){\n    return(NA)\n  } else if (weight >= 50 && weight <= 0776) {\n    # Convert pounds to Kg\n    kgs <- weight / 2.2\n    return(kgs)\n  } else if (weight >= 9000 && weight <= 10000) {\n    # Extract Kilograms\n    kgs = weight %% 1000\n    return(kgs)\n  } else {\n    return(NA)\n  }\n}\n\ndata$Weight <- sapply(data$Weight, convert_weight)\n```\n:::\n\n\nSimilar to Sex, we convert veteran status, smoking, Exercise and Heart Disease columns into corresponding strings from numerical values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n### Convert veteran status, Smoking, Exercise and  Heart Disease to strings\ndata <- data %>%\n  mutate(Veteran = ifelse(Veteran == 1, \"Yes\", ifelse(Veteran == 2,\"No\",NA)),HeartDisease = ifelse(HeartDisease == 1, \"Yes\", ifelse(HeartDisease == 2, \"No\", \"0\")), Smoke = ifelse(Smoke == 1, \"Yes\", ifelse(Smoke == 2,\"No\",NA)),Exercise = ifelse(Exercise == 1, \"Yes\", ifelse(Exercise == 2,\"No\",NA)))\n```\n:::\n\n\nConvert Sleep time to 1-24H\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- data %>%\n  mutate(SleepTime = ifelse(SleepTime < 25, SleepTime, NA))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- na.omit(data)\n\ndata %>% head(15)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Sex\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Age\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"SleepTime\"],\"name\":[3],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Weight\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Height\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Veteran\"],\"name\":[6],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Exercise\"],\"name\":[7],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"HeartDisease\"],\"name\":[8],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Smoke\"],\"name\":[9],\"type\":[\"chr\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"Female\",\"2\":\"56\",\"3\":\"5\",\"4\":\"48.18182\",\"5\":\"170.18\",\"6\":\"No\",\"7\":\"Yes\",\"8\":\"No\",\"9\":\"Yes\",\"_rn_\":\"1\"},{\"1\":\"Female\",\"2\":\"80\",\"3\":\"7\",\"4\":\"57.27273\",\"5\":\"167.64\",\"6\":\"No\",\"7\":\"Yes\",\"8\":\"No\",\"9\":\"No\",\"_rn_\":\"5\"},{\"1\":\"Male\",\"2\":\"66\",\"3\":\"8\",\"4\":\"81.81818\",\"5\":\"175.26\",\"6\":\"No\",\"7\":\"Yes\",\"8\":\"No\",\"9\":\"Yes\",\"_rn_\":\"6\"},{\"1\":\"Female\",\"2\":\"75\",\"3\":\"6\",\"4\":\"68.18182\",\"5\":\"167.64\",\"6\":\"No\",\"7\":\"No\",\"8\":\"No\",\"9\":\"No\",\"_rn_\":\"7\"},{\"1\":\"Female\",\"2\":\"69\",\"3\":\"6\",\"4\":\"68.18182\",\"5\":\"160.02\",\"6\":\"No\",\"7\":\"Yes\",\"8\":\"No\",\"9\":\"Yes\",\"_rn_\":\"8\"},{\"1\":\"Female\",\"2\":\"41\",\"3\":\"8\",\"4\":\"77.27273\",\"5\":\"180.34\",\"6\":\"No\",\"7\":\"Yes\",\"8\":\"No\",\"9\":\"No\",\"_rn_\":\"9\"},{\"1\":\"Female\",\"2\":\"78\",\"3\":\"12\",\"4\":\"74.09091\",\"5\":\"160.02\",\"6\":\"No\",\"7\":\"No\",\"8\":\"Yes\",\"9\":\"Yes\",\"_rn_\":\"10\"},{\"1\":\"Female\",\"2\":\"73\",\"3\":\"4\",\"4\":\"60.90909\",\"5\":\"167.64\",\"6\":\"No\",\"7\":\"Yes\",\"8\":\"No\",\"9\":\"No\",\"_rn_\":\"11\"},{\"1\":\"Female\",\"2\":\"80\",\"3\":\"9\",\"4\":\"73.63636\",\"5\":\"152.40\",\"6\":\"No\",\"7\":\"No\",\"8\":\"No\",\"9\":\"Yes\",\"_rn_\":\"12\"},{\"1\":\"Female\",\"2\":\"80\",\"3\":\"5\",\"4\":\"63.63636\",\"5\":\"154.94\",\"6\":\"No\",\"7\":\"No\",\"8\":\"No\",\"9\":\"No\",\"_rn_\":\"14\"},{\"1\":\"Male\",\"2\":\"68\",\"3\":\"10\",\"4\":\"136.36364\",\"5\":\"182.88\",\"6\":\"No\",\"7\":\"Yes\",\"8\":\"No\",\"9\":\"No\",\"_rn_\":\"15\"},{\"1\":\"Male\",\"2\":\"63\",\"3\":\"15\",\"4\":\"118.18182\",\"5\":\"185.42\",\"6\":\"No\",\"7\":\"No\",\"8\":\"Yes\",\"9\":\"Yes\",\"_rn_\":\"16\"},{\"1\":\"Female\",\"2\":\"58\",\"3\":\"5\",\"4\":\"66.81818\",\"5\":\"152.40\",\"6\":\"No\",\"7\":\"Yes\",\"8\":\"No\",\"9\":\"Yes\",\"_rn_\":\"17\"},{\"1\":\"Male\",\"2\":\"79\",\"3\":\"8\",\"4\":\"97.72727\",\"5\":\"185.42\",\"6\":\"No\",\"7\":\"Yes\",\"8\":\"No\",\"9\":\"Yes\",\"_rn_\":\"18\"},{\"1\":\"Female\",\"2\":\"80\",\"3\":\"7\",\"4\":\"74.54545\",\"5\":\"162.56\",\"6\":\"No\",\"7\":\"No\",\"8\":\"No\",\"9\":\"No\",\"_rn_\":\"19\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nstr(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t347975 obs. of  9 variables:\n $ Sex         : chr  \"Female\" \"Female\" \"Male\" \"Female\" ...\n $ Age         : int  56 80 66 75 69 41 78 73 80 80 ...\n $ SleepTime   : int  5 7 8 6 6 8 12 4 9 5 ...\n $ Weight      : num  48.2 57.3 81.8 68.2 68.2 ...\n $ Height      : num  170 168 175 168 160 ...\n $ Veteran     : chr  \"No\" \"No\" \"No\" \"No\" ...\n $ Exercise    : chr  \"Yes\" \"Yes\" \"Yes\" \"No\" ...\n $ HeartDisease: chr  \"No\" \"No\" \"No\" \"No\" ...\n $ Smoke       : chr  \"Yes\" \"No\" \"Yes\" \"No\" ...\n - attr(*, \"na.action\")= 'omit' Named int [1:53983] 2 3 4 13 25 28 37 51 68 73 ...\n  ..- attr(*, \"names\")= chr [1:53983] \"2\" \"3\" \"4\" \"13\" ...\n```\n:::\n\n```{.r .cell-code}\nsummary(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     Sex                 Age          SleepTime          Weight      \n Length:347975      Min.   :18.00   Min.   : 1.000   Min.   : 22.73  \n Class :character   1st Qu.:40.00   1st Qu.: 6.000   1st Qu.: 68.18  \n Mode  :character   Median :57.00   Median : 7.000   Median : 79.55  \n                    Mean   :54.37   Mean   : 7.095   Mean   : 82.59  \n                    3rd Qu.:69.00   3rd Qu.: 8.000   3rd Qu.: 93.18  \n                    Max.   :80.00   Max.   :24.000   Max.   :352.00  \n     Height         Veteran            Exercise         HeartDisease      \n Min.   : 71.12   Length:347975      Length:347975      Length:347975     \n 1st Qu.:162.56   Class :character   Class :character   Class :character  \n Median :170.18   Mode  :character   Mode  :character   Mode  :character  \n Mean   :170.33                                                           \n 3rd Qu.:177.80                                                           \n Max.   :233.68                                                           \n    Smoke          \n Length:347975     \n Class :character  \n Mode  :character  \n                   \n                   \n                   \n```\n:::\n:::\n\n\nWe have shown the final columns and summary of the data above after cleaning and remapping the data.\n\n\n## Part 3: Visualization\n\n#### Tentative plan for visualization\n\n*   We will first visualize the distribution of samples with respect to age and gender.\n\n*   Then we will study the impact of the following factors on heart disease using Bar plots, Histograms and pie charts.\n\n  1.    Gender\n  2.    Age\n  3.    Veteran Status\n  4.    Somking\n  5.    BMI\n  6.    Exercise\n  7.    Sleeping time\n  \n*   Finally, We will analyze the most vulnerable population and find out which changes if made in lifestyle could help in reduce the risk of heart disease using Pie Charts.\n\n#### Distribution of Male and Female subjects for the data\n\nOne of the major factor which we want to study with respect to the heart disease is the gender of the person. Therefore, we first try see the distribution of the male and female proportion in the data set.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a table with the number of males and females\nsex_table <- data %>%\n  select(Sex) %>%\n  table()\n\n# Calculate the percentage of males and females\nsex_percent <- round(prop.table(sex_table)*100)\n\n# Create a bar plot of the sex data with percentages\nbarplot(sex_table, main=\"Number of Males and Females\",\n        xlab=\"Sex\", ylab=\"Frequency\", col=c(\"pink\", \"lightblue\"),\n        legend=c(\"Female\", \"Male\"), ylim=c(0, max(sex_table)*1.2))\ntext(1:2, sex_table + 0.2, paste0(sex_percent, \"%\"), col = \"black\", cex = 1.5)\n```\n\n::: {.cell-output-display}\n![](AdityaSalveruFinalProject_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\nAs we can see the number of samples of both genders is fairly equal and none of the gender dominate the dataset.\n\n#### Distribution of Subjects across age groups\n\nAnother important factor that we take into our study is the age of the people in the dataset. We divide the people into buckets with a range of 5 and plot a bar chart to see the distribution of the people in different age groups.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nages <- data %>% \n  select(Age)\n\n# Define the age groups\nages$AgeGroup <- cut(ages$Age, breaks = seq(15, 90, by = 10))\n\n# Create a bar plot\nggplot(ages, aes(x = AgeGroup)) +\n  geom_bar(fill = \"skyblue\", color = \"black\", stat = \"count\") +\n  labs(x = \"Age\", y = \"Count\", title = \"Age Distribution\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](AdityaSalveruFinalProject_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\nThough there are a little higher people in the range 40-60, there are good number samples of other ages too. Therefore again the results will not be skewed towards any particular age groups.\n\n\n<!-- #### Distribution of Subjects across Race -->\n\n<!-- ```{r} -->\n<!-- ggplot(data, aes(x = Race)) + -->\n<!--   geom_bar(fill = \"lightblue\") + -->\n<!--   xlab(\"Race\") + -->\n<!--   ylab(\"Count\") + -->\n<!--   ggtitle(\"Count of Race\") + -->\n<!--   geom_text(stat='count', aes(label=..count..), vjust=-0.5)  -->\n<!-- ``` -->\n\n### Analysis of various factors and the probability of heart disease\nWe now have a look at some factors and check what percentages of people have heart disease with these factors.\n\n\n#### How is heart disease related to the gender of the person\n\nWe now study the relation of gender to the likeliness of getting a heart disease. We plot a bar graph of male and female and fill it with the proportion of people with heart disease to study the impact of gender on heart disease.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSex_HeartDisease <- data %>%\n  select(`Sex`,`HeartDisease`)\n# Filter the N/A values\nSex_HeartDisease <- Sex_HeartDisease %>%\n  filter(!is.na(HeartDisease))\n\n\n# Calculate the proportions\nproportions <- Sex_HeartDisease %>%\n  group_by(Sex, HeartDisease) %>%\n  summarise(count = n()) %>%\n  group_by(Sex) %>%\n  mutate(proportion = count / sum(count))\n\n# Create a bar plot\nggplot(proportions, aes(x = Sex, y = proportion, fill = HeartDisease)) +\n  geom_bar(stat = \"identity\", position = \"fill\") +\n  geom_text(aes(label = scales::percent(proportion, accuracy = 0.1)),\n            position = position_fill(vjust = 0.5)) +\n  labs(x = \"Sex\", y = \"Proportion\", fill = \"Heart Disease\") +\n  scale_fill_manual(values = c(\"No\" = \"lightblue\", \"Yes\" = \"orange\", \"NA\" = \"gray\"), na.value = \"gray\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](AdityaSalveruFinalProject_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\nAmong men, 10.7% have heart disease, while 89.3% do not. Among women, 6.8% have heart disease, while 93.2% do not.\n\nFrom these figures, we can infer that both men and women are susceptible to heart disease, but there is a slightly higher prevalence among men compared to women. The data suggests that men have a higher risk of developing heart disease than women, with a 10.7% prevalence compared to 6.8%. This aligns with existing research indicating that men are generally more prone to heart disease.\n\n#### How is heart disease releated to the age of the person?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Remove rows with missing values\ndf <- data %>% select(Age,HeartDisease)\n\n# Calculate the ratio of people with and without heart disease for each age group, handling NA values\nratio_data <- tapply(data$HeartDisease, data$Age, function(x) {\n  n_yes <- sum(x == \"Yes\", na.rm = TRUE)\n  n_no <- sum(x == \"No\", na.rm = TRUE)\n  if (is.na(n_yes) || is.na(n_no))\n    return(NA)\n  else\n    return(n_yes / (n_yes+n_no))\n})\n\n\n# Create a bar plot of the ratio, excluding NA values\nbarplot(ratio_data[!is.na(ratio_data)], col = \"#4D4D4D\", xlab = \"Age\", ylab = \"Ratio of People\", main = \"Ratio of People with Heart Disease by Age\")\n```\n\n::: {.cell-output-display}\n![](AdityaSalveruFinalProject_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\nThe provided data represents the ratio of people with heart disease to people without heart disease across different age groups. The data shows that the prevalence of heart disease tends to increase with age. In the younger age groups (18-29), the ratios range from 0.005562914 to 0.010360138, indicating a relatively low proportion of individuals with heart disease. However, as the age increases, the ratios gradually rise. From ages 30 to 47, the ratios range from 0.012141280 to 0.037837838, suggesting a notable increase in the prevalence of heart disease. This trend continues in the subsequent age groups, with ratios ranging from 0.042045868 to 0.290657149 in the age range of 48-80.\n    \nThe data implies that as individuals grow older, they are more likely to develop heart disease. This inference aligns with the widely recognized understanding that age is a significant risk factor for heart disease. The progressive increase in the ratio of individuals with heart disease across the age groups highlights the importance of preventive measures and regular cardiovascular health monitoring, especially as individuals approach and surpass middle age. These findings underscore the need for early detection, lifestyle modifications, and appropriate medical interventions to mitigate the risk and impact of heart disease, particularly in older populations.\n\n\n#### Veterans Vs Non Veterans\n\nWe now study the probability of heart disease on veterans and non veterans by using a similar bar plot.\n\n::: {.cell}\n\n```{.r .cell-code}\nVeteranHeartDisease <- data %>%\n   select(Veteran, HeartDisease)\n\nproportions <- VeteranHeartDisease %>%\n  group_by(Veteran, HeartDisease) %>%\n  summarise(count = n()) %>%\n  group_by(Veteran) %>%\n  mutate(proportion = count / sum(count))\n\nproportions\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Veteran\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"HeartDisease\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"count\"],\"name\":[3],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"proportion\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"No\",\"2\":\"No\",\"3\":\"281263\",\"4\":\"0.92503379\"},{\"1\":\"No\",\"2\":\"Yes\",\"3\":\"22794\",\"4\":\"0.07496621\"},{\"1\":\"Yes\",\"2\":\"No\",\"3\":\"36282\",\"4\":\"0.82613052\"},{\"1\":\"Yes\",\"2\":\"Yes\",\"3\":\"7636\",\"4\":\"0.17386948\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\n# Create a bar plot\nggplot(proportions, aes(x = Veteran, y = proportion, fill = HeartDisease)) +\n  geom_bar(stat = \"identity\", position = \"fill\") +\n  geom_text(aes(label = scales::percent(proportion, accuracy = 0.1)),\n            position = position_fill(vjust = 0.5)) +\n  labs(x = \"Veteran\", y = \"Proportion\", fill = \"Heart Disease\") +\n  scale_fill_manual(values = c(\"No\" = \"lightblue\", \"Yes\" = \"orange\", \"NA\" = \"gray\"), na.value = \"gray\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](AdityaSalveruFinalProject_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\nThese statistics suggest that there is a notable difference in the prevalence of heart disease between veterans and non-veterans. Veterans appear to have a higher percentage of individuals with heart disease compared to non-veterans. This finding may indicate that veteran status is associated with a higher risk or susceptibility to heart disease.\n\n\n#### How is heart disease related to Smoking status?\n\n::: {.cell}\n\n```{.r .cell-code}\nSmokingHeartDisease <- data %>%\n   select(Smoke, HeartDisease)\n\n\nproportions <- SmokingHeartDisease %>%\n  group_by(Smoke, HeartDisease) %>%\n  summarise(count = n()) %>%\n  group_by(Smoke) %>%\n  mutate(proportion = count / sum(count))\n\n# Create a bar plot\nggplot(proportions, aes(x = Smoke, y = proportion, fill = HeartDisease)) +\n  geom_bar(stat = \"identity\", position = \"fill\") +\n  geom_text(aes(label = scales::percent(proportion, accuracy = 0.1)),\n            position = position_fill(vjust = 0.5)) +\n  labs(x = \"Smoke\", y = \"Proportion\", fill = \"Heart Disease\") +\n  scale_fill_manual(values = c(\"No\" = \"lightblue\", \"Yes\" = \"orange\", \"NA\" = \"gray\"), na.value = \"gray\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](AdityaSalveruFinalProject_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\nThe data presented sheds light on the prevalence of heart disease among smokers and non-smokers, providing valuable insights into the impact of smoking on cardiovascular health. Among smokers, 12.3% are affected by heart disease, while the vast majority, accounting for 87.7%, remain free from this condition. This stark contrast between the two groups underscores the profound influence of smoking on heart health. The statistics reveal that smoking significantly increases the risk of developing heart disease.\n\nOn the other hand, among non-smokers, the prevalence of heart disease is considerably lower, with only 6.1% of individuals being affected. This finding emphasizes the importance of maintaining a smoke-free lifestyle in mitigating the risk of heart disease. It highlights the fact that non-smokers have a significantly reduced likelihood of developing heart issues, further emphasizing the bad impact of smoking on heart health.\n\n\n<!-- ### How is weight of the individuals affecting the heart disease? -->\n\n<!-- ```{r} -->\n<!-- WeightHeartDisease <- data %>% -->\n<!--   select(Weight, HeartDisease) %>% -->\n<!--   filter(!is.na(Weight) & !is.na(HeartDisease)) -->\n\n<!-- # Create the scatter plot -->\n<!-- ggplot(WeightHeartDisease, aes(x = Weight, y = HeartDisease)) + -->\n<!--   geom_point(size = 3, shape = 16, color = \"blue\") + -->\n<!--   labs(x = \"Weight (kg)\", y = \"Heart Disease\") + -->\n<!--   ggtitle(\"Weight vs. Heart Disease\") + -->\n<!--   theme_minimal() -->\n\n\n<!-- # Create the box plot -->\n<!-- ggplot(WeightHeartDisease , aes(x = HeartDisease, y = Weight, fill = HeartDisease)) + -->\n<!--   geom_boxplot() + -->\n<!--   labs(x = \"Heart Disease\", y = \"Weight (kg)\") + -->\n<!--   ggtitle(\"Weight Distribution by Heart Disease\") + -->\n<!--   theme_minimal() -->\n\n<!-- ``` -->\n#### How is heart disease releated to whether a person exercises?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nproportions <- data %>%\n   select(Exercise, HeartDisease)%>%\n  filter(!is.na(Exercise) & !is.na(HeartDisease))%>%\n  group_by(Exercise, HeartDisease) %>%\n  summarise(count = n()) %>%\n  group_by(Exercise) %>%\n  mutate(proportion = count / sum(count))\n\nproportions\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Exercise\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"HeartDisease\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"count\"],\"name\":[3],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"proportion\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"No\",\"2\":\"No\",\"3\":\"68806\",\"4\":\"0.86048373\"},{\"1\":\"No\",\"2\":\"Yes\",\"3\":\"11156\",\"4\":\"0.13951627\"},{\"1\":\"Yes\",\"2\":\"No\",\"3\":\"248739\",\"4\":\"0.92808558\"},{\"1\":\"Yes\",\"2\":\"Yes\",\"3\":\"19274\",\"4\":\"0.07191442\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nIt can be clearly seen that people who exercise are less likely to have the heart disease.\n\n#### How is BMI of the individuals affecting the heart disease?\n\nWe compute the BMI of the individuals from the height and weight information available and segregate them into five standard BMI categories and plot the percentage of people having the heart diseases in the respective categories.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata$BMI <- round(data$Weight / ((data$Height / 100) ^ 2))\n\n# Create a new column for BMI categories\ndata$BMICategory <- cut(data$BMI, breaks = c(0, 18.5, 24.9, 29.9, 34.9, 39.9, Inf),\n                      labels = c(\"Underweight\", \"Normal weight\", \"Overweight\", \"Obesity (Class I)\",\n                                 \"Obesity (Class II)\", \"Obesity (Class III)\"))\nBMICategoryHeartDisease <- data %>% select(BMICategory,HeartDisease)\n\n# Calculate the percentage of people with heart disease for each BMI category\npercent <- aggregate(HeartDisease ~ BMICategory, BMICategoryHeartDisease, function(x) mean(x == \"Yes\") * 100)\npercent\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"BMICategory\"],\"name\":[1],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"HeartDisease\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Underweight\",\"2\":\"8.160369\"},{\"1\":\"Normal weight\",\"2\":\"6.582813\"},{\"1\":\"Overweight\",\"2\":\"8.714392\"},{\"1\":\"Obesity (Class I)\",\"2\":\"10.167626\"},{\"1\":\"Obesity (Class II)\",\"2\":\"10.804440\"},{\"1\":\"Obesity (Class III)\",\"2\":\"11.307970\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\n# Create the bar plot using ggplot2\nggplot(percent, aes(x = BMICategory, y = HeartDisease)) +\n  geom_bar(stat = \"identity\") +\n  xlab(\"BMI Category\") +\n  ylab(\"Percentage of People with Heart Disease\") +\n  scale_fill_manual(values = c(\"steelblue\", \"lightgray\")) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](AdityaSalveruFinalProject_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\nAnalyzing the data, it can be observed that the heart disease percentage varies across different BMI categories. The lowest heart disease percentage is associated with the \"Normal weight\" category, which stands at 6.661403. The \"Underweight\" category follows closely with a slightly higher heart disease percentage of 8.388409. Moving towards higher BMI categories, the heart disease percentages gradually increase. The \"Overweight\" category has a percentage of 8.742972, while \"Obesity (Class I)\" records a higher percentage of 10.245310.\n\nAs the BMI categories progress to higher levels of obesity, the heart disease percentages continue to rise. \"Obesity (Class II)\" displays a percentage of 10.934172, and the highest heart disease percentage is observed in the \"Obesity (Class III)\" category, standing at 11.441625.\n\nThese findings suggest a positive correlation between BMI categories and the likelihood of heart disease. Individuals with higher BMI categories, especially those classified as obese, have a higher risk of developing heart disease. These observations emphasize the importance of maintaining a healthy weight and highlight the potential health risks associated with obesity.\n\n\n#### Heart Disease relation with sleep time:\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- data %>% select(SleepTime,HeartDisease)\n\n# Calculate frequency\nfrequency <- table(df$SleepTime)\n\n# Pie chart\na <- ggplot(data, aes(x = \"\", fill = as.factor(SleepTime))) +\n  geom_bar(width = 1) +\n  coord_polar(\"y\", start = 0) +\n  labs(fill = \"Sleep Time\", title = \"Pie Chart of Sleep Time\") +\n  scale_fill_discrete(name = \"Sleep Time\") +\n  theme_minimal()\nprint(a)\n```\n\n::: {.cell-output-display}\n![](AdityaSalveruFinalProject_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n\n```{.r .cell-code}\nfiltered <- data %>%\n  select(SleepTime,HeartDisease) %>%\n  filter(SleepTime>2 & SleepTime<13) \n\n# Calculate the percentage of people with heart disease for each sleep time\npercentage <- filtered %>%\n  group_by(SleepTime) %>%\n  summarise(HeartDiseasePercentage = sum(HeartDisease == \"Yes\") / n() * 100)\n\npercentage\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"SleepTime\"],\"name\":[1],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"HeartDiseasePercentage\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"3\",\"2\":\"17.582897\"},{\"1\":\"4\",\"2\":\"15.640790\"},{\"1\":\"5\",\"2\":\"10.767280\"},{\"1\":\"6\",\"2\":\"8.313709\"},{\"1\":\"7\",\"2\":\"6.569760\"},{\"1\":\"8\",\"2\":\"8.709945\"},{\"1\":\"9\",\"2\":\"10.752137\"},{\"1\":\"10\",\"2\":\"15.109321\"},{\"1\":\"11\",\"2\":\"17.835671\"},{\"1\":\"12\",\"2\":\"19.030449\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\n# Bar plot\nplot <- ggplot(percentage, aes(x = factor(SleepTime), y = HeartDiseasePercentage)) +\n  geom_bar(stat = \"identity\", fill = \"steelblue\") +\n  labs(x = \"Sleep Time\", y = \"Percentage of People with Heart Disease\",\n       title = \"Percentage of People with Heart Disease by Sleep Time\") +\n  theme_minimal() +\n  scale_x_discrete(drop = FALSE)  # To include all sleep times on the x-axis\n\n# Display the plot\nprint(plot)\n```\n\n::: {.cell-output-display}\n![](AdityaSalveruFinalProject_files/figure-html/unnamed-chunk-21-2.png){width=672}\n:::\n:::\n\n\nUpon analyzing the data, it can be observed that individuals who sleep for shorter durations tend to have higher percentages of heart disease. For instance, those who sleep for 3 or 4 hours have a relatively higher percentage of heart disease at 17.07% and 15.36%, respectively. As sleep duration increases to 5, 6, and 7 hours, the percentage of heart disease decreases to 10.52%, 8.11%, and 6.41%, respectively. The trend continues, with the lowest percentage of heart disease observed at 7 hours of sleep. However, as sleep time increases beyond 7 hours, the percentage of heart disease starts to rise again, reaching its peak at 12 hours with 18.38%. This dataset suggests a potential association between sleep duration and the prevalence of heart disease, with an optimal sleep duration of around 7 hours for maintaining heart health.\n\n\n### Analyzing the most vulnerable population\n\nFrom the above analysis we can suspect that the most vulnerable population has the following characteristics:\n1. Male\n2. Older\n3. Smoke\n4. Bad sleeping habits\n5. High BMI\n6. No Exercise\n\nLet us see what percentage of people with these characteristics have heart disease.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfiltered_data <- data %>%\n  filter(Sex==\"Male\" & Veteran == \"Yes\" & (SleepTime>9 | SleepTime<6) & Smoke == \"Yes\" & BMI>30 & Age>60 & Exercise == \"No\") %>% \n  select(HeartDisease)\n\n# Calculate the percentage of heart disease\noriginal_percentage <- filtered_data %>%\n  group_by(HeartDisease) %>%\n  summarise(HeartDiseasePercentage = n() / nrow(filtered_data) * 100)\noriginal_percentage\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"HeartDisease\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"HeartDiseasePercentage\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"No\",\"2\":\"61.99461\"},{\"1\":\"Yes\",\"2\":\"38.00539\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nA whopping 38 % of the people with above characteristics have the disease.\n\nLet us now analyze the benefit of giving up bad habits for these population:\n\n#### 1. Exercise and Reduce the BMI below the Obesity levels\n\n::: {.cell}\n\n```{.r .cell-code}\nfiltered_data <- data %>%\n  filter(Sex==\"Male\" & Veteran == \"Yes\" & (SleepTime>9 | SleepTime<6) & Smoke == \"Yes\" & BMI<30 & Age>60 & Exercise == \"Yes\") %>% \n  select(HeartDisease)\n\nfiltered_data <- na.omit(filtered_data)\n\n# Calculate the percentage of heart disease\npercentage <- filtered_data %>%\n  group_by(HeartDisease) %>%\n  summarise(HeartDiseasePercentage = n() / nrow(filtered_data) * 100)\npercentage\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"HeartDisease\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"HeartDiseasePercentage\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"No\",\"2\":\"71.92394\"},{\"1\":\"Yes\",\"2\":\"28.07606\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nExercising and getting the BMI below 30 has reduced the probability of having the heart disease by over 10%.\n\n#### 2. Having the right amount of sleep\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfiltered_data <- data %>%\n  filter(Sex==\"Male\" & Veteran == \"Yes\" & (SleepTime>=6 & SleepTime<=9) & Smoke == \"Yes\" & BMI<30 & Age>60 & Exercise == \"Yes\") %>% \n  select(HeartDisease)\n\nfiltered_data <- na.omit(filtered_data)\n\n# Calculate the percentage of heart disease\npercentage <- filtered_data %>%\n  group_by(HeartDisease) %>%\n  summarise(HeartDiseasePercentage = n() / nrow(filtered_data) * 100)\npercentage\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"HeartDisease\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"HeartDiseasePercentage\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"No\",\"2\":\"75.83708\"},{\"1\":\"Yes\",\"2\":\"24.16292\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nSleeping for 6-9 hours a day reduces the heart disease probability of the vulnerable population further by around 4 percent.\n\n#### 2. No Smoking\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfiltered_data <- data %>%\n  filter(Sex==\"Male\" & Veteran == \"Yes\" & (SleepTime>=6 & SleepTime<=9) & Smoke == \"No\" & BMI<30 & Age>60 & Exercise == \"Yes\") %>% \n  select(HeartDisease)\n\nfiltered_data <- na.omit(filtered_data)\n\n# Calculate the percentage of heart disease\npercentage <- filtered_data %>%\n  group_by(HeartDisease) %>%\n  summarise(HeartDiseasePercentage = n() / nrow(filtered_data) * 100)\npercentage\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"HeartDisease\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"HeartDiseasePercentage\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"No\",\"2\":\"82.13921\"},{\"1\":\"Yes\",\"2\":\"17.86079\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nThe people who do not smoke in these population have over 6 percent less chance of heart disease.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_heart_disease_percent <- function(percentage, title_str){\n  plot <- ggplot(percentage, aes(x = \"\", y = HeartDiseasePercentage, fill = HeartDisease)) +\n  geom_bar(stat = \"identity\", width = 1) +\n  coord_polar(theta = \"y\") +\n  labs(fill = \"Heart Disease\", x = \"\", y = \"\", title = title_str) +\n  theme_void() +\n  theme(legend.position = \"right\") +\n  geom_text(aes(label = paste0(round(HeartDiseasePercentage,2), \"%\")), position = position_stack(vjust = 0.5))\n  return(plot)\n}\n\norig = plot_heart_disease_percent(original_percentage,\"Probability of heart disease\")\nnew  = plot_heart_disease_percent(percentage, \"Probability with suggestions\")\nplot_grid(orig, new)\n```\n\n::: {.cell-output-display}\n![](AdityaSalveruFinalProject_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\nOverall with the above three changes in the lifestyle, our vulnerable population can actually reduce the risk of heart disease by more than 20%.\n\n## Part 4 : Conclusion\n\n*   When it comes to the heart disease, males are more susceptible than females. Males are 57% more likely to get effected as compare to females.\n*   The age of a person is also a very important factor of being affected by the heart disease. Older people(>65 years) are more than 10 times prone to the heart disease as compared to young people(25 years)\n*   We can also conclude that people with High BMI(higher than Obese category) are also more likely to get  heart disease than people with low BMI.\n*   Veterans are affected by the heart disease twice as compare to the non-veterans, there could be multiple reasons for this such as stress.\n*   Similarly people who smoke are twice as likely to get affected by heart disease.\n*   People who exercise and have the right amount of sleep are also less likely to get a heart disease.\n\n\n*   Therefore the old male veterans who smoke, do not exercise and do not get a proper sleep are the most at risk population. Our analysis showed that around 40% of the people belonging to this category has the heart disease.\n\n*   We have also shown that by following lifestyle changes such as exercising, appropriate sleep, reducing the BMI can drastically reduce the risk for this population.\n\n\n## Part 5 : Bibliography\n*   R: A language and environment for statistical computing. - https://www.R-project.org/\n*   R Studio IDE. - https://posit.co/products/open-source/rstudio/\n*   CDC - BRFSS - https://www.cdc.gov/brfss/index.html\n\n",
    "supporting": [
      "AdityaSalveruFinalProject_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}