{
  "hash": "732a281a179d651b12f771b4cae0fe5c",
  "result": {
    "markdown": "---\ntitle: \"Challenge 1: Railroad Workers 2012\"\nauthor: \"Teresa Lardo\"\ndesription: \"Reading in and describing a data set about railroad employees in the year 2012.\"\ndate: \"02/21/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_1\n  - Teresa Lardo\n  - dataset\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nknitr::opts_chunk$set(echo = TRUE)\nlibrary(readr)\nlibrary(dplyr)\nrailroad <- read_csv(\"_data/railroad_2012_clean_county.csv\", show_col_types = FALSE)\n```\n:::\n\n\n## Choo-choo, all aboard!\n\nThis data set shows the total number of railroad employees per county in the United States in the year 2012. Running the `head()` function displays the first 6 rows of the data set.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(railroad)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 3\n  state county               total_employees\n  <chr> <chr>                          <dbl>\n1 AE    APO                                2\n2 AK    ANCHORAGE                          7\n3 AK    FAIRBANKS NORTH STAR               2\n4 AK    JUNEAU                             3\n5 AK    MATANUSKA-SUSITNA                  2\n6 AK    SITKA                              1\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(railroad)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2930    3\n```\n:::\n:::\n\n\nThe `dim()` functions shows us that the data set contains 2930 rows (2930 counties) and 3 columns (*state*, *county*, and *total_employees*).\n\nThe very first item lists a state code of \"**AE**\" and a county of \"**APO**\" with 2 employees for the year 2012. Since this is different from the state codes and county names that follow, I want to clarify that this is for **overseas military**. Besides \"AE,\" the other overseas military \"state\" abbreviations are AP and AA. Let's check for all of these state codes in the data set.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter the state column through a vector of overseas military state codes\noverseas <- railroad %>% \n  filter(\n    state %in% c(\"AA\", \"AE\", \"AP\")\n  )\noverseas\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 3\n  state county total_employees\n  <chr> <chr>            <dbl>\n1 AE    APO                  2\n2 AP    APO                  1\n```\n:::\n:::\n\n\nFiltering the original data set by states in a vector of military overseas abbreviations shows that only Armed Forces Europe (AE) and Armed Forces Pacific (AP) appear in this data set; Armed Forces the Americas (AA) does not.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# How many unique values are in the state column?\nrailroad %>% \n  select(state) %>% \n  n_distinct(.)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 53\n```\n:::\n:::\n\n\nSo apparently there are **53** unique values under the 'state' column. There's 50 states, and the two overseas military codes we found before make 52. What's the other one?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nunique(railroad$state)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"AE\" \"AK\" \"AL\" \"AP\" \"AR\" \"AZ\" \"CA\" \"CO\" \"CT\" \"DC\" \"DE\" \"FL\" \"GA\" \"HI\" \"IA\"\n[16] \"ID\" \"IL\" \"IN\" \"KS\" \"KY\" \"LA\" \"MA\" \"MD\" \"ME\" \"MI\" \"MN\" \"MO\" \"MS\" \"MT\" \"NC\"\n[31] \"ND\" \"NE\" \"NH\" \"NJ\" \"NM\" \"NV\" \"NY\" \"OH\" \"OK\" \"OR\" \"PA\" \"RI\" \"SC\" \"SD\" \"TN\"\n[46] \"TX\" \"UT\" \"VA\" \"VT\" \"WA\" \"WI\" \"WV\" \"WY\"\n```\n:::\n:::\n\n\nLooking through the unique listings of the 'state' column, we find '**DC**' hiding in there, being sneaky and upping our \"state\" count to 53.\n\n## Visualization\n\nWe can use a horizontal bar graph to show which areas had the most railroad employees in 2012. Because we know from the `dim()` function that this data set includes **2930 different counties**, a bar graph of the number of state employees by county would be super long and overwhelming. So let's instead opt to use employee counts by state instead of county. Using states will still give us a graph with **53 bars**, so let's add some color to distinguish consecutive bars from each other.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Access ggplot2 and set up a horizontal bar graph to display employees by state\nlibrary(ggplot2)\n\nst_emp_viz <- ggplot(railroad, aes(x=state, y=total_employees, fill=state)) + \n  geom_bar(stat = \"identity\") + \n  coord_flip() + \n  theme(legend.position = \"none\")\n\n# Add a title as well as labels for the x- and y-axes\nst_emp_viz <- st_emp_viz + ggtitle(\"Railroad Employees by State (2012)\") + xlab(\"State\") + ylab(\"Total Employees\")\nst_emp_viz\n```\n\n::: {.cell-output-display}\n![](TeresaLardo_Challenge1_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nThe horizontal bar graph shows that the 3 states with the highest number of railroad employees in 2012 were **Texas**, **Illinois**, and **New York**, which all surpassed 15000 employees. **Nebraska**, **California**, and **Pennsylvania** have the next highest values, with all 3 states surpassing 12500.\n\n## Highest Values by County\n\nLet's do a little bit of sorting to see how the data set reflects or differs from our bar graph.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Arrange the data set in descending order so the counties with the most employees appear at the top\nsorted_by_county <- railroad %>% \n  arrange(-total_employees)\n\nhead(sorted_by_county, 15)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 15 × 3\n   state county           total_employees\n   <chr> <chr>                      <dbl>\n 1 IL    COOK                        8207\n 2 TX    TARRANT                     4235\n 3 NE    DOUGLAS                     3797\n 4 NY    SUFFOLK                     3685\n 5 VA    INDEPENDENT CITY            3249\n 6 FL    DUVAL                       3073\n 7 CA    SAN BERNARDINO              2888\n 8 CA    LOS ANGELES                 2545\n 9 TX    HARRIS                      2535\n10 NE    LINCOLN                     2289\n11 NY    NASSAU                      2076\n12 MO    JACKSON                     2055\n13 IN    LAKE                        1999\n14 IL    WILL                        1784\n15 PA    PHILADELPHIA                1649\n```\n:::\n:::\n\n\nSince there are so many counties in this data set, I've expanded the `head()` view to the top 15 values. We can see that each of the top 6 states from our bar graph is represented in the top 15 counties. Several counties in other states also had particularly high numbers of railroad employees in 2012.\n\n## Conclusion\n\nThis data set shows that at the state level, the states of **Texas**, **Illinois**, and **New York** had the highest total number of railroad employees in the year 2012. At the county level, the highest number of railroad employees were based in **Cook County, Illinois** (8207); **Tarrant County, Texas** (4235); and **Douglas County, Nebraska** (3797). Considering the data set describes data from the year 2012 specifically, the data was likely gathered via local census.\n",
    "supporting": [
      "TeresaLardo_Challenge1_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}