{
  "hash": "3c4037e96b32d51f1dbfa38187deef68",
  "result": {
    "markdown": "---\ntitle: \"Final Project Assignment: Pranav Bharadwaj Komaravolu\"\nauthor: \"Pranav Komaravolu\"\ndescription: \"Impact of behavioral patterns and socio-economic factors on Credit score\"\ndate: \"05/22/2023\"\nformat:\n  html:\n    df-print: paged\n    toc: true\n    code-copy: true\n    code-tools: true\n    css: styles.css\ncategories:\n  - final_Project\neditor_options: \n  chunk_output_type: inline\n---\n\n<!--\n## Important Formatting & Submission Notes: {#important-formatting-submission-notes}\n\n1.  **Use this file as the template to work on: start your own writing from Section \"Part.1\"**\n\n2.  **Please make the following changes to the above YAML header:**\n\n    -   Change the \"title\" to \"Final Project Assignment#1: First Name Last Name\";\n\n    -   Change the \"author\" to your name;\n\n    -   Change the \"date\" to the current date in the \"MM-DD-YYYY\" format;\n\n3.  **Submission:**\n\n    -   Delete the unnecessary sections (\"Overview\", \"Tasks\", \"Special Note\", and \"Evaluation\").\n    -   **In the posts folder of your local 601_Spring_2023 project, create a folder named \"FirstNameLastName_FinalProjectData\", and save your final project dataset(s) in this folder. DO NOT save the dataset(s) to the \\_data folder which stores the dataset(s) for challenges.**\n    -   Render and submit the file to the blog post like a regular challenge.\n-->\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readr)\nlibrary(tidyverse)\nlibrary(ggplot2)\nlibrary(dplyr)\nlibrary(mosaic)\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n## Introduction\nCredits play an important role in the modern society. They enhance the purchase power of the individuals, thus facilitating financial growth and in turn bolstering the global economies. One significant role of credit in society is providing access to capital for individuals and businesses. Many people rely on credit to finance significant purchases such as homes, cars, or education. By borrowing money through loans or mortgages, individuals can acquire assets and investments that may otherwise be unaffordable upfront. This access to credit allows people to meet their immediate needs and pursue their long-term aspirations. Credit cards have played a vital role in the easy accessibility of credit to the common man.\n\nAlthough, defaulting on the repayment of credit can have significant and long-lasting consequences for individuals and their financial well-being. These effects can extend beyond the immediate financial repercussions and impact various aspects of one's life, including credit history, financial opportunities, and overall financial stability. If such behavior is observed in masses it could also affect the economy of the country. In order to avoid such a catastrophe banks and financial institutions have come up with an indicator to represent the borrowing power of an individual, called the credit score. The credit score plays an important role in determining the societal well-being of an individual.\n\nThrough this project I would like to address the following questions:\n\n1) What social parameters or behavioral patterns determine the credit score of an individual?\n\n2) Is it possible for us to estimate the credit score given the required information?\n<!--\nThe goal is to tell a coherent and focused story with your data, which answers a question (or questions) that a researcher, or current or future employer, might want to have answered. The goal might be to understand a source of covariance, make a recommendation, or understand change over time. We don't expect you to reach a definitive conclusion in this analysis. Still, you are expected to tell a data-driven story using evidence to support the claims you are making on the basis of the exploratory analysis conducted over the past term.\n\nIn this final project, statistical analyses **are not required**, but any students who wish to include these may do so. However, **your primary analysis should center around visualization rather than inferential statistics.** Many scientists only compute statistics after a careful process of exploratory data analysis and data visualization. Statistics are a way to gauge your certainty in your results - **NOT A WAY TO DISCOVER MEANINGFUL DATA PATTERNS**. **Do not run a multiple regression with numerous predictors and report which predictors are significant!!**\n-->\n\n## Dataset Introduction\nFor this task I have identified the \"Credit score classification\" dataset on kaggle which was published by Rohan Paris. The number of available datasets for this task are very small in number and out of those datasets the current choice seemed more promising. This dataset is a collection of all the necessary and important information related to 12,500 different individuals and their corresponding credit score classification. This data appears to have been generated as a part of challenge on kaggle. The dataset comprises of 100,000 rows and 28 columns and it covers most of the necessary behavioral and social information of different individuals. Each row represents the individual's financial behavior, societal status related information and a credit score category (\"Good\", \"Standard\", \"Poor\").\n\n## Dataset Description\n\n### Reading the dataset\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- read_csv(\"601_Spring_2023_project/PranavKomaravolu_FinalProjectData/train.csv\", show_col_types = FALSE)\nhead(data)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"ID\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Customer_ID\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Month\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Name\"],\"name\":[4],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Age\"],\"name\":[5],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"SSN\"],\"name\":[6],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Occupation\"],\"name\":[7],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Annual_Income\"],\"name\":[8],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Monthly_Inhand_Salary\"],\"name\":[9],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Num_Bank_Accounts\"],\"name\":[10],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Num_Credit_Card\"],\"name\":[11],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Interest_Rate\"],\"name\":[12],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Num_of_Loan\"],\"name\":[13],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Type_of_Loan\"],\"name\":[14],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Delay_from_due_date\"],\"name\":[15],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Num_of_Delayed_Payment\"],\"name\":[16],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Changed_Credit_Limit\"],\"name\":[17],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Num_Credit_Inquiries\"],\"name\":[18],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Credit_Mix\"],\"name\":[19],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Outstanding_Debt\"],\"name\":[20],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Credit_Utilization_Ratio\"],\"name\":[21],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Credit_History_Age\"],\"name\":[22],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Payment_of_Min_Amount\"],\"name\":[23],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Total_EMI_per_month\"],\"name\":[24],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Amount_invested_monthly\"],\"name\":[25],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Payment_Behaviour\"],\"name\":[26],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Monthly_Balance\"],\"name\":[27],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Credit_Score\"],\"name\":[28],\"type\":[\"chr\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"1602\",\"2\":\"CUS_0xd40\",\"3\":\"January\",\"4\":\"Aaron Maashoh\",\"5\":\"23\",\"6\":\"821-00-0265\",\"7\":\"Scientist\",\"8\":\"19114.12\",\"9\":\"1824.843\",\"10\":\"3\",\"11\":\"4\",\"12\":\"3\",\"13\":\"4\",\"14\":\"Auto Loan, Credit-Builder Loan, Personal Loan, and Home Equity Loan\",\"15\":\"3\",\"16\":\"7\",\"17\":\"11.27\",\"18\":\"4\",\"19\":\"_\",\"20\":\"809.98\",\"21\":\"26.82262\",\"22\":\"22 Years and 1 Months\",\"23\":\"No\",\"24\":\"49.57495\",\"25\":\"80.41529543900250\",\"26\":\"High_spent_Small_value_payments\",\"27\":\"312.4941\",\"28\":\"Good\"},{\"1\":\"1603\",\"2\":\"CUS_0xd40\",\"3\":\"February\",\"4\":\"Aaron Maashoh\",\"5\":\"23\",\"6\":\"821-00-0265\",\"7\":\"Scientist\",\"8\":\"19114.12\",\"9\":\"NA\",\"10\":\"3\",\"11\":\"4\",\"12\":\"3\",\"13\":\"4\",\"14\":\"Auto Loan, Credit-Builder Loan, Personal Loan, and Home Equity Loan\",\"15\":\"-1\",\"16\":\"NA\",\"17\":\"11.27\",\"18\":\"4\",\"19\":\"Good\",\"20\":\"809.98\",\"21\":\"31.94496\",\"22\":\"NA\",\"23\":\"No\",\"24\":\"49.57495\",\"25\":\"118.28022162236700\",\"26\":\"Low_spent_Large_value_payments\",\"27\":\"284.6292\",\"28\":\"Good\"},{\"1\":\"1604\",\"2\":\"CUS_0xd40\",\"3\":\"March\",\"4\":\"Aaron Maashoh\",\"5\":\"-500\",\"6\":\"821-00-0265\",\"7\":\"Scientist\",\"8\":\"19114.12\",\"9\":\"NA\",\"10\":\"3\",\"11\":\"4\",\"12\":\"3\",\"13\":\"4\",\"14\":\"Auto Loan, Credit-Builder Loan, Personal Loan, and Home Equity Loan\",\"15\":\"3\",\"16\":\"7\",\"17\":\"_\",\"18\":\"4\",\"19\":\"Good\",\"20\":\"809.98\",\"21\":\"28.60935\",\"22\":\"22 Years and 3 Months\",\"23\":\"No\",\"24\":\"49.57495\",\"25\":\"81.699521264648\",\"26\":\"Low_spent_Medium_value_payments\",\"27\":\"331.2099\",\"28\":\"Good\"},{\"1\":\"1605\",\"2\":\"CUS_0xd40\",\"3\":\"April\",\"4\":\"Aaron Maashoh\",\"5\":\"23\",\"6\":\"821-00-0265\",\"7\":\"Scientist\",\"8\":\"19114.12\",\"9\":\"NA\",\"10\":\"3\",\"11\":\"4\",\"12\":\"3\",\"13\":\"4\",\"14\":\"Auto Loan, Credit-Builder Loan, Personal Loan, and Home Equity Loan\",\"15\":\"5\",\"16\":\"4\",\"17\":\"6.27\",\"18\":\"4\",\"19\":\"Good\",\"20\":\"809.98\",\"21\":\"31.37786\",\"22\":\"22 Years and 4 Months\",\"23\":\"No\",\"24\":\"49.57495\",\"25\":\"199.4580743910710\",\"26\":\"Low_spent_Small_value_payments\",\"27\":\"223.4513\",\"28\":\"Good\"},{\"1\":\"1606\",\"2\":\"CUS_0xd40\",\"3\":\"May\",\"4\":\"Aaron Maashoh\",\"5\":\"23\",\"6\":\"821-00-0265\",\"7\":\"Scientist\",\"8\":\"19114.12\",\"9\":\"1824.843\",\"10\":\"3\",\"11\":\"4\",\"12\":\"3\",\"13\":\"4\",\"14\":\"Auto Loan, Credit-Builder Loan, Personal Loan, and Home Equity Loan\",\"15\":\"6\",\"16\":\"NA\",\"17\":\"11.27\",\"18\":\"4\",\"19\":\"Good\",\"20\":\"809.98\",\"21\":\"24.79735\",\"22\":\"22 Years and 5 Months\",\"23\":\"No\",\"24\":\"49.57495\",\"25\":\"41.420153086217300\",\"26\":\"High_spent_Medium_value_payments\",\"27\":\"341.4892\",\"28\":\"Good\"},{\"1\":\"1607\",\"2\":\"CUS_0xd40\",\"3\":\"June\",\"4\":\"Aaron Maashoh\",\"5\":\"23\",\"6\":\"821-00-0265\",\"7\":\"Scientist\",\"8\":\"19114.12\",\"9\":\"NA\",\"10\":\"3\",\"11\":\"4\",\"12\":\"3\",\"13\":\"4\",\"14\":\"Auto Loan, Credit-Builder Loan, Personal Loan, and Home Equity Loan\",\"15\":\"8\",\"16\":\"4\",\"17\":\"9.27\",\"18\":\"4\",\"19\":\"Good\",\"20\":\"809.98\",\"21\":\"27.26226\",\"22\":\"22 Years and 6 Months\",\"23\":\"No\",\"24\":\"49.57495\",\"25\":\"62.430172331195300\",\"26\":\"!@9#%8\",\"27\":\"340.4792\",\"28\":\"Good\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\nThe dimensions of the dataset are as follows:\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 100000     28\n```\n:::\n:::\n\nIt is a very vast dataset with 100,000 rows and 28 columns.\n\nThe column names are as follows:\n\n::: {.cell}\n\n```{.r .cell-code}\ncolnames(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"ID\"                       \"Customer_ID\"             \n [3] \"Month\"                    \"Name\"                    \n [5] \"Age\"                      \"SSN\"                     \n [7] \"Occupation\"               \"Annual_Income\"           \n [9] \"Monthly_Inhand_Salary\"    \"Num_Bank_Accounts\"       \n[11] \"Num_Credit_Card\"          \"Interest_Rate\"           \n[13] \"Num_of_Loan\"              \"Type_of_Loan\"            \n[15] \"Delay_from_due_date\"      \"Num_of_Delayed_Payment\"  \n[17] \"Changed_Credit_Limit\"     \"Num_Credit_Inquiries\"    \n[19] \"Credit_Mix\"               \"Outstanding_Debt\"        \n[21] \"Credit_Utilization_Ratio\" \"Credit_History_Age\"      \n[23] \"Payment_of_Min_Amount\"    \"Total_EMI_per_month\"     \n[25] \"Amount_invested_monthly\"  \"Payment_Behaviour\"       \n[27] \"Monthly_Balance\"          \"Credit_Score\"            \n```\n:::\n:::\n\nFrom  the above list of columns we can observe that each row comprises of the detailed personal and behavioral information of the individual and the target column \"Credit_Score\" which indicates the credit score category in which an individual lies in.\n\nThe credit score of an individual is being divided into the following categories:\n\n::: {.cell}\n\n```{.r .cell-code}\nunique(data$Credit_Score)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Good\"     \"Standard\" \"Poor\"    \n```\n:::\n:::\n\nSo there appears to be three categories good, standard and poor and in this project we try to find the impact of various other attributes on the credit score. But from the head of the data shown above we can see some inconsistencies and absence of certain column values for some rows in the dataset. This require some preprocessing for accurate analysis.\n\n### Cleaning the dataset\nFirst we can try to identify the null fields and the number of rows that have them. If there are a significant number of rows with null fields then we'll try to fill these with relevant information, else if they occur in very small numbers we can omit them directly.\n\nThe number of rows with empty fields can be obtained as follows:\n\n::: {.cell}\n\n```{.r .cell-code}\nnrow(data[!complete.cases(data), ])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 46957\n```\n:::\n:::\n\nWe can observe that there are 46,957 rows with inconsistencies.\n\nIn this Customer_ID is the primary identifier for an individual and if it is null we'll have to omit these rows entirely.\n\n::: {.cell}\n\n```{.r .cell-code}\nnrow(data[is.na(data$Customer_ID), ])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0\n```\n:::\n:::\n\nFortunately none of the rows have an empty value for the identifier field. Now we can proceed with removing the columns that will have no affect on the final outcome. From the above set of columns the field \"Name\", \"SSN\", \"ID\" can be removed from our consideration as the field Customer_ID already identify the individual.\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- data %>%\n          select(-Name, -SSN, -ID)\n```\n:::\n\nFrom the above head of the data we can see that the Age column it is currently storing strings but ideally it should be storing integers, so now we will have to typecast the column to integer.\n\n#### Cleaning Age column\n\nFirst we'll have to check for empty age columns in the dataset:\n\n::: {.cell}\n\n```{.r .cell-code}\nnrow(data[is.na(data$Age), ])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0\n```\n:::\n:::\n\nTypecasting the Age column to integer\n\n::: {.cell}\n\n```{.r .cell-code}\ndata$Age <- as.integer(gsub(\"[^-?0-9]+\", \"\", data$Age))\n```\n:::\n\nBut here some distorted age values are unusually high, this needs to be handled, it can be done as follows:\n\nWe can handle the out of range Age values (here I assumed 100 to be the maximum age) as follows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata$Age[data$Age < 0 | data$Age > 100] <- NA\n```\n:::\n\n\nNow we replace all null values with other occurrences that have similar Customer_ID.\n\n::: {.cell}\n\n```{.r .cell-code}\ntemp <- data %>%\n          select(Customer_ID, Age)\ntemp <- na.omit(temp)\ndata <- transform(data, Age=temp$Age[match(data$Customer_ID, temp$Customer_ID)])\n```\n:::\n\nAll the age values appear to have been corrected, the summary of the Age field is as follows:\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(data$Age)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  14.00   24.00   33.00   33.03   41.00   95.00 \n```\n:::\n:::\n\n\n#### Cleaning other columns\n\nThe Annual income column appears to have the same problem as that of Age, so similar processing steps can be taken:\n\n::: {.cell}\n\n```{.r .cell-code}\ndata$Annual_Income <- as.numeric(gsub(\"[^-?0-9.-]+\", \"\", data$Annual_Income))\n```\n:::\n\n\nNow we clean the other columns that are already in the right data type but were fed as NA\n\n::: {.cell}\n\n```{.r .cell-code}\n## Replacing the unusually high values with a median values\ndata$Num_Bank_Accounts[data$Num_Bank_Accounts > 100] <- 5\ndata$Num_Credit_Card[data$Num_Credit_Card > 100] <- 5\ndata$Interest_Rate[data$Interest_Rate > 100] <- 13\ndata$Type_of_Loan[is.na(data$Type_of_Loan)] <- \"Not Specified\"\ndata$Monthly_Balance[is.na(data$Monthly_Balance)] <- 0\ndata$Num_Credit_Inquiries[is.na(data$Num_Credit_Inquiries)] <- 6\ndata$Monthly_Inhand_Salary[is.na(data$Monthly_Inhand_Salary)] <- 0\ndata$Monthly_Balance[is.na(data$Monthly_Balance)] <- 0\n```\n:::\n\n\nNow we'll need to convert the numerical attributes that are wrongly read as string to numerical values:\n\n::: {.cell}\n\n```{.r .cell-code}\n# for months with na I assumed that the salary was not credited\n\ndata$Num_of_Loan <- as.integer(gsub(\"[^-?0-9]+\", \"\", data$Num_of_Loan))\ndata$Changed_Credit_Limit <- as.numeric(gsub(\"[^-?0-9.-]+\", \"\", data$Changed_Credit_Limit))\ndata$Changed_Credit_Limit[is.na(data$Changed_Credit_Limit)] <- 9.4 # the median of the entire dataset\ndata$Type_of_Loan[is.na(data$Type_of_Loan)] <- \"Not Specified\"\ndata$Num_of_Delayed_Payment <- as.integer(gsub(\"[^-?0-9]+\", \"\", data$Num_of_Delayed_Payment))\ndata$Num_of_Delayed_Payment[is.na(data$Num_of_Delayed_Payment)] <- 0\ndata$Num_Credit_Inquiries[is.na(data$Num_Credit_Inquiries)] <- 0\ndata$Outstanding_Debt <- as.numeric(gsub(\"[^-?0-9.-]+\", \"\", data$Outstanding_Debt))\ndata$Amount_invested_monthly <- as.numeric(gsub(\"[^-?0-9.-]+\", \"\", data$Amount_invested_monthly))\ndata$Amount_invested_monthly[is.na(data$Amount_invested_monthly)] <- 0\n```\n:::\n\n\nNow we are left with the pre-processing of the \"Credit_History_Age\" column in the dataset. It has a unique composition of both text and numbers so I will be processing the string and generating a single integer that represents the credit history age in number of months.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngetCreditAge <- function(x) {\n  if(!is.na(x)) {\n    arr <- strsplit(x, split=\" \")\n    return (as.integer(arr[[1]][1])*12+as.integer(arr[[1]][4]))\n  }\n  else {\n    return (NA)\n  }\n}\ndata$Credit_History_Age <- sapply(data$Credit_History_Age, getCreditAge)\n```\n:::\n\nDespite all the preprocessing we can still observe some NA's in the \"Credit_History_Age\" column. Here replacing all the missing columns with zeros would not be ideal as by glancing through the dataset have a minimum of 1 month's credit history. So utilizing the same strategy as above we can replace all such columns with median (219 months) of all the values in the dataset.\n\n::: {.cell}\n\n```{.r .cell-code}\ndata$Credit_History_Age[is.na(data$Credit_History_Age)] <- 219\n```\n:::\n\n\nThe total number of complete instances after preprocessing is as follows:\n\n::: {.cell}\n\n```{.r .cell-code}\nnrow(data[complete.cases(data$Credit_History_Age), ])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 100000\n```\n:::\n:::\n\nSo we managed to obtain all 100,000 instance with a complete set of attributes. The head of the dataset is as follows:\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(data, 100)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Customer_ID\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Month\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Age\"],\"name\":[3],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Occupation\"],\"name\":[4],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Annual_Income\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Monthly_Inhand_Salary\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Num_Bank_Accounts\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Num_Credit_Card\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Interest_Rate\"],\"name\":[9],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Num_of_Loan\"],\"name\":[10],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Type_of_Loan\"],\"name\":[11],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Delay_from_due_date\"],\"name\":[12],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Num_of_Delayed_Payment\"],\"name\":[13],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Changed_Credit_Limit\"],\"name\":[14],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Num_Credit_Inquiries\"],\"name\":[15],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Credit_Mix\"],\"name\":[16],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Outstanding_Debt\"],\"name\":[17],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Credit_Utilization_Ratio\"],\"name\":[18],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Credit_History_Age\"],\"name\":[19],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Payment_of_Min_Amount\"],\"name\":[20],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Total_EMI_per_month\"],\"name\":[21],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Amount_invested_monthly\"],\"name\":[22],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Payment_Behaviour\"],\"name\":[23],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Monthly_Balance\"],\"name\":[24],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Credit_Score\"],\"name\":[25],\"type\":[\"chr\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"CUS_0xd40\",\"2\":\"January\",\"3\":\"23\",\"4\":\"Scientist\",\"5\":\"19114.12\",\"6\":\"1824.843\",\"7\":\"3\",\"8\":\"4\",\"9\":\"3\",\"10\":\"4\",\"11\":\"Auto Loan, Credit-Builder Loan, Personal Loan, and Home Equity Loan\",\"12\":\"3\",\"13\":\"7\",\"14\":\"11.27\",\"15\":\"4\",\"16\":\"_\",\"17\":\"809.98\",\"18\":\"26.82262\",\"19\":\"265\",\"20\":\"No\",\"21\":\"49.57495\",\"22\":\"80.41530\",\"23\":\"High_spent_Small_value_payments\",\"24\":\"312.49409\",\"25\":\"Good\",\"_rn_\":\"1\"},{\"1\":\"CUS_0xd40\",\"2\":\"February\",\"3\":\"23\",\"4\":\"Scientist\",\"5\":\"19114.12\",\"6\":\"0.000\",\"7\":\"3\",\"8\":\"4\",\"9\":\"3\",\"10\":\"4\",\"11\":\"Auto Loan, Credit-Builder Loan, Personal Loan, and Home Equity Loan\",\"12\":\"-1\",\"13\":\"0\",\"14\":\"11.27\",\"15\":\"4\",\"16\":\"Good\",\"17\":\"809.98\",\"18\":\"31.94496\",\"19\":\"219\",\"20\":\"No\",\"21\":\"49.57495\",\"22\":\"118.28022\",\"23\":\"Low_spent_Large_value_payments\",\"24\":\"284.62916\",\"25\":\"Good\",\"_rn_\":\"2\"},{\"1\":\"CUS_0xd40\",\"2\":\"March\",\"3\":\"23\",\"4\":\"Scientist\",\"5\":\"19114.12\",\"6\":\"0.000\",\"7\":\"3\",\"8\":\"4\",\"9\":\"3\",\"10\":\"4\",\"11\":\"Auto Loan, Credit-Builder Loan, Personal Loan, and Home Equity Loan\",\"12\":\"3\",\"13\":\"7\",\"14\":\"9.40\",\"15\":\"4\",\"16\":\"Good\",\"17\":\"809.98\",\"18\":\"28.60935\",\"19\":\"267\",\"20\":\"No\",\"21\":\"49.57495\",\"22\":\"81.69952\",\"23\":\"Low_spent_Medium_value_payments\",\"24\":\"331.20986\",\"25\":\"Good\",\"_rn_\":\"3\"},{\"1\":\"CUS_0xd40\",\"2\":\"April\",\"3\":\"23\",\"4\":\"Scientist\",\"5\":\"19114.12\",\"6\":\"0.000\",\"7\":\"3\",\"8\":\"4\",\"9\":\"3\",\"10\":\"4\",\"11\":\"Auto Loan, Credit-Builder Loan, Personal Loan, and Home Equity Loan\",\"12\":\"5\",\"13\":\"4\",\"14\":\"6.27\",\"15\":\"4\",\"16\":\"Good\",\"17\":\"809.98\",\"18\":\"31.37786\",\"19\":\"268\",\"20\":\"No\",\"21\":\"49.57495\",\"22\":\"199.45807\",\"23\":\"Low_spent_Small_value_payments\",\"24\":\"223.45131\",\"25\":\"Good\",\"_rn_\":\"4\"},{\"1\":\"CUS_0xd40\",\"2\":\"May\",\"3\":\"23\",\"4\":\"Scientist\",\"5\":\"19114.12\",\"6\":\"1824.843\",\"7\":\"3\",\"8\":\"4\",\"9\":\"3\",\"10\":\"4\",\"11\":\"Auto Loan, Credit-Builder Loan, Personal Loan, and Home Equity Loan\",\"12\":\"6\",\"13\":\"0\",\"14\":\"11.27\",\"15\":\"4\",\"16\":\"Good\",\"17\":\"809.98\",\"18\":\"24.79735\",\"19\":\"269\",\"20\":\"No\",\"21\":\"49.57495\",\"22\":\"41.42015\",\"23\":\"High_spent_Medium_value_payments\",\"24\":\"341.48923\",\"25\":\"Good\",\"_rn_\":\"5\"},{\"1\":\"CUS_0xd40\",\"2\":\"June\",\"3\":\"23\",\"4\":\"Scientist\",\"5\":\"19114.12\",\"6\":\"0.000\",\"7\":\"3\",\"8\":\"4\",\"9\":\"3\",\"10\":\"4\",\"11\":\"Auto Loan, Credit-Builder Loan, Personal Loan, and Home Equity Loan\",\"12\":\"8\",\"13\":\"4\",\"14\":\"9.27\",\"15\":\"4\",\"16\":\"Good\",\"17\":\"809.98\",\"18\":\"27.26226\",\"19\":\"270\",\"20\":\"No\",\"21\":\"49.57495\",\"22\":\"62.43017\",\"23\":\"!@9#%8\",\"24\":\"340.47921\",\"25\":\"Good\",\"_rn_\":\"6\"},{\"1\":\"CUS_0xd40\",\"2\":\"July\",\"3\":\"23\",\"4\":\"Scientist\",\"5\":\"19114.12\",\"6\":\"1824.843\",\"7\":\"3\",\"8\":\"4\",\"9\":\"3\",\"10\":\"4\",\"11\":\"Auto Loan, Credit-Builder Loan, Personal Loan, and Home Equity Loan\",\"12\":\"3\",\"13\":\"8\",\"14\":\"11.27\",\"15\":\"4\",\"16\":\"Good\",\"17\":\"809.98\",\"18\":\"22.53759\",\"19\":\"271\",\"20\":\"No\",\"21\":\"49.57495\",\"22\":\"178.34407\",\"23\":\"Low_spent_Small_value_payments\",\"24\":\"244.56532\",\"25\":\"Good\",\"_rn_\":\"7\"},{\"1\":\"CUS_0xd40\",\"2\":\"August\",\"3\":\"23\",\"4\":\"Scientist\",\"5\":\"19114.12\",\"6\":\"1824.843\",\"7\":\"3\",\"8\":\"4\",\"9\":\"3\",\"10\":\"4\",\"11\":\"Auto Loan, Credit-Builder Loan, Personal Loan, and Home Equity Loan\",\"12\":\"3\",\"13\":\"6\",\"14\":\"11.27\",\"15\":\"4\",\"16\":\"Good\",\"17\":\"809.98\",\"18\":\"23.93379\",\"19\":\"219\",\"20\":\"No\",\"21\":\"49.57495\",\"22\":\"24.78522\",\"23\":\"High_spent_Medium_value_payments\",\"24\":\"358.12417\",\"25\":\"Standard\",\"_rn_\":\"8\"},{\"1\":\"CUS_0x21b1\",\"2\":\"January\",\"3\":\"28\",\"4\":\"_______\",\"5\":\"34847.84\",\"6\":\"3037.987\",\"7\":\"2\",\"8\":\"4\",\"9\":\"6\",\"10\":\"1\",\"11\":\"Credit-Builder Loan\",\"12\":\"3\",\"13\":\"4\",\"14\":\"5.42\",\"15\":\"2\",\"16\":\"Good\",\"17\":\"605.03\",\"18\":\"24.46403\",\"19\":\"319\",\"20\":\"No\",\"21\":\"18.81621\",\"22\":\"104.29183\",\"23\":\"Low_spent_Small_value_payments\",\"24\":\"470.69063\",\"25\":\"Standard\",\"_rn_\":\"9\"},{\"1\":\"CUS_0x21b1\",\"2\":\"February\",\"3\":\"28\",\"4\":\"Teacher\",\"5\":\"34847.84\",\"6\":\"3037.987\",\"7\":\"2\",\"8\":\"4\",\"9\":\"6\",\"10\":\"1\",\"11\":\"Credit-Builder Loan\",\"12\":\"7\",\"13\":\"1\",\"14\":\"7.42\",\"15\":\"2\",\"16\":\"Good\",\"17\":\"605.03\",\"18\":\"38.55085\",\"19\":\"320\",\"20\":\"No\",\"21\":\"18.81621\",\"22\":\"40.39124\",\"23\":\"High_spent_Large_value_payments\",\"24\":\"484.59121\",\"25\":\"Good\",\"_rn_\":\"10\"},{\"1\":\"CUS_0x21b1\",\"2\":\"March\",\"3\":\"28\",\"4\":\"Teacher\",\"5\":\"34847.84\",\"6\":\"3037.987\",\"7\":\"2\",\"8\":\"5\",\"9\":\"6\",\"10\":\"1\",\"11\":\"Credit-Builder Loan\",\"12\":\"3\",\"13\":\"-1\",\"14\":\"5.42\",\"15\":\"2\",\"16\":\"_\",\"17\":\"605.03\",\"18\":\"33.22495\",\"19\":\"321\",\"20\":\"No\",\"21\":\"18.81621\",\"22\":\"58.51598\",\"23\":\"High_spent_Large_value_payments\",\"24\":\"466.46648\",\"25\":\"Standard\",\"_rn_\":\"11\"},{\"1\":\"CUS_0x21b1\",\"2\":\"April\",\"3\":\"28\",\"4\":\"Teacher\",\"5\":\"34847.84\",\"6\":\"0.000\",\"7\":\"2\",\"8\":\"4\",\"9\":\"6\",\"10\":\"1\",\"11\":\"Credit-Builder Loan\",\"12\":\"3\",\"13\":\"3\",\"14\":\"5.42\",\"15\":\"2\",\"16\":\"Good\",\"17\":\"605.03\",\"18\":\"39.18266\",\"19\":\"322\",\"20\":\"No\",\"21\":\"18.81621\",\"22\":\"99.30623\",\"23\":\"Low_spent_Medium_value_payments\",\"24\":\"465.67622\",\"25\":\"Good\",\"_rn_\":\"12\"},{\"1\":\"CUS_0x21b1\",\"2\":\"May\",\"3\":\"28\",\"4\":\"Teacher\",\"5\":\"34847.84\",\"6\":\"3037.987\",\"7\":\"2\",\"8\":\"4\",\"9\":\"6\",\"10\":\"1\",\"11\":\"Credit-Builder Loan\",\"12\":\"3\",\"13\":\"1\",\"14\":\"6.42\",\"15\":\"2\",\"16\":\"Good\",\"17\":\"605.03\",\"18\":\"34.97789\",\"19\":\"323\",\"20\":\"No\",\"21\":\"18.81621\",\"22\":\"130.11542\",\"23\":\"Low_spent_Small_value_payments\",\"24\":\"444.86703\",\"25\":\"Good\",\"_rn_\":\"13\"},{\"1\":\"CUS_0x21b1\",\"2\":\"June\",\"3\":\"28\",\"4\":\"Teacher\",\"5\":\"34847.84\",\"6\":\"3037.987\",\"7\":\"2\",\"8\":\"4\",\"9\":\"6\",\"10\":\"1\",\"11\":\"Credit-Builder Loan\",\"12\":\"3\",\"13\":\"0\",\"14\":\"5.42\",\"15\":\"2\",\"16\":\"Good\",\"17\":\"605.03\",\"18\":\"33.38101\",\"19\":\"324\",\"20\":\"No\",\"21\":\"18.81621\",\"22\":\"43.47719\",\"23\":\"High_spent_Large_value_payments\",\"24\":\"481.50526\",\"25\":\"Good\",\"_rn_\":\"14\"},{\"1\":\"CUS_0x21b1\",\"2\":\"July\",\"3\":\"28\",\"4\":\"Teacher\",\"5\":\"34847.84\",\"6\":\"0.000\",\"7\":\"2\",\"8\":\"4\",\"9\":\"6\",\"10\":\"1\",\"11\":\"Credit-Builder Loan\",\"12\":\"3\",\"13\":\"4\",\"14\":\"5.42\",\"15\":\"2\",\"16\":\"Good\",\"17\":\"605.03\",\"18\":\"31.13170\",\"19\":\"325\",\"20\":\"NM\",\"21\":\"18.81621\",\"22\":\"70.10177\",\"23\":\"High_spent_Medium_value_payments\",\"24\":\"464.88068\",\"25\":\"Good\",\"_rn_\":\"15\"},{\"1\":\"CUS_0x21b1\",\"2\":\"August\",\"3\":\"28\",\"4\":\"Teacher\",\"5\":\"34847.84\",\"6\":\"3037.987\",\"7\":\"2\",\"8\":\"4\",\"9\":\"6\",\"10\":\"1\",\"11\":\"Credit-Builder Loan\",\"12\":\"3\",\"13\":\"4\",\"14\":\"5.42\",\"15\":\"2\",\"16\":\"Good\",\"17\":\"605.03\",\"18\":\"32.93386\",\"19\":\"326\",\"20\":\"No\",\"21\":\"18.81621\",\"22\":\"218.90434\",\"23\":\"Low_spent_Small_value_payments\",\"24\":\"356.07811\",\"25\":\"Good\",\"_rn_\":\"16\"},{\"1\":\"CUS_0x2dbc\",\"2\":\"January\",\"3\":\"34\",\"4\":\"_______\",\"5\":\"143162.64\",\"6\":\"12187.220\",\"7\":\"1\",\"8\":\"5\",\"9\":\"8\",\"10\":\"3\",\"11\":\"Auto Loan, Auto Loan, and Not Specified\",\"12\":\"5\",\"13\":\"8\",\"14\":\"7.10\",\"15\":\"3\",\"16\":\"Good\",\"17\":\"1303.01\",\"18\":\"28.61673\",\"19\":\"213\",\"20\":\"No\",\"21\":\"246.99232\",\"22\":\"168.41370\",\"23\":\"!@9#%8\",\"24\":\"1043.31598\",\"25\":\"Good\",\"_rn_\":\"17\"},{\"1\":\"CUS_0x2dbc\",\"2\":\"February\",\"3\":\"34\",\"4\":\"Engineer\",\"5\":\"143162.64\",\"6\":\"12187.220\",\"7\":\"1\",\"8\":\"5\",\"9\":\"8\",\"10\":\"3\",\"11\":\"Auto Loan, Auto Loan, and Not Specified\",\"12\":\"13\",\"13\":\"6\",\"14\":\"7.10\",\"15\":\"3\",\"16\":\"Good\",\"17\":\"1303.01\",\"18\":\"41.70257\",\"19\":\"214\",\"20\":\"No\",\"21\":\"246.99232\",\"22\":\"232.86038\",\"23\":\"High_spent_Small_value_payments\",\"24\":\"998.86930\",\"25\":\"Good\",\"_rn_\":\"18\"},{\"1\":\"CUS_0x2dbc\",\"2\":\"March\",\"3\":\"34\",\"4\":\"_______\",\"5\":\"143162.64\",\"6\":\"0.000\",\"7\":\"1\",\"8\":\"5\",\"9\":\"8\",\"10\":\"3\",\"11\":\"Auto Loan, Auto Loan, and Not Specified\",\"12\":\"8\",\"13\":\"7\",\"14\":\"11.10\",\"15\":\"6\",\"16\":\"Good\",\"17\":\"1303.01\",\"18\":\"26.51982\",\"19\":\"215\",\"20\":\"No\",\"21\":\"246.99232\",\"22\":\"10000.00000\",\"23\":\"High_spent_Small_value_payments\",\"24\":\"715.74137\",\"25\":\"Good\",\"_rn_\":\"19\"},{\"1\":\"CUS_0x2dbc\",\"2\":\"April\",\"3\":\"34\",\"4\":\"Engineer\",\"5\":\"143162.64\",\"6\":\"12187.220\",\"7\":\"1\",\"8\":\"5\",\"9\":\"8\",\"10\":\"3\",\"11\":\"Auto Loan, Auto Loan, and Not Specified\",\"12\":\"8\",\"13\":\"5\",\"14\":\"9.10\",\"15\":\"3\",\"16\":\"_\",\"17\":\"1303.01\",\"18\":\"39.50165\",\"19\":\"219\",\"20\":\"No\",\"21\":\"246.99232\",\"22\":\"825.21627\",\"23\":\"Low_spent_Medium_value_payments\",\"24\":\"426.51341\",\"25\":\"Good\",\"_rn_\":\"20\"},{\"1\":\"CUS_0x2dbc\",\"2\":\"May\",\"3\":\"34\",\"4\":\"_______\",\"5\":\"143162.64\",\"6\":\"12187.220\",\"7\":\"1\",\"8\":\"5\",\"9\":\"8\",\"10\":\"3\",\"11\":\"Auto Loan, Auto Loan, and Not Specified\",\"12\":\"10\",\"13\":\"5\",\"14\":\"7.10\",\"15\":\"3\",\"16\":\"Good\",\"17\":\"1303.01\",\"18\":\"31.37615\",\"19\":\"217\",\"20\":\"No\",\"21\":\"246.99232\",\"22\":\"430.94753\",\"23\":\"Low_spent_Large_value_payments\",\"24\":\"810.78215\",\"25\":\"Good\",\"_rn_\":\"21\"},{\"1\":\"CUS_0x2dbc\",\"2\":\"June\",\"3\":\"34\",\"4\":\"Engineer\",\"5\":\"143162.64\",\"6\":\"12187.220\",\"7\":\"1\",\"8\":\"5\",\"9\":\"8\",\"10\":\"967\",\"11\":\"Auto Loan, Auto Loan, and Not Specified\",\"12\":\"8\",\"13\":\"6\",\"14\":\"7.10\",\"15\":\"3\",\"16\":\"Good\",\"17\":\"1303.01\",\"18\":\"39.78399\",\"19\":\"218\",\"20\":\"No\",\"21\":\"246.99232\",\"22\":\"257.80810\",\"23\":\"High_spent_Medium_value_payments\",\"24\":\"963.92158\",\"25\":\"Good\",\"_rn_\":\"22\"},{\"1\":\"CUS_0x2dbc\",\"2\":\"July\",\"3\":\"34\",\"4\":\"Engineer\",\"5\":\"143162.64\",\"6\":\"12187.220\",\"7\":\"1\",\"8\":\"5\",\"9\":\"8\",\"10\":\"3\",\"11\":\"Auto Loan, Auto Loan, and Not Specified\",\"12\":\"8\",\"13\":\"6\",\"14\":\"7.10\",\"15\":\"3\",\"16\":\"Good\",\"17\":\"1303.01\",\"18\":\"38.06862\",\"19\":\"219\",\"20\":\"No\",\"21\":\"246.99232\",\"22\":\"263.17416\",\"23\":\"High_spent_Small_value_payments\",\"24\":\"968.55552\",\"25\":\"Standard\",\"_rn_\":\"23\"},{\"1\":\"CUS_0x2dbc\",\"2\":\"August\",\"3\":\"34\",\"4\":\"Engineer\",\"5\":\"143162.64\",\"6\":\"12187.220\",\"7\":\"1\",\"8\":\"5\",\"9\":\"8\",\"10\":\"3\",\"11\":\"Auto Loan, Auto Loan, and Not Specified\",\"12\":\"8\",\"13\":\"6\",\"14\":\"7.10\",\"15\":\"3\",\"16\":\"Good\",\"17\":\"1303.01\",\"18\":\"38.37475\",\"19\":\"220\",\"20\":\"No\",\"21\":\"246.99232\",\"22\":\"10000.00000\",\"23\":\"High_spent_Small_value_payments\",\"24\":\"895.49458\",\"25\":\"Standard\",\"_rn_\":\"24\"},{\"1\":\"CUS_0xb891\",\"2\":\"January\",\"3\":\"54\",\"4\":\"Entrepreneur\",\"5\":\"30689.89\",\"6\":\"2612.491\",\"7\":\"2\",\"8\":\"5\",\"9\":\"4\",\"10\":\"1\",\"11\":\"Not Specified\",\"12\":\"0\",\"13\":\"6\",\"14\":\"1.99\",\"15\":\"4\",\"16\":\"Good\",\"17\":\"632.46\",\"18\":\"26.54423\",\"19\":\"207\",\"20\":\"No\",\"21\":\"16.41545\",\"22\":\"81.22886\",\"23\":\"Low_spent_Large_value_payments\",\"24\":\"433.60477\",\"25\":\"Standard\",\"_rn_\":\"25\"},{\"1\":\"CUS_0xb891\",\"2\":\"February\",\"3\":\"54\",\"4\":\"Entrepreneur\",\"5\":\"30689.89\",\"6\":\"2612.491\",\"7\":\"2\",\"8\":\"5\",\"9\":\"4\",\"10\":\"1\",\"11\":\"Not Specified\",\"12\":\"5\",\"13\":\"3\",\"14\":\"1.99\",\"15\":\"4\",\"16\":\"Good\",\"17\":\"632.46\",\"18\":\"35.27998\",\"19\":\"208\",\"20\":\"No\",\"21\":\"16.41545\",\"22\":\"124.88182\",\"23\":\"Low_spent_Small_value_payments\",\"24\":\"409.95181\",\"25\":\"Standard\",\"_rn_\":\"26\"},{\"1\":\"CUS_0xb891\",\"2\":\"March\",\"3\":\"54\",\"4\":\"Entrepreneur\",\"5\":\"30689.89\",\"6\":\"2612.491\",\"7\":\"2\",\"8\":\"5\",\"9\":\"4\",\"10\":\"1\",\"11\":\"Not Specified\",\"12\":\"3\",\"13\":\"9\",\"14\":\"1.99\",\"15\":\"4\",\"16\":\"Good\",\"17\":\"632.46\",\"18\":\"32.30116\",\"19\":\"209\",\"20\":\"NM\",\"21\":\"16.41545\",\"22\":\"83.40651\",\"23\":\"High_spent_Medium_value_payments\",\"24\":\"411.42712\",\"25\":\"Standard\",\"_rn_\":\"27\"},{\"1\":\"CUS_0xb891\",\"2\":\"April\",\"3\":\"54\",\"4\":\"Entrepreneur\",\"5\":\"30689.89\",\"6\":\"2612.491\",\"7\":\"2\",\"8\":\"5\",\"9\":\"4\",\"10\":\"1\",\"11\":\"Not Specified\",\"12\":\"7\",\"13\":\"6\",\"14\":\"-2.01\",\"15\":\"4\",\"16\":\"Good\",\"17\":\"632.46\",\"18\":\"38.13235\",\"19\":\"210\",\"20\":\"No\",\"21\":\"16.41545\",\"22\":\"272.33404\",\"23\":\"Low_spent_Small_value_payments\",\"24\":\"262.49959\",\"25\":\"Standard\",\"_rn_\":\"28\"},{\"1\":\"CUS_0xb891\",\"2\":\"May\",\"3\":\"54\",\"4\":\"Entrepreneur\",\"5\":\"30689.89\",\"6\":\"2612.491\",\"7\":\"2\",\"8\":\"5\",\"9\":\"4\",\"10\":\"1\",\"11\":\"Not Specified\",\"12\":\"5\",\"13\":\"6\",\"14\":\"-1.01\",\"15\":\"4\",\"16\":\"Good\",\"17\":\"632.46\",\"18\":\"41.15432\",\"19\":\"211\",\"20\":\"No\",\"21\":\"16.41545\",\"22\":\"10000.00000\",\"23\":\"Low_spent_Large_value_payments\",\"24\":\"359.37492\",\"25\":\"Standard\",\"_rn_\":\"29\"},{\"1\":\"CUS_0xb891\",\"2\":\"June\",\"3\":\"54\",\"4\":\"_______\",\"5\":\"30689.89\",\"6\":\"2612.491\",\"7\":\"2\",\"8\":\"5\",\"9\":\"4\",\"10\":\"1\",\"11\":\"Not Specified\",\"12\":\"5\",\"13\":\"6\",\"14\":\"-3.01\",\"15\":\"4\",\"16\":\"_\",\"17\":\"632.46\",\"18\":\"27.44542\",\"19\":\"212\",\"20\":\"No\",\"21\":\"16.41545\",\"22\":\"84.95285\",\"23\":\"High_spent_Small_value_payments\",\"24\":\"419.88078\",\"25\":\"Standard\",\"_rn_\":\"30\"},{\"1\":\"CUS_0xb891\",\"2\":\"July\",\"3\":\"54\",\"4\":\"Entrepreneur\",\"5\":\"30689.89\",\"6\":\"2612.491\",\"7\":\"2\",\"8\":\"5\",\"9\":\"4\",\"10\":\"1\",\"11\":\"Not Specified\",\"12\":\"5\",\"13\":\"0\",\"14\":\"1.99\",\"15\":\"4\",\"16\":\"Good\",\"17\":\"632.46\",\"18\":\"26.05640\",\"19\":\"213\",\"20\":\"No\",\"21\":\"16.41545\",\"22\":\"71.28367\",\"23\":\"Low_spent_Large_value_payments\",\"24\":\"443.54996\",\"25\":\"Standard\",\"_rn_\":\"31\"},{\"1\":\"CUS_0xb891\",\"2\":\"August\",\"3\":\"54\",\"4\":\"Entrepreneur\",\"5\":\"30689.89\",\"6\":\"2612.491\",\"7\":\"2\",\"8\":\"5\",\"9\":\"4\",\"10\":\"-100\",\"11\":\"Not Specified\",\"12\":\"4\",\"13\":\"9\",\"14\":\"1.99\",\"15\":\"4\",\"16\":\"Good\",\"17\":\"632.46\",\"18\":\"27.33251\",\"19\":\"214\",\"20\":\"No\",\"21\":\"16.41545\",\"22\":\"125.61725\",\"23\":\"High_spent_Small_value_payments\",\"24\":\"379.21638\",\"25\":\"Standard\",\"_rn_\":\"32\"},{\"1\":\"CUS_0x1cdb\",\"2\":\"January\",\"3\":\"21\",\"4\":\"Developer\",\"5\":\"35547.71\",\"6\":\"2853.309\",\"7\":\"7\",\"8\":\"5\",\"9\":\"5\",\"10\":\"0\",\"11\":\"Not Specified\",\"12\":\"5\",\"13\":\"0\",\"14\":\"2.58\",\"15\":\"4\",\"16\":\"Standard\",\"17\":\"943.86\",\"18\":\"39.79776\",\"19\":\"368\",\"20\":\"Yes\",\"21\":\"0.00000\",\"22\":\"276.72539\",\"23\":\"!@9#%8\",\"24\":\"288.60552\",\"25\":\"Standard\",\"_rn_\":\"33\"},{\"1\":\"CUS_0x1cdb\",\"2\":\"February\",\"3\":\"21\",\"4\":\"Developer\",\"5\":\"35547.71\",\"6\":\"0.000\",\"7\":\"7\",\"8\":\"5\",\"9\":\"5\",\"10\":\"0\",\"11\":\"Not Specified\",\"12\":\"9\",\"13\":\"0\",\"14\":\"2.58\",\"15\":\"4\",\"16\":\"Standard\",\"17\":\"943.86\",\"18\":\"27.02036\",\"19\":\"369\",\"20\":\"NM\",\"21\":\"0.00000\",\"22\":\"74.44364\",\"23\":\"High_spent_Medium_value_payments\",\"24\":\"460.88728\",\"25\":\"Standard\",\"_rn_\":\"34\"},{\"1\":\"CUS_0x1cdb\",\"2\":\"March\",\"3\":\"21\",\"4\":\"Developer\",\"5\":\"35547.71\",\"6\":\"2853.309\",\"7\":\"7\",\"8\":\"5\",\"9\":\"5\",\"10\":\"-100\",\"11\":\"Not Specified\",\"12\":\"5\",\"13\":\"12\",\"14\":\"2.58\",\"15\":\"4\",\"16\":\"Standard\",\"17\":\"943.86\",\"18\":\"23.46230\",\"19\":\"370\",\"20\":\"Yes\",\"21\":\"0.00000\",\"22\":\"173.13865\",\"23\":\"Low_spent_Medium_value_payments\",\"24\":\"392.19227\",\"25\":\"Standard\",\"_rn_\":\"35\"},{\"1\":\"CUS_0x1cdb\",\"2\":\"April\",\"3\":\"21\",\"4\":\"Developer\",\"5\":\"35547.71\",\"6\":\"2853.309\",\"7\":\"7\",\"8\":\"5\",\"9\":\"5\",\"10\":\"0\",\"11\":\"Not Specified\",\"12\":\"1\",\"13\":\"15\",\"14\":\"2.58\",\"15\":\"4\",\"16\":\"_\",\"17\":\"943.86\",\"18\":\"28.92495\",\"19\":\"371\",\"20\":\"Yes\",\"21\":\"0.00000\",\"22\":\"96.78549\",\"23\":\"High_spent_Medium_value_payments\",\"24\":\"438.54543\",\"25\":\"Standard\",\"_rn_\":\"36\"},{\"1\":\"CUS_0x1cdb\",\"2\":\"May\",\"3\":\"21\",\"4\":\"Developer\",\"5\":\"35547.71\",\"6\":\"2853.309\",\"7\":\"7\",\"8\":\"5\",\"9\":\"5\",\"10\":\"0\",\"11\":\"Not Specified\",\"12\":\"9\",\"13\":\"17\",\"14\":\"2.58\",\"15\":\"4\",\"16\":\"_\",\"17\":\"943.86\",\"18\":\"41.77619\",\"19\":\"372\",\"20\":\"Yes\",\"21\":\"0.00000\",\"22\":\"62.72328\",\"23\":\"High_spent_Small_value_payments\",\"24\":\"482.60764\",\"25\":\"Standard\",\"_rn_\":\"37\"},{\"1\":\"CUS_0x1cdb\",\"2\":\"June\",\"3\":\"21\",\"4\":\"Developer\",\"5\":\"35547.71\",\"6\":\"0.000\",\"7\":\"7\",\"8\":\"5\",\"9\":\"5\",\"10\":\"0\",\"11\":\"Not Specified\",\"12\":\"5\",\"13\":\"15\",\"14\":\"2.58\",\"15\":\"4\",\"16\":\"Standard\",\"17\":\"943.86\",\"18\":\"29.21756\",\"19\":\"373\",\"20\":\"Yes\",\"21\":\"0.00000\",\"22\":\"37.64364\",\"23\":\"High_spent_Medium_value_payments\",\"24\":\"497.68728\",\"25\":\"Standard\",\"_rn_\":\"38\"},{\"1\":\"CUS_0x1cdb\",\"2\":\"July\",\"3\":\"21\",\"4\":\"Developer\",\"5\":\"35547.71\",\"6\":\"2853.309\",\"7\":\"7\",\"8\":\"5\",\"9\":\"5\",\"10\":\"0\",\"11\":\"Not Specified\",\"12\":\"10\",\"13\":\"15\",\"14\":\"2.58\",\"15\":\"4\",\"16\":\"Standard\",\"17\":\"943.86\",\"18\":\"26.26382\",\"19\":\"374\",\"20\":\"Yes\",\"21\":\"0.00000\",\"22\":\"181.01198\",\"23\":\"Low_spent_Small_value_payments\",\"24\":\"394.31893\",\"25\":\"Standard\",\"_rn_\":\"39\"},{\"1\":\"CUS_0x1cdb\",\"2\":\"August\",\"3\":\"21\",\"4\":\"Developer\",\"5\":\"35547.71\",\"6\":\"2853.309\",\"7\":\"7\",\"8\":\"5\",\"9\":\"5\",\"10\":\"-100\",\"11\":\"Not Specified\",\"12\":\"1\",\"13\":\"15\",\"14\":\"2.58\",\"15\":\"4\",\"16\":\"Standard\",\"17\":\"943.86\",\"18\":\"25.86292\",\"19\":\"375\",\"20\":\"Yes\",\"21\":\"0.00000\",\"22\":\"181.33090\",\"23\":\"High_spent_Small_value_payments\",\"24\":\"364.00002\",\"25\":\"Standard\",\"_rn_\":\"40\"},{\"1\":\"CUS_0x95ee\",\"2\":\"January\",\"3\":\"31\",\"4\":\"Lawyer\",\"5\":\"73928.46\",\"6\":\"0.000\",\"7\":\"4\",\"8\":\"5\",\"9\":\"8\",\"10\":\"0\",\"11\":\"Not Specified\",\"12\":\"12\",\"13\":\"10\",\"14\":\"10.14\",\"15\":\"2\",\"16\":\"Good\",\"17\":\"548.20\",\"18\":\"39.96269\",\"19\":\"219\",\"20\":\"No\",\"21\":\"15015.00000\",\"22\":\"98.67441\",\"23\":\"High_spent_Large_value_payments\",\"24\":\"740.19609\",\"25\":\"Good\",\"_rn_\":\"41\"},{\"1\":\"CUS_0x95ee\",\"2\":\"February\",\"3\":\"31\",\"4\":\"_______\",\"5\":\"73928.46\",\"6\":\"5988.705\",\"7\":\"4\",\"8\":\"5\",\"9\":\"8\",\"10\":\"0\",\"11\":\"Not Specified\",\"12\":\"8\",\"13\":\"7\",\"14\":\"10.14\",\"15\":\"2\",\"16\":\"Good\",\"17\":\"548.20\",\"18\":\"42.76986\",\"19\":\"384\",\"20\":\"NM\",\"21\":\"0.00000\",\"22\":\"172.93921\",\"23\":\"Low_spent_Medium_value_payments\",\"24\":\"705.93129\",\"25\":\"Good\",\"_rn_\":\"42\"},{\"1\":\"CUS_0x95ee\",\"2\":\"March\",\"3\":\"31\",\"4\":\"Lawyer\",\"5\":\"73928.46\",\"6\":\"5988.705\",\"7\":\"4\",\"8\":\"5\",\"9\":\"8\",\"10\":\"0\",\"11\":\"Not Specified\",\"12\":\"8\",\"13\":\"7\",\"14\":\"10.14\",\"15\":\"2\",\"16\":\"Good\",\"17\":\"548.20\",\"18\":\"40.71219\",\"19\":\"219\",\"20\":\"No\",\"21\":\"0.00000\",\"22\":\"150.05973\",\"23\":\"High_spent_Medium_value_payments\",\"24\":\"698.81077\",\"25\":\"Good\",\"_rn_\":\"43\"},{\"1\":\"CUS_0x95ee\",\"2\":\"April\",\"3\":\"31\",\"4\":\"Lawyer\",\"5\":\"73928.46\",\"6\":\"5988.705\",\"7\":\"4\",\"8\":\"5\",\"9\":\"8\",\"10\":\"0\",\"11\":\"Not Specified\",\"12\":\"8\",\"13\":\"7\",\"14\":\"10.14\",\"15\":\"2\",\"16\":\"Good\",\"17\":\"548.20\",\"18\":\"30.20166\",\"19\":\"386\",\"20\":\"No\",\"21\":\"0.00000\",\"22\":\"618.20239\",\"23\":\"Low_spent_Small_value_payments\",\"24\":\"270.66811\",\"25\":\"Good\",\"_rn_\":\"44\"},{\"1\":\"CUS_0x95ee\",\"2\":\"May\",\"3\":\"31\",\"4\":\"Lawyer\",\"5\":\"73928.46\",\"6\":\"5988.705\",\"7\":\"4\",\"8\":\"5\",\"9\":\"13\",\"10\":\"0\",\"11\":\"Not Specified\",\"12\":\"11\",\"13\":\"7\",\"14\":\"10.14\",\"15\":\"2\",\"16\":\"_\",\"17\":\"548.20\",\"18\":\"26.33331\",\"19\":\"387\",\"20\":\"No\",\"21\":\"0.00000\",\"22\":\"177.95184\",\"23\":\"Low_spent_Large_value_payments\",\"24\":\"690.91866\",\"25\":\"Good\",\"_rn_\":\"45\"},{\"1\":\"CUS_0x95ee\",\"2\":\"June\",\"3\":\"31\",\"4\":\"Lawyer\",\"5\":\"73928.46\",\"6\":\"5988.705\",\"7\":\"4\",\"8\":\"5\",\"9\":\"8\",\"10\":\"0\",\"11\":\"Not Specified\",\"12\":\"7\",\"13\":\"7\",\"14\":\"10.14\",\"15\":\"2\",\"16\":\"Good\",\"17\":\"548.20\",\"18\":\"35.27544\",\"19\":\"219\",\"20\":\"No\",\"21\":\"15515.00000\",\"22\":\"235.79033\",\"23\":\"Low_spent_Large_value_payments\",\"24\":\"633.08017\",\"25\":\"Good\",\"_rn_\":\"46\"},{\"1\":\"CUS_0x95ee\",\"2\":\"July\",\"3\":\"31\",\"4\":\"Lawyer\",\"5\":\"73928.46\",\"6\":\"5988.705\",\"7\":\"4\",\"8\":\"5\",\"9\":\"8\",\"10\":\"0\",\"11\":\"Not Specified\",\"12\":\"8\",\"13\":\"4\",\"14\":\"9.14\",\"15\":\"2\",\"16\":\"_\",\"17\":\"548.20\",\"18\":\"36.62479\",\"19\":\"389\",\"20\":\"No\",\"21\":\"0.00000\",\"22\":\"348.50940\",\"23\":\"High_spent_Small_value_payments\",\"24\":\"510.36110\",\"25\":\"Standard\",\"_rn_\":\"47\"},{\"1\":\"CUS_0x95ee\",\"2\":\"August\",\"3\":\"31\",\"4\":\"Lawyer\",\"5\":\"73928.46\",\"6\":\"5988.705\",\"7\":\"4\",\"8\":\"5\",\"9\":\"8\",\"10\":\"0\",\"11\":\"Not Specified\",\"12\":\"8\",\"13\":\"7\",\"14\":\"10.14\",\"15\":\"6\",\"16\":\"Good\",\"17\":\"548.20\",\"18\":\"31.58099\",\"19\":\"390\",\"20\":\"No\",\"21\":\"0.00000\",\"22\":\"42.63559\",\"23\":\"!@9#%8\",\"24\":\"796.23491\",\"25\":\"Good\",\"_rn_\":\"48\"},{\"1\":\"CUS_0x284a\",\"2\":\"January\",\"3\":\"33\",\"4\":\"Lawyer\",\"5\":\"131313.40\",\"6\":\"11242.783\",\"7\":\"0\",\"8\":\"1\",\"9\":\"8\",\"10\":\"2\",\"11\":\"Credit-Builder Loan, and Mortgage Loan\",\"12\":\"0\",\"13\":\"3\",\"14\":\"9.34\",\"15\":\"2\",\"16\":\"Good\",\"17\":\"352.16\",\"18\":\"32.20051\",\"19\":\"367\",\"20\":\"NM\",\"21\":\"137.64461\",\"22\":\"378.17125\",\"23\":\"High_spent_Medium_value_payments\",\"24\":\"858.46247\",\"25\":\"Good\",\"_rn_\":\"49\"},{\"1\":\"CUS_0x284a\",\"2\":\"February\",\"3\":\"33\",\"4\":\"Lawyer\",\"5\":\"131313.40\",\"6\":\"11242.783\",\"7\":\"0\",\"8\":\"1\",\"9\":\"8\",\"10\":\"2\",\"11\":\"Credit-Builder Loan, and Mortgage Loan\",\"12\":\"-1\",\"13\":\"2\",\"14\":\"15.34\",\"15\":\"4\",\"16\":\"Good\",\"17\":\"352.16\",\"18\":\"31.98371\",\"19\":\"368\",\"20\":\"No\",\"21\":\"137.64461\",\"22\":\"698.87327\",\"23\":\"High_spent_Small_value_payments\",\"24\":\"547.76046\",\"25\":\"Good\",\"_rn_\":\"50\"},{\"1\":\"CUS_0x284a\",\"2\":\"March\",\"3\":\"33\",\"4\":\"Lawyer\",\"5\":\"131313.40\",\"6\":\"10469.208\",\"7\":\"0\",\"8\":\"1\",\"9\":\"8\",\"10\":\"2\",\"11\":\"Credit-Builder Loan, and Mortgage Loan\",\"12\":\"0\",\"13\":\"3\",\"14\":\"9.34\",\"15\":\"4\",\"16\":\"Good\",\"17\":\"352.16\",\"18\":\"31.80313\",\"19\":\"369\",\"20\":\"NM\",\"21\":\"911.22018\",\"22\":\"188.06432\",\"23\":\"High_spent_Large_value_payments\",\"24\":\"1038.56941\",\"25\":\"Good\",\"_rn_\":\"51\"},{\"1\":\"CUS_0x284a\",\"2\":\"April\",\"3\":\"33\",\"4\":\"Lawyer\",\"5\":\"131313.40\",\"6\":\"10469.208\",\"7\":\"0\",\"8\":\"1\",\"9\":\"8\",\"10\":\"2\",\"11\":\"Credit-Builder Loan, and Mortgage Loan\",\"12\":\"0\",\"13\":\"2\",\"14\":\"8.34\",\"15\":\"4\",\"16\":\"Good\",\"17\":\"352.16\",\"18\":\"42.64578\",\"19\":\"370\",\"20\":\"No\",\"21\":\"23834.00000\",\"22\":\"337.43496\",\"23\":\"High_spent_Medium_value_payments\",\"24\":\"899.19877\",\"25\":\"Good\",\"_rn_\":\"52\"},{\"1\":\"CUS_0x284a\",\"2\":\"May\",\"3\":\"33\",\"4\":\"Lawyer\",\"5\":\"131313.40\",\"6\":\"10469.208\",\"7\":\"0\",\"8\":\"1\",\"9\":\"8\",\"10\":\"2\",\"11\":\"Credit-Builder Loan, and Mortgage Loan\",\"12\":\"0\",\"13\":\"4\",\"14\":\"9.34\",\"15\":\"4\",\"16\":\"Good\",\"17\":\"352.16\",\"18\":\"40.90252\",\"19\":\"371\",\"20\":\"No\",\"21\":\"32662.00000\",\"22\":\"263.37891\",\"23\":\"High_spent_Large_value_payments\",\"24\":\"963.25482\",\"25\":\"Good\",\"_rn_\":\"53\"},{\"1\":\"CUS_0x284a\",\"2\":\"June\",\"3\":\"33\",\"4\":\"Lawyer\",\"5\":\"131313.40\",\"6\":\"0.000\",\"7\":\"0\",\"8\":\"1\",\"9\":\"8\",\"10\":\"-100\",\"11\":\"Credit-Builder Loan, and Mortgage Loan\",\"12\":\"0\",\"13\":\"3\",\"14\":\"11.34\",\"15\":\"4\",\"16\":\"Good\",\"17\":\"352.16\",\"18\":\"41.98017\",\"19\":\"372\",\"20\":\"No\",\"21\":\"911.22018\",\"22\":\"86.56639\",\"23\":\"High_spent_Large_value_payments\",\"24\":\"1140.06734\",\"25\":\"Standard\",\"_rn_\":\"54\"},{\"1\":\"CUS_0x284a\",\"2\":\"July\",\"3\":\"33\",\"4\":\"Lawyer\",\"5\":\"10909427.00\",\"6\":\"0.000\",\"7\":\"0\",\"8\":\"1\",\"9\":\"8\",\"10\":\"2\",\"11\":\"Credit-Builder Loan, and Mortgage Loan\",\"12\":\"0\",\"13\":\"2\",\"14\":\"9.34\",\"15\":\"4\",\"16\":\"Good\",\"17\":\"352.16\",\"18\":\"26.94757\",\"19\":\"373\",\"20\":\"No\",\"21\":\"911.22018\",\"22\":\"930.39190\",\"23\":\"!@9#%8\",\"24\":\"326.24183\",\"25\":\"Good\",\"_rn_\":\"55\"},{\"1\":\"CUS_0x284a\",\"2\":\"August\",\"3\":\"33\",\"4\":\"Lawyer\",\"5\":\"131313.40\",\"6\":\"10469.208\",\"7\":\"0\",\"8\":\"1\",\"9\":\"8\",\"10\":\"2\",\"11\":\"Credit-Builder Loan, and Mortgage Loan\",\"12\":\"0\",\"13\":\"2\",\"14\":\"9.34\",\"15\":\"4\",\"16\":\"Good\",\"17\":\"352.16\",\"18\":\"29.18791\",\"19\":\"374\",\"20\":\"No\",\"21\":\"911.22018\",\"22\":\"870.52238\",\"23\":\"Low_spent_Medium_value_payments\",\"24\":\"396.11135\",\"25\":\"Good\",\"_rn_\":\"56\"},{\"1\":\"CUS_0x5407\",\"2\":\"January\",\"3\":\"30\",\"4\":\"Media_Manager\",\"5\":\"34081.38\",\"6\":\"0.000\",\"7\":\"8\",\"8\":\"7\",\"9\":\"15\",\"10\":\"3\",\"11\":\"Not Specified, Auto Loan, and Student Loan\",\"12\":\"30\",\"13\":\"11\",\"14\":\"17.13\",\"15\":\"5\",\"16\":\"Standard\",\"17\":\"1704.18\",\"18\":\"24.44806\",\"19\":\"219\",\"20\":\"NM\",\"21\":\"70.47833\",\"22\":\"162.44101\",\"23\":\"Low_spent_Large_value_payments\",\"24\":\"298.19216\",\"25\":\"Poor\",\"_rn_\":\"57\"},{\"1\":\"CUS_0x5407\",\"2\":\"February\",\"3\":\"30\",\"4\":\"Media_Manager\",\"5\":\"34081.38\",\"6\":\"2611.115\",\"7\":\"8\",\"8\":\"7\",\"9\":\"15\",\"10\":\"3\",\"11\":\"Not Specified, Auto Loan, and Student Loan\",\"12\":\"30\",\"13\":\"14\",\"14\":\"17.13\",\"15\":\"5\",\"16\":\"_\",\"17\":\"1704.18\",\"18\":\"35.17116\",\"19\":\"176\",\"20\":\"Yes\",\"21\":\"70.47833\",\"22\":\"38.43698\",\"23\":\"High_spent_Large_value_payments\",\"24\":\"392.19618\",\"25\":\"Poor\",\"_rn_\":\"58\"},{\"1\":\"CUS_0x5407\",\"2\":\"March\",\"3\":\"30\",\"4\":\"Media_Manager\",\"5\":\"34081.38\",\"6\":\"0.000\",\"7\":\"8\",\"8\":\"7\",\"9\":\"15\",\"10\":\"3\",\"11\":\"Not Specified, Auto Loan, and Student Loan\",\"12\":\"31\",\"13\":\"14\",\"14\":\"17.13\",\"15\":\"5\",\"16\":\"Standard\",\"17\":\"1704.18\",\"18\":\"35.11155\",\"19\":\"177\",\"20\":\"Yes\",\"21\":\"70.47833\",\"22\":\"199.72077\",\"23\":\"Low_spent_Large_value_payments\",\"24\":\"260.91240\",\"25\":\"Poor\",\"_rn_\":\"59\"},{\"1\":\"CUS_0x5407\",\"2\":\"April\",\"3\":\"30\",\"4\":\"_______\",\"5\":\"34081.38\",\"6\":\"2611.115\",\"7\":\"8\",\"8\":\"7\",\"9\":\"15\",\"10\":\"3\",\"11\":\"Not Specified, Auto Loan, and Student Loan\",\"12\":\"34\",\"13\":\"14\",\"14\":\"21.13\",\"15\":\"5\",\"16\":\"_\",\"17\":\"1704.18\",\"18\":\"29.76216\",\"19\":\"178\",\"20\":\"Yes\",\"21\":\"70.47833\",\"22\":\"220.55219\",\"23\":\"Low_spent_Small_value_payments\",\"24\":\"260.08098\",\"25\":\"Poor\",\"_rn_\":\"60\"},{\"1\":\"CUS_0x5407\",\"2\":\"May\",\"3\":\"30\",\"4\":\"_______\",\"5\":\"34081.38\",\"6\":\"2611.115\",\"7\":\"8\",\"8\":\"7\",\"9\":\"15\",\"10\":\"3\",\"11\":\"Not Specified, Auto Loan, and Student Loan\",\"12\":\"27\",\"13\":\"14\",\"14\":\"17.13\",\"15\":\"5\",\"16\":\"_\",\"17\":\"1704.18\",\"18\":\"30.20621\",\"19\":\"179\",\"20\":\"Yes\",\"21\":\"70.47833\",\"22\":\"0.00000\",\"23\":\"High_spent_Large_value_payments\",\"24\":\"397.22835\",\"25\":\"Standard\",\"_rn_\":\"61\"},{\"1\":\"CUS_0x5407\",\"2\":\"June\",\"3\":\"30\",\"4\":\"Media_Manager\",\"5\":\"34081.38\",\"6\":\"2611.115\",\"7\":\"8\",\"8\":\"7\",\"9\":\"15\",\"10\":\"-100\",\"11\":\"Not Specified, Auto Loan, and Student Loan\",\"12\":\"30\",\"13\":\"14\",\"14\":\"18.13\",\"15\":\"5\",\"16\":\"Standard\",\"17\":\"1704.18\",\"18\":\"31.17087\",\"19\":\"180\",\"20\":\"Yes\",\"21\":\"70.47833\",\"22\":\"0.00000\",\"23\":\"!@9#%8\",\"24\":\"410.67437\",\"25\":\"Standard\",\"_rn_\":\"62\"},{\"1\":\"CUS_0x5407\",\"2\":\"July\",\"3\":\"30\",\"4\":\"Media_Manager\",\"5\":\"34081.38\",\"6\":\"0.000\",\"7\":\"8\",\"8\":\"7\",\"9\":\"15\",\"10\":\"3\",\"11\":\"Not Specified, Auto Loan, and Student Loan\",\"12\":\"30\",\"13\":\"11\",\"14\":\"17.13\",\"15\":\"5\",\"16\":\"Standard\",\"17\":\"1704.18\",\"18\":\"38.43851\",\"19\":\"181\",\"20\":\"NM\",\"21\":\"70.47833\",\"22\":\"55.45978\",\"23\":\"High_spent_Small_value_payments\",\"24\":\"395.17339\",\"25\":\"Standard\",\"_rn_\":\"63\"},{\"1\":\"CUS_0x5407\",\"2\":\"August\",\"3\":\"30\",\"4\":\"Media_Manager\",\"5\":\"34081.38\",\"6\":\"2611.115\",\"7\":\"8\",\"8\":\"7\",\"9\":\"15\",\"10\":\"3\",\"11\":\"Not Specified, Auto Loan, and Student Loan\",\"12\":\"30\",\"13\":\"14\",\"14\":\"17.13\",\"15\":\"9\",\"16\":\"_\",\"17\":\"1704.18\",\"18\":\"33.82349\",\"19\":\"182\",\"20\":\"Yes\",\"21\":\"70.47833\",\"22\":\"29.32636\",\"23\":\"High_spent_Medium_value_payments\",\"24\":\"411.30680\",\"25\":\"Poor\",\"_rn_\":\"64\"},{\"1\":\"CUS_0x4157\",\"2\":\"January\",\"3\":\"23\",\"4\":\"Doctor\",\"5\":\"114838.41\",\"6\":\"9843.868\",\"7\":\"2\",\"8\":\"5\",\"9\":\"7\",\"10\":\"-100\",\"11\":\"Personal Loan, Debt Consolidation Loan, and Auto Loan\",\"12\":\"13\",\"13\":\"11\",\"14\":\"8.24\",\"15\":\"3\",\"16\":\"Good\",\"17\":\"1377.74\",\"18\":\"33.66455\",\"19\":\"256\",\"20\":\"No\",\"21\":\"226.89279\",\"22\":\"215.19352\",\"23\":\"High_spent_Small_value_payments\",\"24\":\"802.30044\",\"25\":\"Good\",\"_rn_\":\"65\"},{\"1\":\"CUS_0x4157\",\"2\":\"February\",\"3\":\"23\",\"4\":\"Doctor\",\"5\":\"114838.41\",\"6\":\"9843.868\",\"7\":\"2\",\"8\":\"5\",\"9\":\"7\",\"10\":\"3\",\"11\":\"Personal Loan, Debt Consolidation Loan, and Auto Loan\",\"12\":\"14\",\"13\":\"8\",\"14\":\"9.40\",\"15\":\"3\",\"16\":\"Good\",\"17\":\"1377.74\",\"18\":\"27.62633\",\"19\":\"257\",\"20\":\"NM\",\"21\":\"226.89279\",\"22\":\"212.23560\",\"23\":\"High_spent_Large_value_payments\",\"24\":\"785.25836\",\"25\":\"Good\",\"_rn_\":\"66\"},{\"1\":\"CUS_0x4157\",\"2\":\"March\",\"3\":\"23\",\"4\":\"Doctor\",\"5\":\"114838.41\",\"6\":\"0.000\",\"7\":\"2\",\"8\":\"5\",\"9\":\"7\",\"10\":\"3\",\"11\":\"Personal Loan, Debt Consolidation Loan, and Auto Loan\",\"12\":\"11\",\"13\":\"11\",\"14\":\"9.40\",\"15\":\"3\",\"16\":\"Good\",\"17\":\"1377.74\",\"18\":\"35.14157\",\"19\":\"258\",\"20\":\"NM\",\"21\":\"226.89279\",\"22\":\"470.38580\",\"23\":\"High_spent_Small_value_payments\",\"24\":\"547.10816\",\"25\":\"Good\",\"_rn_\":\"67\"},{\"1\":\"CUS_0x4157\",\"2\":\"April\",\"3\":\"23\",\"4\":\"Doctor\",\"5\":\"114838.41\",\"6\":\"0.000\",\"7\":\"2\",\"8\":\"5\",\"9\":\"7\",\"10\":\"3\",\"11\":\"Personal Loan, Debt Consolidation Loan, and Auto Loan\",\"12\":\"11\",\"13\":\"14\",\"14\":\"8.24\",\"15\":\"8\",\"16\":\"Good\",\"17\":\"1377.74\",\"18\":\"30.45903\",\"19\":\"259\",\"20\":\"No\",\"21\":\"226.89279\",\"22\":\"225.08205\",\"23\":\"!@9#%8\",\"24\":\"772.41191\",\"25\":\"Good\",\"_rn_\":\"68\"},{\"1\":\"CUS_0x4157\",\"2\":\"May\",\"3\":\"23\",\"4\":\"Doctor\",\"5\":\"114838.41\",\"6\":\"9843.868\",\"7\":\"2\",\"8\":\"5\",\"9\":\"7\",\"10\":\"3\",\"11\":\"Personal Loan, Debt Consolidation Loan, and Auto Loan\",\"12\":\"11\",\"13\":\"11\",\"14\":\"11.24\",\"15\":\"8\",\"16\":\"Good\",\"17\":\"1377.74\",\"18\":\"29.81919\",\"19\":\"260\",\"20\":\"No\",\"21\":\"226.89279\",\"22\":\"649.80936\",\"23\":\"High_spent_Small_value_payments\",\"24\":\"367.68459\",\"25\":\"Standard\",\"_rn_\":\"69\"},{\"1\":\"CUS_0x4157\",\"2\":\"June\",\"3\":\"23\",\"4\":\"Doctor\",\"5\":\"114838.41\",\"6\":\"9843.868\",\"7\":\"2\",\"8\":\"5\",\"9\":\"7\",\"10\":\"3\",\"11\":\"Personal Loan, Debt Consolidation Loan, and Auto Loan\",\"12\":\"13\",\"13\":\"14\",\"14\":\"8.24\",\"15\":\"8\",\"16\":\"_\",\"17\":\"1377.74\",\"18\":\"26.11421\",\"19\":\"261\",\"20\":\"NM\",\"21\":\"226.89279\",\"22\":\"546.38057\",\"23\":\"!@9#%8\",\"24\":\"491.11339\",\"25\":\"Good\",\"_rn_\":\"70\"},{\"1\":\"CUS_0x4157\",\"2\":\"July\",\"3\":\"23\",\"4\":\"Doctor\",\"5\":\"114838.41\",\"6\":\"9843.868\",\"7\":\"2\",\"8\":\"5\",\"9\":\"7\",\"10\":\"3\",\"11\":\"Personal Loan, Debt Consolidation Loan, and Auto Loan\",\"12\":\"11\",\"13\":\"0\",\"14\":\"8.24\",\"15\":\"8\",\"16\":\"Good\",\"17\":\"1377.74\",\"18\":\"31.76752\",\"19\":\"262\",\"20\":\"No\",\"21\":\"226.89279\",\"22\":\"215.46830\",\"23\":\"High_spent_Medium_value_payments\",\"24\":\"792.02566\",\"25\":\"Good\",\"_rn_\":\"71\"},{\"1\":\"CUS_0x4157\",\"2\":\"August\",\"3\":\"23\",\"4\":\"Doctor\",\"5\":\"114838.41\",\"6\":\"9843.868\",\"7\":\"2\",\"8\":\"5\",\"9\":\"7\",\"10\":\"3\",\"11\":\"Personal Loan, Debt Consolidation Loan, and Auto Loan\",\"12\":\"11\",\"13\":\"11\",\"14\":\"8.24\",\"15\":\"8\",\"16\":\"Good\",\"17\":\"1377.74\",\"18\":\"27.81335\",\"19\":\"263\",\"20\":\"No\",\"21\":\"226.89279\",\"22\":\"254.57177\",\"23\":\"High_spent_Large_value_payments\",\"24\":\"742.92219\",\"25\":\"Standard\",\"_rn_\":\"72\"},{\"1\":\"CUS_0xba08\",\"2\":\"January\",\"3\":\"44\",\"4\":\"Journalist\",\"5\":\"31370.80\",\"6\":\"2825.233\",\"7\":\"0\",\"8\":\"5\",\"9\":\"12\",\"10\":\"2\",\"11\":\"Not Specified, and Payday Loan\",\"12\":\"4\",\"13\":\"0\",\"14\":\"5.76\",\"15\":\"2\",\"16\":\"Good\",\"17\":\"421.43\",\"18\":\"29.51935\",\"19\":\"219\",\"20\":\"NM\",\"21\":\"46.61613\",\"22\":\"154.35278\",\"23\":\"High_spent_Small_value_payments\",\"24\":\"341.55442\",\"25\":\"Good\",\"_rn_\":\"73\"},{\"1\":\"CUS_0xba08\",\"2\":\"February\",\"3\":\"44\",\"4\":\"Journalist\",\"5\":\"31370.80\",\"6\":\"2825.233\",\"7\":\"1\",\"8\":\"6\",\"9\":\"12\",\"10\":\"2\",\"11\":\"Not Specified, and Payday Loan\",\"12\":\"2\",\"13\":\"0\",\"14\":\"-1.24\",\"15\":\"2\",\"16\":\"Good\",\"17\":\"421.43\",\"18\":\"28.22048\",\"19\":\"318\",\"20\":\"No\",\"21\":\"46.61613\",\"22\":\"298.74447\",\"23\":\"Low_spent_Small_value_payments\",\"24\":\"227.16273\",\"25\":\"Good\",\"_rn_\":\"74\"},{\"1\":\"CUS_0xba08\",\"2\":\"March\",\"3\":\"44\",\"4\":\"Journalist\",\"5\":\"31370.80\",\"6\":\"2825.233\",\"7\":\"1\",\"8\":\"6\",\"9\":\"12\",\"10\":\"2\",\"11\":\"Not Specified, and Payday Loan\",\"12\":\"-2\",\"13\":\"0\",\"14\":\"1.76\",\"15\":\"5\",\"16\":\"Good\",\"17\":\"421.43\",\"18\":\"31.04642\",\"19\":\"319\",\"20\":\"No\",\"21\":\"46.61613\",\"22\":\"140.82070\",\"23\":\"Low_spent_Medium_value_payments\",\"24\":\"375.08651\",\"25\":\"Good\",\"_rn_\":\"75\"},{\"1\":\"CUS_0xba08\",\"2\":\"April\",\"3\":\"44\",\"4\":\"Journalist\",\"5\":\"31370.80\",\"6\":\"2825.233\",\"7\":\"1\",\"8\":\"6\",\"9\":\"12\",\"10\":\"2\",\"11\":\"Not Specified, and Payday Loan\",\"12\":\"1\",\"13\":\"0\",\"14\":\"5.76\",\"15\":\"5\",\"16\":\"_\",\"17\":\"421.43\",\"18\":\"30.16803\",\"19\":\"320\",\"20\":\"No\",\"21\":\"46.61613\",\"22\":\"233.60553\",\"23\":\"Low_spent_Small_value_payments\",\"24\":\"292.30168\",\"25\":\"Good\",\"_rn_\":\"76\"},{\"1\":\"CUS_0xba08\",\"2\":\"May\",\"3\":\"44\",\"4\":\"Journalist\",\"5\":\"31370.80\",\"6\":\"2825.233\",\"7\":\"1\",\"8\":\"6\",\"9\":\"12\",\"10\":\"2\",\"11\":\"Not Specified, and Payday Loan\",\"12\":\"1\",\"13\":\"0\",\"14\":\"5.76\",\"15\":\"5\",\"16\":\"_\",\"17\":\"421.43\",\"18\":\"25.18923\",\"19\":\"321\",\"20\":\"No\",\"21\":\"16415.00000\",\"22\":\"184.70057\",\"23\":\"Low_spent_Small_value_payments\",\"24\":\"341.20663\",\"25\":\"Good\",\"_rn_\":\"77\"},{\"1\":\"CUS_0xba08\",\"2\":\"June\",\"3\":\"44\",\"4\":\"Journalist\",\"5\":\"31370.80\",\"6\":\"2825.233\",\"7\":\"1\",\"8\":\"6\",\"9\":\"12\",\"10\":\"2\",\"11\":\"Not Specified, and Payday Loan\",\"12\":\"1\",\"13\":\"0\",\"14\":\"5.76\",\"15\":\"5\",\"16\":\"Good\",\"17\":\"421.43\",\"18\":\"25.50247\",\"19\":\"219\",\"20\":\"No\",\"21\":\"46.61613\",\"22\":\"137.71742\",\"23\":\"Low_spent_Medium_value_payments\",\"24\":\"378.18978\",\"25\":\"Good\",\"_rn_\":\"78\"},{\"1\":\"CUS_0xba08\",\"2\":\"July\",\"3\":\"44\",\"4\":\"Journalist\",\"5\":\"31370.80\",\"6\":\"2825.233\",\"7\":\"1\",\"8\":\"6\",\"9\":\"12\",\"10\":\"-100\",\"11\":\"Not Specified, and Payday Loan\",\"12\":\"-1\",\"13\":\"2\",\"14\":\"5.76\",\"15\":\"5\",\"16\":\"Good\",\"17\":\"421.43\",\"18\":\"22.76220\",\"19\":\"323\",\"20\":\"No\",\"21\":\"46.61613\",\"22\":\"188.39490\",\"23\":\"Low_spent_Small_value_payments\",\"24\":\"337.51230\",\"25\":\"Good\",\"_rn_\":\"79\"},{\"1\":\"CUS_0xba08\",\"2\":\"August\",\"3\":\"44\",\"4\":\"Journalist\",\"5\":\"31370.80\",\"6\":\"0.000\",\"7\":\"1\",\"8\":\"6\",\"9\":\"12\",\"10\":\"2\",\"11\":\"Not Specified, and Payday Loan\",\"12\":\"-2\",\"13\":\"2\",\"14\":\"5.76\",\"15\":\"5\",\"16\":\"_\",\"17\":\"421.43\",\"18\":\"37.56505\",\"19\":\"324\",\"20\":\"No\",\"21\":\"46.61613\",\"22\":\"252.64483\",\"23\":\"Low_spent_Small_value_payments\",\"24\":\"273.26238\",\"25\":\"Good\",\"_rn_\":\"80\"},{\"1\":\"CUS_0xa66b\",\"2\":\"January\",\"3\":\"40\",\"4\":\"Teacher\",\"5\":\"33751.27\",\"6\":\"2948.606\",\"7\":\"5\",\"8\":\"5\",\"9\":\"20\",\"10\":\"3\",\"11\":\"Credit-Builder Loan, Personal Loan, and Auto Loan\",\"12\":\"16\",\"13\":\"20\",\"14\":\"11.00\",\"15\":\"4\",\"16\":\"Standard\",\"17\":\"1328.93\",\"18\":\"37.08908\",\"19\":\"230\",\"20\":\"NM\",\"21\":\"65.00817\",\"22\":\"117.30670\",\"23\":\"High_spent_Medium_value_payments\",\"24\":\"362.54571\",\"25\":\"Standard\",\"_rn_\":\"81\"},{\"1\":\"CUS_0xa66b\",\"2\":\"February\",\"3\":\"40\",\"4\":\"Teacher\",\"5\":\"33751.27\",\"6\":\"2948.606\",\"7\":\"5\",\"8\":\"5\",\"9\":\"20\",\"10\":\"3\",\"11\":\"Credit-Builder Loan, Personal Loan, and Auto Loan\",\"12\":\"16\",\"13\":\"20\",\"14\":\"11.00\",\"15\":\"4\",\"16\":\"Standard\",\"17\":\"1328.93\",\"18\":\"30.90808\",\"19\":\"231\",\"20\":\"Yes\",\"21\":\"65.00817\",\"22\":\"70.13108\",\"23\":\"High_spent_Large_value_payments\",\"24\":\"399.72133\",\"25\":\"Standard\",\"_rn_\":\"82\"},{\"1\":\"CUS_0xa66b\",\"2\":\"March\",\"3\":\"40\",\"4\":\"_______\",\"5\":\"33751.27\",\"6\":\"0.000\",\"7\":\"5\",\"8\":\"5\",\"9\":\"20\",\"10\":\"3\",\"11\":\"Credit-Builder Loan, Personal Loan, and Auto Loan\",\"12\":\"16\",\"13\":\"20\",\"14\":\"11.00\",\"15\":\"8\",\"16\":\"Standard\",\"17\":\"1328.93\",\"18\":\"38.03072\",\"19\":\"232\",\"20\":\"Yes\",\"21\":\"65.00817\",\"22\":\"270.18258\",\"23\":\"Low_spent_Large_value_payments\",\"24\":\"229.66983\",\"25\":\"Standard\",\"_rn_\":\"83\"},{\"1\":\"CUS_0xa66b\",\"2\":\"April\",\"3\":\"40\",\"4\":\"Teacher\",\"5\":\"33751.27\",\"6\":\"2948.606\",\"7\":\"5\",\"8\":\"5\",\"9\":\"20\",\"10\":\"3\",\"11\":\"Credit-Builder Loan, Personal Loan, and Auto Loan\",\"12\":\"17\",\"13\":\"22\",\"14\":\"11.00\",\"15\":\"8\",\"16\":\"Standard\",\"17\":\"1328.93\",\"18\":\"23.40441\",\"19\":\"233\",\"20\":\"Yes\",\"21\":\"65.00817\",\"22\":\"25.19256\",\"23\":\"High_spent_Large_value_payments\",\"24\":\"444.65985\",\"25\":\"Standard\",\"_rn_\":\"84\"},{\"1\":\"CUS_0xa66b\",\"2\":\"May\",\"3\":\"40\",\"4\":\"Teacher\",\"5\":\"33751.27\",\"6\":\"2948.606\",\"7\":\"5\",\"8\":\"5\",\"9\":\"20\",\"10\":\"3\",\"11\":\"Credit-Builder Loan, Personal Loan, and Auto Loan\",\"12\":\"16\",\"13\":\"20\",\"14\":\"8.00\",\"15\":\"8\",\"16\":\"Standard\",\"17\":\"1328.93\",\"18\":\"29.07376\",\"19\":\"234\",\"20\":\"Yes\",\"21\":\"65.00817\",\"22\":\"243.32968\",\"23\":\"Low_spent_Small_value_payments\",\"24\":\"276.52272\",\"25\":\"Standard\",\"_rn_\":\"85\"},{\"1\":\"CUS_0xa66b\",\"2\":\"June\",\"3\":\"40\",\"4\":\"Teacher\",\"5\":\"33751.27\",\"6\":\"2948.606\",\"7\":\"5\",\"8\":\"5\",\"9\":\"20\",\"10\":\"3\",\"11\":\"Credit-Builder Loan, Personal Loan, and Auto Loan\",\"12\":\"16\",\"13\":\"20\",\"14\":\"11.00\",\"15\":\"8\",\"16\":\"Standard\",\"17\":\"1328.93\",\"18\":\"32.78264\",\"19\":\"235\",\"20\":\"Yes\",\"21\":\"65.00817\",\"22\":\"72.86008\",\"23\":\"High_spent_Medium_value_payments\",\"24\":\"406.99233\",\"25\":\"Standard\",\"_rn_\":\"86\"},{\"1\":\"CUS_0xa66b\",\"2\":\"July\",\"3\":\"40\",\"4\":\"Teacher\",\"5\":\"33751.27\",\"6\":\"2948.606\",\"7\":\"5\",\"8\":\"5\",\"9\":\"20\",\"10\":\"3\",\"11\":\"Credit-Builder Loan, Personal Loan, and Auto Loan\",\"12\":\"16\",\"13\":\"20\",\"14\":\"11.00\",\"15\":\"8\",\"16\":\"Standard\",\"17\":\"1328.93\",\"18\":\"35.58401\",\"19\":\"236\",\"20\":\"Yes\",\"21\":\"65.00817\",\"22\":\"35.42717\",\"23\":\"!@9#%8\",\"24\":\"444.42524\",\"25\":\"Standard\",\"_rn_\":\"87\"},{\"1\":\"CUS_0xa66b\",\"2\":\"August\",\"3\":\"40\",\"4\":\"Teacher\",\"5\":\"33751.27\",\"6\":\"2948.606\",\"7\":\"5\",\"8\":\"5\",\"9\":\"20\",\"10\":\"3\",\"11\":\"Credit-Builder Loan, Personal Loan, and Auto Loan\",\"12\":\"16\",\"13\":\"17\",\"14\":\"11.00\",\"15\":\"8\",\"16\":\"Standard\",\"17\":\"1328.93\",\"18\":\"31.13948\",\"19\":\"219\",\"20\":\"Yes\",\"21\":\"65.00817\",\"22\":\"25.96961\",\"23\":\"High_spent_Large_value_payments\",\"24\":\"443.88280\",\"25\":\"Standard\",\"_rn_\":\"88\"},{\"1\":\"CUS_0xc0ab\",\"2\":\"January\",\"3\":\"32\",\"4\":\"Engineer\",\"5\":\"88640.24\",\"6\":\"7266.687\",\"7\":\"3\",\"8\":\"6\",\"9\":\"1\",\"10\":\"2\",\"11\":\"Payday Loan, and Payday Loan\",\"12\":\"-1\",\"13\":\"0\",\"14\":\"3.51\",\"15\":\"3\",\"16\":\"Good\",\"17\":\"950.36\",\"18\":\"28.21062\",\"19\":\"305\",\"20\":\"No\",\"21\":\"135.17337\",\"22\":\"98.93176\",\"23\":\"High_spent_Large_value_payments\",\"24\":\"732.56353\",\"25\":\"Standard\",\"_rn_\":\"89\"},{\"1\":\"CUS_0xc0ab\",\"2\":\"February\",\"3\":\"32\",\"4\":\"Engineer\",\"5\":\"88640.24\",\"6\":\"7266.687\",\"7\":\"3\",\"8\":\"6\",\"9\":\"13\",\"10\":\"2\",\"11\":\"Payday Loan, and Payday Loan\",\"12\":\"4\",\"13\":\"2\",\"14\":\"3.51\",\"15\":\"3\",\"16\":\"Good\",\"17\":\"950.36\",\"18\":\"41.03617\",\"19\":\"306\",\"20\":\"NM\",\"21\":\"135.17337\",\"22\":\"157.17479\",\"23\":\"High_spent_Large_value_payments\",\"24\":\"674.32051\",\"25\":\"Good\",\"_rn_\":\"90\"},{\"1\":\"CUS_0xc0ab\",\"2\":\"March\",\"3\":\"32\",\"4\":\"Engineer\",\"5\":\"88640.24\",\"6\":\"7266.687\",\"7\":\"3\",\"8\":\"6\",\"9\":\"1\",\"10\":\"2\",\"11\":\"Payday Loan, and Payday Loan\",\"12\":\"4\",\"13\":\"0\",\"14\":\"3.51\",\"15\":\"3\",\"16\":\"Good\",\"17\":\"950.36\",\"18\":\"34.67019\",\"19\":\"307\",\"20\":\"No\",\"21\":\"135.17337\",\"22\":\"298.18891\",\"23\":\"High_spent_Medium_value_payments\",\"24\":\"543.30638\",\"25\":\"Standard\",\"_rn_\":\"91\"},{\"1\":\"CUS_0xc0ab\",\"2\":\"April\",\"3\":\"32\",\"4\":\"Engineer\",\"5\":\"88640.24\",\"6\":\"7266.687\",\"7\":\"3\",\"8\":\"6\",\"9\":\"1\",\"10\":\"2\",\"11\":\"Payday Loan, and Payday Loan\",\"12\":\"4\",\"13\":\"2\",\"14\":\"3.51\",\"15\":\"3\",\"16\":\"Good\",\"17\":\"950.36\",\"18\":\"31.82854\",\"19\":\"308\",\"20\":\"No\",\"21\":\"135.17337\",\"22\":\"0.00000\",\"23\":\"Low_spent_Small_value_payments\",\"24\":\"86.63612\",\"25\":\"Standard\",\"_rn_\":\"92\"},{\"1\":\"CUS_0xc0ab\",\"2\":\"May\",\"3\":\"32\",\"4\":\"Engineer\",\"5\":\"88640.24\",\"6\":\"7266.687\",\"7\":\"3\",\"8\":\"6\",\"9\":\"1\",\"10\":\"2\",\"11\":\"Payday Loan, and Payday Loan\",\"12\":\"4\",\"13\":\"2\",\"14\":\"3.51\",\"15\":\"3\",\"16\":\"Good\",\"17\":\"950.36\",\"18\":\"34.70284\",\"19\":\"309\",\"20\":\"No\",\"21\":\"135.17337\",\"22\":\"279.61862\",\"23\":\"High_spent_Medium_value_payments\",\"24\":\"561.87667\",\"25\":\"Good\",\"_rn_\":\"93\"},{\"1\":\"CUS_0xc0ab\",\"2\":\"June\",\"3\":\"32\",\"4\":\"Engineer\",\"5\":\"88640.24\",\"6\":\"7266.687\",\"7\":\"3\",\"8\":\"6\",\"9\":\"1\",\"10\":\"2\",\"11\":\"Payday Loan, and Payday Loan\",\"12\":\"4\",\"13\":\"0\",\"14\":\"3.51\",\"15\":\"3\",\"16\":\"Good\",\"17\":\"950.36\",\"18\":\"38.32364\",\"19\":\"310\",\"20\":\"No\",\"21\":\"135.17337\",\"22\":\"686.12622\",\"23\":\"Low_spent_Small_value_payments\",\"24\":\"195.36908\",\"25\":\"Good\",\"_rn_\":\"94\"},{\"1\":\"CUS_0xc0ab\",\"2\":\"July\",\"3\":\"32\",\"4\":\"Engineer\",\"5\":\"88640.24\",\"6\":\"0.000\",\"7\":\"3\",\"8\":\"6\",\"9\":\"1\",\"10\":\"2\",\"11\":\"Payday Loan, and Payday Loan\",\"12\":\"4\",\"13\":\"2\",\"14\":\"3.51\",\"15\":\"3\",\"16\":\"_\",\"17\":\"950.36\",\"18\":\"25.97917\",\"19\":\"311\",\"20\":\"No\",\"21\":\"80357.00000\",\"22\":\"164.07482\",\"23\":\"High_spent_Large_value_payments\",\"24\":\"667.42047\",\"25\":\"Good\",\"_rn_\":\"95\"},{\"1\":\"CUS_0xc0ab\",\"2\":\"August\",\"3\":\"32\",\"4\":\"Engineer\",\"5\":\"88640.24\",\"6\":\"7266.687\",\"7\":\"3\",\"8\":\"6\",\"9\":\"1\",\"10\":\"2\",\"11\":\"Payday Loan, and Payday Loan\",\"12\":\"-1\",\"13\":\"0\",\"14\":\"3.51\",\"15\":\"3\",\"16\":\"Good\",\"17\":\"950.36\",\"18\":\"30.87080\",\"19\":\"312\",\"20\":\"No\",\"21\":\"135.17337\",\"22\":\"98.44195\",\"23\":\"High_spent_Large_value_payments\",\"24\":\"733.05334\",\"25\":\"Good\",\"_rn_\":\"96\"},{\"1\":\"CUS_0x3e45\",\"2\":\"January\",\"3\":\"35\",\"4\":\"Entrepreneur\",\"5\":\"54392.16\",\"6\":\"4766.680\",\"7\":\"6\",\"8\":\"4\",\"9\":\"14\",\"10\":\"3\",\"11\":\"Not Specified, Student Loan, and Personal Loan\",\"12\":\"10\",\"13\":\"8\",\"14\":\"5.54\",\"15\":\"3\",\"16\":\"Standard\",\"17\":\"179.22\",\"18\":\"25.64925\",\"19\":\"322\",\"20\":\"Yes\",\"21\":\"124.39208\",\"22\":\"243.73544\",\"23\":\"Low_spent_Large_value_payments\",\"24\":\"378.54048\",\"25\":\"Standard\",\"_rn_\":\"97\"},{\"1\":\"CUS_0x3e45\",\"2\":\"February\",\"3\":\"35\",\"4\":\"Entrepreneur\",\"5\":\"54392.16\",\"6\":\"4766.680\",\"7\":\"6\",\"8\":\"4\",\"9\":\"14\",\"10\":\"3\",\"11\":\"Not Specified, Student Loan, and Personal Loan\",\"12\":\"10\",\"13\":\"10\",\"14\":\"4.54\",\"15\":\"3\",\"16\":\"Standard\",\"17\":\"179.22\",\"18\":\"29.40878\",\"19\":\"323\",\"20\":\"Yes\",\"21\":\"124.39208\",\"22\":\"142.75186\",\"23\":\"High_spent_Medium_value_payments\",\"24\":\"459.52405\",\"25\":\"Standard\",\"_rn_\":\"98\"},{\"1\":\"CUS_0x3e45\",\"2\":\"March\",\"3\":\"35\",\"4\":\"Entrepreneur\",\"5\":\"54392.16\",\"6\":\"0.000\",\"7\":\"6\",\"8\":\"4\",\"9\":\"14\",\"10\":\"3\",\"11\":\"Not Specified, Student Loan, and Personal Loan\",\"12\":\"15\",\"13\":\"11\",\"14\":\"5.54\",\"15\":\"3\",\"16\":\"_\",\"17\":\"179.22\",\"18\":\"31.25893\",\"19\":\"324\",\"20\":\"NM\",\"21\":\"124.39208\",\"22\":\"33.34957\",\"23\":\"High_spent_Large_value_payments\",\"24\":\"558.92635\",\"25\":\"Standard\",\"_rn_\":\"99\"},{\"1\":\"CUS_0x3e45\",\"2\":\"April\",\"3\":\"35\",\"4\":\"Entrepreneur\",\"5\":\"54392.16\",\"6\":\"4766.680\",\"7\":\"6\",\"8\":\"4\",\"9\":\"14\",\"10\":\"3\",\"11\":\"Not Specified, Student Loan, and Personal Loan\",\"12\":\"10\",\"13\":\"7\",\"14\":\"0.54\",\"15\":\"3\",\"16\":\"Standard\",\"17\":\"179.22\",\"18\":\"27.19259\",\"19\":\"325\",\"20\":\"Yes\",\"21\":\"124.39208\",\"22\":\"494.84223\",\"23\":\"Low_spent_Small_value_payments\",\"24\":\"147.43369\",\"25\":\"Standard\",\"_rn_\":\"100\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n## Analysis Plan\nFirstly, we are trying to address the research question of which social/societal parameters such as: \"Occupation\", \"Age\", \"Annual_Income\" or \"Monthly_Inhand_Salary\" affect the decision of credit score category assigned to a person. Through this, we can determine what role social status plays in credit approval by banks and other financial organizations. We can plot bar graphs, box plots, and scatter plots to analyze the correlation between societal parameters and credit scores. \n\nThen, we analyze the impact of behavioral patterns such as: \"Num_Credit_Card\", \"Num_of_Loan\", \"Type_of_Loan\", \"Delay_from_due_date\" and many other similar parameters on the Credit score of an individual.\n\nAfter analyzing the two types of features and their impact on Credit scores, we will identify attributes that provide the most information about an individual and whether it will be ideal to model the data with these attributes as inputs.\n\n## Descriptive Statistics\n\nI will be evaluating both the societal parameters and behavioral parameters and their correlation with Credit_Score field. \n\n### Societal Parameters\n\nThese parameters represent the individuals biographic information in the society. This information is critical as it helps in generalizing trends for a large group of individuals in the society. The attributes I will be evaluating are as follows:\n\n1) Age\n\nIt is an important measure for identifying different groups of the population. The summary of Age is as follows:\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(data$Age)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  14.00   24.00   33.00   33.03   41.00   95.00 \n```\n:::\n:::\n\n\nSo the minimum age in the dataset appears to be 14 years and the maximum being 95 years. The mean age of the population being 33.03 years and the median also being 33.\n\n2) Occupation\n\nThe occupation represents role of a person in the society.\n\nThere are the following occupations are present in the dataset:\n\n::: {.cell}\n\n```{.r .cell-code}\nunique(data$Occupation)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"Scientist\"     \"_______\"       \"Teacher\"       \"Engineer\"     \n [5] \"Entrepreneur\"  \"Developer\"     \"Lawyer\"        \"Media_Manager\"\n [9] \"Doctor\"        \"Journalist\"    \"Manager\"       \"Accountant\"   \n[13] \"Musician\"      \"Mechanic\"      \"Writer\"        \"Architect\"    \n```\n:::\n:::\n\n\nSo there appears to be 16 different profession where one profession \"_______\" represents unemployed status. The counts of individual professions are as follows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfind_mode <- function(x) {\n  u <- unique(x)\n  tab <- tabulate(match(x, u))\n  u[tab == max(tab)]\n}\ncombined_data <- data%>%\n                    group_by(Customer_ID)%>%\n                    summarise(profession = find_mode(Occupation)) %>%\n                    select(Customer_ID, profession)%>%\n                    group_by(profession)%>%\n                    summarise(counts  = n())\nhead(combined_data, 100)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"profession\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"counts\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"_______\",\"2\":\"20\"},{\"1\":\"Accountant\",\"2\":\"843\"},{\"1\":\"Architect\",\"2\":\"853\"},{\"1\":\"Developer\",\"2\":\"840\"},{\"1\":\"Doctor\",\"2\":\"821\"},{\"1\":\"Engineer\",\"2\":\"858\"},{\"1\":\"Entrepreneur\",\"2\":\"831\"},{\"1\":\"Journalist\",\"2\":\"817\"},{\"1\":\"Lawyer\",\"2\":\"887\"},{\"1\":\"Manager\",\"2\":\"804\"},{\"1\":\"Mechanic\",\"2\":\"847\"},{\"1\":\"Media_Manager\",\"2\":\"839\"},{\"1\":\"Musician\",\"2\":\"794\"},{\"1\":\"Scientist\",\"2\":\"843\"},{\"1\":\"Teacher\",\"2\":\"834\"},{\"1\":\"Writer\",\"2\":\"788\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\nSo here is a distribution of different individuals across various professions.\n\n3) Annual Income\nThe annual income is an important decider when it comes to credit score as it determines the amount of money a person can repay in an years time. \n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(data$Annual_Income)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. \n    7006    19458    37579   176416    72791 24198062 \n```\n:::\n:::\n\nWe can observe a very large disparity in the minimum and maximum annual income earned by an individual.\n\n### Behavioral parameters\n\nThere are more than 15 behavioral parameters that indicate the credit habits of the individuals. Of these attributes I picked the following to perform EDA:\n\n1) Num_Credit_Card\nThis attribute indicates the number of credit cards used by an individual. The summary of this field is as follows:\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(data$Num_Credit_Card)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  0.000   4.000   5.000   5.595   7.000 100.000 \n```\n:::\n:::\n\nWe do see some kind of disparity but the mean number of cards appears to be $\\approx 5$ per individual.\n\n2) Delay_from_due_date\nThis is an interesting as well as an important metric as it helps in predicting defaults in credit repayment. The delay in the repayment of monthly credit varies as follows:\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(data$Delay_from_due_date)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  -5.00   10.00   18.00   21.07   28.00   67.00 \n```\n:::\n:::\n\nIt ranges from -5 days probably indicating an early payment to 67 days with the mean being around 21 days.\n\n3) Credit_Utilization_Ratio\nIt indicates the percentage of credit limit a person has utilized during a given month. The utilization ratios vary as follows:\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(data$Credit_Utilization_Ratio)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  20.00   28.05   32.31   32.29   36.50   50.00 \n```\n:::\n:::\n\nAs we can see from the above summary it ranges from 20\\% to 50\\%.\n\n4) Payment_Behavior\nIt represents the nature of spending that was done during a month. The different kinds of behavior categories are as follows:\n\n::: {.cell}\n\n```{.r .cell-code}\nunique(data$Payment_Behaviour)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"High_spent_Small_value_payments\"  \"Low_spent_Large_value_payments\"  \n[3] \"Low_spent_Medium_value_payments\"  \"Low_spent_Small_value_payments\"  \n[5] \"High_spent_Medium_value_payments\" \"!@9#%8\"                          \n[7] \"High_spent_Large_value_payments\" \n```\n:::\n:::\n\nThere are 7 different categories and their occurences in the dataset are as follows:\n\n::: {.cell}\n\n```{.r .cell-code}\nbehavior_data <- data%>%\n                  group_by(Payment_Behaviour)%>%\n                  summarise(counts = n())\nhead(behavior_data)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Payment_Behaviour\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"counts\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"!@9#%8\",\"2\":\"7600\"},{\"1\":\"High_spent_Large_value_payments\",\"2\":\"13721\"},{\"1\":\"High_spent_Medium_value_payments\",\"2\":\"17540\"},{\"1\":\"High_spent_Small_value_payments\",\"2\":\"11340\"},{\"1\":\"Low_spent_Large_value_payments\",\"2\":\"10425\"},{\"1\":\"Low_spent_Medium_value_payments\",\"2\":\"13861\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\nThe dataset appears to cover different types of spending behavior almost equitablly.\n\n## Results: Analysis and Visualization\n\nAs we discussed in the earlier sections we will be performing exploratory data analysis on two different kinds of attributes and their correlation to the Credit_Score.\n\n### Exploratory Data Analysis for Societal parameters\n\n#### Age\nFirstly, we want analyze which age group has the highest number of good credit scores and then decide based on the data which age group performs the best. For this we can observe the data well on a barpolt where different age groups have their corresponding bars for each of the credit score categories.\n\n::: {.cell}\n\n```{.r .cell-code}\nage_data <- data%>%\n              group_by(Age, Credit_Score)%>%\n              summarise(counts= n())\nunique(age_data$Age)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38\n[26] 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 95\n```\n:::\n:::\n\nSince there are a large number of ages in the data we can group them as follows:\n\n::: {.cell}\n\n```{.r .cell-code}\n# let's have a window of size 8 then\n\nwindow_sizes <- c(14, 23, 32, 41, 50, 90)\ntemp <- age_data%>%\n          pivot_wider(names_from = Credit_Score, values_from = counts)\ntemp1 <- temp%>%\n            filter(Age >= 14 & Age <= 22)%>%\n            group_by()%>%\n            summarise(Age_group = \"14 - 22\", Good = sum(Good), Poor = sum(Poor), Standard = sum(Standard))\ntemp2 <- temp%>%\n            filter(Age >= 23 & Age <= 31)%>%\n            group_by()%>%\n            summarise(Age_group = \"23 - 31\", Good = sum(Good), Poor = sum(Poor), Standard = sum(Standard))\ntemp3 <- temp%>%\n            filter(Age >= 32 & Age <= 40)%>%\n            group_by()%>%\n            summarise(Age_group = \"32 - 40\", Good = sum(Good), Poor = sum(Poor), Standard = sum(Standard))\ntemp4 <- temp%>%\n            filter(Age >= 41 & Age <= 49)%>%\n            group_by()%>%\n            summarise(Age_group = \"41 - 49\", Good = sum(Good), Poor = sum(Poor), Standard = sum(Standard))\ntemp5 <- temp%>%\n            filter(Age >= 50 & Age <= 58)%>%\n            group_by()%>%\n            summarise(Age_group = \"50 - 58\", Good = sum(Good), Poor = sum(Poor), Standard = sum(Standard))\ntemp6 <- temp%>%\n            filter(Age >= 90 & Age <= 98)%>%\n            group_by()%>%\n            summarise(Age_group = \"90 - 98\", Good = sum(Good), Poor = sum(Poor), Standard = sum(Standard))\ndf_list <- list(temp1, temp2, temp3, temp4, temp5, temp6)\nage_data <- df_list %>% reduce(full_join, by= c('Age_group', 'Good', 'Poor', 'Standard'))\n```\n:::\n\nNow we perform pivot longer to re-adjust the data for the bar plot.\n\n::: {.cell}\n\n```{.r .cell-code}\nage_data <- age_data%>%\n              pivot_longer(!Age_group, names_to = 'Credit_Score', values_to = 'counts')\nage_data$counts[is.na(age_data$counts)] <- 0\nhead(age_data, 100)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Age_group\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Credit_Score\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"counts\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"14 - 22\",\"2\":\"Good\",\"3\":\"2567\"},{\"1\":\"14 - 22\",\"2\":\"Poor\",\"3\":\"7078\"},{\"1\":\"14 - 22\",\"2\":\"Standard\",\"3\":\"10867\"},{\"1\":\"23 - 31\",\"2\":\"Good\",\"3\":\"4122\"},{\"1\":\"23 - 31\",\"2\":\"Poor\",\"3\":\"8284\"},{\"1\":\"23 - 31\",\"2\":\"Standard\",\"3\":\"13770\"},{\"1\":\"32 - 40\",\"2\":\"Good\",\"3\":\"4456\"},{\"1\":\"32 - 40\",\"2\":\"Poor\",\"3\":\"7778\"},{\"1\":\"32 - 40\",\"2\":\"Standard\",\"3\":\"13614\"},{\"1\":\"41 - 49\",\"2\":\"Good\",\"3\":\"4012\"},{\"1\":\"41 - 49\",\"2\":\"Poor\",\"3\":\"4915\"},{\"1\":\"41 - 49\",\"2\":\"Standard\",\"3\":\"10449\"},{\"1\":\"50 - 58\",\"2\":\"Good\",\"3\":\"0\"},{\"1\":\"50 - 58\",\"2\":\"Poor\",\"3\":\"0\"},{\"1\":\"50 - 58\",\"2\":\"Standard\",\"3\":\"4472\"},{\"1\":\"90 - 98\",\"2\":\"Good\",\"3\":\"0\"},{\"1\":\"90 - 98\",\"2\":\"Poor\",\"3\":\"6\"},{\"1\":\"90 - 98\",\"2\":\"Standard\",\"3\":\"2\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\nThe bar plot is as follows:\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(age_data)+\n  geom_bar(aes(x=Age_group, y = counts, fill=Credit_Score),  stat = \"identity\", position = \"dodge\")+\n  labs(title = \"Barplot depicting the Credit scores of different Age groups\")\n```\n\n::: {.cell-output-display}\n![](PranavKomaravolu_FinalProject_files/figure-html/unnamed-chunk-33-1.png){width=672}\n:::\n:::\n\nFrom the above plot we can observe that the majority of the population lie in the standard category. While upon detailed observation the age groups of 23-31 appear to have the best credit scores which is followed by age groups 32-40, then followed by 14-22 and later we observe the remaining age groups 41-49, 50-58 and 90-98 respectively. This data appears to make sense as the majority of the population in the age group 23-31 represent the working class hence the high credit score.\n\n#### Occupation\nFrom the previous section we observed that there are 16 types of professions in the dataset. Now we can plot a bar plot to analyze each of the professions and their corressponding credit scores.\n\nThe data for the bar plot can be obtained as follows:\n\n::: {.cell}\n\n```{.r .cell-code}\noccupation_data <- data%>%\n                    group_by(Occupation, Credit_Score)%>%\n                    summarise(counts = n())\nhead(occupation_data, 100)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Occupation\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Credit_Score\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"counts\"],\"name\":[3],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"_______\",\"2\":\"Good\",\"3\":\"1243\"},{\"1\":\"_______\",\"2\":\"Poor\",\"3\":\"2031\"},{\"1\":\"_______\",\"2\":\"Standard\",\"3\":\"3788\"},{\"1\":\"Accountant\",\"2\":\"Good\",\"3\":\"1128\"},{\"1\":\"Accountant\",\"2\":\"Poor\",\"3\":\"1879\"},{\"1\":\"Accountant\",\"2\":\"Standard\",\"3\":\"3264\"},{\"1\":\"Architect\",\"2\":\"Good\",\"3\":\"1144\"},{\"1\":\"Architect\",\"2\":\"Poor\",\"3\":\"1734\"},{\"1\":\"Architect\",\"2\":\"Standard\",\"3\":\"3477\"},{\"1\":\"Developer\",\"2\":\"Good\",\"3\":\"1134\"},{\"1\":\"Developer\",\"2\":\"Poor\",\"3\":\"1792\"},{\"1\":\"Developer\",\"2\":\"Standard\",\"3\":\"3309\"},{\"1\":\"Doctor\",\"2\":\"Good\",\"3\":\"1082\"},{\"1\":\"Doctor\",\"2\":\"Poor\",\"3\":\"1661\"},{\"1\":\"Doctor\",\"2\":\"Standard\",\"3\":\"3344\"},{\"1\":\"Engineer\",\"2\":\"Good\",\"3\":\"1182\"},{\"1\":\"Engineer\",\"2\":\"Poor\",\"3\":\"1932\"},{\"1\":\"Engineer\",\"2\":\"Standard\",\"3\":\"3236\"},{\"1\":\"Entrepreneur\",\"2\":\"Good\",\"3\":\"1080\"},{\"1\":\"Entrepreneur\",\"2\":\"Poor\",\"3\":\"1896\"},{\"1\":\"Entrepreneur\",\"2\":\"Standard\",\"3\":\"3198\"},{\"1\":\"Journalist\",\"2\":\"Good\",\"3\":\"1173\"},{\"1\":\"Journalist\",\"2\":\"Poor\",\"3\":\"1725\"},{\"1\":\"Journalist\",\"2\":\"Standard\",\"3\":\"3187\"},{\"1\":\"Lawyer\",\"2\":\"Good\",\"3\":\"1162\"},{\"1\":\"Lawyer\",\"2\":\"Poor\",\"3\":\"1810\"},{\"1\":\"Lawyer\",\"2\":\"Standard\",\"3\":\"3603\"},{\"1\":\"Manager\",\"2\":\"Good\",\"3\":\"1098\"},{\"1\":\"Manager\",\"2\":\"Poor\",\"3\":\"1732\"},{\"1\":\"Manager\",\"2\":\"Standard\",\"3\":\"3143\"},{\"1\":\"Mechanic\",\"2\":\"Good\",\"3\":\"1024\"},{\"1\":\"Mechanic\",\"2\":\"Poor\",\"3\":\"1896\"},{\"1\":\"Mechanic\",\"2\":\"Standard\",\"3\":\"3371\"},{\"1\":\"Media_Manager\",\"2\":\"Good\",\"3\":\"1161\"},{\"1\":\"Media_Manager\",\"2\":\"Poor\",\"3\":\"1645\"},{\"1\":\"Media_Manager\",\"2\":\"Standard\",\"3\":\"3426\"},{\"1\":\"Musician\",\"2\":\"Good\",\"3\":\"1110\"},{\"1\":\"Musician\",\"2\":\"Poor\",\"3\":\"1670\"},{\"1\":\"Musician\",\"2\":\"Standard\",\"3\":\"3131\"},{\"1\":\"Scientist\",\"2\":\"Good\",\"3\":\"1127\"},{\"1\":\"Scientist\",\"2\":\"Poor\",\"3\":\"1921\"},{\"1\":\"Scientist\",\"2\":\"Standard\",\"3\":\"3251\"},{\"1\":\"Teacher\",\"2\":\"Good\",\"3\":\"1143\"},{\"1\":\"Teacher\",\"2\":\"Poor\",\"3\":\"1895\"},{\"1\":\"Teacher\",\"2\":\"Standard\",\"3\":\"3177\"},{\"1\":\"Writer\",\"2\":\"Good\",\"3\":\"837\"},{\"1\":\"Writer\",\"2\":\"Poor\",\"3\":\"1779\"},{\"1\":\"Writer\",\"2\":\"Standard\",\"3\":\"3269\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\nNow we can plot the bar plots to observe the correlation between occupation and credit score.\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(occupation_data)+\n  geom_bar(aes(x = Occupation, y = counts, fill = Credit_Score), stat = \"identity\", position = \"dodge\")+\n  coord_flip()+\n  labs(title = \"Bar plot representing credit scores for different occupations\")\n```\n\n::: {.cell-output-display}\n![](PranavKomaravolu_FinalProject_files/figure-html/unnamed-chunk-35-1.png){width=672}\n:::\n:::\n\nSimilar to the above plot we can observe that the majority of the individuals lie in the standard category. But when it comes to high credit scores we can see that some occupations tend to perform better than the rest of the professions. Them being: \"_________\", \"Engineer\", \"Media Manager\", \"Lawyer\".\n\n#### Annual Income\nHere we analyze the distributions of annual income for different credit categories. We can do this by plotting box plots for the three of the categories and analyzing the distributions.\n\nThe data for the box plot can be obtained as follows:\n\n::: {.cell}\n\n```{.r .cell-code}\nincome_data <- data%>%\n                select(Customer_ID, Annual_Income, Credit_Score)\n#income_data <- unique(income_data)\nincome_data <- income_data%>%\n                select(-Customer_ID)\nhead(income_data, 100)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Annual_Income\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Credit_Score\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"19114.12\",\"2\":\"Good\",\"_rn_\":\"1\"},{\"1\":\"19114.12\",\"2\":\"Good\",\"_rn_\":\"2\"},{\"1\":\"19114.12\",\"2\":\"Good\",\"_rn_\":\"3\"},{\"1\":\"19114.12\",\"2\":\"Good\",\"_rn_\":\"4\"},{\"1\":\"19114.12\",\"2\":\"Good\",\"_rn_\":\"5\"},{\"1\":\"19114.12\",\"2\":\"Good\",\"_rn_\":\"6\"},{\"1\":\"19114.12\",\"2\":\"Good\",\"_rn_\":\"7\"},{\"1\":\"19114.12\",\"2\":\"Standard\",\"_rn_\":\"8\"},{\"1\":\"34847.84\",\"2\":\"Standard\",\"_rn_\":\"9\"},{\"1\":\"34847.84\",\"2\":\"Good\",\"_rn_\":\"10\"},{\"1\":\"34847.84\",\"2\":\"Standard\",\"_rn_\":\"11\"},{\"1\":\"34847.84\",\"2\":\"Good\",\"_rn_\":\"12\"},{\"1\":\"34847.84\",\"2\":\"Good\",\"_rn_\":\"13\"},{\"1\":\"34847.84\",\"2\":\"Good\",\"_rn_\":\"14\"},{\"1\":\"34847.84\",\"2\":\"Good\",\"_rn_\":\"15\"},{\"1\":\"34847.84\",\"2\":\"Good\",\"_rn_\":\"16\"},{\"1\":\"143162.64\",\"2\":\"Good\",\"_rn_\":\"17\"},{\"1\":\"143162.64\",\"2\":\"Good\",\"_rn_\":\"18\"},{\"1\":\"143162.64\",\"2\":\"Good\",\"_rn_\":\"19\"},{\"1\":\"143162.64\",\"2\":\"Good\",\"_rn_\":\"20\"},{\"1\":\"143162.64\",\"2\":\"Good\",\"_rn_\":\"21\"},{\"1\":\"143162.64\",\"2\":\"Good\",\"_rn_\":\"22\"},{\"1\":\"143162.64\",\"2\":\"Standard\",\"_rn_\":\"23\"},{\"1\":\"143162.64\",\"2\":\"Standard\",\"_rn_\":\"24\"},{\"1\":\"30689.89\",\"2\":\"Standard\",\"_rn_\":\"25\"},{\"1\":\"30689.89\",\"2\":\"Standard\",\"_rn_\":\"26\"},{\"1\":\"30689.89\",\"2\":\"Standard\",\"_rn_\":\"27\"},{\"1\":\"30689.89\",\"2\":\"Standard\",\"_rn_\":\"28\"},{\"1\":\"30689.89\",\"2\":\"Standard\",\"_rn_\":\"29\"},{\"1\":\"30689.89\",\"2\":\"Standard\",\"_rn_\":\"30\"},{\"1\":\"30689.89\",\"2\":\"Standard\",\"_rn_\":\"31\"},{\"1\":\"30689.89\",\"2\":\"Standard\",\"_rn_\":\"32\"},{\"1\":\"35547.71\",\"2\":\"Standard\",\"_rn_\":\"33\"},{\"1\":\"35547.71\",\"2\":\"Standard\",\"_rn_\":\"34\"},{\"1\":\"35547.71\",\"2\":\"Standard\",\"_rn_\":\"35\"},{\"1\":\"35547.71\",\"2\":\"Standard\",\"_rn_\":\"36\"},{\"1\":\"35547.71\",\"2\":\"Standard\",\"_rn_\":\"37\"},{\"1\":\"35547.71\",\"2\":\"Standard\",\"_rn_\":\"38\"},{\"1\":\"35547.71\",\"2\":\"Standard\",\"_rn_\":\"39\"},{\"1\":\"35547.71\",\"2\":\"Standard\",\"_rn_\":\"40\"},{\"1\":\"73928.46\",\"2\":\"Good\",\"_rn_\":\"41\"},{\"1\":\"73928.46\",\"2\":\"Good\",\"_rn_\":\"42\"},{\"1\":\"73928.46\",\"2\":\"Good\",\"_rn_\":\"43\"},{\"1\":\"73928.46\",\"2\":\"Good\",\"_rn_\":\"44\"},{\"1\":\"73928.46\",\"2\":\"Good\",\"_rn_\":\"45\"},{\"1\":\"73928.46\",\"2\":\"Good\",\"_rn_\":\"46\"},{\"1\":\"73928.46\",\"2\":\"Standard\",\"_rn_\":\"47\"},{\"1\":\"73928.46\",\"2\":\"Good\",\"_rn_\":\"48\"},{\"1\":\"131313.40\",\"2\":\"Good\",\"_rn_\":\"49\"},{\"1\":\"131313.40\",\"2\":\"Good\",\"_rn_\":\"50\"},{\"1\":\"131313.40\",\"2\":\"Good\",\"_rn_\":\"51\"},{\"1\":\"131313.40\",\"2\":\"Good\",\"_rn_\":\"52\"},{\"1\":\"131313.40\",\"2\":\"Good\",\"_rn_\":\"53\"},{\"1\":\"131313.40\",\"2\":\"Standard\",\"_rn_\":\"54\"},{\"1\":\"10909427.00\",\"2\":\"Good\",\"_rn_\":\"55\"},{\"1\":\"131313.40\",\"2\":\"Good\",\"_rn_\":\"56\"},{\"1\":\"34081.38\",\"2\":\"Poor\",\"_rn_\":\"57\"},{\"1\":\"34081.38\",\"2\":\"Poor\",\"_rn_\":\"58\"},{\"1\":\"34081.38\",\"2\":\"Poor\",\"_rn_\":\"59\"},{\"1\":\"34081.38\",\"2\":\"Poor\",\"_rn_\":\"60\"},{\"1\":\"34081.38\",\"2\":\"Standard\",\"_rn_\":\"61\"},{\"1\":\"34081.38\",\"2\":\"Standard\",\"_rn_\":\"62\"},{\"1\":\"34081.38\",\"2\":\"Standard\",\"_rn_\":\"63\"},{\"1\":\"34081.38\",\"2\":\"Poor\",\"_rn_\":\"64\"},{\"1\":\"114838.41\",\"2\":\"Good\",\"_rn_\":\"65\"},{\"1\":\"114838.41\",\"2\":\"Good\",\"_rn_\":\"66\"},{\"1\":\"114838.41\",\"2\":\"Good\",\"_rn_\":\"67\"},{\"1\":\"114838.41\",\"2\":\"Good\",\"_rn_\":\"68\"},{\"1\":\"114838.41\",\"2\":\"Standard\",\"_rn_\":\"69\"},{\"1\":\"114838.41\",\"2\":\"Good\",\"_rn_\":\"70\"},{\"1\":\"114838.41\",\"2\":\"Good\",\"_rn_\":\"71\"},{\"1\":\"114838.41\",\"2\":\"Standard\",\"_rn_\":\"72\"},{\"1\":\"31370.80\",\"2\":\"Good\",\"_rn_\":\"73\"},{\"1\":\"31370.80\",\"2\":\"Good\",\"_rn_\":\"74\"},{\"1\":\"31370.80\",\"2\":\"Good\",\"_rn_\":\"75\"},{\"1\":\"31370.80\",\"2\":\"Good\",\"_rn_\":\"76\"},{\"1\":\"31370.80\",\"2\":\"Good\",\"_rn_\":\"77\"},{\"1\":\"31370.80\",\"2\":\"Good\",\"_rn_\":\"78\"},{\"1\":\"31370.80\",\"2\":\"Good\",\"_rn_\":\"79\"},{\"1\":\"31370.80\",\"2\":\"Good\",\"_rn_\":\"80\"},{\"1\":\"33751.27\",\"2\":\"Standard\",\"_rn_\":\"81\"},{\"1\":\"33751.27\",\"2\":\"Standard\",\"_rn_\":\"82\"},{\"1\":\"33751.27\",\"2\":\"Standard\",\"_rn_\":\"83\"},{\"1\":\"33751.27\",\"2\":\"Standard\",\"_rn_\":\"84\"},{\"1\":\"33751.27\",\"2\":\"Standard\",\"_rn_\":\"85\"},{\"1\":\"33751.27\",\"2\":\"Standard\",\"_rn_\":\"86\"},{\"1\":\"33751.27\",\"2\":\"Standard\",\"_rn_\":\"87\"},{\"1\":\"33751.27\",\"2\":\"Standard\",\"_rn_\":\"88\"},{\"1\":\"88640.24\",\"2\":\"Standard\",\"_rn_\":\"89\"},{\"1\":\"88640.24\",\"2\":\"Good\",\"_rn_\":\"90\"},{\"1\":\"88640.24\",\"2\":\"Standard\",\"_rn_\":\"91\"},{\"1\":\"88640.24\",\"2\":\"Standard\",\"_rn_\":\"92\"},{\"1\":\"88640.24\",\"2\":\"Good\",\"_rn_\":\"93\"},{\"1\":\"88640.24\",\"2\":\"Good\",\"_rn_\":\"94\"},{\"1\":\"88640.24\",\"2\":\"Good\",\"_rn_\":\"95\"},{\"1\":\"88640.24\",\"2\":\"Good\",\"_rn_\":\"96\"},{\"1\":\"54392.16\",\"2\":\"Standard\",\"_rn_\":\"97\"},{\"1\":\"54392.16\",\"2\":\"Standard\",\"_rn_\":\"98\"},{\"1\":\"54392.16\",\"2\":\"Standard\",\"_rn_\":\"99\"},{\"1\":\"54392.16\",\"2\":\"Standard\",\"_rn_\":\"100\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\nNow we can plot the box plots for the above data:\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(income_data)+\n  geom_boxplot(aes(x=Credit_Score, y=Annual_Income), outlier.shape = NA)+\n  coord_flip()+\n  labs(title = \"Box plot representing annual income of different credit score categories\")+\n  scale_y_continuous(limits = c(7006, 90000))\n```\n\n::: {.cell-output-display}\n![](PranavKomaravolu_FinalProject_files/figure-html/unnamed-chunk-37-1.png){width=672}\n:::\n:::\n\nFrom the above box plots, we can observe that individuals with good credit scores tend to have higher annual income than those with standard credit score who are then followed by those with poor credit scores. The dataset has a very high number of outliers.\n\n### Exploratory Data Analysis for Behavioral parameters\nHere we will be analyzing the impact of behavioral parameters on credit score.\n\n#### Number of Credit Cards\nOne of the most common assumption is that the Credit Score of an individual is directly proportional to the number of credit cards used by the individual. Now we try to find whether that assumption is true for the current dataset or not. There were a lot of NA's in the initial dataset which were later replaced using the median of the distribution. We can analyze this by plotting a box plot and identifying the distributions of number of credit cards for each of the credit score categories.\n\nThe data for the box plot is as follows:\n\n::: {.cell}\n\n```{.r .cell-code}\ncreditcard_data <- data%>%\n                    select(Num_Credit_Card, Credit_Score)\nhead(creditcard_data, 100)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Num_Credit_Card\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Credit_Score\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"4\",\"2\":\"Good\",\"_rn_\":\"1\"},{\"1\":\"4\",\"2\":\"Good\",\"_rn_\":\"2\"},{\"1\":\"4\",\"2\":\"Good\",\"_rn_\":\"3\"},{\"1\":\"4\",\"2\":\"Good\",\"_rn_\":\"4\"},{\"1\":\"4\",\"2\":\"Good\",\"_rn_\":\"5\"},{\"1\":\"4\",\"2\":\"Good\",\"_rn_\":\"6\"},{\"1\":\"4\",\"2\":\"Good\",\"_rn_\":\"7\"},{\"1\":\"4\",\"2\":\"Standard\",\"_rn_\":\"8\"},{\"1\":\"4\",\"2\":\"Standard\",\"_rn_\":\"9\"},{\"1\":\"4\",\"2\":\"Good\",\"_rn_\":\"10\"},{\"1\":\"5\",\"2\":\"Standard\",\"_rn_\":\"11\"},{\"1\":\"4\",\"2\":\"Good\",\"_rn_\":\"12\"},{\"1\":\"4\",\"2\":\"Good\",\"_rn_\":\"13\"},{\"1\":\"4\",\"2\":\"Good\",\"_rn_\":\"14\"},{\"1\":\"4\",\"2\":\"Good\",\"_rn_\":\"15\"},{\"1\":\"4\",\"2\":\"Good\",\"_rn_\":\"16\"},{\"1\":\"5\",\"2\":\"Good\",\"_rn_\":\"17\"},{\"1\":\"5\",\"2\":\"Good\",\"_rn_\":\"18\"},{\"1\":\"5\",\"2\":\"Good\",\"_rn_\":\"19\"},{\"1\":\"5\",\"2\":\"Good\",\"_rn_\":\"20\"},{\"1\":\"5\",\"2\":\"Good\",\"_rn_\":\"21\"},{\"1\":\"5\",\"2\":\"Good\",\"_rn_\":\"22\"},{\"1\":\"5\",\"2\":\"Standard\",\"_rn_\":\"23\"},{\"1\":\"5\",\"2\":\"Standard\",\"_rn_\":\"24\"},{\"1\":\"5\",\"2\":\"Standard\",\"_rn_\":\"25\"},{\"1\":\"5\",\"2\":\"Standard\",\"_rn_\":\"26\"},{\"1\":\"5\",\"2\":\"Standard\",\"_rn_\":\"27\"},{\"1\":\"5\",\"2\":\"Standard\",\"_rn_\":\"28\"},{\"1\":\"5\",\"2\":\"Standard\",\"_rn_\":\"29\"},{\"1\":\"5\",\"2\":\"Standard\",\"_rn_\":\"30\"},{\"1\":\"5\",\"2\":\"Standard\",\"_rn_\":\"31\"},{\"1\":\"5\",\"2\":\"Standard\",\"_rn_\":\"32\"},{\"1\":\"5\",\"2\":\"Standard\",\"_rn_\":\"33\"},{\"1\":\"5\",\"2\":\"Standard\",\"_rn_\":\"34\"},{\"1\":\"5\",\"2\":\"Standard\",\"_rn_\":\"35\"},{\"1\":\"5\",\"2\":\"Standard\",\"_rn_\":\"36\"},{\"1\":\"5\",\"2\":\"Standard\",\"_rn_\":\"37\"},{\"1\":\"5\",\"2\":\"Standard\",\"_rn_\":\"38\"},{\"1\":\"5\",\"2\":\"Standard\",\"_rn_\":\"39\"},{\"1\":\"5\",\"2\":\"Standard\",\"_rn_\":\"40\"},{\"1\":\"5\",\"2\":\"Good\",\"_rn_\":\"41\"},{\"1\":\"5\",\"2\":\"Good\",\"_rn_\":\"42\"},{\"1\":\"5\",\"2\":\"Good\",\"_rn_\":\"43\"},{\"1\":\"5\",\"2\":\"Good\",\"_rn_\":\"44\"},{\"1\":\"5\",\"2\":\"Good\",\"_rn_\":\"45\"},{\"1\":\"5\",\"2\":\"Good\",\"_rn_\":\"46\"},{\"1\":\"5\",\"2\":\"Standard\",\"_rn_\":\"47\"},{\"1\":\"5\",\"2\":\"Good\",\"_rn_\":\"48\"},{\"1\":\"1\",\"2\":\"Good\",\"_rn_\":\"49\"},{\"1\":\"1\",\"2\":\"Good\",\"_rn_\":\"50\"},{\"1\":\"1\",\"2\":\"Good\",\"_rn_\":\"51\"},{\"1\":\"1\",\"2\":\"Good\",\"_rn_\":\"52\"},{\"1\":\"1\",\"2\":\"Good\",\"_rn_\":\"53\"},{\"1\":\"1\",\"2\":\"Standard\",\"_rn_\":\"54\"},{\"1\":\"1\",\"2\":\"Good\",\"_rn_\":\"55\"},{\"1\":\"1\",\"2\":\"Good\",\"_rn_\":\"56\"},{\"1\":\"7\",\"2\":\"Poor\",\"_rn_\":\"57\"},{\"1\":\"7\",\"2\":\"Poor\",\"_rn_\":\"58\"},{\"1\":\"7\",\"2\":\"Poor\",\"_rn_\":\"59\"},{\"1\":\"7\",\"2\":\"Poor\",\"_rn_\":\"60\"},{\"1\":\"7\",\"2\":\"Standard\",\"_rn_\":\"61\"},{\"1\":\"7\",\"2\":\"Standard\",\"_rn_\":\"62\"},{\"1\":\"7\",\"2\":\"Standard\",\"_rn_\":\"63\"},{\"1\":\"7\",\"2\":\"Poor\",\"_rn_\":\"64\"},{\"1\":\"5\",\"2\":\"Good\",\"_rn_\":\"65\"},{\"1\":\"5\",\"2\":\"Good\",\"_rn_\":\"66\"},{\"1\":\"5\",\"2\":\"Good\",\"_rn_\":\"67\"},{\"1\":\"5\",\"2\":\"Good\",\"_rn_\":\"68\"},{\"1\":\"5\",\"2\":\"Standard\",\"_rn_\":\"69\"},{\"1\":\"5\",\"2\":\"Good\",\"_rn_\":\"70\"},{\"1\":\"5\",\"2\":\"Good\",\"_rn_\":\"71\"},{\"1\":\"5\",\"2\":\"Standard\",\"_rn_\":\"72\"},{\"1\":\"5\",\"2\":\"Good\",\"_rn_\":\"73\"},{\"1\":\"6\",\"2\":\"Good\",\"_rn_\":\"74\"},{\"1\":\"6\",\"2\":\"Good\",\"_rn_\":\"75\"},{\"1\":\"6\",\"2\":\"Good\",\"_rn_\":\"76\"},{\"1\":\"6\",\"2\":\"Good\",\"_rn_\":\"77\"},{\"1\":\"6\",\"2\":\"Good\",\"_rn_\":\"78\"},{\"1\":\"6\",\"2\":\"Good\",\"_rn_\":\"79\"},{\"1\":\"6\",\"2\":\"Good\",\"_rn_\":\"80\"},{\"1\":\"5\",\"2\":\"Standard\",\"_rn_\":\"81\"},{\"1\":\"5\",\"2\":\"Standard\",\"_rn_\":\"82\"},{\"1\":\"5\",\"2\":\"Standard\",\"_rn_\":\"83\"},{\"1\":\"5\",\"2\":\"Standard\",\"_rn_\":\"84\"},{\"1\":\"5\",\"2\":\"Standard\",\"_rn_\":\"85\"},{\"1\":\"5\",\"2\":\"Standard\",\"_rn_\":\"86\"},{\"1\":\"5\",\"2\":\"Standard\",\"_rn_\":\"87\"},{\"1\":\"5\",\"2\":\"Standard\",\"_rn_\":\"88\"},{\"1\":\"6\",\"2\":\"Standard\",\"_rn_\":\"89\"},{\"1\":\"6\",\"2\":\"Good\",\"_rn_\":\"90\"},{\"1\":\"6\",\"2\":\"Standard\",\"_rn_\":\"91\"},{\"1\":\"6\",\"2\":\"Standard\",\"_rn_\":\"92\"},{\"1\":\"6\",\"2\":\"Good\",\"_rn_\":\"93\"},{\"1\":\"6\",\"2\":\"Good\",\"_rn_\":\"94\"},{\"1\":\"6\",\"2\":\"Good\",\"_rn_\":\"95\"},{\"1\":\"6\",\"2\":\"Good\",\"_rn_\":\"96\"},{\"1\":\"4\",\"2\":\"Standard\",\"_rn_\":\"97\"},{\"1\":\"4\",\"2\":\"Standard\",\"_rn_\":\"98\"},{\"1\":\"4\",\"2\":\"Standard\",\"_rn_\":\"99\"},{\"1\":\"4\",\"2\":\"Standard\",\"_rn_\":\"100\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\nNow we have the required data so we can proceed with the plotting of the box plot:\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(creditcard_data)+\n  geom_boxplot(aes(x= Credit_Score, y = Num_Credit_Card), outlier.shape = NA)+\n  labs(title = \"Box plot representing number of credit cards for different credit score categories\")+\n  scale_y_continuous(limits = c(0, 12))\n```\n\n::: {.cell-output-display}\n![](PranavKomaravolu_FinalProject_files/figure-html/unnamed-chunk-39-1.png){width=672}\n:::\n:::\n\nThe assumption does not hold for this dataset as people with less number of credit cards appear to have higher credit scores than those with more number of credit cards.\n\n#### Delay from Due Date\nThis attribute represents the number of days after the due date after which the credit card bill was paid by the individual. We can analyze this using a box plot for delay from due date and credit score. Ideally the longer the delay in credit repayment the lower will be the credit score.\n\nThe data for the box plot can be obtained as follows:\n\n::: {.cell}\n\n```{.r .cell-code}\ndelay_data <- data%>%\n                select(Delay_from_due_date, Credit_Score)\nhead(delay_data, 100)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Delay_from_due_date\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Credit_Score\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"3\",\"2\":\"Good\",\"_rn_\":\"1\"},{\"1\":\"-1\",\"2\":\"Good\",\"_rn_\":\"2\"},{\"1\":\"3\",\"2\":\"Good\",\"_rn_\":\"3\"},{\"1\":\"5\",\"2\":\"Good\",\"_rn_\":\"4\"},{\"1\":\"6\",\"2\":\"Good\",\"_rn_\":\"5\"},{\"1\":\"8\",\"2\":\"Good\",\"_rn_\":\"6\"},{\"1\":\"3\",\"2\":\"Good\",\"_rn_\":\"7\"},{\"1\":\"3\",\"2\":\"Standard\",\"_rn_\":\"8\"},{\"1\":\"3\",\"2\":\"Standard\",\"_rn_\":\"9\"},{\"1\":\"7\",\"2\":\"Good\",\"_rn_\":\"10\"},{\"1\":\"3\",\"2\":\"Standard\",\"_rn_\":\"11\"},{\"1\":\"3\",\"2\":\"Good\",\"_rn_\":\"12\"},{\"1\":\"3\",\"2\":\"Good\",\"_rn_\":\"13\"},{\"1\":\"3\",\"2\":\"Good\",\"_rn_\":\"14\"},{\"1\":\"3\",\"2\":\"Good\",\"_rn_\":\"15\"},{\"1\":\"3\",\"2\":\"Good\",\"_rn_\":\"16\"},{\"1\":\"5\",\"2\":\"Good\",\"_rn_\":\"17\"},{\"1\":\"13\",\"2\":\"Good\",\"_rn_\":\"18\"},{\"1\":\"8\",\"2\":\"Good\",\"_rn_\":\"19\"},{\"1\":\"8\",\"2\":\"Good\",\"_rn_\":\"20\"},{\"1\":\"10\",\"2\":\"Good\",\"_rn_\":\"21\"},{\"1\":\"8\",\"2\":\"Good\",\"_rn_\":\"22\"},{\"1\":\"8\",\"2\":\"Standard\",\"_rn_\":\"23\"},{\"1\":\"8\",\"2\":\"Standard\",\"_rn_\":\"24\"},{\"1\":\"0\",\"2\":\"Standard\",\"_rn_\":\"25\"},{\"1\":\"5\",\"2\":\"Standard\",\"_rn_\":\"26\"},{\"1\":\"3\",\"2\":\"Standard\",\"_rn_\":\"27\"},{\"1\":\"7\",\"2\":\"Standard\",\"_rn_\":\"28\"},{\"1\":\"5\",\"2\":\"Standard\",\"_rn_\":\"29\"},{\"1\":\"5\",\"2\":\"Standard\",\"_rn_\":\"30\"},{\"1\":\"5\",\"2\":\"Standard\",\"_rn_\":\"31\"},{\"1\":\"4\",\"2\":\"Standard\",\"_rn_\":\"32\"},{\"1\":\"5\",\"2\":\"Standard\",\"_rn_\":\"33\"},{\"1\":\"9\",\"2\":\"Standard\",\"_rn_\":\"34\"},{\"1\":\"5\",\"2\":\"Standard\",\"_rn_\":\"35\"},{\"1\":\"1\",\"2\":\"Standard\",\"_rn_\":\"36\"},{\"1\":\"9\",\"2\":\"Standard\",\"_rn_\":\"37\"},{\"1\":\"5\",\"2\":\"Standard\",\"_rn_\":\"38\"},{\"1\":\"10\",\"2\":\"Standard\",\"_rn_\":\"39\"},{\"1\":\"1\",\"2\":\"Standard\",\"_rn_\":\"40\"},{\"1\":\"12\",\"2\":\"Good\",\"_rn_\":\"41\"},{\"1\":\"8\",\"2\":\"Good\",\"_rn_\":\"42\"},{\"1\":\"8\",\"2\":\"Good\",\"_rn_\":\"43\"},{\"1\":\"8\",\"2\":\"Good\",\"_rn_\":\"44\"},{\"1\":\"11\",\"2\":\"Good\",\"_rn_\":\"45\"},{\"1\":\"7\",\"2\":\"Good\",\"_rn_\":\"46\"},{\"1\":\"8\",\"2\":\"Standard\",\"_rn_\":\"47\"},{\"1\":\"8\",\"2\":\"Good\",\"_rn_\":\"48\"},{\"1\":\"0\",\"2\":\"Good\",\"_rn_\":\"49\"},{\"1\":\"-1\",\"2\":\"Good\",\"_rn_\":\"50\"},{\"1\":\"0\",\"2\":\"Good\",\"_rn_\":\"51\"},{\"1\":\"0\",\"2\":\"Good\",\"_rn_\":\"52\"},{\"1\":\"0\",\"2\":\"Good\",\"_rn_\":\"53\"},{\"1\":\"0\",\"2\":\"Standard\",\"_rn_\":\"54\"},{\"1\":\"0\",\"2\":\"Good\",\"_rn_\":\"55\"},{\"1\":\"0\",\"2\":\"Good\",\"_rn_\":\"56\"},{\"1\":\"30\",\"2\":\"Poor\",\"_rn_\":\"57\"},{\"1\":\"30\",\"2\":\"Poor\",\"_rn_\":\"58\"},{\"1\":\"31\",\"2\":\"Poor\",\"_rn_\":\"59\"},{\"1\":\"34\",\"2\":\"Poor\",\"_rn_\":\"60\"},{\"1\":\"27\",\"2\":\"Standard\",\"_rn_\":\"61\"},{\"1\":\"30\",\"2\":\"Standard\",\"_rn_\":\"62\"},{\"1\":\"30\",\"2\":\"Standard\",\"_rn_\":\"63\"},{\"1\":\"30\",\"2\":\"Poor\",\"_rn_\":\"64\"},{\"1\":\"13\",\"2\":\"Good\",\"_rn_\":\"65\"},{\"1\":\"14\",\"2\":\"Good\",\"_rn_\":\"66\"},{\"1\":\"11\",\"2\":\"Good\",\"_rn_\":\"67\"},{\"1\":\"11\",\"2\":\"Good\",\"_rn_\":\"68\"},{\"1\":\"11\",\"2\":\"Standard\",\"_rn_\":\"69\"},{\"1\":\"13\",\"2\":\"Good\",\"_rn_\":\"70\"},{\"1\":\"11\",\"2\":\"Good\",\"_rn_\":\"71\"},{\"1\":\"11\",\"2\":\"Standard\",\"_rn_\":\"72\"},{\"1\":\"4\",\"2\":\"Good\",\"_rn_\":\"73\"},{\"1\":\"2\",\"2\":\"Good\",\"_rn_\":\"74\"},{\"1\":\"-2\",\"2\":\"Good\",\"_rn_\":\"75\"},{\"1\":\"1\",\"2\":\"Good\",\"_rn_\":\"76\"},{\"1\":\"1\",\"2\":\"Good\",\"_rn_\":\"77\"},{\"1\":\"1\",\"2\":\"Good\",\"_rn_\":\"78\"},{\"1\":\"-1\",\"2\":\"Good\",\"_rn_\":\"79\"},{\"1\":\"-2\",\"2\":\"Good\",\"_rn_\":\"80\"},{\"1\":\"16\",\"2\":\"Standard\",\"_rn_\":\"81\"},{\"1\":\"16\",\"2\":\"Standard\",\"_rn_\":\"82\"},{\"1\":\"16\",\"2\":\"Standard\",\"_rn_\":\"83\"},{\"1\":\"17\",\"2\":\"Standard\",\"_rn_\":\"84\"},{\"1\":\"16\",\"2\":\"Standard\",\"_rn_\":\"85\"},{\"1\":\"16\",\"2\":\"Standard\",\"_rn_\":\"86\"},{\"1\":\"16\",\"2\":\"Standard\",\"_rn_\":\"87\"},{\"1\":\"16\",\"2\":\"Standard\",\"_rn_\":\"88\"},{\"1\":\"-1\",\"2\":\"Standard\",\"_rn_\":\"89\"},{\"1\":\"4\",\"2\":\"Good\",\"_rn_\":\"90\"},{\"1\":\"4\",\"2\":\"Standard\",\"_rn_\":\"91\"},{\"1\":\"4\",\"2\":\"Standard\",\"_rn_\":\"92\"},{\"1\":\"4\",\"2\":\"Good\",\"_rn_\":\"93\"},{\"1\":\"4\",\"2\":\"Good\",\"_rn_\":\"94\"},{\"1\":\"4\",\"2\":\"Good\",\"_rn_\":\"95\"},{\"1\":\"-1\",\"2\":\"Good\",\"_rn_\":\"96\"},{\"1\":\"10\",\"2\":\"Standard\",\"_rn_\":\"97\"},{\"1\":\"10\",\"2\":\"Standard\",\"_rn_\":\"98\"},{\"1\":\"15\",\"2\":\"Standard\",\"_rn_\":\"99\"},{\"1\":\"10\",\"2\":\"Standard\",\"_rn_\":\"100\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\nWe can observe some values being negative which indicate the early payment of the bill by the customer. The box plot for the data is as follows:\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(delay_data)+\n  geom_boxplot(aes(x=Credit_Score, y=Delay_from_due_date))+\n  labs(title = \"Box plot representing delay from due date for credit score categories\")\n```\n\n::: {.cell-output-display}\n![](PranavKomaravolu_FinalProject_files/figure-html/unnamed-chunk-41-1.png){width=672}\n:::\n:::\n\nWe observe an expected trend showing clear disparity between the distributions of the three different Credit_Score categories. Here we observe the credit score category good to have lower number of delayed days than that of standard which is then followed by poor.\n\n#### Credit Utilization Ratio\nCredit utilization ratio represents the amount of credit utilized by a person divided by the credit limit that was assigned to the person. There are many different opinions on how this parameter affects the attribute. Some believe that a credit utilization under 30\\% improves the credit score while some deny this. We can try to verify whether this under 30\\% assumption is valid for the current datset or not. This can be analyzed using a box plots for different credit score categories.\n\nThe data for the box plot can be obtained as follows:\n\n::: {.cell}\n\n```{.r .cell-code}\nutilization_data <- data%>%\n                      select(Credit_Utilization_Ratio, Credit_Score)\nhead(utilization_data, 100)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Credit_Utilization_Ratio\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Credit_Score\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"26.82262\",\"2\":\"Good\",\"_rn_\":\"1\"},{\"1\":\"31.94496\",\"2\":\"Good\",\"_rn_\":\"2\"},{\"1\":\"28.60935\",\"2\":\"Good\",\"_rn_\":\"3\"},{\"1\":\"31.37786\",\"2\":\"Good\",\"_rn_\":\"4\"},{\"1\":\"24.79735\",\"2\":\"Good\",\"_rn_\":\"5\"},{\"1\":\"27.26226\",\"2\":\"Good\",\"_rn_\":\"6\"},{\"1\":\"22.53759\",\"2\":\"Good\",\"_rn_\":\"7\"},{\"1\":\"23.93379\",\"2\":\"Standard\",\"_rn_\":\"8\"},{\"1\":\"24.46403\",\"2\":\"Standard\",\"_rn_\":\"9\"},{\"1\":\"38.55085\",\"2\":\"Good\",\"_rn_\":\"10\"},{\"1\":\"33.22495\",\"2\":\"Standard\",\"_rn_\":\"11\"},{\"1\":\"39.18266\",\"2\":\"Good\",\"_rn_\":\"12\"},{\"1\":\"34.97789\",\"2\":\"Good\",\"_rn_\":\"13\"},{\"1\":\"33.38101\",\"2\":\"Good\",\"_rn_\":\"14\"},{\"1\":\"31.13170\",\"2\":\"Good\",\"_rn_\":\"15\"},{\"1\":\"32.93386\",\"2\":\"Good\",\"_rn_\":\"16\"},{\"1\":\"28.61673\",\"2\":\"Good\",\"_rn_\":\"17\"},{\"1\":\"41.70257\",\"2\":\"Good\",\"_rn_\":\"18\"},{\"1\":\"26.51982\",\"2\":\"Good\",\"_rn_\":\"19\"},{\"1\":\"39.50165\",\"2\":\"Good\",\"_rn_\":\"20\"},{\"1\":\"31.37615\",\"2\":\"Good\",\"_rn_\":\"21\"},{\"1\":\"39.78399\",\"2\":\"Good\",\"_rn_\":\"22\"},{\"1\":\"38.06862\",\"2\":\"Standard\",\"_rn_\":\"23\"},{\"1\":\"38.37475\",\"2\":\"Standard\",\"_rn_\":\"24\"},{\"1\":\"26.54423\",\"2\":\"Standard\",\"_rn_\":\"25\"},{\"1\":\"35.27998\",\"2\":\"Standard\",\"_rn_\":\"26\"},{\"1\":\"32.30116\",\"2\":\"Standard\",\"_rn_\":\"27\"},{\"1\":\"38.13235\",\"2\":\"Standard\",\"_rn_\":\"28\"},{\"1\":\"41.15432\",\"2\":\"Standard\",\"_rn_\":\"29\"},{\"1\":\"27.44542\",\"2\":\"Standard\",\"_rn_\":\"30\"},{\"1\":\"26.05640\",\"2\":\"Standard\",\"_rn_\":\"31\"},{\"1\":\"27.33251\",\"2\":\"Standard\",\"_rn_\":\"32\"},{\"1\":\"39.79776\",\"2\":\"Standard\",\"_rn_\":\"33\"},{\"1\":\"27.02036\",\"2\":\"Standard\",\"_rn_\":\"34\"},{\"1\":\"23.46230\",\"2\":\"Standard\",\"_rn_\":\"35\"},{\"1\":\"28.92495\",\"2\":\"Standard\",\"_rn_\":\"36\"},{\"1\":\"41.77619\",\"2\":\"Standard\",\"_rn_\":\"37\"},{\"1\":\"29.21756\",\"2\":\"Standard\",\"_rn_\":\"38\"},{\"1\":\"26.26382\",\"2\":\"Standard\",\"_rn_\":\"39\"},{\"1\":\"25.86292\",\"2\":\"Standard\",\"_rn_\":\"40\"},{\"1\":\"39.96269\",\"2\":\"Good\",\"_rn_\":\"41\"},{\"1\":\"42.76986\",\"2\":\"Good\",\"_rn_\":\"42\"},{\"1\":\"40.71219\",\"2\":\"Good\",\"_rn_\":\"43\"},{\"1\":\"30.20166\",\"2\":\"Good\",\"_rn_\":\"44\"},{\"1\":\"26.33331\",\"2\":\"Good\",\"_rn_\":\"45\"},{\"1\":\"35.27544\",\"2\":\"Good\",\"_rn_\":\"46\"},{\"1\":\"36.62479\",\"2\":\"Standard\",\"_rn_\":\"47\"},{\"1\":\"31.58099\",\"2\":\"Good\",\"_rn_\":\"48\"},{\"1\":\"32.20051\",\"2\":\"Good\",\"_rn_\":\"49\"},{\"1\":\"31.98371\",\"2\":\"Good\",\"_rn_\":\"50\"},{\"1\":\"31.80313\",\"2\":\"Good\",\"_rn_\":\"51\"},{\"1\":\"42.64578\",\"2\":\"Good\",\"_rn_\":\"52\"},{\"1\":\"40.90252\",\"2\":\"Good\",\"_rn_\":\"53\"},{\"1\":\"41.98017\",\"2\":\"Standard\",\"_rn_\":\"54\"},{\"1\":\"26.94757\",\"2\":\"Good\",\"_rn_\":\"55\"},{\"1\":\"29.18791\",\"2\":\"Good\",\"_rn_\":\"56\"},{\"1\":\"24.44806\",\"2\":\"Poor\",\"_rn_\":\"57\"},{\"1\":\"35.17116\",\"2\":\"Poor\",\"_rn_\":\"58\"},{\"1\":\"35.11155\",\"2\":\"Poor\",\"_rn_\":\"59\"},{\"1\":\"29.76216\",\"2\":\"Poor\",\"_rn_\":\"60\"},{\"1\":\"30.20621\",\"2\":\"Standard\",\"_rn_\":\"61\"},{\"1\":\"31.17087\",\"2\":\"Standard\",\"_rn_\":\"62\"},{\"1\":\"38.43851\",\"2\":\"Standard\",\"_rn_\":\"63\"},{\"1\":\"33.82349\",\"2\":\"Poor\",\"_rn_\":\"64\"},{\"1\":\"33.66455\",\"2\":\"Good\",\"_rn_\":\"65\"},{\"1\":\"27.62633\",\"2\":\"Good\",\"_rn_\":\"66\"},{\"1\":\"35.14157\",\"2\":\"Good\",\"_rn_\":\"67\"},{\"1\":\"30.45903\",\"2\":\"Good\",\"_rn_\":\"68\"},{\"1\":\"29.81919\",\"2\":\"Standard\",\"_rn_\":\"69\"},{\"1\":\"26.11421\",\"2\":\"Good\",\"_rn_\":\"70\"},{\"1\":\"31.76752\",\"2\":\"Good\",\"_rn_\":\"71\"},{\"1\":\"27.81335\",\"2\":\"Standard\",\"_rn_\":\"72\"},{\"1\":\"29.51935\",\"2\":\"Good\",\"_rn_\":\"73\"},{\"1\":\"28.22048\",\"2\":\"Good\",\"_rn_\":\"74\"},{\"1\":\"31.04642\",\"2\":\"Good\",\"_rn_\":\"75\"},{\"1\":\"30.16803\",\"2\":\"Good\",\"_rn_\":\"76\"},{\"1\":\"25.18923\",\"2\":\"Good\",\"_rn_\":\"77\"},{\"1\":\"25.50247\",\"2\":\"Good\",\"_rn_\":\"78\"},{\"1\":\"22.76220\",\"2\":\"Good\",\"_rn_\":\"79\"},{\"1\":\"37.56505\",\"2\":\"Good\",\"_rn_\":\"80\"},{\"1\":\"37.08908\",\"2\":\"Standard\",\"_rn_\":\"81\"},{\"1\":\"30.90808\",\"2\":\"Standard\",\"_rn_\":\"82\"},{\"1\":\"38.03072\",\"2\":\"Standard\",\"_rn_\":\"83\"},{\"1\":\"23.40441\",\"2\":\"Standard\",\"_rn_\":\"84\"},{\"1\":\"29.07376\",\"2\":\"Standard\",\"_rn_\":\"85\"},{\"1\":\"32.78264\",\"2\":\"Standard\",\"_rn_\":\"86\"},{\"1\":\"35.58401\",\"2\":\"Standard\",\"_rn_\":\"87\"},{\"1\":\"31.13948\",\"2\":\"Standard\",\"_rn_\":\"88\"},{\"1\":\"28.21062\",\"2\":\"Standard\",\"_rn_\":\"89\"},{\"1\":\"41.03617\",\"2\":\"Good\",\"_rn_\":\"90\"},{\"1\":\"34.67019\",\"2\":\"Standard\",\"_rn_\":\"91\"},{\"1\":\"31.82854\",\"2\":\"Standard\",\"_rn_\":\"92\"},{\"1\":\"34.70284\",\"2\":\"Good\",\"_rn_\":\"93\"},{\"1\":\"38.32364\",\"2\":\"Good\",\"_rn_\":\"94\"},{\"1\":\"25.97917\",\"2\":\"Good\",\"_rn_\":\"95\"},{\"1\":\"30.87080\",\"2\":\"Good\",\"_rn_\":\"96\"},{\"1\":\"25.64925\",\"2\":\"Standard\",\"_rn_\":\"97\"},{\"1\":\"29.40878\",\"2\":\"Standard\",\"_rn_\":\"98\"},{\"1\":\"31.25893\",\"2\":\"Standard\",\"_rn_\":\"99\"},{\"1\":\"27.19259\",\"2\":\"Standard\",\"_rn_\":\"100\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\nNow we can plot the box plot as follows:\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(utilization_data)+\n  geom_boxplot(aes(x=Credit_Score, y=Credit_Utilization_Ratio))+\n  labs(title = \"Box plot representing Credit utilization for credit score categories\")\n```\n\n::: {.cell-output-display}\n![](PranavKomaravolu_FinalProject_files/figure-html/unnamed-chunk-43-1.png){width=672}\n:::\n:::\n\nThere is no significant difference between three Credit score categories. The utilization seems to be slightly higher for the good category, the other two categories has almost similar distribution.\n\n#### Payment Behavior\nThe credit score is also dependent on how the credit is being utilized. That is how much credit and in what kind of payments. To observe the correlation of payment behavior with the credit score we can utilize bar plots.\n\nThe data for the barplot can be obtained as follows:\n\n::: {.cell}\n\n```{.r .cell-code}\npayment_data <- data%>%\n                  group_by(Payment_Behaviour, Credit_Score)%>%\n                  summarise(counts = n())\nhead(payment_data, 100)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Payment_Behaviour\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Credit_Score\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"counts\"],\"name\":[3],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"!@9#%8\",\"2\":\"Good\",\"3\":\"1383\"},{\"1\":\"!@9#%8\",\"2\":\"Poor\",\"3\":\"2225\"},{\"1\":\"!@9#%8\",\"2\":\"Standard\",\"3\":\"3992\"},{\"1\":\"High_spent_Large_value_payments\",\"2\":\"Good\",\"3\":\"3172\"},{\"1\":\"High_spent_Large_value_payments\",\"2\":\"Poor\",\"3\":\"2979\"},{\"1\":\"High_spent_Large_value_payments\",\"2\":\"Standard\",\"3\":\"7570\"},{\"1\":\"High_spent_Medium_value_payments\",\"2\":\"Good\",\"3\":\"3524\"},{\"1\":\"High_spent_Medium_value_payments\",\"2\":\"Poor\",\"3\":\"4439\"},{\"1\":\"High_spent_Medium_value_payments\",\"2\":\"Standard\",\"3\":\"9577\"},{\"1\":\"High_spent_Small_value_payments\",\"2\":\"Good\",\"3\":\"2114\"},{\"1\":\"High_spent_Small_value_payments\",\"2\":\"Poor\",\"3\":\"3088\"},{\"1\":\"High_spent_Small_value_payments\",\"2\":\"Standard\",\"3\":\"6138\"},{\"1\":\"Low_spent_Large_value_payments\",\"2\":\"Good\",\"3\":\"1880\"},{\"1\":\"Low_spent_Large_value_payments\",\"2\":\"Poor\",\"3\":\"2931\"},{\"1\":\"Low_spent_Large_value_payments\",\"2\":\"Standard\",\"3\":\"5614\"},{\"1\":\"Low_spent_Medium_value_payments\",\"2\":\"Good\",\"3\":\"2482\"},{\"1\":\"Low_spent_Medium_value_payments\",\"2\":\"Poor\",\"3\":\"4211\"},{\"1\":\"Low_spent_Medium_value_payments\",\"2\":\"Standard\",\"3\":\"7168\"},{\"1\":\"Low_spent_Small_value_payments\",\"2\":\"Good\",\"3\":\"3273\"},{\"1\":\"Low_spent_Small_value_payments\",\"2\":\"Poor\",\"3\":\"9125\"},{\"1\":\"Low_spent_Small_value_payments\",\"2\":\"Standard\",\"3\":\"13115\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\nNow we can plot the bar plot as follows:\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(payment_data)+\n  geom_bar(aes(x = Payment_Behaviour, y=counts, fill=Credit_Score), stat = \"identity\", position = \"dodge\")+\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](PranavKomaravolu_FinalProject_files/figure-html/unnamed-chunk-45-1.png){width=672}\n:::\n:::\n\nTherefore individuals who spent high in the form of medium valued payments appear to have higher credit score. But when it comes to the people having poor or standard credit scores appear to spend low in the form of small valued payments.\n\n## Conclusions & Discussion\n\nThe calculation of credit score involves collection of large amount of information about an individual and some set of complex algorithms that are developed and updated by the credit bureaus. This score determines the individuals purchasing power and access in the society. Through this paper, I tried to understand how this calculation is performed and what kind of factors affect it the most. The answers to the initially mentioned research questions are as follows:\n\n1) What social parameters or behavioral patterns determine the credit score of an individual?\n\nIn this project I analyzed 7 parameter of which three of these were social parameters and four of these were behavioral patterns. I observed the following from the experiments:\n\n* The age of the person appears to impact the credit score as the individuals closer to the median age groups of the working class have higher credit scores as compared to those who are either younger or older. This could be due to the fact that most of the individuals in these age groups are skilled and employed.\n\n* Upon analysis of the occupation being a deciding factor for credit score, I found that some professions in the society tend to tend to favor higher credit scores.\n\n* The Annual income of an individual clearly affects the credit score as from the dataset we can observe a clear disparity in the income of individuals with good credit scores as compared to those with poor credit scores.\n\n* When it comes to number of credit cards, we observe that the people with higher credit scores tend to have less number of credit cards as compared to those with standard and poor credit scores.\n\n* The delay in repayment of credit had a clear impact on the credit score as we observed that longer delays lead to lower credit scores.\n\n* When it comes to credit utilization we do not observe a significant affect on the credit score.\n\n* The payment behavior seems to affect the credit score significantly.\n\nTherefore 6 out of the 7 parameters analyzed tend to have a significant affect on how the credit score is calculated.\n\n2) Is it possible for us to estimate the credit score given the required information?\n\nFrom the above analysis, we can conclude that it is possible to estimate the credit score of an individual given certain bigrahic information and financial behavioral patterns.\n\n## Bibliography\n1) Paris, Rohan. “Credit Score Classification.” Kaggle, 22 June 2022, www.kaggle.com/datasets/parisrohan/credit-score-classification. [Accessed: 22-May-2023] \n2) J. Lohokare, R. Dani and S. Sontakke, \"Automated data collection for credit score calculation based on financial transactions and social media,\" 2017 International Conference on Emerging Trends & Innovation in ICT (ICEI), Pune, India, 2017, pp. 134-138, doi: 10.1109/ETIICT.2017.7977024.\n3) R, The Comprehensive R Archive Network, https://cran.r-project.org/. [Accessed: 22-May-2023] \n\n",
    "supporting": [
      "PranavKomaravolu_FinalProject_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}