{
  "hash": "38a5abb3e89a289642b166a5ec9c4bb4",
  "result": {
    "markdown": "---\ntitle: \"Final Project: Fnu Avinesh Krishnan\"\nauthor: \"Fnu Avinesh Krishnan\"\ndescription: \"Final Project writeup\"\ndate: \"05/22/2023\"\nformat:\n  html:\n    df-print: paged\n    toc: true\n    code-copy: true\n    code-tools: true\n    css: styles.css\ncategories:\n  - final_Project\neditor_options: \n  chunk_output_type: console\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(ggplot2)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Part 1. Introduction \n\nProject Topic: The project aims to analyze factors of a patient suffering from a particular genetic disorder based on their medical record containing various information about the patient.\n\nGeneral Research Questions: What are the major conditions that help in early diagnosis of a genetic disorder in a patient? Are these factors inter-dependent on each other?\n\nDataset Description: \n\nThe genome and genetics dataset is collected by the National Center for Biotechnology Information (NCBI). The dataset includes patients with various genetic disorders, and the genetic disorders can be broadly categorized into three groups: mitochondrial genetic inheritance disorders, single-gene inheritance diseases, and multifactorial genetic inheritance disorders. These genetic disorders are just a few examples of the conditions that are included in the dataset.\n\nUnit of Analysis: Each row represents classified medicial information like Age, Maternal and Paternal gene, Blood cell count, Respiratory and Heart rate, Test results, Previous abortions, Presence of symptoms, Birth defects and the Genetic disorder of a particular patient.\n\nMy study aims to analyse the relationship between different genetic factors, extracting insights based on correlation between medical precursors and test results, and predict the specific genetic disorder and its subclass for each patient based on their medical information.\n\n## Part 2. Background of the Topic/Literature Review\n\nThe exponential growth of the global population has resulted in a strain on essential resources such as healthcare, food, and shelter, which in turn has led to an increase in the incidence of genetic disorders. Genetic disorders are health conditions that typically result from DNA mutations or changes in the overall structure or number of chromosomes. Hereditary illnesses are becoming more prevalent due to insufficient awareness regarding the necessity of genetic testing. Tragically, such illnesses frequently result in the premature death of children, underscoring the vital significance of genetic testing during pregnancy.\n\n## Part 3. Dataset Introduction\n\nThe dataset includes patients with various genetic disorders, and the objective is to predict the specific genetic disorder and its subclass for each patient based on their medical information. Some of the disorder subclasses present in the dataset are Leigh syndrome, which is a rare inherited neurometabolic disorder, mitochondrial myopathy, which is a genetic disorder that affects the muscles and other organs that require a lot of energy, cystic fibrosis, which is a progressive genetic disorder that affects the lungs, pancreas, and other organs, Tay-Sachs, which is a rare inherited disorder that progressively destroys nerve cells in the brain and spinal cord, and diabetes, which is a metabolic disorder characterized by high blood sugar levels. These disorder subclasses are just a few examples of the conditions that are included in the dataset, and our project aims to study the subclass for each patient based on their medical information and analysing the correlation between them to help in pre-emptive detection of the disease. \n\n## Part 4. Dataset Description\n\n(Story)\nThis dataset contains a total of 22083 rows and 45 columns and the descriptive information about each of the 45 features are given below: \n\n    -     Patient Id: Represents the unique identification number of a patient\n    -     Patient Age: Represents the age of a patient\n    -     Genes in mother's side: Represents a gene defect in the patient's mother\n    -     Inherited from father: Represents a gene defect in the patient's father\n    -     Maternal gene: Represents a gene defect in the patient's maternal side of the family\n    -     Paternal gene: Represents a gene defect in the patient's paternal side of the family\n    -     Blood cell count (mcL): Represents the blood cell count of a patient\n    -     Patient First Name: Represents a patient's first name\n    -     Family Name: Represents a patient's family name or surname\n    -     Father's name: Represents a patient's father's name\n    -    Mother's age: Represents a patient's mother's name                                    \n    -     Father's age: Represents a patient's father's age                                   \n    -     Institute Name: Represents the medical institute where a patient was born                   \n    -     Location of Institute: Represents the location of the medical institute                      \n    -     Status: Represents whether a patient is deceased                                         \n    -     Respiratory Rate (breaths/min): Represents a patient's respiratory breathing rate           \n    -    Heart Rate (rates/min): Represents a patient's heart rate                          \n    -     Test 1 to Test 5: Represents different (masked) tests that were conducted on a patient\n    -     Parental consent: Represents whether a patient's parents approved the treatment plan        \n    -    Follow-up: Represents a patient's level of risk (how intense their condition is)  \n    -     Gender: Represents a patient's gender                                         \n    -     Birth asphyxia: Represents whether a patient suffered from birth asphyxia                    \n    -     Autopsy shows birth defect (if applicable): Represents whether a patient's autopsy showed any birth defects     \n    -     Place of birth: Represents whether a patient was born in a medical institute or home        \n    -     Folic acid details (peri-conceptional): Represents the periconceptional folic acid supplementation details of a patient          \n    -    H/O serious maternal illness: Represents an unexpected outcome of labor and delivery that resulted in significant short or long-term consequences to a patient's mother                 \n    -    H/O radiation exposure (x-ray): Represents whether a patient has any radiation exposure history     \n    -    H/O substance abuse: Represents whether a parent has a history of drug addiction             \n    -    Assisted conception IVF/ART: Represents the type of treatment used for infertility            \n    -    History of anomalies in previous pregnancies: Represents whether the mother had any anomalies in her previous pregnancies   \n    -    No. of previous abortion: Represents the number of abortions that a mother had                \n    -    Birth defects: Represents whether a patient has birth defects                                \n    -    White Blood cell count (thousand per microliter): Represents a patient's white blood cell count\n    -    Blood test result: Represents a patient's blood test results                              \n    -    Symptom 1 to Symptom 5: Represents (masked) different types of symptoms that a patient had    \n    -    Genetic Disorder: Represents the genetic disorder that a patient has                          \n    -    Disorder Subclass: Represents the subclass of the disorder\n\nCoding Component:\n\n1.  Read the titanic dataset;\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#read and get a overview of the data\nlibrary(readr)\ndata<-read_csv(\"/Users/avineshkrishnan/Desktop/FnuAvineshKrishnan_FinalProjectData/train_genetic_disorders.csv\")\nview(data)\n```\n:::\n\n\n2. Descriptive information of the titanic dataset :\n\n\n    ::: {.cell}\n    \n    ```{.r .cell-code}\n    # Checking the dimensions of the data\n    dim(data)\n    ```\n    \n    ::: {.cell-output .cell-output-stdout}\n    ```\n    [1] 22083    45\n    ```\n    :::\n    \n    ```{.r .cell-code}\n    # checking the number of unique disorder sub classes present \n    length(unique(data$`Disorder Subclass`))\n    ```\n    \n    ::: {.cell-output .cell-output-stdout}\n    ```\n    [1] 10\n    ```\n    :::\n    \n    ```{.r .cell-code}\n    #printing out the first few examples\n    head(data)\n    ```\n    \n    ::: {.cell-output-display}\n    `````{=html}\n    <div data-pagedtable=\"false\">\n      <script data-pagedtable-source type=\"application/json\">\n    {\"columns\":[{\"label\":[\"Patient Id\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Patient Age\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Genes in mother's side\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Inherited from father\"],\"name\":[4],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Maternal gene\"],\"name\":[5],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Paternal gene\"],\"name\":[6],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Blood cell count (mcL)\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Patient First Name\"],\"name\":[8],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Family Name\"],\"name\":[9],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Father's name\"],\"name\":[10],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Mother's age\"],\"name\":[11],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Father's age\"],\"name\":[12],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Institute Name\"],\"name\":[13],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Location of Institute\"],\"name\":[14],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Status\"],\"name\":[15],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Respiratory Rate (breaths/min)\"],\"name\":[16],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Heart Rate (rates/min\"],\"name\":[17],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Test 1\"],\"name\":[18],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Test 2\"],\"name\":[19],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Test 3\"],\"name\":[20],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Test 4\"],\"name\":[21],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Test 5\"],\"name\":[22],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Parental consent\"],\"name\":[23],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Follow-up\"],\"name\":[24],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Gender\"],\"name\":[25],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Birth asphyxia\"],\"name\":[26],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Autopsy shows birth defect (if applicable)\"],\"name\":[27],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Place of birth\"],\"name\":[28],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Folic acid details (peri-conceptional)\"],\"name\":[29],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"H/O serious maternal illness\"],\"name\":[30],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"H/O radiation exposure (x-ray)\"],\"name\":[31],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"H/O substance abuse\"],\"name\":[32],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Assisted conception IVF/ART\"],\"name\":[33],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"History of anomalies in previous pregnancies\"],\"name\":[34],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"No. of previous abortion\"],\"name\":[35],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Birth defects\"],\"name\":[36],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"White Blood cell count (thousand per microliter)\"],\"name\":[37],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Blood test result\"],\"name\":[38],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Symptom 1\"],\"name\":[39],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Symptom 2\"],\"name\":[40],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Symptom 3\"],\"name\":[41],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Symptom 4\"],\"name\":[42],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Symptom 5\"],\"name\":[43],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Genetic Disorder\"],\"name\":[44],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Disorder Subclass\"],\"name\":[45],\"type\":[\"chr\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"PID0x6418\",\"2\":\"2\",\"3\":\"Yes\",\"4\":\"No\",\"5\":\"Yes\",\"6\":\"No\",\"7\":\"4.760603\",\"8\":\"Richard\",\"9\":\"NA\",\"10\":\"Larre\",\"11\":\"NA\",\"12\":\"NA\",\"13\":\"Boston Specialty & Rehabilitation Hospital\",\"14\":\"55 FRUIT ST\\\\nCENTRAL, MA 02114\\\\n(42.36247485742686, -71.06924724545246)\",\"15\":\"Alive\",\"16\":\"Normal (30-60)\",\"17\":\"Normal\",\"18\":\"0\",\"19\":\"NA\",\"20\":\"NA\",\"21\":\"1\",\"22\":\"0\",\"23\":\"Yes\",\"24\":\"High\",\"25\":\"NA\",\"26\":\"NA\",\"27\":\"Not applicable\",\"28\":\"Institute\",\"29\":\"No\",\"30\":\"NA\",\"31\":\"No\",\"32\":\"No\",\"33\":\"No\",\"34\":\"Yes\",\"35\":\"NA\",\"36\":\"NA\",\"37\":\"9.857562\",\"38\":\"NA\",\"39\":\"1\",\"40\":\"1\",\"41\":\"1\",\"42\":\"1\",\"43\":\"1\",\"44\":\"Mitochondrial genetic inheritance disorders\",\"45\":\"Leber's hereditary optic neuropathy\"},{\"1\":\"PID0x25d5\",\"2\":\"4\",\"3\":\"Yes\",\"4\":\"Yes\",\"5\":\"No\",\"6\":\"No\",\"7\":\"4.910669\",\"8\":\"Mike\",\"9\":\"NA\",\"10\":\"Brycen\",\"11\":\"NA\",\"12\":\"23\",\"13\":\"St. Margaret's Hospital For Women\",\"14\":\"1515 COMMONWEALTH AV\\\\nALLSTON/BRIGHTON, MA 02135\\\\n(42.34665771451756, -71.14136122385321)\",\"15\":\"Deceased\",\"16\":\"Tachypnea\",\"17\":\"Normal\",\"18\":\"NA\",\"19\":\"0\",\"20\":\"0\",\"21\":\"1\",\"22\":\"0\",\"23\":\"Yes\",\"24\":\"High\",\"25\":\"NA\",\"26\":\"No\",\"27\":\"None\",\"28\":\"NA\",\"29\":\"Yes\",\"30\":\"Yes\",\"31\":\"Not applicable\",\"32\":\"Not applicable\",\"33\":\"No\",\"34\":\"Yes\",\"35\":\"NA\",\"36\":\"Multiple\",\"37\":\"5.522560\",\"38\":\"normal\",\"39\":\"1\",\"40\":\"NA\",\"41\":\"1\",\"42\":\"1\",\"43\":\"0\",\"44\":\"NA\",\"45\":\"Cystic fibrosis\"},{\"1\":\"PID0x4a82\",\"2\":\"6\",\"3\":\"Yes\",\"4\":\"No\",\"5\":\"No\",\"6\":\"No\",\"7\":\"4.893297\",\"8\":\"Kimberly\",\"9\":\"NA\",\"10\":\"Nashon\",\"11\":\"41\",\"12\":\"22\",\"13\":\"NA\",\"14\":\"-\",\"15\":\"Alive\",\"16\":\"Normal (30-60)\",\"17\":\"Tachycardia\",\"18\":\"0\",\"19\":\"0\",\"20\":\"0\",\"21\":\"1\",\"22\":\"0\",\"23\":\"Yes\",\"24\":\"Low\",\"25\":\"NA\",\"26\":\"No record\",\"27\":\"Not applicable\",\"28\":\"NA\",\"29\":\"Yes\",\"30\":\"No\",\"31\":\"Yes\",\"32\":\"NA\",\"33\":\"Yes\",\"34\":\"Yes\",\"35\":\"4\",\"36\":\"Singular\",\"37\":\"NA\",\"38\":\"normal\",\"39\":\"0\",\"40\":\"1\",\"41\":\"1\",\"42\":\"1\",\"43\":\"1\",\"44\":\"Multifactorial genetic inheritance disorders\",\"45\":\"Diabetes\"},{\"1\":\"PID0x4ac8\",\"2\":\"12\",\"3\":\"Yes\",\"4\":\"No\",\"5\":\"Yes\",\"6\":\"No\",\"7\":\"4.705280\",\"8\":\"Jeffery\",\"9\":\"Hoelscher\",\"10\":\"Aayaan\",\"11\":\"21\",\"12\":\"NA\",\"13\":\"NA\",\"14\":\"55 FRUIT ST\\\\nCENTRAL, MA 02114\\\\n(42.36247485742686, -71.06924724545246)\",\"15\":\"Deceased\",\"16\":\"Tachypnea\",\"17\":\"Normal\",\"18\":\"0\",\"19\":\"0\",\"20\":\"0\",\"21\":\"1\",\"22\":\"0\",\"23\":\"Yes\",\"24\":\"High\",\"25\":\"Male\",\"26\":\"Not available\",\"27\":\"No\",\"28\":\"Institute\",\"29\":\"No\",\"30\":\"Yes\",\"31\":\"-\",\"32\":\"Not applicable\",\"33\":\"NA\",\"34\":\"Yes\",\"35\":\"1\",\"36\":\"Singular\",\"37\":\"7.919321\",\"38\":\"inconclusive\",\"39\":\"0\",\"40\":\"0\",\"41\":\"1\",\"42\":\"0\",\"43\":\"0\",\"44\":\"Mitochondrial genetic inheritance disorders\",\"45\":\"Leigh syndrome\"},{\"1\":\"PID0x1bf7\",\"2\":\"11\",\"3\":\"Yes\",\"4\":\"No\",\"5\":\"NA\",\"6\":\"Yes\",\"7\":\"4.720703\",\"8\":\"Johanna\",\"9\":\"Stutzman\",\"10\":\"Suave\",\"11\":\"32\",\"12\":\"NA\",\"13\":\"Carney Hospital\",\"14\":\"300 LONGWOOD AV\\\\nFENWAY/KENMORE, MA 02115\\\\n(42.337592548462226, -71.10472284437952)\",\"15\":\"Alive\",\"16\":\"Tachypnea\",\"17\":\"Tachycardia\",\"18\":\"0\",\"19\":\"0\",\"20\":\"0\",\"21\":\"1\",\"22\":\"0\",\"23\":\"NA\",\"24\":\"Low\",\"25\":\"Male\",\"26\":\"Not available\",\"27\":\"Not applicable\",\"28\":\"Institute\",\"29\":\"No\",\"30\":\"Yes\",\"31\":\"-\",\"32\":\"Not applicable\",\"33\":\"Yes\",\"34\":\"No\",\"35\":\"4\",\"36\":\"Multiple\",\"37\":\"4.098210\",\"38\":\"NA\",\"39\":\"0\",\"40\":\"0\",\"41\":\"0\",\"42\":\"0\",\"43\":\"NA\",\"44\":\"Multifactorial genetic inheritance disorders\",\"45\":\"Cancer\"},{\"1\":\"PID0x44fe\",\"2\":\"14\",\"3\":\"Yes\",\"4\":\"No\",\"5\":\"Yes\",\"6\":\"No\",\"7\":\"5.103188\",\"8\":\"Richard\",\"9\":\"NA\",\"10\":\"Coleston\",\"11\":\"NA\",\"12\":\"NA\",\"13\":\"Massachusetts General Hospital\",\"14\":\"55 FRUIT ST\\\\nCENTRAL, MA 02114\\\\n(42.36247485742686, -71.06924724545246)\",\"15\":\"Deceased\",\"16\":\"NA\",\"17\":\"Normal\",\"18\":\"0\",\"19\":\"0\",\"20\":\"0\",\"21\":\"1\",\"22\":\"0\",\"23\":\"Yes\",\"24\":\"Low\",\"25\":\"Female\",\"26\":\"Not available\",\"27\":\"None\",\"28\":\"Institute\",\"29\":\"No\",\"30\":\"No\",\"31\":\"No\",\"32\":\"No\",\"33\":\"NA\",\"34\":\"No\",\"35\":\"0\",\"36\":\"Multiple\",\"37\":\"10.272230\",\"38\":\"normal\",\"39\":\"1\",\"40\":\"0\",\"41\":\"0\",\"42\":\"1\",\"43\":\"0\",\"44\":\"Single-gene inheritance diseases\",\"45\":\"Cystic fibrosis\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n      </script>\n    </div>\n    `````\n    :::\n    :::\n\n\n3.  Conduct summary statistics of the dataset : \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(knitr)\n\n# Displaying the summary of the Patients data in a table\n\nsummary_stats <- summary(data)\nkable(summary_stats)\n```\n\n::: {.cell-output-display}\n|   | Patient Id      | Patient Age   |Genes in mother's side |Inherited from father |Maternal gene    |Paternal gene    |Blood cell count (mcL) |Patient First Name |Family Name      |Father's name    | Mother's age | Father's age |Institute Name   |Location of Institute |   Status        |Respiratory Rate (breaths/min) |Heart Rate (rates/min |    Test 1   |    Test 2   |    Test 3   |    Test 4   |    Test 5   |Parental consent | Follow-up       |   Gender        |Birth asphyxia   |Autopsy shows birth defect (if applicable) |Place of birth   |Folic acid details (peri-conceptional) |H/O serious maternal illness |H/O radiation exposure (x-ray) |H/O substance abuse |Assisted conception IVF/ART |History of anomalies in previous pregnancies |No. of previous abortion |Birth defects    |White Blood cell count (thousand per microliter) |Blood test result |  Symptom 1   |  Symptom 2   |  Symptom 3    |  Symptom 4    |  Symptom 5    |Genetic Disorder |Disorder Subclass |\n|:--|:----------------|:--------------|:----------------------|:---------------------|:----------------|:----------------|:----------------------|:------------------|:----------------|:----------------|:-------------|:-------------|:----------------|:---------------------|:----------------|:------------------------------|:---------------------|:------------|:------------|:------------|:------------|:------------|:----------------|:----------------|:----------------|:----------------|:------------------------------------------|:----------------|:--------------------------------------|:----------------------------|:------------------------------|:-------------------|:---------------------------|:--------------------------------------------|:------------------------|:----------------|:------------------------------------------------|:-----------------|:-------------|:-------------|:--------------|:--------------|:--------------|:----------------|:-----------------|\n|   |Length:22083     |Min.   : 0.000 |Length:22083           |Length:22083          |Length:22083     |Length:22083     |Min.   :4.093          |Length:22083       |Length:22083     |Length:22083     |Min.   :18.00 |Min.   :20.00 |Length:22083     |Length:22083          |Length:22083     |Length:22083                   |Length:22083          |Min.   :0    |Min.   :0    |Min.   :0    |Min.   :1    |Min.   :0    |Length:22083     |Length:22083     |Length:22083     |Length:22083     |Length:22083                               |Length:22083     |Length:22083                           |Length:22083                 |Length:22083                   |Length:22083        |Length:22083                |Length:22083                                 |Min.   :0                |Length:22083     |Min.   : 3.000                                   |Length:22083      |Min.   :0.000 |Min.   :0.000 |Min.   :0.0000 |Min.   :0.0000 |Min.   :0.0000 |Length:22083     |Length:22083      |\n|   |Class :character |1st Qu.: 3.000 |Class :character       |Class :character      |Class :character |Class :character |1st Qu.:4.763          |Class :character   |Class :character |Class :character |1st Qu.:26.00 |1st Qu.:31.00 |Class :character |Class :character      |Class :character |Class :character               |Class :character      |1st Qu.:0    |1st Qu.:0    |1st Qu.:0    |1st Qu.:1    |1st Qu.:0    |Class :character |Class :character |Class :character |Class :character |Class :character                           |Class :character |Class :character                       |Class :character             |Class :character               |Class :character    |Class :character            |Class :character                             |1st Qu.:1                |Class :character |1st Qu.: 5.419                                   |Class :character  |1st Qu.:0.000 |1st Qu.:0.000 |1st Qu.:0.0000 |1st Qu.:0.0000 |1st Qu.:0.0000 |Class :character |Class :character  |\n|   |Mode  :character |Median : 7.000 |Mode  :character       |Mode  :character      |Mode  :character |Mode  :character |Median :4.899          |Mode  :character   |Mode  :character |Mode  :character |Median :35.00 |Median :42.00 |Mode  :character |Mode  :character      |Mode  :character |Mode  :character               |Mode  :character      |Median :0    |Median :0    |Median :0    |Median :1    |Median :0    |Mode  :character |Mode  :character |Mode  :character |Mode  :character |Mode  :character                           |Mode  :character |Mode  :character                       |Mode  :character             |Mode  :character               |Mode  :character    |Mode  :character            |Mode  :character                             |Median :2                |Mode  :character |Median : 7.473                                   |Mode  :character  |Median :1.000 |Median :1.000 |Median :1.0000 |Median :0.0000 |Median :0.0000 |Mode  :character |Mode  :character  |\n|   |NA               |Mean   : 6.975 |NA                     |NA                    |NA               |NA               |Mean   :4.899          |NA                 |NA               |NA               |Mean   :34.52 |Mean   :41.94 |NA               |NA                    |NA               |NA                             |NA                    |Mean   :0    |Mean   :0    |Mean   :0    |Mean   :1    |Mean   :0    |NA               |NA               |NA               |NA               |NA                                         |NA               |NA                                     |NA                           |NA                             |NA                  |NA                          |NA                                           |Mean   :2                |NA               |Mean   : 7.485                                   |NA                |Mean   :0.592 |Mean   :0.553 |Mean   :0.5374 |Mean   :0.4974 |Mean   :0.4608 |NA               |NA                |\n|   |NA               |3rd Qu.:11.000 |NA                     |NA                    |NA               |NA               |3rd Qu.:5.034          |NA                 |NA               |NA               |3rd Qu.:43.00 |3rd Qu.:53.00 |NA               |NA                    |NA               |NA                             |NA                    |3rd Qu.:0    |3rd Qu.:0    |3rd Qu.:0    |3rd Qu.:1    |3rd Qu.:0    |NA               |NA               |NA               |NA               |NA                                         |NA               |NA                                     |NA                           |NA                             |NA                  |NA                          |NA                                           |3rd Qu.:3                |NA               |3rd Qu.: 9.529                                   |NA                |3rd Qu.:1.000 |3rd Qu.:1.000 |3rd Qu.:1.0000 |3rd Qu.:1.0000 |3rd Qu.:1.0000 |NA               |NA                |\n|   |NA               |Max.   :14.000 |NA                     |NA                    |NA               |NA               |Max.   :5.610          |NA                 |NA               |NA               |Max.   :51.00 |Max.   :64.00 |NA               |NA                    |NA               |NA                             |NA                    |Max.   :0    |Max.   :0    |Max.   :0    |Max.   :1    |Max.   :0    |NA               |NA               |NA               |NA               |NA                                         |NA               |NA                                     |NA                           |NA                             |NA                  |NA                          |NA                                           |Max.   :4                |NA               |Max.   :12.000                                   |NA                |Max.   :1.000 |Max.   :1.000 |Max.   :1.0000 |Max.   :1.0000 |Max.   :1.0000 |NA               |NA                |\n|   |NA               |NA's   :2440   |NA                     |NA                    |NA               |NA               |NA's   :1072           |NA                 |NA               |NA               |NA's   :6790  |NA's   :6761  |NA               |NA                    |NA               |NA                             |NA                    |NA's   :3091 |NA's   :3125 |NA's   :3113 |NA's   :3121 |NA's   :3144 |NA               |NA               |NA               |NA               |NA                                         |NA               |NA                                     |NA                           |NA                             |NA                  |NA                          |NA                                           |NA's   :3126             |NA               |NA's   :3118                                     |NA                |NA's   :3128  |NA's   :3184  |NA's   :3075   |NA's   :3096   |NA's   :3127   |NA               |NA                |\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Displaying number of NAs in key variables Genetic Disorder and Disorder Subclass\n\nsum(is.na(data$`Genetic Disorder`))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 3121\n```\n:::\n\n```{.r .cell-code}\nsum(is.na(data$`Disorder Subclass`))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 3140\n```\n:::\n:::\n\n\nNumber of NA values in Genetic Disorder and Disorder Subclass are 3121 and 3140 respectively. We remove these at the start of our Data Pre-processing section since we don't want to have missing values in our important features.\n\n## Part 5. Data Pre-processing and Analysis Plan\n\nSpecific questions : \n\n1. How are features causing the genetic disorder related with one another?\n\n2. How much variability is present in the important factors affecting the type of disease?\n\n3. What is the distibution of categories within each feature influencing the disease?\n\n4. What are the most common types of Genetic disorders children suffer from?\n\n5. What are the most important parts of the medical information of a patient that helps in early diagnosis of the genetic disorder?\n\nPre-processing Plan:\n\n  - Dropping null values from our main disease columns, Genetic Disorder and Disorder Subclass\n\n  - Dropping features that are not important and do not affect our key disease columns\n  \n  - Analyzing unique values present in each feature to replace noisy values and null values with suitable values\n\nAnalysis Plan :\n\n  - To answer the research questions mentioned above, I plan to conduct a combination of data analysis and visualization techniques.\n\n  - Bar Charts and Histograms: I will create bar charts and histograms to visualize the relationship between categorical and numerical variables (e.g., Respiratory Rate, Heart Rate, Follow-up, Folic acid details), and their frequencies. This will allow for a quick study of distribution of sub categories of different features.\n\n  - Scatter Plot: Scatter plots are valuable for analyzing the relationship between numerical variables, such as Patient Age, Blood cell count and White Blood cell count. They enable us to observe the dispersion of data points and determine if there is any correlation or trend between the variables.\n\n  - Bivariate Visualization: Bivariate visualizations such as bar charts or stacked bar plots, are useful for comparing two variables. They allow us to visually examine the relationship between two categorical variables and allow us to derive insights about the inter-dependency of these features.\n\n## Part 6. Data Pre-processing and Visualization\n\nPre-processing plan: Task 1 and 2\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Dropping patients with missing values in 'Genetic Disorder' and 'Disorder Subclass' columns\ndata <- data[!is.na(data$`Genetic Disorder`) & !is.na(data$`Disorder Subclass`), ]\n```\n:::\n\n\nMy goal is to study the correlation of other features with these two disorder columns and NA values in these target variables would make that particular patient record useless. Hence I am removing rows which have null values in these target columns.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Dropping specific columns from the dataset\ndata <- select(data, -c(`Patient Id`, `Family Name`, `Institute Name`, `Patient First Name`, `Father's name`, `Place of birth`, `Location of Institute`))\n```\n:::\n\n\nDropping features that do not affect the type of genetic disorder or subclass in any way and hence analyzing them isn't of any use.\n\nPre-processing plan: Task 3 and Specific Questions 1, 2 and 3\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Checking unique values in 'Test 1', 'Test 2', 'Test 3', 'Test 4', and 'Test 5' columns\nunique(data$`Test 1`)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1]  0 NA\n```\n:::\n\n```{.r .cell-code}\nunique(data$`Test 2`)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] NA  0\n```\n:::\n\n```{.r .cell-code}\nunique(data$`Test 3`)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] NA  0\n```\n:::\n\n```{.r .cell-code}\nunique(data$`Test 4`)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1]  1 NA\n```\n:::\n\n```{.r .cell-code}\nunique(data$`Test 5`)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1]  0 NA\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filling NA values with -99.0 in 'Test 1', 'Test 2', 'Test 3', 'Test 4', and 'Test 5' columns\ndata$`Test 1` <- ifelse(is.na(data$`Test 1`), -99.0, data$`Test 1`)\ndata$`Test 2` <- ifelse(is.na(data$`Test 2`), -99.0, data$`Test 2`)\ndata$`Test 3` <- ifelse(is.na(data$`Test 3`), -99.0, data$`Test 3`)\ndata$`Test 4` <- ifelse(is.na(data$`Test 4`), -99.0, data$`Test 4`)\ndata$`Test 5` <- ifelse(is.na(data$`Test 5`), -99.0, data$`Test 5`)\n```\n:::\n\n\nChecking the unique values in the test results columns and replacing the missing values with an arbitrary negative value to identify them during future analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Creating density plots for `Patient Age`\n\nggplot(data, aes(x = `Patient Age`, fill = \"Patient age\")) +\n  geom_density(alpha = 0.5, color = \"red\") +\n  labs(x = \"Value\", y = \"Density\") +\n  ggtitle(\"Distribution of Patient Age\") +\n  scale_fill_manual(values = \"red\", labels = \"Patient age\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](FnuAvineshKrishnan_final_project_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Creating density plots for `Blood cell count (mcL)` \n\nggplot(data, aes(x = `Blood cell count (mcL)`, fill = \"Blood cell count (mcL)\")) +\n  geom_density(alpha = 0.5, color = \"blue\") +\n  labs(x = \"Value\", y = \"Density\") +\n  ggtitle(\"Distribution of Blood cell count (mcL)\") +\n  scale_fill_manual(values = \"blue\", labels = \"Blood cell count (mcL)\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](FnuAvineshKrishnan_final_project_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Creating density plots for `White Blood cell count (thousand per microliter)` \n\nggplot(data, aes(x = `White Blood cell count (thousand per microliter)`, fill = \"White Blood cell count (thousand per microliter)\")) +\n  geom_density(alpha = 0.5, color = \"black\") +\n  labs(x = \"Value\", y = \"Density\") +\n  ggtitle(\"Distribution of White Blood cell count (thousand per microliter)\") +\n  scale_fill_manual(values = \"black\", labels = \"White Blood cell count (thousand per microliter)\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](FnuAvineshKrishnan_final_project_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\nI can see that Patient age is uniformly distributed from 0-14 verifying the summary statistic that our dataset includes children in that particular age range only. Blood cell count has a normal distribution around 4.9mcL showing that most children have their blood cell count between 4mcL and 5.5mcL with majority of the children having the mean blood cell count of about 4.9mcL. I also observed that the White blood cell count is somewhat uniformly distributed between 3 and 12 thousand per microliter telling us all children have varying White blood cell count which reflects in their varying strength of immune system.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Creating scatter plot of `Blood cell count (mcL)` against `White Blood cell count (thousand per #microliter)`\nggplot(data, aes(x = `White Blood cell count (thousand per microliter)`, y = `Blood cell count (mcL)`)) +\n  geom_point() +\n  labs(x = \"White Blood cell count (thousand per microliter)\", y = \"Blood cell count (mcL)\") +\n  ggtitle(\"White Blood cell count vs. Blood cell count\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](FnuAvineshKrishnan_final_project_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\nFrom the scatter plot, it looks like there are lot of outliers for the white blood cells. I can see that the blood cell count and white blood cell count do not have a strong positive or negative correlation, therefore the symptoms of in the blood sample are probably not caused by the white blood cells(leukocytes).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create scatter plot of `Blood cell count (mcL)` against `Patient Age`\nggplot(data, aes(x = `Patient Age`, y = `Blood cell count (mcL)`)) +\n  geom_point() +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"red\") +\n  labs(x = \"Patient Age\", y = \"Blood cell count (mcL)\") +\n  ggtitle(\"Patient Age vs. Blood cell count\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](FnuAvineshKrishnan_final_project_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create scatter plot of `White Blood cell count (thousand per microliter)` against `Patient Age`\nggplot(data, aes(x = `Patient Age`, y = `Blood cell count (mcL)`)) +\n  geom_point() +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"red\") +\n  labs(x = \"Patient Age\", y = \"Blood cell count (mcL)\") +\n  ggtitle(\"Patient Age vs. Blood cell count\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](FnuAvineshKrishnan_final_project_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\nFrom the scatter plots, I can see that the patients are uniformly distributed over the range of blood cell counts and white blood cell counts giving us the idea that there is very little to no correlation between the Cell count and Age of the patient.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculating mean values of `White Blood cell count (thousand per microliter)`,`Blood cell count #(mcL)`  and `Patient Age`\nmean_wbc <- mean(data$`White Blood cell count (thousand per microliter)`, na.rm = TRUE)\nmean_bc <- mean(data$`Blood cell count (mcL)`, na.rm = TRUE)\nmean_age <- floor(mean(data$`Patient Age`, na.rm = TRUE))\n\n# Filling NA values with calculated mean values\ndata$`White Blood cell count (thousand per microliter)` <- ifelse(is.na(data$`White Blood cell count (thousand per microliter)`), mean_wbc, data$`White Blood cell count (thousand per microliter)`)\ndata$`Blood cell count (mcL)` <- ifelse(is.na(data$`Blood cell count (mcL)`), mean_bc, data$`Blood cell count (mcL)`)\ndata$`Patient Age` <- ifelse(is.na(data$`Patient Age`), mean_age, data$`Patient Age`)\n```\n:::\n\n\nAs the cell count and age are important features, I am replacing the missing cell counts with the mean value and the missing age with floor of the mean value since age needs to be a round number.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Creating scatter plot of `Mother's age` against `Father's age`\nggplot(data, aes(x = `Father's age`, y = `Mother's age`)) +\n  geom_point() +\n  labs(x = \"Father's age\", y = \"Mother's age\") +\n  ggtitle(\"Father's age vs. Mother's age\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](FnuAvineshKrishnan_final_project_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\nI wanted to see if there is any correlation between the parents age which is clearly not the case from the views of the scatter plot.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Creating density plot with fitted normal distribution for Mother's age\nggplot(data, aes(x = `Mother's age`)) +\n  geom_density(fill = \"blue\", color = \"black\") +\n  stat_function(fun = dnorm, args = list(mean = mean(data$`Mother's age`, na.rm = TRUE), sd = sd(data$`Mother's age`, na.rm = TRUE)), color = \"red\", size = 1.5) +\n  labs(x = \"Mother's age\", y = \"Density\") +\n  ggtitle(\"Distribution of Mother's age\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](FnuAvineshKrishnan_final_project_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Creating density plot with fitted normal distribution for Father's age\nggplot(data, aes(x = `Father's age`)) +\n  geom_density(fill = \"blue\", color = \"black\") +\n  stat_function(fun = dnorm, args = list(mean = mean(data$`Father's age`, na.rm = TRUE), sd = sd(data$`Father's age`, na.rm = TRUE)), color = \"red\", size = 1.5) +\n  labs(x = \"Father's age\", y = \"Density\") +\n  ggtitle(\"Distribution of Father's age\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](FnuAvineshKrishnan_final_project_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\nBoth the parents age follows a normal distribution  being symmetric about their mean value. This shows that majority of fathers are about 43 years old and majority of the mothers are about 35 years old.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculating mean values\nmean_mother_age <- floor(mean(data$`Mother's age`, na.rm = TRUE))\nmean_father_age <- floor(mean(data$`Father's age`, na.rm = TRUE))\n\n# Filling NA values with calculated mean values\ndata$`Mother's age` <- ifelse(is.na(data$`Mother's age`), mean_mother_age, data$`Mother's age`)\ndata$`Father's age` <- ifelse(is.na(data$`Father's age`), mean_father_age, data$`Father's age`)\n```\n:::\n\n\nI am replacing the missing values in Father's and Mother's age with the  floor of the mean value since age needs to be a round number.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Creating density plot of `No. of previous abortion`\nggplot(data, aes(x = `No. of previous abortion`, y = ..density..)) +\n  geom_density(fill = \"blue\", color = \"black\") +\n  labs(x = \"No. of previous abortion\", y = \"Density\") +\n  ggtitle(\"Distribution of No. of previous abortion\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](FnuAvineshKrishnan_final_project_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Checking unique values in `No. of previous abortion`\nunique(data$`No. of previous abortion`)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] NA  4  1  0  3  2\n```\n:::\n:::\n\n\nI wanted to learn about the `No. of previous abortion` variable and from its density distribution, it is surprising to see that there are many children who have had 1,2,3 and even 4 abortions already. I want to check their Mothers age to get more insights.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Creating scatter plot of `Mother's age` against `No. of previous abortion`\nggplot(data, aes(x = `No. of previous abortion`, y = `Mother's age`)) +\n  geom_point() +\n  labs(x = \"No. of previous abortion\", y = \"Mother's age\") +\n  ggtitle(\"Mother's age vs. No. of previous abortion\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](FnuAvineshKrishnan_final_project_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\nWow, there are cases where patients with just 18 year old mothers have had 4 abortions. I want to look into the Father's age of these patients.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filtering data for Mother's age equal to 18\nfiltered_data <- subset(data, `Mother's age` == 18)\n\n# Creating count Bar graph of Father's age for these records\nggplot(filtered_data, aes(x = `Father's age`)) +\n  geom_bar() +\n  labs(x = \"Father's age\", y = \"Count\") +\n  ggtitle(\"Father's age for 18 year old mother\") +\n  theme_minimal() +\n  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](FnuAvineshKrishnan_final_project_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\nI can see that majority of fathers of these patients who have a 18 year old mother and have had a few abortions are about 41 years old.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculating mean value of `No. of previous abortion`\nmean_previous_abortion <- floor(mean(data$`No. of previous abortion`, na.rm = TRUE))\n\n# Filling NA values with calculated mean value\ndata$`No. of previous abortion` <- ifelse(is.na(data$`No. of previous abortion`), mean_previous_abortion, data$`No. of previous abortion`)\n```\n:::\n\n\nI am replacing the missing values in No. of previous abortion with the  floor of the mean value since the variable needs to be a round number.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filling NA values of Symptoms columns with 0.0\ndata$`Symptom 1` <- ifelse(is.na(data$`Symptom 1`), 0.0, data$`Symptom 1`)\ndata$`Symptom 2` <- ifelse(is.na(data$`Symptom 2`), 0.0, data$`Symptom 2`)\ndata$`Symptom 3` <- ifelse(is.na(data$`Symptom 3`), 0.0, data$`Symptom 3`)\ndata$`Symptom 4` <- ifelse(is.na(data$`Symptom 4`), 0.0, data$`Symptom 4`)\ndata$`Symptom 5` <- ifelse(is.na(data$`Symptom 5`), 0.0, data$`Symptom 5`)\n```\n:::\n\n\nI am replacing the missing values in the Symptoms columns with 0 since 0 represents no symptoms and 1 represents that symptoms are present and when the symptoms aren't mentioned, it is safe to assume that they have no symptoms. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Creating count Bar graphs for Categorical features\nggplot(data) +\n  geom_bar(aes(x = `Maternal gene`), fill = \"blue\") +\n  labs(title = \"Count Plot: Maternal gene\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](FnuAvineshKrishnan_final_project_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data) +\n  geom_bar(aes(x = `Respiratory Rate (breaths/min)`), fill = \"red\") +\n  labs(title = \"Count Plot: Respiratory Rate (breaths/min)\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](FnuAvineshKrishnan_final_project_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data) +\n  geom_bar(aes(x = `Heart Rate (rates/min`), fill = \"green\") +\n  labs(title = \"Count Plot: Heart Rate (rates/min)\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](FnuAvineshKrishnan_final_project_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data) +\n  geom_bar(aes(x = `Parental consent`), fill = \"orange\") +\n  labs(title = \"Count Plot: Parental consent\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](FnuAvineshKrishnan_final_project_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data) +\n  geom_bar(aes(x = `Follow-up`), fill = \"purple\") +\n  labs(title = \"Count Plot: Follow-up\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](FnuAvineshKrishnan_final_project_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data) +\n  geom_bar(aes(x = `Folic acid details (peri-conceptional)`), fill = \"pink\") +\n  labs(title = \"Count Plot: Folic acid details (peri-conceptional)\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](FnuAvineshKrishnan_final_project_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data) +\n  geom_bar(aes(x = `H/O radiation exposure (x-ray)`), fill = \"brown\") +\n  labs(title = \"Count Plot: H/O radiation exposure (x-ray)\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](FnuAvineshKrishnan_final_project_files/figure-html/unnamed-chunk-33-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data) +\n  geom_bar(aes(x = `H/O substance abuse`), fill = \"gray\") +\n  labs(title = \"Count Plot: H/O substance abuse\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](FnuAvineshKrishnan_final_project_files/figure-html/unnamed-chunk-34-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data) +\n  geom_bar(aes(x = `Assisted conception IVF/ART`), fill = \"cyan\") +\n  labs(title = \"Count Plot: Assisted conception IVF/ART\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](FnuAvineshKrishnan_final_project_files/figure-html/unnamed-chunk-35-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data) +\n  geom_bar(aes(x = `History of anomalies in previous pregnancies`), fill = \"yellow\") +\n  labs(title = \"Count Plot: History of anomalies in previous pregnancies\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](FnuAvineshKrishnan_final_project_files/figure-html/unnamed-chunk-36-1.png){width=672}\n:::\n:::\n\n\nFrom the Bar graphs of the counts of these categorical features, I can see which sub category of each variable accounts for the majority percentage. Since there are lot of parental consent, I will assume that tests conducted due to parents consent and there's no way a kid will check up on his own. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Dropping Parental consent column\ndata <- select(data, -c(`Parental consent`))\n```\n:::\n\n\nDropping the parental consent since most of them require it and the feature does not have influence on the type of genetic disorder.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Checking unique values in columns\nunique(data$`Maternal gene`)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Yes\" \"No\"  NA   \n```\n:::\n\n```{.r .cell-code}\nunique(data$`Respiratory Rate (breaths/min)`)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Normal (30-60)\" \"Tachypnea\"      NA              \n```\n:::\n\n```{.r .cell-code}\nunique(data$`Heart Rate (rates/min`)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Normal\"      \"Tachycardia\" NA           \n```\n:::\n\n```{.r .cell-code}\nunique(data$`Follow-up`)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"High\" \"Low\"  NA    \n```\n:::\n\n```{.r .cell-code}\nunique(data$`Folic acid details (peri-conceptional)`)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"No\"  \"Yes\" NA   \n```\n:::\n\n```{.r .cell-code}\nunique(data$`H/O radiation exposure (x-ray)`)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"No\"             \"Yes\"            \"-\"              \"Not applicable\"\n[5] NA              \n```\n:::\n\n```{.r .cell-code}\nunique(data$`H/O substance abuse`)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"No\"             NA               \"Not applicable\" \"-\"             \n[5] \"Yes\"           \n```\n:::\n\n```{.r .cell-code}\nunique(data$`Assisted conception IVF/ART`)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"No\"  \"Yes\" NA   \n```\n:::\n\n```{.r .cell-code}\nunique(data$`History of anomalies in previous pregnancies`)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Yes\" \"No\"  NA   \n```\n:::\n\n```{.r .cell-code}\nunique(data$`Birth asphyxia`)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] NA              \"No record\"     \"Not available\" \"Yes\"          \n[5] \"No\"           \n```\n:::\n\n```{.r .cell-code}\nunique(data$`Gender`)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] NA          \"Male\"      \"Female\"    \"Ambiguous\"\n```\n:::\n\n```{.r .cell-code}\nunique(data$`Birth defects`)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] NA         \"Singular\" \"Multiple\"\n```\n:::\n\n```{.r .cell-code}\nunique(data$`Blood test result`)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] NA                  \"normal\"            \"inconclusive\"     \n[4] \"slightly abnormal\" \"abnormal\"         \n```\n:::\n\n```{.r .cell-code}\nunique(data$`H/O serious maternal illness`)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] NA    \"No\"  \"Yes\"\n```\n:::\n\n```{.r .cell-code}\nunique(data$`Inherited from father`)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"No\"  \"Yes\" NA   \n```\n:::\n\n```{.r .cell-code}\nunique(data$`Autopsy shows birth defect (if applicable)`)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Not applicable\" \"No\"             \"None\"           \"Yes\"           \n[5] NA              \n```\n:::\n\n```{.r .cell-code}\nunique(data$Status)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Alive\"    \"Deceased\"\n```\n:::\n\n```{.r .cell-code}\nunique(data$`Genes in mother's side`)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Yes\" \"No\" \n```\n:::\n\n```{.r .cell-code}\nunique(data$`Paternal gene`)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"No\"  \"Yes\"\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filling NA with \"No\" in specific columns\ndata$`Maternal gene` <- ifelse(is.na(data$`Maternal gene`), \"No\", data$`Maternal gene`)\ndata$`Folic acid details (peri-conceptional)` <- ifelse(is.na(data$`Folic acid details (peri-conceptional)`), \"No\", data$`Folic acid details (peri-conceptional)`)\ndata$`H/O radiation exposure (x-ray)` <- ifelse(is.na(data$`H/O radiation exposure (x-ray)`), \"No\", data$`H/O radiation exposure (x-ray)`)\ndata$`H/O substance abuse` <- ifelse(is.na(data$`H/O substance abuse`), \"No\", data$`H/O substance abuse`)\ndata$`Assisted conception IVF/ART` <- ifelse(is.na(data$`Assisted conception IVF/ART`), \"No\", data$`Assisted conception IVF/ART`)\ndata$`History of anomalies in previous pregnancies` <- ifelse(is.na(data$`History of anomalies in previous pregnancies`), \"No\", data$`History of anomalies in previous pregnancies`)\ndata$`Birth asphyxia` <- ifelse(is.na(data$`Birth asphyxia`), \"No\", data$`Birth asphyxia`)\ndata$`H/O serious maternal illness` <- ifelse(is.na(data$`H/O serious maternal illness`), \"No\", data$`H/O serious maternal illness`)\ndata$`Inherited from father` <- ifelse(is.na(data$`Inherited from father`), \"No\", data$`Inherited from father`)\ndata$`Autopsy shows birth defect (if applicable)` <- ifelse(is.na(data$`Autopsy shows birth defect (if applicable)`), \"No\", data$`Autopsy shows birth defect (if applicable)`)\ndata$`Genes in mother's side` <- ifelse(is.na(data$`Genes in mother's side`), \"No\", data$`Genes in mother's side`)\ndata$`Paternal gene` <- ifelse(is.na(data$`Paternal gene`), \"No\", data$`Paternal gene`)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Function to calculate mode\nMode <- function(x) {\n  ux <- unique(x)\n  ux[which.max(tabulate(match(x, ux)))]\n}\n\n# Filling NA with the most frequent value in specific columns\ndata$`Respiratory Rate (breaths/min)` <- ifelse(is.na(data$`Respiratory Rate (breaths/min)`), Mode(data$`Respiratory Rate (breaths/min)`), data$`Respiratory Rate (breaths/min)`)\ndata$`Heart Rate (rates/min` <- ifelse(is.na(data$`Heart Rate (rates/min`), Mode(data$`Heart Rate (rates/min`), data$`Heart Rate (rates/min`)\ndata$`Follow-up` <- ifelse(is.na(data$`Follow-up`), Mode(data$`Follow-up`), data$`Follow-up`)\ndata$Gender <- ifelse(is.na(data$Gender), Mode(data$Gender), data$Gender)\ndata$`Birth defects` <- ifelse(is.na(data$`Birth defects`), Mode(data$`Birth defects`), data$`Birth defects`)\ndata$`Blood test result` <- ifelse(is.na(data$`Blood test result`), Mode(data$`Blood test result`), data$`Blood test result`)\ndata$Status <- ifelse(is.na(data$Status), Mode(data$Status), data$Status)\n```\n:::\n\n\nI checked the values in these columns and replaced the missing values in the categorical features with \"No\" since that would be most apt if the illness wasn't mentioned and with value of the most frequent value(mode) in the numerical features since these variables have a partial but not so strong impact on the genetic disorder. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Replacing -99 with 0 in 'Test 1', 'Test 2', 'Test 3', 'Test 4', 'Test 5'\ndata$`Test 1`[data$`Test 1` == -99] <- 0\ndata$`Test 2`[data$`Test 2` == -99] <- 0\ndata$`Test 3`[data$`Test 3` == -99] <- 0\ndata$`Test 4`[data$`Test 4` == -99] <- 0\ndata$`Test 5`[data$`Test 5` == -99] <- 0\n\n# Replacing -99 in 'White Blood cell count (thousand per microliter)' with median\ndata$`White Blood cell count (thousand per microliter)`[data$`White Blood cell count (thousand per microliter)` == -99] <- median(data$`White Blood cell count (thousand per microliter)`, na.rm = TRUE)\n\n# Replacing '-99' with mode in 'Respiratory Rate (breaths/min)', 'Heart Rate (rates/min)'\ndata$`Respiratory Rate (breaths/min)`[data$`Respiratory Rate (breaths/min)` == '-99'] <- Mode(data$`Respiratory Rate (breaths/min)`)\ndata$`Heart Rate (rates/min`[data$`Heart Rate (rates/min` == '-99'] <- Mode(data$`Heart Rate (rates/min`)\n\n# Replacing 'Normal (30-60)' with 'Normal' in 'Respiratory Rate (breaths/min)'\ndata$`Respiratory Rate (breaths/min)`[data$`Respiratory Rate (breaths/min)` == 'Normal (30-60)'] <- 'Normal'\n\n# Replacing 'No record' with 'Not available' in 'Birth asphyxia'\ndata$`Birth asphyxia`[data$`Birth asphyxia` == 'No record'] <- 'Not available'\n\n# Replacing 'None' and '-' with 'No' in 'Autopsy shows birth defect (if applicable)', 'H/O radiation exposure (x-ray)', 'H/O substance abuse'\ndata$`Autopsy shows birth defect (if applicable)`[data$`Autopsy shows birth defect (if applicable)` == 'None' | data$`Autopsy shows birth defect (if applicable)` == '-'] <- 'No'\ndata$`H/O radiation exposure (x-ray)`[data$`H/O radiation exposure (x-ray)` == 'None' | data$`H/O radiation exposure (x-ray)` == '-'] <- 'No'\ndata$`H/O substance abuse`[data$`H/O substance abuse` == 'None' | data$`H/O substance abuse` == '-'] <- 'No'\n```\n:::\n\n\nI replaced arbitrary negative value(-99) in Test results feature with 0 since it implies that missing value equals a negative test which is the most appropriate to assume. I replaced the arbitrary value in White Blood cell count, Respiratory and heart rate with median and mode respectively as taking the central tendency value would make the most sense as these features are key for determining the type of genetic disorder. I replaced 'Normal (30-60)' with 'Normal', 'No record' with 'Not available', 'None' and '-' with 'No' in Respiratory Rate, Birth asphyxia, Autopsy shows birth defect, H/O radiation exposure and H/O substance abuse respectively to maintain uniformity within the sub categories. \n\nSpecific Question 4\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Creating the count plot for `Disorder Subclass`\nggplot(data, aes(x = `Disorder Subclass`)) +\n  geom_bar(fill = \"steelblue\") +\n  labs(title = \"Disorder Subclass\", x = \"Disorder Subclass\", y = \"Count\") +\n  theme(axis.text.x = element_text(angle = 90, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](FnuAvineshKrishnan_final_project_files/figure-html/unnamed-chunk-42-1.png){width=672}\n:::\n:::\n\n\nFrom the Count plot for the subclasses of genetic disorder, I can say that most of the patients suffer from Leigh Syndrome while the least amount of children have Cancer.\n\nSpecific Question 5\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Creating the correlation graph between Maternal gene and Genetic Disorder\nggplot(data, aes(x = `Maternal gene`, fill = `Genetic Disorder`)) +\n  geom_bar() +\n  labs(x = \"Maternal gene\", y = \"Count\", fill = \"Genetic Disorder\") +\n  ggtitle(\"Maternal gene vs. Genetic Disorder\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](FnuAvineshKrishnan_final_project_files/figure-html/unnamed-chunk-43-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Creating the correlation graph between Paternal gene and Genetic Disorder\nggplot(data, aes(x = `Paternal gene`, fill = `Genetic Disorder`)) +\n  geom_bar() +\n  labs(x = \"Paternal gene\", y = \"Count\", fill = \"Genetic Disorder\") +\n  ggtitle(\"Paternal gene vs. Genetic Disorder\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](FnuAvineshKrishnan_final_project_files/figure-html/unnamed-chunk-44-1.png){width=672}\n:::\n:::\n\n\nI observe that the maternal gene equally affects patients and is does not determine the type of genetic disorder whereas the absence of the paternal gene is seen in more cases of genetic abnormalities as compared to the patients containing the paternal gene.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Creating the correlation graph between Respiratory Rate (breaths/min) and Genetic Disorder\nggplot(data, aes(x = `Respiratory Rate (breaths/min)`, fill = `Genetic Disorder`)) +\n  geom_bar() +\n  labs(x = \"Respiratory Rate (breaths/min)\", y = \"Count\", fill = \"Genetic Disorder\") +\n  ggtitle(\"Respiratory Rate (breaths/min) vs. Genetic Disorder\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](FnuAvineshKrishnan_final_project_files/figure-html/unnamed-chunk-45-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Creating the correlation graph between Heart Rate (rates/min and Genetic Disorder\nggplot(data, aes(x = `Heart Rate (rates/min`, fill = `Genetic Disorder`)) +\n  geom_bar() +\n  labs(x = \"Heart Rate (rates/min\", y = \"Count\", fill = \"Genetic Disorder\") +\n  ggtitle(\"Heart Rate (rates/min) vs. Genetic Disorder\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](FnuAvineshKrishnan_final_project_files/figure-html/unnamed-chunk-46-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Creating the correlation graph between Birth asphyxia and Genetic Disorder\nggplot(data, aes(x = `Birth asphyxia`, fill = `Genetic Disorder`)) +\n  geom_bar() +\n  labs(x = \"Birth asphyxia\", y = \"Count\", fill = \"Genetic Disorder\") +\n  ggtitle(\"Birth asphyxia vs. Genetic Disorder\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](FnuAvineshKrishnan_final_project_files/figure-html/unnamed-chunk-47-1.png){width=672}\n:::\n:::\n\n\nI see that patients with a normal Respiratory breathing rate are in larger proportion when it comes to having a genetic disorder and hence I think that Respiratory rate may not be a primary factor for determining presence of a genetic disease. In the same manner, Heart rate and Birth asphyxia can also be taken out of consideration for early prognosis of a genetic disorder.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Creating the correlation graph between H/O radiation exposure (x-ray) and Genetic Disorder\nggplot(data, aes(x = `H/O radiation exposure (x-ray)`, fill = `Genetic Disorder`)) +\n  geom_bar() +\n  labs(x = \"H/O radiation exposure (x-ray)\", y = \"Count\", fill = \"Genetic Disorder\") +\n  ggtitle(\"H/O radiation exposure (x-ray) vs. Genetic Disorder\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](FnuAvineshKrishnan_final_project_files/figure-html/unnamed-chunk-48-1.png){width=672}\n:::\n:::\n\n\nI observe that people with no radiation exposure also suffer from a lot of genetic disorders compared to people exposed to x-rays, and this condition may also not be a part of predicting the presence of a genetic disease in the patient.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Creating the correlation graph between No. of previous abortion and Genetic Disorder\nggplot(data, aes(x = `No. of previous abortion`, fill = `Genetic Disorder`)) +\n  geom_bar() +\n  labs(x = \"No. of previous abortion\", y = \"Count\", fill = \"Genetic Disorder\") +\n  ggtitle(\"No. of previous abortion vs. Genetic Disorder\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](FnuAvineshKrishnan_final_project_files/figure-html/unnamed-chunk-49-1.png){width=672}\n:::\n:::\n\n\nFrom the correlation plot, patients with even a single previous abortion tend to have a higher chance of suffering from a genetic disorder, mainly Mitochondrial Inheritance disorders.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Creating the correlation graph between Blood cell count (mcL) and Genetic Disorder\nggplot(data, aes(y = `Blood cell count (mcL)`, x = `Genetic Disorder`)) +\n  geom_point() +\n  labs(y = \"Blood cell count (mcL)\", x = \"Genetic Disorder\") +\n  ggtitle(\"Blood cell count (mcL) vs. Genetic Disorder\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](FnuAvineshKrishnan_final_project_files/figure-html/unnamed-chunk-50-1.png){width=672}\n:::\n:::\n\n\nFrom the graph, I see that patients with blood cell count within the full range suffer from genetic disorders which means that this feature may not be a key influence for causing genetic diseases in children.\n\n## Part 7. Conclusion and Discussion :\n\n  - The analysis of the dataset has provided valuable insights into the relationship between various features and the presence of genetic disorders. The first step was to remove rows with missing values in the target columns, as these records would not contribute to the analysis. Additionally, irrelevant features that did not affect the type of genetic disorder were dropped, streamlining the dataset for further examination. The examination of the test results columns revealed unique values and the replacement of missing values with an arbitrary negative value for future identification. The analysis of patient age, blood cell count, and white blood cell count showcased interesting patterns. Patient age was found to be uniformly distributed within the range of 0 to 14 years, indicating that the dataset primarily consists of children in this age group. Blood cell count exhibited a normal distribution, with the majority of children having counts between 4mcL and 5.5mcL. Similarly, white blood cell count showed a somewhat uniform distribution between 3 and 12 thousand per microliter, reflecting the varying strength of the immune system among children.\n\n  - Scatter plots were employed to explore potential correlations between variables. The scatter plot of blood cell count and white blood cell count indicated no strong positive or negative correlation, suggesting that the symptoms observed in the blood sample may not be caused by variations in white blood cell count. Additionally, scatter plots of blood cell count versus patient age and parental age exhibited no discernible correlation, indicating that these factors may have limited influence on the occurrence of genetic disorders.\n\n  - The examination of parental age distributions revealed normal distributions for both fathers and mothers, with the majority of fathers being around 43 years old and mothers around 35 years old. Missing values in father's and mother's age were replaced with the floor of the mean value to maintain consistency and roundness in the age representation. Exploring the \"No. of previous abortion\" variable provided insights into the frequency of abortions among patients. It was observed that there were cases where patients with 18-year-old mothers had undergone multiple abortions. Furthermore, the examination of father's age in these cases revealed that the majority of fathers were around 41 years old.\n\n  - Count plots were used to analyze categorical features, such as parental consent, and revealed the predominance of specific categories. As a result, the parental consent feature was dropped, as it was determined to have little influence on the type of genetic disorder. Missing values in categorical features were replaced with \"No\" to represent the absence of the mentioned condition. Furthermore, specific values such as \"Normal (30-60)\" were replaced with simplified representations like \"Normal\" for consistency.\n\n  - Count plots of the subclasses of genetic disorders highlighted the distribution of disorders within the dataset. Leigh Syndrome was found to be the most prevalent disorder, while Cancer accounted for the fewest cases. The analysis of the maternal gene revealed that it did not significantly influence the type of genetic disorder, whereas the absence of the paternal gene was more prevalent in cases of genetic abnormalities.\n\n  - The examination of features such as respiratory rate, heart rate, radiation exposure, and birth asphyxia indicated that these factors may not be primary indicators of genetic disorders. Similarly, the correlation plot showed that patients with previous abortions tended to have a higher likelihood of suffering from genetic disorders, particularly those related to mitochondrial inheritance. Lastly, the scatter plot of blood cell count versus genetic disorders suggested that blood cell count may not be a key determining factor in the presence of genetic diseases.\n\n  - In conclusion, the analysis of the dataset provided valuable insights into the relationship between various features and the occurrence of genetic disorders. The examination of unique values, data distributions, scatter plots, and count plots enabled a deeper understanding of the dataset and facilitated the identification of influential factors. These findings contribute to the field of genetic disorder research and can potentially aid in early prognosis and understanding the underlying mechanisms of these disorders\n\n## Part 8. Bibliography :\n\nDataset : https://www.kaggle.com/datasets/aibuzz/predict-the-genetic-disorders-datasetof-genomes\n\n\nProgramming Language : R\n",
    "supporting": [
      "FnuAvineshKrishnan_final_project_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}