{
  "hash": "254383b850100eba90c9e6c9b8816a31",
  "result": {
    "markdown": "---\ntitle: \"Challenge 8 Submission\"\nauthor: \"Cam Needels\"\ndescription: \"Joining Data\"\ndate: \"05/01/2023\"\nformat:\n  html:\n    toc: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_8\n  - military\n  - CamNeedels\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(ggplot2)\nlibrary(readxl)\nlibrary(readr)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n\n\n### Briefly describe the data\n\nAll these data sets are the amount of a certain item that are produced from livestock, dairy cattle, and eggs.\n\n## Tidy Data (as needed)\n\nData is already tidy, all I needed to do is join it together. It makes it easy that they all have the same variables so merging them was pretty simple!\n\n::: {.cell}\n\n```{.r .cell-code}\n#assigning the eggs data set to an object\nEggs <- read_csv((\"B:/Needels/Documents/DACCS 601/DACSS_601_New/posts/_data/FAOSTAT_egg_chicken.csv\"))\ndim(Eggs)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 38170    14\n```\n:::\n\n```{.r .cell-code}\nEggs\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 38,170 × 14\n   Domain Cod…¹ Domain Area …² Area  Eleme…³ Element Item …⁴ Item  Year …⁵  Year\n   <chr>        <chr>    <dbl> <chr>   <dbl> <chr>     <dbl> <chr>   <dbl> <dbl>\n 1 QL           Lives…       2 Afgh…    5313 Laying     1062 Eggs…    1961  1961\n 2 QL           Lives…       2 Afgh…    5410 Yield      1062 Eggs…    1961  1961\n 3 QL           Lives…       2 Afgh…    5510 Produc…    1062 Eggs…    1961  1961\n 4 QL           Lives…       2 Afgh…    5313 Laying     1062 Eggs…    1962  1962\n 5 QL           Lives…       2 Afgh…    5410 Yield      1062 Eggs…    1962  1962\n 6 QL           Lives…       2 Afgh…    5510 Produc…    1062 Eggs…    1962  1962\n 7 QL           Lives…       2 Afgh…    5313 Laying     1062 Eggs…    1963  1963\n 8 QL           Lives…       2 Afgh…    5410 Yield      1062 Eggs…    1963  1963\n 9 QL           Lives…       2 Afgh…    5510 Produc…    1062 Eggs…    1963  1963\n10 QL           Lives…       2 Afgh…    5313 Laying     1062 Eggs…    1964  1964\n# … with 38,160 more rows, 4 more variables: Unit <chr>, Value <dbl>,\n#   Flag <chr>, `Flag Description` <chr>, and abbreviated variable names\n#   ¹​`Domain Code`, ²​`Area Code`, ³​`Element Code`, ⁴​`Item Code`, ⁵​`Year Code`\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#assigning the livestock data set to an object\nlivestock<- read_csv(\"B:/Needels/Documents/DACCS 601/DACSS_601_New/posts/_data/FAOSTAT_livestock.csv\")\n#the dimensions of livestock\ndim(livestock)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 82116    14\n```\n:::\n\n```{.r .cell-code}\nlivestock\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 82,116 × 14\n   Domain Cod…¹ Domain Area …² Area  Eleme…³ Element Item …⁴ Item  Year …⁵  Year\n   <chr>        <chr>    <dbl> <chr>   <dbl> <chr>     <dbl> <chr>   <dbl> <dbl>\n 1 QA           Live …       2 Afgh…    5111 Stocks     1107 Asses    1961  1961\n 2 QA           Live …       2 Afgh…    5111 Stocks     1107 Asses    1962  1962\n 3 QA           Live …       2 Afgh…    5111 Stocks     1107 Asses    1963  1963\n 4 QA           Live …       2 Afgh…    5111 Stocks     1107 Asses    1964  1964\n 5 QA           Live …       2 Afgh…    5111 Stocks     1107 Asses    1965  1965\n 6 QA           Live …       2 Afgh…    5111 Stocks     1107 Asses    1966  1966\n 7 QA           Live …       2 Afgh…    5111 Stocks     1107 Asses    1967  1967\n 8 QA           Live …       2 Afgh…    5111 Stocks     1107 Asses    1968  1968\n 9 QA           Live …       2 Afgh…    5111 Stocks     1107 Asses    1969  1969\n10 QA           Live …       2 Afgh…    5111 Stocks     1107 Asses    1970  1970\n# … with 82,106 more rows, 4 more variables: Unit <chr>, Value <dbl>,\n#   Flag <chr>, `Flag Description` <chr>, and abbreviated variable names\n#   ¹​`Domain Code`, ²​`Area Code`, ³​`Element Code`, ⁴​`Item Code`, ⁵​`Year Code`\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#assinging the dairy cattle dataset to an object\ndairy<- read_csv(\"B:/Needels/Documents/DACCS 601/DACSS_601_New/posts/_data/FAOSTAT_cattle_dairy.csv\")\n#the dimensions for dairy\ndim(dairy)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 36449    14\n```\n:::\n\n```{.r .cell-code}\ndairy\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 36,449 × 14\n   Domain Cod…¹ Domain Area …² Area  Eleme…³ Element Item …⁴ Item  Year …⁵  Year\n   <chr>        <chr>    <dbl> <chr>   <dbl> <chr>     <dbl> <chr>   <dbl> <dbl>\n 1 QL           Lives…       2 Afgh…    5318 Milk A…     882 Milk…    1961  1961\n 2 QL           Lives…       2 Afgh…    5420 Yield       882 Milk…    1961  1961\n 3 QL           Lives…       2 Afgh…    5510 Produc…     882 Milk…    1961  1961\n 4 QL           Lives…       2 Afgh…    5318 Milk A…     882 Milk…    1962  1962\n 5 QL           Lives…       2 Afgh…    5420 Yield       882 Milk…    1962  1962\n 6 QL           Lives…       2 Afgh…    5510 Produc…     882 Milk…    1962  1962\n 7 QL           Lives…       2 Afgh…    5318 Milk A…     882 Milk…    1963  1963\n 8 QL           Lives…       2 Afgh…    5420 Yield       882 Milk…    1963  1963\n 9 QL           Lives…       2 Afgh…    5510 Produc…     882 Milk…    1963  1963\n10 QL           Lives…       2 Afgh…    5318 Milk A…     882 Milk…    1964  1964\n# … with 36,439 more rows, 4 more variables: Unit <chr>, Value <dbl>,\n#   Flag <chr>, `Flag Description` <chr>, and abbreviated variable names\n#   ¹​`Domain Code`, ²​`Area Code`, ³​`Element Code`, ⁴​`Item Code`, ⁵​`Year Code`\n```\n:::\n:::\n\n\n## Join Data\n\nTo double check the dimensions I should expect with math that the sum of the rows in both the dairy cattle and livestock should be 36449 + 82116 = 118565\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#joining the dairy cattle and livestock datasets\ncattlestock <- full_join(dairy,livestock)\n#the dimension of the joining\ndim(cattlestock)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 118565     14\n```\n:::\n\n```{.r .cell-code}\ncattlestock\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 118,565 × 14\n   Domain Cod…¹ Domain Area …² Area  Eleme…³ Element Item …⁴ Item  Year …⁵  Year\n   <chr>        <chr>    <dbl> <chr>   <dbl> <chr>     <dbl> <chr>   <dbl> <dbl>\n 1 QL           Lives…       2 Afgh…    5318 Milk A…     882 Milk…    1961  1961\n 2 QL           Lives…       2 Afgh…    5420 Yield       882 Milk…    1961  1961\n 3 QL           Lives…       2 Afgh…    5510 Produc…     882 Milk…    1961  1961\n 4 QL           Lives…       2 Afgh…    5318 Milk A…     882 Milk…    1962  1962\n 5 QL           Lives…       2 Afgh…    5420 Yield       882 Milk…    1962  1962\n 6 QL           Lives…       2 Afgh…    5510 Produc…     882 Milk…    1962  1962\n 7 QL           Lives…       2 Afgh…    5318 Milk A…     882 Milk…    1963  1963\n 8 QL           Lives…       2 Afgh…    5420 Yield       882 Milk…    1963  1963\n 9 QL           Lives…       2 Afgh…    5510 Produc…     882 Milk…    1963  1963\n10 QL           Lives…       2 Afgh…    5318 Milk A…     882 Milk…    1964  1964\n# … with 118,555 more rows, 4 more variables: Unit <chr>, Value <dbl>,\n#   Flag <chr>, `Flag Description` <chr>, and abbreviated variable names\n#   ¹​`Domain Code`, ²​`Area Code`, ³​`Element Code`, ⁴​`Item Code`, ⁵​`Year Code`\n```\n:::\n:::\n\n\nWe should expect 36449 + 38170 = 74619 for cattle_eggs\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#joining the dairy cattle and eggs datasets\ncattle_eggs <- full_join(dairy, Eggs)\n#the dimensions of the joining\ndim(cattle_eggs)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 74619    14\n```\n:::\n\n```{.r .cell-code}\ncattle_eggs\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 74,619 × 14\n   Domain Cod…¹ Domain Area …² Area  Eleme…³ Element Item …⁴ Item  Year …⁵  Year\n   <chr>        <chr>    <dbl> <chr>   <dbl> <chr>     <dbl> <chr>   <dbl> <dbl>\n 1 QL           Lives…       2 Afgh…    5318 Milk A…     882 Milk…    1961  1961\n 2 QL           Lives…       2 Afgh…    5420 Yield       882 Milk…    1961  1961\n 3 QL           Lives…       2 Afgh…    5510 Produc…     882 Milk…    1961  1961\n 4 QL           Lives…       2 Afgh…    5318 Milk A…     882 Milk…    1962  1962\n 5 QL           Lives…       2 Afgh…    5420 Yield       882 Milk…    1962  1962\n 6 QL           Lives…       2 Afgh…    5510 Produc…     882 Milk…    1962  1962\n 7 QL           Lives…       2 Afgh…    5318 Milk A…     882 Milk…    1963  1963\n 8 QL           Lives…       2 Afgh…    5420 Yield       882 Milk…    1963  1963\n 9 QL           Lives…       2 Afgh…    5510 Produc…     882 Milk…    1963  1963\n10 QL           Lives…       2 Afgh…    5318 Milk A…     882 Milk…    1964  1964\n# … with 74,609 more rows, 4 more variables: Unit <chr>, Value <dbl>,\n#   Flag <chr>, `Flag Description` <chr>, and abbreviated variable names\n#   ¹​`Domain Code`, ²​`Area Code`, ³​`Element Code`, ⁴​`Item Code`, ⁵​`Year Code`\n```\n:::\n:::\n\n\nWe should expect 82116 + 38170 = 120286\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#joining the livestock and eggs datasets\nstockeggs <- full_join(livestock, Eggs)\n#the dimensions of the joining\ndim(stockeggs)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 120286     14\n```\n:::\n\n```{.r .cell-code}\nstockeggs\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 120,286 × 14\n   Domain Cod…¹ Domain Area …² Area  Eleme…³ Element Item …⁴ Item  Year …⁵  Year\n   <chr>        <chr>    <dbl> <chr>   <dbl> <chr>     <dbl> <chr>   <dbl> <dbl>\n 1 QA           Live …       2 Afgh…    5111 Stocks     1107 Asses    1961  1961\n 2 QA           Live …       2 Afgh…    5111 Stocks     1107 Asses    1962  1962\n 3 QA           Live …       2 Afgh…    5111 Stocks     1107 Asses    1963  1963\n 4 QA           Live …       2 Afgh…    5111 Stocks     1107 Asses    1964  1964\n 5 QA           Live …       2 Afgh…    5111 Stocks     1107 Asses    1965  1965\n 6 QA           Live …       2 Afgh…    5111 Stocks     1107 Asses    1966  1966\n 7 QA           Live …       2 Afgh…    5111 Stocks     1107 Asses    1967  1967\n 8 QA           Live …       2 Afgh…    5111 Stocks     1107 Asses    1968  1968\n 9 QA           Live …       2 Afgh…    5111 Stocks     1107 Asses    1969  1969\n10 QA           Live …       2 Afgh…    5111 Stocks     1107 Asses    1970  1970\n# … with 120,276 more rows, 4 more variables: Unit <chr>, Value <dbl>,\n#   Flag <chr>, `Flag Description` <chr>, and abbreviated variable names\n#   ¹​`Domain Code`, ²​`Area Code`, ³​`Element Code`, ⁴​`Item Code`, ⁵​`Year Code`\n```\n:::\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}