{
  "hash": "d2777ab86961690f1b6c262cbdc54b43",
  "result": {
    "markdown": "---\ntitle: \"Challenge 3 Submission\"\nauthor: \"Cam Needels\"\ndescription: \"Tidy Data: Pivoting Featuring Eggs\"\ndate: \"08/17/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_3\n  - eggs\n  - Cam Needels\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(summarytools)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readr)\neggs_data <- read.csv(\"B:/Needels/Documents/DACCS 601/601_Spring_2023/posts/_data/eggs_tidy.csv\")\neggs_data\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        month year large_half_dozen large_dozen extra_large_half_dozen\n1     January 2004          126.000     230.000                132.000\n2    February 2004          128.500     226.250                134.500\n3       March 2004          131.000     225.000                137.000\n4       April 2004          131.000     225.000                137.000\n5         May 2004          131.000     225.000                137.000\n6        June 2004          133.500     231.375                137.000\n7        July 2004          133.500     233.500                137.000\n8      August 2004          133.500     233.500                137.000\n9   September 2004          129.750     233.500                135.875\n10    October 2004          128.500     233.500                135.500\n11   November 2004          128.500     233.500                135.500\n12   December 2004          128.500     233.500                135.500\n13    January 2005          128.500     233.500                135.500\n14   February 2005          128.500     233.500                135.500\n15      March 2005          128.500     233.500                135.500\n16      April 2005          128.500     233.500                135.500\n17        May 2005          128.500     233.500                135.500\n18       June 2005          128.500     233.500                135.500\n19       July 2005          128.500     233.500                135.500\n20     August 2005          128.500     233.500                135.500\n21  September 2005          128.500     233.500                135.500\n22    October 2005          128.500     233.500                135.500\n23   November 2005          128.500     233.500                135.500\n24   December 2005          128.500     233.500                135.500\n25    January 2006          128.500     233.500                135.500\n26   February 2006          128.500     233.500                135.500\n27      March 2006          128.500     233.500                135.500\n28      April 2006          128.500     233.500                135.500\n29        May 2006          128.500     233.500                135.500\n30       June 2006          128.500     233.500                135.500\n31       July 2006          128.500     233.500                135.500\n32     August 2006          128.500     233.500                135.500\n33  September 2006          128.500     233.500                135.500\n34    October 2006          128.500     233.500                135.500\n35   November 2006          128.500     233.500                135.500\n36   December 2006          128.500     233.500                135.500\n37    January 2007          128.500     233.500                135.500\n38   February 2007          131.125     236.125                138.125\n39      March 2007          132.000     237.000                139.000\n40      April 2007          132.000     237.000                139.000\n41        May 2007          132.000     237.000                139.000\n42       June 2007          132.000     237.000                139.000\n43       July 2007          132.000     237.000                139.000\n44     August 2007          132.000     237.000                139.000\n45  September 2007          132.000     237.000                139.000\n46    October 2007          132.000     237.000                139.000\n47   November 2007          132.000     237.000                139.000\n48   December 2007          132.000     237.000                139.000\n49    January 2008          132.000     237.000                139.000\n50   February 2008          132.000     237.000                139.000\n51      March 2008          132.000     237.000                139.000\n52      April 2008          132.000     237.000                139.000\n53        May 2008          132.000     237.000                139.000\n54       June 2008          174.500     277.500                185.500\n55       July 2008          174.500     277.500                185.500\n56     August 2008          174.500     277.500                185.500\n57  September 2008          174.500     277.500                185.500\n58    October 2008          174.500     277.500                185.500\n59   November 2008          174.500     277.500                185.500\n60   December 2008          174.500     277.500                185.500\n61    January 2009          174.500     277.500                185.500\n62   February 2009          174.500     277.500                185.500\n63      March 2009          174.500     277.500                185.500\n64      April 2009          174.500     277.500                185.500\n65        May 2009          174.500     277.500                185.500\n66       June 2009          174.500     277.500                185.500\n67       July 2009          174.500     277.500                185.500\n68     August 2009          174.500     271.500                185.500\n69  September 2009          174.500     271.500                185.500\n70    October 2009          174.500     271.500                185.500\n71   November 2009          174.500     271.500                185.500\n72   December 2009          174.500     271.500                185.500\n73    January 2010          174.500     271.500                185.500\n74   February 2010          174.500     271.500                185.500\n75      March 2010          174.500     268.000                185.500\n76      April 2010          174.500     268.000                185.500\n77        May 2010          174.500     268.000                185.500\n78       June 2010          174.500     268.000                185.500\n79       July 2010          174.500     268.000                185.500\n80     August 2010          174.500     268.000                185.500\n81  September 2010          174.500     268.000                185.500\n82    October 2010          174.500     267.500                185.500\n83   November 2010          174.500     267.500                185.500\n84   December 2010          174.500     267.500                185.500\n85    January 2011          174.500     267.500                185.500\n86   February 2011          174.500     267.500                185.500\n87      March 2011          174.500     267.500                185.500\n88      April 2011          174.500     267.500                185.500\n89        May 2011          174.500     267.500                185.500\n90       June 2011          174.500     270.000                185.500\n91       July 2011          174.500     270.000                185.500\n92     August 2011          174.500     270.000                185.500\n93  September 2011          174.500     270.000                185.500\n94    October 2011          174.500     270.000                185.500\n95   November 2011          174.500     270.000                185.500\n96   December 2011          174.500     270.000                185.500\n97    January 2012          174.500     267.500                185.500\n98   February 2012          174.500     267.500                185.500\n99      March 2012          174.500     267.500                185.500\n100     April 2012          174.500     267.500                185.500\n101       May 2012          173.250     267.500                185.500\n102      June 2012          173.250     267.500                185.500\n103      July 2012          173.250     267.500                185.500\n104    August 2012          173.250     267.500                185.500\n105 September 2012          173.250     267.500                185.500\n106   October 2012          173.250     267.500                185.500\n107  November 2012          178.000     267.500                188.130\n108  December 2012          178.000     267.500                188.130\n109   January 2013          178.000     267.500                188.130\n110  February 2013          178.000     267.500                188.130\n111     March 2013          178.000     267.500                188.130\n112     April 2013          178.000     267.500                188.130\n113       May 2013          178.000     267.500                188.130\n114      June 2013          178.000     267.500                188.130\n115      July 2013          178.000     267.500                188.130\n116    August 2013          178.000     267.500                188.130\n117 September 2013          178.000     267.500                188.130\n118   October 2013          178.000     267.500                188.130\n119  November 2013          178.000     267.500                188.130\n120  December 2013          178.000     267.500                188.130\n    extra_large_dozen\n1             230.000\n2             230.000\n3             230.000\n4             234.500\n5             236.000\n6             241.000\n7             241.000\n8             241.000\n9             241.000\n10            241.000\n11            241.000\n12            241.000\n13            241.000\n14            241.000\n15            241.000\n16            241.000\n17            241.000\n18            241.000\n19            241.000\n20            241.000\n21            241.000\n22            241.000\n23            241.000\n24            241.000\n25            241.000\n26            241.000\n27            241.375\n28            241.500\n29            241.500\n30            241.500\n31            241.500\n32            241.500\n33            241.500\n34            241.500\n35            241.500\n36            241.500\n37            241.500\n38            244.125\n39            245.000\n40            245.000\n41            245.000\n42            245.000\n43            245.000\n44            245.000\n45            245.000\n46            245.000\n47            245.000\n48            245.000\n49            245.000\n50            245.000\n51            245.000\n52            245.000\n53            245.000\n54            285.500\n55            285.500\n56            285.500\n57            285.500\n58            285.500\n59            285.500\n60            285.500\n61            285.500\n62            285.500\n63            285.500\n64            285.500\n65            285.500\n66            285.500\n67            285.500\n68            285.500\n69            285.500\n70            285.500\n71            285.500\n72            285.500\n73            285.500\n74            285.500\n75            285.500\n76            285.500\n77            285.500\n78            285.500\n79            285.500\n80            285.500\n81            285.500\n82            285.500\n83            285.500\n84            285.500\n85            285.500\n86            285.500\n87            285.500\n88            285.500\n89            285.500\n90            285.500\n91            285.500\n92            285.500\n93            285.500\n94            285.500\n95            285.500\n96            285.500\n97            285.500\n98            288.500\n99            288.500\n100           288.500\n101           288.500\n102           288.500\n103           288.500\n104           288.500\n105           288.500\n106           288.500\n107           290.000\n108           290.000\n109           290.000\n110           290.000\n111           290.000\n112           290.000\n113           290.000\n114           290.000\n115           290.000\n116           290.000\n117           290.000\n118           290.000\n119           290.000\n120           290.000\n```\n:::\n:::\n\n\n### Describing the Data\n\nThis data is about the number of eggs coming from various dozen sizes. The dates vary from January 2004 until December 2013. This data looks solid however the extra large dozen column is all by itself and it isn't very tidy. In order to make it tidy I decided to make it long by having each category of dozen be a different data point so that extra large dozen can fit in.\n\n### Data prediction\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#existing rows/cases\nnrow(eggs_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 120\n```\n:::\n\n```{.r .cell-code}\n#existing columns/cases\nncol(eggs_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 6\n```\n:::\n\n```{.r .cell-code}\n#expected rows/cases\nnrow(eggs_data) * (ncol(eggs_data)-2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 480\n```\n:::\n\n```{.r .cell-code}\n# expected columns \n2+2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 4\n```\n:::\n:::\n\n\nWith 120 rows in the current data set and 6 columns. 2  columns describe the case of the data set which include the month and year. The remainder of the 4 describe the carton and size of eggs. \n\nAfter creating the carton_type column and the price_per_pound column there are 4 columns total. We should now expect to see 480 columns total because the old 4 columns merged into new rows multiplying the 120 by four times.\n\n## Pivot the Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\neggs_data <-pivot_longer(eggs_data, col = c(large_half_dozen, large_dozen, extra_large_half_dozen, extra_large_dozen),\n                         names_to= \"carton_size\",\n                         values_to= \"price_per_pound\")\neggs_data\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 480 × 4\n   month     year carton_size            price_per_pound\n   <chr>    <int> <chr>                            <dbl>\n 1 January   2004 large_half_dozen                  126 \n 2 January   2004 large_dozen                       230 \n 3 January   2004 extra_large_half_dozen            132 \n 4 January   2004 extra_large_dozen                 230 \n 5 February  2004 large_half_dozen                  128.\n 6 February  2004 large_dozen                       226.\n 7 February  2004 extra_large_half_dozen            134.\n 8 February  2004 extra_large_dozen                 230 \n 9 March     2004 large_half_dozen                  131 \n10 March     2004 large_dozen                       225 \n# … with 470 more rows\n```\n:::\n:::\n\n\nThe pivoted data looks great and has the expected dimensions of 480 rows x 4 columns!\n\n\n\n\n::: {.cell}\n\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}