{
  "hash": "106e7bba68a8a71d6c98d8832ee1629f",
  "result": {
    "markdown": "---\ntitle: \"Challenge 4\"\nauthor: \"Harsha Kanaka Eswar Gudipudi\"\ndescription: \"More data wrangling: pivoting\"\ndate: \"05/15/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_4\n  - Harsha Kanaka Eswar Gudipudi\n  - poultry_tidy.xlsx\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(dplyr)\nlibrary(lubridate)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Challenge Overview\n\nToday's challenge is to:\n\n1)  read in a data set, and describe the data set using both words and any supporting information (e.g., tables, etc)\n2)  tidy data (as needed, including sanity checks)\n3)  identify variables that need to be mutated\n4)  mutate variables and sanity check all mutations\n\n## Read in data\n\nRead in one (or more) of the following datasets, using the correct R package and command.\n\n-   abc_poll.csv ⭐\n-   poultry_tidy.xlsx or organiceggpoultry.xls⭐⭐\n-   FedFundsRate.csv⭐⭐⭐\n-   hotel_bookings.csv⭐⭐⭐⭐\n-   debt_in_trillions.xlsx ⭐⭐⭐⭐⭐\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Reading the poultry dataset\ndf <-readxl::read_excel(\"_data/poultry_tidy.xlsx\")\ndf\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 600 × 4\n   Product  Year Month     Price_Dollar\n   <chr>   <dbl> <chr>            <dbl>\n 1 Whole    2013 January           2.38\n 2 Whole    2013 February          2.38\n 3 Whole    2013 March             2.38\n 4 Whole    2013 April             2.38\n 5 Whole    2013 May               2.38\n 6 Whole    2013 June              2.38\n 7 Whole    2013 July              2.38\n 8 Whole    2013 August            2.38\n 9 Whole    2013 September         2.38\n10 Whole    2013 October           2.38\n# ℹ 590 more rows\n```\n:::\n\n```{.r .cell-code}\nsummary(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Product               Year         Month            Price_Dollar  \n Length:600         Min.   :2004   Length:600         Min.   :1.935  \n Class :character   1st Qu.:2006   Class :character   1st Qu.:2.150  \n Mode  :character   Median :2008   Mode  :character   Median :2.350  \n                    Mean   :2008                      Mean   :3.390  \n                    3rd Qu.:2011                      3rd Qu.:3.905  \n                    Max.   :2013                      Max.   :7.037  \n                                                      NA's   :7      \n```\n:::\n\n```{.r .cell-code}\ndim(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 600   4\n```\n:::\n:::\n\n\nThere are four types of product in poultry. Which are as follows:\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(paste(unique(df$Product), collapse = \", \"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nWhole, B/S Breast, Bone-in Breast, Whole Legs, Thighs\n```\n:::\n:::\n\n\n### Briefly describe the data\n\nThe data includes information about products, their prices in US dollars, year, and month. It has 600 rows and 4 columns: Product, Year, Month, and Price_Dollar. The minimum and maximum year in the data are 2004 and 2013, respectively. The minimum and maximum price in the data are 1.935 and 7.037 US dollars, respectively. The data has some missing values in the Price_Dollar column, indicated by NA's.\n\n## Tidy Data (as needed)\n\nIs your data already tidy, or is there work to be done? Be sure to anticipate your end result to provide a sanity check, and document your work here.\n\nThe data can still be considered tidy even with some NA values in the Price_Dollar column. The tidy data principles only require that each variable has a separate column, each observation has a separate row, and each value has a separate cell. As long as the data follows these principles, it is considered tidy. In this case, the data meets these requirements, so no additional steps are required to make it tidy.\n\nAny additional comments?\n\n## Identify variables that need to be mutated\n\nAre there any variables that require mutation to be usable in your analysis stream? For example, are all time variables correctly coded as dates? Are all string variables reduced and cleaned to sensible categories? Do you need to turn any variables into factors and reorder for ease of graphics and visualization?\n\nDocument your work here.\n\nCombining the \"Year\" and \"Month\" variables to create a \"Date\" variable in a suitable format can be useful in a few ways.\n\nFirst, it allows for easy time-series analysis and visualization. By having the data in a time-series format, we can easily plot the data and observe trends and patterns over time.\n\nSecond, it can simplify the data structure. Instead of having multiple variables representing time (i.e., \"Year\" and \"Month\"), we can have a single variable that represents time and use it for further analysis and visualization.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- df %>%\n  mutate(Date = ymd(paste(Year, Month, \"01\", sep = \"-\")))\n\ndf\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 600 × 5\n   Product  Year Month     Price_Dollar Date      \n   <chr>   <dbl> <chr>            <dbl> <date>    \n 1 Whole    2013 January           2.38 2013-01-01\n 2 Whole    2013 February          2.38 2013-02-01\n 3 Whole    2013 March             2.38 2013-03-01\n 4 Whole    2013 April             2.38 2013-04-01\n 5 Whole    2013 May               2.38 2013-05-01\n 6 Whole    2013 June              2.38 2013-06-01\n 7 Whole    2013 July              2.38 2013-07-01\n 8 Whole    2013 August            2.38 2013-08-01\n 9 Whole    2013 September         2.38 2013-09-01\n10 Whole    2013 October           2.38 2013-10-01\n# ℹ 590 more rows\n```\n:::\n:::\n\n\nAny additional comments?",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}