{
  "hash": "89816e3da8dcbda0a462f4afe8b81295",
  "result": {
    "markdown": "---\ntitle: \"Challenge 2\"\nauthor: \"Sai Venkatesh\"\ndescription: \"Data wrangling: using group() and summarise()\"\ndate: \"04/12/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n- challenge_2\n- railroads\n- faostat\n- hotel_bookings\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Challenge Overview\n\nToday's challenge is to\n\n1)  read in a data set, and describe the data using both words and any supporting information (e.g., tables, etc)\n2)  provide summary statistics for different interesting groups within the data, and interpret those statistics\n\n## Read in the Data\n\n\nWe are going to load and use the railroad data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  library(readr)\n  railroaddata <-read_csv(\"_data/railroad_2012_clean_county.csv\")\n```\n:::\n\n\n\n## Describe the data\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  print(\"Lets load the data and see the dimensions and columns of the data.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Lets load the data and see the dimensions and columns of the data.\"\n```\n:::\n\n```{.r .cell-code}\n  # The Dimensions \n  dim(railroaddata)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2930    3\n```\n:::\n\n```{.r .cell-code}\n  # The Column Names \n  colnames(railroaddata)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"state\"           \"county\"          \"total_employees\"\n```\n:::\n\n```{.r .cell-code}\n  # THe total employees\n  summarize(railroaddata, sum(`total_employees`))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 1\n  `sum(total_employees)`\n                   <dbl>\n1                 255432\n```\n:::\n:::\n\n\nFrom the above, we can see that the Railroad data has 2930 rows and 3 columns.\nThe 3 column names are state, county and total_employees.\nThe data displayed shows that this is the railroad employees count distribution based on the state and county.\n\nWe can also see the total number of employees as 255432.\n\n## Provide Grouped Summary Statistics\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Number of Employees Per State\nprint(\"The total number of employees in the states > 1000 ordered by the count:-\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"The total number of employees in the states > 1000 ordered by the count:-\"\n```\n:::\n\n```{.r .cell-code}\nrailroaddata %>%\n  group_by(state) %>%\n  summarize(state_total = sum(total_employees))  %>%\n  filter(state_total > 1000)  %>%\n  select(state, state_total)  %>%\n  arrange(desc(state_total))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 42 × 2\n   state state_total\n   <chr>       <dbl>\n 1 TX          19839\n 2 IL          19131\n 3 NY          17050\n 4 NE          13176\n 5 CA          13137\n 6 PA          12769\n 7 OH           9056\n 8 GA           8605\n 9 IN           8537\n10 MO           8419\n# … with 32 more rows\n```\n:::\n:::\n\n\n\nGrouping By State\n\nWe are going to consider state and group by it.\nWe are then going to find the distribution of employees in each state and associated functions to get more sense of the underlying data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummarizedData <- railroaddata %>%\n  group_by(state) %>%\n  summarize(Mean = mean(total_employees, na.rm=TRUE), \n            SD = sd(total_employees, na.rm = TRUE), \n            Max = max(total_employees, na.rm = TRUE), \n            Min = min(total_employees, na.rm = TRUE), \n            Median = median(total_employees, na.rm = TRUE))\n\nprint(summarizedData, n=60)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 53 × 6\n   state   Mean      SD   Max   Min Median\n   <chr>  <dbl>   <dbl> <dbl> <dbl>  <dbl>\n 1 AE      2     NA         2     2    2  \n 2 AK     17.2   34.8      88     1    2.5\n 3 AL     63.5  130.      990     1   26  \n 4 AP      1     NA         1     1    1  \n 5 AR     53.8  131.      972     1   16.5\n 6 AZ    210.   228.      749     3   94  \n 7 CA    239.   549.     2888     1   61  \n 8 CO     64.0  128.      553     1   10  \n 9 CT    324    520.     1561    26  125  \n10 DC    279     NA       279   279  279  \n11 DE    498.   674.     1275    62  158  \n12 FL    111.   386.     3073     1   20  \n13 GA     56.6  113.      878     1   15  \n14 HI      1.33   0.577     2     1    1  \n15 IA     40.6   76.8     609     1   14  \n16 ID     43.4   95.5     538     1   12  \n17 IL    186.   829.     8207     1   42  \n18 IN     92.8  233.     1999     3   30  \n19 KS     64.1  167.     1286     1   12  \n20 KY     40.4   76.9     483     1   11  \n21 LA     62.1  101.      546     1   20  \n22 MA    282.   204.      673    44  271  \n23 MD    196.   233.      809     1  108. \n24 ME     40.9   38.1     117     2   29  \n25 MI     50.4  110.      849     1   13  \n26 MN     63.6  122.      651     1   22  \n27 MO     73.2  208.     2055     1   24  \n28 MS     27.1   46.7     341     1   11.5\n29 MT     62.8  123.      525     1   11  \n30 NC     33.4   58.6     322     1   14  \n31 ND     45.0   92.5     407     1    8  \n32 NE    148.   512.     3797     1   15  \n33 NH     39.3   54.3     146     2   15.5\n34 NJ    397.   338.     1097    19  296  \n35 NM     67.5  113.      431     2   26  \n36 NV     62.2   94.8     269     1   19  \n37 NY    280.   591.     3685     5   71  \n38 OH    103.   148.      842     3   41  \n39 OK     31.8   55.9     377     1   14  \n40 OR     70.4  108.      467     2   30  \n41 PA    196.   293.     1649     3   85  \n42 RI     97.4  129.      318     8   48  \n43 SC     49.9   53.9     220     1   25  \n44 SD     18.2   34.6     167     1    5  \n45 TN     54.4   94.8     621     1   26  \n46 TX     89.8  350.     4235     1   17  \n47 UT     76.7  143.      580     1   16  \n48 VA     82.1  341.     3249     1   25.5\n49 VT     18.5   24.5      83     3    8.5\n50 WA    134.   256.     1039     1   29  \n51 WI     54.7   82.2     465     2   23  \n52 WV     60.6   85.8     406     1   33  \n53 WY    131.   169.      737     3   60.5\n```\n:::\n:::\n\n\n\n### Explain and Interpret\n\nI choose state because we are able to analyse the distributions of employees across counties using this. We are able to notice that Texas has the largest number of employees. However it is not the counties in Texas that have the maximum number of employees. But instead Cook county in IL has the maximum number of employees. Similarly there are counties whose mean employee counts exceed Texas like IL, NY even though the total is largest in the latter. Infact Texas median is 17 and mean is around 89 which means that there are a lot of counties in Texas with less than 100 employees. Hence having more total need not correlate to larger counties/employee count. It could be a large number of small counties which skews the overall count like Texas.",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}