{
  "hash": "e36b9a6fc90773cc947524debee88889",
  "result": {
    "markdown": "---\ntitle: \"Challenge 8: Michele Carlin\"\nauthor: \"Michele Carlin\"\ndesription: \"Joining data\"\ndate: \"05/03/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_8\n  - Michele Carlin\n  - snl\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(summarytools)\nlibrary(dbplyr)\nlibrary(readr)\n\n\nknitr::opts_chunk$set(echo = TRUE)\n```\n:::\n\n\nRead in and view summary of SNL_actors dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsnl_actors <- read_csv (\"_data/snl_actors.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nRows: 2306 Columns: 4\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (4): aid, url, type, gender\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n:::\n\n```{.r .cell-code}\nView(snl_actors)\nview(dfSummary(snl_actors))\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nSwitching method to 'browser'\nOutput file written: C:\\Users\\CarlinML\\AppData\\Local\\Temp\\RtmpGkYA9b\\file52743747a45.html\n```\n:::\n:::\n\n\nRead in and view summary of SNL_casts dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsnl_casts <- read_csv (\"_data/snl_casts.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nRows: 614 Columns: 8\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (1): aid\ndbl (5): sid, first_epid, last_epid, n_episodes, season_fraction\nlgl (2): featured, update_anchor\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n:::\n\n```{.r .cell-code}\nView(snl_casts)\nview(dfSummary(snl_casts))\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nSwitching method to 'browser'\nOutput file written: C:\\Users\\CarlinML\\AppData\\Local\\Temp\\RtmpGkYA9b\\file52743e911dc7.html\n```\n:::\n:::\n\n\nRead in and view summary of SNL_seasons dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsnl_seasons <- read_csv (\"_data/snl_seasons.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nRows: 46 Columns: 5\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\ndbl (5): sid, year, first_epid, last_epid, n_episodes\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n:::\n\n```{.r .cell-code}\nView(snl_seasons)\nview(dfSummary(snl_seasons))\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nSwitching method to 'browser'\nOutput file written: C:\\Users\\CarlinML\\AppData\\Local\\Temp\\RtmpGkYA9b\\file52746d185302.html\n```\n:::\n:::\n\n\n\nSummarize datasets...\nThe SNL_actors dataset contains 2306 rows and 4 columns including the actor's name (aid), a url to more information about that actor, the type of actor (cast, crew, guest, or unknown) and their gender.\n\nThe SNL_casts dataset contains 614 rows and 8 columns of data about cast members only (e.g., the cast member's name (aid), season ID (sid), the date of their first and last episodes, etc.). In this dataset, every cast member has a separate row for each season they were on, as well as the number of episodes they were in for each of those seasons.\n\nThe SNL_seasons dataset contains 46 rows and 5 columns including season ID (sid), the year, dates of first and last episodes, and number of episodes in each season.\n\nI will start with the SNL_casts file and merge in the SNL_actors file matching on actor ID (aid). The casts file only contains information on cast members, therefore if a did a left join, only cast member data would be retained.  I am going to perform a full join so that I can retain data on both cast members and guests.  \n\n\n::: {.cell}\n\n```{.r .cell-code}\ncasts_actors <- snl_casts %>% full_join(snl_actors, \n                              by=c('aid'))\nView(casts_actors)\nview(dfSummary(casts_actors))\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nSwitching method to 'browser'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nOutput file written: C:\\Users\\CarlinML\\AppData\\Local\\Temp\\RtmpGkYA9b\\file52747bc81f05.html\n```\n:::\n:::\n\n\nThis new casts_actors file now contains 2764 rows and 11 columns.\n\nI will now join the SNL_seasons file into my newly created casts_actors dataset; matching on season ID (sid).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSNL <- casts_actors %>% left_join(snl_seasons, \n                              by=c('sid'))\nView(SNL)\nview(dfSummary(SNL))\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nSwitching method to 'browser'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nOutput file written: C:\\Users\\CarlinML\\AppData\\Local\\Temp\\RtmpGkYA9b\\file5274a0413cc.html\n```\n:::\n:::\n\n\nMy new SNL dataset contains 2764 rows and 15 columns. \n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}