{
  "hash": "5761f7aa599502b4a1bf1bd6a71db3c4",
  "result": {
    "markdown": "---\ntitle: \"Challenge 4\"\nauthor: \"Jaswanth Reddy Kommuru\"\ndescription: \"More data wrangling: pivoting\"\ndate: \"05/09/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_4\n  - Jaswanth Reddy Kommuru\n  - poultry_tidy\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(lubridate)\nlibrary(tidyverse)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Challenge Overview\n\nToday's challenge is to:\n\n1)  read in a data set, and describe the data set using both words and any supporting information (e.g., tables, etc)\n2)  tidy data (as needed, including sanity checks)\n3)  identify variables that need to be mutated\n4)  mutate variables and sanity check all mutations\n\n## Read in data\n\nRead in one (or more) of the following datasets, using the correct R package and command.\n\n-   abc_poll.csv ⭐\n-   poultry_tidy.xlsx or organiceggpoultry.xls⭐⭐\n-   FedFundsRate.csv⭐⭐⭐\n-   hotel_bookings.csv⭐⭐⭐⭐\n-   debt_in_trillions.xlsx ⭐⭐⭐⭐⭐\n\n\n::: {.cell}\n\n```{.r .cell-code}\npoultrydata <-readxl::read_excel(\"~/Documents/601/601_Spring_2023/posts/_data/poultry_tidy.xlsx\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(poultrydata)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 4\n  Product  Year Month    Price_Dollar\n  <chr>   <dbl> <chr>           <dbl>\n1 Whole    2013 January          2.38\n2 Whole    2013 February         2.38\n3 Whole    2013 March            2.38\n4 Whole    2013 April            2.38\n5 Whole    2013 May              2.38\n6 Whole    2013 June             2.38\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(poultrydata)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 600   4\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(poultrydata)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ntibble [600 × 4] (S3: tbl_df/tbl/data.frame)\n $ Product     : chr [1:600] \"Whole\" \"Whole\" \"Whole\" \"Whole\" ...\n $ Year        : num [1:600] 2013 2013 2013 2013 2013 ...\n $ Month       : chr [1:600] \"January\" \"February\" \"March\" \"April\" ...\n $ Price_Dollar: num [1:600] 2.38 2.38 2.38 2.38 2.38 ...\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n poultrydata%>%\n  select(\"Product\") %>%\n  distinct(.)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 5 × 1\n  Product       \n  <chr>         \n1 Whole         \n2 B/S Breast    \n3 Bone-in Breast\n4 Whole Legs    \n5 Thighs        \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n poultrydata%>%\n  select(\"Year\") %>%\n  distinct(.)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 10 × 1\n    Year\n   <dbl>\n 1  2013\n 2  2012\n 3  2011\n 4  2010\n 5  2009\n 6  2008\n 7  2007\n 8  2006\n 9  2005\n10  2004\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncolnames(poultrydata)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Product\"      \"Year\"         \"Month\"        \"Price_Dollar\"\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nnrow(poultrydata)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 600\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(poultrydata)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Product               Year         Month            Price_Dollar  \n Length:600         Min.   :2004   Length:600         Min.   :1.935  \n Class :character   1st Qu.:2006   Class :character   1st Qu.:2.150  \n Mode  :character   Median :2008   Mode  :character   Median :2.350  \n                    Mean   :2008                      Mean   :3.390  \n                    3rd Qu.:2011                      3rd Qu.:3.905  \n                    Max.   :2013                      Max.   :7.037  \n                                                      NA's   :7      \n```\n:::\n:::\n\n\n\n### Briefly describe the data\n\nThe dataset comprises 4 columns and 600 rows spanning from 2004 to 2013. It includes various poultry products such as Whole, B/S Breast, Bone-in Breast, Whole Legs, and Thighs. The price range for these products extends from a minimum of 1.935 to 7.037. Upon examining the summary, it becomes evident that certain price values are missing, specifically those associated with product Bone-in Breast and Thighs. Upon further investigation, it was observed that a majority of the missing values are concentrated within these two product categories.\n\n## Tidy Data (as needed)\n\nIs your data already tidy, or is there work to be done? Be sure to anticipate your end result to provide a sanity check, and document your work here.\n\nThe provided dataset is already in a tidy format. While there is the possibility of removing the rows with missing data, but still I will preserve these rows. Despite the presence of missing values, these rows still contain valuable information in other columns, making them important for a comprehensive analysis.\n\n\nAny additional comments?\n\n## Identify variables that need to be mutated\n\nAre there any variables that require mutation to be usable in your analysis stream? For example, are all time variables correctly coded as dates? Are all string variables reduced and cleaned to sensible categories? Do you need to turn any variables into factors and reorder for ease of graphics and visualization?\n\nDocument your work here.\n\nMaking two modifications to the dataset would enhance the analysis. Firstly, since the prices are currently discrete values, it would be advantageous to introduce price ranges, allowing for categorization into high, low, and medium price categories. This would provide a more meaningful representation of the data. Secondly, I suggest combining the variables \"year\" and \"month\" into a single column to facilitate direct analysis using the merged time information. This would streamline the analysis process and enable more comprehensive insights.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npoultrydata_mutated <- poultrydata %>%\n  mutate(Price_Range = ifelse(Price_Dollar < 3, 'low', ifelse(Price_Dollar < 5, 'medium', 'high')))\n\npoultrydata_mutated <- poultrydata_mutated %>%\n  mutate(Date = as.Date(paste(Year, Month, '01'), format = '%Y %B %d'))\n\npoultrydata_mutated\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 600 × 6\n   Product  Year Month     Price_Dollar Price_Range Date      \n   <chr>   <dbl> <chr>            <dbl> <chr>       <date>    \n 1 Whole    2013 January           2.38 low         2013-01-01\n 2 Whole    2013 February          2.38 low         2013-02-01\n 3 Whole    2013 March             2.38 low         2013-03-01\n 4 Whole    2013 April             2.38 low         2013-04-01\n 5 Whole    2013 May               2.38 low         2013-05-01\n 6 Whole    2013 June              2.38 low         2013-06-01\n 7 Whole    2013 July              2.38 low         2013-07-01\n 8 Whole    2013 August            2.38 low         2013-08-01\n 9 Whole    2013 September         2.38 low         2013-09-01\n10 Whole    2013 October           2.38 low         2013-10-01\n# ℹ 590 more rows\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n poultrydata_mutated%>%\n  select(`Price_Range`) %>%\n  n_distinct(.)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 4\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n poultrydata_mutated%>%\n  select(`Price_Range`) %>%\n  distinct(.)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 4 × 1\n  Price_Range\n  <chr>      \n1 low        \n2 high       \n3 medium     \n4 <NA>       \n```\n:::\n:::\n\n\nAny additional comments?\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}