{
  "hash": "a43bf206c8e5031a04ac9b6d00a40691",
  "result": {
    "markdown": "---\ntitle: \"Challenge 7 Instructions\"\nauthor: \"Kevin Martell Luya\"\ndescription: \"Visualizing Multiple Dimensions\"\ndate: \"05/05/2023\"\nformat:\n  html:\n    toc: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_7\n  - hotel_bookings\n  - australian_marriage\n  - air_bnb\n  - eggs\n  - abc_poll\n  - faostat\n  - usa_households\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(ggplot2)\nlibrary(here)\nlibrary(ggthemes)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Challenge Overview\n\nToday's challenge is to:\n\n1)  read in a data set, and describe the data set using both words and any supporting information (e.g., tables, etc)\n2)  tidy data (as needed, including sanity checks)\n3)  mutate variables as needed (including sanity checks)\n4)  Recreate at least two graphs from previous exercises, but introduce at least one additional dimension that you omitted before using ggplot functionality (color, shape, line, facet, etc) The goal is not to create unneeded [chart ink (Tufte)](https://www.edwardtufte.com/tufte/), but to concisely capture variation in additional dimensions that were collapsed in your earlier 2 or 3 dimensional graphs.\n   - Explain why you choose the specific graph type\n5) If you haven't tried in previous weeks, work this week to make your graphs \"publication\" ready with titles, captions, and pretty axis labels and other viewer-friendly features\n\n[R Graph Gallery](https://r-graph-gallery.com/) is a good starting point for thinking about what information is conveyed in standard graph types, and includes example R code. And anyone not familiar with Edward Tufte should check out his [fantastic books](https://www.edwardtufte.com/tufte/books_vdqi) and [courses on data visualizaton.](https://www.edwardtufte.com/tufte/courses)\n\n(be sure to only include the category tags for the data you use!)\n\n## Read in data\n\nRead in one (or more) of the following datasets, using the correct R package and command.\n\n  - eggs ⭐\n  - abc_poll ⭐⭐\n  - australian_marriage ⭐⭐\n  - hotel_bookings ⭐⭐⭐\n  - air_bnb  ⭐⭐⭐\n  - us_hh ⭐⭐⭐⭐\n  - faostat ⭐⭐⭐⭐⭐\n\n\n::: {.cell}\n\n```{.r .cell-code}\nairb<-here(\"posts\",\"_data\",\"AB_NYC_2019.csv\") %>%\n  read_csv()\nairb\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 48,895 × 16\n      id name      host_id host_…¹ neigh…² neigh…³ latit…⁴ longi…⁵ room_…⁶ price\n   <dbl> <chr>       <dbl> <chr>   <chr>   <chr>     <dbl>   <dbl> <chr>   <dbl>\n 1  2539 Clean & …    2787 John    Brookl… Kensin…    40.6   -74.0 Privat…   149\n 2  2595 Skylit M…    2845 Jennif… Manhat… Midtown    40.8   -74.0 Entire…   225\n 3  3647 THE VILL…    4632 Elisab… Manhat… Harlem     40.8   -73.9 Privat…   150\n 4  3831 Cozy Ent…    4869 LisaRo… Brookl… Clinto…    40.7   -74.0 Entire…    89\n 5  5022 Entire A…    7192 Laura   Manhat… East H…    40.8   -73.9 Entire…    80\n 6  5099 Large Co…    7322 Chris   Manhat… Murray…    40.7   -74.0 Entire…   200\n 7  5121 BlissArt…    7356 Garon   Brookl… Bedfor…    40.7   -74.0 Privat…    60\n 8  5178 Large Fu…    8967 Shunic… Manhat… Hell's…    40.8   -74.0 Privat…    79\n 9  5203 Cozy Cle…    7490 MaryEl… Manhat… Upper …    40.8   -74.0 Privat…    79\n10  5238 Cute & C…    7549 Ben     Manhat… Chinat…    40.7   -74.0 Entire…   150\n# … with 48,885 more rows, 6 more variables: minimum_nights <dbl>,\n#   number_of_reviews <dbl>, last_review <date>, reviews_per_month <dbl>,\n#   calculated_host_listings_count <dbl>, availability_365 <dbl>, and\n#   abbreviated variable names ¹​host_name, ²​neighbourhood_group,\n#   ³​neighbourhood, ⁴​latitude, ⁵​longitude, ⁶​room_type\n```\n:::\n:::\n\n\n### Briefly describe the data\nAB_NYC_2019.csv contains listing data about rental places in New York. It would be interesting\nanalyzing this data which comes from the concept of share economy.\n\n## Tidy Data (as needed)\n\nIs your data already tidy, or is there work to be done? Be sure to anticipate your end result to provide a sanity check, and document your work here.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(airb,aes(minimum_nights))+\n  geom_histogram()\n```\n\n::: {.cell-output-display}\n![](KevinMartell_challenge7_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\nFor minimum_nights varible, the plotted histograms presents outliers, let's remove them.\n\n::: {.cell}\n\n```{.r .cell-code}\nless_than_400 = airb%>%\n  filter(minimum_nights < 400)\nggplot(less_than_400,aes(minimum_nights))+\n  geom_histogram()\n```\n\n::: {.cell-output-display}\n![](KevinMartell_challenge7_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\nFor minimum_nights varible, the plotted histograms presents outliers, let's remove them.\n\n::: {.cell}\n\n```{.r .cell-code}\nless_than_200 = airb%>%\n  filter(minimum_nights < 200)\nggplot(less_than_200,aes(minimum_nights))+\n  geom_histogram()\n```\n\n::: {.cell-output-display}\n![](KevinMartell_challenge7_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nClearly we have more outliers, let's filter data even more.\n\n::: {.cell}\n\n```{.r .cell-code}\nless_than_40 <- airb%>%\n  filter(minimum_nights < 40)\nggplot(less_than_40,aes(minimum_nights))+\n  geom_histogram()\n```\n\n::: {.cell-output-display}\n![](KevinMartell_challenge7_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\nThe shape has two humps. It is bimobal.\n\n## Visualization with Multiple Dimensions\nNow let's consider rooms types and how they relate to the  minimmum nights.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nless_than_40 %>%\n  ggplot(aes(room_type,minimum_nights))+\n  geom_boxplot(alpha=.6)+\n  scale_y_continuous(labels=scales::number_format())+\n  labs(x=\"Type of room\",\n       y=\"number of nigths\")+\n  ggthemes::theme_few()\n```\n\n::: {.cell-output-display}\n![](KevinMartell_challenge7_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nNow, lets check the minimmum nights per neighbourhood group and check if follow the same bimodal \ndistribution.\n\n::: {.cell}\n\n```{.r .cell-code}\nless_than_40 %>%\n  ggplot(aes(minimum_nights))+\n  geom_histogram()+\n  facet_wrap(vars(neighbourhood_group),scales=\"free\")\n```\n\n::: {.cell-output-display}\n![](KevinMartell_challenge7_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\nWe can observe that all the neighbourhoods follow the same distribution. This suggests they have the\nsame behavior when in terms of minimum nights.\n\nNow, let's create a new column that shows 5-day intervals for minimum nights. Because there are outliers\nwe take values below 200 minimum nights. We filtered this data in previous steps.\n\n::: {.cell}\n\n```{.r .cell-code}\nnights_ranges_by_5_days <- less_than_200 %>%\n  mutate(nights_ranges = case_when(\n    minimum_nights <= 5  ~ \"1_5\",\n    minimum_nights > 5  & minimum_nights <= 10  ~ \"5-10\",\n    minimum_nights > 10  & minimum_nights <= 15  ~ \"10-15\",\n    minimum_nights > 15  & minimum_nights <= 20  ~ \"15-20\",\n    minimum_nights > 20  & minimum_nights <= 25  ~ \"20-25\",\n    minimum_nights > 25  & minimum_nights <= 30  ~ \"25-30\",\n    minimum_nights > 30  & minimum_nights <= 35  ~ \"30-35\",\n    minimum_nights > 35  & minimum_nights <= 40  ~ \"35-40\",\n    minimum_nights > 40  & minimum_nights <= 45  ~ \"40-45\",\n    minimum_nights > 45  & minimum_nights <= 50  ~ \"45-50\",\n    minimum_nights > 50  & minimum_nights <= 55  ~ \"50-55\",\n    minimum_nights > 55  & minimum_nights <= 100  ~ \"55-100\",\n    minimum_nights > 100 ~ \"+100\" ))%>%\n  fill(nights_ranges, .direction = \"down\")\n\nnights_ranges_by_5_days_factor <- nights_ranges_by_5_days %>%\n  mutate( nights_ranges = factor(nights_ranges))\n```\n:::\n\n\n\nLet's check the intervals were created.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(nights_ranges_by_5_days_factor)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       id               name              host_id           host_name        \n Min.   :    2539   Length:48822       Min.   :     2438   Length:48822      \n 1st Qu.: 9476788   Class :character   1st Qu.:  7831209   Class :character  \n Median :19692584   Mode  :character   Median : 30844240   Mode  :character  \n Mean   :19025154                      Mean   : 67666153                     \n 3rd Qu.:29156076                      3rd Qu.:107434423                     \n Max.   :36487245                      Max.   :274321313                     \n                                                                             \n neighbourhood_group neighbourhood         latitude       longitude     \n Length:48822        Length:48822       Min.   :40.50   Min.   :-74.24  \n Class :character    Class :character   1st Qu.:40.69   1st Qu.:-73.98  \n Mode  :character    Mode  :character   Median :40.72   Median :-73.96  \n                                        Mean   :40.73   Mean   :-73.95  \n                                        3rd Qu.:40.76   3rd Qu.:-73.94  \n                                        Max.   :40.91   Max.   :-73.71  \n                                                                        \n  room_type             price         minimum_nights    number_of_reviews\n Length:48822       Min.   :    0.0   Min.   :  1.000   Min.   :  0.00   \n Class :character   1st Qu.:   69.0   1st Qu.:  1.000   1st Qu.:  1.00   \n Mode  :character   Median :  105.5   Median :  2.000   Median :  5.00   \n                    Mean   :  152.6   Mean   :  6.461   Mean   : 23.29   \n                    3rd Qu.:  175.0   3rd Qu.:  5.000   3rd Qu.: 24.00   \n                    Max.   :10000.0   Max.   :198.000   Max.   :629.00   \n                                                                         \n  last_review         reviews_per_month calculated_host_listings_count\n Min.   :2011-03-28   Min.   : 0.010    Min.   :  1.000               \n 1st Qu.:2018-07-10   1st Qu.: 0.190    1st Qu.:  1.000               \n Median :2019-05-19   Median : 0.720    Median :  1.000               \n Mean   :2018-10-04   Mean   : 1.374    Mean   :  7.152               \n 3rd Qu.:2019-06-23   3rd Qu.: 2.020    3rd Qu.:  2.000               \n Max.   :2019-07-08   Max.   :58.500    Max.   :327.000               \n NA's   :10020        NA's   :10020                                   \n availability_365 nights_ranges  \n Min.   :  0.0    1_5    :38752  \n 1st Qu.:  0.0    25-30  : 4336  \n Median : 45.0    5-10   : 3503  \n Mean   :112.6    10-15  : 1019  \n 3rd Qu.:226.0    15-20  :  291  \n Max.   :365.0    55-100 :  273  \n                  (Other):  648  \n```\n:::\n:::\n\n\nNow, let see the 5-day intervals for minimum nights and how they relate to the average price for each interval.\n\n::: {.cell}\n\n```{.r .cell-code}\nnights_ranges_by_5_days_factor %>%\n\n  group_by(nights_ranges) %>%\n  summarise(mean_price=mean(price)) %>%\n  ggplot(aes(reorder(nights_ranges,-mean_price), mean_price))+\n  geom_col()+\n  labs(x=\"minimum_nights ranges in days\")\n```\n\n::: {.cell-output-display}\n![](KevinMartell_challenge7_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\nAfter tailoring the outliers, minimum_nights less than 200, data suggests that for minimum nights between 35 and 40, \na host might charge around 365 dollars in average which is higer than minimum nights between 1 and 5, where the host \nmight charge 150 dollars dollars in average.\n\nHowever, if the 1-5-day hosts were able to rent the at least 4 consecutive times (4 _ 20 days), then the income would\nbe higher in average compared to the 35-40-day hosts. \n\nFrom the host perspective, data suggest that it is more profitable to rent a house for less number of days compared to \nother minimum nights 5-day interval.\n",
    "supporting": [
      "KevinMartell_challenge7_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}