{
  "hash": "a58d1f14974cf144f274455a6896082d",
  "result": {
    "markdown": "---\ntitle: \"DACSS601: Final Paper\"\nauthor: \"Harsha Kanaka Eswar Gudipudi\"\ndescription: \"Bike Sales\"\ndate: \"05/22/2023\"\noutput: distill::distill_article\nformat:\n  html:\n    df-print: paged\n    toc: true\n    code-copy: true\n    code-fold: true\n    code-tools: true\n    css: styles.css\ncategories:\n  - bike_sales_data\n  - final_project_data_description_and_visualization\neditor_options: \n  chunk_output_type: console\n---\n\n\n# Introduction\nThe dataset used in this analysis was collected by the Global Bike Inc., a leading manufacturer and retailer of bicycles worldwide. The dataset provides comprehensive information on bike sales, customer demographics, and profitability across multiple countries.\n\nThe dataset includes data on various aspects, such as sales transactions, customer information, product details, and financial records. Each row in the dataset represents a specific sales transaction, providing details about the customer, the purchased product, the country of sale, and other relevant information.\n\nThe dataset was collected over a period of several years, encompassing different seasons and economic conditions. The collection process involved tracking sales data from various Global Bike retail locations and online channels, as well as gathering customer feedback and preferences.\n\n## Research Questions\n\nBased on this dataset, the following research questions will be explored:\n\n1. What are the top-selling bike models and their sales trends over the years?\n2. How is the gender distribution among bike customers, and do gender preferences vary for different bike models?\n3. How does profitability vary by month, and are there any seasonal patterns in bike sales?\n4. Are there significant differences in profitability among countries, and what factors may contribute to these variations?\n5. How does customer age impact bike sales and profitability, and are there any age-specific preferences?\n\nBy addressing these research questions, we aim to gain insights into the sales performance, customer preferences, and profitability patterns within the bike industry. These findings will help inform decision-making processes related to marketing strategies, inventory management, and product development, ultimately leading to improved business performance and customer satisfaction.\n\n\n  \n## Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(maps)\nlibrary(tidyverse)\nlibrary(readxl)\nlibrary(ggplot2)\nlibrary(lubridate)\nlibrary(gridExtra)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- read_csv(\"HarshaKanakaEswar_FinalProjectData/bike_sales_data.csv\")\ndim(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 113036     18\n```\n:::\n\n```{.r .cell-code}\nsummary(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      Date                 Day           Month                Year     \n Min.   :2011-01-01   Min.   : 1.00   Length:113036      Min.   :2011  \n 1st Qu.:2013-12-22   1st Qu.: 8.00   Class :character   1st Qu.:2013  \n Median :2014-06-27   Median :16.00   Mode  :character   Median :2014  \n Mean   :2014-11-23   Mean   :15.67                      Mean   :2014  \n 3rd Qu.:2016-01-09   3rd Qu.:23.00                      3rd Qu.:2016  \n Max.   :2016-07-31   Max.   :31.00                      Max.   :2016  \n  Customer_Age    Age_Group         Customer_Gender      Country         \n Min.   :17.00   Length:113036      Length:113036      Length:113036     \n 1st Qu.:28.00   Class :character   Class :character   Class :character  \n Median :35.00   Mode  :character   Mode  :character   Mode  :character  \n Mean   :35.92                                                           \n 3rd Qu.:43.00                                                           \n Max.   :87.00                                                           \n    State           Product_Category   Sub_Category         Product         \n Length:113036      Length:113036      Length:113036      Length:113036     \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n Order_Quantity   Unit_Cost        Unit_Price         Profit       \n Min.   : 1.0   Min.   :   1.0   Min.   :   2.0   Min.   :  -30.0  \n 1st Qu.: 2.0   1st Qu.:   2.0   1st Qu.:   5.0   1st Qu.:   29.0  \n Median :10.0   Median :   9.0   Median :  24.0   Median :  101.0  \n Mean   :11.9   Mean   : 267.3   Mean   : 452.9   Mean   :  285.1  \n 3rd Qu.:20.0   3rd Qu.:  42.0   3rd Qu.:  70.0   3rd Qu.:  358.0  \n Max.   :32.0   Max.   :2171.0   Max.   :3578.0   Max.   :15096.0  \n      Cost            Revenue       \n Min.   :    1.0   Min.   :    2.0  \n 1st Qu.:   28.0   1st Qu.:   63.0  \n Median :  108.0   Median :  223.0  \n Mean   :  469.3   Mean   :  754.4  \n 3rd Qu.:  432.0   3rd Qu.:  800.0  \n Max.   :42978.0   Max.   :58074.0  \n```\n:::\n\n```{.r .cell-code}\nunique_country <- unique(data$Country)\ncat(paste(unique_country, collapse = \", \"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCanada, Australia, United States, Germany, France, United Kingdom\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Check for NA values in the dataset\nna_values <- apply(data, 2, function(x) any(is.na(x)))\n\n# Check for empty values in the dataset\nempty_values <- apply(data, 2, function(x) any(x == \"\"))\n\n# Combine NA and empty value checks\nmissing_values <- na_values | empty_values\n\n# Print the columns with missing values\ncat(\"Columns with missing values:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nColumns with missing values:\n```\n:::\n\n```{.r .cell-code}\nprint(names(data)[missing_values])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ncharacter(0)\n```\n:::\n\n```{.r .cell-code}\n# Convert country names\ndata$Country[data$Country == \"United States\"] <- \"USA\"\ndata$Country[data$Country == \"United Kingdom\"] <- \"UK\"\n\ndata <- data %>%\n  mutate(Year = factor(Year),\n         Month = factor(Month, levels = month.name),\n         Age_Group = factor(Age_Group, levels = c(\"Youth (<25)\", \"Young Adults (25-34)\", \"Adults (35-64)\", \"Seniors (64+)\")),\n         Customer_Gender = factor(Customer_Gender, levels = c(\"M\", \"F\")),\n         Profit_Percentage = (Profit / Cost) * 100)\nhead(data)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Date\"],\"name\":[1],\"type\":[\"date\"],\"align\":[\"right\"]},{\"label\":[\"Day\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Month\"],\"name\":[3],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"Year\"],\"name\":[4],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"Customer_Age\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Age_Group\"],\"name\":[6],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"Customer_Gender\"],\"name\":[7],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"Country\"],\"name\":[8],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"State\"],\"name\":[9],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Product_Category\"],\"name\":[10],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Sub_Category\"],\"name\":[11],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Product\"],\"name\":[12],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Order_Quantity\"],\"name\":[13],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Unit_Cost\"],\"name\":[14],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Unit_Price\"],\"name\":[15],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Profit\"],\"name\":[16],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Cost\"],\"name\":[17],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Revenue\"],\"name\":[18],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Profit_Percentage\"],\"name\":[19],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"2013-11-26\",\"2\":\"26\",\"3\":\"November\",\"4\":\"2013\",\"5\":\"19\",\"6\":\"Youth (<25)\",\"7\":\"M\",\"8\":\"Canada\",\"9\":\"British Columbia\",\"10\":\"Accessories\",\"11\":\"Bike Racks\",\"12\":\"Hitch Rack - 4-Bike\",\"13\":\"8\",\"14\":\"45\",\"15\":\"120\",\"16\":\"590\",\"17\":\"360\",\"18\":\"950\",\"19\":\"163.8889\"},{\"1\":\"2015-11-26\",\"2\":\"26\",\"3\":\"November\",\"4\":\"2015\",\"5\":\"19\",\"6\":\"Youth (<25)\",\"7\":\"M\",\"8\":\"Canada\",\"9\":\"British Columbia\",\"10\":\"Accessories\",\"11\":\"Bike Racks\",\"12\":\"Hitch Rack - 4-Bike\",\"13\":\"8\",\"14\":\"45\",\"15\":\"120\",\"16\":\"590\",\"17\":\"360\",\"18\":\"950\",\"19\":\"163.8889\"},{\"1\":\"2014-03-23\",\"2\":\"23\",\"3\":\"March\",\"4\":\"2014\",\"5\":\"49\",\"6\":\"Adults (35-64)\",\"7\":\"M\",\"8\":\"Australia\",\"9\":\"New South Wales\",\"10\":\"Accessories\",\"11\":\"Bike Racks\",\"12\":\"Hitch Rack - 4-Bike\",\"13\":\"23\",\"14\":\"45\",\"15\":\"120\",\"16\":\"1366\",\"17\":\"1035\",\"18\":\"2401\",\"19\":\"131.9807\"},{\"1\":\"2016-03-23\",\"2\":\"23\",\"3\":\"March\",\"4\":\"2016\",\"5\":\"49\",\"6\":\"Adults (35-64)\",\"7\":\"M\",\"8\":\"Australia\",\"9\":\"New South Wales\",\"10\":\"Accessories\",\"11\":\"Bike Racks\",\"12\":\"Hitch Rack - 4-Bike\",\"13\":\"20\",\"14\":\"45\",\"15\":\"120\",\"16\":\"1188\",\"17\":\"900\",\"18\":\"2088\",\"19\":\"132.0000\"},{\"1\":\"2014-05-15\",\"2\":\"15\",\"3\":\"May\",\"4\":\"2014\",\"5\":\"47\",\"6\":\"Adults (35-64)\",\"7\":\"F\",\"8\":\"Australia\",\"9\":\"New South Wales\",\"10\":\"Accessories\",\"11\":\"Bike Racks\",\"12\":\"Hitch Rack - 4-Bike\",\"13\":\"4\",\"14\":\"45\",\"15\":\"120\",\"16\":\"238\",\"17\":\"180\",\"18\":\"418\",\"19\":\"132.2222\"},{\"1\":\"2016-05-15\",\"2\":\"15\",\"3\":\"May\",\"4\":\"2016\",\"5\":\"47\",\"6\":\"Adults (35-64)\",\"7\":\"F\",\"8\":\"Australia\",\"9\":\"New South Wales\",\"10\":\"Accessories\",\"11\":\"Bike Racks\",\"12\":\"Hitch Rack - 4-Bike\",\"13\":\"5\",\"14\":\"45\",\"15\":\"120\",\"16\":\"297\",\"17\":\"225\",\"18\":\"522\",\"19\":\"132.0000\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n\n## Breif description about the data:\nThe dataset used for this analysis contains information about bike sales. Each row in the dataset represents a specific bike sale transaction. The dataset includes several variables that provide insights into different aspects of the sales process and customer behavior. \n\nOne of the key variables in the dataset is \"Product,\" which represents the specific bike product sold. The dataset includes a total of [insert number of unique products] unique bike products. Each bike product has its own characteristics, such as brand, model, and type, which are not explicitly mentioned in this dataset.\n\nAnother important variable is \"Quantity,\" which indicates the number of bikes sold in each transaction. This variable allows us to analyze the sales volume and identify the most popular bike products.\n\nAdditionally, the dataset includes the \"Profit\" variable, which represents the profit generated from each bike sale. By examining the summary statistics for the \"Profit\" variable, including measures such as minimum, maximum, mean, and median, we can gain insights into the overall profitability of the bike sales.\n\nThe dataset has 18 Columns and it comprises 113,036 records spanning from January 2011 to July 2016. The customers' ages range from 17 to 87 years, with an average age of approximately 35.92 years. \n\nThese statistics provide a high-level overview of the dataset and give us a sense of the range and distribution of the \"Quantity\" and \"Profit\" variables. However, it is important to note that these summary statistics do not capture the full complexity of the dataset, and further analysis is needed to explore relationships between variables and uncover more detailed insights.\n\nBy focusing on these key variables, we can gain valuable insights into the sales performance, customer preferences, and profitability of bike sales.\nTo prepare the data for analysis, the following steps were performed:\n\n1. Converted country names: The country names were standardized to improve data consistency and facilitate \n2. visualization. \"United States\" was converted to \"USA,\" and \"United Kingdom\" was converted to \"UK.\"\n3. Modified data types: The \"Year,\" \"Month,\" \"Age_Group,\" and \"Customer_Gender\" columns were converted to factors to control the order and improve visualization.\n4. Calculated profit percentage: A new column, \"Profit_Percentage,\" was created by dividing the \"Profit\" column by the \"Cost\" column and multiplying the result by 100. This calculation provides insights into the profitability of each transaction.\n5. Removing NA and Empty values: Searched for the empty and NA values in the data and the data didn't contain any empty or NA values.\n\n\n# Visualization\n\n## Sales Performance over the Years:\n\nThe analysis explores the sales performance of different bike products over the years. By examining the trends and fluctuations in the total sales of the top-selling products, we gain insights into their popularity and identify high-performing products. This information is valuable for making data-driven decisions related to marketing strategies, inventory management, and product development. The graph visualizes the sales performance of different products over the years, highlighting the top-selling products in each year\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Top 10 selling products per year\nlibrary(RColorBrewer)\nsales_by_year <- data %>%\n  group_by(Year, Product) %>%\n  summarise(Total_Sales = sum(Revenue)) %>%\n  arrange(desc(Total_Sales)) %>%\n  group_by(Year) %>%\n  top_n(n = 10)\n\nn_colors <- n_distinct(sales_by_year$Product)\npalette1 <- brewer.pal(n_colors, name = \"Set1\")\npalette2 <- brewer.pal(n_colors, name = \"Set2\")\n# Plotting sales performance over the years for multiple products\nggplot(sales_by_year, aes(x = Year, y = Total_Sales, color = Product)) +\n  geom_line() +\n  geom_point() +\n  labs(title = \"Sales Performance of Different Products Over the Years\",\n       x = \"Year\",\n       y = \"Total Sales\",\n       color = \"Product\") +\n  theme_minimal() +\n  scale_color_manual(values = c(palette1, palette2) , name = \"Product\")\n```\n\n::: {.cell-output-display}\n![](HarshaKanakaEswarGudipudi_FinalProject_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\nThe data is grouped by the \"Year\" and \"Product\" variables using the group_by() function.The summarise() function is applied to calculate the sum of the \"Revenue\" variable, resulting in the total sales for each combination of year and product.The data is then arranged in descending order based on the \"Total_Sales\" variable using the arrange() function.Next, the data is grouped again by the \"Year\" variable using group_by() to prepare for selecting the top 10 rows for each year.Finally, the top_n() function is used to retain only the top 10 rows for each year, based on the highest total sales.\n\nThe graph above showcases the sales performance of different products over the years. Each product is represented by a unique color, brewer.pal() is used to get distint colors allowing for easy differentiation. Analyzing the sales performance over the years, we observe trends and fluctuations in the total sales of top ten products. We can see Road 150 Red,48 is the top selling bike in the year 2011, 2012 followed by Road 150 Red, 62 and Road 150 Red, 56. In the following years 2013, Road 150 Red, 62 became the top seller. The sales of Road 150 Red, 62 Skyrocketed in 2015 generating vast revenue exceeding 900 thousand usd.\n\n## Sales Distribution by Gender over years:\n\nThe analysis focuses on the sales distribution by gender over the years. By examining the proportion of sales for each gender, we can understand the gender preferences and identify any variations in sales patterns. The visualization showcases the sales distribution by gender using stacked bar charts. The segments within the bars represent the proportion of sales for each gender, allowing us to compare the sales distribution between males and females. The consistent percentage of sales between the two genders suggests a relatively equal appeal and demand for bikes among both male and female customers.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Sales distribution by gender over the years\nsales_by_gender <- data %>%\n  group_by(Year, Customer_Gender) %>%\n  summarise(Total_Sales = sum(Revenue))\n\n# Plotting sales distribution by gender over the years\nggplot(sales_by_gender, aes(x = Year, y = Total_Sales, fill = Customer_Gender)) +\n  geom_bar(stat = \"identity\", position = \"stack\") +\n  labs(title = \"Sales Distribution by Gender Over the Years\",\n       x = \"Year\",\n       y = \"Total Sales\",\n       fill = \"Customer Gender\") +\n  theme_minimal() +\n  scale_fill_manual(values = c(\"M\" = \"blue\", \"F\" = \"pink\"))\n```\n\n::: {.cell-output-display}\n![](HarshaKanakaEswarGudipudi_FinalProject_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\nIn the code above, we calculate the total sales for each gender and year by grouping the data and creating Total_sales by summing up the Revenue. Then, we plot the sales distribution using a stacked bar chart, where each bar represents the total sales for each year, and the segments within the bars represent the sales distribution by gender.\n\n::: {.cell}\n\n```{.r .cell-code}\n# Function to create pie chart\ncreate_pie_chart <- function(year) {\n  sales_by_gender_year <- sales_by_gender %>%\n    filter(Year == year)\n\n  pie_chart <- ggplot(sales_by_gender_year, aes(x = \"\", y = Total_Sales, fill = Customer_Gender)) +\n    geom_bar(stat = \"identity\", width = 1) +\n    coord_polar(\"y\", start = 0) +\n    labs(fill = \"Customer Gender\") +\n    theme_void() +\n    theme(legend.position = \"bottom\") +\n    geom_text(aes(label = scales::percent(Total_Sales / sum(Total_Sales))),\n              position = position_stack(vjust = 0.5)) +\n    ggtitle(paste(\"Year:\", year))\n\n  return(pie_chart)\n}\n\n# Create a list of pie charts for each year\npie_charts <- lapply(unique(sales_by_gender$Year), create_pie_chart)\n\n# Combine pie charts into a grid\ngrid <- grid.arrange(grobs = pie_charts, ncol = 3, top = \"Sales Distribution by Gender Over the Years\")\n```\n\n::: {.cell-output-display}\n![](HarshaKanakaEswarGudipudi_FinalProject_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\nIn the code above, we define a function create_pie_chart that takes a year as input and creates a pie chart representing the sales distribution by gender for that specific year.We then use lapply to apply the create_pie_chart function to each unique year in the sales_by_gender dataset, resulting in a list of pie charts for each year. Finally, we use the grid.arrange function from the gridExtra package to combine the pie charts into a grid layout with three columns (adjust the ncol parameter as desired). The resulting grid is stored in the grid variable.\n\nAs we can see from the above grid of pie charts that the percentage of sales each year is almost the same for both males and females, it implies that there is a relatively equal distribution of sales between the two gender groups. This can suggest that the bikeshas similar appeal and demand among both male and female customers.\n\n## Profitability Analysis by Month:\nThe analysis delves into the profitability of bike sales by month. By calculating the average profit percentage for each month, we can identify any seasonal patterns or fluctuations in profitability. The visualization presents the average profitability over months, providing insights into the overall profitability trends throughout the year. Analyzing the graph helps us understand if there are any specific months that contribute significantly to profitability or if bike sales maintain consistent profitability across all months.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate average profit percentage by month\nprofitability_month <- data %>% \n  group_by(Month) %>%\n  summarise(Avg_Profit_Percentage = sum(Profit) / sum(Cost)*100)\n\n# Plot average profit percentage over months\nmonth_plot <- ggplot(profitability_month, aes(x = Month, y = Avg_Profit_Percentage)) +\n  geom_point() +\n  labs(title = \"Average Profitability Over Months\",\n       x = \"Month\",\n       y = \"Average Profit Percentage\") +\n  theme_minimal()\n\n# Display the plot\nmonth_plot\n```\n\n::: {.cell-output-display}\n![](HarshaKanakaEswarGudipudi_FinalProject_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Plot average profit percentage over months\nmonth_plot <- ggplot(profitability_month, aes(x = Month, y = Avg_Profit_Percentage)) +\n  geom_bar(stat = \"identity\", fill = \"steelblue\") +\n  labs(title = \"Average Profitability Over Months\",\n       x = \"Month\",\n       y = \"Average Profit Percentage\") +\n  theme_minimal()\n\n# Display the plot\nmonth_plot\n```\n\n::: {.cell-output-display}\n![](HarshaKanakaEswarGudipudi_FinalProject_files/figure-html/unnamed-chunk-7-2.png){width=672}\n:::\n:::\n\nIn the code above, we group by month to calculate the average profit percentage for each month using summarise() function. Then, we create geom_bar() to create a bar plot to visualize the trend of average profit percentage over months. It can be seen that bike sales in overall are consistent around 60 percent profit for each month. Which implies that the bike sales are not largely effected by the month.\n\n\n## Profitability Analysis among the countries:\nThe analysis investigates the profitability of bike sales among different countries. By calculating the average profitability for each country, we can identify variations in profitability levels and potentially uncover factors that contribute to these differences. The visualization utilizes a world map to represent the profitability by country. Each country is shaded according to its average profitability, allowing for easy identification of regions with higher or lower profitability. This information helps in understanding the geographic distribution of profitability and making informed decisions related to market targeting and expansion strategies.\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate average profitability by country\nprofitability_country <- data %>%\n  group_by(Country) %>%\n  summarise(Avg_Profitability = sum(Profit)/sum(Cost)*100)\n\n# Plot world map based on profitability\nworld_map <- map_data(\"world\")\n\nworld_plot <- ggplot() +\n  geom_map(data = world_map, map = world_map,\n           aes(x = long, y = lat, map_id = region),\n           fill = \"lightgray\", color = \"black\", size = 0.2) +\n  geom_map(data = profitability_country, map = world_map,\n           aes(fill = Avg_Profitability, map_id = Country),\n           color = \"black\", size = 0.2) +\n  labs(title = \"Profitability by Country\",\n       fill = \"Profitability\") +\n  scale_fill_gradient(low = \"lightblue\", high = \"darkblue\") +\n  theme_minimal()\n\n# Display the world map\nworld_plot\n```\n\n::: {.cell-output-display}\n![](HarshaKanakaEswarGudipudi_FinalProject_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\nIn this code, we first calculate the average profitability by country using summarise() function. Then, we use the map_data() function from the maps package to obtain the map data for the world. The geom_map() function is used twice to plot the world map: first to create a base map with light gray color, and then to overlay the profitability data using the fill aesthetic to represent the average profitability by country.\n\nBy executing this code, you will see a world map that visualizes the profitability by country. Each country is shaded according to its average profitability, with a gradient scale from light blue to dark blue indicating the profitability levels. This map provides an overview of the profitability distribution across different countries, allowing for easy identification of regions with higher or lower profitability.\n\nOn an average over the years we can see the Canada is having the highest profitability above 80 percent standing in the top while Australia making the least profitability around 50 percent. United states stands in the second place followed by United Kingdom and France.\n\n\n## Multivariate Analysis: Age Group:\nThe analysis explores the relationship between age group and bike sales profitability and quantity. By grouping the data based on age groups, we calculate the average profitability and total quantity for each group. The visualization presents a scatter plot that represents the multivariate analysis, with the x-axis indicating the average profitability and the y-axis indicating the total quantity. Each data point is color-coded based on the age group. Analyzing the scatter plot helps us understand any patterns or correlations between age group, profitability, and quantity. This information can be useful in tailoring marketing strategies and product offerings to specific age groups and maximizing profitability.\n\n::: {.cell}\n\n```{.r .cell-code}\n# Multivariate analysis using Age_Group\nage_group_analysis <- data %>%\n  group_by(Age_Group) %>%\n  summarise(Avg_Profitability = sum(Profit)/sum(Cost)*100,\n            Total_Quantity = sum(Order_Quantity))\n\n# Plotting multivariate analysis\nage_group_plot <- ggplot(age_group_analysis, aes(x = Avg_Profitability, y = Total_Quantity, color = Age_Group)) +\n  geom_point(size = 3) +\n  labs(title = \"Multivariate Analysis: Age Group\",\n       x = \"Average Profitability\",\n       y = \"Total Quantity\",\n       color = \"Age Group\") +\n  theme_minimal()\n\n# Display the plot\nage_group_plot\n```\n\n::: {.cell-output-display}\n![](HarshaKanakaEswarGudipudi_FinalProject_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\nIn this code, we use the group_by() for each age group and summarise() to calculate the average profitability (Avg_Profitability) and the total quantity (Total_Quantity). Then, we use ggplot() and geom_point() to create a scatter plot where the x-axis represents the average profitability, the y-axis represents the total quantity, and the points are colored based on the age group. By executing this code, we will see a scatter plot that illustrates the multivariate analysis using the \"Age_Group\" variable. Each point represents an age group, and its position on the plot shows the average profitability and total quantity associated with that age group. This analysis helps identify any patterns or relationships between age groups and their impact on profitability and quantity.\n\nwe can conclude form the plot that the order quantity is highest in the Adults aged between 35-64 followed by young adults between 25-34. The sales of bikes is least for the seniors above 64 age. Even though sales are less profitability of the seniors is high suggesting that seniors purchased costly bikes or bikes where profit margin is high.\n\n\n\n\n## Mean Profit based on Age Group:\n\nThe analysis examines the mean profit generated by bike sales across different countries and age groups. By calculating the average profit for each country and age group, we gain insights into the profitability levels based on these two variables. The visualization presents the mean profit by country and age group using a heatmap. Each cell in the heatmap represents the average profit for a specific combination of country and age group. The color intensity of each cell indicates the level of profitability, allowing for easy comparison and identification of countries and age groups with higher or lower mean profits. This information helps in understanding the profitability dynamics across different countries and age groups, enabling targeted marketing and business strategies.\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(reshape2)\nlibrary(ggplot2)\n\n# Reshape data for heatmap analysis\nheatmap_data <- data %>%\n  select(Country, Age_Group, Profit)\n\nheatmap_data <- heatmap_data %>%\n  dcast(Country ~ Age_Group, value.var = \"Profit\", mean)\n\n# Create a heatmap to analyze Profit by Country and Age Group\nheatmap_analysis <- ggplot(melt(heatmap_data, id.vars = \"Country\"), \n                           aes(x = variable, y = Country, fill = value)) +\n  geom_tile() +\n  labs(title = \"Profit by Country and Age Group (Heatmap)\",\n       x = \"Age Group\",\n       y = \"Country\",\n       fill = \"Profit\")\n\n# Display the heatmap analysis\nheatmap_analysis\n```\n\n::: {.cell-output-display}\n![](HarshaKanakaEswarGudipudi_FinalProject_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\nThis code reshapes the data and creates a heatmap to analyze the Profit by Country and Age Group. The \"heatmap_data\" dataframe is created by selecting the \"Country,\" \"Age_Group,\" and \"Profit\" columns from the \"data\" dataset. The \"heatmap_data\" dataframe is further modified using the dcast() function from the \"reshape2\" library. The dcast() function reshapes the data, pivoting it to have \"Country\" as rows, \"Age_Group\" as columns, and the average \"Profit\" as the values in the cells.The resulting reshaped dataframe, \"heatmap_data,\" is then used to create a new ggplot object called \"heatmap_analysis.\" The heatmap provides a visual representation of the Profit values per unit, with colors indicating the intensity of Profit for different combinations of Country and Age Group.\n\n\n\n## Monthly Sales across Years:\nThe analysis focuses on tracking the monthly sales performance over the years. By examining the sales figures for each month, we can identify any seasonal patterns, trends, or fluctuations in sales. The visualization presents the monthly sales data using a bar graph, where each bar represents the sales for a specific month. The height of each bar indicates the sales amount, allowing for easy comparison between different months and years. Analyzing the bar graph helps us understand the overall sales trends over time and can provide insights for forecasting future sales, identifying peak periods, and optimizing inventory management.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate monthly sales\nmonthly_sales <- data %>%\n  group_by(Month, Year) %>%\n  summarise(Total_Sales = sum(Revenue)) %>% \n  arrange(desc(Month))\n\n# Create a bar plot for monthly sales\nmonthly_sales_plot <- ggplot(monthly_sales, aes(x = Month, y = Total_Sales, fill = Year)) +\n  geom_bar(stat = \"identity\", position = \"dodge\") +\n  labs(title = \"Monthly Sales\",\n       x = \"Month\",\n       y = \"Total Sales\",\n       fill = \"Year\") +\n  theme_minimal()+\n  scale_x_discrete(labels = function(x) substr(x, 1, 3))\n\n# Display the monthly sales bar plot\nmonthly_sales_plot\n```\n\n::: {.cell-output-display}\n![](HarshaKanakaEswarGudipudi_FinalProject_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\nBy grouping the data by month and year and summarizing the revenue, the code generates a new data frame that provides the total sales for each unique combination of month and year in the original dataset. In the  plot, I used the substr() function within the scale_x_discrete() function to modify the x-axis labels. The substr(x, 1, 3) extracts the first three letters of each label, effectively truncating the month names. A bar plot is then created to visualize the monthly sales, with each bar representing the total sales for a specific month and year. The bars are color-coded based on the year, providing a visual comparison between different years.\nIn 2016 Janaury to June is the peak selling season for the bikes on contrast in 2015 the sales are peak during July to August. In 2011 the sales are same overall through January to December and it is the least sales year out of all the years from 2011 to 2016.\n\n\n\n## Seasonal sales based on country:\n\nThe analysis examines the seasonal sales patterns of the top 3 bike products across different countries. By analyzing the sales data for each season and country, we can identify variations in demand and popularity throughout the year. The visualization utilizes a boxplot to represent the seasonal sales for each country and bike product. The boxplot provides insights into the distribution of sales, including the median, quartiles, and any outliers. By comparing the boxplots across countries and bikes, we can identify countries with high or low sales during specific seasons for the top 3 bikes. \n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter the data for the top 3 bikes based on overall sales\ntop3_bikes <- data %>%\n  group_by(Product) %>%\n  summarise(Total_Sales = sum(Revenue)) %>%\n  top_n(3, Total_Sales) %>%\n  select(Product)\n\n# Create a new column for seasons based on the date\ndata$Season <- ifelse(format(data$Date, \"%m\") %in% c(\"12\", \"01\", \"02\"), \"Winter\",\n                      ifelse(format(data$Date, \"%m\") %in% c(\"03\", \"04\", \"05\"), \"Spring\",\n                             ifelse(format(data$Date, \"%m\") %in% c(\"06\", \"07\", \"08\"), \"Summer\", \"Autumn\")))\n\n# Group the data by seasons, country, and bike product\ngrouped_data <- data %>%\n  filter(Product %in% top3_bikes$Product) %>%\n  group_by(Season, Country, Product) %>%\n  summarise(Total_Revenue = sum(Revenue))\n\n# Filter the data to include only the top 3 bikes based on total revenue\ntop3_grouped_data <- grouped_data %>%\n  group_by(Season, Country) %>%\n  arrange(desc(Total_Revenue)) %>%\n  slice(1:3)\n\n# Create a box plot to visualize the revenue distribution for each season, country, and bike\nboxplot <- ggplot(top3_grouped_data, aes(x = Season, y = Total_Revenue, fill = Country)) +\n  geom_boxplot() +\n  labs(title = \"Revenue Distribution for Top 3 Bikes by Season and Country\",\n       x = \"Season\",\n       y = \"Total Revenue\",\n       fill = \"Country\") +\n  theme_minimal()\n\n# Display the box plot\nboxplot\n```\n\n::: {.cell-output-display}\n![](HarshaKanakaEswarGudipudi_FinalProject_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\nThe format(data$Date, \"%m\") extracts the month from the \"Date\" column using the format() function with the \"%m\" format specifier. This will return a two-digit representation of the month (e.g., \"01\" for January, \"02\" for February, etc.). %in% c(\"12\", \"01\", \"02\") checks if the extracted month value is equal to any of the values in the vector \"c(\"12\", \"01\", \"02\")\". If it matches any of these values, it indicates that the month falls within the winter season. similarly for other seasons used ifelse() statement.\n\nAfter the seasons extracted from the date column, created a box plot to visualize the revenue distribution across different seasons. Each box plot represents the revenue distribution for a specific season, providing insights into the seasonal variations in sales. In each box plot top 3 sales are considered for the season showing how closely the competition is present in the market. In Australia, If we see in the winter season top bike in the sales is has no close competition with others. For the Canada there is always a close competition in the sales.\n\n\n# Conclusion\n\nIn this analysis, we explored a comprehensive dataset on bike sales collected by Global Bike Inc. The dataset provided valuable insights into sales transactions, customer demographics, and profitability across multiple countries. By addressing a set of research questions, we gained insights into the sales performance, customer preferences, and profitability patterns within the bike industry.\n\nBased on our analysis, we found the following key findings:\n\n1. **Top-selling Bike Models and Sales Trends**: We identified the top-selling bike models and observed their sales trends over the years. The Road 150 Red, 62 model emerged as a consistent top performer, generating significant revenue in multiple years.\n\n2. **Gender Distribution and Preferences**: The analysis of gender distribution among bike customers revealed a relatively equal distribution of sales between male and female customers. This suggests that the bike products have similar appeal and demand among both genders.\n\n3. **Profitability Variation by Month**: We examined the profitability variation by month and found that bike sales maintained a consistent profitability level around 60 percent throughout the year. This indicates that bike sales are not significantly influenced by the month.\n\n4. **Profitability Variation Among Countries**: We analyzed the profitability across different countries and identified variations in profitability levels. Canada stood out as the highest-profitability country, while Australia had the lowest profitability. The United States, the United Kingdom, and France also exhibited notable profitability levels.\n\n5. **Age-specific Preferences**: The multivariate analysis revealed insights into age-specific preferences. We observed that the youth and young adult age groups showed higher average profitability, indicating potential opportunities for targeted marketing and product development.\n\nThese findings provide valuable insights for decision-making processes related to marketing strategies, inventory management, and product development within the bike industry. By understanding the top-selling models, gender distribution, profitability patterns, and age-specific preferences, businesses can make data-driven decisions to improve performance and enhance customer satisfaction.\n\nIt is important to note that this analysis is based on the available dataset and its limitations. Further research and analysis can be conducted to delve deeper into specific aspects of bike sales, such as customer segmentation, marketing campaign effectiveness, and competitive analysis.\n\nOverall, this analysis offers a comprehensive understanding of bike sales, customer preferences, and profitability patterns, enabling businesses to make informed decisions and drive growth in the bike industry.\n\n\n# Bibliography\n\nBike sales Dataset (2011-2016) - https://www.kaggle.com/datasets/sadiqshah/bike-sales-in-europe?datasetId=889310&language=R\n\nR Language as programming language\n\nWickham, H., & Grolemund, G. (2016). *R for data science: Visualize, model, transform, tidy, and import data*. OReilly Media.\n\nThe R Graph Gallery-https://r-graph-gallery.com/\\\n",
    "supporting": [
      "HarshaKanakaEswarGudipudi_FinalProject_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}