{
  "hash": "12a63a5f42da537af97a648c8a8e7279",
  "result": {
    "markdown": "---\ntitle: \"Challenge 2 submission\"\nauthor: \"Cameron Needels\"\ndesription: \"Data wrangling: using filter(), dfSummary(), and summarise()\"\ndate: \"03/1/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_2\n  - railroads\n  - CamNeedels\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(summarytools)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n\n## Data set used\n\nI used the railroads dataset from 2012. Here's what I found!\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#creating the dataset while also practicing permanently changing one of the variable names at the top\n\nlibrary(readr)\nrailroads <- read.csv(\"B:/Needels/Documents/DACCS 601/601_Spring_2023/posts/_data/railroad_2012_clean_county.csv\")\nrailroads <- rename(railroads, counties = county)\nrailroads\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     state             counties total_employees\n1       AE                  APO               2\n2       AK            ANCHORAGE               7\n3       AK FAIRBANKS NORTH STAR               2\n4       AK               JUNEAU               3\n5       AK    MATANUSKA-SUSITNA               2\n6       AK                SITKA               1\n7       AK SKAGWAY MUNICIPALITY              88\n8       AL              AUTAUGA             102\n9       AL              BALDWIN             143\n10      AL              BARBOUR               1\n11      AL                 BIBB              25\n12      AL               BLOUNT             154\n13      AL              BULLOCK              13\n14      AL               BUTLER              29\n15      AL              CALHOUN              45\n16      AL             CHAMBERS              13\n17      AL             CHEROKEE               9\n18      AL              CHILTON              72\n19      AL              CHOCTAW               7\n20      AL               CLARKE              26\n21      AL                 CLAY              10\n22      AL             CLEBURNE               7\n23      AL               COFFEE              14\n24      AL              COLBERT             199\n25      AL              CONECUH              11\n26      AL                COOSA               5\n27      AL            COVINGTON              12\n28      AL             CRENSHAW               5\n29      AL              CULLMAN             129\n30      AL                 DALE              11\n31      AL               DALLAS             122\n32      AL               DEKALB              33\n33      AL               ELMORE             116\n34      AL             ESCAMBIA              47\n35      AL               ETOWAH              78\n36      AL              FAYETTE               3\n37      AL             FRANKLIN              40\n38      AL               GENEVA               8\n39      AL               GREENE               7\n40      AL                 HALE               8\n41      AL                HENRY               1\n42      AL              HOUSTON              46\n43      AL              JACKSON              55\n44      AL            JEFFERSON             990\n45      AL                LAMAR              25\n46      AL           LAUDERDALE             117\n47      AL             LAWRENCE              11\n48      AL                  LEE              46\n49      AL            LIMESTONE               7\n50      AL              LOWNDES               7\n51      AL                MACON               6\n52      AL              MADISON              29\n53      AL              MARENGO              16\n54      AL               MARION              17\n55      AL             MARSHALL              29\n56      AL               MOBILE             331\n57      AL               MONROE              43\n58      AL           MONTGOMERY             102\n59      AL               MORGAN              42\n60      AL                PERRY               4\n61      AL              PICKENS              24\n62      AL                 PIKE              19\n63      AL             RANDOLPH              39\n64      AL              RUSSELL              38\n65      AL               SHELBY             158\n66      AL             ST CLAIR             162\n67      AL               SUMTER               9\n68      AL            TALLADEGA              42\n69      AL           TALLAPOOSA              19\n70      AL           TUSCALOOSA              60\n71      AL               WALKER             192\n72      AL           WASHINGTON              11\n73      AL               WILCOX              11\n74      AL              WINSTON              45\n75      AP                  APO               1\n76      AR             ARKANSAS              11\n77      AR               ASHLEY              18\n78      AR               BAXTER              25\n79      AR               BENTON              35\n80      AR                BOONE               5\n81      AR              BRADLEY               8\n82      AR              CALHOUN               5\n83      AR               CHICOT               3\n84      AR                CLARK              40\n85      AR                 CLAY              13\n86      AR             CLEBURNE               8\n87      AR            CLEVELAND              79\n88      AR             COLUMBIA               5\n89      AR               CONWAY              19\n90      AR            CRAIGHEAD              61\n91      AR             CRAWFORD              55\n92      AR           CRITTENDEN              48\n93      AR                CROSS              30\n94      AR               DALLAS              12\n95      AR                DESHA              15\n96      AR                 DREW              34\n97      AR             FAULKNER             289\n98      AR             FRANKLIN               5\n99      AR               FULTON              54\n100     AR              GARLAND              68\n101     AR                GRANT             167\n102     AR               GREENE              15\n103     AR            HEMPSTEAD               6\n104     AR           HOT SPRING              79\n105     AR               HOWARD              37\n106     AR         INDEPENDENCE              32\n107     AR                IZARD               4\n108     AR              JACKSON              13\n109     AR            JEFFERSON             361\n110     AR              JOHNSON               7\n111     AR            LAFAYETTE              11\n112     AR             LAWRENCE              32\n113     AR                  LEE               3\n114     AR              LINCOLN              54\n115     AR         LITTLE RIVER              22\n116     AR                LOGAN               4\n117     AR               LONOKE             330\n118     AR              MADISON               7\n119     AR               MARION               8\n120     AR               MILLER              10\n121     AR          MISSISSIPPI              18\n122     AR               MONROE               7\n123     AR           MONTGOMERY               2\n124     AR               NEVADA              15\n125     AR               NEWTON               1\n126     AR             OUACHITA              15\n127     AR                PERRY              22\n128     AR             PHILLIPS              11\n129     AR                 PIKE              10\n130     AR             POINSETT               4\n131     AR                 POLK              17\n132     AR                 POPE              31\n133     AR              PRAIRIE               5\n134     AR              PULASKI             972\n135     AR             RANDOLPH              19\n136     AR               SALINE             262\n137     AR                SCOTT               3\n138     AR            SEBASTIAN              43\n139     AR               SEVIER              50\n140     AR                SHARP              20\n141     AR           ST FRANCIS              16\n142     AR                STONE               2\n143     AR                UNION              20\n144     AR            VAN BUREN               2\n145     AR           WASHINGTON              46\n146     AR                WHITE             102\n147     AR                 YELL               9\n148     AZ               APACHE             270\n149     AZ              COCHISE              60\n150     AZ             COCONINO             268\n151     AZ                 GILA              37\n152     AZ               GRAHAM              48\n153     AZ             GREENLEE               3\n154     AZ               LA PAZ              10\n155     AZ             MARICOPA             462\n156     AZ               MOHAVE             407\n157     AZ               NAVAJO             510\n158     AZ                 PIMA             749\n159     AZ                PINAL             154\n160     AZ           SANTA CRUZ              18\n161     AZ              YAVAPAI              63\n162     AZ                 YUMA              94\n163     CA              ALAMEDA             346\n164     CA               AMADOR               9\n165     CA                BUTTE              69\n166     CA            CALAVERAS              30\n167     CA               COLUSA               2\n168     CA         CONTRA COSTA             348\n169     CA            EL DORADO             103\n170     CA               FRESNO             341\n171     CA                GLENN               4\n172     CA             HUMBOLDT               2\n173     CA             IMPERIAL              65\n174     CA                 KERN             500\n175     CA                KINGS              21\n176     CA                 LAKE               2\n177     CA               LASSEN              14\n178     CA          LOS ANGELES            2545\n179     CA               MADERA              39\n180     CA                MARIN              12\n181     CA             MARIPOSA               4\n182     CA            MENDOCINO               6\n183     CA               MERCED              59\n184     CA                MODOC               3\n185     CA                 MONO               1\n186     CA             MONTEREY              29\n187     CA                 NAPA              17\n188     CA               NEVADA              36\n189     CA               ORANGE             460\n190     CA               PLACER             539\n191     CA               PLUMAS              84\n192     CA            RIVERSIDE            1567\n193     CA           SACRAMENTO             738\n194     CA           SAN BENITO              13\n195     CA       SAN BERNARDINO            2888\n196     CA            SAN DIEGO             206\n197     CA        SAN FRANCISCO              61\n198     CA          SAN JOAQUIN             474\n199     CA      SAN LUIS OBISPO              98\n200     CA            SAN MATEO              80\n201     CA        SANTA BARBARA              36\n202     CA          SANTA CLARA             244\n203     CA           SANTA CRUZ              44\n204     CA               SHASTA              69\n205     CA               SIERRA               2\n206     CA             SISKIYOU              83\n207     CA               SOLANO             221\n208     CA               SONOMA              38\n209     CA           STANISLAUS             195\n210     CA               SUTTER              54\n211     CA               TEHAMA              10\n212     CA              TRINITY               2\n213     CA               TULARE              97\n214     CA             TUOLUMNE               9\n215     CA              VENTURA              68\n216     CA                 YOLO              62\n217     CA                 YUBA              88\n218     CO                ADAMS             553\n219     CO              ALAMOSA              10\n220     CO             ARAPAHOE             128\n221     CO            ARCHULETA               2\n222     CO                 BACA               3\n223     CO                 BENT               1\n224     CO              BOULDER              71\n225     CO           BROOMFIELD              42\n226     CO              CHAFFEE               6\n227     CO             CHEYENNE               1\n228     CO          CLEAR CREEK               2\n229     CO              CONEJOS               6\n230     CO             COSTILLA               1\n231     CO              CROWLEY               7\n232     CO               CUSTER               3\n233     CO                DELTA              16\n234     CO               DENVER             503\n235     CO              DOLORES               1\n236     CO              DOUGLAS             112\n237     CO                EAGLE              10\n238     CO              EL PASO             129\n239     CO               ELBERT              10\n240     CO              FREMONT              28\n241     CO             GARFIELD              13\n242     CO               GILPIN               5\n243     CO                GRAND              10\n244     CO             GUNNISON               1\n245     CO             HUERFANO              10\n246     CO            JEFFERSON             267\n247     CO                KIOWA               3\n248     CO           KIT CARSON               2\n249     CO             LA PLATA               1\n250     CO                 LAKE               2\n251     CO              LARIMER             159\n252     CO           LAS ANIMAS              77\n253     CO              LINCOLN               5\n254     CO                LOGAN             137\n255     CO                 MESA             252\n256     CO               MOFFAT               6\n257     CO            MONTEZUMA               2\n258     CO             MONTROSE              10\n259     CO               MORGAN              34\n260     CO                OTERO             141\n261     CO                 PARK              12\n262     CO             PHILLIPS               4\n263     CO               PITKIN               1\n264     CO              PROWERS              26\n265     CO               PUEBLO             526\n266     CO           RIO GRANDE              10\n267     CO                ROUTT              30\n268     CO             SAGUACHE               2\n269     CO             SEDGWICK              16\n270     CO               SUMMIT               6\n271     CO               TELLER               6\n272     CO           WASHINGTON               3\n273     CO                 WELD             223\n274     CO                 YUMA               3\n275     CT            FAIRFIELD             486\n276     CT             HARTFORD             113\n277     CT           LITCHFIELD              57\n278     CT            MIDDLESEX             137\n279     CT            NEW HAVEN            1561\n280     CT           NEW LONDON             146\n281     CT              TOLLAND              26\n282     CT              WINDHAM              66\n283     DC        WASHINGTON DC             279\n284     DE                 KENT             158\n285     DE           NEW CASTLE            1275\n286     DE               SUSSEX              62\n287     FL              ALACHUA              22\n288     FL                BAKER              81\n289     FL                  BAY              45\n290     FL             BRADFORD              20\n291     FL              BREVARD              33\n292     FL              BROWARD             294\n293     FL              CALHOUN               1\n294     FL            CHARLOTTE              10\n295     FL               CITRUS              23\n296     FL                 CLAY             636\n297     FL              COLLIER              14\n298     FL             COLUMBIA              35\n299     FL               DESOTO               9\n300     FL                DIXIE               2\n301     FL                DUVAL            3073\n302     FL             ESCAMBIA             124\n303     FL              FLAGLER              29\n304     FL             FRANKLIN               2\n305     FL              GADSDEN               5\n306     FL            GILCHRIST               1\n307     FL               GLADES               5\n308     FL                 GULF               6\n309     FL             HAMILTON              11\n310     FL               HARDEE               2\n311     FL               HENDRY               1\n312     FL             HERNANDO              30\n313     FL            HIGHLANDS              15\n314     FL         HILLSBOROUGH             387\n315     FL               HOLMES               6\n316     FL         INDIAN RIVER              12\n317     FL              JACKSON              12\n318     FL            JEFFERSON               3\n319     FL            LAFAYETTE               5\n320     FL                 LAKE              77\n321     FL                  LEE              43\n322     FL                 LEON              21\n323     FL                 LEVY               6\n324     FL              LIBERTY               1\n325     FL              MADISON               1\n326     FL              MANATEE              23\n327     FL               MARION              48\n328     FL               MARTIN               9\n329     FL           MIAMI-DADE             346\n330     FL               MONROE               7\n331     FL               NASSAU             242\n332     FL             OKALOOSA               6\n333     FL           OKEECHOBEE              12\n334     FL               ORANGE             101\n335     FL              OSCEOLA              30\n336     FL           PALM BEACH             155\n337     FL                PASCO              71\n338     FL             PINELLAS              73\n339     FL                 POLK             238\n340     FL               PUTNAM              34\n341     FL           SANTA ROSA              48\n342     FL             SARASOTA              18\n343     FL             SEMINOLE              92\n344     FL             ST JOHNS             449\n345     FL             ST LUCIE              56\n346     FL               SUMTER              36\n347     FL             SUWANNEE              11\n348     FL               TAYLOR               5\n349     FL                UNION              11\n350     FL              VOLUSIA             175\n351     FL              WAKULLA               4\n352     FL               WALTON               3\n353     FL           WASHINGTON              13\n354     GA              APPLING              24\n355     GA             ATKINSON              22\n356     GA                BACON              56\n357     GA              BALDWIN              11\n358     GA                BANKS               1\n359     GA               BARROW              32\n360     GA               BARTOW             114\n361     GA             BEN HILL             120\n362     GA              BERRIEN              12\n363     GA                 BIBB             304\n364     GA             BLECKLEY              17\n365     GA             BRANTLEY             112\n366     GA               BROOKS               4\n367     GA                BRYAN              95\n368     GA              BULLOCH              42\n369     GA                BURKE              17\n370     GA                BUTTS              23\n371     GA              CALHOUN               3\n372     GA               CAMDEN              41\n373     GA              CANDLER               4\n374     GA              CARROLL             130\n375     GA              CATOOSA             120\n376     GA             CHARLTON              35\n377     GA              CHATHAM             281\n378     GA        CHATTAHOOCHEE               4\n379     GA            CHATTOOGA               4\n380     GA             CHEROKEE             129\n381     GA               CLARKE               9\n382     GA                 CLAY               2\n383     GA              CLAYTON             194\n384     GA               CLINCH              16\n385     GA                 COBB             661\n386     GA               COFFEE              85\n387     GA             COLQUITT               5\n388     GA             COLUMBIA              89\n389     GA                 COOK               4\n390     GA               COWETA             116\n391     GA             CRAWFORD               6\n392     GA                CRISP              12\n393     GA                 DADE              31\n394     GA               DAWSON               3\n395     GA              DECATUR              11\n396     GA               DEKALB             315\n397     GA                DODGE               9\n398     GA                DOOLY               6\n399     GA            DOUGHERTY              43\n400     GA              DOUGLAS             282\n401     GA                EARLY               6\n402     GA            EFFINGHAM             130\n403     GA               ELBERT               1\n404     GA              EMANUEL              33\n405     GA                EVANS               5\n406     GA               FANNIN               9\n407     GA              FAYETTE             177\n408     GA                FLOYD              31\n409     GA              FORSYTH              40\n410     GA             FRANKLIN               6\n411     GA               FULTON             878\n412     GA               GILMER               6\n413     GA             GLASCOCK               1\n414     GA                GLYNN              40\n415     GA               GORDON              33\n416     GA                GRADY               9\n417     GA               GREENE               5\n418     GA             GWINNETT             372\n419     GA            HABERSHAM              12\n420     GA                 HALL              55\n421     GA              HANCOCK               4\n422     GA             HARALSON              21\n423     GA               HARRIS              37\n424     GA                 HART              10\n425     GA                HEARD               4\n426     GA                HENRY             269\n427     GA              HOUSTON              89\n428     GA                IRWIN              24\n429     GA              JACKSON              38\n430     GA               JASPER              13\n431     GA           JEFF DAVIS              12\n432     GA            JEFFERSON              11\n433     GA              JENKINS              17\n434     GA              JOHNSON               4\n435     GA                JONES              42\n436     GA                LAMAR              19\n437     GA               LANIER              10\n438     GA              LAURENS              11\n439     GA                  LEE              22\n440     GA              LIBERTY              28\n441     GA              LINCOLN              15\n442     GA                 LONG               4\n443     GA              LOWNDES              87\n444     GA              LUMPKIN               2\n445     GA                MACON               4\n446     GA              MADISON               6\n447     GA               MARION               7\n448     GA             MCDUFFIE              32\n449     GA             MCINTOSH               7\n450     GA           MERIWETHER              78\n451     GA               MILLER               2\n452     GA             MITCHELL               6\n453     GA               MONROE              63\n454     GA           MONTGOMERY               4\n455     GA               MORGAN               2\n456     GA               MURRAY               6\n457     GA             MUSCOGEE              84\n458     GA               NEWTON               9\n459     GA               OCONEE               7\n460     GA           OGLETHORPE               3\n461     GA             PAULDING             200\n462     GA                PEACH              47\n463     GA              PICKENS              16\n464     GA               PIERCE             271\n465     GA                 PIKE              17\n466     GA                 POLK              65\n467     GA              PULASKI               3\n468     GA               PUTNAM              10\n469     GA                RABUN               4\n470     GA             RANDOLPH              12\n471     GA             RICHMOND             206\n472     GA             ROCKDALE              60\n473     GA               SCHLEY               7\n474     GA              SCREVEN               7\n475     GA             SEMINOLE               2\n476     GA             SPALDING              33\n477     GA             STEPHENS               8\n478     GA              STEWART               3\n479     GA               SUMTER               9\n480     GA               TALBOT              13\n481     GA             TATTNALL               4\n482     GA               TAYLOR              11\n483     GA              TELFAIR               5\n484     GA              TERRELL               9\n485     GA               THOMAS              30\n486     GA                 TIFT              13\n487     GA               TOOMBS              28\n488     GA             TREUTLEN               1\n489     GA                TROUP              53\n490     GA               TURNER               7\n491     GA               TWIGGS              12\n492     GA                UPSON              18\n493     GA               WALKER              54\n494     GA               WALTON             117\n495     GA                 WARE             413\n496     GA               WARREN               8\n497     GA           WASHINGTON              34\n498     GA                WAYNE              94\n499     GA              WEBSTER               3\n500     GA                WHITE               3\n501     GA            WHITFIELD              22\n502     GA               WILCOX              15\n503     GA               WILKES               7\n504     GA            WILKINSON              22\n505     GA                WORTH              11\n506     HI               HAWAII               1\n507     HI             HONOLULU               2\n508     HI                KAUAI               1\n509     IA                ADAIR               5\n510     IA                ADAMS               7\n511     IA            ALLAMAKEE              18\n512     IA            APPANOOSE              13\n513     IA              AUDUBON               1\n514     IA               BENTON              39\n515     IA           BLACK HAWK             116\n516     IA                BOONE             206\n517     IA               BREMER              17\n518     IA             BUCHANAN              35\n519     IA          BUENA VISTA               2\n520     IA               BUTLER              23\n521     IA              CALHOUN              16\n522     IA              CARROLL              38\n523     IA                 CASS              13\n524     IA                CEDAR              19\n525     IA          CERRO GORDO             157\n526     IA             CHEROKEE               2\n527     IA            CHICKASAW               7\n528     IA               CLARKE              16\n529     IA                 CLAY               2\n530     IA              CLAYTON              24\n531     IA              CLINTON             140\n532     IA             CRAWFORD               8\n533     IA               DALLAS              46\n534     IA                DAVIS              11\n535     IA              DECATUR               9\n536     IA             DELAWARE              18\n537     IA           DES MOINES             179\n538     IA            DICKINSON               2\n539     IA              DUBUQUE              71\n540     IA                EMMET               6\n541     IA              FAYETTE              23\n542     IA                FLOYD              34\n543     IA             FRANKLIN              11\n544     IA              FREMONT              15\n545     IA               GREENE              19\n546     IA               GRUNDY               9\n547     IA              GUTHRIE              10\n548     IA             HAMILTON              31\n549     IA              HANCOCK              10\n550     IA               HARDIN              20\n551     IA             HARRISON             102\n552     IA                HENRY              26\n553     IA               HOWARD               1\n554     IA             HUMBOLDT              17\n555     IA                  IDA               1\n556     IA                 IOWA              13\n557     IA              JACKSON              26\n558     IA               JASPER              24\n559     IA            JEFFERSON              10\n560     IA              JOHNSON              37\n561     IA                JONES              14\n562     IA               KEOKUK               3\n563     IA              KOSSUTH               5\n564     IA                  LEE             204\n565     IA                 LINN             146\n566     IA               LOUISA               7\n567     IA                LUCAS               5\n568     IA                 LYON               2\n569     IA              MADISON              12\n570     IA              MAHASKA               3\n571     IA               MARION              14\n572     IA             MARSHALL              90\n573     IA                MILLS              96\n574     IA             MITCHELL              15\n575     IA               MONONA              12\n576     IA               MONROE              14\n577     IA           MONTGOMERY              19\n578     IA            MUSCATINE              29\n579     IA              O'BRIEN               1\n580     IA              OSCEOLA               1\n581     IA                 PAGE              13\n582     IA            PALO ALTO               2\n583     IA             PLYMOUTH              14\n584     IA           POCAHONTAS               5\n585     IA                 POLK             235\n586     IA        POTTAWATTAMIE             609\n587     IA            POWESHIEK               7\n588     IA             RINGGOLD              13\n589     IA                  SAC              10\n590     IA                SCOTT             137\n591     IA               SHELBY              12\n592     IA                SIOUX               1\n593     IA                STORY              94\n594     IA                 TAMA              20\n595     IA               TAYLOR               3\n596     IA                UNION              70\n597     IA            VAN BUREN               8\n598     IA              WAPELLO              42\n599     IA               WARREN              37\n600     IA           WASHINGTON              10\n601     IA                WAYNE               5\n602     IA              WEBSTER              65\n603     IA            WINNEBAGO               6\n604     IA           WINNESHIEK               1\n605     IA             WOODBURY             155\n606     IA                WORTH              12\n607     IA               WRIGHT              36\n608     ID                  ADA              81\n609     ID                ADAMS               2\n610     ID              BANNOCK             538\n611     ID            BEAR LAKE              71\n612     ID              BENEWAH              10\n613     ID              BINGHAM              47\n614     ID                BOISE               3\n615     ID               BONNER              40\n616     ID           BONNEVILLE              44\n617     ID             BOUNDARY              44\n618     ID               CANYON             168\n619     ID              CARIBOU              12\n620     ID               CASSIA              16\n621     ID           CLEARWATER               1\n622     ID               CUSTER               1\n623     ID               ELMORE               9\n624     ID             FRANKLIN              20\n625     ID              FREMONT               1\n626     ID                  GEM              26\n627     ID              GOODING               4\n628     ID                IDAHO               4\n629     ID            JEFFERSON               6\n630     ID               JEROME              11\n631     ID             KOOTENAI             205\n632     ID                LATAH              11\n633     ID                LEWIS               2\n634     ID              LINCOLN               6\n635     ID             MINIDOKA              32\n636     ID            NEZ PERCE              13\n637     ID               ONEIDA               8\n638     ID               OWYHEE               7\n639     ID              PAYETTE              23\n640     ID                POWER              12\n641     ID           TWIN FALLS              63\n642     ID               VALLEY               1\n643     ID           WASHINGTON              21\n644     IL                ADAMS             116\n645     IL            ALEXANDER               2\n646     IL                 BOND              23\n647     IL                BOONE              44\n648     IL                BROWN               7\n649     IL               BUREAU              35\n650     IL              CALHOUN               4\n651     IL              CARROLL              96\n652     IL                 CASS              66\n653     IL            CHAMPAIGN             131\n654     IL            CHRISTIAN             104\n655     IL                CLARK              24\n656     IL                 CLAY              14\n657     IL              CLINTON              38\n658     IL                COLES              42\n659     IL                 COOK            8207\n660     IL             CRAWFORD              12\n661     IL           CUMBERLAND               9\n662     IL              DE WITT              46\n663     IL               DEKALB             119\n664     IL              DOUGLAS              60\n665     IL               DUPAGE             837\n666     IL              DUPAGEE              45\n667     IL                EDGAR              12\n668     IL              EDWARDS               4\n669     IL            EFFINGHAM              33\n670     IL              FAYETTE              32\n671     IL                 FORD              23\n672     IL             FRANKLIN              39\n673     IL               FULTON              56\n674     IL             GALLATIN               7\n675     IL               GREENE              13\n676     IL               GRUNDY              83\n677     IL             HAMILTON              19\n678     IL              HANCOCK             127\n679     IL               HARDIN               1\n680     IL            HENDERSON             100\n681     IL                HENRY              74\n682     IL             IROQUOIS              87\n683     IL              JACKSON              37\n684     IL               JASPER               4\n685     IL            JEFFERSON              72\n686     IL               JERSEY              14\n687     IL           JO DAVIESS              14\n688     IL              JOHNSON              26\n689     IL                 KANE             577\n690     IL             KANKAKEE             289\n691     IL              KENDALL             122\n692     IL                 KNOX             885\n693     IL             LA SALLE             132\n694     IL                 LAKE             340\n695     IL             LAWRENCE               6\n696     IL                  LEE              40\n697     IL           LIVINGSTON              12\n698     IL                LOGAN              16\n699     IL                MACON             425\n700     IL             MACOUPIN              79\n701     IL              MADISON             427\n702     IL               MARION             261\n703     IL             MARSHALL              10\n704     IL                MASON              23\n705     IL               MASSAC               9\n706     IL            MCDONOUGH              53\n707     IL              MCHENRY             273\n708     IL               MCLEAN              45\n709     IL               MENARD              10\n710     IL               MERCER              18\n711     IL               MONROE             122\n712     IL           MONTGOMERY              38\n713     IL               MORGAN              43\n714     IL             MOULTRIE              49\n715     IL                 OGLE              75\n716     IL               PEORIA             130\n717     IL                PERRY              20\n718     IL                PIATT              54\n719     IL                 PIKE              50\n720     IL                 POPE               1\n721     IL              PULASKI               7\n722     IL               PUTNAM               5\n723     IL             RANDOLPH              68\n724     IL             RICHLAND               9\n725     IL          ROCK ISLAND              94\n726     IL               SALINE              11\n727     IL             SANGAMON             114\n728     IL             SCHUYLER              32\n729     IL                SCOTT              15\n730     IL               SHELBY              45\n731     IL             ST CLAIR             495\n732     IL                STARK               5\n733     IL           STEPHENSON              33\n734     IL             TAZEWELL              71\n735     IL                UNION              41\n736     IL            VERMILION             178\n737     IL               WABASH              14\n738     IL               WARREN             188\n739     IL           WASHINGTON              29\n740     IL                WAYNE              18\n741     IL                WHITE              16\n742     IL            WHITESIDE             124\n743     IL                 WILL            1784\n744     IL           WILLIAMSON              53\n745     IL            WINNEBAGO              76\n746     IL             WOODFORD              14\n747     IN                ADAMS              11\n748     IN                ALLEN             536\n749     IN          BARTHOLOMEW              12\n750     IN               BENTON               6\n751     IN            BLACKFORD              24\n752     IN                BOONE              22\n753     IN                BROWN               7\n754     IN              CARROLL              26\n755     IN                 CASS              35\n756     IN                CLARK             131\n757     IN                 CLAY              28\n758     IN              CLINTON              28\n759     IN             CRAWFORD              21\n760     IN              DAVIESS              35\n761     IN             DEARBORN              50\n762     IN              DECATUR               7\n763     IN               DEKALB             118\n764     IN             DELAWARE             125\n765     IN               DUBOIS              35\n766     IN              ELKHART             306\n767     IN              FAYETTE              19\n768     IN                FLOYD              85\n769     IN             FOUNTAIN              21\n770     IN             FRANKLIN              10\n771     IN               FULTON               8\n772     IN               GIBSON             153\n773     IN                GRANT              39\n774     IN               GREENE              72\n775     IN             HAMILTON              63\n776     IN              HANCOCK              60\n777     IN             HARRISON             147\n778     IN            HENDRICKS             229\n779     IN                HENRY              35\n780     IN               HOWARD              34\n781     IN           HUNTINGTON              66\n782     IN              JACKSON              11\n783     IN               JASPER              80\n784     IN                  JAY              18\n785     IN            JEFFERSON              10\n786     IN             JENNINGS              13\n787     IN              JOHNSON             165\n788     IN                 KNOX              16\n789     IN            KOSCIUSKO              30\n790     IN             LAGRANGE              16\n791     IN                 LAKE            1999\n792     IN              LAPORTE             360\n793     IN             LAPORTEE              24\n794     IN             LAWRENCE              16\n795     IN              MADISON              70\n796     IN               MARION             703\n797     IN             MARSHALL              40\n798     IN               MARTIN               3\n799     IN                MIAMI             146\n800     IN               MONROE              27\n801     IN           MONTGOMERY              30\n802     IN               MORGAN             105\n803     IN               NEWTON              18\n804     IN                NOBLE              59\n805     IN                 OHIO               5\n806     IN               ORANGE               7\n807     IN                 OWEN              19\n808     IN                PARKE              10\n809     IN                PERRY               7\n810     IN                 PIKE              27\n811     IN               PORTER             550\n812     IN                POSEY              41\n813     IN              PULASKI              11\n814     IN               PUTNAM              41\n815     IN             RANDOLPH              23\n816     IN               RIPLEY               8\n817     IN                 RUSH               7\n818     IN                SCOTT              10\n819     IN               SHELBY              43\n820     IN              SPENCER              23\n821     IN            ST JOSEPH             258\n822     IN               STARKE              58\n823     IN              STEUBEN              45\n824     IN             SULLIVAN              34\n825     IN           TIPPECANOE             118\n826     IN               TIPTON              14\n827     IN                UNION               7\n828     IN          VANDERBURGH             221\n829     IN           VERMILLION              23\n830     IN                 VIGO             103\n831     IN               WABASH              30\n832     IN               WARREN               8\n833     IN              WARRICK              82\n834     IN           WASHINGTON              29\n835     IN                WAYNE              12\n836     IN                WELLS              39\n837     IN                WHITE              23\n838     IN              WHITLEY              38\n839     KS                ALLEN              16\n840     KS             ANDERSON              12\n841     KS             ATCHISON              42\n842     KS               BARBER              11\n843     KS               BARTON              22\n844     KS              BOURBON              47\n845     KS                BROWN              14\n846     KS               BUTLER              76\n847     KS                CHASE              11\n848     KS           CHAUTAUQUA               1\n849     KS             CHEROKEE              38\n850     KS                 CLAY               5\n851     KS                CLOUD              14\n852     KS               COFFEY              10\n853     KS             COMANCHE               1\n854     KS               COWLEY              94\n855     KS             CRAWFORD             205\n856     KS              DECATUR               3\n857     KS            DICKINSON             138\n858     KS             DONIPHAN              24\n859     KS              DOUGLAS             126\n860     KS              EDWARDS               4\n861     KS                  ELK               7\n862     KS                ELLIS              12\n863     KS            ELLSWORTH               3\n864     KS               FINNEY               9\n865     KS                 FORD              22\n866     KS             FRANKLIN              72\n867     KS                GEARY              24\n868     KS                 GRAY               1\n869     KS              GREELEY               3\n870     KS            GREENWOOD               3\n871     KS             HAMILTON               1\n872     KS               HARPER              14\n873     KS               HARVEY             153\n874     KS              HASKELL              19\n875     KS             HODGEMAN               4\n876     KS              JACKSON              56\n877     KS            JEFFERSON             122\n878     KS               JEWELL               1\n879     KS              JOHNSON            1286\n880     KS              KINGMAN              12\n881     KS                KIOWA               1\n882     KS              LABETTE              88\n883     KS          LEAVENWORTH             232\n884     KS              LINCOLN               2\n885     KS                 LINN              31\n886     KS                LOGAN               6\n887     KS                 LYON              91\n888     KS               MARION              46\n889     KS             MARSHALL             233\n890     KS            MCPHERSON              34\n891     KS                MEADE               5\n892     KS                MIAMI             113\n893     KS             MITCHELL               2\n894     KS           MONTGOMERY             111\n895     KS               MORRIS              54\n896     KS               NEMAHA              22\n897     KS               NEOSHO              16\n898     KS               NORTON               2\n899     KS                OSAGE              73\n900     KS              OSBORNE               1\n901     KS               OTTAWA              12\n902     KS               PAWNEE               1\n903     KS             PHILLIPS              25\n904     KS         POTTAWATOMIE              17\n905     KS                PRATT              34\n906     KS              RAWLINS               2\n907     KS                 RENO              67\n908     KS             REPUBLIC               2\n909     KS                 RICE               7\n910     KS                RILEY              30\n911     KS                ROOKS               9\n912     KS                 RUSH              10\n913     KS              RUSSELL               1\n914     KS               SALINE             107\n915     KS                SCOTT               3\n916     KS             SEDGWICK             325\n917     KS               SEWARD              12\n918     KS              SHAWNEE             856\n919     KS              SHERMAN               9\n920     KS                SMITH               2\n921     KS             STAFFORD               3\n922     KS              STANTON               1\n923     KS              STEVENS               3\n924     KS               SUMNER             168\n925     KS               THOMAS               3\n926     KS                TREGO               2\n927     KS            WABAUNSEE              21\n928     KS              WALLACE               9\n929     KS           WASHINGTON              22\n930     KS              WICHITA               2\n931     KS               WILSON               4\n932     KS              WOODSON               7\n933     KS            WYANDOTTE             415\n934     KY                ADAIR               1\n935     KY                ALLEN               5\n936     KY             ANDERSON               5\n937     KY              BALLARD               7\n938     KY               BARREN               5\n939     KY                 BATH               3\n940     KY                 BELL              27\n941     KY                BOONE             236\n942     KY              BOURBON               8\n943     KY                 BOYD             232\n944     KY                BOYLE              62\n945     KY              BRACKEN              11\n946     KY            BREATHITT              36\n947     KY         BRECKINRIDGE              14\n948     KY              BULLITT             125\n949     KY               BUTLER               1\n950     KY             CALDWELL              29\n951     KY             CALLOWAY               4\n952     KY             CAMPBELL              79\n953     KY             CARLISLE               7\n954     KY              CARROLL              19\n955     KY               CARTER              54\n956     KY                CASEY              18\n957     KY            CHRISTIAN              15\n958     KY                CLARK               6\n959     KY                 CLAY               7\n960     KY           CRITTENDEN               1\n961     KY           CUMBERLAND               1\n962     KY              DAVIESS              31\n963     KY             EDMONSON               5\n964     KY              ELLIOTT               1\n965     KY               ESTILL              42\n966     KY              FAYETTE              58\n967     KY              FLEMING               9\n968     KY                FLOYD              84\n969     KY             FRANKLIN               5\n970     KY               FULTON               4\n971     KY             GALLATIN               8\n972     KY              GARRARD               8\n973     KY                GRANT              91\n974     KY               GRAVES              24\n975     KY              GRAYSON              11\n976     KY                GREEN               4\n977     KY              GREENUP             483\n978     KY              HANCOCK               3\n979     KY               HARDIN              67\n980     KY               HARLAN              44\n981     KY             HARRISON              15\n982     KY                 HART               6\n983     KY            HENDERSON              48\n984     KY                HENRY              24\n985     KY              HICKMAN               3\n986     KY              HOPKINS             133\n987     KY              JACKSON               4\n988     KY            JEFFERSON             413\n989     KY            JESSAMINE              13\n990     KY              JOHNSON              50\n991     KY               KENTON             244\n992     KY                KNOTT              16\n993     KY                 KNOX              38\n994     KY                LARUE               7\n995     KY               LAUREL             113\n996     KY             LAWRENCE              97\n997     KY                  LEE               8\n998     KY               LESLIE               3\n999     KY              LETCHER              22\n1000    KY                LEWIS              55\n1001    KY              LINCOLN             113\n1002    KY           LIVINGSTON              11\n1003    KY                LOGAN              16\n1004    KY                 LYON               6\n1005    KY              MADISON              47\n1006    KY             MAGOFFIN               1\n1007    KY               MARION               7\n1008    KY             MARSHALL              22\n1009    KY               MARTIN              16\n1010    KY                MASON               8\n1011    KY            MCCRACKEN              84\n1012    KY             MCCREARY               7\n1013    KY               MCLEAN               5\n1014    KY                MEADE              28\n1015    KY              MENIFEE               1\n1016    KY               MERCER              55\n1017    KY             METCALFE               1\n1018    KY               MONROE               4\n1019    KY           MONTGOMERY               5\n1020    KY               MORGAN               1\n1021    KY           MUHLENBERG              22\n1022    KY               NELSON              59\n1023    KY             NICHOLAS              11\n1024    KY                 OHIO              16\n1025    KY               OLDHAM              35\n1026    KY                 OWEN               3\n1027    KY               OWSLEY               2\n1028    KY            PENDLETON              31\n1029    KY                PERRY              39\n1030    KY                 PIKE             231\n1031    KY               POWELL               6\n1032    KY              PULASKI             104\n1033    KY            ROBERTSON               2\n1034    KY           ROCKCASTLE              32\n1035    KY                ROWAN               4\n1036    KY              RUSSELL               5\n1037    KY                SCOTT              15\n1038    KY               SHELBY              33\n1039    KY              SIMPSON               1\n1040    KY              SPENCER              22\n1041    KY               TAYLOR               2\n1042    KY                 TODD              15\n1043    KY                TRIGG               3\n1044    KY              TRIMBLE               4\n1045    KY                UNION               7\n1046    KY               WARREN              12\n1047    KY           WASHINGTON               3\n1048    KY                WAYNE               2\n1049    KY              WEBSTER              10\n1050    KY              WHITLEY             322\n1051    KY                WOLFE               3\n1052    KY             WOODFORD               5\n1053    LA               ACADIA              13\n1054    LA                ALLEN              19\n1055    LA            ASCENSION             103\n1056    LA           ASSUMPTION               5\n1057    LA            AVOYELLES              37\n1058    LA           BEAUREGARD              43\n1059    LA            BIENVILLE              21\n1060    LA              BOSSIER             285\n1061    LA                CADDO             546\n1062    LA            CALCASIEU             280\n1063    LA             CALDWELL               7\n1064    LA              CAMERON               1\n1065    LA            CATAHOULA               1\n1066    LA            CLAIBORNE              31\n1067    LA            CONCORDIA               3\n1068    LA              DE SOTO              40\n1069    LA     EAST BATON ROUGE             285\n1070    LA         EAST CARROLL               1\n1071    LA       EAST FELICIANA              11\n1072    LA           EVANGELINE              11\n1073    LA             FRANKLIN               4\n1074    LA                GRANT              25\n1075    LA               IBERIA              25\n1076    LA            IBERVILLE              86\n1077    LA              JACKSON              20\n1078    LA            JEFFERSON             368\n1079    LA      JEFFERSON DAVIS               6\n1080    LA             LA SALLE               5\n1081    LA            LAFAYETTE             124\n1082    LA            LAFOURCHE              10\n1083    LA              LINCOLN              16\n1084    LA           LIVINGSTON              78\n1085    LA              MADISON              10\n1086    LA            MOREHOUSE              19\n1087    LA         NATCHITOCHES              22\n1088    LA              ORLEANS             240\n1089    LA             OUACHITA             128\n1090    LA          PLAQUEMINES              17\n1091    LA        POINTE COUPEE              67\n1092    LA              RAPIDES             158\n1093    LA            RED RIVER               6\n1094    LA             RICHLAND               2\n1095    LA               SABINE               8\n1096    LA           ST BERNARD              35\n1097    LA           ST CHARLES              46\n1098    LA             ST JAMES              11\n1099    LA  ST JOHN THE BAPTIST              38\n1100    LA            ST LANDRY              91\n1101    LA            ST MARTIN              31\n1102    LA              ST MARY               2\n1103    LA           ST TAMMANY             128\n1104    LA           TANGIPAHOA             105\n1105    LA               TENSAS               1\n1106    LA           TERREBONNE              14\n1107    LA                UNION               8\n1108    LA            VERMILION               5\n1109    LA               VERNON              42\n1110    LA           WASHINGTON              20\n1111    LA              WEBSTER              68\n1112    LA     WEST BATON ROUGE              73\n1113    LA         WEST CARROLL               3\n1114    LA       WEST FELICIANA               5\n1115    LA                 WINN               2\n1116    MA           BARNSTABLE              44\n1117    MA            BERKSHIRE              50\n1118    MA              BRISTOL             232\n1119    MA                ESSEX             314\n1120    MA             FRANKLIN             113\n1121    MA              HAMPDEN             202\n1122    MA            HAMPSHIRE              68\n1123    MA            MIDDLESEX             673\n1124    MA              NORFOLK             386\n1125    MA             PLYMOUTH             429\n1126    MA              SUFFOLK             558\n1127    MA            WORCESTER             310\n1128    MD             ALLEGANY             509\n1129    MD         ANNE ARUNDEL             406\n1130    MD            BALTIMORE             415\n1131    MD              CALVERT             103\n1132    MD             CAROLINE               8\n1133    MD              CARROLL             118\n1134    MD                CECIL             393\n1135    MD              CHARLES             112\n1136    MD           DORCHESTER               8\n1137    MD            FREDERICK             157\n1138    MD              GARRETT              53\n1139    MD              HARFORD             248\n1140    MD               HOWARD              79\n1141    MD     INDEPENDENT CITY             722\n1142    MD                 KENT               3\n1143    MD           MONTGOMERY             302\n1144    MD       PRINCE GEORGES             809\n1145    MD          QUEEN ANNES              22\n1146    MD             SOMERSET               1\n1147    MD             ST MARYS              94\n1148    MD               TALBOT               2\n1149    MD           WASHINGTON             127\n1150    MD             WICOMICO              12\n1151    MD            WORCESTER               6\n1152    ME         ANDROSCOGGIN              22\n1153    ME            AROOSTOOK              57\n1154    ME           CUMBERLAND              71\n1155    ME             FRANKLIN               2\n1156    ME              HANCOCK               3\n1157    ME             KENNEBEC             109\n1158    ME                 KNOX               5\n1159    ME              LINCOLN               7\n1160    ME               OXFORD              36\n1161    ME            PENOBSCOT             117\n1162    ME          PISCATAQUIS              75\n1163    ME            SAGADAHOC               8\n1164    ME             SOMERSET              67\n1165    ME                WALDO              11\n1166    ME           WASHINGTON              17\n1167    ME                 YORK              47\n1168    MI               ALCONA               1\n1169    MI                ALGER               8\n1170    MI              ALLEGAN              27\n1171    MI               ALPENA               3\n1172    MI               ARENAC              19\n1173    MI               BARAGA               4\n1174    MI                BARRY              16\n1175    MI                  BAY              58\n1176    MI               BENZIE               2\n1177    MI              BERRIEN             136\n1178    MI               BRANCH              13\n1179    MI              CALHOUN             164\n1180    MI                 CASS              89\n1181    MI            CHEBOYGAN               2\n1182    MI             CHIPPEWA               8\n1183    MI                CLARE               5\n1184    MI              CLINTON              10\n1185    MI             CRAWFORD               1\n1186    MI                DELTA             188\n1187    MI            DICKINSON               7\n1188    MI                EATON              42\n1189    MI                EMMET               1\n1190    MI              GENESEE             195\n1191    MI              GLADWIN               4\n1192    MI              GOGEBIC               3\n1193    MI       GRAND TRAVERSE               4\n1194    MI              GRATIOT               5\n1195    MI            HILLSDALE              17\n1196    MI             HOUGHTON               6\n1197    MI                HURON               9\n1198    MI               INGHAM              46\n1199    MI                IONIA              32\n1200    MI                IOSCO              13\n1201    MI                 IRON               3\n1202    MI             ISABELLA               5\n1203    MI              JACKSON              77\n1204    MI            KALAMAZOO              58\n1205    MI             KALKASKA               3\n1206    MI                 KENT             149\n1207    MI                 LAKE               1\n1208    MI               LAPEER              36\n1209    MI             LEELANAU               3\n1210    MI              LENAWEE              70\n1211    MI           LIVINGSTON              33\n1212    MI                 LUCE               2\n1213    MI             MACKINAC               2\n1214    MI               MACOMB             170\n1215    MI             MANISTEE              12\n1216    MI            MARQUETTE             137\n1217    MI                MASON              17\n1218    MI              MECOSTA               5\n1219    MI            MENOMINEE              14\n1220    MI              MIDLAND               5\n1221    MI               MONROE             266\n1222    MI             MONTCALM              17\n1223    MI             MUSKEGON              24\n1224    MI              NEWAYGO              15\n1225    MI              OAKLAND             265\n1226    MI               OCEANA               1\n1227    MI               OGEMAW               6\n1228    MI            ONTONAGON              11\n1229    MI              OSCEOLA               2\n1230    MI               OSCODA               1\n1231    MI               OTSEGO               1\n1232    MI               OTTAWA              40\n1233    MI         PRESQUE ISLE               1\n1234    MI            ROSCOMMON               2\n1235    MI              SAGINAW              80\n1236    MI              SANILAC              14\n1237    MI          SCHOOLCRAFT              13\n1238    MI           SHIAWASSEE             100\n1239    MI             ST CLAIR             109\n1240    MI            ST JOSEPH              42\n1241    MI              TUSCOLA              38\n1242    MI            VAN BUREN              27\n1243    MI            WASHTENAW              63\n1244    MI                WAYNE             849\n1245    MI              WEXFORD               5\n1246    MN               AITKIN              19\n1247    MN                ANOKA             346\n1248    MN               BECKER              62\n1249    MN             BELTRAMI              10\n1250    MN               BENTON              20\n1251    MN            BIG STONE              10\n1252    MN           BLUE EARTH              59\n1253    MN                BROWN              25\n1254    MN              CARLTON             181\n1255    MN               CARVER              41\n1256    MN                 CASS              20\n1257    MN             CHIPPEWA               6\n1258    MN              CHISAGO              91\n1259    MN                 CLAY             175\n1260    MN           CLEARWATER               9\n1261    MN           COTTONWOOD               4\n1262    MN            CROW WING             143\n1263    MN               DAKOTA             348\n1264    MN                DODGE               1\n1265    MN              DOUGLAS              44\n1266    MN            FARIBAULT               8\n1267    MN             FILLMORE               4\n1268    MN             FREEBORN              24\n1269    MN              GOODHUE              35\n1270    MN                GRANT               3\n1271    MN             HENNEPIN             651\n1272    MN              HOUSTON              42\n1273    MN              HUBBARD              14\n1274    MN               ISANTI              57\n1275    MN               ITASCA              37\n1276    MN              JACKSON               7\n1277    MN              KANABEC              10\n1278    MN            KANDIYOHI             157\n1279    MN              KITTSON               4\n1280    MN          KOOCHICHING              43\n1281    MN        LAC QUI PARLE               2\n1282    MN                 LAKE              68\n1283    MN    LAKE OF THE WOODS               6\n1284    MN             LE SUEUR              27\n1285    MN              LINCOLN               4\n1286    MN                 LYON              10\n1287    MN             MAHNOMEN               7\n1288    MN             MARSHALL              13\n1289    MN               MARTIN               3\n1290    MN               MCLEOD              46\n1291    MN               MEEKER              32\n1292    MN           MILLE LACS              34\n1293    MN             MORRISON              43\n1294    MN                MOWER              20\n1295    MN               MURRAY               3\n1296    MN             NICOLLET               6\n1297    MN               NOBLES               6\n1298    MN               NORMAN               9\n1299    MN              OLMSTED              18\n1300    MN           OTTER TAIL              54\n1301    MN           PENNINGTON              62\n1302    MN                 PINE              35\n1303    MN            PIPESTONE               5\n1304    MN                 POLK             106\n1305    MN                 POPE              43\n1306    MN               RAMSEY             579\n1307    MN             RED LAKE              10\n1308    MN              REDWOOD               9\n1309    MN             RENVILLE              13\n1310    MN                 RICE              37\n1311    MN                 ROCK               9\n1312    MN               ROSEAU               4\n1313    MN                SCOTT              72\n1314    MN            SHERBURNE             148\n1315    MN               SIBLEY              11\n1316    MN             ST LOUIS             595\n1317    MN              STEARNS             100\n1318    MN               STEELE              16\n1319    MN              STEVENS               9\n1320    MN                SWIFT              16\n1321    MN                 TODD              28\n1322    MN             TRAVERSE               2\n1323    MN              WABASHA              13\n1324    MN               WADENA               9\n1325    MN               WASECA              49\n1326    MN           WASHINGTON             207\n1327    MN             WATONWAN              32\n1328    MN               WILKIN              34\n1329    MN               WINONA              26\n1330    MN               WRIGHT              62\n1331    MN      YELLOW MEDICINE               5\n1332    MO                ADAIR              21\n1333    MO               ANDREW              17\n1334    MO             ATCHISON               5\n1335    MO              AUDRAIN              25\n1336    MO                BARRY              17\n1337    MO               BARTON              26\n1338    MO                BATES              12\n1339    MO               BENTON              29\n1340    MO            BOLLINGER              12\n1341    MO                BOONE              52\n1342    MO             BUCHANAN             150\n1343    MO               BUTLER              84\n1344    MO             CALDWELL              38\n1345    MO             CALLAWAY              15\n1346    MO               CAMDEN              11\n1347    MO       CAPE GIRARDEAU              86\n1348    MO              CARROLL              23\n1349    MO               CARTER              20\n1350    MO                 CASS             235\n1351    MO                CEDAR              10\n1352    MO             CHARITON              50\n1353    MO            CHRISTIAN             112\n1354    MO                CLARK              29\n1355    MO                 CLAY             681\n1356    MO              CLINTON              97\n1357    MO                 COLE              46\n1358    MO               COOPER              60\n1359    MO             CRAWFORD              17\n1360    MO                 DADE              19\n1361    MO               DALLAS               8\n1362    MO              DAVIESS              21\n1363    MO               DEKALB              36\n1364    MO                 DENT               2\n1365    MO              DOUGLAS               1\n1366    MO              DUNKLIN              24\n1367    MO             FRANKLIN              54\n1368    MO            GASCONADE              14\n1369    MO               GENTRY               5\n1370    MO               GREENE             362\n1371    MO               GRUNDY              23\n1372    MO             HARRISON              19\n1373    MO                HENRY              20\n1374    MO              HICKORY               3\n1375    MO                 HOLT              16\n1376    MO               HOWARD               7\n1377    MO               HOWELL              87\n1378    MO     INDEPENDENT CITY             226\n1379    MO                 IRON              13\n1380    MO              JACKSON            2055\n1381    MO               JASPER             127\n1382    MO            JEFFERSON             436\n1383    MO              JOHNSON              42\n1384    MO                 KNOX              16\n1385    MO              LACLEDE              18\n1386    MO            LAFAYETTE              74\n1387    MO             LAWRENCE              64\n1388    MO                LEWIS              20\n1389    MO              LINCOLN              18\n1390    MO                 LINN             140\n1391    MO           LIVINGSTON              44\n1392    MO                MACON              47\n1393    MO              MADISON              30\n1394    MO               MARIES               1\n1395    MO               MARION              93\n1396    MO             MCDONALD               5\n1397    MO               MERCER               9\n1398    MO               MILLER              15\n1399    MO          MISSISSIPPI               1\n1400    MO             MONITEAU              24\n1401    MO               MONROE              24\n1402    MO           MONTGOMERY               9\n1403    MO               MORGAN              24\n1404    MO           NEW MADRID              10\n1405    MO               NEWTON              38\n1406    MO              NODAWAY               7\n1407    MO               OREGON             132\n1408    MO                OSAGE              12\n1409    MO                OZARK               5\n1410    MO             PEMISCOT               3\n1411    MO                PERRY              29\n1412    MO               PETTIS              95\n1413    MO               PHELPS              18\n1414    MO                 PIKE              33\n1415    MO               PLATTE              98\n1416    MO                 POLK              38\n1417    MO              PULASKI               5\n1418    MO               PUTNAM               1\n1419    MO                RALLS              23\n1420    MO             RANDOLPH             138\n1421    MO                  RAY             126\n1422    MO             REYNOLDS               5\n1423    MO               RIPLEY              48\n1424    MO     SAINTE GENEVIEVE              27\n1425    MO               SALINE              27\n1426    MO             SCHUYLER               8\n1427    MO             SCOTLAND               1\n1428    MO                SCOTT             126\n1429    MO              SHANNON              10\n1430    MO               SHELBY              12\n1431    MO           ST CHARLES             166\n1432    MO             ST CLAIR               8\n1433    MO          ST FRANCOIS             202\n1434    MO             ST LOUIS             316\n1435    MO             STODDARD              47\n1436    MO                STONE              20\n1437    MO             SULLIVAN               6\n1438    MO                TANEY              19\n1439    MO                TEXAS              34\n1440    MO               VERNON              25\n1441    MO               WARREN               8\n1442    MO           WASHINGTON              50\n1443    MO                WAYNE              38\n1444    MO              WEBSTER              86\n1445    MO                WORTH               3\n1446    MO               WRIGHT              40\n1447    MS                ADAMS               3\n1448    MS               ALCORN              45\n1449    MS                AMITE              16\n1450    MS               ATTALA              33\n1451    MS               BENTON              12\n1452    MS              CARROLL              14\n1453    MS            CHICKASAW              11\n1454    MS              CHOCTAW               6\n1455    MS            CLAIBORNE               3\n1456    MS               CLARKE              15\n1457    MS                 CLAY              10\n1458    MS              COAHOMA               1\n1459    MS               COPIAH              16\n1460    MS            COVINGTON               8\n1461    MS               DESOTO             341\n1462    MS              FORREST              64\n1463    MS             FRANKLIN              12\n1464    MS               GEORGE              21\n1465    MS               GREENE               2\n1466    MS              GRENADA              15\n1467    MS              HANCOCK              57\n1468    MS             HARRISON              46\n1469    MS                HINDS             130\n1470    MS               HOLMES              23\n1471    MS            HUMPHREYS               3\n1472    MS            ISSAQUENA               1\n1473    MS             ITAWAMBA               7\n1474    MS              JACKSON              42\n1475    MS               JASPER              10\n1476    MS            JEFFERSON               4\n1477    MS                JONES              10\n1478    MS               KEMPER               6\n1479    MS            LAFAYETTE               5\n1480    MS                LAMAR              27\n1481    MS           LAUDERDALE             169\n1482    MS             LAWRENCE              15\n1483    MS                LEAKE               6\n1484    MS                  LEE              23\n1485    MS              LEFLORE               1\n1486    MS              LINCOLN              46\n1487    MS              LOWNDES              79\n1488    MS              MADISON              45\n1489    MS               MARION              24\n1490    MS             MARSHALL              50\n1491    MS               MONROE              65\n1492    MS           MONTGOMERY              15\n1493    MS              NESHOBA               3\n1494    MS               NEWTON              47\n1495    MS              NOXUBEE               8\n1496    MS            OKTIBBEHA              10\n1497    MS               PANOLA              13\n1498    MS          PEARL RIVER              67\n1499    MS                PERRY              11\n1500    MS                 PIKE              56\n1501    MS             PONTOTOC               3\n1502    MS             PRENTISS               1\n1503    MS              QUITMAN               5\n1504    MS               RANKIN             104\n1505    MS                SCOTT              12\n1506    MS              SHARKEY               1\n1507    MS              SIMPSON              15\n1508    MS                STONE               8\n1509    MS            SUNFLOWER               2\n1510    MS         TALLAHATCHIE               3\n1511    MS                 TATE              36\n1512    MS               TIPPAH               8\n1513    MS           TISHOMINGO              10\n1514    MS               TUNICA               3\n1515    MS                UNION               8\n1516    MS             WALTHALL               5\n1517    MS               WARREN              49\n1518    MS           WASHINGTON               4\n1519    MS                WAYNE              18\n1520    MS              WEBSTER               6\n1521    MS            WILKINSON               5\n1522    MS              WINSTON              16\n1523    MS            YALOBUSHA              10\n1524    MS                YAZOO               7\n1525    MT           BEAVERHEAD               8\n1526    MT             BIG HORN               5\n1527    MT               BLAINE              32\n1528    MT           BROADWATER               4\n1529    MT               CARBON              40\n1530    MT              CASCADE             199\n1531    MT             CHOUTEAU               9\n1532    MT               CUSTER              61\n1533    MT              DANIELS               2\n1534    MT               DAWSON             301\n1535    MT           DEER LODGE              18\n1536    MT               FALLON               4\n1537    MT               FERGUS              11\n1538    MT             FLATHEAD             367\n1539    MT             GALLATIN              30\n1540    MT              GLACIER              29\n1541    MT        GOLDEN VALLEY               2\n1542    MT              GRANITE               8\n1543    MT                 HILL             513\n1544    MT            JEFFERSON               8\n1545    MT         JUDITH BASIN               2\n1546    MT                 LAKE              46\n1547    MT      LEWIS AND CLARK              83\n1548    MT              LIBERTY               9\n1549    MT              LINCOLN              31\n1550    MT              MADISON               1\n1551    MT               MCCONE               1\n1552    MT              MEAGHER               1\n1553    MT              MINERAL              14\n1554    MT             MISSOULA             362\n1555    MT          MUSSELSHELL               3\n1556    MT                 PARK              64\n1557    MT             PHILLIPS               9\n1558    MT              PONDERA              25\n1559    MT         POWDER RIVER               3\n1560    MT               POWELL               9\n1561    MT              PRAIRIE              11\n1562    MT              RAVALLI              49\n1563    MT             RICHLAND              26\n1564    MT            ROOSEVELT               9\n1565    MT              ROSEBUD              84\n1566    MT              SANDERS              37\n1567    MT             SHERIDAN               7\n1568    MT           SILVER BOW              20\n1569    MT           STILLWATER              52\n1570    MT          SWEET GRASS               7\n1571    MT                TETON               5\n1572    MT                TOOLE              28\n1573    MT             TREASURE               2\n1574    MT               VALLEY             143\n1575    MT            WHEATLAND               1\n1576    MT               WIBAUX               7\n1577    MT          YELLOWSTONE             525\n1578    NC             ALAMANCE              14\n1579    NC            ALEXANDER              10\n1580    NC            ALLEGHANY               1\n1581    NC                ANSON              12\n1582    NC                 ASHE               3\n1583    NC                AVERY               4\n1584    NC             BEAUFORT               4\n1585    NC               BLADEN               7\n1586    NC            BRUNSWICK              22\n1587    NC             BUNCOMBE              94\n1588    NC                BURKE              15\n1589    NC             CABARRUS              84\n1590    NC             CALDWELL               5\n1591    NC               CAMDEN              10\n1592    NC             CARTERET               5\n1593    NC              CASWELL               7\n1594    NC              CATAWBA              22\n1595    NC              CHATHAM               3\n1596    NC             CHEROKEE               8\n1597    NC               CHOWAN               2\n1598    NC                 CLAY               1\n1599    NC            CLEVELAND              12\n1600    NC             COLUMBUS              17\n1601    NC               CRAVEN              14\n1602    NC           CUMBERLAND              39\n1603    NC            CURRITUCK              29\n1604    NC                 DARE               3\n1605    NC             DAVIDSON              90\n1606    NC                DAVIE              28\n1607    NC               DUPLIN               4\n1608    NC               DURHAM              24\n1609    NC            EDGECOMBE               7\n1610    NC              FORSYTH              77\n1611    NC             FRANKLIN               5\n1612    NC               GASTON              55\n1613    NC                GATES               6\n1614    NC               GRAHAM               2\n1615    NC            GRANVILLE               8\n1616    NC             GUILFORD              78\n1617    NC              HALIFAX              36\n1618    NC              HARNETT              15\n1619    NC              HAYWOOD              21\n1620    NC            HENDERSON              32\n1621    NC             HERTFORD               3\n1622    NC                 HOKE               4\n1623    NC              IREDELL              48\n1624    NC              JACKSON               8\n1625    NC             JOHNSTON              56\n1626    NC                  LEE               8\n1627    NC               LENOIR               5\n1628    NC              LINCOLN              19\n1629    NC              MADISON              66\n1630    NC               MARTIN               4\n1631    NC             MCDOWELL              26\n1632    NC          MECKLENBURG             224\n1633    NC             MITCHELL              13\n1634    NC           MONTGOMERY              22\n1635    NC                MOORE              41\n1636    NC                 NASH             205\n1637    NC          NEW HANOVER              45\n1638    NC          NORTHAMPTON              15\n1639    NC               ONSLOW               4\n1640    NC               ORANGE              15\n1641    NC              PAMLICO               1\n1642    NC           PASQUOTANK              16\n1643    NC               PENDER              18\n1644    NC           PERQUIMANS               2\n1645    NC               PERSON               2\n1646    NC                 PITT              19\n1647    NC                 POLK               5\n1648    NC             RANDOLPH              18\n1649    NC             RICHMOND             291\n1650    NC              ROBESON             122\n1651    NC           ROCKINGHAM              12\n1652    NC                ROWAN             228\n1653    NC           RUTHERFORD              30\n1654    NC              SAMPSON               5\n1655    NC             SCOTLAND              30\n1656    NC               STANLY              49\n1657    NC               STOKES               9\n1658    NC                SURRY              30\n1659    NC                SWAIN               3\n1660    NC         TRANSYLVANIA               4\n1661    NC                UNION              50\n1662    NC                VANCE               4\n1663    NC                 WAKE             322\n1664    NC               WARREN               6\n1665    NC           WASHINGTON               6\n1666    NC              WATAUGA               1\n1667    NC                WAYNE              15\n1668    NC               WILKES               1\n1669    NC               WILSON              49\n1670    NC               YADKIN               6\n1671    NC               YANCEY              23\n1672    ND                ADAMS               2\n1673    ND               BARNES              25\n1674    ND               BENSON               2\n1675    ND            BOTTINEAU               6\n1676    ND               BOWMAN               1\n1677    ND                BURKE               7\n1678    ND             BURLEIGH             317\n1679    ND                 CASS             373\n1680    ND             CAVALIER               2\n1681    ND               DICKEY              11\n1682    ND               DIVIDE              12\n1683    ND                 DUNN               1\n1684    ND                 EDDY               7\n1685    ND               EMMONS               2\n1686    ND               FOSTER              14\n1687    ND        GOLDEN VALLEY               4\n1688    ND          GRAND FORKS             173\n1689    ND                GRANT               5\n1690    ND               GRIGGS               2\n1691    ND            HETTINGER               1\n1692    ND               KIDDER               9\n1693    ND              LAMOURE               5\n1694    ND                LOGAN               2\n1695    ND              MCHENRY              78\n1696    ND             MCINTOSH              10\n1697    ND             MCKENZIE               1\n1698    ND               MCLEAN              34\n1699    ND               MORTON             191\n1700    ND            MOUNTRAIL              14\n1701    ND               NELSON               6\n1702    ND               OLIVER               2\n1703    ND              PEMBINA               4\n1704    ND               PIERCE               9\n1705    ND               RAMSEY              14\n1706    ND               RANSOM              70\n1707    ND             RENVILLE               8\n1708    ND             RICHLAND              58\n1709    ND              ROLETTE               6\n1710    ND              SARGENT               3\n1711    ND             SHERIDAN               8\n1712    ND                SIOUX               1\n1713    ND                SLOPE               2\n1714    ND                STARK              34\n1715    ND             STUTSMAN              48\n1716    ND               TRAILL              11\n1717    ND                WALSH              76\n1718    ND                 WARD             407\n1719    ND                WELLS             101\n1720    ND             WILLIAMS              25\n1721    NE                ADAMS              77\n1722    NE             ANTELOPE               2\n1723    NE               ARTHUR               2\n1724    NE               BANNER               8\n1725    NE               BLAINE               2\n1726    NE                BOONE               2\n1727    NE            BOX BUTTE            1168\n1728    NE                BROWN               1\n1729    NE              BUFFALO             107\n1730    NE                 BURT               9\n1731    NE               BUTLER              40\n1732    NE                 CASS             192\n1733    NE                CEDAR               8\n1734    NE                CHASE               2\n1735    NE               CHERRY               1\n1736    NE             CHEYENNE              68\n1737    NE                 CLAY              13\n1738    NE               COLFAX               4\n1739    NE               CUMING               4\n1740    NE               CUSTER              82\n1741    NE               DAKOTA              35\n1742    NE                DAWES             120\n1743    NE               DAWSON             142\n1744    NE                DEUEL              13\n1745    NE                DIXON               5\n1746    NE                DODGE              78\n1747    NE              DOUGLAS            3797\n1748    NE                DUNDY               5\n1749    NE             FILLMORE              13\n1750    NE             FRANKLIN               3\n1751    NE             FRONTIER              30\n1752    NE               FURNAS              18\n1753    NE                 GAGE             152\n1754    NE               GARDEN              21\n1755    NE               GOSPER               9\n1756    NE                GRANT               8\n1757    NE              GREELEY               3\n1758    NE                 HALL             135\n1759    NE             HAMILTON              14\n1760    NE               HARLAN               4\n1761    NE                HAYES               3\n1762    NE            HITCHCOCK              15\n1763    NE                 HOLT               3\n1764    NE               HOOKER              17\n1765    NE               HOWARD              21\n1766    NE            JEFFERSON              42\n1767    NE              JOHNSON              30\n1768    NE              KEARNEY               6\n1769    NE                KEITH              98\n1770    NE              KIMBALL              24\n1771    NE                 KNOX               9\n1772    NE            LANCASTER            1619\n1773    NE              LINCOLN            2289\n1774    NE                LOGAN              35\n1775    NE                 LOUP               1\n1776    NE              MADISON              45\n1777    NE            MCPHERSON              19\n1778    NE              MERRICK              14\n1779    NE              MORRILL             112\n1780    NE                NANCE               1\n1781    NE               NEMAHA              12\n1782    NE             NUCKOLLS               8\n1783    NE                 OTOE              71\n1784    NE               PAWNEE               7\n1785    NE              PERKINS              20\n1786    NE               PHELPS               7\n1787    NE               PIERCE               7\n1788    NE               PLATTE              92\n1789    NE                 POLK               8\n1790    NE           RED WILLOW             124\n1791    NE           RICHARDSON              66\n1792    NE                 ROCK               1\n1793    NE               SALINE              41\n1794    NE                SARPY             840\n1795    NE             SAUNDERS             123\n1796    NE         SCOTTS BLUFF             614\n1797    NE               SEWARD             114\n1798    NE             SHERIDAN              49\n1799    NE              SHERMAN              18\n1800    NE                SIOUX               1\n1801    NE              STANTON              11\n1802    NE               THAYER              22\n1803    NE               THOMAS               5\n1804    NE             THURSTON               1\n1805    NE               VALLEY              13\n1806    NE           WASHINGTON              75\n1807    NE                WAYNE               3\n1808    NE              WEBSTER               5\n1809    NE                 YORK              18\n1810    NH              BELKNAP               2\n1811    NH              CARROLL              12\n1812    NH             CHESHIRE              28\n1813    NH                 COOS              19\n1814    NH              GRAFTON               7\n1815    NH         HILLSBOROUGH             136\n1816    NH            MERRIMACK               9\n1817    NH           ROCKINGHAM             146\n1818    NH            STRAFFORD              27\n1819    NH             SULLIVAN               7\n1820    NJ             ATLANTIC              58\n1821    NJ               BERGEN             513\n1822    NJ           BURLINGTON             464\n1823    NJ               CAMDEN             427\n1824    NJ             CAPE MAY              19\n1825    NJ           CUMBERLAND              39\n1826    NJ                ESSEX            1097\n1827    NJ           GLOUCESTER             270\n1828    NJ               HUDSON             871\n1829    NJ            HUNTERDON              68\n1830    NJ               MERCER             361\n1831    NJ            MIDDLESEX             955\n1832    NJ             MONMOUTH             862\n1833    NJ               MORRIS             296\n1834    NJ                OCEAN             589\n1835    NJ              PASSAIC             231\n1836    NJ                SALEM              30\n1837    NJ             SOMERSET             148\n1838    NJ               SUSSEX             178\n1839    NJ                UNION             738\n1840    NJ               WARREN             115\n1841    NM           BERNALILLO             227\n1842    NM               CATRON               4\n1843    NM               CHAVES              14\n1844    NM               CIBOLA              27\n1845    NM               COLFAX              25\n1846    NM                CURRY             431\n1847    NM              DE BACA               7\n1848    NM             DONA ANA              91\n1849    NM                 EDDY              43\n1850    NM                GRANT              13\n1851    NM            GUADALUPE               8\n1852    NM              HIDALGO              11\n1853    NM                  LEA               4\n1854    NM              LINCOLN               7\n1855    NM                 LUNA              41\n1856    NM             MCKINLEY             240\n1857    NM                OTERO              45\n1858    NM                 QUAY              42\n1859    NM           RIO ARRIBA               2\n1860    NM            ROOSEVELT              58\n1861    NM             SAN JUAN              56\n1862    NM           SAN MIGUEL               6\n1863    NM             SANDOVAL              80\n1864    NM             SANTA FE              26\n1865    NM               SIERRA               3\n1866    NM              SOCORRO              12\n1867    NM             TORRANCE              29\n1868    NM                UNION               5\n1869    NM             VALENCIA             401\n1870    NV            CHURCHILL               5\n1871    NV                CLARK             269\n1872    NV                 ELKO              77\n1873    NV             HUMBOLDT              47\n1874    NV     INDEPENDENT CITY               8\n1875    NV               LANDER               5\n1876    NV              LINCOLN              26\n1877    NV                 LYON              42\n1878    NV                  NYE              12\n1879    NV             PERSHING               5\n1880    NV               STOREY               1\n1881    NV               WASHOE             249\n1882    NY               ALBANY             629\n1883    NY             ALLEGANY              55\n1884    NY                BRONX             648\n1885    NY               BROOME             141\n1886    NY          CATTARAUGUS              72\n1887    NY               CAYUGA              36\n1888    NY           CHAUTAUQUA              57\n1889    NY              CHEMUNG              21\n1890    NY             CHENANGO              39\n1891    NY              CLINTON              24\n1892    NY             COLUMBIA             126\n1893    NY             CORTLAND              11\n1894    NY             DELAWARE              25\n1895    NY             DUTCHESS            1157\n1896    NY                 ERIE             784\n1897    NY                ESSEX              27\n1898    NY             FRANKLIN              11\n1899    NY               FULTON              20\n1900    NY              GENESEE              46\n1901    NY               GREENE             196\n1902    NY             HERKIMER              48\n1903    NY            JEFFERSON              19\n1904    NY                KINGS             970\n1905    NY                LEWIS               5\n1906    NY           LIVINGSTON              71\n1907    NY              MADISON              43\n1908    NY               MONROE             131\n1909    NY           MONTGOMERY              36\n1910    NY               NASSAU            2076\n1911    NY             NEW YORK             373\n1912    NY              NIAGARA             119\n1913    NY               ONEIDA              72\n1914    NY             ONONDAGA             184\n1915    NY              ONTARIO              33\n1916    NY               ORANGE             342\n1917    NY              ORLEANS              11\n1918    NY               OSWEGO              91\n1919    NY               OTSEGO              89\n1920    NY               PUTNAM             317\n1921    NY               QUEENS            1470\n1922    NY           RENSSELAER             358\n1923    NY             RICHMOND             177\n1924    NY             ROCKLAND              89\n1925    NY             SARATOGA             233\n1926    NY          SCHENECTADY             149\n1927    NY            SCHOHARIE              43\n1928    NY             SCHUYLER               7\n1929    NY               SENECA              13\n1930    NY          ST LAWRENCE              79\n1931    NY              STEUBEN              99\n1932    NY              SUFFOLK            3685\n1933    NY             SULLIVAN              14\n1934    NY                TIOGA              32\n1935    NY             TOMPKINS               8\n1936    NY               ULSTER             211\n1937    NY               WARREN              26\n1938    NY           WASHINGTON              60\n1939    NY                WAYNE              46\n1940    NY          WESTCHESTER            1040\n1941    NY              WYOMING              50\n1942    NY                YATES               6\n1943    OH                ADAMS              24\n1944    OH                ALLEN              92\n1945    OH              ASHLAND              56\n1946    OH            ASHTABULA             270\n1947    OH               ATHENS              21\n1948    OH             AUGLAIZE              23\n1949    OH              BELMONT              22\n1950    OH                BROWN              14\n1951    OH               BUTLER             220\n1952    OH              CARROLL              25\n1953    OH            CHAMPAIGN              28\n1954    OH                CLARK              23\n1955    OH             CLERMONT              68\n1956    OH              CLINTON              25\n1957    OH           COLUMBIANA             211\n1958    OH            COSHOCTON              87\n1959    OH             CRAWFORD             112\n1960    OH             CUYAHOGA             552\n1961    OH                DARKE              16\n1962    OH             DEFIANCE              33\n1963    OH             DELAWARE              58\n1964    OH                 ERIE             213\n1965    OH            FAIRFIELD              53\n1966    OH              FAYETTE              18\n1967    OH             FRANKLIN             359\n1968    OH               FULTON              60\n1969    OH               GALLIA              19\n1970    OH               GEAUGA              29\n1971    OH               GREENE              19\n1972    OH             GUERNSEY              16\n1973    OH             HAMILTON             278\n1974    OH              HANCOCK              71\n1975    OH               HARDIN              22\n1976    OH             HARRISON              26\n1977    OH                HENRY              38\n1978    OH             HIGHLAND              15\n1979    OH              HOCKING               9\n1980    OH               HOLMES               4\n1981    OH                HURON             674\n1982    OH              JACKSON              14\n1983    OH            JEFFERSON             108\n1984    OH                 KNOX              17\n1985    OH                 LAKE             114\n1986    OH             LAWRENCE             305\n1987    OH              LICKING              49\n1988    OH                LOGAN              54\n1989    OH               LORAIN             280\n1990    OH                LUCAS             842\n1991    OH              MADISON              20\n1992    OH             MAHONING             176\n1993    OH               MARION              60\n1994    OH               MEDINA             117\n1995    OH                MEIGS              20\n1996    OH               MERCER               8\n1997    OH                MIAMI              24\n1998    OH               MONROE               4\n1999    OH           MONTGOMERY              83\n2000    OH               MORGAN               3\n2001    OH               MORROW              21\n2002    OH            MUSKINGUM              29\n2003    OH                NOBLE               3\n2004    OH               OTTAWA             151\n2005    OH             PAULDING              18\n2006    OH                PERRY              12\n2007    OH             PICKAWAY              40\n2008    OH                 PIKE              39\n2009    OH              PORTAGE              51\n2010    OH               PREBLE              12\n2011    OH               PUTNAM              58\n2012    OH             RICHLAND             251\n2013    OH                 ROSS              40\n2014    OH             SANDUSKY             129\n2015    OH               SCIOTO             451\n2016    OH               SENECA             175\n2017    OH               SHELBY              21\n2018    OH                STARK             335\n2019    OH               SUMMIT             140\n2020    OH             TRUMBULL             121\n2021    OH           TUSCARAWAS             133\n2022    OH                UNION              54\n2023    OH             VAN WERT              16\n2024    OH               VINTON               6\n2025    OH               WARREN              69\n2026    OH           WASHINGTON              22\n2027    OH                WAYNE              65\n2028    OH             WILLIAMS              42\n2029    OH                 WOOD             316\n2030    OH              WYANDOT              35\n2031    OK                ADAIR               2\n2032    OK              ALFALFA               5\n2033    OK                ATOKA               4\n2034    OK               BEAVER               1\n2035    OK              BECKHAM              11\n2036    OK               BLAINE               7\n2037    OK                BRYAN              49\n2038    OK                CADDO              24\n2039    OK             CANADIAN              59\n2040    OK               CARTER               8\n2041    OK             CHEROKEE               6\n2042    OK              CHOCTAW              32\n2043    OK            CLEVELAND              41\n2044    OK                 COAL               5\n2045    OK             COMANCHE              15\n2046    OK               COTTON               3\n2047    OK                CRAIG              17\n2048    OK                CREEK              75\n2049    OK               CUSTER              38\n2050    OK             DELAWARE              14\n2051    OK                DEWEY               2\n2052    OK                ELLIS               7\n2053    OK             GARFIELD             161\n2054    OK               GARVIN              11\n2055    OK                GRADY              55\n2056    OK                GRANT              12\n2057    OK                GREER               5\n2058    OK               HARPER               1\n2059    OK              HASKELL               8\n2060    OK               HUGHES               9\n2061    OK              JACKSON               3\n2062    OK            JEFFERSON               5\n2063    OK             JOHNSTON               8\n2064    OK                  KAY              66\n2065    OK           KINGFISHER               7\n2066    OK                KIOWA               2\n2067    OK              LATIMER              43\n2068    OK             LE FLORE             176\n2069    OK              LINCOLN              18\n2070    OK                LOGAN              19\n2071    OK                 LOVE              11\n2072    OK                MAJOR               5\n2073    OK             MARSHALL              29\n2074    OK                MAYES              19\n2075    OK              MCCLAIN              27\n2076    OK            MCCURTAIN              18\n2077    OK             MCINTOSH              18\n2078    OK               MURRAY               7\n2079    OK             MUSKOGEE             127\n2080    OK                NOBLE              10\n2081    OK               NOWATA              34\n2082    OK             OKFUSKEE               7\n2083    OK             OKLAHOMA             193\n2084    OK             OKMULGEE              34\n2085    OK                OSAGE               1\n2086    OK               OTTAWA              14\n2087    OK               PAWNEE              11\n2088    OK                PAYNE               9\n2089    OK            PITTSBURG              23\n2090    OK             PONTOTOC              37\n2091    OK         POTTAWATOMIE              21\n2092    OK           PUSHMATAHA              11\n2093    OK               ROGERS              72\n2094    OK             SEMINOLE               6\n2095    OK             SEQUOYAH              48\n2096    OK             STEPHENS               9\n2097    OK                TEXAS               7\n2098    OK                TULSA             377\n2099    OK              WAGONER              19\n2100    OK           WASHINGTON              31\n2101    OK              WASHITA               6\n2102    OK                WOODS              20\n2103    OK             WOODWARD              23\n2104    OR                BAKER              37\n2105    OR               BENTON              15\n2106    OR            CLACKAMAS             127\n2107    OR              CLATSOP               4\n2108    OR             COLUMBIA              48\n2109    OR                 COOS              10\n2110    OR                CROOK               8\n2111    OR            DESCHUTES              53\n2112    OR              DOUGLAS              39\n2113    OR              GILLIAM               2\n2114    OR                GRANT               2\n2115    OR           HOOD RIVER              14\n2116    OR              JACKSON              30\n2117    OR            JEFFERSON              10\n2118    OR            JOSEPHINE               8\n2119    OR              KLAMATH             228\n2120    OR                 LAKE               4\n2121    OR                 LANE             229\n2122    OR              LINCOLN               4\n2123    OR                 LINN             103\n2124    OR              MALHEUR              10\n2125    OR               MARION              85\n2126    OR               MORROW              39\n2127    OR            MULTNOMAH             349\n2128    OR                 POLK              11\n2129    OR              SHERMAN               2\n2130    OR            TILLAMOOK               7\n2131    OR             UMATILLA             467\n2132    OR                UNION             196\n2133    OR              WALLOWA               6\n2134    OR                WASCO              50\n2135    OR           WASHINGTON              87\n2136    OR              YAMHILL              38\n2137    PA                ADAMS              39\n2138    PA            ALLEGHENY             760\n2139    PA            ARMSTRONG              39\n2140    PA               BEAVER             566\n2141    PA              BEDFORD             138\n2142    PA                BERKS             195\n2143    PA                BLAIR             910\n2144    PA             BRADFORD              38\n2145    PA                BUCKS            1106\n2146    PA               BUTLER             136\n2147    PA              CAMBRIA             420\n2148    PA              CAMERON               4\n2149    PA               CARBON             121\n2150    PA               CENTRE              32\n2151    PA              CHESTER             308\n2152    PA              CLARION              22\n2153    PA           CLEARFIELD             120\n2154    PA              CLINTON              39\n2155    PA             COLUMBIA               3\n2156    PA             CRAWFORD              67\n2157    PA           CUMBERLAND             299\n2158    PA              DAUPHIN             357\n2159    PA             DELAWARE             815\n2160    PA                  ELK               7\n2161    PA                 ERIE             140\n2162    PA              FAYETTE             291\n2163    PA             FRANKLIN              64\n2164    PA               FULTON               3\n2165    PA               GREENE              29\n2166    PA           HUNTINGDON              47\n2167    PA              INDIANA              36\n2168    PA            JEFFERSON              67\n2169    PA              JUNIATA              67\n2170    PA           LACKAWANNA             109\n2171    PA            LANCASTER             350\n2172    PA             LAWRENCE             173\n2173    PA              LEBANON              70\n2174    PA               LEHIGH             145\n2175    PA              LUZERNE              85\n2176    PA             LYCOMING              58\n2177    PA               MCKEAN               8\n2178    PA               MERCER              84\n2179    PA              MIFFLIN              53\n2180    PA               MONROE             207\n2181    PA           MONTGOMERY             532\n2182    PA              MONTOUR               3\n2183    PA          NORTHAMPTON             229\n2184    PA       NORTHUMBERLAND             102\n2185    PA                PERRY             169\n2186    PA         PHILADELPHIA            1649\n2187    PA                 PIKE              88\n2188    PA               POTTER               5\n2189    PA           SCHUYLKILL             131\n2190    PA               SNYDER              26\n2191    PA             SOMERSET             149\n2192    PA          SUSQUEHANNA              84\n2193    PA                TIOGA              15\n2194    PA                UNION              19\n2195    PA              VENANGO              16\n2196    PA               WARREN              10\n2197    PA           WASHINGTON             195\n2198    PA                WAYNE              51\n2199    PA         WESTMORELAND             392\n2200    PA              WYOMING              17\n2201    PA                 YORK             260\n2202    RI              BRISTOL               8\n2203    RI                 KENT             102\n2204    RI              NEWPORT              11\n2205    RI           PROVIDENCE             318\n2206    RI           WASHINGTON              48\n2207    SC            ABBEVILLE             124\n2208    SC                AIKEN             193\n2209    SC            ALLENDALE               1\n2210    SC             ANDERSON              34\n2211    SC              BAMBERG               6\n2212    SC             BARNWELL               9\n2213    SC             BEAUFORT              17\n2214    SC             BERKELEY              94\n2215    SC              CALHOUN               2\n2216    SC           CHARLESTON             148\n2217    SC             CHEROKEE               9\n2218    SC              CHESTER              15\n2219    SC         CHESTERFIELD              24\n2220    SC            CLARENDON              18\n2221    SC             COLLETON              29\n2222    SC           DARLINGTON              53\n2223    SC               DILLON              74\n2224    SC           DORCHESTER             139\n2225    SC            EDGEFIELD              17\n2226    SC            FAIRFIELD              22\n2227    SC             FLORENCE             220\n2228    SC           GEORGETOWN              29\n2229    SC           GREENVILLE             139\n2230    SC            GREENWOOD              94\n2231    SC              HAMPTON              25\n2232    SC                HORRY              42\n2233    SC               JASPER               7\n2234    SC              KERSHAW              26\n2235    SC            LANCASTER              19\n2236    SC              LAURENS              20\n2237    SC                  LEE               4\n2238    SC            LEXINGTON             118\n2239    SC               MARION              22\n2240    SC             MARLBORO              19\n2241    SC            MCCORMICK              20\n2242    SC             NEWBERRY              28\n2243    SC               OCONEE               5\n2244    SC           ORANGEBURG              25\n2245    SC              PICKENS              48\n2246    SC             RICHLAND              87\n2247    SC               SALUDA               5\n2248    SC          SPARTANBURG             124\n2249    SC               SUMTER              29\n2250    SC                UNION              19\n2251    SC         WILLIAMSBURG              22\n2252    SC                 YORK              72\n2253    SD               AURORA               1\n2254    SD               BEADLE              82\n2255    SD              BENNETT               2\n2256    SD            BON HOMME               1\n2257    SD            BROOKINGS              34\n2258    SD                BROWN             127\n2259    SD                BRULE               5\n2260    SD                BUTTE               4\n2261    SD             CAMPBELL               1\n2262    SD          CHARLES MIX               1\n2263    SD                 CLAY               5\n2264    SD            CODINGTON              13\n2265    SD               CUSTER              60\n2266    SD              DAVISON               6\n2267    SD                  DAY               4\n2268    SD                DEUEL               3\n2269    SD                DEWEY               2\n2270    SD              DOUGLAS               1\n2271    SD              EDMUNDS               9\n2272    SD           FALL RIVER             167\n2273    SD                GRANT               5\n2274    SD              GREGORY               3\n2275    SD               HAAKON               6\n2276    SD               HAMLIN               3\n2277    SD                 HAND               9\n2278    SD               HANSON               1\n2279    SD               HUGHES              17\n2280    SD                 HYDE               1\n2281    SD              JERAULD               1\n2282    SD            KINGSBURY              13\n2283    SD                 LAKE               3\n2284    SD             LAWRENCE              19\n2285    SD              LINCOLN              10\n2286    SD             MARSHALL               1\n2287    SD               MCCOOK               2\n2288    SD                MEADE              69\n2289    SD                MINER               1\n2290    SD            MINNEHAHA             106\n2291    SD                MOODY               2\n2292    SD           PENNINGTON              49\n2293    SD              PERKINS               1\n2294    SD               POTTER               1\n2295    SD              ROBERTS              10\n2296    SD              SANBORN               8\n2297    SD              SHANNON               2\n2298    SD                SPINK               5\n2299    SD              STANLEY               4\n2300    SD                SULLY               1\n2301    SD               TURNER               5\n2302    SD                UNION              52\n2303    SD             WALWORTH               6\n2304    SD              YANKTON               5\n2305    TN             ANDERSON              45\n2306    TN              BEDFORD              12\n2307    TN               BENTON              24\n2308    TN              BLEDSOE              10\n2309    TN               BLOUNT             128\n2310    TN              BRADLEY              72\n2311    TN             CAMPBELL              57\n2312    TN               CANNON               8\n2313    TN              CARROLL              57\n2314    TN               CARTER              21\n2315    TN             CHEATHAM              16\n2316    TN              CHESTER               3\n2317    TN            CLAIBORNE              32\n2318    TN                COCKE              37\n2319    TN               COFFEE              12\n2320    TN             CROCKETT              16\n2321    TN           CUMBERLAND              14\n2322    TN             DAVIDSON             162\n2323    TN              DECATUR               1\n2324    TN               DEKALB               6\n2325    TN              DICKSON              64\n2326    TN                 DYER              18\n2327    TN              FAYETTE              30\n2328    TN             FENTRESS               5\n2329    TN             FRANKLIN              36\n2330    TN               GIBSON              25\n2331    TN                GILES              10\n2332    TN             GRAINGER              53\n2333    TN               GREENE              43\n2334    TN               GRUNDY              59\n2335    TN              HAMBLEN              62\n2336    TN             HAMILTON             429\n2337    TN              HANCOCK               2\n2338    TN             HARDEMAN              14\n2339    TN               HARDIN              10\n2340    TN              HAWKINS              57\n2341    TN              HAYWOOD               4\n2342    TN            HENDERSON              14\n2343    TN                HENRY              22\n2344    TN              HICKMAN              16\n2345    TN            HUMPHREYS              24\n2346    TN              JACKSON               2\n2347    TN            JEFFERSON              60\n2348    TN              JOHNSON               1\n2349    TN                 KNOX             458\n2350    TN                 LAKE               2\n2351    TN           LAUDERDALE              44\n2352    TN             LAWRENCE              42\n2353    TN                LEWIS               6\n2354    TN              LINCOLN               4\n2355    TN               LOUDON              26\n2356    TN              MADISON              22\n2357    TN               MARION             115\n2358    TN             MARSHALL              40\n2359    TN                MAURY             111\n2360    TN               MCMINN             114\n2361    TN              MCNAIRY              17\n2362    TN                MEIGS              10\n2363    TN               MONROE              46\n2364    TN           MONTGOMERY              27\n2365    TN               MORGAN              60\n2366    TN                OBION              37\n2367    TN              OVERTON               1\n2368    TN                PERRY               2\n2369    TN              PICKETT               2\n2370    TN                 POLK              41\n2371    TN               PUTNAM               3\n2372    TN                 RHEA              70\n2373    TN                ROANE              44\n2374    TN            ROBERTSON              78\n2375    TN           RUTHERFORD             171\n2376    TN                SCOTT              45\n2377    TN           SEQUATCHIE              11\n2378    TN               SEVIER              51\n2379    TN               SHELBY             621\n2380    TN                SMITH               7\n2381    TN              STEWART               2\n2382    TN             SULLIVAN              72\n2383    TN               SUMNER              88\n2384    TN               TIPTON              45\n2385    TN            TROUSDALE               2\n2386    TN               UNICOI             230\n2387    TN                UNION              23\n2388    TN            VAN BUREN               3\n2389    TN               WARREN               6\n2390    TN           WASHINGTON             164\n2391    TN                WAYNE               3\n2392    TN              WEAKLEY              39\n2393    TN                WHITE               3\n2394    TN           WILLIAMSON              77\n2395    TN               WILSON              74\n2396    TX             ANDERSON             241\n2397    TX              ANDREWS               3\n2398    TX             ANGELINA              53\n2399    TX              ARANSAS               6\n2400    TX               ARCHER               8\n2401    TX            ARMSTRONG              12\n2402    TX             ATASCOSA              64\n2403    TX               AUSTIN              35\n2404    TX               BAILEY               5\n2405    TX              BANDERA              15\n2406    TX              BASTROP             102\n2407    TX               BAYLOR               1\n2408    TX                  BEE               9\n2409    TX                 BELL             413\n2410    TX                BEXAR             950\n2411    TX               BLANCO               3\n2412    TX               BOSQUE              17\n2413    TX                BOWIE              64\n2414    TX             BRAZORIA             259\n2415    TX               BRAZOS              55\n2416    TX             BREWSTER              14\n2417    TX              BRISCOE               3\n2418    TX                BROWN              39\n2419    TX             BURLESON              21\n2420    TX               BURNET               6\n2421    TX             CALDWELL              25\n2422    TX              CALHOUN               7\n2423    TX             CALLAHAN              12\n2424    TX              CAMERON             119\n2425    TX                 CAMP              14\n2426    TX               CARSON              21\n2427    TX                 CASS              54\n2428    TX             CHAMBERS               9\n2429    TX             CHEROKEE              57\n2430    TX                 CLAY              17\n2431    TX              COLEMAN              11\n2432    TX               COLLIN             159\n2433    TX        COLLINGSWORTH               4\n2434    TX             COLORADO              16\n2435    TX                COMAL             132\n2436    TX             COMANCHE              15\n2437    TX               CONCHO               1\n2438    TX                COOKE              56\n2439    TX              CORYELL              87\n2440    TX             CROCKETT               1\n2441    TX               CROSBY               2\n2442    TX            CULBERSON              13\n2443    TX               DALLAM             130\n2444    TX               DALLAS             406\n2445    TX           DEAF SMITH               7\n2446    TX                DELTA               2\n2447    TX               DENTON             394\n2448    TX               DEWITT               6\n2449    TX              DICKENS               2\n2450    TX               DIMMIT               1\n2451    TX               DONLEY               1\n2452    TX                DUVAL               1\n2453    TX             EASTLAND              16\n2454    TX                ECTOR              20\n2455    TX              EDWARDS               1\n2456    TX              EL PASO             863\n2457    TX                ELLIS             125\n2458    TX                ERATH              20\n2459    TX                FALLS              20\n2460    TX               FANNIN              19\n2461    TX              FAYETTE              26\n2462    TX               FISHER               2\n2463    TX                FLOYD               2\n2464    TX                FOARD               1\n2465    TX            FORT BEND             258\n2466    TX            FREESTONE              87\n2467    TX                 FRIO              20\n2468    TX            GALVESTON             283\n2469    TX                GARZA               2\n2470    TX            GILLESPIE               2\n2471    TX               GOLIAD               5\n2472    TX             GONZALES              42\n2473    TX                 GRAY              22\n2474    TX              GRAYSON             151\n2475    TX                GREGG             154\n2476    TX               GRIMES               9\n2477    TX            GUADALUPE              69\n2478    TX                 HALE              10\n2479    TX                 HALL               7\n2480    TX             HAMILTON               2\n2481    TX             HANSFORD               1\n2482    TX             HARDEMAN               8\n2483    TX               HARDIN             141\n2484    TX               HARRIS            2535\n2485    TX             HARRISON              98\n2486    TX              HARTLEY               9\n2487    TX                 HAYS              33\n2488    TX            HENDERSON              37\n2489    TX              HIDALGO              39\n2490    TX                 HILL              78\n2491    TX              HOCKLEY               7\n2492    TX                 HOOD             102\n2493    TX              HOPKINS              22\n2494    TX              HOUSTON              21\n2495    TX               HOWARD              75\n2496    TX             HUDSPETH               7\n2497    TX                 HUNT              32\n2498    TX           HUTCHINSON              37\n2499    TX                 JACK              33\n2500    TX              JACKSON               8\n2501    TX               JASPER              30\n2502    TX           JEFF DAVIS               2\n2503    TX            JEFFERSON             244\n2504    TX             JIM HOGG               4\n2505    TX            JIM WELLS              11\n2506    TX              JOHNSON             429\n2507    TX                JONES               7\n2508    TX               KARNES               3\n2509    TX              KAUFMAN              49\n2510    TX              KENDALL              10\n2511    TX                 KERR               5\n2512    TX               KINNEY              35\n2513    TX              KLEBERG              20\n2514    TX                 KNOX               1\n2515    TX             LA SALLE              14\n2516    TX                LAMAR              26\n2517    TX                 LAMB               4\n2518    TX             LAMPASAS               9\n2519    TX               LAVACA              14\n2520    TX                  LEE              12\n2521    TX                 LEON              31\n2522    TX              LIBERTY             144\n2523    TX            LIMESTONE              24\n2524    TX             LIVE OAK               4\n2525    TX                LLANO               3\n2526    TX              LUBBOCK             292\n2527    TX                 LYNN               2\n2528    TX              MADISON               8\n2529    TX               MARION              14\n2530    TX               MARTIN               2\n2531    TX                MASON               2\n2532    TX            MATAGORDA              12\n2533    TX             MAVERICK              71\n2534    TX            MCCULLOCH               4\n2535    TX             MCLENNAN             148\n2536    TX               MEDINA              56\n2537    TX              MIDLAND              30\n2538    TX                MILAM              37\n2539    TX                MILLS               4\n2540    TX             MITCHELL              11\n2541    TX             MONTAGUE              17\n2542    TX           MONTGOMERY             474\n2543    TX                MOORE              49\n2544    TX               MORRIS              16\n2545    TX               MOTLEY              17\n2546    TX          NACOGDOCHES              37\n2547    TX              NAVARRO              25\n2548    TX               NEWTON              14\n2549    TX                NOLAN              34\n2550    TX               NUECES              82\n2551    TX               OLDHAM               8\n2552    TX               ORANGE             105\n2553    TX           PALO PINTO              31\n2554    TX               PANOLA              21\n2555    TX               PARKER             303\n2556    TX               PARMER              28\n2557    TX                PECOS               2\n2558    TX                 POLK              27\n2559    TX               POTTER             883\n2560    TX             PRESIDIO               9\n2561    TX                RAINS               5\n2562    TX              RANDALL              72\n2563    TX                 REAL               2\n2564    TX            RED RIVER               1\n2565    TX               REEVES               3\n2566    TX              REFUGIO               2\n2567    TX            ROBERTSON              30\n2568    TX             ROCKWALL              32\n2569    TX              RUNNELS              10\n2570    TX                 RUSK              13\n2571    TX               SABINE               5\n2572    TX        SAN AUGUSTINE               3\n2573    TX          SAN JACINTO              24\n2574    TX         SAN PATRICIO              38\n2575    TX             SAN SABA               5\n2576    TX               SCURRY               9\n2577    TX               SHELBY              17\n2578    TX              SHERMAN               1\n2579    TX                SMITH             127\n2580    TX            SOMERVELL               5\n2581    TX                STARR               2\n2582    TX             STEPHENS               1\n2583    TX            STONEWALL               1\n2584    TX              SWISHER              13\n2585    TX              TARRANT            4235\n2586    TX               TAYLOR              86\n2587    TX              TERRELL              15\n2588    TX                TERRY               5\n2589    TX                TITUS              10\n2590    TX            TOM GREEN              52\n2591    TX               TRAVIS              74\n2592    TX              TRINITY               6\n2593    TX                TYLER              29\n2594    TX               UPSHUR              41\n2595    TX                UPTON               2\n2596    TX               UVALDE              35\n2597    TX            VAL VERDE              93\n2598    TX            VAN ZANDT              47\n2599    TX             VICTORIA              60\n2600    TX               WALKER              38\n2601    TX               WALLER              21\n2602    TX                 WARD               5\n2603    TX           WASHINGTON               4\n2604    TX                 WEBB             291\n2605    TX              WHARTON              13\n2606    TX              WHEELER               4\n2607    TX              WICHITA             120\n2608    TX            WILBARGER               4\n2609    TX              WILLACY               1\n2610    TX           WILLIAMSON              77\n2611    TX               WILSON              75\n2612    TX                 WISE             156\n2613    TX                 WOOD              60\n2614    TX                YOUNG               2\n2615    TX               ZAPATA               2\n2616    TX               ZAVALA               4\n2617    UT               BEAVER              85\n2618    UT            BOX ELDER              58\n2619    UT                CACHE              23\n2620    UT               CARBON              52\n2621    UT              DAGGETT               2\n2622    UT                DAVIS             337\n2623    UT             DUCHESNE              10\n2624    UT                EMERY               8\n2625    UT                GRAND               1\n2626    UT                 IRON              48\n2627    UT                 JUAB              25\n2628    UT              MILLARD               8\n2629    UT               MORGAN              18\n2630    UT                 RICH               5\n2631    UT            SALT LAKE             580\n2632    UT             SAN JUAN               8\n2633    UT              SANPETE               5\n2634    UT               SEVIER               1\n2635    UT               SUMMIT              12\n2636    UT               TOOELE              52\n2637    UT               UINTAH              10\n2638    UT                 UTAH             186\n2639    UT              WASATCH               7\n2640    UT           WASHINGTON              16\n2641    UT                WEBER             360\n2642    VA             ACCOMACK               4\n2643    VA            ALBEMARLE              28\n2644    VA            ALLEGHANY             108\n2645    VA               AMELIA              10\n2646    VA              AMHERST              28\n2647    VA           APPOMATTOX              16\n2648    VA            ARLINGTON              63\n2649    VA              AUGUSTA              12\n2650    VA                 BATH              12\n2651    VA              BEDFORD             395\n2652    VA                BLAND              14\n2653    VA            BOTETOURT             288\n2654    VA            BRUNSWICK               9\n2655    VA             BUCHANAN              25\n2656    VA           BUCKINGHAM              32\n2657    VA             CAMPBELL              43\n2658    VA             CAROLINE              46\n2659    VA              CARROLL               3\n2660    VA         CHARLES CITY               6\n2661    VA            CHARLOTTE              30\n2662    VA         CHESTERFIELD             228\n2663    VA               CLARKE               2\n2664    VA                CRAIG              31\n2665    VA             CULPEPER              24\n2666    VA           CUMBERLAND               5\n2667    VA            DICKENSON              15\n2668    VA            DINWIDDIE              23\n2669    VA                ESSEX               4\n2670    VA              FAIRFAX             225\n2671    VA             FAUQUIER              24\n2672    VA                FLOYD              43\n2673    VA             FLUVANNA               9\n2674    VA             FRANKLIN             202\n2675    VA            FREDERICK              24\n2676    VA                GILES              41\n2677    VA           GLOUCESTER              14\n2678    VA            GOOCHLAND              15\n2679    VA               GREENE               4\n2680    VA          GREENSVILLE               2\n2681    VA              HALIFAX              10\n2682    VA              HANOVER             117\n2683    VA              HENRICO             128\n2684    VA                HENRY              24\n2685    VA     INDEPENDENT CITY            3249\n2686    VA        ISLE OF WIGHT              36\n2687    VA           JAMES CITY               6\n2688    VA       KING AND QUEEN               6\n2689    VA          KING GEORGE               6\n2690    VA         KING WILLIAM              29\n2691    VA            LANCASTER               1\n2692    VA                  LEE              32\n2693    VA              LOUDOUN              42\n2694    VA               LOUISA              31\n2695    VA            LUNENBURG              43\n2696    VA              MADISON               3\n2697    VA              MATHEWS               3\n2698    VA          MECKLENBURG               7\n2699    VA            MIDDLESEX               2\n2700    VA           MONTGOMERY             101\n2701    VA               NELSON              12\n2702    VA             NEW KENT              29\n2703    VA          NORTHAMPTON               7\n2704    VA             NOTTOWAY             106\n2705    VA               ORANGE              35\n2706    VA                 PAGE              70\n2707    VA              PATRICK               9\n2708    VA         PITTSYLVANIA              49\n2709    VA             POWHATAN              28\n2710    VA        PRINCE EDWARD              34\n2711    VA        PRINCE GEORGE              13\n2712    VA       PRINCE WILLIAM             110\n2713    VA              PULASKI              33\n2714    VA         RAPPAHANNOCK               9\n2715    VA             RICHMOND               1\n2716    VA              ROANOKE             193\n2717    VA           ROCKBRIDGE              16\n2718    VA           ROCKINGHAM              40\n2719    VA              RUSSELL             172\n2720    VA                SCOTT              30\n2721    VA           SHENANDOAH              13\n2722    VA                SMYTH              15\n2723    VA          SOUTHAMPTON              26\n2724    VA         SPOTSYLVANIA              46\n2725    VA             STAFFORD              37\n2726    VA               SUSSEX              10\n2727    VA             TAZEWELL             197\n2728    VA               WARREN              22\n2729    VA           WASHINGTON              26\n2730    VA         WESTMORELAND               7\n2731    VA                 WISE             114\n2732    VA                WYTHE              39\n2733    VA                 YORK              20\n2734    VT              ADDISON               8\n2735    VT           BENNINGTON               8\n2736    VT            CALEDONIA               3\n2737    VT           CHITTENDEN              40\n2738    VT                ESSEX               4\n2739    VT             FRANKLIN              83\n2740    VT           GRAND ISLE               5\n2741    VT             LAMOILLE               4\n2742    VT               ORANGE               9\n2743    VT              ORLEANS              13\n2744    VT              RUTLAND              59\n2745    VT           WASHINGTON               3\n2746    VT              WINDHAM              10\n2747    VT              WINDSOR              10\n2748    WA                ADAMS              15\n2749    WA               ASOTIN              17\n2750    WA               BENTON             294\n2751    WA               CHELAN              79\n2752    WA              CLALLAM               8\n2753    WA                CLARK             850\n2754    WA             COLUMBIA               2\n2755    WA              COWLITZ             151\n2756    WA              DOUGLAS               2\n2757    WA                FERRY               1\n2758    WA             FRANKLIN             148\n2759    WA             GARFIELD               1\n2760    WA                GRANT              22\n2761    WA         GRAYS HARBOR              29\n2762    WA               ISLAND              39\n2763    WA            JEFFERSON               4\n2764    WA                 KING            1039\n2765    WA               KITSAP              60\n2766    WA             KITTITAS              15\n2767    WA            KLICKITAT              63\n2768    WA                LEWIS              73\n2769    WA              LINCOLN              12\n2770    WA                MASON              20\n2771    WA             OKANOGAN              15\n2772    WA              PACIFIC               6\n2773    WA         PEND OREILLE              21\n2774    WA               PIERCE             614\n2775    WA             SAN JUAN               2\n2776    WA               SKAGIT              57\n2777    WA             SKAMANIA              14\n2778    WA            SNOHOMISH             506\n2779    WA              SPOKANE             757\n2780    WA              STEVENS              34\n2781    WA             THURSTON              94\n2782    WA            WAHKIAKUM               3\n2783    WA          WALLA WALLA              45\n2784    WA              WHATCOM              45\n2785    WA              WHITMAN               9\n2786    WA               YAKIMA              56\n2787    WI                ADAMS              29\n2788    WI              ASHLAND               7\n2789    WI               BARRON              20\n2790    WI             BAYFIELD              11\n2791    WI                BROWN              76\n2792    WI              BUFFALO              16\n2793    WI              BURNETT               6\n2794    WI              CALUMET               8\n2795    WI             CHIPPEWA              35\n2796    WI                CLARK               9\n2797    WI             COLUMBIA             106\n2798    WI             CRAWFORD              24\n2799    WI                 DANE              74\n2800    WI                DODGE              63\n2801    WI                 DOOR               2\n2802    WI              DOUGLAS             465\n2803    WI                 DUNN              13\n2804    WI           EAU CLAIRE              78\n2805    WI          FOND DU LAC             275\n2806    WI               FOREST              16\n2807    WI                GRANT              33\n2808    WI                GREEN              11\n2809    WI           GREEN LAKE              17\n2810    WI                 IOWA               5\n2811    WI                 IRON               4\n2812    WI              JACKSON              19\n2813    WI            JEFFERSON              27\n2814    WI               JUNEAU              14\n2815    WI              KENOSHA             111\n2816    WI             KEWAUNEE               4\n2817    WI            LA CROSSE             339\n2818    WI            LAFAYETTE               7\n2819    WI             LANGLADE               7\n2820    WI              LINCOLN              23\n2821    WI            MANITOWOC              15\n2822    WI             MARATHON              23\n2823    WI            MARINETTE              12\n2824    WI            MARQUETTE              36\n2825    WI            MILWAUKEE             188\n2826    WI               MONROE              51\n2827    WI               OCONTO              16\n2828    WI               ONEIDA              13\n2829    WI            OUTAGAMIE              57\n2830    WI              OZAUKEE               6\n2831    WI                PEPIN              12\n2832    WI               PIERCE              43\n2833    WI                 POLK              23\n2834    WI              PORTAGE             240\n2835    WI                PRICE              10\n2836    WI               RACINE             100\n2837    WI                 ROCK             138\n2838    WI                 RUSK              21\n2839    WI                 SAUK              29\n2840    WI               SAWYER              14\n2841    WI              SHAWANO               9\n2842    WI            SHEBOYGAN               9\n2843    WI             ST CROIX             168\n2844    WI               TAYLOR              15\n2845    WI          TREMPEALEAU              54\n2846    WI               VERNON              48\n2847    WI                VILAS               5\n2848    WI             WALWORTH              47\n2849    WI             WASHBURN              23\n2850    WI           WASHINGTON              37\n2851    WI             WAUKESHA              96\n2852    WI              WAUPACA              34\n2853    WI             WAUSHARA              13\n2854    WI            WINNEBAGO              95\n2855    WI                 WOOD             119\n2856    WV              BARBOUR              33\n2857    WV             BERKELEY             108\n2858    WV                BOONE              50\n2859    WV              BRAXTON              22\n2860    WV               BROOKE              19\n2861    WV               CABELL             406\n2862    WV                 CLAY               4\n2863    WV            DODDRIDGE               4\n2864    WV              FAYETTE              30\n2865    WV               GILMER               1\n2866    WV                GRANT               7\n2867    WV           GREENBRIER              75\n2868    WV            HAMPSHIRE              37\n2869    WV              HANCOCK              37\n2870    WV                HARDY               7\n2871    WV             HARRISON              51\n2872    WV              JACKSON              22\n2873    WV            JEFFERSON              56\n2874    WV              KANAWHA             130\n2875    WV                LEWIS               3\n2876    WV              LINCOLN             107\n2877    WV                LOGAN              61\n2878    WV               MARION              16\n2879    WV             MARSHALL              26\n2880    WV                MASON              34\n2881    WV             MCDOWELL              43\n2882    WV               MERCER             387\n2883    WV              MINERAL             223\n2884    WV                MINGO             168\n2885    WV           MONONGALIA              19\n2886    WV               MONROE              35\n2887    WV               MORGAN              33\n2888    WV             NICHOLAS               6\n2889    WV                 OHIO              25\n2890    WV            PLEASANTS               3\n2891    WV           POCAHONTAS              13\n2892    WV              PRESTON              35\n2893    WV               PUTNAM              83\n2894    WV              RALEIGH              98\n2895    WV             RANDOLPH              21\n2896    WV              RITCHIE               7\n2897    WV                ROANE               3\n2898    WV              SUMMERS             153\n2899    WV               TAYLOR              94\n2900    WV               TUCKER               2\n2901    WV                TYLER               2\n2902    WV               UPSHUR               5\n2903    WV                WAYNE             217\n2904    WV              WEBSTER               5\n2905    WV               WETZEL               9\n2906    WV                 WIRT               7\n2907    WV                 WOOD             108\n2908    WV              WYOMING              63\n2909    WY               ALBANY              90\n2910    WY             BIG HORN              70\n2911    WY             CAMPBELL             386\n2912    WY               CARBON             168\n2913    WY             CONVERSE             211\n2914    WY                CROOK              33\n2915    WY              FREMONT              42\n2916    WY               GOSHEN             244\n2917    WY          HOT SPRINGS               4\n2918    WY              JOHNSON              18\n2919    WY              LARAMIE             737\n2920    WY              LINCOLN              25\n2921    WY              NATRONA              92\n2922    WY             NIOBRARA              51\n2923    WY                 PARK              29\n2924    WY               PLATTE             129\n2925    WY             SHERIDAN             252\n2926    WY             SUBLETTE               3\n2927    WY           SWEETWATER             196\n2928    WY                UINTA              49\n2929    WY             WASHAKIE              10\n2930    WY               WESTON              37\n```\n:::\n:::\n\n\n\n## General information about data set\n\nThis data set took trains from certain states and asked for the total number of employees in each county.The mean amount of employees is 87.2 and the standard deviation is 283.6. The min is 1, the median is 21, and the max is 8207 employees. Below is how I found this data. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#the manual version of finding median for railroads\nrailroads %>%\n  summarize_all(median, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  state counties total_employees\n1    NA       NA              21\n```\n:::\n\n```{.r .cell-code}\n#the manual version of finding mean for railroads\nrailroads %>%\n  summarize_all(mean, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  state counties total_employees\n1    NA       NA        87.17816\n```\n:::\n\n```{.r .cell-code}\n#the manual version of finding the IQR for railroads\nrailroads %>%\n  summarize_all(IQR, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  state counties total_employees\n1    NA       NA              58\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#an general summary of the data set for railroads\ndfSummary(railroads)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nData Frame Summary  \nrailroads  \nDimensions: 2930 x 3  \nDuplicates: 0  \n\n-----------------------------------------------------------------------------------------------------------------\nNo   Variable          Stats / Values             Freqs (% of Valid)    Graph                Valid      Missing  \n---- ----------------- -------------------------- --------------------- -------------------- ---------- ---------\n1    state             1. TX                       221 ( 7.5%)          I                    2930       0        \n     [character]       2. GA                       152 ( 5.2%)          I                    (100.0%)   (0.0%)   \n                       3. KY                       119 ( 4.1%)                                                   \n                       4. MO                       115 ( 3.9%)                                                   \n                       5. IL                       103 ( 3.5%)                                                   \n                       6. IA                        99 ( 3.4%)                                                   \n                       7. KS                        95 ( 3.2%)                                                   \n                       8. NC                        94 ( 3.2%)                                                   \n                       9. IN                        92 ( 3.1%)                                                   \n                       10. VA                       92 ( 3.1%)                                                   \n                       [ 43 others ]              1748 (59.7%)          IIIIIIIIIII                              \n\n2    counties          1. WASHINGTON                31 ( 1.1%)                               2930       0        \n     [character]       2. JEFFERSON                 26 ( 0.9%)                               (100.0%)   (0.0%)   \n                       3. FRANKLIN                  24 ( 0.8%)                                                   \n                       4. LINCOLN                   24 ( 0.8%)                                                   \n                       5. JACKSON                   22 ( 0.8%)                                                   \n                       6. MADISON                   19 ( 0.6%)                                                   \n                       7. MONTGOMERY                18 ( 0.6%)                                                   \n                       8. CLAY                      17 ( 0.6%)                                                   \n                       9. MARION                    17 ( 0.6%)                                                   \n                       10. MONROE                   17 ( 0.6%)                                                   \n                       [ 1699 others ]            2715 (92.7%)          IIIIIIIIIIIIIIIIII                       \n\n3    total_employees   Mean (sd) : 87.2 (283.6)   404 distinct values   :                    2930       0        \n     [integer]         min < med < max:                                 :                    (100.0%)   (0.0%)   \n                       1 < 21 < 8207                                    :                                        \n                       IQR (CV) : 58 (3.3)                              :                                        \n                                                                        :                                        \n-----------------------------------------------------------------------------------------------------------------\n```\n:::\n:::\n\n\n\n## Texas Information\n\n7.5% of the counties on the list are Texas (TX) and there are\n221 counties from TX total. I decided to focus on texas as they have the most amount of counties and conducted averages for texas on my own.\n\nTex has a min of 1 employee, a median of 17 employees, and a max of 4235 employees. The mean amount of employees in texas is 89.8 with a standard deviation of 350.1. The IQR in texas is 50 as well.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#I create a new object called texas which takes the original railroads data set and\n# makes it only states with texas to be included.\nTEXAS <- filter(railroads, state == \"TX\")\n\n#the manual version of finding the median for TX\nTEXAS %>%\n  summarize_all(median, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  state counties total_employees\n1    TX  JOHNSON              17\n```\n:::\n\n```{.r .cell-code}\n#the manual version of finding the mean for TX\nTEXAS %>%\n  summarize_all(mean, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  state counties total_employees\n1    NA       NA        89.76923\n```\n:::\n\n```{.r .cell-code}\n#the manual version of finding the IQR for TX\nTEXAS %>%\n  summarize_all(IQR, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  state counties total_employees\n1    NA       NA              50\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#a general summary for the texas portion of the data set\ndfSummary(TEXAS)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nData Frame Summary  \nTEXAS  \nDimensions: 221 x 3  \nDuplicates: 0  \n\n------------------------------------------------------------------------------------------------------------------\nNo   Variable          Stats / Values             Freqs (% of Valid)   Graph                  Valid      Missing  \n---- ----------------- -------------------------- -------------------- ---------------------- ---------- ---------\n1    state             1. TX                      221 (100.0%)         IIIIIIIIIIIIIIIIIIII   221        0        \n     [character]                                                                              (100.0%)   (0.0%)   \n\n2    counties          1. ANDERSON                  1 ( 0.5%)                                 221        0        \n     [character]       2. ANDREWS                   1 ( 0.5%)                                 (100.0%)   (0.0%)   \n                       3. ANGELINA                  1 ( 0.5%)                                                     \n                       4. ARANSAS                   1 ( 0.5%)                                                     \n                       5. ARCHER                    1 ( 0.5%)                                                     \n                       6. ARMSTRONG                 1 ( 0.5%)                                                     \n                       7. ATASCOSA                  1 ( 0.5%)                                                     \n                       8. AUSTIN                    1 ( 0.5%)                                                     \n                       9. BAILEY                    1 ( 0.5%)                                                     \n                       10. BANDERA                  1 ( 0.5%)                                                     \n                       [ 211 others ]             211 (95.5%)          IIIIIIIIIIIIIIIIIII                        \n\n3    total_employees   Mean (sd) : 89.8 (350.1)   93 distinct values   :                      221        0        \n     [integer]         min < med < max:                                :                      (100.0%)   (0.0%)   \n                       1 < 17 < 4235                                   :                                          \n                       IQR (CV) : 50 (3.9)                             :                                          \n                                                                       :                                          \n------------------------------------------------------------------------------------------------------------------\n```\n:::\n:::\n\n## Washington County Information\n\nI went with washington as a filter/category to focus on because it is the most common county name and I thought it would be interesting to look into washingtons in different places. \n\nWashington counties have a minimum of 3 employees, a median of 26 employees, and a maximum of 207 employees. They also have a mean of 45.8 employees with a standard deviation of 55.2. The IQR for washington counties is 37.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#creating a new filter that only takes into account counties named\n#washington as it has the highest amount of names in the data set\nWASHINGTON <- filter(railroads, counties == \"WASHINGTON\")\n\n#the manual version of finding the median for Washington Counties\nWASHINGTON %>%\n  summarize_all(median, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  state   counties total_employees\n1    MO WASHINGTON              26\n```\n:::\n\n```{.r .cell-code}\n#the manual version of finding the mean for Washington Counties\nWASHINGTON %>%\n  summarize_all(mean, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  state counties total_employees\n1    NA       NA        45.80645\n```\n:::\n\n```{.r .cell-code}\n#the manual version of finding the IQR for Washington Counties\nWASHINGTON %>%\n  summarize_all(IQR, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  state counties total_employees\n1    NA       NA              37\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#the df summary for the washington county data points ONLY\n\ndfSummary(WASHINGTON)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nData Frame Summary  \nWASHINGTON  \nDimensions: 31 x 3  \nDuplicates: 0  \n\n-----------------------------------------------------------------------------------------------------------------\nNo   Variable          Stats / Values            Freqs (% of Valid)   Graph                  Valid      Missing  \n---- ----------------- ------------------------- -------------------- ---------------------- ---------- ---------\n1    state             1. AL                      1 ( 3.2%)                                  31         0        \n     [character]       2. AR                      1 ( 3.2%)                                  (100.0%)   (0.0%)   \n                       3. CO                      1 ( 3.2%)                                                      \n                       4. FL                      1 ( 3.2%)                                                      \n                       5. GA                      1 ( 3.2%)                                                      \n                       6. IA                      1 ( 3.2%)                                                      \n                       7. ID                      1 ( 3.2%)                                                      \n                       8. IL                      1 ( 3.2%)                                                      \n                       9. IN                      1 ( 3.2%)                                                      \n                       10. KS                     1 ( 3.2%)                                                      \n                       [ 21 others ]             21 (67.7%)           IIIIIIIIIIIII                              \n\n2    counties          1. WASHINGTON             31 (100.0%)          IIIIIIIIIIIIIIIIIIII   31         0        \n     [character]                                                                             (100.0%)   (0.0%)   \n\n3    total_employees   Mean (sd) : 45.8 (55.2)   26 distinct values   :                      31         0        \n     [integer]         min < med < max:                               :                      (100.0%)   (0.0%)   \n                       3 < 26 < 207                                   :                                          \n                       IQR (CV) : 37 (1.2)                            :                                          \n                                                                      : .   .                                    \n-----------------------------------------------------------------------------------------------------------------\n```\n:::\n:::\n\n\n## Conclusion\n\nI conclude that this data set has conducted studies on employee\nnumbers from 50 different states and has taken data from 2930 total counties in this data set.\n\n\n\n\n\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}