{
  "hash": "818e5166ed23e8d5ced032e8ac900406",
  "result": {
    "markdown": "---\ntitle: \"Challenge 8\"\nauthor: \"Poobigan Murugesan\"\ndescription: \"Joining Data\"\ndate: \"05/20/2023\"\nformat:\n  html:\n    toc: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_8\n  - snl\n  - poobigan murugesan\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(ggplot2)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Challenge Overview\n\nToday's challenge is to:\n\n1)  read in multiple data sets, and describe the data set using both words and any supporting information (e.g., tables, etc)\n2)  tidy data (as needed, including sanity checks)\n3)  mutate variables as needed (including sanity checks)\n4)  join two or more data sets and analyze some aspect of the joined data\n\n(be sure to only include the category tags for the data you use!)\n\n## Read in data\n\nReading in the snl datasets:\n\n::: {.cell}\n\n```{.r .cell-code}\nsnl_actors <- read.csv(\"_data/snl_actors.csv\")\nsnl_casts <- read.csv(\"_data/snl_casts.csv\")\nsnl_seasons <- read.csv(\"_data/snl_seasons.csv\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(snl_actors)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n             aid           url  type  gender\n1  Kate McKinnon   /Cast/?KaMc  cast  female\n2    Alex Moffat   /Cast/?AlMo  cast    male\n3     Ego Nwodim   /Cast/?EgNw  cast unknown\n4     Chris Redd   /Cast/?ChRe  cast    male\n5 Kenan Thompson   /Cast/?KeTh  cast    male\n6 Carey Mulligan /Guests/?3677 guest    andy\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(snl_actors)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2306    4\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(snl_casts)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n               aid sid featured first_epid last_epid update_anchor n_episodes\n1 A. Whitney Brown  11     True   19860222        NA         False          8\n2 A. Whitney Brown  12     True         NA        NA         False         20\n3 A. Whitney Brown  13     True         NA        NA         False         13\n4 A. Whitney Brown  14     True         NA        NA         False         20\n5 A. Whitney Brown  15     True         NA        NA         False         20\n6 A. Whitney Brown  16     True         NA        NA         False         20\n  season_fraction\n1       0.4444444\n2       1.0000000\n3       1.0000000\n4       1.0000000\n5       1.0000000\n6       1.0000000\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(snl_casts)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 614   8\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(snl_seasons)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  sid year first_epid last_epid n_episodes\n1   1 1975   19751011  19760731         24\n2   2 1976   19760918  19770521         22\n3   3 1977   19770924  19780520         20\n4   4 1978   19781007  19790526         20\n5   5 1979   19791013  19800524         20\n6   6 1980   19801115  19810411         13\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(snl_seasons)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 46  5\n```\n:::\n:::\n\n\n### Briefly describe the data\nThese three datasets contain information pertaining to actors, casts, and seasons associated with the television program \"Saturday Night Live.\" From the dimensions of these dataframes we can observe that  Saturday Night Live featured a total of 2306 actors and spanned across 46 seasons. The dataset named \"snl_actors\" contains specific actor-related information, while the \"snl_casts\" dataset comprises information about the cast members' appearances on the show, including details such as their featured episodes, number of appearances, and other relevant data. Lastly, the \"snl_seasons\" dataset has information related to each season of the show, such as the initial and final episodes, the year of airing, and the total number of episodes within each respective season.\n\n## Tidy Data (as needed)\n\nThe data is already tidy.\n\n\n## Join Data\nJoining actors and casts dataframes with the aid column and using select to keep useful columns, followed by joining the snl_casts_actors dataframe with the seasons dataframe with the sid column.\nThe resulting dataframe can be used to explore the relationship between the various variables.\n\n::: {.cell}\n\n```{.r .cell-code}\nsnl_casts_actors <- snl_casts %>%\n  left_join(snl_actors, by = \"aid\") %>%\n  select(sid, type, gender, n_episodes, featured)\n\nsnl_join <- snl_seasons %>%\n  left_join(snl_casts_actors, by = \"sid\")\nhead(snl_join)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  sid year first_epid last_epid n_episodes.x type gender n_episodes.y featured\n1   1 1975   19751011  19760731           24 cast female           24    False\n2   1 1975   19751011  19760731           24 cast   male            4    False\n3   1 1975   19751011  19760731           24 cast female           24    False\n4   1 1975   19751011  19760731           24 cast   male           24    False\n5   1 1975   19751011  19760731           24 cast female           24    False\n6   1 1975   19751011  19760731           24 cast   male            1    False\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(snl_join)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 614   9\n```\n:::\n:::\n\nSince ours is a left_join no. of columns must be same as snl_join which is 614.\n\n## Visualization\nPlotting the number of actors on snl shows based on gender over the years.\n\n::: {.cell}\n\n```{.r .cell-code}\nsnl_join<-snl_join %>%\n  group_by(sid, year, gender) %>%\n  summarise(count = n(), groups = 'drop')\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsnl_join %>%\n  ggplot(aes(year, count, col = gender)) +\n  geom_line() +\n  ylab(\"Count\") +\n  xlab(\"Year\")+\n  ggtitle(\"Yearwise actor count by gender\")+\n  scale_colour_manual(values= c(\"#0000FF\",\"#FF0000\", \"#000000\"\n))\n```\n\n::: {.cell-output-display}\n![](PoobiganMurugesan_challenge_8_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n",
    "supporting": [
      "PoobiganMurugesan_challenge_8_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}