{
  "hash": "54eaf1a3190a740f682ca4d6528bbc8d",
  "result": {
    "markdown": "---\ntitle: \"Challenge 8\"\nauthor: \"Thrishul\"\ndesription: \"\"\ndate: \"05/05/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_8\n---\n\nBefore we read in the data, we’ll need to load the dplyr, tidyr, ggplot2, and readr packages.\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──\n✔ ggplot2 3.4.0     ✔ purrr   1.0.1\n✔ tibble  3.1.8     ✔ dplyr   1.1.0\n✔ tidyr   1.3.0     ✔ stringr 1.5.0\n✔ readr   2.1.4     ✔ forcats 1.0.0\n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\n```\n:::\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(lubridate)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'lubridate'\n\nThe following objects are masked from 'package:base':\n\n    date, intersect, setdiff, union\n```\n:::\n\n```{.r .cell-code}\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n# Read in data\n\n::: {.cell}\n\n```{.r .cell-code}\nsnl_actors <- read.csv(\"_data/snl_actors.csv\")\ndim(snl_actors)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2306    4\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(snl_actors)  \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n             aid           url  type  gender\n1  Kate McKinnon   /Cast/?KaMc  cast  female\n2    Alex Moffat   /Cast/?AlMo  cast    male\n3     Ego Nwodim   /Cast/?EgNw  cast unknown\n4     Chris Redd   /Cast/?ChRe  cast    male\n5 Kenan Thompson   /Cast/?KeTh  cast    male\n6 Carey Mulligan /Guests/?3677 guest    andy\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsnl_casts <- read.csv(\"_data/snl_casts.csv\")\ndim(snl_casts)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 614   8\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(snl_casts)  \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n               aid sid featured first_epid last_epid update_anchor n_episodes\n1 A. Whitney Brown  11     True   19860222        NA         False          8\n2 A. Whitney Brown  12     True         NA        NA         False         20\n3 A. Whitney Brown  13     True         NA        NA         False         13\n4 A. Whitney Brown  14     True         NA        NA         False         20\n5 A. Whitney Brown  15     True         NA        NA         False         20\n6 A. Whitney Brown  16     True         NA        NA         False         20\n  season_fraction\n1       0.4444444\n2       1.0000000\n3       1.0000000\n4       1.0000000\n5       1.0000000\n6       1.0000000\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsnl_seasons <-read.csv(\"_data/snl_seasons.csv\")\ndim(snl_seasons)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 46  5\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(snl_seasons)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  sid year first_epid last_epid n_episodes\n1   1 1975   19751011  19760731         24\n2   2 1976   19760918  19770521         22\n3   3 1977   19770924  19780520         20\n4   4 1978   19781007  19790526         20\n5   5 1979   19791013  19800524         20\n6   6 1980   19801115  19810411         13\n```\n:::\n:::\n\nThe SNL dataset is comprised of three separate data sources: SNL actors, SNL casts, and SNL seasons.\n\nThe SNL actors dataset consists of a list of all cast and guest members who have appeared on SNL (2306). Each actor is linked to additional information, such as their gender and whether they were a cast member or a guest. Each row in the dataset represents a single actor.\n\nThe SNL casts dataset, on the other hand, is much more comprehensive in terms of variables. It includes information on the cast members (614) rather than guests, and provides details on the seasons in which they appeared, the number of episodes in each season, and the dates of the first and last episodes of each season. Most of the values for the first and last episodes are NA, only being included if they differ from the first or last episode of that season. We will deal with this issue later in our analysis.\n\nThe SNL casts data has the desired format for our analysis, where each row represents an \"actor-year.\" This is what we will use as our final data set.\n\nLastly, the SNL seasons dataset contains information on the 46 seasons of SNL, including the year, dates of the first and last episodes, and the episode count per season. Each row in the dataset represents a single season.\n\n# Tidy & Mutate Data\nTo join the data sets, I will perform some tidying operations. After the join, I will conduct additional mutations to clean the final data set.\n\nTo start with, I will filter out the guest actors from the SNL actors data set, as we lack sufficient information about them, except for gender, to use in an analysis.\n\n::: {.cell}\n\n```{.r .cell-code}\n#filtering out guests from actors data\nsnl_actors <- snl_actors %>% \n  filter(type == \"cast\") %>%\n  select(aid, gender)\n```\n:::\n\nAs you can see, there are two columns in the SNL casts data set (whether the cast member was an update anchor, and whether they were featured) which are currently of character data type, but they should be of logical data type. I have updated these columns to logical data type below.\n\n::: {.cell}\n\n```{.r .cell-code}\n#showing character class before mutation\nclass(snl_casts$update_anchor)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"character\"\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#mutating to change to logical\nsnl_casts <- snl_casts %>%\n  mutate(`update_anchor` = case_when(\n    `update_anchor` == \"True\" ~ TRUE,\n    `update_anchor` == \"False\" ~ FALSE)) %>%\n  mutate(`featured` = case_when(\n    `featured` == \"True\" ~ TRUE,\n    `featured` == \"False\" ~ FALSE))\n\n#showing logical class after mutation\nclass(snl_casts$update_anchor)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"logical\"\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nclass(snl_casts$featured)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"logical\"\n```\n:::\n:::\n\n# Joining Data\nAs we join the three data sets, we will use the SNL casts data as the primary data set and add information from the other data sets into this. The final data set should have 614 cases, with each case representing an “actor-season”.\n\nTo do this, we will first add the information about each season into the SNL casts data set. This includes the first and last date of the season, the number of episodes, and the year of the season.\n\nNext, we will use the SNL actors data set to add the gender of the cast member into our SNL casts data set.\n\n::: {.cell}\n\n```{.r .cell-code}\n#combining seasons data INTO casts data\nsnl_castsandseasons <- left_join(snl_casts, snl_seasons, by = \"sid\")\n\n#combining actors data INTO casts and seasons data\nsnl_castsseasonsandactors <- left_join(snl_castsandseasons, snl_actors, \"aid\")\n\nhead(snl_castsseasonsandactors)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n               aid sid featured first_epid.x last_epid.x update_anchor\n1 A. Whitney Brown  11     TRUE     19860222          NA         FALSE\n2 A. Whitney Brown  12     TRUE           NA          NA         FALSE\n3 A. Whitney Brown  13     TRUE           NA          NA         FALSE\n4 A. Whitney Brown  14     TRUE           NA          NA         FALSE\n5 A. Whitney Brown  15     TRUE           NA          NA         FALSE\n6 A. Whitney Brown  16     TRUE           NA          NA         FALSE\n  n_episodes.x season_fraction year first_epid.y last_epid.y n_episodes.y\n1            8       0.4444444 1985     19851109    19860524           18\n2           20       1.0000000 1986     19861011    19870523           20\n3           13       1.0000000 1987     19871017    19880227           13\n4           20       1.0000000 1988     19881008    19890520           20\n5           20       1.0000000 1989     19890930    19900519           20\n6           20       1.0000000 1990     19900929    19910518           20\n  gender\n1   male\n2   male\n3   male\n4   male\n5   male\n6   male\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(snl_castsseasonsandactors)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 614  13\n```\n:::\n:::\n\nAfter joining the three data sets, I have a data set with all the relevant variables, but it still needs some tidying up.\n\nCurrently, there are four date columns in the data, two for the first episode and two for the last episode. Since our cases are \"actor-seasons,\" I will combine these in a way that reflects the first and last episode dates of the season, unless the actor was only present for part of the season. In those cases, the dates will reflect the first or last episode in which they were involved. This will reduce the column count to 11.\n\nAdditionally, I have converted the numeric date columns into actual date format.\n\nFinally, there are two episode count columns: one for the number of episodes a cast member was involved in and one for the number of episodes in a season. To make these column names clearer, I have renamed them.\n\n::: {.cell}\n\n```{.r .cell-code}\n#creating final combined dataset\nsnl_all <- snl_castsseasonsandactors %>%\n  \n  #combining multiple first and last episode date columns to reflect dates participated by actors\n  mutate(first_episode = coalesce(first_epid.x, first_epid.y),\n         last_episode = coalesce(last_epid.x, last_epid.y)) %>%\n  \n  #changing numeric values to be dates\n  mutate(first_episode = ymd(first_episode),\n         last_episode = ymd(last_episode)) %>%\n  \n  #removing unused date columns\n  select(-c(first_epid.x, first_epid.y, last_epid.x, last_epid.y)) %>%\n  \n  #renaming for clarity\n  rename(\"actor_episodes\" = n_episodes.x) %>%\n  rename(\"season_episodes\" = n_episodes.y) \n\n#printing dimensions and summary\ndim(snl_casts)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 614   8\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(snl_all)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 614  11\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(snl_all)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n               aid sid featured update_anchor actor_episodes season_fraction\n1 A. Whitney Brown  11     TRUE         FALSE              8       0.4444444\n2 A. Whitney Brown  12     TRUE         FALSE             20       1.0000000\n3 A. Whitney Brown  13     TRUE         FALSE             13       1.0000000\n4 A. Whitney Brown  14     TRUE         FALSE             20       1.0000000\n5 A. Whitney Brown  15     TRUE         FALSE             20       1.0000000\n6 A. Whitney Brown  16     TRUE         FALSE             20       1.0000000\n  year season_episodes gender first_episode last_episode\n1 1985              18   male    1986-02-22   1986-05-24\n2 1986              20   male    1986-10-11   1987-05-23\n3 1987              13   male    1987-10-17   1988-02-27\n4 1988              20   male    1988-10-08   1989-05-20\n5 1989              20   male    1989-09-30   1990-05-19\n6 1990              20   male    1990-09-29   1991-05-18\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(summarytools::dfSummary(snl_all,\n                              valid.col=FALSE), \n      method = 'render')\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"container st-container\">\n<h3>Data Frame Summary</h3>\n<h4>snl_all</h4>\n<strong>Dimensions</strong>: 614 x 11\n  <br/><strong>Duplicates</strong>: 0\n<br/>\n<table class=\"table table-striped table-bordered st-table st-table-striped st-table-bordered st-multiline \">\n  <thead>\n    <tr>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>No</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Variable</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Stats / Values</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Freqs (% of Valid)</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Graph</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Missing</strong></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td align=\"center\">1</td>\n      <td align=\"left\">aid\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. Kenan Thompson</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. Darrell Hammond</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. Seth Meyers</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. Al Franken</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. Fred Armisen</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. Kate McKinnon</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. Tim Meadows</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. Aidy Bryant</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">9. Bobby Moynihan</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">10. Cecily Strong</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">[ 146 others ]</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">18</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">2.9%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">14</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">2.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">13</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">2.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">1.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">1.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">10</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">1.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">10</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">1.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">9</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">1.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">9</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">1.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">9</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">1.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">500</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">81.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAIYAAAEKBAMAAAAlUjC1AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5wUGDzMA1SlzOwAAALRJREFUeNrt18ENg0AMBEBaoISYDqD/3vgkRMrz7BMmmi1gHreSV7cs8puI1zqct7EdDAaD8Wyj4haOA/9pROSNbWcwGIxnGxW3MCG0M2wDg8Fg2JcZRuY7d/XCYDAYjJJ7mhDaGfaFwWAwbMMMw74wGAyGfZlh2BcGg8GwLzPeo0u3DAaDcadhX+rfo0u3DAaDcadhX+rfo0u3DAaDMWrYhnojMvl0e4xnZzAYjAZGxS2Ub04L5s4W5UTEYQAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMy0wNS0wNlQxNTo1MTowMCswMDowMEZKuvUAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjMtMDUtMDZUMTU6NTE6MDArMDA6MDA3FwJJAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"center\">2</td>\n      <td align=\"left\">sid\n[integer]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 25.5 (13.1)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1 &le; 26 &le; 46</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 22 (0.5)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">46 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAJgAAABuBAMAAAApJ8cWAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5wUGDzMA1SlzOwAAAItJREFUaN7t1sENgCAMQFFWwA2EDXT/3UykHpqQRqEhEf6/eKHPA6kxBGop1kqlPb7NwvJ5Z2CbvM8HKycOsNHYc40+mChg/8T0Tvdiag5sDkx/Lj5j1fFWLBsKGNiMmCyQD6YUsBFYUnVitXEwMDAwMDAwMDCwhTD5sfbB5AEGBgYGBrYGllwK1NIFUZiD1ldgmhYAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjMtMDUtMDZUMTU6NTE6MDArMDA6MDBGSrr1AAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIzLTA1LTA2VDE1OjUxOjAwKzAwOjAwNxcCSQAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"center\">3</td>\n      <td align=\"left\">featured\n[logical]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. FALSE</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. TRUE</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">451</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">73.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">163</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">26.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAHsAAAA3BAMAAADecyhbAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5wUGDzMA1SlzOwAAAERJREFUSMdjYBjZQIk8oADVrmxMFhjVPqp9VPuo9iGlncKiUpA8IDAotGPzGAnasYS80aj2Ue2j2ke1DzftFBaVIxUAAGWhfqPL0mjOAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIzLTA1LTA2VDE1OjUxOjAwKzAwOjAwRkq69QAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMy0wNS0wNlQxNTo1MTowMCswMDowMDcXAkkAAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"center\">4</td>\n      <td align=\"left\">update_anchor\n[logical]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. FALSE</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. TRUE</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">541</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">88.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">73</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">11.9%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAJAAAAA3BAMAAAARcd7dAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5wUGDzMA1SlzOwAAAEtJREFUSMdjYBgFxAAligHUIGVjCoHRqEGjBo0aNGrQqEH0Mohqhb8gxWDQGgT3qiKFBsFjbdSgUYNGDRo1aNSgQW8Q1Qr/UYAfAABKYp4IcHwVJAAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMy0wNS0wNlQxNTo1MTowMCswMDowMEZKuvUAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjMtMDUtMDZUMTU6NTE6MDArMDA6MDA3FwJJAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"center\">5</td>\n      <td align=\"left\">actor_episodes\n[integer]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 18.7 (4)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1 &le; 20 &le; 24</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 2 (0.2)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">22 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAJgAAABuBAMAAAApJ8cWAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5wUGDzMA1SlzOwAAAJJJREFUaN7t10EKgCAQhWGvUDfIbpD3v1vkCD6iIkZJiP8tXIzOh25EQyCeTI7EnEUqDdiajoCBgYGBgYGBgYGBgYF9jNnfrhOWxw0MDAwMDAwMDOw32Jxfi72wyoCBgY3D9BfYjOn6Tpjsrx1LtWsQNst5Yr1SC2aVZyxKpEvXp/Ook9ZZsJuu15iVL3bmTyCe7EfndVA6TaPyAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIzLTA1LTA2VDE1OjUxOjAwKzAwOjAwRkq69QAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMy0wNS0wNlQxNTo1MTowMCswMDowMDcXAkkAAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"center\">6</td>\n      <td align=\"left\">season_fraction\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 0.9 (0.2)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 1 &le; 1</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 0 (0.2)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">36 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAJgAAABuBAMAAAApJ8cWAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5wUGDzMA1SlzOwAAAFtJREFUaN7t2bENwCAMRUGvACMwAtl/NyRCEykiiFDe637hW8AR2in9Kpe7M9jVqzAYDAaDwWAwGAwGg8FgMBgMBoPBYDAYDAabHoxX7et6YuW7cTBb69hCoZ0a401CYwD7uMYAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjMtMDUtMDZUMTU6NTE6MDArMDA6MDBGSrr1AAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIzLTA1LTA2VDE1OjUxOjAwKzAwOjAwNxcCSQAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"center\">7</td>\n      <td align=\"left\">year\n[integer]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 1999.5 (13.1)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1975 &le; 2000 &le; 2020</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 22 (0)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">46 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAJgAAABuBAMAAAApJ8cWAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5wUGDzMA1SlzOwAAAIxJREFUaN7t1MENgCAMhWFWkA2EDXD/3TxYTGjgUqoh+r8b0H4hITQEYsk2k5gkLthxpYB5Y/WZdg8sS9kbWL24CybHBWyM3T/aBatdYGAfwwYj1YaprkcxPVJlacN012AbbEkstm8/ibXVYGALY2oKzmG5Ww0GBgYGBgYGBgYGBgYGBgb2Eyy5JBBLTjzNt2g8dciaAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIzLTA1LTA2VDE1OjUxOjAwKzAwOjAwRkq69QAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMy0wNS0wNlQxNTo1MTowMCswMDowMDcXAkkAAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"center\">8</td>\n      <td align=\"left\">season_episodes\n[integer]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 19.7 (2.1)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">12 &le; 20 &le; 24</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 1 (0.1)</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">12</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">12</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">2.0%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">13</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">24</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">3.9%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">17</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">30</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">4.9%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">18</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">31</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">5.0%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">19</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">37</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">6.0%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">20</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">297</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">48.4%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">21</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">111</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">18.1%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">22</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">63</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">10.3%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">24</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">9</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">1.5%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFUAAADbBAMAAADuYcDBAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5wUGDzMA1SlzOwAAAK5JREFUaN7t2bERwyAQRFGVYDqwzx1A/71ZgQMsCZZTwBzjv/ELxM7sJdq29WKWZB5f+85YLPZoPRvSMpY1s9dwZ6VgsdiD9WxIuWh2f5u8flVn8qpisf9mPRtSboZl81jsPLvifVAfXPUgi8BisW3r2VsayJT7IPKselDBYrFt69lbvPvQtz89ZCwW691QGkgk23/VZWcZi8Xe21AaSCSr/7ZUnWGx2JP1bGilfACa/scVBIaAiQAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMy0wNS0wNlQxNTo1MTowMCswMDowMEZKuvUAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjMtMDUtMDZUMTU6NTE6MDArMDA6MDA3FwJJAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"center\">9</td>\n      <td align=\"left\">gender\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. female</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. male</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. unknown</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">194</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">32.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">409</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">67.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">4</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.7%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAHEAAABOBAMAAADlfOSbAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5wUGDzMA1SlzOwAAAFFJREFUWMPt1LENACAMA0FGgA0gjMD+u9FQEqFAFfLfX2XJKcVJlFrRykv2sQ+JRCJt8v6HijmfUszVwyp6SCTyZ3n/Jr5e8+FvkUgk0q2M0ARAKqxt0Gw8OQAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMy0wNS0wNlQxNTo1MTowMCswMDowMEZKuvUAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjMtMDUtMDZUMTU6NTE6MDArMDA6MDA3FwJJAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">7\n(1.1%)</td>\n    </tr>\n    <tr>\n      <td align=\"center\">10</td>\n      <td align=\"left\">first_episode\n[Date]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min : 1975-10-11</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">med : 2000-10-07</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">max : 2020-10-03</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">range : 44y 11m 22d</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">80 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAJgAAABuBAMAAAApJ8cWAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5wUGDzMA1SlzOwAAAJNJREFUaN7t1s0NgCAMhmFWgA3EDWD/3TzYHiBqCG2MxPc7QvuEhJ8QAplJvE6WbHEoz9hez4B9Gku66S6YVBWwl7DUXlkjJsN6JFwwmS5gK2KpOws2rLbdYEti/fNgwvquMUyX4ILpNBjYvzG5VT5YWw0GBgYGBgYGBjaA5fZDZsNuusDAwMDAwMDAXLDskkBmcgCBhI1mAx13swAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMy0wNS0wNlQxNTo1MTowMCswMDowMEZKuvUAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjMtMDUtMDZUMTU6NTE6MDArMDA6MDA3FwJJAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"center\">11</td>\n      <td align=\"left\">last_episode\n[Date]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min : 1975-10-11</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">med : 2001-05-19</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">max : 2021-04-10</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">range : 45y 5m 30d</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">63 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAJgAAABuBAMAAAApJ8cWAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5wUGDzMA1SlzOwAAAItJREFUaN7t2E0KgCAQhmGvUDfIbtDc/24tmlk4IJgzBNX7bcS/B0ERsRQykyWStWpSMLlygL0Cs7232VrdbmGG7DraLcW6xzBFpINZMxhYKuZOaQyTtgT7Eeau1Bhm3WBgYGlY+2AJYu1oMDAwMDAwMDCwpzH/HRXCOrPAwMDAwMDAwD6O1ZQUMpMTTLuzjOxgNrEAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjMtMDUtMDZUMTU6NTE6MDArMDA6MDBGSrr1AAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIzLTA1LTA2VDE1OjUxOjAwKzAwOjAwNxcCSQAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n  </tbody>\n</table>\n<p>Generated by <a href='https://github.com/dcomtois/summarytools'>summarytools</a> 1.0.1 (<a href='https://www.r-project.org/'>R</a> version 4.2.2)<br/>2023-05-06</p>\n</div>\n```\n:::\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}