{
  "hash": "9bf76c286f37ceaa8fff49950156d12b",
  "result": {
    "markdown": "---\ntitle: \"Final Project Assignment#1: Susmita Madineni\"\nauthor: \"Susmita Madineni\"\ndescription: \"Global Internet users dataset from 1980-2020\"\ndate: \"04/12/2023\"\nformat:\n  html:\n    df-print: paged\n    toc: true\n    code-copy: true\n    code-tools: true\n    css: styles.css\ncategories:\n  - final_Project_assignment_1\n  - final_project_data_description\neditor_options: \n  chunk_output_type: console\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Part 1. Introduction {#describe-the-data-sets}\n\nIn this part, you should introduce the dataset(s) and your research questions.\n\n1.  Dataset(s) Introduction:\n\nThe internet users have grown exponentially since the time of its inception in the late 1960s. It is one of the most transformative inventions of the modern times. In the early days, primarily scientists, researchers and academics used the internet to share information across on the collaborated projects. But, later on due to the technological advancements, many people started to use internet for various activities. It evolved into a platform that connects people from all over the world  for various reasons. \n\nThere are a number of factors that has contributed to the growth of internet, such as faster and more reliable connections, the development and increase in usage of smartphones and other mobile devices, the popularity of social media. Due to the internet's increasing accessibility and user-friendliness, the usage has risen exponentially over the years.\n\nInternet usage has become an integral part of a person's life today. From communication and entertainment to education and commerce, billions of people utilize the internet on a daily basis. As the internet continues to develop and new technologies are emerging, it is foreseen that its use will continue to grow and transform our way of living, working and interacting with the world. \n\nThe dataset consists of country-wise internet users from 1980 to 2020. Each row in the dataset represents the mobile phone subscription per 100 people along with percentage of internet users using the internet, number of people using the internet and number of fixed broadband subscriptions per 100 people for a particular country and an year.\n\n\n2.  What questions do you like to answer with this dataset(s)?\n\nWith the help of the data analysis, I would like to answer the following questions:\n\n1. How the internet usage has increased over the years from 1980 to 1920 for the countries? \n\n2. What does the relationship between the mobile phone subscriptions and internet users looks like over the years? Are they strongly correlated to each other? Does increase in mobile phone subscriptions has an effect on the usage of the internet? \n\n3. Similarly what does the relationship between the fixed broadband subscriptions and internet users looks like over the years? Are they strongly correlated to each other? Does increase in fixed broadband subscriptions has an effect on the usage of the internet? \n\n4. Which country has the most number of internet users in the last 10 years?\n\n Many organizations can benefit with the help of these data visualizations. For example,\n - Market research companies can understand consumer behavior, trends and preferences in different parts of the world.They can make informed decisions while marketing the products, in product development and target the suitable demographics.\n - Advertising agencies will be able to identify the most popular and effective advertising channels and strategize accordingly to reach their target audience.\n - E-commerce companies can also benefit from this. They can understand the customer behavior, trends and preferences in different parts of the world. It will help them create a better experience for their customers and offer targeted promotions and discounts. \n - Government agencies can use these to monitor the usage patterns and identify any potential security threats, gain insights to what the public wants and also understand the sentiment of the public regarding various issues.\n - Social media platforms can use it to understand trends and preferences and improve user satisfaction and engagement.\n - Educational institutions, can understand how students are using the internet for research and learning, and to develop more effective online education tools and platforms.\n\n## Part 2. Describe the data set(s) {#describe-the-data-sets-1}\n\nThis part contains both a coding and a storytelling component.\n\nIn the coding component, you should:\n\n1.  read the dataset;\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readr)\nglobalInternetUsers <- read_csv(\"C:/Users/SUSMITA/OneDrive/Documents/Spring23/Courses/DACSS_601/DACSS_601/posts/SusmitaMadineni_FinalProjectData/Final.csv\")\nView(globalInternetUsers)\n```\n:::\n\n\n2.  present the descriptive information of the dataset(s) using the functions in Challenges 1, 2, and 3;\n\n    -   for examples: dim(), length(unique()), head();\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Preview the first few rows of the dataset\nhead(globalInternetUsers)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"...1\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Entity\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Code\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Year\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Cellular Subscription\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Internet Users(%)\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"No. of Internet Users\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Broadband Subscription\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"0\",\"2\":\"Afghanistan\",\"3\":\"AFG\",\"4\":\"1980\",\"5\":\"0\",\"6\":\"0\",\"7\":\"0\",\"8\":\"0\"},{\"1\":\"1\",\"2\":\"Afghanistan\",\"3\":\"AFG\",\"4\":\"1981\",\"5\":\"0\",\"6\":\"0\",\"7\":\"0\",\"8\":\"0\"},{\"1\":\"2\",\"2\":\"Afghanistan\",\"3\":\"AFG\",\"4\":\"1982\",\"5\":\"0\",\"6\":\"0\",\"7\":\"0\",\"8\":\"0\"},{\"1\":\"3\",\"2\":\"Afghanistan\",\"3\":\"AFG\",\"4\":\"1983\",\"5\":\"0\",\"6\":\"0\",\"7\":\"0\",\"8\":\"0\"},{\"1\":\"4\",\"2\":\"Afghanistan\",\"3\":\"AFG\",\"4\":\"1984\",\"5\":\"0\",\"6\":\"0\",\"7\":\"0\",\"8\":\"0\"},{\"1\":\"5\",\"2\":\"Afghanistan\",\"3\":\"AFG\",\"4\":\"1985\",\"5\":\"0\",\"6\":\"0\",\"7\":\"0\",\"8\":\"0\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\n# Understanding the dimensions of the dataset \ndim(globalInternetUsers)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 8867    8\n```\n:::\n\n```{.r .cell-code}\n# Identifying the column names of the dataset \ncolnames(globalInternetUsers)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"...1\"                   \"Entity\"                 \"Code\"                  \n[4] \"Year\"                   \"Cellular Subscription\"  \"Internet Users(%)\"     \n[7] \"No. of Internet Users\"  \"Broadband Subscription\"\n```\n:::\n\n```{.r .cell-code}\n# Identifying unique values for column - entity\nunique(globalInternetUsers$Entity)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  [1] \"Afghanistan\"                      \"Albania\"                         \n  [3] \"Algeria\"                          \"American Samoa\"                  \n  [5] \"Andorra\"                          \"Angola\"                          \n  [7] \"Antigua and Barbuda\"              \"Argentina\"                       \n  [9] \"Armenia\"                          \"Aruba\"                           \n [11] \"Australia\"                        \"Austria\"                         \n [13] \"Azerbaijan\"                       \"Bahamas\"                         \n [15] \"Bahrain\"                          \"Bangladesh\"                      \n [17] \"Barbados\"                         \"Belarus\"                         \n [19] \"Belgium\"                          \"Belize\"                          \n [21] \"Benin\"                            \"Bermuda\"                         \n [23] \"Bhutan\"                           \"Bolivia\"                         \n [25] \"Bosnia and Herzegovina\"           \"Botswana\"                        \n [27] \"Brazil\"                           \"British Virgin Islands\"          \n [29] \"Brunei\"                           \"Bulgaria\"                        \n [31] \"Burkina Faso\"                     \"Burundi\"                         \n [33] \"Cambodia\"                         \"Cameroon\"                        \n [35] \"Canada\"                           \"Cape Verde\"                      \n [37] \"Cayman Islands\"                   \"Central African Republic\"        \n [39] \"Chad\"                             \"Chile\"                           \n [41] \"China\"                            \"Colombia\"                        \n [43] \"Comoros\"                          \"Congo\"                           \n [45] \"Costa Rica\"                       \"Cote d'Ivoire\"                   \n [47] \"Croatia\"                          \"Cuba\"                            \n [49] \"Curacao\"                          \"Cyprus\"                          \n [51] \"Czechia\"                          \"Democratic Republic of Congo\"    \n [53] \"Denmark\"                          \"Djibouti\"                        \n [55] \"Dominica\"                         \"Dominican Republic\"              \n [57] \"East Asia and Pacific\"            \"Ecuador\"                         \n [59] \"Egypt\"                            \"El Salvador\"                     \n [61] \"Equatorial Guinea\"                \"Eritrea\"                         \n [63] \"Estonia\"                          \"Eswatini\"                        \n [65] \"Ethiopia\"                         \"Europe and Central Asia\"         \n [67] \"European Union\"                   \"Faeroe Islands\"                  \n [69] \"Fiji\"                             \"Finland\"                         \n [71] \"France\"                           \"French Polynesia\"                \n [73] \"Gabon\"                            \"Gambia\"                          \n [75] \"Georgia\"                          \"Germany\"                         \n [77] \"Ghana\"                            \"Gibraltar\"                       \n [79] \"Greece\"                           \"Greenland\"                       \n [81] \"Grenada\"                          \"Guam\"                            \n [83] \"Guatemala\"                        \"Guinea\"                          \n [85] \"Guinea-Bissau\"                    \"Guyana\"                          \n [87] \"Haiti\"                            \"High income\"                     \n [89] \"Honduras\"                         \"Hong Kong\"                       \n [91] \"Hungary\"                          \"Iceland\"                         \n [93] \"India\"                            \"Indonesia\"                       \n [95] \"Iran\"                             \"Iraq\"                            \n [97] \"Ireland\"                          \"Israel\"                          \n [99] \"Italy\"                            \"Jamaica\"                         \n[101] \"Japan\"                            \"Jordan\"                          \n[103] \"Kazakhstan\"                       \"Kenya\"                           \n[105] \"Kiribati\"                         \"Kosovo\"                          \n[107] \"Kuwait\"                           \"Kyrgyzstan\"                      \n[109] \"Laos\"                             \"Latin America and Caribbean\"     \n[111] \"Latvia\"                           \"Lebanon\"                         \n[113] \"Lesotho\"                          \"Liberia\"                         \n[115] \"Libya\"                            \"Liechtenstein\"                   \n[117] \"Lithuania\"                        \"Low and middle income\"           \n[119] \"Low income\"                       \"Lower middle income\"             \n[121] \"Luxembourg\"                       \"Macao\"                           \n[123] \"Madagascar\"                       \"Malawi\"                          \n[125] \"Malaysia\"                         \"Maldives\"                        \n[127] \"Mali\"                             \"Malta\"                           \n[129] \"Marshall Islands\"                 \"Mauritania\"                      \n[131] \"Mauritius\"                        \"Mexico\"                          \n[133] \"Micronesia (country)\"             \"Middle East and North Africa\"    \n[135] \"Middle income\"                    \"Moldova\"                         \n[137] \"Monaco\"                           \"Mongolia\"                        \n[139] \"Montenegro\"                       \"Morocco\"                         \n[141] \"Mozambique\"                       \"Myanmar\"                         \n[143] \"Namibia\"                          \"Nauru\"                           \n[145] \"Nepal\"                            \"Netherlands\"                     \n[147] \"New Caledonia\"                    \"New Zealand\"                     \n[149] \"Nicaragua\"                        \"Niger\"                           \n[151] \"Nigeria\"                          \"North America\"                   \n[153] \"North Korea\"                      \"North Macedonia\"                 \n[155] \"Northern Mariana Islands\"         \"Norway\"                          \n[157] \"Oman\"                             \"Pakistan\"                        \n[159] \"Palau\"                            \"Palestine\"                       \n[161] \"Panama\"                           \"Papua New Guinea\"                \n[163] \"Paraguay\"                         \"Peru\"                            \n[165] \"Philippines\"                      \"Poland\"                          \n[167] \"Portugal\"                         \"Puerto Rico\"                     \n[169] \"Qatar\"                            \"Romania\"                         \n[171] \"Russia\"                           \"Rwanda\"                          \n[173] \"Saint Kitts and Nevis\"            \"Saint Lucia\"                     \n[175] \"Saint Vincent and the Grenadines\" \"Samoa\"                           \n[177] \"San Marino\"                       \"Sao Tome and Principe\"           \n[179] \"Saudi Arabia\"                     \"Senegal\"                         \n[181] \"Serbia\"                           \"Seychelles\"                      \n[183] \"Sierra Leone\"                     \"Singapore\"                       \n[185] \"Sint Maarten (Dutch part)\"        \"Slovakia\"                        \n[187] \"Slovenia\"                         \"Solomon Islands\"                 \n[189] \"Somalia\"                          \"South Africa\"                    \n[191] \"South Asia\"                       \"South Korea\"                     \n[193] \"South Sudan\"                      \"Spain\"                           \n[195] \"Sri Lanka\"                        \"Sub-Saharan Africa\"              \n[197] \"Sudan\"                            \"Suriname\"                        \n[199] \"Sweden\"                           \"Switzerland\"                     \n[201] \"Syria\"                            \"Tajikistan\"                      \n[203] \"Tanzania\"                         \"Thailand\"                        \n[205] \"Timor\"                            \"Togo\"                            \n[207] \"Tonga\"                            \"Trinidad and Tobago\"             \n[209] \"Tunisia\"                          \"Turkey\"                          \n[211] \"Turkmenistan\"                     \"Turks and Caicos Islands\"        \n[213] \"Tuvalu\"                           \"Uganda\"                          \n[215] \"Ukraine\"                          \"United Arab Emirates\"            \n[217] \"United Kingdom\"                   \"United States\"                   \n[219] \"United States Virgin Islands\"     \"Upper middle income\"             \n[221] \"Uruguay\"                          \"Uzbekistan\"                      \n[223] \"Vanuatu\"                          \"Venezuela\"                       \n[225] \"Vietnam\"                          \"World\"                           \n[227] \"Yemen\"                            \"Zambia\"                          \n[229] \"Zimbabwe\"                        \n```\n:::\n\n```{.r .cell-code}\n# Identifying the data types of the columns\ntable(sapply(globalInternetUsers, function(x) typeof(x)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\ncharacter    double \n        2         6 \n```\n:::\n\n```{.r .cell-code}\nsapply(globalInternetUsers, class)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                  ...1                 Entity                   Code \n             \"numeric\"            \"character\"            \"character\" \n                  Year  Cellular Subscription      Internet Users(%) \n             \"numeric\"              \"numeric\"              \"numeric\" \n No. of Internet Users Broadband Subscription \n             \"numeric\"              \"numeric\" \n```\n:::\n:::\n\n\n3.  conduct summary statistics of the dataset(s); especially show the basic statistics (min, max, mean, median, etc.) for the variables you are interested in.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Summary statistics of the datasets \n\nsummary(globalInternetUsers$`Cellular Subscription`)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  0.000   0.000   5.501  39.990  82.232 436.103 \n```\n:::\n\n```{.r .cell-code}\nsummary(globalInternetUsers$`Internet Users(%)`)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. \n  0.0000   0.0000   0.8557  17.0436  25.4499 100.0000 \n```\n:::\n\n```{.r .cell-code}\nsummary(globalInternetUsers$`No. of Internet Users`)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. \n0.000e+00 0.000e+00 1.005e+04 1.089e+07 8.664e+05 4.700e+09 \n```\n:::\n\n```{.r .cell-code}\nsummary(globalInternetUsers$`Broadband Subscription`)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  0.000   0.000   0.000   4.441   2.008  78.524 \n```\n:::\n:::\n\n\n\nThis dataset consists of 229 countries, where each row represents the mobile phone subscription per 100 people(Cellular Subscription) along with percentage of internet users using the internet(Internet Users(%)), number of people using the internet(No. of Internet Users) and number of fixed broadband subscriptions per 100 people(Broadband Subscription) for a particular country(Entity) and an year. The dataset has the above mentioned information from the year 1980 to 2020 for all the 229 countries.\n\nThere are 8867 rows and 8 columns(\"...1\" , \"Entity\", \"Code\", \"Year\", \"Cellular Subscription\", \"Internet Users(%)\",    \"No. of Internet Users\", \"Broadband Subscription\") in total in the dataset.There are 2 character datatype columns - \"Entity\", \"Code\" and there are 6 numeric columns - \"...1\" , \"Entity\", \"Cellular Subscription\", \"Internet Users(%)\",    \"No. of Internet Users\", \"Broadband Subscription\".  Based on the summary statistics for the cellular subscription per 100 people, we can say that average is 39.990 with a maximum value as 436.103. The average value for the percentage of internet users is 17.0436% across all the years for the countries with a maximum value as 100%. The average value for the number of internet users is 1.005e+04 across all the years for the countries with a maximum value as 4.700e+09. The average value for the fixed Broadband Subscription is 4.441 across all the years for the countries with a maximum value as 78.524.\n\n\n## 3. The Tentative Plan for Visualization {#the-tentative-plan-for-visualization}\n\nWith a bivariate visualization the relationship between the variables can be clearly depicted. For example, the increase in usage of internet over the years can be visualized using Time Series. We can plot the evolution using ggplot2 and build an interactive Candlestick plot using dygraphs package. Likewise, the relationship between mobile phone subscriptions and internet users and the relationship between the fixed broadband subscriptions and internet users over the years can be depicted using correlogram. The GGALLY package has ggpairs() function that can build a classic correlogram with scatterplot to visualize the relationship between the aforementioned numeric variables. With the use of interactive Choropleth map with leaflet package we can build an interactive map in R to understand the number of internet users across the world in the past 10 years. \n\nThe data is tidy enough to conduct these visualizations. There are no null data and outliers in the dataset, which makes it easy to use it for data analysis and visualization. To visualize the number of internet users in the last 10 years, I would mutate the dataset by creating a new variable and store the average value of the number of internet users for ten years for each country. For visualizing the correlation between other numeric data, I would map the country and number of mobile phone subscriptions and internet users and visualize the correlation between them. I would do a similar visualization for fixed broadband subscriptions and internet users.",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}