{
  "hash": "006d50f9f302a01963c75dcafae1ea89",
  "result": {
    "markdown": "---\ntitle: \"Challenge 4\"\nauthor: \"Abhinav Reddy Yadatha\"\ndescription: \"More data wrangling: pivoting\"\ndate: \"05/06/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_4\n  - poultry_tidy\n  - Abhinav Reddy Yadatha\n\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(dplyr)\nlibrary(lubridate)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Challenge Overview\n\nToday's challenge is to:\n\n1)  read in a data set, and describe the data set using both words and any supporting information (e.g., tables, etc)\n2)  tidy data (as needed, including sanity checks)\n3)  identify variables that need to be mutated\n4)  mutate variables and sanity check all mutations\n\n## Read in data\n\nReading poultry_tidy.xlsx dataset.\n\n-   poultry_tidy.xlsx⭐⭐\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Reading the poultry dataset\npoultry_data <-readxl::read_excel(\"_data/poultry_tidy.xlsx\")\npoultry_data\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 600 × 4\n   Product  Year Month     Price_Dollar\n   <chr>   <dbl> <chr>            <dbl>\n 1 Whole    2013 January           2.38\n 2 Whole    2013 February          2.38\n 3 Whole    2013 March             2.38\n 4 Whole    2013 April             2.38\n 5 Whole    2013 May               2.38\n 6 Whole    2013 June              2.38\n 7 Whole    2013 July              2.38\n 8 Whole    2013 August            2.38\n 9 Whole    2013 September         2.38\n10 Whole    2013 October           2.38\n# ℹ 590 more rows\n```\n:::\n\n```{.r .cell-code}\n# Display the summary of the dataset\nsummary(poultry_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Product               Year         Month            Price_Dollar  \n Length:600         Min.   :2004   Length:600         Min.   :1.935  \n Class :character   1st Qu.:2006   Class :character   1st Qu.:2.150  \n Mode  :character   Median :2008   Mode  :character   Median :2.350  \n                    Mean   :2008                      Mean   :3.390  \n                    3rd Qu.:2011                      3rd Qu.:3.905  \n                    Max.   :2013                      Max.   :7.037  \n                                                      NA's   :7      \n```\n:::\n\n```{.r .cell-code}\n# Check for any empty/missing data\nna_data <- filter(poultry_data, is.na(Price_Dollar))\n\nna_data\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 7 × 4\n  Product         Year Month    Price_Dollar\n  <chr>          <dbl> <chr>           <dbl>\n1 Bone-in Breast  2004 January            NA\n2 Bone-in Breast  2004 February           NA\n3 Bone-in Breast  2004 March              NA\n4 Bone-in Breast  2004 April              NA\n5 Bone-in Breast  2004 May                NA\n6 Bone-in Breast  2004 June               NA\n7 Thighs          2004 January            NA\n```\n:::\n\n```{.r .cell-code}\n# Displaying all the unique poultry product names.\nunique(poultry_data$Product)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Whole\"          \"B/S Breast\"     \"Bone-in Breast\" \"Whole Legs\"    \n[5] \"Thighs\"        \n```\n:::\n:::\n\n\n### Briefly describe the data\n\nThe dataset contains 600 rows and four columns that span from 2004 to 2013. The columns represent various poultry products, including Whole, B/S Breast, Bone-in Breast, Whole Legs, and Thighs, and the corresponding prices range from 1.935 to 7.037 dollars. Upon reviewing the summary, it's evident that some of the prices are missing, particularly for product 7. Further analysis revealed that most of the missing values belong to the Bone-in Breast and Thighs products.\n\n## Tidy Data (as needed)\n\nIs your data already tidy, or is there work to be done? Be sure to anticipate your end result to provide a sanity check, and document your work here.\n\nThe data is already tidy. Although we have the option to remove the NA data, I believe it's essential to retain the rows with missing values as they contain other important column information\nAny additional comments?\n\n## Identify variables that need to be mutated\n\nAre there any variables that require mutation to be usable in your analysis stream? For example, are all time variables correctly coded as dates? Are all string variables reduced and cleaned to sensible categories? Do you need to turn any variables into factors and reorder for ease of graphics and visualization?\n\nDocument your work here.\n\n\nI believe that two mutations would be beneficial foe the analysis of the dataset. First, it can be observed that the prices are discrete values and it would be helpful if there were ranges so that the price can be categorized as high, low and medium.\nSecond, i believe that the variables year and month can be joined so that we can use it for analysis directly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Creating ranges for the prices to be categorized in ranges.\npoultry_data_mutated <- poultry_data %>%\n  mutate(Price_type = case_when(Price_Dollar < 3 ~ 'low',Price_Dollar < 5 ~ 'medium', Price_Dollar > 5 ~ 'high'))\n\n# Combining the year and the month.\npoultry_data_mutated <- poultry_data_mutated %>%\n        mutate(Date = ym(paste(Year, Month)))\n\npoultry_data_mutated\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 600 × 6\n   Product  Year Month     Price_Dollar Price_type Date      \n   <chr>   <dbl> <chr>            <dbl> <chr>      <date>    \n 1 Whole    2013 January           2.38 low        2013-01-01\n 2 Whole    2013 February          2.38 low        2013-02-01\n 3 Whole    2013 March             2.38 low        2013-03-01\n 4 Whole    2013 April             2.38 low        2013-04-01\n 5 Whole    2013 May               2.38 low        2013-05-01\n 6 Whole    2013 June              2.38 low        2013-06-01\n 7 Whole    2013 July              2.38 low        2013-07-01\n 8 Whole    2013 August            2.38 low        2013-08-01\n 9 Whole    2013 September         2.38 low        2013-09-01\n10 Whole    2013 October           2.38 low        2013-10-01\n# ℹ 590 more rows\n```\n:::\n\n```{.r .cell-code}\n# Displaying the unique values of Price_type column after the mutation.\nunique(poultry_data_mutated$Price_type)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"low\"    \"high\"   \"medium\" NA      \n```\n:::\n:::\n\n\nAny additional comments?\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}