{
  "hash": "a002e2c92b163eec00d5e165e0e0e57c",
  "result": {
    "markdown": "---\ntitle: \"Final Project: Neha Jhurani\"\nauthor: \"Neha Jhurani\"\ndescription: \"Project\"\ndate: \"06/16/2023\"\nformat:\n  html:\n    df-print: paged\n    toc: true\n    code-copy: true\n    code-tools: true\n    css: styles.css\ncategories:\n  - final_project\neditor_options: \n  chunk_output_type: console\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidyr)\nlibrary(dplyr)\nlibrary(scales)\nlibrary(ggplot2)\nlibrary(janitor)\nlibrary(rworldmap)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Part 1. Introduction\n\nThe main goal of this project is to identify the key causes that have had the greatest impact on global mortality rates from 1990 to 2019.\n\n**General Research Question:** What is the leading cause of death across the world (including people from all demographics)? How did the causes of death change over time and differ between different countries and world regions?\n\n**Dataset Description:** Our analysis relies on data obtained from The Global Burden of Disease, a comprehensive worldwide study that provides information on the annual number of deaths at the country level spanning the years 1990 to 2019. The dataset captures a broad spectrum of causes of death, encompassing communicable and non-communicable diseases, and injuries that contribute to mortality rates. Each row in the dataset corresponds to the annual deaths recorded for a specific country and cause for the mentioned year. It covers the entire demographic spectrum, enabling us to examine mortality trends across various population groups. By utilizing this extensive dataset, we can gain valuable insights into the factors influencing global mortality and explore how they have evolved over time.\n\n**Unit of Analysis:** Each row in the dataset represents the annual death numbers for the specific country during the mentioned year from the specified cause or disease. The dataset includes data for all people irrespective of their demographic characteristics.\n\n## Part 2. Literature Review\n\nThe **Global Burden of Disease (GBD)** initiative, launched by the World Health Organization (WHO) in collaboration with the World Bank and the Harvard School of Public Health, is a comprehensive effort to analyze and quantify the impact of diseases, injuries, and risk factors on global health. The causes of death dataset derived from this initiative provides valuable insights into global mortality patterns, enabling us to identify the leading causes of death and their distribution across different regions.\n\nBy understanding the specific causes of death, policymakers and public health professionals can prioritize interventions and allocate resources effectively. The dataset facilitates cross-country comparisons, revealing variations in causes of death and highlighting disparities in health outcomes. It serves as a vital tool for identifying successful interventions in specific regions and promoting best practices globally.\n\nMoreover, the causes of death dataset from the GBD initiative not only helps in generating a better understanding of the burden of diseases but also serves as a powerful advocacy tool. It aids in mobilizing resources, generating public support, and driving political action towards addressing the identified health issues. The dataset's comprehensive and rigorous assessment of global health burdens contributes to evidence-based decision-making and supports efforts to improve health outcomes worldwide.\n\n## Part 3. Dataset Introduction\n\nThe Global Burden of Disease is a major global study on the causes of death and disease published in the medical journal **The Lancet**. The dataset represents data for all demographic people from the year 1990 to 2019 as mentioned on their website. We extract our data from this source.\n\nThe dataset includes data on country level. Every row in the dataset mentions the annual death numbers attributed to each of the cause for the specified country during the mentioned year.\n\n## Part 4. Dataset Description\n\nThe dataset contains data for all countries (globally) across time period 1990 to 2019. It has 200,772 rows and 6 columns, i.e., it covers a wide range of causes of death for various countries from the year 1990 to 2019. \n\nExploring the variables present in the dataset:\n\nCauses name - This represents the cause of death. This can be a disease or a natural phenomena or a legal action\n\nCauses Full Description - This represents if the death is in all age groups or in a particular set of age groups, and weather it is in all the genders or in specific gender. In the dataset that we are using, we can see that all the data is mentioned for all ages and genders. \n\nDeath Numbers - This represents the annual number of deaths for specific value of cause, year and country\n\nEntity - This represents the name of the country in which the deaths occurred.\n\nCode - This represents the ISO Code of the country in which deaths occurred\n\nYear - This represents the year in which the deaths occurred.\n\n**Coding Component:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readr)\ndeath_dataset <- read_csv(\"NehaJhurani_FinalProjectData/CausesOfDeath.csv\")\n\n#Dimensions of Global Death Dataset\n\ndim(death_dataset)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 200772      6\n```\n:::\n\n```{.r .cell-code}\n#Columns of death dataset\n\ncolnames(death_dataset)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Causes name\"             \"Causes Full Description\"\n[3] \"Death Numbers\"           \"Entity\"                 \n[5] \"Code\"                    \"Year\"                   \n```\n:::\n\n```{.r .cell-code}\n#Viewing first few rows of the dataset\n\nhead(death_dataset)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Causes name\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Causes Full Description\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Death Numbers\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Entity\"],\"name\":[4],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Code\"],\"name\":[5],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Year\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Meningitis\",\"2\":\"Deaths - Meningitis - Sex: Both - Age: All Ages (Number)\",\"3\":\"2933\",\"4\":\"Afghanistan\",\"5\":\"AFG\",\"6\":\"2007\"},{\"1\":\"Neoplasms\",\"2\":\"Deaths - Neoplasms - Sex: Both - Age: All Ages (Number)\",\"3\":\"15925\",\"4\":\"Afghanistan\",\"5\":\"AFG\",\"6\":\"2007\"},{\"1\":\"Fire, heat, and hot substances\",\"2\":\"Deaths - Fire, heat, and hot substances - Sex: Both - Age: All Ages (Number)\",\"3\":\"481\",\"4\":\"Afghanistan\",\"5\":\"AFG\",\"6\":\"2007\"},{\"1\":\"Malaria\",\"2\":\"Deaths - Malaria - Sex: Both - Age: All Ages (Number)\",\"3\":\"393\",\"4\":\"Afghanistan\",\"5\":\"AFG\",\"6\":\"2007\"},{\"1\":\"Drowning\",\"2\":\"Deaths - Drowning - Sex: Both - Age: All Ages (Number)\",\"3\":\"2127\",\"4\":\"Afghanistan\",\"5\":\"AFG\",\"6\":\"2007\"},{\"1\":\"Interpersonal violence\",\"2\":\"Deaths - Interpersonal violence - Sex: Both - Age: All Ages (Number)\",\"3\":\"3657\",\"4\":\"Afghanistan\",\"5\":\"AFG\",\"6\":\"2007\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\n#summary of each of the columns in the dataset\n\nsummary(death_dataset)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Causes name        Causes Full Description Death Numbers    \n Length:200772      Length:200772           Min.   :      0  \n Class :character   Class :character        1st Qu.:     14  \n Mode  :character   Mode  :character        Median :    209  \n                                            Mean   :   7712  \n                                            3rd Qu.:   1860  \n                                            Max.   :4584273  \n                                            NA's   :11127    \n    Entity              Code                Year     \n Length:200772      Length:200772      Min.   :1990  \n Class :character   Class :character   1st Qu.:1997  \n Mode  :character   Mode  :character   Median :2004  \n                                       Mean   :2004  \n                                       3rd Qu.:2012  \n                                       Max.   :2019  \n                                                     \n```\n:::\n:::\n\n\nThe mean number of annual deaths across countries during the years 1990 to 2019 is around 7712. We can also see that there are 11,127 NAs in Death Numbers. We will further analyze the statistics in the data preprocessing section.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#different causes of death included in the dataset\n\nunique(death_dataset$'Causes name')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"Meningitis\"                                  \n [2] \"Neoplasms\"                                   \n [3] \"Fire, heat, and hot substances\"              \n [4] \"Malaria\"                                     \n [5] \"Drowning\"                                    \n [6] \"Interpersonal violence\"                      \n [7] \"HIV/AIDS\"                                    \n [8] \"Drug use disorders\"                          \n [9] \"Tuberculosis\"                                \n[10] \"Road injuries\"                               \n[11] \"Maternal disorders\"                          \n[12] \"Lower respiratory infections\"                \n[13] \"Neonatal disorders\"                          \n[14] \"Alcohol use disorders\"                       \n[15] \"Exposure to forces of nature\"                \n[16] \"Diarrheal diseases\"                          \n[17] \"Environmental heat and cold exposure\"        \n[18] \"Nutritional deficiencies\"                    \n[19] \"Self-harm\"                                   \n[20] \"Conflict and terrorism\"                      \n[21] \"Diabetes mellitus\"                           \n[22] \"Poisonings\"                                  \n[23] \"Protein-energy malnutrition\"                 \n[24] \"Terrorism (deaths)\"                          \n[25] \"Cardiovascular diseases\"                     \n[26] \"Chronic kidney disease\"                      \n[27] \"Chronic respiratory diseases\"                \n[28] \"Cirrhosis and other chronic liver diseases\"  \n[29] \"Digestive diseases\"                          \n[30] \"Acute hepatitis\"                             \n[31] \"Alzheimer's disease and other dementias\"     \n[32] \"Parkinson's disease\"                         \n[33] \"Number of executions (Amnesty International)\"\n```\n:::\n:::\n\n\nWe can see that there are 33 different causes of death showed across countries in the world. These causes include communicable diseases (such as HIV/AIDS, malaria, etc), non-communicable diseases (such as cancers, diabetes, etc), and injuries (such as road accidents, natural disasters, etc). \n\n\n::: {.cell}\n\n```{.r .cell-code}\n#renaming the columns for better understanding and for making it more accessible\n\ndeath_dataset <- death_dataset %>%  \n    rename(Country = `Entity`,\n           Cause = 'Causes name',\n           NumberOfDeaths = 'Death Numbers') %>%  \n    as.data.frame()\nhead(death_dataset)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Cause\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Causes Full Description\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"NumberOfDeaths\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Country\"],\"name\":[4],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Code\"],\"name\":[5],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Year\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Meningitis\",\"2\":\"Deaths - Meningitis - Sex: Both - Age: All Ages (Number)\",\"3\":\"2933\",\"4\":\"Afghanistan\",\"5\":\"AFG\",\"6\":\"2007\",\"_rn_\":\"1\"},{\"1\":\"Neoplasms\",\"2\":\"Deaths - Neoplasms - Sex: Both - Age: All Ages (Number)\",\"3\":\"15925\",\"4\":\"Afghanistan\",\"5\":\"AFG\",\"6\":\"2007\",\"_rn_\":\"2\"},{\"1\":\"Fire, heat, and hot substances\",\"2\":\"Deaths - Fire, heat, and hot substances - Sex: Both - Age: All Ages (Number)\",\"3\":\"481\",\"4\":\"Afghanistan\",\"5\":\"AFG\",\"6\":\"2007\",\"_rn_\":\"3\"},{\"1\":\"Malaria\",\"2\":\"Deaths - Malaria - Sex: Both - Age: All Ages (Number)\",\"3\":\"393\",\"4\":\"Afghanistan\",\"5\":\"AFG\",\"6\":\"2007\",\"_rn_\":\"4\"},{\"1\":\"Drowning\",\"2\":\"Deaths - Drowning - Sex: Both - Age: All Ages (Number)\",\"3\":\"2127\",\"4\":\"Afghanistan\",\"5\":\"AFG\",\"6\":\"2007\",\"_rn_\":\"5\"},{\"1\":\"Interpersonal violence\",\"2\":\"Deaths - Interpersonal violence - Sex: Both - Age: All Ages (Number)\",\"3\":\"3657\",\"4\":\"Afghanistan\",\"5\":\"AFG\",\"6\":\"2007\",\"_rn_\":\"6\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nUsing a bar graph to represent the total death numbers from 1990 to 2019 for every disease or cause.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Number of NAs in the number of deaths column\n\nsum(is.na(death_dataset$NumberOfDeaths))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 11127\n```\n:::\n\n```{.r .cell-code}\n#grouping the data by cause and finding the number of deaths for each cause from the year 1990 to 2019\n\n#ignoring NA values for this initial graph as this graph is generated for representing/visualizing data in a simpler and understandable format. Further analyzes of why there are NAs in the dataset is done in the later sections.\n\nfrequency_of_causes <- death_dataset%>%\ngroup_by(Cause) %>%\nsummarise(deaths = sum(NumberOfDeaths, na.rm=TRUE))\n\n#Ordering the data in the order of the number of deaths it causes\n\nfrequency_of_causes$Cause <- factor(frequency_of_causes$Cause, levels = frequency_of_causes$Cause[order(frequency_of_causes$deaths)])\n\n#the below command helps us avoid showing frequency in exponential/scientific notation\n\noptions(scipen = 999)\n\n#using ggplot2 to show a pictorial representation of data as a histogram\n\nggplot(frequency_of_causes) + \n  geom_bar(aes(x=deaths, y=Cause), stat=\"identity\", color=\"black\", fill = \"pink\") + \n  scale_x_continuous(labels = label_number(suffix = \" M\", scale = 1e-6)) +\n  labs(title = \"Death frequency for all causes\", \n       subtitle = \"1990 - 2019\", \n       x = \"Number of Deaths (in millions)\", \n       y = \"Cause of Death\")\n```\n\n::: {.cell-output-display}\n![](NehaJhurani_FinalProject_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nWe can see from the above bar graph that the highest number of deaths during those years are due to cardiovascular diseases. \n\n**Data Preprocessing:**\n\na) We have already renamed few columns of our data above for better understanding.\n\nb) Many ISO Codes are missing. As this is same as Country Name that is represented by Entity (which is non null), we will drop Code column.\n\nc) Dropping 'Causes Full Description' because that column mentions that the data is for all age groups and genders. We observed that there are only 33 unique values for the column (same as that of Causes column) and all mention that they are for all age groups and genders. As all of the data are for the same demographic people, having this column is redundant or unnecessary.\n\nd) We saw above that Number of deaths are missing in a lot of rows. GBD study provides detailed information about the data sources used, the methodology employed and any known data gaps or limitations. Further researching on GBD study, the following are the possible reasons why we see missing or NA values for number of deaths in GBD study. \n\n    - There are limitations in data collection processes in countries with limited healthcare infrastructure. This has lead to incomplete death reporting, lack of standardized tests, etc. \n\n    - Vital registration systems, which records births, death, and causes of death, may be less developed or incomplete in some countries. So, lack of reporting system can lead to missing values.\n\n    - The source of data is of inadequate quality or is unreliable.\n\n    - Access to mortality data may be restricted due to legal or privacy considerations, especially in cases where individual-level data is involved. This can result in missing values for specific years or regions.\n\n    - As the study is dynamic and ever evolving, delay in reporting can also lead to NA or missing values.\n\n    For our analysis we will drop those rows. This is because we are more concerned about analyzing the established causes of death rather than analyzing the gaps in the data collection. Also, Dropping the rows is more appropriate than making them 0 because there are no deaths for that particular cause or that particular cause of death is non existent describes the same case. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n#extracting the unique values of Causes Full Description column\n\nunique(death_dataset$`Causes Full Description`)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"Deaths - Meningitis - Sex: Both - Age: All Ages (Number)\"                                \n [2] \"Deaths - Neoplasms - Sex: Both - Age: All Ages (Number)\"                                 \n [3] \"Deaths - Fire, heat, and hot substances - Sex: Both - Age: All Ages (Number)\"            \n [4] \"Deaths - Malaria - Sex: Both - Age: All Ages (Number)\"                                   \n [5] \"Deaths - Drowning - Sex: Both - Age: All Ages (Number)\"                                  \n [6] \"Deaths - Interpersonal violence - Sex: Both - Age: All Ages (Number)\"                    \n [7] \"Deaths - HIV/AIDS - Sex: Both - Age: All Ages (Number)\"                                  \n [8] \"Deaths - Drug use disorders - Sex: Both - Age: All Ages (Number)\"                        \n [9] \"Deaths - Tuberculosis - Sex: Both - Age: All Ages (Number)\"                              \n[10] \"Deaths - Road injuries - Sex: Both - Age: All Ages (Number)\"                             \n[11] \"Deaths - Maternal disorders - Sex: Both - Age: All Ages (Number)\"                        \n[12] \"Deaths - Lower respiratory infections - Sex: Both - Age: All Ages (Number)\"              \n[13] \"Deaths - Neonatal disorders - Sex: Both - Age: All Ages (Number)\"                        \n[14] \"Deaths - Alcohol use disorders - Sex: Both - Age: All Ages (Number)\"                     \n[15] \"Deaths - Exposure to forces of nature - Sex: Both - Age: All Ages (Number)\"              \n[16] \"Deaths - Diarrheal diseases - Sex: Both - Age: All Ages (Number)\"                        \n[17] \"Deaths - Environmental heat and cold exposure - Sex: Both - Age: All Ages (Number)\"      \n[18] \"Deaths - Nutritional deficiencies - Sex: Both - Age: All Ages (Number)\"                  \n[19] \"Deaths - Self-harm - Sex: Both - Age: All Ages (Number)\"                                 \n[20] \"Deaths - Conflict and terrorism - Sex: Both - Age: All Ages (Number)\"                    \n[21] \"Deaths - Diabetes mellitus - Sex: Both - Age: All Ages (Number)\"                         \n[22] \"Deaths - Poisonings - Sex: Both - Age: All Ages (Number)\"                                \n[23] \"Deaths - Protein-energy malnutrition - Sex: Both - Age: All Ages (Number)\"               \n[24] \"Deaths - Terrorism (deaths) ---\"                                                         \n[25] \"Deaths - Cardiovascular diseases - Sex: Both - Age: All Ages (Number)\"                   \n[26] \"Deaths - Chronic kidney disease - Sex: Both - Age: All Ages (Number)\"                    \n[27] \"Deaths - Chronic respiratory diseases - Sex: Both - Age: All Ages (Number)\"              \n[28] \"Deaths - Cirrhosis and other chronic liver diseases - Sex: Both - Age: All Ages (Number)\"\n[29] \"Deaths - Digestive diseases - Sex: Both - Age: All Ages (Number)\"                        \n[30] \"Deaths - Acute hepatitis - Sex: Both - Age: All Ages (Number)\"                           \n[31] \"Deaths - Alzheimer's disease and other dementias - Sex: Both - Age: All Ages (Number)\"   \n[32] \"Deaths - Parkinson's disease - Sex: Both - Age: All Ages (Number)\"                       \n[33] \"Deaths - Number of executions (Amnesty International) ---\"                               \n```\n:::\n\n```{.r .cell-code}\ndeath_dataset <- death_dataset %>%  \n    select(-c(`Causes Full Description`, `Code`)) %>% \n    as.data.frame()\nhead(death_dataset)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Cause\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"NumberOfDeaths\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Country\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Year\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Meningitis\",\"2\":\"2933\",\"3\":\"Afghanistan\",\"4\":\"2007\",\"_rn_\":\"1\"},{\"1\":\"Neoplasms\",\"2\":\"15925\",\"3\":\"Afghanistan\",\"4\":\"2007\",\"_rn_\":\"2\"},{\"1\":\"Fire, heat, and hot substances\",\"2\":\"481\",\"3\":\"Afghanistan\",\"4\":\"2007\",\"_rn_\":\"3\"},{\"1\":\"Malaria\",\"2\":\"393\",\"3\":\"Afghanistan\",\"4\":\"2007\",\"_rn_\":\"4\"},{\"1\":\"Drowning\",\"2\":\"2127\",\"3\":\"Afghanistan\",\"4\":\"2007\",\"_rn_\":\"5\"},{\"1\":\"Interpersonal violence\",\"2\":\"3657\",\"3\":\"Afghanistan\",\"4\":\"2007\",\"_rn_\":\"6\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\ndeath_dataset <- death_dataset%>%drop_na('NumberOfDeaths')\n\n#Checking if all NA values rows are dropped\n\nsum(is.na(death_dataset$NumberOfDeaths))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0\n```\n:::\n:::\n\n\n## Part 5. Analysis Plan\n\nWe will analyze the above dataset to answer the following granular questions:\n\n- What is the distribution of deaths globally from the year 1990 to 2019?\n\n- What is the proportion of global deaths contributed by each group of diseases (communicable, non-communicable, and injuries) as a percentage from 1990 to 2019?\n\n- Which countries consistently report the highest number of deaths each year?\n\n- Which countries consistently report the lowest number of deaths each year?\n\n- Which cause of death had the highest prevalence globally during the time period from 1990 to 2019?\n\n- For a selection of countries with both the highest and lowest number of deaths, what was the trend in the occurrence of the three most common causes of death from 1990 to 2019?\n\n- How does the prevalence of mental illness correlate with the number of deaths over the years in a selection of countries with both the highest and lowest mortality rates?\n\n- How does the distribution of deaths vary globally for the leading cause of death during the year with the highest number of deaths?\n\n**Analysis Plan:**\n\nTo answer the research questions mentioned above, I plan to use a combination of visualization techniques and data analysis.\n\n**Data analysis** helps by providing insights, identifying patterns, making informed decisions, solving problems, measuring performance, predicting outcomes, and promoting evidence-based decision-making.\n\nFrequency of deaths analyses: I will group the data by year and calculate the total number of deaths for each year from 1990 to 2019.\n\nFrequency of causes of death analyzes: I will group the data by cause and calculate the total number of deaths for each cause across the years 1990 to 2019.\n\nGroup causes of death analyzes - To analyze the contribution of different cause groups (communicable, non-communicable, injuries) to overall deaths, I will use the janitor library to group the data by year and calculate the proportion of deaths attributed to each group.\n\nFrequency of specific cause of death analyzes -  I will extract the data for the mentioned cause, group it by year and country, and calculate the number of deaths.\n\n**Visualization techniques**, such as graphs, charts, and diagrams, can simplify complex concepts, patterns, or relationships, making them easier to understand and comprehend. They help us identify patterns, trends, and anomalies in data more easily. We will be using the following types of graph for our project:\n\n- *Bivariate and Multivariate Graphs:* They allow us to identify the nature of the relationship between two or more variables. We can determine if the variables are positively or negatively correlated, or if there is no apparent relationship between them. Scatter plot and line plots are used to represent them. I will be using these graphs to find the relations between the time-period and the number of deaths across countries and diseases.\n\n- *Histogram and Bar Graphs:* They provide a visual representation of the distribution of data, allowing us to observe the shape, center, and spread of the variable. I will be using these to represent the most common diseases across countries and the number of deaths globally for every year from 1990 to 2019.\n\n- *Ribbon and area plot:* They help visualize the distribution and relative proportions of different categories or variables over a given time period or across different groups. I will use this to visualize the contribution of each of the group of causes (communicable, non-communicable and injuries) in the total number of deaths.\n\n- *Map graph:* A map graph helps visualize geographic data and reveals spatial patterns, distributions, and variations across regions or countries. It enables the identification of hotspots, regional differences, and concentration of specific attributes or variables on a map. By utilizing a map graph, I will effectively visualize the distribution of deaths attributed to the leading cause during the year with the highest number of deaths. This visualization will provide valuable insights into the geographic impact of the leading cause of death.\n\n## Part 6. Statistical Analysis and Visualizations\n\n**Research question answered - ** *What is the distribution of deaths globally from the year 1990 to 2019?*\n\nGenerating a line graph to visually depict the changing pattern of global deaths over the time period from 1990 to 2019.\n\n::: {.cell}\n\n```{.r .cell-code}\ndeath_dataset %>%\n  group_by(Year)%>%\n  summarise(deaths = sum(NumberOfDeaths))%>%\n  ggplot(aes(x = Year, y = deaths)) + \n  geom_point(alpha = 1) + \n  geom_smooth(se = F, span = 0.2) + \n  scale_y_continuous(labels = label_number(suffix = \" M\", scale = 1e-6)) +\n  scale_x_continuous(breaks = seq(1990, 2019, 3), minor_breaks = T) + \n  labs(title = \"Distribution of deaths globally from the year 1990 to 2019\", \n       x = \"Year\", \n       y = \"Number of Deaths (in millions)\", \n       col = \"Country\")\n```\n\n::: {.cell-output-display}\n![](NehaJhurani_FinalProject_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\nThe data reveals a clear and consistent trend of a substantial increase in the number of deaths over the years, with the lowest count recorded in 1990 (approximately 43.39 million) and the highest count observed in 2019 (approximately 54.18 million). This upward trajectory highlights a significant rise in mortality rates over the analyzed period.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Total number of deaths from 1990 to 2019\n\nsum(death_dataset$NumberOfDeaths)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1462523465\n```\n:::\n:::\n\nThe cumulative number of deaths worldwide, spanning the years 1990 to 2019, amounts to approximately 1.46 billion individuals.\n\n**Research question answered -** *What is the proportion of global deaths contributed by each group of diseases (communicable, non-communicable, and injuries) as a percentage from 1990 to 2019?*\n\nTo analyze the contribution of different disease categories to the highest number of deaths across countries from 1990 to 2019, the dataset can be divided into three groups:\n\n1. *Communicable diseases (infectious diseases)*: This group includes Meningitis, Malaria, Tuberculosis, Lower respiratory infections, and HIV/AIDS. These diseases are caused by pathogens and can spread from person to person.\n\n2. *Non-communicable diseases*: This category comprises chronic and long-term illnesses such as Neoplasms (cancer), Maternal disorders, Neonatal disorders, Alcohol use disorders, Diabetes mellitus, Cardiovascular diseases, Chronic kidney disease, Chronic respiratory diseases, Cirrhosis and other chronic liver diseases, Digestive diseases, Alzheimer's disease and other dementias, and Parkinson's disease. Non-communicable diseases typically develop over time and are not contagious.\n\n3. *Injuries*: This group includes causes related to accidents, violence, and self-harm. It consists of Fire, heat, and hot substances, Drowning, Interpersonal violence, Road injuries, Exposure to forces of nature, Environmental heat and cold exposure, Self-harm, Poisonings, Terrorism (deaths), Acute hepatitis, and Number of executions (Amnesty International).\n\nBy categorizing the dataset into these three groups, we can analyze and determine which type of disease contributes the most to the highest number of deaths across countries during the period from 1990 to 2019.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# First we would divide the dataset into 3 sub datasets\n\n#extracting rows which has a communicable disease as the cause of death\n\ncommunicable_disease_death_dataset <- death_dataset[death_dataset$Cause== (alist('Meningitis', 'Malaria', 'Tuberculosis', 'Lower respiratory infections', 'HIV/AIDS')),]\n\n#extracting rows which has a non - communicable disease as the cause of death\n\nnon_communicable_disease_death_dataset <- death_dataset[death_dataset$Cause== (alist('Neoplasms', 'Maternal disorders', 'Neonatal disorders', 'Alcohol use disorders', 'Diabetes mellitus', 'Cardiovascular diseases', 'Chronic kidney disease', 'Chronic respiratory diseases', 'Cirrhosis and other chronic liver diseases', 'Digestive diseases', \"Alzheimer's disease and other dementias\", \"Parkinson's disease\")),]\n\n#extracting rows which has injuries as the cause of death\n\ninjuries_death_dataset <- death_dataset[death_dataset$Cause== (alist('Fire, heat, and hot substances', 'Drowning', 'Interpersonal violence', 'Road injuries', 'Exposure to forces of nature', 'Environmental heat and cold exposure', 'Self-harm', 'Poisonings', 'Terrorism (deaths)', 'Acute hepatitis', 'Number of executions (Amnesty International)')),]\n\n#Getting total number of deaths for every individual year from 1990 to 2019 for all 3 groups of diseases\n\ncommunicable_disease_death_dataset <- communicable_disease_death_dataset %>%\n  group_by(Year)%>%\n  summarise(deaths_due_to_communicable_diseases = sum(NumberOfDeaths))\n\nnon_communicable_disease_death_dataset <- non_communicable_disease_death_dataset %>%\n  group_by(Year)%>%\n  summarise(deaths_due_to_non_communicable_diseases = sum(NumberOfDeaths))\n\ninjuries_death_dataset <- injuries_death_dataset %>%\n  group_by(Year)%>%\n  summarise(deaths_due_to_injuries = sum(NumberOfDeaths))\n\n#joining all the three tables created above to analyze it further\n\nintermiddent_joined_table <- full_join(x = communicable_disease_death_dataset, y= non_communicable_disease_death_dataset, by = 'Year')\n\ndisease_group_death_dataset <- full_join(x = intermiddent_joined_table, y = injuries_death_dataset, by = 'Year')\n\n# Generating the percentage of deaths contributed by each of the group of causes of deaths worldwide from the years 1990 to 2019 - communicable, non-communicable and injuries.\n\ndisease_group_death_dataset <- disease_group_death_dataset %>% \n  adorn_percentages(denominator = \"row\") %>% \n  adorn_pct_formatting(digits = 2)\n\n#converting percentages as numeric\n\ndisease_group_death_dataset$deaths_due_to_communicable_diseases <- as.numeric(sub(\"%\", \"\", disease_group_death_dataset$deaths_due_to_communicable_diseases))\n\ndisease_group_death_dataset$deaths_due_to_non_communicable_diseases <- as.numeric(sub(\"%\", \"\", disease_group_death_dataset$deaths_due_to_non_communicable_diseases))\n\ndisease_group_death_dataset$deaths_due_to_injuries <- as.numeric(sub(\"%\", \"\", disease_group_death_dataset$deaths_due_to_injuries))\n\n#calculating cumulative death numbers for communicable and non-communicable diseases for all the years\n\ndisease_group_death_dataset$cummulative_deaths <- disease_group_death_dataset$deaths_due_to_non_communicable_diseases + disease_group_death_dataset$deaths_due_to_communicable_diseases\n\n#Creating a graph to represent the percentage of deaths contributed by each of the disease or cause group globally over the years 1990 to 2019\n\nggplot(disease_group_death_dataset, aes(x = Year)) + \n  geom_point(aes(y = deaths_due_to_communicable_diseases)) +\n  geom_smooth(se=FALSE, method =\"lm\", aes(x = Year, y = deaths_due_to_communicable_diseases)) +\n  \n  geom_point(aes(y = cummulative_deaths)) +\n  geom_smooth(se=FALSE, method =\"lm\", aes(x = Year, y = cummulative_deaths)) +\n\n  #shading the regions for better visualizations\n  \n  geom_ribbon(aes(x = Year,\n                  ymin = 0,\n                  ymax = predict(loess(deaths_due_to_communicable_diseases~Year))),\n              fill = \"pink\") +\n  \n  geom_ribbon(aes(x = Year,\n                  ymin = predict(loess(deaths_due_to_communicable_diseases~Year)),\n                  ymax = predict(loess(cummulative_deaths~Year))),\n              fill = \"lightblue\") +\n  \n  geom_ribbon(aes(x = Year,\n                  ymin = predict(loess(cummulative_deaths~Year)),\n                  ymax = 100),\n              fill = \"lightgreen\") +\n\n  scale_x_continuous(breaks = seq(1990, 2019, 5), minor_breaks = T) + \n  scale_y_continuous(breaks = seq(0, 100, 20)) + \n  labs(title = \"Percentage of deaths contributed by the group of diseases\", \n       subtitle = \"1990 - 2019\", \n       x = \"Year\", \n       y = \"Percentage of Deaths\") +\n  annotate(\"text\", x = 2000, y=20, label= \"Deaths due to communicable diseases\", fontface = 3) +\n  annotate(\"text\", x = 2000, y=60, label= \"Deaths due to non communicable diseases\", fontface = 3) +\n  annotate(\"text\", x = 2000, y=97, label= \"Deaths due to injuries\", fontface = 3) \n```\n\n::: {.cell-output-display}\n![](NehaJhurani_FinalProject_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nThe observed ribbon and area plot indicate that non-communicable diseases (NCDs) are the leading cause of death globally. This trend can be attributed to various factors associated with societal development and improved living conditions. As countries progress, there is a shift in disease patterns characterized by a decline in infectious diseases and a rise in chronic conditions. This shift can be attributed to several demographic and lifestyle changes, including an aging population, urbanization, unhealthy diets, and increased tobacco and alcohol use.\n\nThe decrease in the proportion of deaths due to communicable diseases can be attributed to global efforts focused on prevention, treatment, and control. Vaccination programs, improved sanitation, and enhanced access to healthcare have played a crucial role in reducing the impact of infectious diseases. These measures have resulted in a decline in communicable diseases as a significant cause of mortality in many countries.\n\nFurthermore, there has been a notable decrease in deaths caused by injuries in recent years. This decline can be attributed to a combination of factors and interventions. Countries have implemented measures to improve road safety, including stricter traffic regulations, enhanced infrastructure, and public awareness campaigns. Advancements in emergency medical services and trauma care have contributed to improved outcomes for individuals with severe injuries. Workplace safety regulations and enforcement have also played a role in reducing work-related injuries. Additionally, public health interventions focusing on access to clean water, sanitation, and hygiene practices have contributed to a decrease in injuries caused by environmental factors.\n\nOverall, the observed trends reflect the complex interplay between societal development, public health interventions, and advancements in healthcare that have collectively contributed to the decreasing proportion of deaths due to communicable diseases and injuries, while non-communicable diseases remain the leading cause of death globally.\n\nTo represent the data in a more *structured and tidy* format, we organize the data with key-value pairs across multiple column values (converting wide format data to long format):\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngather(disease_group_death_dataset, key = \"GroupOfDisease\", value = \"PercentageOfDeathsContributed\", deaths_due_to_communicable_diseases, deaths_due_to_non_communicable_diseases, deaths_due_to_injuries)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Year\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"cummulative_deaths\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"GroupOfDisease\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"PercentageOfDeathsContributed\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"1990\",\"2\":\"92.80\",\"3\":\"deaths_due_to_communicable_diseases\",\"4\":\"23.48\"},{\"1\":\"1991\",\"2\":\"92.66\",\"3\":\"deaths_due_to_communicable_diseases\",\"4\":\"33.03\"},{\"1\":\"1992\",\"2\":\"94.64\",\"3\":\"deaths_due_to_communicable_diseases\",\"4\":\"38.94\"},{\"1\":\"1993\",\"2\":\"86.44\",\"3\":\"deaths_due_to_communicable_diseases\",\"4\":\"49.27\"},{\"1\":\"1994\",\"2\":\"89.25\",\"3\":\"deaths_due_to_communicable_diseases\",\"4\":\"42.28\"},{\"1\":\"1995\",\"2\":\"92.76\",\"3\":\"deaths_due_to_communicable_diseases\",\"4\":\"45.17\"},{\"1\":\"1996\",\"2\":\"95.48\",\"3\":\"deaths_due_to_communicable_diseases\",\"4\":\"33.01\"},{\"1\":\"1997\",\"2\":\"89.81\",\"3\":\"deaths_due_to_communicable_diseases\",\"4\":\"43.87\"},{\"1\":\"1998\",\"2\":\"95.63\",\"3\":\"deaths_due_to_communicable_diseases\",\"4\":\"46.35\"},{\"1\":\"1999\",\"2\":\"92.21\",\"3\":\"deaths_due_to_communicable_diseases\",\"4\":\"28.52\"},{\"1\":\"2000\",\"2\":\"90.52\",\"3\":\"deaths_due_to_communicable_diseases\",\"4\":\"41.05\"},{\"1\":\"2001\",\"2\":\"92.31\",\"3\":\"deaths_due_to_communicable_diseases\",\"4\":\"48.53\"},{\"1\":\"2002\",\"2\":\"96.84\",\"3\":\"deaths_due_to_communicable_diseases\",\"4\":\"30.01\"},{\"1\":\"2003\",\"2\":\"87.86\",\"3\":\"deaths_due_to_communicable_diseases\",\"4\":\"34.59\"},{\"1\":\"2004\",\"2\":\"85.53\",\"3\":\"deaths_due_to_communicable_diseases\",\"4\":\"43.64\"},{\"1\":\"2005\",\"2\":\"93.37\",\"3\":\"deaths_due_to_communicable_diseases\",\"4\":\"25.82\"},{\"1\":\"2006\",\"2\":\"93.83\",\"3\":\"deaths_due_to_communicable_diseases\",\"4\":\"40.57\"},{\"1\":\"2007\",\"2\":\"88.92\",\"3\":\"deaths_due_to_communicable_diseases\",\"4\":\"34.10\"},{\"1\":\"2008\",\"2\":\"90.71\",\"3\":\"deaths_due_to_communicable_diseases\",\"4\":\"48.86\"},{\"1\":\"2009\",\"2\":\"95.58\",\"3\":\"deaths_due_to_communicable_diseases\",\"4\":\"33.95\"},{\"1\":\"2010\",\"2\":\"85.07\",\"3\":\"deaths_due_to_communicable_diseases\",\"4\":\"28.97\"},{\"1\":\"2011\",\"2\":\"92.29\",\"3\":\"deaths_due_to_communicable_diseases\",\"4\":\"27.92\"},{\"1\":\"2012\",\"2\":\"90.31\",\"3\":\"deaths_due_to_communicable_diseases\",\"4\":\"55.83\"},{\"1\":\"2013\",\"2\":\"96.65\",\"3\":\"deaths_due_to_communicable_diseases\",\"4\":\"22.19\"},{\"1\":\"2014\",\"2\":\"95.16\",\"3\":\"deaths_due_to_communicable_diseases\",\"4\":\"37.23\"},{\"1\":\"2015\",\"2\":\"94.55\",\"3\":\"deaths_due_to_communicable_diseases\",\"4\":\"25.34\"},{\"1\":\"2016\",\"2\":\"91.51\",\"3\":\"deaths_due_to_communicable_diseases\",\"4\":\"21.05\"},{\"1\":\"2017\",\"2\":\"95.77\",\"3\":\"deaths_due_to_communicable_diseases\",\"4\":\"38.98\"},{\"1\":\"2018\",\"2\":\"97.59\",\"3\":\"deaths_due_to_communicable_diseases\",\"4\":\"29.90\"},{\"1\":\"2019\",\"2\":\"96.16\",\"3\":\"deaths_due_to_communicable_diseases\",\"4\":\"9.65\"},{\"1\":\"1990\",\"2\":\"92.80\",\"3\":\"deaths_due_to_non_communicable_diseases\",\"4\":\"69.32\"},{\"1\":\"1991\",\"2\":\"92.66\",\"3\":\"deaths_due_to_non_communicable_diseases\",\"4\":\"59.63\"},{\"1\":\"1992\",\"2\":\"94.64\",\"3\":\"deaths_due_to_non_communicable_diseases\",\"4\":\"55.70\"},{\"1\":\"1993\",\"2\":\"86.44\",\"3\":\"deaths_due_to_non_communicable_diseases\",\"4\":\"37.17\"},{\"1\":\"1994\",\"2\":\"89.25\",\"3\":\"deaths_due_to_non_communicable_diseases\",\"4\":\"46.97\"},{\"1\":\"1995\",\"2\":\"92.76\",\"3\":\"deaths_due_to_non_communicable_diseases\",\"4\":\"47.59\"},{\"1\":\"1996\",\"2\":\"95.48\",\"3\":\"deaths_due_to_non_communicable_diseases\",\"4\":\"62.47\"},{\"1\":\"1997\",\"2\":\"89.81\",\"3\":\"deaths_due_to_non_communicable_diseases\",\"4\":\"45.94\"},{\"1\":\"1998\",\"2\":\"95.63\",\"3\":\"deaths_due_to_non_communicable_diseases\",\"4\":\"49.28\"},{\"1\":\"1999\",\"2\":\"92.21\",\"3\":\"deaths_due_to_non_communicable_diseases\",\"4\":\"63.69\"},{\"1\":\"2000\",\"2\":\"90.52\",\"3\":\"deaths_due_to_non_communicable_diseases\",\"4\":\"49.47\"},{\"1\":\"2001\",\"2\":\"92.31\",\"3\":\"deaths_due_to_non_communicable_diseases\",\"4\":\"43.78\"},{\"1\":\"2002\",\"2\":\"96.84\",\"3\":\"deaths_due_to_non_communicable_diseases\",\"4\":\"66.83\"},{\"1\":\"2003\",\"2\":\"87.86\",\"3\":\"deaths_due_to_non_communicable_diseases\",\"4\":\"53.27\"},{\"1\":\"2004\",\"2\":\"85.53\",\"3\":\"deaths_due_to_non_communicable_diseases\",\"4\":\"41.89\"},{\"1\":\"2005\",\"2\":\"93.37\",\"3\":\"deaths_due_to_non_communicable_diseases\",\"4\":\"67.55\"},{\"1\":\"2006\",\"2\":\"93.83\",\"3\":\"deaths_due_to_non_communicable_diseases\",\"4\":\"53.26\"},{\"1\":\"2007\",\"2\":\"88.92\",\"3\":\"deaths_due_to_non_communicable_diseases\",\"4\":\"54.82\"},{\"1\":\"2008\",\"2\":\"90.71\",\"3\":\"deaths_due_to_non_communicable_diseases\",\"4\":\"41.85\"},{\"1\":\"2009\",\"2\":\"95.58\",\"3\":\"deaths_due_to_non_communicable_diseases\",\"4\":\"61.63\"},{\"1\":\"2010\",\"2\":\"85.07\",\"3\":\"deaths_due_to_non_communicable_diseases\",\"4\":\"56.10\"},{\"1\":\"2011\",\"2\":\"92.29\",\"3\":\"deaths_due_to_non_communicable_diseases\",\"4\":\"64.37\"},{\"1\":\"2012\",\"2\":\"90.31\",\"3\":\"deaths_due_to_non_communicable_diseases\",\"4\":\"34.48\"},{\"1\":\"2013\",\"2\":\"96.65\",\"3\":\"deaths_due_to_non_communicable_diseases\",\"4\":\"74.46\"},{\"1\":\"2014\",\"2\":\"95.16\",\"3\":\"deaths_due_to_non_communicable_diseases\",\"4\":\"57.93\"},{\"1\":\"2015\",\"2\":\"94.55\",\"3\":\"deaths_due_to_non_communicable_diseases\",\"4\":\"69.21\"},{\"1\":\"2016\",\"2\":\"91.51\",\"3\":\"deaths_due_to_non_communicable_diseases\",\"4\":\"70.46\"},{\"1\":\"2017\",\"2\":\"95.77\",\"3\":\"deaths_due_to_non_communicable_diseases\",\"4\":\"56.79\"},{\"1\":\"2018\",\"2\":\"97.59\",\"3\":\"deaths_due_to_non_communicable_diseases\",\"4\":\"67.69\"},{\"1\":\"2019\",\"2\":\"96.16\",\"3\":\"deaths_due_to_non_communicable_diseases\",\"4\":\"86.51\"},{\"1\":\"1990\",\"2\":\"92.80\",\"3\":\"deaths_due_to_injuries\",\"4\":\"7.21\"},{\"1\":\"1991\",\"2\":\"92.66\",\"3\":\"deaths_due_to_injuries\",\"4\":\"7.33\"},{\"1\":\"1992\",\"2\":\"94.64\",\"3\":\"deaths_due_to_injuries\",\"4\":\"5.36\"},{\"1\":\"1993\",\"2\":\"86.44\",\"3\":\"deaths_due_to_injuries\",\"4\":\"13.57\"},{\"1\":\"1994\",\"2\":\"89.25\",\"3\":\"deaths_due_to_injuries\",\"4\":\"10.75\"},{\"1\":\"1995\",\"2\":\"92.76\",\"3\":\"deaths_due_to_injuries\",\"4\":\"7.23\"},{\"1\":\"1996\",\"2\":\"95.48\",\"3\":\"deaths_due_to_injuries\",\"4\":\"4.51\"},{\"1\":\"1997\",\"2\":\"89.81\",\"3\":\"deaths_due_to_injuries\",\"4\":\"10.19\"},{\"1\":\"1998\",\"2\":\"95.63\",\"3\":\"deaths_due_to_injuries\",\"4\":\"4.37\"},{\"1\":\"1999\",\"2\":\"92.21\",\"3\":\"deaths_due_to_injuries\",\"4\":\"7.79\"},{\"1\":\"2000\",\"2\":\"90.52\",\"3\":\"deaths_due_to_injuries\",\"4\":\"9.48\"},{\"1\":\"2001\",\"2\":\"92.31\",\"3\":\"deaths_due_to_injuries\",\"4\":\"7.69\"},{\"1\":\"2002\",\"2\":\"96.84\",\"3\":\"deaths_due_to_injuries\",\"4\":\"3.16\"},{\"1\":\"2003\",\"2\":\"87.86\",\"3\":\"deaths_due_to_injuries\",\"4\":\"12.14\"},{\"1\":\"2004\",\"2\":\"85.53\",\"3\":\"deaths_due_to_injuries\",\"4\":\"14.47\"},{\"1\":\"2005\",\"2\":\"93.37\",\"3\":\"deaths_due_to_injuries\",\"4\":\"6.63\"},{\"1\":\"2006\",\"2\":\"93.83\",\"3\":\"deaths_due_to_injuries\",\"4\":\"6.16\"},{\"1\":\"2007\",\"2\":\"88.92\",\"3\":\"deaths_due_to_injuries\",\"4\":\"11.08\"},{\"1\":\"2008\",\"2\":\"90.71\",\"3\":\"deaths_due_to_injuries\",\"4\":\"9.30\"},{\"1\":\"2009\",\"2\":\"95.58\",\"3\":\"deaths_due_to_injuries\",\"4\":\"4.42\"},{\"1\":\"2010\",\"2\":\"85.07\",\"3\":\"deaths_due_to_injuries\",\"4\":\"14.93\"},{\"1\":\"2011\",\"2\":\"92.29\",\"3\":\"deaths_due_to_injuries\",\"4\":\"7.71\"},{\"1\":\"2012\",\"2\":\"90.31\",\"3\":\"deaths_due_to_injuries\",\"4\":\"9.68\"},{\"1\":\"2013\",\"2\":\"96.65\",\"3\":\"deaths_due_to_injuries\",\"4\":\"3.36\"},{\"1\":\"2014\",\"2\":\"95.16\",\"3\":\"deaths_due_to_injuries\",\"4\":\"4.84\"},{\"1\":\"2015\",\"2\":\"94.55\",\"3\":\"deaths_due_to_injuries\",\"4\":\"5.45\"},{\"1\":\"2016\",\"2\":\"91.51\",\"3\":\"deaths_due_to_injuries\",\"4\":\"8.49\"},{\"1\":\"2017\",\"2\":\"95.77\",\"3\":\"deaths_due_to_injuries\",\"4\":\"4.23\"},{\"1\":\"2018\",\"2\":\"97.59\",\"3\":\"deaths_due_to_injuries\",\"4\":\"2.41\"},{\"1\":\"2019\",\"2\":\"96.16\",\"3\":\"deaths_due_to_injuries\",\"4\":\"3.84\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nIn this representation, each row represents a different group of diseases (communicable, non-communicable, injuries), and the corresponding percentage indicates the contribution of each group to the overall death rate. This long format allows for easier data manipulation and analysis using functions such as group_by() and summarize().\n\n**Research question answered -** *Which countries consistently report the highest number of deaths each year?*\n\nWe are identifying the top 5 countries that exhibit the highest number of deaths across the years 1990 to 2019.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Calculating the total number of deaths after grouping the data by year and then country, then fetching the top 5 countries from it. This will help us get the countries with the highest number of deaths from the year 1990 to 2019.\n\ncountry_with_highest_death_numbers_for_every_year <- death_dataset %>%\n  group_by(Year, Country)%>%\n  summarise(deaths = sum(NumberOfDeaths)) %>%\n  top_n(5, deaths)\n\n#Unique values of the countries with highest death rates from 1990 to 2019\n\nunique(country_with_highest_death_numbers_for_every_year$Country)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"China\"         \"India\"         \"Indonesia\"     \"Russia\"       \n[5] \"United States\" \"Nigeria\"      \n```\n:::\n\n```{.r .cell-code}\n#Number of unique countries with highest death rates from 1990 to 2019\n\nlength(unique(country_with_highest_death_numbers_for_every_year$Country))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 6\n```\n:::\n\n```{.r .cell-code}\n#visualizing the above extracted data in the form of scatterplot\n\ncountry_with_highest_death_numbers_for_every_year %>%\n  ggplot(aes(x = Year, y = deaths, col = Country)) + \n  geom_point(alpha = 1) + \n  geom_smooth(se = F, span = 0.2) + \n  scale_x_continuous(breaks = seq(1990, 2019, 2), minor_breaks = T) + \n  scale_y_continuous(labels = label_number(suffix = \" M\", scale = 1e-6)) +\n  labs(title = \"Death distribution for countries with highest mortality rates\", \n       subtitle = \"1990 - 2019\", \n       x = \"Year\", \n       y = \"Number of Deaths (in millions)\", \n       col = \"Country\")\n```\n\n::: {.cell-output-display}\n![](NehaJhurani_FinalProject_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\nFrom the scatter plot above, it is evident that only six countries consistently had the highest number of deaths from 1990 to 2019. These countries include China, India, United States, Russia, Indonesia, and Nigeria.\n\nChina and India stand out with significantly higher annual death rates compared to the other countries. One of the contributing factors is their dense population in comparison to other nations. Additionally, differences in factors such as affordability, access to healthcare services, healthcare quality, income levels, education, and living conditions also play a role in the higher death rates observed in these countries.\n\nOn the other hand, Indonesia and Nigeria exhibit similar death numbers. These countries share similarities in terms of their health systems, data collection practices, registration of deaths, and reporting mechanisms. The population structures and age distributions in Indonesia and Nigeria also bear a resemblance, which may contribute to the comparable death rates observed in these nations.\n\n**Research question answered -** *Which countries consistently report the lowest number of deaths each year?*\n\nWe are identifying the top 5 countries that consistently exhibit the lowest number of deaths across the years 1990 to 2019.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Calculating the total number of deaths after grouping the data by year and then country, then fetching the lowest death numbers countries from it. \n\ncountry_with_lowest_death_numbers_for_every_year <- death_dataset %>%\n  group_by(Year, Country)%>%\n  summarise(deaths = sum(NumberOfDeaths)) %>%\n  top_n(-5, deaths)\n\n#Unique values of the countries with highest death rates from 1990 to 2019\n\nunique(country_with_lowest_death_numbers_for_every_year$Country)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"Hong Kong\"         \"Nauru\"             \"Niue\"             \n [4] \"Tokelau\"           \"Tuvalu\"            \"Guadeloupe\"       \n [7] \"Martinique\"        \"Zaire\"             \"New Caledonia\"    \n[10] \"Western Sahara\"    \"Cook Islands\"      \"Wallis and Futuna\"\n[13] \"French Polynesia\"  \"Macau\"             \"French Guiana\"    \n[16] \"Kosovo\"            \"East Timor\"       \n```\n:::\n\n```{.r .cell-code}\n#Number of unique countries with lowest death rates from 1990 to 2019\n\nlength(unique(country_with_lowest_death_numbers_for_every_year$Country))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 17\n```\n:::\n\n```{.r .cell-code}\n#visualizing the above extracted data in the form of graph\n\ncountry_with_lowest_death_numbers_for_every_year %>%\n  ggplot(aes(x = Year, y = deaths, col = Country)) + \n  geom_point(alpha = 0.5) + \n  geom_line(alpha = 1) + \n  geom_smooth(se = F, span = 0.2) + \n  scale_x_continuous(breaks = seq(1990, 2019, 2), minor_breaks = T) +\n  labs(title = \"Death distribution for countries with lowest mortality rates\", \n       subtitle = \"1990 - 2019\", \n       x = \"Year\", \n       y = \"Number of Deaths\", \n       col = \"Country\")\n```\n\n::: {.cell-output-display}\n![](NehaJhurani_FinalProject_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\nFrom the line chart above, it is evident that there are a total of 17 unique countries that consistently experienced the lowest number of deaths from 1990 to 2019.\n\nThese countries are characterized by relatively small populations. For instance, Tuvalu, a small island nation in the Pacific, has a population of approximately 11,000 people, in contrast to a country like India with a population of around 1.4 billion.\n\nThe countries with the lowest number of deaths demonstrate good access to healthcare services, including preventive care, early detection of diseases, and high-quality medical treatments. They prioritize public health measures to ensure the well-being of their populations. Additionally, these regions tend to have relatively younger populations, resulting in lower mortality rates compared to countries with older populations.\n\n**Research question answered - ** *Which cause of death had the highest prevalence globally during the time period from 1990 to 2019?*\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#During the initial data description, we calculated the frequency of deaths worldwide from 1990 to 2019. Using this information to identify the top causes of death across the globe.\n\nhead(frequency_of_causes %>% arrange(desc(deaths)), n=10)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Cause\"],\"name\":[1],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"deaths\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Cardiovascular diseases\",\"2\":\"447185738\"},{\"1\":\"Neoplasms\",\"2\":\"229503682\"},{\"1\":\"Chronic respiratory diseases\",\"2\":\"104502658\"},{\"1\":\"Lower respiratory infections\",\"2\":\"83146095\"},{\"1\":\"Neonatal disorders\",\"2\":\"76099923\"},{\"1\":\"Diarrheal diseases\",\"2\":\"65867214\"},{\"1\":\"Digestive diseases\",\"2\":\"65461101\"},{\"1\":\"Tuberculosis\",\"2\":\"45606215\"},{\"1\":\"Cirrhosis and other chronic liver diseases\",\"2\":\"37372823\"},{\"1\":\"Road injuries\",\"2\":\"36203659\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\nUpon analyzing the data for the years 1990 to 2019, it is evident that the three leading causes of death on a global scale are Cardiovascular diseases, Neoplasms (cancer), and Chronic respiratory diseases.\n\n**Research question answered - ** *For a selection of countries with both the highest and lowest number of deaths, what was the trend in the occurrence of the three most common causes of death from 1990 to 2019?*\n\nFor further analysis, we have chosen a selection of countries with varying death rates: China, India, United States, Tuvalu, and Hong Kong. These countries have been specifically selected to represent different trends in annual death rates from 1990 to 2019.\n\nChina, India, and the United States are included as they exhibit higher annual death rates, reflecting countries with larger populations and potentially different healthcare systems and socio-economic factors influencing mortality.\n\nOn the other hand, Hong Kong and Tuvalu have been chosen as representatives of countries with lower annual death rates. These countries have smaller populations and may have distinct characteristics related to healthcare access, public health initiatives, and demographic factors contributing to their comparatively lower death rates.\n\nBy analyzing these diverse countries, we can gain insights into the trends and factors influencing death rates across different regions and population sizes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndeath_data_subset <- death_dataset[death_dataset$Country== (alist('United States', 'India', 'China', 'Nigeria', 'Tuvalu')),]\n\n# Dimensions of the subset\n\ndim(death_data_subset)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 954   4\n```\n:::\n\n```{.r .cell-code}\n#summary of the subset\n\nsummary(death_data_subset)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    Cause           NumberOfDeaths      Country               Year     \n Length:954         Min.   :      0   Length:954         Min.   :1990  \n Class :character   1st Qu.:    200   Class :character   1st Qu.:1997  \n Mode  :character   Median :  11740   Mode  :character   Median :2005  \n                    Mean   : 123813                      Mean   :2005  \n                    3rd Qu.:  75378                      3rd Qu.:2012  \n                    Max.   :4459245                      Max.   :2019  \n```\n:::\n:::\n\nWe can see that the mean number of death across the selected countries over the years 1990 to 2019 is approximately 120k.\n\nRepresenting the Number of Deaths in the extracted subset at the country level over the years 1990 to 2019 using a scatter plot:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndeath_data_subset %>%\n  group_by(Country, Year)%>%\n  summarise(deaths = sum(NumberOfDeaths))%>%\n  ggplot(aes(x = Year, y = deaths, col = Country)) + \n  geom_point(alpha = 1) + \n  geom_smooth(se = F, span = 0.2) + \n  scale_x_continuous(breaks = seq(1990, 2019, 3), minor_breaks = T) + \n  scale_y_continuous(labels = label_number(suffix = \" M\", scale = 1e-6)) +\n  labs(title = \"Distribution of death numbers in the extracted subset\", \n       subtitle = \"1990 - 2019\", \n       x = \"Year\", \n       y = \"Number of Deaths (in millions)\", \n       col = \"Country\")\n```\n\n::: {.cell-output-display}\n![](NehaJhurani_FinalProject_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\nLet's examine the trend in the occurrence of *Cardiovascular diseases* among the selected countries (China, India, United States, Tuvalu, and Hong Kong) from 1990 to 2019.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncardio_dataset <- death_data_subset[death_data_subset$'Cause'=='Cardiovascular diseases',]\n\ncardio_dataset%>%\n  group_by(Country, Year, NumberOfDeaths)%>%\n  ggplot(aes(x = Year, y = NumberOfDeaths, col = Country)) + \n  geom_point(alpha = 0.5) + \n  geom_smooth(se = F, span = 1.5) + \n  scale_x_continuous(breaks = seq(1990, 2019, 3), minor_breaks = T) + \n  scale_y_continuous(breaks = seq(0, 5000000, 200000), minor_breaks = T, labels = label_number(suffix = \" K\", scale = 1e-3)) +\n  labs(title = \"Number of Deaths due to Cardiovascular diseases in the extracted subset\",\n       subtitle = \"1990 - 2019\", \n       x = \"Year\", \n       y = \"Number of Deaths (in thousands)\", \n       col = \"Country\")\n```\n\n::: {.cell-output-display}\n![](NehaJhurani_FinalProject_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\nUpon analyzing the above line graph, we can see that in India and China, there has been a significant and steep increase in the number of deaths attributed to cardiovascular diseases over the years. This could be attributed to various factors, including lifestyle changes, economic development, rapid urbanization, and a potential increase in risk factors such as obesity rates, unhealthy dietary patterns, and sedentary lifestyles.\n\nOn the other hand, the United States initially experienced a decrease in deaths due to cardiovascular diseases, followed by a subsequent increase. This pattern may be influenced by advancements in medical treatments and increased awareness about the risks associated with cardiovascular diseases. Additionally, factors such as an aging population can contribute to an increased risk of cardiovascular diseases.\n\nIn contrast, Tuvalu and Hong Kong exhibit relatively stable trends with little fluctuation in the number of deaths caused by cardiovascular diseases. The reasons for this stability could be attributed to various factors, including effective public health initiatives, access to healthcare services, and demographic characteristics.\n\nOverall, the observed trends highlight the complex interplay of factors influencing the occurrence of cardiovascular diseases, including lifestyle changes, healthcare advancements, population demographics, and socioeconomic factors.\n\nLet's examine the trend in the occurrence of *Neoplasms* among the selected countries (China, India, United States, Tuvalu, and Hong Kong) from 1990 to 2019.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nneo_dataset <- death_data_subset[death_data_subset$'Cause'=='Neoplasms',]\n\nneo_dataset%>%\n  group_by(Country, Year, NumberOfDeaths)%>%\n  ggplot(aes(x = Year, y = NumberOfDeaths, col = Country)) + \n  geom_point(alpha = 0.5) + \n  geom_smooth(se = F, span = 1.5) + \n  scale_x_continuous(breaks = seq(1990, 2019, 3), minor_breaks = T) + \n  scale_y_continuous(breaks = seq(0, 5000000, 200000), minor_breaks = T, labels = label_number(suffix = \" K\", scale = 1e-3)) + \n  labs(title = \"Number of Deaths due to Neoplasms in the extracted subset\",\n       subtitle = \"1990 - 2019\", \n       x = \"Year\", \n       y = \"Number of Deaths (in thousands)\", \n       col = \"Country\")\n```\n\n::: {.cell-output-display}\n![](NehaJhurani_FinalProject_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\nUpon analyzing the above line graph, we can see that the number of deaths due to Neoplasms has increased significantly in India, China, United States, and Nigeria, while there is minimal change in Tuvalu. Lifestyle factors like excessive alcohol consumption and tobacco use contribute to the increase in death numbers. Smaller countries prioritize public health safety measures, resulting in relatively stable rates.\n\nLet's examine the trend in the occurrence of *Chronic respiratory diseases* among the selected countries (China, India, United States, Tuvalu, and Hong Kong) from 1990 to 2019.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchronic_dataset <- death_data_subset[death_data_subset$'Cause'=='Chronic respiratory diseases',]\n\nchronic_dataset%>%\n  group_by(Country, Year, NumberOfDeaths)%>%\n  ggplot(aes(x = Year, y = NumberOfDeaths, col = Country)) + \n  geom_point(alpha = 0.5) + \n  geom_smooth(se = F, span = 1.5) + \n  scale_x_continuous(breaks = seq(1990, 2019, 3), minor_breaks = T) + \n  scale_y_continuous(breaks = seq(0, 5000000, 200000), minor_breaks = T, labels = label_number(suffix = \" K\", scale = 1e-3)) + \n  labs(title = \"Number of Deaths due to Chronic respiratory diseases in extracted subset\",\n       subtitle = \"1990 - 2019\", \n       x = \"Year\", \n       y = \"Number of Deaths (in thousands)\", \n       col = \"Country\")\n```\n\n::: {.cell-output-display}\n![](NehaJhurani_FinalProject_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\nUpon analyzing the above line graph, we can see that India and the United States have experienced a significant increase in deaths, likely due to air pollution, both outdoors in urban areas and indoors from solid fuel use. In contrast, Nigeria and Tuvalu have seen minimal change in death rates. China, on the other hand, has witnessed a decrease in deaths attributed to Chronic respiratory diseases. This can be attributed to the implementation of measures to address air pollution, including stricter regulations, promotion of clean energy sources, and pollution control policies. Improved air quality has resulted in reduced exposure to harmful pollutants, thus lowering the risk of respiratory diseases.\n\n**Research question answered - ** *How does the prevalence of mental illness correlate with the number of deaths over the years in a selection of countries with both the highest and lowest mortality rates?*\n\nMental illness has profound implications for individual well-being, quality of life, and overall functioning. It can result in emotional distress, impaired cognitive abilities, and challenges in maintaining relationships, work, and daily activities. With its substantial contribution to disability and overall disease burden, addressing mental health issues is crucial for fostering healthier communities and reducing the burden on public health systems. In the selected dataset, we are focusing on specific causes related to mental illness, namely \"Drug use disorders,\" \"Alcohol use disorders,\" and \"Self-harm,\" to examine the number of deaths associated with mental health in the selected dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmi_dataset <- death_data_subset[death_data_subset$'Cause'== (alist(\"Alcohol use disorders\",\"Drug use disorders\",\"Self-harm\")),]\n\nmi_dataset%>%\n  group_by(Cause, Year, Country)%>%\n  summarise(deaths = sum(NumberOfDeaths)) %>%\n  ggplot(aes(x = Year, y = deaths, col = Country)) + \n  geom_point(alpha = 0.5) + \n  geom_smooth(se = F, span = 1.5) + \n  scale_x_continuous(breaks = seq(1990, 2019, 3), minor_breaks = T) + \n  scale_y_continuous(labels = label_number(suffix = \" K\", scale = 1e-3)) +\n  labs(title = \"Number of Deaths due to Mental Illness in the extracted subset\",\n       subtitle = \"1990 - 2019\", \n       x = \"Year\", \n       y = \"Number of Deaths (in thousands)\", \n       col = \"Cause\")\n```\n\n::: {.cell-output-display}\n![](NehaJhurani_FinalProject_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\nIn analyzing the number of deaths due to mental illness, we observe varying trends in the above line graph across different countries.\n\nIn India and Nigeria, we observe an increase and decrease in the number of deaths related to mental illness. This can be attributed to the implementation of mental health policies and legislation that prioritize mental well-being. Over time, there has been a growing awareness and recognition of mental health in these countries.\n\nIn Tuvalu, with its proper healthcare infrastructure and smaller population, we observe minimal changes in the number of deaths due to mental illness.\n\nHowever, in China and the United States, we witness distinct patterns. In China, there is a decrease followed by a steep increase in the number of deaths. This may be due to inadequate access to mental health services, including a shortage of mental health professionals and limited insurance coverage for mental health treatment. Substance abuse and drug-related issues can further exacerbate mental health conditions, increasing the risk of mortality.\n\nIn the United States, we observe an exponential increase in the number of deaths due to mental illness. This could be attributed to various factors such as insufficient access to mental health services, systemic challenges in the healthcare system, and the complex interplay between mental health and substance abuse.\n\nThese trends highlight the importance of prioritizing mental health support, improving access to mental health services, and addressing the underlying factors contributing to mental illness-related deaths in different countries.\n\n**Research question answered - ** *How does the distribution of deaths vary globally for the leading cause of death during the year with the highest number of deaths?*\n\nBy filtering the dataset specifically for the year 2019 and focusing on deaths attributed to cardiovascular diseases, we can analyze the distribution of deaths for the leading cause during the year with the highest number of fatalities.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndeath_2019_dataset <- death_dataset %>%\n  filter(Cause == \"Cardiovascular diseases\" & Year == 2019)\n\nworld_map <- map_data(\"world\")\n\nmerged_dataset <- merge(world_map, death_2019_dataset, by.x = \"region\", by.y = \"Country\")\n\nggplot() +\n  geom_polygon(data = merged_dataset, aes(x = long, y = lat, group = group, fill = NumberOfDeaths)) +\n  scale_fill_gradient(low = \"lightblue\", high = \"red\", name = \"Deaths\") +\n  labs(title = \"Distribution of death numbers due to Cardiovascular Diseases\",\n       x = \"longitude\", \n       y = \"latitude\",\n       subtitle = \"Year - 2019\") +\n  theme_minimal() \n```\n\n::: {.cell-output-display}\n![](NehaJhurani_FinalProject_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\nThe above map graph provides a more intuitive visualization of the death distribution across countries. The color gradient highlights the varying intensity of deaths due to cardiovascular diseases. From the graph, we observe that China has the highest number of deaths, followed by India, Russia, Brazil, and several other countries. This representation enhances the readability and understanding of the data, allowing for easier comparisons and identification of the countries with the highest mortality rates.\n\n## Part 7. Conclusion and Discussion\n\nAfter conducting a comprehensive analysis of the dataset, we have gained valuable insights into global mortality trends from 1990 to 2019. Non-communicable diseases emerged as the leading cause of death worldwide during this period. We observed a consistent increase in the number of deaths globally, indicating the importance of addressing public health challenges associated with mortality.\n\nCountries with denser populations exhibited higher death rates, while those with smaller populations and better healthcare infrastructure experienced relatively fewer deaths. This highlights the crucial role of population density and healthcare accessibility in shaping mortality patterns.\n\nCardiovascular diseases emerged as the primary cause of death across the globe during the studied timeframe, emphasizing the need for targeted interventions and preventive measures to combat these conditions. Additionally, we identified a notable increase in deaths attributed to mental illness, highlighting the importance of prioritizing mental health services and addressing the associated risk factors.\n\nThis dataset opens up avenues for further in-depth analysis, allowing researchers to explore the relationships between factors such as obesity rates and cardiovascular diseases. By examining subsets of age groups and genders in conjunction with this dataset, we can gain a deeper understanding of the underlying causes of mortality. These insights will contribute to enhanced public health strategies aimed at controlling and preventing deaths worldwide.\n\nOverall, this dataset provides a valuable foundation for future research directions, enabling us to address public health challenges, improve health outcomes, and ultimately reduce the global burden of mortality.\n\n## Part 8. Bibliography\n\n- https://ourworldindata.org/causes-of-death\n- R Language as programming language\n- The R Graph Gallery-https://r-graph-gallery.com/\n- https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8234939/\n",
    "supporting": [
      "NehaJhurani_FinalProject_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}