<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.427">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Aritra Basu">
<meta name="dcterms.date" content="2023-02-28">

<title>Challenge 1</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../images/DACSS_Round_Network.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<meta name="twitter:title" content="Challenge 1">
<meta name="twitter:description" content="">
<meta name="twitter:creator" content="@UMassDACSS">
<meta name="twitter:site" content="@UMassDACSS">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../images/UMass White Wordmark Horiz.png" alt="" class="navbar-logo">
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://github.com/DACSS" rel="" target="">
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html" rel="" target="">
 <span class="menu-text">Contributors</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://umass.edu/sbs/dacss" rel="" target="">
 <span class="menu-text">DACSS</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/DACSS" rel="" target=""><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#reading-the-data" id="toc-reading-the-data" class="nav-link active" data-scroll-target="#reading-the-data">Reading the Data</a></li>
  <li><a href="#describing-the-data" id="toc-describing-the-data" class="nav-link" data-scroll-target="#describing-the-data">Describing the data</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Challenge 1</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
  <div class="quarto-categories">
    <div class="quarto-category">challenge_1</div>
    <div class="quarto-category">Aritra Basu</div>
    <div class="quarto-category">wildbirds</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Aritra Basu </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">February 28, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(descr)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(summarytools)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">TRUE</span>, <span class="at">warning=</span><span class="cn">FALSE</span>, <span class="at">message=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="reading-the-data" class="level2">
<h2 class="anchored" data-anchor-id="reading-the-data">Reading the Data</h2>
<p>I have decided to work on the dataset birds:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>birds <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"_data/birds.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="describing-the-data" class="level2">
<h2 class="anchored" data-anchor-id="describing-the-data">Describing the data</h2>
<p>Using the package descr, it can be seen that the dataset contains observations on birds from 1976 to 2018. We can see the frequency. The summary statistics, because of the nature of the variables is not very useful here.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages('descr')</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co">#library(descr)</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">descr</span>(birds)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Descriptive Statistics  
birds  
N: 30977  

                    Area.Code   Element.Code   Item.Code         Value       Year   Year.Code
----------------- ----------- -------------- ----------- ------------- ---------- -----------
             Mean     1201.73        5112.00     1066.48      99410.63    1990.58     1990.58
          Std.Dev     2099.42           0.00        9.03     720611.42      16.73       16.73
              Min        1.00        5112.00     1057.00          0.00    1961.00     1961.00
               Q1       79.00        5112.00     1057.00        171.00    1976.00     1976.00
           Median      156.00        5112.00     1068.00       1800.00    1992.00     1992.00
               Q3      231.00        5112.00     1072.00      15404.00    2005.00     2005.00
              Max     5504.00        5112.00     1083.00   23707134.00    2018.00     2018.00
              MAD      114.16           0.00       16.31       2647.92      20.76       20.76
              IQR      152.00           0.00       15.00      15233.00      29.00       29.00
               CV        1.75           0.00        0.01          7.25       0.01        0.01
         Skewness        1.43            NaN        0.26         18.18      -0.09       -0.09
      SE.Skewness        0.01           0.01        0.01          0.01       0.01        0.01
         Kurtosis        0.05            NaN       -1.37        424.79      -1.19       -1.19
          N.Valid    30977.00       30977.00    30977.00      29941.00   30977.00    30977.00
        Pct.Valid      100.00         100.00      100.00         96.66     100.00      100.00</code></pre>
</div>
</div>
<p>Using n_distinct, it can be observed that there are 248 distinct area codes.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>birds<span class="sc">%&gt;%</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Area.Code)<span class="sc">%&gt;%</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">n_distinct</span>(.)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 248</code></pre>
</div>
</div>
<p>Next, we could look at a cross sectional component by looking at the dataset for a particular year. Say, we want to filter chickens in 1962, and looking at area, items and value.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>birds<span class="sc">%&gt;%</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Area, Item, Value, Year)<span class="sc">%&gt;%</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Year<span class="sc">==</span><span class="st">"1962"</span>, Item<span class="sc">==</span><span class="st">"Chickens"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                                                    Area     Item   Value Year
1                                            Afghanistan Chickens    4900 1962
2                                                Albania Chickens    1677 1962
3                                                Algeria Chickens    8600 1962
4                                         American Samoa Chickens      80 1962
5                                                 Angola Chickens    3500 1962
6                                    Antigua and Barbuda Chickens      44 1962
7                                              Argentina Chickens   38000 1962
8                                              Australia Chickens   20290 1962
9                                                Austria Chickens    9943 1962
10                                               Bahamas Chickens     580 1962
11                                               Bahrain Chickens      80 1962
12                                            Bangladesh Chickens   20000 1962
13                                              Barbados Chickens     319 1962
14                                    Belgium-Luxembourg Chickens   31177 1962
15                                                Belize Chickens     150 1962
16                                                 Benin Chickens    5000 1962
17                                               Bermuda Chickens      56 1962
18                                                Bhutan Chickens      75 1962
19                      Bolivia (Plurinational State of) Chickens    5200 1962
20                                              Botswana Chickens     244 1962
21                                                Brazil Chickens  137430 1962
22                                     Brunei Darussalam Chickens     160 1962
23                                              Bulgaria Chickens   21574 1962
24                                          Burkina Faso Chickens    8900 1962
25                                               Burundi Chickens    1200 1962
26                                            Cabo Verde Chickens      42 1962
27                                              Cambodia Chickens    2315 1962
28                                              Cameroon Chickens    3000 1962
29                                                Canada Chickens   65031 1962
30                              Central African Republic Chickens     800 1962
31                                                  Chad Chickens    2500 1962
32                                                 Chile Chickens    9630 1962
33                                  China, Hong Kong SAR Chickens    3251 1962
34                                      China, Macao SAR Chickens     230 1962
35                                       China, mainland Chickens  543000 1962
36                             China, Taiwan Province of Chickens    7942 1962
37                                              Colombia Chickens   19750 1962
38                                               Comoros Chickens     190 1962
39                                                 Congo Chickens     580 1962
40                                          Cook Islands Chickens      50 1962
41                                            Costa Rica Chickens    2361 1962
42                                         Côte d'Ivoire Chickens    4380 1962
43                                                  Cuba Chickens    7500 1962
44                                                Cyprus Chickens    1500 1962
45                                        Czechoslovakia Chickens   28507 1962
46                 Democratic People's Republic of Korea Chickens   11500 1962
47                      Democratic Republic of the Congo Chickens    4400 1962
48                                               Denmark Chickens   29047 1962
49                                              Dominica Chickens      54 1962
50                                    Dominican Republic Chickens    6400 1962
51                                               Ecuador Chickens    4380 1962
52                                                 Egypt Chickens   22096 1962
53                                           El Salvador Chickens    1878 1962
54                                     Equatorial Guinea Chickens      77 1962
55                                              Eswatini Chickens     334 1962
56                                          Ethiopia PDR Chickens   41000 1962
57                           Falkland Islands (Malvinas) Chickens       1 1962
58                                                  Fiji Chickens     200 1962
59                                               Finland Chickens    6509 1962
60                                                France Chickens  170000 1962
61                                         French Guyana Chickens      35 1962
62                                      French Polynesia Chickens      10 1962
63                                                 Gabon Chickens     270 1962
64                                                Gambia Chickens     180 1962
65                                               Germany Chickens  101716 1962
66                                                 Ghana Chickens    6005 1962
67                                                Greece Chickens   15030 1962
68                                               Grenada Chickens     151 1962
69                                            Guadeloupe Chickens     160 1962
70                                                  Guam Chickens      90 1962
71                                             Guatemala Chickens    7330 1962
72                                                Guinea Chickens    3200 1962
73                                         Guinea-Bissau Chickens     200 1962
74                                                Guyana Chickens    2100 1962
75                                                 Haiti Chickens    2600 1962
76                                              Honduras Chickens    2367 1962
77                                               Hungary Chickens   26245 1962
78                                               Iceland Chickens      95 1962
79                                                 India Chickens  107200 1962
80                                             Indonesia Chickens   60500 1962
81                            Iran (Islamic Republic of) Chickens   24382 1962
82                                                  Iraq Chickens    7100 1962
83                                               Ireland Chickens    6954 1962
84                                                Israel Chickens   11500 1962
85                                                 Italy Chickens   93000 1962
86                                               Jamaica Chickens    1899 1962
87                                                 Japan Chickens   90669 1962
88                                                Jordan Chickens    1500 1962
89                                                 Kenya Chickens    8300 1962
90                                              Kiribati Chickens     103 1962
91                                                Kuwait Chickens    2000 1962
92                      Lao People's Democratic Republic Chickens    6000 1962
93                                               Lebanon Chickens    3900 1962
94                                               Lesotho Chickens     657 1962
95                                               Liberia Chickens    1250 1962
96                                                 Libya Chickens     439 1962
97                                         Liechtenstein Chickens      NA 1962
98                                            Madagascar Chickens   10200 1962
99                                                Malawi Chickens    3000 1962
100                                             Malaysia Chickens   22500 1962
101                                                 Mali Chickens   10545 1962
102                                                Malta Chickens     526 1962
103                                           Martinique Chickens     300 1962
104                                           Mauritania Chickens    1850 1962
105                                            Mauritius Chickens     400 1962
106                                               Mexico Chickens   64172 1962
107                                             Mongolia Chickens     139 1962
108                                           Montserrat Chickens      24 1962
109                                              Morocco Chickens   13170 1962
110                                           Mozambique Chickens    4300 1962
111                                              Myanmar Chickens    7756 1962
112                                              Namibia Chickens     234 1962
113                                                Nauru Chickens       2 1962
114                                                Nepal Chickens    4300 1962
115                                          Netherlands Chickens   45890 1962
116                        Netherlands Antilles (former) Chickens      56 1962
117                                        New Caledonia Chickens     139 1962
118                                          New Zealand Chickens    4500 1962
119                                            Nicaragua Chickens    2062 1962
120                                                Niger Chickens    4850 1962
121                                              Nigeria Chickens   38710 1962
122                                                 Niue Chickens      11 1962
123                                               Norway Chickens    4745 1962
124                                                 Oman Chickens     315 1962
125                      Pacific Islands Trust Territory Chickens     106 1962
126                                             Pakistan Chickens   12000 1962
127                                            Palestine Chickens      NA 1962
128                                               Panama Chickens    2410 1962
129                                     Papua New Guinea Chickens     746 1962
130                                             Paraguay Chickens    5384 1962
131                                                 Peru Chickens   21000 1962
132                                          Philippines Chickens   51354 1962
133                                               Poland Chickens   69525 1962
134                                             Portugal Chickens    8900 1962
135                                          Puerto Rico Chickens    3532 1962
136                                                Qatar Chickens      22 1962
137                                    Republic of Korea Chickens   13047 1962
138                                              Réunion Chickens    1500 1962
139                                              Romania Chickens   38192 1962
140                                               Rwanda Chickens     400 1962
141         Saint Helena, Ascension and Tristan da Cunha Chickens      10 1962
142                                Saint Kitts and Nevis Chickens      48 1962
143                                          Saint Lucia Chickens      45 1962
144                     Saint Vincent and the Grenadines Chickens      30 1962
145                                                Samoa Chickens     450 1962
146                                Sao Tome and Principe Chickens      36 1962
147                                         Saudi Arabia Chickens    1550 1962
148                                              Senegal Chickens    2900 1962
149                                           Seychelles Chickens      45 1962
150                                         Sierra Leone Chickens    2000 1962
151                                            Singapore Chickens    2000 1962
152                                      Solomon Islands Chickens     100 1962
153                                              Somalia Chickens    1400 1962
154                                         South Africa Chickens   19000 1962
155                                                Spain Chickens   36248 1962
156                                            Sri Lanka Chickens    3765 1962
157                                       Sudan (former) Chickens   10000 1962
158                                             Suriname Chickens    3000 1962
159                                               Sweden Chickens   10061 1962
160                                          Switzerland Chickens    5880 1962
161                                 Syrian Arab Republic Chickens    3356 1962
162                                             Thailand Chickens   41192 1962
163                                          Timor-Leste Chickens     530 1962
164                                                 Togo Chickens    1028 1962
165                                              Tokelau Chickens       2 1962
166                                                Tonga Chickens      55 1962
167                                  Trinidad and Tobago Chickens    2800 1962
168                                              Tunisia Chickens    5200 1962
169                                               Turkey Chickens   26116 1962
170                                               Tuvalu Chickens      10 1962
171                                               Uganda Chickens    6700 1962
172                                 United Arab Emirates Chickens      40 1962
173 United Kingdom of Great Britain and Northern Ireland Chickens  104288 1962
174                          United Republic of Tanzania Chickens    7200 1962
175                             United States of America Chickens  782000 1962
176                         United States Virgin Islands Chickens      18 1962
177                                              Uruguay Chickens    4800 1962
178                                                 USSR Chickens  488300 1962
179                                              Vanuatu Chickens      95 1962
180                   Venezuela (Bolivarian Republic of) Chickens   13696 1962
181                                             Viet Nam Chickens   37100 1962
182                            Wallis and Futuna Islands Chickens      20 1962
183                                                Yemen Chickens    2340 1962
184                                         Yugoslav SFR Chickens   24908 1962
185                                               Zambia Chickens    4200 1962
186                                             Zimbabwe Chickens    6600 1962
187                                                World Chickens 4048728 1962
188                                               Africa Chickens  282821 1962
189                                       Eastern Africa Chickens   96635 1962
190                                        Middle Africa Chickens   15163 1962
191                                      Northern Africa Chickens   59505 1962
192                                      Southern Africa Chickens   20469 1962
193                                       Western Africa Chickens   91049 1962
194                                             Americas Chickens 1220784 1962
195                                     Northern America Chickens  847087 1962
196                                      Central America Chickens   82730 1962
197                                            Caribbean Chickens   26560 1962
198                                        South America Chickens  264407 1962
199                                                 Asia Chickens 1139125 1962
200                                         Eastern Asia Chickens  669777 1962
201                                        Southern Asia Chickens  176622 1962
202                                   South-eastern Asia Chickens  231407 1962
203                                         Western Asia Chickens   61319 1962
204                                               Europe Chickens 1378938 1962
205                                       Eastern Europe Chickens  672343 1962
206                                      Northern Europe Chickens  161699 1962
207                                      Southern Europe Chickens  180289 1962
208                                       Western Europe Chickens  364607 1962
209                                              Oceania Chickens   27059 1962
210                            Australia and New Zealand Chickens   24790 1962
211                                            Melanesia Chickens    1280 1962
212                                           Micronesia Chickens     301 1962
213                                            Polynesia Chickens     688 1962</code></pre>
</div>
</div>
<p>Next, I identify the missing values for 1962.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>birds<span class="sc">%&gt;%</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Area, Element, Item, Value, Year)<span class="sc">%&gt;%</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Year <span class="sc">==</span> <span class="st">"1962"</span>)<span class="sc">%&gt;%</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">is.na</span>(Value))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                                    Area Element                   Item Value
1                                Albania  Stocks                  Ducks    NA
2                                Albania  Stocks Geese and guinea fowls    NA
3                                Albania  Stocks                Turkeys    NA
4                               Barbados  Stocks                Turkeys    NA
5                                  Chile  Stocks                Turkeys    NA
6  Democratic People's Republic of Korea  Stocks                  Ducks    NA
7                                Finland  Stocks                Turkeys    NA
8                          Liechtenstein  Stocks               Chickens    NA
9                                Morocco  Stocks                Turkeys    NA
10                            Mozambique  Stocks Geese and guinea fowls    NA
11                            Mozambique  Stocks                Turkeys    NA
12                               Namibia  Stocks   Pigeons, other birds    NA
13                                Norway  Stocks                  Ducks    NA
14                                Norway  Stocks                Turkeys    NA
15                             Palestine  Stocks               Chickens    NA
16             Saint Pierre and Miquelon  Stocks                  Ducks    NA
17                           Switzerland  Stocks Geese and guinea fowls    NA
18                           Switzerland  Stocks                Turkeys    NA
19                       Southern Africa  Stocks   Pigeons, other birds    NA
   Year
1  1962
2  1962
3  1962
4  1962
5  1962
6  1962
7  1962
8  1962
9  1962
10 1962
11 1962
12 1962
13 1962
14 1962
15 1962
16 1962
17 1962
18 1962
19 1962</code></pre>
</div>
</div>
<p>Trying another function: dfsummary. This function is provided by the package summary tools.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages('summarytools')</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="co">#library(summarytools)</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">dfSummary</span>(birds, <span class="at">style=</span><span class="st">"grid"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Data Frame Summary  
birds  
Dimensions: 30977 x 14  
Duplicates: 0  

+----+------------------+--------------------------------+-----------------------+----------------------+----------+---------+
| No | Variable         | Stats / Values                 | Freqs (% of Valid)    | Graph                | Valid    | Missing |
+====+==================+================================+=======================+======================+==========+=========+
| 1  | Domain.Code      | 1. QA                          | 30977 (100.0%)        | IIIIIIIIIIIIIIIIIIII | 30977    | 0       |
|    | [character]      |                                |                       |                      | (100.0%) | (0.0%)  |
+----+------------------+--------------------------------+-----------------------+----------------------+----------+---------+
| 2  | Domain           | 1. Live Animals                | 30977 (100.0%)        | IIIIIIIIIIIIIIIIIIII | 30977    | 0       |
|    | [character]      |                                |                       |                      | (100.0%) | (0.0%)  |
+----+------------------+--------------------------------+-----------------------+----------------------+----------+---------+
| 3  | Area.Code        | Mean (sd) : 1201.7 (2099.4)    | 248 distinct values   | :                    | 30977    | 0       |
|    | [integer]        | min &lt; med &lt; max:               |                       | :                    | (100.0%) | (0.0%)  |
|    |                  | 1 &lt; 156 &lt; 5504                 |                       | :                    |          |         |
|    |                  | IQR (CV) : 152 (1.7)           |                       | :                 .  |          |         |
|    |                  |                                |                       | :                 :  |          |         |
+----+------------------+--------------------------------+-----------------------+----------------------+----------+---------+
| 4  | Area             | 1. Africa                      |   290 ( 0.9%)         |                      | 30977    | 0       |
|    | [character]      | 2. Asia                        |   290 ( 0.9%)         |                      | (100.0%) | (0.0%)  |
|    |                  | 3. Eastern Asia                |   290 ( 0.9%)         |                      |          |         |
|    |                  | 4. Egypt                       |   290 ( 0.9%)         |                      |          |         |
|    |                  | 5. Europe                      |   290 ( 0.9%)         |                      |          |         |
|    |                  | 6. France                      |   290 ( 0.9%)         |                      |          |         |
|    |                  | 7. Greece                      |   290 ( 0.9%)         |                      |          |         |
|    |                  | 8. Myanmar                     |   290 ( 0.9%)         |                      |          |         |
|    |                  | 9. Northern Africa             |   290 ( 0.9%)         |                      |          |         |
|    |                  | 10. South-eastern Asia         |   290 ( 0.9%)         |                      |          |         |
|    |                  | [ 238 others ]                 | 28077 (90.6%)         | IIIIIIIIIIIIIIIIII   |          |         |
+----+------------------+--------------------------------+-----------------------+----------------------+----------+---------+
| 5  | Element.Code     | 1 distinct value               | 5112 : 30977 (100.0%) | IIIIIIIIIIIIIIIIIIII | 30977    | 0       |
|    | [integer]        |                                |                       |                      | (100.0%) | (0.0%)  |
+----+------------------+--------------------------------+-----------------------+----------------------+----------+---------+
| 6  | Element          | 1. Stocks                      | 30977 (100.0%)        | IIIIIIIIIIIIIIIIIIII | 30977    | 0       |
|    | [character]      |                                |                       |                      | (100.0%) | (0.0%)  |
+----+------------------+--------------------------------+-----------------------+----------------------+----------+---------+
| 7  | Item.Code        | Mean (sd) : 1066.5 (9)         | 1057 : 13074 (42.2%)  | IIIIIIII             | 30977    | 0       |
|    | [integer]        | min &lt; med &lt; max:               | 1068 :  6909 (22.3%)  | IIII                 | (100.0%) | (0.0%)  |
|    |                  | 1057 &lt; 1068 &lt; 1083             | 1072 :  4136 (13.4%)  | II                   |          |         |
|    |                  | IQR (CV) : 15 (0)              | 1079 :  5693 (18.4%)  | III                  |          |         |
|    |                  |                                | 1083 :  1165 ( 3.8%)  |                      |          |         |
+----+------------------+--------------------------------+-----------------------+----------------------+----------+---------+
| 8  | Item             | 1. Chickens                    | 13074 (42.2%)         | IIIIIIII             | 30977    | 0       |
|    | [character]      | 2. Ducks                       |  6909 (22.3%)         | IIII                 | (100.0%) | (0.0%)  |
|    |                  | 3. Geese and guinea fowls      |  4136 (13.4%)         | II                   |          |         |
|    |                  | 4. Pigeons, other birds        |  1165 ( 3.8%)         |                      |          |         |
|    |                  | 5. Turkeys                     |  5693 (18.4%)         | III                  |          |         |
+----+------------------+--------------------------------+-----------------------+----------------------+----------+---------+
| 9  | Year.Code        | Mean (sd) : 1990.6 (16.7)      | 58 distinct values    | . . .   . :   : : :  | 30977    | 0       |
|    | [integer]        | min &lt; med &lt; max:               |                       | : : : . : : : : : :  | (100.0%) | (0.0%)  |
|    |                  | 1961 &lt; 1992 &lt; 2018             |                       | : : : : : : : : : :  |          |         |
|    |                  | IQR (CV) : 29 (0)              |                       | : : : : : : : : : :  |          |         |
|    |                  |                                |                       | : : : : : : : : : :  |          |         |
+----+------------------+--------------------------------+-----------------------+----------------------+----------+---------+
| 10 | Year             | Mean (sd) : 1990.6 (16.7)      | 58 distinct values    | . . .   . :   : : :  | 30977    | 0       |
|    | [integer]        | min &lt; med &lt; max:               |                       | : : : . : : : : : :  | (100.0%) | (0.0%)  |
|    |                  | 1961 &lt; 1992 &lt; 2018             |                       | : : : : : : : : : :  |          |         |
|    |                  | IQR (CV) : 29 (0)              |                       | : : : : : : : : : :  |          |         |
|    |                  |                                |                       | : : : : : : : : : :  |          |         |
+----+------------------+--------------------------------+-----------------------+----------------------+----------+---------+
| 11 | Unit             | 1. 1000 Head                   | 30977 (100.0%)        | IIIIIIIIIIIIIIIIIIII | 30977    | 0       |
|    | [character]      |                                |                       |                      | (100.0%) | (0.0%)  |
+----+------------------+--------------------------------+-----------------------+----------------------+----------+---------+
| 12 | Value            | Mean (sd) : 99410.6 (720611.4) | 11495 distinct values | :                    | 29941    | 1036    |
|    | [integer]        | min &lt; med &lt; max:               |                       | :                    | (96.7%)  | (3.3%)  |
|    |                  | 0 &lt; 1800 &lt; 23707134            |                       | :                    |          |         |
|    |                  | IQR (CV) : 15233 (7.2)         |                       | :                    |          |         |
|    |                  |                                |                       | :                    |          |         |
+----+------------------+--------------------------------+-----------------------+----------------------+----------+---------+
| 13 | Flag             | 1. (Empty string)              | 10773 (34.8%)         | IIIIII               | 30977    | 0       |
|    | [character]      | 2. *                           |  1494 ( 4.8%)         |                      | (100.0%) | (0.0%)  |
|    |                  | 3. A                           |  6488 (20.9%)         | IIII                 |          |         |
|    |                  | 4. F                           | 10007 (32.3%)         | IIIIII               |          |         |
|    |                  | 5. Im                          |  1213 ( 3.9%)         |                      |          |         |
|    |                  | 6. M                           |  1002 ( 3.2%)         |                      |          |         |
+----+------------------+--------------------------------+-----------------------+----------------------+----------+---------+
| 14 | Flag.Description | 1. Aggregate, may include of   |  6488 (20.9%)         | IIII                 | 30977    | 0       |
|    | [character]      | 2. Data not available          |  1002 ( 3.2%)         |                      | (100.0%) | (0.0%)  |
|    |                  | 3. FAO data based on imputat   |  1213 ( 3.9%)         |                      |          |         |
|    |                  | 4. FAO estimate                | 10007 (32.3%)         | IIIIII               |          |         |
|    |                  | 5. Official data               | 10773 (34.8%)         | IIIIII               |          |         |
|    |                  | 6. Unofficial figure           |  1494 ( 4.8%)         |                      |          |         |
+----+------------------+--------------------------------+-----------------------+----------------------+----------+---------+</code></pre>
</div>
</div>
<p>Here, I have used dfsummary for the entire dataset. It provides a clear description of the data.We can see that there are 30977 rows and 15 columns. As had been obseved before, there are 248 area codes. In the composition of birds, we can see that chickens comprise of 42.2% of the total, followed by ducks (22.3%), Geese and Guinea Fowls (13.4%), Pigeons (3.8%) and Turkeys (18.4%). From the flag description, it can be observed that 34.8% of the data have been obtained from official sources, 32.3% are FAO estimates, 20.9% comprise of other aggregation.</p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="DACSS/601_Spring_2023" data-repo-id="R_kgDOI4JcJA" data-category="Announcements" data-category-id="" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb13" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Challenge 1"</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Aritra Basu"</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="an">desription:</span><span class="co"> "Reading in data and creating a post"</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "02/28/2023"</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a><span class="co">    code-copy: true</span></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span></span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a><span class="co">  - challenge_1</span></span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a><span class="co">  - Aritra Basu</span></span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a><span class="co">  - wildbirds</span></span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: setup</span></span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb13-23"><a href="#cb13-23" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb13-24"><a href="#cb13-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-25"><a href="#cb13-25" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb13-26"><a href="#cb13-26" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb13-27"><a href="#cb13-27" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(descr)</span>
<span id="cb13-28"><a href="#cb13-28" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(summarytools)</span>
<span id="cb13-29"><a href="#cb13-29" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">TRUE</span>, <span class="at">warning=</span><span class="cn">FALSE</span>, <span class="at">message=</span><span class="cn">FALSE</span>)</span>
<span id="cb13-30"><a href="#cb13-30" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb13-31"><a href="#cb13-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-32"><a href="#cb13-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-33"><a href="#cb13-33" aria-hidden="true" tabindex="-1"></a><span class="fu">## Reading the Data</span></span>
<span id="cb13-34"><a href="#cb13-34" aria-hidden="true" tabindex="-1"></a>I have decided to work on the dataset birds:</span>
<span id="cb13-37"><a href="#cb13-37" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb13-38"><a href="#cb13-38" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb13-39"><a href="#cb13-39" aria-hidden="true" tabindex="-1"></a>birds <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"_data/birds.csv"</span>)</span>
<span id="cb13-40"><a href="#cb13-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-41"><a href="#cb13-41" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb13-42"><a href="#cb13-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-43"><a href="#cb13-43" aria-hidden="true" tabindex="-1"></a><span class="fu">## Describing the data</span></span>
<span id="cb13-44"><a href="#cb13-44" aria-hidden="true" tabindex="-1"></a>Using the package descr, it can be seen that the dataset contains observations on birds from 1976 to 2018. We can see the frequency. The summary statistics, because of the nature of the variables is not very useful here.</span>
<span id="cb13-45"><a href="#cb13-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-48"><a href="#cb13-48" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb13-49"><a href="#cb13-49" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages('descr')</span></span>
<span id="cb13-50"><a href="#cb13-50" aria-hidden="true" tabindex="-1"></a><span class="co">#library(descr)</span></span>
<span id="cb13-51"><a href="#cb13-51" aria-hidden="true" tabindex="-1"></a><span class="fu">descr</span>(birds)</span>
<span id="cb13-52"><a href="#cb13-52" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb13-53"><a href="#cb13-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-54"><a href="#cb13-54" aria-hidden="true" tabindex="-1"></a>Using n_distinct, it can be observed that there are 248 distinct area codes.</span>
<span id="cb13-57"><a href="#cb13-57" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb13-58"><a href="#cb13-58" aria-hidden="true" tabindex="-1"></a>birds<span class="sc">%&gt;%</span></span>
<span id="cb13-59"><a href="#cb13-59" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Area.Code)<span class="sc">%&gt;%</span></span>
<span id="cb13-60"><a href="#cb13-60" aria-hidden="true" tabindex="-1"></a>  <span class="fu">n_distinct</span>(.)</span>
<span id="cb13-61"><a href="#cb13-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-62"><a href="#cb13-62" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb13-63"><a href="#cb13-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-64"><a href="#cb13-64" aria-hidden="true" tabindex="-1"></a>Next, we could look at a cross sectional component by looking at the dataset for a particular year. Say, we want to filter chickens in 1962, and looking at area, items and value.</span>
<span id="cb13-67"><a href="#cb13-67" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb13-68"><a href="#cb13-68" aria-hidden="true" tabindex="-1"></a>birds<span class="sc">%&gt;%</span></span>
<span id="cb13-69"><a href="#cb13-69" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Area, Item, Value, Year)<span class="sc">%&gt;%</span></span>
<span id="cb13-70"><a href="#cb13-70" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Year<span class="sc">==</span><span class="st">"1962"</span>, Item<span class="sc">==</span><span class="st">"Chickens"</span>)</span>
<span id="cb13-71"><a href="#cb13-71" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb13-72"><a href="#cb13-72" aria-hidden="true" tabindex="-1"></a>Next, I identify the missing values for 1962.</span>
<span id="cb13-75"><a href="#cb13-75" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb13-76"><a href="#cb13-76" aria-hidden="true" tabindex="-1"></a>birds<span class="sc">%&gt;%</span></span>
<span id="cb13-77"><a href="#cb13-77" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Area, Element, Item, Value, Year)<span class="sc">%&gt;%</span></span>
<span id="cb13-78"><a href="#cb13-78" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Year <span class="sc">==</span> <span class="st">"1962"</span>)<span class="sc">%&gt;%</span></span>
<span id="cb13-79"><a href="#cb13-79" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">is.na</span>(Value))</span>
<span id="cb13-80"><a href="#cb13-80" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb13-81"><a href="#cb13-81" aria-hidden="true" tabindex="-1"></a>Trying another function: dfsummary. This function is provided by the package summary tools. </span>
<span id="cb13-84"><a href="#cb13-84" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb13-85"><a href="#cb13-85" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages('summarytools')</span></span>
<span id="cb13-86"><a href="#cb13-86" aria-hidden="true" tabindex="-1"></a><span class="co">#library(summarytools)</span></span>
<span id="cb13-87"><a href="#cb13-87" aria-hidden="true" tabindex="-1"></a><span class="fu">dfSummary</span>(birds, <span class="at">style=</span><span class="st">"grid"</span>)</span>
<span id="cb13-88"><a href="#cb13-88" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb13-89"><a href="#cb13-89" aria-hidden="true" tabindex="-1"></a>Here, I have used dfsummary for the entire dataset. It provides a clear description of the data.We can see that there are 30977 rows and 15 columns. As had been obseved before, there are 248 area codes. In the composition of birds, we can see that chickens comprise of 42.2% of the total, followed by ducks (22.3%), Geese and Guinea Fowls (13.4%), Pigeons (3.8%) and Turkeys (18.4%). From the flag description, it can be observed that 34.8% of the data have been obtained from official sources, 32.3% are FAO estimates, 20.9% comprise of other aggregation.</span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>