---
title: "Challenge 1 Analysis"
author: "Connor Landreth"
desription: "Read-in and description of Bird data"
date: "03/01/2023"
format:
  html:
    toc: true
    code-fold: true
    code-copy: true
    code-tools: true
categories:
  - challenge1
  - Connor Landreth
  - birds.csv
  - tidyr, diplyr, utils
---

```{r}
#| label: setup
#| warning: false

library(tidyverse)

knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#....Setup....

setwd("C:/Github Projects/601_Spring_2023/posts/_data")

library(tidyr)
library(tidyverse)
library(dplyr)
library(utils)

#.... Read in birds.csv ....
birds <- read.csv("birds.csv")
View(birds)

```

```{r}
#....Isolate Variables with Select().....
birds %>% 
  select(Area, Item, Year, Value) %>% 
  View()

#..... Summary .....
birds %>% 
  select(Area, Item, Year, Value) %>% 
  summary()

unique(birds$Item)

table(birds$Item)
birds %>% 
  select(Area, Item, Year) %>% 
  filter(Item %in% c("Ducks", "Chickens")) %>% 
  table()
```
```{r}
# Although manipulation was not perfect, in exploring the data, it has become clear it is: Quantity of various types of bird species present in each country by year.
```
