---
title: "Describing Cross-sectional Survey Data 2021"
author: "Dirichi Umunna"
desription: "Loading and Describing the dataset"
date: "02/12/2023"
format:
  html:
    toc: true
    code-fold: true
    code-copy: true
    code-tools: true
categories:
  - hw1
  - challenge1
  - Dirichi Umunna
  - dataset (abc_poll_2021)
  - ggplot2
---

```{r}
#| label: setup
#| warning: false

library(tidyverse)

knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
abc_poll_2021 <- read_csv("/Users/dirichiumunna/Documents/DACS601/GITHUB/dacss601_spring2023/posts/_data/abc_poll_2021.csv")
View(abc_poll_2021)
```

## Getting descriptive statistics of the data set

```{r}
summary(abc_poll_2021)

```

## Identifying variable name

```{r}
names(abc_poll_2021)

# trying all the means to get a description of the variables in the dataset and the result does not exactly give me the complete names. It seems like I have gone beyond my pay grade for today.
```

## Attempted scatter plot of two variables

```{r}

plot(abc_poll_2021$ppgender, abc_poll_2021$ppmarit5)

#this data needs to be cleaned. To be continued...

```
