---
title: "Boahen_Final_Proposal"
author: "Eli B"
date: "2023-04-18"
output: html_document
---

## Introductions
This page will explain my final project for DACSS 601

## Background
>Stress in the US

I did a self Designed major in Arts and Technology, combining Computer Science, Engineering, Art, and Design into one field of study. I believe that IDP ( interdisciplinary ) is an amazing way to not only problem solve, but verify a problem in the first place.

## Research Questions
>Qualitative Questions
- What trends can we see when human stress increases or decreases
- To what degree have life events have impacted stress?
- Are

>Quanatative Questions
1. Is there a correlation between stress and age?
2. Is there a correlation between stress and health?
3. Is there a correlation between identities ( gender, race, etc. ) and their stress over time?

## Goals
In this project, I want to explore the stress of humans over time because I believe this can be important in understanding how and why we connect with technology the way we do. My research interests include Cyborg Anthropology, HCI, and AI Ethics. This is my first step towards exploring anthropology and ethnography and how that connects with technology.

If I have time, I want to add COVID-19 data and find data on technology usage and see what information we can gain when we overlap stress, health, and technology.


## Why Did I Pick This Project?
I am interested in the IOT and assistive devices and I want to explore their overlaps with the health sector. I believe that by auditing and establishing ethical codes for data collection, machine un-learning, and LLMs ( language learning models ), we can create technology that improves the health and well being of humans

