<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.361">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Abhinav Reddy Yadatha">
<meta name="dcterms.date" content="2023-05-21">
<meta name="description" content="Final Project writeup">

<title>Final Project: Abhinav Reddy Yadatha</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../images/DACSS_Round_Network.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

<link href="../site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">
<script src="../site_libs/pagedtable-1.1/js/pagedtable.js"></script>


<link rel="stylesheet" href="styles.css">
<meta name="twitter:title" content="Final Project: Abhinav Reddy Yadatha">
<meta name="twitter:description" content="Final Project writeup">
<meta name="twitter:image" content="https://dacss.github.io/601_Spring_2023/posts/final_project_AbhinavReddyYadatha_files/figure-html/unnamed-chunk-11-1.png">
<meta name="twitter:creator" content="@UMassDACSS">
<meta name="twitter:site" content="@UMassDACSS">
<meta name="twitter:image-height" content="960">
<meta name="twitter:image-width" content="1344">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../images/UMass White Wordmark Horiz.png" alt="" class="navbar-logo">
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://github.com/DACSS" rel="" target="">
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html" rel="" target="">
 <span class="menu-text">Contributors</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://umass.edu/sbs/dacss" rel="" target="">
 <span class="menu-text">DACSS</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/DACSS" rel="" target=""><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#part-1.-introduction" id="toc-part-1.-introduction" class="nav-link active" data-scroll-target="#part-1.-introduction">Part 1. Introduction</a></li>
  <li><a href="#part-2.-background-of-the-topicliterature-review" id="toc-part-2.-background-of-the-topicliterature-review" class="nav-link" data-scroll-target="#part-2.-background-of-the-topicliterature-review">Part 2. Background of the Topic/Literature Review</a></li>
  <li><a href="#part-3.-dataset-introduction" id="toc-part-3.-dataset-introduction" class="nav-link" data-scroll-target="#part-3.-dataset-introduction">Part 3. Dataset Introduction</a></li>
  <li><a href="#part-4.-dataset-description" id="toc-part-4.-dataset-description" class="nav-link" data-scroll-target="#part-4.-dataset-description">Part 4. Dataset Description</a></li>
  <li><a href="#part-5.-analysis-plan" id="toc-part-5.-analysis-plan" class="nav-link" data-scroll-target="#part-5.-analysis-plan">Part 5. Analysis Plan</a></li>
  <li><a href="#part-6.-survival-rate-analysis-and-visualization" id="toc-part-6.-survival-rate-analysis-and-visualization" class="nav-link" data-scroll-target="#part-6.-survival-rate-analysis-and-visualization">Part 6. Survival Rate Analysis and Visualization</a></li>
  <li><a href="#part-7.-conclusion-and-discussion" id="toc-part-7.-conclusion-and-discussion" class="nav-link" data-scroll-target="#part-7.-conclusion-and-discussion">Part 7. Conclusion and Discussion :</a></li>
  <li><a href="#part-8.-bibliography" id="toc-part-8.-bibliography" class="nav-link" data-scroll-target="#part-8.-bibliography">Part 8. Bibliography :</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Final Project: Abhinav Reddy Yadatha</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
  <div class="quarto-categories">
    <div class="quarto-category">final_Project</div>
  </div>
  </div>

<div>
  <div class="description">
    Final Project writeup
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Abhinav Reddy Yadatha </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 21, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">TRUE</span>, <span class="at">warning=</span><span class="cn">FALSE</span>, <span class="at">message=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="part-1.-introduction" class="level2">
<h2 class="anchored" data-anchor-id="part-1.-introduction">Part 1. Introduction</h2>
<p>Project Topic: The project aims to analyze the factors influencing the survival of passengers aboard the RMS Titanic during its tragic maiden voyage in 1912.</p>
<p>General Research Question: What were the determinants of survival among the passengers on the Titanic?</p>
<p>Dataset Description: The project utilizes the Titanic dataset, a well-known and frequently used dataset in data analysis and machine learning tasks. This dataset is derived from the passenger manifest of the RMS Titanic and has been curated by various organizations and individuals for educational and research purposes. Each row in the dataset represents a passenger who was aboard the Titanic during its ill-fated voyage.</p>
<p>The dataset includes a range of variables such as the passenger’s name, age, gender, passenger class, ticket fare, cabin number, port of embarkation, survival status, and more. These attributes were collected from passenger records, survivor interviews, and historical documents related to the disaster. The dataset encompasses both survivors and non-survivors, with the survival status column indicating whether a passenger survived (labeled as “1”) or did not survive (labeled as “0”) the sinking of the Titanic.</p>
<p>Unit of Analysis: In the Titanic dataset, each case or unit of analysis refers to an individual passenger who was on board the Titanic. The dataset contains information for 891 passengers, with each row representing a unique passenger and the associated attributes.</p>
<p>The project aims to explore the relationships between various factors such as gender, age, passenger class, family size, and cabin location with the survival outcome. By analyzing this dataset, we can gain insights into the demographics and characteristics of the passengers, investigate the impact of different variables on survival rates, and uncover patterns and correlations that shed light on the tragic events of the Titanic disaster.</p>
</section>
<section id="part-2.-background-of-the-topicliterature-review" class="level2">
<h2 class="anchored" data-anchor-id="part-2.-background-of-the-topicliterature-review">Part 2. Background of the Topic/Literature Review</h2>
<p>The sinking of the Titanic in 1912 remains a captivating and tragic event in history. By analyzing the factors that influenced the survival of its passengers, we can gain valuable insights into the social dynamics, inequalities, and decision-making processes of that time. Exploring the Titanic dataset allows us to uncover patterns and correlations that have practical implications for emergency preparedness today. Understanding the determinants of survival on the Titanic not only deepens our knowledge of this historic event but also offers lessons for enhancing safety and well-being in future crises.</p>
</section>
<section id="part-3.-dataset-introduction" class="level2">
<h2 class="anchored" data-anchor-id="part-3.-dataset-introduction">Part 3. Dataset Introduction</h2>
<p>The Titanic dataset is a widely recognized and extensively used dataset for data analysis and machine learning purposes. It originates from the passenger manifest of the RMS Titanic, a British passenger liner that tragically sank during its inaugural voyage in April 1912. Numerous organizations and individuals have carefully compiled and organized the dataset for educational and research applications based on the real-life incident. Each row in the dataset corresponds to an individual passenger who was on board the Titanic during its ill-fated journey. The dataset comprises various attributes pertaining to the passengers, including their names, ages, genders, passenger classes, ticket fares, cabin numbers, ports of embarkation, survival status, and more. These attributes were gathered from passenger records, survivor interviews, and historical documents related to the disaster. The dataset encompasses both survivors and non-survivors, with the survival status column denoting whether a passenger survived (labeled as “1”) or did not survive (labeled as “0”) the sinking of the Titanic.</p>
</section>
<section id="part-4.-dataset-description" class="level2">
<h2 class="anchored" data-anchor-id="part-4.-dataset-description">Part 4. Dataset Description</h2>
<p>(Story) This dataset contains a total of 891 rows and 12 columns and the descriptive information about what each of the 12 fields are given below :</p>
<p>PassengerId: A unique identifier assigned to each passenger. Survived: Indicates whether the passenger survived the sinking or not (0 = No, 1 = Yes). Pclass: Represents the passenger class (1 = 1st class, 2 = 2nd class, 3 = 3rd class). Name: The name of the passenger. Sex: The gender of the passenger (Male or Female). Age: The age of the passenger in years (some values may be missing). SibSp: The number of siblings/spouses aboard the Titanic. Parch: The number of parents/children aboard the Titanic. Ticket: The ticket number of the passenger. Fare: The fare or ticket price paid by the passenger Cabin: The cabin number assigned to the passenger (some values may be missing). Embarked: The port of embarkation (C = Cherbourg, Q = Queenstown, S = Southampton).</p>
<p>Coding Component:</p>
<ol type="1">
<li>Read the titanic dataset;</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#read and get a overview of the data</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"AbhinavReddyYadatha_FinalProjectData/titanic.csv"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">view</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="2" type="1">
<li><p>Descriptive information of the titanic dataset :</p>
<p>::: {.cell}</p>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Checking the dimensions of the data</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>::: {.cell-output .cell-output-stdout} <code>[1] 891  12</code> :::</p>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># checking the unique age group count</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">unique</span>(data<span class="sc">$</span>Age))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>::: {.cell-output .cell-output-stdout} <code>[1] 89</code> :::</p>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co">#printing out the first few examples</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>::: {.cell-output-display}</p>

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["PassengerId"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["Survived"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["Pclass"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["Name"],"name":[4],"type":["chr"],"align":["left"]},{"label":["Sex"],"name":[5],"type":["chr"],"align":["left"]},{"label":["Age"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["SibSp"],"name":[7],"type":["dbl"],"align":["right"]},{"label":["Parch"],"name":[8],"type":["dbl"],"align":["right"]},{"label":["Ticket"],"name":[9],"type":["chr"],"align":["left"]},{"label":["Fare"],"name":[10],"type":["dbl"],"align":["right"]},{"label":["Cabin"],"name":[11],"type":["chr"],"align":["left"]},{"label":["Embarked"],"name":[12],"type":["chr"],"align":["left"]}],"data":[{"1":"1","2":"0","3":"3","4":"Braund, Mr. Owen Harris","5":"male","6":"22","7":"1","8":"0","9":"A/5 21171","10":"7.2500","11":"NA","12":"S"},{"1":"2","2":"1","3":"1","4":"Cumings, Mrs. John Bradley (Florence Briggs Thayer)","5":"female","6":"38","7":"1","8":"0","9":"PC 17599","10":"71.2833","11":"C85","12":"C"},{"1":"3","2":"1","3":"3","4":"Heikkinen, Miss. Laina","5":"female","6":"26","7":"0","8":"0","9":"STON/O2. 3101282","10":"7.9250","11":"NA","12":"S"},{"1":"4","2":"1","3":"1","4":"Futrelle, Mrs. Jacques Heath (Lily May Peel)","5":"female","6":"35","7":"1","8":"0","9":"113803","10":"53.1000","11":"C123","12":"S"},{"1":"5","2":"0","3":"3","4":"Allen, Mr. William Henry","5":"male","6":"35","7":"0","8":"0","9":"373450","10":"8.0500","11":"NA","12":"S"},{"1":"6","2":"0","3":"3","4":"Moran, Mr. James","5":"male","6":"NA","7":"0","8":"0","9":"330877","10":"8.4583","11":"NA","12":"Q"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>::: :::</p></li>
<li><p>Conduct summary statistics of the dataset :</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Displaying the summary of the titanic data</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  PassengerId       Survived          Pclass          Name          
 Min.   :  1.0   Min.   :0.0000   Min.   :1.000   Length:891        
 1st Qu.:223.5   1st Qu.:0.0000   1st Qu.:2.000   Class :character  
 Median :446.0   Median :0.0000   Median :3.000   Mode  :character  
 Mean   :446.0   Mean   :0.3838   Mean   :2.309                     
 3rd Qu.:668.5   3rd Qu.:1.0000   3rd Qu.:3.000                     
 Max.   :891.0   Max.   :1.0000   Max.   :3.000                     
                                                                    
     Sex                 Age            SibSp           Parch       
 Length:891         Min.   : 0.42   Min.   :0.000   Min.   :0.0000  
 Class :character   1st Qu.:20.12   1st Qu.:0.000   1st Qu.:0.0000  
 Mode  :character   Median :28.00   Median :0.000   Median :0.0000  
                    Mean   :29.70   Mean   :0.523   Mean   :0.3816  
                    3rd Qu.:38.00   3rd Qu.:1.000   3rd Qu.:0.0000  
                    Max.   :80.00   Max.   :8.000   Max.   :6.0000  
                    NA's   :177                                     
    Ticket               Fare           Cabin             Embarked        
 Length:891         Min.   :  0.00   Length:891         Length:891        
 Class :character   1st Qu.:  7.91   Class :character   Class :character  
 Mode  :character   Median : 14.45   Mode  :character   Mode  :character  
                    Mean   : 32.20                                        
                    3rd Qu.: 31.00                                        
                    Max.   :512.33                                        
                                                                          </code></pre>
</div>
</div>
<p>Exploring the variables of the dataset :</p>
<p>Variable : Sex</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Count the number of males and females</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>gender_counts <span class="ot">&lt;-</span> <span class="fu">table</span>(data<span class="sc">$</span>Sex)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the counts</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>gender_counts</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
female   male 
   314    577 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the total number of passengers</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>total_passengers <span class="ot">&lt;-</span> <span class="fu">nrow</span>(data)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the number of female passengers</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>male_passengers <span class="ot">&lt;-</span> <span class="fu">sum</span>(data<span class="sc">$</span>Sex <span class="sc">==</span> <span class="st">"male"</span>)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the percentage of females</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>percentage_males <span class="ot">&lt;-</span> (male_passengers <span class="sc">/</span> total_passengers) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the percentage of females</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>percentage_males</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 64.7587</code></pre>
</div>
</div>
<p>This variable refers to the gender of the passenger. It can be observed that there are 314 females and 577 males. Hence, the majority of the proportion of males is higher , in fact it’s a staggering ‘64.7587%’.</p>
<p>Variable : Survived</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Count the number of passengers survived.</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>survived_counts <span class="ot">&lt;-</span> <span class="fu">table</span>(data<span class="sc">$</span>Survived)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the counts</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>survived_counts</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  0   1 
549 342 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the number of survived passengers</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>survived_passengers <span class="ot">&lt;-</span> <span class="fu">sum</span>(data<span class="sc">$</span>Survived <span class="sc">==</span> <span class="st">"1"</span>)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the percentage of survived passengers</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>percentage_survived <span class="ot">&lt;-</span> (survived_passengers <span class="sc">/</span> total_passengers) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the percentage of survived passengers</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>percentage_survived</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 38.38384</code></pre>
</div>
</div>
<p>This variable indicates if a passenger has survived or not, it can be observed that only 342 passengers survived out of the total of 891 passengers. The survival rate of the titanic was just a mere 38.38384 %</p>
<p>Variable Pclass:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Count the number of passengers in each passenger class</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>pclass_counts <span class="ot">&lt;-</span> <span class="fu">table</span>(data<span class="sc">$</span>Pclass)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the counts</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>pclass_counts</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  1   2   3 
216 184 491 </code></pre>
</div>
</div>
<p>It can be observed that a majority of the passengers were travelling in class 3, then class 1 and the least in class 2.</p>
<p>Variable : Fare</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the maximum fare</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>max_fare <span class="ot">&lt;-</span> <span class="fu">max</span>(data<span class="sc">$</span>Fare, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the minimum fare</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>min_fare <span class="ot">&lt;-</span> <span class="fu">min</span>(data<span class="sc">$</span>Fare, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the maximum and minimum fare</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>max_fare</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 512.3292</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>min_fare</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the mean fare</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>mean_fare <span class="ot">&lt;-</span> <span class="fu">mean</span>(data<span class="sc">$</span>Fare, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the mean fare</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>mean_fare</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 32.20421</code></pre>
</div>
</div>
<p>From the analysis above it can be observed that there were passengers who did not have to pay any fare whereas others had to pay a maximum of 512.3292. The mean fare paid by the passengers is 32.20421 USD.</p>
<p>Variable Age :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the maximum age</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>max_age <span class="ot">&lt;-</span> <span class="fu">max</span>(data<span class="sc">$</span>Age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the minimum age</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>min_age <span class="ot">&lt;-</span> <span class="fu">min</span>(data<span class="sc">$</span>Age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the maximum and minimum age</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>max_age</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 80</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>min_age</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.42</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the mean age</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>mean_age <span class="ot">&lt;-</span> <span class="fu">mean</span>(data<span class="sc">$</span>Age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the mean age</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>mean_age</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 29.69912</code></pre>
</div>
</div>
<p>There were people from all ages on the titanic. The maximum age being 80 and the minimum age being 0.42 while the mean age is 29.69912 ~ 30 years.</p>
</section>
<section id="part-5.-analysis-plan" class="level2">
<h2 class="anchored" data-anchor-id="part-5.-analysis-plan">Part 5. Analysis Plan</h2>
<p>Specific questions :</p>
<ol type="1">
<li><p>What was the overall survival rate of passengers aboard the Titanic?</p></li>
<li><p>How does the survival rate vary based on passenger gender?</p></li>
<li><p>Did the passenger class have an impact on the survival rate?</p></li>
<li><p>What were the survival rates for passengers with family members aboard the Titanic versus those traveling alone</p></li>
<li><p>How does the survival rate differ among different age groups or passenger classes?</p></li>
<li><p>What was the distribution of ages among the passengers, and did age play a role in survival?</p></li>
<li><p>How does the ticket fare correlate with the passenger class and survival?</p></li>
</ol>
<p>Analysis Plan :</p>
<p>To answer the research questions mentioned above, I plan to conduct a combination of data analysis and visualization techniques.</p>
<p>Descriptive Statistics: I will calculate summary statistics such as means, medians, and proportions to provide an overview of the variables of interest, including survival rates based on different categories.</p>
<p>Bar Charts: I will create bar charts to visualize the relationship between categorical variables (e.g., passenger class, gender, port of embarkation) and survival rates. This will allow for a quick comparison of survival probabilities across different categories.</p>
<p>Histograms : I will use histograms to explore the distribution of continuous variables (e.g., age, fare) for both survivors and non-survivors. This will help identify any patterns or differences in the distributions between the two groups.</p>
<p>Boxplots: Boxplots will be used to compare the median age and fare of survivors and non-survivors, providing insights into potential differences in these variables.</p>
<p>Data Analyses I plan to do for this project are as follows :</p>
<p>Survival Rate Analysis:</p>
<p>Calculate the overall survival rate of passengers (percentage of survivors) to provide an initial understanding of survival outcomes.</p>
<p>Gender-based Analysis:</p>
<p>Compare the survival rates of male and female passengers using a bivariate visualization (such as a bar chart or stacked bar plot) to explore the potential impact of gender on survival.</p>
<p>Passenger Class Analysis:</p>
<p>Examine the survival rates across different passenger classes (first, second, and third) using visualizations (such as a stacked bar chart) to investigate the relationship between socio-economic status and survival.</p>
<p>Age Distribution Analysis:</p>
<p>Plot the age distribution of passengers using a histogram to visualize the age groups and identify any patterns or trends in survival rates within different age ranges.</p>
<p>Family Size Analysis:</p>
<p>Investigate the relationship between family size (based on the SibSp and Parch variables) and survival rates using a bivariate visualization (such as a scatter plot or grouped bar chart) to explore the impact of traveling with family members on survival.</p>
<p>Bivariate Visualization:</p>
<p>Bivariate visualizations, such as bar charts or stacked bar plots, are useful for comparing two variables, such as gender and survival or passenger class and survival. They allow us to visually examine the relationship between two categorical variables and observe any patterns or differences in survival rates based on these variables.</p>
<p>Scatter Plot:</p>
<p>Scatter plots are valuable for analyzing the relationship between two continuous variables, such as family size and survival rates. They enable us to observe the dispersion of data points and determine if there is any correlation or trend between the variables.</p>
<p>Box Plot :</p>
<p>Box plots are excellent for comparing the distribution of a continuous variable, such as fare, between different groups (e.g., survivors vs.&nbsp;non-survivors). They provide a visual representation of the median, quartiles, and outliers in the data, allowing us to detect any variations or differences in fare distributions based on survival outcomes.</p>
<p>Calculating Age Groups:</p>
<p>Grouping passengers into age categories: You can create a new variable called “Age Group” by categorizing the passengers’ ages into different groups, such as “Child,” “Adult,” and “Elderly.” This can be done by specifying age ranges and using conditional statements or the cut() function in R. Converting Categorical Variables:</p>
<p>Mapping categorical variables to numerical values: If any categorical variables, such as “Sex” or “Embarked,” are represented as text, you can create new variables that map these categories to numerical values. For example, you can create a new variable called “Sex_Code” where “male” is encoded as 0 and “female” as 1. Calculating Family Size:</p>
<p>Creating a variable for family size: You can create a new variable called “Family Size” by summing the “SibSp” (number of siblings/spouses aboard) and “Parch” (number of parents/children aboard) variables. This new variable represents the total number of family members a passenger had onboard.</p>
<p>If any column has too much empty data, I plan to drop it completely as it would not contain a lot of information.</p>
</section>
<section id="part-6.-survival-rate-analysis-and-visualization" class="level2">
<h2 class="anchored" data-anchor-id="part-6.-survival-rate-analysis-and-visualization">Part 6. Survival Rate Analysis and Visualization</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate summary statistics for continuous variables</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data<span class="sc">$</span>Age)  <span class="co"># Summary statistics for age</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
   0.42   20.12   28.00   29.70   38.00   80.00     177 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data<span class="sc">$</span>Fare)  <span class="co"># Summary statistics for fare</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   0.00    7.91   14.45   32.20   31.00  512.33 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate summary statistics for categorical variables</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>Sex)  <span class="co"># Frequency count for gender</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
female   male 
   314    577 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>Pclass)  <span class="co"># Frequency count for passenger class</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  1   2   3 
216 184 491 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>Survived)  <span class="co"># Frequency count for survival status</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  0   1 
549 342 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate survival rates based on different categories</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>survival_rates_gender <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(<span class="fu">table</span>(data<span class="sc">$</span>Survived, data<span class="sc">$</span>Sex), <span class="at">margin =</span> <span class="dv">2</span>) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>survival_rates_class <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(<span class="fu">table</span>(data<span class="sc">$</span>Survived, data<span class="sc">$</span>Pclass), <span class="at">margin =</span> <span class="dv">2</span>) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Display survival rates w.r.t gender and class</span></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>survival_rates_gender</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   
      female     male
  0 25.79618 81.10919
  1 74.20382 18.89081</code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>survival_rates_class</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   
           1        2        3
  0 37.03704 52.71739 75.76375
  1 62.96296 47.28261 24.23625</code></pre>
</div>
</div>
<p>From the above statistics, it can be observed that approximately 75% of females have survived the tragedy whereas only nearly 19% of men have survived. A trend could be identified about the gender and the survival rate. In addition to this, based on the class it is observed that people who were in class 1 had a significantly higher survival rate compare to that of class 2 and class 3.</p>
<p>Analysis :</p>
<p>Research Question analysed : How does the survival rate vary based on passenger gender?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># count of survivors by gender</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x=</span>Sex, <span class="at">y=</span>Survived, <span class="at">fill=</span>Sex)) <span class="sc">+</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat=</span><span class="st">"identity"</span>)<span class="sc">+</span></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_grey</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="final_project_AbhinavReddyYadatha_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Survival counts of Male and Female Passengers"</span>) <span class="sc">+</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggtitle</span>(<span class="st">"Counts of female vs male survivors"</span>) <span class="sc">+</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in ggtitle("Survival counts of Male and Female Passengers") + ggtitle("Counts of female vs male survivors"): non-numeric argument to binary operator</code></pre>
</div>
</div>
<p>Research Analysed: Median age and fare from survivors and non-survivors.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create boxplots comparing the median age and fare between survivors and non-survivors</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(Survived), <span class="at">y =</span> Age)) <span class="sc">+</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">"lightblue"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Survived"</span>, <span class="at">y =</span> <span class="st">"Age"</span>, <span class="at">title =</span> <span class="st">"Boxplot of Age: Survivors vs. Non-Survivors"</span>) <span class="sc">+</span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="final_project_AbhinavReddyYadatha_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(Survived), <span class="at">y =</span> Fare)) <span class="sc">+</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">"lightblue"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Survived"</span>, <span class="at">y =</span> <span class="st">"Fare"</span>, <span class="at">title =</span> <span class="st">"Boxplot of Fare: Survivors vs. Non-Survivors"</span>) <span class="sc">+</span></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="final_project_AbhinavReddyYadatha_files/figure-html/unnamed-chunk-12-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>From the boxplots comparing the median age and fare between survivors and non-survivors, we can infer the following:</p>
<p>Age: The median age of survivors appears to be slightly lower than that of non-survivors. This suggests that there may have been a higher proportion of younger passengers who survived the Titanic disaster. However, it’s important to note that the difference in median age might not be substantial.</p>
<p>Fare: The median fare of survivors seems to be slightly higher compared to non-survivors. This indicates that passengers who paid higher fares might have had a better chance of survival. It’s possible that higher-paying passengers were assigned to more favorable locations on the ship or had access to better life-saving resources.</p>
<p>These inferences are based on the central tendency represented by the median values in the boxplots. However, it’s essential to conduct further statistical analysis to validate these observations.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the survival rates by gender</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>survival_rates_gender <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(<span class="fu">table</span>(data<span class="sc">$</span>Survived, data<span class="sc">$</span>Sex), <span class="at">margin =</span> <span class="dv">2</span>) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(survival_rates_gender)</span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>subset_df <span class="ot">&lt;-</span> <span class="fu">subset</span>(df, Var1 <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>subset_df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["Var1"],"name":[1],"type":["fct"],"align":["left"]},{"label":["Var2"],"name":[2],"type":["fct"],"align":["left"]},{"label":["Freq"],"name":[3],"type":["dbl"],"align":["right"]}],"data":[{"1":"1","2":"female","3":"74.20382","_rn_":"2"},{"1":"1","2":"male","3":"18.89081","_rn_":"4"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a bar chart to compare survival rates by gender</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> subset_df, <span class="fu">aes</span>(<span class="at">x=</span>Var2, <span class="at">y=</span>Freq, <span class="at">fill=</span>Var2)) <span class="sc">+</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="st">"stack"</span>) <span class="sc">+</span></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Gender"</span>, <span class="at">y =</span> <span class="st">"Survival rate %"</span>, <span class="at">fill =</span> <span class="st">"Survived"</span>) <span class="sc">+</span></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"blue"</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"% of females survived"</span>, <span class="st">"% of males survived"</span>)) <span class="sc">+</span></span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Survival Rates of Male VS Female Passengers"</span>) <span class="sc">+</span></span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="final_project_AbhinavReddyYadatha_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>From the above analyses, it is observed that despite the fact that there are males than compard to females, gender could be treated as an indicator survival chance. This is due to the fact that females on titanic had a survival rate of 74 % whereas the males on the same boat only had 18%.</p>
<p>Research question answered : Passenger Class Analysis Examine the survival rates across different passenger classes (first, second, and third) using visualizations (such as a Stacked bar chart) to investigate the relationship between socio-economic status and survival.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># count of survivors by passenger class via stacked bar graph</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x=</span>Pclass, <span class="at">y=</span>Survived, <span class="at">fill=</span>Sex)) <span class="sc">+</span></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat=</span><span class="st">"identity"</span>)<span class="sc">+</span></span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_grey</span>()<span class="sc">+</span></span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Survival counts of Male and Female Passengers"</span>) <span class="sc">+</span></span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggtitle</span>(<span class="st">"Counts of female vs male survivors"</span>) <span class="sc">+</span></span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="final_project_AbhinavReddyYadatha_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Bar graph to determine the relationship between survival and socio-economic status</span></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the survival rates by passenger class</span></span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>survival_rates_pclass <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(<span class="fu">table</span>(data<span class="sc">$</span>Survived, data<span class="sc">$</span>Pclass), <span class="at">margin =</span> <span class="dv">2</span>) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(survival_rates_pclass)</span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a>subset_df <span class="ot">&lt;-</span> <span class="fu">subset</span>(df, Var1 <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb52-10"><a href="#cb52-10" aria-hidden="true" tabindex="-1"></a>subset_df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["Var1"],"name":[1],"type":["fct"],"align":["left"]},{"label":["Var2"],"name":[2],"type":["fct"],"align":["left"]},{"label":["Freq"],"name":[3],"type":["dbl"],"align":["right"]}],"data":[{"1":"1","2":"1","3":"62.96296","_rn_":"2"},{"1":"1","2":"2","3":"47.28261","_rn_":"4"},{"1":"1","2":"3","3":"24.23625","_rn_":"6"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a bar chart to compare survival rates by gender</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> subset_df, <span class="fu">aes</span>(<span class="at">x=</span>Var2, <span class="at">y=</span>Freq, <span class="at">fill=</span>Var2)) <span class="sc">+</span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="st">"stack"</span>) <span class="sc">+</span></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_grey</span>() <span class="sc">+</span></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"blue"</span>, <span class="st">"green"</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Class 1 surivor %"</span>, <span class="st">"Class 2 surivor %"</span>, <span class="st">"Class 3 surivor %"</span>))<span class="sc">+</span></span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Passenger Class"</span>, <span class="at">y =</span> <span class="st">"Survival rate %"</span>, <span class="at">fill =</span> <span class="st">"Survived"</span>) <span class="sc">+</span></span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Survival Rates of Male VS Female Passengers"</span>) <span class="sc">+</span></span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="final_project_AbhinavReddyYadatha_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Two observations are made : 1. The number of passengers in class1 are significantly higher than the passengers in class 2 and class 3. 2. Despite having such high numbers, it is observed that the class 1 passengers have the highest rate of survival indicating that the passenger class type played a very important role in determining the survival.</p>
<p>Research question analysed : Age Distribution Analysis:</p>
<p>Plot the age distribution of passengers using a histogram to visualize the age groups and identify any patterns or trends in survival rates within different age ranges.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a histogram of the age distribution</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> Age)) <span class="sc">+</span></span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">5</span>, <span class="at">fill =</span> <span class="st">"lightblue"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Age"</span>, <span class="at">y =</span> <span class="st">"Frequency"</span>) <span class="sc">+</span></span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Age Distribution of Passengers"</span>) <span class="sc">+</span></span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="final_project_AbhinavReddyYadatha_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The age groups are all discrete, so we would not be in a position to analyse. So we will mutate the age column into age groups and analyse accordingly.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Mutate the 'Age' column into age groups</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>AgeGroup <span class="ot">&lt;-</span> <span class="fu">cut</span>(data<span class="sc">$</span>Age, <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">18</span>, <span class="dv">30</span>, <span class="dv">50</span>, <span class="cn">Inf</span>),</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Child"</span>, <span class="st">"Young Adult"</span>, <span class="st">"Adult"</span>, <span class="st">"Senior"</span>))</span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["PassengerId"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["Survived"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["Pclass"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["Name"],"name":[4],"type":["chr"],"align":["left"]},{"label":["Sex"],"name":[5],"type":["chr"],"align":["left"]},{"label":["Age"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["SibSp"],"name":[7],"type":["dbl"],"align":["right"]},{"label":["Parch"],"name":[8],"type":["dbl"],"align":["right"]},{"label":["Ticket"],"name":[9],"type":["chr"],"align":["left"]},{"label":["Fare"],"name":[10],"type":["dbl"],"align":["right"]},{"label":["Cabin"],"name":[11],"type":["chr"],"align":["left"]},{"label":["Embarked"],"name":[12],"type":["chr"],"align":["left"]},{"label":["AgeGroup"],"name":[13],"type":["fct"],"align":["left"]}],"data":[{"1":"1","2":"0","3":"3","4":"Braund, Mr. Owen Harris","5":"male","6":"22","7":"1","8":"0","9":"A/5 21171","10":"7.2500","11":"NA","12":"S","13":"Young Adult"},{"1":"2","2":"1","3":"1","4":"Cumings, Mrs. John Bradley (Florence Briggs Thayer)","5":"female","6":"38","7":"1","8":"0","9":"PC 17599","10":"71.2833","11":"C85","12":"C","13":"Adult"},{"1":"3","2":"1","3":"3","4":"Heikkinen, Miss. Laina","5":"female","6":"26","7":"0","8":"0","9":"STON/O2. 3101282","10":"7.9250","11":"NA","12":"S","13":"Young Adult"},{"1":"4","2":"1","3":"1","4":"Futrelle, Mrs. Jacques Heath (Lily May Peel)","5":"female","6":"35","7":"1","8":"0","9":"113803","10":"53.1000","11":"C123","12":"S","13":"Adult"},{"1":"5","2":"0","3":"3","4":"Allen, Mr. William Henry","5":"male","6":"35","7":"0","8":"0","9":"373450","10":"8.0500","11":"NA","12":"S","13":"Adult"},{"1":"6","2":"0","3":"3","4":"Moran, Mr. James","5":"male","6":"NA","7":"0","8":"0","9":"330877","10":"8.4583","11":"NA","12":"Q","13":"NA"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># For example, calculate the survival rate by age group</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>survival_rates_agegroup <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(<span class="fu">table</span>(data<span class="sc">$</span>Survived, data<span class="sc">$</span>AgeGroup), <span class="at">margin =</span> <span class="dv">2</span>) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the resulting table</span></span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>survival_rates_agegroup</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   
       Child Young Adult    Adult   Senior
  0 49.64029    64.44444 57.67635 65.62500
  1 50.35971    35.55556 42.32365 34.37500</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co"># For example, calculate the survival rate by age group</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>survival_rates_agegroup <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(<span class="fu">table</span>(data<span class="sc">$</span>Survived, data<span class="sc">$</span>AgeGroup), <span class="at">margin =</span> <span class="dv">2</span>) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(survival_rates_agegroup)</span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>subset_df <span class="ot">&lt;-</span> <span class="fu">subset</span>(df, Var1 <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a>subset_df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["Var1"],"name":[1],"type":["fct"],"align":["left"]},{"label":["Var2"],"name":[2],"type":["fct"],"align":["left"]},{"label":["Freq"],"name":[3],"type":["dbl"],"align":["right"]}],"data":[{"1":"1","2":"Child","3":"50.35971","_rn_":"2"},{"1":"1","2":"Young Adult","3":"35.55556","_rn_":"4"},{"1":"1","2":"Adult","3":"42.32365","_rn_":"6"},{"1":"1","2":"Senior","3":"34.37500","_rn_":"8"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a bar chart to compare survival rates by gender</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> subset_df, <span class="fu">aes</span>(<span class="at">x=</span>Var2, <span class="at">y=</span>Freq, <span class="at">fill=</span>Var2)) <span class="sc">+</span></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="st">"stack"</span>) <span class="sc">+</span></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_grey</span>() <span class="sc">+</span></span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"blue"</span>, <span class="st">"green"</span>, <span class="st">"orange"</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"child"</span>, <span class="st">"Young Adult"</span>, <span class="st">"Adult"</span>, <span class="st">"Senior"</span>))<span class="sc">+</span></span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Passenger Class"</span>, <span class="at">y =</span> <span class="st">"Survival rate %"</span>, <span class="at">fill =</span> <span class="st">"Survived"</span>) <span class="sc">+</span></span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Survival Rates of different age groups"</span>) <span class="sc">+</span></span>
<span id="cb59-8"><a href="#cb59-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="final_project_AbhinavReddyYadatha_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>While, it can be observed that the children have the highest survival rate and seniors have the lowest rate, it is inconclusive to say whether the age factor is a factor affecting the chance of survival as all of them are pretty close. Due to the lack of this significant gap, I am ruling out Age as an definite factor affecting the survival.</p>
<p>Research Question Analysed : Family Size Analysis:</p>
<p>Investigate the relationship between family size (based on the SibSp and Parch variables) and survival rates using a bivariate visualization (such as a scatter plot or grouped bar chart) to explore the impact of traveling with family members on survival.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Grouped bar chart </span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the total family size by adding 'SibSp' and 'Parch'</span></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>FamilySize <span class="ot">&lt;-</span> data<span class="sc">$</span>SibSp <span class="sc">+</span> data<span class="sc">$</span>Parch</span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the survival rate by family size</span></span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a>survival_rates <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(Survived <span class="sc">~</span> FamilySize, <span class="at">data =</span> data, <span class="at">FUN =</span> <span class="cf">function</span>(x) <span class="fu">sum</span>(x) <span class="sc">/</span> <span class="fu">length</span>(x) <span class="sc">*</span> <span class="dv">100</span>)</span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a grouped bar chart of survival rates by family size</span></span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(survival_rates, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">as.factor</span>(FamilySize), <span class="at">y =</span> Survived)) <span class="sc">+</span></span>
<span id="cb60-10"><a href="#cb60-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">fill =</span> <span class="st">"lightblue"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb60-11"><a href="#cb60-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Family Size"</span>, <span class="at">y =</span> <span class="st">"Survival Rate (%)"</span>) <span class="sc">+</span></span>
<span id="cb60-12"><a href="#cb60-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Relationship between Family Size and Survival Rates"</span>) <span class="sc">+</span></span>
<span id="cb60-13"><a href="#cb60-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="final_project_AbhinavReddyYadatha_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>From the grouped bar chart that visualizes the relationship between family size and survival rates, we can infer the following:</p>
<p>Survival rates tend to be higher for passengers traveling with a small family size. As the family size increases, the survival rates generally decrease. Passengers who were traveling alone (family size of 0) have a relatively lower survival rate compared to those with small family sizes (1-3). This suggests that having a few family members onboard might have provided some level of support or assistance during the Titanic disaster. Larger family sizes (4 and above) generally have lower survival rates, indicating that it might have been more challenging to navigate and escape the sinking ship with a larger group. The highest survival rate is observed for passengers with a family size of 3, while the lowest survival rate is observed for passengers with a family size of 7 or more. Overall, this visualization suggests that the family size of passengers aboard the Titanic had an impact on their chances of survival.</p>
</section>
<section id="part-7.-conclusion-and-discussion" class="level2">
<h2 class="anchored" data-anchor-id="part-7.-conclusion-and-discussion">Part 7. Conclusion and Discussion :</h2>
<p>In this analysis of the Titanic dataset, we explored various aspects related to the survival of passengers. Here is a summary of our findings:</p>
<p>Overall Survival Rate: The overall survival rate of passengers was approximately 38.38%. This means that out of all the passengers in the dataset, around 38.38% survived the Titanic disaster.</p>
<p>Gender and Survival: We observed that females had a significantly higher survival rate compared to males. The survival rate for females was approximately 74.20%, while for males it was around 18.89%. This suggests that gender played a significant role in determining the chances of survival, with females having a higher likelihood of surviving.</p>
<p>Age and Survival: Analyzing the age groups, we noticed that there was no clear pattern of age influencing survival rates. However, younger passengers (children and adolescents) seemed to have a slightly higher survival rate compared to other age groups.</p>
<p>Family Size and Survival: Examining the relationship between family size (based on SibSp and Parch variables) and survival rates, we found that passengers traveling with larger families had lower chances of survival. This indicates that having a larger family onboard might have posed challenges in terms of coordination and accessing life-saving resources</p>
<p>In summary, gender, family size, and fare were found to be factors that influenced survival rates on the Titanic. Females, passengers with smaller families, and those who paid higher fares had higher chances of surviving the disaster. These findings align with historical accounts and popular narratives about the Titanic tragedy.</p>
<p>Variables such as cabin number, had a substantial number of missing values, we tackled this issue by not doing any sort of analysis for it as it wont be very fruitful.</p>
</section>
<section id="part-8.-bibliography" class="level2">
<h2 class="anchored" data-anchor-id="part-8.-bibliography">Part 8. Bibliography :</h2>
<p>Dataset : https://www.kaggle.com/competitions/titanic/data</p>
<p>Programming Language : R</p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="DACSS/601_Spring_2023" data-repo-id="R_kgDOI4JcJA" data-category="Announcements" data-category-id="" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb61" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Final Project: Abhinav Reddy Yadatha"</span></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Abhinav Reddy Yadatha"</span></span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> "Final Project writeup"</span></span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "05/21/2023"</span></span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a><span class="co">    df-print: paged</span></span>
<span id="cb61-9"><a href="#cb61-9" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb61-10"><a href="#cb61-10" aria-hidden="true" tabindex="-1"></a><span class="co">    code-copy: true</span></span>
<span id="cb61-11"><a href="#cb61-11" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb61-12"><a href="#cb61-12" aria-hidden="true" tabindex="-1"></a><span class="co">    css: styles.css</span></span>
<span id="cb61-13"><a href="#cb61-13" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span></span>
<span id="cb61-14"><a href="#cb61-14" aria-hidden="true" tabindex="-1"></a><span class="co">  - final_Project</span></span>
<span id="cb61-15"><a href="#cb61-15" aria-hidden="true" tabindex="-1"></a><span class="an">editor_options:</span><span class="co"> </span></span>
<span id="cb61-16"><a href="#cb61-16" aria-hidden="true" tabindex="-1"></a><span class="co">  chunk_output_type: console</span></span>
<span id="cb61-17"><a href="#cb61-17" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb61-18"><a href="#cb61-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-19"><a href="#cb61-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-22"><a href="#cb61-22" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-23"><a href="#cb61-23" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: setup</span></span>
<span id="cb61-24"><a href="#cb61-24" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb61-25"><a href="#cb61-25" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb61-26"><a href="#cb61-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-27"><a href="#cb61-27" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb61-28"><a href="#cb61-28" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb61-29"><a href="#cb61-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-30"><a href="#cb61-30" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">TRUE</span>, <span class="at">warning=</span><span class="cn">FALSE</span>, <span class="at">message=</span><span class="cn">FALSE</span>)</span>
<span id="cb61-31"><a href="#cb61-31" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-32"><a href="#cb61-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-33"><a href="#cb61-33" aria-hidden="true" tabindex="-1"></a><span class="fu">## Part 1. Introduction </span></span>
<span id="cb61-34"><a href="#cb61-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-35"><a href="#cb61-35" aria-hidden="true" tabindex="-1"></a>Project Topic: The project aims to analyze the factors influencing the survival of passengers aboard the RMS Titanic during its tragic maiden voyage in 1912.</span>
<span id="cb61-36"><a href="#cb61-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-37"><a href="#cb61-37" aria-hidden="true" tabindex="-1"></a>General Research Question: What were the determinants of survival among the passengers on the Titanic?</span>
<span id="cb61-38"><a href="#cb61-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-39"><a href="#cb61-39" aria-hidden="true" tabindex="-1"></a>Dataset Description: The project utilizes the Titanic dataset, a well-known and frequently used dataset in data analysis and machine learning tasks. This dataset is derived from the passenger manifest of the RMS Titanic and has been curated by various organizations and individuals for educational and research purposes. Each row in the dataset represents a passenger who was aboard the Titanic during its ill-fated voyage.</span>
<span id="cb61-40"><a href="#cb61-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-41"><a href="#cb61-41" aria-hidden="true" tabindex="-1"></a>The dataset includes a range of variables such as the passenger's name, age, gender, passenger class, ticket fare, cabin number, port of embarkation, survival status, and more. These attributes were collected from passenger records, survivor interviews, and historical documents related to the disaster. The dataset encompasses both survivors and non-survivors, with the survival status column indicating whether a passenger survived (labeled as "1") or did not survive (labeled as "0") the sinking of the Titanic.</span>
<span id="cb61-42"><a href="#cb61-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-43"><a href="#cb61-43" aria-hidden="true" tabindex="-1"></a>Unit of Analysis: In the Titanic dataset, each case or unit of analysis refers to an individual passenger who was on board the Titanic. The dataset contains information for 891 passengers, with each row representing a unique passenger and the associated attributes.</span>
<span id="cb61-44"><a href="#cb61-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-45"><a href="#cb61-45" aria-hidden="true" tabindex="-1"></a>The project aims to explore the relationships between various factors such as gender, age, passenger class, family size, and cabin location with the survival outcome. By analyzing this dataset, we can gain insights into the demographics and characteristics of the passengers, investigate the impact of different variables on survival rates, and uncover patterns and correlations that shed light on the tragic events of the Titanic disaster.</span>
<span id="cb61-46"><a href="#cb61-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-47"><a href="#cb61-47" aria-hidden="true" tabindex="-1"></a><span class="fu">## Part 2. Background of the Topic/Literature Review</span></span>
<span id="cb61-48"><a href="#cb61-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-49"><a href="#cb61-49" aria-hidden="true" tabindex="-1"></a>The sinking of the Titanic in 1912 remains a captivating and tragic event in history. By analyzing the factors that influenced the survival of its passengers, we can gain valuable insights into the social dynamics, inequalities, and decision-making processes of that time. Exploring the Titanic dataset allows us to uncover patterns and correlations that have practical implications for emergency preparedness today. Understanding the determinants of survival on the Titanic not only deepens our knowledge of this historic event but also offers lessons for enhancing safety and well-being in future crises.</span>
<span id="cb61-50"><a href="#cb61-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-51"><a href="#cb61-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-52"><a href="#cb61-52" aria-hidden="true" tabindex="-1"></a><span class="fu">## Part 3. Dataset Introduction</span></span>
<span id="cb61-53"><a href="#cb61-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-54"><a href="#cb61-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-55"><a href="#cb61-55" aria-hidden="true" tabindex="-1"></a>The Titanic dataset is a widely recognized and extensively used dataset for data analysis and machine learning purposes. It originates from the passenger manifest of the RMS Titanic, a British passenger liner that tragically sank during its inaugural voyage in April 1912. Numerous organizations and individuals have carefully compiled and organized the dataset for educational and research applications based on the real-life incident. Each row in the dataset corresponds to an individual passenger who was on board the Titanic during its ill-fated journey. The dataset comprises various attributes pertaining to the passengers, including their names, ages, genders, passenger classes, ticket fares, cabin numbers, ports of embarkation, survival status, and more. These attributes were gathered from passenger records, survivor interviews, and historical documents related to the disaster. The dataset encompasses both survivors and non-survivors, with the survival status column denoting whether a passenger survived (labeled as "1") or did not survive (labeled as "0") the sinking of the Titanic. </span>
<span id="cb61-56"><a href="#cb61-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-57"><a href="#cb61-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-58"><a href="#cb61-58" aria-hidden="true" tabindex="-1"></a><span class="fu">## Part 4. Dataset Description</span></span>
<span id="cb61-59"><a href="#cb61-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-60"><a href="#cb61-60" aria-hidden="true" tabindex="-1"></a>(Story)</span>
<span id="cb61-61"><a href="#cb61-61" aria-hidden="true" tabindex="-1"></a>This dataset contains a total of 891 rows and 12 columns and the descriptive information about what each of the 12 fields are given below : </span>
<span id="cb61-62"><a href="#cb61-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-63"><a href="#cb61-63" aria-hidden="true" tabindex="-1"></a>PassengerId: A unique identifier assigned to each passenger.</span>
<span id="cb61-64"><a href="#cb61-64" aria-hidden="true" tabindex="-1"></a>Survived: Indicates whether the passenger survived the sinking or not (0 = No, 1 = Yes).</span>
<span id="cb61-65"><a href="#cb61-65" aria-hidden="true" tabindex="-1"></a>Pclass: Represents the passenger class (1 = 1st class, 2 = 2nd class, 3 = 3rd class).</span>
<span id="cb61-66"><a href="#cb61-66" aria-hidden="true" tabindex="-1"></a>Name: The name of the passenger.</span>
<span id="cb61-67"><a href="#cb61-67" aria-hidden="true" tabindex="-1"></a>Sex: The gender of the passenger (Male or Female).</span>
<span id="cb61-68"><a href="#cb61-68" aria-hidden="true" tabindex="-1"></a>Age: The age of the passenger in years (some values may be missing).</span>
<span id="cb61-69"><a href="#cb61-69" aria-hidden="true" tabindex="-1"></a>SibSp: The number of siblings/spouses aboard the Titanic.</span>
<span id="cb61-70"><a href="#cb61-70" aria-hidden="true" tabindex="-1"></a>Parch: The number of parents/children aboard the Titanic.</span>
<span id="cb61-71"><a href="#cb61-71" aria-hidden="true" tabindex="-1"></a>Ticket: The ticket number of the passenger.</span>
<span id="cb61-72"><a href="#cb61-72" aria-hidden="true" tabindex="-1"></a>Fare: The fare or ticket price paid by the passenger</span>
<span id="cb61-73"><a href="#cb61-73" aria-hidden="true" tabindex="-1"></a>Cabin: The cabin number assigned to the passenger (some values may be missing).</span>
<span id="cb61-74"><a href="#cb61-74" aria-hidden="true" tabindex="-1"></a>Embarked: The port of embarkation (C = Cherbourg, Q = Queenstown, S = Southampton).</span>
<span id="cb61-75"><a href="#cb61-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-76"><a href="#cb61-76" aria-hidden="true" tabindex="-1"></a>Coding Component:</span>
<span id="cb61-77"><a href="#cb61-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-78"><a href="#cb61-78" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>Read the titanic dataset;</span>
<span id="cb61-79"><a href="#cb61-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-82"><a href="#cb61-82" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-83"><a href="#cb61-83" aria-hidden="true" tabindex="-1"></a><span class="co">#read and get a overview of the data</span></span>
<span id="cb61-84"><a href="#cb61-84" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"AbhinavReddyYadatha_FinalProjectData/titanic.csv"</span>)</span>
<span id="cb61-85"><a href="#cb61-85" aria-hidden="true" tabindex="-1"></a><span class="fu">view</span>(data)</span>
<span id="cb61-86"><a href="#cb61-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-87"><a href="#cb61-87" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-88"><a href="#cb61-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-89"><a href="#cb61-89" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>Descriptive information of the titanic dataset :</span>
<span id="cb61-90"><a href="#cb61-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-91"><a href="#cb61-91" aria-hidden="true" tabindex="-1"></a>    <span class="in">```{r}</span></span>
<span id="cb61-92"><a href="#cb61-92" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Checking the dimensions of the data</span></span>
<span id="cb61-93"><a href="#cb61-93" aria-hidden="true" tabindex="-1"></a>    <span class="fu">dim</span>(data)</span>
<span id="cb61-94"><a href="#cb61-94" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb61-95"><a href="#cb61-95" aria-hidden="true" tabindex="-1"></a>    <span class="co"># checking the unique age group count</span></span>
<span id="cb61-96"><a href="#cb61-96" aria-hidden="true" tabindex="-1"></a>    <span class="fu">length</span>(<span class="fu">unique</span>(data<span class="sc">$</span>Age))</span>
<span id="cb61-97"><a href="#cb61-97" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb61-98"><a href="#cb61-98" aria-hidden="true" tabindex="-1"></a>    <span class="co">#printing out the first few examples</span></span>
<span id="cb61-99"><a href="#cb61-99" aria-hidden="true" tabindex="-1"></a>    <span class="fu">head</span>(data)</span>
<span id="cb61-100"><a href="#cb61-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-101"><a href="#cb61-101" aria-hidden="true" tabindex="-1"></a>    <span class="in">```</span></span>
<span id="cb61-102"><a href="#cb61-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-103"><a href="#cb61-103" aria-hidden="true" tabindex="-1"></a><span class="ss">3.  </span>Conduct summary statistics of the dataset : </span>
<span id="cb61-104"><a href="#cb61-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-107"><a href="#cb61-107" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-108"><a href="#cb61-108" aria-hidden="true" tabindex="-1"></a><span class="co"># Displaying the summary of the titanic data</span></span>
<span id="cb61-109"><a href="#cb61-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-110"><a href="#cb61-110" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data)</span>
<span id="cb61-111"><a href="#cb61-111" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-112"><a href="#cb61-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-113"><a href="#cb61-113" aria-hidden="true" tabindex="-1"></a>Exploring the variables of the dataset : </span>
<span id="cb61-114"><a href="#cb61-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-115"><a href="#cb61-115" aria-hidden="true" tabindex="-1"></a>Variable : Sex</span>
<span id="cb61-118"><a href="#cb61-118" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-119"><a href="#cb61-119" aria-hidden="true" tabindex="-1"></a><span class="co"># Count the number of males and females</span></span>
<span id="cb61-120"><a href="#cb61-120" aria-hidden="true" tabindex="-1"></a>gender_counts <span class="ot">&lt;-</span> <span class="fu">table</span>(data<span class="sc">$</span>Sex)</span>
<span id="cb61-121"><a href="#cb61-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-122"><a href="#cb61-122" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the counts</span></span>
<span id="cb61-123"><a href="#cb61-123" aria-hidden="true" tabindex="-1"></a>gender_counts</span>
<span id="cb61-124"><a href="#cb61-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-125"><a href="#cb61-125" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the total number of passengers</span></span>
<span id="cb61-126"><a href="#cb61-126" aria-hidden="true" tabindex="-1"></a>total_passengers <span class="ot">&lt;-</span> <span class="fu">nrow</span>(data)</span>
<span id="cb61-127"><a href="#cb61-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-128"><a href="#cb61-128" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the number of female passengers</span></span>
<span id="cb61-129"><a href="#cb61-129" aria-hidden="true" tabindex="-1"></a>male_passengers <span class="ot">&lt;-</span> <span class="fu">sum</span>(data<span class="sc">$</span>Sex <span class="sc">==</span> <span class="st">"male"</span>)</span>
<span id="cb61-130"><a href="#cb61-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-131"><a href="#cb61-131" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the percentage of females</span></span>
<span id="cb61-132"><a href="#cb61-132" aria-hidden="true" tabindex="-1"></a>percentage_males <span class="ot">&lt;-</span> (male_passengers <span class="sc">/</span> total_passengers) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb61-133"><a href="#cb61-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-134"><a href="#cb61-134" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the percentage of females</span></span>
<span id="cb61-135"><a href="#cb61-135" aria-hidden="true" tabindex="-1"></a>percentage_males</span>
<span id="cb61-136"><a href="#cb61-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-137"><a href="#cb61-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-138"><a href="#cb61-138" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-139"><a href="#cb61-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-140"><a href="#cb61-140" aria-hidden="true" tabindex="-1"></a>This variable refers to the gender of the passenger. It can be observed that there are 314 females and 577 males. Hence, the majority of the proportion of males is higher , in fact it's a staggering '64.7587%'.</span>
<span id="cb61-141"><a href="#cb61-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-142"><a href="#cb61-142" aria-hidden="true" tabindex="-1"></a>Variable : Survived</span>
<span id="cb61-143"><a href="#cb61-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-146"><a href="#cb61-146" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-147"><a href="#cb61-147" aria-hidden="true" tabindex="-1"></a><span class="co"># Count the number of passengers survived.</span></span>
<span id="cb61-148"><a href="#cb61-148" aria-hidden="true" tabindex="-1"></a>survived_counts <span class="ot">&lt;-</span> <span class="fu">table</span>(data<span class="sc">$</span>Survived)</span>
<span id="cb61-149"><a href="#cb61-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-150"><a href="#cb61-150" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the counts</span></span>
<span id="cb61-151"><a href="#cb61-151" aria-hidden="true" tabindex="-1"></a>survived_counts</span>
<span id="cb61-152"><a href="#cb61-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-153"><a href="#cb61-153" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the number of survived passengers</span></span>
<span id="cb61-154"><a href="#cb61-154" aria-hidden="true" tabindex="-1"></a>survived_passengers <span class="ot">&lt;-</span> <span class="fu">sum</span>(data<span class="sc">$</span>Survived <span class="sc">==</span> <span class="st">"1"</span>)</span>
<span id="cb61-155"><a href="#cb61-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-156"><a href="#cb61-156" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the percentage of survived passengers</span></span>
<span id="cb61-157"><a href="#cb61-157" aria-hidden="true" tabindex="-1"></a>percentage_survived <span class="ot">&lt;-</span> (survived_passengers <span class="sc">/</span> total_passengers) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb61-158"><a href="#cb61-158" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-159"><a href="#cb61-159" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the percentage of survived passengers</span></span>
<span id="cb61-160"><a href="#cb61-160" aria-hidden="true" tabindex="-1"></a>percentage_survived</span>
<span id="cb61-161"><a href="#cb61-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-162"><a href="#cb61-162" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-163"><a href="#cb61-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-164"><a href="#cb61-164" aria-hidden="true" tabindex="-1"></a>This variable indicates if a passenger has survived or not, it can be observed that only 342 passengers survived out of the total of 891 passengers. The survival rate of the titanic was just a mere 38.38384 %</span>
<span id="cb61-165"><a href="#cb61-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-166"><a href="#cb61-166" aria-hidden="true" tabindex="-1"></a>Variable Pclass:</span>
<span id="cb61-167"><a href="#cb61-167" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-170"><a href="#cb61-170" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-171"><a href="#cb61-171" aria-hidden="true" tabindex="-1"></a><span class="co"># Count the number of passengers in each passenger class</span></span>
<span id="cb61-172"><a href="#cb61-172" aria-hidden="true" tabindex="-1"></a>pclass_counts <span class="ot">&lt;-</span> <span class="fu">table</span>(data<span class="sc">$</span>Pclass)</span>
<span id="cb61-173"><a href="#cb61-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-174"><a href="#cb61-174" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the counts</span></span>
<span id="cb61-175"><a href="#cb61-175" aria-hidden="true" tabindex="-1"></a>pclass_counts</span>
<span id="cb61-176"><a href="#cb61-176" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-177"><a href="#cb61-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-178"><a href="#cb61-178" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-179"><a href="#cb61-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-180"><a href="#cb61-180" aria-hidden="true" tabindex="-1"></a>It can be observed that a majority of the passengers were travelling in class 3, then class 1 and the least in class 2.</span>
<span id="cb61-181"><a href="#cb61-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-182"><a href="#cb61-182" aria-hidden="true" tabindex="-1"></a>Variable : Fare</span>
<span id="cb61-183"><a href="#cb61-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-186"><a href="#cb61-186" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-187"><a href="#cb61-187" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the maximum fare</span></span>
<span id="cb61-188"><a href="#cb61-188" aria-hidden="true" tabindex="-1"></a>max_fare <span class="ot">&lt;-</span> <span class="fu">max</span>(data<span class="sc">$</span>Fare, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb61-189"><a href="#cb61-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-190"><a href="#cb61-190" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the minimum fare</span></span>
<span id="cb61-191"><a href="#cb61-191" aria-hidden="true" tabindex="-1"></a>min_fare <span class="ot">&lt;-</span> <span class="fu">min</span>(data<span class="sc">$</span>Fare, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb61-192"><a href="#cb61-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-193"><a href="#cb61-193" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the maximum and minimum fare</span></span>
<span id="cb61-194"><a href="#cb61-194" aria-hidden="true" tabindex="-1"></a>max_fare</span>
<span id="cb61-195"><a href="#cb61-195" aria-hidden="true" tabindex="-1"></a>min_fare</span>
<span id="cb61-196"><a href="#cb61-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-197"><a href="#cb61-197" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the mean fare</span></span>
<span id="cb61-198"><a href="#cb61-198" aria-hidden="true" tabindex="-1"></a>mean_fare <span class="ot">&lt;-</span> <span class="fu">mean</span>(data<span class="sc">$</span>Fare, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb61-199"><a href="#cb61-199" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-200"><a href="#cb61-200" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the mean fare</span></span>
<span id="cb61-201"><a href="#cb61-201" aria-hidden="true" tabindex="-1"></a>mean_fare</span>
<span id="cb61-202"><a href="#cb61-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-203"><a href="#cb61-203" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-204"><a href="#cb61-204" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-205"><a href="#cb61-205" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-206"><a href="#cb61-206" aria-hidden="true" tabindex="-1"></a>From the analysis above it can be observed that there were passengers who did not have to pay any fare whereas others had to pay a maximum of 512.3292. The mean fare paid by the passengers is 32.20421 USD.</span>
<span id="cb61-207"><a href="#cb61-207" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-208"><a href="#cb61-208" aria-hidden="true" tabindex="-1"></a>Variable Age : </span>
<span id="cb61-209"><a href="#cb61-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-212"><a href="#cb61-212" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-213"><a href="#cb61-213" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the maximum age</span></span>
<span id="cb61-214"><a href="#cb61-214" aria-hidden="true" tabindex="-1"></a>max_age <span class="ot">&lt;-</span> <span class="fu">max</span>(data<span class="sc">$</span>Age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb61-215"><a href="#cb61-215" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-216"><a href="#cb61-216" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the minimum age</span></span>
<span id="cb61-217"><a href="#cb61-217" aria-hidden="true" tabindex="-1"></a>min_age <span class="ot">&lt;-</span> <span class="fu">min</span>(data<span class="sc">$</span>Age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb61-218"><a href="#cb61-218" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-219"><a href="#cb61-219" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the maximum and minimum age</span></span>
<span id="cb61-220"><a href="#cb61-220" aria-hidden="true" tabindex="-1"></a>max_age</span>
<span id="cb61-221"><a href="#cb61-221" aria-hidden="true" tabindex="-1"></a>min_age</span>
<span id="cb61-222"><a href="#cb61-222" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-223"><a href="#cb61-223" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the mean age</span></span>
<span id="cb61-224"><a href="#cb61-224" aria-hidden="true" tabindex="-1"></a>mean_age <span class="ot">&lt;-</span> <span class="fu">mean</span>(data<span class="sc">$</span>Age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb61-225"><a href="#cb61-225" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-226"><a href="#cb61-226" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the mean age</span></span>
<span id="cb61-227"><a href="#cb61-227" aria-hidden="true" tabindex="-1"></a>mean_age</span>
<span id="cb61-228"><a href="#cb61-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-229"><a href="#cb61-229" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-230"><a href="#cb61-230" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-231"><a href="#cb61-231" aria-hidden="true" tabindex="-1"></a>There were people from all ages on the titanic. The maximum age being 80 and the minimum age being 0.42 while the mean age is 29.69912 ~ 30 years.</span>
<span id="cb61-232"><a href="#cb61-232" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-233"><a href="#cb61-233" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-234"><a href="#cb61-234" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-235"><a href="#cb61-235" aria-hidden="true" tabindex="-1"></a><span class="fu">## Part 5. Analysis Plan</span></span>
<span id="cb61-236"><a href="#cb61-236" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-237"><a href="#cb61-237" aria-hidden="true" tabindex="-1"></a>Specific questions : </span>
<span id="cb61-238"><a href="#cb61-238" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-239"><a href="#cb61-239" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>What was the overall survival rate of passengers aboard the Titanic?</span>
<span id="cb61-240"><a href="#cb61-240" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-241"><a href="#cb61-241" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>How does the survival rate vary based on passenger gender?</span>
<span id="cb61-242"><a href="#cb61-242" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-243"><a href="#cb61-243" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>Did the passenger class have an impact on the survival rate?</span>
<span id="cb61-244"><a href="#cb61-244" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-245"><a href="#cb61-245" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>What were the survival rates for passengers with family members aboard the Titanic versus those traveling alone</span>
<span id="cb61-246"><a href="#cb61-246" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-247"><a href="#cb61-247" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>How does the survival rate differ among different age groups or passenger classes?</span>
<span id="cb61-248"><a href="#cb61-248" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-249"><a href="#cb61-249" aria-hidden="true" tabindex="-1"></a><span class="ss">6. </span>What was the distribution of ages among the passengers, and did age play a role in survival?</span>
<span id="cb61-250"><a href="#cb61-250" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-251"><a href="#cb61-251" aria-hidden="true" tabindex="-1"></a><span class="ss">7. </span>How does the ticket fare correlate with the passenger class and survival?</span>
<span id="cb61-252"><a href="#cb61-252" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-253"><a href="#cb61-253" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-254"><a href="#cb61-254" aria-hidden="true" tabindex="-1"></a>Analysis Plan :</span>
<span id="cb61-255"><a href="#cb61-255" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-256"><a href="#cb61-256" aria-hidden="true" tabindex="-1"></a>To answer the research questions mentioned above, I plan to conduct a combination of data analysis and visualization techniques.</span>
<span id="cb61-257"><a href="#cb61-257" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-258"><a href="#cb61-258" aria-hidden="true" tabindex="-1"></a>Descriptive Statistics: I will calculate summary statistics such as means, medians, and proportions to provide an overview of the variables of interest, including survival rates based on different categories.</span>
<span id="cb61-259"><a href="#cb61-259" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-260"><a href="#cb61-260" aria-hidden="true" tabindex="-1"></a>Bar Charts: I will create bar charts to visualize the relationship between categorical variables (e.g., passenger class, gender, port of embarkation) and survival rates. This will allow for a quick comparison of survival probabilities across different categories.</span>
<span id="cb61-261"><a href="#cb61-261" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-262"><a href="#cb61-262" aria-hidden="true" tabindex="-1"></a>Histograms : I will use histograms to explore the distribution of continuous variables (e.g., age, fare) for both survivors and non-survivors. This will help identify any patterns or differences in the distributions between the two groups.</span>
<span id="cb61-263"><a href="#cb61-263" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-264"><a href="#cb61-264" aria-hidden="true" tabindex="-1"></a>Boxplots: Boxplots will be used to compare the median age and fare of survivors and non-survivors, providing insights into potential differences in these variables.</span>
<span id="cb61-265"><a href="#cb61-265" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-266"><a href="#cb61-266" aria-hidden="true" tabindex="-1"></a>Data Analyses I plan to do for this project are as follows :</span>
<span id="cb61-267"><a href="#cb61-267" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-268"><a href="#cb61-268" aria-hidden="true" tabindex="-1"></a>Survival Rate Analysis:</span>
<span id="cb61-269"><a href="#cb61-269" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-270"><a href="#cb61-270" aria-hidden="true" tabindex="-1"></a>Calculate the overall survival rate of passengers (percentage of survivors) to provide an initial understanding of survival outcomes.</span>
<span id="cb61-271"><a href="#cb61-271" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-272"><a href="#cb61-272" aria-hidden="true" tabindex="-1"></a>Gender-based Analysis:</span>
<span id="cb61-273"><a href="#cb61-273" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-274"><a href="#cb61-274" aria-hidden="true" tabindex="-1"></a>Compare the survival rates of male and female passengers using a bivariate visualization (such as a bar chart or stacked bar plot) to explore the potential impact of gender on survival.</span>
<span id="cb61-275"><a href="#cb61-275" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-276"><a href="#cb61-276" aria-hidden="true" tabindex="-1"></a>Passenger Class Analysis:</span>
<span id="cb61-277"><a href="#cb61-277" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-278"><a href="#cb61-278" aria-hidden="true" tabindex="-1"></a>Examine the survival rates across different passenger classes (first, second, and third) using visualizations (such as a stacked bar chart) to investigate the relationship between socio-economic status and survival.</span>
<span id="cb61-279"><a href="#cb61-279" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-280"><a href="#cb61-280" aria-hidden="true" tabindex="-1"></a>Age Distribution Analysis:</span>
<span id="cb61-281"><a href="#cb61-281" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-282"><a href="#cb61-282" aria-hidden="true" tabindex="-1"></a>Plot the age distribution of passengers using a histogram to visualize the age groups and identify any patterns or trends in survival rates within different age ranges.</span>
<span id="cb61-283"><a href="#cb61-283" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-284"><a href="#cb61-284" aria-hidden="true" tabindex="-1"></a>Family Size Analysis:</span>
<span id="cb61-285"><a href="#cb61-285" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-286"><a href="#cb61-286" aria-hidden="true" tabindex="-1"></a>Investigate the relationship between family size (based on the SibSp and Parch variables) and survival rates using a bivariate visualization (such as a scatter plot or grouped bar chart) to explore the impact of traveling with family members on survival.</span>
<span id="cb61-287"><a href="#cb61-287" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-288"><a href="#cb61-288" aria-hidden="true" tabindex="-1"></a>Bivariate Visualization:</span>
<span id="cb61-289"><a href="#cb61-289" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-290"><a href="#cb61-290" aria-hidden="true" tabindex="-1"></a>Bivariate visualizations, such as bar charts or stacked bar plots, are useful for comparing two variables, such as gender and survival or passenger class and survival. They allow us to visually examine the relationship between two categorical variables and observe any patterns or differences in survival rates based on these variables.</span>
<span id="cb61-291"><a href="#cb61-291" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-292"><a href="#cb61-292" aria-hidden="true" tabindex="-1"></a>Scatter Plot:</span>
<span id="cb61-293"><a href="#cb61-293" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-294"><a href="#cb61-294" aria-hidden="true" tabindex="-1"></a>Scatter plots are valuable for analyzing the relationship between two continuous variables, such as family size and survival rates. They enable us to observe the dispersion of data points and determine if there is any correlation or trend between the variables.</span>
<span id="cb61-295"><a href="#cb61-295" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-296"><a href="#cb61-296" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-297"><a href="#cb61-297" aria-hidden="true" tabindex="-1"></a>Box Plot :</span>
<span id="cb61-298"><a href="#cb61-298" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-299"><a href="#cb61-299" aria-hidden="true" tabindex="-1"></a>Box plots are excellent for comparing the distribution of a continuous variable, such as fare, between different groups (e.g., survivors vs. non-survivors). They provide a visual representation of the median, quartiles, and outliers in the data, allowing us to detect any variations or differences in fare distributions based on survival outcomes.</span>
<span id="cb61-300"><a href="#cb61-300" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb61-301"><a href="#cb61-301" aria-hidden="true" tabindex="-1"></a>Calculating Age Groups:</span>
<span id="cb61-302"><a href="#cb61-302" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-303"><a href="#cb61-303" aria-hidden="true" tabindex="-1"></a>Grouping passengers into age categories: You can create a new variable called "Age Group" by categorizing the passengers' ages into different groups, such as "Child," "Adult," and "Elderly." This can be done by specifying age ranges and using conditional statements or the cut() function in R.</span>
<span id="cb61-304"><a href="#cb61-304" aria-hidden="true" tabindex="-1"></a>Converting Categorical Variables:</span>
<span id="cb61-305"><a href="#cb61-305" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-306"><a href="#cb61-306" aria-hidden="true" tabindex="-1"></a>Mapping categorical variables to numerical values: If any categorical variables, such as "Sex" or "Embarked," are represented as text, you can create new variables that map these categories to numerical values. For example, you can create a new variable called "Sex_Code" where "male" is encoded as 0 and "female" as 1.</span>
<span id="cb61-307"><a href="#cb61-307" aria-hidden="true" tabindex="-1"></a>Calculating Family Size:</span>
<span id="cb61-308"><a href="#cb61-308" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-309"><a href="#cb61-309" aria-hidden="true" tabindex="-1"></a>Creating a variable for family size: You can create a new variable called "Family Size" by summing the "SibSp" (number of siblings/spouses aboard) and "Parch" (number of parents/children aboard) variables. This new variable represents the total number of family members a passenger had onboard.</span>
<span id="cb61-310"><a href="#cb61-310" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-311"><a href="#cb61-311" aria-hidden="true" tabindex="-1"></a>If any column has too much empty data, I plan to drop it completely as it would not contain a lot of information.</span>
<span id="cb61-312"><a href="#cb61-312" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-313"><a href="#cb61-313" aria-hidden="true" tabindex="-1"></a><span class="fu">## Part 6. Survival Rate Analysis and Visualization</span></span>
<span id="cb61-316"><a href="#cb61-316" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-317"><a href="#cb61-317" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate summary statistics for continuous variables</span></span>
<span id="cb61-318"><a href="#cb61-318" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data<span class="sc">$</span>Age)  <span class="co"># Summary statistics for age</span></span>
<span id="cb61-319"><a href="#cb61-319" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data<span class="sc">$</span>Fare)  <span class="co"># Summary statistics for fare</span></span>
<span id="cb61-320"><a href="#cb61-320" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-321"><a href="#cb61-321" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate summary statistics for categorical variables</span></span>
<span id="cb61-322"><a href="#cb61-322" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>Sex)  <span class="co"># Frequency count for gender</span></span>
<span id="cb61-323"><a href="#cb61-323" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>Pclass)  <span class="co"># Frequency count for passenger class</span></span>
<span id="cb61-324"><a href="#cb61-324" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>Survived)  <span class="co"># Frequency count for survival status</span></span>
<span id="cb61-325"><a href="#cb61-325" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-326"><a href="#cb61-326" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate survival rates based on different categories</span></span>
<span id="cb61-327"><a href="#cb61-327" aria-hidden="true" tabindex="-1"></a>survival_rates_gender <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(<span class="fu">table</span>(data<span class="sc">$</span>Survived, data<span class="sc">$</span>Sex), <span class="at">margin =</span> <span class="dv">2</span>) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb61-328"><a href="#cb61-328" aria-hidden="true" tabindex="-1"></a>survival_rates_class <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(<span class="fu">table</span>(data<span class="sc">$</span>Survived, data<span class="sc">$</span>Pclass), <span class="at">margin =</span> <span class="dv">2</span>) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb61-329"><a href="#cb61-329" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-330"><a href="#cb61-330" aria-hidden="true" tabindex="-1"></a><span class="co"># Display survival rates w.r.t gender and class</span></span>
<span id="cb61-331"><a href="#cb61-331" aria-hidden="true" tabindex="-1"></a>survival_rates_gender</span>
<span id="cb61-332"><a href="#cb61-332" aria-hidden="true" tabindex="-1"></a>survival_rates_class</span>
<span id="cb61-333"><a href="#cb61-333" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-334"><a href="#cb61-334" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-335"><a href="#cb61-335" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-336"><a href="#cb61-336" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-337"><a href="#cb61-337" aria-hidden="true" tabindex="-1"></a>From the above statistics, it can be observed that approximately 75% of females have survived the tragedy whereas only nearly 19% of men have survived. A trend could be identified about the gender and the survival rate. In addition to this, based on the class it is observed that people who were in class 1 had a significantly higher survival rate compare to that of class 2 and class 3.</span>
<span id="cb61-338"><a href="#cb61-338" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-339"><a href="#cb61-339" aria-hidden="true" tabindex="-1"></a>Analysis : </span>
<span id="cb61-340"><a href="#cb61-340" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-341"><a href="#cb61-341" aria-hidden="true" tabindex="-1"></a>Research Question analysed : How does the survival rate vary based on passenger gender?</span>
<span id="cb61-342"><a href="#cb61-342" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-345"><a href="#cb61-345" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-346"><a href="#cb61-346" aria-hidden="true" tabindex="-1"></a><span class="co"># count of survivors by gender</span></span>
<span id="cb61-347"><a href="#cb61-347" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x=</span>Sex, <span class="at">y=</span>Survived, <span class="at">fill=</span>Sex)) <span class="sc">+</span></span>
<span id="cb61-348"><a href="#cb61-348" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat=</span><span class="st">"identity"</span>)<span class="sc">+</span></span>
<span id="cb61-349"><a href="#cb61-349" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_grey</span>()</span>
<span id="cb61-350"><a href="#cb61-350" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Survival counts of Male and Female Passengers"</span>) <span class="sc">+</span></span>
<span id="cb61-351"><a href="#cb61-351" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggtitle</span>(<span class="st">"Counts of female vs male survivors"</span>) <span class="sc">+</span></span>
<span id="cb61-352"><a href="#cb61-352" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb61-353"><a href="#cb61-353" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-354"><a href="#cb61-354" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-355"><a href="#cb61-355" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-356"><a href="#cb61-356" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-357"><a href="#cb61-357" aria-hidden="true" tabindex="-1"></a>Research Analysed: Median age and fare from survivors and non-survivors.</span>
<span id="cb61-358"><a href="#cb61-358" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-361"><a href="#cb61-361" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-362"><a href="#cb61-362" aria-hidden="true" tabindex="-1"></a><span class="co"># Create boxplots comparing the median age and fare between survivors and non-survivors</span></span>
<span id="cb61-363"><a href="#cb61-363" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(Survived), <span class="at">y =</span> Age)) <span class="sc">+</span></span>
<span id="cb61-364"><a href="#cb61-364" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">"lightblue"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb61-365"><a href="#cb61-365" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Survived"</span>, <span class="at">y =</span> <span class="st">"Age"</span>, <span class="at">title =</span> <span class="st">"Boxplot of Age: Survivors vs. Non-Survivors"</span>) <span class="sc">+</span></span>
<span id="cb61-366"><a href="#cb61-366" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb61-367"><a href="#cb61-367" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-368"><a href="#cb61-368" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(Survived), <span class="at">y =</span> Fare)) <span class="sc">+</span></span>
<span id="cb61-369"><a href="#cb61-369" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">"lightblue"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb61-370"><a href="#cb61-370" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Survived"</span>, <span class="at">y =</span> <span class="st">"Fare"</span>, <span class="at">title =</span> <span class="st">"Boxplot of Fare: Survivors vs. Non-Survivors"</span>) <span class="sc">+</span></span>
<span id="cb61-371"><a href="#cb61-371" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb61-372"><a href="#cb61-372" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-373"><a href="#cb61-373" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-374"><a href="#cb61-374" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-375"><a href="#cb61-375" aria-hidden="true" tabindex="-1"></a>From the boxplots comparing the median age and fare between survivors and non-survivors, we can infer the following:</span>
<span id="cb61-376"><a href="#cb61-376" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-377"><a href="#cb61-377" aria-hidden="true" tabindex="-1"></a>Age: The median age of survivors appears to be slightly lower than that of non-survivors. This suggests that there may have been a higher proportion of younger passengers who survived the Titanic disaster. However, it's important to note that the difference in median age might not be substantial.</span>
<span id="cb61-378"><a href="#cb61-378" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-379"><a href="#cb61-379" aria-hidden="true" tabindex="-1"></a>Fare: The median fare of survivors seems to be slightly higher compared to non-survivors. This indicates that passengers who paid higher fares might have had a better chance of survival. It's possible that higher-paying passengers were assigned to more favorable locations on the ship or had access to better life-saving resources.</span>
<span id="cb61-380"><a href="#cb61-380" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-381"><a href="#cb61-381" aria-hidden="true" tabindex="-1"></a>These inferences are based on the central tendency represented by the median values in the boxplots. However, it's essential to conduct further statistical analysis to validate these observations.</span>
<span id="cb61-382"><a href="#cb61-382" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-383"><a href="#cb61-383" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-386"><a href="#cb61-386" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-387"><a href="#cb61-387" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb61-388"><a href="#cb61-388" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-389"><a href="#cb61-389" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the survival rates by gender</span></span>
<span id="cb61-390"><a href="#cb61-390" aria-hidden="true" tabindex="-1"></a>survival_rates_gender <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(<span class="fu">table</span>(data<span class="sc">$</span>Survived, data<span class="sc">$</span>Sex), <span class="at">margin =</span> <span class="dv">2</span>) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb61-391"><a href="#cb61-391" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-392"><a href="#cb61-392" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(survival_rates_gender)</span>
<span id="cb61-393"><a href="#cb61-393" aria-hidden="true" tabindex="-1"></a>subset_df <span class="ot">&lt;-</span> <span class="fu">subset</span>(df, Var1 <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb61-394"><a href="#cb61-394" aria-hidden="true" tabindex="-1"></a>subset_df</span>
<span id="cb61-395"><a href="#cb61-395" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-396"><a href="#cb61-396" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-397"><a href="#cb61-397" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a bar chart to compare survival rates by gender</span></span>
<span id="cb61-398"><a href="#cb61-398" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> subset_df, <span class="fu">aes</span>(<span class="at">x=</span>Var2, <span class="at">y=</span>Freq, <span class="at">fill=</span>Var2)) <span class="sc">+</span></span>
<span id="cb61-399"><a href="#cb61-399" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="st">"stack"</span>) <span class="sc">+</span></span>
<span id="cb61-400"><a href="#cb61-400" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Gender"</span>, <span class="at">y =</span> <span class="st">"Survival rate %"</span>, <span class="at">fill =</span> <span class="st">"Survived"</span>) <span class="sc">+</span></span>
<span id="cb61-401"><a href="#cb61-401" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"blue"</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"% of females survived"</span>, <span class="st">"% of males survived"</span>)) <span class="sc">+</span></span>
<span id="cb61-402"><a href="#cb61-402" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Survival Rates of Male VS Female Passengers"</span>) <span class="sc">+</span></span>
<span id="cb61-403"><a href="#cb61-403" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb61-404"><a href="#cb61-404" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-405"><a href="#cb61-405" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-406"><a href="#cb61-406" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-407"><a href="#cb61-407" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-408"><a href="#cb61-408" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-409"><a href="#cb61-409" aria-hidden="true" tabindex="-1"></a>From the above analyses, it is observed that despite the fact that there are males than compard to females, gender could be treated as an indicator survival chance. This is due to the fact that females on titanic had a survival rate of 74 % whereas the males on the same boat only had 18%. </span>
<span id="cb61-410"><a href="#cb61-410" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-411"><a href="#cb61-411" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-412"><a href="#cb61-412" aria-hidden="true" tabindex="-1"></a>Research question answered : Passenger Class Analysis</span>
<span id="cb61-413"><a href="#cb61-413" aria-hidden="true" tabindex="-1"></a>Examine the survival rates across different passenger classes (first, second, and third) using visualizations (such as a Stacked bar chart) to investigate the relationship between socio-economic status and survival.</span>
<span id="cb61-414"><a href="#cb61-414" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-417"><a href="#cb61-417" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-418"><a href="#cb61-418" aria-hidden="true" tabindex="-1"></a><span class="co"># count of survivors by passenger class via stacked bar graph</span></span>
<span id="cb61-419"><a href="#cb61-419" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-420"><a href="#cb61-420" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x=</span>Pclass, <span class="at">y=</span>Survived, <span class="at">fill=</span>Sex)) <span class="sc">+</span></span>
<span id="cb61-421"><a href="#cb61-421" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat=</span><span class="st">"identity"</span>)<span class="sc">+</span></span>
<span id="cb61-422"><a href="#cb61-422" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_grey</span>()<span class="sc">+</span></span>
<span id="cb61-423"><a href="#cb61-423" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Survival counts of Male and Female Passengers"</span>) <span class="sc">+</span></span>
<span id="cb61-424"><a href="#cb61-424" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggtitle</span>(<span class="st">"Counts of female vs male survivors"</span>) <span class="sc">+</span></span>
<span id="cb61-425"><a href="#cb61-425" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb61-426"><a href="#cb61-426" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-427"><a href="#cb61-427" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-428"><a href="#cb61-428" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-429"><a href="#cb61-429" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-432"><a href="#cb61-432" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-433"><a href="#cb61-433" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb61-434"><a href="#cb61-434" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-435"><a href="#cb61-435" aria-hidden="true" tabindex="-1"></a><span class="co"># Bar graph to determine the relationship between survival and socio-economic status</span></span>
<span id="cb61-436"><a href="#cb61-436" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-437"><a href="#cb61-437" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the survival rates by passenger class</span></span>
<span id="cb61-438"><a href="#cb61-438" aria-hidden="true" tabindex="-1"></a>survival_rates_pclass <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(<span class="fu">table</span>(data<span class="sc">$</span>Survived, data<span class="sc">$</span>Pclass), <span class="at">margin =</span> <span class="dv">2</span>) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb61-439"><a href="#cb61-439" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-440"><a href="#cb61-440" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(survival_rates_pclass)</span>
<span id="cb61-441"><a href="#cb61-441" aria-hidden="true" tabindex="-1"></a>subset_df <span class="ot">&lt;-</span> <span class="fu">subset</span>(df, Var1 <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb61-442"><a href="#cb61-442" aria-hidden="true" tabindex="-1"></a>subset_df</span>
<span id="cb61-443"><a href="#cb61-443" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-444"><a href="#cb61-444" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-445"><a href="#cb61-445" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a bar chart to compare survival rates by gender</span></span>
<span id="cb61-446"><a href="#cb61-446" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> subset_df, <span class="fu">aes</span>(<span class="at">x=</span>Var2, <span class="at">y=</span>Freq, <span class="at">fill=</span>Var2)) <span class="sc">+</span></span>
<span id="cb61-447"><a href="#cb61-447" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="st">"stack"</span>) <span class="sc">+</span></span>
<span id="cb61-448"><a href="#cb61-448" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_grey</span>() <span class="sc">+</span></span>
<span id="cb61-449"><a href="#cb61-449" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"blue"</span>, <span class="st">"green"</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Class 1 surivor %"</span>, <span class="st">"Class 2 surivor %"</span>, <span class="st">"Class 3 surivor %"</span>))<span class="sc">+</span></span>
<span id="cb61-450"><a href="#cb61-450" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Passenger Class"</span>, <span class="at">y =</span> <span class="st">"Survival rate %"</span>, <span class="at">fill =</span> <span class="st">"Survived"</span>) <span class="sc">+</span></span>
<span id="cb61-451"><a href="#cb61-451" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Survival Rates of Male VS Female Passengers"</span>) <span class="sc">+</span></span>
<span id="cb61-452"><a href="#cb61-452" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb61-453"><a href="#cb61-453" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-454"><a href="#cb61-454" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-455"><a href="#cb61-455" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-456"><a href="#cb61-456" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-457"><a href="#cb61-457" aria-hidden="true" tabindex="-1"></a>Two observations are made : 1. The number of passengers in class1 are significantly higher than the passengers in class 2 and class 3. 2. Despite having such high numbers, it is observed that the class 1 passengers have the highest rate of survival indicating that the passenger class type played a very important role in determining the survival.</span>
<span id="cb61-458"><a href="#cb61-458" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-459"><a href="#cb61-459" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-460"><a href="#cb61-460" aria-hidden="true" tabindex="-1"></a>Research question analysed : Age Distribution Analysis:</span>
<span id="cb61-461"><a href="#cb61-461" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-462"><a href="#cb61-462" aria-hidden="true" tabindex="-1"></a>Plot the age distribution of passengers using a histogram to visualize the age groups and identify any patterns or trends in survival rates within different age ranges.</span>
<span id="cb61-463"><a href="#cb61-463" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-466"><a href="#cb61-466" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-467"><a href="#cb61-467" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a histogram of the age distribution</span></span>
<span id="cb61-468"><a href="#cb61-468" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb61-469"><a href="#cb61-469" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> Age)) <span class="sc">+</span></span>
<span id="cb61-470"><a href="#cb61-470" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">5</span>, <span class="at">fill =</span> <span class="st">"lightblue"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb61-471"><a href="#cb61-471" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Age"</span>, <span class="at">y =</span> <span class="st">"Frequency"</span>) <span class="sc">+</span></span>
<span id="cb61-472"><a href="#cb61-472" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Age Distribution of Passengers"</span>) <span class="sc">+</span></span>
<span id="cb61-473"><a href="#cb61-473" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb61-474"><a href="#cb61-474" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-475"><a href="#cb61-475" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-476"><a href="#cb61-476" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-477"><a href="#cb61-477" aria-hidden="true" tabindex="-1"></a>The age groups are all discrete, so we would not be in a position to analyse. So we will mutate the age column into age groups and analyse accordingly.</span>
<span id="cb61-478"><a href="#cb61-478" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-481"><a href="#cb61-481" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-482"><a href="#cb61-482" aria-hidden="true" tabindex="-1"></a><span class="co"># Mutate the 'Age' column into age groups</span></span>
<span id="cb61-483"><a href="#cb61-483" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>AgeGroup <span class="ot">&lt;-</span> <span class="fu">cut</span>(data<span class="sc">$</span>Age, <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">18</span>, <span class="dv">30</span>, <span class="dv">50</span>, <span class="cn">Inf</span>),</span>
<span id="cb61-484"><a href="#cb61-484" aria-hidden="true" tabindex="-1"></a>                     <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Child"</span>, <span class="st">"Young Adult"</span>, <span class="st">"Adult"</span>, <span class="st">"Senior"</span>))</span>
<span id="cb61-485"><a href="#cb61-485" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-486"><a href="#cb61-486" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data)</span>
<span id="cb61-487"><a href="#cb61-487" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-488"><a href="#cb61-488" aria-hidden="true" tabindex="-1"></a><span class="co"># For example, calculate the survival rate by age group</span></span>
<span id="cb61-489"><a href="#cb61-489" aria-hidden="true" tabindex="-1"></a>survival_rates_agegroup <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(<span class="fu">table</span>(data<span class="sc">$</span>Survived, data<span class="sc">$</span>AgeGroup), <span class="at">margin =</span> <span class="dv">2</span>) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb61-490"><a href="#cb61-490" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-491"><a href="#cb61-491" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the resulting table</span></span>
<span id="cb61-492"><a href="#cb61-492" aria-hidden="true" tabindex="-1"></a>survival_rates_agegroup</span>
<span id="cb61-493"><a href="#cb61-493" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-494"><a href="#cb61-494" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-495"><a href="#cb61-495" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-496"><a href="#cb61-496" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-497"><a href="#cb61-497" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-498"><a href="#cb61-498" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-501"><a href="#cb61-501" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-502"><a href="#cb61-502" aria-hidden="true" tabindex="-1"></a><span class="co"># For example, calculate the survival rate by age group</span></span>
<span id="cb61-503"><a href="#cb61-503" aria-hidden="true" tabindex="-1"></a>survival_rates_agegroup <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(<span class="fu">table</span>(data<span class="sc">$</span>Survived, data<span class="sc">$</span>AgeGroup), <span class="at">margin =</span> <span class="dv">2</span>) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb61-504"><a href="#cb61-504" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-505"><a href="#cb61-505" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-506"><a href="#cb61-506" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(survival_rates_agegroup)</span>
<span id="cb61-507"><a href="#cb61-507" aria-hidden="true" tabindex="-1"></a>subset_df <span class="ot">&lt;-</span> <span class="fu">subset</span>(df, Var1 <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb61-508"><a href="#cb61-508" aria-hidden="true" tabindex="-1"></a>subset_df</span>
<span id="cb61-509"><a href="#cb61-509" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-510"><a href="#cb61-510" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-511"><a href="#cb61-511" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a bar chart to compare survival rates by gender</span></span>
<span id="cb61-512"><a href="#cb61-512" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> subset_df, <span class="fu">aes</span>(<span class="at">x=</span>Var2, <span class="at">y=</span>Freq, <span class="at">fill=</span>Var2)) <span class="sc">+</span></span>
<span id="cb61-513"><a href="#cb61-513" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="st">"stack"</span>) <span class="sc">+</span></span>
<span id="cb61-514"><a href="#cb61-514" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_grey</span>() <span class="sc">+</span></span>
<span id="cb61-515"><a href="#cb61-515" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"blue"</span>, <span class="st">"green"</span>, <span class="st">"orange"</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"child"</span>, <span class="st">"Young Adult"</span>, <span class="st">"Adult"</span>, <span class="st">"Senior"</span>))<span class="sc">+</span></span>
<span id="cb61-516"><a href="#cb61-516" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Passenger Class"</span>, <span class="at">y =</span> <span class="st">"Survival rate %"</span>, <span class="at">fill =</span> <span class="st">"Survived"</span>) <span class="sc">+</span></span>
<span id="cb61-517"><a href="#cb61-517" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Survival Rates of different age groups"</span>) <span class="sc">+</span></span>
<span id="cb61-518"><a href="#cb61-518" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb61-519"><a href="#cb61-519" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-520"><a href="#cb61-520" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-521"><a href="#cb61-521" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-522"><a href="#cb61-522" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-523"><a href="#cb61-523" aria-hidden="true" tabindex="-1"></a>While, it can be observed that the children have the highest survival rate and seniors have the lowest rate, it is inconclusive to say whether the age factor is a factor affecting the chance of survival as all of them are pretty close. Due to the lack of this significant gap, I am ruling out Age as an definite factor affecting the survival.</span>
<span id="cb61-524"><a href="#cb61-524" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-525"><a href="#cb61-525" aria-hidden="true" tabindex="-1"></a>Research Question Analysed : Family Size Analysis:</span>
<span id="cb61-526"><a href="#cb61-526" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-527"><a href="#cb61-527" aria-hidden="true" tabindex="-1"></a>Investigate the relationship between family size (based on the SibSp and Parch variables) and survival rates using a bivariate visualization (such as a scatter plot or grouped bar chart) to explore the impact of traveling with family members on survival.</span>
<span id="cb61-528"><a href="#cb61-528" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-529"><a href="#cb61-529" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-532"><a href="#cb61-532" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-533"><a href="#cb61-533" aria-hidden="true" tabindex="-1"></a><span class="co"># Grouped bar chart </span></span>
<span id="cb61-534"><a href="#cb61-534" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the total family size by adding 'SibSp' and 'Parch'</span></span>
<span id="cb61-535"><a href="#cb61-535" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>FamilySize <span class="ot">&lt;-</span> data<span class="sc">$</span>SibSp <span class="sc">+</span> data<span class="sc">$</span>Parch</span>
<span id="cb61-536"><a href="#cb61-536" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-537"><a href="#cb61-537" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the survival rate by family size</span></span>
<span id="cb61-538"><a href="#cb61-538" aria-hidden="true" tabindex="-1"></a>survival_rates <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(Survived <span class="sc">~</span> FamilySize, <span class="at">data =</span> data, <span class="at">FUN =</span> <span class="cf">function</span>(x) <span class="fu">sum</span>(x) <span class="sc">/</span> <span class="fu">length</span>(x) <span class="sc">*</span> <span class="dv">100</span>)</span>
<span id="cb61-539"><a href="#cb61-539" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-540"><a href="#cb61-540" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a grouped bar chart of survival rates by family size</span></span>
<span id="cb61-541"><a href="#cb61-541" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(survival_rates, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">as.factor</span>(FamilySize), <span class="at">y =</span> Survived)) <span class="sc">+</span></span>
<span id="cb61-542"><a href="#cb61-542" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">fill =</span> <span class="st">"lightblue"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb61-543"><a href="#cb61-543" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Family Size"</span>, <span class="at">y =</span> <span class="st">"Survival Rate (%)"</span>) <span class="sc">+</span></span>
<span id="cb61-544"><a href="#cb61-544" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Relationship between Family Size and Survival Rates"</span>) <span class="sc">+</span></span>
<span id="cb61-545"><a href="#cb61-545" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb61-546"><a href="#cb61-546" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-547"><a href="#cb61-547" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-548"><a href="#cb61-548" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-549"><a href="#cb61-549" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-550"><a href="#cb61-550" aria-hidden="true" tabindex="-1"></a>From the grouped bar chart that visualizes the relationship between family size and survival rates, we can infer the following:</span>
<span id="cb61-551"><a href="#cb61-551" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-552"><a href="#cb61-552" aria-hidden="true" tabindex="-1"></a>Survival rates tend to be higher for passengers traveling with a small family size. As the family size increases, the survival rates generally decrease.</span>
<span id="cb61-553"><a href="#cb61-553" aria-hidden="true" tabindex="-1"></a>Passengers who were traveling alone (family size of 0) have a relatively lower survival rate compared to those with small family sizes (1-3). This suggests that having a few family members onboard might have provided some level of support or assistance during the Titanic disaster.</span>
<span id="cb61-554"><a href="#cb61-554" aria-hidden="true" tabindex="-1"></a>Larger family sizes (4 and above) generally have lower survival rates, indicating that it might have been more challenging to navigate and escape the sinking ship with a larger group.</span>
<span id="cb61-555"><a href="#cb61-555" aria-hidden="true" tabindex="-1"></a>The highest survival rate is observed for passengers with a family size of 3, while the lowest survival rate is observed for passengers with a family size of 7 or more.</span>
<span id="cb61-556"><a href="#cb61-556" aria-hidden="true" tabindex="-1"></a>Overall, this visualization suggests that the family size of passengers aboard the Titanic had an impact on their chances of survival.</span>
<span id="cb61-557"><a href="#cb61-557" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-558"><a href="#cb61-558" aria-hidden="true" tabindex="-1"></a><span class="fu">## Part 7. Conclusion and Discussion :</span></span>
<span id="cb61-559"><a href="#cb61-559" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-560"><a href="#cb61-560" aria-hidden="true" tabindex="-1"></a>In this analysis of the Titanic dataset, we explored various aspects related to the survival of passengers. Here is a summary of our findings:</span>
<span id="cb61-561"><a href="#cb61-561" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-562"><a href="#cb61-562" aria-hidden="true" tabindex="-1"></a>Overall Survival Rate: The overall survival rate of passengers was approximately 38.38%. This means that out of all the passengers in the dataset, around 38.38% survived the Titanic disaster.</span>
<span id="cb61-563"><a href="#cb61-563" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-564"><a href="#cb61-564" aria-hidden="true" tabindex="-1"></a>Gender and Survival: We observed that females had a significantly higher survival rate compared to males. The survival rate for females was approximately 74.20%, while for males it was around 18.89%. This suggests that gender played a significant role in determining the chances of survival, with females having a higher likelihood of surviving.</span>
<span id="cb61-565"><a href="#cb61-565" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-566"><a href="#cb61-566" aria-hidden="true" tabindex="-1"></a>Age and Survival: Analyzing the age groups, we noticed that there was no clear pattern of age influencing survival rates. However, younger passengers (children and adolescents) seemed to have a slightly higher survival rate compared to other age groups.</span>
<span id="cb61-567"><a href="#cb61-567" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-568"><a href="#cb61-568" aria-hidden="true" tabindex="-1"></a>Family Size and Survival: Examining the relationship between family size (based on SibSp and Parch variables) and survival rates, we found that passengers traveling with larger families had lower chances of survival. This indicates that having a larger family onboard might have posed challenges in terms of coordination and accessing life-saving resources</span>
<span id="cb61-569"><a href="#cb61-569" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-570"><a href="#cb61-570" aria-hidden="true" tabindex="-1"></a>In summary, gender, family size, and fare were found to be factors that influenced survival rates on the Titanic. Females, passengers with smaller families, and those who paid higher fares had higher chances of surviving the disaster. These findings align with historical accounts and popular narratives about the Titanic tragedy.</span>
<span id="cb61-571"><a href="#cb61-571" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-572"><a href="#cb61-572" aria-hidden="true" tabindex="-1"></a>Variables such as cabin number, had a substantial number of missing values, we tackled this issue by not doing any sort of analysis for it as it wont be very fruitful.</span>
<span id="cb61-573"><a href="#cb61-573" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-574"><a href="#cb61-574" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-575"><a href="#cb61-575" aria-hidden="true" tabindex="-1"></a><span class="fu">## Part 8. Bibliography :</span></span>
<span id="cb61-576"><a href="#cb61-576" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-577"><a href="#cb61-577" aria-hidden="true" tabindex="-1"></a>Dataset : https://www.kaggle.com/competitions/titanic/data</span>
<span id="cb61-578"><a href="#cb61-578" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-579"><a href="#cb61-579" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-580"><a href="#cb61-580" aria-hidden="true" tabindex="-1"></a>Programming Language : R</span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>