<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.427">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Harsha Kanaka Eswar Gudipudi">
<meta name="dcterms.date" content="2023-05-22">
<meta name="description" content="Bike Sales">

<title>DACSS601: Final Paper</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../images/DACSS_Round_Network.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

<link href="../site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">
<script src="../site_libs/pagedtable-1.1/js/pagedtable.js"></script>


<link rel="stylesheet" href="styles.css">
<meta name="twitter:title" content="DACSS601: Final Paper">
<meta name="twitter:description" content="Bike Sales">
<meta name="twitter:image" content="https://dacss.github.io/601_Spring_2023/posts/HarshaKanakaEswarGudipudi_FinalProject_files/figure-html/unnamed-chunk-4-1.png">
<meta name="twitter:creator" content="@UMassDACSS">
<meta name="twitter:site" content="@UMassDACSS">
<meta name="twitter:image-height" content="960">
<meta name="twitter:image-width" content="1344">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../images/UMass White Wordmark Horiz.png" alt="" class="navbar-logo">
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://github.com/DACSS" rel="" target="">
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html" rel="" target="">
 <span class="menu-text">Contributors</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://umass.edu/sbs/dacss" rel="" target="">
 <span class="menu-text">DACSS</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/DACSS" rel="" target=""><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a>
  <ul class="collapse">
  <li><a href="#research-questions" id="toc-research-questions" class="nav-link" data-scroll-target="#research-questions">Research Questions</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">Data</a></li>
  <li><a href="#breif-description-about-the-data" id="toc-breif-description-about-the-data" class="nav-link" data-scroll-target="#breif-description-about-the-data">Breif description about the data:</a></li>
  </ul></li>
  <li><a href="#visualization" id="toc-visualization" class="nav-link" data-scroll-target="#visualization">Visualization</a>
  <ul class="collapse">
  <li><a href="#sales-performance-over-the-years" id="toc-sales-performance-over-the-years" class="nav-link" data-scroll-target="#sales-performance-over-the-years">Sales Performance over the Years:</a></li>
  <li><a href="#sales-distribution-by-gender-over-years" id="toc-sales-distribution-by-gender-over-years" class="nav-link" data-scroll-target="#sales-distribution-by-gender-over-years">Sales Distribution by Gender over years:</a></li>
  <li><a href="#profitability-analysis-by-month" id="toc-profitability-analysis-by-month" class="nav-link" data-scroll-target="#profitability-analysis-by-month">Profitability Analysis by Month:</a></li>
  <li><a href="#profitability-analysis-among-the-countries" id="toc-profitability-analysis-among-the-countries" class="nav-link" data-scroll-target="#profitability-analysis-among-the-countries">Profitability Analysis among the countries:</a></li>
  <li><a href="#multivariate-analysis-age-group" id="toc-multivariate-analysis-age-group" class="nav-link" data-scroll-target="#multivariate-analysis-age-group">Multivariate Analysis: Age Group:</a></li>
  <li><a href="#mean-profit-based-on-age-group" id="toc-mean-profit-based-on-age-group" class="nav-link" data-scroll-target="#mean-profit-based-on-age-group">Mean Profit based on Age Group:</a></li>
  <li><a href="#monthly-sales-across-years" id="toc-monthly-sales-across-years" class="nav-link" data-scroll-target="#monthly-sales-across-years">Monthly Sales across Years:</a></li>
  <li><a href="#seasonal-sales-based-on-country" id="toc-seasonal-sales-based-on-country" class="nav-link" data-scroll-target="#seasonal-sales-based-on-country">Seasonal sales based on country:</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  <li><a href="#bibliography" id="toc-bibliography" class="nav-link" data-scroll-target="#bibliography">Bibliography</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">DACSS601: Final Paper</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
  <div class="quarto-categories">
    <div class="quarto-category">bike_sales_data</div>
    <div class="quarto-category">final_project_data_description_and_visualization</div>
  </div>
  </div>

<div>
  <div class="description">
    Bike Sales
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Harsha Kanaka Eswar Gudipudi </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 22, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>The dataset used in this analysis was collected by the Global Bike Inc., a leading manufacturer and retailer of bicycles worldwide. The dataset provides comprehensive information on bike sales, customer demographics, and profitability across multiple countries.</p>
<p>The dataset includes data on various aspects, such as sales transactions, customer information, product details, and financial records. Each row in the dataset represents a specific sales transaction, providing details about the customer, the purchased product, the country of sale, and other relevant information.</p>
<p>The dataset was collected over a period of several years, encompassing different seasons and economic conditions. The collection process involved tracking sales data from various Global Bike retail locations and online channels, as well as gathering customer feedback and preferences.</p>
<section id="research-questions" class="level2">
<h2 class="anchored" data-anchor-id="research-questions">Research Questions</h2>
<p>Based on this dataset, the following research questions will be explored:</p>
<ol type="1">
<li>What are the top-selling bike models and their sales trends over the years?</li>
<li>How is the gender distribution among bike customers, and do gender preferences vary for different bike models?</li>
<li>How does profitability vary by month, and are there any seasonal patterns in bike sales?</li>
<li>Are there significant differences in profitability among countries, and what factors may contribute to these variations?</li>
<li>How does customer age impact bike sales and profitability, and are there any age-specific preferences?</li>
</ol>
<p>By addressing these research questions, we aim to gain insights into the sales performance, customer preferences, and profitability patterns within the bike industry. These findings will help inform decision-making processes related to marketing strategies, inventory management, and product development, ultimately leading to improved business performance and customer satisfaction.</p>
</section>
<section id="data" class="level2">
<h2 class="anchored" data-anchor-id="data">Data</h2>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(maps)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gridExtra)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">TRUE</span>, <span class="at">warning=</span><span class="cn">FALSE</span>, <span class="at">message=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"HarshaKanakaEswar_FinalProjectData/bike_sales_data.csv"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 113036     18</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>      Date                 Day           Month                Year     
 Min.   :2011-01-01   Min.   : 1.00   Length:113036      Min.   :2011  
 1st Qu.:2013-12-22   1st Qu.: 8.00   Class :character   1st Qu.:2013  
 Median :2014-06-27   Median :16.00   Mode  :character   Median :2014  
 Mean   :2014-11-23   Mean   :15.67                      Mean   :2014  
 3rd Qu.:2016-01-09   3rd Qu.:23.00                      3rd Qu.:2016  
 Max.   :2016-07-31   Max.   :31.00                      Max.   :2016  
  Customer_Age    Age_Group         Customer_Gender      Country         
 Min.   :17.00   Length:113036      Length:113036      Length:113036     
 1st Qu.:28.00   Class :character   Class :character   Class :character  
 Median :35.00   Mode  :character   Mode  :character   Mode  :character  
 Mean   :35.92                                                           
 3rd Qu.:43.00                                                           
 Max.   :87.00                                                           
    State           Product_Category   Sub_Category         Product         
 Length:113036      Length:113036      Length:113036      Length:113036     
 Class :character   Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character   Mode  :character  
                                                                            
                                                                            
                                                                            
 Order_Quantity   Unit_Cost        Unit_Price         Profit       
 Min.   : 1.0   Min.   :   1.0   Min.   :   2.0   Min.   :  -30.0  
 1st Qu.: 2.0   1st Qu.:   2.0   1st Qu.:   5.0   1st Qu.:   29.0  
 Median :10.0   Median :   9.0   Median :  24.0   Median :  101.0  
 Mean   :11.9   Mean   : 267.3   Mean   : 452.9   Mean   :  285.1  
 3rd Qu.:20.0   3rd Qu.:  42.0   3rd Qu.:  70.0   3rd Qu.:  358.0  
 Max.   :32.0   Max.   :2171.0   Max.   :3578.0   Max.   :15096.0  
      Cost            Revenue       
 Min.   :    1.0   Min.   :    2.0  
 1st Qu.:   28.0   1st Qu.:   63.0  
 Median :  108.0   Median :  223.0  
 Mean   :  469.3   Mean   :  754.4  
 3rd Qu.:  432.0   3rd Qu.:  800.0  
 Max.   :42978.0   Max.   :58074.0  </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>unique_country <span class="ot">&lt;-</span> <span class="fu">unique</span>(data<span class="sc">$</span>Country)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">paste</span>(unique_country, <span class="at">collapse =</span> <span class="st">", "</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Canada, Australia, United States, Germany, France, United Kingdom</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check for NA values in the dataset</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>na_values <span class="ot">&lt;-</span> <span class="fu">apply</span>(data, <span class="dv">2</span>, <span class="cf">function</span>(x) <span class="fu">any</span>(<span class="fu">is.na</span>(x)))</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Check for empty values in the dataset</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>empty_values <span class="ot">&lt;-</span> <span class="fu">apply</span>(data, <span class="dv">2</span>, <span class="cf">function</span>(x) <span class="fu">any</span>(x <span class="sc">==</span> <span class="st">""</span>))</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine NA and empty value checks</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>missing_values <span class="ot">&lt;-</span> na_values <span class="sc">|</span> empty_values</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the columns with missing values</span></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Columns with missing values:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Columns with missing values:</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">names</span>(data)[missing_values])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>character(0)</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert country names</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>Country[data<span class="sc">$</span>Country <span class="sc">==</span> <span class="st">"United States"</span>] <span class="ot">&lt;-</span> <span class="st">"USA"</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>Country[data<span class="sc">$</span>Country <span class="sc">==</span> <span class="st">"United Kingdom"</span>] <span class="ot">&lt;-</span> <span class="st">"UK"</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Year =</span> <span class="fu">factor</span>(Year),</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">Month =</span> <span class="fu">factor</span>(Month, <span class="at">levels =</span> month.name),</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">Age_Group =</span> <span class="fu">factor</span>(Age_Group, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Youth (&lt;25)"</span>, <span class="st">"Young Adults (25-34)"</span>, <span class="st">"Adults (35-64)"</span>, <span class="st">"Seniors (64+)"</span>)),</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">Customer_Gender =</span> <span class="fu">factor</span>(Customer_Gender, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"M"</span>, <span class="st">"F"</span>)),</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">Profit_Percentage =</span> (Profit <span class="sc">/</span> Cost) <span class="sc">*</span> <span class="dv">100</span>)</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["Date"],"name":[1],"type":["date"],"align":["right"]},{"label":["Day"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["Month"],"name":[3],"type":["fct"],"align":["left"]},{"label":["Year"],"name":[4],"type":["fct"],"align":["left"]},{"label":["Customer_Age"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["Age_Group"],"name":[6],"type":["fct"],"align":["left"]},{"label":["Customer_Gender"],"name":[7],"type":["fct"],"align":["left"]},{"label":["Country"],"name":[8],"type":["chr"],"align":["left"]},{"label":["State"],"name":[9],"type":["chr"],"align":["left"]},{"label":["Product_Category"],"name":[10],"type":["chr"],"align":["left"]},{"label":["Sub_Category"],"name":[11],"type":["chr"],"align":["left"]},{"label":["Product"],"name":[12],"type":["chr"],"align":["left"]},{"label":["Order_Quantity"],"name":[13],"type":["dbl"],"align":["right"]},{"label":["Unit_Cost"],"name":[14],"type":["dbl"],"align":["right"]},{"label":["Unit_Price"],"name":[15],"type":["dbl"],"align":["right"]},{"label":["Profit"],"name":[16],"type":["dbl"],"align":["right"]},{"label":["Cost"],"name":[17],"type":["dbl"],"align":["right"]},{"label":["Revenue"],"name":[18],"type":["dbl"],"align":["right"]},{"label":["Profit_Percentage"],"name":[19],"type":["dbl"],"align":["right"]}],"data":[{"1":"2013-11-26","2":"26","3":"November","4":"2013","5":"19","6":"Youth (<25)","7":"M","8":"Canada","9":"British Columbia","10":"Accessories","11":"Bike Racks","12":"Hitch Rack - 4-Bike","13":"8","14":"45","15":"120","16":"590","17":"360","18":"950","19":"163.8889"},{"1":"2015-11-26","2":"26","3":"November","4":"2015","5":"19","6":"Youth (<25)","7":"M","8":"Canada","9":"British Columbia","10":"Accessories","11":"Bike Racks","12":"Hitch Rack - 4-Bike","13":"8","14":"45","15":"120","16":"590","17":"360","18":"950","19":"163.8889"},{"1":"2014-03-23","2":"23","3":"March","4":"2014","5":"49","6":"Adults (35-64)","7":"M","8":"Australia","9":"New South Wales","10":"Accessories","11":"Bike Racks","12":"Hitch Rack - 4-Bike","13":"23","14":"45","15":"120","16":"1366","17":"1035","18":"2401","19":"131.9807"},{"1":"2016-03-23","2":"23","3":"March","4":"2016","5":"49","6":"Adults (35-64)","7":"M","8":"Australia","9":"New South Wales","10":"Accessories","11":"Bike Racks","12":"Hitch Rack - 4-Bike","13":"20","14":"45","15":"120","16":"1188","17":"900","18":"2088","19":"132.0000"},{"1":"2014-05-15","2":"15","3":"May","4":"2014","5":"47","6":"Adults (35-64)","7":"F","8":"Australia","9":"New South Wales","10":"Accessories","11":"Bike Racks","12":"Hitch Rack - 4-Bike","13":"4","14":"45","15":"120","16":"238","17":"180","18":"418","19":"132.2222"},{"1":"2016-05-15","2":"15","3":"May","4":"2016","5":"47","6":"Adults (35-64)","7":"F","8":"Australia","9":"New South Wales","10":"Accessories","11":"Bike Racks","12":"Hitch Rack - 4-Bike","13":"5","14":"45","15":"120","16":"297","17":"225","18":"522","19":"132.0000"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
</section>
<section id="breif-description-about-the-data" class="level2">
<h2 class="anchored" data-anchor-id="breif-description-about-the-data">Breif description about the data:</h2>
<p>The dataset used for this analysis contains information about bike sales. Each row in the dataset represents a specific bike sale transaction. The dataset includes several variables that provide insights into different aspects of the sales process and customer behavior.</p>
<p>One of the key variables in the dataset is “Product,” which represents the specific bike product sold. The dataset includes a total of [insert number of unique products] unique bike products. Each bike product has its own characteristics, such as brand, model, and type, which are not explicitly mentioned in this dataset.</p>
<p>Another important variable is “Quantity,” which indicates the number of bikes sold in each transaction. This variable allows us to analyze the sales volume and identify the most popular bike products.</p>
<p>Additionally, the dataset includes the “Profit” variable, which represents the profit generated from each bike sale. By examining the summary statistics for the “Profit” variable, including measures such as minimum, maximum, mean, and median, we can gain insights into the overall profitability of the bike sales.</p>
<p>The dataset has 18 Columns and it comprises 113,036 records spanning from January 2011 to July 2016. The customers’ ages range from 17 to 87 years, with an average age of approximately 35.92 years.</p>
<p>These statistics provide a high-level overview of the dataset and give us a sense of the range and distribution of the “Quantity” and “Profit” variables. However, it is important to note that these summary statistics do not capture the full complexity of the dataset, and further analysis is needed to explore relationships between variables and uncover more detailed insights.</p>
<p>By focusing on these key variables, we can gain valuable insights into the sales performance, customer preferences, and profitability of bike sales. To prepare the data for analysis, the following steps were performed:</p>
<ol type="1">
<li>Converted country names: The country names were standardized to improve data consistency and facilitate</li>
<li>visualization. “United States” was converted to “USA,” and “United Kingdom” was converted to “UK.”</li>
<li>Modified data types: The “Year,” “Month,” “Age_Group,” and “Customer_Gender” columns were converted to factors to control the order and improve visualization.</li>
<li>Calculated profit percentage: A new column, “Profit_Percentage,” was created by dividing the “Profit” column by the “Cost” column and multiplying the result by 100. This calculation provides insights into the profitability of each transaction.</li>
<li>Removing NA and Empty values: Searched for the empty and NA values in the data and the data didn’t contain any empty or NA values.</li>
</ol>
</section>
</section>
<section id="visualization" class="level1">
<h1>Visualization</h1>
<section id="sales-performance-over-the-years" class="level2">
<h2 class="anchored" data-anchor-id="sales-performance-over-the-years">Sales Performance over the Years:</h2>
<p>The analysis explores the sales performance of different bike products over the years. By examining the trends and fluctuations in the total sales of the top-selling products, we gain insights into their popularity and identify high-performing products. This information is valuable for making data-driven decisions related to marketing strategies, inventory management, and product development. The graph visualizes the sales performance of different products over the years, highlighting the top-selling products in each year</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Top 10 selling products per year</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(RColorBrewer)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>sales_by_year <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Year, Product) <span class="sc">%&gt;%</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Total_Sales =</span> <span class="fu">sum</span>(Revenue)) <span class="sc">%&gt;%</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(Total_Sales)) <span class="sc">%&gt;%</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Year) <span class="sc">%&gt;%</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">top_n</span>(<span class="at">n =</span> <span class="dv">10</span>)</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>n_colors <span class="ot">&lt;-</span> <span class="fu">n_distinct</span>(sales_by_year<span class="sc">$</span>Product)</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>palette1 <span class="ot">&lt;-</span> <span class="fu">brewer.pal</span>(n_colors, <span class="at">name =</span> <span class="st">"Set1"</span>)</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>palette2 <span class="ot">&lt;-</span> <span class="fu">brewer.pal</span>(n_colors, <span class="at">name =</span> <span class="st">"Set2"</span>)</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting sales performance over the years for multiple products</span></span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sales_by_year, <span class="fu">aes</span>(<span class="at">x =</span> Year, <span class="at">y =</span> Total_Sales, <span class="at">color =</span> Product)) <span class="sc">+</span></span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Sales Performance of Different Products Over the Years"</span>,</span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Year"</span>,</span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Total Sales"</span>,</span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"Product"</span>) <span class="sc">+</span></span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(palette1, palette2) , <span class="at">name =</span> <span class="st">"Product"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="HarshaKanakaEswarGudipudi_FinalProject_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The data is grouped by the “Year” and “Product” variables using the group_by() function.The summarise() function is applied to calculate the sum of the “Revenue” variable, resulting in the total sales for each combination of year and product.The data is then arranged in descending order based on the “Total_Sales” variable using the arrange() function.Next, the data is grouped again by the “Year” variable using group_by() to prepare for selecting the top 10 rows for each year.Finally, the top_n() function is used to retain only the top 10 rows for each year, based on the highest total sales.</p>
<p>The graph above showcases the sales performance of different products over the years. Each product is represented by a unique color, brewer.pal() is used to get distint colors allowing for easy differentiation. Analyzing the sales performance over the years, we observe trends and fluctuations in the total sales of top ten products. We can see Road 150 Red,48 is the top selling bike in the year 2011, 2012 followed by Road 150 Red, 62 and Road 150 Red, 56. In the following years 2013, Road 150 Red, 62 became the top seller. The sales of Road 150 Red, 62 Skyrocketed in 2015 generating vast revenue exceeding 900 thousand usd.</p>
</section>
<section id="sales-distribution-by-gender-over-years" class="level2">
<h2 class="anchored" data-anchor-id="sales-distribution-by-gender-over-years">Sales Distribution by Gender over years:</h2>
<p>The analysis focuses on the sales distribution by gender over the years. By examining the proportion of sales for each gender, we can understand the gender preferences and identify any variations in sales patterns. The visualization showcases the sales distribution by gender using stacked bar charts. The segments within the bars represent the proportion of sales for each gender, allowing us to compare the sales distribution between males and females. The consistent percentage of sales between the two genders suggests a relatively equal appeal and demand for bikes among both male and female customers.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Sales distribution by gender over the years</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>sales_by_gender <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Year, Customer_Gender) <span class="sc">%&gt;%</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Total_Sales =</span> <span class="fu">sum</span>(Revenue))</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting sales distribution by gender over the years</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sales_by_gender, <span class="fu">aes</span>(<span class="at">x =</span> Year, <span class="at">y =</span> Total_Sales, <span class="at">fill =</span> Customer_Gender)) <span class="sc">+</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="st">"stack"</span>) <span class="sc">+</span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Sales Distribution by Gender Over the Years"</span>,</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Year"</span>,</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Total Sales"</span>,</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Customer Gender"</span>) <span class="sc">+</span></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"M"</span> <span class="ot">=</span> <span class="st">"blue"</span>, <span class="st">"F"</span> <span class="ot">=</span> <span class="st">"pink"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="HarshaKanakaEswarGudipudi_FinalProject_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>In the code above, we calculate the total sales for each gender and year by grouping the data and creating Total_sales by summing up the Revenue. Then, we plot the sales distribution using a stacked bar chart, where each bar represents the total sales for each year, and the segments within the bars represent the sales distribution by gender.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Function to create pie chart</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>create_pie_chart <span class="ot">&lt;-</span> <span class="cf">function</span>(year) {</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  sales_by_gender_year <span class="ot">&lt;-</span> sales_by_gender <span class="sc">%&gt;%</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(Year <span class="sc">==</span> year)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>  pie_chart <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(sales_by_gender_year, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">""</span>, <span class="at">y =</span> Total_Sales, <span class="at">fill =</span> Customer_Gender)) <span class="sc">+</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">width =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">coord_polar</span>(<span class="st">"y"</span>, <span class="at">start =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">fill =</span> <span class="st">"Customer Gender"</span>) <span class="sc">+</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_void</span>() <span class="sc">+</span></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>) <span class="sc">+</span></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> scales<span class="sc">::</span><span class="fu">percent</span>(Total_Sales <span class="sc">/</span> <span class="fu">sum</span>(Total_Sales))),</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>              <span class="at">position =</span> <span class="fu">position_stack</span>(<span class="at">vjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggtitle</span>(<span class="fu">paste</span>(<span class="st">"Year:"</span>, year))</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(pie_chart)</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a list of pie charts for each year</span></span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a>pie_charts <span class="ot">&lt;-</span> <span class="fu">lapply</span>(<span class="fu">unique</span>(sales_by_gender<span class="sc">$</span>Year), create_pie_chart)</span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine pie charts into a grid</span></span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a>grid <span class="ot">&lt;-</span> <span class="fu">grid.arrange</span>(<span class="at">grobs =</span> pie_charts, <span class="at">ncol =</span> <span class="dv">3</span>, <span class="at">top =</span> <span class="st">"Sales Distribution by Gender Over the Years"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="HarshaKanakaEswarGudipudi_FinalProject_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>In the code above, we define a function create_pie_chart that takes a year as input and creates a pie chart representing the sales distribution by gender for that specific year.We then use lapply to apply the create_pie_chart function to each unique year in the sales_by_gender dataset, resulting in a list of pie charts for each year. Finally, we use the grid.arrange function from the gridExtra package to combine the pie charts into a grid layout with three columns (adjust the ncol parameter as desired). The resulting grid is stored in the grid variable.</p>
<p>As we can see from the above grid of pie charts that the percentage of sales each year is almost the same for both males and females, it implies that there is a relatively equal distribution of sales between the two gender groups. This can suggest that the bikeshas similar appeal and demand among both male and female customers.</p>
</section>
<section id="profitability-analysis-by-month" class="level2">
<h2 class="anchored" data-anchor-id="profitability-analysis-by-month">Profitability Analysis by Month:</h2>
<p>The analysis delves into the profitability of bike sales by month. By calculating the average profit percentage for each month, we can identify any seasonal patterns or fluctuations in profitability. The visualization presents the average profitability over months, providing insights into the overall profitability trends throughout the year. Analyzing the graph helps us understand if there are any specific months that contribute significantly to profitability or if bike sales maintain consistent profitability across all months.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate average profit percentage by month</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>profitability_month <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Month) <span class="sc">%&gt;%</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Avg_Profit_Percentage =</span> <span class="fu">sum</span>(Profit) <span class="sc">/</span> <span class="fu">sum</span>(Cost)<span class="sc">*</span><span class="dv">100</span>)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot average profit percentage over months</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>month_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(profitability_month, <span class="fu">aes</span>(<span class="at">x =</span> Month, <span class="at">y =</span> Avg_Profit_Percentage)) <span class="sc">+</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Average Profitability Over Months"</span>,</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Month"</span>,</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Average Profit Percentage"</span>) <span class="sc">+</span></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the plot</span></span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>month_plot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="HarshaKanakaEswarGudipudi_FinalProject_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot average profit percentage over months</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>month_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(profitability_month, <span class="fu">aes</span>(<span class="at">x =</span> Month, <span class="at">y =</span> Avg_Profit_Percentage)) <span class="sc">+</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Average Profitability Over Months"</span>,</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Month"</span>,</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Average Profit Percentage"</span>) <span class="sc">+</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the plot</span></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>month_plot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="HarshaKanakaEswarGudipudi_FinalProject_files/figure-html/unnamed-chunk-7-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>In the code above, we group by month to calculate the average profit percentage for each month using summarise() function. Then, we create geom_bar() to create a bar plot to visualize the trend of average profit percentage over months. It can be seen that bike sales in overall are consistent around 60 percent profit for each month. Which implies that the bike sales are not largely effected by the month.</p>
</section>
<section id="profitability-analysis-among-the-countries" class="level2">
<h2 class="anchored" data-anchor-id="profitability-analysis-among-the-countries">Profitability Analysis among the countries:</h2>
<p>The analysis investigates the profitability of bike sales among different countries. By calculating the average profitability for each country, we can identify variations in profitability levels and potentially uncover factors that contribute to these differences. The visualization utilizes a world map to represent the profitability by country. Each country is shaded according to its average profitability, allowing for easy identification of regions with higher or lower profitability. This information helps in understanding the geographic distribution of profitability and making informed decisions related to market targeting and expansion strategies.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate average profitability by country</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>profitability_country <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Country) <span class="sc">%&gt;%</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Avg_Profitability =</span> <span class="fu">sum</span>(Profit)<span class="sc">/</span><span class="fu">sum</span>(Cost)<span class="sc">*</span><span class="dv">100</span>)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot world map based on profitability</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>world_map <span class="ot">&lt;-</span> <span class="fu">map_data</span>(<span class="st">"world"</span>)</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>world_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_map</span>(<span class="at">data =</span> world_map, <span class="at">map =</span> world_map,</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>           <span class="fu">aes</span>(<span class="at">x =</span> long, <span class="at">y =</span> lat, <span class="at">map_id =</span> region),</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>           <span class="at">fill =</span> <span class="st">"lightgray"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">size =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_map</span>(<span class="at">data =</span> profitability_country, <span class="at">map =</span> world_map,</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>           <span class="fu">aes</span>(<span class="at">fill =</span> Avg_Profitability, <span class="at">map_id =</span> Country),</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>           <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">size =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Profitability by Country"</span>,</span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Profitability"</span>) <span class="sc">+</span></span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_gradient</span>(<span class="at">low =</span> <span class="st">"lightblue"</span>, <span class="at">high =</span> <span class="st">"darkblue"</span>) <span class="sc">+</span></span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the world map</span></span>
<span id="cb18-22"><a href="#cb18-22" aria-hidden="true" tabindex="-1"></a>world_plot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="HarshaKanakaEswarGudipudi_FinalProject_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>In this code, we first calculate the average profitability by country using summarise() function. Then, we use the map_data() function from the maps package to obtain the map data for the world. The geom_map() function is used twice to plot the world map: first to create a base map with light gray color, and then to overlay the profitability data using the fill aesthetic to represent the average profitability by country.</p>
<p>By executing this code, you will see a world map that visualizes the profitability by country. Each country is shaded according to its average profitability, with a gradient scale from light blue to dark blue indicating the profitability levels. This map provides an overview of the profitability distribution across different countries, allowing for easy identification of regions with higher or lower profitability.</p>
<p>On an average over the years we can see the Canada is having the highest profitability above 80 percent standing in the top while Australia making the least profitability around 50 percent. United states stands in the second place followed by United Kingdom and France.</p>
</section>
<section id="multivariate-analysis-age-group" class="level2">
<h2 class="anchored" data-anchor-id="multivariate-analysis-age-group">Multivariate Analysis: Age Group:</h2>
<p>The analysis explores the relationship between age group and bike sales profitability and quantity. By grouping the data based on age groups, we calculate the average profitability and total quantity for each group. The visualization presents a scatter plot that represents the multivariate analysis, with the x-axis indicating the average profitability and the y-axis indicating the total quantity. Each data point is color-coded based on the age group. Analyzing the scatter plot helps us understand any patterns or correlations between age group, profitability, and quantity. This information can be useful in tailoring marketing strategies and product offerings to specific age groups and maximizing profitability.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Multivariate analysis using Age_Group</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>age_group_analysis <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Age_Group) <span class="sc">%&gt;%</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Avg_Profitability =</span> <span class="fu">sum</span>(Profit)<span class="sc">/</span><span class="fu">sum</span>(Cost)<span class="sc">*</span><span class="dv">100</span>,</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">Total_Quantity =</span> <span class="fu">sum</span>(Order_Quantity))</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting multivariate analysis</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>age_group_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(age_group_analysis, <span class="fu">aes</span>(<span class="at">x =</span> Avg_Profitability, <span class="at">y =</span> Total_Quantity, <span class="at">color =</span> Age_Group)) <span class="sc">+</span></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Multivariate Analysis: Age Group"</span>,</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Average Profitability"</span>,</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Total Quantity"</span>,</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"Age Group"</span>) <span class="sc">+</span></span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the plot</span></span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>age_group_plot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="HarshaKanakaEswarGudipudi_FinalProject_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>In this code, we use the group_by() for each age group and summarise() to calculate the average profitability (Avg_Profitability) and the total quantity (Total_Quantity). Then, we use ggplot() and geom_point() to create a scatter plot where the x-axis represents the average profitability, the y-axis represents the total quantity, and the points are colored based on the age group. By executing this code, we will see a scatter plot that illustrates the multivariate analysis using the “Age_Group” variable. Each point represents an age group, and its position on the plot shows the average profitability and total quantity associated with that age group. This analysis helps identify any patterns or relationships between age groups and their impact on profitability and quantity.</p>
<p>we can conclude form the plot that the order quantity is highest in the Adults aged between 35-64 followed by young adults between 25-34. The sales of bikes is least for the seniors above 64 age. Even though sales are less profitability of the seniors is high suggesting that seniors purchased costly bikes or bikes where profit margin is high.</p>
</section>
<section id="mean-profit-based-on-age-group" class="level2">
<h2 class="anchored" data-anchor-id="mean-profit-based-on-age-group">Mean Profit based on Age Group:</h2>
<p>The analysis examines the mean profit generated by bike sales across different countries and age groups. By calculating the average profit for each country and age group, we gain insights into the profitability levels based on these two variables. The visualization presents the mean profit by country and age group using a heatmap. Each cell in the heatmap represents the average profit for a specific combination of country and age group. The color intensity of each cell indicates the level of profitability, allowing for easy comparison and identification of countries and age groups with higher or lower mean profits. This information helps in understanding the profitability dynamics across different countries and age groups, enabling targeted marketing and business strategies.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(reshape2)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Reshape data for heatmap analysis</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>heatmap_data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Country, Age_Group, Profit)</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>heatmap_data <span class="ot">&lt;-</span> heatmap_data <span class="sc">%&gt;%</span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">dcast</span>(Country <span class="sc">~</span> Age_Group, <span class="at">value.var =</span> <span class="st">"Profit"</span>, mean)</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a heatmap to analyze Profit by Country and Age Group</span></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>heatmap_analysis <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="fu">melt</span>(heatmap_data, <span class="at">id.vars =</span> <span class="st">"Country"</span>), </span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>                           <span class="fu">aes</span>(<span class="at">x =</span> variable, <span class="at">y =</span> Country, <span class="at">fill =</span> value)) <span class="sc">+</span></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_tile</span>() <span class="sc">+</span></span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Profit by Country and Age Group (Heatmap)"</span>,</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Age Group"</span>,</span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Country"</span>,</span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Profit"</span>)</span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the heatmap analysis</span></span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a>heatmap_analysis</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="HarshaKanakaEswarGudipudi_FinalProject_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This code reshapes the data and creates a heatmap to analyze the Profit by Country and Age Group. The “heatmap_data” dataframe is created by selecting the “Country,” “Age_Group,” and “Profit” columns from the “data” dataset. The “heatmap_data” dataframe is further modified using the dcast() function from the “reshape2” library. The dcast() function reshapes the data, pivoting it to have “Country” as rows, “Age_Group” as columns, and the average “Profit” as the values in the cells.The resulting reshaped dataframe, “heatmap_data,” is then used to create a new ggplot object called “heatmap_analysis.” The heatmap provides a visual representation of the Profit values per unit, with colors indicating the intensity of Profit for different combinations of Country and Age Group.</p>
</section>
<section id="monthly-sales-across-years" class="level2">
<h2 class="anchored" data-anchor-id="monthly-sales-across-years">Monthly Sales across Years:</h2>
<p>The analysis focuses on tracking the monthly sales performance over the years. By examining the sales figures for each month, we can identify any seasonal patterns, trends, or fluctuations in sales. The visualization presents the monthly sales data using a bar graph, where each bar represents the sales for a specific month. The height of each bar indicates the sales amount, allowing for easy comparison between different months and years. Analyzing the bar graph helps us understand the overall sales trends over time and can provide insights for forecasting future sales, identifying peak periods, and optimizing inventory management.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate monthly sales</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>monthly_sales <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Month, Year) <span class="sc">%&gt;%</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Total_Sales =</span> <span class="fu">sum</span>(Revenue)) <span class="sc">%&gt;%</span> </span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(Month))</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a bar plot for monthly sales</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>monthly_sales_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(monthly_sales, <span class="fu">aes</span>(<span class="at">x =</span> Month, <span class="at">y =</span> Total_Sales, <span class="at">fill =</span> Year)) <span class="sc">+</span></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Monthly Sales"</span>,</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Month"</span>,</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Total Sales"</span>,</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Year"</span>) <span class="sc">+</span></span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()<span class="sc">+</span></span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">labels =</span> <span class="cf">function</span>(x) <span class="fu">substr</span>(x, <span class="dv">1</span>, <span class="dv">3</span>))</span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the monthly sales bar plot</span></span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a>monthly_sales_plot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="HarshaKanakaEswarGudipudi_FinalProject_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>By grouping the data by month and year and summarizing the revenue, the code generates a new data frame that provides the total sales for each unique combination of month and year in the original dataset. In the plot, I used the substr() function within the scale_x_discrete() function to modify the x-axis labels. The substr(x, 1, 3) extracts the first three letters of each label, effectively truncating the month names. A bar plot is then created to visualize the monthly sales, with each bar representing the total sales for a specific month and year. The bars are color-coded based on the year, providing a visual comparison between different years. In 2016 Janaury to June is the peak selling season for the bikes on contrast in 2015 the sales are peak during July to August. In 2011 the sales are same overall through January to December and it is the least sales year out of all the years from 2011 to 2016.</p>
</section>
<section id="seasonal-sales-based-on-country" class="level2">
<h2 class="anchored" data-anchor-id="seasonal-sales-based-on-country">Seasonal sales based on country:</h2>
<p>The analysis examines the seasonal sales patterns of the top 3 bike products across different countries. By analyzing the sales data for each season and country, we can identify variations in demand and popularity throughout the year. The visualization utilizes a boxplot to represent the seasonal sales for each country and bike product. The boxplot provides insights into the distribution of sales, including the median, quartiles, and any outliers. By comparing the boxplots across countries and bikes, we can identify countries with high or low sales during specific seasons for the top 3 bikes.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter the data for the top 3 bikes based on overall sales</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>top3_bikes <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Product) <span class="sc">%&gt;%</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Total_Sales =</span> <span class="fu">sum</span>(Revenue)) <span class="sc">%&gt;%</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">top_n</span>(<span class="dv">3</span>, Total_Sales) <span class="sc">%&gt;%</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Product)</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a new column for seasons based on the date</span></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>Season <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(<span class="fu">format</span>(data<span class="sc">$</span>Date, <span class="st">"%m"</span>) <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"12"</span>, <span class="st">"01"</span>, <span class="st">"02"</span>), <span class="st">"Winter"</span>,</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>                      <span class="fu">ifelse</span>(<span class="fu">format</span>(data<span class="sc">$</span>Date, <span class="st">"%m"</span>) <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"03"</span>, <span class="st">"04"</span>, <span class="st">"05"</span>), <span class="st">"Spring"</span>,</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>                             <span class="fu">ifelse</span>(<span class="fu">format</span>(data<span class="sc">$</span>Date, <span class="st">"%m"</span>) <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"06"</span>, <span class="st">"07"</span>, <span class="st">"08"</span>), <span class="st">"Summer"</span>, <span class="st">"Autumn"</span>)))</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Group the data by seasons, country, and bike product</span></span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>grouped_data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Product <span class="sc">%in%</span> top3_bikes<span class="sc">$</span>Product) <span class="sc">%&gt;%</span></span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Season, Country, Product) <span class="sc">%&gt;%</span></span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Total_Revenue =</span> <span class="fu">sum</span>(Revenue))</span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter the data to include only the top 3 bikes based on total revenue</span></span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a>top3_grouped_data <span class="ot">&lt;-</span> grouped_data <span class="sc">%&gt;%</span></span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Season, Country) <span class="sc">%&gt;%</span></span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(Total_Revenue)) <span class="sc">%&gt;%</span></span>
<span id="cb22-23"><a href="#cb22-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>)</span>
<span id="cb22-24"><a href="#cb22-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-25"><a href="#cb22-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a box plot to visualize the revenue distribution for each season, country, and bike</span></span>
<span id="cb22-26"><a href="#cb22-26" aria-hidden="true" tabindex="-1"></a>boxplot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(top3_grouped_data, <span class="fu">aes</span>(<span class="at">x =</span> Season, <span class="at">y =</span> Total_Revenue, <span class="at">fill =</span> Country)) <span class="sc">+</span></span>
<span id="cb22-27"><a href="#cb22-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb22-28"><a href="#cb22-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Revenue Distribution for Top 3 Bikes by Season and Country"</span>,</span>
<span id="cb22-29"><a href="#cb22-29" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Season"</span>,</span>
<span id="cb22-30"><a href="#cb22-30" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Total Revenue"</span>,</span>
<span id="cb22-31"><a href="#cb22-31" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Country"</span>) <span class="sc">+</span></span>
<span id="cb22-32"><a href="#cb22-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb22-33"><a href="#cb22-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-34"><a href="#cb22-34" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the box plot</span></span>
<span id="cb22-35"><a href="#cb22-35" aria-hidden="true" tabindex="-1"></a>boxplot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="HarshaKanakaEswarGudipudi_FinalProject_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The format(data$Date, “%m”) extracts the month from the “Date” column using the format() function with the “%m” format specifier. This will return a two-digit representation of the month (e.g., “01” for January, “02” for February, etc.). %in% c(“12”, “01”, “02”) checks if the extracted month value is equal to any of the values in the vector “c(”12”, “01”, “02”)“. If it matches any of these values, it indicates that the month falls within the winter season. similarly for other seasons used ifelse() statement.</p>
<p>After the seasons extracted from the date column, created a box plot to visualize the revenue distribution across different seasons. Each box plot represents the revenue distribution for a specific season, providing insights into the seasonal variations in sales. In each box plot top 3 sales are considered for the season showing how closely the competition is present in the market. In Australia, If we see in the winter season top bike in the sales is has no close competition with others. For the Canada there is always a close competition in the sales.</p>
</section>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>In this analysis, we explored a comprehensive dataset on bike sales collected by Global Bike Inc.&nbsp;The dataset provided valuable insights into sales transactions, customer demographics, and profitability across multiple countries. By addressing a set of research questions, we gained insights into the sales performance, customer preferences, and profitability patterns within the bike industry.</p>
<p>Based on our analysis, we found the following key findings:</p>
<ol type="1">
<li><p><strong>Top-selling Bike Models and Sales Trends</strong>: We identified the top-selling bike models and observed their sales trends over the years. The Road 150 Red, 62 model emerged as a consistent top performer, generating significant revenue in multiple years.</p></li>
<li><p><strong>Gender Distribution and Preferences</strong>: The analysis of gender distribution among bike customers revealed a relatively equal distribution of sales between male and female customers. This suggests that the bike products have similar appeal and demand among both genders.</p></li>
<li><p><strong>Profitability Variation by Month</strong>: We examined the profitability variation by month and found that bike sales maintained a consistent profitability level around 60 percent throughout the year. This indicates that bike sales are not significantly influenced by the month.</p></li>
<li><p><strong>Profitability Variation Among Countries</strong>: We analyzed the profitability across different countries and identified variations in profitability levels. Canada stood out as the highest-profitability country, while Australia had the lowest profitability. The United States, the United Kingdom, and France also exhibited notable profitability levels.</p></li>
<li><p><strong>Age-specific Preferences</strong>: The multivariate analysis revealed insights into age-specific preferences. We observed that the youth and young adult age groups showed higher average profitability, indicating potential opportunities for targeted marketing and product development.</p></li>
</ol>
<p>These findings provide valuable insights for decision-making processes related to marketing strategies, inventory management, and product development within the bike industry. By understanding the top-selling models, gender distribution, profitability patterns, and age-specific preferences, businesses can make data-driven decisions to improve performance and enhance customer satisfaction.</p>
<p>It is important to note that this analysis is based on the available dataset and its limitations. Further research and analysis can be conducted to delve deeper into specific aspects of bike sales, such as customer segmentation, marketing campaign effectiveness, and competitive analysis.</p>
<p>Overall, this analysis offers a comprehensive understanding of bike sales, customer preferences, and profitability patterns, enabling businesses to make informed decisions and drive growth in the bike industry.</p>
</section>
<section id="bibliography" class="level1">
<h1>Bibliography</h1>
<p>Bike sales Dataset (2011-2016) - https://www.kaggle.com/datasets/sadiqshah/bike-sales-in-europe?datasetId=889310&amp;language=R</p>
<p>R Language as programming language</p>
<p>Wickham, H., &amp; Grolemund, G. (2016). <em>R for data science: Visualize, model, transform, tidy, and import data</em>. OReilly Media.</p>
<p>The R Graph Gallery-https://r-graph-gallery.com/<br>
</p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="DACSS/601_Spring_2023" data-repo-id="R_kgDOI4JcJA" data-category="Announcements" data-category-id="" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb23" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "DACSS601: Final Paper"</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Harsha Kanaka Eswar Gudipudi"</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> "Bike Sales"</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "05/22/2023"</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="an">output:</span><span class="co"> distill::distill_article</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a><span class="co">    df-print: paged</span></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a><span class="co">    code-copy: true</span></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a><span class="co">    css: styles.css</span></span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span></span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a><span class="co">  - bike_sales_data</span></span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a><span class="co">  - final_project_data_description_and_visualization</span></span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a><span class="an">editor_options:</span><span class="co"> </span></span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a><span class="co">  chunk_output_type: console</span></span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-22"><a href="#cb23-22" aria-hidden="true" tabindex="-1"></a><span class="fu"># Introduction</span></span>
<span id="cb23-23"><a href="#cb23-23" aria-hidden="true" tabindex="-1"></a>The dataset used in this analysis was collected by the Global Bike Inc., a leading manufacturer and retailer of bicycles worldwide. The dataset provides comprehensive information on bike sales, customer demographics, and profitability across multiple countries.</span>
<span id="cb23-24"><a href="#cb23-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-25"><a href="#cb23-25" aria-hidden="true" tabindex="-1"></a>The dataset includes data on various aspects, such as sales transactions, customer information, product details, and financial records. Each row in the dataset represents a specific sales transaction, providing details about the customer, the purchased product, the country of sale, and other relevant information.</span>
<span id="cb23-26"><a href="#cb23-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-27"><a href="#cb23-27" aria-hidden="true" tabindex="-1"></a>The dataset was collected over a period of several years, encompassing different seasons and economic conditions. The collection process involved tracking sales data from various Global Bike retail locations and online channels, as well as gathering customer feedback and preferences.</span>
<span id="cb23-28"><a href="#cb23-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-29"><a href="#cb23-29" aria-hidden="true" tabindex="-1"></a><span class="fu">## Research Questions</span></span>
<span id="cb23-30"><a href="#cb23-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-31"><a href="#cb23-31" aria-hidden="true" tabindex="-1"></a>Based on this dataset, the following research questions will be explored:</span>
<span id="cb23-32"><a href="#cb23-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-33"><a href="#cb23-33" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>What are the top-selling bike models and their sales trends over the years?</span>
<span id="cb23-34"><a href="#cb23-34" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>How is the gender distribution among bike customers, and do gender preferences vary for different bike models?</span>
<span id="cb23-35"><a href="#cb23-35" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>How does profitability vary by month, and are there any seasonal patterns in bike sales?</span>
<span id="cb23-36"><a href="#cb23-36" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>Are there significant differences in profitability among countries, and what factors may contribute to these variations?</span>
<span id="cb23-37"><a href="#cb23-37" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>How does customer age impact bike sales and profitability, and are there any age-specific preferences?</span>
<span id="cb23-38"><a href="#cb23-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-39"><a href="#cb23-39" aria-hidden="true" tabindex="-1"></a>By addressing these research questions, we aim to gain insights into the sales performance, customer preferences, and profitability patterns within the bike industry. These findings will help inform decision-making processes related to marketing strategies, inventory management, and product development, ultimately leading to improved business performance and customer satisfaction.</span>
<span id="cb23-40"><a href="#cb23-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-41"><a href="#cb23-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-42"><a href="#cb23-42" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb23-43"><a href="#cb23-43" aria-hidden="true" tabindex="-1"></a><span class="fu">## Data</span></span>
<span id="cb23-44"><a href="#cb23-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-47"><a href="#cb23-47" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb23-48"><a href="#cb23-48" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: setup</span></span>
<span id="cb23-49"><a href="#cb23-49" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb23-50"><a href="#cb23-50" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb23-51"><a href="#cb23-51" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(maps)</span>
<span id="cb23-52"><a href="#cb23-52" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb23-53"><a href="#cb23-53" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb23-54"><a href="#cb23-54" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb23-55"><a href="#cb23-55" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb23-56"><a href="#cb23-56" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gridExtra)</span>
<span id="cb23-57"><a href="#cb23-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-58"><a href="#cb23-58" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">TRUE</span>, <span class="at">warning=</span><span class="cn">FALSE</span>, <span class="at">message=</span><span class="cn">FALSE</span>)</span>
<span id="cb23-59"><a href="#cb23-59" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb23-60"><a href="#cb23-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-61"><a href="#cb23-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-64"><a href="#cb23-64" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb23-65"><a href="#cb23-65" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"HarshaKanakaEswar_FinalProjectData/bike_sales_data.csv"</span>)</span>
<span id="cb23-66"><a href="#cb23-66" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(data)</span>
<span id="cb23-67"><a href="#cb23-67" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data)</span>
<span id="cb23-68"><a href="#cb23-68" aria-hidden="true" tabindex="-1"></a>unique_country <span class="ot">&lt;-</span> <span class="fu">unique</span>(data<span class="sc">$</span>Country)</span>
<span id="cb23-69"><a href="#cb23-69" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">paste</span>(unique_country, <span class="at">collapse =</span> <span class="st">", "</span>))</span>
<span id="cb23-70"><a href="#cb23-70" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb23-73"><a href="#cb23-73" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb23-74"><a href="#cb23-74" aria-hidden="true" tabindex="-1"></a><span class="co"># Check for NA values in the dataset</span></span>
<span id="cb23-75"><a href="#cb23-75" aria-hidden="true" tabindex="-1"></a>na_values <span class="ot">&lt;-</span> <span class="fu">apply</span>(data, <span class="dv">2</span>, <span class="cf">function</span>(x) <span class="fu">any</span>(<span class="fu">is.na</span>(x)))</span>
<span id="cb23-76"><a href="#cb23-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-77"><a href="#cb23-77" aria-hidden="true" tabindex="-1"></a><span class="co"># Check for empty values in the dataset</span></span>
<span id="cb23-78"><a href="#cb23-78" aria-hidden="true" tabindex="-1"></a>empty_values <span class="ot">&lt;-</span> <span class="fu">apply</span>(data, <span class="dv">2</span>, <span class="cf">function</span>(x) <span class="fu">any</span>(x <span class="sc">==</span> <span class="st">""</span>))</span>
<span id="cb23-79"><a href="#cb23-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-80"><a href="#cb23-80" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine NA and empty value checks</span></span>
<span id="cb23-81"><a href="#cb23-81" aria-hidden="true" tabindex="-1"></a>missing_values <span class="ot">&lt;-</span> na_values <span class="sc">|</span> empty_values</span>
<span id="cb23-82"><a href="#cb23-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-83"><a href="#cb23-83" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the columns with missing values</span></span>
<span id="cb23-84"><a href="#cb23-84" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Columns with missing values:</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb23-85"><a href="#cb23-85" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">names</span>(data)[missing_values])</span>
<span id="cb23-86"><a href="#cb23-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-87"><a href="#cb23-87" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert country names</span></span>
<span id="cb23-88"><a href="#cb23-88" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>Country[data<span class="sc">$</span>Country <span class="sc">==</span> <span class="st">"United States"</span>] <span class="ot">&lt;-</span> <span class="st">"USA"</span></span>
<span id="cb23-89"><a href="#cb23-89" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>Country[data<span class="sc">$</span>Country <span class="sc">==</span> <span class="st">"United Kingdom"</span>] <span class="ot">&lt;-</span> <span class="st">"UK"</span></span>
<span id="cb23-90"><a href="#cb23-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-91"><a href="#cb23-91" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb23-92"><a href="#cb23-92" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Year =</span> <span class="fu">factor</span>(Year),</span>
<span id="cb23-93"><a href="#cb23-93" aria-hidden="true" tabindex="-1"></a>         <span class="at">Month =</span> <span class="fu">factor</span>(Month, <span class="at">levels =</span> month.name),</span>
<span id="cb23-94"><a href="#cb23-94" aria-hidden="true" tabindex="-1"></a>         <span class="at">Age_Group =</span> <span class="fu">factor</span>(Age_Group, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Youth (&lt;25)"</span>, <span class="st">"Young Adults (25-34)"</span>, <span class="st">"Adults (35-64)"</span>, <span class="st">"Seniors (64+)"</span>)),</span>
<span id="cb23-95"><a href="#cb23-95" aria-hidden="true" tabindex="-1"></a>         <span class="at">Customer_Gender =</span> <span class="fu">factor</span>(Customer_Gender, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"M"</span>, <span class="st">"F"</span>)),</span>
<span id="cb23-96"><a href="#cb23-96" aria-hidden="true" tabindex="-1"></a>         <span class="at">Profit_Percentage =</span> (Profit <span class="sc">/</span> Cost) <span class="sc">*</span> <span class="dv">100</span>)</span>
<span id="cb23-97"><a href="#cb23-97" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data)</span>
<span id="cb23-98"><a href="#cb23-98" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb23-99"><a href="#cb23-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-100"><a href="#cb23-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-101"><a href="#cb23-101" aria-hidden="true" tabindex="-1"></a><span class="fu">## Breif description about the data:</span></span>
<span id="cb23-102"><a href="#cb23-102" aria-hidden="true" tabindex="-1"></a>The dataset used for this analysis contains information about bike sales. Each row in the dataset represents a specific bike sale transaction. The dataset includes several variables that provide insights into different aspects of the sales process and customer behavior. </span>
<span id="cb23-103"><a href="#cb23-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-104"><a href="#cb23-104" aria-hidden="true" tabindex="-1"></a>One of the key variables in the dataset is "Product," which represents the specific bike product sold. The dataset includes a total of <span class="co">[</span><span class="ot">insert number of unique products</span><span class="co">]</span> unique bike products. Each bike product has its own characteristics, such as brand, model, and type, which are not explicitly mentioned in this dataset.</span>
<span id="cb23-105"><a href="#cb23-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-106"><a href="#cb23-106" aria-hidden="true" tabindex="-1"></a>Another important variable is "Quantity," which indicates the number of bikes sold in each transaction. This variable allows us to analyze the sales volume and identify the most popular bike products.</span>
<span id="cb23-107"><a href="#cb23-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-108"><a href="#cb23-108" aria-hidden="true" tabindex="-1"></a>Additionally, the dataset includes the "Profit" variable, which represents the profit generated from each bike sale. By examining the summary statistics for the "Profit" variable, including measures such as minimum, maximum, mean, and median, we can gain insights into the overall profitability of the bike sales.</span>
<span id="cb23-109"><a href="#cb23-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-110"><a href="#cb23-110" aria-hidden="true" tabindex="-1"></a>The dataset has 18 Columns and it comprises 113,036 records spanning from January 2011 to July 2016. The customers' ages range from 17 to 87 years, with an average age of approximately 35.92 years. </span>
<span id="cb23-111"><a href="#cb23-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-112"><a href="#cb23-112" aria-hidden="true" tabindex="-1"></a>These statistics provide a high-level overview of the dataset and give us a sense of the range and distribution of the "Quantity" and "Profit" variables. However, it is important to note that these summary statistics do not capture the full complexity of the dataset, and further analysis is needed to explore relationships between variables and uncover more detailed insights.</span>
<span id="cb23-113"><a href="#cb23-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-114"><a href="#cb23-114" aria-hidden="true" tabindex="-1"></a>By focusing on these key variables, we can gain valuable insights into the sales performance, customer preferences, and profitability of bike sales.</span>
<span id="cb23-115"><a href="#cb23-115" aria-hidden="true" tabindex="-1"></a>To prepare the data for analysis, the following steps were performed:</span>
<span id="cb23-116"><a href="#cb23-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-117"><a href="#cb23-117" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>Converted country names: The country names were standardized to improve data consistency and facilitate </span>
<span id="cb23-118"><a href="#cb23-118" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>visualization. "United States" was converted to "USA," and "United Kingdom" was converted to "UK."</span>
<span id="cb23-119"><a href="#cb23-119" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>Modified data types: The "Year," "Month," "Age_Group," and "Customer_Gender" columns were converted to factors to control the order and improve visualization.</span>
<span id="cb23-120"><a href="#cb23-120" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>Calculated profit percentage: A new column, "Profit_Percentage," was created by dividing the "Profit" column by the "Cost" column and multiplying the result by 100. This calculation provides insights into the profitability of each transaction.</span>
<span id="cb23-121"><a href="#cb23-121" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>Removing NA and Empty values: Searched for the empty and NA values in the data and the data didn't contain any empty or NA values.</span>
<span id="cb23-122"><a href="#cb23-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-123"><a href="#cb23-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-124"><a href="#cb23-124" aria-hidden="true" tabindex="-1"></a><span class="fu"># Visualization</span></span>
<span id="cb23-125"><a href="#cb23-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-126"><a href="#cb23-126" aria-hidden="true" tabindex="-1"></a><span class="fu">## Sales Performance over the Years:</span></span>
<span id="cb23-127"><a href="#cb23-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-128"><a href="#cb23-128" aria-hidden="true" tabindex="-1"></a>The analysis explores the sales performance of different bike products over the years. By examining the trends and fluctuations in the total sales of the top-selling products, we gain insights into their popularity and identify high-performing products. This information is valuable for making data-driven decisions related to marketing strategies, inventory management, and product development. The graph visualizes the sales performance of different products over the years, highlighting the top-selling products in each year</span>
<span id="cb23-129"><a href="#cb23-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-130"><a href="#cb23-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-133"><a href="#cb23-133" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb23-134"><a href="#cb23-134" aria-hidden="true" tabindex="-1"></a><span class="co"># Top 10 selling products per year</span></span>
<span id="cb23-135"><a href="#cb23-135" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(RColorBrewer)</span>
<span id="cb23-136"><a href="#cb23-136" aria-hidden="true" tabindex="-1"></a>sales_by_year <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb23-137"><a href="#cb23-137" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Year, Product) <span class="sc">%&gt;%</span></span>
<span id="cb23-138"><a href="#cb23-138" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Total_Sales =</span> <span class="fu">sum</span>(Revenue)) <span class="sc">%&gt;%</span></span>
<span id="cb23-139"><a href="#cb23-139" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(Total_Sales)) <span class="sc">%&gt;%</span></span>
<span id="cb23-140"><a href="#cb23-140" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Year) <span class="sc">%&gt;%</span></span>
<span id="cb23-141"><a href="#cb23-141" aria-hidden="true" tabindex="-1"></a>  <span class="fu">top_n</span>(<span class="at">n =</span> <span class="dv">10</span>)</span>
<span id="cb23-142"><a href="#cb23-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-143"><a href="#cb23-143" aria-hidden="true" tabindex="-1"></a>n_colors <span class="ot">&lt;-</span> <span class="fu">n_distinct</span>(sales_by_year<span class="sc">$</span>Product)</span>
<span id="cb23-144"><a href="#cb23-144" aria-hidden="true" tabindex="-1"></a>palette1 <span class="ot">&lt;-</span> <span class="fu">brewer.pal</span>(n_colors, <span class="at">name =</span> <span class="st">"Set1"</span>)</span>
<span id="cb23-145"><a href="#cb23-145" aria-hidden="true" tabindex="-1"></a>palette2 <span class="ot">&lt;-</span> <span class="fu">brewer.pal</span>(n_colors, <span class="at">name =</span> <span class="st">"Set2"</span>)</span>
<span id="cb23-146"><a href="#cb23-146" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting sales performance over the years for multiple products</span></span>
<span id="cb23-147"><a href="#cb23-147" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sales_by_year, <span class="fu">aes</span>(<span class="at">x =</span> Year, <span class="at">y =</span> Total_Sales, <span class="at">color =</span> Product)) <span class="sc">+</span></span>
<span id="cb23-148"><a href="#cb23-148" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb23-149"><a href="#cb23-149" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb23-150"><a href="#cb23-150" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Sales Performance of Different Products Over the Years"</span>,</span>
<span id="cb23-151"><a href="#cb23-151" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Year"</span>,</span>
<span id="cb23-152"><a href="#cb23-152" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Total Sales"</span>,</span>
<span id="cb23-153"><a href="#cb23-153" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"Product"</span>) <span class="sc">+</span></span>
<span id="cb23-154"><a href="#cb23-154" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb23-155"><a href="#cb23-155" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(palette1, palette2) , <span class="at">name =</span> <span class="st">"Product"</span>)</span>
<span id="cb23-156"><a href="#cb23-156" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb23-157"><a href="#cb23-157" aria-hidden="true" tabindex="-1"></a>The data is grouped by the "Year" and "Product" variables using the group_by() function.The summarise() function is applied to calculate the sum of the "Revenue" variable, resulting in the total sales for each combination of year and product.The data is then arranged in descending order based on the "Total_Sales" variable using the arrange() function.Next, the data is grouped again by the "Year" variable using group_by() to prepare for selecting the top 10 rows for each year.Finally, the top_n() function is used to retain only the top 10 rows for each year, based on the highest total sales.</span>
<span id="cb23-158"><a href="#cb23-158" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-159"><a href="#cb23-159" aria-hidden="true" tabindex="-1"></a>The graph above showcases the sales performance of different products over the years. Each product is represented by a unique color, brewer.pal() is used to get distint colors allowing for easy differentiation. Analyzing the sales performance over the years, we observe trends and fluctuations in the total sales of top ten products. We can see Road 150 Red,48 is the top selling bike in the year 2011, 2012 followed by Road 150 Red, 62 and Road 150 Red, 56. In the following years 2013, Road 150 Red, 62 became the top seller. The sales of Road 150 Red, 62 Skyrocketed in 2015 generating vast revenue exceeding 900 thousand usd.</span>
<span id="cb23-160"><a href="#cb23-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-161"><a href="#cb23-161" aria-hidden="true" tabindex="-1"></a><span class="fu">## Sales Distribution by Gender over years:</span></span>
<span id="cb23-162"><a href="#cb23-162" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-163"><a href="#cb23-163" aria-hidden="true" tabindex="-1"></a>The analysis focuses on the sales distribution by gender over the years. By examining the proportion of sales for each gender, we can understand the gender preferences and identify any variations in sales patterns. The visualization showcases the sales distribution by gender using stacked bar charts. The segments within the bars represent the proportion of sales for each gender, allowing us to compare the sales distribution between males and females. The consistent percentage of sales between the two genders suggests a relatively equal appeal and demand for bikes among both male and female customers.</span>
<span id="cb23-164"><a href="#cb23-164" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-167"><a href="#cb23-167" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb23-168"><a href="#cb23-168" aria-hidden="true" tabindex="-1"></a><span class="co"># Sales distribution by gender over the years</span></span>
<span id="cb23-169"><a href="#cb23-169" aria-hidden="true" tabindex="-1"></a>sales_by_gender <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb23-170"><a href="#cb23-170" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Year, Customer_Gender) <span class="sc">%&gt;%</span></span>
<span id="cb23-171"><a href="#cb23-171" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Total_Sales =</span> <span class="fu">sum</span>(Revenue))</span>
<span id="cb23-172"><a href="#cb23-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-173"><a href="#cb23-173" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting sales distribution by gender over the years</span></span>
<span id="cb23-174"><a href="#cb23-174" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sales_by_gender, <span class="fu">aes</span>(<span class="at">x =</span> Year, <span class="at">y =</span> Total_Sales, <span class="at">fill =</span> Customer_Gender)) <span class="sc">+</span></span>
<span id="cb23-175"><a href="#cb23-175" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="st">"stack"</span>) <span class="sc">+</span></span>
<span id="cb23-176"><a href="#cb23-176" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Sales Distribution by Gender Over the Years"</span>,</span>
<span id="cb23-177"><a href="#cb23-177" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Year"</span>,</span>
<span id="cb23-178"><a href="#cb23-178" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Total Sales"</span>,</span>
<span id="cb23-179"><a href="#cb23-179" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Customer Gender"</span>) <span class="sc">+</span></span>
<span id="cb23-180"><a href="#cb23-180" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb23-181"><a href="#cb23-181" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"M"</span> <span class="ot">=</span> <span class="st">"blue"</span>, <span class="st">"F"</span> <span class="ot">=</span> <span class="st">"pink"</span>))</span>
<span id="cb23-182"><a href="#cb23-182" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-183"><a href="#cb23-183" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb23-184"><a href="#cb23-184" aria-hidden="true" tabindex="-1"></a>In the code above, we calculate the total sales for each gender and year by grouping the data and creating Total_sales by summing up the Revenue. Then, we plot the sales distribution using a stacked bar chart, where each bar represents the total sales for each year, and the segments within the bars represent the sales distribution by gender.</span>
<span id="cb23-187"><a href="#cb23-187" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb23-188"><a href="#cb23-188" aria-hidden="true" tabindex="-1"></a><span class="co"># Function to create pie chart</span></span>
<span id="cb23-189"><a href="#cb23-189" aria-hidden="true" tabindex="-1"></a>create_pie_chart <span class="ot">&lt;-</span> <span class="cf">function</span>(year) {</span>
<span id="cb23-190"><a href="#cb23-190" aria-hidden="true" tabindex="-1"></a>  sales_by_gender_year <span class="ot">&lt;-</span> sales_by_gender <span class="sc">%&gt;%</span></span>
<span id="cb23-191"><a href="#cb23-191" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(Year <span class="sc">==</span> year)</span>
<span id="cb23-192"><a href="#cb23-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-193"><a href="#cb23-193" aria-hidden="true" tabindex="-1"></a>  pie_chart <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(sales_by_gender_year, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">""</span>, <span class="at">y =</span> Total_Sales, <span class="at">fill =</span> Customer_Gender)) <span class="sc">+</span></span>
<span id="cb23-194"><a href="#cb23-194" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">width =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb23-195"><a href="#cb23-195" aria-hidden="true" tabindex="-1"></a>    <span class="fu">coord_polar</span>(<span class="st">"y"</span>, <span class="at">start =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb23-196"><a href="#cb23-196" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">fill =</span> <span class="st">"Customer Gender"</span>) <span class="sc">+</span></span>
<span id="cb23-197"><a href="#cb23-197" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_void</span>() <span class="sc">+</span></span>
<span id="cb23-198"><a href="#cb23-198" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>) <span class="sc">+</span></span>
<span id="cb23-199"><a href="#cb23-199" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> scales<span class="sc">::</span><span class="fu">percent</span>(Total_Sales <span class="sc">/</span> <span class="fu">sum</span>(Total_Sales))),</span>
<span id="cb23-200"><a href="#cb23-200" aria-hidden="true" tabindex="-1"></a>              <span class="at">position =</span> <span class="fu">position_stack</span>(<span class="at">vjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb23-201"><a href="#cb23-201" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggtitle</span>(<span class="fu">paste</span>(<span class="st">"Year:"</span>, year))</span>
<span id="cb23-202"><a href="#cb23-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-203"><a href="#cb23-203" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(pie_chart)</span>
<span id="cb23-204"><a href="#cb23-204" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb23-205"><a href="#cb23-205" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-206"><a href="#cb23-206" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a list of pie charts for each year</span></span>
<span id="cb23-207"><a href="#cb23-207" aria-hidden="true" tabindex="-1"></a>pie_charts <span class="ot">&lt;-</span> <span class="fu">lapply</span>(<span class="fu">unique</span>(sales_by_gender<span class="sc">$</span>Year), create_pie_chart)</span>
<span id="cb23-208"><a href="#cb23-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-209"><a href="#cb23-209" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine pie charts into a grid</span></span>
<span id="cb23-210"><a href="#cb23-210" aria-hidden="true" tabindex="-1"></a>grid <span class="ot">&lt;-</span> <span class="fu">grid.arrange</span>(<span class="at">grobs =</span> pie_charts, <span class="at">ncol =</span> <span class="dv">3</span>, <span class="at">top =</span> <span class="st">"Sales Distribution by Gender Over the Years"</span>)</span>
<span id="cb23-211"><a href="#cb23-211" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb23-212"><a href="#cb23-212" aria-hidden="true" tabindex="-1"></a>In the code above, we define a function create_pie_chart that takes a year as input and creates a pie chart representing the sales distribution by gender for that specific year.We then use lapply to apply the create_pie_chart function to each unique year in the sales_by_gender dataset, resulting in a list of pie charts for each year. Finally, we use the grid.arrange function from the gridExtra package to combine the pie charts into a grid layout with three columns (adjust the ncol parameter as desired). The resulting grid is stored in the grid variable.</span>
<span id="cb23-213"><a href="#cb23-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-214"><a href="#cb23-214" aria-hidden="true" tabindex="-1"></a>As we can see from the above grid of pie charts that the percentage of sales each year is almost the same for both males and females, it implies that there is a relatively equal distribution of sales between the two gender groups. This can suggest that the bikeshas similar appeal and demand among both male and female customers.</span>
<span id="cb23-215"><a href="#cb23-215" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-216"><a href="#cb23-216" aria-hidden="true" tabindex="-1"></a><span class="fu">## Profitability Analysis by Month:</span></span>
<span id="cb23-217"><a href="#cb23-217" aria-hidden="true" tabindex="-1"></a>The analysis delves into the profitability of bike sales by month. By calculating the average profit percentage for each month, we can identify any seasonal patterns or fluctuations in profitability. The visualization presents the average profitability over months, providing insights into the overall profitability trends throughout the year. Analyzing the graph helps us understand if there are any specific months that contribute significantly to profitability or if bike sales maintain consistent profitability across all months.</span>
<span id="cb23-218"><a href="#cb23-218" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-221"><a href="#cb23-221" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb23-222"><a href="#cb23-222" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate average profit percentage by month</span></span>
<span id="cb23-223"><a href="#cb23-223" aria-hidden="true" tabindex="-1"></a>profitability_month <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb23-224"><a href="#cb23-224" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Month) <span class="sc">%&gt;%</span></span>
<span id="cb23-225"><a href="#cb23-225" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Avg_Profit_Percentage =</span> <span class="fu">sum</span>(Profit) <span class="sc">/</span> <span class="fu">sum</span>(Cost)<span class="sc">*</span><span class="dv">100</span>)</span>
<span id="cb23-226"><a href="#cb23-226" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-227"><a href="#cb23-227" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot average profit percentage over months</span></span>
<span id="cb23-228"><a href="#cb23-228" aria-hidden="true" tabindex="-1"></a>month_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(profitability_month, <span class="fu">aes</span>(<span class="at">x =</span> Month, <span class="at">y =</span> Avg_Profit_Percentage)) <span class="sc">+</span></span>
<span id="cb23-229"><a href="#cb23-229" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb23-230"><a href="#cb23-230" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Average Profitability Over Months"</span>,</span>
<span id="cb23-231"><a href="#cb23-231" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Month"</span>,</span>
<span id="cb23-232"><a href="#cb23-232" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Average Profit Percentage"</span>) <span class="sc">+</span></span>
<span id="cb23-233"><a href="#cb23-233" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb23-234"><a href="#cb23-234" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-235"><a href="#cb23-235" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the plot</span></span>
<span id="cb23-236"><a href="#cb23-236" aria-hidden="true" tabindex="-1"></a>month_plot</span>
<span id="cb23-237"><a href="#cb23-237" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-238"><a href="#cb23-238" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot average profit percentage over months</span></span>
<span id="cb23-239"><a href="#cb23-239" aria-hidden="true" tabindex="-1"></a>month_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(profitability_month, <span class="fu">aes</span>(<span class="at">x =</span> Month, <span class="at">y =</span> Avg_Profit_Percentage)) <span class="sc">+</span></span>
<span id="cb23-240"><a href="#cb23-240" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb23-241"><a href="#cb23-241" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Average Profitability Over Months"</span>,</span>
<span id="cb23-242"><a href="#cb23-242" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Month"</span>,</span>
<span id="cb23-243"><a href="#cb23-243" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Average Profit Percentage"</span>) <span class="sc">+</span></span>
<span id="cb23-244"><a href="#cb23-244" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb23-245"><a href="#cb23-245" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-246"><a href="#cb23-246" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the plot</span></span>
<span id="cb23-247"><a href="#cb23-247" aria-hidden="true" tabindex="-1"></a>month_plot</span>
<span id="cb23-248"><a href="#cb23-248" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-249"><a href="#cb23-249" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb23-250"><a href="#cb23-250" aria-hidden="true" tabindex="-1"></a>In the code above, we group by month to calculate the average profit percentage for each month using summarise() function. Then, we create geom_bar() to create a bar plot to visualize the trend of average profit percentage over months. It can be seen that bike sales in overall are consistent around 60 percent profit for each month. Which implies that the bike sales are not largely effected by the month.</span>
<span id="cb23-251"><a href="#cb23-251" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-252"><a href="#cb23-252" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-253"><a href="#cb23-253" aria-hidden="true" tabindex="-1"></a><span class="fu">## Profitability Analysis among the countries:</span></span>
<span id="cb23-254"><a href="#cb23-254" aria-hidden="true" tabindex="-1"></a>The analysis investigates the profitability of bike sales among different countries. By calculating the average profitability for each country, we can identify variations in profitability levels and potentially uncover factors that contribute to these differences. The visualization utilizes a world map to represent the profitability by country. Each country is shaded according to its average profitability, allowing for easy identification of regions with higher or lower profitability. This information helps in understanding the geographic distribution of profitability and making informed decisions related to market targeting and expansion strategies.</span>
<span id="cb23-257"><a href="#cb23-257" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb23-258"><a href="#cb23-258" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate average profitability by country</span></span>
<span id="cb23-259"><a href="#cb23-259" aria-hidden="true" tabindex="-1"></a>profitability_country <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb23-260"><a href="#cb23-260" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Country) <span class="sc">%&gt;%</span></span>
<span id="cb23-261"><a href="#cb23-261" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Avg_Profitability =</span> <span class="fu">sum</span>(Profit)<span class="sc">/</span><span class="fu">sum</span>(Cost)<span class="sc">*</span><span class="dv">100</span>)</span>
<span id="cb23-262"><a href="#cb23-262" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-263"><a href="#cb23-263" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot world map based on profitability</span></span>
<span id="cb23-264"><a href="#cb23-264" aria-hidden="true" tabindex="-1"></a>world_map <span class="ot">&lt;-</span> <span class="fu">map_data</span>(<span class="st">"world"</span>)</span>
<span id="cb23-265"><a href="#cb23-265" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-266"><a href="#cb23-266" aria-hidden="true" tabindex="-1"></a>world_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb23-267"><a href="#cb23-267" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_map</span>(<span class="at">data =</span> world_map, <span class="at">map =</span> world_map,</span>
<span id="cb23-268"><a href="#cb23-268" aria-hidden="true" tabindex="-1"></a>           <span class="fu">aes</span>(<span class="at">x =</span> long, <span class="at">y =</span> lat, <span class="at">map_id =</span> region),</span>
<span id="cb23-269"><a href="#cb23-269" aria-hidden="true" tabindex="-1"></a>           <span class="at">fill =</span> <span class="st">"lightgray"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">size =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb23-270"><a href="#cb23-270" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_map</span>(<span class="at">data =</span> profitability_country, <span class="at">map =</span> world_map,</span>
<span id="cb23-271"><a href="#cb23-271" aria-hidden="true" tabindex="-1"></a>           <span class="fu">aes</span>(<span class="at">fill =</span> Avg_Profitability, <span class="at">map_id =</span> Country),</span>
<span id="cb23-272"><a href="#cb23-272" aria-hidden="true" tabindex="-1"></a>           <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">size =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb23-273"><a href="#cb23-273" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Profitability by Country"</span>,</span>
<span id="cb23-274"><a href="#cb23-274" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Profitability"</span>) <span class="sc">+</span></span>
<span id="cb23-275"><a href="#cb23-275" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_gradient</span>(<span class="at">low =</span> <span class="st">"lightblue"</span>, <span class="at">high =</span> <span class="st">"darkblue"</span>) <span class="sc">+</span></span>
<span id="cb23-276"><a href="#cb23-276" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb23-277"><a href="#cb23-277" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-278"><a href="#cb23-278" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the world map</span></span>
<span id="cb23-279"><a href="#cb23-279" aria-hidden="true" tabindex="-1"></a>world_plot</span>
<span id="cb23-280"><a href="#cb23-280" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-281"><a href="#cb23-281" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb23-282"><a href="#cb23-282" aria-hidden="true" tabindex="-1"></a>In this code, we first calculate the average profitability by country using summarise() function. Then, we use the map_data() function from the maps package to obtain the map data for the world. The geom_map() function is used twice to plot the world map: first to create a base map with light gray color, and then to overlay the profitability data using the fill aesthetic to represent the average profitability by country.</span>
<span id="cb23-283"><a href="#cb23-283" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-284"><a href="#cb23-284" aria-hidden="true" tabindex="-1"></a>By executing this code, you will see a world map that visualizes the profitability by country. Each country is shaded according to its average profitability, with a gradient scale from light blue to dark blue indicating the profitability levels. This map provides an overview of the profitability distribution across different countries, allowing for easy identification of regions with higher or lower profitability.</span>
<span id="cb23-285"><a href="#cb23-285" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-286"><a href="#cb23-286" aria-hidden="true" tabindex="-1"></a>On an average over the years we can see the Canada is having the highest profitability above 80 percent standing in the top while Australia making the least profitability around 50 percent. United states stands in the second place followed by United Kingdom and France.</span>
<span id="cb23-287"><a href="#cb23-287" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-288"><a href="#cb23-288" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-289"><a href="#cb23-289" aria-hidden="true" tabindex="-1"></a><span class="fu">## Multivariate Analysis: Age Group:</span></span>
<span id="cb23-290"><a href="#cb23-290" aria-hidden="true" tabindex="-1"></a>The analysis explores the relationship between age group and bike sales profitability and quantity. By grouping the data based on age groups, we calculate the average profitability and total quantity for each group. The visualization presents a scatter plot that represents the multivariate analysis, with the x-axis indicating the average profitability and the y-axis indicating the total quantity. Each data point is color-coded based on the age group. Analyzing the scatter plot helps us understand any patterns or correlations between age group, profitability, and quantity. This information can be useful in tailoring marketing strategies and product offerings to specific age groups and maximizing profitability.</span>
<span id="cb23-293"><a href="#cb23-293" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb23-294"><a href="#cb23-294" aria-hidden="true" tabindex="-1"></a><span class="co"># Multivariate analysis using Age_Group</span></span>
<span id="cb23-295"><a href="#cb23-295" aria-hidden="true" tabindex="-1"></a>age_group_analysis <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb23-296"><a href="#cb23-296" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Age_Group) <span class="sc">%&gt;%</span></span>
<span id="cb23-297"><a href="#cb23-297" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Avg_Profitability =</span> <span class="fu">sum</span>(Profit)<span class="sc">/</span><span class="fu">sum</span>(Cost)<span class="sc">*</span><span class="dv">100</span>,</span>
<span id="cb23-298"><a href="#cb23-298" aria-hidden="true" tabindex="-1"></a>            <span class="at">Total_Quantity =</span> <span class="fu">sum</span>(Order_Quantity))</span>
<span id="cb23-299"><a href="#cb23-299" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-300"><a href="#cb23-300" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting multivariate analysis</span></span>
<span id="cb23-301"><a href="#cb23-301" aria-hidden="true" tabindex="-1"></a>age_group_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(age_group_analysis, <span class="fu">aes</span>(<span class="at">x =</span> Avg_Profitability, <span class="at">y =</span> Total_Quantity, <span class="at">color =</span> Age_Group)) <span class="sc">+</span></span>
<span id="cb23-302"><a href="#cb23-302" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb23-303"><a href="#cb23-303" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Multivariate Analysis: Age Group"</span>,</span>
<span id="cb23-304"><a href="#cb23-304" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Average Profitability"</span>,</span>
<span id="cb23-305"><a href="#cb23-305" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Total Quantity"</span>,</span>
<span id="cb23-306"><a href="#cb23-306" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"Age Group"</span>) <span class="sc">+</span></span>
<span id="cb23-307"><a href="#cb23-307" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb23-308"><a href="#cb23-308" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-309"><a href="#cb23-309" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the plot</span></span>
<span id="cb23-310"><a href="#cb23-310" aria-hidden="true" tabindex="-1"></a>age_group_plot</span>
<span id="cb23-311"><a href="#cb23-311" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-312"><a href="#cb23-312" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb23-313"><a href="#cb23-313" aria-hidden="true" tabindex="-1"></a>In this code, we use the group_by() for each age group and summarise() to calculate the average profitability (Avg_Profitability) and the total quantity (Total_Quantity). Then, we use ggplot() and geom_point() to create a scatter plot where the x-axis represents the average profitability, the y-axis represents the total quantity, and the points are colored based on the age group. By executing this code, we will see a scatter plot that illustrates the multivariate analysis using the "Age_Group" variable. Each point represents an age group, and its position on the plot shows the average profitability and total quantity associated with that age group. This analysis helps identify any patterns or relationships between age groups and their impact on profitability and quantity.</span>
<span id="cb23-314"><a href="#cb23-314" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-315"><a href="#cb23-315" aria-hidden="true" tabindex="-1"></a>we can conclude form the plot that the order quantity is highest in the Adults aged between 35-64 followed by young adults between 25-34. The sales of bikes is least for the seniors above 64 age. Even though sales are less profitability of the seniors is high suggesting that seniors purchased costly bikes or bikes where profit margin is high.</span>
<span id="cb23-316"><a href="#cb23-316" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-317"><a href="#cb23-317" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-318"><a href="#cb23-318" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-319"><a href="#cb23-319" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-320"><a href="#cb23-320" aria-hidden="true" tabindex="-1"></a><span class="fu">## Mean Profit based on Age Group:</span></span>
<span id="cb23-321"><a href="#cb23-321" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-322"><a href="#cb23-322" aria-hidden="true" tabindex="-1"></a>The analysis examines the mean profit generated by bike sales across different countries and age groups. By calculating the average profit for each country and age group, we gain insights into the profitability levels based on these two variables. The visualization presents the mean profit by country and age group using a heatmap. Each cell in the heatmap represents the average profit for a specific combination of country and age group. The color intensity of each cell indicates the level of profitability, allowing for easy comparison and identification of countries and age groups with higher or lower mean profits. This information helps in understanding the profitability dynamics across different countries and age groups, enabling targeted marketing and business strategies.</span>
<span id="cb23-325"><a href="#cb23-325" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb23-326"><a href="#cb23-326" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(reshape2)</span>
<span id="cb23-327"><a href="#cb23-327" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb23-328"><a href="#cb23-328" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-329"><a href="#cb23-329" aria-hidden="true" tabindex="-1"></a><span class="co"># Reshape data for heatmap analysis</span></span>
<span id="cb23-330"><a href="#cb23-330" aria-hidden="true" tabindex="-1"></a>heatmap_data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb23-331"><a href="#cb23-331" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Country, Age_Group, Profit)</span>
<span id="cb23-332"><a href="#cb23-332" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-333"><a href="#cb23-333" aria-hidden="true" tabindex="-1"></a>heatmap_data <span class="ot">&lt;-</span> heatmap_data <span class="sc">%&gt;%</span></span>
<span id="cb23-334"><a href="#cb23-334" aria-hidden="true" tabindex="-1"></a>  <span class="fu">dcast</span>(Country <span class="sc">~</span> Age_Group, <span class="at">value.var =</span> <span class="st">"Profit"</span>, mean)</span>
<span id="cb23-335"><a href="#cb23-335" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-336"><a href="#cb23-336" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a heatmap to analyze Profit by Country and Age Group</span></span>
<span id="cb23-337"><a href="#cb23-337" aria-hidden="true" tabindex="-1"></a>heatmap_analysis <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="fu">melt</span>(heatmap_data, <span class="at">id.vars =</span> <span class="st">"Country"</span>), </span>
<span id="cb23-338"><a href="#cb23-338" aria-hidden="true" tabindex="-1"></a>                           <span class="fu">aes</span>(<span class="at">x =</span> variable, <span class="at">y =</span> Country, <span class="at">fill =</span> value)) <span class="sc">+</span></span>
<span id="cb23-339"><a href="#cb23-339" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_tile</span>() <span class="sc">+</span></span>
<span id="cb23-340"><a href="#cb23-340" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Profit by Country and Age Group (Heatmap)"</span>,</span>
<span id="cb23-341"><a href="#cb23-341" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Age Group"</span>,</span>
<span id="cb23-342"><a href="#cb23-342" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Country"</span>,</span>
<span id="cb23-343"><a href="#cb23-343" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Profit"</span>)</span>
<span id="cb23-344"><a href="#cb23-344" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-345"><a href="#cb23-345" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the heatmap analysis</span></span>
<span id="cb23-346"><a href="#cb23-346" aria-hidden="true" tabindex="-1"></a>heatmap_analysis</span>
<span id="cb23-347"><a href="#cb23-347" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-348"><a href="#cb23-348" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb23-349"><a href="#cb23-349" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-350"><a href="#cb23-350" aria-hidden="true" tabindex="-1"></a>This code reshapes the data and creates a heatmap to analyze the Profit by Country and Age Group. The "heatmap_data" dataframe is created by selecting the "Country," "Age_Group," and "Profit" columns from the "data" dataset. The "heatmap_data" dataframe is further modified using the dcast() function from the "reshape2" library. The dcast() function reshapes the data, pivoting it to have "Country" as rows, "Age_Group" as columns, and the average "Profit" as the values in the cells.The resulting reshaped dataframe, "heatmap_data," is then used to create a new ggplot object called "heatmap_analysis." The heatmap provides a visual representation of the Profit values per unit, with colors indicating the intensity of Profit for different combinations of Country and Age Group.</span>
<span id="cb23-351"><a href="#cb23-351" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-352"><a href="#cb23-352" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-353"><a href="#cb23-353" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-354"><a href="#cb23-354" aria-hidden="true" tabindex="-1"></a><span class="fu">## Monthly Sales across Years:</span></span>
<span id="cb23-355"><a href="#cb23-355" aria-hidden="true" tabindex="-1"></a>The analysis focuses on tracking the monthly sales performance over the years. By examining the sales figures for each month, we can identify any seasonal patterns, trends, or fluctuations in sales. The visualization presents the monthly sales data using a bar graph, where each bar represents the sales for a specific month. The height of each bar indicates the sales amount, allowing for easy comparison between different months and years. Analyzing the bar graph helps us understand the overall sales trends over time and can provide insights for forecasting future sales, identifying peak periods, and optimizing inventory management.</span>
<span id="cb23-356"><a href="#cb23-356" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-359"><a href="#cb23-359" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb23-360"><a href="#cb23-360" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate monthly sales</span></span>
<span id="cb23-361"><a href="#cb23-361" aria-hidden="true" tabindex="-1"></a>monthly_sales <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb23-362"><a href="#cb23-362" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Month, Year) <span class="sc">%&gt;%</span></span>
<span id="cb23-363"><a href="#cb23-363" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Total_Sales =</span> <span class="fu">sum</span>(Revenue)) <span class="sc">%&gt;%</span> </span>
<span id="cb23-364"><a href="#cb23-364" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(Month))</span>
<span id="cb23-365"><a href="#cb23-365" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-366"><a href="#cb23-366" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a bar plot for monthly sales</span></span>
<span id="cb23-367"><a href="#cb23-367" aria-hidden="true" tabindex="-1"></a>monthly_sales_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(monthly_sales, <span class="fu">aes</span>(<span class="at">x =</span> Month, <span class="at">y =</span> Total_Sales, <span class="at">fill =</span> Year)) <span class="sc">+</span></span>
<span id="cb23-368"><a href="#cb23-368" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span></span>
<span id="cb23-369"><a href="#cb23-369" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Monthly Sales"</span>,</span>
<span id="cb23-370"><a href="#cb23-370" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Month"</span>,</span>
<span id="cb23-371"><a href="#cb23-371" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Total Sales"</span>,</span>
<span id="cb23-372"><a href="#cb23-372" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Year"</span>) <span class="sc">+</span></span>
<span id="cb23-373"><a href="#cb23-373" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()<span class="sc">+</span></span>
<span id="cb23-374"><a href="#cb23-374" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">labels =</span> <span class="cf">function</span>(x) <span class="fu">substr</span>(x, <span class="dv">1</span>, <span class="dv">3</span>))</span>
<span id="cb23-375"><a href="#cb23-375" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-376"><a href="#cb23-376" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the monthly sales bar plot</span></span>
<span id="cb23-377"><a href="#cb23-377" aria-hidden="true" tabindex="-1"></a>monthly_sales_plot</span>
<span id="cb23-378"><a href="#cb23-378" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb23-379"><a href="#cb23-379" aria-hidden="true" tabindex="-1"></a>By grouping the data by month and year and summarizing the revenue, the code generates a new data frame that provides the total sales for each unique combination of month and year in the original dataset. In the  plot, I used the substr() function within the scale_x_discrete() function to modify the x-axis labels. The substr(x, 1, 3) extracts the first three letters of each label, effectively truncating the month names. A bar plot is then created to visualize the monthly sales, with each bar representing the total sales for a specific month and year. The bars are color-coded based on the year, providing a visual comparison between different years.</span>
<span id="cb23-380"><a href="#cb23-380" aria-hidden="true" tabindex="-1"></a>In 2016 Janaury to June is the peak selling season for the bikes on contrast in 2015 the sales are peak during July to August. In 2011 the sales are same overall through January to December and it is the least sales year out of all the years from 2011 to 2016.</span>
<span id="cb23-381"><a href="#cb23-381" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-382"><a href="#cb23-382" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-383"><a href="#cb23-383" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-384"><a href="#cb23-384" aria-hidden="true" tabindex="-1"></a><span class="fu">## Seasonal sales based on country:</span></span>
<span id="cb23-385"><a href="#cb23-385" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-386"><a href="#cb23-386" aria-hidden="true" tabindex="-1"></a>The analysis examines the seasonal sales patterns of the top 3 bike products across different countries. By analyzing the sales data for each season and country, we can identify variations in demand and popularity throughout the year. The visualization utilizes a boxplot to represent the seasonal sales for each country and bike product. The boxplot provides insights into the distribution of sales, including the median, quartiles, and any outliers. By comparing the boxplots across countries and bikes, we can identify countries with high or low sales during specific seasons for the top 3 bikes. </span>
<span id="cb23-389"><a href="#cb23-389" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb23-390"><a href="#cb23-390" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter the data for the top 3 bikes based on overall sales</span></span>
<span id="cb23-391"><a href="#cb23-391" aria-hidden="true" tabindex="-1"></a>top3_bikes <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb23-392"><a href="#cb23-392" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Product) <span class="sc">%&gt;%</span></span>
<span id="cb23-393"><a href="#cb23-393" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Total_Sales =</span> <span class="fu">sum</span>(Revenue)) <span class="sc">%&gt;%</span></span>
<span id="cb23-394"><a href="#cb23-394" aria-hidden="true" tabindex="-1"></a>  <span class="fu">top_n</span>(<span class="dv">3</span>, Total_Sales) <span class="sc">%&gt;%</span></span>
<span id="cb23-395"><a href="#cb23-395" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Product)</span>
<span id="cb23-396"><a href="#cb23-396" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-397"><a href="#cb23-397" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a new column for seasons based on the date</span></span>
<span id="cb23-398"><a href="#cb23-398" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>Season <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(<span class="fu">format</span>(data<span class="sc">$</span>Date, <span class="st">"%m"</span>) <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"12"</span>, <span class="st">"01"</span>, <span class="st">"02"</span>), <span class="st">"Winter"</span>,</span>
<span id="cb23-399"><a href="#cb23-399" aria-hidden="true" tabindex="-1"></a>                      <span class="fu">ifelse</span>(<span class="fu">format</span>(data<span class="sc">$</span>Date, <span class="st">"%m"</span>) <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"03"</span>, <span class="st">"04"</span>, <span class="st">"05"</span>), <span class="st">"Spring"</span>,</span>
<span id="cb23-400"><a href="#cb23-400" aria-hidden="true" tabindex="-1"></a>                             <span class="fu">ifelse</span>(<span class="fu">format</span>(data<span class="sc">$</span>Date, <span class="st">"%m"</span>) <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"06"</span>, <span class="st">"07"</span>, <span class="st">"08"</span>), <span class="st">"Summer"</span>, <span class="st">"Autumn"</span>)))</span>
<span id="cb23-401"><a href="#cb23-401" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-402"><a href="#cb23-402" aria-hidden="true" tabindex="-1"></a><span class="co"># Group the data by seasons, country, and bike product</span></span>
<span id="cb23-403"><a href="#cb23-403" aria-hidden="true" tabindex="-1"></a>grouped_data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb23-404"><a href="#cb23-404" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Product <span class="sc">%in%</span> top3_bikes<span class="sc">$</span>Product) <span class="sc">%&gt;%</span></span>
<span id="cb23-405"><a href="#cb23-405" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Season, Country, Product) <span class="sc">%&gt;%</span></span>
<span id="cb23-406"><a href="#cb23-406" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Total_Revenue =</span> <span class="fu">sum</span>(Revenue))</span>
<span id="cb23-407"><a href="#cb23-407" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-408"><a href="#cb23-408" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter the data to include only the top 3 bikes based on total revenue</span></span>
<span id="cb23-409"><a href="#cb23-409" aria-hidden="true" tabindex="-1"></a>top3_grouped_data <span class="ot">&lt;-</span> grouped_data <span class="sc">%&gt;%</span></span>
<span id="cb23-410"><a href="#cb23-410" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Season, Country) <span class="sc">%&gt;%</span></span>
<span id="cb23-411"><a href="#cb23-411" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(Total_Revenue)) <span class="sc">%&gt;%</span></span>
<span id="cb23-412"><a href="#cb23-412" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>)</span>
<span id="cb23-413"><a href="#cb23-413" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-414"><a href="#cb23-414" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a box plot to visualize the revenue distribution for each season, country, and bike</span></span>
<span id="cb23-415"><a href="#cb23-415" aria-hidden="true" tabindex="-1"></a>boxplot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(top3_grouped_data, <span class="fu">aes</span>(<span class="at">x =</span> Season, <span class="at">y =</span> Total_Revenue, <span class="at">fill =</span> Country)) <span class="sc">+</span></span>
<span id="cb23-416"><a href="#cb23-416" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb23-417"><a href="#cb23-417" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Revenue Distribution for Top 3 Bikes by Season and Country"</span>,</span>
<span id="cb23-418"><a href="#cb23-418" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Season"</span>,</span>
<span id="cb23-419"><a href="#cb23-419" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Total Revenue"</span>,</span>
<span id="cb23-420"><a href="#cb23-420" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Country"</span>) <span class="sc">+</span></span>
<span id="cb23-421"><a href="#cb23-421" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb23-422"><a href="#cb23-422" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-423"><a href="#cb23-423" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the box plot</span></span>
<span id="cb23-424"><a href="#cb23-424" aria-hidden="true" tabindex="-1"></a>boxplot</span>
<span id="cb23-425"><a href="#cb23-425" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-426"><a href="#cb23-426" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb23-427"><a href="#cb23-427" aria-hidden="true" tabindex="-1"></a>The format(data$Date, "%m") extracts the month from the "Date" column using the format() function with the "%m" format specifier. This will return a two-digit representation of the month (e.g., "01" for January, "02" for February, etc.). %in% c("12", "01", "02") checks if the extracted month value is equal to any of the values in the vector "c("12", "01", "02")". If it matches any of these values, it indicates that the month falls within the winter season. similarly for other seasons used ifelse() statement.</span>
<span id="cb23-428"><a href="#cb23-428" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-429"><a href="#cb23-429" aria-hidden="true" tabindex="-1"></a>After the seasons extracted from the date column, created a box plot to visualize the revenue distribution across different seasons. Each box plot represents the revenue distribution for a specific season, providing insights into the seasonal variations in sales. In each box plot top 3 sales are considered for the season showing how closely the competition is present in the market. In Australia, If we see in the winter season top bike in the sales is has no close competition with others. For the Canada there is always a close competition in the sales.</span>
<span id="cb23-430"><a href="#cb23-430" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-431"><a href="#cb23-431" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-432"><a href="#cb23-432" aria-hidden="true" tabindex="-1"></a><span class="fu"># Conclusion</span></span>
<span id="cb23-433"><a href="#cb23-433" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-434"><a href="#cb23-434" aria-hidden="true" tabindex="-1"></a>In this analysis, we explored a comprehensive dataset on bike sales collected by Global Bike Inc. The dataset provided valuable insights into sales transactions, customer demographics, and profitability across multiple countries. By addressing a set of research questions, we gained insights into the sales performance, customer preferences, and profitability patterns within the bike industry.</span>
<span id="cb23-435"><a href="#cb23-435" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-436"><a href="#cb23-436" aria-hidden="true" tabindex="-1"></a>Based on our analysis, we found the following key findings:</span>
<span id="cb23-437"><a href="#cb23-437" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-438"><a href="#cb23-438" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**Top-selling Bike Models and Sales Trends**: We identified the top-selling bike models and observed their sales trends over the years. The Road 150 Red, 62 model emerged as a consistent top performer, generating significant revenue in multiple years.</span>
<span id="cb23-439"><a href="#cb23-439" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-440"><a href="#cb23-440" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**Gender Distribution and Preferences**: The analysis of gender distribution among bike customers revealed a relatively equal distribution of sales between male and female customers. This suggests that the bike products have similar appeal and demand among both genders.</span>
<span id="cb23-441"><a href="#cb23-441" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-442"><a href="#cb23-442" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**Profitability Variation by Month**: We examined the profitability variation by month and found that bike sales maintained a consistent profitability level around 60 percent throughout the year. This indicates that bike sales are not significantly influenced by the month.</span>
<span id="cb23-443"><a href="#cb23-443" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-444"><a href="#cb23-444" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>**Profitability Variation Among Countries**: We analyzed the profitability across different countries and identified variations in profitability levels. Canada stood out as the highest-profitability country, while Australia had the lowest profitability. The United States, the United Kingdom, and France also exhibited notable profitability levels.</span>
<span id="cb23-445"><a href="#cb23-445" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-446"><a href="#cb23-446" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>**Age-specific Preferences**: The multivariate analysis revealed insights into age-specific preferences. We observed that the youth and young adult age groups showed higher average profitability, indicating potential opportunities for targeted marketing and product development.</span>
<span id="cb23-447"><a href="#cb23-447" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-448"><a href="#cb23-448" aria-hidden="true" tabindex="-1"></a>These findings provide valuable insights for decision-making processes related to marketing strategies, inventory management, and product development within the bike industry. By understanding the top-selling models, gender distribution, profitability patterns, and age-specific preferences, businesses can make data-driven decisions to improve performance and enhance customer satisfaction.</span>
<span id="cb23-449"><a href="#cb23-449" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-450"><a href="#cb23-450" aria-hidden="true" tabindex="-1"></a>It is important to note that this analysis is based on the available dataset and its limitations. Further research and analysis can be conducted to delve deeper into specific aspects of bike sales, such as customer segmentation, marketing campaign effectiveness, and competitive analysis.</span>
<span id="cb23-451"><a href="#cb23-451" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-452"><a href="#cb23-452" aria-hidden="true" tabindex="-1"></a>Overall, this analysis offers a comprehensive understanding of bike sales, customer preferences, and profitability patterns, enabling businesses to make informed decisions and drive growth in the bike industry.</span>
<span id="cb23-453"><a href="#cb23-453" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-454"><a href="#cb23-454" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-455"><a href="#cb23-455" aria-hidden="true" tabindex="-1"></a><span class="fu"># Bibliography</span></span>
<span id="cb23-456"><a href="#cb23-456" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-457"><a href="#cb23-457" aria-hidden="true" tabindex="-1"></a>Bike sales Dataset (2011-2016) - https://www.kaggle.com/datasets/sadiqshah/bike-sales-in-europe?datasetId=889310&amp;language=R</span>
<span id="cb23-458"><a href="#cb23-458" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-459"><a href="#cb23-459" aria-hidden="true" tabindex="-1"></a>R Language as programming language</span>
<span id="cb23-460"><a href="#cb23-460" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-461"><a href="#cb23-461" aria-hidden="true" tabindex="-1"></a>Wickham, H., &amp; Grolemund, G. (2016). *R for data science: Visualize, model, transform, tidy, and import data*. OReilly Media.</span>
<span id="cb23-462"><a href="#cb23-462" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-463"><a href="#cb23-463" aria-hidden="true" tabindex="-1"></a>The R Graph Gallery-https://r-graph-gallery.com/\</span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>