---
title: "Challenge 2"
author: "Janani Natarajan"
desription: "Data wrangling: using group() and summarise()"
date: "04/30/2022"
format:
  html:
    toc: true
    code-fold: true
    code-copy: true
    code-tools: true
categories:
  - challenge_2
  - railroads
  - faostat
  - hotel_bookings
---

```{r}
#| label: setup
#| warning: false
#| message: false

library(tidyverse)

knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```

```{r}
data <- read_csv("_data/railroad_2012_clean_county.csv")
print(data,show_col_types = FALSE)
```

```{r}
dim(data)
```

```{r}
str(data)
```

```{r}
df<-select(data,state, total_employees)
View(df)
```

```{r}
df<- data %>% 
  filter(county == "CHILTON")
print(df)
```

```{r}
data %>% 
  group_by(state) %>% 
  summarise(MeanEmployees = mean(total_employees, na.rm=TRUE), StandardDeviation = sd(total_employees, na.rm = TRUE))
```

```{r}
data %>% 
  group_by(county) %>% 
  summarise(MeanEmployees = mean(total_employees, na.rm=TRUE), StandardDeviation = sd(total_employees, na.rm = TRUE))
```

```{r}
data %>% 
  group_by(state) %>% 
  summarise(CountOfCounty = n())
```
