---
title: "Challenge 1 Instructions"
author: "Meredith Rolfe"
description: "Reading in data and creating a post"
date: "08/15/2022"
format:
  html:
    toc: true
    code-fold: true
    code-copy: true
    code-tools: true
categories:
  - challenge_1
  - railroads
  - faostat
  - wildbirds
---

```{r}
#| label: setup
#| warning: false
#| message: false

library(tidyverse)

knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```

```{r}
library(readr)
```

```{r}
railroad <- read.csv('_data/railroad_2012_clean_county.csv')

```

```{r}
dim(railroad)
```

```{r}
colnames(railroad)
```

```{r}
print("Top rows of the data ")
head(railroad)
```

```{r}
print("Total number of employees in the states ordered by the count:")
```

```{r}
railroad %>%
  group_by(state) %>%
  summarize(state_total = sum(total_employees))  %>%
  select(state, state_total)  %>%
  arrange(desc(state_total))
```

```{r}
print("The counties with employees greater than 1000")
```

```{r}
railroad %>%
  filter(total_employees > 1000)  %>%
  select(state, county, total_employees) %>%
  arrange(desc(total_employees))
```
