--- 
title: "Challenge 1"
author: "Khadijat Adeleye"
desription: "Analysing Animal weight data"
date: "02/26/2023"
format:
  html:
    toc: true
    code-fold: true
    code-copy: true
    code-tools: true
categories:
  - hw1
  - challenge1
  - KhadijatAdeleye
  - animal_weight
  - ggplot2
---

##Reading in data
```{r}
df <- read.csv("_data\\animal_weight.csv")
```
#Description of Datasets
The data set is about the  weight of 17 animals in nine continents. There are 9 variables as can be seen using the colnames command-data. The weight of animals are continuous variable. The data was gathered from several continents as seen in the table.
```{r}
data %>%  group_by (IPCC.Area)  %>% select(ends_with("buffaloes"))
```
# Total Buffaloes across the 9 continent
```{r}
data%>%select(Buffaloes)%>%sum()
 sumofrow <- data%>%filter(IPCC.Area=="Africa")%>%sum()
sumofrow
buffalo<-data%>%select(Buffaloes)%>%sum()
```
```{r}
sumrow<-
data%>%select("Cattle...dairy":"Llamas")%>%rowSums()
sumrow
#data%>%!(select("IPCC.Area"))%>%rowSums()
```
```{r}
data%>%select(-c(IPCC.Area))%>%rowSums()
colnames(data)
```
```{r}
table(data%>%select(-c(IPCC.Area))%>%rowSums())
```
```{r}
prop.table(table(data))
```