---
title: "Challenge 3 Instructions"
author: "Khadijat Adeleye"
desription: "Tidy Data: Pivoting"
date: "03/19/2023"
format:
  html:
    toc: true
    code-fold: true
    code-copy: true
    code-tools: true
categories:
  - challenge_3
  - animal_weights
  - eggs
  - australian_marriage
  - usa_households
  - sce_labor
---

```{r}
#| label: setup
#| warning: false
#| message: false

library(tidyverse)

knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```

## Challenge Overview

```{r}
data<-read.csv("_data\\animal_weight.csv")
view(data)
nrow(data)
ncol(data)
```
```{r}
list(colnames(data))
```
###  describe the data
The data set contains 9 observations with 17 variables from different continents.

```{r}
nrow(data) * (ncol(data)-3)

```

Any additional comments?
Expected column is 126
## Pivot the Data

```{r}

data<-pivot_longer(data, col = c(Turkeys,Ducks),
                 names_to="Animal_name",
                 values_to = "animal_value")

```

```{r}
data
```
The number of row has increased to 18
```{r}
nrow(data)
```

```{r}
ncol(data)
```

