<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.427">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Kris Smole">
<meta name="dcterms.date" content="2023-03-01">

<title>Challenge 2 Using dataset ‘railroads’</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../images/DACSS_Round_Network.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<meta name="twitter:title" content="Challenge 2 Using dataset ‘railroads’">
<meta name="twitter:description" content="">
<meta name="twitter:creator" content="@UMassDACSS">
<meta name="twitter:site" content="@UMassDACSS">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../images/UMass White Wordmark Horiz.png" alt="" class="navbar-logo">
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://github.com/DACSS" rel="" target="">
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html" rel="" target="">
 <span class="menu-text">Contributors</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://umass.edu/sbs/dacss" rel="" target="">
 <span class="menu-text">DACSS</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/DACSS" rel="" target=""><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#description-of-the-dataset-railroads" id="toc-description-of-the-dataset-railroads" class="nav-link active" data-scroll-target="#description-of-the-dataset-railroads">Description of the dataset ‘Railroads’</a></li>
  <li><a href="#grouped-summary-statistics---looking-at-our-dataset-by-state-totals" id="toc-grouped-summary-statistics---looking-at-our-dataset-by-state-totals" class="nav-link" data-scroll-target="#grouped-summary-statistics---looking-at-our-dataset-by-state-totals">Grouped Summary Statistics - Looking at our Dataset by State totals</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">CONCLUSION</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Challenge 2 Using dataset ‘railroads’</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
  <div class="quarto-categories">
    <div class="quarto-category">challenge_2</div>
    <div class="quarto-category">railroads</div>
    <div class="quarto-category">faostat</div>
    <div class="quarto-category">hotel_bookings</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Kris Smole </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 1, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">TRUE</span>, <span class="at">warning=</span><span class="cn">FALSE</span>, <span class="at">message=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="description-of-the-dataset-railroads" class="level2">
<h2 class="anchored" data-anchor-id="description-of-the-dataset-railroads">Description of the dataset ‘Railroads’</h2>
<p>Railroads dataset contains distinct observations of total employee counts, by counties within US states/principalities.</p>
<p>Let’s review some of the basics of this dataset: it’s overall size, its content in its columns and rows (which are the variables and observations, respectively, and how this dataset might have been compiled. We can do this by looking at the dataset itself:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>railroad <span class="ot">&lt;-</span><span class="fu">read_csv</span>(<span class="st">"_data/railroad_2012_clean_county.csv"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(modeest)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(railroad, state, county, total_employees)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2,930 × 3
   state county               total_employees
   &lt;chr&gt; &lt;chr&gt;                          &lt;dbl&gt;
 1 AE    APO                                2
 2 AK    ANCHORAGE                          7
 3 AK    FAIRBANKS NORTH STAR               2
 4 AK    JUNEAU                             3
 5 AK    MATANUSKA-SUSITNA                  2
 6 AK    SITKA                              1
 7 AK    SKAGWAY MUNICIPALITY              88
 8 AL    AUTAUGA                          102
 9 AL    BALDWIN                          143
10 AL    BARBOUR                            1
# … with 2,920 more rows</code></pre>
</div>
</div>
<p>We can see in the results above, and confirmed in the results showing the entire dataframe contained in the file, that this dataset contains a count of rows (2930) and columns (3).</p>
<p>We also see in the left-most column, familiar state abbreviations, as well as some other abbreviations such as AE, AP, and DC, representing 53 state and military/governmental principalities of the US. Next column to the right, we see specific county names that relate to the identified states and principalities. The right-most column provides the total count of employees for the stated county and state.</p>
<p>The observations of this dataset are the rows of data, which record the number of employees within each county that the railroad operates, while the variable is the county and state combination for each railroad employment site.</p>
<p>How many counties have distinct names within this dataset?</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>railroad<span class="sc">%&gt;%</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(county)<span class="sc">%&gt;%</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">n_distinct</span>(.)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1709</code></pre>
</div>
</div>
<p>The answer of 1709 distinct county names indicates that some county names repeat across various states, because the count of county names are not equal to 2930, the total number of distinct observations by counties within states/principalities. We are able to use a function named “distinct” on the county name column to find this answer.</p>
<p>So, we know this dataset represents information about a railroad or railroads that operate in the stated counties of the United States. In terms of the source of the data, It is likely the data was compiled by an individual railroad company, or some trade or regulatory or governmental body about one railroad, or about several railroads. The data does not include definitive data to know exactly which of these possibilities are true. Unless or until we know the exact source of the data, we can make suppositions through verifying the employee counts and locations of operations by railroad(s), if relevant and important to identify the specific data source.</p>
<p>Although the dataframe within the dataset file is a solid starting point, the dataframe in its current state contains minimalcomparative or analytical information about the employees of the railroad(s) working within various counties across the states/principalities. Thankfully, we have the tools to use the existing data in the dataset and find more information using sorting, arithmetic and statistical calculations.</p>
<p>Let’s start with some basic descriptive statistics of this dataset.</p>
<p>First, we see the total of all employees by county and state.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summarize</span>(railroad,<span class="fu">sum</span>(<span class="st">`</span><span class="at">total_employees</span><span class="st">`</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  `sum(total_employees)`
                   &lt;dbl&gt;
1                 255432</code></pre>
</div>
</div>
<p>The overall total count of employees for the railroad(s) in the counties and states of the US in this dataframe is 255,432 employees.</p>
<p>Below is the mean, or average count of railroad employees by county.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summarize</span>(railroad,<span class="fu">mean</span>(<span class="st">`</span><span class="at">total_employees</span><span class="st">`</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  `mean(total_employees)`
                    &lt;dbl&gt;
1                    87.2</code></pre>
</div>
</div>
<p>The counties of the US states in which these railroad operations exist have an average employee count of 87.2 employees. Because we speak in terms of individuals, we will use a whole number of 87 as the approximate average count of employees by county.</p>
<p>Next is the median of railroad employees by county.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summarize</span>(railroad, <span class="fu">median</span>(<span class="st">`</span><span class="at">total_employees</span><span class="st">`</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  `median(total_employees)`
                      &lt;dbl&gt;
1                        21</code></pre>
</div>
</div>
<p>The counties of the US states in which these railroad operations exist have a median employee count of 21 employees. This statistical calculation results in a whole number because the median is the most frequently occurring observation within the dataframe, not a calculation per se, as the mean/average is.</p>
<p>And, finally, we have the mode of railroad employees by county</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>mode<span class="ot">=</span><span class="fu">mfv</span>(railroad<span class="sc">$</span>total_employees)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span> (mode)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
<p>The counties of the US states in which these railroad operations exist have a mode of employee count of 1 employee. This statistical result in a whole number, like the result for the median, because the mode and median are the statistical occurrences of actual dataframe observations, not a calculation per se. The mode is the most frequently occurring observation within the dataframe. Remember this as we move forward to view the standard deviation and quantiles of this dataset.</p>
<p>Now we’ll look at the lowest employee count among the counties. The mode tells us that the count of 1 employee is the most frequent count of employees by county, so we have a good guess as to the lowest count of employees among the counties (ie: 1).</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summarize</span>(railroad, <span class="fu">min</span>(<span class="st">`</span><span class="at">total_employees</span><span class="st">`</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  `min(total_employees)`
                   &lt;dbl&gt;
1                      1</code></pre>
</div>
</div>
<p>We see the lowest employee count among the counties is 1 employee.</p>
<p>We want to see the highest count of employees among the counties.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summarize</span>(railroad, <span class="fu">max</span>(<span class="st">`</span><span class="at">total_employees</span><span class="st">`</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  `max(total_employees)`
                   &lt;dbl&gt;
1                   8207</code></pre>
</div>
</div>
<p>The highest count of employees among the counties is 8,207. We knew that of the 2930 counties, some of them had to have larger numbers of employee counts to get to an overall employee total count of 255,432, since employee counts of one would not bring us to 255,432 over 2930 counties if the employee count was 87, or 21, as we saw in the mean and median of the dataset.</p>
<p>In a bit, we will see in the quantiles and standard deviation of the dataframe that the employee count of 1 has many occurrences within the dataframe, as previously indicated by the mode. With over 255,432 employees across 53 states/principalities, a mode of 1, an average of 87, and a median of 21, and the largest county count of employees of 8,207, the dispersion of employee counts will likely be skewed closer to employee counts of 1 than to the employee count of 8,207. Does that mean more counties have employee counts of less than 87 than employee counts of 88 or more? Yes.</p>
<p>What are the quantiles of the dataframe?</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summarize</span>(railroad,<span class="fu">quantile</span>(<span class="st">`</span><span class="at">total_employees</span><span class="st">`</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 1
  `quantile(total_employees)`
                        &lt;dbl&gt;
1                           1
2                           7
3                          21
4                          65
5                        8207</code></pre>
</div>
</div>
<p>The 1st quantile of the count of employees by county begins at 1, and ends with 6.</p>
<p>The 2nd quantile of the count of employees by county begins at 7 and ends with 20.</p>
<p>The 3rd quantile of the count of employees by county begins at 21 and ends with 64.</p>
<p>The 4th quantile of the count of employees by county begins at 65 and ends with 8207.</p>
<p>We are seeing that the dataset has some very large counts of employees, and some very low counts of employees. From what we see in the ranges of employee counts in the quantile output, the 4th quantile of counts of employees by county has a very large range of employee counts, from 65 employees to 8,207 employees. The range of 65 employees to 8,207 employees is a very large range of employee counts, given the other 3 quantiles of occurrences of employee counts by county span only the count of 1 to the count of 64. The 4th quantile requires more examination, that will likely be best done through creating a new dataframe of only the 4th quantile to allow statistical calculations to examine the larger range of the 4th quantile, to provide more meaningful analysis of all of the original dataframe, since the first 3 quantiles have reltaively little variation in employee counts in comparison to the 4th quantile.</p>
<p>This makes us curious about the standard deviation of the individual counts of employees by county. Like the name conveys, the standard deviation ‘standardizes’ the variance of each observation’s difference from the dataset mean of 87.17816. Or, said differently, the standard deviation helps make the variances of each employee count from the employee mean more comparable.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(railroad,<span class="st">`</span><span class="at">total_employees</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2,930 × 1
   total_employees
             &lt;dbl&gt;
 1               2
 2               7
 3               2
 4               3
 5               2
 6               1
 7              88
 8             102
 9             143
10               1
# … with 2,920 more rows</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summarize</span>(railroad,<span class="fu">sd</span>(<span class="st">`</span><span class="at">total_employees</span><span class="st">`</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  `sd(total_employees)`
                  &lt;dbl&gt;
1                  284.</code></pre>
</div>
</div>
<p>We see the standard deviation of all employee counts by county in the dataset is 284 from the mean of 87.2. Standard deviation is different than the description of the variance between each employee count observation and the mean of the overall dataset employee count. Each employee count varies, or has a variance from the mean that is different from 283.6359. The standard deviation is a mathematical standarizing of the variances to help make the collection of variances more general, and more simple to understand. Examining the 4th quantile independently of the first 3 quantiles will provide a different standard deviation, mean, median, mode and set of quantiles. This may lead to yet another, new, separate dataframe so as to examine the resulting new quantiles, in pursuit of finding a more evenly distributed set of quantiles - quantiles that might approximate a normal distribution. That’s ahead in our work…</p>
</section>
<section id="grouped-summary-statistics---looking-at-our-dataset-by-state-totals" class="level2">
<h2 class="anchored" data-anchor-id="grouped-summary-statistics---looking-at-our-dataset-by-state-totals">Grouped Summary Statistics - Looking at our Dataset by State totals</h2>
<p>Often, viewers of data like this dataset, want to know information by state, which this dataset doesn’t provide in summary. We can now look at some descriptive statistical measures of the states. We look at the highest employee count by state, the lowest employee count by state, the mean (or average) of each state in alphbetical order, and median of each state in alphbetical order.</p>
<p>Below we have the number of employees summarizing the county employee counts of each state, in alphabetical order of state.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>railroad<span class="sc">%&gt;%</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(state)<span class="sc">%&gt;%</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span> (<span class="st">`</span><span class="at">total_employees</span><span class="st">`</span>)<span class="sc">%&gt;%</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize_all</span>(sum, <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 53 × 2
   state total_employees
   &lt;chr&gt;           &lt;dbl&gt;
 1 AE                  2
 2 AK                103
 3 AL               4257
 4 AP                  1
 5 AR               3871
 6 AZ               3153
 7 CA              13137
 8 CO               3650
 9 CT               2592
10 DC                279
# … with 43 more rows</code></pre>
</div>
</div>
<p>Knowing the states with the highest number of employees and the lowest number of employees might be of interest. What follows are those two summarized listings of the highest and lowest counts of employees among the counties by state, in alphabetic order of states. A rank order of the highest and lowest employee counts is in the works for the future.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>railroad<span class="sc">%&gt;%</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(state)<span class="sc">%&gt;%</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span> (<span class="st">`</span><span class="at">total_employees</span><span class="st">`</span>)<span class="sc">%&gt;%</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize_all</span>(max, <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 53 × 2
   state total_employees
   &lt;chr&gt;           &lt;dbl&gt;
 1 AE                  2
 2 AK                 88
 3 AL                990
 4 AP                  1
 5 AR                972
 6 AZ                749
 7 CA               2888
 8 CO                553
 9 CT               1561
10 DC                279
# … with 43 more rows</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>railroad<span class="sc">%&gt;%</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(state)<span class="sc">%&gt;%</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span> (<span class="st">`</span><span class="at">total_employees</span><span class="st">`</span>)<span class="sc">%&gt;%</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize_all</span>(min, <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 53 × 2
   state total_employees
   &lt;chr&gt;           &lt;dbl&gt;
 1 AE                  2
 2 AK                  1
 3 AL                  1
 4 AP                  1
 5 AR                  1
 6 AZ                  3
 7 CA                  1
 8 CO                  1
 9 CT                 26
10 DC                279
# … with 43 more rows</code></pre>
</div>
</div>
<p>The mean of each state’s county employee counts, or, the average number of employees of all the counties within each state. The list is in alphabetical order of the states.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>railroad<span class="sc">%&gt;%</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(state)<span class="sc">%&gt;%</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span> (<span class="st">`</span><span class="at">total_employees</span><span class="st">`</span>)<span class="sc">%&gt;%</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize_all</span>(mean, <span class="at">na.rm=</span><span class="cn">TRUE</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 53 × 2
   state total_employees
   &lt;chr&gt;           &lt;dbl&gt;
 1 AE                2  
 2 AK               17.2
 3 AL               63.5
 4 AP                1  
 5 AR               53.8
 6 AZ              210. 
 7 CA              239. 
 8 CO               64.0
 9 CT              324  
10 DC              279  
# … with 43 more rows</code></pre>
</div>
</div>
<p>The median of each state’s county employee counts, or, the median number of employees among the counties within each state, listed in alphabetical order of states.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>railroad<span class="sc">%&gt;%</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(state)<span class="sc">%&gt;%</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span> (<span class="st">`</span><span class="at">total_employees</span><span class="st">`</span>)<span class="sc">%&gt;%</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize_all</span>(median, <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 53 × 2
   state total_employees
   &lt;chr&gt;           &lt;dbl&gt;
 1 AE                2  
 2 AK                2.5
 3 AL               26  
 4 AP                1  
 5 AR               16.5
 6 AZ               94  
 7 CA               61  
 8 CO               10  
 9 CT              125  
10 DC              279  
# … with 43 more rows</code></pre>
</div>
</div>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">CONCLUSION</h2>
<p>We’ve uncovered more information of this dataset in the use of the tools of R Studio performed above. More statistical analysis of this dataset is ahead, using the information summarized by state, and by creating new dataframes from subsets of the original dataset.The questions could be a simple as: 1) How many counties have more than 87 employees? The count of 87 employees was selected because 87 is the overall mean of the dataset of employee count by county.</p>
<p>OR</p>
<ol start="2" type="1">
<li>How many counties have more than 65 employees? The count of 65 employees was selected because 65 is the count of employees of the beginning of the 4th quantile of the dataset.</li>
</ol>
<p>OR</p>
<ol start="3" type="1">
<li>What is the standard deviation of the new dataframe of the 4th quantile? Does this standard deviation indicate we might want to further explore subsets of the 4th quantile and perform statistical analysis on that new dataframe?</li>
</ol>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="DACSS/601_Spring_2023" data-repo-id="R_kgDOI4JcJA" data-category="Announcements" data-category-id="" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb35" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Challenge 2 Using dataset 'railroads’"</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Kris Smole"</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "03/01/2023"</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a><span class="co">    code-copy: true</span></span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span></span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a><span class="co">  - challenge_2</span></span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a><span class="co">  - railroads</span></span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a><span class="co">  - faostat</span></span>
<span id="cb35-15"><a href="#cb35-15" aria-hidden="true" tabindex="-1"></a><span class="co">  - hotel_bookings</span></span>
<span id="cb35-16"><a href="#cb35-16" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb35-17"><a href="#cb35-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-20"><a href="#cb35-20" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb35-21"><a href="#cb35-21" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: setup</span></span>
<span id="cb35-22"><a href="#cb35-22" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb35-23"><a href="#cb35-23" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb35-24"><a href="#cb35-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-25"><a href="#cb35-25" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb35-26"><a href="#cb35-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-27"><a href="#cb35-27" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">TRUE</span>, <span class="at">warning=</span><span class="cn">FALSE</span>, <span class="at">message=</span><span class="cn">FALSE</span>)</span>
<span id="cb35-28"><a href="#cb35-28" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb35-29"><a href="#cb35-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-30"><a href="#cb35-30" aria-hidden="true" tabindex="-1"></a><span class="fu">## Description of the dataset 'Railroads'</span></span>
<span id="cb35-31"><a href="#cb35-31" aria-hidden="true" tabindex="-1"></a>Railroads dataset contains distinct observations of total employee counts, by counties within US states/principalities. </span>
<span id="cb35-32"><a href="#cb35-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-33"><a href="#cb35-33" aria-hidden="true" tabindex="-1"></a>Let's review some of the basics of this dataset: it’s overall size, its content in its columns and rows (which are the variables and observations, respectively, and how this dataset might have been compiled.  We can do this by looking at the dataset itself:</span>
<span id="cb35-34"><a href="#cb35-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-37"><a href="#cb35-37" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb35-38"><a href="#cb35-38" aria-hidden="true" tabindex="-1"></a>railroad <span class="ot">&lt;-</span><span class="fu">read_csv</span>(<span class="st">"_data/railroad_2012_clean_county.csv"</span>)</span>
<span id="cb35-39"><a href="#cb35-39" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(modeest)</span>
<span id="cb35-40"><a href="#cb35-40" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb35-43"><a href="#cb35-43" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb35-44"><a href="#cb35-44" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(railroad, state, county, total_employees)</span>
<span id="cb35-45"><a href="#cb35-45" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb35-46"><a href="#cb35-46" aria-hidden="true" tabindex="-1"></a>We can see in the results above, and confirmed in the results showing the entire dataframe contained in the file, that this dataset contains a count of rows (2930) and columns (3).</span>
<span id="cb35-47"><a href="#cb35-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-48"><a href="#cb35-48" aria-hidden="true" tabindex="-1"></a>We also see in the left-most column, familiar state abbreviations, as well as some other abbreviations such as AE, AP, and DC, representing 53 state and military/governmental principalities of the US. Next column to the right, we see specific county names that relate to the identified states and principalities. The right-most column provides the total count of employees for the stated county and state.</span>
<span id="cb35-49"><a href="#cb35-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-50"><a href="#cb35-50" aria-hidden="true" tabindex="-1"></a>The observations of this dataset are the rows of data, which record the number of employees within each county that the railroad operates, while the variable is the county and state combination for each railroad employment site. </span>
<span id="cb35-51"><a href="#cb35-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-52"><a href="#cb35-52" aria-hidden="true" tabindex="-1"></a>How many counties have distinct names within this dataset? </span>
<span id="cb35-55"><a href="#cb35-55" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb35-56"><a href="#cb35-56" aria-hidden="true" tabindex="-1"></a>railroad<span class="sc">%&gt;%</span></span>
<span id="cb35-57"><a href="#cb35-57" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(county)<span class="sc">%&gt;%</span></span>
<span id="cb35-58"><a href="#cb35-58" aria-hidden="true" tabindex="-1"></a>  <span class="fu">n_distinct</span>(.)</span>
<span id="cb35-59"><a href="#cb35-59" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb35-60"><a href="#cb35-60" aria-hidden="true" tabindex="-1"></a>The answer of 1709 distinct county names indicates that some county names repeat across various states, because the count of county names are not equal to 2930, the total number of distinct observations by counties within states/principalities. </span>
<span id="cb35-61"><a href="#cb35-61" aria-hidden="true" tabindex="-1"></a>We are able to use a function named “distinct” on the county name column to find this answer.</span>
<span id="cb35-62"><a href="#cb35-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-63"><a href="#cb35-63" aria-hidden="true" tabindex="-1"></a>So, we know this dataset represents information about a railroad or railroads that operate in the stated counties of the United States. In terms of the source of the data, It is likely the data was compiled by an individual railroad company, or some trade or regulatory or governmental body about one railroad, or about several railroads. The data does not include definitive data to know exactly which of these possibilities are true. Unless or until we know the exact source of the data, we can make suppositions through verifying the employee counts and locations of operations by railroad(s), if relevant and important to identify the specific data source. </span>
<span id="cb35-64"><a href="#cb35-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-65"><a href="#cb35-65" aria-hidden="true" tabindex="-1"></a>Although the dataframe within the dataset file is a solid starting point, the dataframe in its current state contains minimalcomparative or analytical information about the employees of the railroad(s) working within various counties across the states/principalities. Thankfully, we have the tools to use the existing data in the dataset and find more information using sorting, arithmetic and statistical calculations.</span>
<span id="cb35-66"><a href="#cb35-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-67"><a href="#cb35-67" aria-hidden="true" tabindex="-1"></a>Let's start with some basic descriptive statistics of this dataset.</span>
<span id="cb35-68"><a href="#cb35-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-69"><a href="#cb35-69" aria-hidden="true" tabindex="-1"></a>First, we see the total of all employees by county and state.</span>
<span id="cb35-72"><a href="#cb35-72" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb35-73"><a href="#cb35-73" aria-hidden="true" tabindex="-1"></a><span class="fu">summarize</span>(railroad,<span class="fu">sum</span>(<span class="st">`</span><span class="at">total_employees</span><span class="st">`</span>))</span>
<span id="cb35-74"><a href="#cb35-74" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb35-75"><a href="#cb35-75" aria-hidden="true" tabindex="-1"></a>The overall total count of employees for the railroad(s) in the counties and states of the US in this dataframe is 255,432 employees.</span>
<span id="cb35-76"><a href="#cb35-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-77"><a href="#cb35-77" aria-hidden="true" tabindex="-1"></a>Below is the mean, or average count of railroad employees by county.</span>
<span id="cb35-80"><a href="#cb35-80" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb35-81"><a href="#cb35-81" aria-hidden="true" tabindex="-1"></a><span class="fu">summarize</span>(railroad,<span class="fu">mean</span>(<span class="st">`</span><span class="at">total_employees</span><span class="st">`</span>))</span>
<span id="cb35-82"><a href="#cb35-82" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb35-83"><a href="#cb35-83" aria-hidden="true" tabindex="-1"></a>The counties of the US states in which these railroad operations exist have an average employee count of 87.2 employees. Because we speak in terms of individuals, we will use a whole number of 87 as the approximate average count of employees by county.</span>
<span id="cb35-84"><a href="#cb35-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-85"><a href="#cb35-85" aria-hidden="true" tabindex="-1"></a>Next is the median of railroad employees by county.</span>
<span id="cb35-88"><a href="#cb35-88" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb35-89"><a href="#cb35-89" aria-hidden="true" tabindex="-1"></a><span class="fu">summarize</span>(railroad, <span class="fu">median</span>(<span class="st">`</span><span class="at">total_employees</span><span class="st">`</span>))</span>
<span id="cb35-90"><a href="#cb35-90" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb35-91"><a href="#cb35-91" aria-hidden="true" tabindex="-1"></a>The counties of the US states in which these railroad operations exist have a median employee count of 21 employees. This statistical calculation results in a whole number because the median is the most frequently occurring observation within the dataframe, not a calculation per se, as the mean/average is.</span>
<span id="cb35-92"><a href="#cb35-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-93"><a href="#cb35-93" aria-hidden="true" tabindex="-1"></a>And, finally, we have the mode of railroad employees by county</span>
<span id="cb35-96"><a href="#cb35-96" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb35-97"><a href="#cb35-97" aria-hidden="true" tabindex="-1"></a>mode<span class="ot">=</span><span class="fu">mfv</span>(railroad<span class="sc">$</span>total_employees)</span>
<span id="cb35-98"><a href="#cb35-98" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span> (mode)</span>
<span id="cb35-99"><a href="#cb35-99" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb35-100"><a href="#cb35-100" aria-hidden="true" tabindex="-1"></a>The counties of the US states in which these railroad operations exist have a mode of employee count of 1 employee. This statistical result in a whole number, like the result for the median, because the mode and median are the statistical occurrences of actual dataframe observations, not a calculation per se. The mode is the most frequently occurring observation within the dataframe. Remember this as we move forward to view the standard deviation and quantiles of this dataset.</span>
<span id="cb35-101"><a href="#cb35-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-102"><a href="#cb35-102" aria-hidden="true" tabindex="-1"></a>Now we'll look at the lowest employee count among the counties. The mode tells us that the count of 1 employee is the most frequent count of employees by county, so we have a good guess as to the lowest count of employees among the counties (ie: 1).</span>
<span id="cb35-105"><a href="#cb35-105" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb35-106"><a href="#cb35-106" aria-hidden="true" tabindex="-1"></a><span class="fu">summarize</span>(railroad, <span class="fu">min</span>(<span class="st">`</span><span class="at">total_employees</span><span class="st">`</span>))</span>
<span id="cb35-107"><a href="#cb35-107" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb35-108"><a href="#cb35-108" aria-hidden="true" tabindex="-1"></a>We see the lowest employee count among the counties is 1 employee.</span>
<span id="cb35-109"><a href="#cb35-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-110"><a href="#cb35-110" aria-hidden="true" tabindex="-1"></a>We want to see the highest count of employees among the counties.</span>
<span id="cb35-113"><a href="#cb35-113" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb35-114"><a href="#cb35-114" aria-hidden="true" tabindex="-1"></a><span class="fu">summarize</span>(railroad, <span class="fu">max</span>(<span class="st">`</span><span class="at">total_employees</span><span class="st">`</span>))</span>
<span id="cb35-115"><a href="#cb35-115" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb35-116"><a href="#cb35-116" aria-hidden="true" tabindex="-1"></a>The highest count of employees among the counties is 8,207. We knew that of the 2930 counties, some of them had to have larger numbers of employee counts to get to an overall employee total count of 255,432, since employee counts of one would not bring us to 255,432 over 2930 counties if the employee count was 87, or 21, as we saw in the mean and median of the dataset. </span>
<span id="cb35-117"><a href="#cb35-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-118"><a href="#cb35-118" aria-hidden="true" tabindex="-1"></a>In a bit, we will see in the quantiles and standard deviation of the dataframe that the employee count of 1 has many occurrences within the dataframe, as previously indicated by the mode. With over 255,432 employees across 53 states/principalities, a mode of 1, an average of 87, and a median of 21, and the largest county count of employees of 8,207, the dispersion of employee counts will likely be skewed closer to employee counts of 1 than to the employee count of 8,207. Does that mean more counties have employee counts of less than 87 than employee counts of 88 or more? Yes.</span>
<span id="cb35-119"><a href="#cb35-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-120"><a href="#cb35-120" aria-hidden="true" tabindex="-1"></a>What are the quantiles of the dataframe?</span>
<span id="cb35-123"><a href="#cb35-123" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb35-124"><a href="#cb35-124" aria-hidden="true" tabindex="-1"></a><span class="fu">summarize</span>(railroad,<span class="fu">quantile</span>(<span class="st">`</span><span class="at">total_employees</span><span class="st">`</span>))</span>
<span id="cb35-125"><a href="#cb35-125" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb35-126"><a href="#cb35-126" aria-hidden="true" tabindex="-1"></a>The 1st quantile of the count of employees by county begins at 1, and ends with 6.</span>
<span id="cb35-127"><a href="#cb35-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-128"><a href="#cb35-128" aria-hidden="true" tabindex="-1"></a>The 2nd quantile of the count of employees by county begins at 7 and ends with 20.</span>
<span id="cb35-129"><a href="#cb35-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-130"><a href="#cb35-130" aria-hidden="true" tabindex="-1"></a>The 3rd quantile of the count of employees by county begins at 21 and ends with 64.</span>
<span id="cb35-131"><a href="#cb35-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-132"><a href="#cb35-132" aria-hidden="true" tabindex="-1"></a>The 4th quantile of the count of employees by county begins at 65 and ends with 8207.</span>
<span id="cb35-133"><a href="#cb35-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-134"><a href="#cb35-134" aria-hidden="true" tabindex="-1"></a>We are seeing that the dataset has some very large counts of employees, and some very low counts of employees. From what we see in the ranges of employee counts in the quantile output, the 4th quantile of counts of employees by county has a very large range of employee counts, from 65 employees to 8,207 employees. The range of 65 employees to 8,207 employees is a very large range of employee counts, given the other 3 quantiles of occurrences of employee counts by county span only the count of 1 to the count of 64. The 4th quantile requires more examination, that will likely be best done through creating a new dataframe of only the 4th quantile to allow statistical calculations to examine the larger range of the 4th quantile, to provide more meaningful analysis of all of the original dataframe, since the first 3 quantiles have reltaively little variation in employee counts in comparison to the 4th quantile.</span>
<span id="cb35-135"><a href="#cb35-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-136"><a href="#cb35-136" aria-hidden="true" tabindex="-1"></a>This makes us curious about the standard deviation of the individual counts of employees by county. Like the name conveys, the standard deviation 'standardizes' the variance of each observation's difference from the dataset mean of 87.17816. Or, said differently, the standard deviation helps make the variances of each employee count from the employee mean more comparable. </span>
<span id="cb35-137"><a href="#cb35-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-140"><a href="#cb35-140" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb35-141"><a href="#cb35-141" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(railroad,<span class="st">`</span><span class="at">total_employees</span><span class="st">`</span>)</span>
<span id="cb35-142"><a href="#cb35-142" aria-hidden="true" tabindex="-1"></a><span class="fu">summarize</span>(railroad,<span class="fu">sd</span>(<span class="st">`</span><span class="at">total_employees</span><span class="st">`</span>))</span>
<span id="cb35-143"><a href="#cb35-143" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb35-144"><a href="#cb35-144" aria-hidden="true" tabindex="-1"></a>We see the standard deviation of all employee counts by county in the dataset is 284 from the mean of 87.2. Standard deviation is different than the description of the variance between each employee count observation and the mean of the overall dataset employee count. Each employee count varies, or has a variance from the mean that is different from 283.6359. The standard deviation is a mathematical standarizing of the variances to help make the collection of variances more general, and more simple to understand. Examining the 4th quantile independently of the first 3 quantiles will provide a different standard deviation, mean, median, mode and set of quantiles. This may lead to yet another, new, separate dataframe so as to examine the resulting new quantiles, in pursuit of finding a more evenly distributed set of quantiles - quantiles that might approximate a normal distribution. That's ahead in our work...</span>
<span id="cb35-145"><a href="#cb35-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-146"><a href="#cb35-146" aria-hidden="true" tabindex="-1"></a><span class="fu">## Grouped Summary Statistics - Looking at our Dataset by State totals</span></span>
<span id="cb35-147"><a href="#cb35-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-148"><a href="#cb35-148" aria-hidden="true" tabindex="-1"></a>Often, viewers of data like this dataset, want to know information by state, which this dataset doesn’t provide in summary. We can now look at some descriptive statistical measures of the states. We look at the highest employee count by state, the lowest employee count by state, the mean (or average) of each state in alphbetical order, and median of each state in alphbetical order. </span>
<span id="cb35-149"><a href="#cb35-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-150"><a href="#cb35-150" aria-hidden="true" tabindex="-1"></a>Below we have the number of employees summarizing the county employee counts of each state, in alphabetical order of state.  </span>
<span id="cb35-153"><a href="#cb35-153" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb35-154"><a href="#cb35-154" aria-hidden="true" tabindex="-1"></a>railroad<span class="sc">%&gt;%</span></span>
<span id="cb35-155"><a href="#cb35-155" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(state)<span class="sc">%&gt;%</span></span>
<span id="cb35-156"><a href="#cb35-156" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span> (<span class="st">`</span><span class="at">total_employees</span><span class="st">`</span>)<span class="sc">%&gt;%</span></span>
<span id="cb35-157"><a href="#cb35-157" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize_all</span>(sum, <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span>
<span id="cb35-158"><a href="#cb35-158" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb35-159"><a href="#cb35-159" aria-hidden="true" tabindex="-1"></a>Knowing the states with the highest number of employees and the lowest number of employees might be of interest. What follows are those two summarized listings of the highest and lowest counts of employees among the counties by state, in alphabetic order of states. A rank order of the highest and lowest employee counts is in the works for the future.</span>
<span id="cb35-160"><a href="#cb35-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-163"><a href="#cb35-163" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb35-164"><a href="#cb35-164" aria-hidden="true" tabindex="-1"></a>railroad<span class="sc">%&gt;%</span></span>
<span id="cb35-165"><a href="#cb35-165" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(state)<span class="sc">%&gt;%</span></span>
<span id="cb35-166"><a href="#cb35-166" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span> (<span class="st">`</span><span class="at">total_employees</span><span class="st">`</span>)<span class="sc">%&gt;%</span></span>
<span id="cb35-167"><a href="#cb35-167" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize_all</span>(max, <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span>
<span id="cb35-168"><a href="#cb35-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-169"><a href="#cb35-169" aria-hidden="true" tabindex="-1"></a>railroad<span class="sc">%&gt;%</span></span>
<span id="cb35-170"><a href="#cb35-170" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(state)<span class="sc">%&gt;%</span></span>
<span id="cb35-171"><a href="#cb35-171" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span> (<span class="st">`</span><span class="at">total_employees</span><span class="st">`</span>)<span class="sc">%&gt;%</span></span>
<span id="cb35-172"><a href="#cb35-172" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize_all</span>(min, <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span>
<span id="cb35-173"><a href="#cb35-173" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb35-174"><a href="#cb35-174" aria-hidden="true" tabindex="-1"></a>The mean of each state’s county employee counts, or, the average number of employees of all the counties within each state. The list is in alphabetical order of the states.</span>
<span id="cb35-177"><a href="#cb35-177" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb35-178"><a href="#cb35-178" aria-hidden="true" tabindex="-1"></a>railroad<span class="sc">%&gt;%</span></span>
<span id="cb35-179"><a href="#cb35-179" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(state)<span class="sc">%&gt;%</span></span>
<span id="cb35-180"><a href="#cb35-180" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span> (<span class="st">`</span><span class="at">total_employees</span><span class="st">`</span>)<span class="sc">%&gt;%</span></span>
<span id="cb35-181"><a href="#cb35-181" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize_all</span>(mean, <span class="at">na.rm=</span><span class="cn">TRUE</span>) </span>
<span id="cb35-182"><a href="#cb35-182" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb35-183"><a href="#cb35-183" aria-hidden="true" tabindex="-1"></a>The median of each state’s county employee counts, or, the median number of employees among the counties within each state, listed in alphabetical order of states.</span>
<span id="cb35-186"><a href="#cb35-186" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb35-187"><a href="#cb35-187" aria-hidden="true" tabindex="-1"></a>railroad<span class="sc">%&gt;%</span></span>
<span id="cb35-188"><a href="#cb35-188" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(state)<span class="sc">%&gt;%</span></span>
<span id="cb35-189"><a href="#cb35-189" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span> (<span class="st">`</span><span class="at">total_employees</span><span class="st">`</span>)<span class="sc">%&gt;%</span></span>
<span id="cb35-190"><a href="#cb35-190" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize_all</span>(median, <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span>
<span id="cb35-191"><a href="#cb35-191" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb35-192"><a href="#cb35-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-193"><a href="#cb35-193" aria-hidden="true" tabindex="-1"></a><span class="fu">## CONCLUSION</span></span>
<span id="cb35-194"><a href="#cb35-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-195"><a href="#cb35-195" aria-hidden="true" tabindex="-1"></a>We've uncovered more information of this dataset in the use of the tools of R Studio performed above. More statistical analysis of this dataset is ahead, using the information summarized by state, and by creating new dataframes from subsets of the original dataset.The questions could be a simple as: 1) How many counties have more than 87 employees? The count of 87 employees was selected because 87 is the overall mean of the dataset of employee count by county. </span>
<span id="cb35-196"><a href="#cb35-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-197"><a href="#cb35-197" aria-hidden="true" tabindex="-1"></a>OR</span>
<span id="cb35-198"><a href="#cb35-198" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-199"><a href="#cb35-199" aria-hidden="true" tabindex="-1"></a>2) How many counties have more than 65 employees? The count of 65 employees was selected because 65 is the count of employees of the beginning of the 4th quantile of the dataset.  </span>
<span id="cb35-200"><a href="#cb35-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-201"><a href="#cb35-201" aria-hidden="true" tabindex="-1"></a>OR</span>
<span id="cb35-202"><a href="#cb35-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-203"><a href="#cb35-203" aria-hidden="true" tabindex="-1"></a>3) What is the standard deviation of the new dataframe of the 4th quantile? Does this standard deviation indicate we might want to further explore subsets of the 4th quantile and perform statistical analysis on that new dataframe?</span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>