---
title: "Final Project Assignment#1: Project & Data Description"
author: "Lauren Zichittella"
description: "Project & Data Description"
date: "03/31/2023"
format:
  html:
    df-print: paged
    toc: true
    code-copy: true
    code-tools: true
    css: styles.css
categories:
  - final_Project_assignment_1
  - final_project_data_description
editor_options: 
  chunk_output_type: console
---

## Assignment 1: Proposed project     

The Vaccine Adverse Event Reporting System (VAERS) was established by the Food and Drug Administration and Centers for Disease Control to monitor the safety of licensed vaccines in the United States. Reports to this system are submitted by the general public to capture information on:
1) the person exposed
2) type and dose of vaccine administered
3) nature and severity of the adverse event.  
Rather than using this data to evaluate associations between vaccines and outcome, I will describe the population submitting reports to this system and evaluate trends in characteristics overtime. To limit biases in this analysis, the study population will be limited to:  
- Those who received a vaccine in the 5 years prior to the COVID pandemic 2015-2019  
- Adults age 18+ as of vaccination date  
- Received influenza vaccination: vaccine has been available consistently throughout   time period where yearly dosage is recommended  
Trends will be evaluated by the following population characteristics (alone and in combination):  
- geographic location     
- age  
- sex  
- race/ethnicity  


```{r}
#| label: setup
#| warning: false
#| message: false

library(tidyverse)

knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```
