<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.427">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Livia Charles">
<meta name="dcterms.date" content="2023-05-30">
<meta name="description" content="Final Project Paper and Code">

<title>Final Project</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../images/DACSS_Round_Network.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

<script src="../site_libs/htmlwidgets-1.6.2/htmlwidgets.js"></script>
<script src="../site_libs/plotly-binding-4.10.1/plotly.js"></script>
<script src="../site_libs/typedarray-0.1/typedarray.min.js"></script>
<script src="../site_libs/jquery-3.5.1/jquery.min.js"></script>
<link href="../site_libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet">
<script src="../site_libs/crosstalk-1.2.0/js/crosstalk.min.js"></script>
<link href="../site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet">
<script src="../site_libs/plotly-main-2.11.1/plotly-latest.min.js"></script>
<link href="../site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">
<script src="../site_libs/pagedtable-1.1/js/pagedtable.js"></script>


<link rel="stylesheet" href="styles.css">
<meta name="twitter:title" content="Final Project">
<meta name="twitter:description" content="Final Project Paper and Code">
<meta name="twitter:image" content="https://dacss.github.io/601_Spring_2023/posts/Livia_Charles_final_project_updateNew_files/figure-html/unnamed-chunk-10-1.png">
<meta name="twitter:creator" content="@UMassDACSS">
<meta name="twitter:site" content="@UMassDACSS">
<meta name="twitter:image-height" content="960">
<meta name="twitter:image-width" content="1344">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../images/UMass White Wordmark Horiz.png" alt="" class="navbar-logo">
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://github.com/DACSS" rel="" target="">
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html" rel="" target="">
 <span class="menu-text">Contributors</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://umass.edu/sbs/dacss" rel="" target="">
 <span class="menu-text">DACSS</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/DACSS" rel="" target=""><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#the-data" id="toc-the-data" class="nav-link" data-scroll-target="#the-data">The Data</a>
  <ul class="collapse">
  <li><a href="#restructuring-and-combining-the-data-sets" id="toc-restructuring-and-combining-the-data-sets" class="nav-link" data-scroll-target="#restructuring-and-combining-the-data-sets">Restructuring and combining the data sets</a></li>
  <li><a href="#describing-the-new-data-set" id="toc-describing-the-new-data-set" class="nav-link" data-scroll-target="#describing-the-new-data-set">Describing the new data set</a></li>
  </ul></li>
  <li><a href="#removing-racquets-based-on-physical-characteristics" id="toc-removing-racquets-based-on-physical-characteristics" class="nav-link" data-scroll-target="#removing-racquets-based-on-physical-characteristics">Removing racquets based on physical characteristics</a></li>
  <li><a href="#assessing-racquets-based-on-reviewer-scores" id="toc-assessing-racquets-based-on-reviewer-scores" class="nav-link" data-scroll-target="#assessing-racquets-based-on-reviewer-scores">Assessing racquets based on reviewer scores</a>
  <ul class="collapse">
  <li><a href="#choosing-the-final-racquets" id="toc-choosing-the-final-racquets" class="nav-link" data-scroll-target="#choosing-the-final-racquets">Choosing the final racquets</a></li>
  </ul></li>
  <li><a href="#conclusion-and-reflection" id="toc-conclusion-and-reflection" class="nav-link" data-scroll-target="#conclusion-and-reflection">Conclusion and Reflection</a></li>
  <li><a href="#bibliography" id="toc-bibliography" class="nav-link" data-scroll-target="#bibliography">Bibliography</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Final Project</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
  <div class="quarto-categories">
    <div class="quarto-category">final_Project</div>
  </div>
  </div>

<div>
  <div class="description">
    Final Project Paper and Code
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Livia Charles </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 30, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(plotly)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">TRUE</span>, <span class="at">warning=</span><span class="cn">FALSE</span>, <span class="at">message=</span><span class="cn">FALSE</span>) </span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_knit<span class="sc">$</span><span class="fu">set</span>(<span class="at">root.dir =</span> <span class="st">"/Users/liviacharles/Documents/R Class/601_Spring_2023"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>I’ve recently found myself in a situation that applies to hundreds of thousands, perhaps millions of people each year: I need to purchase a new tennis racquet, but am completely overwhelmed by the multitude of options to choose from.</p>
<p>Every tennis racquet plays very differently and can have an impact on player performance. I am just starting to play and have found that finding the right racquet to buy is a tricky process, and while there are reviews and suggestions on racquets to buy, it is quite overwhelming. So here, I plan to use the power of data and code to narrow down the racquet options from well over a hundred to just a few that will fit my playing level, game style, and individual requirements for a racquet. The same methodology could be applied to other players by making adjustments for their skill level, experience with other racquets, play style, etc.</p>
</section>
<section id="the-data" class="level2">
<h2 class="anchored" data-anchor-id="the-data">The Data</h2>
<p>I am using several different data sets which originated from the website Tennis Warehouse. The data sets are constantly updated, and the versions I have are current as of May 1, 2023. All the data sets contain information on different tennis racquets.</p>
<p>The first data set is a compilation of reviewer scores for each unique racquet that has been reviewed. Each row in the data set represents a different racquet and reviewer score combination (i.e.&nbsp;every row contains the name of a racquet, a score category, and the reviewer score given for that category). There are several different score variables that correspond to important characteristics of a tennis racquet such as power, control, spin potential, etc.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Read in the reviewer scores data set</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>reviewer_scores <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"posts/data_LiviaCharles/reviewer_scores.csv"</span>, <span class="at">header =</span> T) </span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Look at the head of the data</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(reviewer_scores)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["Category"],"name":[1],"type":["chr"],"align":["left"]},{"label":["Score"],"name":[2],"type":["int"],"align":["right"]},{"label":["Racquet"],"name":[3],"type":["chr"],"align":["left"]}],"data":[{"1":"Overall","2":"83","3":"Prince Vortex 300","_rn_":"1"},{"1":"Groundstrokes","2":"83","3":"Prince Vortex 300","_rn_":"2"},{"1":"Volleys","2":"82","3":"Prince Vortex 300","_rn_":"3"},{"1":"Serves","2":"82","3":"Prince Vortex 300","_rn_":"4"},{"1":"Returns","2":"82","3":"Prince Vortex 300","_rn_":"5"},{"1":"Power","2":"87","3":"Prince Vortex 300","_rn_":"6"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check the dimensions of the data set</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(reviewer_scores)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1677    3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check for rows that contain NAs </span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(<span class="sc">!</span><span class="fu">complete.cases</span>(reviewer_scores))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>integer(0)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">getwd</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "/Users/liviacharles/Documents/R Class/601_Spring_2023"</code></pre>
</div>
</div>
<p>The second and third data sets are both compilations of technical specifications for each tennis racquet. They are broken into two data sets because one data set contains measurements that are generated by a specific machine, while the other contains more general specifications that are usually provided by the racquet manufacturer.</p>
<p>The second data set, which is called the specifications data set contains the racquet name, a racquet specification, and one or two values in each row, depending on the specification. Specifications include values for the length of the racquet, the weight of the racquet, the racquets string pattern, etc.</p>
<p>The third data set, called the rate data set, is configured similarly to the first two, with each row containing a racquet name and a value for one of the two measurements given by the specific machine used to test for racquet stiffness and swingweight. So in this data set, each unique racquet has two rows of data, one containing the value for its stiffness and the other for its swingweight.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Read in the racquet specs and racquet rates data sets </span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>racquet_specs <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"posts/data_LiviaCharles/racquet_specs.csv"</span>, <span class="at">header =</span> T) </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>racquet_rates <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"posts/data_LiviaCharles/racquet_rate.csv"</span>, <span class="at">header =</span> T) </span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Check the head of each data set</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(racquet_specs) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["Spec"],"name":[1],"type":["chr"],"align":["left"]},{"label":["Value1"],"name":[2],"type":["chr"],"align":["left"]},{"label":["Value2"],"name":[3],"type":["chr"],"align":["left"]},{"label":["Racquet"],"name":[4],"type":["chr"],"align":["left"]}],"data":[{"1":"Length","2":"27 in","3":"69 cm","4":"Tecnifibre TF-X1 300","_rn_":"1"},{"1":"Head Size","2":"100 in","3":"645.16 cm","4":"Tecnifibre TF-X1 300","_rn_":"2"},{"1":"Weight","2":"11.1 oz","3":"315 gm","4":"Tecnifibre TF-X1 300","_rn_":"3"},{"1":"Balance Point","2":"13 in 33.02 cm","3":"4pts HL","4":"Tecnifibre TF-X1 300","_rn_":"4"},{"1":"Construction","2":"24mm / 24mm / 24mm","3":"","4":"Tecnifibre TF-X1 300","_rn_":"5"},{"1":"Composition","2":"Graphite","3":"","4":"Tecnifibre TF-X1 300","_rn_":"6"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(racquet_rates)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["Spec"],"name":[1],"type":["chr"],"align":["left"]},{"label":["Value"],"name":[2],"type":["int"],"align":["right"]},{"label":["Racquet"],"name":[3],"type":["chr"],"align":["left"]}],"data":[{"1":"Flex Rating","2":"71","3":"Tecnifibre TF-X1 300","_rn_":"1"},{"1":"Swing Weight","2":"323","3":"Tecnifibre TF-X1 300","_rn_":"2"},{"1":"Flex Rating","2":"58","3":"Prince Phantom 100X 305","_rn_":"3"},{"1":"Swing Weight","2":"321","3":"Prince Phantom 100X 305","_rn_":"4"},{"1":"Flex Rating","2":"64","3":"Prince Textreme Tour 95","_rn_":"5"},{"1":"Swing Weight","2":"325","3":"Prince Textreme Tour 95","_rn_":"6"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check the dimensions of the data sets</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(racquet_specs) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 917   4</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(racquet_rates) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 262   3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check for rows with NAs </span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(<span class="sc">!</span><span class="fu">complete.cases</span>(racquet_specs))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>integer(0)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(<span class="sc">!</span><span class="fu">complete.cases</span>(racquet_rates))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>integer(0)</code></pre>
</div>
</div>
<p>Finally, there is a fourth data set that contains the year each racquet was reviewed. Each row contians the name of the racquet and the year it was reviewed.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Read in the racquet year data set</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>racquet_year <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"posts/data_LiviaCharles/racquet_year.csv"</span>, <span class="at">header =</span> T) </span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Check the head of the data set</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(racquet_year)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["Year"],"name":[1],"type":["int"],"align":["right"]},{"label":["Racquet"],"name":[2],"type":["chr"],"align":["left"]}],"data":[{"1":"2022","2":"Babolat Pure Aero 2023","_rn_":"1"},{"1":"2019","2":"Babolat Pure Aero Plus 2019","_rn_":"2"},{"1":"2023","2":"Babolat Pure Aero Plus 2023","_rn_":"3"},{"1":"2022","2":"Babolat Pure Aero Team 2023","_rn_":"4"},{"1":"2021","2":"Babolat Pure Drive 107","_rn_":"5"},{"1":"2020","2":"Babolat Pure Drive 2021","_rn_":"6"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co">#check the dimensions of the data set</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(racquet_year) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 131   2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check for rows with NAs </span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(<span class="sc">!</span><span class="fu">complete.cases</span>(racquet_year))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>integer(0)</code></pre>
</div>
</div>
<p>None of the data sets contain NAs, but I still need to make sure that they contain all the same racquets. Here I will compare the length of the data sets to see if they contain the same number of racquets.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co">#count the number of unique racquets in each data set</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">unique</span>(reviewer_scores<span class="sc">$</span>Racquet))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 129</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">unique</span>(racquet_specs<span class="sc">$</span>Racquet))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 131</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">unique</span>(racquet_rates<span class="sc">$</span>Racquet))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 131</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">unique</span>(racquet_year<span class="sc">$</span>Racquet)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 131</code></pre>
</div>
</div>
<section id="restructuring-and-combining-the-data-sets" class="level3">
<h3 class="anchored" data-anchor-id="restructuring-and-combining-the-data-sets">Restructuring and combining the data sets</h3>
<p>The data set lengths are are not all equal, meaning that each type of data was not available for every racquet. So we need to combine the data sets and only keep the racquets which have every data set. First though, we also need to restructure the data sets. For the specs data set, I only need the values in column Value1, except for those that correspond to the Balance Point.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Create a new column that only contains the values I need </span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>racquet_specs <span class="ot">&lt;-</span> racquet_specs <span class="sc">%&gt;%</span> </span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Value =</span> <span class="fu">ifelse</span>(Spec <span class="sc">==</span> <span class="st">"Balance Point"</span>, Value2, Value1)) </span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Now remove Value1 and Value2 columns </span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>racquet_specs <span class="ot">&lt;-</span> racquet_specs <span class="sc">%&gt;%</span> </span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>Value1, <span class="sc">-</span>Value2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now I need to transform the data sets so that each row represents a single unique racquet, except for the racquet year data which is already in an acceptable format</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>racquet_rates <span class="ot">&lt;-</span> racquet_rates <span class="sc">%&gt;%</span> </span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">spread</span>(Spec, Value)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>racquet_specs <span class="ot">&lt;-</span> racquet_specs <span class="sc">%&gt;%</span> </span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">spread</span>(Spec, Value) </span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>reviewer_scores <span class="ot">&lt;-</span> reviewer_scores <span class="sc">%&gt;%</span> </span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">spread</span>(Category, Score) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now I need to merge the data sets. I only want to keep racquets in the data set that have been reviewed so I will drop those that don’t appear in that data set.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>temp_df <span class="ot">&lt;-</span> <span class="fu">merge</span>(racquet_specs, racquet_rates, <span class="at">by =</span> <span class="st">"Racquet"</span>, <span class="at">all =</span> <span class="cn">TRUE</span>)  <span class="co"># Merge df1 and df2</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>temp_df2 <span class="ot">&lt;-</span> <span class="fu">merge</span>(temp_df, racquet_year, <span class="at">by =</span> <span class="st">"Racquet"</span>, <span class="at">all =</span> <span class="cn">TRUE</span>)  <span class="co"># Merge with df3</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>racquet_data <span class="ot">&lt;-</span> <span class="fu">merge</span>(temp_df2, reviewer_scores, <span class="at">by =</span> <span class="st">"Racquet"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="describing-the-new-data-set" class="level3">
<h3 class="anchored" data-anchor-id="describing-the-new-data-set">Describing the new data set</h3>
<p>Now that I’ve created a new data set, let’s review it to understand what is contained therein.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check the head of the data</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(racquet_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["Racquet"],"name":[1],"type":["chr"],"align":["left"]},{"label":["Balance Point"],"name":[2],"type":["chr"],"align":["left"]},{"label":["Composition"],"name":[3],"type":["chr"],"align":["left"]},{"label":["Construction"],"name":[4],"type":["chr"],"align":["left"]},{"label":["Head Size"],"name":[5],"type":["chr"],"align":["left"]},{"label":["Length"],"name":[6],"type":["chr"],"align":["left"]},{"label":["String Pattern"],"name":[7],"type":["chr"],"align":["left"]},{"label":["Weight"],"name":[8],"type":["chr"],"align":["left"]},{"label":["Flex Rating"],"name":[9],"type":["int"],"align":["right"]},{"label":["Swing Weight"],"name":[10],"type":["int"],"align":["right"]},{"label":["Year"],"name":[11],"type":["int"],"align":["right"]},{"label":["Comfort"],"name":[12],"type":["int"],"align":["right"]},{"label":["Control"],"name":[13],"type":["int"],"align":["right"]},{"label":["Groundstrokes"],"name":[14],"type":["int"],"align":["right"]},{"label":["Maneuverability"],"name":[15],"type":["int"],"align":["right"]},{"label":["Overall"],"name":[16],"type":["int"],"align":["right"]},{"label":["Power"],"name":[17],"type":["int"],"align":["right"]},{"label":["Returns"],"name":[18],"type":["int"],"align":["right"]},{"label":["Serves"],"name":[19],"type":["int"],"align":["right"]},{"label":["Slice"],"name":[20],"type":["int"],"align":["right"]},{"label":["Stability"],"name":[21],"type":["int"],"align":["right"]},{"label":["Topspin"],"name":[22],"type":["int"],"align":["right"]},{"label":["Touch/Feel"],"name":[23],"type":["int"],"align":["right"]},{"label":["Volleys"],"name":[24],"type":["int"],"align":["right"]}],"data":[{"1":"Babolat Pure Aero 2023","2":"4 pts Head Light","3":"Graphite","4":"23mm / 26mm / 23mm","5":"100 sq in","6":"27 in","7":"16 / 19","8":"11.2oz oz","9":"65","10":"322","11":"2022","12":"82","13":"80","14":"84","15":"85","16":"84","17":"83","18":"86","19":"84","20":"82","21":"81","22":"89","23":"81","24":"83","_rn_":"1"},{"1":"Babolat Pure Aero Plus 2019","2":"6pts Head Light","3":"Graphite","4":"23mm/26mm/23mm","5":"100 sq in","6":"27.5 in","7":"16 Mains / 19 Crosses","8":"11.3 oz","9":"68","10":"330","11":"2019","12":"79","13":"80","14":"87","15":"80","16":"86","17":"90","18":"85","19":"89","20":"83","21":"82","22":"90","23":"77","24":"80","_rn_":"2"},{"1":"Babolat Pure Aero Plus 2023","2":"6 pts Head Light","3":"Graphite","4":"23mm/26mm/23mm","5":"100 sq in","6":"27.5 in","7":"16 Mains / 19 Crosses","8":"11.3 oz","9":"65","10":"334","11":"2023","12":"82","13":"81","14":"87","15":"79","16":"86","17":"88","18":"81","19":"91","20":"82","21":"87","22":"89","23":"80","24":"83","_rn_":"3"},{"1":"Babolat Pure Aero Team 2023","2":"5pts Head Light","3":"Graphite","4":"23mm / 26mm / 23mm","5":"100 sq in","6":"27 in","7":"16 Mains / 19 Crosses","8":"10.6 oz","9":"67","10":"302","11":"2022","12":"75","13":"76","14":"80","15":"90","16":"80","17":"83","18":"79","19":"81","20":"78","21":"72","22":"88","23":"78","24":"79","_rn_":"4"},{"1":"Babolat Pure Drive 107","2":"5.5pts Head Light","3":"Graphite","4":"23mm / 26mm / 23mm","5":"107 sq in","6":"27.2 in","7":"16 Mains / 19 Crosses","8":"10.6 oz","9":"69","10":"309","11":"2021","12":"78","13":"80","14":"87","15":"79","16":"84","17":"88","18":"84","19":"83","20":"82","21":"85","22":"86","23":"78","24":"86","_rn_":"5"},{"1":"Babolat Pure Drive 2021","2":"4pts Head Light","3":"Graphite","4":"23mm / 26mm / 23mm","5":"100 sq in","6":"27 in","7":"16 Mains / 19 Crosses","8":"11.2 oz","9":"71","10":"320","11":"2020","12":"82","13":"80","14":"85","15":"85","16":"87","17":"92","18":"85","19":"87","20":"86","21":"85","22":"83","23":"79","24":"83","_rn_":"6"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check the dimensions of the data set</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(racquet_data)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 129  24</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check to ensure the data set does not contain NAs </span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(<span class="sc">!</span><span class="fu">complete.cases</span>(racquet_data))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>integer(0)</code></pre>
</div>
</div>
<p>The new data has 129 rows, which each represent an individual racquet, so there are 129 racquets contained in this final data set. The data set has 24 columns which contain information on each racquet including the racquet name and the year it was manufactured, physical charactersitics of the racquet (e.g., string pattern, swing weight, head size, etc.) and reviewer scores (e.g., Overall, Power, Returns, etc.) for each racquet.</p>
<p>Every column (besides racquet name) could in theory be used to narrow down which racquets might be best for me. However, some characteristics are more important than others and will serve as a better proxy for helping me choose a new racquet than others. I will get into the more important characteristics below, but an example of some characteristics that are less important and will not be discussed include racquet composition and racquet construction. Almost all racquets are composed of some form of graphite, and there is little consensus on if one company’s graphite material is better than another’s. While material does matter, a racquet’s performance cannot be judged simply on what kind of graphite is used in the frame. Instead, reviewer scores is a better proxy. Similarly, the construction, or beam widths, of a racquet do affect performance, but there is not one rule for how a thick-beamed vs thin-beamed racquet will play. Generally thick-beamed will have more power and less feel, but again these characteristics can be judged better by other physical characteristics such as swingweight and by reviewer scores. There are other characteristics in addition to these two that I will also not use in selecting a racquet because there are better proxies in the data set, which I (and the tennis community at large) deem as more important.</p>
</section>
</section>
<section id="removing-racquets-based-on-physical-characteristics" class="level2">
<h2 class="anchored" data-anchor-id="removing-racquets-based-on-physical-characteristics">Removing racquets based on physical characteristics</h2>
<p>The resulting data frame now contains all the information I need to begin narrowing down my choice for a new racquet. There are many different variables that determine how a racquet plays, and we can explore some of those now, so that the choices I make to narrow down the racquet options make sense. For now, we’ll focus on the physical characterisitcs of the racquet and ignore reviewer scores. This is because while some racquets may have high reviewer scores, they would not be ideal for me because they may not be well suited for a beginner player or may not be well suited for my game style.</p>
<p>One of the most central qualities to how a racquet plays is its head size, wich is a measure of the surface area of the inner hoop of the racquet (where the strings are). Racquets range in head size with most modern racquets falling in between 95 and 100 square inches. A 5 square inch difference may not sound like much, but a 100 square inch frame will be much more powerful and forgiving than a 95 square inch frame, all thing being equal. On the other hand, the 95 square inch frame will provide much more control than the larger head size racquet. Let’s take a look at the range of head sizes of racquets in the data set.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove the text in the head size column so that there are only integer values</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>racquet_data<span class="sc">$</span><span class="st">`</span><span class="at">Head Size</span><span class="st">`</span> <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">gsub</span>(<span class="st">"[^0-9.]+"</span>, <span class="st">""</span>, racquet_data<span class="sc">$</span><span class="st">`</span><span class="at">Head Size</span><span class="st">`</span>))</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(racquet_data<span class="sc">$</span><span class="st">`</span><span class="at">Head Size</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 100 100 100 100 107 100</code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a bar chart showing the occurrence of different head sizes in the data set </span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(racquet_data, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">`</span><span class="at">Head Size</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">na.rm =</span> T) <span class="sc">+</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">stat =</span> <span class="st">"count"</span>, <span class="fu">aes</span>(<span class="at">label =</span> ..count..), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Head Size (sq in)"</span>, <span class="at">y =</span> <span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Occurrences of Different Head Sizes"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Livia_Charles_final_project_updateNew_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>As seen in the graph, the 100 square inch and 98 square inch head size are by far the most common head size with few racquets falling below or above 95 and 100 square inches respectively.</p>
<p>Since I’m a beginner, racquets with a head size below 100 square inches are unlikely to be suitable for me and so I will now restrict the dataset to only contain racquets that have a head size greater than or equal to 100.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter the data set to only include racquets with a h ead size equal to or greater than 100</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>my_racquets <span class="ot">&lt;-</span> racquet_data <span class="sc">%&gt;%</span> </span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="st">`</span><span class="at">Head Size</span><span class="st">`</span> <span class="sc">&gt;=</span> <span class="dv">100</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next we’ll look at another very important characteristic for how a racquet plays: the swingweight. Swingweight is measured in units of kilogram centimeter squared (kg-cm2), but what’s really important is that swingweight is essentially a measure of how easy or difficult it is to swing a racquet through the air. A higher swingweight = more power and a lower swingweight = more manuevarability. Beginner players have trouble with higher swingweights and often cannot swing high swingweight racquets with proper form to generate good power and consistency, while more advanced players may feel limited with a racquet that has too low of a swingweight as they won’t be able to generate much power and the racquet may feel unstable.</p>
<p>Swingweight is influenced by other features of a racquet, mainly its overall weight and its balance. Generally, a heavier racquet will have a higher swingweight and vice versa but swingweight is also heavily incluenced by balance. Racquets can either be head heavy (more weight is contained in the head of the racquet), head light (more weight is contained in the racquet handle), or evenly balanced (racquet weight evenly distributed between head and handle of the racquet). The more head light a racquet is, the lower its swingweight and vice versa. These days, most racquets are produced to be head light, and within this data set, every single racquet is actually head light or even balanced. Let’s look at how swingweights vary based on weight and balance.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co">#First, check that all racquets are head light so that we don't need to specify whether a racquet is head light or head heavy within a numeric only value </span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(my_racquets<span class="sc">$</span><span class="st">`</span><span class="at">Balance Point</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "4 pts Head Light"   "6pts Head Light"    "6 pts Head Light"  
 [4] "5pts Head Light"    "5.5pts Head Light"  "4pts Head Light"   
 [7] "4pts HL"            "3pts Head Light"    "7 pts Head Light"  
[10] "7pts Head Light"    "Even Balance"       "9pts Head Light"   
[13] "8pts Head Light"    "9pts HL"            "3 pts Head Light"  
[16] "6.08pts Head Light" "9 pts Head Light"   "7pts HL"           
[19] "5pts HL"            "3pts HL"           </code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co">#There is at least one racquet that is even balance. We'll replace that with a value of 0 to indicate that it is even balnaced numerically. </span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>my_racquets<span class="sc">$</span><span class="st">`</span><span class="at">Balance Point</span><span class="st">`</span> <span class="ot">&lt;-</span> <span class="fu">replace</span>(my_racquets<span class="sc">$</span><span class="st">`</span><span class="at">Balance Point</span><span class="st">`</span>, my_racquets<span class="sc">$</span><span class="st">`</span><span class="at">Balance Point</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Even Balance"</span>, <span class="dv">0</span>)</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Now make all values in the balance point column numeric</span></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>my_racquets<span class="sc">$</span><span class="st">`</span><span class="at">Balance Point</span><span class="st">`</span> <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">gsub</span>(<span class="st">"[^0-9.]+"</span>, <span class="st">""</span>, my_racquets<span class="sc">$</span><span class="st">`</span><span class="at">Balance Point</span><span class="st">`</span>))</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a><span class="co">#ensure all values in the weight column have ounces as units </span></span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(my_racquets<span class="sc">$</span>Weight) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "11.2oz oz" "11.3 oz"   "10.6 oz"   "11.2 oz"   "11.8 oz"   "11.1 oz"  
 [7] "11 oz"     "11.6 oz"   "11.7 oz"   "11.5 oz"   "10.7 oz"   "10.8 oz"  
[13] "11.4 oz"   "10.4 oz"   "10.9 oz"  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co">#convert to numeric </span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>my_racquets<span class="sc">$</span>Weight <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">gsub</span>(<span class="st">"[^0-9.]+"</span>, <span class="st">""</span>, my_racquets<span class="sc">$</span><span class="st">`</span><span class="at">Weight</span><span class="st">`</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now we can create scatter plots to assess how swingweight varies based on weight and balance point.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Scatter plots: swingweight vs weight, swingweight vs balance point</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(my_racquets, <span class="fu">aes</span>(<span class="at">x =</span> Weight, <span class="at">y =</span> <span class="st">`</span><span class="at">Swing Weight</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"#D8B4FF"</span>) <span class="sc">+</span></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Weight (oz)"</span>, <span class="at">y =</span> <span class="st">"Swing Weight"</span>) <span class="sc">+</span> </span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Swingweight vs Weight"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Livia_Charles_final_project_updateNew_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(my_racquets, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">`</span><span class="at">Balance Point</span><span class="st">`</span>, <span class="at">y =</span> <span class="st">`</span><span class="at">Swing Weight</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"#D8B4FF"</span>) <span class="sc">+</span></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Balance Point (pts head light)"</span>, <span class="at">y =</span> <span class="st">"Swing Weight"</span>) <span class="sc">+</span> </span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Balance Point vs Swing Weight"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Livia_Charles_final_project_updateNew_files/figure-html/unnamed-chunk-13-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>At first glance, it appears that balance point doesn’t actually affect swingweight very much, but this is misleading because more head light racquets often have a higher overall weight.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(my_racquets, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">`</span><span class="at">Balance Point</span><span class="st">`</span>, <span class="at">y =</span> Weight)) <span class="sc">+</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"#D8B4FF"</span>) <span class="sc">+</span></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Balance Point (pts head light)"</span>, <span class="at">y =</span> <span class="st">"Weight (oz)"</span>) <span class="sc">+</span> </span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Balance Point vs Weight"</span>)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Livia_Charles_final_project_updateNew_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>As we can see, this is the case in our data set. Here I’ve shown how overall weight and balance point relate to swingweight, and each of these characteristics can be good indicators of how a racquet might play, but overall, swingweight is considered a better overall metric for helping choose a racquet. As such, I’m going to analyze the spread of swingweights in the dataset and further narrow down my racquet options.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a bar plot with the number of racquets with different swing weights</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(my_racquets, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">`</span><span class="at">Swing Weight</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">na.rm =</span> T) <span class="sc">+</span></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">stat =</span> <span class="st">"count"</span>, <span class="fu">aes</span>(<span class="at">label =</span> ..count..), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Swing Weight"</span>, <span class="at">y =</span> <span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Occurrences of Different Swing Weights"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Livia_Charles_final_project_updateNew_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Compute summary statistics of racquet swingweights </span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(my_racquets<span class="sc">$</span><span class="st">`</span><span class="at">Swing Weight</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  302.0   317.2   322.0   321.7   325.0   349.0 </code></pre>
</div>
</div>
<p>As we can see, both the mean and median of racquet swing weights is around 322. As a beginner, I need to avoid high swingweights and so I will remove racquets with a swingweight above 322 from the data set.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Remove racquets with a swingweight greater than 322</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>my_racquets <span class="ot">&lt;-</span> my_racquets <span class="sc">%&gt;%</span> </span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(<span class="st">`</span><span class="at">Swing Weight</span><span class="st">`</span> <span class="sc">&lt;=</span> <span class="dv">322</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>There are a few other physical characteristics of racquets that can influence how they might play, but limiting by head size and swingweight as a first step should be enough to ensure that I’ve eliminated most of the racquets that will be outside of my skill level. Now we can begin focusing on reviewer scores to further narrow down my choice for a racquet.</p>
</section>
<section id="assessing-racquets-based-on-reviewer-scores" class="level2">
<h2 class="anchored" data-anchor-id="assessing-racquets-based-on-reviewer-scores">Assessing racquets based on reviewer scores</h2>
<p>Before beginning to narrow down the data set further, I want to analyze if ther reviewer scores are biased towards racquets with certain characteristics. It could be that the reviewers prefer racquets with higher swingweights or a higher flex rating, etc. Or perhaps racquets with certain physical characteristics perform better for most people. Either way, it will be interesting to see if there are any patterns between physical racquet characteristics and reviewer scores.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot racquet swingweight vs overall score</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(my_racquets, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">`</span><span class="at">Swing Weight</span><span class="st">`</span>, <span class="at">y =</span> Overall)) <span class="sc">+</span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"#D8B4FF"</span>) <span class="sc">+</span></span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Swing Weight"</span>, <span class="at">y =</span> <span class="st">"Overall Score"</span>) <span class="sc">+</span> </span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Swing Weight vs Overall Score"</span>)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Livia_Charles_final_project_updateNew_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot racquet balance vs overall score</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(my_racquets, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">`</span><span class="at">Balance Point</span><span class="st">`</span>, <span class="at">y =</span> Overall)) <span class="sc">+</span></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"#D8B4FF"</span>) <span class="sc">+</span></span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Balance Point"</span>, <span class="at">y =</span> <span class="st">"Overall Score"</span>) <span class="sc">+</span> </span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Balance Point vs Overall Score"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Livia_Charles_final_project_updateNew_files/figure-html/unnamed-chunk-17-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot racquet flex vs overall score </span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(my_racquets, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">`</span><span class="at">Flex Rating</span><span class="st">`</span>, <span class="at">y =</span> Overall)) <span class="sc">+</span></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"#D8B4FF"</span>) <span class="sc">+</span></span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Flex Rating"</span>, <span class="at">y =</span> <span class="st">"Overall Score"</span>) <span class="sc">+</span> </span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Flex Rating vs Overall Score"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Livia_Charles_final_project_updateNew_files/figure-html/unnamed-chunk-17-3.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>It is interesting to see that there is a discernible pattern to overall scores based on both swingweight and flex rating (higher flex rating = more stiff). Reviewers preferred racquets with higher swing weights and lower flex ratings. This means that they preferred racquets that are more powerful, harder to swing, and less stiff. While I will continue on and trust the reviewer scores, it is worth noting that by using reviewer scores, the racquets that will be recommended are more likely to be higher swing weight and less stiff.</p>
<p>I will start by looking at the racquet’s overall scores as I don’t want to choose a racquet that has on overall poor review.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co">#First convert Overall column to numeric </span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>my_racquets<span class="sc">$</span>Overall <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(my_racquets<span class="sc">$</span>Overall)</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Plot occurrences of different overall scores</span></span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(my_racquets, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">`</span><span class="at">Overall</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">na.rm =</span> T) <span class="sc">+</span></span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">stat =</span> <span class="st">"count"</span>, <span class="fu">aes</span>(<span class="at">label =</span> ..count..), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb59-8"><a href="#cb59-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Overall Score"</span>, <span class="at">y =</span> <span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb59-9"><a href="#cb59-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Occurrences of Overall Scores"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Livia_Charles_final_project_updateNew_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Get summary statistics for the overall scores column</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(my_racquets<span class="sc">$</span>Overall) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  77.00   81.00   83.00   83.03   84.75   88.00 </code></pre>
</div>
</div>
<p>By looking at the graph, we can get an idea of where most racquets fall in overall score.</p>
<p>As before, the median and mean are similar here (83 overall score), so I’ll remove all racquets with an overall score of less than 83.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter out racquets with an overall score of less than 83 </span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>my_racquets <span class="ot">&lt;-</span> my_racquets <span class="sc">%&gt;%</span> </span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Overall <span class="sc">&gt;</span> <span class="dv">83</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now that there are only 16 racquets left in the data set, it’s time to get more specific about what type of racquet I’m looking for and what might suit my game style. Other than an overall score, there are 12 other categories that reviewers assigned scores for each racquet. To predict which racquet will best suit my game style, I’ll weight the scores of the racquets differently based on how important they are for my game style and what I want out of a racquet.</p>
<p>Without getting too far into the details of my game style, I’ve broken the 12 categories into 3 tiers based on how important they are for selecting my racquet. Tier 1: Power, Control, Touch/Feel, and Groundstrokes Tier 2: Maneuvarability, Returns, Serves, and Topspin Tier 3: Comfort, Volleys, Slice, and Stability For Tier 1, I will multiply each score by 1.1, Tier 2 by 1.0, and Tier 3 by 0.9 to produced weighted values for each category.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Mutate the dataframe to reflect the new weighted scoring </span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>my_racquets <span class="ot">&lt;-</span> my_racquets <span class="sc">%&gt;%</span> </span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Power_weight =</span> Power <span class="sc">*</span> <span class="fl">1.1</span>, <span class="at">Control_weight =</span> Control <span class="sc">*</span> <span class="fl">1.1</span>, <span class="st">`</span><span class="at">Touch/Feel_weight</span><span class="st">`</span> <span class="ot">=</span> <span class="st">`</span><span class="at">Touch/Feel</span><span class="st">`</span> <span class="sc">*</span> <span class="fl">1.1</span>, <span class="at">Groundstrokes_weight =</span> Groundstrokes <span class="sc">*</span> <span class="fl">1.1</span>, <span class="at">Maneuverability_weight =</span> Maneuverability, <span class="at">Returns_weight =</span> Returns, <span class="at">Serves_weight =</span> Serves, <span class="at">Topspin_weight =</span> Topspin, <span class="at">Comfort_weight =</span> Comfort <span class="sc">*</span> <span class="fl">0.9</span>, <span class="at">Volleys_weight =</span> Volleys <span class="sc">*</span> <span class="fl">0.9</span>, <span class="at">Slice_weight =</span> Slice <span class="sc">*</span> <span class="fl">0.9</span>, <span class="at">Stability_weight =</span> Stability <span class="sc">*</span> <span class="fl">0.9</span>) </span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a final overall score column that reflects the weighted reviewer scores</span></span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>my_racquets<span class="sc">$</span>Final_Score <span class="ot">&lt;-</span> <span class="fu">rowSums</span>(my_racquets[, <span class="dv">25</span><span class="sc">:</span><span class="dv">36</span>])<span class="sc">/</span><span class="dv">12</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s look at a graph of the racquets by final overall score. Hover over each dot to see the racquet and its score.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a scatter plot of racquets by final overall score</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(my_racquets, <span class="fu">aes</span>(<span class="at">x =</span> Racquet, <span class="at">y =</span> Final_Score, <span class="at">label =</span> Racquet)) <span class="sc">+</span> </span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Racquet"</span>, <span class="at">y =</span> <span class="st">"Final Overall Score"</span>) <span class="sc">+</span></span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span> </span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x=</span><span class="fu">element_blank</span>()) <span class="sc">+</span> </span>
<span id="cb64-7"><a href="#cb64-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Final Overall Racquet Score"</span>)</span>
<span id="cb64-8"><a href="#cb64-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-9"><a href="#cb64-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplotly</span>(p, <span class="at">tooltip =</span> <span class="fu">c</span>(<span class="st">"x"</span>, <span class="st">"y"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="plotly html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-f0e7c54b0a208a1eafab" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-f0e7c54b0a208a1eafab">{"x":{"data":[{"x":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16],"y":[83.3333333333333,83.0166666666667,84.3333333333333,84.0833333333333,84.675,86.2666666666667,83.75,85.625,84.5166666666667,82.6416666666667,85.8333333333333,83.6166666666667,84.0916666666667,82.1666666666667,85.3333333333333,85.1166666666667],"text":["Racquet: Babolat Pure Aero 2023<br />Final_Score: 83.33333","Racquet: Babolat Pure Drive 107<br />Final_Score: 83.01667","Racquet: Babolat Pure Drive 2021<br />Final_Score: 84.33333","Racquet: Prince ATS Textreme Tour 100 290<br />Final_Score: 84.08333","Racquet: Prince ATS Textreme Tour 100P<br />Final_Score: 84.67500","Racquet: Prince Phantom 100X 305<br />Final_Score: 86.26667","Racquet: Prince Phantom 107G<br />Final_Score: 83.75000","Racquet: Prince Phantom Pro 100<br />Final_Score: 85.62500","Racquet: Prince Twistpower X100<br />Final_Score: 84.51667","Racquet: Prince Twistpower X105 (290g)<br />Final_Score: 82.64167","Racquet: Wilson Clash 100<br />Final_Score: 85.83333","Racquet: Wilson Clash 100 Tour<br />Final_Score: 83.61667","Racquet: Wilson Clash 100 v2<br />Final_Score: 84.09167","Racquet: Wilson Ultra 100 v4<br />Final_Score: 82.16667","Racquet: Yonex EZONE 100<br />Final_Score: 85.33333","Racquet: Yonex VCORE 100 2023<br />Final_Score: 85.11667"],"type":"scatter","mode":"markers","marker":{"autocolorscale":false,"color":"rgba(0,0,0,1)","opacity":1,"size":5.66929133858268,"symbol":"circle","line":{"width":1.88976377952756,"color":"rgba(0,0,0,1)"}},"hoveron":"points","showlegend":false,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null}],"layout":{"margin":{"t":43.7625570776256,"r":7.30593607305936,"b":28.4931506849315,"l":37.2602739726027},"plot_bgcolor":"rgba(255,255,255,1)","paper_bgcolor":"rgba(255,255,255,1)","font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187},"title":{"text":"Final Overall Racquet Score","font":{"color":"rgba(0,0,0,1)","family":"","size":17.5342465753425},"x":0,"xref":"paper"},"xaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[0.4,16.6],"tickmode":"array","ticktext":["Babolat Pure Aero 2023","Babolat Pure Drive 107","Babolat Pure Drive 2021","Prince ATS Textreme Tour 100 290","Prince ATS Textreme Tour 100P","Prince Phantom 100X 305","Prince Phantom 107G","Prince Phantom Pro 100","Prince Twistpower X100","Prince Twistpower X105 (290g)","Wilson Clash 100","Wilson Clash 100 Tour","Wilson Clash 100 v2","Wilson Ultra 100 v4","Yonex EZONE 100","Yonex VCORE 100 2023"],"tickvals":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16],"categoryorder":"array","categoryarray":["Babolat Pure Aero 2023","Babolat Pure Drive 107","Babolat Pure Drive 2021","Prince ATS Textreme Tour 100 290","Prince ATS Textreme Tour 100P","Prince Phantom 100X 305","Prince Phantom 107G","Prince Phantom Pro 100","Prince Twistpower X100","Prince Twistpower X105 (290g)","Wilson Clash 100","Wilson Clash 100 Tour","Wilson Clash 100 v2","Wilson Ultra 100 v4","Yonex EZONE 100","Yonex VCORE 100 2023"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.65296803652968,"tickwidth":0.66417600664176,"showticklabels":false,"tickfont":{"color":null,"family":null,"size":0},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(235,235,235,1)","gridwidth":0.66417600664176,"zeroline":false,"anchor":"y","title":{"text":"Racquet","font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187}},"hoverformat":".2f"},"yaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[81.9616666666667,86.4716666666667],"tickmode":"array","ticktext":["82","83","84","85","86"],"tickvals":[82,83,84,85,86],"categoryorder":"array","categoryarray":["82","83","84","85","86"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.65296803652968,"tickwidth":0.66417600664176,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.689497716895},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(235,235,235,1)","gridwidth":0.66417600664176,"zeroline":false,"anchor":"x","title":{"text":"Final Overall Score","font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187}},"hoverformat":".2f"},"shapes":[{"type":"rect","fillcolor":"transparent","line":{"color":"rgba(51,51,51,1)","width":0.66417600664176,"linetype":"solid"},"yref":"paper","xref":"paper","x0":0,"x1":1,"y0":0,"y1":1}],"showlegend":false,"legend":{"bgcolor":"rgba(255,255,255,1)","bordercolor":"transparent","borderwidth":1.88976377952756,"font":{"color":"rgba(0,0,0,1)","family":"","size":11.689497716895}},"hovermode":"closest","barmode":"relative"},"config":{"doubleClick":"reset","modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"source":"A","attrs":{"95a62602d7bb":{"x":{},"y":{},"label":{},"type":"scatter"}},"cur_data":"95a62602d7bb","visdat":{"95a62602d7bb":["function (y) ","x"]},"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.2,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<p>Now that we have a final overall score that better reflects how a racquet suits my game style, we can pull out the top rated racquets. Since it’s always best to try before you buy, I’ll pull out the top 4 racquets so that I can try those before making my final purchase.</p>
<section id="choosing-the-final-racquets" class="level3">
<h3 class="anchored" data-anchor-id="choosing-the-final-racquets">Choosing the final racquets</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Make a new data frame with just the top 4 racquets based on the Final_Score column</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>final_racquets <span class="ot">&lt;-</span> my_racquets <span class="sc">%&gt;%</span> <span class="fu">top_n</span>(<span class="at">n =</span> <span class="dv">4</span>, <span class="at">wt =</span> Final_Score) </span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the racquet names</span></span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>final_racquets<span class="sc">$</span>Racquet</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Prince Phantom 100X 305" "Prince Phantom Pro 100" 
[3] "Wilson Clash 100"        "Yonex EZONE 100"        </code></pre>
</div>
</div>
</section>
</section>
<section id="conclusion-and-reflection" class="level2">
<h2 class="anchored" data-anchor-id="conclusion-and-reflection">Conclusion and Reflection</h2>
<p>By using some freely available datasets, I’ve systematically narrowed down my search for a new tennis racquet from well over 100 to just 4. The marketplace for racquets is overwhelming both for myself and for many other individuals. Using the powerful programming language of R has made my tennis racquet search much easier. While most tennis players are unlikely to go through the steps I’ve shown here to help them find a new racquet, this code could be altered in a way that allows individuals to answer a series of questions about their game style and racquet preferences and result in having a few racquets suggested to them.</p>
<p>I also created code that shows how certain tennis racquet characteristics are related to one another and how they vary across racquets. There are other features of racquets in the data sets that were not examined here, but could be explored further in future analyses or if this code/data were actually turned into a tool for the use of more individuals.</p>
</section>
<section id="bibliography" class="level2">
<h2 class="anchored" data-anchor-id="bibliography">Bibliography</h2>
<p>Tennis Warehouse. (2023). Reviewed Racquets - Tennis Warehouse. https://www.tennis-warehouse.com/reviewedracquets.html</p>
<p>Farthing, T. (2020, February 5). Tennis racket specifications explained. Tennishead. https://tennishead.net/tennis-racket-specifications-explained/</p>
<p>R Core Team. (2023). R: A language and environment for statistical computing (Version 4.1.1) [Computer software]. Retrieved from https://www.R-project.org/</p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="DACSS/601_Spring_2023" data-repo-id="R_kgDOI4JcJA" data-category="Announcements" data-category-id="" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb67" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Final Project"</span></span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Livia Charles"</span></span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> "Final Project Paper and Code"</span></span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "05/30/2023"</span></span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb67-7"><a href="#cb67-7" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb67-8"><a href="#cb67-8" aria-hidden="true" tabindex="-1"></a><span class="co">    df-print: paged</span></span>
<span id="cb67-9"><a href="#cb67-9" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb67-10"><a href="#cb67-10" aria-hidden="true" tabindex="-1"></a><span class="co">    code-copy: true</span></span>
<span id="cb67-11"><a href="#cb67-11" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb67-12"><a href="#cb67-12" aria-hidden="true" tabindex="-1"></a><span class="co">    css: styles.css</span></span>
<span id="cb67-13"><a href="#cb67-13" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span></span>
<span id="cb67-14"><a href="#cb67-14" aria-hidden="true" tabindex="-1"></a><span class="co">  - final_Project</span></span>
<span id="cb67-15"><a href="#cb67-15" aria-hidden="true" tabindex="-1"></a><span class="an">editor_options:</span><span class="co"> </span></span>
<span id="cb67-16"><a href="#cb67-16" aria-hidden="true" tabindex="-1"></a><span class="co">  chunk_output_type: console</span></span>
<span id="cb67-17"><a href="#cb67-17" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb67-18"><a href="#cb67-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-21"><a href="#cb67-21" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb67-22"><a href="#cb67-22" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: setup</span></span>
<span id="cb67-23"><a href="#cb67-23" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb67-24"><a href="#cb67-24" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb67-25"><a href="#cb67-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-26"><a href="#cb67-26" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb67-27"><a href="#cb67-27" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(plotly)</span>
<span id="cb67-28"><a href="#cb67-28" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">TRUE</span>, <span class="at">warning=</span><span class="cn">FALSE</span>, <span class="at">message=</span><span class="cn">FALSE</span>) </span>
<span id="cb67-29"><a href="#cb67-29" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_knit<span class="sc">$</span><span class="fu">set</span>(<span class="at">root.dir =</span> <span class="st">"/Users/liviacharles/Documents/R Class/601_Spring_2023"</span>)</span>
<span id="cb67-30"><a href="#cb67-30" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb67-31"><a href="#cb67-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-32"><a href="#cb67-32" aria-hidden="true" tabindex="-1"></a><span class="fu">## Introduction</span></span>
<span id="cb67-33"><a href="#cb67-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-34"><a href="#cb67-34" aria-hidden="true" tabindex="-1"></a>I've recently found myself in a situation that applies to hundreds of thousands, perhaps millions of people each year: I need to purchase a new tennis racquet, but am completely overwhelmed by the multitude of options to choose from. </span>
<span id="cb67-35"><a href="#cb67-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-36"><a href="#cb67-36" aria-hidden="true" tabindex="-1"></a>Every tennis racquet plays very differently and can have an impact on player performance. I am just starting to play and have found that finding the right racquet to buy is a tricky process, and while there are reviews and suggestions on racquets to buy, it is quite overwhelming. So here, I plan to use the power of data and code to narrow down the racquet options from well over a hundred to just a few that will fit my playing level, game style, and individual requirements for a racquet. The same methodology could be applied to other players by making adjustments for their skill level, experience with other racquets, play style, etc. </span>
<span id="cb67-37"><a href="#cb67-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-38"><a href="#cb67-38" aria-hidden="true" tabindex="-1"></a><span class="fu">## The Data</span></span>
<span id="cb67-39"><a href="#cb67-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-40"><a href="#cb67-40" aria-hidden="true" tabindex="-1"></a>I am using several different data sets which originated from the website Tennis Warehouse. The data sets are constantly updated, and the versions I have are current as of May 1, 2023. All the data sets contain information on different tennis racquets.</span>
<span id="cb67-41"><a href="#cb67-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-42"><a href="#cb67-42" aria-hidden="true" tabindex="-1"></a>The first data set is a compilation of reviewer scores for each unique racquet that has been reviewed. Each row in the data set represents a different racquet and reviewer score combination (i.e. every row contains the name of a racquet, a score category, and the reviewer score given for that category). There are several different score variables that correspond to important characteristics of a tennis racquet such as power, control, spin potential, etc. </span>
<span id="cb67-43"><a href="#cb67-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-44"><a href="#cb67-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-47"><a href="#cb67-47" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb67-48"><a href="#cb67-48" aria-hidden="true" tabindex="-1"></a><span class="co"># Read in the reviewer scores data set</span></span>
<span id="cb67-49"><a href="#cb67-49" aria-hidden="true" tabindex="-1"></a>reviewer_scores <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"posts/data_LiviaCharles/reviewer_scores.csv"</span>, <span class="at">header =</span> T) </span>
<span id="cb67-50"><a href="#cb67-50" aria-hidden="true" tabindex="-1"></a><span class="co"># Look at the head of the data</span></span>
<span id="cb67-51"><a href="#cb67-51" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(reviewer_scores)</span>
<span id="cb67-52"><a href="#cb67-52" aria-hidden="true" tabindex="-1"></a><span class="co"># Check the dimensions of the data set</span></span>
<span id="cb67-53"><a href="#cb67-53" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(reviewer_scores)  </span>
<span id="cb67-54"><a href="#cb67-54" aria-hidden="true" tabindex="-1"></a><span class="co"># Check for rows that contain NAs </span></span>
<span id="cb67-55"><a href="#cb67-55" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(<span class="sc">!</span><span class="fu">complete.cases</span>(reviewer_scores))</span>
<span id="cb67-56"><a href="#cb67-56" aria-hidden="true" tabindex="-1"></a><span class="fu">getwd</span>()</span>
<span id="cb67-57"><a href="#cb67-57" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb67-58"><a href="#cb67-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-59"><a href="#cb67-59" aria-hidden="true" tabindex="-1"></a>The second and third data sets are both compilations of technical specifications for each tennis racquet. They are broken into two data sets because one data set contains measurements that are generated by a specific machine, while the other contains more general specifications that are usually provided by the racquet manufacturer. </span>
<span id="cb67-60"><a href="#cb67-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-61"><a href="#cb67-61" aria-hidden="true" tabindex="-1"></a>The second data set, which is called the specifications data set contains the racquet name, a racquet specification, and one or two values in each row, depending on the specification. Specifications include values for the length of the racquet, the weight of the racquet, the racquets string pattern, etc.</span>
<span id="cb67-62"><a href="#cb67-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-63"><a href="#cb67-63" aria-hidden="true" tabindex="-1"></a>The third data set, called the rate data set, is configured similarly to the first two, with each row containing a racquet name and a value for one of the two measurements given by the specific machine used to test for racquet stiffness and swingweight. So in this data set, each unique racquet has two rows of data, one containing the value for its stiffness and the other for its swingweight.</span>
<span id="cb67-64"><a href="#cb67-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-67"><a href="#cb67-67" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb67-68"><a href="#cb67-68" aria-hidden="true" tabindex="-1"></a><span class="co">#Read in the racquet specs and racquet rates data sets </span></span>
<span id="cb67-69"><a href="#cb67-69" aria-hidden="true" tabindex="-1"></a>racquet_specs <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"posts/data_LiviaCharles/racquet_specs.csv"</span>, <span class="at">header =</span> T) </span>
<span id="cb67-70"><a href="#cb67-70" aria-hidden="true" tabindex="-1"></a>racquet_rates <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"posts/data_LiviaCharles/racquet_rate.csv"</span>, <span class="at">header =</span> T) </span>
<span id="cb67-71"><a href="#cb67-71" aria-hidden="true" tabindex="-1"></a><span class="co"># Check the head of each data set</span></span>
<span id="cb67-72"><a href="#cb67-72" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(racquet_specs) </span>
<span id="cb67-73"><a href="#cb67-73" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(racquet_rates)</span>
<span id="cb67-74"><a href="#cb67-74" aria-hidden="true" tabindex="-1"></a><span class="co"># Check the dimensions of the data sets</span></span>
<span id="cb67-75"><a href="#cb67-75" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(racquet_specs) </span>
<span id="cb67-76"><a href="#cb67-76" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(racquet_rates) </span>
<span id="cb67-77"><a href="#cb67-77" aria-hidden="true" tabindex="-1"></a><span class="co"># Check for rows with NAs </span></span>
<span id="cb67-78"><a href="#cb67-78" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(<span class="sc">!</span><span class="fu">complete.cases</span>(racquet_specs))</span>
<span id="cb67-79"><a href="#cb67-79" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(<span class="sc">!</span><span class="fu">complete.cases</span>(racquet_rates))</span>
<span id="cb67-80"><a href="#cb67-80" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb67-81"><a href="#cb67-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-82"><a href="#cb67-82" aria-hidden="true" tabindex="-1"></a>Finally, there is a fourth data set that contains the year each racquet was reviewed. Each row contians the name of the racquet and the year it was reviewed. </span>
<span id="cb67-83"><a href="#cb67-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-86"><a href="#cb67-86" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb67-87"><a href="#cb67-87" aria-hidden="true" tabindex="-1"></a><span class="co">#Read in the racquet year data set</span></span>
<span id="cb67-88"><a href="#cb67-88" aria-hidden="true" tabindex="-1"></a>racquet_year <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"posts/data_LiviaCharles/racquet_year.csv"</span>, <span class="at">header =</span> T) </span>
<span id="cb67-89"><a href="#cb67-89" aria-hidden="true" tabindex="-1"></a><span class="co">#Check the head of the data set</span></span>
<span id="cb67-90"><a href="#cb67-90" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(racquet_year)</span>
<span id="cb67-91"><a href="#cb67-91" aria-hidden="true" tabindex="-1"></a><span class="co">#check the dimensions of the data set</span></span>
<span id="cb67-92"><a href="#cb67-92" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(racquet_year) </span>
<span id="cb67-93"><a href="#cb67-93" aria-hidden="true" tabindex="-1"></a><span class="co"># Check for rows with NAs </span></span>
<span id="cb67-94"><a href="#cb67-94" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(<span class="sc">!</span><span class="fu">complete.cases</span>(racquet_year))</span>
<span id="cb67-95"><a href="#cb67-95" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb67-96"><a href="#cb67-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-97"><a href="#cb67-97" aria-hidden="true" tabindex="-1"></a>None of the data sets contain NAs, but I still need to make sure that they contain all the same racquets. Here I will compare the length of the data sets to see if they contain the same number of racquets. </span>
<span id="cb67-98"><a href="#cb67-98" aria-hidden="true" tabindex="-1"></a>       </span>
<span id="cb67-101"><a href="#cb67-101" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb67-102"><a href="#cb67-102" aria-hidden="true" tabindex="-1"></a><span class="co">#count the number of unique racquets in each data set</span></span>
<span id="cb67-103"><a href="#cb67-103" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">unique</span>(reviewer_scores<span class="sc">$</span>Racquet))</span>
<span id="cb67-104"><a href="#cb67-104" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">unique</span>(racquet_specs<span class="sc">$</span>Racquet))</span>
<span id="cb67-105"><a href="#cb67-105" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">unique</span>(racquet_rates<span class="sc">$</span>Racquet))</span>
<span id="cb67-106"><a href="#cb67-106" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">unique</span>(racquet_year<span class="sc">$</span>Racquet)) </span>
<span id="cb67-107"><a href="#cb67-107" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb67-108"><a href="#cb67-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-109"><a href="#cb67-109" aria-hidden="true" tabindex="-1"></a><span class="fu">### Restructuring and combining the data sets</span></span>
<span id="cb67-110"><a href="#cb67-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-111"><a href="#cb67-111" aria-hidden="true" tabindex="-1"></a>The data set lengths are are not all equal, meaning that each type of data was not available for every racquet. So we need to combine the data sets and only keep the racquets which have every data set. </span>
<span id="cb67-112"><a href="#cb67-112" aria-hidden="true" tabindex="-1"></a>First though, we also need to restructure the data sets. For the specs data set, I only need the values in column Value1, except for those that correspond to the Balance Point.  </span>
<span id="cb67-115"><a href="#cb67-115" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb67-116"><a href="#cb67-116" aria-hidden="true" tabindex="-1"></a><span class="co">#Create a new column that only contains the values I need </span></span>
<span id="cb67-117"><a href="#cb67-117" aria-hidden="true" tabindex="-1"></a>racquet_specs <span class="ot">&lt;-</span> racquet_specs <span class="sc">%&gt;%</span> </span>
<span id="cb67-118"><a href="#cb67-118" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Value =</span> <span class="fu">ifelse</span>(Spec <span class="sc">==</span> <span class="st">"Balance Point"</span>, Value2, Value1)) </span>
<span id="cb67-119"><a href="#cb67-119" aria-hidden="true" tabindex="-1"></a><span class="co">#Now remove Value1 and Value2 columns </span></span>
<span id="cb67-120"><a href="#cb67-120" aria-hidden="true" tabindex="-1"></a>racquet_specs <span class="ot">&lt;-</span> racquet_specs <span class="sc">%&gt;%</span> </span>
<span id="cb67-121"><a href="#cb67-121" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>Value1, <span class="sc">-</span>Value2)</span>
<span id="cb67-122"><a href="#cb67-122" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb67-123"><a href="#cb67-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-124"><a href="#cb67-124" aria-hidden="true" tabindex="-1"></a>Now I need to transform the data sets so that each row represents a single unique racquet, except for the racquet year data which is already in an acceptable format </span>
<span id="cb67-125"><a href="#cb67-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-128"><a href="#cb67-128" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb67-129"><a href="#cb67-129" aria-hidden="true" tabindex="-1"></a>racquet_rates <span class="ot">&lt;-</span> racquet_rates <span class="sc">%&gt;%</span> </span>
<span id="cb67-130"><a href="#cb67-130" aria-hidden="true" tabindex="-1"></a>  <span class="fu">spread</span>(Spec, Value)</span>
<span id="cb67-131"><a href="#cb67-131" aria-hidden="true" tabindex="-1"></a>racquet_specs <span class="ot">&lt;-</span> racquet_specs <span class="sc">%&gt;%</span> </span>
<span id="cb67-132"><a href="#cb67-132" aria-hidden="true" tabindex="-1"></a>  <span class="fu">spread</span>(Spec, Value) </span>
<span id="cb67-133"><a href="#cb67-133" aria-hidden="true" tabindex="-1"></a>reviewer_scores <span class="ot">&lt;-</span> reviewer_scores <span class="sc">%&gt;%</span> </span>
<span id="cb67-134"><a href="#cb67-134" aria-hidden="true" tabindex="-1"></a>  <span class="fu">spread</span>(Category, Score) </span>
<span id="cb67-135"><a href="#cb67-135" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb67-136"><a href="#cb67-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-137"><a href="#cb67-137" aria-hidden="true" tabindex="-1"></a>Now I need to merge the data sets. I only want to keep racquets in the data set that have been reviewed so I will drop those that don't appear in that data set. </span>
<span id="cb67-138"><a href="#cb67-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-141"><a href="#cb67-141" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb67-142"><a href="#cb67-142" aria-hidden="true" tabindex="-1"></a>temp_df <span class="ot">&lt;-</span> <span class="fu">merge</span>(racquet_specs, racquet_rates, <span class="at">by =</span> <span class="st">"Racquet"</span>, <span class="at">all =</span> <span class="cn">TRUE</span>)  <span class="co"># Merge df1 and df2</span></span>
<span id="cb67-143"><a href="#cb67-143" aria-hidden="true" tabindex="-1"></a>temp_df2 <span class="ot">&lt;-</span> <span class="fu">merge</span>(temp_df, racquet_year, <span class="at">by =</span> <span class="st">"Racquet"</span>, <span class="at">all =</span> <span class="cn">TRUE</span>)  <span class="co"># Merge with df3</span></span>
<span id="cb67-144"><a href="#cb67-144" aria-hidden="true" tabindex="-1"></a>racquet_data <span class="ot">&lt;-</span> <span class="fu">merge</span>(temp_df2, reviewer_scores, <span class="at">by =</span> <span class="st">"Racquet"</span>) </span>
<span id="cb67-145"><a href="#cb67-145" aria-hidden="true" tabindex="-1"></a><span class="in">```</span> </span>
<span id="cb67-146"><a href="#cb67-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-147"><a href="#cb67-147" aria-hidden="true" tabindex="-1"></a><span class="fu">### Describing the new data set </span></span>
<span id="cb67-148"><a href="#cb67-148" aria-hidden="true" tabindex="-1"></a>Now that I've created a new data set, let's review it to understand what is contained therein. </span>
<span id="cb67-149"><a href="#cb67-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-152"><a href="#cb67-152" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb67-153"><a href="#cb67-153" aria-hidden="true" tabindex="-1"></a><span class="co"># Check the head of the data</span></span>
<span id="cb67-154"><a href="#cb67-154" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(racquet_data)</span>
<span id="cb67-155"><a href="#cb67-155" aria-hidden="true" tabindex="-1"></a><span class="co"># Check the dimensions of the data set</span></span>
<span id="cb67-156"><a href="#cb67-156" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(racquet_data)  </span>
<span id="cb67-157"><a href="#cb67-157" aria-hidden="true" tabindex="-1"></a><span class="co"># Check to ensure the data set does not contain NAs </span></span>
<span id="cb67-158"><a href="#cb67-158" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(<span class="sc">!</span><span class="fu">complete.cases</span>(racquet_data))</span>
<span id="cb67-159"><a href="#cb67-159" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb67-160"><a href="#cb67-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-161"><a href="#cb67-161" aria-hidden="true" tabindex="-1"></a>The new data has 129 rows, which each represent an individual racquet, so there are 129 racquets contained in this final data set. The data set has 24 columns which contain information on each racquet including the racquet name and the year it was manufactured, physical charactersitics of the racquet (e.g., string pattern, swing weight, head size, etc.) and reviewer scores (e.g., Overall, Power, Returns, etc.) for each racquet. </span>
<span id="cb67-162"><a href="#cb67-162" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-163"><a href="#cb67-163" aria-hidden="true" tabindex="-1"></a>Every column (besides racquet name) could in theory be used to narrow down which racquets might be best for me. However, some characteristics are more important than others and will serve as a better proxy for helping me choose a new racquet than others. I will get into the more important characteristics below, but an example of some characteristics that are less important and will not be discussed include racquet composition and racquet construction. Almost all racquets are composed of some form of graphite, and there is little consensus on if one company's graphite material is better than another's. While material does matter, a racquet's performance cannot be judged simply on what kind of graphite is used in the frame. Instead, reviewer scores is a better proxy. Similarly, the construction, or beam widths, of a racquet do affect performance, but there is not one rule for how a thick-beamed vs thin-beamed racquet will play. Generally thick-beamed will have more power and less feel, but again these characteristics can be judged better by other physical characteristics such as swingweight and by reviewer scores. There are other characteristics in addition to these two that I will also not use in selecting a racquet because there are better proxies in the data set, which I (and the tennis community at large) deem as more important. </span>
<span id="cb67-164"><a href="#cb67-164" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-165"><a href="#cb67-165" aria-hidden="true" tabindex="-1"></a><span class="fu">## Removing racquets based on physical characteristics </span></span>
<span id="cb67-166"><a href="#cb67-166" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-167"><a href="#cb67-167" aria-hidden="true" tabindex="-1"></a>The resulting data frame now contains all the information I need to begin narrowing down my choice for a new racquet. There are many different variables that determine how a racquet plays, and we can explore some of those now, so that the choices I make to narrow down the racquet options make sense. For now, we'll focus on the physical characterisitcs of the racquet and ignore reviewer scores. This is because while some racquets may have high reviewer scores, they would not be ideal for me because they may not be well suited for a beginner player or may not be well suited for my game style.</span>
<span id="cb67-168"><a href="#cb67-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-169"><a href="#cb67-169" aria-hidden="true" tabindex="-1"></a>One of the most central qualities to how a racquet plays is its head size, wich is a measure of the surface area of the inner hoop of the racquet (where the strings are). Racquets range in head size with most modern racquets falling in between 95 and 100 square inches. A 5 square inch difference may not sound like much, but a 100 square inch frame will be much more powerful and forgiving than a 95 square inch frame, all thing being equal. On the other hand, the 95 square inch frame will provide much more control than the larger head size racquet. Let's take a look at the range of head sizes of racquets in the data set.</span>
<span id="cb67-170"><a href="#cb67-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-173"><a href="#cb67-173" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb67-174"><a href="#cb67-174" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove the text in the head size column so that there are only integer values</span></span>
<span id="cb67-175"><a href="#cb67-175" aria-hidden="true" tabindex="-1"></a>racquet_data<span class="sc">$</span><span class="st">`</span><span class="at">Head Size</span><span class="st">`</span> <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">gsub</span>(<span class="st">"[^0-9.]+"</span>, <span class="st">""</span>, racquet_data<span class="sc">$</span><span class="st">`</span><span class="at">Head Size</span><span class="st">`</span>))</span>
<span id="cb67-176"><a href="#cb67-176" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(racquet_data<span class="sc">$</span><span class="st">`</span><span class="at">Head Size</span><span class="st">`</span>)</span>
<span id="cb67-177"><a href="#cb67-177" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a bar chart showing the occurrence of different head sizes in the data set </span></span>
<span id="cb67-178"><a href="#cb67-178" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(racquet_data, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">`</span><span class="at">Head Size</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb67-179"><a href="#cb67-179" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">na.rm =</span> T) <span class="sc">+</span></span>
<span id="cb67-180"><a href="#cb67-180" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">stat =</span> <span class="st">"count"</span>, <span class="fu">aes</span>(<span class="at">label =</span> ..count..), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb67-181"><a href="#cb67-181" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Head Size (sq in)"</span>, <span class="at">y =</span> <span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb67-182"><a href="#cb67-182" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Occurrences of Different Head Sizes"</span>)</span>
<span id="cb67-183"><a href="#cb67-183" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb67-184"><a href="#cb67-184" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-185"><a href="#cb67-185" aria-hidden="true" tabindex="-1"></a>As seen in the graph, the 100 square inch and 98 square inch head size are by far the most common head size with few racquets falling below or above 95 and 100 square inches respectively.</span>
<span id="cb67-186"><a href="#cb67-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-187"><a href="#cb67-187" aria-hidden="true" tabindex="-1"></a>Since I'm a beginner, racquets with a head size below 100 square inches are unlikely to be suitable for me and so I will now restrict the dataset to only contain racquets that have a head size greater than or equal to 100.</span>
<span id="cb67-188"><a href="#cb67-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-191"><a href="#cb67-191" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb67-192"><a href="#cb67-192" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter the data set to only include racquets with a h ead size equal to or greater than 100</span></span>
<span id="cb67-193"><a href="#cb67-193" aria-hidden="true" tabindex="-1"></a>my_racquets <span class="ot">&lt;-</span> racquet_data <span class="sc">%&gt;%</span> </span>
<span id="cb67-194"><a href="#cb67-194" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="st">`</span><span class="at">Head Size</span><span class="st">`</span> <span class="sc">&gt;=</span> <span class="dv">100</span>)</span>
<span id="cb67-195"><a href="#cb67-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-196"><a href="#cb67-196" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb67-197"><a href="#cb67-197" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-198"><a href="#cb67-198" aria-hidden="true" tabindex="-1"></a>Next we'll look at another very important characteristic for how a racquet plays: the swingweight. Swingweight is measured in units of kilogram centimeter squared (kg-cm2), but what's really important is that swingweight is essentially a measure of how easy or difficult it is to swing a racquet through the air. A higher swingweight = more power and a lower swingweight = more manuevarability. Beginner players have trouble with higher swingweights and often cannot swing high swingweight racquets with proper form to generate good power and consistency, while more advanced players may feel limited with a racquet that has too low of a swingweight as they won't be able to generate much power and the racquet may feel unstable.</span>
<span id="cb67-199"><a href="#cb67-199" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-200"><a href="#cb67-200" aria-hidden="true" tabindex="-1"></a>Swingweight is influenced by other features of a racquet, mainly its overall weight and its balance. Generally, a heavier racquet will have a higher swingweight and vice versa but swingweight is also heavily incluenced by balance. Racquets can either be head heavy (more weight is contained in the head of the racquet), head light (more weight is contained in the racquet handle), or evenly balanced (racquet weight evenly distributed between head and handle of the racquet). The more head light a racquet is, the lower its swingweight and vice versa. These days, most racquets are produced to be head light, and within this data set, every single racquet is actually head light or even balanced. Let's look at how swingweights vary based on weight and balance.</span>
<span id="cb67-201"><a href="#cb67-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-204"><a href="#cb67-204" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb67-205"><a href="#cb67-205" aria-hidden="true" tabindex="-1"></a><span class="co">#First, check that all racquets are head light so that we don't need to specify whether a racquet is head light or head heavy within a numeric only value </span></span>
<span id="cb67-206"><a href="#cb67-206" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(my_racquets<span class="sc">$</span><span class="st">`</span><span class="at">Balance Point</span><span class="st">`</span>)</span>
<span id="cb67-207"><a href="#cb67-207" aria-hidden="true" tabindex="-1"></a><span class="co">#There is at least one racquet that is even balance. We'll replace that with a value of 0 to indicate that it is even balnaced numerically. </span></span>
<span id="cb67-208"><a href="#cb67-208" aria-hidden="true" tabindex="-1"></a>my_racquets<span class="sc">$</span><span class="st">`</span><span class="at">Balance Point</span><span class="st">`</span> <span class="ot">&lt;-</span> <span class="fu">replace</span>(my_racquets<span class="sc">$</span><span class="st">`</span><span class="at">Balance Point</span><span class="st">`</span>, my_racquets<span class="sc">$</span><span class="st">`</span><span class="at">Balance Point</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Even Balance"</span>, <span class="dv">0</span>)</span>
<span id="cb67-209"><a href="#cb67-209" aria-hidden="true" tabindex="-1"></a><span class="co">#Now make all values in the balance point column numeric</span></span>
<span id="cb67-210"><a href="#cb67-210" aria-hidden="true" tabindex="-1"></a>my_racquets<span class="sc">$</span><span class="st">`</span><span class="at">Balance Point</span><span class="st">`</span> <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">gsub</span>(<span class="st">"[^0-9.]+"</span>, <span class="st">""</span>, my_racquets<span class="sc">$</span><span class="st">`</span><span class="at">Balance Point</span><span class="st">`</span>))</span>
<span id="cb67-211"><a href="#cb67-211" aria-hidden="true" tabindex="-1"></a><span class="co">#ensure all values in the weight column have ounces as units </span></span>
<span id="cb67-212"><a href="#cb67-212" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(my_racquets<span class="sc">$</span>Weight) </span>
<span id="cb67-213"><a href="#cb67-213" aria-hidden="true" tabindex="-1"></a><span class="co">#convert to numeric </span></span>
<span id="cb67-214"><a href="#cb67-214" aria-hidden="true" tabindex="-1"></a>my_racquets<span class="sc">$</span>Weight <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">gsub</span>(<span class="st">"[^0-9.]+"</span>, <span class="st">""</span>, my_racquets<span class="sc">$</span><span class="st">`</span><span class="at">Weight</span><span class="st">`</span>))</span>
<span id="cb67-215"><a href="#cb67-215" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-216"><a href="#cb67-216" aria-hidden="true" tabindex="-1"></a><span class="in">```</span> </span>
<span id="cb67-217"><a href="#cb67-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-218"><a href="#cb67-218" aria-hidden="true" tabindex="-1"></a>Now we can create scatter plots to assess how swingweight varies based on weight and balance point. </span>
<span id="cb67-219"><a href="#cb67-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-222"><a href="#cb67-222" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb67-223"><a href="#cb67-223" aria-hidden="true" tabindex="-1"></a><span class="co"># Scatter plots: swingweight vs weight, swingweight vs balance point</span></span>
<span id="cb67-224"><a href="#cb67-224" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(my_racquets, <span class="fu">aes</span>(<span class="at">x =</span> Weight, <span class="at">y =</span> <span class="st">`</span><span class="at">Swing Weight</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb67-225"><a href="#cb67-225" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb67-226"><a href="#cb67-226" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"#D8B4FF"</span>) <span class="sc">+</span></span>
<span id="cb67-227"><a href="#cb67-227" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Weight (oz)"</span>, <span class="at">y =</span> <span class="st">"Swing Weight"</span>) <span class="sc">+</span> </span>
<span id="cb67-228"><a href="#cb67-228" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Swingweight vs Weight"</span>)</span>
<span id="cb67-229"><a href="#cb67-229" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-230"><a href="#cb67-230" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(my_racquets, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">`</span><span class="at">Balance Point</span><span class="st">`</span>, <span class="at">y =</span> <span class="st">`</span><span class="at">Swing Weight</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb67-231"><a href="#cb67-231" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb67-232"><a href="#cb67-232" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"#D8B4FF"</span>) <span class="sc">+</span></span>
<span id="cb67-233"><a href="#cb67-233" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Balance Point (pts head light)"</span>, <span class="at">y =</span> <span class="st">"Swing Weight"</span>) <span class="sc">+</span> </span>
<span id="cb67-234"><a href="#cb67-234" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Balance Point vs Swing Weight"</span>) </span>
<span id="cb67-235"><a href="#cb67-235" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-236"><a href="#cb67-236" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb67-237"><a href="#cb67-237" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-238"><a href="#cb67-238" aria-hidden="true" tabindex="-1"></a>At first glance, it appears that balance point doesn't actually affect swingweight very much, but this is misleading because more head light racquets often have a higher overall weight.</span>
<span id="cb67-239"><a href="#cb67-239" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-242"><a href="#cb67-242" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb67-243"><a href="#cb67-243" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(my_racquets, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">`</span><span class="at">Balance Point</span><span class="st">`</span>, <span class="at">y =</span> Weight)) <span class="sc">+</span></span>
<span id="cb67-244"><a href="#cb67-244" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb67-245"><a href="#cb67-245" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"#D8B4FF"</span>) <span class="sc">+</span></span>
<span id="cb67-246"><a href="#cb67-246" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Balance Point (pts head light)"</span>, <span class="at">y =</span> <span class="st">"Weight (oz)"</span>) <span class="sc">+</span> </span>
<span id="cb67-247"><a href="#cb67-247" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Balance Point vs Weight"</span>)  </span>
<span id="cb67-248"><a href="#cb67-248" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-249"><a href="#cb67-249" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb67-250"><a href="#cb67-250" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-251"><a href="#cb67-251" aria-hidden="true" tabindex="-1"></a>As we can see, this is the case in our data set. Here I've shown how overall weight and balance point relate to swingweight, and each of these characteristics can be good indicators of how a racquet might play, but overall, swingweight is considered a better overall metric for helping choose a racquet. As such, I'm going to analyze the spread of swingweights in the dataset and further narrow down my racquet options.</span>
<span id="cb67-252"><a href="#cb67-252" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-255"><a href="#cb67-255" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb67-256"><a href="#cb67-256" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a bar plot with the number of racquets with different swing weights</span></span>
<span id="cb67-257"><a href="#cb67-257" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(my_racquets, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">`</span><span class="at">Swing Weight</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb67-258"><a href="#cb67-258" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">na.rm =</span> T) <span class="sc">+</span></span>
<span id="cb67-259"><a href="#cb67-259" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">stat =</span> <span class="st">"count"</span>, <span class="fu">aes</span>(<span class="at">label =</span> ..count..), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb67-260"><a href="#cb67-260" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Swing Weight"</span>, <span class="at">y =</span> <span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb67-261"><a href="#cb67-261" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Occurrences of Different Swing Weights"</span>)</span>
<span id="cb67-262"><a href="#cb67-262" aria-hidden="true" tabindex="-1"></a><span class="co">#Compute summary statistics of racquet swingweights </span></span>
<span id="cb67-263"><a href="#cb67-263" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(my_racquets<span class="sc">$</span><span class="st">`</span><span class="at">Swing Weight</span><span class="st">`</span>)</span>
<span id="cb67-264"><a href="#cb67-264" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-265"><a href="#cb67-265" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb67-266"><a href="#cb67-266" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-267"><a href="#cb67-267" aria-hidden="true" tabindex="-1"></a>As we can see, both the mean and median of racquet swing weights is around 322. As a beginner, I need to avoid high swingweights and so I will remove racquets with a swingweight above 322 from the data set.</span>
<span id="cb67-268"><a href="#cb67-268" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-271"><a href="#cb67-271" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb67-272"><a href="#cb67-272" aria-hidden="true" tabindex="-1"></a><span class="co">#Remove racquets with a swingweight greater than 322</span></span>
<span id="cb67-273"><a href="#cb67-273" aria-hidden="true" tabindex="-1"></a>my_racquets <span class="ot">&lt;-</span> my_racquets <span class="sc">%&gt;%</span> </span>
<span id="cb67-274"><a href="#cb67-274" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(<span class="st">`</span><span class="at">Swing Weight</span><span class="st">`</span> <span class="sc">&lt;=</span> <span class="dv">322</span>)</span>
<span id="cb67-275"><a href="#cb67-275" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-276"><a href="#cb67-276" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb67-277"><a href="#cb67-277" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-278"><a href="#cb67-278" aria-hidden="true" tabindex="-1"></a>There are a few other physical characteristics of racquets that can influence how they might play, but limiting by head size and swingweight as a first step should be enough to ensure that I've eliminated most of the racquets that will be outside of my skill level. Now we can begin focusing on reviewer scores to further narrow down my choice for a racquet.</span>
<span id="cb67-279"><a href="#cb67-279" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-280"><a href="#cb67-280" aria-hidden="true" tabindex="-1"></a><span class="fu">## Assessing racquets based on reviewer scores</span></span>
<span id="cb67-281"><a href="#cb67-281" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-282"><a href="#cb67-282" aria-hidden="true" tabindex="-1"></a>Before beginning to narrow down the data set further, I want to analyze if ther reviewer scores are biased towards racquets with certain characteristics. It could be that the reviewers prefer racquets with higher swingweights or a higher flex rating, etc. Or perhaps racquets with certain physical characteristics perform better for most people. Either way, it will be interesting to see if there are any patterns between physical racquet characteristics and reviewer scores. </span>
<span id="cb67-283"><a href="#cb67-283" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-286"><a href="#cb67-286" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb67-287"><a href="#cb67-287" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot racquet swingweight vs overall score</span></span>
<span id="cb67-288"><a href="#cb67-288" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(my_racquets, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">`</span><span class="at">Swing Weight</span><span class="st">`</span>, <span class="at">y =</span> Overall)) <span class="sc">+</span></span>
<span id="cb67-289"><a href="#cb67-289" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb67-290"><a href="#cb67-290" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"#D8B4FF"</span>) <span class="sc">+</span></span>
<span id="cb67-291"><a href="#cb67-291" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Swing Weight"</span>, <span class="at">y =</span> <span class="st">"Overall Score"</span>) <span class="sc">+</span> </span>
<span id="cb67-292"><a href="#cb67-292" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Swing Weight vs Overall Score"</span>)  </span>
<span id="cb67-293"><a href="#cb67-293" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-294"><a href="#cb67-294" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot racquet balance vs overall score</span></span>
<span id="cb67-295"><a href="#cb67-295" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(my_racquets, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">`</span><span class="at">Balance Point</span><span class="st">`</span>, <span class="at">y =</span> Overall)) <span class="sc">+</span></span>
<span id="cb67-296"><a href="#cb67-296" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb67-297"><a href="#cb67-297" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"#D8B4FF"</span>) <span class="sc">+</span></span>
<span id="cb67-298"><a href="#cb67-298" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Balance Point"</span>, <span class="at">y =</span> <span class="st">"Overall Score"</span>) <span class="sc">+</span> </span>
<span id="cb67-299"><a href="#cb67-299" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Balance Point vs Overall Score"</span>) </span>
<span id="cb67-300"><a href="#cb67-300" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-301"><a href="#cb67-301" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot racquet flex vs overall score </span></span>
<span id="cb67-302"><a href="#cb67-302" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(my_racquets, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">`</span><span class="at">Flex Rating</span><span class="st">`</span>, <span class="at">y =</span> Overall)) <span class="sc">+</span></span>
<span id="cb67-303"><a href="#cb67-303" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb67-304"><a href="#cb67-304" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"#D8B4FF"</span>) <span class="sc">+</span></span>
<span id="cb67-305"><a href="#cb67-305" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Flex Rating"</span>, <span class="at">y =</span> <span class="st">"Overall Score"</span>) <span class="sc">+</span> </span>
<span id="cb67-306"><a href="#cb67-306" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Flex Rating vs Overall Score"</span>) </span>
<span id="cb67-307"><a href="#cb67-307" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb67-308"><a href="#cb67-308" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-309"><a href="#cb67-309" aria-hidden="true" tabindex="-1"></a>It is interesting to see that there is a discernible pattern to overall scores based on both swingweight and flex rating (higher flex rating = more stiff). Reviewers preferred racquets with higher swing weights and lower flex ratings. This means that they preferred racquets that are more powerful, harder to swing, and less stiff. While I will continue on and trust the reviewer scores, it is worth noting that by using reviewer scores, the racquets that will be recommended are more likely to be higher swing weight and less stiff. </span>
<span id="cb67-310"><a href="#cb67-310" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-311"><a href="#cb67-311" aria-hidden="true" tabindex="-1"></a>I will start by looking at the racquet's overall scores as I don't want to choose a racquet that has on overall poor review.</span>
<span id="cb67-312"><a href="#cb67-312" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-315"><a href="#cb67-315" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb67-316"><a href="#cb67-316" aria-hidden="true" tabindex="-1"></a><span class="co">#First convert Overall column to numeric </span></span>
<span id="cb67-317"><a href="#cb67-317" aria-hidden="true" tabindex="-1"></a>my_racquets<span class="sc">$</span>Overall <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(my_racquets<span class="sc">$</span>Overall)</span>
<span id="cb67-318"><a href="#cb67-318" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-319"><a href="#cb67-319" aria-hidden="true" tabindex="-1"></a><span class="co">#Plot occurrences of different overall scores</span></span>
<span id="cb67-320"><a href="#cb67-320" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(my_racquets, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">`</span><span class="at">Overall</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb67-321"><a href="#cb67-321" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">na.rm =</span> T) <span class="sc">+</span></span>
<span id="cb67-322"><a href="#cb67-322" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">stat =</span> <span class="st">"count"</span>, <span class="fu">aes</span>(<span class="at">label =</span> ..count..), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb67-323"><a href="#cb67-323" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Overall Score"</span>, <span class="at">y =</span> <span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb67-324"><a href="#cb67-324" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Occurrences of Overall Scores"</span>)</span>
<span id="cb67-325"><a href="#cb67-325" aria-hidden="true" tabindex="-1"></a><span class="co">#Get summary statistics for the overall scores column</span></span>
<span id="cb67-326"><a href="#cb67-326" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(my_racquets<span class="sc">$</span>Overall) </span>
<span id="cb67-327"><a href="#cb67-327" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-328"><a href="#cb67-328" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb67-329"><a href="#cb67-329" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-330"><a href="#cb67-330" aria-hidden="true" tabindex="-1"></a>By looking at the graph, we can get an idea of where most racquets fall in overall score. </span>
<span id="cb67-331"><a href="#cb67-331" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-332"><a href="#cb67-332" aria-hidden="true" tabindex="-1"></a>As before, the median and mean are similar here (83 overall score), so I'll remove all racquets with an overall score of less than 83.</span>
<span id="cb67-333"><a href="#cb67-333" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-336"><a href="#cb67-336" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb67-337"><a href="#cb67-337" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter out racquets with an overall score of less than 83 </span></span>
<span id="cb67-338"><a href="#cb67-338" aria-hidden="true" tabindex="-1"></a>my_racquets <span class="ot">&lt;-</span> my_racquets <span class="sc">%&gt;%</span> </span>
<span id="cb67-339"><a href="#cb67-339" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Overall <span class="sc">&gt;</span> <span class="dv">83</span>)</span>
<span id="cb67-340"><a href="#cb67-340" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-341"><a href="#cb67-341" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb67-342"><a href="#cb67-342" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-343"><a href="#cb67-343" aria-hidden="true" tabindex="-1"></a>Now that there are only 16 racquets left in the data set, it's time to get more specific about what type of racquet I'm looking for and what might suit my game style. Other than an overall score, there are 12 other categories that reviewers assigned scores for each racquet. To predict which racquet will best suit my game style, I'll weight the scores of the racquets differently based on how important they are for my game style and what I want out of a racquet.</span>
<span id="cb67-344"><a href="#cb67-344" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-345"><a href="#cb67-345" aria-hidden="true" tabindex="-1"></a>Without getting too far into the details of my game style, I've broken the 12 categories into 3 tiers based on how important they are for selecting my racquet. </span>
<span id="cb67-346"><a href="#cb67-346" aria-hidden="true" tabindex="-1"></a>Tier 1: Power, Control, Touch/Feel, and Groundstrokes</span>
<span id="cb67-347"><a href="#cb67-347" aria-hidden="true" tabindex="-1"></a>Tier 2: Maneuvarability, Returns, Serves, and Topspin </span>
<span id="cb67-348"><a href="#cb67-348" aria-hidden="true" tabindex="-1"></a>Tier 3: Comfort, Volleys, Slice, and Stability </span>
<span id="cb67-349"><a href="#cb67-349" aria-hidden="true" tabindex="-1"></a>For Tier 1, I will multiply each score by 1.1, Tier 2 by 1.0, and Tier 3 by 0.9 to produced weighted values for each category.</span>
<span id="cb67-350"><a href="#cb67-350" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-353"><a href="#cb67-353" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb67-354"><a href="#cb67-354" aria-hidden="true" tabindex="-1"></a><span class="co"># Mutate the dataframe to reflect the new weighted scoring </span></span>
<span id="cb67-355"><a href="#cb67-355" aria-hidden="true" tabindex="-1"></a>my_racquets <span class="ot">&lt;-</span> my_racquets <span class="sc">%&gt;%</span> </span>
<span id="cb67-356"><a href="#cb67-356" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Power_weight =</span> Power <span class="sc">*</span> <span class="fl">1.1</span>, <span class="at">Control_weight =</span> Control <span class="sc">*</span> <span class="fl">1.1</span>, <span class="st">`</span><span class="at">Touch/Feel_weight</span><span class="st">`</span> <span class="ot">=</span> <span class="st">`</span><span class="at">Touch/Feel</span><span class="st">`</span> <span class="sc">*</span> <span class="fl">1.1</span>, <span class="at">Groundstrokes_weight =</span> Groundstrokes <span class="sc">*</span> <span class="fl">1.1</span>, <span class="at">Maneuverability_weight =</span> Maneuverability, <span class="at">Returns_weight =</span> Returns, <span class="at">Serves_weight =</span> Serves, <span class="at">Topspin_weight =</span> Topspin, <span class="at">Comfort_weight =</span> Comfort <span class="sc">*</span> <span class="fl">0.9</span>, <span class="at">Volleys_weight =</span> Volleys <span class="sc">*</span> <span class="fl">0.9</span>, <span class="at">Slice_weight =</span> Slice <span class="sc">*</span> <span class="fl">0.9</span>, <span class="at">Stability_weight =</span> Stability <span class="sc">*</span> <span class="fl">0.9</span>) </span>
<span id="cb67-357"><a href="#cb67-357" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a final overall score column that reflects the weighted reviewer scores</span></span>
<span id="cb67-358"><a href="#cb67-358" aria-hidden="true" tabindex="-1"></a>my_racquets<span class="sc">$</span>Final_Score <span class="ot">&lt;-</span> <span class="fu">rowSums</span>(my_racquets[, <span class="dv">25</span><span class="sc">:</span><span class="dv">36</span>])<span class="sc">/</span><span class="dv">12</span> </span>
<span id="cb67-359"><a href="#cb67-359" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb67-360"><a href="#cb67-360" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-361"><a href="#cb67-361" aria-hidden="true" tabindex="-1"></a>Let's look at a graph of the racquets by final overall score. Hover over each dot to see the racquet and its score.  </span>
<span id="cb67-362"><a href="#cb67-362" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-365"><a href="#cb67-365" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb67-366"><a href="#cb67-366" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a scatter plot of racquets by final overall score</span></span>
<span id="cb67-367"><a href="#cb67-367" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(my_racquets, <span class="fu">aes</span>(<span class="at">x =</span> Racquet, <span class="at">y =</span> Final_Score, <span class="at">label =</span> Racquet)) <span class="sc">+</span> </span>
<span id="cb67-368"><a href="#cb67-368" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Racquet"</span>, <span class="at">y =</span> <span class="st">"Final Overall Score"</span>) <span class="sc">+</span></span>
<span id="cb67-369"><a href="#cb67-369" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb67-370"><a href="#cb67-370" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span> </span>
<span id="cb67-371"><a href="#cb67-371" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x=</span><span class="fu">element_blank</span>()) <span class="sc">+</span> </span>
<span id="cb67-372"><a href="#cb67-372" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Final Overall Racquet Score"</span>)</span>
<span id="cb67-373"><a href="#cb67-373" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-374"><a href="#cb67-374" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplotly</span>(p, <span class="at">tooltip =</span> <span class="fu">c</span>(<span class="st">"x"</span>, <span class="st">"y"</span>))</span>
<span id="cb67-375"><a href="#cb67-375" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-376"><a href="#cb67-376" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb67-377"><a href="#cb67-377" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-378"><a href="#cb67-378" aria-hidden="true" tabindex="-1"></a>Now that we have a final overall score that better reflects how a racquet suits my game style, we can pull out the top rated racquets. Since it's always best to try before you buy, I'll pull out the top 4 racquets so that I can try those before making my final purchase. </span>
<span id="cb67-379"><a href="#cb67-379" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-380"><a href="#cb67-380" aria-hidden="true" tabindex="-1"></a><span class="fu">### Choosing the final racquets</span></span>
<span id="cb67-381"><a href="#cb67-381" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-384"><a href="#cb67-384" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb67-385"><a href="#cb67-385" aria-hidden="true" tabindex="-1"></a><span class="co"># Make a new data frame with just the top 4 racquets based on the Final_Score column</span></span>
<span id="cb67-386"><a href="#cb67-386" aria-hidden="true" tabindex="-1"></a>final_racquets <span class="ot">&lt;-</span> my_racquets <span class="sc">%&gt;%</span> <span class="fu">top_n</span>(<span class="at">n =</span> <span class="dv">4</span>, <span class="at">wt =</span> Final_Score) </span>
<span id="cb67-387"><a href="#cb67-387" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the racquet names</span></span>
<span id="cb67-388"><a href="#cb67-388" aria-hidden="true" tabindex="-1"></a>final_racquets<span class="sc">$</span>Racquet</span>
<span id="cb67-389"><a href="#cb67-389" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb67-390"><a href="#cb67-390" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-391"><a href="#cb67-391" aria-hidden="true" tabindex="-1"></a><span class="fu">## Conclusion and Reflection </span></span>
<span id="cb67-392"><a href="#cb67-392" aria-hidden="true" tabindex="-1"></a>By using some freely available datasets, I've systematically narrowed down my search for a new tennis racquet from well over 100 to just 4. The marketplace for racquets is overwhelming both for myself and for many other individuals. Using the powerful programming language of R has made my tennis racquet search much easier. While most tennis players are unlikely to go through the steps I've shown here to help them find a new racquet, this code could be altered in a way that allows individuals to answer a series of questions about their game style and racquet preferences and result in having a few racquets suggested to them. </span>
<span id="cb67-393"><a href="#cb67-393" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-394"><a href="#cb67-394" aria-hidden="true" tabindex="-1"></a>I also created code that shows how certain tennis racquet characteristics are related to one another and how they vary across racquets. There are other features of racquets in the data sets that were not examined here, but could be explored further in future analyses or if this code/data were actually turned into a tool for the use of more individuals. </span>
<span id="cb67-395"><a href="#cb67-395" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-396"><a href="#cb67-396" aria-hidden="true" tabindex="-1"></a><span class="fu">## Bibliography </span></span>
<span id="cb67-397"><a href="#cb67-397" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-398"><a href="#cb67-398" aria-hidden="true" tabindex="-1"></a>Tennis Warehouse. (2023). Reviewed Racquets - Tennis Warehouse. https://www.tennis-warehouse.com/reviewedracquets.html </span>
<span id="cb67-399"><a href="#cb67-399" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-400"><a href="#cb67-400" aria-hidden="true" tabindex="-1"></a>Farthing, T. (2020, February 5). Tennis racket specifications explained. Tennishead. https://tennishead.net/tennis-racket-specifications-explained/ </span>
<span id="cb67-401"><a href="#cb67-401" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-402"><a href="#cb67-402" aria-hidden="true" tabindex="-1"></a>R Core Team. (2023). R: A language and environment for statistical computing (Version 4.1.1) <span class="co">[</span><span class="ot">Computer software</span><span class="co">]</span>. Retrieved from https://www.R-project.org/</span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>