---
title: "Read and describe dataset"
author: "Neha Jhurani"
desription: "Import and analysize the dataset: birds.csv, wild_bird_data.xlsx using R commands"
date: "02/22/2023"
format:
  html:
    toc: true
    code-fold: true
    code-copy: true
    code-tools: true
categories:
  - challenge1
  - Neha Jhurani
  - birds.csv, wild_bird_data.xlsx
---

```{r}
#| label: setup
#| warning: false

library(tidyverse)

knitr::opts_chunk$set(echo = TRUE)
```

## Analysing birds data

```{r}
library(readr)

#reading birds csv data
birds_data <- read_csv("_data/birds.csv")

#visualizing birds data in spreadsheet style
view(birds_data)

#getting the number of rows and columns in the csv
dim(birds_data)

#viewing the last few rows of the birds data
tail(birds_data)

#extracting all the column names
colnames(birds_data)

#selecting only the unique values of Item column
unique(select(birds_data, c("Item")))

#filtering all the rows which has the Year as 2018
filter(birds_data, Year == "2018")

#finding the mean value for each item in a specific area during a specific year
birds_data %>% group_by(Year,Area,Item) %>% summarise(mean(Value), .groups = 'drop')

#summarizing the values in each column of birds data, It gives us (minimum, 1st quartile, median, mean, 3rd quartile, maximum, number of NA's present) for a column that has numerical values and gives (length, class, mode) for a column that has character values
summary(birds_data)
```

## Analysing wild birds data

```{r}
library(readxl)

#reading wild_bird_data xlsx
wild_bird_data <- read_xlsx("_data/wild_bird_data.xlsx")

#visualizing wild bird data in spreadsheet style
view(wild_bird_data)

#extracting the number of rows and columns in the excel
dim(wild_bird_data)

#viewing the last 10 rows of wild bird data
tail(wild_bird_data, n = 10)

#extracting all the column names
colnames(wild_bird_data)

#extracting a subset of wild bird data
wild_bird_data[4:12,]

```