<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Priyanka Perumalla">
<meta name="dcterms.date" content="2023-05-21">
<meta name="description" content="Data Science and STEM Salaries Analysis">

<title>DACCS 601 Final Project</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../images/DACSS_Round_Network.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

<link href="../site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">
<script src="../site_libs/pagedtable-1.1/js/pagedtable.js"></script>


<link rel="stylesheet" href="styles.css">
<meta name="twitter:title" content="DACCS 601 Final Project">
<meta name="twitter:description" content="Data Science and STEM Salaries Analysis">
<meta name="twitter:image" content="https://dacss.github.io/601_Spring_2023/posts/PriyankaPerumalla_final_project_files/figure-html/unnamed-chunk-15-1.png">
<meta name="twitter:creator" content="@UMassDACSS">
<meta name="twitter:site" content="@UMassDACSS">
<meta name="twitter:image-height" content="960">
<meta name="twitter:image-width" content="1344">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../images/UMass White Wordmark Horiz.png" alt="" class="navbar-logo">
    </a>
  </div>
            <div id="quarto-search" class="" title="true"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://github.com/DACSS" rel="" target="">
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html" rel="" target="">
 <span class="menu-text">Contributors</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://umass.edu/sbs/dacss" rel="" target="">
 <span class="menu-text">DACSS</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/DACSS" rel="" target=""><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#data-description" id="toc-data-description" class="nav-link" data-scroll-target="#data-description">Data Description</a>
  <ul class="collapse">
  <li><a href="#data-tidying-and-mutation" id="toc-data-tidying-and-mutation" class="nav-link" data-scroll-target="#data-tidying-and-mutation">Data tidying and mutation</a></li>
  <li><a href="#potential-research-questions" id="toc-potential-research-questions" class="nav-link" data-scroll-target="#potential-research-questions">Potential research questions</a></li>
  <li><a href="#education-level-vs-number-of-people" id="toc-education-level-vs-number-of-people" class="nav-link" data-scroll-target="#education-level-vs-number-of-people">Education level vs number of people</a></li>
  <li><a href="#education-level-vs-salary-vs-gender" id="toc-education-level-vs-salary-vs-gender" class="nav-link" data-scroll-target="#education-level-vs-salary-vs-gender">Education level vs Salary vs Gender</a></li>
  <li><a href="#salary-vs-education-level" id="toc-salary-vs-education-level" class="nav-link" data-scroll-target="#salary-vs-education-level">Salary vs Education level</a></li>
  </ul></li>
  <li><a href="#average-total-compensation-for-different-years" id="toc-average-total-compensation-for-different-years" class="nav-link" data-scroll-target="#average-total-compensation-for-different-years">Average Total Compensation for different years :</a>
  <ul class="collapse">
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">CONCLUSION</a></li>
  <li><a href="#reflection" id="toc-reflection" class="nav-link" data-scroll-target="#reflection">Reflection</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">DACCS 601 Final Project</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
  <div class="quarto-categories">
    <div class="quarto-category">final_Project_assignment</div>
    <div class="quarto-category">final_project</div>
    <div class="quarto-category">Priyanka Perumalla</div>
    <div class="quarto-category">Data Science and STEM salary dataset</div>
    <div class="quarto-category">Tech Salary</div>
  </div>
  </div>

<div>
  <div class="description">
    Data Science and STEM Salaries Analysis
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Priyanka Perumalla </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 21, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(summarytools)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">TRUE</span>, <span class="at">warning=</span><span class="cn">FALSE</span>, <span class="at">message=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>The dataset I am analyzing, “The Data Science and STEM Salaries Dataset,” is sourced from levels.fyi. Levels.fyi is a platform that collects and provides information on job levels, salaries, and compensation packages in various companies and industries. The dataset represents salary and compensation information for individuals working in data science and STEM (Science, Technology, Engineering, and Mathematics) fields.</p>
<p>Each row in the dataset represents an individual case or observation, which corresponds to a specific person’s employment details and compensation information. The dataset includes columns such as timestamp (when the data was recorded), company (the company the individual works for), level (job level or position), title (job title), total yearly compensation, location (geographic location), years of experience, years at the company, various tags (related to skills or domains), base salary, stock grant value, bonus, gender, other details, city ID, designated market area (DMA) ID, row number, and information about the individual’s education and race.</p>
</section>
<section id="data-description" class="level2">
<h2 class="anchored" data-anchor-id="data-description">Data Description</h2>
<p>The dataset used in this analysis is sourced from levels.fyi, a platform that collects and provides information on job levels, salaries, and compensation packages. The data represents salary and compensation information specifically for data science and STEM (Science, Technology, Engineering, and Mathematics) roles. The data collection process on levels.fyi involves individuals voluntarily sharing their employment and compensation details. Users can submit their salary information, along with other relevant details, to contribute to the platform’s database. This crowd sourced approach allows for a diverse range of data to be collected, representing different companies, job levels, and locations. The dataset offers insights into the salaries and compensation packages received by data science and STEM professionals, enabling analysis and exploration of various factors that influence compensation in these fields.</p>
<p>Reading the dataset</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"PriyankaPerumalla_FinalProjectData/Levels_Fyi_Salary_Data.csv"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["timestamp"],"name":[1],"type":["chr"],"align":["left"]},{"label":["company"],"name":[2],"type":["chr"],"align":["left"]},{"label":["level"],"name":[3],"type":["chr"],"align":["left"]},{"label":["title"],"name":[4],"type":["chr"],"align":["left"]},{"label":["totalyearlycompensation"],"name":[5],"type":["int"],"align":["right"]},{"label":["location"],"name":[6],"type":["chr"],"align":["left"]},{"label":["yearsofexperience"],"name":[7],"type":["dbl"],"align":["right"]},{"label":["yearsatcompany"],"name":[8],"type":["dbl"],"align":["right"]},{"label":["tag"],"name":[9],"type":["chr"],"align":["left"]},{"label":["basesalary"],"name":[10],"type":["dbl"],"align":["right"]},{"label":["stockgrantvalue"],"name":[11],"type":["dbl"],"align":["right"]},{"label":["bonus"],"name":[12],"type":["dbl"],"align":["right"]},{"label":["gender"],"name":[13],"type":["chr"],"align":["left"]},{"label":["otherdetails"],"name":[14],"type":["chr"],"align":["left"]},{"label":["cityid"],"name":[15],"type":["int"],"align":["right"]},{"label":["dmaid"],"name":[16],"type":["int"],"align":["right"]},{"label":["rowNumber"],"name":[17],"type":["int"],"align":["right"]},{"label":["Masters_Degree"],"name":[18],"type":["int"],"align":["right"]},{"label":["Bachelors_Degree"],"name":[19],"type":["int"],"align":["right"]},{"label":["Doctorate_Degree"],"name":[20],"type":["int"],"align":["right"]},{"label":["Highschool"],"name":[21],"type":["int"],"align":["right"]},{"label":["Some_College"],"name":[22],"type":["int"],"align":["right"]},{"label":["Race_Asian"],"name":[23],"type":["int"],"align":["right"]},{"label":["Race_White"],"name":[24],"type":["int"],"align":["right"]},{"label":["Race_Two_Or_More"],"name":[25],"type":["int"],"align":["right"]},{"label":["Race_Black"],"name":[26],"type":["int"],"align":["right"]},{"label":["Race_Hispanic"],"name":[27],"type":["int"],"align":["right"]},{"label":["Race"],"name":[28],"type":["chr"],"align":["left"]},{"label":["Education"],"name":[29],"type":["chr"],"align":["left"]}],"data":[{"1":"6/7/2017 11:33:27","2":"Oracle","3":"L3","4":"Product Manager","5":"127000","6":"Redwood City, CA","7":"1.5","8":"1.5","9":"NA","10":"107000","11":"20000","12":"10000","13":"NA","14":"NA","15":"7392","16":"807","17":"1","18":"0","19":"0","20":"0","21":"0","22":"0","23":"0","24":"0","25":"0","26":"0","27":"0","28":"NA","29":"NA","_rn_":"1"},{"1":"6/10/2017 17:11:29","2":"eBay","3":"SE 2","4":"Software Engineer","5":"100000","6":"San Francisco, CA","7":"5.0","8":"3.0","9":"NA","10":"0","11":"0","12":"0","13":"NA","14":"NA","15":"7419","16":"807","17":"2","18":"0","19":"0","20":"0","21":"0","22":"0","23":"0","24":"0","25":"0","26":"0","27":"0","28":"NA","29":"NA","_rn_":"2"},{"1":"6/11/2017 14:53:57","2":"Amazon","3":"L7","4":"Product Manager","5":"310000","6":"Seattle, WA","7":"8.0","8":"0.0","9":"NA","10":"155000","11":"0","12":"0","13":"NA","14":"NA","15":"11527","16":"819","17":"3","18":"0","19":"0","20":"0","21":"0","22":"0","23":"0","24":"0","25":"0","26":"0","27":"0","28":"NA","29":"NA","_rn_":"3"},{"1":"6/17/2017 0:23:14","2":"Apple","3":"M1","4":"Software Engineering Manager","5":"372000","6":"Sunnyvale, CA","7":"7.0","8":"5.0","9":"NA","10":"157000","11":"180000","12":"35000","13":"NA","14":"NA","15":"7472","16":"807","17":"7","18":"0","19":"0","20":"0","21":"0","22":"0","23":"0","24":"0","25":"0","26":"0","27":"0","28":"NA","29":"NA","_rn_":"4"},{"1":"6/20/2017 10:58:51","2":"Microsoft","3":"60","4":"Software Engineer","5":"157000","6":"Mountain View, CA","7":"5.0","8":"3.0","9":"NA","10":"0","11":"0","12":"0","13":"NA","14":"NA","15":"7322","16":"807","17":"9","18":"0","19":"0","20":"0","21":"0","22":"0","23":"0","24":"0","25":"0","26":"0","27":"0","28":"NA","29":"NA","_rn_":"5"},{"1":"6/21/2017 17:27:47","2":"Microsoft","3":"63","4":"Software Engineer","5":"208000","6":"Seattle, WA","7":"8.5","8":"8.5","9":"NA","10":"0","11":"0","12":"0","13":"NA","14":"NA","15":"11527","16":"819","17":"11","18":"0","19":"0","20":"0","21":"0","22":"0","23":"0","24":"0","25":"0","26":"0","27":"0","28":"NA","29":"NA","_rn_":"6"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>Presenting the descriptive information of the dataset. Like what all columns are present and what all information is present in every column. The nature of every column can be viewed through this sample data.</p>
<pre><code>::: {.cell}

```{.r .cell-code}
head(data)
```

::: {.cell-output-display}

`````{=html}
&lt;div data-pagedtable="false"&gt;
  &lt;script data-pagedtable-source type="application/json"&gt;
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["timestamp"],"name":[1],"type":["chr"],"align":["left"]},{"label":["company"],"name":[2],"type":["chr"],"align":["left"]},{"label":["level"],"name":[3],"type":["chr"],"align":["left"]},{"label":["title"],"name":[4],"type":["chr"],"align":["left"]},{"label":["totalyearlycompensation"],"name":[5],"type":["int"],"align":["right"]},{"label":["location"],"name":[6],"type":["chr"],"align":["left"]},{"label":["yearsofexperience"],"name":[7],"type":["dbl"],"align":["right"]},{"label":["yearsatcompany"],"name":[8],"type":["dbl"],"align":["right"]},{"label":["tag"],"name":[9],"type":["chr"],"align":["left"]},{"label":["basesalary"],"name":[10],"type":["dbl"],"align":["right"]},{"label":["stockgrantvalue"],"name":[11],"type":["dbl"],"align":["right"]},{"label":["bonus"],"name":[12],"type":["dbl"],"align":["right"]},{"label":["gender"],"name":[13],"type":["chr"],"align":["left"]},{"label":["otherdetails"],"name":[14],"type":["chr"],"align":["left"]},{"label":["cityid"],"name":[15],"type":["int"],"align":["right"]},{"label":["dmaid"],"name":[16],"type":["int"],"align":["right"]},{"label":["rowNumber"],"name":[17],"type":["int"],"align":["right"]},{"label":["Masters_Degree"],"name":[18],"type":["int"],"align":["right"]},{"label":["Bachelors_Degree"],"name":[19],"type":["int"],"align":["right"]},{"label":["Doctorate_Degree"],"name":[20],"type":["int"],"align":["right"]},{"label":["Highschool"],"name":[21],"type":["int"],"align":["right"]},{"label":["Some_College"],"name":[22],"type":["int"],"align":["right"]},{"label":["Race_Asian"],"name":[23],"type":["int"],"align":["right"]},{"label":["Race_White"],"name":[24],"type":["int"],"align":["right"]},{"label":["Race_Two_Or_More"],"name":[25],"type":["int"],"align":["right"]},{"label":["Race_Black"],"name":[26],"type":["int"],"align":["right"]},{"label":["Race_Hispanic"],"name":[27],"type":["int"],"align":["right"]},{"label":["Race"],"name":[28],"type":["chr"],"align":["left"]},{"label":["Education"],"name":[29],"type":["chr"],"align":["left"]}],"data":[{"1":"6/7/2017 11:33:27","2":"Oracle","3":"L3","4":"Product Manager","5":"127000","6":"Redwood City, CA","7":"1.5","8":"1.5","9":"NA","10":"107000","11":"20000","12":"10000","13":"NA","14":"NA","15":"7392","16":"807","17":"1","18":"0","19":"0","20":"0","21":"0","22":"0","23":"0","24":"0","25":"0","26":"0","27":"0","28":"NA","29":"NA","_rn_":"1"},{"1":"6/10/2017 17:11:29","2":"eBay","3":"SE 2","4":"Software Engineer","5":"100000","6":"San Francisco, CA","7":"5.0","8":"3.0","9":"NA","10":"0","11":"0","12":"0","13":"NA","14":"NA","15":"7419","16":"807","17":"2","18":"0","19":"0","20":"0","21":"0","22":"0","23":"0","24":"0","25":"0","26":"0","27":"0","28":"NA","29":"NA","_rn_":"2"},{"1":"6/11/2017 14:53:57","2":"Amazon","3":"L7","4":"Product Manager","5":"310000","6":"Seattle, WA","7":"8.0","8":"0.0","9":"NA","10":"155000","11":"0","12":"0","13":"NA","14":"NA","15":"11527","16":"819","17":"3","18":"0","19":"0","20":"0","21":"0","22":"0","23":"0","24":"0","25":"0","26":"0","27":"0","28":"NA","29":"NA","_rn_":"3"},{"1":"6/17/2017 0:23:14","2":"Apple","3":"M1","4":"Software Engineering Manager","5":"372000","6":"Sunnyvale, CA","7":"7.0","8":"5.0","9":"NA","10":"157000","11":"180000","12":"35000","13":"NA","14":"NA","15":"7472","16":"807","17":"7","18":"0","19":"0","20":"0","21":"0","22":"0","23":"0","24":"0","25":"0","26":"0","27":"0","28":"NA","29":"NA","_rn_":"4"},{"1":"6/20/2017 10:58:51","2":"Microsoft","3":"60","4":"Software Engineer","5":"157000","6":"Mountain View, CA","7":"5.0","8":"3.0","9":"NA","10":"0","11":"0","12":"0","13":"NA","14":"NA","15":"7322","16":"807","17":"9","18":"0","19":"0","20":"0","21":"0","22":"0","23":"0","24":"0","25":"0","26":"0","27":"0","28":"NA","29":"NA","_rn_":"5"},{"1":"6/21/2017 17:27:47","2":"Microsoft","3":"63","4":"Software Engineer","5":"208000","6":"Seattle, WA","7":"8.5","8":"8.5","9":"NA","10":"0","11":"0","12":"0","13":"NA","14":"NA","15":"11527","16":"819","17":"11","18":"0","19":"0","20":"0","21":"0","22":"0","23":"0","24":"0","25":"0","26":"0","27":"0","28":"NA","29":"NA","_rn_":"6"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  &lt;/script&gt;
&lt;/div&gt;
`````

:::
:::</code></pre>
<p>On,analysing the dimensions of the data set. We see that the dataset has 62642 rows to begin with and 29 distinct columns.</p>
<pre><code>::: {.cell}

```{.r .cell-code}
dim(data)
```

::: {.cell-output .cell-output-stdout}
```
[1] 62642    29
```
:::
:::</code></pre>
<p>Checking to see if any columns are repeating. We can notice that all the 29 columns ar eunique</p>
<pre><code>::: {.cell}

```{.r .cell-code}
length(unique(data))
```

::: {.cell-output .cell-output-stdout}
```
[1] 29
```
:::
:::</code></pre>
<p>Taking a look on what all columns are present in the dataset.</p>
<pre><code>::: {.cell}

```{.r .cell-code}
colnames(data)
```

::: {.cell-output .cell-output-stdout}
```
 [1] "timestamp"               "company"                
 [3] "level"                   "title"                  
 [5] "totalyearlycompensation" "location"               
 [7] "yearsofexperience"       "yearsatcompany"         
 [9] "tag"                     "basesalary"             
[11] "stockgrantvalue"         "bonus"                  
[13] "gender"                  "otherdetails"           
[15] "cityid"                  "dmaid"                  
[17] "rowNumber"               "Masters_Degree"         
[19] "Bachelors_Degree"        "Doctorate_Degree"       
[21] "Highschool"              "Some_College"           
[23] "Race_Asian"              "Race_White"             
[25] "Race_Two_Or_More"        "Race_Black"             
[27] "Race_Hispanic"           "Race"                   
[29] "Education"              
```
:::
:::</code></pre>
<p>Understanding the data:</p>
<p>The data set contains information from the “Data Science and STEM Salaries” data collected by levels.fyi. It consists of 62642 rows, representing as many as 62642 participants who volunteered to enter information in Levels.fyi. The data set contains 29 columns that capture various attributes of the participants and their responses.</p>
<ol type="1">
<li>timestamp - The timestamp indicates when the survey response was recorded.</li>
<li>company - This column represents the name of the company where the particpant is employed.</li>
<li>level - It denotes the career level or seniority of the participant.</li>
<li>title - This column specifies the job title or position held by the participant.</li>
<li>totalyearlycompensation - It represents the total annual compensation of the participant, including salary, stock grants, and bonuses.</li>
<li>location - This column indicates the geographical location of the participant.</li>
<li>yearsofexperience - It indicates the number of years of professional experience the participant has.</li>
<li>yearsatcompany - This column specifies the number of years the participant has been with their current company.</li>
<li>tag - The tag column may provide additional information or categorization related to the participant or their response.</li>
<li>basesalary - It represents the base salary component of the participant’s total yearly compensation.</li>
<li>stockgrantvalue - This column captures the value of stock grants included in the participant’s total yearly compensation.</li>
<li>bonus - It denotes the bonus amount included in the participant’s total yearly compensation.</li>
<li>gender - This column represents the gender of the participant.</li>
<li>otherdetails - The otherdetails column may contain additional information or details provided by the participant.</li>
<li>cityid - It indicates the city identifier associated with the participant’s location.</li>
<li>dmaid - The dmaid column represents the Designated Market Area (DMA) identifier, which relates to the participant’s location.</li>
<li>rowNumber - This column assigns a unique row number to each participant in the dataset.</li>
<li>Masters_Degree - This column captures whether the participant holds a Master’s degree.</li>
<li>Bachelors_Degree - It indicates whether the participant holds a Bachelor’s degree.</li>
<li>Doctorate_Degree - This column specifies whether the participant holds a Doctorate degree.</li>
<li>Highschool - It denotes whether the participant has completed high school education.</li>
<li>Some_College - This column represents whether the participant has attended college without completing a degree.</li>
<li>Race_Asian - It indicates whether the participant identifies as Asian.</li>
<li>Race_White - This column represents whether the participant identifies as White.</li>
<li>Race_Two_Or_More - It denotes whether the participant identifies as belonging to two or more races.</li>
<li>Race_Black - This column indicates whether the participant identifies as Black.</li>
<li>Race_Hispanic - It represents whether the participant identifies as Hispanic.</li>
<li>Race - This column captures the participant’s race or ethnic background.</li>
<li>Education - It denotes the highest level of formal education completed by the participant.</li>
</ol>
<section id="data-tidying-and-mutation" class="level3">
<h3 class="anchored" data-anchor-id="data-tidying-and-mutation">Data tidying and mutation</h3>
<p>To start off with any analysis the data needs to be tidy.</p>
<p>Loading the required libraries</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scales)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>annotate <span class="ot">&lt;-</span> ggplot2<span class="sc">::</span>annotate</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>I am trying to check if this data has any null values. As a next step, I have omitted the null values as they would not contribute positively to my analysis. After omitting the rows which have atleast one null value, I am left with 21575 rows and 29 columns.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(data))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 115356</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>data<span class="ot">&lt;-</span> <span class="fu">na.omit</span>(data)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 21575    29</code></pre>
</div>
</div>
<p>It can be noticed that the summary column for race and education level already exists. But the flag columns for every category of education and race also exist. This is a redundancy and such columns can be deleted. I am getting rid of the columns Race_Asian,Race_White, Race_Black,Race_Hispanic,Some_College,Highschool,Doctorate_Degree,Bachelors_Degree,Masters_Degree,otherdetails. My dataset now has 19 columns.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>data<span class="ot">&lt;-</span> <span class="fu">subset</span>(data, <span class="at">select =</span> <span class="sc">-</span><span class="fu">c</span>(Race_Asian,Race_White, Race_Black,Race_Hispanic,Some_College,Highschool,Doctorate_Degree,Bachelors_Degree,Masters_Degree,otherdetails) )</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 21575    19</code></pre>
</div>
</div>
<p>The location column in the dataset has the format ‘city,state,country’. But I would like to mutate this column to extract city,state and country columns separtely. After this mutation, I have 21 columns.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>data<span class="ot">&lt;-</span><span class="fu">separate</span>(<span class="at">data =</span> data, <span class="at">col =</span> location, <span class="at">into =</span> <span class="fu">c</span>(<span class="st">"City"</span>, <span class="st">"State"</span>,<span class="st">"Country"</span>), <span class="at">sep =</span> <span class="st">","</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 21575    21</code></pre>
</div>
</div>
<p>The datetimestamp column in the dataset has the format ‘MM/DD/YYYY hh:mm:ss’. But I would like to mutate this column to extract Date and time separtely. After this mutation, I have 22 columns.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>data<span class="ot">&lt;-</span><span class="fu">separate</span>(<span class="at">data =</span> data, <span class="at">col =</span> timestamp, <span class="at">into =</span> <span class="fu">c</span>(<span class="st">"Date "</span>, <span class="st">"Time"</span>), <span class="at">sep =</span> <span class="st">" "</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 21575    22</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["Date "],"name":[1],"type":["chr"],"align":["left"]},{"label":["Time"],"name":[2],"type":["chr"],"align":["left"]},{"label":["company"],"name":[3],"type":["chr"],"align":["left"]},{"label":["level"],"name":[4],"type":["chr"],"align":["left"]},{"label":["title"],"name":[5],"type":["chr"],"align":["left"]},{"label":["totalyearlycompensation"],"name":[6],"type":["int"],"align":["right"]},{"label":["City"],"name":[7],"type":["chr"],"align":["left"]},{"label":["State"],"name":[8],"type":["chr"],"align":["left"]},{"label":["Country"],"name":[9],"type":["chr"],"align":["left"]},{"label":["yearsofexperience"],"name":[10],"type":["dbl"],"align":["right"]},{"label":["yearsatcompany"],"name":[11],"type":["dbl"],"align":["right"]},{"label":["tag"],"name":[12],"type":["chr"],"align":["left"]},{"label":["basesalary"],"name":[13],"type":["dbl"],"align":["right"]},{"label":["stockgrantvalue"],"name":[14],"type":["dbl"],"align":["right"]},{"label":["bonus"],"name":[15],"type":["dbl"],"align":["right"]},{"label":["gender"],"name":[16],"type":["chr"],"align":["left"]},{"label":["cityid"],"name":[17],"type":["int"],"align":["right"]},{"label":["dmaid"],"name":[18],"type":["int"],"align":["right"]},{"label":["rowNumber"],"name":[19],"type":["int"],"align":["right"]},{"label":["Race_Two_Or_More"],"name":[20],"type":["int"],"align":["right"]},{"label":["Race"],"name":[21],"type":["chr"],"align":["left"]},{"label":["Education"],"name":[22],"type":["chr"],"align":["left"]}],"data":[{"1":"1/27/2020","2":"22:59:06","3":"Google","4":"L6","5":"Software Engineer","6":"400000","7":"Sunnyvale","8":"CA","9":"NA","10":"5","11":"5","12":"Distributed Systems (Back-End)","13":"210000","14":"145000","15":"45000","16":"Male","17":"7472","18":"807","19":"21208","20":"0","21":"Asian","22":"PhD","_rn_":"15711"},{"1":"7/3/2020","2":"19:56:38","3":"Microsoft","4":"61","5":"Software Engineer","6":"136000","7":"Redmond","8":"WA","9":"NA","10":"3","11":"2","12":"DevOps","13":"124000","14":"1000","15":"11000","16":"Male","17":"11521","18":"819","19":"32237","20":"1","21":"Two Or More","22":"Bachelor's Degree","_rn_":"23533"},{"1":"7/3/2020","2":"20:03:57","3":"Google","4":"L5","5":"Software Engineer","6":"337000","7":"San Bruno","8":"CA","9":"NA","10":"6","11":"6","12":"Full Stack","13":"177000","14":"125000","15":"36000","16":"Male","17":"7413","18":"807","19":"32239","20":"0","21":"Asian","22":"Bachelor's Degree","_rn_":"23534"},{"1":"7/3/2020","2":"20:05:37","3":"Microsoft","4":"62","5":"Software Engineer","6":"222000","7":"Seattle","8":"WA","9":"NA","10":"4","11":"4","12":"API Development (Back-End)","13":"164000","14":"38000","15":"20000","16":"Male","17":"11527","18":"819","19":"32240","20":"0","21":"Asian","22":"Master's Degree","_rn_":"23535"},{"1":"7/3/2020","2":"20:19:06","3":"Blend","4":"IC3","5":"Software Engineer","6":"187000","7":"San Francisco","8":"CA","9":"NA","10":"5","11":"0","12":"Full Stack","13":"165000","14":"22000","15":"0","16":"Male","17":"7419","18":"807","19":"32241","20":"0","21":"White","22":"Bachelor's Degree","_rn_":"23536"},{"1":"7/3/2020","2":"20:24:20","3":"Amazon","4":"L6","5":"Software Engineer","6":"310000","7":"Seattle","8":"WA","9":"NA","10":"15","11":"3","12":"ML / AI","13":"160000","14":"150000","15":"0","16":"Male","17":"11527","18":"819","19":"32243","20":"0","21":"Asian","22":"Bachelor's Degree","_rn_":"23538"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>The date column in the dataset has the format ‘MM/DD/YYYY’. But I would like to mutate this column further to extract month,day and year separtely. After this mutation, I have 24 columns.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>data<span class="ot">&lt;-</span><span class="fu">separate</span>(<span class="at">data =</span> data, <span class="at">col =</span> <span class="dv">1</span>, <span class="at">into =</span> <span class="fu">c</span>(<span class="st">"Month"</span>, <span class="st">"Day"</span>,<span class="st">"Year"</span>), <span class="at">sep =</span> <span class="st">"/"</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 21575    24</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["Month"],"name":[1],"type":["chr"],"align":["left"]},{"label":["Day"],"name":[2],"type":["chr"],"align":["left"]},{"label":["Year"],"name":[3],"type":["chr"],"align":["left"]},{"label":["Time"],"name":[4],"type":["chr"],"align":["left"]},{"label":["company"],"name":[5],"type":["chr"],"align":["left"]},{"label":["level"],"name":[6],"type":["chr"],"align":["left"]},{"label":["title"],"name":[7],"type":["chr"],"align":["left"]},{"label":["totalyearlycompensation"],"name":[8],"type":["int"],"align":["right"]},{"label":["City"],"name":[9],"type":["chr"],"align":["left"]},{"label":["State"],"name":[10],"type":["chr"],"align":["left"]},{"label":["Country"],"name":[11],"type":["chr"],"align":["left"]},{"label":["yearsofexperience"],"name":[12],"type":["dbl"],"align":["right"]},{"label":["yearsatcompany"],"name":[13],"type":["dbl"],"align":["right"]},{"label":["tag"],"name":[14],"type":["chr"],"align":["left"]},{"label":["basesalary"],"name":[15],"type":["dbl"],"align":["right"]},{"label":["stockgrantvalue"],"name":[16],"type":["dbl"],"align":["right"]},{"label":["bonus"],"name":[17],"type":["dbl"],"align":["right"]},{"label":["gender"],"name":[18],"type":["chr"],"align":["left"]},{"label":["cityid"],"name":[19],"type":["int"],"align":["right"]},{"label":["dmaid"],"name":[20],"type":["int"],"align":["right"]},{"label":["rowNumber"],"name":[21],"type":["int"],"align":["right"]},{"label":["Race_Two_Or_More"],"name":[22],"type":["int"],"align":["right"]},{"label":["Race"],"name":[23],"type":["chr"],"align":["left"]},{"label":["Education"],"name":[24],"type":["chr"],"align":["left"]}],"data":[{"1":"1","2":"27","3":"2020","4":"22:59:06","5":"Google","6":"L6","7":"Software Engineer","8":"400000","9":"Sunnyvale","10":"CA","11":"NA","12":"5","13":"5","14":"Distributed Systems (Back-End)","15":"210000","16":"145000","17":"45000","18":"Male","19":"7472","20":"807","21":"21208","22":"0","23":"Asian","24":"PhD","_rn_":"15711"},{"1":"7","2":"3","3":"2020","4":"19:56:38","5":"Microsoft","6":"61","7":"Software Engineer","8":"136000","9":"Redmond","10":"WA","11":"NA","12":"3","13":"2","14":"DevOps","15":"124000","16":"1000","17":"11000","18":"Male","19":"11521","20":"819","21":"32237","22":"1","23":"Two Or More","24":"Bachelor's Degree","_rn_":"23533"},{"1":"7","2":"3","3":"2020","4":"20:03:57","5":"Google","6":"L5","7":"Software Engineer","8":"337000","9":"San Bruno","10":"CA","11":"NA","12":"6","13":"6","14":"Full Stack","15":"177000","16":"125000","17":"36000","18":"Male","19":"7413","20":"807","21":"32239","22":"0","23":"Asian","24":"Bachelor's Degree","_rn_":"23534"},{"1":"7","2":"3","3":"2020","4":"20:05:37","5":"Microsoft","6":"62","7":"Software Engineer","8":"222000","9":"Seattle","10":"WA","11":"NA","12":"4","13":"4","14":"API Development (Back-End)","15":"164000","16":"38000","17":"20000","18":"Male","19":"11527","20":"819","21":"32240","22":"0","23":"Asian","24":"Master's Degree","_rn_":"23535"},{"1":"7","2":"3","3":"2020","4":"20:19:06","5":"Blend","6":"IC3","7":"Software Engineer","8":"187000","9":"San Francisco","10":"CA","11":"NA","12":"5","13":"0","14":"Full Stack","15":"165000","16":"22000","17":"0","18":"Male","19":"7419","20":"807","21":"32241","22":"0","23":"White","24":"Bachelor's Degree","_rn_":"23536"},{"1":"7","2":"3","3":"2020","4":"20:24:20","5":"Amazon","6":"L6","7":"Software Engineer","8":"310000","9":"Seattle","10":"WA","11":"NA","12":"15","13":"3","14":"ML / AI","15":"160000","16":"150000","17":"0","18":"Male","19":"11527","20":"819","21":"32243","22":"0","23":"Asian","24":"Bachelor's Degree","_rn_":"23538"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>I want to group salaries together into buckets for further analysis. I have kept the bucket size as $25,000 USD. I am trying get the count of people who fall into each of such compensation buckets.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Salary_bucket =</span> <span class="fu">case_when</span>(totalyearlycompensation <span class="sc">&gt;=</span><span class="dv">0</span> <span class="sc">&amp;</span> totalyearlycompensation <span class="sc">&lt;</span><span class="dv">25000</span> <span class="sc">~</span> <span class="st">"0-25k"</span>,</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  totalyearlycompensation <span class="sc">&gt;=</span><span class="dv">25000</span> <span class="sc">&amp;</span> totalyearlycompensation <span class="sc">&lt;</span><span class="dv">50000</span> <span class="sc">~</span> <span class="st">"25k-50k"</span>,</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  totalyearlycompensation <span class="sc">&gt;=</span><span class="dv">50000</span> <span class="sc">&amp;</span> totalyearlycompensation <span class="sc">&lt;</span><span class="dv">75000</span> <span class="sc">~</span> <span class="st">"50k-750k"</span>,</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>  totalyearlycompensation <span class="sc">&gt;=</span><span class="dv">75000</span> <span class="sc">&amp;</span> totalyearlycompensation <span class="sc">&lt;</span><span class="dv">100000</span> <span class="sc">~</span> <span class="st">"75k-100k"</span>,</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>  totalyearlycompensation <span class="sc">&gt;=</span><span class="dv">100000</span> <span class="sc">&amp;</span> totalyearlycompensation <span class="sc">&lt;</span><span class="dv">125000</span> <span class="sc">~</span> <span class="st">"100k-125k"</span>,                      </span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>  totalyearlycompensation <span class="sc">&gt;=</span><span class="dv">125000</span> <span class="sc">&amp;</span> totalyearlycompensation <span class="sc">&lt;</span><span class="dv">150000</span> <span class="sc">~</span> <span class="st">"125k-150k"</span>,</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>  totalyearlycompensation <span class="sc">&gt;=</span><span class="dv">150000</span> <span class="sc">&amp;</span> totalyearlycompensation <span class="sc">&lt;</span><span class="dv">175000</span> <span class="sc">~</span> <span class="st">"150k-175k"</span>,</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>  totalyearlycompensation <span class="sc">&gt;=</span><span class="dv">175000</span> <span class="sc">&amp;</span> totalyearlycompensation <span class="sc">&lt;</span><span class="dv">200000</span> <span class="sc">~</span> <span class="st">"175k-200k"</span>,</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>  totalyearlycompensation <span class="sc">&gt;=</span><span class="dv">200000</span> <span class="sc">&amp;</span> totalyearlycompensation <span class="sc">&lt;</span><span class="dv">225000</span> <span class="sc">~</span> <span class="st">"200k-225k"</span>,</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>  totalyearlycompensation <span class="sc">&gt;=</span><span class="dv">225000</span> <span class="sc">&amp;</span> totalyearlycompensation <span class="sc">&lt;</span><span class="dv">250000</span> <span class="sc">~</span> <span class="st">"225k-250k"</span>,</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>  totalyearlycompensation <span class="sc">&gt;=</span><span class="dv">250000</span> <span class="sc">&amp;</span> totalyearlycompensation <span class="sc">&lt;</span><span class="dv">275000</span> <span class="sc">~</span> <span class="st">"250k-275k"</span>,</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>  totalyearlycompensation <span class="sc">&gt;=</span><span class="dv">275000</span> <span class="sc">&amp;</span> totalyearlycompensation <span class="sc">&lt;</span><span class="dv">300000</span> <span class="sc">~</span> <span class="st">"275k-300k"</span>,</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>  totalyearlycompensation <span class="sc">&gt;=</span><span class="dv">300000</span> <span class="sc">&amp;</span> totalyearlycompensation <span class="sc">&lt;</span><span class="dv">325000</span> <span class="sc">~</span> <span class="st">"300k-325k"</span>,</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>  totalyearlycompensation <span class="sc">&gt;=</span><span class="dv">325000</span> <span class="sc">&amp;</span> totalyearlycompensation <span class="sc">&lt;</span><span class="dv">350000</span> <span class="sc">~</span> <span class="st">"325k-350k"</span>,</span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>  totalyearlycompensation <span class="sc">&gt;=</span><span class="dv">350000</span> <span class="sc">&amp;</span> totalyearlycompensation <span class="sc">&lt;</span><span class="dv">375000</span> <span class="sc">~</span> <span class="st">"350k-375k"</span>,</span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>  totalyearlycompensation <span class="sc">&gt;=</span><span class="dv">375000</span> <span class="sc">&amp;</span> totalyearlycompensation <span class="sc">&lt;</span><span class="dv">400000</span> <span class="sc">~</span> <span class="st">"375k-400k"</span>,</span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>  totalyearlycompensation <span class="sc">&gt;=</span><span class="dv">400000</span> <span class="sc">&amp;</span> totalyearlycompensation <span class="sc">&lt;</span><span class="dv">425000</span> <span class="sc">~</span> <span class="st">"400k-425k"</span>,</span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a>  totalyearlycompensation <span class="sc">&gt;=</span><span class="dv">425000</span> <span class="sc">&amp;</span> totalyearlycompensation <span class="sc">&lt;</span><span class="dv">450000</span> <span class="sc">~</span> <span class="st">"425k-450k"</span>,</span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a>  totalyearlycompensation <span class="sc">&gt;=</span><span class="dv">450000</span> <span class="sc">&amp;</span> totalyearlycompensation <span class="sc">&lt;</span><span class="dv">475000</span> <span class="sc">~</span> <span class="st">"450k-475k"</span>,</span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a>  totalyearlycompensation <span class="sc">&gt;=</span><span class="dv">475000</span> <span class="sc">&amp;</span> totalyearlycompensation <span class="sc">&lt;</span><span class="dv">500000</span> <span class="sc">~</span> <span class="st">"475k-500k"</span>,</span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a>  totalyearlycompensation <span class="sc">&gt;=</span><span class="dv">500000</span> <span class="sc">~</span> <span class="st">"500k+"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>#conduct summary statistics of the dataset(s)</p>
<p>Now that the data is clean, tidy and all set for analysis, I would like to now view the summary statistics of the cleaned dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summarise_all</span>(data, mean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["Month"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["Day"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["Year"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["Time"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["company"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["level"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["title"],"name":[7],"type":["dbl"],"align":["right"]},{"label":["totalyearlycompensation"],"name":[8],"type":["dbl"],"align":["right"]},{"label":["City"],"name":[9],"type":["dbl"],"align":["right"]},{"label":["State"],"name":[10],"type":["dbl"],"align":["right"]},{"label":["Country"],"name":[11],"type":["dbl"],"align":["right"]},{"label":["yearsofexperience"],"name":[12],"type":["dbl"],"align":["right"]},{"label":["yearsatcompany"],"name":[13],"type":["dbl"],"align":["right"]},{"label":["tag"],"name":[14],"type":["dbl"],"align":["right"]},{"label":["basesalary"],"name":[15],"type":["dbl"],"align":["right"]},{"label":["stockgrantvalue"],"name":[16],"type":["dbl"],"align":["right"]},{"label":["bonus"],"name":[17],"type":["dbl"],"align":["right"]},{"label":["gender"],"name":[18],"type":["dbl"],"align":["right"]},{"label":["cityid"],"name":[19],"type":["dbl"],"align":["right"]},{"label":["dmaid"],"name":[20],"type":["dbl"],"align":["right"]},{"label":["rowNumber"],"name":[21],"type":["dbl"],"align":["right"]},{"label":["Race_Two_Or_More"],"name":[22],"type":["dbl"],"align":["right"]},{"label":["Race"],"name":[23],"type":["dbl"],"align":["right"]},{"label":["Education"],"name":[24],"type":["dbl"],"align":["right"]},{"label":["Salary_bucket"],"name":[25],"type":["dbl"],"align":["right"]}],"data":[{"1":"NA","2":"NA","3":"NA","4":"NA","5":"NA","6":"NA","7":"NA","8":"197855","9":"NA","10":"NA","11":"NA","12":"7.122549","13":"2.704148","14":"NA","15":"133864.8","16":"44893.77","17":"18417.89","18":"NA","19":"10175.51","20":"561.1813","21":"59203.42","22":"0.03541136","23":"NA","24":"NA","25":"NA"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summarise_all</span>(data, min)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["Month"],"name":[1],"type":["chr"],"align":["left"]},{"label":["Day"],"name":[2],"type":["chr"],"align":["left"]},{"label":["Year"],"name":[3],"type":["chr"],"align":["left"]},{"label":["Time"],"name":[4],"type":["chr"],"align":["left"]},{"label":["company"],"name":[5],"type":["chr"],"align":["left"]},{"label":["level"],"name":[6],"type":["chr"],"align":["left"]},{"label":["title"],"name":[7],"type":["chr"],"align":["left"]},{"label":["totalyearlycompensation"],"name":[8],"type":["int"],"align":["right"]},{"label":["City"],"name":[9],"type":["chr"],"align":["left"]},{"label":["State"],"name":[10],"type":["chr"],"align":["left"]},{"label":["Country"],"name":[11],"type":["chr"],"align":["left"]},{"label":["yearsofexperience"],"name":[12],"type":["dbl"],"align":["right"]},{"label":["yearsatcompany"],"name":[13],"type":["dbl"],"align":["right"]},{"label":["tag"],"name":[14],"type":["chr"],"align":["left"]},{"label":["basesalary"],"name":[15],"type":["dbl"],"align":["right"]},{"label":["stockgrantvalue"],"name":[16],"type":["dbl"],"align":["right"]},{"label":["bonus"],"name":[17],"type":["dbl"],"align":["right"]},{"label":["gender"],"name":[18],"type":["chr"],"align":["left"]},{"label":["cityid"],"name":[19],"type":["int"],"align":["right"]},{"label":["dmaid"],"name":[20],"type":["int"],"align":["right"]},{"label":["rowNumber"],"name":[21],"type":["int"],"align":["right"]},{"label":["Race_Two_Or_More"],"name":[22],"type":["int"],"align":["right"]},{"label":["Race"],"name":[23],"type":["chr"],"align":["left"]},{"label":["Education"],"name":[24],"type":["chr"],"align":["left"]},{"label":["Salary_bucket"],"name":[25],"type":["chr"],"align":["left"]}],"data":[{"1":"1","2":"1","3":"2020","4":"0:00:04","5":" Google","6":"-","7":"Business Analyst","8":"10000","9":"Aachen","10":"AA","11":"NA","12":"0","13":"0","14":"#finance","15":"4000","16":"0","17":"0","18":"Female","19":"10","20":"0","21":"21208","22":"0","23":"Asian","24":"Bachelor's Degree","25":"0-25k"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summarise_all</span>(data, max)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["Month"],"name":[1],"type":["chr"],"align":["left"]},{"label":["Day"],"name":[2],"type":["chr"],"align":["left"]},{"label":["Year"],"name":[3],"type":["chr"],"align":["left"]},{"label":["Time"],"name":[4],"type":["chr"],"align":["left"]},{"label":["company"],"name":[5],"type":["chr"],"align":["left"]},{"label":["level"],"name":[6],"type":["chr"],"align":["left"]},{"label":["title"],"name":[7],"type":["chr"],"align":["left"]},{"label":["totalyearlycompensation"],"name":[8],"type":["int"],"align":["right"]},{"label":["City"],"name":[9],"type":["chr"],"align":["left"]},{"label":["State"],"name":[10],"type":["chr"],"align":["left"]},{"label":["Country"],"name":[11],"type":["chr"],"align":["left"]},{"label":["yearsofexperience"],"name":[12],"type":["dbl"],"align":["right"]},{"label":["yearsatcompany"],"name":[13],"type":["dbl"],"align":["right"]},{"label":["tag"],"name":[14],"type":["chr"],"align":["left"]},{"label":["basesalary"],"name":[15],"type":["dbl"],"align":["right"]},{"label":["stockgrantvalue"],"name":[16],"type":["dbl"],"align":["right"]},{"label":["bonus"],"name":[17],"type":["dbl"],"align":["right"]},{"label":["gender"],"name":[18],"type":["chr"],"align":["left"]},{"label":["cityid"],"name":[19],"type":["int"],"align":["right"]},{"label":["dmaid"],"name":[20],"type":["int"],"align":["right"]},{"label":["rowNumber"],"name":[21],"type":["int"],"align":["right"]},{"label":["Race_Two_Or_More"],"name":[22],"type":["int"],"align":["right"]},{"label":["Race"],"name":[23],"type":["chr"],"align":["left"]},{"label":["Education"],"name":[24],"type":["chr"],"align":["left"]},{"label":["Salary_bucket"],"name":[25],"type":["chr"],"align":["left"]}],"data":[{"1":"9","2":"9","3":"2021","4":"9:59:58","5":"Zynga","6":"專員","7":"Technical Program Manager","8":"4980000","9":"Zurich","10":"ZJ","11":"NA","12":"45","13":"40","14":"Z Systems","15":"9e+05","16":"954000","17":"9e+05","18":"Other","19":"47926","20":"881","21":"83875","22":"1","23":"White","24":"Some College","25":"75k-100k"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summarise_all</span>(data, median)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["Month"],"name":[1],"type":["chr"],"align":["left"]},{"label":["Day"],"name":[2],"type":["chr"],"align":["left"]},{"label":["Year"],"name":[3],"type":["chr"],"align":["left"]},{"label":["Time"],"name":[4],"type":["chr"],"align":["left"]},{"label":["company"],"name":[5],"type":["chr"],"align":["left"]},{"label":["level"],"name":[6],"type":["chr"],"align":["left"]},{"label":["title"],"name":[7],"type":["chr"],"align":["left"]},{"label":["totalyearlycompensation"],"name":[8],"type":["int"],"align":["right"]},{"label":["City"],"name":[9],"type":["chr"],"align":["left"]},{"label":["State"],"name":[10],"type":["chr"],"align":["left"]},{"label":["Country"],"name":[11],"type":["chr"],"align":["left"]},{"label":["yearsofexperience"],"name":[12],"type":["dbl"],"align":["right"]},{"label":["yearsatcompany"],"name":[13],"type":["dbl"],"align":["right"]},{"label":["tag"],"name":[14],"type":["chr"],"align":["left"]},{"label":["basesalary"],"name":[15],"type":["dbl"],"align":["right"]},{"label":["stockgrantvalue"],"name":[16],"type":["dbl"],"align":["right"]},{"label":["bonus"],"name":[17],"type":["dbl"],"align":["right"]},{"label":["gender"],"name":[18],"type":["chr"],"align":["left"]},{"label":["cityid"],"name":[19],"type":["int"],"align":["right"]},{"label":["dmaid"],"name":[20],"type":["int"],"align":["right"]},{"label":["rowNumber"],"name":[21],"type":["int"],"align":["right"]},{"label":["Race_Two_Or_More"],"name":[22],"type":["int"],"align":["right"]},{"label":["Race"],"name":[23],"type":["chr"],"align":["left"]},{"label":["Education"],"name":[24],"type":["chr"],"align":["left"]},{"label":["Salary_bucket"],"name":[25],"type":["chr"],"align":["left"]}],"data":[{"1":"5","2":"23","3":"2021","4":"17:47:38","5":"Google","6":"L4","7":"Software Engineer","8":"174000","9":"New York","10":"MA","11":"NA","12":"6","13":"2","14":"Full Stack","15":"135000","16":"20000","17":"13000","18":"Male","19":"8198","20":"751","21":"59844","22":"0","23":"Asian","24":"Bachelor's Degree","25":"200k-225k"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Month               Day                Year               Time          
 Length:21575       Length:21575       Length:21575       Length:21575      
 Class :character   Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character   Mode  :character  
                                                                            
                                                                            
                                                                            
   company             level              title          
 Length:21575       Length:21575       Length:21575      
 Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character  
                                                         
                                                         
                                                         
 totalyearlycompensation     City              State          
 Min.   :  10000         Length:21575       Length:21575      
 1st Qu.: 119000         Class :character   Class :character  
 Median : 174000         Mode  :character   Mode  :character  
 Mean   : 197855                                              
 3rd Qu.: 245000                                              
 Max.   :4980000                                              
   Country          yearsofexperience yearsatcompany       tag           
 Length:21575       Min.   : 0.000    Min.   : 0.000   Length:21575      
 Class :character   1st Qu.: 3.000    1st Qu.: 0.000   Class :character  
 Mode  :character   Median : 6.000    Median : 2.000   Mode  :character  
                    Mean   : 7.123    Mean   : 2.704                     
                    3rd Qu.:10.000    3rd Qu.: 4.000                     
                    Max.   :45.000    Max.   :40.000                     
   basesalary     stockgrantvalue      bonus           gender         
 Min.   :  4000   Min.   :     0   Min.   :     0   Length:21575      
 1st Qu.:100000   1st Qu.:     0   1st Qu.:  3000   Class :character  
 Median :135000   Median : 20000   Median : 13000   Mode  :character  
 Mean   :133865   Mean   : 44894   Mean   : 18418                     
 3rd Qu.:165000   3rd Qu.: 55000   3rd Qu.: 25000                     
 Max.   :900000   Max.   :954000   Max.   :900000                     
     cityid          dmaid         rowNumber     Race_Two_Or_More 
 Min.   :   10   Min.   :  0.0   Min.   :21208   Min.   :0.00000  
 1st Qu.: 7322   1st Qu.:501.0   1st Qu.:47069   1st Qu.:0.00000  
 Median : 8198   Median :751.0   Median :59844   Median :0.00000  
 Mean   :10176   Mean   :561.2   Mean   :59203   Mean   :0.03541  
 3rd Qu.:11521   3rd Qu.:807.0   3rd Qu.:71590   3rd Qu.:0.00000  
 Max.   :47926   Max.   :881.0   Max.   :83875   Max.   :1.00000  
     Race            Education         Salary_bucket     
 Length:21575       Length:21575       Length:21575      
 Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character  
                                                         
                                                         
                                                         </code></pre>
</div>
</div>
<p>I notice that the minimum total compensation is 10,000 USD and the maximum total compensation is 4,980,000 USD. The average compensation is 197,855 USD which is approximately 198,000 USD. The mean average years of experience is ar 7.12 years.</p>
</section>
<section id="potential-research-questions" class="level3">
<h3 class="anchored" data-anchor-id="potential-research-questions">Potential research questions</h3>
<p>The dataset provides several variables that can be used to answer various questions related to data science and STEM salaries. Here are some potential questions I tried to explore:</p>
<ol type="a">
<li><p>How is the education level effecting the people who are seeking jobs in Data Science and STEM Domains.</p></li>
<li><p>How does the gender pay gap manifest in the data? Are there noticeable differences in compensation between genders?</p></li>
<li><p>Are there any trends or patterns in compensation based on educational attainment (Masters, Bachelors, Doctorate, etc.)?</p></li>
<li><p>How does compensation vary across different years?</p></li>
<li><p>Is there a correlation between years of experience at the company and total yearly compensation?</p></li>
<li><p>Are there any regional differences in salaries for data science and STEM roles?</p></li>
<li><p>Is level and years of experience proportional always?</p></li>
<li><p>Number of states involved in the data set and is the data set skewed towards a specific state of the US given the number of companies in thar region?</p></li>
<li><p>Which education level is currently the most popular?</p></li>
<li><p>Can we explain education level based on gender(man and women) and age?</p></li>
<li><p>Is a highest level of education required to earn an above average salary even with less than average years of experience for the role?</p></li>
</ol>
</section>
<section id="education-level-vs-number-of-people" class="level3">
<h3 class="anchored" data-anchor-id="education-level-vs-number-of-people">Education level vs number of people</h3>
<p>We will now examine the education metric. We use scatter charts and tile charts, respectively, to display the proportion of the indicated levels of both variables and the number of respondents to two indicators with the levels of the variables under consideration.</p>
<p>From the below plot, we see that about 9000 of respondants have a Master’s degree, 11,000 have a Bachelor’s degree and only a few hundrends have just a high school diploma. It looks like atleast a Bachelor’s degree is mandatory to get a job in the STEM and Data Science Domain. While a master’s degree does not look mandatory, only analysing the compensation difference would tell us if a master’s degree is worth it or not in terms of increased salary compensation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>education <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">table</span>(data<span class="sc">$</span>Education))</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(education, <span class="fu">aes</span>(<span class="fu">reorder</span>(Var1, <span class="sc">+</span>Freq), Freq))<span class="sc">+</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">col =</span> <span class="st">"gray10"</span>, <span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">width =</span> <span class="fl">0.6</span>, <span class="at">fill =</span> <span class="st">"lightblue"</span>)<span class="sc">+</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="st">"Master's Degree"</span>, <span class="st">"Bachelor's Degree"</span>, <span class="st">"Highschool"</span>))<span class="sc">+</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Education level"</span>, <span class="at">y =</span> <span class="st">"count"</span>, <span class="at">x =</span> <span class="st">"Education level"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="PriyankaPerumalla_final_project_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="education-level-vs-salary-vs-gender" class="level3">
<h3 class="anchored" data-anchor-id="education-level-vs-salary-vs-gender">Education level vs Salary vs Gender</h3>
<p>We observe a gender- and education-based breakdown of the population who entered their salaries. The “I prefer to define myself” options in the variable are limited to the two most popular levels, female and male, due to the small number of refusals and indications. There are four times fewer women than men among the respondents. The proportions of people with and without a college degree are very similar for both sexes, but it is clear that those without a college degree are more likely to be men than the rest of the sample. It is interesting to see that the gender with most “Masters” degree and “College/High school” is men.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>tile2 <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(gender <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Female"</span>, <span class="st">"Male"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(gender, Education) <span class="sc">%&gt;%</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>(), <span class="at">.groups =</span> <span class="st">'drop'</span>) </span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(tile2, <span class="fu">aes</span>(Education, gender))<span class="sc">+</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_tile</span>(<span class="fu">aes</span>(<span class="at">fill =</span> count), <span class="at">colour =</span> <span class="st">"gray10"</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>)<span class="sc">+</span></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="st">"Master's Degree"</span>, <span class="st">"Bachelor's Degree"</span>, <span class="st">"Highschool"</span>))<span class="sc">+</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">paste0</span>(<span class="fu">round</span>(count<span class="sc">/</span><span class="fu">sum</span>(tile2<span class="sc">$</span>count) <span class="sc">*</span> <span class="dv">100</span>,<span class="dv">1</span>), <span class="st">"%"</span>)), <span class="at">size =</span> <span class="dv">7</span>)<span class="sc">+</span></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Education level"</span>, <span class="at">subtitle =</span> <span class="st">"count by education level and gender"</span>, <span class="at">y =</span> <span class="st">"Gender"</span>, <span class="at">x =</span> <span class="st">"Education level"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="PriyankaPerumalla_final_project_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="salary-vs-education-level" class="level3">
<h3 class="anchored" data-anchor-id="salary-vs-education-level">Salary vs Education level</h3>
<p>The usual expectation is that salary should increase with education level. But in the tech industry, I feel that its only your talent and abilities that matter but not the education level. I have run the analysis to see it that is true. I can clearly see that the pattern is very similar for Bachelor’s Degree and Master’s Degree when I look at higher bands of salaries (200k USD +). So for jobs that pay above 200k USD, looks like degree does not matter. But when I look at the 100k USD to 200k USD salary band, the Bachelor’s degree population seems to win. But that might be because of the skewed distribution towards them. I can also notice some highschool diploma holders that fell in the band of 300k+. I can’t stop myself from mapping them to be a CEO of a company but a college dropout.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Salary_bucket<span class="sc">!=</span><span class="st">""</span>) <span class="sc">%&gt;%</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(., <span class="fu">aes</span>(Education, Salary_bucket, <span class="at">col =</span> Education))<span class="sc">+</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_count</span>()<span class="sc">+</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="st">"Master's Degree"</span>, <span class="st">"Bachelor's Degree"</span>, <span class="st">"Highschool"</span>))<span class="sc">+</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_discrete</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="st">"0-25k"</span>,<span class="st">"25k-50k"</span>,<span class="st">"50k-75k"</span>,<span class="st">"75k-100k"</span>,<span class="st">"100k-125k"</span>,<span class="st">"125k-150k"</span>,<span class="st">"150k-175k"</span>,<span class="st">"175k-200k"</span>,<span class="st">"200-225k"</span>,<span class="st">"225k-250k"</span>,<span class="st">"250k-275k"</span>,<span class="st">"275k-300k"</span>,<span class="st">"300-325k"</span>,<span class="st">"325k-350k"</span>,<span class="st">"350k-375k"</span>,<span class="st">"375k-400k"</span>,<span class="st">"400-425k"</span>,<span class="st">"425k-450k"</span>,<span class="st">"450k-475k"</span>,<span class="st">"475k-500k"</span>,<span class="st">"500k+"</span>))<span class="sc">+</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Education level"</span>, <span class="at">subtitle =</span> <span class="st">"Count by education level and salary range"</span>, <span class="at">y =</span> <span class="st">"Salary"</span>, <span class="at">x =</span> <span class="st">"Education level"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="PriyankaPerumalla_final_project_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="average-total-compensation-for-different-years" class="level2">
<h2 class="anchored" data-anchor-id="average-total-compensation-for-different-years">Average Total Compensation for different years :</h2>
<p>If we want to see how average total compensation for different years looks like, we could use a scatter plot to deduce a relationship between average total compensation and year. From below plot, we could see that, the average total compensation decreased from 2020 to 2021. There could be multiple unwarranted reasons for this trend which could be deduced from the given plot.But I strongly feel that the economic downtime has something to do with the reduced compensations at Tech firms.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">=</span> data<span class="sc">%&gt;%</span> <span class="fu">na.omit</span>() <span class="sc">%&gt;%</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(Year) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">Mean_salary =</span> <span class="fu">mean</span>(totalyearlycompensation))</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  data,</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">y =</span>  <span class="fu">as.numeric</span>(Mean_salary), <span class="at">x =</span> <span class="fu">as.factor</span>(Year), <span class="at">color =</span> <span class="fu">factor</span>(Year), <span class="at">group =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size=</span><span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_viridis_d</span>() <span class="sc">+</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_linetype_manual</span>() <span class="sc">+</span></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Year"</span>, <span class="at">y =</span> <span class="st">"Average Total Compensation"</span>) <span class="sc">+</span></span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"top"</span>)</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>p <span class="sc">+</span>  <span class="fu">geom_line</span>(<span class="at">color=</span><span class="st">'blue'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="PriyankaPerumalla_final_project_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="conclusion" class="level3">
<h3 class="anchored" data-anchor-id="conclusion">CONCLUSION</h3>
<p>With all the analysis above, we can answer the following questions-</p>
<ol type="1">
<li><p>The respondents are from different education backgrounds but the distribution is skewed towards peple who are atleast graduates. They make 99% of the participants, given its higher population (shown in excel sheet).</p></li>
<li><p>There is a huge gender gap that can be noticed. While it can be concluded that there is only one female for every 4 males in the data that has job in our interested domain. It can also be noticed that men tend to pursue higher education more tham female.</p></li>
<li><p>We see that there is a clear correlation between Education level (completed degree) vs job compensation. In every salary band such a trend is varying. Salary bands above 250k USD value individual accomplishments over educational degree.</p></li>
<li><p>The average total compensation changes with every year. In fact it reduced from the year 2020 to 2021.</p></li>
</ol>
</section>
<section id="reflection" class="level3">
<h3 class="anchored" data-anchor-id="reflection">Reflection</h3>
<p>Since it is my first project in R, I learned that working with a data set involves taking raw data, cleaning it, then visualizing and interpreting different relationships. I focused on the variables that I was most intrigued by. Eg: I was curious about how gender/degrees influence jobs and compensation. What paths or roles do Data Science enthusiasts from different education backgrounds prefer? Which states are currently paying high? For somebody would I advise to pursue a masters degree in order to get a high salary? I’ve enjoyed learning the process for exploratory data analysis and visualization.</p>


<!-- -->

</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="DACSS/601_Spring_2023" data-repo-id="R_kgDOI4JcJA" data-category="Announcements" data-category-id="" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb33" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "DACCS 601 Final Project"</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Priyanka Perumalla"</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> "Data Science and STEM Salaries Analysis"</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "05/21/2023"</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a><span class="co">    df-print: paged</span></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a><span class="co">    code-copy: true</span></span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a><span class="co">    css: styles.css</span></span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span></span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a><span class="co">  - final_Project_assignment</span></span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a><span class="co">  - final_project</span></span>
<span id="cb33-16"><a href="#cb33-16" aria-hidden="true" tabindex="-1"></a><span class="co">  - Priyanka Perumalla</span></span>
<span id="cb33-17"><a href="#cb33-17" aria-hidden="true" tabindex="-1"></a><span class="co">  - Data Science and STEM salary dataset</span></span>
<span id="cb33-18"><a href="#cb33-18" aria-hidden="true" tabindex="-1"></a><span class="co">  - Tech Salary</span></span>
<span id="cb33-19"><a href="#cb33-19" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb33-20"><a href="#cb33-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-23"><a href="#cb33-23" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb33-24"><a href="#cb33-24" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: setup</span></span>
<span id="cb33-25"><a href="#cb33-25" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb33-26"><a href="#cb33-26" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb33-27"><a href="#cb33-27" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb33-28"><a href="#cb33-28" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb33-29"><a href="#cb33-29" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb33-30"><a href="#cb33-30" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(summarytools)</span>
<span id="cb33-31"><a href="#cb33-31" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb33-32"><a href="#cb33-32" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb33-33"><a href="#cb33-33" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">TRUE</span>, <span class="at">warning=</span><span class="cn">FALSE</span>, <span class="at">message=</span><span class="cn">FALSE</span>)</span>
<span id="cb33-34"><a href="#cb33-34" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb33-35"><a href="#cb33-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-36"><a href="#cb33-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-37"><a href="#cb33-37" aria-hidden="true" tabindex="-1"></a><span class="fu">## Introduction</span></span>
<span id="cb33-38"><a href="#cb33-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-39"><a href="#cb33-39" aria-hidden="true" tabindex="-1"></a>The dataset I am analyzing, "The Data Science and STEM Salaries Dataset," is sourced from levels.fyi. Levels.fyi is a platform that collects and provides information on job levels, salaries, and compensation packages in various companies and industries. The dataset represents salary and compensation information for individuals working in data science and STEM (Science, Technology, Engineering, and Mathematics) fields.</span>
<span id="cb33-40"><a href="#cb33-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-41"><a href="#cb33-41" aria-hidden="true" tabindex="-1"></a>Each row in the dataset represents an individual case or observation, which corresponds to a specific person's employment details and compensation information. The dataset includes columns such as timestamp (when the data was recorded), company (the company the individual works for), level (job level or position), title (job title), total yearly compensation, location (geographic location), years of experience, years at the company, various tags (related to skills or domains), base salary, stock grant value, bonus, gender, other details, city ID, designated market area (DMA) ID, row number, and information about the individual's education and race.</span>
<span id="cb33-42"><a href="#cb33-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-43"><a href="#cb33-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-44"><a href="#cb33-44" aria-hidden="true" tabindex="-1"></a><span class="fu">## Data Description</span></span>
<span id="cb33-45"><a href="#cb33-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-46"><a href="#cb33-46" aria-hidden="true" tabindex="-1"></a>The dataset used in this analysis is sourced from levels.fyi, a platform that collects and provides information on job levels, salaries, and compensation packages. The data represents salary and compensation information specifically for data science and STEM (Science, Technology, Engineering, and Mathematics) roles. The data collection process on levels.fyi involves individuals voluntarily sharing their employment and compensation details. Users can submit their salary information, along with other relevant details, to contribute to the platform's database. This crowd sourced approach allows for a diverse range of data to be collected, representing different companies, job levels, and locations. The dataset offers insights into the salaries and compensation packages received by data science and STEM professionals, enabling analysis and exploration of various factors that influence compensation in these fields.</span>
<span id="cb33-47"><a href="#cb33-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-48"><a href="#cb33-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-49"><a href="#cb33-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-50"><a href="#cb33-50" aria-hidden="true" tabindex="-1"></a>Reading the dataset</span>
<span id="cb33-51"><a href="#cb33-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-54"><a href="#cb33-54" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb33-55"><a href="#cb33-55" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"PriyankaPerumalla_FinalProjectData/Levels_Fyi_Salary_Data.csv"</span>)</span>
<span id="cb33-56"><a href="#cb33-56" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data)</span>
<span id="cb33-57"><a href="#cb33-57" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb33-58"><a href="#cb33-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-59"><a href="#cb33-59" aria-hidden="true" tabindex="-1"></a>Presenting the descriptive information of the dataset. Like what all columns are present and what all information is present in every column. The nature of every column can be viewed through this sample data.</span>
<span id="cb33-60"><a href="#cb33-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-61"><a href="#cb33-61" aria-hidden="true" tabindex="-1"></a><span class="in">    ```{r}</span></span>
<span id="cb33-62"><a href="#cb33-62" aria-hidden="true" tabindex="-1"></a>head(data)</span>
<span id="cb33-63"><a href="#cb33-63" aria-hidden="true" tabindex="-1"></a>    <span class="in">```</span></span>
<span id="cb33-64"><a href="#cb33-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-65"><a href="#cb33-65" aria-hidden="true" tabindex="-1"></a><span class="in">On,analysing the dimensions of the data set. We see that the dataset has 62642 rows to begin with and 29 distinct columns.</span></span>
<span id="cb33-66"><a href="#cb33-66" aria-hidden="true" tabindex="-1"></a><span class="in">    ```{r}</span></span>
<span id="cb33-67"><a href="#cb33-67" aria-hidden="true" tabindex="-1"></a><span class="in">dim(data)</span></span>
<span id="cb33-68"><a href="#cb33-68" aria-hidden="true" tabindex="-1"></a><span class="in">    ```</span></span>
<span id="cb33-69"><a href="#cb33-69" aria-hidden="true" tabindex="-1"></a>Checking to see if any columns are repeating. We can notice that all the 29 columns ar eunique</span>
<span id="cb33-70"><a href="#cb33-70" aria-hidden="true" tabindex="-1"></a>    <span class="in">```{r}</span></span>
<span id="cb33-71"><a href="#cb33-71" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">unique</span>(data))</span>
<span id="cb33-72"><a href="#cb33-72" aria-hidden="true" tabindex="-1"></a>    <span class="in">```</span></span>
<span id="cb33-73"><a href="#cb33-73" aria-hidden="true" tabindex="-1"></a>Taking a look on what all columns are present in the dataset.   </span>
<span id="cb33-74"><a href="#cb33-74" aria-hidden="true" tabindex="-1"></a>    <span class="in">```{r}</span></span>
<span id="cb33-75"><a href="#cb33-75" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(data)</span>
<span id="cb33-76"><a href="#cb33-76" aria-hidden="true" tabindex="-1"></a>    <span class="in">```</span></span>
<span id="cb33-77"><a href="#cb33-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-78"><a href="#cb33-78" aria-hidden="true" tabindex="-1"></a>Understanding the data:</span>
<span id="cb33-79"><a href="#cb33-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-80"><a href="#cb33-80" aria-hidden="true" tabindex="-1"></a>The data set contains information from the "Data Science and STEM Salaries" data collected by levels.fyi. It consists of 62642 rows, representing as many as  62642 participants who volunteered to enter information in Levels.fyi. The data set contains 29 columns that capture various attributes of the participants and their responses.</span>
<span id="cb33-81"><a href="#cb33-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-82"><a href="#cb33-82" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>timestamp - The timestamp indicates when the survey response was recorded.</span>
<span id="cb33-83"><a href="#cb33-83" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>company - This column represents the name of the company where the particpant is employed.</span>
<span id="cb33-84"><a href="#cb33-84" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>level - It denotes the career level or seniority of the participant.</span>
<span id="cb33-85"><a href="#cb33-85" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>title - This column specifies the job title or position held by the participant.</span>
<span id="cb33-86"><a href="#cb33-86" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>totalyearlycompensation - It represents the total annual compensation of the participant, including salary, stock grants, and bonuses.</span>
<span id="cb33-87"><a href="#cb33-87" aria-hidden="true" tabindex="-1"></a><span class="ss">6. </span>location - This column indicates the geographical location of the participant.</span>
<span id="cb33-88"><a href="#cb33-88" aria-hidden="true" tabindex="-1"></a><span class="ss">7. </span>yearsofexperience - It indicates the number of years of professional experience the participant has.</span>
<span id="cb33-89"><a href="#cb33-89" aria-hidden="true" tabindex="-1"></a><span class="ss">8. </span>yearsatcompany - This column specifies the number of years the participant has been with their current company.</span>
<span id="cb33-90"><a href="#cb33-90" aria-hidden="true" tabindex="-1"></a><span class="ss">9. </span>tag - The tag column may provide additional information or categorization related to the participant or their response.</span>
<span id="cb33-91"><a href="#cb33-91" aria-hidden="true" tabindex="-1"></a><span class="ss">10. </span>basesalary - It represents the base salary component of the participant's total yearly compensation.</span>
<span id="cb33-92"><a href="#cb33-92" aria-hidden="true" tabindex="-1"></a><span class="ss">11. </span>stockgrantvalue - This column captures the value of stock grants included in the participant's total yearly compensation.</span>
<span id="cb33-93"><a href="#cb33-93" aria-hidden="true" tabindex="-1"></a><span class="ss">12. </span>bonus - It denotes the bonus amount included in the participant's total yearly compensation.</span>
<span id="cb33-94"><a href="#cb33-94" aria-hidden="true" tabindex="-1"></a><span class="ss">13. </span>gender - This column represents the gender of the participant.</span>
<span id="cb33-95"><a href="#cb33-95" aria-hidden="true" tabindex="-1"></a><span class="ss">14. </span>otherdetails - The otherdetails column may contain additional information or details provided by the participant.</span>
<span id="cb33-96"><a href="#cb33-96" aria-hidden="true" tabindex="-1"></a><span class="ss">15. </span>cityid - It indicates the city identifier associated with the participant's location.</span>
<span id="cb33-97"><a href="#cb33-97" aria-hidden="true" tabindex="-1"></a><span class="ss">16. </span>dmaid - The dmaid column represents the Designated Market Area (DMA) identifier, which relates to the participant's location.</span>
<span id="cb33-98"><a href="#cb33-98" aria-hidden="true" tabindex="-1"></a><span class="ss">17. </span>rowNumber - This column assigns a unique row number to each participant in the dataset.</span>
<span id="cb33-99"><a href="#cb33-99" aria-hidden="true" tabindex="-1"></a><span class="ss">18. </span>Masters_Degree - This column captures whether the participant holds a Master's degree.</span>
<span id="cb33-100"><a href="#cb33-100" aria-hidden="true" tabindex="-1"></a><span class="ss">19. </span>Bachelors_Degree - It indicates whether the participant holds a Bachelor's degree.</span>
<span id="cb33-101"><a href="#cb33-101" aria-hidden="true" tabindex="-1"></a><span class="ss">20. </span>Doctorate_Degree - This column specifies whether the participant holds a Doctorate degree.</span>
<span id="cb33-102"><a href="#cb33-102" aria-hidden="true" tabindex="-1"></a><span class="ss">21. </span>Highschool - It denotes whether the participant has completed high school education.</span>
<span id="cb33-103"><a href="#cb33-103" aria-hidden="true" tabindex="-1"></a><span class="ss">22. </span>Some_College - This column represents whether the participant has attended college without completing a degree.</span>
<span id="cb33-104"><a href="#cb33-104" aria-hidden="true" tabindex="-1"></a><span class="ss">23. </span>Race_Asian - It indicates whether the participant identifies as Asian.</span>
<span id="cb33-105"><a href="#cb33-105" aria-hidden="true" tabindex="-1"></a><span class="ss">24. </span>Race_White - This column represents whether the participant identifies as White.</span>
<span id="cb33-106"><a href="#cb33-106" aria-hidden="true" tabindex="-1"></a><span class="ss">25. </span>Race_Two_Or_More - It denotes whether the participant identifies as belonging to two or more races.</span>
<span id="cb33-107"><a href="#cb33-107" aria-hidden="true" tabindex="-1"></a><span class="ss">26. </span>Race_Black - This column indicates whether the participant identifies as Black.</span>
<span id="cb33-108"><a href="#cb33-108" aria-hidden="true" tabindex="-1"></a><span class="ss">27. </span>Race_Hispanic - It represents whether the participant identifies as Hispanic.</span>
<span id="cb33-109"><a href="#cb33-109" aria-hidden="true" tabindex="-1"></a><span class="ss">28. </span>Race - This column captures the participant's race or ethnic background.</span>
<span id="cb33-110"><a href="#cb33-110" aria-hidden="true" tabindex="-1"></a><span class="ss">29. </span>Education - It denotes the highest level of formal education completed by the participant.</span>
<span id="cb33-111"><a href="#cb33-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-112"><a href="#cb33-112" aria-hidden="true" tabindex="-1"></a><span class="fu">### Data tidying and mutation</span></span>
<span id="cb33-113"><a href="#cb33-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-114"><a href="#cb33-114" aria-hidden="true" tabindex="-1"></a>To start off with any analysis the data needs to be tidy.</span>
<span id="cb33-115"><a href="#cb33-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-116"><a href="#cb33-116" aria-hidden="true" tabindex="-1"></a>Loading the required libraries</span>
<span id="cb33-119"><a href="#cb33-119" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb33-120"><a href="#cb33-120" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb33-121"><a href="#cb33-121" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scales)</span>
<span id="cb33-122"><a href="#cb33-122" aria-hidden="true" tabindex="-1"></a>annotate <span class="ot">&lt;-</span> ggplot2<span class="sc">::</span>annotate</span>
<span id="cb33-123"><a href="#cb33-123" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb33-124"><a href="#cb33-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-125"><a href="#cb33-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-126"><a href="#cb33-126" aria-hidden="true" tabindex="-1"></a>I am trying to check if this data has any null values. As a next step, I have omitted the null values as they would not contribute positively to my analysis. After omitting the rows which have atleast one null value, I am left with 21575 rows and 29 columns.</span>
<span id="cb33-129"><a href="#cb33-129" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb33-130"><a href="#cb33-130" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(data))</span>
<span id="cb33-131"><a href="#cb33-131" aria-hidden="true" tabindex="-1"></a>data<span class="ot">&lt;-</span> <span class="fu">na.omit</span>(data)</span>
<span id="cb33-132"><a href="#cb33-132" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(data)</span>
<span id="cb33-133"><a href="#cb33-133" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb33-134"><a href="#cb33-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-135"><a href="#cb33-135" aria-hidden="true" tabindex="-1"></a>It can be noticed that the summary column for race and education level already exists. But the flag columns for every category of education and race also exist. This is a redundancy and such columns can be deleted. </span>
<span id="cb33-136"><a href="#cb33-136" aria-hidden="true" tabindex="-1"></a>I am getting rid of the columns Race_Asian,Race_White, Race_Black,Race_Hispanic,Some_College,Highschool,Doctorate_Degree,Bachelors_Degree,Masters_Degree,otherdetails. My dataset now has 19 columns.</span>
<span id="cb33-139"><a href="#cb33-139" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb33-140"><a href="#cb33-140" aria-hidden="true" tabindex="-1"></a>data<span class="ot">&lt;-</span> <span class="fu">subset</span>(data, <span class="at">select =</span> <span class="sc">-</span><span class="fu">c</span>(Race_Asian,Race_White, Race_Black,Race_Hispanic,Some_College,Highschool,Doctorate_Degree,Bachelors_Degree,Masters_Degree,otherdetails) )</span>
<span id="cb33-141"><a href="#cb33-141" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(data)</span>
<span id="cb33-142"><a href="#cb33-142" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb33-143"><a href="#cb33-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-144"><a href="#cb33-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-145"><a href="#cb33-145" aria-hidden="true" tabindex="-1"></a>The location column in the dataset has the format 'city,state,country'. But I would like to mutate this column to extract city,state and country columns separtely. After this mutation, I have 21 columns.</span>
<span id="cb33-148"><a href="#cb33-148" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb33-149"><a href="#cb33-149" aria-hidden="true" tabindex="-1"></a>data<span class="ot">&lt;-</span><span class="fu">separate</span>(<span class="at">data =</span> data, <span class="at">col =</span> location, <span class="at">into =</span> <span class="fu">c</span>(<span class="st">"City"</span>, <span class="st">"State"</span>,<span class="st">"Country"</span>), <span class="at">sep =</span> <span class="st">","</span>)</span>
<span id="cb33-150"><a href="#cb33-150" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(data)</span>
<span id="cb33-151"><a href="#cb33-151" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb33-152"><a href="#cb33-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-153"><a href="#cb33-153" aria-hidden="true" tabindex="-1"></a>The datetimestamp column in the dataset has the format 'MM/DD/YYYY hh:mm:ss'. But I would like to mutate this column to extract Date and time separtely. After this mutation, I have 22 columns.</span>
<span id="cb33-156"><a href="#cb33-156" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb33-157"><a href="#cb33-157" aria-hidden="true" tabindex="-1"></a>data<span class="ot">&lt;-</span><span class="fu">separate</span>(<span class="at">data =</span> data, <span class="at">col =</span> timestamp, <span class="at">into =</span> <span class="fu">c</span>(<span class="st">"Date "</span>, <span class="st">"Time"</span>), <span class="at">sep =</span> <span class="st">" "</span>)</span>
<span id="cb33-158"><a href="#cb33-158" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(data)</span>
<span id="cb33-159"><a href="#cb33-159" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data)</span>
<span id="cb33-160"><a href="#cb33-160" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb33-161"><a href="#cb33-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-162"><a href="#cb33-162" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-163"><a href="#cb33-163" aria-hidden="true" tabindex="-1"></a>The date column in the dataset has the format 'MM/DD/YYYY'. But I would like to mutate this column further to extract month,day and year separtely. After this mutation, I have 24 columns.</span>
<span id="cb33-166"><a href="#cb33-166" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb33-167"><a href="#cb33-167" aria-hidden="true" tabindex="-1"></a>data<span class="ot">&lt;-</span><span class="fu">separate</span>(<span class="at">data =</span> data, <span class="at">col =</span> <span class="dv">1</span>, <span class="at">into =</span> <span class="fu">c</span>(<span class="st">"Month"</span>, <span class="st">"Day"</span>,<span class="st">"Year"</span>), <span class="at">sep =</span> <span class="st">"/"</span>)</span>
<span id="cb33-168"><a href="#cb33-168" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(data)</span>
<span id="cb33-169"><a href="#cb33-169" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data)</span>
<span id="cb33-170"><a href="#cb33-170" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb33-171"><a href="#cb33-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-172"><a href="#cb33-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-173"><a href="#cb33-173" aria-hidden="true" tabindex="-1"></a>I want to group salaries together into buckets for further analysis. I have kept the bucket size as $25,000 USD. I am trying get the count of people who fall into each of such compensation buckets.</span>
<span id="cb33-176"><a href="#cb33-176" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb33-177"><a href="#cb33-177" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb33-178"><a href="#cb33-178" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Salary_bucket =</span> <span class="fu">case_when</span>(totalyearlycompensation <span class="sc">&gt;=</span><span class="dv">0</span> <span class="sc">&amp;</span> totalyearlycompensation <span class="sc">&lt;</span><span class="dv">25000</span> <span class="sc">~</span> <span class="st">"0-25k"</span>,</span>
<span id="cb33-179"><a href="#cb33-179" aria-hidden="true" tabindex="-1"></a>  totalyearlycompensation <span class="sc">&gt;=</span><span class="dv">25000</span> <span class="sc">&amp;</span> totalyearlycompensation <span class="sc">&lt;</span><span class="dv">50000</span> <span class="sc">~</span> <span class="st">"25k-50k"</span>,</span>
<span id="cb33-180"><a href="#cb33-180" aria-hidden="true" tabindex="-1"></a>  totalyearlycompensation <span class="sc">&gt;=</span><span class="dv">50000</span> <span class="sc">&amp;</span> totalyearlycompensation <span class="sc">&lt;</span><span class="dv">75000</span> <span class="sc">~</span> <span class="st">"50k-750k"</span>,</span>
<span id="cb33-181"><a href="#cb33-181" aria-hidden="true" tabindex="-1"></a>  totalyearlycompensation <span class="sc">&gt;=</span><span class="dv">75000</span> <span class="sc">&amp;</span> totalyearlycompensation <span class="sc">&lt;</span><span class="dv">100000</span> <span class="sc">~</span> <span class="st">"75k-100k"</span>,</span>
<span id="cb33-182"><a href="#cb33-182" aria-hidden="true" tabindex="-1"></a>  totalyearlycompensation <span class="sc">&gt;=</span><span class="dv">100000</span> <span class="sc">&amp;</span> totalyearlycompensation <span class="sc">&lt;</span><span class="dv">125000</span> <span class="sc">~</span> <span class="st">"100k-125k"</span>,                      </span>
<span id="cb33-183"><a href="#cb33-183" aria-hidden="true" tabindex="-1"></a>  totalyearlycompensation <span class="sc">&gt;=</span><span class="dv">125000</span> <span class="sc">&amp;</span> totalyearlycompensation <span class="sc">&lt;</span><span class="dv">150000</span> <span class="sc">~</span> <span class="st">"125k-150k"</span>,</span>
<span id="cb33-184"><a href="#cb33-184" aria-hidden="true" tabindex="-1"></a>  totalyearlycompensation <span class="sc">&gt;=</span><span class="dv">150000</span> <span class="sc">&amp;</span> totalyearlycompensation <span class="sc">&lt;</span><span class="dv">175000</span> <span class="sc">~</span> <span class="st">"150k-175k"</span>,</span>
<span id="cb33-185"><a href="#cb33-185" aria-hidden="true" tabindex="-1"></a>  totalyearlycompensation <span class="sc">&gt;=</span><span class="dv">175000</span> <span class="sc">&amp;</span> totalyearlycompensation <span class="sc">&lt;</span><span class="dv">200000</span> <span class="sc">~</span> <span class="st">"175k-200k"</span>,</span>
<span id="cb33-186"><a href="#cb33-186" aria-hidden="true" tabindex="-1"></a>  totalyearlycompensation <span class="sc">&gt;=</span><span class="dv">200000</span> <span class="sc">&amp;</span> totalyearlycompensation <span class="sc">&lt;</span><span class="dv">225000</span> <span class="sc">~</span> <span class="st">"200k-225k"</span>,</span>
<span id="cb33-187"><a href="#cb33-187" aria-hidden="true" tabindex="-1"></a>  totalyearlycompensation <span class="sc">&gt;=</span><span class="dv">225000</span> <span class="sc">&amp;</span> totalyearlycompensation <span class="sc">&lt;</span><span class="dv">250000</span> <span class="sc">~</span> <span class="st">"225k-250k"</span>,</span>
<span id="cb33-188"><a href="#cb33-188" aria-hidden="true" tabindex="-1"></a>  totalyearlycompensation <span class="sc">&gt;=</span><span class="dv">250000</span> <span class="sc">&amp;</span> totalyearlycompensation <span class="sc">&lt;</span><span class="dv">275000</span> <span class="sc">~</span> <span class="st">"250k-275k"</span>,</span>
<span id="cb33-189"><a href="#cb33-189" aria-hidden="true" tabindex="-1"></a>  totalyearlycompensation <span class="sc">&gt;=</span><span class="dv">275000</span> <span class="sc">&amp;</span> totalyearlycompensation <span class="sc">&lt;</span><span class="dv">300000</span> <span class="sc">~</span> <span class="st">"275k-300k"</span>,</span>
<span id="cb33-190"><a href="#cb33-190" aria-hidden="true" tabindex="-1"></a>  totalyearlycompensation <span class="sc">&gt;=</span><span class="dv">300000</span> <span class="sc">&amp;</span> totalyearlycompensation <span class="sc">&lt;</span><span class="dv">325000</span> <span class="sc">~</span> <span class="st">"300k-325k"</span>,</span>
<span id="cb33-191"><a href="#cb33-191" aria-hidden="true" tabindex="-1"></a>  totalyearlycompensation <span class="sc">&gt;=</span><span class="dv">325000</span> <span class="sc">&amp;</span> totalyearlycompensation <span class="sc">&lt;</span><span class="dv">350000</span> <span class="sc">~</span> <span class="st">"325k-350k"</span>,</span>
<span id="cb33-192"><a href="#cb33-192" aria-hidden="true" tabindex="-1"></a>  totalyearlycompensation <span class="sc">&gt;=</span><span class="dv">350000</span> <span class="sc">&amp;</span> totalyearlycompensation <span class="sc">&lt;</span><span class="dv">375000</span> <span class="sc">~</span> <span class="st">"350k-375k"</span>,</span>
<span id="cb33-193"><a href="#cb33-193" aria-hidden="true" tabindex="-1"></a>  totalyearlycompensation <span class="sc">&gt;=</span><span class="dv">375000</span> <span class="sc">&amp;</span> totalyearlycompensation <span class="sc">&lt;</span><span class="dv">400000</span> <span class="sc">~</span> <span class="st">"375k-400k"</span>,</span>
<span id="cb33-194"><a href="#cb33-194" aria-hidden="true" tabindex="-1"></a>  totalyearlycompensation <span class="sc">&gt;=</span><span class="dv">400000</span> <span class="sc">&amp;</span> totalyearlycompensation <span class="sc">&lt;</span><span class="dv">425000</span> <span class="sc">~</span> <span class="st">"400k-425k"</span>,</span>
<span id="cb33-195"><a href="#cb33-195" aria-hidden="true" tabindex="-1"></a>  totalyearlycompensation <span class="sc">&gt;=</span><span class="dv">425000</span> <span class="sc">&amp;</span> totalyearlycompensation <span class="sc">&lt;</span><span class="dv">450000</span> <span class="sc">~</span> <span class="st">"425k-450k"</span>,</span>
<span id="cb33-196"><a href="#cb33-196" aria-hidden="true" tabindex="-1"></a>  totalyearlycompensation <span class="sc">&gt;=</span><span class="dv">450000</span> <span class="sc">&amp;</span> totalyearlycompensation <span class="sc">&lt;</span><span class="dv">475000</span> <span class="sc">~</span> <span class="st">"450k-475k"</span>,</span>
<span id="cb33-197"><a href="#cb33-197" aria-hidden="true" tabindex="-1"></a>  totalyearlycompensation <span class="sc">&gt;=</span><span class="dv">475000</span> <span class="sc">&amp;</span> totalyearlycompensation <span class="sc">&lt;</span><span class="dv">500000</span> <span class="sc">~</span> <span class="st">"475k-500k"</span>,</span>
<span id="cb33-198"><a href="#cb33-198" aria-hidden="true" tabindex="-1"></a>  totalyearlycompensation <span class="sc">&gt;=</span><span class="dv">500000</span> <span class="sc">~</span> <span class="st">"500k+"</span>))</span>
<span id="cb33-199"><a href="#cb33-199" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb33-200"><a href="#cb33-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-201"><a href="#cb33-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-202"><a href="#cb33-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-203"><a href="#cb33-203" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-204"><a href="#cb33-204" aria-hidden="true" tabindex="-1"></a>#conduct summary statistics of the dataset(s)</span>
<span id="cb33-205"><a href="#cb33-205" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-206"><a href="#cb33-206" aria-hidden="true" tabindex="-1"></a>Now that the data is clean, tidy and all set for analysis, I would like to now view the summary statistics of the cleaned dataset.</span>
<span id="cb33-209"><a href="#cb33-209" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb33-210"><a href="#cb33-210" aria-hidden="true" tabindex="-1"></a><span class="fu">summarise_all</span>(data, mean)</span>
<span id="cb33-211"><a href="#cb33-211" aria-hidden="true" tabindex="-1"></a><span class="fu">summarise_all</span>(data, min)</span>
<span id="cb33-212"><a href="#cb33-212" aria-hidden="true" tabindex="-1"></a><span class="fu">summarise_all</span>(data, max)</span>
<span id="cb33-213"><a href="#cb33-213" aria-hidden="true" tabindex="-1"></a><span class="fu">summarise_all</span>(data, median)</span>
<span id="cb33-214"><a href="#cb33-214" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data)</span>
<span id="cb33-215"><a href="#cb33-215" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-216"><a href="#cb33-216" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb33-217"><a href="#cb33-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-218"><a href="#cb33-218" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-219"><a href="#cb33-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-220"><a href="#cb33-220" aria-hidden="true" tabindex="-1"></a>I notice that the minimum total compensation is 10,000 USD and the maximum total compensation is 4,980,000 USD. The average compensation is 197,855 USD which is approximately 198,000 USD. The mean average years of experience is ar 7.12 years. </span>
<span id="cb33-221"><a href="#cb33-221" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-222"><a href="#cb33-222" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-223"><a href="#cb33-223" aria-hidden="true" tabindex="-1"></a><span class="fu">### Potential research questions</span></span>
<span id="cb33-224"><a href="#cb33-224" aria-hidden="true" tabindex="-1"></a>The dataset provides several variables that can be used to answer various questions related to data science and STEM salaries. Here are some potential questions I tried to explore:</span>
<span id="cb33-225"><a href="#cb33-225" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-226"><a href="#cb33-226" aria-hidden="true" tabindex="-1"></a>a) How is the education level effecting the people who are seeking jobs in Data Science and STEM Domains.</span>
<span id="cb33-227"><a href="#cb33-227" aria-hidden="true" tabindex="-1"></a>b)  How does the gender pay gap manifest in the data? Are there noticeable differences in compensation between genders?</span>
<span id="cb33-228"><a href="#cb33-228" aria-hidden="true" tabindex="-1"></a>c) Are there any trends or patterns in compensation based on educational attainment (Masters, Bachelors, Doctorate, etc.)?</span>
<span id="cb33-229"><a href="#cb33-229" aria-hidden="true" tabindex="-1"></a>d) How does compensation vary across different years?</span>
<span id="cb33-230"><a href="#cb33-230" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-231"><a href="#cb33-231" aria-hidden="true" tabindex="-1"></a>g) Is there a correlation between years of experience at the company and total yearly compensation?</span>
<span id="cb33-232"><a href="#cb33-232" aria-hidden="true" tabindex="-1"></a>h) Are there any regional differences in salaries for data science and STEM roles?</span>
<span id="cb33-233"><a href="#cb33-233" aria-hidden="true" tabindex="-1"></a>i) Is level and years of experience proportional always?</span>
<span id="cb33-234"><a href="#cb33-234" aria-hidden="true" tabindex="-1"></a>j) Number of states involved in the data set and is the data set skewed towards a specific state of the US given the number of companies in thar region?</span>
<span id="cb33-235"><a href="#cb33-235" aria-hidden="true" tabindex="-1"></a>k) Which education level is currently the most popular?</span>
<span id="cb33-236"><a href="#cb33-236" aria-hidden="true" tabindex="-1"></a>l) Can we explain education level based on gender(man and women) and age?</span>
<span id="cb33-237"><a href="#cb33-237" aria-hidden="true" tabindex="-1"></a>m) Is a highest level of education required to earn an above average salary even with less than average years of experience for the role?</span>
<span id="cb33-238"><a href="#cb33-238" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-239"><a href="#cb33-239" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-240"><a href="#cb33-240" aria-hidden="true" tabindex="-1"></a><span class="fu">### Education level vs number of people</span></span>
<span id="cb33-241"><a href="#cb33-241" aria-hidden="true" tabindex="-1"></a>We will now examine the education metric. We use scatter charts and tile charts, respectively, to display the proportion of the indicated levels of both variables and the number of respondents to two indicators with the levels of the variables under consideration.</span>
<span id="cb33-242"><a href="#cb33-242" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-243"><a href="#cb33-243" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-244"><a href="#cb33-244" aria-hidden="true" tabindex="-1"></a>From the below plot, we see that about  9000 of respondants have a Master's degree, 11,000 have a Bachelor's degree and only a few hundrends have just a high school diploma. It looks like atleast a Bachelor's degree is mandatory to get a job in the STEM and Data Science Domain. While a master's degree does not look mandatory, only analysing the compensation difference would tell us if a master's degree is worth it or not in terms of increased salary compensation.</span>
<span id="cb33-245"><a href="#cb33-245" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-248"><a href="#cb33-248" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb33-249"><a href="#cb33-249" aria-hidden="true" tabindex="-1"></a>education <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">table</span>(data<span class="sc">$</span>Education))</span>
<span id="cb33-250"><a href="#cb33-250" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(education, <span class="fu">aes</span>(<span class="fu">reorder</span>(Var1, <span class="sc">+</span>Freq), Freq))<span class="sc">+</span></span>
<span id="cb33-251"><a href="#cb33-251" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">col =</span> <span class="st">"gray10"</span>, <span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">width =</span> <span class="fl">0.6</span>, <span class="at">fill =</span> <span class="st">"lightblue"</span>)<span class="sc">+</span></span>
<span id="cb33-252"><a href="#cb33-252" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="st">"Master's Degree"</span>, <span class="st">"Bachelor's Degree"</span>, <span class="st">"Highschool"</span>))<span class="sc">+</span></span>
<span id="cb33-253"><a href="#cb33-253" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Education level"</span>, <span class="at">y =</span> <span class="st">"count"</span>, <span class="at">x =</span> <span class="st">"Education level"</span>)</span>
<span id="cb33-254"><a href="#cb33-254" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb33-255"><a href="#cb33-255" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-256"><a href="#cb33-256" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-257"><a href="#cb33-257" aria-hidden="true" tabindex="-1"></a><span class="fu">### Education level vs Salary vs Gender</span></span>
<span id="cb33-258"><a href="#cb33-258" aria-hidden="true" tabindex="-1"></a>We observe a gender- and education-based breakdown of the population who entered their salaries. The "I prefer to define myself" options in the variable are limited to the two most popular levels, female and male, due to the small number of refusals and indications. There are four times fewer women than men among the respondents. The proportions of people with and without a college degree are very similar for both sexes, but it is clear that those without a college degree are more likely to be men than the rest of the sample.</span>
<span id="cb33-259"><a href="#cb33-259" aria-hidden="true" tabindex="-1"></a>It is interesting to see that the gender with most "Masters" degree and "College/High school" is men.</span>
<span id="cb33-260"><a href="#cb33-260" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-263"><a href="#cb33-263" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb33-264"><a href="#cb33-264" aria-hidden="true" tabindex="-1"></a>tile2 <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb33-265"><a href="#cb33-265" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(gender <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Female"</span>, <span class="st">"Male"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb33-266"><a href="#cb33-266" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(gender, Education) <span class="sc">%&gt;%</span></span>
<span id="cb33-267"><a href="#cb33-267" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>(), <span class="at">.groups =</span> <span class="st">'drop'</span>) </span>
<span id="cb33-268"><a href="#cb33-268" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(tile2, <span class="fu">aes</span>(Education, gender))<span class="sc">+</span></span>
<span id="cb33-269"><a href="#cb33-269" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_tile</span>(<span class="fu">aes</span>(<span class="at">fill =</span> count), <span class="at">colour =</span> <span class="st">"gray10"</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>)<span class="sc">+</span></span>
<span id="cb33-270"><a href="#cb33-270" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="st">"Master's Degree"</span>, <span class="st">"Bachelor's Degree"</span>, <span class="st">"Highschool"</span>))<span class="sc">+</span></span>
<span id="cb33-271"><a href="#cb33-271" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">paste0</span>(<span class="fu">round</span>(count<span class="sc">/</span><span class="fu">sum</span>(tile2<span class="sc">$</span>count) <span class="sc">*</span> <span class="dv">100</span>,<span class="dv">1</span>), <span class="st">"%"</span>)), <span class="at">size =</span> <span class="dv">7</span>)<span class="sc">+</span></span>
<span id="cb33-272"><a href="#cb33-272" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Education level"</span>, <span class="at">subtitle =</span> <span class="st">"count by education level and gender"</span>, <span class="at">y =</span> <span class="st">"Gender"</span>, <span class="at">x =</span> <span class="st">"Education level"</span>)</span>
<span id="cb33-273"><a href="#cb33-273" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb33-274"><a href="#cb33-274" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-275"><a href="#cb33-275" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-276"><a href="#cb33-276" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-277"><a href="#cb33-277" aria-hidden="true" tabindex="-1"></a><span class="fu">### Salary vs Education level</span></span>
<span id="cb33-278"><a href="#cb33-278" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-279"><a href="#cb33-279" aria-hidden="true" tabindex="-1"></a>The usual expectation is that salary should increase with education level. But in the tech industry, I feel that its only your talent and abilities that matter but not the education level. I have run the analysis to see it that is true. I can clearly see that the pattern is very similar for Bachelor's Degree and Master's Degree when I look at higher bands of salaries (200k USD +). So for jobs that pay above 200k USD, looks like degree does not matter. But when I look at the 100k USD to 200k USD salary band, the Bachelor's degree population seems to win. But that might be because of the skewed distribution towards them. I can also notice some highschool diploma holders that fell in the band of 300k+. I can't stop myself from mapping them to be a CEO of a company but a college dropout.</span>
<span id="cb33-280"><a href="#cb33-280" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-283"><a href="#cb33-283" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb33-284"><a href="#cb33-284" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span></span>
<span id="cb33-285"><a href="#cb33-285" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Salary_bucket<span class="sc">!=</span><span class="st">""</span>) <span class="sc">%&gt;%</span></span>
<span id="cb33-286"><a href="#cb33-286" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(., <span class="fu">aes</span>(Education, Salary_bucket, <span class="at">col =</span> Education))<span class="sc">+</span></span>
<span id="cb33-287"><a href="#cb33-287" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_count</span>()<span class="sc">+</span></span>
<span id="cb33-288"><a href="#cb33-288" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="st">"Master's Degree"</span>, <span class="st">"Bachelor's Degree"</span>, <span class="st">"Highschool"</span>))<span class="sc">+</span></span>
<span id="cb33-289"><a href="#cb33-289" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_discrete</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="st">"0-25k"</span>,<span class="st">"25k-50k"</span>,<span class="st">"50k-75k"</span>,<span class="st">"75k-100k"</span>,<span class="st">"100k-125k"</span>,<span class="st">"125k-150k"</span>,<span class="st">"150k-175k"</span>,<span class="st">"175k-200k"</span>,<span class="st">"200-225k"</span>,<span class="st">"225k-250k"</span>,<span class="st">"250k-275k"</span>,<span class="st">"275k-300k"</span>,<span class="st">"300-325k"</span>,<span class="st">"325k-350k"</span>,<span class="st">"350k-375k"</span>,<span class="st">"375k-400k"</span>,<span class="st">"400-425k"</span>,<span class="st">"425k-450k"</span>,<span class="st">"450k-475k"</span>,<span class="st">"475k-500k"</span>,<span class="st">"500k+"</span>))<span class="sc">+</span></span>
<span id="cb33-290"><a href="#cb33-290" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Education level"</span>, <span class="at">subtitle =</span> <span class="st">"Count by education level and salary range"</span>, <span class="at">y =</span> <span class="st">"Salary"</span>, <span class="at">x =</span> <span class="st">"Education level"</span>)</span>
<span id="cb33-291"><a href="#cb33-291" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb33-292"><a href="#cb33-292" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-293"><a href="#cb33-293" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-294"><a href="#cb33-294" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-295"><a href="#cb33-295" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-296"><a href="#cb33-296" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-297"><a href="#cb33-297" aria-hidden="true" tabindex="-1"></a><span class="fu">## Average Total Compensation for different years :</span></span>
<span id="cb33-298"><a href="#cb33-298" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-299"><a href="#cb33-299" aria-hidden="true" tabindex="-1"></a>If we want to see how average total compensation for different years looks like, we could use a scatter plot to deduce a relationship between average total compensation and year. From below plot, we could see that, the average total compensation decreased from 2020 to 2021. There could be multiple unwarranted reasons for this trend which could be deduced from the given plot.But I strongly feel that the economic downtime has something to do with the reduced compensations at Tech firms.</span>
<span id="cb33-300"><a href="#cb33-300" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-301"><a href="#cb33-301" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-304"><a href="#cb33-304" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb33-305"><a href="#cb33-305" aria-hidden="true" tabindex="-1"></a>data <span class="ot">=</span> data<span class="sc">%&gt;%</span> <span class="fu">na.omit</span>() <span class="sc">%&gt;%</span></span>
<span id="cb33-306"><a href="#cb33-306" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(Year) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">Mean_salary =</span> <span class="fu">mean</span>(totalyearlycompensation))</span>
<span id="cb33-307"><a href="#cb33-307" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(</span>
<span id="cb33-308"><a href="#cb33-308" aria-hidden="true" tabindex="-1"></a>  data,</span>
<span id="cb33-309"><a href="#cb33-309" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">y =</span>  <span class="fu">as.numeric</span>(Mean_salary), <span class="at">x =</span> <span class="fu">as.factor</span>(Year), <span class="at">color =</span> <span class="fu">factor</span>(Year), <span class="at">group =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb33-310"><a href="#cb33-310" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size=</span><span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb33-311"><a href="#cb33-311" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_viridis_d</span>() <span class="sc">+</span></span>
<span id="cb33-312"><a href="#cb33-312" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_linetype_manual</span>() <span class="sc">+</span></span>
<span id="cb33-313"><a href="#cb33-313" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Year"</span>, <span class="at">y =</span> <span class="st">"Average Total Compensation"</span>) <span class="sc">+</span></span>
<span id="cb33-314"><a href="#cb33-314" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"top"</span>)</span>
<span id="cb33-315"><a href="#cb33-315" aria-hidden="true" tabindex="-1"></a>p <span class="sc">+</span>  <span class="fu">geom_line</span>(<span class="at">color=</span><span class="st">'blue'</span>)</span>
<span id="cb33-316"><a href="#cb33-316" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb33-317"><a href="#cb33-317" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-318"><a href="#cb33-318" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-319"><a href="#cb33-319" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-320"><a href="#cb33-320" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-321"><a href="#cb33-321" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-322"><a href="#cb33-322" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-323"><a href="#cb33-323" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-324"><a href="#cb33-324" aria-hidden="true" tabindex="-1"></a><span class="fu">### CONCLUSION</span></span>
<span id="cb33-325"><a href="#cb33-325" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-326"><a href="#cb33-326" aria-hidden="true" tabindex="-1"></a>With all the analysis above, we can answer the following questions-</span>
<span id="cb33-327"><a href="#cb33-327" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-328"><a href="#cb33-328" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>The respondents are from different education backgrounds but the distribution is skewed towards peple who are atleast graduates. They make 99% of the participants, given its higher population (shown in excel sheet).</span>
<span id="cb33-329"><a href="#cb33-329" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-330"><a href="#cb33-330" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>There is a huge gender gap that can be noticed. While it can be concluded that there is only one female for every 4 males in the data that has job in our interested domain. It can also be noticed that men tend to pursue higher education more tham female. </span>
<span id="cb33-331"><a href="#cb33-331" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-332"><a href="#cb33-332" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>We see that there is a clear correlation between Education level (completed degree) vs job compensation. In every salary band such a trend is varying. Salary bands above 250k USD value individual accomplishments over educational degree. </span>
<span id="cb33-333"><a href="#cb33-333" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-334"><a href="#cb33-334" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>The average total compensation changes with every year. In fact it reduced from the year 2020 to 2021.</span>
<span id="cb33-335"><a href="#cb33-335" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-336"><a href="#cb33-336" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-337"><a href="#cb33-337" aria-hidden="true" tabindex="-1"></a><span class="fu">### Reflection</span></span>
<span id="cb33-338"><a href="#cb33-338" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-339"><a href="#cb33-339" aria-hidden="true" tabindex="-1"></a>Since it is my first project in R, I learned that working with a data set involves taking raw data, cleaning it, then visualizing and interpreting different relationships.</span>
<span id="cb33-340"><a href="#cb33-340" aria-hidden="true" tabindex="-1"></a>I focused on the variables that I was most intrigued by. Eg: I was curious about how gender/degrees influence jobs and compensation. What paths or roles do Data Science enthusiasts from different education backgrounds prefer? Which states are currently paying high? For somebody would I advise to pursue a masters degree in order to get a high salary?</span>
<span id="cb33-341"><a href="#cb33-341" aria-hidden="true" tabindex="-1"></a>I've enjoyed learning the process for exploratory data analysis and visualization.</span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>