{
  "hash": "08fee32f3c34a10ee2ec511093748907",
  "result": {
    "markdown": "---\ntitle: \"Challenge 2 - FAO_Stat\"\nauthor: \"Joseph Vincent\"\ndescription: \"Data wrangling: using group() and summarise()\"\ndate: \"03/01/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_2\n  - faostat\n  - Joseph Vincent\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(summarytools)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Reading in and cleaning up the Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# reading in FAO stat, dairy cattle and assigning to FAO_Dairy\nFAO_Dairy <- read.csv(\"_data/FAOSTAT_cattle_dairy.csv\")\nhead(FAO_Dairy)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Domain.Code            Domain Area.Code        Area Element.Code      Element\n1          QL Livestock Primary         2 Afghanistan         5318 Milk Animals\n2          QL Livestock Primary         2 Afghanistan         5420        Yield\n3          QL Livestock Primary         2 Afghanistan         5510   Production\n4          QL Livestock Primary         2 Afghanistan         5318 Milk Animals\n5          QL Livestock Primary         2 Afghanistan         5420        Yield\n6          QL Livestock Primary         2 Afghanistan         5510   Production\n  Item.Code                  Item Year.Code Year   Unit  Value Flag\n1       882 Milk, whole fresh cow      1961 1961   Head 700000    F\n2       882 Milk, whole fresh cow      1961 1961  hg/An   5000   Fc\n3       882 Milk, whole fresh cow      1961 1961 tonnes 350000    F\n4       882 Milk, whole fresh cow      1962 1962   Head 700000    F\n5       882 Milk, whole fresh cow      1962 1962  hg/An   5000   Fc\n6       882 Milk, whole fresh cow      1962 1962 tonnes 350000    F\n  Flag.Description\n1     FAO estimate\n2  Calculated data\n3     FAO estimate\n4     FAO estimate\n5  Calculated data\n6     FAO estimate\n```\n:::\n\n```{.r .cell-code}\n# removing unchanging and duplicate variables\n# turning Element into variables to remove duplicate observations\n# renaming new variables to contain units\n# assigning to FAO_Dairy_Clean\n\nFAO_Dairy_Clean <- FAO_Dairy %>%\n  select('Area', 'Element', 'Year', 'Value') %>%\n  pivot_wider(names_from = 'Element', values_from = 'Value') %>%\n  rename('Milk Animals (heads)' = 'Milk Animals') %>%\n  rename('Yield (hg/AN)' = 'Yield') %>%\n  rename('Production (tonnes)' = 'Production')\n  \nhead(FAO_Dairy_Clean)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 5\n  Area         Year `Milk Animals (heads)` `Yield (hg/AN)` `Production (tonnes)`\n  <chr>       <int>                  <int>           <int>                 <int>\n1 Afghanistan  1961                 700000            5000                350000\n2 Afghanistan  1962                 700000            5000                350000\n3 Afghanistan  1963                 780000            5128                400000\n4 Afghanistan  1964                 780000            5128                400000\n5 Afghanistan  1965                 870000            5172                450000\n6 Afghanistan  1966                 960000            5208                500000\n```\n:::\n:::\n\n\n## Describe the data\n\nThis data set appears to be describing dairy production - specifically, whole milk production - by area and year.\n\nThe earliest year is 1961 and the most recent year is 2018, though because the count of these years increases in the table below, this suggests that some countries either did not produce dairy or did not report data until later years.\n\nThere are 36,449 observations, but only 222 of those represent unique areas. Area is typically country, but also contains some broader regions including continents and even the entire world.\n\nThe original data set consists of 14 column names, but many of these variables are duplicates:\nFor example, 'Element' and 'Element.Code' or 'Year' and 'Year.Code'.\nIn addition to duplicates, there are a few that remain the same for each observation.\nFor example, 'Domain' is always 'Livestock Primary' and 'Item' is always 'Milk, Whole fresh cow'.\nThese suggest that the data comes from a larger dataset. For this analysis I removed these variables.\n\nThere are dublicate observations as well. This is because of the variables 'Element' and 'Unit'. For each country and year, the number of cows, yield per cow and total milk production are listed as separate observations.\nFor this analysis, I transformed the 'Element' variable into variables 'Milk Animals', 'Yield' and 'Production' and also included the units in each column name in order to get each obeservation onto its own row.\n\nThe median number of cows per year/area is 295,000.\nThe median tonnes of production is year/area is 9,001,419.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# summarizing the original data set, viewing year and area in tables\ndfSummary(FAO_Dairy)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nData Frame Summary  \nFAO_Dairy  \nDimensions: 36449 x 14  \nDuplicates: 0  \n\n----------------------------------------------------------------------------------------------------------------------------\nNo   Variable           Stats / Values                   Freqs (% of Valid)      Graph                  Valid      Missing  \n---- ------------------ -------------------------------- ----------------------- ---------------------- ---------- ---------\n1    Domain.Code        1. QL                            36449 (100.0%)          IIIIIIIIIIIIIIIIIIII   36449      0        \n     [character]                                                                                        (100.0%)   (0.0%)   \n\n2    Domain             1. Livestock Primary             36449 (100.0%)          IIIIIIIIIIIIIIIIIIII   36449      0        \n     [character]                                                                                        (100.0%)   (0.0%)   \n\n3    Area.Code          Mean (sd) : 775.2 (1713.8)       232 distinct values     :                      36449      0        \n     [integer]          min < med < max:                                         :                      (100.0%)   (0.0%)   \n                        1 < 141 < 5504                                           :                                          \n                        IQR (CV) : 146 (2.2)                                     :                                          \n                                                                                 :                 .                        \n\n4    Area               1. Afghanistan                     174 ( 0.5%)                                  36449      0        \n     [character]        2. Africa                          174 ( 0.5%)                                  (100.0%)   (0.0%)   \n                        3. Albania                         174 ( 0.5%)                                                      \n                        4. Algeria                         174 ( 0.5%)                                                      \n                        5. American Samoa                  174 ( 0.5%)                                                      \n                        6. Americas                        174 ( 0.5%)                                                      \n                        7. Angola                          174 ( 0.5%)                                                      \n                        8. Antigua and Barbuda             174 ( 0.5%)                                                      \n                        9. Argentina                       174 ( 0.5%)                                                      \n                        10. Asia                           174 ( 0.5%)                                                      \n                        [ 222 others ]                   34709 (95.2%)           IIIIIIIIIIIIIIIIIII                        \n\n5    Element.Code       Mean (sd) : 5416 (78.5)          5318 : 12158 (33.4%)    IIIIII                 36449      0        \n     [integer]          min < med < max:                 5420 : 12121 (33.3%)    IIIIII                 (100.0%)   (0.0%)   \n                        5318 < 5420 < 5510               5510 : 12170 (33.4%)    IIIIII                                     \n                        IQR (CV) : 192 (0)                                                                                  \n\n6    Element            1. Milk Animals                  12158 (33.4%)           IIIIII                 36449      0        \n     [character]        2. Production                    12170 (33.4%)           IIIIII                 (100.0%)   (0.0%)   \n                        3. Yield                         12121 (33.3%)           IIIIII                                     \n\n7    Item.Code          1 distinct value                 882 : 36449 (100.0%)    IIIIIIIIIIIIIIIIIIII   36449      0        \n     [integer]                                                                                          (100.0%)   (0.0%)   \n\n8    Item               1. Milk, whole fresh cow         36449 (100.0%)          IIIIIIIIIIIIIIIIIIII   36449      0        \n     [character]                                                                                        (100.0%)   (0.0%)   \n\n9    Year.Code          Mean (sd) : 1990.4 (16.8)        58 distinct values      . . .   . :   : : :    36449      0        \n     [integer]          min < med < max:                                         : : : . : : : : : :    (100.0%)   (0.0%)   \n                        1961 < 1991 < 2018                                       : : : : : : : : : :                        \n                        IQR (CV) : 29 (0)                                        : : : : : : : : : :                        \n                                                                                 : : : : : : : : : :                        \n\n10   Year               Mean (sd) : 1990.4 (16.8)        58 distinct values      . . .   . :   : : :    36449      0        \n     [integer]          min < med < max:                                         : : : . : : : : : :    (100.0%)   (0.0%)   \n                        1961 < 1991 < 2018                                       : : : : : : : : : :                        \n                        IQR (CV) : 29 (0)                                        : : : : : : : : : :                        \n                                                                                 : : : : : : : : : :                        \n\n11   Unit               1. Head                          12158 (33.4%)           IIIIII                 36449      0        \n     [character]        2. hg/An                         12121 (33.3%)           IIIIII                 (100.0%)   (0.0%)   \n                        3. tonnes                        12170 (33.4%)           IIIIII                                     \n\n12   Value              Mean (sd) : 4410235 (25744621)   24088 distinct values   :                      36375      74       \n     [integer]          min < med < max:                                         :                      (99.8%)    (0.2%)   \n                        7 < 43266 < 683217055                                    :                                          \n                        IQR (CV) : 692151 (5.8)                                  :                                          \n                                                                                 :                                          \n\n13   Flag               1. (Empty string)                10044 (27.6%)           IIIII                  36449      0        \n     [character]        2. *                               810 ( 2.2%)                                  (100.0%)   (0.0%)   \n                        3. A                              3070 ( 8.4%)           I                                          \n                        4. F                              7045 (19.3%)           III                                        \n                        5. Fc                            13136 (36.0%)           IIIIIII                                    \n                        6. Im                             2270 ( 6.2%)           I                                          \n                        7. M                                74 ( 0.2%)                                                      \n\n14   Flag.Description   1. Aggregate, may include of      3070 ( 8.4%)           I                      36449      0        \n     [character]        2. Calculated data               13136 (36.0%)           IIIIIII                (100.0%)   (0.0%)   \n                        3. Data not available               74 ( 0.2%)                                                      \n                        4. FAO data based on imputat      2270 ( 6.2%)           I                                          \n                        5. FAO estimate                   7045 (19.3%)           III                                        \n                        6. Official data                 10044 (27.6%)           IIIII                                      \n                        7. Unofficial figure               810 ( 2.2%)                                                      \n----------------------------------------------------------------------------------------------------------------------------\n```\n:::\n\n```{.r .cell-code}\ntable(select(FAO_Dairy, 'Year'))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nYear\n1961 1962 1963 1964 1965 1966 1967 1968 1969 1970 1971 1972 1973 1974 1975 1976 \n 594  594  594  594  594  594  594  594  594  594  594  594  594  594  594  594 \n1977 1978 1979 1980 1981 1982 1983 1984 1985 1986 1987 1988 1989 1990 1991 1992 \n 594  594  594  594  594  594  594  594  594  594  594  594  594  594  600  657 \n1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004 2005 2006 2007 2008 \n 663  664  664  664  664  664  665  666  666  666  666  666  666  669  671  669 \n2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 \n 671  669  669  672  672  674  674  674  672  672 \n```\n:::\n\n```{.r .cell-code}\ntable(select(FAO_Dairy, 'Area'))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nArea\n                                         Afghanistan \n                                                 174 \n                                              Africa \n                                                 174 \n                                             Albania \n                                                 174 \n                                             Algeria \n                                                 174 \n                                      American Samoa \n                                                 174 \n                                            Americas \n                                                 174 \n                                              Angola \n                                                 174 \n                                 Antigua and Barbuda \n                                                 174 \n                                           Argentina \n                                                 174 \n                                             Armenia \n                                                  81 \n                                                Asia \n                                                 174 \n                                           Australia \n                                                 174 \n                           Australia and New Zealand \n                                                 174 \n                                             Austria \n                                                 174 \n                                          Azerbaijan \n                                                  81 \n                                             Bahamas \n                                                 174 \n                                             Bahrain \n                                                 174 \n                                          Bangladesh \n                                                 174 \n                                            Barbados \n                                                 174 \n                                             Belarus \n                                                  81 \n                                             Belgium \n                                                  57 \n                                  Belgium-Luxembourg \n                                                 117 \n                                              Belize \n                                                 174 \n                                               Benin \n                                                 174 \n                                             Bermuda \n                                                 174 \n                                              Bhutan \n                                                 174 \n                    Bolivia (Plurinational State of) \n                                                 174 \n                              Bosnia and Herzegovina \n                                                  81 \n                                            Botswana \n                                                 174 \n                                              Brazil \n                                                 174 \n                              British Virgin Islands \n                                                  52 \n                                   Brunei Darussalam \n                                                  76 \n                                            Bulgaria \n                                                 174 \n                                        Burkina Faso \n                                                 174 \n                                             Burundi \n                                                 174 \n                                          Cabo Verde \n                                                 174 \n                                            Cambodia \n                                                 174 \n                                            Cameroon \n                                                 174 \n                                              Canada \n                                                 174 \n                                           Caribbean \n                                                 174 \n                            Central African Republic \n                                                 174 \n                                     Central America \n                                                 174 \n                                        Central Asia \n                                                  81 \n                                                Chad \n                                                 174 \n                                               Chile \n                                                 150 \n                                China, Hong Kong SAR \n                                                 174 \n                                     China, mainland \n                                                 174 \n                           China, Taiwan Province of \n                                                 174 \n                                            Colombia \n                                                 174 \n                                             Comoros \n                                                 174 \n                                               Congo \n                                                 174 \n                                          Costa Rica \n                                                 174 \n                                       Côte d'Ivoire \n                                                 174 \n                                             Croatia \n                                                  81 \n                                                Cuba \n                                                 174 \n                                              Cyprus \n                                                 174 \n                                             Czechia \n                                                  78 \n                                      Czechoslovakia \n                                                  96 \n               Democratic People's Republic of Korea \n                                                 174 \n                    Democratic Republic of the Congo \n                                                 174 \n                                             Denmark \n                                                 174 \n                                            Djibouti \n                                                 174 \n                                            Dominica \n                                                 174 \n                                  Dominican Republic \n                                                 174 \n                                      Eastern Africa \n                                                 174 \n                                        Eastern Asia \n                                                 174 \n                                      Eastern Europe \n                                                 174 \n                                             Ecuador \n                                                 174 \n                                               Egypt \n                                                 174 \n                                         El Salvador \n                                                 174 \n                                             Eritrea \n                                                  78 \n                                             Estonia \n                                                  81 \n                                            Eswatini \n                                                 174 \n                                            Ethiopia \n                                                  78 \n                                        Ethiopia PDR \n                                                  96 \n                                              Europe \n                                                 174 \n                         Falkland Islands (Malvinas) \n                                                 174 \n                                                Fiji \n                                                 174 \n                                             Finland \n                                                 174 \n                                              France \n                                                 174 \n                                       French Guyana \n                                                 174 \n                                    French Polynesia \n                                                 174 \n                                               Gabon \n                                                 174 \n                                              Gambia \n                                                 174 \n                                             Georgia \n                                                  81 \n                                             Germany \n                                                 174 \n                                               Ghana \n                                                 174 \n                                              Greece \n                                                 174 \n                                             Grenada \n                                                 174 \n                                          Guadeloupe \n                                                 174 \n                                           Guatemala \n                                                 174 \n                                              Guinea \n                                                 174 \n                                       Guinea-Bissau \n                                                 174 \n                                              Guyana \n                                                 174 \n                                               Haiti \n                                                 174 \n                                            Honduras \n                                                 174 \n                                             Hungary \n                                                 174 \n                                             Iceland \n                                                 174 \n                                               India \n                                                 174 \n                                           Indonesia \n                                                 174 \n                          Iran (Islamic Republic of) \n                                                 174 \n                                                Iraq \n                                                 174 \n                                             Ireland \n                                                 174 \n                                              Israel \n                                                 174 \n                                               Italy \n                                                 174 \n                                             Jamaica \n                                                 174 \n                                               Japan \n                                                 174 \n                                              Jordan \n                                                 174 \n                                          Kazakhstan \n                                                  81 \n                                               Kenya \n                                                 174 \n                                              Kuwait \n                                                 174 \n                                          Kyrgyzstan \n                                                  81 \n                    Lao People's Democratic Republic \n                                                 174 \n                                              Latvia \n                                                  81 \n                                             Lebanon \n                                                 174 \n                                             Lesotho \n                                                 174 \n                                             Liberia \n                                                 174 \n                                               Libya \n                                                 174 \n                                       Liechtenstein \n                                                 174 \n                                           Lithuania \n                                                  81 \n                                          Luxembourg \n                                                  57 \n                                          Madagascar \n                                                 174 \n                                              Malawi \n                                                 174 \n                                            Malaysia \n                                                 174 \n                                                Mali \n                                                 174 \n                                               Malta \n                                                 174 \n                                          Martinique \n                                                 174 \n                                          Mauritania \n                                                 174 \n                                           Mauritius \n                                                 174 \n                                           Melanesia \n                                                 174 \n                                              Mexico \n                                                 174 \n                                       Middle Africa \n                                                 174 \n                                            Mongolia \n                                                 174 \n                                          Montenegro \n                                                  39 \n                                          Montserrat \n                                                 174 \n                                             Morocco \n                                                 174 \n                                          Mozambique \n                                                 174 \n                                             Myanmar \n                                                 174 \n                                             Namibia \n                                                 174 \n                                               Nepal \n                                                 174 \n                                         Netherlands \n                                                 174 \n                       Netherlands Antilles (former) \n                                                 174 \n                                       New Caledonia \n                                                 174 \n                                         New Zealand \n                                                 174 \n                                           Nicaragua \n                                                 174 \n                                               Niger \n                                                 174 \n                                             Nigeria \n                                                 174 \n                                                Niue \n                                                 174 \n                                     North Macedonia \n                                                  81 \n                                     Northern Africa \n                                                 174 \n                                    Northern America \n                                                 174 \n                                     Northern Europe \n                                                 174 \n                                              Norway \n                                                 174 \n                                             Oceania \n                                                 174 \n                                                Oman \n                                                 174 \n                                            Pakistan \n                                                 174 \n                                           Palestine \n                                                  81 \n                                              Panama \n                                                 174 \n                                    Papua New Guinea \n                                                 174 \n                                            Paraguay \n                                                 174 \n                                                Peru \n                                                 174 \n                                         Philippines \n                                                 174 \n                                              Poland \n                                                 174 \n                                           Polynesia \n                                                 174 \n                                            Portugal \n                                                 174 \n                                         Puerto Rico \n                                                 174 \n                                               Qatar \n                                                 174 \n                                   Republic of Korea \n                                                 174 \n                                 Republic of Moldova \n                                                  81 \n                                             Réunion \n                                                 174 \n                                             Romania \n                                                 174 \n                                  Russian Federation \n                                                  81 \n                                              Rwanda \n                                                 174 \n                                         Saint Lucia \n                                                 174 \n                    Saint Vincent and the Grenadines \n                                                 174 \n                                               Samoa \n                                                 174 \n                               Sao Tome and Principe \n                                                 174 \n                                        Saudi Arabia \n                                                 174 \n                                             Senegal \n                                                 174 \n                                              Serbia \n                                                  39 \n                               Serbia and Montenegro \n                                                  42 \n                                          Seychelles \n                                                 174 \n                                        Sierra Leone \n                                                 174 \n                                            Slovakia \n                                                  78 \n                                            Slovenia \n                                                  81 \n                                     Solomon Islands \n                                                 174 \n                                             Somalia \n                                                 174 \n                                        South Africa \n                                                 174 \n                                       South America \n                                                 174 \n                                         South Sudan \n                                                  21 \n                                  South-eastern Asia \n                                                 174 \n                                     Southern Africa \n                                                 174 \n                                       Southern Asia \n                                                 174 \n                                     Southern Europe \n                                                 174 \n                                               Spain \n                                                 174 \n                                           Sri Lanka \n                                                 174 \n                                               Sudan \n                                                  21 \n                                      Sudan (former) \n                                                 153 \n                                            Suriname \n                                                 174 \n                                              Sweden \n                                                 174 \n                                         Switzerland \n                                                 174 \n                                Syrian Arab Republic \n                                                 174 \n                                          Tajikistan \n                                                  81 \n                                            Thailand \n                                                 174 \n                                                Togo \n                                                 174 \n                                               Tonga \n                                                 174 \n                                 Trinidad and Tobago \n                                                 174 \n                                             Tunisia \n                                                 174 \n                                              Turkey \n                                                 174 \n                                        Turkmenistan \n                                                  81 \n                                              Uganda \n                                                 174 \n                                             Ukraine \n                                                  81 \n                                United Arab Emirates \n                                                 174 \nUnited Kingdom of Great Britain and Northern Ireland \n                                                 174 \n                         United Republic of Tanzania \n                                                 174 \n                            United States of America \n                                                 174 \n                        United States Virgin Islands \n                                                 174 \n                                             Uruguay \n                                                 174 \n                                                USSR \n                                                  93 \n                                          Uzbekistan \n                                                  81 \n                                             Vanuatu \n                                                 174 \n                  Venezuela (Bolivarian Republic of) \n                                                 174 \n                                            Viet Nam \n                                                 174 \n                           Wallis and Futuna Islands \n                                                 174 \n                                      Western Africa \n                                                 174 \n                                        Western Asia \n                                                 174 \n                                      Western Europe \n                                                 174 \n                                               World \n                                                 174 \n                                               Yemen \n                                                 174 \n                                        Yugoslav SFR \n                                                  93 \n                                              Zambia \n                                                 174 \n                                            Zimbabwe \n                                                 174 \n```\n:::\n\n```{.r .cell-code}\n#summarizing the clean data set\ndfSummary(FAO_Dairy_Clean)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nData Frame Summary  \nFAO_Dairy_Clean  \nDimensions: 12170 x 5  \nDuplicates: 0  \n\n------------------------------------------------------------------------------------------------------------------------------\nNo   Variable               Stats / Values                   Freqs (% of Valid)     Graph                 Valid      Missing  \n---- ---------------------- -------------------------------- ---------------------- --------------------- ---------- ---------\n1    Area                   1. Afghanistan                      58 ( 0.5%)                                12170      0        \n     [character]            2. Africa                           58 ( 0.5%)                                (100.0%)   (0.0%)   \n                            3. Albania                          58 ( 0.5%)                                                    \n                            4. Algeria                          58 ( 0.5%)                                                    \n                            5. American Samoa                   58 ( 0.5%)                                                    \n                            6. Americas                         58 ( 0.5%)                                                    \n                            7. Angola                           58 ( 0.5%)                                                    \n                            8. Antigua and Barbuda              58 ( 0.5%)                                                    \n                            9. Argentina                        58 ( 0.5%)                                                    \n                            10. Asia                            58 ( 0.5%)                                                    \n                            [ 222 others ]                   11590 (95.2%)          IIIIIIIIIIIIIIIIIII                       \n\n2    Year                   Mean (sd) : 1990.4 (16.8)        58 distinct values     . . .   . :   : : :   12170      0        \n     [integer]              min < med < max:                                        : : : . : : : : : :   (100.0%)   (0.0%)   \n                            1961 < 1991 < 2018                                      : : : : : : : : : :                       \n                            IQR (CV) : 29 (0)                                       : : : : : : : : : :                       \n                                                                                    : : : : : : : : : :                       \n\n3    Milk Animals (heads)   Mean (sd) : 4205410 (18041595)   7915 distinct values   :                     12121      49       \n     [integer]              min < med < max:                                        :                     (99.6%)    (0.4%)   \n                            8 < 295000 < 276573845                                  :                                         \n                            IQR (CV) : 1525233 (4.3)                                :                                         \n                                                                                    :                                         \n\n4    Yield (hg/AN)          Mean (sd) : 19329.1 (19361)      8365 distinct values   :                     12121      49       \n     [integer]              min < med < max:                                        :                     (99.6%)    (0.4%)   \n                            923 < 13218 < 134121                                    :                                         \n                            IQR (CV) : 21367 (1)                                    : .                                       \n                                                                                    : : : . .                                 \n\n5    Production (tonnes)    Mean (sd) : 9001419 (40268994)   9646 distinct values   :                     12133      37       \n     [integer]              min < med < max:                                        :                     (99.7%)    (0.3%)   \n                            7 < 295500 < 683217055                                  :                                         \n                            IQR (CV) : 2736860 (4.5)                                :                                         \n                                                                                    :                                         \n------------------------------------------------------------------------------------------------------------------------------\n```\n:::\n:::\n\n\n## Provide Grouped Summary Statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# creating tables for 1961 and 2018 production\nfirstyear <- FAO_Dairy_Clean %>%\n  select('Area', 'Year', `Production (tonnes)`) %>%\n  filter(Year == \"1961\")\n\nlastyear <- FAO_Dairy_Clean %>%\n  select('Area', 'Year', `Production (tonnes)`) %>%\n  filter(Year == \"2018\")\n\n# calculating mean and median production for 1961 and 2018\nmedian(firstyear$`Production (tonnes)`)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 100368\n```\n:::\n\n```{.r .cell-code}\nmedian(lastyear$`Production (tonnes)`)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 602297.5\n```\n:::\n\n```{.r .cell-code}\n# How did production increase over time in Asia vs Europe\n# creating table of asian production\nAsiaproduction <- FAO_Dairy_Clean %>%\n  select('Area', 'Year', `Production (tonnes)`) %>%\n  filter(Area == \"Asia\") %>%\n  rename('Production' = 'Production (tonnes)')\n\n# mean and median of asian production over time\nmean(Asiaproduction$Production)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 80628670\n```\n:::\n\n```{.r .cell-code}\nmedian(Asiaproduction$Production)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 55479513\n```\n:::\n\n```{.r .cell-code}\n# graphing asian milk production from 1961-2018\nggplot(data = Asiaproduction) +\n  geom_line(mapping = aes(x = Year, y = Production))\n```\n\n::: {.cell-output-display}\n![](JosephVincent_challenge2_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# creating table of european production\nEuropeproduction <- FAO_Dairy_Clean %>%\n  select('Area', 'Year', `Production (tonnes)`) %>%\n  filter(Area == \"Europe\") %>%\n  rename('Production' = 'Production (tonnes)')\n\n# mean and median of asian production over time\nmean(Europeproduction$Production)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 228904979\n```\n:::\n\n```{.r .cell-code}\nmedian(Europeproduction$Production)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 220194403\n```\n:::\n\n```{.r .cell-code}\n# graphing asian milk production from 1961-2018\nggplot(data = Europeproduction) +\n  geom_line(mapping = aes(x = Year, y = Production))\n```\n\n::: {.cell-output-display}\n![](JosephVincent_challenge2_files/figure-html/unnamed-chunk-4-2.png){width=672}\n:::\n:::\n\n\n### Explain and Interpret\n\n# First year vs Last year\nFirst, I wanted to take a look at how milk production compared in the first year of data (1961) vs the last year of data (2018) for all areas.\nWe'll focus on median production here, since mean would be skewed too heavily by the continent observations.\nThe median production in 1961 for all areas was 100,368 tons.\nThe median production in 2018 for all areas was 602,297 tons.\nAs you can see, more milk is being produce per country in 2018.\n\n# Asia vs Europe\nNext, I wanted to compare two continents to see how their milk production compared.\nI looked at Asia and Europe.\nIn Asia, the median production over all years was 55,479,513 tons.\nIn Europe, the median production over all years was about 4 times higher, at 220,194,403 tons.\n\nWhen we graph the results, things get more interesting.\nAsia had an exponential growth in milk production over time.\nEurope had steady growth in milk production from the early sixties until about 1990, when milk production plunged. This has only recovered slightly in recent years.",
    "supporting": [
      "JosephVincent_challenge2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}