{
  "hash": "43d95f4a96fa205acf5390ab846d0ec9",
  "result": {
    "markdown": "---\ntitle: \"Joining SNL Datasets\"\nauthor: \"Kris Smole\"\ndescription: \"Using Join Functions to Combine Two or More Datasets into One Dataset\"\ndate: \"04/26/2023\"\nformat:\n  html:\n    toc: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_8\n\n  - snl\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(ggplot2)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Challenge Overview {#challenge-overview}\n\nToday's challenge is to:\n\n\n2)  tidy data (as needed, including sanity checks)\n3)  mutate variables as needed (including sanity checks)\n4)  join two or more data sets and analyze some aspect of the joined data (see detailed instruction below)\n\n(be sure to only include the category tags for the data you use!)\n\n## Reading in the SNL files: Actors, Casts, Seasons\n\n### Brief description of the SNL data sets\n\nThree datasets of the NBC television program, Saturday Night Live (SNL), exist with three themes: Actors, Casts, and Seasons. Let's take a look at the content and features of each dataset, and determine if and how these three datasets might be combined on common features to provide the combined dataset we want for performing the analysis we'd like to do.\n\n### The actors data set format and data content:\nFirst let's look at the actors file, and consider what columns might be options to use for joining with the other two files: \n\n::: {.cell}\n\n```{.r .cell-code}\n#creating actors variable from file snl_actors.csv:\nsnl_actors <- read_csv(\"_data/snl_actors.csv\")\n#The dataset of the file snl_actors.csv has __________\ndim(snl_actors)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2306    4\n```\n:::\n\n```{.r .cell-code}\nhead(snl_actors)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 4\n  aid            url           type  gender \n  <chr>          <chr>         <chr> <chr>  \n1 Kate McKinnon  /Cast/?KaMc   cast  female \n2 Alex Moffat    /Cast/?AlMo   cast  male   \n3 Ego Nwodim     /Cast/?EgNw   cast  unknown\n4 Chris Redd     /Cast/?ChRe   cast  male   \n5 Kenan Thompson /Cast/?KeTh   cast  male   \n6 Carey Mulligan /Guests/?3677 guest andy   \n```\n:::\n\n```{.r .cell-code}\n#Remove url column from actors file\nsnl_actors <- snl_actors %>% select(-c(url))\n#display head of snl_actors data set to confirm removal of url column\nhead(snl_actors)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 3\n  aid            type  gender \n  <chr>          <chr> <chr>  \n1 Kate McKinnon  cast  female \n2 Alex Moffat    cast  male   \n3 Ego Nwodim     cast  unknown\n4 Chris Redd     cast  male   \n5 Kenan Thompson cast  male   \n6 Carey Mulligan guest andy   \n```\n:::\n:::\n\nI removed the url column from the actors file, and I see in the changes took place, and the url is not included any longer.\n\nThe actors file has 2306 rows and 4 columns after removing the url column.\n\nLet's take a look at the actors data set using summarytools function:\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(summarytools::dfSummary(snl_actors,\n                        varnumbers = FALSE,\n                        plain.ascii  = FALSE, \n                        style        = \"grid\", \n                        graph.magnif = 0.70, \n                        valid.col    = FALSE),\n      method = 'render',\n      table.classes = 'table-condensed')\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"container st-container\">\n<h3>Data Frame Summary</h3>\n<h4>snl_actors</h4>\n<strong>Dimensions</strong>: 2306 x 3\n  <br/><strong>Duplicates</strong>: 0\n<br/>\n<table class=\"table table-striped table-bordered st-table st-table-striped st-table-bordered st-multiline table-condensed\">\n  <thead>\n    <tr>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Variable</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Stats / Values</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Freqs (% of Valid)</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Graph</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Missing</strong></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td align=\"left\">aid\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. 'N Sync</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. 070 Shake</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. 10,000 Maniacs</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. 14 Karat Soul</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. 2 Chainz</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. 3-D</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. 3RDEYEGIRL</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. 50 Cent</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">9. A Tribe Called Quest</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">10. A. Whitney Brown</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">[ 2296 others ]</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2296</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">99.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAHUAAAC9CAQAAAAntvruAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnBBwQDCit/Iv7AAABP0lEQVR42u3XQQrCQBQFQSPe0ZN5CE+p24ngRoVg/S5XISBpMoJve5ymOB/9AKWW+pXH8rlxP9y1btBbLVVUqqhUUamiUkWligalbutu245+mp9b6wa91V2qN83fptpKFZUqKlVUqqhUUamiQalNc1HTXFSqqFRRqaJSRaWKShW1V0XtVVGpolJFpYpKFZUqKlU0KLVpLmqai0oVlSoqVVSqqFRRqaJBqU1zUdNcVKqoVFGpolJFpYpKFbVXRe1VUamiUkWlikoVlSoqVTQotWkuapqLShWVKipVVKqoVFGpovaqqL0qKlVUqqhUUamiUkWligalNs1FTXNRqaJSRaWKShWVKipVNCi1aS66rBfgNF8O6mV/53r0o/3UfXc16ACXKipVVKqoVFGpopf/wPfPvuUvbN6YeWfQAS5V9AQ/lDZhDrIF9wAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMy0wNC0yOFQxNjoxMjo0MCswMDowMAd49nQAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjMtMDQtMjhUMTY6MTI6NDArMDA6MDB2JU7IAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">type\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. cast</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. crew</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. guest</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. unknown</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">154</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">6.7%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">170</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">7.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1926</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">83.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">56</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">2.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGQAAABJCAQAAABh2Us3AAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnBBwQDCit/Iv7AAAAy0lEQVRo3u3ZsQ3CQBAFUQ65R4qgHuiBKiFkfRaWiDz7PS8COdkRZ+lWjPclw/XoAQxJDVnql+f0wtzH0ePtq+Mu60e38vl19Jx/iTlahtAYQmMIjSE0htBMd61e96tq1Bsk/LK7UWfPPFqPZvvIzxD3EQBDaAyhMYTGEBpDaGJCXKwIzrdY4ZUjtLNY0a3f55ijZQiNITSG0BhCYwhNTIiLFcFZFqtO/1N9Tb9Ip8VqN6QvQ2gMoTGExhAaQ2hSQ0IWq85Sj1ZfMSEfyHMXLQ4zwacAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjMtMDQtMjhUMTY6MTI6NDArMDA6MDAHePZ0AAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIzLTA0LTI4VDE2OjEyOjQwKzAwOjAwdiVOyAAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">gender\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. andy</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. female</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. male</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. unknown</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">21</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.9%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">671</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">29.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1226</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">53.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">388</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">16.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAEQAAABJCAQAAAAuhEjnAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnBBwQDCit/Iv7AAAArklEQVRo3u3ZSw6AIAxF0WLYo4twPboHV4nTQuIAyqch982Y6Ikl6UsMSXzkWA0A8peoD08SucK8l+v76eaLAAECBAgQIKMT9AacuHhFxOn2zfrIbSqwtiYT8+PZ/KDX+EXcjAYIECBAgGwLKZaedXW1h2JUpmMxaogaQbdiVJ/8ProZDRAgQIAA2RZCMRLZpRiN+sNVWYzG3SE3owECBAgQINtCfBajlXEzGiBlPuuHFi3ZlefKAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIzLTA0LTI4VDE2OjEyOjQwKzAwOjAwB3j2dAAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMy0wNC0yOFQxNjoxMjo0MCswMDowMHYlTsgAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n  </tbody>\n</table>\n<p>Generated by <a href='https://github.com/dcomtois/summarytools'>summarytools</a> 1.0.1 (<a href='https://www.r-project.org/'>R</a> version 4.2.2)<br/>2023-04-28</p>\n</div>\n```\n:::\n:::\n\nSummarytools provides more information than we may have needed, yet when we see all of this information about the data set, we may be inspired to consider additional analysis, or investigate aspects of the data set we weren't previously focusing upon.\n\n### The casts data set format and data content:\n\nHere's the basic file characteristics for the casts data set:\n\n::: {.cell}\n\n```{.r .cell-code}\n#creating casts variable from file snl_casts.csv\nsnl_casts <- read_csv(\"_data/snl_casts.csv\")\n#The dataset of the file snl_casts.csv format and content\ndim(snl_casts)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 614   8\n```\n:::\n\n```{.r .cell-code}\nhead(snl_casts)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 8\n  aid                sid featured first_epid last_epid update_…¹ n_epi…² seaso…³\n  <chr>            <dbl> <lgl>         <dbl>     <dbl> <lgl>       <dbl>   <dbl>\n1 A. Whitney Brown    11 TRUE       19860222        NA FALSE           8   0.444\n2 A. Whitney Brown    12 TRUE             NA        NA FALSE          20   1    \n3 A. Whitney Brown    13 TRUE             NA        NA FALSE          13   1    \n4 A. Whitney Brown    14 TRUE             NA        NA FALSE          20   1    \n5 A. Whitney Brown    15 TRUE             NA        NA FALSE          20   1    \n6 A. Whitney Brown    16 TRUE             NA        NA FALSE          20   1    \n# … with abbreviated variable names ¹​update_anchor, ²​n_episodes,\n#   ³​season_fraction\n```\n:::\n:::\n\nThe casts file has 614 rows and 8 columns.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(summarytools::dfSummary(snl_casts,\n                        varnumbers = FALSE,\n                        plain.ascii  = FALSE, \n                        style        = \"grid\", \n                        graph.magnif = 0.70, \n                        valid.col    = FALSE),\n      method = 'render',\n      table.classes = 'table-condensed')\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"container st-container\">\n<h3>Data Frame Summary</h3>\n<h4>snl_casts</h4>\n<strong>Dimensions</strong>: 614 x 8\n  <br/><strong>Duplicates</strong>: 0\n<br/>\n<table class=\"table table-striped table-bordered st-table st-table-striped st-table-bordered st-multiline table-condensed\">\n  <thead>\n    <tr>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Variable</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Stats / Values</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Freqs (% of Valid)</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Graph</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Missing</strong></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td align=\"left\">aid\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. Kenan Thompson</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. Darrell Hammond</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. Seth Meyers</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. Al Franken</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. Fred Armisen</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. Kate McKinnon</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. Tim Meadows</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. Aidy Bryant</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">9. Bobby Moynihan</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">10. Cecily Strong</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">[ 146 others ]</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">18</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">2.9%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">14</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">2.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">13</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">2.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">1.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">1.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">10</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">1.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">10</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">1.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">9</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">1.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">9</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">1.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">9</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">1.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">500</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">81.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGIAAAC9CAQAAADixGB/AAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnBBwQDCit/Iv7AAABbklEQVR42u3dQU4CQRRF0cawRxfhenAPrhInxtBoNGFA3/o5Z8asbyiSfpPidN3W93L0A4iYFHG+/fD+9QN5Ox39WP+7/S3ffROv2+vRT/eAEcdJRIWIChEVIipEVIyIOO8/fhz9PA853b7SLvAG/u2PV/E17Y7T5bpta0yivR+jaEUjjpOIChEVIipEVIiomBhhFD2VUVRkFFWIqBBRIaJCRIWICnviSPZEkT1RIaJCRIWIChEVIiomRhhFT2UUFRlFFSIqRFSIqBBRIaJiYoRR9FTjRtEu4nK9LHmNx7xvYlUiKkRUiKgQUSGiYkSEPVFhT1SIqBBRIaJCRIWIChEVIyKMogqjqEJEhYgKERUiKkRUiKiwJyrsiQoRFSIqRFSIqBBRIaJiRIRRVGEUVYioEFEhokJEhYgKERUjIoyiil/uPFvEzbG5+wfaVe4821/NMeI4iagQUSGiQkSFiIq7d6cB14WtasRxElHxCcLsOtL6736BAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIzLTA0LTI4VDE2OjEyOjQwKzAwOjAwB3j2dAAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMy0wNC0yOFQxNjoxMjo0MCswMDowMHYlTsgAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">sid\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 25.5 (13.1)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1 &le; 26 &le; 46</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 22 (0.5)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">46 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAG0AAABPCAQAAABLlYPgAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnBBwQDCit/Iv7AAABE0lEQVR42u2aQQ6CMBBFreGO3EHPg3fwlLqtOCKZtND389+uLJo+8qdDScvrosr17AVYzWo1Uz0o6WmWoGTv+enS1MuY0rOsmFfjZ9MlL+Fut/3ymqn1Zv568u/lCdeasNqAgVwafUUMqJapqwjhQAqrHRrITHeCqLWqon0IB9JqRAboa61a9IFqe5fc68zQUe3I3TBCuNasRsRqRITVEpt/rxY7gNr5HWsfwoEUVvsIJKWKEmrRpyqjriKEA2k1IlYjYjUiViNiNSJWI2I1IlYjYjUiViNiNSLCagNcrsgT/O2u7nuh1bavZQgH0mpErEbEakSsRsRqRKxGxGpESn2ae+AvMt2qo2jB2/xEOJBWI/IGki0gMi2FOB4AAAAldEVYdGRhdGU6Y3JlYXRlADIwMjMtMDQtMjhUMTY6MTI6NDArMDA6MDAHePZ0AAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIzLTA0LTI4VDE2OjEyOjQwKzAwOjAwdiVOyAAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">featured\n[logical]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. FALSE</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. TRUE</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">451</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">73.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">163</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">26.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFkAAAAoCAQAAAA/fJ5AAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnBBwQDCit/Iv7AAAAgklEQVRYw+3WwQmAMAxG4Ubc0R10Ht2hU+q1SrwUTfPDe7deygdNIXYWtabRAMg5m9vDkXawV3shl7KMtrnV20lwMCBDhgwZcq4gQ3Z7rEW175bQrN03rfuav2uV6oOxd6/4W+ADfbLix/4AwcGADBkyZMi5ggzZTX3F10hwMCBHdAGkfQuprNQRTAAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMy0wNC0yOFQxNjoxMjo0MCswMDowMAd49nQAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjMtMDQtMjhUMTY6MTI6NDArMDA6MDB2JU7IAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">first_epid\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 19909634 (111264.8)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">19770115 &le; 19901110 &le; 20141025</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 156624.2 (0)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">35 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAG0AAABPCAQAAABLlYPgAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnBBwQDCit/Iv7AAAA90lEQVR42u2bQQ7CIBAAxfSP/kHfU//gK/WKphgI2dDZzNzalMIkW7J0obwvWbmuHoBqqtVs9UVpPLQ3P8hHq8ki6oFufU1uh3dfq03+kjggVSOiGhHViKhGRDUiqhHpzPzHOMciKETtHIugxAGpGhHViKhGRDUiqhFRjYhqRFQjohoR1YioRkQ1IqoRSaz2Vc7Yw/d9tno4ruDMVXx+KjXRFZbR98+MJ3FAqkZksioaP/EM9ltNL5Nqqwq7Pf0mDkjViKhGRDUiidWC9miNEpHVnEQtIqtJHJCqEVGNiGpEEquVOg144o/W36t/IwVv0yRxQKpG5ANxTRz+AHP3/wAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMy0wNC0yOFQxNjoxMjo0MCswMDowMAd49nQAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjMtMDQtMjhUMTY6MTI6NDArMDA6MDB2JU7IAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">564\n(91.9%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">last_epid\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 19944038 (126122.2)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">19751011 &le; 19950225 &le; 20140201</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 190005 (0)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">17 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAG0AAABPCAQAAABLlYPgAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnBBwQDCit/Iv7AAAA5UlEQVR42u3awQ3CMBAAQYzSIz1APaEHqoTvIWEpjm2SPe38yCPHSuZxMuV9yep69BcwzbRoiR/K5GFr9Yf9GDQ6Dlh2v2WX28+nrymzEh9I04hMIzKNyDQi04hMIzKN6Gtfm78qHpb231VxtsQH0jQi04hMIzKNyDQi04hMI0qc1nUrOm4rX0f9xyPM7bzwHbWV197T+jxKfCBNIzKNyDQi04hMIzKNyDSixGkbV9HWLXjY1jw/rXWbPsOdeOIDaRqRaUSmEZlGZBqRaUSmEZW4Mz5PsED2uYcL34KvqUp8IE0j+gCQWRlmMB+CWAAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMy0wNC0yOFQxNjoxMjo0MCswMDowMAd49nQAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjMtMDQtMjhUMTY6MTI6NDArMDA6MDB2JU7IAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">597\n(97.2%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">update_anchor\n[logical]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. FALSE</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. TRUE</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">541</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">88.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">73</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">11.9%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGkAAAAoCAQAAABXjxx4AAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnBBwQDCit/Iv7AAAAi0lEQVRo3u2XQQqAMAwEG/GP/kHfo3/oK/VahYL0EmfdueUSMjSBbpxFjSl7ACv9U2luiwN7WGt0lEpZsmcbot4qwcWzEgErEbASASsRsBIBQaXHt7WOdfkU0eaJGG6TTWuhvnh7NwJuoAd8FQFZFya4eFYiYCUCViJgJQJWIiCopB4BNRBcPCsRuADEmwupHej2EAAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMy0wNC0yOFQxNjoxMjo0MCswMDowMAd49nQAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjMtMDQtMjhUMTY6MTI6NDArMDA6MDB2JU7IAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">n_episodes\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 18.7 (4)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1 &le; 20 &le; 24</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 2 (0.2)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">22 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAG0AAABPCAQAAABLlYPgAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnBBwQDCit/Iv7AAAA8klEQVR42u3bQQ6CMBQAUTDc0TvoefAOnlK3tY00P0Do/MzsiCH2SWOJlfkzZe129QCkSStbyoP56tFUrc0XwbMzxPKEZRq6+8/RO3Ru4gkpjZg0YtKISSMmjZg0YtKISSMmjZg0YtKISSMmjZg0Yolpg29C1dU7blv7bTBaZL8t8YSURkwaMWnEpBGTRkwaMWnEpBGTRkwascS0oX6sWw99wGco2r7/9dclnpDSiEkjJo3Yqeta/NE6DK1dgiO7moPTetQzC9F6Eyx+D3jsXeMGrf9GvQkWvSp7r2Iz4uKjnsvXXvhH6x//aLlKvK5JI/YFJekiKMI7qMYAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjMtMDQtMjhUMTY6MTI6NDArMDA6MDAHePZ0AAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIzLTA0LTI4VDE2OjEyOjQwKzAwOjAwdiVOyAAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">season_fraction\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 0.9 (0.2)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 1 &le; 1</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 0 (0.2)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">36 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAG0AAABPCAQAAABLlYPgAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnBBwQDCit/Iv7AAAAv0lEQVR42u3bsQ2DMBgFYYy8Y3aAecwOmZK0v8FIRingrPs6N8BJQPfSPo1qfvoBTDMtyvGQnn6aW0rjN7GEhNx/qff5HM7f6jTwC2kakWlEphGZRmQakWlEphGZRmQakWlEphGZRmQakWlEphGZRmQakWlEphGZRmQakWlEphGZRmQakWlEphGZRmQakWlEphGZRmQaUbUVbQ1L19M2tjRX6mvHhrb8sW/vuX4txbtt+Gl9XPgmfM2lgb8104h+7FsOn420pZIAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjMtMDQtMjhUMTY6MTI6NDArMDA6MDAHePZ0AAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIzLTA0LTI4VDE2OjEyOjQwKzAwOjAwdiVOyAAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n  </tbody>\n</table>\n<p>Generated by <a href='https://github.com/dcomtois/summarytools'>summarytools</a> 1.0.1 (<a href='https://www.r-project.org/'>R</a> version 4.2.2)<br/>2023-04-28</p>\n</div>\n```\n:::\n:::\n\n\n\n\n### The seasons data set format and data content:\n\nHere's the basic file characteristics for the seasons data set:\n\n::: {.cell}\n\n```{.r .cell-code}\n#creating seasons variable from file snl_seasons.csv:\nsnl_seasons <- read_csv(\"_data/snl_seasons.csv\")\n#Showing the format and contents of the data set of the file snl_seasons.csv \ndim(snl_seasons)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 46  5\n```\n:::\n\n```{.r .cell-code}\nhead(snl_seasons)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 5\n    sid  year first_epid last_epid n_episodes\n  <dbl> <dbl>      <dbl>     <dbl>      <dbl>\n1     1  1975   19751011  19760731         24\n2     2  1976   19760918  19770521         22\n3     3  1977   19770924  19780520         20\n4     4  1978   19781007  19790526         20\n5     5  1979   19791013  19800524         20\n6     6  1980   19801115  19810411         13\n```\n:::\n:::\n\nNow, let's take a look at the seasons data set using summarytools function:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(summarytools::dfSummary(snl_seasons,\n                        varnumbers = FALSE,\n                        plain.ascii  = FALSE, \n                        style        = \"grid\", \n                        graph.magnif = 0.70, \n                        valid.col    = FALSE),\n      method = 'render',\n      table.classes = 'table-condensed')\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"container st-container\">\n<h3>Data Frame Summary</h3>\n<h4>snl_seasons</h4>\n<strong>Dimensions</strong>: 46 x 5\n  <br/><strong>Duplicates</strong>: 0\n<br/>\n<table class=\"table table-striped table-bordered st-table st-table-striped st-table-bordered st-multiline table-condensed\">\n  <thead>\n    <tr>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Variable</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Stats / Values</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Freqs (% of Valid)</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Graph</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Missing</strong></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td align=\"left\">sid\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 23.5 (13.4)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1 &le; 23.5 &le; 46</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 22.5 (0.6)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">46 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAG0AAABPCAQAAABLlYPgAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnBBwQDCna+7ttAAAAvklEQVR42u3bXQpAQBRAYaPZoz2wHvZglbxeJlKKzu18b8ZPTo2aB1O2Lqv+7xcwzbSoxoMF9uFN5TwSA+rx1HC6dG1Gno59cee9xBPSNCLTiEwjMo3INCLTiEwjMo3INCLTiEwjMo3INCLTiEwjMo3INCLTiEwjMo3INCLTiEwjMo3INCLTiBKn1feP+M/c7ksIf/6j09odAlHiCWkakWlEphGZRmQaUeK0EhfPtB2+rTGs/Au+5lLiCWka0Q40UBQ28F7wdAAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMy0wNC0yOFQxNjoxMjo0MSswMDowMKEP/cAAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjMtMDQtMjhUMTY6MTI6NDErMDA6MDDQUkV8AAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">year\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 1997.5 (13.4)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1975 &le; 1997.5 &le; 2020</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 22.5 (0)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">46 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAG0AAABPCAQAAABLlYPgAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnBBwQDCna+7ttAAAAxklEQVR42u3bQQqDMBQA0abkjt7BnsfcwVO22y9NaKiLMJ95OzVKBiLoIuX9yOq5egKmmRbVeNC6L96rrJ7kvBhQr5e2r8Hn6tn+LfGCNI3INCLTiEwjSpxWfw85SL904Xt3Im3rnDtvnr17/+ipUeIFaRqRaUSmEZlGZBqRaUSmEZlGZBqRaUSmEZlGZBqRaUSmEZlGZBqRaUSmEZlGZBqRaUSmEZlGZBqRaUSmESVOK3HrRSPtw+jaw+6Mgq8ZSrwgTSP6AHDmEzZnBOdFAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIzLTA0LTI4VDE2OjEyOjQxKzAwOjAwoQ/9wAAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMy0wNC0yOFQxNjoxMjo0MSswMDowMNBSRXwAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">first_epid\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 19975965 (134209.3)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">19751011 &le; 19975926 &le; 20201003</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 224910.2 (0)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">46 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAG0AAABPCAQAAABLlYPgAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnBBwQDCna+7ttAAAAvklEQVR42u3bXQpAQBRAYaPZoz2wHvZglbxeJlKKzu18b8ZPTo2aB1O2Lqv+7xcwzbSoxoMF9uFN5TwSA+rx1HC6dG1Gno59cee9xBPSNCLTiEwjMo3INCLTiEwjMo3INCLTiEwjMo3INCLTiEwjMo3INCLTiEwjMo3INCLTiEwjMo3INCLTiBKn1feP+M/c7ksIf/6j09odAlHiCWkakWlEphGZRmQaUeK0EhfPtB2+rTGs/Au+5lLiCWka0Q40UBQ28F7wdAAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMy0wNC0yOFQxNjoxMjo0MSswMDowMKEP/cAAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjMtMDQtMjhUMTY6MTI6NDErMDA6MDDQUkV8AAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">last_epid\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 19985509 (134223.9)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">19760731 &le; 19985512 &le; 20210410</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 225066.2 (0)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">46 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAG0AAABPCAQAAABLlYPgAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnBBwQDCna+7ttAAAAzklEQVR42u3aywmFMBQAUSP2aA9az7MHq9TtlfhUcGHmMrPzBzkQIWjK1mWt/3oA0qTFhnhQqsu/pl/FuRpwHO5w9/hYnVkfnXt217snr0s8IaURk0ZMGjFpxKQRS0w7LI/bXue/onUnq3BuiSekNGLSiEkjJo2YNGLSiEkjJo2YNGLSiEkjJo1YYtrtlpiWO/lHEfb/oGnXfygST0hpxKQRk0ZMGjFpxKQRk0ZMGjFpxKQRk0ZMGrHEtBI/my/4ff5T+OZf8Jq/JZ6Q0ojtU/sVzp8UQw4AAAAldEVYdGRhdGU6Y3JlYXRlADIwMjMtMDQtMjhUMTY6MTI6NDErMDA6MDChD/3AAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIzLTA0LTI4VDE2OjEyOjQxKzAwOjAw0FJFfAAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">n_episodes\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 19.7 (2.3)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">12 &le; 20 &le; 24</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 1 (0.1)</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">12</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">2.2%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">13</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">2</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">4.3%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">17</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">2</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">4.3%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">18</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">2</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">4.3%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">19</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">3</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">6.5%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">20</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">23</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">50.0%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">21</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">7</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">15.2%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">22</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">5</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">10.9%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">24</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">2.2%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAEEAAACcCAQAAACKXg4/AAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnBBwQDCna+7ttAAABIElEQVR42u3cwQ3CMBBE0TGiR4qgHtMDVYZDADmWCeHg3UH6e+PEk2cljyBKWZQ9p2wAhHXO7YfbIknXMv9r2w3sTuGScAoGQUCAAAEChAOEewKhtHdWwBX5nJ2bMmM2faG+cRGdYUh49YXYjTAIAgIECBAgmBK6a4rKkjVUFskiCAgQIECAYEqgskh+QVBZ8gYCBAgQIIyGviD5BVG7x3tiWsOwL6wTtRcGQUCAAAECBFMClUXyC6LGPZHcHPhOZZk3240zCAICBAgQIJgSqCySXxDfK8uM311+qixzNsUgCAgQIECAMBr6guQXxKe+MPffmQN9YfZ+GAQBAQIECBBMCVQWyS+IGvY6kHZ4HQgECBAgQPgfQnplsTgFCFnzAA5pM4cE8gHyAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIzLTA0LTI4VDE2OjEyOjQxKzAwOjAwoQ/9wAAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMy0wNC0yOFQxNjoxMjo0MSswMDowMNBSRXwAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n  </tbody>\n</table>\n<p>Generated by <a href='https://github.com/dcomtois/summarytools'>summarytools</a> 1.0.1 (<a href='https://www.r-project.org/'>R</a> version 4.2.2)<br/>2023-04-28</p>\n</div>\n```\n:::\n:::\n\n\n\n\n\n### How the data sets will be joined:   \nFrom seeing the contents and format of the data sets, we see the column names of each dataset, and deduce that the three datasets do not have common columns among all three data sets. Casts and seasons data sets share common data in their columns entitled \"sid\". Casts and actors data sets shared common data in their columns entitled \"aid\". We'll join the three data sets in two steps within a piped function set:\n\n1.Join snl_casts to snl_seasons\n\n2.Join data set created in Step 1 to snl_actors.\n\n# Tidy Data steps needed?\n\nAlthough not every single column of the three data sets are needed - specifically one column in snl_actors, entitled \"URL\". When reviewing the individual data sets above, I removed the url column, and checked that the removal was successful. Retaining the rest of the columns within the data sets provides the possibilities of unanticipated analysis by keeping the columns and rows of the three data sets. Because the size of the data set files are not extraordinarily large, we can easily keep all of the data sets' contents without burdening our coding work or analysis.\n\n::: {.cell}\n\n:::\n\n## Joining the data sets\n\n\n### Joining all 3 data sets:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#full join of joined casts and seasons to actors\n\nSNL_csa<-full_join(snl_casts, snl_seasons, by=\"sid\")%>%\n  full_join(.,snl_actors, by=\"aid\")\n\nhead(SNL_csa)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 14\n  aid          sid featu…¹ first…² last_…³ updat…⁴ n_epi…⁵ seaso…⁶  year first…⁷\n  <chr>      <dbl> <lgl>     <dbl>   <dbl> <lgl>     <dbl>   <dbl> <dbl>   <dbl>\n1 A. Whitne…    11 TRUE     1.99e7      NA FALSE         8   0.444  1985  1.99e7\n2 A. Whitne…    12 TRUE    NA           NA FALSE        20   1      1986  1.99e7\n3 A. Whitne…    13 TRUE    NA           NA FALSE        13   1      1987  1.99e7\n4 A. Whitne…    14 TRUE    NA           NA FALSE        20   1      1988  1.99e7\n5 A. Whitne…    15 TRUE    NA           NA FALSE        20   1      1989  1.99e7\n6 A. Whitne…    16 TRUE    NA           NA FALSE        20   1      1990  1.99e7\n# … with 4 more variables: last_epid.y <dbl>, n_episodes.y <dbl>, type <chr>,\n#   gender <chr>, and abbreviated variable names ¹​featured, ²​first_epid.x,\n#   ³​last_epid.x, ⁴​update_anchor, ⁵​n_episodes.x, ⁶​season_fraction,\n#   ⁷​first_epid.y\n```\n:::\n\n```{.r .cell-code}\ndim(SNL_csa)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2764   14\n```\n:::\n:::\n\nThe combined data set of the 3 files for SNL has 2764 rows with 14 columns. The actors file had 2764 rows, so this data set's count of rows is what we were expecting.\n\n## \nWe see the join of all three data sets was successful.  \n\nWe can now see the full summarytools view of all three data sets now combined into one data set:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(summarytools::dfSummary(SNL_csa,\n                        varnumbers = FALSE,\n                        plain.ascii  = FALSE, \n                        style        = \"grid\", \n                        graph.magnif = 0.70, \n                        valid.col    = FALSE),\n      method = 'render',\n      table.classes = 'table-condensed')\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"container st-container\">\n<h3>Data Frame Summary</h3>\n<h4>SNL_csa</h4>\n<strong>Dimensions</strong>: 2764 x 14\n  <br/><strong>Duplicates</strong>: 0\n<br/>\n<table class=\"table table-striped table-bordered st-table st-table-striped st-table-bordered st-multiline table-condensed\">\n  <thead>\n    <tr>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Variable</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Stats / Values</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Freqs (% of Valid)</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Graph</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Missing</strong></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td align=\"left\">aid\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. Kenan Thompson</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. Darrell Hammond</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. Seth Meyers</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. Al Franken</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. Fred Armisen</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. Kate McKinnon</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. Tim Meadows</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. Aidy Bryant</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">9. Bobby Moynihan</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">10. Cecily Strong</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">[ 2296 others ]</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">18</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.7%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">14</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">13</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">10</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">10</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">9</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">9</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">9</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2650</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">95.9%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAHEAAAC9CAQAAAAuXVqUAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnBBwQDCna+7ttAAABP0lEQVR42u3XQQrCQBQFQSPe0ZN5CE+p24kgiAiR+l2uQkDSZATf9jjpzkc/QIklfuSxfG7MD3OtGvAWSxSUKChRUKKgREGJggGJ27qftqOf5mfWqgFvcZfoTOK3iaYSBSUKShSUKChRUKJgQGKTWNAkFpQoKFFQoqBEQYmCEgXtRUF7UVCioERBiYISBSUKShQMSGwSC5rEghIFJQpKFJQoKFFQomBAYpNY0CQWlCgoUVCioERBiYISBe1FQXtRUKKgREGJghIFJQpKFAxIbBILmsSCEgUlCkoUlCgoUVCioL0oaC8KShSUKChRUKKgREGJggGJTWJBk1hQoqBEQYmCEgUlCkoUDEhsEgsu6wU0iZcDednfuR79aD9x310NOKglCkoUlCgoUVCi4OU/6v27b/lrmzMu3hlwUEsUPAFiZjZhRvflmgAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMy0wNC0yOFQxNjoxMjo0MSswMDowMKEP/cAAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjMtMDQtMjhUMTY6MTI6NDErMDA6MDDQUkV8AAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">sid\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 25.5 (13.1)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1 &le; 26 &le; 46</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 22 (0.5)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">46 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAG0AAABPCAQAAABLlYPgAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnBBwQDCna+7ttAAABE0lEQVR42u2aQQ6CMBBFreGO3EHPg3fwlLqtOCKZtND389+uLJo+8qdDScvrosr17AVYzWo1Uz0o6WmWoGTv+enS1MuY0rOsmFfjZ9MlL+Fut/3ymqn1Zv568u/lCdeasNqAgVwafUUMqJapqwjhQAqrHRrITHeCqLWqon0IB9JqRAboa61a9IFqe5fc68zQUe3I3TBCuNasRsRqRITVEpt/rxY7gNr5HWsfwoEUVvsIJKWKEmrRpyqjriKEA2k1IlYjYjUiViNiNSJWI2I1IlYjYjUiViNiNSLCagNcrsgT/O2u7nuh1bavZQgH0mpErEbEakSsRsRqRKxGxGpESn2ae+AvMt2qo2jB2/xEOJBWI/IGki0gMi2FOB4AAAAldEVYdGRhdGU6Y3JlYXRlADIwMjMtMDQtMjhUMTY6MTI6NDErMDA6MDChD/3AAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIzLTA0LTI4VDE2OjEyOjQxKzAwOjAw0FJFfAAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">2150\n(77.8%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">featured\n[logical]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. FALSE</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. TRUE</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">451</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">73.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">163</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">26.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFkAAAAoCAQAAAA/fJ5AAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnBBwQDCna+7ttAAAAgklEQVRYw+3WwQmAMAxG4Ubc0R10Ht2hU+q1SrwUTfPDe7deygdNIXYWtabRAMg5m9vDkXawV3shl7KMtrnV20lwMCBDhgwZcq4gQ3Z7rEW175bQrN03rfuav2uV6oOxd6/4W+ADfbLix/4AwcGADBkyZMi5ggzZTX3F10hwMCBHdAGkfQuprNQRTAAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMy0wNC0yOFQxNjoxMjo0MSswMDowMKEP/cAAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjMtMDQtMjhUMTY6MTI6NDErMDA6MDDQUkV8AAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">2150\n(77.8%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">first_epid.x\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 19909634 (111264.8)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">19770115 &le; 19901110 &le; 20141025</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 156624.2 (0)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">35 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAG0AAABPCAQAAABLlYPgAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnBBwQDCna+7ttAAAA90lEQVR42u2bQQ7CIBAAxfSP/kHfU//gK/WKphgI2dDZzNzalMIkW7J0obwvWbmuHoBqqtVs9UVpPLQ3P8hHq8ki6oFufU1uh3dfq03+kjggVSOiGhHViKhGRDUiqhHpzPzHOMciKETtHIugxAGpGhHViKhGRDUiqhFRjYhqRFQjohoR1YioRkQ1IqoRSaz2Vc7Yw/d9tno4ruDMVXx+KjXRFZbR98+MJ3FAqkZksioaP/EM9ltNL5Nqqwq7Pf0mDkjViKhGRDUiidWC9miNEpHVnEQtIqtJHJCqEVGNiGpEEquVOg144o/W36t/IwVv0yRxQKpG5ANxTRz+AHP3/wAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMy0wNC0yOFQxNjoxMjo0MSswMDowMKEP/cAAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjMtMDQtMjhUMTY6MTI6NDErMDA6MDDQUkV8AAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">2714\n(98.2%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">last_epid.x\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 19944038 (126122.2)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">19751011 &le; 19950225 &le; 20140201</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 190005 (0)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">17 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAG0AAABPCAQAAABLlYPgAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnBBwQDCna+7ttAAAA5UlEQVR42u3awQ3CMBAAQYzSIz1APaEHqoTvIWEpjm2SPe38yCPHSuZxMuV9yep69BcwzbRoiR/K5GFr9Yf9GDQ6Dlh2v2WX28+nrymzEh9I04hMIzKNyDQi04hMIzKN6Gtfm78qHpb231VxtsQH0jQi04hMIzKNyDQi04hMI0qc1nUrOm4rX0f9xyPM7bzwHbWV197T+jxKfCBNIzKNyDQi04hMIzKNyDSixGkbV9HWLXjY1jw/rXWbPsOdeOIDaRqRaUSmEZlGZBqRaUSmEZW4Mz5PsED2uYcL34KvqUp8IE0j+gCQWRlmMB+CWAAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMy0wNC0yOFQxNjoxMjo0MSswMDowMKEP/cAAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjMtMDQtMjhUMTY6MTI6NDErMDA6MDDQUkV8AAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">2747\n(99.4%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">update_anchor\n[logical]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. FALSE</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. TRUE</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">541</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">88.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">73</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">11.9%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGkAAAAoCAQAAABXjxx4AAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnBBwQDCna+7ttAAAAi0lEQVRo3u2XQQqAMAwEG/GP/kHfo3/oK/VahYL0EmfdueUSMjSBbpxFjSl7ACv9U2luiwN7WGt0lEpZsmcbot4qwcWzEgErEbASASsRsBIBQaXHt7WOdfkU0eaJGG6TTWuhvnh7NwJuoAd8FQFZFya4eFYiYCUCViJgJQJWIiCopB4BNRBcPCsRuADEmwupHej2EAAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMy0wNC0yOFQxNjoxMjo0MSswMDowMKEP/cAAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjMtMDQtMjhUMTY6MTI6NDErMDA6MDDQUkV8AAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">2150\n(77.8%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">n_episodes.x\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 18.7 (4)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1 &le; 20 &le; 24</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 2 (0.2)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">22 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAG0AAABPCAQAAABLlYPgAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnBBwQDCna+7ttAAAA8klEQVR42u3bQQ6CMBQAUTDc0TvoefAOnlK3tY00P0Do/MzsiCH2SWOJlfkzZe129QCkSStbyoP56tFUrc0XwbMzxPKEZRq6+8/RO3Ru4gkpjZg0YtKISSMmjZg0YtKISSMmjZg0YtKISSMmjZg0Yolpg29C1dU7blv7bTBaZL8t8YSURkwaMWnEpBGTRkwaMWnEpBGTRkwascS0oX6sWw99wGco2r7/9dclnpDSiEkjJo3Yqeta/NE6DK1dgiO7moPTetQzC9F6Eyx+D3jsXeMGrf9GvQkWvSp7r2Iz4uKjnsvXXvhH6x//aLlKvK5JI/YFJekiKMI7qMYAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjMtMDQtMjhUMTY6MTI6NDErMDA6MDChD/3AAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIzLTA0LTI4VDE2OjEyOjQxKzAwOjAw0FJFfAAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">2150\n(77.8%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">season_fraction\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 0.9 (0.2)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 1 &le; 1</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 0 (0.2)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">36 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAG0AAABPCAQAAABLlYPgAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnBBwQDCna+7ttAAAAv0lEQVR42u3bsQ2DMBgFYYy8Y3aAecwOmZK0v8FIRingrPs6N8BJQPfSPo1qfvoBTDMtyvGQnn6aW0rjN7GEhNx/qff5HM7f6jTwC2kakWlEphGZRmQakWlEphGZRmQakWlEphGZRmQakWlEphGZRmQakWlEphGZRmQakWlEphGZRmQakWlEphGZRmQakWlEphGZRmQaUbUVbQ1L19M2tjRX6mvHhrb8sW/vuX4txbtt+Gl9XPgmfM2lgb8104h+7FsOn420pZIAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjMtMDQtMjhUMTY6MTI6NDErMDA6MDChD/3AAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIzLTA0LTI4VDE2OjEyOjQxKzAwOjAw0FJFfAAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">2150\n(77.8%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">year\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 1999.5 (13.1)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1975 &le; 2000 &le; 2020</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 22 (0)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">46 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAG0AAABPCAQAAABLlYPgAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnBBwQDCna+7ttAAABB0lEQVR42u2bQQ6DIBQFa+MdvUN7HnsHT9kuiymmSlCYn5kdLoyTPB5ocHjfonJv/QCqqZYypoOh9dMcYM6WxCNRGPfeqj+mnyvLahQ4kIHVqgZy3lgkn00mceW5NmWuLYfv0qXaGcyFGyaAWmkWrJHaXFE4zQJ5fuEEDqRqRFQjsmrIfCW32QFWVvv/DkTiknVt/y6wdL/YTG1/Fmou5IFrRDUihXOt5nTvTK2vTwV5AgdSNSKqEdnRkISiL1Trv+bzBA6kakRUI6IaEdWIqEZENSKqEVGNiGpEVCOiGhHViKhGRDUiqhFRjYhqRFQjElhtSA+FvKAnRL6kf/gOeJtNAgdSNSIfGwEenTMzyfEAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjMtMDQtMjhUMTY6MTI6NDErMDA6MDChD/3AAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIzLTA0LTI4VDE2OjEyOjQxKzAwOjAw0FJFfAAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">2150\n(77.8%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">first_epid.y\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 19995688 (130607)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">19751011 &le; 20001007 &le; 20201003</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 219994 (0)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">46 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAG0AAABPCAQAAABLlYPgAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnBBwQDCna+7ttAAABE0lEQVR42u2aQQ6CMBBFreGO3EHPg3fwlLqtOCKZtND389+uLJo+8qdDScvrosr17AVYzWo1Uz0o6WmWoGTv+enS1MuY0rOsmFfjZ9MlL+Fut/3ymqn1Zv568u/lCdeasNqAgVwafUUMqJapqwjhQAqrHRrITHeCqLWqon0IB9JqRAboa61a9IFqe5fc68zQUe3I3TBCuNasRsRqRITVEpt/rxY7gNr5HWsfwoEUVvsIJKWKEmrRpyqjriKEA2k1IlYjYjUiViNiNSJWI2I1IlYjYjUiViNiNSLCagNcrsgT/O2u7nuh1bavZQgH0mpErEbEakSsRsRqRKxGxGpESn2ae+AvMt2qo2jB2/xEOJBWI/IGki0gMi2FOB4AAAAldEVYdGRhdGU6Y3JlYXRlADIwMjMtMDQtMjhUMTY6MTI6NDErMDA6MDChD/3AAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIzLTA0LTI4VDE2OjEyOjQxKzAwOjAw0FJFfAAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">2150\n(77.8%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">last_epid.y\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 20005232 (130621.3)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">19760731 &le; 20010519 &le; 20210410</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 220000 (0)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">46 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAG0AAABPCAQAAABLlYPgAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnBBwQDCna+7ttAAABC0lEQVR42u2ZQQ6CMBAAqeGP/kHeg3/wlXqtUKQhpXTqzA0iSae7Lls2vIdeuV29ANVUixnji3D1ajaZkyVhWi04/tk4QLiv7rx2niikltrV6eIkKBa15a7u7en5/EsZaYO5UBfRoNqRknG5Wm4JL0PlqJWJRx6WkSPkloNSZaOiWm7ynfVG7DghVSOiGhHViKhGZKcbqdurV1VLt0tndX2V1XJ126Pj/5pqRFQjohoR1YioRkQ1Ik0OoXJJHK6ikyRa7fcn9S81xhEzl0XU2hu2H6fjMqIaEdWIqEZENSKqEVGNiGpEVCOiGhHViKhGRDUiqhFRjUiI505P/BDqEY0OA95mk44TUjUiH+voIjTe7fD1AAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIzLTA0LTI4VDE2OjEyOjQxKzAwOjAwoQ/9wAAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMy0wNC0yOFQxNjoxMjo0MSswMDowMNBSRXwAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">2150\n(77.8%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">n_episodes.y\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 19.7 (2.1)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">12 &le; 20 &le; 24</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 1 (0.1)</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">12</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">12</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">2.0%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">13</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">24</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">3.9%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">17</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">30</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">4.9%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">18</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">31</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">5.0%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">19</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">37</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">6.0%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">20</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">297</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">48.4%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">21</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">111</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">18.1%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">22</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">63</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">10.3%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">24</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">9</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">1.5%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAD8AAACcCAQAAABi3rsUAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnBBwQDCna+7ttAAABDElEQVR42u3cUQrCMBCE4US8o4fwPPUOnrK+qCSlKaV0Zwvzz5tPn9ENs1iwziUzt1TdnL+3L15zKaU8ayzZTtvi9A/x6b2/e3h4ePhc/i3ma9s/wVX3zUbjqdP1/fR/Y9Gdv8r/+l43AdeafHh4eHj4yCwqh3VDmcG6oVo4VtcN3Qx4Xzx4eHh4L551IzGsG4mBh4eH9+Lp+8QM+17T+IO+V02B98WDh4eH9+JZNxKzsW6EpfmQh+tGVPrp8r548PDw8F4860ZiDq0b5/3ucWDdOHM+vC8ePDw8vDj0fWJ29X3cc40dfR85D94XDx4eHt6LZ91ITMdPs+h5xiVPDw8PDw8PH5fK/2zZ8h91/TOt3XMbCQAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMy0wNC0yOFQxNjoxMjo0MSswMDowMKEP/cAAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjMtMDQtMjhUMTY6MTI6NDErMDA6MDDQUkV8AAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">2150\n(77.8%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">type\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. cast</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. crew</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. guest</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. unknown</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">607</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">22.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">170</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">6.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1926</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">69.7%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">61</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">2.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFYAAABJCAQAAAAN3xkyAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnBBwQDCna+7ttAAAAv0lEQVRo3u3YwQmAMBBEUSPp0SKsR3uwSj0JmxyEoFl3wp+bCPLQEQfTOelk/hsANkKyPdgbC7ym/kBLyuWppeEyR39pFakagAULFixYsJrYahv4f+9bkuyqcRhRzbE+3RpsxZ71WKsvsHbPRmyvVA3AggULFixYsN3D+P4yI47vIDGP+8XPZI+U75BUDcCCBQsWLFiw3cP4/jIjje94f7zvVHc22vh+xMYOWLBgwYIFC9YbKzS+o0e5BrEjhb0AK5sXLX20x3QAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjMtMDQtMjhUMTY6MTI6NDErMDA6MDChD/3AAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIzLTA0LTI4VDE2OjEyOjQxKzAwOjAw0FJFfAAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">gender\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. andy</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. female</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. male</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. unknown</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">21</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">813</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">29.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1540</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">55.7%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">390</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">14.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAEcAAABJCAQAAADFs/PkAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnBBwQDCna+7ttAAAAsklEQVRo3u3ZwQ2AIBBE0cXQo0VYj/ZglXgFD0RZhIn5c+NiXlySnYSQTCnLbACc54n54UhmWxhNyG+v2N+BAwcOHDhKgVNLyPfp8GVuZtIbveg7u7M4+7tSLI+r41On12Jyw4IDBw4cOEoR49xWaI816An1q5au9asx2VA61q+2lLdVbFhw4MCBA0cpYhzq1z1/qV/fvwS+qF8j7pXYsODAgQMHjlLEOMr1a37EhgWnlguL2hYtalNncQAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMy0wNC0yOFQxNjoxMjo0MSswMDowMKEP/cAAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjMtMDQtMjhUMTY6MTI6NDErMDA6MDDQUkV8AAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n  </tbody>\n</table>\n<p>Generated by <a href='https://github.com/dcomtois/summarytools'>summarytools</a> 1.0.1 (<a href='https://www.r-project.org/'>R</a> version 4.2.2)<br/>2023-04-28</p>\n</div>\n```\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\n## Analysis of New, Combined SNL Dataset\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(SNL_csa, aes(x=`year`, y=`n_episodes.y`)) +\n    geom_point()+\n    labs(title = \"Number of SNL Episodes by Year, 1975-2020\")\n```\n\n::: {.cell-output-display}\n![](KrisSmole_Challenge_8_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\nWe can quickly and easily conclude that most frequent count of episodes per year is 20.\n\n\n## CONCLUSION\n\nCombining data sets with the Join functions is a powerful and essential function. Finding common column content in the data sets is one of the first steps - after determining how you want your end result to appear. Some data sets do not share a common column, and must be joined with 3rd data set with which each of the two original data sets share different, while each share a different common column of the 3rd data set.\n\n",
    "supporting": [
      "KrisSmole_Challenge_8_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}