{
  "hash": "9c5ae4b4d57bf588b7f93b271568374a",
  "result": {
    "markdown": "---\ntitle: \"DACCS 601 Final Project\"\nauthor: \"Priyanka Perumalla\"\ndescription: \"Data Science and STEM Salaries Analysis\"\ndate: \"05/21/2023\"\nformat:\n  html:\n    df-print: paged\n    toc: true\n    code-copy: true\n    code-tools: true\n    css: styles.css\ncategories:\n  - final_Project_assignment\n  - final_project\n  - Priyanka Perumalla\n  - Data Science and STEM salary dataset\n  - Tech Salary\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(readr)\nlibrary(ggplot2)\nlibrary(summarytools)\nlibrary(lubridate)\nlibrary(dplyr)\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n\n## Introduction\n\nThe dataset I am analyzing, \"The Data Science and STEM Salaries Dataset,\" is sourced from levels.fyi. Levels.fyi is a platform that collects and provides information on job levels, salaries, and compensation packages in various companies and industries. The dataset represents salary and compensation information for individuals working in data science and STEM (Science, Technology, Engineering, and Mathematics) fields.\n\nEach row in the dataset represents an individual case or observation, which corresponds to a specific person's employment details and compensation information. The dataset includes columns such as timestamp (when the data was recorded), company (the company the individual works for), level (job level or position), title (job title), total yearly compensation, location (geographic location), years of experience, years at the company, various tags (related to skills or domains), base salary, stock grant value, bonus, gender, other details, city ID, designated market area (DMA) ID, row number, and information about the individual's education and race.\n\n\n## Data Description\n\nThe dataset used in this analysis is sourced from levels.fyi, a platform that collects and provides information on job levels, salaries, and compensation packages. The data represents salary and compensation information specifically for data science and STEM (Science, Technology, Engineering, and Mathematics) roles. The data collection process on levels.fyi involves individuals voluntarily sharing their employment and compensation details. Users can submit their salary information, along with other relevant details, to contribute to the platform's database. This crowd sourced approach allows for a diverse range of data to be collected, representing different companies, job levels, and locations. The dataset offers insights into the salaries and compensation packages received by data science and STEM professionals, enabling analysis and exploration of various factors that influence compensation in these fields.\n\n\n\nReading the dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- read.csv(\"PriyankaPerumalla_FinalProjectData/Levels_Fyi_Salary_Data.csv\")\n```\n:::\n\n\nPresenting the descriptive information of the dataset. Like what all columns are present and what all information is present in every column. The nature of every column can be viewed through this sample data.\n\n\n    ::: {.cell}\n    \n    ```{.r .cell-code}\n    head(data)\n    ```\n    \n    ::: {.cell-output-display}\n    `````{=html}\n    <div data-pagedtable=\"false\">\n      <script data-pagedtable-source type=\"application/json\">\n    {\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"timestamp\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"company\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"level\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"title\"],\"name\":[4],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"totalyearlycompensation\"],\"name\":[5],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"location\"],\"name\":[6],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"yearsofexperience\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"yearsatcompany\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"tag\"],\"name\":[9],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"basesalary\"],\"name\":[10],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"stockgrantvalue\"],\"name\":[11],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"bonus\"],\"name\":[12],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"gender\"],\"name\":[13],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"otherdetails\"],\"name\":[14],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"cityid\"],\"name\":[15],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"dmaid\"],\"name\":[16],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"rowNumber\"],\"name\":[17],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Masters_Degree\"],\"name\":[18],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Bachelors_Degree\"],\"name\":[19],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Doctorate_Degree\"],\"name\":[20],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Highschool\"],\"name\":[21],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Some_College\"],\"name\":[22],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Race_Asian\"],\"name\":[23],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Race_White\"],\"name\":[24],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Race_Two_Or_More\"],\"name\":[25],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Race_Black\"],\"name\":[26],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Race_Hispanic\"],\"name\":[27],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Race\"],\"name\":[28],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Education\"],\"name\":[29],\"type\":[\"chr\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"6/7/2017 11:33:27\",\"2\":\"Oracle\",\"3\":\"L3\",\"4\":\"Product Manager\",\"5\":\"127000\",\"6\":\"Redwood City, CA\",\"7\":\"1.5\",\"8\":\"1.5\",\"9\":\"NA\",\"10\":\"107000\",\"11\":\"20000\",\"12\":\"10000\",\"13\":\"NA\",\"14\":\"NA\",\"15\":\"7392\",\"16\":\"807\",\"17\":\"1\",\"18\":\"0\",\"19\":\"0\",\"20\":\"0\",\"21\":\"0\",\"22\":\"0\",\"23\":\"0\",\"24\":\"0\",\"25\":\"0\",\"26\":\"0\",\"27\":\"0\",\"28\":\"NA\",\"29\":\"NA\",\"_rn_\":\"1\"},{\"1\":\"6/10/2017 17:11:29\",\"2\":\"eBay\",\"3\":\"SE 2\",\"4\":\"Software Engineer\",\"5\":\"100000\",\"6\":\"San Francisco, CA\",\"7\":\"5.0\",\"8\":\"3.0\",\"9\":\"NA\",\"10\":\"0\",\"11\":\"0\",\"12\":\"0\",\"13\":\"NA\",\"14\":\"NA\",\"15\":\"7419\",\"16\":\"807\",\"17\":\"2\",\"18\":\"0\",\"19\":\"0\",\"20\":\"0\",\"21\":\"0\",\"22\":\"0\",\"23\":\"0\",\"24\":\"0\",\"25\":\"0\",\"26\":\"0\",\"27\":\"0\",\"28\":\"NA\",\"29\":\"NA\",\"_rn_\":\"2\"},{\"1\":\"6/11/2017 14:53:57\",\"2\":\"Amazon\",\"3\":\"L7\",\"4\":\"Product Manager\",\"5\":\"310000\",\"6\":\"Seattle, WA\",\"7\":\"8.0\",\"8\":\"0.0\",\"9\":\"NA\",\"10\":\"155000\",\"11\":\"0\",\"12\":\"0\",\"13\":\"NA\",\"14\":\"NA\",\"15\":\"11527\",\"16\":\"819\",\"17\":\"3\",\"18\":\"0\",\"19\":\"0\",\"20\":\"0\",\"21\":\"0\",\"22\":\"0\",\"23\":\"0\",\"24\":\"0\",\"25\":\"0\",\"26\":\"0\",\"27\":\"0\",\"28\":\"NA\",\"29\":\"NA\",\"_rn_\":\"3\"},{\"1\":\"6/17/2017 0:23:14\",\"2\":\"Apple\",\"3\":\"M1\",\"4\":\"Software Engineering Manager\",\"5\":\"372000\",\"6\":\"Sunnyvale, CA\",\"7\":\"7.0\",\"8\":\"5.0\",\"9\":\"NA\",\"10\":\"157000\",\"11\":\"180000\",\"12\":\"35000\",\"13\":\"NA\",\"14\":\"NA\",\"15\":\"7472\",\"16\":\"807\",\"17\":\"7\",\"18\":\"0\",\"19\":\"0\",\"20\":\"0\",\"21\":\"0\",\"22\":\"0\",\"23\":\"0\",\"24\":\"0\",\"25\":\"0\",\"26\":\"0\",\"27\":\"0\",\"28\":\"NA\",\"29\":\"NA\",\"_rn_\":\"4\"},{\"1\":\"6/20/2017 10:58:51\",\"2\":\"Microsoft\",\"3\":\"60\",\"4\":\"Software Engineer\",\"5\":\"157000\",\"6\":\"Mountain View, CA\",\"7\":\"5.0\",\"8\":\"3.0\",\"9\":\"NA\",\"10\":\"0\",\"11\":\"0\",\"12\":\"0\",\"13\":\"NA\",\"14\":\"NA\",\"15\":\"7322\",\"16\":\"807\",\"17\":\"9\",\"18\":\"0\",\"19\":\"0\",\"20\":\"0\",\"21\":\"0\",\"22\":\"0\",\"23\":\"0\",\"24\":\"0\",\"25\":\"0\",\"26\":\"0\",\"27\":\"0\",\"28\":\"NA\",\"29\":\"NA\",\"_rn_\":\"5\"},{\"1\":\"6/21/2017 17:27:47\",\"2\":\"Microsoft\",\"3\":\"63\",\"4\":\"Software Engineer\",\"5\":\"208000\",\"6\":\"Seattle, WA\",\"7\":\"8.5\",\"8\":\"8.5\",\"9\":\"NA\",\"10\":\"0\",\"11\":\"0\",\"12\":\"0\",\"13\":\"NA\",\"14\":\"NA\",\"15\":\"11527\",\"16\":\"819\",\"17\":\"11\",\"18\":\"0\",\"19\":\"0\",\"20\":\"0\",\"21\":\"0\",\"22\":\"0\",\"23\":\"0\",\"24\":\"0\",\"25\":\"0\",\"26\":\"0\",\"27\":\"0\",\"28\":\"NA\",\"29\":\"NA\",\"_rn_\":\"6\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n      </script>\n    </div>\n    `````\n    :::\n    :::\n\n\n\nOn,analysing the dimensions of the data set. We see that the dataset has 62642 rows to begin with and 29 distinct columns.\n\n    ::: {.cell}\n    \n    ```{.r .cell-code}\n    dim(data)\n    ```\n    \n    ::: {.cell-output .cell-output-stdout}\n    ```\n    [1] 62642    29\n    ```\n    :::\n    :::\n\n\n\nChecking to see if any columns are repeating. We can notice that all the 29 columns ar eunique\n\n    ::: {.cell}\n    \n    ```{.r .cell-code}\n    length(unique(data))\n    ```\n    \n    ::: {.cell-output .cell-output-stdout}\n    ```\n    [1] 29\n    ```\n    :::\n    :::\n\n\n\n\nTaking a look on what all columns are present in the dataset.   \n\n    ::: {.cell}\n    \n    ```{.r .cell-code}\n    colnames(data)\n    ```\n    \n    ::: {.cell-output .cell-output-stdout}\n    ```\n     [1] \"timestamp\"               \"company\"                \n     [3] \"level\"                   \"title\"                  \n     [5] \"totalyearlycompensation\" \"location\"               \n     [7] \"yearsofexperience\"       \"yearsatcompany\"         \n     [9] \"tag\"                     \"basesalary\"             \n    [11] \"stockgrantvalue\"         \"bonus\"                  \n    [13] \"gender\"                  \"otherdetails\"           \n    [15] \"cityid\"                  \"dmaid\"                  \n    [17] \"rowNumber\"               \"Masters_Degree\"         \n    [19] \"Bachelors_Degree\"        \"Doctorate_Degree\"       \n    [21] \"Highschool\"              \"Some_College\"           \n    [23] \"Race_Asian\"              \"Race_White\"             \n    [25] \"Race_Two_Or_More\"        \"Race_Black\"             \n    [27] \"Race_Hispanic\"           \"Race\"                   \n    [29] \"Education\"              \n    ```\n    :::\n    :::\n\n\nUnderstanding the data:\n\nThe data set contains information from the \"Data Science and STEM Salaries\" data collected by levels.fyi. It consists of 62642 rows, representing as many as  62642 participants who volunteered to enter information in Levels.fyi. The data set contains 29 columns that capture various attributes of the participants and their responses.\n\n1. timestamp - The timestamp indicates when the survey response was recorded.\n2. company - This column represents the name of the company where the particpant is employed.\n3. level - It denotes the career level or seniority of the participant.\n4. title - This column specifies the job title or position held by the participant.\n5. totalyearlycompensation - It represents the total annual compensation of the participant, including salary, stock grants, and bonuses.\n6. location - This column indicates the geographical location of the participant.\n7. yearsofexperience - It indicates the number of years of professional experience the participant has.\n8. yearsatcompany - This column specifies the number of years the participant has been with their current company.\n9. tag - The tag column may provide additional information or categorization related to the participant or their response.\n10. basesalary - It represents the base salary component of the participant's total yearly compensation.\n11. stockgrantvalue - This column captures the value of stock grants included in the participant's total yearly compensation.\n12. bonus - It denotes the bonus amount included in the participant's total yearly compensation.\n13. gender - This column represents the gender of the participant.\n14. otherdetails - The otherdetails column may contain additional information or details provided by the participant.\n15. cityid - It indicates the city identifier associated with the participant's location.\n16. dmaid - The dmaid column represents the Designated Market Area (DMA) identifier, which relates to the participant's location.\n17. rowNumber - This column assigns a unique row number to each participant in the dataset.\n18. Masters_Degree - This column captures whether the participant holds a Master's degree.\n19. Bachelors_Degree - It indicates whether the participant holds a Bachelor's degree.\n20. Doctorate_Degree - This column specifies whether the participant holds a Doctorate degree.\n21. Highschool - It denotes whether the participant has completed high school education.\n22. Some_College - This column represents whether the participant has attended college without completing a degree.\n23. Race_Asian - It indicates whether the participant identifies as Asian.\n24. Race_White - This column represents whether the participant identifies as White.\n25. Race_Two_Or_More - It denotes whether the participant identifies as belonging to two or more races.\n26. Race_Black - This column indicates whether the participant identifies as Black.\n27. Race_Hispanic - It represents whether the participant identifies as Hispanic.\n28. Race - This column captures the participant's race or ethnic background.\n29. Education - It denotes the highest level of formal education completed by the participant.\n\n### Data tidying and mutation\n\nTo start off with any analysis the data needs to be tidy.\n\nLoading the required libraries\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(scales)\nannotate <- ggplot2::annotate\n```\n:::\n\n\n\nI am trying to check if this data has any null values. As a next step, I have omitted the null values as they would not contribute positively to my analysis. After omitting the rows which have atleast one null value, I am left with 21575 rows and 29 columns.\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(is.na(data))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 115356\n```\n:::\n\n```{.r .cell-code}\ndata<- na.omit(data)\ndim(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 21575    29\n```\n:::\n:::\n\n\nIt can be noticed that the summary column for race and education level already exists. But the flag columns for every category of education and race also exist. This is a redundancy and such columns can be deleted. \nI am getting rid of the columns Race_Asian,Race_White, Race_Black,Race_Hispanic,Some_College,Highschool,Doctorate_Degree,Bachelors_Degree,Masters_Degree,otherdetails. My dataset now has 19 columns.\n\n::: {.cell}\n\n```{.r .cell-code}\ndata<- subset(data, select = -c(Race_Asian,Race_White, Race_Black,Race_Hispanic,Some_College,Highschool,Doctorate_Degree,Bachelors_Degree,Masters_Degree,otherdetails) )\ndim(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 21575    19\n```\n:::\n:::\n\n\n\nThe location column in the dataset has the format 'city,state,country'. But I would like to mutate this column to extract city,state and country columns separtely. After this mutation, I have 21 columns.\n\n::: {.cell}\n\n```{.r .cell-code}\ndata<-separate(data = data, col = location, into = c(\"City\", \"State\",\"Country\"), sep = \",\")\ndim(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 21575    21\n```\n:::\n:::\n\n\nThe datetimestamp column in the dataset has the format 'MM/DD/YYYY hh:mm:ss'. But I would like to mutate this column to extract Date and time separtely. After this mutation, I have 22 columns.\n\n::: {.cell}\n\n```{.r .cell-code}\ndata<-separate(data = data, col = timestamp, into = c(\"Date \", \"Time\"), sep = \" \")\ndim(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 21575    22\n```\n:::\n\n```{.r .cell-code}\nhead(data)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Date \"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Time\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"company\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"level\"],\"name\":[4],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"title\"],\"name\":[5],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"totalyearlycompensation\"],\"name\":[6],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"City\"],\"name\":[7],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"State\"],\"name\":[8],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Country\"],\"name\":[9],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"yearsofexperience\"],\"name\":[10],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"yearsatcompany\"],\"name\":[11],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"tag\"],\"name\":[12],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"basesalary\"],\"name\":[13],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"stockgrantvalue\"],\"name\":[14],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"bonus\"],\"name\":[15],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"gender\"],\"name\":[16],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"cityid\"],\"name\":[17],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"dmaid\"],\"name\":[18],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"rowNumber\"],\"name\":[19],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Race_Two_Or_More\"],\"name\":[20],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Race\"],\"name\":[21],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Education\"],\"name\":[22],\"type\":[\"chr\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"1/27/2020\",\"2\":\"22:59:06\",\"3\":\"Google\",\"4\":\"L6\",\"5\":\"Software Engineer\",\"6\":\"400000\",\"7\":\"Sunnyvale\",\"8\":\"CA\",\"9\":\"NA\",\"10\":\"5\",\"11\":\"5\",\"12\":\"Distributed Systems (Back-End)\",\"13\":\"210000\",\"14\":\"145000\",\"15\":\"45000\",\"16\":\"Male\",\"17\":\"7472\",\"18\":\"807\",\"19\":\"21208\",\"20\":\"0\",\"21\":\"Asian\",\"22\":\"PhD\",\"_rn_\":\"15711\"},{\"1\":\"7/3/2020\",\"2\":\"19:56:38\",\"3\":\"Microsoft\",\"4\":\"61\",\"5\":\"Software Engineer\",\"6\":\"136000\",\"7\":\"Redmond\",\"8\":\"WA\",\"9\":\"NA\",\"10\":\"3\",\"11\":\"2\",\"12\":\"DevOps\",\"13\":\"124000\",\"14\":\"1000\",\"15\":\"11000\",\"16\":\"Male\",\"17\":\"11521\",\"18\":\"819\",\"19\":\"32237\",\"20\":\"1\",\"21\":\"Two Or More\",\"22\":\"Bachelor's Degree\",\"_rn_\":\"23533\"},{\"1\":\"7/3/2020\",\"2\":\"20:03:57\",\"3\":\"Google\",\"4\":\"L5\",\"5\":\"Software Engineer\",\"6\":\"337000\",\"7\":\"San Bruno\",\"8\":\"CA\",\"9\":\"NA\",\"10\":\"6\",\"11\":\"6\",\"12\":\"Full Stack\",\"13\":\"177000\",\"14\":\"125000\",\"15\":\"36000\",\"16\":\"Male\",\"17\":\"7413\",\"18\":\"807\",\"19\":\"32239\",\"20\":\"0\",\"21\":\"Asian\",\"22\":\"Bachelor's Degree\",\"_rn_\":\"23534\"},{\"1\":\"7/3/2020\",\"2\":\"20:05:37\",\"3\":\"Microsoft\",\"4\":\"62\",\"5\":\"Software Engineer\",\"6\":\"222000\",\"7\":\"Seattle\",\"8\":\"WA\",\"9\":\"NA\",\"10\":\"4\",\"11\":\"4\",\"12\":\"API Development (Back-End)\",\"13\":\"164000\",\"14\":\"38000\",\"15\":\"20000\",\"16\":\"Male\",\"17\":\"11527\",\"18\":\"819\",\"19\":\"32240\",\"20\":\"0\",\"21\":\"Asian\",\"22\":\"Master's Degree\",\"_rn_\":\"23535\"},{\"1\":\"7/3/2020\",\"2\":\"20:19:06\",\"3\":\"Blend\",\"4\":\"IC3\",\"5\":\"Software Engineer\",\"6\":\"187000\",\"7\":\"San Francisco\",\"8\":\"CA\",\"9\":\"NA\",\"10\":\"5\",\"11\":\"0\",\"12\":\"Full Stack\",\"13\":\"165000\",\"14\":\"22000\",\"15\":\"0\",\"16\":\"Male\",\"17\":\"7419\",\"18\":\"807\",\"19\":\"32241\",\"20\":\"0\",\"21\":\"White\",\"22\":\"Bachelor's Degree\",\"_rn_\":\"23536\"},{\"1\":\"7/3/2020\",\"2\":\"20:24:20\",\"3\":\"Amazon\",\"4\":\"L6\",\"5\":\"Software Engineer\",\"6\":\"310000\",\"7\":\"Seattle\",\"8\":\"WA\",\"9\":\"NA\",\"10\":\"15\",\"11\":\"3\",\"12\":\"ML / AI\",\"13\":\"160000\",\"14\":\"150000\",\"15\":\"0\",\"16\":\"Male\",\"17\":\"11527\",\"18\":\"819\",\"19\":\"32243\",\"20\":\"0\",\"21\":\"Asian\",\"22\":\"Bachelor's Degree\",\"_rn_\":\"23538\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n\nThe date column in the dataset has the format 'MM/DD/YYYY'. But I would like to mutate this column further to extract month,day and year separtely. After this mutation, I have 24 columns.\n\n::: {.cell}\n\n```{.r .cell-code}\ndata<-separate(data = data, col = 1, into = c(\"Month\", \"Day\",\"Year\"), sep = \"/\")\ndim(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 21575    24\n```\n:::\n\n```{.r .cell-code}\nhead(data)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Month\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Day\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Year\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Time\"],\"name\":[4],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"company\"],\"name\":[5],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"level\"],\"name\":[6],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"title\"],\"name\":[7],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"totalyearlycompensation\"],\"name\":[8],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"City\"],\"name\":[9],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"State\"],\"name\":[10],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Country\"],\"name\":[11],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"yearsofexperience\"],\"name\":[12],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"yearsatcompany\"],\"name\":[13],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"tag\"],\"name\":[14],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"basesalary\"],\"name\":[15],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"stockgrantvalue\"],\"name\":[16],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"bonus\"],\"name\":[17],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"gender\"],\"name\":[18],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"cityid\"],\"name\":[19],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"dmaid\"],\"name\":[20],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"rowNumber\"],\"name\":[21],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Race_Two_Or_More\"],\"name\":[22],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Race\"],\"name\":[23],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Education\"],\"name\":[24],\"type\":[\"chr\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"1\",\"2\":\"27\",\"3\":\"2020\",\"4\":\"22:59:06\",\"5\":\"Google\",\"6\":\"L6\",\"7\":\"Software Engineer\",\"8\":\"400000\",\"9\":\"Sunnyvale\",\"10\":\"CA\",\"11\":\"NA\",\"12\":\"5\",\"13\":\"5\",\"14\":\"Distributed Systems (Back-End)\",\"15\":\"210000\",\"16\":\"145000\",\"17\":\"45000\",\"18\":\"Male\",\"19\":\"7472\",\"20\":\"807\",\"21\":\"21208\",\"22\":\"0\",\"23\":\"Asian\",\"24\":\"PhD\",\"_rn_\":\"15711\"},{\"1\":\"7\",\"2\":\"3\",\"3\":\"2020\",\"4\":\"19:56:38\",\"5\":\"Microsoft\",\"6\":\"61\",\"7\":\"Software Engineer\",\"8\":\"136000\",\"9\":\"Redmond\",\"10\":\"WA\",\"11\":\"NA\",\"12\":\"3\",\"13\":\"2\",\"14\":\"DevOps\",\"15\":\"124000\",\"16\":\"1000\",\"17\":\"11000\",\"18\":\"Male\",\"19\":\"11521\",\"20\":\"819\",\"21\":\"32237\",\"22\":\"1\",\"23\":\"Two Or More\",\"24\":\"Bachelor's Degree\",\"_rn_\":\"23533\"},{\"1\":\"7\",\"2\":\"3\",\"3\":\"2020\",\"4\":\"20:03:57\",\"5\":\"Google\",\"6\":\"L5\",\"7\":\"Software Engineer\",\"8\":\"337000\",\"9\":\"San Bruno\",\"10\":\"CA\",\"11\":\"NA\",\"12\":\"6\",\"13\":\"6\",\"14\":\"Full Stack\",\"15\":\"177000\",\"16\":\"125000\",\"17\":\"36000\",\"18\":\"Male\",\"19\":\"7413\",\"20\":\"807\",\"21\":\"32239\",\"22\":\"0\",\"23\":\"Asian\",\"24\":\"Bachelor's Degree\",\"_rn_\":\"23534\"},{\"1\":\"7\",\"2\":\"3\",\"3\":\"2020\",\"4\":\"20:05:37\",\"5\":\"Microsoft\",\"6\":\"62\",\"7\":\"Software Engineer\",\"8\":\"222000\",\"9\":\"Seattle\",\"10\":\"WA\",\"11\":\"NA\",\"12\":\"4\",\"13\":\"4\",\"14\":\"API Development (Back-End)\",\"15\":\"164000\",\"16\":\"38000\",\"17\":\"20000\",\"18\":\"Male\",\"19\":\"11527\",\"20\":\"819\",\"21\":\"32240\",\"22\":\"0\",\"23\":\"Asian\",\"24\":\"Master's Degree\",\"_rn_\":\"23535\"},{\"1\":\"7\",\"2\":\"3\",\"3\":\"2020\",\"4\":\"20:19:06\",\"5\":\"Blend\",\"6\":\"IC3\",\"7\":\"Software Engineer\",\"8\":\"187000\",\"9\":\"San Francisco\",\"10\":\"CA\",\"11\":\"NA\",\"12\":\"5\",\"13\":\"0\",\"14\":\"Full Stack\",\"15\":\"165000\",\"16\":\"22000\",\"17\":\"0\",\"18\":\"Male\",\"19\":\"7419\",\"20\":\"807\",\"21\":\"32241\",\"22\":\"0\",\"23\":\"White\",\"24\":\"Bachelor's Degree\",\"_rn_\":\"23536\"},{\"1\":\"7\",\"2\":\"3\",\"3\":\"2020\",\"4\":\"20:24:20\",\"5\":\"Amazon\",\"6\":\"L6\",\"7\":\"Software Engineer\",\"8\":\"310000\",\"9\":\"Seattle\",\"10\":\"WA\",\"11\":\"NA\",\"12\":\"15\",\"13\":\"3\",\"14\":\"ML / AI\",\"15\":\"160000\",\"16\":\"150000\",\"17\":\"0\",\"18\":\"Male\",\"19\":\"11527\",\"20\":\"819\",\"21\":\"32243\",\"22\":\"0\",\"23\":\"Asian\",\"24\":\"Bachelor's Degree\",\"_rn_\":\"23538\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n\nI want to group salaries together into buckets for further analysis. I have kept the bucket size as $25,000 USD. I am trying get the count of people who fall into each of such compensation buckets.\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- data %>%\n  mutate(Salary_bucket = case_when(totalyearlycompensation >=0 & totalyearlycompensation <25000 ~ \"0-25k\",\n  totalyearlycompensation >=25000 & totalyearlycompensation <50000 ~ \"25k-50k\",\n  totalyearlycompensation >=50000 & totalyearlycompensation <75000 ~ \"50k-750k\",\n  totalyearlycompensation >=75000 & totalyearlycompensation <100000 ~ \"75k-100k\",\n  totalyearlycompensation >=100000 & totalyearlycompensation <125000 ~ \"100k-125k\",                      \n  totalyearlycompensation >=125000 & totalyearlycompensation <150000 ~ \"125k-150k\",\n  totalyearlycompensation >=150000 & totalyearlycompensation <175000 ~ \"150k-175k\",\n  totalyearlycompensation >=175000 & totalyearlycompensation <200000 ~ \"175k-200k\",\n  totalyearlycompensation >=200000 & totalyearlycompensation <225000 ~ \"200k-225k\",\n  totalyearlycompensation >=225000 & totalyearlycompensation <250000 ~ \"225k-250k\",\n  totalyearlycompensation >=250000 & totalyearlycompensation <275000 ~ \"250k-275k\",\n  totalyearlycompensation >=275000 & totalyearlycompensation <300000 ~ \"275k-300k\",\n  totalyearlycompensation >=300000 & totalyearlycompensation <325000 ~ \"300k-325k\",\n  totalyearlycompensation >=325000 & totalyearlycompensation <350000 ~ \"325k-350k\",\n  totalyearlycompensation >=350000 & totalyearlycompensation <375000 ~ \"350k-375k\",\n  totalyearlycompensation >=375000 & totalyearlycompensation <400000 ~ \"375k-400k\",\n  totalyearlycompensation >=400000 & totalyearlycompensation <425000 ~ \"400k-425k\",\n  totalyearlycompensation >=425000 & totalyearlycompensation <450000 ~ \"425k-450k\",\n  totalyearlycompensation >=450000 & totalyearlycompensation <475000 ~ \"450k-475k\",\n  totalyearlycompensation >=475000 & totalyearlycompensation <500000 ~ \"475k-500k\",\n  totalyearlycompensation >=500000 ~ \"500k+\"))\n```\n:::\n\n\n\nI want to group years of experience into buckets for further analysis. I have kept the bucket size as 5 years . I am trying get the count of people who fall into each of such experience buckets.\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- data %>%\n  mutate(Work_experience_bucket = case_when(yearsofexperience >=0 & yearsofexperience <5 ~ \"0-5\",\n  yearsofexperience >=5 & yearsofexperience <10 ~ \"5-10\",\n  yearsofexperience >=10 & yearsofexperience <15 ~ \"10-15\",\n  yearsofexperience >=15 & yearsofexperience <20 ~ \"15-20\",\n  yearsofexperience >=20 & yearsofexperience <25 ~ \"20-25\",                      \n  yearsofexperience >=25 & yearsofexperience <30 ~ \"25-30\",\n  yearsofexperience >=30 & yearsofexperience <35 ~ \"30-35\",\n  yearsofexperience >=35 & yearsofexperience <40 ~ \"35-40\",\n  yearsofexperience >=40  ~ \"40+\"))\n```\n:::\n\n\n\nI want to group months of the year into quarters to deep dive and understand how hiring and compensation offers change with respect to quarters in a company. I am trying get 4 quarters of a fiscal year.\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- data %>%\n  mutate(quarter_year = case_when(Month >=1 & Month <=3 ~ \"Quarter 1\",\n  Month >=4 & Month <=6 ~ \"Quarter 2\",\n  Month >=7 & Month <=9 ~ \"Quarter 3\",\n  Month >=10 & Month <=12 ~ \"Quarter 4\"\n  ))\n```\n:::\n\n#conduct summary statistics of the dataset(s)\n\nNow that the data is clean, tidy and all set for analysis, I would like to now view the summary statistics of the cleaned dataset.\n\n::: {.cell}\n\n```{.r .cell-code}\nsummarise_all(data, mean)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Month\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Day\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Year\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Time\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"company\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"level\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"title\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"totalyearlycompensation\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"City\"],\"name\":[9],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"State\"],\"name\":[10],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Country\"],\"name\":[11],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"yearsofexperience\"],\"name\":[12],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"yearsatcompany\"],\"name\":[13],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"tag\"],\"name\":[14],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"basesalary\"],\"name\":[15],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"stockgrantvalue\"],\"name\":[16],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"bonus\"],\"name\":[17],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"gender\"],\"name\":[18],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"cityid\"],\"name\":[19],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"dmaid\"],\"name\":[20],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"rowNumber\"],\"name\":[21],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Race_Two_Or_More\"],\"name\":[22],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Race\"],\"name\":[23],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Education\"],\"name\":[24],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Salary_bucket\"],\"name\":[25],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Work_experience_bucket\"],\"name\":[26],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"quarter_year\"],\"name\":[27],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"NA\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"NA\",\"6\":\"NA\",\"7\":\"NA\",\"8\":\"197855\",\"9\":\"NA\",\"10\":\"NA\",\"11\":\"NA\",\"12\":\"7.122549\",\"13\":\"2.704148\",\"14\":\"NA\",\"15\":\"133864.8\",\"16\":\"44893.77\",\"17\":\"18417.89\",\"18\":\"NA\",\"19\":\"10175.51\",\"20\":\"561.1813\",\"21\":\"59203.42\",\"22\":\"0.03541136\",\"23\":\"NA\",\"24\":\"NA\",\"25\":\"NA\",\"26\":\"NA\",\"27\":\"NA\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nsummarise_all(data, min)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Month\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Day\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Year\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Time\"],\"name\":[4],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"company\"],\"name\":[5],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"level\"],\"name\":[6],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"title\"],\"name\":[7],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"totalyearlycompensation\"],\"name\":[8],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"City\"],\"name\":[9],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"State\"],\"name\":[10],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Country\"],\"name\":[11],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"yearsofexperience\"],\"name\":[12],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"yearsatcompany\"],\"name\":[13],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"tag\"],\"name\":[14],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"basesalary\"],\"name\":[15],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"stockgrantvalue\"],\"name\":[16],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"bonus\"],\"name\":[17],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"gender\"],\"name\":[18],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"cityid\"],\"name\":[19],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"dmaid\"],\"name\":[20],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"rowNumber\"],\"name\":[21],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Race_Two_Or_More\"],\"name\":[22],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Race\"],\"name\":[23],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Education\"],\"name\":[24],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Salary_bucket\"],\"name\":[25],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Work_experience_bucket\"],\"name\":[26],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"quarter_year\"],\"name\":[27],\"type\":[\"chr\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"1\",\"2\":\"1\",\"3\":\"2020\",\"4\":\"0:00:04\",\"5\":\" Google\",\"6\":\"-\",\"7\":\"Business Analyst\",\"8\":\"10000\",\"9\":\"Aachen\",\"10\":\"AA\",\"11\":\"NA\",\"12\":\"0\",\"13\":\"0\",\"14\":\"#finance\",\"15\":\"4000\",\"16\":\"0\",\"17\":\"0\",\"18\":\"Female\",\"19\":\"10\",\"20\":\"0\",\"21\":\"21208\",\"22\":\"0\",\"23\":\"Asian\",\"24\":\"Bachelor's Degree\",\"25\":\"0-25k\",\"26\":\"0-5\",\"27\":\"Quarter 1\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nsummarise_all(data, max)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Month\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Day\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Year\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Time\"],\"name\":[4],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"company\"],\"name\":[5],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"level\"],\"name\":[6],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"title\"],\"name\":[7],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"totalyearlycompensation\"],\"name\":[8],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"City\"],\"name\":[9],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"State\"],\"name\":[10],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Country\"],\"name\":[11],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"yearsofexperience\"],\"name\":[12],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"yearsatcompany\"],\"name\":[13],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"tag\"],\"name\":[14],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"basesalary\"],\"name\":[15],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"stockgrantvalue\"],\"name\":[16],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"bonus\"],\"name\":[17],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"gender\"],\"name\":[18],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"cityid\"],\"name\":[19],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"dmaid\"],\"name\":[20],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"rowNumber\"],\"name\":[21],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Race_Two_Or_More\"],\"name\":[22],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Race\"],\"name\":[23],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Education\"],\"name\":[24],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Salary_bucket\"],\"name\":[25],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Work_experience_bucket\"],\"name\":[26],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"quarter_year\"],\"name\":[27],\"type\":[\"chr\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"9\",\"2\":\"9\",\"3\":\"2021\",\"4\":\"9:59:58\",\"5\":\"Zynga\",\"6\":\"專員\",\"7\":\"Technical Program Manager\",\"8\":\"4980000\",\"9\":\"Zurich\",\"10\":\"ZJ\",\"11\":\"NA\",\"12\":\"45\",\"13\":\"40\",\"14\":\"Z Systems\",\"15\":\"9e+05\",\"16\":\"954000\",\"17\":\"9e+05\",\"18\":\"Other\",\"19\":\"47926\",\"20\":\"881\",\"21\":\"83875\",\"22\":\"1\",\"23\":\"White\",\"24\":\"Some College\",\"25\":\"75k-100k\",\"26\":\"5-10\",\"27\":\"Quarter 3\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nsummarise_all(data, median)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Month\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Day\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Year\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Time\"],\"name\":[4],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"company\"],\"name\":[5],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"level\"],\"name\":[6],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"title\"],\"name\":[7],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"totalyearlycompensation\"],\"name\":[8],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"City\"],\"name\":[9],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"State\"],\"name\":[10],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Country\"],\"name\":[11],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"yearsofexperience\"],\"name\":[12],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"yearsatcompany\"],\"name\":[13],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"tag\"],\"name\":[14],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"basesalary\"],\"name\":[15],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"stockgrantvalue\"],\"name\":[16],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"bonus\"],\"name\":[17],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"gender\"],\"name\":[18],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"cityid\"],\"name\":[19],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"dmaid\"],\"name\":[20],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"rowNumber\"],\"name\":[21],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Race_Two_Or_More\"],\"name\":[22],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Race\"],\"name\":[23],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Education\"],\"name\":[24],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Salary_bucket\"],\"name\":[25],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Work_experience_bucket\"],\"name\":[26],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"quarter_year\"],\"name\":[27],\"type\":[\"chr\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"5\",\"2\":\"23\",\"3\":\"2021\",\"4\":\"17:47:38\",\"5\":\"Google\",\"6\":\"L4\",\"7\":\"Software Engineer\",\"8\":\"174000\",\"9\":\"New York\",\"10\":\"MA\",\"11\":\"NA\",\"12\":\"6\",\"13\":\"2\",\"14\":\"Full Stack\",\"15\":\"135000\",\"16\":\"20000\",\"17\":\"13000\",\"18\":\"Male\",\"19\":\"8198\",\"20\":\"751\",\"21\":\"59844\",\"22\":\"0\",\"23\":\"Asian\",\"24\":\"Bachelor's Degree\",\"25\":\"200k-225k\",\"26\":\"10-15\",\"27\":\"Quarter 2\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nsummary(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    Month               Day                Year               Time          \n Length:21575       Length:21575       Length:21575       Length:21575      \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n   company             level              title          \n Length:21575       Length:21575       Length:21575      \n Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character  \n                                                         \n                                                         \n                                                         \n totalyearlycompensation     City              State          \n Min.   :  10000         Length:21575       Length:21575      \n 1st Qu.: 119000         Class :character   Class :character  \n Median : 174000         Mode  :character   Mode  :character  \n Mean   : 197855                                              \n 3rd Qu.: 245000                                              \n Max.   :4980000                                              \n   Country          yearsofexperience yearsatcompany       tag           \n Length:21575       Min.   : 0.000    Min.   : 0.000   Length:21575      \n Class :character   1st Qu.: 3.000    1st Qu.: 0.000   Class :character  \n Mode  :character   Median : 6.000    Median : 2.000   Mode  :character  \n                    Mean   : 7.123    Mean   : 2.704                     \n                    3rd Qu.:10.000    3rd Qu.: 4.000                     \n                    Max.   :45.000    Max.   :40.000                     \n   basesalary     stockgrantvalue      bonus           gender         \n Min.   :  4000   Min.   :     0   Min.   :     0   Length:21575      \n 1st Qu.:100000   1st Qu.:     0   1st Qu.:  3000   Class :character  \n Median :135000   Median : 20000   Median : 13000   Mode  :character  \n Mean   :133865   Mean   : 44894   Mean   : 18418                     \n 3rd Qu.:165000   3rd Qu.: 55000   3rd Qu.: 25000                     \n Max.   :900000   Max.   :954000   Max.   :900000                     \n     cityid          dmaid         rowNumber     Race_Two_Or_More \n Min.   :   10   Min.   :  0.0   Min.   :21208   Min.   :0.00000  \n 1st Qu.: 7322   1st Qu.:501.0   1st Qu.:47069   1st Qu.:0.00000  \n Median : 8198   Median :751.0   Median :59844   Median :0.00000  \n Mean   :10176   Mean   :561.2   Mean   :59203   Mean   :0.03541  \n 3rd Qu.:11521   3rd Qu.:807.0   3rd Qu.:71590   3rd Qu.:0.00000  \n Max.   :47926   Max.   :881.0   Max.   :83875   Max.   :1.00000  \n     Race            Education         Salary_bucket     \n Length:21575       Length:21575       Length:21575      \n Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character  \n                                                         \n                                                         \n                                                         \n Work_experience_bucket quarter_year      \n Length:21575           Length:21575      \n Class :character       Class :character  \n Mode  :character       Mode  :character  \n                                          \n                                          \n                                          \n```\n:::\n:::\n\n\n\n\nI notice that the minimum total compensation is 10,000 USD and the maximum total compensation is 4,980,000 USD. The average compensation is 197,855 USD which is approximately 198,000 USD. The mean average years of experience is ar 7.12 years. \n\n\n### Potential research questions\nThe dataset provides several variables that can be used to answer various questions related to data science and STEM salaries. Here are some potential questions I tried to explore:\n\na) How is the education level effecting the people who are seeking jobs in Data Science and STEM Domains.\nb)  How does the gender pay gap manifest in the data? Are there noticeable differences in compensation between genders?\nc) Are there any trends or patterns in compensation based on educational attainment (Masters, Bachelors, Doctorate, etc.)?\nd) How does compensation vary across different fiscal years?\ne) Are there any preferred companies? What comes under the most desired 10 companies list?\nf) Are there any roles that are more preferred than others? What comes under the most desired 10 roles list?\ng) If somebody wants to switch a job to get a higher compensation, are there any preferred months of the year?\nh) If somebody wants to increase the likelihood of getting back interview calls, is there a preferred quarter for hiring?\ni) Correlation between State, Work Experience in years and yearly compensation?\nj) Correlation between State, Company and yearly compensation?\nk) States with varied jobs in terms of pay compared to others?\nl) Does racial discrimination exist in compensation packages?\n\n\n### Education level vs number of people\nWe will now examine the education metric. We use scatter charts and tile charts, respectively, to display the proportion of the indicated levels of both variables and the number of respondents to two indicators with the levels of the variables under consideration.\n\n\nFrom the below plot, we see that about  9000 of respondants have a Master's degree, 11,000 have a Bachelor's degree and only a few hundrends have just a high school diploma. It looks like atleast a Bachelor's degree is mandatory to get a job in the STEM and Data Science Domain. While a master's degree does not look mandatory, only analysing the compensation difference would tell us if a master's degree is worth it or not in terms of increased salary compensation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\neducation <- as.data.frame(table(data$Education))\nggplot(education, aes(reorder(Var1, +Freq), Freq))+\n  geom_bar(col = \"gray10\", stat = \"identity\", width = 0.6, fill = \"orange\")+\n  scale_x_discrete(limits = c(\"Master's Degree\", \"Bachelor's Degree\", \"Highschool\"))+\n  labs(title = \"Education level\", y = \"count\", x = \"Education level\")\n```\n\n::: {.cell-output-display}\n![](PriyankaPerumalla_final_project_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n\n### Education level vs Salary vs Gender\nWe observe a gender- and education-based breakdown of the population who entered their salaries. The \"I prefer to define myself\" options in the variable are limited to the two most popular levels, female and male, due to the small number of refusals and indications. There are four times fewer women than men among the respondents. The proportions of people with and without a college degree are very similar for both sexes, but it is clear that those without a college degree are more likely to be men than the rest of the sample.\nIt is interesting to see that the gender with most \"Masters\" degree and \"College/High school\" is men.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntile2 <- data %>%\n  filter(gender %in% c(\"Female\", \"Male\")) %>%\n  group_by(gender, Education) %>%\n  summarise(count = n(), .groups = 'drop') \nggplot(tile2, aes(Education, gender))+\n  geom_tile(aes(fill = count), colour = \"gray10\", alpha = 0.5)+\n  scale_x_discrete(limits = c(\"Master's Degree\", \"Bachelor's Degree\", \"Highschool\"))+\n  geom_text(aes(label = paste0(round(count/sum(tile2$count) * 100,1), \"%\")), size = 7)+\n  labs(title = \"Education level\", subtitle = \"count by education level and gender\", y = \"Gender\", x = \"Education level\")\n```\n\n::: {.cell-output-display}\n![](PriyankaPerumalla_final_project_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\n\n\n### Salary vs Education level\n\nThe usual expectation is that salary should increase with education level. But in the tech industry, I feel that its only your talent and abilities that matter but not the education level. I have run the analysis to see it that is true. I can clearly see that the pattern is very similar for Bachelor's Degree and Master's Degree when I look at higher bands of salaries (200k USD +). So for jobs that pay above 200k USD, looks like degree does not matter. But when I look at the 100k USD to 200k USD salary band, the Bachelor's degree population seems to win. But that might be because of the skewed distribution towards them. I can also notice some highschool diploma holders that fell in the band of 300k+. I can't stop myself from mapping them to be a CEO of a company but a college dropout.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata %>%\n  filter(Salary_bucket!=\"\") %>%\nggplot(., aes(Education, Salary_bucket, col = Education))+\n  geom_count()+\n  scale_x_discrete(limits = c(\"Master's Degree\", \"Bachelor's Degree\", \"Highschool\"))+\n  scale_y_discrete(limits = c(\"0-25k\",\"25k-50k\",\"50k-75k\",\"75k-100k\",\"100k-125k\",\"125k-150k\",\"150k-175k\",\"175k-200k\",\"200-225k\",\"225k-250k\",\"250k-275k\",\"275k-300k\",\"300-325k\",\"325k-350k\",\"350k-375k\",\"375k-400k\",\"400-425k\",\"425k-450k\",\"450k-475k\",\"475k-500k\",\"500k+\"))+\n  labs(title = \"Education level\", subtitle = \"Count by education level and salary range\", y = \"Salary\", x = \"Education level\")\n```\n\n::: {.cell-output-display}\n![](PriyankaPerumalla_final_project_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n## Average Total Compensation for different years :\n\nIf we want to see how average total compensation for different years looks like, we could use a scatter plot to deduce a relationship between average total compensation and year. From below plot, we could see that, the average total compensation decreased from 2020 to 2021. There could be multiple unwarranted reasons for this trend which could be deduced from the given plot.But I strongly feel that the economic downtime has something to do with the reduced compensations at Tech firms.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata1 = data%>% na.omit() %>%\n    group_by(Year) %>% summarise(Mean_salary = mean(totalyearlycompensation))\np <- ggplot(\n  data1,\n  aes(y =  as.numeric(Mean_salary), x = as.factor(Year), color = factor(Year), group = 1)) +\n  geom_point(size=1.5) +\n  scale_color_viridis_d() +\n  scale_linetype_manual() +\n  labs(x = \"Year\", y = \"Average Total Compensation\") +\n  theme(legend.position = \"top\")\np +  geom_line(color='blue')\n```\n\n::: {.cell-output-display}\n![](PriyankaPerumalla_final_project_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\n\n\n## Top 10 Companies \nAny fresh graduate like me would be interested to know what are the trending companies that pay above average salaries for that year in order to apply and join. For the year 2020 and 2021, we have Uber,Netflix,Figma,HRT,ServiceNow,UiPath etc as some of the top companies. As a person from STEM background, even I can attest that these companies truly are dream companies to land a job at for any graduate student.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolnames(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"Month\"                   \"Day\"                    \n [3] \"Year\"                    \"Time\"                   \n [5] \"company\"                 \"level\"                  \n [7] \"title\"                   \"totalyearlycompensation\"\n [9] \"City\"                    \"State\"                  \n[11] \"Country\"                 \"yearsofexperience\"      \n[13] \"yearsatcompany\"          \"tag\"                    \n[15] \"basesalary\"              \"stockgrantvalue\"        \n[17] \"bonus\"                   \"gender\"                 \n[19] \"cityid\"                  \"dmaid\"                  \n[21] \"rowNumber\"               \"Race_Two_Or_More\"       \n[23] \"Race\"                    \"Education\"              \n[25] \"Salary_bucket\"           \"Work_experience_bucket\" \n[27] \"quarter_year\"           \n```\n:::\n\n```{.r .cell-code}\n# Top companies\nlibrary(RColorBrewer)\ntop_companies_year <- data %>%group_by(Year,company) %>%summarise(avg_compensation=mean(totalyearlycompensation))%>%arrange(desc(avg_compensation))%>%group_by(Year)%>%\ntop_n(n = 10)\ncolour_count <- n_distinct(top_companies_year$company)\ncolour_palette1 <- brewer.pal(colour_count, name = \"Set1\")\ncolour_palette2 <- brewer.pal(colour_count, name = \"Set2\")\n\nggplot(top_companies_year, aes(x = Year, y = avg_compensation, color = company)) +\n  geom_line() +\n  geom_point() +\n  labs(title = \"Top 10 companies\",\n       x = \"Year\",\n       y = \"Total People who reported Salaries\",\n       color = \"Company Name\") +\n  theme_minimal() +\n  scale_color_manual(values = c(colour_palette1, colour_palette2,\"black\",\"blue\") , name = \"Company Name\")\n```\n\n::: {.cell-output-display}\n![](PriyankaPerumalla_final_project_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\n### Top 10 Roles\nThe top 10 roles based on average yearly compensation come out to be\n 1 Data Scientist              \n 2 Hardware Engineer           \n 3 Human Resources             \n 4 Marketing                   \n 5 Product Designer            \n 6 Product Manager             \n 7 Sales                       \n 8 Software Engineering Manager\n 9 Solution Architect          \n10 Technical Program Manager\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter the data for the top 3 bikes based on overall sales\ntop_ten_roles <- data %>%\ngroup_by(title) %>%\nsummarise(avg_compensation = mean(totalyearlycompensation)) %>%\ntop_n(10, avg_compensation) %>%\nselect(title)\n\ntop_ten_roles\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"title\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"Data Scientist\"},{\"1\":\"Hardware Engineer\"},{\"1\":\"Human Resources\"},{\"1\":\"Marketing\"},{\"1\":\"Product Designer\"},{\"1\":\"Product Manager\"},{\"1\":\"Sales\"},{\"1\":\"Software Engineering Manager\"},{\"1\":\"Solution Architect\"},{\"1\":\"Technical Program Manager\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n\n### Month on month entries\nIf somebody were to switch their role, they have a natural tendency to aim for a higher compensation package. But companies strictly spend in some months of the year and hence do not allow negotiation etc which helps to increase an techie's package. But there are also months when the hiring is aggressive and companies only target to hire the required head count not very strict with the packages. We understand from all of this that planning is crucial in such processes. As seen in our analysis, the months of Dec, Jan, Feb, Mar are ideal for a job change as people have typically reported a higher package during those months.\n\n::: {.cell}\n\n```{.r .cell-code}\njob_month <- data %>% \n  group_by(Month) %>%arrange(desc(Month)) %>%\n  summarise(avg_compensation=mean(totalyearlycompensation))\n\n\n# Plot average profit percentage over months\nmonth_plot <- ggplot(job_month, aes(x = Month, y = avg_compensation)) +\n  geom_bar(stat = \"identity\", fill = \"steelblue\") +\n  labs(title = \"Average Profitability Over Months\",\n       x = \"Month\",\n       y = \"Average Profit Percentage\") +\n  theme_minimal()\n# Display the plot\nmonth_plot\n```\n\n::: {.cell-output-display}\n![](PriyankaPerumalla_final_project_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\n### Hiring Scene every quarter\nIf somebody were to switch their role, they first have to apply then clear the interviews etc. A lot of times, even after applying aggresively, people don't get the callbacks for interviews. Hence, it is crucial to plan the time of the year which would be favorable for interview calls. The below analysis says,Quarter 1 of the year is highly favorable for such a thing,\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 21575    27\n```\n:::\n\n```{.r .cell-code}\nggplot(data, aes(x = quarter_year)) + geom_bar() + ggtitle(\"Hiring Quarter\")\n```\n\n::: {.cell-output-display}\n![](PriyankaPerumalla_final_project_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\n\n\n\n### Heat Map of Statewise distribution of salaries\nUsually the salary of person increases with years of experience. But it can vary depending on the cost of living of the state he is working in. The below analysis says that California has highest salaries followed by Washington.\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(reshape2)\nlibrary(ggplot2)\nfiltered_data <- data%>%filter(State %in% c(\" NY\", \" CA\", \" WA\", \" MA\", \" IL\", \" TX\", \" GA\", \" NH\", \" NC\", \" IL\",\" WY\",\" RI\"))\n\nheatmap_plot<-ggplot(filtered_data, aes(x = State, y = Work_experience_bucket, fill = totalyearlycompensation)) + geom_tile() + scale_fill_gradient(low = \"lightgreen\", high = \"darkgreen\", na.value = \"grey\", name = \"Total Yearly Compensation\") + labs(title = \"Heatmap of Total Yearly Compensation by State and Work Experience\", x = \"State\", y = \"Work Experience Bucket\") + theme_minimal() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))\n\n# Display the heatmap\nheatmap_plot\n```\n\n::: {.cell-output-display}\n![](PriyankaPerumalla_final_project_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\n\n\n### Heat Map of State vs Company\nUsually companies vary the compensation slightly to suite the cost of living in some regions. Our analysis supports this hypothesis. While the analysis says that California and Washington pay the highest salaries. It also rightly highlights the companies like UiPath,Netflix,Uber etc which pay people on a higher end.\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(reshape2)\nlibrary(ggplot2)\nfiltered_data1 <- data%>%filter(State %in% c(\" NY\", \" CA\", \" WA\", \" MA\", \" IL\", \" TX\", \" GA\", \" NH\", \" NC\", \" IL\",\" WY\",\" RI\"))%>%filter(company %in% c(\"Microsoft\",\"Amazon\",\"3M\",\"Addepar\",\"Tesla\",\"BCG\",\"Fidelity Investments\",\"UiPath\",\"Uber\",\"Netflix\",\"Figma\",\"HRT\",\"ServiceNow\"))\n\nheatmap_plot<-ggplot(filtered_data1, aes(x = company, y = State, fill = totalyearlycompensation)) + geom_tile() + scale_fill_gradient(low = \"lightblue\", high = \"darkblue\", na.value = \"grey\", name = \"Total Yearly Compensation\") + labs(title = \"Heatmap of Total Yearly Compensation by State and Company\", x = \"company\", y = \"State\") + theme_minimal() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))\n\n# Display the heatmap\nheatmap_plot\n```\n\n::: {.cell-output-display}\n![](PriyankaPerumalla_final_project_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n\n\n\n### State wise pay distribution\nWhile some states may have highest pay bands, but some states are more suitable for people who are the average pay band as they will have many options when they switch the jobs. For example,the state of Rhode Island has wider range of pay compared to Illinois but for an average earning person, Illinois has many job oppportunities to pursue at the same pay band compared to Rhode Island.\n\n::: {.cell}\n\n```{.r .cell-code}\n# Using number of observation per group\nfiltered_data2 <- data%>%filter(State %in% c(\" NY\", \" CA\", \" WA\",\" IL\", \" TX\", \" GA\", \" NH\", \" NC\",\" WY\",\" RI\"))\n\nfunc <- function(x) sprintf(\"%d\", x)\nplot <- filtered_data2 %>% na.omit() %>% ggplot(aes(x = State, y = totalyearlycompensation)) +\n       stat_boxplot(geom = \"errorbar\", # Boxplot with error bars \n                    width = 0.2) +\n       geom_boxplot(fill = 'red', colour = \"blue\", # Colors\n                    alpha = 0.9, outlier.colour = \"red\") +\n       scale_y_continuous(name = \"Total Pay\", labels = func) +  # Continuous variable label\n       scale_x_discrete(name = \"Work Location\") +      # Group label\n       ggtitle(\"Boxplot by Work Location\") + # Plot title\n       theme(axis.line = element_line(colour = \"black\", # Theme customization\n                                      size = 0.25), axis.text.y = element_text(size = 8 ))\nplot\n```\n\n::: {.cell-output-display}\n![](PriyankaPerumalla_final_project_files/figure-html/unnamed-chunk-27-1.png){width=960}\n:::\n:::\n\n\n\n\n### Racial discrimination\nCompanies try their best to not discriminate anybody in any way. But some races have lesser representation in our respondants list. We can clearly see this dataset is skewed towards Asian and White races compared to others.\n\n::: {.cell}\n\n```{.r .cell-code}\n#ggplot(data, aes(x = Race, y= totalyearlycompensation)) + geom_bar() + ggtitle(\"Racial Distribution vs Pay\")\n\nggplot(data, aes(x = Race, y = totalyearlycompensation)) +\n  geom_point(size = 2)  +\n  labs(title = \"Total Compensation vs Race\",\n       x = \"Race\",\n       y = \"Yearly Compensation\")\n```\n\n::: {.cell-output-display}\n![](PriyankaPerumalla_final_project_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n\n\n### CONCLUSION\n\nWith all the analysis above, we can answer the following questions-\n\n1. The respondents are from different education backgrounds but the distribution is skewed towards peple who are atleast graduates. They make 99% of the participants, given its higher population (shown in excel sheet).\n\n2. There is a huge gender gap that can be noticed. While it can be concluded that there is only one female for every 4 males in the data that has job in our interested domain. It can also be noticed that men tend to pursue higher education more tham female. \n\n3. We see that there is a clear correlation between Education level (completed degree) vs job compensation. In every salary band such a trend is varying. Salary bands above 250k USD value individual accomplishments over educational degree. \n\n4. The average total compensation changes with every year. In fact it reduced from the year 2020 to 2021.\n\n5. There are definately preferred companies in terms of pay band.\n\n6. Some roles in the tech industry are very popular compared to others like Data Scientist, Software Development Engineer, Hardware engineer etc.\n\n7. Dec, Jan, Feb are more favorable for getting a higher package than other months of the year.\n\n8. Quarter 1 gives an individual more chances of callbacks for interviews over other quarters.\n\n9. Some states in the US are better for average earning people and some other states are better for people who earn way above the average pay bands.\n\n10. The dataset I have picked is skewed towards some human races(Asians, White) over others(Hispanic)\n\n### Reflection\n\nSince it is my first project in R, I learned that working with a data set involves taking raw data, cleaning it, then visualizing and interpreting different relationships.\nI focused on the variables that I was most intrigued by. Eg: I was curious about how gender/degrees influence jobs and compensation. What paths or roles do Data Science enthusiasts from different education backgrounds prefer? Which states are currently paying high? For somebody would I advise to pursue a masters degree in order to get a high salary?\nI've enjoyed learning the process for exploratory data analysis and visualization.",
    "supporting": [
      "PriyankaPerumalla_final_project_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}