{
  "hash": "5807446e439ca53ef50624a52173cbca",
  "result": {
    "markdown": "---\ntitle: \"Final Project: Abhinav Reddy Yadatha\"\nauthor: \"Abhinav Reddy Yadatha\"\ndescription: \"Final Project writeup\"\ndate: \"05/21/2023\"\nformat:\n  html:\n    df-print: paged\n    toc: true\n    code-copy: true\n    code-tools: true\n    css: styles.css\ncategories:\n  - final_Project\n  \neditor_options: \n  chunk_output_type: console\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(ggplot2)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Part 1. Introduction \n\nProject Topic: The project aims to analyze the factors influencing the survival of passengers aboard the RMS Titanic during its tragic maiden voyage in 1912.\n\nGeneral Research Question: What were the determinants of survival among the passengers on the Titanic?\n\nDataset Description: The project utilizes the Titanic dataset, a well-known and frequently used dataset in data analysis and machine learning tasks. This dataset is derived from the passenger manifest of the RMS Titanic and has been curated by various organizations and individuals for educational and research purposes. Each row in the dataset represents a passenger who was aboard the Titanic during its ill-fated voyage.\n\nThe dataset includes a range of variables such as the passenger's name, age, gender, passenger class, ticket fare, cabin number, port of embarkation, survival status, and more. These attributes were collected from passenger records, survivor interviews, and historical documents related to the disaster. The dataset encompasses both survivors and non-survivors, with the survival status column indicating whether a passenger survived (labeled as \"1\") or did not survive (labeled as \"0\") the sinking of the Titanic.\n\nUnit of Analysis: In the Titanic dataset, each case or unit of analysis refers to an individual passenger who was on board the Titanic. The dataset contains information for 891 passengers, with each row representing a unique passenger and the associated attributes.\n\nThe project aims to explore the relationships between various factors such as gender, age, passenger class, family size, and cabin location with the survival outcome. By analyzing this dataset, we can gain insights into the demographics and characteristics of the passengers, investigate the impact of different variables on survival rates, and uncover patterns and correlations that shed light on the tragic events of the Titanic disaster.\n\n## Part 2. Background of the Topic/Literature Review\n\nThe sinking of the Titanic in 1912 remains a captivating and tragic event in history. By analyzing the factors that influenced the survival of its passengers, we can gain valuable insights into the social dynamics, inequalities, and decision-making processes of that time. Exploring the Titanic dataset allows us to uncover patterns and correlations that have practical implications for emergency preparedness today. Understanding the determinants of survival on the Titanic not only deepens our knowledge of this historic event but also offers lessons for enhancing safety and well-being in future crises.\n\n\n## Part 3. Dataset Introduction\n\n\nThe Titanic dataset is a widely recognized and extensively used dataset for data analysis and machine learning purposes. It originates from the passenger manifest of the RMS Titanic, a British passenger liner that tragically sank during its inaugural voyage in April 1912. Numerous organizations and individuals have carefully compiled and organized the dataset for educational and research applications based on the real-life incident. Each row in the dataset corresponds to an individual passenger who was on board the Titanic during its ill-fated journey. The dataset comprises various attributes pertaining to the passengers, including their names, ages, genders, passenger classes, ticket fares, cabin numbers, ports of embarkation, survival status, and more. These attributes were gathered from passenger records, survivor interviews, and historical documents related to the disaster. The dataset encompasses both survivors and non-survivors, with the survival status column denoting whether a passenger survived (labeled as \"1\") or did not survive (labeled as \"0\") the sinking of the Titanic. \n\n\n## Part 4. Dataset Description\n\n(Story)\nThis dataset contains a total of 891 rows and 12 columns and the descriptive information about what each of the 12 fields are given below : \n\nPassengerId: A unique identifier assigned to each passenger.\nSurvived: Indicates whether the passenger survived the sinking or not (0 = No, 1 = Yes).\nPclass: Represents the passenger class (1 = 1st class, 2 = 2nd class, 3 = 3rd class).\nName: The name of the passenger.\nSex: The gender of the passenger (Male or Female).\nAge: The age of the passenger in years (some values may be missing).\nSibSp: The number of siblings/spouses aboard the Titanic.\nParch: The number of parents/children aboard the Titanic.\nTicket: The ticket number of the passenger.\nFare: The fare or ticket price paid by the passenger\nCabin: The cabin number assigned to the passenger (some values may be missing).\nEmbarked: The port of embarkation (C = Cherbourg, Q = Queenstown, S = Southampton).\n\nCoding Component:\n\n1.  Read the titanic dataset;\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#read and get a overview of the data\ndata <- read_csv(\"AbhinavReddyYadatha_FinalProjectData/titanic.csv\")\nview(data)\n```\n:::\n\n\n2. Descriptive information of the titanic dataset :\n\n\n    ::: {.cell}\n    \n    ```{.r .cell-code}\n    # Checking the dimensions of the data\n    dim(data)\n    ```\n    \n    ::: {.cell-output .cell-output-stdout}\n    ```\n    [1] 891  12\n    ```\n    :::\n    \n    ```{.r .cell-code}\n    # checking the unique age group count\n    length(unique(data$Age))\n    ```\n    \n    ::: {.cell-output .cell-output-stdout}\n    ```\n    [1] 89\n    ```\n    :::\n    \n    ```{.r .cell-code}\n    #printing out the first few examples\n    head(data)\n    ```\n    \n    ::: {.cell-output-display}\n    `````{=html}\n    <div data-pagedtable=\"false\">\n      <script data-pagedtable-source type=\"application/json\">\n    {\"columns\":[{\"label\":[\"PassengerId\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Survived\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pclass\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Name\"],\"name\":[4],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Sex\"],\"name\":[5],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Age\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"SibSp\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Parch\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Ticket\"],\"name\":[9],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Fare\"],\"name\":[10],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Cabin\"],\"name\":[11],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Embarked\"],\"name\":[12],\"type\":[\"chr\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"1\",\"2\":\"0\",\"3\":\"3\",\"4\":\"Braund, Mr. Owen Harris\",\"5\":\"male\",\"6\":\"22\",\"7\":\"1\",\"8\":\"0\",\"9\":\"A/5 21171\",\"10\":\"7.2500\",\"11\":\"NA\",\"12\":\"S\"},{\"1\":\"2\",\"2\":\"1\",\"3\":\"1\",\"4\":\"Cumings, Mrs. John Bradley (Florence Briggs Thayer)\",\"5\":\"female\",\"6\":\"38\",\"7\":\"1\",\"8\":\"0\",\"9\":\"PC 17599\",\"10\":\"71.2833\",\"11\":\"C85\",\"12\":\"C\"},{\"1\":\"3\",\"2\":\"1\",\"3\":\"3\",\"4\":\"Heikkinen, Miss. Laina\",\"5\":\"female\",\"6\":\"26\",\"7\":\"0\",\"8\":\"0\",\"9\":\"STON/O2. 3101282\",\"10\":\"7.9250\",\"11\":\"NA\",\"12\":\"S\"},{\"1\":\"4\",\"2\":\"1\",\"3\":\"1\",\"4\":\"Futrelle, Mrs. Jacques Heath (Lily May Peel)\",\"5\":\"female\",\"6\":\"35\",\"7\":\"1\",\"8\":\"0\",\"9\":\"113803\",\"10\":\"53.1000\",\"11\":\"C123\",\"12\":\"S\"},{\"1\":\"5\",\"2\":\"0\",\"3\":\"3\",\"4\":\"Allen, Mr. William Henry\",\"5\":\"male\",\"6\":\"35\",\"7\":\"0\",\"8\":\"0\",\"9\":\"373450\",\"10\":\"8.0500\",\"11\":\"NA\",\"12\":\"S\"},{\"1\":\"6\",\"2\":\"0\",\"3\":\"3\",\"4\":\"Moran, Mr. James\",\"5\":\"male\",\"6\":\"NA\",\"7\":\"0\",\"8\":\"0\",\"9\":\"330877\",\"10\":\"8.4583\",\"11\":\"NA\",\"12\":\"Q\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n      </script>\n    </div>\n    `````\n    :::\n    :::\n\n\n3.  Conduct summary statistics of the dataset : \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Displaying the summary of the titanic data\n\nsummary(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  PassengerId       Survived          Pclass          Name          \n Min.   :  1.0   Min.   :0.0000   Min.   :1.000   Length:891        \n 1st Qu.:223.5   1st Qu.:0.0000   1st Qu.:2.000   Class :character  \n Median :446.0   Median :0.0000   Median :3.000   Mode  :character  \n Mean   :446.0   Mean   :0.3838   Mean   :2.309                     \n 3rd Qu.:668.5   3rd Qu.:1.0000   3rd Qu.:3.000                     \n Max.   :891.0   Max.   :1.0000   Max.   :3.000                     \n                                                                    \n     Sex                 Age            SibSp           Parch       \n Length:891         Min.   : 0.42   Min.   :0.000   Min.   :0.0000  \n Class :character   1st Qu.:20.12   1st Qu.:0.000   1st Qu.:0.0000  \n Mode  :character   Median :28.00   Median :0.000   Median :0.0000  \n                    Mean   :29.70   Mean   :0.523   Mean   :0.3816  \n                    3rd Qu.:38.00   3rd Qu.:1.000   3rd Qu.:0.0000  \n                    Max.   :80.00   Max.   :8.000   Max.   :6.0000  \n                    NA's   :177                                     \n    Ticket               Fare           Cabin             Embarked        \n Length:891         Min.   :  0.00   Length:891         Length:891        \n Class :character   1st Qu.:  7.91   Class :character   Class :character  \n Mode  :character   Median : 14.45   Mode  :character   Mode  :character  \n                    Mean   : 32.20                                        \n                    3rd Qu.: 31.00                                        \n                    Max.   :512.33                                        \n                                                                          \n```\n:::\n:::\n\n\nExploring the variables of the dataset : \n\nVariable : Sex\n\n::: {.cell}\n\n```{.r .cell-code}\n# Count the number of males and females\ngender_counts <- table(data$Sex)\n\n# Display the counts\ngender_counts\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nfemale   male \n   314    577 \n```\n:::\n\n```{.r .cell-code}\n# Calculate the total number of passengers\ntotal_passengers <- nrow(data)\n\n# Calculate the number of female passengers\nmale_passengers <- sum(data$Sex == \"male\")\n\n# Calculate the percentage of females\npercentage_males <- (male_passengers / total_passengers) * 100\n\n# Display the percentage of females\npercentage_males\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 64.7587\n```\n:::\n:::\n\n\nThis variable refers to the gender of the passenger. It can be observed that there are 314 females and 577 males. Hence, the majority of the proportion of males is higher , in fact it's a staggering '64.7587%'.\n\nVariable : Survived\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Count the number of passengers survived.\nsurvived_counts <- table(data$Survived)\n\n# Display the counts\nsurvived_counts\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  0   1 \n549 342 \n```\n:::\n\n```{.r .cell-code}\n# Calculate the number of survived passengers\nsurvived_passengers <- sum(data$Survived == \"1\")\n\n# Calculate the percentage of survived passengers\npercentage_survived <- (survived_passengers / total_passengers) * 100\n\n# Display the percentage of survived passengers\npercentage_survived\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 38.38384\n```\n:::\n:::\n\n\nThis variable indicates if a passenger has survived or not, it can be observed that only 342 passengers survived out of the total of 891 passengers. The survival rate of the titanic was just a mere 38.38384 %\n\nVariable Pclass:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Count the number of passengers in each passenger class\npclass_counts <- table(data$Pclass)\n\n# Display the counts\npclass_counts\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  1   2   3 \n216 184 491 \n```\n:::\n:::\n\n\nIt can be observed that a majority of the passengers were travelling in class 3, then class 1 and the least in class 2.\n\nVariable : Fare\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Find the maximum fare\nmax_fare <- max(data$Fare, na.rm = TRUE)\n\n# Find the minimum fare\nmin_fare <- min(data$Fare, na.rm = TRUE)\n\n# Display the maximum and minimum fare\nmax_fare\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 512.3292\n```\n:::\n\n```{.r .cell-code}\nmin_fare\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0\n```\n:::\n\n```{.r .cell-code}\n# Calculate the mean fare\nmean_fare <- mean(data$Fare, na.rm = TRUE)\n\n# Display the mean fare\nmean_fare\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 32.20421\n```\n:::\n:::\n\n\nFrom the analysis above it can be observed that there were passengers who did not have to pay any fare whereas others had to pay a maximum of 512.3292. The mean fare paid by the passengers is 32.20421 USD.\n\nVariable Age : \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Find the maximum age\nmax_age <- max(data$Age, na.rm = TRUE)\n\n# Find the minimum age\nmin_age <- min(data$Age, na.rm = TRUE)\n\n# Display the maximum and minimum age\nmax_age\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 80\n```\n:::\n\n```{.r .cell-code}\nmin_age\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.42\n```\n:::\n\n```{.r .cell-code}\n# Calculate the mean age\nmean_age <- mean(data$Age, na.rm = TRUE)\n\n# Display the mean age\nmean_age\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 29.69912\n```\n:::\n:::\n\n\nThere were people from all ages on the titanic. The maximum age being 80 and the minimum age being 0.42 while the mean age is 29.69912 ~ 30 years.\n\n\n\n## Part 5. Analysis Plan\n\nSpecific questions : \n\n1. What was the overall survival rate of passengers aboard the Titanic?\n\n2. How does the survival rate vary based on passenger gender?\n\n3. Did the passenger class have an impact on the survival rate?\n\n4. What were the survival rates for passengers with family members aboard the Titanic versus those traveling alone\n\n5. How does the survival rate differ among different age groups or passenger classes?\n\n6. What was the distribution of ages among the passengers, and did age play a role in survival?\n\n7. How does the ticket fare correlate with the passenger class and survival?\n\n\nAnalysis Plan :\n\nTo answer the research questions mentioned above, I plan to conduct a combination of data analysis and visualization techniques.\n\nDescriptive Statistics: I will calculate summary statistics such as means, medians, and proportions to provide an overview of the variables of interest, including survival rates based on different categories.\n\nBar Charts: I will create bar charts to visualize the relationship between categorical variables (e.g., passenger class, gender, port of embarkation) and survival rates. This will allow for a quick comparison of survival probabilities across different categories.\n\nHistograms : I will use histograms to explore the distribution of continuous variables (e.g., age, fare) for both survivors and non-survivors. This will help identify any patterns or differences in the distributions between the two groups.\n\nBoxplots: Boxplots will be used to compare the median age and fare of survivors and non-survivors, providing insights into potential differences in these variables.\n\nData Analyses I plan to do for this project are as follows :\n\nSurvival Rate Analysis:\n\nCalculate the overall survival rate of passengers (percentage of survivors) to provide an initial understanding of survival outcomes.\n\nGender-based Analysis:\n\nCompare the survival rates of male and female passengers using a bivariate visualization (such as a bar chart or stacked bar plot) to explore the potential impact of gender on survival.\n\nPassenger Class Analysis:\n\nExamine the survival rates across different passenger classes (first, second, and third) using visualizations (such as a stacked bar chart) to investigate the relationship between socio-economic status and survival.\n\nAge Distribution Analysis:\n\nPlot the age distribution of passengers using a histogram to visualize the age groups and identify any patterns or trends in survival rates within different age ranges.\n\nFamily Size Analysis:\n\nInvestigate the relationship between family size (based on the SibSp and Parch variables) and survival rates using a bivariate visualization (such as a scatter plot or grouped bar chart) to explore the impact of traveling with family members on survival.\n\nBivariate Visualization:\n\nBivariate visualizations, such as bar charts or stacked bar plots, are useful for comparing two variables, such as gender and survival or passenger class and survival. They allow us to visually examine the relationship between two categorical variables and observe any patterns or differences in survival rates based on these variables.\n\nScatter Plot:\n\nScatter plots are valuable for analyzing the relationship between two continuous variables, such as family size and survival rates. They enable us to observe the dispersion of data points and determine if there is any correlation or trend between the variables.\n\n\nBox Plot :\n\nBox plots are excellent for comparing the distribution of a continuous variable, such as fare, between different groups (e.g., survivors vs. non-survivors). They provide a visual representation of the median, quartiles, and outliers in the data, allowing us to detect any variations or differences in fare distributions based on survival outcomes.\n    \nCalculating Age Groups:\n\nGrouping passengers into age categories: You can create a new variable called \"Age Group\" by categorizing the passengers' ages into different groups, such as \"Child,\" \"Adult,\" and \"Elderly.\" This can be done by specifying age ranges and using conditional statements or the cut() function in R.\nConverting Categorical Variables:\n\nMapping categorical variables to numerical values: If any categorical variables, such as \"Sex\" or \"Embarked,\" are represented as text, you can create new variables that map these categories to numerical values. For example, you can create a new variable called \"Sex_Code\" where \"male\" is encoded as 0 and \"female\" as 1.\nCalculating Family Size:\n\nCreating a variable for family size: You can create a new variable called \"Family Size\" by summing the \"SibSp\" (number of siblings/spouses aboard) and \"Parch\" (number of parents/children aboard) variables. This new variable represents the total number of family members a passenger had onboard.\n\nIf any column has too much empty data, I plan to drop it completely as it would not contain a lot of information.\n\n## Part 6. Survival Rate Analysis and Visualization\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate summary statistics for continuous variables\nsummary(data$Age)  # Summary statistics for age\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n   0.42   20.12   28.00   29.70   38.00   80.00     177 \n```\n:::\n\n```{.r .cell-code}\nsummary(data$Fare)  # Summary statistics for fare\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   0.00    7.91   14.45   32.20   31.00  512.33 \n```\n:::\n\n```{.r .cell-code}\n# Calculate summary statistics for categorical variables\ntable(data$Sex)  # Frequency count for gender\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nfemale   male \n   314    577 \n```\n:::\n\n```{.r .cell-code}\ntable(data$Pclass)  # Frequency count for passenger class\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  1   2   3 \n216 184 491 \n```\n:::\n\n```{.r .cell-code}\ntable(data$Survived)  # Frequency count for survival status\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  0   1 \n549 342 \n```\n:::\n\n```{.r .cell-code}\n# Calculate survival rates based on different categories\nsurvival_rates_gender <- prop.table(table(data$Survived, data$Sex), margin = 2) * 100\nsurvival_rates_class <- prop.table(table(data$Survived, data$Pclass), margin = 2) * 100\n\n# Display survival rates w.r.t gender and class\nsurvival_rates_gender\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   \n      female     male\n  0 25.79618 81.10919\n  1 74.20382 18.89081\n```\n:::\n\n```{.r .cell-code}\nsurvival_rates_class\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   \n           1        2        3\n  0 37.03704 52.71739 75.76375\n  1 62.96296 47.28261 24.23625\n```\n:::\n:::\n\n\nFrom the above statistics, it can be observed that approximately 75% of females have survived the tragedy whereas only nearly 19% of men have survived. A trend could be identified about the gender and the survival rate. In addition to this, based on the class it is observed that people who were in class 1 had a significantly higher survival rate compare to that of class 2 and class 3.\n\nAnalysis : \n\nResearch Question analysed : How does the survival rate vary based on passenger gender?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# count of survivors by gender\nggplot(data, aes(x=Sex, y=Survived, fill=Sex)) +\n  geom_bar(stat=\"identity\")+\n  scale_fill_grey()\n```\n\n::: {.cell-output-display}\n![](final_project_draft_AbhinavReddyYadatha_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n\n```{.r .cell-code}\n  ggtitle(\"Survival counts of Male and Female Passengers\") +\n    ggtitle(\"Counts of female vs male survivors\") +\n  theme_minimal()\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in ggtitle(\"Survival counts of Male and Female Passengers\") + ggtitle(\"Counts of female vs male survivors\"): non-numeric argument to binary operator\n```\n:::\n:::\n\n\n\nResearch Analysed: Median age and fare from survivors and non-survivors.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create boxplots comparing the median age and fare between survivors and non-survivors\nggplot(data, aes(x = factor(Survived), y = Age)) +\n  geom_boxplot(fill = \"lightblue\", color = \"black\") +\n  labs(x = \"Survived\", y = \"Age\", title = \"Boxplot of Age: Survivors vs. Non-Survivors\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](final_project_draft_AbhinavReddyYadatha_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(data, aes(x = factor(Survived), y = Fare)) +\n  geom_boxplot(fill = \"lightblue\", color = \"black\") +\n  labs(x = \"Survived\", y = \"Fare\", title = \"Boxplot of Fare: Survivors vs. Non-Survivors\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](final_project_draft_AbhinavReddyYadatha_files/figure-html/unnamed-chunk-12-2.png){width=672}\n:::\n:::\n\n\nFrom the boxplots comparing the median age and fare between survivors and non-survivors, we can infer the following:\n\nAge: The median age of survivors appears to be slightly lower than that of non-survivors. This suggests that there may have been a higher proportion of younger passengers who survived the Titanic disaster. However, it's important to note that the difference in median age might not be substantial.\n\nFare: The median fare of survivors seems to be slightly higher compared to non-survivors. This indicates that passengers who paid higher fares might have had a better chance of survival. It's possible that higher-paying passengers were assigned to more favorable locations on the ship or had access to better life-saving resources.\n\nThese inferences are based on the central tendency represented by the median values in the boxplots. However, it's essential to conduct further statistical analysis to validate these observations.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\n# Calculate the survival rates by gender\nsurvival_rates_gender <- prop.table(table(data$Survived, data$Sex), margin = 2) * 100\n\ndf <- as.data.frame(survival_rates_gender)\nsubset_df <- subset(df, Var1 == 1)\nsubset_df\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Var1\"],\"name\":[1],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"Var2\"],\"name\":[2],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"Freq\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"1\",\"2\":\"female\",\"3\":\"74.20382\",\"_rn_\":\"2\"},{\"1\":\"1\",\"2\":\"male\",\"3\":\"18.89081\",\"_rn_\":\"4\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\n# Create a bar chart to compare survival rates by gender\nggplot(data = subset_df, aes(x=Var2, y=Freq, fill=Var2)) +\n  geom_bar(stat = \"identity\", position = \"stack\") +\n  labs(x = \"Gender\", y = \"Survival rate %\", fill = \"Survived\") +\n  scale_fill_manual(values = c(\"red\", \"blue\"), labels = c(\"% of females survived\", \"% of males survived\")) +\n  ggtitle(\"Survival Rates of Male VS Female Passengers\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](final_project_draft_AbhinavReddyYadatha_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n\nFrom the above analyses, it is observed that despite the fact that there are males than compard to females, gender could be treated as an indicator survival chance. This is due to the fact that females on titanic had a survival rate of 74 % whereas the males on the same boat only had 18%. \n\n\nResearch question answered : Passenger Class Analysis\nExamine the survival rates across different passenger classes (first, second, and third) using visualizations (such as a Stacked bar chart) to investigate the relationship between socio-economic status and survival.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# count of survivors by passenger class via stacked bar graph\n\nggplot(data, aes(x=Pclass, y=Survived, fill=Sex)) +\n  geom_bar(stat=\"identity\")+\n  scale_fill_grey()+\n  ggtitle(\"Survival counts of Male and Female Passengers\") +\n    ggtitle(\"Counts of female vs male survivors\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](final_project_draft_AbhinavReddyYadatha_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\n# Bar graph to determine the relationship between survival and socio-economic status\n\n# Calculate the survival rates by passenger class\nsurvival_rates_pclass <- prop.table(table(data$Survived, data$Pclass), margin = 2) * 100\n\ndf <- as.data.frame(survival_rates_pclass)\nsubset_df <- subset(df, Var1 == 1)\nsubset_df\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Var1\"],\"name\":[1],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"Var2\"],\"name\":[2],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"Freq\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"1\",\"2\":\"1\",\"3\":\"62.96296\",\"_rn_\":\"2\"},{\"1\":\"1\",\"2\":\"2\",\"3\":\"47.28261\",\"_rn_\":\"4\"},{\"1\":\"1\",\"2\":\"3\",\"3\":\"24.23625\",\"_rn_\":\"6\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\n# Create a bar chart to compare survival rates by gender\nggplot(data = subset_df, aes(x=Var2, y=Freq, fill=Var2)) +\n  geom_bar(stat = \"identity\", position = \"stack\") +\n  scale_fill_grey() +\n  scale_fill_manual(values = c(\"red\", \"blue\", \"green\"), labels = c(\"Class 1 surivor %\", \"Class 2 surivor %\", \"Class 3 surivor %\"))+\n  labs(x = \"Passenger Class\", y = \"Survival rate %\", fill = \"Survived\") +\n  ggtitle(\"Survival Rates of Male VS Female Passengers\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](final_project_draft_AbhinavReddyYadatha_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\nTwo observations are made : 1. The number of passengers in class1 are significantly higher than the passengers in class 2 and class 3. 2. Despite having such high numbers, it is observed that the class 1 passengers have the highest rate of survival indicating that the passenger class type played a very important role in determining the survival.\n\n\nResearch question analysed : Age Distribution Analysis:\n\nPlot the age distribution of passengers using a histogram to visualize the age groups and identify any patterns or trends in survival rates within different age ranges.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a histogram of the age distribution\nlibrary(ggplot2)\nggplot(data, aes(x = Age)) +\n  geom_histogram(binwidth = 5, fill = \"lightblue\", color = \"black\") +\n  labs(x = \"Age\", y = \"Frequency\") +\n  ggtitle(\"Age Distribution of Passengers\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](final_project_draft_AbhinavReddyYadatha_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\nThe age groups are all discrete, so we would not be in a position to analyse. So we will mutate the age column into age groups and analyse accordingly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Mutate the 'Age' column into age groups\ndata$AgeGroup <- cut(data$Age, breaks = c(0, 18, 30, 50, Inf),\n                     labels = c(\"Child\", \"Young Adult\", \"Adult\", \"Senior\"))\n\nhead(data)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"PassengerId\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Survived\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pclass\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Name\"],\"name\":[4],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Sex\"],\"name\":[5],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Age\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"SibSp\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Parch\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Ticket\"],\"name\":[9],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Fare\"],\"name\":[10],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Cabin\"],\"name\":[11],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Embarked\"],\"name\":[12],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"AgeGroup\"],\"name\":[13],\"type\":[\"fct\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"1\",\"2\":\"0\",\"3\":\"3\",\"4\":\"Braund, Mr. Owen Harris\",\"5\":\"male\",\"6\":\"22\",\"7\":\"1\",\"8\":\"0\",\"9\":\"A/5 21171\",\"10\":\"7.2500\",\"11\":\"NA\",\"12\":\"S\",\"13\":\"Young Adult\"},{\"1\":\"2\",\"2\":\"1\",\"3\":\"1\",\"4\":\"Cumings, Mrs. John Bradley (Florence Briggs Thayer)\",\"5\":\"female\",\"6\":\"38\",\"7\":\"1\",\"8\":\"0\",\"9\":\"PC 17599\",\"10\":\"71.2833\",\"11\":\"C85\",\"12\":\"C\",\"13\":\"Adult\"},{\"1\":\"3\",\"2\":\"1\",\"3\":\"3\",\"4\":\"Heikkinen, Miss. Laina\",\"5\":\"female\",\"6\":\"26\",\"7\":\"0\",\"8\":\"0\",\"9\":\"STON/O2. 3101282\",\"10\":\"7.9250\",\"11\":\"NA\",\"12\":\"S\",\"13\":\"Young Adult\"},{\"1\":\"4\",\"2\":\"1\",\"3\":\"1\",\"4\":\"Futrelle, Mrs. Jacques Heath (Lily May Peel)\",\"5\":\"female\",\"6\":\"35\",\"7\":\"1\",\"8\":\"0\",\"9\":\"113803\",\"10\":\"53.1000\",\"11\":\"C123\",\"12\":\"S\",\"13\":\"Adult\"},{\"1\":\"5\",\"2\":\"0\",\"3\":\"3\",\"4\":\"Allen, Mr. William Henry\",\"5\":\"male\",\"6\":\"35\",\"7\":\"0\",\"8\":\"0\",\"9\":\"373450\",\"10\":\"8.0500\",\"11\":\"NA\",\"12\":\"S\",\"13\":\"Adult\"},{\"1\":\"6\",\"2\":\"0\",\"3\":\"3\",\"4\":\"Moran, Mr. James\",\"5\":\"male\",\"6\":\"NA\",\"7\":\"0\",\"8\":\"0\",\"9\":\"330877\",\"10\":\"8.4583\",\"11\":\"NA\",\"12\":\"Q\",\"13\":\"NA\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\n# For example, calculate the survival rate by age group\nsurvival_rates_agegroup <- prop.table(table(data$Survived, data$AgeGroup), margin = 2) * 100\n\n# Print the resulting table\nsurvival_rates_agegroup\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   \n       Child Young Adult    Adult   Senior\n  0 49.64029    64.44444 57.67635 65.62500\n  1 50.35971    35.55556 42.32365 34.37500\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# For example, calculate the survival rate by age group\nsurvival_rates_agegroup <- prop.table(table(data$Survived, data$AgeGroup), margin = 2) * 100\n\n\ndf <- as.data.frame(survival_rates_agegroup)\nsubset_df <- subset(df, Var1 == 1)\nsubset_df\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Var1\"],\"name\":[1],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"Var2\"],\"name\":[2],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"Freq\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"1\",\"2\":\"Child\",\"3\":\"50.35971\",\"_rn_\":\"2\"},{\"1\":\"1\",\"2\":\"Young Adult\",\"3\":\"35.55556\",\"_rn_\":\"4\"},{\"1\":\"1\",\"2\":\"Adult\",\"3\":\"42.32365\",\"_rn_\":\"6\"},{\"1\":\"1\",\"2\":\"Senior\",\"3\":\"34.37500\",\"_rn_\":\"8\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\n# Create a bar chart to compare survival rates by gender\nggplot(data = subset_df, aes(x=Var2, y=Freq, fill=Var2)) +\n  geom_bar(stat = \"identity\", position = \"stack\") +\n  scale_fill_grey() +\n  scale_fill_manual(values = c(\"red\", \"blue\", \"green\", \"orange\"), labels = c(\"child\", \"Young Adult\", \"Adult\", \"Senior\"))+\n  labs(x = \"Passenger Class\", y = \"Survival rate %\", fill = \"Survived\") +\n  ggtitle(\"Survival Rates of different age groups\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](final_project_draft_AbhinavReddyYadatha_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\nWhile, it can be observed that the children have the highest survival rate and seniors have the lowest rate, it is inconclusive to say whether the age factor is a factor affecting the chance of survival as all of them are pretty close. Due to the lack of this significant gap, I am ruling out Age as an definite factor affecting the survival.\n\nResearch Question Analysed : Family Size Analysis:\n\nInvestigate the relationship between family size (based on the SibSp and Parch variables) and survival rates using a bivariate visualization (such as a scatter plot or grouped bar chart) to explore the impact of traveling with family members on survival.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Grouped bar chart \n# Calculate the total family size by adding 'SibSp' and 'Parch'\ndata$FamilySize <- data$SibSp + data$Parch\n\n# Calculate the survival rate by family size\nsurvival_rates <- aggregate(Survived ~ FamilySize, data = data, FUN = function(x) sum(x) / length(x) * 100)\n\n# Create a grouped bar chart of survival rates by family size\nggplot(survival_rates, aes(x = as.factor(FamilySize), y = Survived)) +\n  geom_bar(stat = \"identity\", fill = \"lightblue\", color = \"black\") +\n  labs(x = \"Family Size\", y = \"Survival Rate (%)\") +\n  ggtitle(\"Relationship between Family Size and Survival Rates\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](final_project_draft_AbhinavReddyYadatha_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n\nFrom the grouped bar chart that visualizes the relationship between family size and survival rates, we can infer the following:\n\nSurvival rates tend to be higher for passengers traveling with a small family size. As the family size increases, the survival rates generally decrease.\nPassengers who were traveling alone (family size of 0) have a relatively lower survival rate compared to those with small family sizes (1-3). This suggests that having a few family members onboard might have provided some level of support or assistance during the Titanic disaster.\nLarger family sizes (4 and above) generally have lower survival rates, indicating that it might have been more challenging to navigate and escape the sinking ship with a larger group.\nThe highest survival rate is observed for passengers with a family size of 3, while the lowest survival rate is observed for passengers with a family size of 7 or more.\nOverall, this visualization suggests that the family size of passengers aboard the Titanic had an impact on their chances of survival.\n\n## Part 6. Conclusion and Discussion :\n\nIn this analysis of the Titanic dataset, we explored various aspects related to the survival of passengers. Here is a summary of our findings:\n\nOverall Survival Rate: The overall survival rate of passengers was approximately 38.38%. This means that out of all the passengers in the dataset, around 38.38% survived the Titanic disaster.\n\nGender and Survival: We observed that females had a significantly higher survival rate compared to males. The survival rate for females was approximately 74.20%, while for males it was around 18.89%. This suggests that gender played a significant role in determining the chances of survival, with females having a higher likelihood of surviving.\n\nAge and Survival: Analyzing the age groups, we noticed that there was no clear pattern of age influencing survival rates. However, younger passengers (children and adolescents) seemed to have a slightly higher survival rate compared to other age groups.\n\nFamily Size and Survival: Examining the relationship between family size (based on SibSp and Parch variables) and survival rates, we found that passengers traveling with larger families had lower chances of survival. This indicates that having a larger family onboard might have posed challenges in terms of coordination and accessing life-saving resources\n\nIn summary, gender, family size, and fare were found to be factors that influenced survival rates on the Titanic. Females, passengers with smaller families, and those who paid higher fares had higher chances of surviving the disaster. These findings align with historical accounts and popular narratives about the Titanic tragedy.\n\nVariables such as cabin number, had a substantial number of missing values, we tackled this issue by not doing any sort of analysis for it as it wont be very fruitful.\n\n\n## Part 7. Bibliography :\n\nDataset : https://www.kaggle.com/competitions/titanic/data\nProgramming Language : R\n",
    "supporting": [
      "final_project_draft_AbhinavReddyYadatha_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}