{
  "hash": "91bdbf205e603acf7c5f5997aff7892e",
  "result": {
    "markdown": "---\ntitle: \"Challenge 3: Pivoting Egg Data\"\nauthor: \"Saksham Kumar\"\ndescription: \"Pivoting Egg Data\"\ndate: \"04/03/2023\"\nformat:\n  html:\n    df-print: paged\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_3\n  - eggs\n  - Saksham Kumar\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(readxl)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Challenge Overview\n\nToday we attempt to:\n\n1.  read in the eggs dataset, and describe the data set using both words and any supporting information (e.g., tables, etc)\n2.  identify what needs to be done to tidy the current data\n3.  anticipate the shape of pivoted data\n4.  pivot the data into tidy format using `pivot_longer`\n\n## Read in data\n\n\n::: {.cell}\n\n```{.r .cell-code}\neggs<-read_csv(\"_data/eggs_tidy.csv\")\neggs\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"month\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"year\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"large_half_dozen\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"large_dozen\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"extra_large_half_dozen\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"extra_large_dozen\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"January\",\"2\":\"2004\",\"3\":\"126.000\",\"4\":\"230.000\",\"5\":\"132.000\",\"6\":\"230.000\"},{\"1\":\"February\",\"2\":\"2004\",\"3\":\"128.500\",\"4\":\"226.250\",\"5\":\"134.500\",\"6\":\"230.000\"},{\"1\":\"March\",\"2\":\"2004\",\"3\":\"131.000\",\"4\":\"225.000\",\"5\":\"137.000\",\"6\":\"230.000\"},{\"1\":\"April\",\"2\":\"2004\",\"3\":\"131.000\",\"4\":\"225.000\",\"5\":\"137.000\",\"6\":\"234.500\"},{\"1\":\"May\",\"2\":\"2004\",\"3\":\"131.000\",\"4\":\"225.000\",\"5\":\"137.000\",\"6\":\"236.000\"},{\"1\":\"June\",\"2\":\"2004\",\"3\":\"133.500\",\"4\":\"231.375\",\"5\":\"137.000\",\"6\":\"241.000\"},{\"1\":\"July\",\"2\":\"2004\",\"3\":\"133.500\",\"4\":\"233.500\",\"5\":\"137.000\",\"6\":\"241.000\"},{\"1\":\"August\",\"2\":\"2004\",\"3\":\"133.500\",\"4\":\"233.500\",\"5\":\"137.000\",\"6\":\"241.000\"},{\"1\":\"September\",\"2\":\"2004\",\"3\":\"129.750\",\"4\":\"233.500\",\"5\":\"135.875\",\"6\":\"241.000\"},{\"1\":\"October\",\"2\":\"2004\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.000\"},{\"1\":\"November\",\"2\":\"2004\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.000\"},{\"1\":\"December\",\"2\":\"2004\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.000\"},{\"1\":\"January\",\"2\":\"2005\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.000\"},{\"1\":\"February\",\"2\":\"2005\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.000\"},{\"1\":\"March\",\"2\":\"2005\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.000\"},{\"1\":\"April\",\"2\":\"2005\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.000\"},{\"1\":\"May\",\"2\":\"2005\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.000\"},{\"1\":\"June\",\"2\":\"2005\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.000\"},{\"1\":\"July\",\"2\":\"2005\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.000\"},{\"1\":\"August\",\"2\":\"2005\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.000\"},{\"1\":\"September\",\"2\":\"2005\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.000\"},{\"1\":\"October\",\"2\":\"2005\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.000\"},{\"1\":\"November\",\"2\":\"2005\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.000\"},{\"1\":\"December\",\"2\":\"2005\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.000\"},{\"1\":\"January\",\"2\":\"2006\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.000\"},{\"1\":\"February\",\"2\":\"2006\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.000\"},{\"1\":\"March\",\"2\":\"2006\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.375\"},{\"1\":\"April\",\"2\":\"2006\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.500\"},{\"1\":\"May\",\"2\":\"2006\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.500\"},{\"1\":\"June\",\"2\":\"2006\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.500\"},{\"1\":\"July\",\"2\":\"2006\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.500\"},{\"1\":\"August\",\"2\":\"2006\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.500\"},{\"1\":\"September\",\"2\":\"2006\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.500\"},{\"1\":\"October\",\"2\":\"2006\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.500\"},{\"1\":\"November\",\"2\":\"2006\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.500\"},{\"1\":\"December\",\"2\":\"2006\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.500\"},{\"1\":\"January\",\"2\":\"2007\",\"3\":\"128.500\",\"4\":\"233.500\",\"5\":\"135.500\",\"6\":\"241.500\"},{\"1\":\"February\",\"2\":\"2007\",\"3\":\"131.125\",\"4\":\"236.125\",\"5\":\"138.125\",\"6\":\"244.125\"},{\"1\":\"March\",\"2\":\"2007\",\"3\":\"132.000\",\"4\":\"237.000\",\"5\":\"139.000\",\"6\":\"245.000\"},{\"1\":\"April\",\"2\":\"2007\",\"3\":\"132.000\",\"4\":\"237.000\",\"5\":\"139.000\",\"6\":\"245.000\"},{\"1\":\"May\",\"2\":\"2007\",\"3\":\"132.000\",\"4\":\"237.000\",\"5\":\"139.000\",\"6\":\"245.000\"},{\"1\":\"June\",\"2\":\"2007\",\"3\":\"132.000\",\"4\":\"237.000\",\"5\":\"139.000\",\"6\":\"245.000\"},{\"1\":\"July\",\"2\":\"2007\",\"3\":\"132.000\",\"4\":\"237.000\",\"5\":\"139.000\",\"6\":\"245.000\"},{\"1\":\"August\",\"2\":\"2007\",\"3\":\"132.000\",\"4\":\"237.000\",\"5\":\"139.000\",\"6\":\"245.000\"},{\"1\":\"September\",\"2\":\"2007\",\"3\":\"132.000\",\"4\":\"237.000\",\"5\":\"139.000\",\"6\":\"245.000\"},{\"1\":\"October\",\"2\":\"2007\",\"3\":\"132.000\",\"4\":\"237.000\",\"5\":\"139.000\",\"6\":\"245.000\"},{\"1\":\"November\",\"2\":\"2007\",\"3\":\"132.000\",\"4\":\"237.000\",\"5\":\"139.000\",\"6\":\"245.000\"},{\"1\":\"December\",\"2\":\"2007\",\"3\":\"132.000\",\"4\":\"237.000\",\"5\":\"139.000\",\"6\":\"245.000\"},{\"1\":\"January\",\"2\":\"2008\",\"3\":\"132.000\",\"4\":\"237.000\",\"5\":\"139.000\",\"6\":\"245.000\"},{\"1\":\"February\",\"2\":\"2008\",\"3\":\"132.000\",\"4\":\"237.000\",\"5\":\"139.000\",\"6\":\"245.000\"},{\"1\":\"March\",\"2\":\"2008\",\"3\":\"132.000\",\"4\":\"237.000\",\"5\":\"139.000\",\"6\":\"245.000\"},{\"1\":\"April\",\"2\":\"2008\",\"3\":\"132.000\",\"4\":\"237.000\",\"5\":\"139.000\",\"6\":\"245.000\"},{\"1\":\"May\",\"2\":\"2008\",\"3\":\"132.000\",\"4\":\"237.000\",\"5\":\"139.000\",\"6\":\"245.000\"},{\"1\":\"June\",\"2\":\"2008\",\"3\":\"174.500\",\"4\":\"277.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"July\",\"2\":\"2008\",\"3\":\"174.500\",\"4\":\"277.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"August\",\"2\":\"2008\",\"3\":\"174.500\",\"4\":\"277.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"September\",\"2\":\"2008\",\"3\":\"174.500\",\"4\":\"277.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"October\",\"2\":\"2008\",\"3\":\"174.500\",\"4\":\"277.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"November\",\"2\":\"2008\",\"3\":\"174.500\",\"4\":\"277.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"December\",\"2\":\"2008\",\"3\":\"174.500\",\"4\":\"277.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"January\",\"2\":\"2009\",\"3\":\"174.500\",\"4\":\"277.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"February\",\"2\":\"2009\",\"3\":\"174.500\",\"4\":\"277.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"March\",\"2\":\"2009\",\"3\":\"174.500\",\"4\":\"277.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"April\",\"2\":\"2009\",\"3\":\"174.500\",\"4\":\"277.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"May\",\"2\":\"2009\",\"3\":\"174.500\",\"4\":\"277.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"June\",\"2\":\"2009\",\"3\":\"174.500\",\"4\":\"277.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"July\",\"2\":\"2009\",\"3\":\"174.500\",\"4\":\"277.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"August\",\"2\":\"2009\",\"3\":\"174.500\",\"4\":\"271.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"September\",\"2\":\"2009\",\"3\":\"174.500\",\"4\":\"271.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"October\",\"2\":\"2009\",\"3\":\"174.500\",\"4\":\"271.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"November\",\"2\":\"2009\",\"3\":\"174.500\",\"4\":\"271.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"December\",\"2\":\"2009\",\"3\":\"174.500\",\"4\":\"271.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"January\",\"2\":\"2010\",\"3\":\"174.500\",\"4\":\"271.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"February\",\"2\":\"2010\",\"3\":\"174.500\",\"4\":\"271.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"March\",\"2\":\"2010\",\"3\":\"174.500\",\"4\":\"268.000\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"April\",\"2\":\"2010\",\"3\":\"174.500\",\"4\":\"268.000\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"May\",\"2\":\"2010\",\"3\":\"174.500\",\"4\":\"268.000\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"June\",\"2\":\"2010\",\"3\":\"174.500\",\"4\":\"268.000\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"July\",\"2\":\"2010\",\"3\":\"174.500\",\"4\":\"268.000\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"August\",\"2\":\"2010\",\"3\":\"174.500\",\"4\":\"268.000\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"September\",\"2\":\"2010\",\"3\":\"174.500\",\"4\":\"268.000\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"October\",\"2\":\"2010\",\"3\":\"174.500\",\"4\":\"267.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"November\",\"2\":\"2010\",\"3\":\"174.500\",\"4\":\"267.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"December\",\"2\":\"2010\",\"3\":\"174.500\",\"4\":\"267.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"January\",\"2\":\"2011\",\"3\":\"174.500\",\"4\":\"267.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"February\",\"2\":\"2011\",\"3\":\"174.500\",\"4\":\"267.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"March\",\"2\":\"2011\",\"3\":\"174.500\",\"4\":\"267.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"April\",\"2\":\"2011\",\"3\":\"174.500\",\"4\":\"267.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"May\",\"2\":\"2011\",\"3\":\"174.500\",\"4\":\"267.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"June\",\"2\":\"2011\",\"3\":\"174.500\",\"4\":\"270.000\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"July\",\"2\":\"2011\",\"3\":\"174.500\",\"4\":\"270.000\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"August\",\"2\":\"2011\",\"3\":\"174.500\",\"4\":\"270.000\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"September\",\"2\":\"2011\",\"3\":\"174.500\",\"4\":\"270.000\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"October\",\"2\":\"2011\",\"3\":\"174.500\",\"4\":\"270.000\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"November\",\"2\":\"2011\",\"3\":\"174.500\",\"4\":\"270.000\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"December\",\"2\":\"2011\",\"3\":\"174.500\",\"4\":\"270.000\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"January\",\"2\":\"2012\",\"3\":\"174.500\",\"4\":\"267.500\",\"5\":\"185.500\",\"6\":\"285.500\"},{\"1\":\"February\",\"2\":\"2012\",\"3\":\"174.500\",\"4\":\"267.500\",\"5\":\"185.500\",\"6\":\"288.500\"},{\"1\":\"March\",\"2\":\"2012\",\"3\":\"174.500\",\"4\":\"267.500\",\"5\":\"185.500\",\"6\":\"288.500\"},{\"1\":\"April\",\"2\":\"2012\",\"3\":\"174.500\",\"4\":\"267.500\",\"5\":\"185.500\",\"6\":\"288.500\"},{\"1\":\"May\",\"2\":\"2012\",\"3\":\"173.250\",\"4\":\"267.500\",\"5\":\"185.500\",\"6\":\"288.500\"},{\"1\":\"June\",\"2\":\"2012\",\"3\":\"173.250\",\"4\":\"267.500\",\"5\":\"185.500\",\"6\":\"288.500\"},{\"1\":\"July\",\"2\":\"2012\",\"3\":\"173.250\",\"4\":\"267.500\",\"5\":\"185.500\",\"6\":\"288.500\"},{\"1\":\"August\",\"2\":\"2012\",\"3\":\"173.250\",\"4\":\"267.500\",\"5\":\"185.500\",\"6\":\"288.500\"},{\"1\":\"September\",\"2\":\"2012\",\"3\":\"173.250\",\"4\":\"267.500\",\"5\":\"185.500\",\"6\":\"288.500\"},{\"1\":\"October\",\"2\":\"2012\",\"3\":\"173.250\",\"4\":\"267.500\",\"5\":\"185.500\",\"6\":\"288.500\"},{\"1\":\"November\",\"2\":\"2012\",\"3\":\"178.000\",\"4\":\"267.500\",\"5\":\"188.130\",\"6\":\"290.000\"},{\"1\":\"December\",\"2\":\"2012\",\"3\":\"178.000\",\"4\":\"267.500\",\"5\":\"188.130\",\"6\":\"290.000\"},{\"1\":\"January\",\"2\":\"2013\",\"3\":\"178.000\",\"4\":\"267.500\",\"5\":\"188.130\",\"6\":\"290.000\"},{\"1\":\"February\",\"2\":\"2013\",\"3\":\"178.000\",\"4\":\"267.500\",\"5\":\"188.130\",\"6\":\"290.000\"},{\"1\":\"March\",\"2\":\"2013\",\"3\":\"178.000\",\"4\":\"267.500\",\"5\":\"188.130\",\"6\":\"290.000\"},{\"1\":\"April\",\"2\":\"2013\",\"3\":\"178.000\",\"4\":\"267.500\",\"5\":\"188.130\",\"6\":\"290.000\"},{\"1\":\"May\",\"2\":\"2013\",\"3\":\"178.000\",\"4\":\"267.500\",\"5\":\"188.130\",\"6\":\"290.000\"},{\"1\":\"June\",\"2\":\"2013\",\"3\":\"178.000\",\"4\":\"267.500\",\"5\":\"188.130\",\"6\":\"290.000\"},{\"1\":\"July\",\"2\":\"2013\",\"3\":\"178.000\",\"4\":\"267.500\",\"5\":\"188.130\",\"6\":\"290.000\"},{\"1\":\"August\",\"2\":\"2013\",\"3\":\"178.000\",\"4\":\"267.500\",\"5\":\"188.130\",\"6\":\"290.000\"},{\"1\":\"September\",\"2\":\"2013\",\"3\":\"178.000\",\"4\":\"267.500\",\"5\":\"188.130\",\"6\":\"290.000\"},{\"1\":\"October\",\"2\":\"2013\",\"3\":\"178.000\",\"4\":\"267.500\",\"5\":\"188.130\",\"6\":\"290.000\"},{\"1\":\"November\",\"2\":\"2013\",\"3\":\"178.000\",\"4\":\"267.500\",\"5\":\"188.130\",\"6\":\"290.000\"},{\"1\":\"December\",\"2\":\"2013\",\"3\":\"178.000\",\"4\":\"267.500\",\"5\":\"188.130\",\"6\":\"290.000\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nunique(eggs$month)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"January\"   \"February\"  \"March\"     \"April\"     \"May\"       \"June\"     \n [7] \"July\"      \"August\"    \"September\" \"October\"   \"November\"  \"December\" \n```\n:::\n\n```{.r .cell-code}\nunique(eggs$year)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013\n```\n:::\n:::\n\n\nThe dataset has information rearding the prices of eggs in various months across years 2004 to 2013. The eggs are of 2 types: large and extra large. The eggs come in two sizes: dozen and half a dozen.\n\n### Challenge: Describe the final dimensions\n\nDocument your work here.\n\n\n::: {.cell tbl-cap='Example'}\n\n```{.r .cell-code}\n#existing rows/cases\nnrow(eggs)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 120\n```\n:::\n\n```{.r .cell-code}\n#existing columns/cases\nncol(eggs)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 6\n```\n:::\n\n```{.r .cell-code}\n#expected rows/cases\nnrow(eggs) * (ncol(eggs)-2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 480\n```\n:::\n\n```{.r .cell-code}\n# expected columns \n2 + 2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 4\n```\n:::\n:::\n\nThe inital number of columns are 6 and there are 120 rows. As we are converting 4 columns into 2, the expected number of rows should be (120)*(4) i.e. 480. The number of columns should be reduced to 4.\n\n## Pivot the Data\n\nNow we will pivot the data, and compare our pivoted data dimensions to the dimensions calculated above as a \"sanity\" check.\n\n\n::: {.cell tbl-cap='Pivoted Example'}\n\n```{.r .cell-code}\neggs_pivoted<-eggs%>%\n  pivot_longer(cols=contains(\"dozen\"), \n               names_to = \"size_quantity\",\n               values_to = \"price\"\n  )\neggs_pivoted\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"month\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"year\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"size_quantity\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"price\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"January\",\"2\":\"2004\",\"3\":\"large_half_dozen\",\"4\":\"126.000\"},{\"1\":\"January\",\"2\":\"2004\",\"3\":\"large_dozen\",\"4\":\"230.000\"},{\"1\":\"January\",\"2\":\"2004\",\"3\":\"extra_large_half_dozen\",\"4\":\"132.000\"},{\"1\":\"January\",\"2\":\"2004\",\"3\":\"extra_large_dozen\",\"4\":\"230.000\"},{\"1\":\"February\",\"2\":\"2004\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"February\",\"2\":\"2004\",\"3\":\"large_dozen\",\"4\":\"226.250\"},{\"1\":\"February\",\"2\":\"2004\",\"3\":\"extra_large_half_dozen\",\"4\":\"134.500\"},{\"1\":\"February\",\"2\":\"2004\",\"3\":\"extra_large_dozen\",\"4\":\"230.000\"},{\"1\":\"March\",\"2\":\"2004\",\"3\":\"large_half_dozen\",\"4\":\"131.000\"},{\"1\":\"March\",\"2\":\"2004\",\"3\":\"large_dozen\",\"4\":\"225.000\"},{\"1\":\"March\",\"2\":\"2004\",\"3\":\"extra_large_half_dozen\",\"4\":\"137.000\"},{\"1\":\"March\",\"2\":\"2004\",\"3\":\"extra_large_dozen\",\"4\":\"230.000\"},{\"1\":\"April\",\"2\":\"2004\",\"3\":\"large_half_dozen\",\"4\":\"131.000\"},{\"1\":\"April\",\"2\":\"2004\",\"3\":\"large_dozen\",\"4\":\"225.000\"},{\"1\":\"April\",\"2\":\"2004\",\"3\":\"extra_large_half_dozen\",\"4\":\"137.000\"},{\"1\":\"April\",\"2\":\"2004\",\"3\":\"extra_large_dozen\",\"4\":\"234.500\"},{\"1\":\"May\",\"2\":\"2004\",\"3\":\"large_half_dozen\",\"4\":\"131.000\"},{\"1\":\"May\",\"2\":\"2004\",\"3\":\"large_dozen\",\"4\":\"225.000\"},{\"1\":\"May\",\"2\":\"2004\",\"3\":\"extra_large_half_dozen\",\"4\":\"137.000\"},{\"1\":\"May\",\"2\":\"2004\",\"3\":\"extra_large_dozen\",\"4\":\"236.000\"},{\"1\":\"June\",\"2\":\"2004\",\"3\":\"large_half_dozen\",\"4\":\"133.500\"},{\"1\":\"June\",\"2\":\"2004\",\"3\":\"large_dozen\",\"4\":\"231.375\"},{\"1\":\"June\",\"2\":\"2004\",\"3\":\"extra_large_half_dozen\",\"4\":\"137.000\"},{\"1\":\"June\",\"2\":\"2004\",\"3\":\"extra_large_dozen\",\"4\":\"241.000\"},{\"1\":\"July\",\"2\":\"2004\",\"3\":\"large_half_dozen\",\"4\":\"133.500\"},{\"1\":\"July\",\"2\":\"2004\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"July\",\"2\":\"2004\",\"3\":\"extra_large_half_dozen\",\"4\":\"137.000\"},{\"1\":\"July\",\"2\":\"2004\",\"3\":\"extra_large_dozen\",\"4\":\"241.000\"},{\"1\":\"August\",\"2\":\"2004\",\"3\":\"large_half_dozen\",\"4\":\"133.500\"},{\"1\":\"August\",\"2\":\"2004\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"August\",\"2\":\"2004\",\"3\":\"extra_large_half_dozen\",\"4\":\"137.000\"},{\"1\":\"August\",\"2\":\"2004\",\"3\":\"extra_large_dozen\",\"4\":\"241.000\"},{\"1\":\"September\",\"2\":\"2004\",\"3\":\"large_half_dozen\",\"4\":\"129.750\"},{\"1\":\"September\",\"2\":\"2004\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"September\",\"2\":\"2004\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.875\"},{\"1\":\"September\",\"2\":\"2004\",\"3\":\"extra_large_dozen\",\"4\":\"241.000\"},{\"1\":\"October\",\"2\":\"2004\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"October\",\"2\":\"2004\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"October\",\"2\":\"2004\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"October\",\"2\":\"2004\",\"3\":\"extra_large_dozen\",\"4\":\"241.000\"},{\"1\":\"November\",\"2\":\"2004\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"November\",\"2\":\"2004\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"November\",\"2\":\"2004\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"November\",\"2\":\"2004\",\"3\":\"extra_large_dozen\",\"4\":\"241.000\"},{\"1\":\"December\",\"2\":\"2004\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"December\",\"2\":\"2004\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"December\",\"2\":\"2004\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"December\",\"2\":\"2004\",\"3\":\"extra_large_dozen\",\"4\":\"241.000\"},{\"1\":\"January\",\"2\":\"2005\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"January\",\"2\":\"2005\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"January\",\"2\":\"2005\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"January\",\"2\":\"2005\",\"3\":\"extra_large_dozen\",\"4\":\"241.000\"},{\"1\":\"February\",\"2\":\"2005\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"February\",\"2\":\"2005\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"February\",\"2\":\"2005\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"February\",\"2\":\"2005\",\"3\":\"extra_large_dozen\",\"4\":\"241.000\"},{\"1\":\"March\",\"2\":\"2005\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"March\",\"2\":\"2005\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"March\",\"2\":\"2005\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"March\",\"2\":\"2005\",\"3\":\"extra_large_dozen\",\"4\":\"241.000\"},{\"1\":\"April\",\"2\":\"2005\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"April\",\"2\":\"2005\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"April\",\"2\":\"2005\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"April\",\"2\":\"2005\",\"3\":\"extra_large_dozen\",\"4\":\"241.000\"},{\"1\":\"May\",\"2\":\"2005\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"May\",\"2\":\"2005\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"May\",\"2\":\"2005\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"May\",\"2\":\"2005\",\"3\":\"extra_large_dozen\",\"4\":\"241.000\"},{\"1\":\"June\",\"2\":\"2005\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"June\",\"2\":\"2005\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"June\",\"2\":\"2005\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"June\",\"2\":\"2005\",\"3\":\"extra_large_dozen\",\"4\":\"241.000\"},{\"1\":\"July\",\"2\":\"2005\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"July\",\"2\":\"2005\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"July\",\"2\":\"2005\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"July\",\"2\":\"2005\",\"3\":\"extra_large_dozen\",\"4\":\"241.000\"},{\"1\":\"August\",\"2\":\"2005\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"August\",\"2\":\"2005\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"August\",\"2\":\"2005\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"August\",\"2\":\"2005\",\"3\":\"extra_large_dozen\",\"4\":\"241.000\"},{\"1\":\"September\",\"2\":\"2005\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"September\",\"2\":\"2005\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"September\",\"2\":\"2005\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"September\",\"2\":\"2005\",\"3\":\"extra_large_dozen\",\"4\":\"241.000\"},{\"1\":\"October\",\"2\":\"2005\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"October\",\"2\":\"2005\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"October\",\"2\":\"2005\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"October\",\"2\":\"2005\",\"3\":\"extra_large_dozen\",\"4\":\"241.000\"},{\"1\":\"November\",\"2\":\"2005\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"November\",\"2\":\"2005\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"November\",\"2\":\"2005\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"November\",\"2\":\"2005\",\"3\":\"extra_large_dozen\",\"4\":\"241.000\"},{\"1\":\"December\",\"2\":\"2005\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"December\",\"2\":\"2005\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"December\",\"2\":\"2005\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"December\",\"2\":\"2005\",\"3\":\"extra_large_dozen\",\"4\":\"241.000\"},{\"1\":\"January\",\"2\":\"2006\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"January\",\"2\":\"2006\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"January\",\"2\":\"2006\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"January\",\"2\":\"2006\",\"3\":\"extra_large_dozen\",\"4\":\"241.000\"},{\"1\":\"February\",\"2\":\"2006\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"February\",\"2\":\"2006\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"February\",\"2\":\"2006\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"February\",\"2\":\"2006\",\"3\":\"extra_large_dozen\",\"4\":\"241.000\"},{\"1\":\"March\",\"2\":\"2006\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"March\",\"2\":\"2006\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"March\",\"2\":\"2006\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"March\",\"2\":\"2006\",\"3\":\"extra_large_dozen\",\"4\":\"241.375\"},{\"1\":\"April\",\"2\":\"2006\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"April\",\"2\":\"2006\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"April\",\"2\":\"2006\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"April\",\"2\":\"2006\",\"3\":\"extra_large_dozen\",\"4\":\"241.500\"},{\"1\":\"May\",\"2\":\"2006\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"May\",\"2\":\"2006\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"May\",\"2\":\"2006\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"May\",\"2\":\"2006\",\"3\":\"extra_large_dozen\",\"4\":\"241.500\"},{\"1\":\"June\",\"2\":\"2006\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"June\",\"2\":\"2006\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"June\",\"2\":\"2006\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"June\",\"2\":\"2006\",\"3\":\"extra_large_dozen\",\"4\":\"241.500\"},{\"1\":\"July\",\"2\":\"2006\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"July\",\"2\":\"2006\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"July\",\"2\":\"2006\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"July\",\"2\":\"2006\",\"3\":\"extra_large_dozen\",\"4\":\"241.500\"},{\"1\":\"August\",\"2\":\"2006\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"August\",\"2\":\"2006\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"August\",\"2\":\"2006\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"August\",\"2\":\"2006\",\"3\":\"extra_large_dozen\",\"4\":\"241.500\"},{\"1\":\"September\",\"2\":\"2006\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"September\",\"2\":\"2006\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"September\",\"2\":\"2006\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"September\",\"2\":\"2006\",\"3\":\"extra_large_dozen\",\"4\":\"241.500\"},{\"1\":\"October\",\"2\":\"2006\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"October\",\"2\":\"2006\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"October\",\"2\":\"2006\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"October\",\"2\":\"2006\",\"3\":\"extra_large_dozen\",\"4\":\"241.500\"},{\"1\":\"November\",\"2\":\"2006\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"November\",\"2\":\"2006\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"November\",\"2\":\"2006\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"November\",\"2\":\"2006\",\"3\":\"extra_large_dozen\",\"4\":\"241.500\"},{\"1\":\"December\",\"2\":\"2006\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"December\",\"2\":\"2006\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"December\",\"2\":\"2006\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"December\",\"2\":\"2006\",\"3\":\"extra_large_dozen\",\"4\":\"241.500\"},{\"1\":\"January\",\"2\":\"2007\",\"3\":\"large_half_dozen\",\"4\":\"128.500\"},{\"1\":\"January\",\"2\":\"2007\",\"3\":\"large_dozen\",\"4\":\"233.500\"},{\"1\":\"January\",\"2\":\"2007\",\"3\":\"extra_large_half_dozen\",\"4\":\"135.500\"},{\"1\":\"January\",\"2\":\"2007\",\"3\":\"extra_large_dozen\",\"4\":\"241.500\"},{\"1\":\"February\",\"2\":\"2007\",\"3\":\"large_half_dozen\",\"4\":\"131.125\"},{\"1\":\"February\",\"2\":\"2007\",\"3\":\"large_dozen\",\"4\":\"236.125\"},{\"1\":\"February\",\"2\":\"2007\",\"3\":\"extra_large_half_dozen\",\"4\":\"138.125\"},{\"1\":\"February\",\"2\":\"2007\",\"3\":\"extra_large_dozen\",\"4\":\"244.125\"},{\"1\":\"March\",\"2\":\"2007\",\"3\":\"large_half_dozen\",\"4\":\"132.000\"},{\"1\":\"March\",\"2\":\"2007\",\"3\":\"large_dozen\",\"4\":\"237.000\"},{\"1\":\"March\",\"2\":\"2007\",\"3\":\"extra_large_half_dozen\",\"4\":\"139.000\"},{\"1\":\"March\",\"2\":\"2007\",\"3\":\"extra_large_dozen\",\"4\":\"245.000\"},{\"1\":\"April\",\"2\":\"2007\",\"3\":\"large_half_dozen\",\"4\":\"132.000\"},{\"1\":\"April\",\"2\":\"2007\",\"3\":\"large_dozen\",\"4\":\"237.000\"},{\"1\":\"April\",\"2\":\"2007\",\"3\":\"extra_large_half_dozen\",\"4\":\"139.000\"},{\"1\":\"April\",\"2\":\"2007\",\"3\":\"extra_large_dozen\",\"4\":\"245.000\"},{\"1\":\"May\",\"2\":\"2007\",\"3\":\"large_half_dozen\",\"4\":\"132.000\"},{\"1\":\"May\",\"2\":\"2007\",\"3\":\"large_dozen\",\"4\":\"237.000\"},{\"1\":\"May\",\"2\":\"2007\",\"3\":\"extra_large_half_dozen\",\"4\":\"139.000\"},{\"1\":\"May\",\"2\":\"2007\",\"3\":\"extra_large_dozen\",\"4\":\"245.000\"},{\"1\":\"June\",\"2\":\"2007\",\"3\":\"large_half_dozen\",\"4\":\"132.000\"},{\"1\":\"June\",\"2\":\"2007\",\"3\":\"large_dozen\",\"4\":\"237.000\"},{\"1\":\"June\",\"2\":\"2007\",\"3\":\"extra_large_half_dozen\",\"4\":\"139.000\"},{\"1\":\"June\",\"2\":\"2007\",\"3\":\"extra_large_dozen\",\"4\":\"245.000\"},{\"1\":\"July\",\"2\":\"2007\",\"3\":\"large_half_dozen\",\"4\":\"132.000\"},{\"1\":\"July\",\"2\":\"2007\",\"3\":\"large_dozen\",\"4\":\"237.000\"},{\"1\":\"July\",\"2\":\"2007\",\"3\":\"extra_large_half_dozen\",\"4\":\"139.000\"},{\"1\":\"July\",\"2\":\"2007\",\"3\":\"extra_large_dozen\",\"4\":\"245.000\"},{\"1\":\"August\",\"2\":\"2007\",\"3\":\"large_half_dozen\",\"4\":\"132.000\"},{\"1\":\"August\",\"2\":\"2007\",\"3\":\"large_dozen\",\"4\":\"237.000\"},{\"1\":\"August\",\"2\":\"2007\",\"3\":\"extra_large_half_dozen\",\"4\":\"139.000\"},{\"1\":\"August\",\"2\":\"2007\",\"3\":\"extra_large_dozen\",\"4\":\"245.000\"},{\"1\":\"September\",\"2\":\"2007\",\"3\":\"large_half_dozen\",\"4\":\"132.000\"},{\"1\":\"September\",\"2\":\"2007\",\"3\":\"large_dozen\",\"4\":\"237.000\"},{\"1\":\"September\",\"2\":\"2007\",\"3\":\"extra_large_half_dozen\",\"4\":\"139.000\"},{\"1\":\"September\",\"2\":\"2007\",\"3\":\"extra_large_dozen\",\"4\":\"245.000\"},{\"1\":\"October\",\"2\":\"2007\",\"3\":\"large_half_dozen\",\"4\":\"132.000\"},{\"1\":\"October\",\"2\":\"2007\",\"3\":\"large_dozen\",\"4\":\"237.000\"},{\"1\":\"October\",\"2\":\"2007\",\"3\":\"extra_large_half_dozen\",\"4\":\"139.000\"},{\"1\":\"October\",\"2\":\"2007\",\"3\":\"extra_large_dozen\",\"4\":\"245.000\"},{\"1\":\"November\",\"2\":\"2007\",\"3\":\"large_half_dozen\",\"4\":\"132.000\"},{\"1\":\"November\",\"2\":\"2007\",\"3\":\"large_dozen\",\"4\":\"237.000\"},{\"1\":\"November\",\"2\":\"2007\",\"3\":\"extra_large_half_dozen\",\"4\":\"139.000\"},{\"1\":\"November\",\"2\":\"2007\",\"3\":\"extra_large_dozen\",\"4\":\"245.000\"},{\"1\":\"December\",\"2\":\"2007\",\"3\":\"large_half_dozen\",\"4\":\"132.000\"},{\"1\":\"December\",\"2\":\"2007\",\"3\":\"large_dozen\",\"4\":\"237.000\"},{\"1\":\"December\",\"2\":\"2007\",\"3\":\"extra_large_half_dozen\",\"4\":\"139.000\"},{\"1\":\"December\",\"2\":\"2007\",\"3\":\"extra_large_dozen\",\"4\":\"245.000\"},{\"1\":\"January\",\"2\":\"2008\",\"3\":\"large_half_dozen\",\"4\":\"132.000\"},{\"1\":\"January\",\"2\":\"2008\",\"3\":\"large_dozen\",\"4\":\"237.000\"},{\"1\":\"January\",\"2\":\"2008\",\"3\":\"extra_large_half_dozen\",\"4\":\"139.000\"},{\"1\":\"January\",\"2\":\"2008\",\"3\":\"extra_large_dozen\",\"4\":\"245.000\"},{\"1\":\"February\",\"2\":\"2008\",\"3\":\"large_half_dozen\",\"4\":\"132.000\"},{\"1\":\"February\",\"2\":\"2008\",\"3\":\"large_dozen\",\"4\":\"237.000\"},{\"1\":\"February\",\"2\":\"2008\",\"3\":\"extra_large_half_dozen\",\"4\":\"139.000\"},{\"1\":\"February\",\"2\":\"2008\",\"3\":\"extra_large_dozen\",\"4\":\"245.000\"},{\"1\":\"March\",\"2\":\"2008\",\"3\":\"large_half_dozen\",\"4\":\"132.000\"},{\"1\":\"March\",\"2\":\"2008\",\"3\":\"large_dozen\",\"4\":\"237.000\"},{\"1\":\"March\",\"2\":\"2008\",\"3\":\"extra_large_half_dozen\",\"4\":\"139.000\"},{\"1\":\"March\",\"2\":\"2008\",\"3\":\"extra_large_dozen\",\"4\":\"245.000\"},{\"1\":\"April\",\"2\":\"2008\",\"3\":\"large_half_dozen\",\"4\":\"132.000\"},{\"1\":\"April\",\"2\":\"2008\",\"3\":\"large_dozen\",\"4\":\"237.000\"},{\"1\":\"April\",\"2\":\"2008\",\"3\":\"extra_large_half_dozen\",\"4\":\"139.000\"},{\"1\":\"April\",\"2\":\"2008\",\"3\":\"extra_large_dozen\",\"4\":\"245.000\"},{\"1\":\"May\",\"2\":\"2008\",\"3\":\"large_half_dozen\",\"4\":\"132.000\"},{\"1\":\"May\",\"2\":\"2008\",\"3\":\"large_dozen\",\"4\":\"237.000\"},{\"1\":\"May\",\"2\":\"2008\",\"3\":\"extra_large_half_dozen\",\"4\":\"139.000\"},{\"1\":\"May\",\"2\":\"2008\",\"3\":\"extra_large_dozen\",\"4\":\"245.000\"},{\"1\":\"June\",\"2\":\"2008\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"June\",\"2\":\"2008\",\"3\":\"large_dozen\",\"4\":\"277.500\"},{\"1\":\"June\",\"2\":\"2008\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"June\",\"2\":\"2008\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"July\",\"2\":\"2008\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"July\",\"2\":\"2008\",\"3\":\"large_dozen\",\"4\":\"277.500\"},{\"1\":\"July\",\"2\":\"2008\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"July\",\"2\":\"2008\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"August\",\"2\":\"2008\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"August\",\"2\":\"2008\",\"3\":\"large_dozen\",\"4\":\"277.500\"},{\"1\":\"August\",\"2\":\"2008\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"August\",\"2\":\"2008\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"September\",\"2\":\"2008\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"September\",\"2\":\"2008\",\"3\":\"large_dozen\",\"4\":\"277.500\"},{\"1\":\"September\",\"2\":\"2008\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"September\",\"2\":\"2008\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"October\",\"2\":\"2008\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"October\",\"2\":\"2008\",\"3\":\"large_dozen\",\"4\":\"277.500\"},{\"1\":\"October\",\"2\":\"2008\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"October\",\"2\":\"2008\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"November\",\"2\":\"2008\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"November\",\"2\":\"2008\",\"3\":\"large_dozen\",\"4\":\"277.500\"},{\"1\":\"November\",\"2\":\"2008\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"November\",\"2\":\"2008\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"December\",\"2\":\"2008\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"December\",\"2\":\"2008\",\"3\":\"large_dozen\",\"4\":\"277.500\"},{\"1\":\"December\",\"2\":\"2008\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"December\",\"2\":\"2008\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"January\",\"2\":\"2009\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"January\",\"2\":\"2009\",\"3\":\"large_dozen\",\"4\":\"277.500\"},{\"1\":\"January\",\"2\":\"2009\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"January\",\"2\":\"2009\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"February\",\"2\":\"2009\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"February\",\"2\":\"2009\",\"3\":\"large_dozen\",\"4\":\"277.500\"},{\"1\":\"February\",\"2\":\"2009\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"February\",\"2\":\"2009\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"March\",\"2\":\"2009\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"March\",\"2\":\"2009\",\"3\":\"large_dozen\",\"4\":\"277.500\"},{\"1\":\"March\",\"2\":\"2009\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"March\",\"2\":\"2009\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"April\",\"2\":\"2009\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"April\",\"2\":\"2009\",\"3\":\"large_dozen\",\"4\":\"277.500\"},{\"1\":\"April\",\"2\":\"2009\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"April\",\"2\":\"2009\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"May\",\"2\":\"2009\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"May\",\"2\":\"2009\",\"3\":\"large_dozen\",\"4\":\"277.500\"},{\"1\":\"May\",\"2\":\"2009\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"May\",\"2\":\"2009\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"June\",\"2\":\"2009\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"June\",\"2\":\"2009\",\"3\":\"large_dozen\",\"4\":\"277.500\"},{\"1\":\"June\",\"2\":\"2009\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"June\",\"2\":\"2009\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"July\",\"2\":\"2009\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"July\",\"2\":\"2009\",\"3\":\"large_dozen\",\"4\":\"277.500\"},{\"1\":\"July\",\"2\":\"2009\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"July\",\"2\":\"2009\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"August\",\"2\":\"2009\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"August\",\"2\":\"2009\",\"3\":\"large_dozen\",\"4\":\"271.500\"},{\"1\":\"August\",\"2\":\"2009\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"August\",\"2\":\"2009\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"September\",\"2\":\"2009\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"September\",\"2\":\"2009\",\"3\":\"large_dozen\",\"4\":\"271.500\"},{\"1\":\"September\",\"2\":\"2009\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"September\",\"2\":\"2009\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"October\",\"2\":\"2009\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"October\",\"2\":\"2009\",\"3\":\"large_dozen\",\"4\":\"271.500\"},{\"1\":\"October\",\"2\":\"2009\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"October\",\"2\":\"2009\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"November\",\"2\":\"2009\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"November\",\"2\":\"2009\",\"3\":\"large_dozen\",\"4\":\"271.500\"},{\"1\":\"November\",\"2\":\"2009\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"November\",\"2\":\"2009\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"December\",\"2\":\"2009\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"December\",\"2\":\"2009\",\"3\":\"large_dozen\",\"4\":\"271.500\"},{\"1\":\"December\",\"2\":\"2009\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"December\",\"2\":\"2009\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"January\",\"2\":\"2010\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"January\",\"2\":\"2010\",\"3\":\"large_dozen\",\"4\":\"271.500\"},{\"1\":\"January\",\"2\":\"2010\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"January\",\"2\":\"2010\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"February\",\"2\":\"2010\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"February\",\"2\":\"2010\",\"3\":\"large_dozen\",\"4\":\"271.500\"},{\"1\":\"February\",\"2\":\"2010\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"February\",\"2\":\"2010\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"March\",\"2\":\"2010\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"March\",\"2\":\"2010\",\"3\":\"large_dozen\",\"4\":\"268.000\"},{\"1\":\"March\",\"2\":\"2010\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"March\",\"2\":\"2010\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"April\",\"2\":\"2010\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"April\",\"2\":\"2010\",\"3\":\"large_dozen\",\"4\":\"268.000\"},{\"1\":\"April\",\"2\":\"2010\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"April\",\"2\":\"2010\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"May\",\"2\":\"2010\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"May\",\"2\":\"2010\",\"3\":\"large_dozen\",\"4\":\"268.000\"},{\"1\":\"May\",\"2\":\"2010\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"May\",\"2\":\"2010\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"June\",\"2\":\"2010\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"June\",\"2\":\"2010\",\"3\":\"large_dozen\",\"4\":\"268.000\"},{\"1\":\"June\",\"2\":\"2010\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"June\",\"2\":\"2010\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"July\",\"2\":\"2010\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"July\",\"2\":\"2010\",\"3\":\"large_dozen\",\"4\":\"268.000\"},{\"1\":\"July\",\"2\":\"2010\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"July\",\"2\":\"2010\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"August\",\"2\":\"2010\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"August\",\"2\":\"2010\",\"3\":\"large_dozen\",\"4\":\"268.000\"},{\"1\":\"August\",\"2\":\"2010\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"August\",\"2\":\"2010\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"September\",\"2\":\"2010\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"September\",\"2\":\"2010\",\"3\":\"large_dozen\",\"4\":\"268.000\"},{\"1\":\"September\",\"2\":\"2010\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"September\",\"2\":\"2010\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"October\",\"2\":\"2010\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"October\",\"2\":\"2010\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"October\",\"2\":\"2010\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"October\",\"2\":\"2010\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"November\",\"2\":\"2010\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"November\",\"2\":\"2010\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"November\",\"2\":\"2010\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"November\",\"2\":\"2010\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"December\",\"2\":\"2010\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"December\",\"2\":\"2010\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"December\",\"2\":\"2010\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"December\",\"2\":\"2010\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"January\",\"2\":\"2011\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"January\",\"2\":\"2011\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"January\",\"2\":\"2011\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"January\",\"2\":\"2011\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"February\",\"2\":\"2011\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"February\",\"2\":\"2011\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"February\",\"2\":\"2011\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"February\",\"2\":\"2011\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"March\",\"2\":\"2011\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"March\",\"2\":\"2011\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"March\",\"2\":\"2011\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"March\",\"2\":\"2011\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"April\",\"2\":\"2011\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"April\",\"2\":\"2011\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"April\",\"2\":\"2011\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"April\",\"2\":\"2011\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"May\",\"2\":\"2011\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"May\",\"2\":\"2011\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"May\",\"2\":\"2011\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"May\",\"2\":\"2011\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"June\",\"2\":\"2011\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"June\",\"2\":\"2011\",\"3\":\"large_dozen\",\"4\":\"270.000\"},{\"1\":\"June\",\"2\":\"2011\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"June\",\"2\":\"2011\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"July\",\"2\":\"2011\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"July\",\"2\":\"2011\",\"3\":\"large_dozen\",\"4\":\"270.000\"},{\"1\":\"July\",\"2\":\"2011\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"July\",\"2\":\"2011\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"August\",\"2\":\"2011\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"August\",\"2\":\"2011\",\"3\":\"large_dozen\",\"4\":\"270.000\"},{\"1\":\"August\",\"2\":\"2011\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"August\",\"2\":\"2011\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"September\",\"2\":\"2011\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"September\",\"2\":\"2011\",\"3\":\"large_dozen\",\"4\":\"270.000\"},{\"1\":\"September\",\"2\":\"2011\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"September\",\"2\":\"2011\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"October\",\"2\":\"2011\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"October\",\"2\":\"2011\",\"3\":\"large_dozen\",\"4\":\"270.000\"},{\"1\":\"October\",\"2\":\"2011\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"October\",\"2\":\"2011\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"November\",\"2\":\"2011\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"November\",\"2\":\"2011\",\"3\":\"large_dozen\",\"4\":\"270.000\"},{\"1\":\"November\",\"2\":\"2011\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"November\",\"2\":\"2011\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"December\",\"2\":\"2011\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"December\",\"2\":\"2011\",\"3\":\"large_dozen\",\"4\":\"270.000\"},{\"1\":\"December\",\"2\":\"2011\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"December\",\"2\":\"2011\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"January\",\"2\":\"2012\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"January\",\"2\":\"2012\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"January\",\"2\":\"2012\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"January\",\"2\":\"2012\",\"3\":\"extra_large_dozen\",\"4\":\"285.500\"},{\"1\":\"February\",\"2\":\"2012\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"February\",\"2\":\"2012\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"February\",\"2\":\"2012\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"February\",\"2\":\"2012\",\"3\":\"extra_large_dozen\",\"4\":\"288.500\"},{\"1\":\"March\",\"2\":\"2012\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"March\",\"2\":\"2012\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"March\",\"2\":\"2012\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"March\",\"2\":\"2012\",\"3\":\"extra_large_dozen\",\"4\":\"288.500\"},{\"1\":\"April\",\"2\":\"2012\",\"3\":\"large_half_dozen\",\"4\":\"174.500\"},{\"1\":\"April\",\"2\":\"2012\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"April\",\"2\":\"2012\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"April\",\"2\":\"2012\",\"3\":\"extra_large_dozen\",\"4\":\"288.500\"},{\"1\":\"May\",\"2\":\"2012\",\"3\":\"large_half_dozen\",\"4\":\"173.250\"},{\"1\":\"May\",\"2\":\"2012\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"May\",\"2\":\"2012\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"May\",\"2\":\"2012\",\"3\":\"extra_large_dozen\",\"4\":\"288.500\"},{\"1\":\"June\",\"2\":\"2012\",\"3\":\"large_half_dozen\",\"4\":\"173.250\"},{\"1\":\"June\",\"2\":\"2012\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"June\",\"2\":\"2012\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"June\",\"2\":\"2012\",\"3\":\"extra_large_dozen\",\"4\":\"288.500\"},{\"1\":\"July\",\"2\":\"2012\",\"3\":\"large_half_dozen\",\"4\":\"173.250\"},{\"1\":\"July\",\"2\":\"2012\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"July\",\"2\":\"2012\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"July\",\"2\":\"2012\",\"3\":\"extra_large_dozen\",\"4\":\"288.500\"},{\"1\":\"August\",\"2\":\"2012\",\"3\":\"large_half_dozen\",\"4\":\"173.250\"},{\"1\":\"August\",\"2\":\"2012\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"August\",\"2\":\"2012\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"August\",\"2\":\"2012\",\"3\":\"extra_large_dozen\",\"4\":\"288.500\"},{\"1\":\"September\",\"2\":\"2012\",\"3\":\"large_half_dozen\",\"4\":\"173.250\"},{\"1\":\"September\",\"2\":\"2012\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"September\",\"2\":\"2012\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"September\",\"2\":\"2012\",\"3\":\"extra_large_dozen\",\"4\":\"288.500\"},{\"1\":\"October\",\"2\":\"2012\",\"3\":\"large_half_dozen\",\"4\":\"173.250\"},{\"1\":\"October\",\"2\":\"2012\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"October\",\"2\":\"2012\",\"3\":\"extra_large_half_dozen\",\"4\":\"185.500\"},{\"1\":\"October\",\"2\":\"2012\",\"3\":\"extra_large_dozen\",\"4\":\"288.500\"},{\"1\":\"November\",\"2\":\"2012\",\"3\":\"large_half_dozen\",\"4\":\"178.000\"},{\"1\":\"November\",\"2\":\"2012\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"November\",\"2\":\"2012\",\"3\":\"extra_large_half_dozen\",\"4\":\"188.130\"},{\"1\":\"November\",\"2\":\"2012\",\"3\":\"extra_large_dozen\",\"4\":\"290.000\"},{\"1\":\"December\",\"2\":\"2012\",\"3\":\"large_half_dozen\",\"4\":\"178.000\"},{\"1\":\"December\",\"2\":\"2012\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"December\",\"2\":\"2012\",\"3\":\"extra_large_half_dozen\",\"4\":\"188.130\"},{\"1\":\"December\",\"2\":\"2012\",\"3\":\"extra_large_dozen\",\"4\":\"290.000\"},{\"1\":\"January\",\"2\":\"2013\",\"3\":\"large_half_dozen\",\"4\":\"178.000\"},{\"1\":\"January\",\"2\":\"2013\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"January\",\"2\":\"2013\",\"3\":\"extra_large_half_dozen\",\"4\":\"188.130\"},{\"1\":\"January\",\"2\":\"2013\",\"3\":\"extra_large_dozen\",\"4\":\"290.000\"},{\"1\":\"February\",\"2\":\"2013\",\"3\":\"large_half_dozen\",\"4\":\"178.000\"},{\"1\":\"February\",\"2\":\"2013\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"February\",\"2\":\"2013\",\"3\":\"extra_large_half_dozen\",\"4\":\"188.130\"},{\"1\":\"February\",\"2\":\"2013\",\"3\":\"extra_large_dozen\",\"4\":\"290.000\"},{\"1\":\"March\",\"2\":\"2013\",\"3\":\"large_half_dozen\",\"4\":\"178.000\"},{\"1\":\"March\",\"2\":\"2013\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"March\",\"2\":\"2013\",\"3\":\"extra_large_half_dozen\",\"4\":\"188.130\"},{\"1\":\"March\",\"2\":\"2013\",\"3\":\"extra_large_dozen\",\"4\":\"290.000\"},{\"1\":\"April\",\"2\":\"2013\",\"3\":\"large_half_dozen\",\"4\":\"178.000\"},{\"1\":\"April\",\"2\":\"2013\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"April\",\"2\":\"2013\",\"3\":\"extra_large_half_dozen\",\"4\":\"188.130\"},{\"1\":\"April\",\"2\":\"2013\",\"3\":\"extra_large_dozen\",\"4\":\"290.000\"},{\"1\":\"May\",\"2\":\"2013\",\"3\":\"large_half_dozen\",\"4\":\"178.000\"},{\"1\":\"May\",\"2\":\"2013\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"May\",\"2\":\"2013\",\"3\":\"extra_large_half_dozen\",\"4\":\"188.130\"},{\"1\":\"May\",\"2\":\"2013\",\"3\":\"extra_large_dozen\",\"4\":\"290.000\"},{\"1\":\"June\",\"2\":\"2013\",\"3\":\"large_half_dozen\",\"4\":\"178.000\"},{\"1\":\"June\",\"2\":\"2013\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"June\",\"2\":\"2013\",\"3\":\"extra_large_half_dozen\",\"4\":\"188.130\"},{\"1\":\"June\",\"2\":\"2013\",\"3\":\"extra_large_dozen\",\"4\":\"290.000\"},{\"1\":\"July\",\"2\":\"2013\",\"3\":\"large_half_dozen\",\"4\":\"178.000\"},{\"1\":\"July\",\"2\":\"2013\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"July\",\"2\":\"2013\",\"3\":\"extra_large_half_dozen\",\"4\":\"188.130\"},{\"1\":\"July\",\"2\":\"2013\",\"3\":\"extra_large_dozen\",\"4\":\"290.000\"},{\"1\":\"August\",\"2\":\"2013\",\"3\":\"large_half_dozen\",\"4\":\"178.000\"},{\"1\":\"August\",\"2\":\"2013\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"August\",\"2\":\"2013\",\"3\":\"extra_large_half_dozen\",\"4\":\"188.130\"},{\"1\":\"August\",\"2\":\"2013\",\"3\":\"extra_large_dozen\",\"4\":\"290.000\"},{\"1\":\"September\",\"2\":\"2013\",\"3\":\"large_half_dozen\",\"4\":\"178.000\"},{\"1\":\"September\",\"2\":\"2013\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"September\",\"2\":\"2013\",\"3\":\"extra_large_half_dozen\",\"4\":\"188.130\"},{\"1\":\"September\",\"2\":\"2013\",\"3\":\"extra_large_dozen\",\"4\":\"290.000\"},{\"1\":\"October\",\"2\":\"2013\",\"3\":\"large_half_dozen\",\"4\":\"178.000\"},{\"1\":\"October\",\"2\":\"2013\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"October\",\"2\":\"2013\",\"3\":\"extra_large_half_dozen\",\"4\":\"188.130\"},{\"1\":\"October\",\"2\":\"2013\",\"3\":\"extra_large_dozen\",\"4\":\"290.000\"},{\"1\":\"November\",\"2\":\"2013\",\"3\":\"large_half_dozen\",\"4\":\"178.000\"},{\"1\":\"November\",\"2\":\"2013\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"November\",\"2\":\"2013\",\"3\":\"extra_large_half_dozen\",\"4\":\"188.130\"},{\"1\":\"November\",\"2\":\"2013\",\"3\":\"extra_large_dozen\",\"4\":\"290.000\"},{\"1\":\"December\",\"2\":\"2013\",\"3\":\"large_half_dozen\",\"4\":\"178.000\"},{\"1\":\"December\",\"2\":\"2013\",\"3\":\"large_dozen\",\"4\":\"267.500\"},{\"1\":\"December\",\"2\":\"2013\",\"3\":\"extra_large_half_dozen\",\"4\":\"188.130\"},{\"1\":\"December\",\"2\":\"2013\",\"3\":\"extra_large_dozen\",\"4\":\"290.000\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nAs we can see that we have 480 rows and 4 columns as predicted before. The data seems tidier. However we see that information in the `size_quantity` column can be split into two: `size` and `quantity`. We perform the same below. We can see that values in this variable follow the pattern *size*_*quantity*. So we first replace this underscore with a space character. And then we use this space to split the string. \n\n\n::: {.cell}\n\n```{.r .cell-code}\neggs_pivoted$size_quantity<-sub(\"large_\", \"large \", eggs_pivoted$size_quantity)\n\neggs_pivoted_separated <- separate(eggs_pivoted, size_quantity, c(\"size\", \"quantity\"), \" \")\n\neggs_pivoted_separated\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"month\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"year\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"size\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"quantity\"],\"name\":[4],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"price\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"January\",\"2\":\"2004\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"126.000\"},{\"1\":\"January\",\"2\":\"2004\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"230.000\"},{\"1\":\"January\",\"2\":\"2004\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"132.000\"},{\"1\":\"January\",\"2\":\"2004\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"230.000\"},{\"1\":\"February\",\"2\":\"2004\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"128.500\"},{\"1\":\"February\",\"2\":\"2004\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"226.250\"},{\"1\":\"February\",\"2\":\"2004\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"134.500\"},{\"1\":\"February\",\"2\":\"2004\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"230.000\"},{\"1\":\"March\",\"2\":\"2004\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"131.000\"},{\"1\":\"March\",\"2\":\"2004\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"225.000\"},{\"1\":\"March\",\"2\":\"2004\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"137.000\"},{\"1\":\"March\",\"2\":\"2004\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"230.000\"},{\"1\":\"April\",\"2\":\"2004\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"131.000\"},{\"1\":\"April\",\"2\":\"2004\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"225.000\"},{\"1\":\"April\",\"2\":\"2004\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"137.000\"},{\"1\":\"April\",\"2\":\"2004\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"234.500\"},{\"1\":\"May\",\"2\":\"2004\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"131.000\"},{\"1\":\"May\",\"2\":\"2004\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"225.000\"},{\"1\":\"May\",\"2\":\"2004\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"137.000\"},{\"1\":\"May\",\"2\":\"2004\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"236.000\"},{\"1\":\"June\",\"2\":\"2004\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"133.500\"},{\"1\":\"June\",\"2\":\"2004\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"231.375\"},{\"1\":\"June\",\"2\":\"2004\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"137.000\"},{\"1\":\"June\",\"2\":\"2004\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"241.000\"},{\"1\":\"July\",\"2\":\"2004\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"133.500\"},{\"1\":\"July\",\"2\":\"2004\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"233.500\"},{\"1\":\"July\",\"2\":\"2004\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"137.000\"},{\"1\":\"July\",\"2\":\"2004\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"241.000\"},{\"1\":\"August\",\"2\":\"2004\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"133.500\"},{\"1\":\"August\",\"2\":\"2004\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"233.500\"},{\"1\":\"August\",\"2\":\"2004\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"137.000\"},{\"1\":\"August\",\"2\":\"2004\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"241.000\"},{\"1\":\"September\",\"2\":\"2004\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"129.750\"},{\"1\":\"September\",\"2\":\"2004\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"233.500\"},{\"1\":\"September\",\"2\":\"2004\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"135.875\"},{\"1\":\"September\",\"2\":\"2004\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"241.000\"},{\"1\":\"October\",\"2\":\"2004\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"128.500\"},{\"1\":\"October\",\"2\":\"2004\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"233.500\"},{\"1\":\"October\",\"2\":\"2004\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"135.500\"},{\"1\":\"October\",\"2\":\"2004\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"241.000\"},{\"1\":\"November\",\"2\":\"2004\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"128.500\"},{\"1\":\"November\",\"2\":\"2004\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"233.500\"},{\"1\":\"November\",\"2\":\"2004\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"135.500\"},{\"1\":\"November\",\"2\":\"2004\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"241.000\"},{\"1\":\"December\",\"2\":\"2004\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"128.500\"},{\"1\":\"December\",\"2\":\"2004\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"233.500\"},{\"1\":\"December\",\"2\":\"2004\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"135.500\"},{\"1\":\"December\",\"2\":\"2004\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"241.000\"},{\"1\":\"January\",\"2\":\"2005\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"128.500\"},{\"1\":\"January\",\"2\":\"2005\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"233.500\"},{\"1\":\"January\",\"2\":\"2005\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"135.500\"},{\"1\":\"January\",\"2\":\"2005\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"241.000\"},{\"1\":\"February\",\"2\":\"2005\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"128.500\"},{\"1\":\"February\",\"2\":\"2005\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"233.500\"},{\"1\":\"February\",\"2\":\"2005\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"135.500\"},{\"1\":\"February\",\"2\":\"2005\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"241.000\"},{\"1\":\"March\",\"2\":\"2005\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"128.500\"},{\"1\":\"March\",\"2\":\"2005\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"233.500\"},{\"1\":\"March\",\"2\":\"2005\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"135.500\"},{\"1\":\"March\",\"2\":\"2005\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"241.000\"},{\"1\":\"April\",\"2\":\"2005\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"128.500\"},{\"1\":\"April\",\"2\":\"2005\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"233.500\"},{\"1\":\"April\",\"2\":\"2005\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"135.500\"},{\"1\":\"April\",\"2\":\"2005\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"241.000\"},{\"1\":\"May\",\"2\":\"2005\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"128.500\"},{\"1\":\"May\",\"2\":\"2005\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"233.500\"},{\"1\":\"May\",\"2\":\"2005\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"135.500\"},{\"1\":\"May\",\"2\":\"2005\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"241.000\"},{\"1\":\"June\",\"2\":\"2005\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"128.500\"},{\"1\":\"June\",\"2\":\"2005\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"233.500\"},{\"1\":\"June\",\"2\":\"2005\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"135.500\"},{\"1\":\"June\",\"2\":\"2005\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"241.000\"},{\"1\":\"July\",\"2\":\"2005\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"128.500\"},{\"1\":\"July\",\"2\":\"2005\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"233.500\"},{\"1\":\"July\",\"2\":\"2005\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"135.500\"},{\"1\":\"July\",\"2\":\"2005\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"241.000\"},{\"1\":\"August\",\"2\":\"2005\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"128.500\"},{\"1\":\"August\",\"2\":\"2005\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"233.500\"},{\"1\":\"August\",\"2\":\"2005\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"135.500\"},{\"1\":\"August\",\"2\":\"2005\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"241.000\"},{\"1\":\"September\",\"2\":\"2005\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"128.500\"},{\"1\":\"September\",\"2\":\"2005\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"233.500\"},{\"1\":\"September\",\"2\":\"2005\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"135.500\"},{\"1\":\"September\",\"2\":\"2005\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"241.000\"},{\"1\":\"October\",\"2\":\"2005\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"128.500\"},{\"1\":\"October\",\"2\":\"2005\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"233.500\"},{\"1\":\"October\",\"2\":\"2005\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"135.500\"},{\"1\":\"October\",\"2\":\"2005\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"241.000\"},{\"1\":\"November\",\"2\":\"2005\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"128.500\"},{\"1\":\"November\",\"2\":\"2005\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"233.500\"},{\"1\":\"November\",\"2\":\"2005\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"135.500\"},{\"1\":\"November\",\"2\":\"2005\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"241.000\"},{\"1\":\"December\",\"2\":\"2005\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"128.500\"},{\"1\":\"December\",\"2\":\"2005\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"233.500\"},{\"1\":\"December\",\"2\":\"2005\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"135.500\"},{\"1\":\"December\",\"2\":\"2005\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"241.000\"},{\"1\":\"January\",\"2\":\"2006\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"128.500\"},{\"1\":\"January\",\"2\":\"2006\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"233.500\"},{\"1\":\"January\",\"2\":\"2006\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"135.500\"},{\"1\":\"January\",\"2\":\"2006\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"241.000\"},{\"1\":\"February\",\"2\":\"2006\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"128.500\"},{\"1\":\"February\",\"2\":\"2006\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"233.500\"},{\"1\":\"February\",\"2\":\"2006\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"135.500\"},{\"1\":\"February\",\"2\":\"2006\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"241.000\"},{\"1\":\"March\",\"2\":\"2006\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"128.500\"},{\"1\":\"March\",\"2\":\"2006\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"233.500\"},{\"1\":\"March\",\"2\":\"2006\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"135.500\"},{\"1\":\"March\",\"2\":\"2006\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"241.375\"},{\"1\":\"April\",\"2\":\"2006\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"128.500\"},{\"1\":\"April\",\"2\":\"2006\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"233.500\"},{\"1\":\"April\",\"2\":\"2006\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"135.500\"},{\"1\":\"April\",\"2\":\"2006\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"241.500\"},{\"1\":\"May\",\"2\":\"2006\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"128.500\"},{\"1\":\"May\",\"2\":\"2006\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"233.500\"},{\"1\":\"May\",\"2\":\"2006\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"135.500\"},{\"1\":\"May\",\"2\":\"2006\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"241.500\"},{\"1\":\"June\",\"2\":\"2006\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"128.500\"},{\"1\":\"June\",\"2\":\"2006\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"233.500\"},{\"1\":\"June\",\"2\":\"2006\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"135.500\"},{\"1\":\"June\",\"2\":\"2006\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"241.500\"},{\"1\":\"July\",\"2\":\"2006\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"128.500\"},{\"1\":\"July\",\"2\":\"2006\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"233.500\"},{\"1\":\"July\",\"2\":\"2006\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"135.500\"},{\"1\":\"July\",\"2\":\"2006\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"241.500\"},{\"1\":\"August\",\"2\":\"2006\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"128.500\"},{\"1\":\"August\",\"2\":\"2006\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"233.500\"},{\"1\":\"August\",\"2\":\"2006\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"135.500\"},{\"1\":\"August\",\"2\":\"2006\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"241.500\"},{\"1\":\"September\",\"2\":\"2006\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"128.500\"},{\"1\":\"September\",\"2\":\"2006\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"233.500\"},{\"1\":\"September\",\"2\":\"2006\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"135.500\"},{\"1\":\"September\",\"2\":\"2006\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"241.500\"},{\"1\":\"October\",\"2\":\"2006\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"128.500\"},{\"1\":\"October\",\"2\":\"2006\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"233.500\"},{\"1\":\"October\",\"2\":\"2006\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"135.500\"},{\"1\":\"October\",\"2\":\"2006\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"241.500\"},{\"1\":\"November\",\"2\":\"2006\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"128.500\"},{\"1\":\"November\",\"2\":\"2006\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"233.500\"},{\"1\":\"November\",\"2\":\"2006\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"135.500\"},{\"1\":\"November\",\"2\":\"2006\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"241.500\"},{\"1\":\"December\",\"2\":\"2006\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"128.500\"},{\"1\":\"December\",\"2\":\"2006\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"233.500\"},{\"1\":\"December\",\"2\":\"2006\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"135.500\"},{\"1\":\"December\",\"2\":\"2006\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"241.500\"},{\"1\":\"January\",\"2\":\"2007\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"128.500\"},{\"1\":\"January\",\"2\":\"2007\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"233.500\"},{\"1\":\"January\",\"2\":\"2007\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"135.500\"},{\"1\":\"January\",\"2\":\"2007\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"241.500\"},{\"1\":\"February\",\"2\":\"2007\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"131.125\"},{\"1\":\"February\",\"2\":\"2007\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"236.125\"},{\"1\":\"February\",\"2\":\"2007\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"138.125\"},{\"1\":\"February\",\"2\":\"2007\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"244.125\"},{\"1\":\"March\",\"2\":\"2007\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"132.000\"},{\"1\":\"March\",\"2\":\"2007\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"237.000\"},{\"1\":\"March\",\"2\":\"2007\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"139.000\"},{\"1\":\"March\",\"2\":\"2007\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"245.000\"},{\"1\":\"April\",\"2\":\"2007\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"132.000\"},{\"1\":\"April\",\"2\":\"2007\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"237.000\"},{\"1\":\"April\",\"2\":\"2007\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"139.000\"},{\"1\":\"April\",\"2\":\"2007\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"245.000\"},{\"1\":\"May\",\"2\":\"2007\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"132.000\"},{\"1\":\"May\",\"2\":\"2007\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"237.000\"},{\"1\":\"May\",\"2\":\"2007\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"139.000\"},{\"1\":\"May\",\"2\":\"2007\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"245.000\"},{\"1\":\"June\",\"2\":\"2007\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"132.000\"},{\"1\":\"June\",\"2\":\"2007\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"237.000\"},{\"1\":\"June\",\"2\":\"2007\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"139.000\"},{\"1\":\"June\",\"2\":\"2007\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"245.000\"},{\"1\":\"July\",\"2\":\"2007\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"132.000\"},{\"1\":\"July\",\"2\":\"2007\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"237.000\"},{\"1\":\"July\",\"2\":\"2007\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"139.000\"},{\"1\":\"July\",\"2\":\"2007\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"245.000\"},{\"1\":\"August\",\"2\":\"2007\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"132.000\"},{\"1\":\"August\",\"2\":\"2007\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"237.000\"},{\"1\":\"August\",\"2\":\"2007\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"139.000\"},{\"1\":\"August\",\"2\":\"2007\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"245.000\"},{\"1\":\"September\",\"2\":\"2007\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"132.000\"},{\"1\":\"September\",\"2\":\"2007\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"237.000\"},{\"1\":\"September\",\"2\":\"2007\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"139.000\"},{\"1\":\"September\",\"2\":\"2007\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"245.000\"},{\"1\":\"October\",\"2\":\"2007\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"132.000\"},{\"1\":\"October\",\"2\":\"2007\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"237.000\"},{\"1\":\"October\",\"2\":\"2007\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"139.000\"},{\"1\":\"October\",\"2\":\"2007\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"245.000\"},{\"1\":\"November\",\"2\":\"2007\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"132.000\"},{\"1\":\"November\",\"2\":\"2007\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"237.000\"},{\"1\":\"November\",\"2\":\"2007\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"139.000\"},{\"1\":\"November\",\"2\":\"2007\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"245.000\"},{\"1\":\"December\",\"2\":\"2007\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"132.000\"},{\"1\":\"December\",\"2\":\"2007\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"237.000\"},{\"1\":\"December\",\"2\":\"2007\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"139.000\"},{\"1\":\"December\",\"2\":\"2007\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"245.000\"},{\"1\":\"January\",\"2\":\"2008\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"132.000\"},{\"1\":\"January\",\"2\":\"2008\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"237.000\"},{\"1\":\"January\",\"2\":\"2008\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"139.000\"},{\"1\":\"January\",\"2\":\"2008\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"245.000\"},{\"1\":\"February\",\"2\":\"2008\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"132.000\"},{\"1\":\"February\",\"2\":\"2008\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"237.000\"},{\"1\":\"February\",\"2\":\"2008\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"139.000\"},{\"1\":\"February\",\"2\":\"2008\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"245.000\"},{\"1\":\"March\",\"2\":\"2008\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"132.000\"},{\"1\":\"March\",\"2\":\"2008\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"237.000\"},{\"1\":\"March\",\"2\":\"2008\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"139.000\"},{\"1\":\"March\",\"2\":\"2008\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"245.000\"},{\"1\":\"April\",\"2\":\"2008\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"132.000\"},{\"1\":\"April\",\"2\":\"2008\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"237.000\"},{\"1\":\"April\",\"2\":\"2008\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"139.000\"},{\"1\":\"April\",\"2\":\"2008\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"245.000\"},{\"1\":\"May\",\"2\":\"2008\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"132.000\"},{\"1\":\"May\",\"2\":\"2008\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"237.000\"},{\"1\":\"May\",\"2\":\"2008\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"139.000\"},{\"1\":\"May\",\"2\":\"2008\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"245.000\"},{\"1\":\"June\",\"2\":\"2008\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"174.500\"},{\"1\":\"June\",\"2\":\"2008\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"277.500\"},{\"1\":\"June\",\"2\":\"2008\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"185.500\"},{\"1\":\"June\",\"2\":\"2008\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"285.500\"},{\"1\":\"July\",\"2\":\"2008\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"174.500\"},{\"1\":\"July\",\"2\":\"2008\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"277.500\"},{\"1\":\"July\",\"2\":\"2008\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"185.500\"},{\"1\":\"July\",\"2\":\"2008\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"285.500\"},{\"1\":\"August\",\"2\":\"2008\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"174.500\"},{\"1\":\"August\",\"2\":\"2008\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"277.500\"},{\"1\":\"August\",\"2\":\"2008\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"185.500\"},{\"1\":\"August\",\"2\":\"2008\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"285.500\"},{\"1\":\"September\",\"2\":\"2008\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"174.500\"},{\"1\":\"September\",\"2\":\"2008\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"277.500\"},{\"1\":\"September\",\"2\":\"2008\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"185.500\"},{\"1\":\"September\",\"2\":\"2008\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"285.500\"},{\"1\":\"October\",\"2\":\"2008\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"174.500\"},{\"1\":\"October\",\"2\":\"2008\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"277.500\"},{\"1\":\"October\",\"2\":\"2008\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"185.500\"},{\"1\":\"October\",\"2\":\"2008\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"285.500\"},{\"1\":\"November\",\"2\":\"2008\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"174.500\"},{\"1\":\"November\",\"2\":\"2008\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"277.500\"},{\"1\":\"November\",\"2\":\"2008\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"185.500\"},{\"1\":\"November\",\"2\":\"2008\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"285.500\"},{\"1\":\"December\",\"2\":\"2008\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"174.500\"},{\"1\":\"December\",\"2\":\"2008\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"277.500\"},{\"1\":\"December\",\"2\":\"2008\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"185.500\"},{\"1\":\"December\",\"2\":\"2008\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"285.500\"},{\"1\":\"January\",\"2\":\"2009\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"174.500\"},{\"1\":\"January\",\"2\":\"2009\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"277.500\"},{\"1\":\"January\",\"2\":\"2009\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"185.500\"},{\"1\":\"January\",\"2\":\"2009\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"285.500\"},{\"1\":\"February\",\"2\":\"2009\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"174.500\"},{\"1\":\"February\",\"2\":\"2009\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"277.500\"},{\"1\":\"February\",\"2\":\"2009\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"185.500\"},{\"1\":\"February\",\"2\":\"2009\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"285.500\"},{\"1\":\"March\",\"2\":\"2009\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"174.500\"},{\"1\":\"March\",\"2\":\"2009\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"277.500\"},{\"1\":\"March\",\"2\":\"2009\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"185.500\"},{\"1\":\"March\",\"2\":\"2009\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"285.500\"},{\"1\":\"April\",\"2\":\"2009\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"174.500\"},{\"1\":\"April\",\"2\":\"2009\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"277.500\"},{\"1\":\"April\",\"2\":\"2009\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"185.500\"},{\"1\":\"April\",\"2\":\"2009\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"285.500\"},{\"1\":\"May\",\"2\":\"2009\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"174.500\"},{\"1\":\"May\",\"2\":\"2009\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"277.500\"},{\"1\":\"May\",\"2\":\"2009\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"185.500\"},{\"1\":\"May\",\"2\":\"2009\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"285.500\"},{\"1\":\"June\",\"2\":\"2009\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"174.500\"},{\"1\":\"June\",\"2\":\"2009\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"277.500\"},{\"1\":\"June\",\"2\":\"2009\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"185.500\"},{\"1\":\"June\",\"2\":\"2009\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"285.500\"},{\"1\":\"July\",\"2\":\"2009\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"174.500\"},{\"1\":\"July\",\"2\":\"2009\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"277.500\"},{\"1\":\"July\",\"2\":\"2009\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"185.500\"},{\"1\":\"July\",\"2\":\"2009\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"285.500\"},{\"1\":\"August\",\"2\":\"2009\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"174.500\"},{\"1\":\"August\",\"2\":\"2009\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"271.500\"},{\"1\":\"August\",\"2\":\"2009\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"185.500\"},{\"1\":\"August\",\"2\":\"2009\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"285.500\"},{\"1\":\"September\",\"2\":\"2009\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"174.500\"},{\"1\":\"September\",\"2\":\"2009\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"271.500\"},{\"1\":\"September\",\"2\":\"2009\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"185.500\"},{\"1\":\"September\",\"2\":\"2009\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"285.500\"},{\"1\":\"October\",\"2\":\"2009\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"174.500\"},{\"1\":\"October\",\"2\":\"2009\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"271.500\"},{\"1\":\"October\",\"2\":\"2009\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"185.500\"},{\"1\":\"October\",\"2\":\"2009\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"285.500\"},{\"1\":\"November\",\"2\":\"2009\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"174.500\"},{\"1\":\"November\",\"2\":\"2009\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"271.500\"},{\"1\":\"November\",\"2\":\"2009\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"185.500\"},{\"1\":\"November\",\"2\":\"2009\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"285.500\"},{\"1\":\"December\",\"2\":\"2009\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"174.500\"},{\"1\":\"December\",\"2\":\"2009\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"271.500\"},{\"1\":\"December\",\"2\":\"2009\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"185.500\"},{\"1\":\"December\",\"2\":\"2009\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"285.500\"},{\"1\":\"January\",\"2\":\"2010\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"174.500\"},{\"1\":\"January\",\"2\":\"2010\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"271.500\"},{\"1\":\"January\",\"2\":\"2010\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"185.500\"},{\"1\":\"January\",\"2\":\"2010\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"285.500\"},{\"1\":\"February\",\"2\":\"2010\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"174.500\"},{\"1\":\"February\",\"2\":\"2010\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"271.500\"},{\"1\":\"February\",\"2\":\"2010\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"185.500\"},{\"1\":\"February\",\"2\":\"2010\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"285.500\"},{\"1\":\"March\",\"2\":\"2010\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"174.500\"},{\"1\":\"March\",\"2\":\"2010\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"268.000\"},{\"1\":\"March\",\"2\":\"2010\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"185.500\"},{\"1\":\"March\",\"2\":\"2010\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"285.500\"},{\"1\":\"April\",\"2\":\"2010\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"174.500\"},{\"1\":\"April\",\"2\":\"2010\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"268.000\"},{\"1\":\"April\",\"2\":\"2010\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"185.500\"},{\"1\":\"April\",\"2\":\"2010\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"285.500\"},{\"1\":\"May\",\"2\":\"2010\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"174.500\"},{\"1\":\"May\",\"2\":\"2010\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"268.000\"},{\"1\":\"May\",\"2\":\"2010\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"185.500\"},{\"1\":\"May\",\"2\":\"2010\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"285.500\"},{\"1\":\"June\",\"2\":\"2010\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"174.500\"},{\"1\":\"June\",\"2\":\"2010\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"268.000\"},{\"1\":\"June\",\"2\":\"2010\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"185.500\"},{\"1\":\"June\",\"2\":\"2010\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"285.500\"},{\"1\":\"July\",\"2\":\"2010\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"174.500\"},{\"1\":\"July\",\"2\":\"2010\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"268.000\"},{\"1\":\"July\",\"2\":\"2010\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"185.500\"},{\"1\":\"July\",\"2\":\"2010\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"285.500\"},{\"1\":\"August\",\"2\":\"2010\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"174.500\"},{\"1\":\"August\",\"2\":\"2010\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"268.000\"},{\"1\":\"August\",\"2\":\"2010\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"185.500\"},{\"1\":\"August\",\"2\":\"2010\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"285.500\"},{\"1\":\"September\",\"2\":\"2010\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"174.500\"},{\"1\":\"September\",\"2\":\"2010\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"268.000\"},{\"1\":\"September\",\"2\":\"2010\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"185.500\"},{\"1\":\"September\",\"2\":\"2010\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"285.500\"},{\"1\":\"October\",\"2\":\"2010\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"174.500\"},{\"1\":\"October\",\"2\":\"2010\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"267.500\"},{\"1\":\"October\",\"2\":\"2010\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"185.500\"},{\"1\":\"October\",\"2\":\"2010\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"285.500\"},{\"1\":\"November\",\"2\":\"2010\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"174.500\"},{\"1\":\"November\",\"2\":\"2010\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"267.500\"},{\"1\":\"November\",\"2\":\"2010\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"185.500\"},{\"1\":\"November\",\"2\":\"2010\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"285.500\"},{\"1\":\"December\",\"2\":\"2010\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"174.500\"},{\"1\":\"December\",\"2\":\"2010\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"267.500\"},{\"1\":\"December\",\"2\":\"2010\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"185.500\"},{\"1\":\"December\",\"2\":\"2010\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"285.500\"},{\"1\":\"January\",\"2\":\"2011\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"174.500\"},{\"1\":\"January\",\"2\":\"2011\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"267.500\"},{\"1\":\"January\",\"2\":\"2011\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"185.500\"},{\"1\":\"January\",\"2\":\"2011\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"285.500\"},{\"1\":\"February\",\"2\":\"2011\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"174.500\"},{\"1\":\"February\",\"2\":\"2011\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"267.500\"},{\"1\":\"February\",\"2\":\"2011\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"185.500\"},{\"1\":\"February\",\"2\":\"2011\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"285.500\"},{\"1\":\"March\",\"2\":\"2011\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"174.500\"},{\"1\":\"March\",\"2\":\"2011\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"267.500\"},{\"1\":\"March\",\"2\":\"2011\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"185.500\"},{\"1\":\"March\",\"2\":\"2011\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"285.500\"},{\"1\":\"April\",\"2\":\"2011\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"174.500\"},{\"1\":\"April\",\"2\":\"2011\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"267.500\"},{\"1\":\"April\",\"2\":\"2011\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"185.500\"},{\"1\":\"April\",\"2\":\"2011\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"285.500\"},{\"1\":\"May\",\"2\":\"2011\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"174.500\"},{\"1\":\"May\",\"2\":\"2011\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"267.500\"},{\"1\":\"May\",\"2\":\"2011\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"185.500\"},{\"1\":\"May\",\"2\":\"2011\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"285.500\"},{\"1\":\"June\",\"2\":\"2011\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"174.500\"},{\"1\":\"June\",\"2\":\"2011\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"270.000\"},{\"1\":\"June\",\"2\":\"2011\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"185.500\"},{\"1\":\"June\",\"2\":\"2011\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"285.500\"},{\"1\":\"July\",\"2\":\"2011\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"174.500\"},{\"1\":\"July\",\"2\":\"2011\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"270.000\"},{\"1\":\"July\",\"2\":\"2011\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"185.500\"},{\"1\":\"July\",\"2\":\"2011\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"285.500\"},{\"1\":\"August\",\"2\":\"2011\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"174.500\"},{\"1\":\"August\",\"2\":\"2011\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"270.000\"},{\"1\":\"August\",\"2\":\"2011\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"185.500\"},{\"1\":\"August\",\"2\":\"2011\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"285.500\"},{\"1\":\"September\",\"2\":\"2011\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"174.500\"},{\"1\":\"September\",\"2\":\"2011\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"270.000\"},{\"1\":\"September\",\"2\":\"2011\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"185.500\"},{\"1\":\"September\",\"2\":\"2011\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"285.500\"},{\"1\":\"October\",\"2\":\"2011\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"174.500\"},{\"1\":\"October\",\"2\":\"2011\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"270.000\"},{\"1\":\"October\",\"2\":\"2011\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"185.500\"},{\"1\":\"October\",\"2\":\"2011\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"285.500\"},{\"1\":\"November\",\"2\":\"2011\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"174.500\"},{\"1\":\"November\",\"2\":\"2011\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"270.000\"},{\"1\":\"November\",\"2\":\"2011\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"185.500\"},{\"1\":\"November\",\"2\":\"2011\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"285.500\"},{\"1\":\"December\",\"2\":\"2011\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"174.500\"},{\"1\":\"December\",\"2\":\"2011\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"270.000\"},{\"1\":\"December\",\"2\":\"2011\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"185.500\"},{\"1\":\"December\",\"2\":\"2011\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"285.500\"},{\"1\":\"January\",\"2\":\"2012\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"174.500\"},{\"1\":\"January\",\"2\":\"2012\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"267.500\"},{\"1\":\"January\",\"2\":\"2012\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"185.500\"},{\"1\":\"January\",\"2\":\"2012\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"285.500\"},{\"1\":\"February\",\"2\":\"2012\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"174.500\"},{\"1\":\"February\",\"2\":\"2012\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"267.500\"},{\"1\":\"February\",\"2\":\"2012\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"185.500\"},{\"1\":\"February\",\"2\":\"2012\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"288.500\"},{\"1\":\"March\",\"2\":\"2012\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"174.500\"},{\"1\":\"March\",\"2\":\"2012\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"267.500\"},{\"1\":\"March\",\"2\":\"2012\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"185.500\"},{\"1\":\"March\",\"2\":\"2012\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"288.500\"},{\"1\":\"April\",\"2\":\"2012\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"174.500\"},{\"1\":\"April\",\"2\":\"2012\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"267.500\"},{\"1\":\"April\",\"2\":\"2012\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"185.500\"},{\"1\":\"April\",\"2\":\"2012\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"288.500\"},{\"1\":\"May\",\"2\":\"2012\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"173.250\"},{\"1\":\"May\",\"2\":\"2012\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"267.500\"},{\"1\":\"May\",\"2\":\"2012\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"185.500\"},{\"1\":\"May\",\"2\":\"2012\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"288.500\"},{\"1\":\"June\",\"2\":\"2012\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"173.250\"},{\"1\":\"June\",\"2\":\"2012\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"267.500\"},{\"1\":\"June\",\"2\":\"2012\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"185.500\"},{\"1\":\"June\",\"2\":\"2012\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"288.500\"},{\"1\":\"July\",\"2\":\"2012\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"173.250\"},{\"1\":\"July\",\"2\":\"2012\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"267.500\"},{\"1\":\"July\",\"2\":\"2012\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"185.500\"},{\"1\":\"July\",\"2\":\"2012\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"288.500\"},{\"1\":\"August\",\"2\":\"2012\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"173.250\"},{\"1\":\"August\",\"2\":\"2012\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"267.500\"},{\"1\":\"August\",\"2\":\"2012\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"185.500\"},{\"1\":\"August\",\"2\":\"2012\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"288.500\"},{\"1\":\"September\",\"2\":\"2012\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"173.250\"},{\"1\":\"September\",\"2\":\"2012\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"267.500\"},{\"1\":\"September\",\"2\":\"2012\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"185.500\"},{\"1\":\"September\",\"2\":\"2012\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"288.500\"},{\"1\":\"October\",\"2\":\"2012\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"173.250\"},{\"1\":\"October\",\"2\":\"2012\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"267.500\"},{\"1\":\"October\",\"2\":\"2012\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"185.500\"},{\"1\":\"October\",\"2\":\"2012\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"288.500\"},{\"1\":\"November\",\"2\":\"2012\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"178.000\"},{\"1\":\"November\",\"2\":\"2012\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"267.500\"},{\"1\":\"November\",\"2\":\"2012\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"188.130\"},{\"1\":\"November\",\"2\":\"2012\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"290.000\"},{\"1\":\"December\",\"2\":\"2012\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"178.000\"},{\"1\":\"December\",\"2\":\"2012\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"267.500\"},{\"1\":\"December\",\"2\":\"2012\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"188.130\"},{\"1\":\"December\",\"2\":\"2012\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"290.000\"},{\"1\":\"January\",\"2\":\"2013\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"178.000\"},{\"1\":\"January\",\"2\":\"2013\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"267.500\"},{\"1\":\"January\",\"2\":\"2013\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"188.130\"},{\"1\":\"January\",\"2\":\"2013\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"290.000\"},{\"1\":\"February\",\"2\":\"2013\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"178.000\"},{\"1\":\"February\",\"2\":\"2013\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"267.500\"},{\"1\":\"February\",\"2\":\"2013\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"188.130\"},{\"1\":\"February\",\"2\":\"2013\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"290.000\"},{\"1\":\"March\",\"2\":\"2013\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"178.000\"},{\"1\":\"March\",\"2\":\"2013\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"267.500\"},{\"1\":\"March\",\"2\":\"2013\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"188.130\"},{\"1\":\"March\",\"2\":\"2013\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"290.000\"},{\"1\":\"April\",\"2\":\"2013\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"178.000\"},{\"1\":\"April\",\"2\":\"2013\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"267.500\"},{\"1\":\"April\",\"2\":\"2013\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"188.130\"},{\"1\":\"April\",\"2\":\"2013\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"290.000\"},{\"1\":\"May\",\"2\":\"2013\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"178.000\"},{\"1\":\"May\",\"2\":\"2013\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"267.500\"},{\"1\":\"May\",\"2\":\"2013\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"188.130\"},{\"1\":\"May\",\"2\":\"2013\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"290.000\"},{\"1\":\"June\",\"2\":\"2013\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"178.000\"},{\"1\":\"June\",\"2\":\"2013\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"267.500\"},{\"1\":\"June\",\"2\":\"2013\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"188.130\"},{\"1\":\"June\",\"2\":\"2013\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"290.000\"},{\"1\":\"July\",\"2\":\"2013\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"178.000\"},{\"1\":\"July\",\"2\":\"2013\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"267.500\"},{\"1\":\"July\",\"2\":\"2013\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"188.130\"},{\"1\":\"July\",\"2\":\"2013\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"290.000\"},{\"1\":\"August\",\"2\":\"2013\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"178.000\"},{\"1\":\"August\",\"2\":\"2013\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"267.500\"},{\"1\":\"August\",\"2\":\"2013\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"188.130\"},{\"1\":\"August\",\"2\":\"2013\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"290.000\"},{\"1\":\"September\",\"2\":\"2013\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"178.000\"},{\"1\":\"September\",\"2\":\"2013\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"267.500\"},{\"1\":\"September\",\"2\":\"2013\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"188.130\"},{\"1\":\"September\",\"2\":\"2013\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"290.000\"},{\"1\":\"October\",\"2\":\"2013\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"178.000\"},{\"1\":\"October\",\"2\":\"2013\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"267.500\"},{\"1\":\"October\",\"2\":\"2013\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"188.130\"},{\"1\":\"October\",\"2\":\"2013\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"290.000\"},{\"1\":\"November\",\"2\":\"2013\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"178.000\"},{\"1\":\"November\",\"2\":\"2013\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"267.500\"},{\"1\":\"November\",\"2\":\"2013\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"188.130\"},{\"1\":\"November\",\"2\":\"2013\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"290.000\"},{\"1\":\"December\",\"2\":\"2013\",\"3\":\"large\",\"4\":\"half_dozen\",\"5\":\"178.000\"},{\"1\":\"December\",\"2\":\"2013\",\"3\":\"large\",\"4\":\"dozen\",\"5\":\"267.500\"},{\"1\":\"December\",\"2\":\"2013\",\"3\":\"extra_large\",\"4\":\"half_dozen\",\"5\":\"188.130\"},{\"1\":\"December\",\"2\":\"2013\",\"3\":\"extra_large\",\"4\":\"dozen\",\"5\":\"290.000\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}