{
  "hash": "ba9e47006a056b7689d21864bc66c390",
  "result": {
    "markdown": "---\ntitle: \"Exploring Factors Influencing Diabetes Diagnosis in the Pima Indian Population\"\nauthor: \"Megha Joseph\"\ndate: \"05/29/2023\"\nformat:\n  html:\n    df-print: paged\n    toc: true\n    code-copy: true\n    code-tools: true\n    css: styles.css\ncategories:\n  - final_Project\n  - final_project_data_description\neditor_options: \n  chunk_output_type: console\n---\n\n\n# Load required packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# This line loads the tidyverse package, which includes several useful packages for data manipulation and visualization.\nlibrary(tidyverse)\n\n# This line loads the ggplot2 package, which is a powerful library for creating visualizations.\nlibrary(ggplot2)\n\n# suppressing large warning messages while run time\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n# Introduction\n\nThis project focuses on exploring the factors that influence the presence and absence of diabetes in the Pima Indian population by analyzing variables such as age, pregnancies, BMI, skin thickness, glucose levels and insulin level.By analyzing the data using visualizations, we aim to gain insights and understand the relationships between different variables and the outcome of diabetes in the specific Pima Indian population.\nThe research question guiding this study is: How do factors such as age, pregnancies, BMI, skin thickness, glucose levels, and insulin levels relate to the presence or absence of diabetes in the Pima Indian population? To address this, we utilize a comprehensive dataset collected by the National Institute of Diabetes and Digestive and Kidney Diseases. The dataset specifically includes data from females of Pima Indian heritage aged 21 or older. Each individual in the dataset represents a case or unit of analysis.\n\n# Background\n\nDiabetes is a prevalent chronic disease that disproportionately affects the Pima Indian population and understanding the factors contributing to diabetes in this community is crucial for developing effective startegies and improving health outcomes. Previous research has identified age, pregnancies, BMI, skin thickness, glucose levels, and insulin levels as significant factors related to diabetes. By analyzing these variables, we can unfold the complex relationships associated with diabetes onset in the Pima population. The findings of this study help healthcare providers and researchers about the specific risk factors faced by the community and develop preventive and personalized healthcare approaches. Additionally, the insights gained from this research can contribute to advancing our understanding of diabetes and shape future research directions globally.By exploring the multifaceted factors influencing diabetes seeks to improve the lives of individuals affected by diabetes and benefit broader populations affected by this chronic disease. \n\n# Dataset Description\n\nThe dataset used in this project was originally collected by the National Institute of Diabetes and Digestive and Kidney Diseases. It provides a comprehensive collection of medical data specifically focused on females of Pima Indian heritage who are 21 years of age or older. Each row in the dataset represents an individual patient, making them the unit of analysis or \"case\" in this study with the variables providing information on factors such as pregnancies, glucose levels, blood pressure, skin thickness, insulin levels, BMI, diabetes pedigree function, and age. The dataset enables the examination of these variables in relation to the presence or absence of diabetes in the Pima Indian population.\n\nThis study investigates the factors associated with diabetes by analyzing a comprehensive set of variables. The number of pregnancies a person has had is examined to understand the potential influence of pregnancy on diabetes risk. Glucose levels, measured through an Oral Glucose Tolerance Test, provide insights into the relationship between glucose metabolism and diabetes. Diastolic blood pressure values are considered to assess any correlation with diabetes. The thickness of the triceps skin fold is measured to evaluate its association with diabetes. Serum insulin concentration, measured two hours after consuming a glucose solution, is examined as a potential indicator of diabetes. Body mass index (BMI) is calculated based on weight and height to estimate body fat and its impact on diabetes risk. The diabetes pedigree function provides an estimation of the genetic influence of diabetes based on family history. Age is also considered as a variable to explore the relationship between age and diabetes. The outcome variable indicates whether the patient has diabetes or not, with binary values of 1 (positive for diabetes) and 0 (negative for diabetes). By analyzing these variables in relation to the outcome, this study aims to identify potential predictors of diabetes.\n\n### Read the dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndiabetes = read.csv(\"~/601_Spring_2023/posts/_data/Diabetes_Dataset.csv\")\n```\n:::\n\n\n### Get the dimensions of the \"diabetes\" dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(diabetes) # Returns the number of rows and columns in the dataset\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 768   9\n```\n:::\n:::\n\nThe \"diabetes\" dataset has 768 rows and 9 columns, indicating 768 individual observations and 9 variables.\n\n### Selecting the first 20 rows of the \"diabetes\" dataset and displaying all columns for those rows\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndiabetes[1:20,] \n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Pregnancies\"],\"name\":[1],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Glucose\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"BloodPressure\"],\"name\":[3],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"SkinThickness\"],\"name\":[4],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Insulin\"],\"name\":[5],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"BMI\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"DiabetesPedigreeFunction\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Age\"],\"name\":[8],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Outcome\"],\"name\":[9],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"6\",\"2\":\"148\",\"3\":\"72\",\"4\":\"35\",\"5\":\"0\",\"6\":\"33.6\",\"7\":\"0.627\",\"8\":\"50\",\"9\":\"1\",\"_rn_\":\"1\"},{\"1\":\"1\",\"2\":\"85\",\"3\":\"66\",\"4\":\"29\",\"5\":\"0\",\"6\":\"26.6\",\"7\":\"0.351\",\"8\":\"31\",\"9\":\"0\",\"_rn_\":\"2\"},{\"1\":\"8\",\"2\":\"183\",\"3\":\"64\",\"4\":\"0\",\"5\":\"0\",\"6\":\"23.3\",\"7\":\"0.672\",\"8\":\"32\",\"9\":\"1\",\"_rn_\":\"3\"},{\"1\":\"1\",\"2\":\"89\",\"3\":\"66\",\"4\":\"23\",\"5\":\"94\",\"6\":\"28.1\",\"7\":\"0.167\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"4\"},{\"1\":\"0\",\"2\":\"137\",\"3\":\"40\",\"4\":\"35\",\"5\":\"168\",\"6\":\"43.1\",\"7\":\"2.288\",\"8\":\"33\",\"9\":\"1\",\"_rn_\":\"5\"},{\"1\":\"5\",\"2\":\"116\",\"3\":\"74\",\"4\":\"0\",\"5\":\"0\",\"6\":\"25.6\",\"7\":\"0.201\",\"8\":\"30\",\"9\":\"0\",\"_rn_\":\"6\"},{\"1\":\"3\",\"2\":\"78\",\"3\":\"50\",\"4\":\"32\",\"5\":\"88\",\"6\":\"31.0\",\"7\":\"0.248\",\"8\":\"26\",\"9\":\"1\",\"_rn_\":\"7\"},{\"1\":\"10\",\"2\":\"115\",\"3\":\"0\",\"4\":\"0\",\"5\":\"0\",\"6\":\"35.3\",\"7\":\"0.134\",\"8\":\"29\",\"9\":\"0\",\"_rn_\":\"8\"},{\"1\":\"2\",\"2\":\"197\",\"3\":\"70\",\"4\":\"45\",\"5\":\"543\",\"6\":\"30.5\",\"7\":\"0.158\",\"8\":\"53\",\"9\":\"1\",\"_rn_\":\"9\"},{\"1\":\"8\",\"2\":\"125\",\"3\":\"96\",\"4\":\"0\",\"5\":\"0\",\"6\":\"0.0\",\"7\":\"0.232\",\"8\":\"54\",\"9\":\"1\",\"_rn_\":\"10\"},{\"1\":\"4\",\"2\":\"110\",\"3\":\"92\",\"4\":\"0\",\"5\":\"0\",\"6\":\"37.6\",\"7\":\"0.191\",\"8\":\"30\",\"9\":\"0\",\"_rn_\":\"11\"},{\"1\":\"10\",\"2\":\"168\",\"3\":\"74\",\"4\":\"0\",\"5\":\"0\",\"6\":\"38.0\",\"7\":\"0.537\",\"8\":\"34\",\"9\":\"1\",\"_rn_\":\"12\"},{\"1\":\"10\",\"2\":\"139\",\"3\":\"80\",\"4\":\"0\",\"5\":\"0\",\"6\":\"27.1\",\"7\":\"1.441\",\"8\":\"57\",\"9\":\"0\",\"_rn_\":\"13\"},{\"1\":\"1\",\"2\":\"189\",\"3\":\"60\",\"4\":\"23\",\"5\":\"846\",\"6\":\"30.1\",\"7\":\"0.398\",\"8\":\"59\",\"9\":\"1\",\"_rn_\":\"14\"},{\"1\":\"5\",\"2\":\"166\",\"3\":\"72\",\"4\":\"19\",\"5\":\"175\",\"6\":\"25.8\",\"7\":\"0.587\",\"8\":\"51\",\"9\":\"1\",\"_rn_\":\"15\"},{\"1\":\"7\",\"2\":\"100\",\"3\":\"0\",\"4\":\"0\",\"5\":\"0\",\"6\":\"30.0\",\"7\":\"0.484\",\"8\":\"32\",\"9\":\"1\",\"_rn_\":\"16\"},{\"1\":\"0\",\"2\":\"118\",\"3\":\"84\",\"4\":\"47\",\"5\":\"230\",\"6\":\"45.8\",\"7\":\"0.551\",\"8\":\"31\",\"9\":\"1\",\"_rn_\":\"17\"},{\"1\":\"7\",\"2\":\"107\",\"3\":\"74\",\"4\":\"0\",\"5\":\"0\",\"6\":\"29.6\",\"7\":\"0.254\",\"8\":\"31\",\"9\":\"1\",\"_rn_\":\"18\"},{\"1\":\"1\",\"2\":\"103\",\"3\":\"30\",\"4\":\"38\",\"5\":\"83\",\"6\":\"43.3\",\"7\":\"0.183\",\"8\":\"33\",\"9\":\"0\",\"_rn_\":\"19\"},{\"1\":\"1\",\"2\":\"115\",\"3\":\"70\",\"4\":\"30\",\"5\":\"96\",\"6\":\"34.6\",\"7\":\"0.529\",\"8\":\"32\",\"9\":\"1\",\"_rn_\":\"20\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\nThe output shows a subset of the diabetes dataset, specifically the first 20 rows where each row corresponds to an individual and includes information such as the number of pregnancies, glucose levels, blood pressure, skin thickness, insulin levels, BMI, diabetes pedigree function, age, and the outcome.\n\nFor the first individual (row 1), they have had 6 pregnancies and have glucose levels of 148 mg/dL, blood pressure of 72 mm Hg, skin thickness of 35 mm, no insulin recorded, a BMI of 33.6, a diabetes pedigree function of 0.627, and an age of 50. The outcome variable indicates that this individual has been diagnosed with diabetes (Outcome = 1). Similarly, each subsequent row provides information about the corresponding individual's characteristics, including medical measurements and the diabetes outcome. Also, upon examining the table, it is evident that some variables such as Blood Pressure, SkinThickness, and Insulin have 0 values, which are unrealistic in the real world. It is important to note that invalid values can significantly impact the analysis and interpretation of the data. As a part of our data cleansing exercise, it is necessary to remove these records from our data frame before proceeding with further analysis. This ensures that our analysis is based on reliable and meaningful data, thereby improving the accuracy of our findings and conclusions.\n\n### Distribution of Outcomes\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(diabetes$Outcome) # Here, value '0' is assigned to \"Normal\" people and '1'is assigned to people with \"Diabetes\"\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  0   1 \n500 268 \n```\n:::\n:::\n\nThe dataset contains 500 individuals labeled as \"0\" (without diabetes) and 268 individuals labeled as \"1\" (with diabetes), indicating the distribution of diabetes cases within the dataset. Notably, this distribution reveals an imbalance, as the majority class (\"0\") has 500 instances, while the minority class (\"1\") has 268 instances.\n\n\n### Diabetes Dataset Structure\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(diabetes) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t768 obs. of  9 variables:\n $ Pregnancies             : int  6 1 8 1 0 5 3 10 2 8 ...\n $ Glucose                 : int  148 85 183 89 137 116 78 115 197 125 ...\n $ BloodPressure           : int  72 66 64 66 40 74 50 0 70 96 ...\n $ SkinThickness           : int  35 29 0 23 35 0 32 0 45 0 ...\n $ Insulin                 : int  0 0 0 94 168 0 88 0 543 0 ...\n $ BMI                     : num  33.6 26.6 23.3 28.1 43.1 25.6 31 35.3 30.5 0 ...\n $ DiabetesPedigreeFunction: num  0.627 0.351 0.672 0.167 2.288 ...\n $ Age                     : int  50 31 32 21 33 30 26 29 53 54 ...\n $ Outcome                 : int  1 0 1 0 1 0 1 0 1 1 ...\n```\n:::\n:::\n\nBased on the above we can see that the variables \"Pregnancies,\" \"Glucose,\" \"BloodPressure,\" \"SkinThickness,\" \"Insulin,\" \"Age,\" and \"Outcome\" are of integer data type, indicating that they represent whole numbers. The variable \"BMI\", \"DiabetesPedigreeFunction\" is of numeric data type, suggesting that it represents decimal numbers. It doesnt appear we have any categorical variables with the exception of our response variable outcome. Also variables, namely \"BloodPressure,\" \"SkinThickness,\" \"Insulin,\" and \"BMI,\" have inappropriate values, which are represented by 0 in the dataset. These missing values should be handled appropriately to ensure accurate interpretations.\n\n### Summary statistics for variables\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(diabetes[c(\"Pregnancies\", \"Glucose\", \"BloodPressure\", \"SkinThickness\", \"Insulin\", \"BMI\", \"Age\", \"Outcome\")])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Pregnancies        Glucose      BloodPressure    SkinThickness  \n Min.   : 0.000   Min.   :  0.0   Min.   :  0.00   Min.   : 0.00  \n 1st Qu.: 1.000   1st Qu.: 99.0   1st Qu.: 62.00   1st Qu.: 0.00  \n Median : 3.000   Median :117.0   Median : 72.00   Median :23.00  \n Mean   : 3.845   Mean   :120.9   Mean   : 69.11   Mean   :20.54  \n 3rd Qu.: 6.000   3rd Qu.:140.2   3rd Qu.: 80.00   3rd Qu.:32.00  \n Max.   :17.000   Max.   :199.0   Max.   :122.00   Max.   :99.00  \n    Insulin           BMI             Age           Outcome     \n Min.   :  0.0   Min.   : 0.00   Min.   :21.00   Min.   :0.000  \n 1st Qu.:  0.0   1st Qu.:27.30   1st Qu.:24.00   1st Qu.:0.000  \n Median : 30.5   Median :32.00   Median :29.00   Median :0.000  \n Mean   : 79.8   Mean   :31.99   Mean   :33.24   Mean   :0.349  \n 3rd Qu.:127.2   3rd Qu.:36.60   3rd Qu.:41.00   3rd Qu.:1.000  \n Max.   :846.0   Max.   :67.10   Max.   :81.00   Max.   :1.000  \n```\n:::\n:::\n\nThe dataset contains information on pregnancies, glucose levels, blood pressure, skin thickness, insulin levels, BMI, age, and the presence or absence of diabetes (outcome). The pregnancies variable ranges from 0 to 17, with a median of 3, indicating that half of the individuals in the dataset had 3 pregnancies. The glucose levels range from 0 to 199 mg/dL, with a median of 117 mg/dL, representing the middle value. The blood pressure readings range from 0 to 122 mm Hg, with a median of 72 mm Hg. The skin thickness measurements range from 0 to 99 mm, with a median of 23 mm. Insulin levels range from 0 to 846 units/ml, with a median of 30.5 units/ml. The BMI values range from 0 to 67.1, with a median of 32.0. The age of the individuals ranges from 21 to 81 years, with a median of 29 years. The outcome variable indicates the presence or absence of diabetes, with approximately 35% of the individuals in the data set being diagnosed with diabetes.\n\nWe can see that for many of the independent variables our min value is 0, this is fine for pregnancies but intuitively a value of 0 likely does not make sense for Glucose, Bloodpressure, SkinThickness, Insulin, and BMI.\n\n\n### Data Preprocessing - Handling Invalid Entries in the Diabetes Dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\nzero_indices_glucose <- diabetes$Glucose == 0\nzero_indices_bp <- diabetes$BloodPressure == 0\nzero_indices_st <- diabetes$SkinThickness == 0\nzero_indices_insulin <- diabetes$Insulin == 0\nzero_indices_bmi <- diabetes$BMI == 0\nmean_glucose <- mean(diabetes$Glucose[!zero_indices_glucose])\nmean_bp <- mean(diabetes$BloodPressure[!zero_indices_bp])\nmean_st <- mean(diabetes$SkinThickness[!zero_indices_st])\nmean_insulin <- mean(diabetes$Insulin[!zero_indices_insulin])\nmean_bmi <- mean(diabetes$BMI[!zero_indices_bmi])\ndiabetes$Glucose[zero_indices_glucose] <- mean_glucose\ndiabetes$BloodPressure[zero_indices_bp] <- mean_bp\ndiabetes$SkinThickness[zero_indices_st] <- mean_st\ndiabetes$Insulin[zero_indices_insulin] <- mean_insulin\ndiabetes$BMI[zero_indices_bmi] <- mean_bmi\n```\n:::\n\nTo handle the problem of zero values in the Bloodpressure, BMI, and Glucose columns of the diabetes dataset, we will replace those values with the mean value of each respective column. This process involves iterating through all the columns in the dataset and substituting any invalid (zero) entries with the mean value specific to the corresponding column. By doing this, we ensure that the dataset contains more accurate and meaningful data, improving the reliability of future analyses and modeling tasks.\n\n### Verifying Replacement of Invalid Observations with Mean Values\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(diabetes[c(\"Pregnancies\", \"Glucose\", \"BloodPressure\", \"SkinThickness\", \"Insulin\", \"BMI\", \"Age\", \"Outcome\")])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Pregnancies        Glucose       BloodPressure    SkinThickness  \n Min.   : 0.000   Min.   : 44.00   Min.   : 24.00   Min.   : 7.00  \n 1st Qu.: 1.000   1st Qu.: 99.75   1st Qu.: 64.00   1st Qu.:25.00  \n Median : 3.000   Median :117.00   Median : 72.20   Median :29.15  \n Mean   : 3.845   Mean   :121.69   Mean   : 72.41   Mean   :29.15  \n 3rd Qu.: 6.000   3rd Qu.:140.25   3rd Qu.: 80.00   3rd Qu.:32.00  \n Max.   :17.000   Max.   :199.00   Max.   :122.00   Max.   :99.00  \n    Insulin           BMI             Age           Outcome     \n Min.   : 14.0   Min.   :18.20   Min.   :21.00   Min.   :0.000  \n 1st Qu.:121.5   1st Qu.:27.50   1st Qu.:24.00   1st Qu.:0.000  \n Median :155.5   Median :32.40   Median :29.00   Median :0.000  \n Mean   :155.5   Mean   :32.46   Mean   :33.24   Mean   :0.349  \n 3rd Qu.:155.5   3rd Qu.:36.60   3rd Qu.:41.00   3rd Qu.:1.000  \n Max.   :846.0   Max.   :67.10   Max.   :81.00   Max.   :1.000  \n```\n:::\n:::\n\nAfter replacing the invalid entries in the columns with their respective mean values, we will check the summary statistics again to confirm whether the replacement was successful. This step allows us to ensure that the invalid observations have been appropriately substituted, making the dataset more reliable for further analysis.\n\n### Handling Null Values \n\n::: {.cell}\n\n```{.r .cell-code}\ndiabetes <- na.omit(diabetes)\ndiabetes\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Pregnancies\"],\"name\":[1],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Glucose\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"BloodPressure\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"SkinThickness\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Insulin\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"BMI\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"DiabetesPedigreeFunction\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Age\"],\"name\":[8],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Outcome\"],\"name\":[9],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"6\",\"2\":\"148.0000\",\"3\":\"72.00000\",\"4\":\"35.00000\",\"5\":\"155.5482\",\"6\":\"33.60000\",\"7\":\"0.627\",\"8\":\"50\",\"9\":\"1\",\"_rn_\":\"1\"},{\"1\":\"1\",\"2\":\"85.0000\",\"3\":\"66.00000\",\"4\":\"29.00000\",\"5\":\"155.5482\",\"6\":\"26.60000\",\"7\":\"0.351\",\"8\":\"31\",\"9\":\"0\",\"_rn_\":\"2\"},{\"1\":\"8\",\"2\":\"183.0000\",\"3\":\"64.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"23.30000\",\"7\":\"0.672\",\"8\":\"32\",\"9\":\"1\",\"_rn_\":\"3\"},{\"1\":\"1\",\"2\":\"89.0000\",\"3\":\"66.00000\",\"4\":\"23.00000\",\"5\":\"94.0000\",\"6\":\"28.10000\",\"7\":\"0.167\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"4\"},{\"1\":\"0\",\"2\":\"137.0000\",\"3\":\"40.00000\",\"4\":\"35.00000\",\"5\":\"168.0000\",\"6\":\"43.10000\",\"7\":\"2.288\",\"8\":\"33\",\"9\":\"1\",\"_rn_\":\"5\"},{\"1\":\"5\",\"2\":\"116.0000\",\"3\":\"74.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"25.60000\",\"7\":\"0.201\",\"8\":\"30\",\"9\":\"0\",\"_rn_\":\"6\"},{\"1\":\"3\",\"2\":\"78.0000\",\"3\":\"50.00000\",\"4\":\"32.00000\",\"5\":\"88.0000\",\"6\":\"31.00000\",\"7\":\"0.248\",\"8\":\"26\",\"9\":\"1\",\"_rn_\":\"7\"},{\"1\":\"10\",\"2\":\"115.0000\",\"3\":\"72.40518\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"35.30000\",\"7\":\"0.134\",\"8\":\"29\",\"9\":\"0\",\"_rn_\":\"8\"},{\"1\":\"2\",\"2\":\"197.0000\",\"3\":\"70.00000\",\"4\":\"45.00000\",\"5\":\"543.0000\",\"6\":\"30.50000\",\"7\":\"0.158\",\"8\":\"53\",\"9\":\"1\",\"_rn_\":\"9\"},{\"1\":\"8\",\"2\":\"125.0000\",\"3\":\"96.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"32.45746\",\"7\":\"0.232\",\"8\":\"54\",\"9\":\"1\",\"_rn_\":\"10\"},{\"1\":\"4\",\"2\":\"110.0000\",\"3\":\"92.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"37.60000\",\"7\":\"0.191\",\"8\":\"30\",\"9\":\"0\",\"_rn_\":\"11\"},{\"1\":\"10\",\"2\":\"168.0000\",\"3\":\"74.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"38.00000\",\"7\":\"0.537\",\"8\":\"34\",\"9\":\"1\",\"_rn_\":\"12\"},{\"1\":\"10\",\"2\":\"139.0000\",\"3\":\"80.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"27.10000\",\"7\":\"1.441\",\"8\":\"57\",\"9\":\"0\",\"_rn_\":\"13\"},{\"1\":\"1\",\"2\":\"189.0000\",\"3\":\"60.00000\",\"4\":\"23.00000\",\"5\":\"846.0000\",\"6\":\"30.10000\",\"7\":\"0.398\",\"8\":\"59\",\"9\":\"1\",\"_rn_\":\"14\"},{\"1\":\"5\",\"2\":\"166.0000\",\"3\":\"72.00000\",\"4\":\"19.00000\",\"5\":\"175.0000\",\"6\":\"25.80000\",\"7\":\"0.587\",\"8\":\"51\",\"9\":\"1\",\"_rn_\":\"15\"},{\"1\":\"7\",\"2\":\"100.0000\",\"3\":\"72.40518\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"30.00000\",\"7\":\"0.484\",\"8\":\"32\",\"9\":\"1\",\"_rn_\":\"16\"},{\"1\":\"0\",\"2\":\"118.0000\",\"3\":\"84.00000\",\"4\":\"47.00000\",\"5\":\"230.0000\",\"6\":\"45.80000\",\"7\":\"0.551\",\"8\":\"31\",\"9\":\"1\",\"_rn_\":\"17\"},{\"1\":\"7\",\"2\":\"107.0000\",\"3\":\"74.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"29.60000\",\"7\":\"0.254\",\"8\":\"31\",\"9\":\"1\",\"_rn_\":\"18\"},{\"1\":\"1\",\"2\":\"103.0000\",\"3\":\"30.00000\",\"4\":\"38.00000\",\"5\":\"83.0000\",\"6\":\"43.30000\",\"7\":\"0.183\",\"8\":\"33\",\"9\":\"0\",\"_rn_\":\"19\"},{\"1\":\"1\",\"2\":\"115.0000\",\"3\":\"70.00000\",\"4\":\"30.00000\",\"5\":\"96.0000\",\"6\":\"34.60000\",\"7\":\"0.529\",\"8\":\"32\",\"9\":\"1\",\"_rn_\":\"20\"},{\"1\":\"3\",\"2\":\"126.0000\",\"3\":\"88.00000\",\"4\":\"41.00000\",\"5\":\"235.0000\",\"6\":\"39.30000\",\"7\":\"0.704\",\"8\":\"27\",\"9\":\"0\",\"_rn_\":\"21\"},{\"1\":\"8\",\"2\":\"99.0000\",\"3\":\"84.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"35.40000\",\"7\":\"0.388\",\"8\":\"50\",\"9\":\"0\",\"_rn_\":\"22\"},{\"1\":\"7\",\"2\":\"196.0000\",\"3\":\"90.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"39.80000\",\"7\":\"0.451\",\"8\":\"41\",\"9\":\"1\",\"_rn_\":\"23\"},{\"1\":\"9\",\"2\":\"119.0000\",\"3\":\"80.00000\",\"4\":\"35.00000\",\"5\":\"155.5482\",\"6\":\"29.00000\",\"7\":\"0.263\",\"8\":\"29\",\"9\":\"1\",\"_rn_\":\"24\"},{\"1\":\"11\",\"2\":\"143.0000\",\"3\":\"94.00000\",\"4\":\"33.00000\",\"5\":\"146.0000\",\"6\":\"36.60000\",\"7\":\"0.254\",\"8\":\"51\",\"9\":\"1\",\"_rn_\":\"25\"},{\"1\":\"10\",\"2\":\"125.0000\",\"3\":\"70.00000\",\"4\":\"26.00000\",\"5\":\"115.0000\",\"6\":\"31.10000\",\"7\":\"0.205\",\"8\":\"41\",\"9\":\"1\",\"_rn_\":\"26\"},{\"1\":\"7\",\"2\":\"147.0000\",\"3\":\"76.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"39.40000\",\"7\":\"0.257\",\"8\":\"43\",\"9\":\"1\",\"_rn_\":\"27\"},{\"1\":\"1\",\"2\":\"97.0000\",\"3\":\"66.00000\",\"4\":\"15.00000\",\"5\":\"140.0000\",\"6\":\"23.20000\",\"7\":\"0.487\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"28\"},{\"1\":\"13\",\"2\":\"145.0000\",\"3\":\"82.00000\",\"4\":\"19.00000\",\"5\":\"110.0000\",\"6\":\"22.20000\",\"7\":\"0.245\",\"8\":\"57\",\"9\":\"0\",\"_rn_\":\"29\"},{\"1\":\"5\",\"2\":\"117.0000\",\"3\":\"92.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"34.10000\",\"7\":\"0.337\",\"8\":\"38\",\"9\":\"0\",\"_rn_\":\"30\"},{\"1\":\"5\",\"2\":\"109.0000\",\"3\":\"75.00000\",\"4\":\"26.00000\",\"5\":\"155.5482\",\"6\":\"36.00000\",\"7\":\"0.546\",\"8\":\"60\",\"9\":\"0\",\"_rn_\":\"31\"},{\"1\":\"3\",\"2\":\"158.0000\",\"3\":\"76.00000\",\"4\":\"36.00000\",\"5\":\"245.0000\",\"6\":\"31.60000\",\"7\":\"0.851\",\"8\":\"28\",\"9\":\"1\",\"_rn_\":\"32\"},{\"1\":\"3\",\"2\":\"88.0000\",\"3\":\"58.00000\",\"4\":\"11.00000\",\"5\":\"54.0000\",\"6\":\"24.80000\",\"7\":\"0.267\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"33\"},{\"1\":\"6\",\"2\":\"92.0000\",\"3\":\"92.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"19.90000\",\"7\":\"0.188\",\"8\":\"28\",\"9\":\"0\",\"_rn_\":\"34\"},{\"1\":\"10\",\"2\":\"122.0000\",\"3\":\"78.00000\",\"4\":\"31.00000\",\"5\":\"155.5482\",\"6\":\"27.60000\",\"7\":\"0.512\",\"8\":\"45\",\"9\":\"0\",\"_rn_\":\"35\"},{\"1\":\"4\",\"2\":\"103.0000\",\"3\":\"60.00000\",\"4\":\"33.00000\",\"5\":\"192.0000\",\"6\":\"24.00000\",\"7\":\"0.966\",\"8\":\"33\",\"9\":\"0\",\"_rn_\":\"36\"},{\"1\":\"11\",\"2\":\"138.0000\",\"3\":\"76.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"33.20000\",\"7\":\"0.420\",\"8\":\"35\",\"9\":\"0\",\"_rn_\":\"37\"},{\"1\":\"9\",\"2\":\"102.0000\",\"3\":\"76.00000\",\"4\":\"37.00000\",\"5\":\"155.5482\",\"6\":\"32.90000\",\"7\":\"0.665\",\"8\":\"46\",\"9\":\"1\",\"_rn_\":\"38\"},{\"1\":\"2\",\"2\":\"90.0000\",\"3\":\"68.00000\",\"4\":\"42.00000\",\"5\":\"155.5482\",\"6\":\"38.20000\",\"7\":\"0.503\",\"8\":\"27\",\"9\":\"1\",\"_rn_\":\"39\"},{\"1\":\"4\",\"2\":\"111.0000\",\"3\":\"72.00000\",\"4\":\"47.00000\",\"5\":\"207.0000\",\"6\":\"37.10000\",\"7\":\"1.390\",\"8\":\"56\",\"9\":\"1\",\"_rn_\":\"40\"},{\"1\":\"3\",\"2\":\"180.0000\",\"3\":\"64.00000\",\"4\":\"25.00000\",\"5\":\"70.0000\",\"6\":\"34.00000\",\"7\":\"0.271\",\"8\":\"26\",\"9\":\"0\",\"_rn_\":\"41\"},{\"1\":\"7\",\"2\":\"133.0000\",\"3\":\"84.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"40.20000\",\"7\":\"0.696\",\"8\":\"37\",\"9\":\"0\",\"_rn_\":\"42\"},{\"1\":\"7\",\"2\":\"106.0000\",\"3\":\"92.00000\",\"4\":\"18.00000\",\"5\":\"155.5482\",\"6\":\"22.70000\",\"7\":\"0.235\",\"8\":\"48\",\"9\":\"0\",\"_rn_\":\"43\"},{\"1\":\"9\",\"2\":\"171.0000\",\"3\":\"110.00000\",\"4\":\"24.00000\",\"5\":\"240.0000\",\"6\":\"45.40000\",\"7\":\"0.721\",\"8\":\"54\",\"9\":\"1\",\"_rn_\":\"44\"},{\"1\":\"7\",\"2\":\"159.0000\",\"3\":\"64.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"27.40000\",\"7\":\"0.294\",\"8\":\"40\",\"9\":\"0\",\"_rn_\":\"45\"},{\"1\":\"0\",\"2\":\"180.0000\",\"3\":\"66.00000\",\"4\":\"39.00000\",\"5\":\"155.5482\",\"6\":\"42.00000\",\"7\":\"1.893\",\"8\":\"25\",\"9\":\"1\",\"_rn_\":\"46\"},{\"1\":\"1\",\"2\":\"146.0000\",\"3\":\"56.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"29.70000\",\"7\":\"0.564\",\"8\":\"29\",\"9\":\"0\",\"_rn_\":\"47\"},{\"1\":\"2\",\"2\":\"71.0000\",\"3\":\"70.00000\",\"4\":\"27.00000\",\"5\":\"155.5482\",\"6\":\"28.00000\",\"7\":\"0.586\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"48\"},{\"1\":\"7\",\"2\":\"103.0000\",\"3\":\"66.00000\",\"4\":\"32.00000\",\"5\":\"155.5482\",\"6\":\"39.10000\",\"7\":\"0.344\",\"8\":\"31\",\"9\":\"1\",\"_rn_\":\"49\"},{\"1\":\"7\",\"2\":\"105.0000\",\"3\":\"72.40518\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"32.45746\",\"7\":\"0.305\",\"8\":\"24\",\"9\":\"0\",\"_rn_\":\"50\"},{\"1\":\"1\",\"2\":\"103.0000\",\"3\":\"80.00000\",\"4\":\"11.00000\",\"5\":\"82.0000\",\"6\":\"19.40000\",\"7\":\"0.491\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"51\"},{\"1\":\"1\",\"2\":\"101.0000\",\"3\":\"50.00000\",\"4\":\"15.00000\",\"5\":\"36.0000\",\"6\":\"24.20000\",\"7\":\"0.526\",\"8\":\"26\",\"9\":\"0\",\"_rn_\":\"52\"},{\"1\":\"5\",\"2\":\"88.0000\",\"3\":\"66.00000\",\"4\":\"21.00000\",\"5\":\"23.0000\",\"6\":\"24.40000\",\"7\":\"0.342\",\"8\":\"30\",\"9\":\"0\",\"_rn_\":\"53\"},{\"1\":\"8\",\"2\":\"176.0000\",\"3\":\"90.00000\",\"4\":\"34.00000\",\"5\":\"300.0000\",\"6\":\"33.70000\",\"7\":\"0.467\",\"8\":\"58\",\"9\":\"1\",\"_rn_\":\"54\"},{\"1\":\"7\",\"2\":\"150.0000\",\"3\":\"66.00000\",\"4\":\"42.00000\",\"5\":\"342.0000\",\"6\":\"34.70000\",\"7\":\"0.718\",\"8\":\"42\",\"9\":\"0\",\"_rn_\":\"55\"},{\"1\":\"1\",\"2\":\"73.0000\",\"3\":\"50.00000\",\"4\":\"10.00000\",\"5\":\"155.5482\",\"6\":\"23.00000\",\"7\":\"0.248\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"56\"},{\"1\":\"7\",\"2\":\"187.0000\",\"3\":\"68.00000\",\"4\":\"39.00000\",\"5\":\"304.0000\",\"6\":\"37.70000\",\"7\":\"0.254\",\"8\":\"41\",\"9\":\"1\",\"_rn_\":\"57\"},{\"1\":\"0\",\"2\":\"100.0000\",\"3\":\"88.00000\",\"4\":\"60.00000\",\"5\":\"110.0000\",\"6\":\"46.80000\",\"7\":\"0.962\",\"8\":\"31\",\"9\":\"0\",\"_rn_\":\"58\"},{\"1\":\"0\",\"2\":\"146.0000\",\"3\":\"82.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"40.50000\",\"7\":\"1.781\",\"8\":\"44\",\"9\":\"0\",\"_rn_\":\"59\"},{\"1\":\"0\",\"2\":\"105.0000\",\"3\":\"64.00000\",\"4\":\"41.00000\",\"5\":\"142.0000\",\"6\":\"41.50000\",\"7\":\"0.173\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"60\"},{\"1\":\"2\",\"2\":\"84.0000\",\"3\":\"72.40518\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"32.45746\",\"7\":\"0.304\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"61\"},{\"1\":\"8\",\"2\":\"133.0000\",\"3\":\"72.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"32.90000\",\"7\":\"0.270\",\"8\":\"39\",\"9\":\"1\",\"_rn_\":\"62\"},{\"1\":\"5\",\"2\":\"44.0000\",\"3\":\"62.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"25.00000\",\"7\":\"0.587\",\"8\":\"36\",\"9\":\"0\",\"_rn_\":\"63\"},{\"1\":\"2\",\"2\":\"141.0000\",\"3\":\"58.00000\",\"4\":\"34.00000\",\"5\":\"128.0000\",\"6\":\"25.40000\",\"7\":\"0.699\",\"8\":\"24\",\"9\":\"0\",\"_rn_\":\"64\"},{\"1\":\"7\",\"2\":\"114.0000\",\"3\":\"66.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"32.80000\",\"7\":\"0.258\",\"8\":\"42\",\"9\":\"1\",\"_rn_\":\"65\"},{\"1\":\"5\",\"2\":\"99.0000\",\"3\":\"74.00000\",\"4\":\"27.00000\",\"5\":\"155.5482\",\"6\":\"29.00000\",\"7\":\"0.203\",\"8\":\"32\",\"9\":\"0\",\"_rn_\":\"66\"},{\"1\":\"0\",\"2\":\"109.0000\",\"3\":\"88.00000\",\"4\":\"30.00000\",\"5\":\"155.5482\",\"6\":\"32.50000\",\"7\":\"0.855\",\"8\":\"38\",\"9\":\"1\",\"_rn_\":\"67\"},{\"1\":\"2\",\"2\":\"109.0000\",\"3\":\"92.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"42.70000\",\"7\":\"0.845\",\"8\":\"54\",\"9\":\"0\",\"_rn_\":\"68\"},{\"1\":\"1\",\"2\":\"95.0000\",\"3\":\"66.00000\",\"4\":\"13.00000\",\"5\":\"38.0000\",\"6\":\"19.60000\",\"7\":\"0.334\",\"8\":\"25\",\"9\":\"0\",\"_rn_\":\"69\"},{\"1\":\"4\",\"2\":\"146.0000\",\"3\":\"85.00000\",\"4\":\"27.00000\",\"5\":\"100.0000\",\"6\":\"28.90000\",\"7\":\"0.189\",\"8\":\"27\",\"9\":\"0\",\"_rn_\":\"70\"},{\"1\":\"2\",\"2\":\"100.0000\",\"3\":\"66.00000\",\"4\":\"20.00000\",\"5\":\"90.0000\",\"6\":\"32.90000\",\"7\":\"0.867\",\"8\":\"28\",\"9\":\"1\",\"_rn_\":\"71\"},{\"1\":\"5\",\"2\":\"139.0000\",\"3\":\"64.00000\",\"4\":\"35.00000\",\"5\":\"140.0000\",\"6\":\"28.60000\",\"7\":\"0.411\",\"8\":\"26\",\"9\":\"0\",\"_rn_\":\"72\"},{\"1\":\"13\",\"2\":\"126.0000\",\"3\":\"90.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"43.40000\",\"7\":\"0.583\",\"8\":\"42\",\"9\":\"1\",\"_rn_\":\"73\"},{\"1\":\"4\",\"2\":\"129.0000\",\"3\":\"86.00000\",\"4\":\"20.00000\",\"5\":\"270.0000\",\"6\":\"35.10000\",\"7\":\"0.231\",\"8\":\"23\",\"9\":\"0\",\"_rn_\":\"74\"},{\"1\":\"1\",\"2\":\"79.0000\",\"3\":\"75.00000\",\"4\":\"30.00000\",\"5\":\"155.5482\",\"6\":\"32.00000\",\"7\":\"0.396\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"75\"},{\"1\":\"1\",\"2\":\"121.6868\",\"3\":\"48.00000\",\"4\":\"20.00000\",\"5\":\"155.5482\",\"6\":\"24.70000\",\"7\":\"0.140\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"76\"},{\"1\":\"7\",\"2\":\"62.0000\",\"3\":\"78.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"32.60000\",\"7\":\"0.391\",\"8\":\"41\",\"9\":\"0\",\"_rn_\":\"77\"},{\"1\":\"5\",\"2\":\"95.0000\",\"3\":\"72.00000\",\"4\":\"33.00000\",\"5\":\"155.5482\",\"6\":\"37.70000\",\"7\":\"0.370\",\"8\":\"27\",\"9\":\"0\",\"_rn_\":\"78\"},{\"1\":\"0\",\"2\":\"131.0000\",\"3\":\"72.40518\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"43.20000\",\"7\":\"0.270\",\"8\":\"26\",\"9\":\"1\",\"_rn_\":\"79\"},{\"1\":\"2\",\"2\":\"112.0000\",\"3\":\"66.00000\",\"4\":\"22.00000\",\"5\":\"155.5482\",\"6\":\"25.00000\",\"7\":\"0.307\",\"8\":\"24\",\"9\":\"0\",\"_rn_\":\"80\"},{\"1\":\"3\",\"2\":\"113.0000\",\"3\":\"44.00000\",\"4\":\"13.00000\",\"5\":\"155.5482\",\"6\":\"22.40000\",\"7\":\"0.140\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"81\"},{\"1\":\"2\",\"2\":\"74.0000\",\"3\":\"72.40518\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"32.45746\",\"7\":\"0.102\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"82\"},{\"1\":\"7\",\"2\":\"83.0000\",\"3\":\"78.00000\",\"4\":\"26.00000\",\"5\":\"71.0000\",\"6\":\"29.30000\",\"7\":\"0.767\",\"8\":\"36\",\"9\":\"0\",\"_rn_\":\"83\"},{\"1\":\"0\",\"2\":\"101.0000\",\"3\":\"65.00000\",\"4\":\"28.00000\",\"5\":\"155.5482\",\"6\":\"24.60000\",\"7\":\"0.237\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"84\"},{\"1\":\"5\",\"2\":\"137.0000\",\"3\":\"108.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"48.80000\",\"7\":\"0.227\",\"8\":\"37\",\"9\":\"1\",\"_rn_\":\"85\"},{\"1\":\"2\",\"2\":\"110.0000\",\"3\":\"74.00000\",\"4\":\"29.00000\",\"5\":\"125.0000\",\"6\":\"32.40000\",\"7\":\"0.698\",\"8\":\"27\",\"9\":\"0\",\"_rn_\":\"86\"},{\"1\":\"13\",\"2\":\"106.0000\",\"3\":\"72.00000\",\"4\":\"54.00000\",\"5\":\"155.5482\",\"6\":\"36.60000\",\"7\":\"0.178\",\"8\":\"45\",\"9\":\"0\",\"_rn_\":\"87\"},{\"1\":\"2\",\"2\":\"100.0000\",\"3\":\"68.00000\",\"4\":\"25.00000\",\"5\":\"71.0000\",\"6\":\"38.50000\",\"7\":\"0.324\",\"8\":\"26\",\"9\":\"0\",\"_rn_\":\"88\"},{\"1\":\"15\",\"2\":\"136.0000\",\"3\":\"70.00000\",\"4\":\"32.00000\",\"5\":\"110.0000\",\"6\":\"37.10000\",\"7\":\"0.153\",\"8\":\"43\",\"9\":\"1\",\"_rn_\":\"89\"},{\"1\":\"1\",\"2\":\"107.0000\",\"3\":\"68.00000\",\"4\":\"19.00000\",\"5\":\"155.5482\",\"6\":\"26.50000\",\"7\":\"0.165\",\"8\":\"24\",\"9\":\"0\",\"_rn_\":\"90\"},{\"1\":\"1\",\"2\":\"80.0000\",\"3\":\"55.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"19.10000\",\"7\":\"0.258\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"91\"},{\"1\":\"4\",\"2\":\"123.0000\",\"3\":\"80.00000\",\"4\":\"15.00000\",\"5\":\"176.0000\",\"6\":\"32.00000\",\"7\":\"0.443\",\"8\":\"34\",\"9\":\"0\",\"_rn_\":\"92\"},{\"1\":\"7\",\"2\":\"81.0000\",\"3\":\"78.00000\",\"4\":\"40.00000\",\"5\":\"48.0000\",\"6\":\"46.70000\",\"7\":\"0.261\",\"8\":\"42\",\"9\":\"0\",\"_rn_\":\"93\"},{\"1\":\"4\",\"2\":\"134.0000\",\"3\":\"72.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"23.80000\",\"7\":\"0.277\",\"8\":\"60\",\"9\":\"1\",\"_rn_\":\"94\"},{\"1\":\"2\",\"2\":\"142.0000\",\"3\":\"82.00000\",\"4\":\"18.00000\",\"5\":\"64.0000\",\"6\":\"24.70000\",\"7\":\"0.761\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"95\"},{\"1\":\"6\",\"2\":\"144.0000\",\"3\":\"72.00000\",\"4\":\"27.00000\",\"5\":\"228.0000\",\"6\":\"33.90000\",\"7\":\"0.255\",\"8\":\"40\",\"9\":\"0\",\"_rn_\":\"96\"},{\"1\":\"2\",\"2\":\"92.0000\",\"3\":\"62.00000\",\"4\":\"28.00000\",\"5\":\"155.5482\",\"6\":\"31.60000\",\"7\":\"0.130\",\"8\":\"24\",\"9\":\"0\",\"_rn_\":\"97\"},{\"1\":\"1\",\"2\":\"71.0000\",\"3\":\"48.00000\",\"4\":\"18.00000\",\"5\":\"76.0000\",\"6\":\"20.40000\",\"7\":\"0.323\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"98\"},{\"1\":\"6\",\"2\":\"93.0000\",\"3\":\"50.00000\",\"4\":\"30.00000\",\"5\":\"64.0000\",\"6\":\"28.70000\",\"7\":\"0.356\",\"8\":\"23\",\"9\":\"0\",\"_rn_\":\"99\"},{\"1\":\"1\",\"2\":\"122.0000\",\"3\":\"90.00000\",\"4\":\"51.00000\",\"5\":\"220.0000\",\"6\":\"49.70000\",\"7\":\"0.325\",\"8\":\"31\",\"9\":\"1\",\"_rn_\":\"100\"},{\"1\":\"1\",\"2\":\"163.0000\",\"3\":\"72.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"39.00000\",\"7\":\"1.222\",\"8\":\"33\",\"9\":\"1\",\"_rn_\":\"101\"},{\"1\":\"1\",\"2\":\"151.0000\",\"3\":\"60.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"26.10000\",\"7\":\"0.179\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"102\"},{\"1\":\"0\",\"2\":\"125.0000\",\"3\":\"96.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"22.50000\",\"7\":\"0.262\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"103\"},{\"1\":\"1\",\"2\":\"81.0000\",\"3\":\"72.00000\",\"4\":\"18.00000\",\"5\":\"40.0000\",\"6\":\"26.60000\",\"7\":\"0.283\",\"8\":\"24\",\"9\":\"0\",\"_rn_\":\"104\"},{\"1\":\"2\",\"2\":\"85.0000\",\"3\":\"65.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"39.60000\",\"7\":\"0.930\",\"8\":\"27\",\"9\":\"0\",\"_rn_\":\"105\"},{\"1\":\"1\",\"2\":\"126.0000\",\"3\":\"56.00000\",\"4\":\"29.00000\",\"5\":\"152.0000\",\"6\":\"28.70000\",\"7\":\"0.801\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"106\"},{\"1\":\"1\",\"2\":\"96.0000\",\"3\":\"122.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"22.40000\",\"7\":\"0.207\",\"8\":\"27\",\"9\":\"0\",\"_rn_\":\"107\"},{\"1\":\"4\",\"2\":\"144.0000\",\"3\":\"58.00000\",\"4\":\"28.00000\",\"5\":\"140.0000\",\"6\":\"29.50000\",\"7\":\"0.287\",\"8\":\"37\",\"9\":\"0\",\"_rn_\":\"108\"},{\"1\":\"3\",\"2\":\"83.0000\",\"3\":\"58.00000\",\"4\":\"31.00000\",\"5\":\"18.0000\",\"6\":\"34.30000\",\"7\":\"0.336\",\"8\":\"25\",\"9\":\"0\",\"_rn_\":\"109\"},{\"1\":\"0\",\"2\":\"95.0000\",\"3\":\"85.00000\",\"4\":\"25.00000\",\"5\":\"36.0000\",\"6\":\"37.40000\",\"7\":\"0.247\",\"8\":\"24\",\"9\":\"1\",\"_rn_\":\"110\"},{\"1\":\"3\",\"2\":\"171.0000\",\"3\":\"72.00000\",\"4\":\"33.00000\",\"5\":\"135.0000\",\"6\":\"33.30000\",\"7\":\"0.199\",\"8\":\"24\",\"9\":\"1\",\"_rn_\":\"111\"},{\"1\":\"8\",\"2\":\"155.0000\",\"3\":\"62.00000\",\"4\":\"26.00000\",\"5\":\"495.0000\",\"6\":\"34.00000\",\"7\":\"0.543\",\"8\":\"46\",\"9\":\"1\",\"_rn_\":\"112\"},{\"1\":\"1\",\"2\":\"89.0000\",\"3\":\"76.00000\",\"4\":\"34.00000\",\"5\":\"37.0000\",\"6\":\"31.20000\",\"7\":\"0.192\",\"8\":\"23\",\"9\":\"0\",\"_rn_\":\"113\"},{\"1\":\"4\",\"2\":\"76.0000\",\"3\":\"62.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"34.00000\",\"7\":\"0.391\",\"8\":\"25\",\"9\":\"0\",\"_rn_\":\"114\"},{\"1\":\"7\",\"2\":\"160.0000\",\"3\":\"54.00000\",\"4\":\"32.00000\",\"5\":\"175.0000\",\"6\":\"30.50000\",\"7\":\"0.588\",\"8\":\"39\",\"9\":\"1\",\"_rn_\":\"115\"},{\"1\":\"4\",\"2\":\"146.0000\",\"3\":\"92.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"31.20000\",\"7\":\"0.539\",\"8\":\"61\",\"9\":\"1\",\"_rn_\":\"116\"},{\"1\":\"5\",\"2\":\"124.0000\",\"3\":\"74.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"34.00000\",\"7\":\"0.220\",\"8\":\"38\",\"9\":\"1\",\"_rn_\":\"117\"},{\"1\":\"5\",\"2\":\"78.0000\",\"3\":\"48.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"33.70000\",\"7\":\"0.654\",\"8\":\"25\",\"9\":\"0\",\"_rn_\":\"118\"},{\"1\":\"4\",\"2\":\"97.0000\",\"3\":\"60.00000\",\"4\":\"23.00000\",\"5\":\"155.5482\",\"6\":\"28.20000\",\"7\":\"0.443\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"119\"},{\"1\":\"4\",\"2\":\"99.0000\",\"3\":\"76.00000\",\"4\":\"15.00000\",\"5\":\"51.0000\",\"6\":\"23.20000\",\"7\":\"0.223\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"120\"},{\"1\":\"0\",\"2\":\"162.0000\",\"3\":\"76.00000\",\"4\":\"56.00000\",\"5\":\"100.0000\",\"6\":\"53.20000\",\"7\":\"0.759\",\"8\":\"25\",\"9\":\"1\",\"_rn_\":\"121\"},{\"1\":\"6\",\"2\":\"111.0000\",\"3\":\"64.00000\",\"4\":\"39.00000\",\"5\":\"155.5482\",\"6\":\"34.20000\",\"7\":\"0.260\",\"8\":\"24\",\"9\":\"0\",\"_rn_\":\"122\"},{\"1\":\"2\",\"2\":\"107.0000\",\"3\":\"74.00000\",\"4\":\"30.00000\",\"5\":\"100.0000\",\"6\":\"33.60000\",\"7\":\"0.404\",\"8\":\"23\",\"9\":\"0\",\"_rn_\":\"123\"},{\"1\":\"5\",\"2\":\"132.0000\",\"3\":\"80.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"26.80000\",\"7\":\"0.186\",\"8\":\"69\",\"9\":\"0\",\"_rn_\":\"124\"},{\"1\":\"0\",\"2\":\"113.0000\",\"3\":\"76.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"33.30000\",\"7\":\"0.278\",\"8\":\"23\",\"9\":\"1\",\"_rn_\":\"125\"},{\"1\":\"1\",\"2\":\"88.0000\",\"3\":\"30.00000\",\"4\":\"42.00000\",\"5\":\"99.0000\",\"6\":\"55.00000\",\"7\":\"0.496\",\"8\":\"26\",\"9\":\"1\",\"_rn_\":\"126\"},{\"1\":\"3\",\"2\":\"120.0000\",\"3\":\"70.00000\",\"4\":\"30.00000\",\"5\":\"135.0000\",\"6\":\"42.90000\",\"7\":\"0.452\",\"8\":\"30\",\"9\":\"0\",\"_rn_\":\"127\"},{\"1\":\"1\",\"2\":\"118.0000\",\"3\":\"58.00000\",\"4\":\"36.00000\",\"5\":\"94.0000\",\"6\":\"33.30000\",\"7\":\"0.261\",\"8\":\"23\",\"9\":\"0\",\"_rn_\":\"128\"},{\"1\":\"1\",\"2\":\"117.0000\",\"3\":\"88.00000\",\"4\":\"24.00000\",\"5\":\"145.0000\",\"6\":\"34.50000\",\"7\":\"0.403\",\"8\":\"40\",\"9\":\"1\",\"_rn_\":\"129\"},{\"1\":\"0\",\"2\":\"105.0000\",\"3\":\"84.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"27.90000\",\"7\":\"0.741\",\"8\":\"62\",\"9\":\"1\",\"_rn_\":\"130\"},{\"1\":\"4\",\"2\":\"173.0000\",\"3\":\"70.00000\",\"4\":\"14.00000\",\"5\":\"168.0000\",\"6\":\"29.70000\",\"7\":\"0.361\",\"8\":\"33\",\"9\":\"1\",\"_rn_\":\"131\"},{\"1\":\"9\",\"2\":\"122.0000\",\"3\":\"56.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"33.30000\",\"7\":\"1.114\",\"8\":\"33\",\"9\":\"1\",\"_rn_\":\"132\"},{\"1\":\"3\",\"2\":\"170.0000\",\"3\":\"64.00000\",\"4\":\"37.00000\",\"5\":\"225.0000\",\"6\":\"34.50000\",\"7\":\"0.356\",\"8\":\"30\",\"9\":\"1\",\"_rn_\":\"133\"},{\"1\":\"8\",\"2\":\"84.0000\",\"3\":\"74.00000\",\"4\":\"31.00000\",\"5\":\"155.5482\",\"6\":\"38.30000\",\"7\":\"0.457\",\"8\":\"39\",\"9\":\"0\",\"_rn_\":\"134\"},{\"1\":\"2\",\"2\":\"96.0000\",\"3\":\"68.00000\",\"4\":\"13.00000\",\"5\":\"49.0000\",\"6\":\"21.10000\",\"7\":\"0.647\",\"8\":\"26\",\"9\":\"0\",\"_rn_\":\"135\"},{\"1\":\"2\",\"2\":\"125.0000\",\"3\":\"60.00000\",\"4\":\"20.00000\",\"5\":\"140.0000\",\"6\":\"33.80000\",\"7\":\"0.088\",\"8\":\"31\",\"9\":\"0\",\"_rn_\":\"136\"},{\"1\":\"0\",\"2\":\"100.0000\",\"3\":\"70.00000\",\"4\":\"26.00000\",\"5\":\"50.0000\",\"6\":\"30.80000\",\"7\":\"0.597\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"137\"},{\"1\":\"0\",\"2\":\"93.0000\",\"3\":\"60.00000\",\"4\":\"25.00000\",\"5\":\"92.0000\",\"6\":\"28.70000\",\"7\":\"0.532\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"138\"},{\"1\":\"0\",\"2\":\"129.0000\",\"3\":\"80.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"31.20000\",\"7\":\"0.703\",\"8\":\"29\",\"9\":\"0\",\"_rn_\":\"139\"},{\"1\":\"5\",\"2\":\"105.0000\",\"3\":\"72.00000\",\"4\":\"29.00000\",\"5\":\"325.0000\",\"6\":\"36.90000\",\"7\":\"0.159\",\"8\":\"28\",\"9\":\"0\",\"_rn_\":\"140\"},{\"1\":\"3\",\"2\":\"128.0000\",\"3\":\"78.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"21.10000\",\"7\":\"0.268\",\"8\":\"55\",\"9\":\"0\",\"_rn_\":\"141\"},{\"1\":\"5\",\"2\":\"106.0000\",\"3\":\"82.00000\",\"4\":\"30.00000\",\"5\":\"155.5482\",\"6\":\"39.50000\",\"7\":\"0.286\",\"8\":\"38\",\"9\":\"0\",\"_rn_\":\"142\"},{\"1\":\"2\",\"2\":\"108.0000\",\"3\":\"52.00000\",\"4\":\"26.00000\",\"5\":\"63.0000\",\"6\":\"32.50000\",\"7\":\"0.318\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"143\"},{\"1\":\"10\",\"2\":\"108.0000\",\"3\":\"66.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"32.40000\",\"7\":\"0.272\",\"8\":\"42\",\"9\":\"1\",\"_rn_\":\"144\"},{\"1\":\"4\",\"2\":\"154.0000\",\"3\":\"62.00000\",\"4\":\"31.00000\",\"5\":\"284.0000\",\"6\":\"32.80000\",\"7\":\"0.237\",\"8\":\"23\",\"9\":\"0\",\"_rn_\":\"145\"},{\"1\":\"0\",\"2\":\"102.0000\",\"3\":\"75.00000\",\"4\":\"23.00000\",\"5\":\"155.5482\",\"6\":\"32.45746\",\"7\":\"0.572\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"146\"},{\"1\":\"9\",\"2\":\"57.0000\",\"3\":\"80.00000\",\"4\":\"37.00000\",\"5\":\"155.5482\",\"6\":\"32.80000\",\"7\":\"0.096\",\"8\":\"41\",\"9\":\"0\",\"_rn_\":\"147\"},{\"1\":\"2\",\"2\":\"106.0000\",\"3\":\"64.00000\",\"4\":\"35.00000\",\"5\":\"119.0000\",\"6\":\"30.50000\",\"7\":\"1.400\",\"8\":\"34\",\"9\":\"0\",\"_rn_\":\"148\"},{\"1\":\"5\",\"2\":\"147.0000\",\"3\":\"78.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"33.70000\",\"7\":\"0.218\",\"8\":\"65\",\"9\":\"0\",\"_rn_\":\"149\"},{\"1\":\"2\",\"2\":\"90.0000\",\"3\":\"70.00000\",\"4\":\"17.00000\",\"5\":\"155.5482\",\"6\":\"27.30000\",\"7\":\"0.085\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"150\"},{\"1\":\"1\",\"2\":\"136.0000\",\"3\":\"74.00000\",\"4\":\"50.00000\",\"5\":\"204.0000\",\"6\":\"37.40000\",\"7\":\"0.399\",\"8\":\"24\",\"9\":\"0\",\"_rn_\":\"151\"},{\"1\":\"4\",\"2\":\"114.0000\",\"3\":\"65.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"21.90000\",\"7\":\"0.432\",\"8\":\"37\",\"9\":\"0\",\"_rn_\":\"152\"},{\"1\":\"9\",\"2\":\"156.0000\",\"3\":\"86.00000\",\"4\":\"28.00000\",\"5\":\"155.0000\",\"6\":\"34.30000\",\"7\":\"1.189\",\"8\":\"42\",\"9\":\"1\",\"_rn_\":\"153\"},{\"1\":\"1\",\"2\":\"153.0000\",\"3\":\"82.00000\",\"4\":\"42.00000\",\"5\":\"485.0000\",\"6\":\"40.60000\",\"7\":\"0.687\",\"8\":\"23\",\"9\":\"0\",\"_rn_\":\"154\"},{\"1\":\"8\",\"2\":\"188.0000\",\"3\":\"78.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"47.90000\",\"7\":\"0.137\",\"8\":\"43\",\"9\":\"1\",\"_rn_\":\"155\"},{\"1\":\"7\",\"2\":\"152.0000\",\"3\":\"88.00000\",\"4\":\"44.00000\",\"5\":\"155.5482\",\"6\":\"50.00000\",\"7\":\"0.337\",\"8\":\"36\",\"9\":\"1\",\"_rn_\":\"156\"},{\"1\":\"2\",\"2\":\"99.0000\",\"3\":\"52.00000\",\"4\":\"15.00000\",\"5\":\"94.0000\",\"6\":\"24.60000\",\"7\":\"0.637\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"157\"},{\"1\":\"1\",\"2\":\"109.0000\",\"3\":\"56.00000\",\"4\":\"21.00000\",\"5\":\"135.0000\",\"6\":\"25.20000\",\"7\":\"0.833\",\"8\":\"23\",\"9\":\"0\",\"_rn_\":\"158\"},{\"1\":\"2\",\"2\":\"88.0000\",\"3\":\"74.00000\",\"4\":\"19.00000\",\"5\":\"53.0000\",\"6\":\"29.00000\",\"7\":\"0.229\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"159\"},{\"1\":\"17\",\"2\":\"163.0000\",\"3\":\"72.00000\",\"4\":\"41.00000\",\"5\":\"114.0000\",\"6\":\"40.90000\",\"7\":\"0.817\",\"8\":\"47\",\"9\":\"1\",\"_rn_\":\"160\"},{\"1\":\"4\",\"2\":\"151.0000\",\"3\":\"90.00000\",\"4\":\"38.00000\",\"5\":\"155.5482\",\"6\":\"29.70000\",\"7\":\"0.294\",\"8\":\"36\",\"9\":\"0\",\"_rn_\":\"161\"},{\"1\":\"7\",\"2\":\"102.0000\",\"3\":\"74.00000\",\"4\":\"40.00000\",\"5\":\"105.0000\",\"6\":\"37.20000\",\"7\":\"0.204\",\"8\":\"45\",\"9\":\"0\",\"_rn_\":\"162\"},{\"1\":\"0\",\"2\":\"114.0000\",\"3\":\"80.00000\",\"4\":\"34.00000\",\"5\":\"285.0000\",\"6\":\"44.20000\",\"7\":\"0.167\",\"8\":\"27\",\"9\":\"0\",\"_rn_\":\"163\"},{\"1\":\"2\",\"2\":\"100.0000\",\"3\":\"64.00000\",\"4\":\"23.00000\",\"5\":\"155.5482\",\"6\":\"29.70000\",\"7\":\"0.368\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"164\"},{\"1\":\"0\",\"2\":\"131.0000\",\"3\":\"88.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"31.60000\",\"7\":\"0.743\",\"8\":\"32\",\"9\":\"1\",\"_rn_\":\"165\"},{\"1\":\"6\",\"2\":\"104.0000\",\"3\":\"74.00000\",\"4\":\"18.00000\",\"5\":\"156.0000\",\"6\":\"29.90000\",\"7\":\"0.722\",\"8\":\"41\",\"9\":\"1\",\"_rn_\":\"166\"},{\"1\":\"3\",\"2\":\"148.0000\",\"3\":\"66.00000\",\"4\":\"25.00000\",\"5\":\"155.5482\",\"6\":\"32.50000\",\"7\":\"0.256\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"167\"},{\"1\":\"4\",\"2\":\"120.0000\",\"3\":\"68.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"29.60000\",\"7\":\"0.709\",\"8\":\"34\",\"9\":\"0\",\"_rn_\":\"168\"},{\"1\":\"4\",\"2\":\"110.0000\",\"3\":\"66.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"31.90000\",\"7\":\"0.471\",\"8\":\"29\",\"9\":\"0\",\"_rn_\":\"169\"},{\"1\":\"3\",\"2\":\"111.0000\",\"3\":\"90.00000\",\"4\":\"12.00000\",\"5\":\"78.0000\",\"6\":\"28.40000\",\"7\":\"0.495\",\"8\":\"29\",\"9\":\"0\",\"_rn_\":\"170\"},{\"1\":\"6\",\"2\":\"102.0000\",\"3\":\"82.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"30.80000\",\"7\":\"0.180\",\"8\":\"36\",\"9\":\"1\",\"_rn_\":\"171\"},{\"1\":\"6\",\"2\":\"134.0000\",\"3\":\"70.00000\",\"4\":\"23.00000\",\"5\":\"130.0000\",\"6\":\"35.40000\",\"7\":\"0.542\",\"8\":\"29\",\"9\":\"1\",\"_rn_\":\"172\"},{\"1\":\"2\",\"2\":\"87.0000\",\"3\":\"72.40518\",\"4\":\"23.00000\",\"5\":\"155.5482\",\"6\":\"28.90000\",\"7\":\"0.773\",\"8\":\"25\",\"9\":\"0\",\"_rn_\":\"173\"},{\"1\":\"1\",\"2\":\"79.0000\",\"3\":\"60.00000\",\"4\":\"42.00000\",\"5\":\"48.0000\",\"6\":\"43.50000\",\"7\":\"0.678\",\"8\":\"23\",\"9\":\"0\",\"_rn_\":\"174\"},{\"1\":\"2\",\"2\":\"75.0000\",\"3\":\"64.00000\",\"4\":\"24.00000\",\"5\":\"55.0000\",\"6\":\"29.70000\",\"7\":\"0.370\",\"8\":\"33\",\"9\":\"0\",\"_rn_\":\"175\"},{\"1\":\"8\",\"2\":\"179.0000\",\"3\":\"72.00000\",\"4\":\"42.00000\",\"5\":\"130.0000\",\"6\":\"32.70000\",\"7\":\"0.719\",\"8\":\"36\",\"9\":\"1\",\"_rn_\":\"176\"},{\"1\":\"6\",\"2\":\"85.0000\",\"3\":\"78.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"31.20000\",\"7\":\"0.382\",\"8\":\"42\",\"9\":\"0\",\"_rn_\":\"177\"},{\"1\":\"0\",\"2\":\"129.0000\",\"3\":\"110.00000\",\"4\":\"46.00000\",\"5\":\"130.0000\",\"6\":\"67.10000\",\"7\":\"0.319\",\"8\":\"26\",\"9\":\"1\",\"_rn_\":\"178\"},{\"1\":\"5\",\"2\":\"143.0000\",\"3\":\"78.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"45.00000\",\"7\":\"0.190\",\"8\":\"47\",\"9\":\"0\",\"_rn_\":\"179\"},{\"1\":\"5\",\"2\":\"130.0000\",\"3\":\"82.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"39.10000\",\"7\":\"0.956\",\"8\":\"37\",\"9\":\"1\",\"_rn_\":\"180\"},{\"1\":\"6\",\"2\":\"87.0000\",\"3\":\"80.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"23.20000\",\"7\":\"0.084\",\"8\":\"32\",\"9\":\"0\",\"_rn_\":\"181\"},{\"1\":\"0\",\"2\":\"119.0000\",\"3\":\"64.00000\",\"4\":\"18.00000\",\"5\":\"92.0000\",\"6\":\"34.90000\",\"7\":\"0.725\",\"8\":\"23\",\"9\":\"0\",\"_rn_\":\"182\"},{\"1\":\"1\",\"2\":\"121.6868\",\"3\":\"74.00000\",\"4\":\"20.00000\",\"5\":\"23.0000\",\"6\":\"27.70000\",\"7\":\"0.299\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"183\"},{\"1\":\"5\",\"2\":\"73.0000\",\"3\":\"60.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"26.80000\",\"7\":\"0.268\",\"8\":\"27\",\"9\":\"0\",\"_rn_\":\"184\"},{\"1\":\"4\",\"2\":\"141.0000\",\"3\":\"74.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"27.60000\",\"7\":\"0.244\",\"8\":\"40\",\"9\":\"0\",\"_rn_\":\"185\"},{\"1\":\"7\",\"2\":\"194.0000\",\"3\":\"68.00000\",\"4\":\"28.00000\",\"5\":\"155.5482\",\"6\":\"35.90000\",\"7\":\"0.745\",\"8\":\"41\",\"9\":\"1\",\"_rn_\":\"186\"},{\"1\":\"8\",\"2\":\"181.0000\",\"3\":\"68.00000\",\"4\":\"36.00000\",\"5\":\"495.0000\",\"6\":\"30.10000\",\"7\":\"0.615\",\"8\":\"60\",\"9\":\"1\",\"_rn_\":\"187\"},{\"1\":\"1\",\"2\":\"128.0000\",\"3\":\"98.00000\",\"4\":\"41.00000\",\"5\":\"58.0000\",\"6\":\"32.00000\",\"7\":\"1.321\",\"8\":\"33\",\"9\":\"1\",\"_rn_\":\"188\"},{\"1\":\"8\",\"2\":\"109.0000\",\"3\":\"76.00000\",\"4\":\"39.00000\",\"5\":\"114.0000\",\"6\":\"27.90000\",\"7\":\"0.640\",\"8\":\"31\",\"9\":\"1\",\"_rn_\":\"189\"},{\"1\":\"5\",\"2\":\"139.0000\",\"3\":\"80.00000\",\"4\":\"35.00000\",\"5\":\"160.0000\",\"6\":\"31.60000\",\"7\":\"0.361\",\"8\":\"25\",\"9\":\"1\",\"_rn_\":\"190\"},{\"1\":\"3\",\"2\":\"111.0000\",\"3\":\"62.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"22.60000\",\"7\":\"0.142\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"191\"},{\"1\":\"9\",\"2\":\"123.0000\",\"3\":\"70.00000\",\"4\":\"44.00000\",\"5\":\"94.0000\",\"6\":\"33.10000\",\"7\":\"0.374\",\"8\":\"40\",\"9\":\"0\",\"_rn_\":\"192\"},{\"1\":\"7\",\"2\":\"159.0000\",\"3\":\"66.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"30.40000\",\"7\":\"0.383\",\"8\":\"36\",\"9\":\"1\",\"_rn_\":\"193\"},{\"1\":\"11\",\"2\":\"135.0000\",\"3\":\"72.40518\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"52.30000\",\"7\":\"0.578\",\"8\":\"40\",\"9\":\"1\",\"_rn_\":\"194\"},{\"1\":\"8\",\"2\":\"85.0000\",\"3\":\"55.00000\",\"4\":\"20.00000\",\"5\":\"155.5482\",\"6\":\"24.40000\",\"7\":\"0.136\",\"8\":\"42\",\"9\":\"0\",\"_rn_\":\"195\"},{\"1\":\"5\",\"2\":\"158.0000\",\"3\":\"84.00000\",\"4\":\"41.00000\",\"5\":\"210.0000\",\"6\":\"39.40000\",\"7\":\"0.395\",\"8\":\"29\",\"9\":\"1\",\"_rn_\":\"196\"},{\"1\":\"1\",\"2\":\"105.0000\",\"3\":\"58.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"24.30000\",\"7\":\"0.187\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"197\"},{\"1\":\"3\",\"2\":\"107.0000\",\"3\":\"62.00000\",\"4\":\"13.00000\",\"5\":\"48.0000\",\"6\":\"22.90000\",\"7\":\"0.678\",\"8\":\"23\",\"9\":\"1\",\"_rn_\":\"198\"},{\"1\":\"4\",\"2\":\"109.0000\",\"3\":\"64.00000\",\"4\":\"44.00000\",\"5\":\"99.0000\",\"6\":\"34.80000\",\"7\":\"0.905\",\"8\":\"26\",\"9\":\"1\",\"_rn_\":\"199\"},{\"1\":\"4\",\"2\":\"148.0000\",\"3\":\"60.00000\",\"4\":\"27.00000\",\"5\":\"318.0000\",\"6\":\"30.90000\",\"7\":\"0.150\",\"8\":\"29\",\"9\":\"1\",\"_rn_\":\"200\"},{\"1\":\"0\",\"2\":\"113.0000\",\"3\":\"80.00000\",\"4\":\"16.00000\",\"5\":\"155.5482\",\"6\":\"31.00000\",\"7\":\"0.874\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"201\"},{\"1\":\"1\",\"2\":\"138.0000\",\"3\":\"82.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"40.10000\",\"7\":\"0.236\",\"8\":\"28\",\"9\":\"0\",\"_rn_\":\"202\"},{\"1\":\"0\",\"2\":\"108.0000\",\"3\":\"68.00000\",\"4\":\"20.00000\",\"5\":\"155.5482\",\"6\":\"27.30000\",\"7\":\"0.787\",\"8\":\"32\",\"9\":\"0\",\"_rn_\":\"203\"},{\"1\":\"2\",\"2\":\"99.0000\",\"3\":\"70.00000\",\"4\":\"16.00000\",\"5\":\"44.0000\",\"6\":\"20.40000\",\"7\":\"0.235\",\"8\":\"27\",\"9\":\"0\",\"_rn_\":\"204\"},{\"1\":\"6\",\"2\":\"103.0000\",\"3\":\"72.00000\",\"4\":\"32.00000\",\"5\":\"190.0000\",\"6\":\"37.70000\",\"7\":\"0.324\",\"8\":\"55\",\"9\":\"0\",\"_rn_\":\"205\"},{\"1\":\"5\",\"2\":\"111.0000\",\"3\":\"72.00000\",\"4\":\"28.00000\",\"5\":\"155.5482\",\"6\":\"23.90000\",\"7\":\"0.407\",\"8\":\"27\",\"9\":\"0\",\"_rn_\":\"206\"},{\"1\":\"8\",\"2\":\"196.0000\",\"3\":\"76.00000\",\"4\":\"29.00000\",\"5\":\"280.0000\",\"6\":\"37.50000\",\"7\":\"0.605\",\"8\":\"57\",\"9\":\"1\",\"_rn_\":\"207\"},{\"1\":\"5\",\"2\":\"162.0000\",\"3\":\"104.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"37.70000\",\"7\":\"0.151\",\"8\":\"52\",\"9\":\"1\",\"_rn_\":\"208\"},{\"1\":\"1\",\"2\":\"96.0000\",\"3\":\"64.00000\",\"4\":\"27.00000\",\"5\":\"87.0000\",\"6\":\"33.20000\",\"7\":\"0.289\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"209\"},{\"1\":\"7\",\"2\":\"184.0000\",\"3\":\"84.00000\",\"4\":\"33.00000\",\"5\":\"155.5482\",\"6\":\"35.50000\",\"7\":\"0.355\",\"8\":\"41\",\"9\":\"1\",\"_rn_\":\"210\"},{\"1\":\"2\",\"2\":\"81.0000\",\"3\":\"60.00000\",\"4\":\"22.00000\",\"5\":\"155.5482\",\"6\":\"27.70000\",\"7\":\"0.290\",\"8\":\"25\",\"9\":\"0\",\"_rn_\":\"211\"},{\"1\":\"0\",\"2\":\"147.0000\",\"3\":\"85.00000\",\"4\":\"54.00000\",\"5\":\"155.5482\",\"6\":\"42.80000\",\"7\":\"0.375\",\"8\":\"24\",\"9\":\"0\",\"_rn_\":\"212\"},{\"1\":\"7\",\"2\":\"179.0000\",\"3\":\"95.00000\",\"4\":\"31.00000\",\"5\":\"155.5482\",\"6\":\"34.20000\",\"7\":\"0.164\",\"8\":\"60\",\"9\":\"0\",\"_rn_\":\"213\"},{\"1\":\"0\",\"2\":\"140.0000\",\"3\":\"65.00000\",\"4\":\"26.00000\",\"5\":\"130.0000\",\"6\":\"42.60000\",\"7\":\"0.431\",\"8\":\"24\",\"9\":\"1\",\"_rn_\":\"214\"},{\"1\":\"9\",\"2\":\"112.0000\",\"3\":\"82.00000\",\"4\":\"32.00000\",\"5\":\"175.0000\",\"6\":\"34.20000\",\"7\":\"0.260\",\"8\":\"36\",\"9\":\"1\",\"_rn_\":\"215\"},{\"1\":\"12\",\"2\":\"151.0000\",\"3\":\"70.00000\",\"4\":\"40.00000\",\"5\":\"271.0000\",\"6\":\"41.80000\",\"7\":\"0.742\",\"8\":\"38\",\"9\":\"1\",\"_rn_\":\"216\"},{\"1\":\"5\",\"2\":\"109.0000\",\"3\":\"62.00000\",\"4\":\"41.00000\",\"5\":\"129.0000\",\"6\":\"35.80000\",\"7\":\"0.514\",\"8\":\"25\",\"9\":\"1\",\"_rn_\":\"217\"},{\"1\":\"6\",\"2\":\"125.0000\",\"3\":\"68.00000\",\"4\":\"30.00000\",\"5\":\"120.0000\",\"6\":\"30.00000\",\"7\":\"0.464\",\"8\":\"32\",\"9\":\"0\",\"_rn_\":\"218\"},{\"1\":\"5\",\"2\":\"85.0000\",\"3\":\"74.00000\",\"4\":\"22.00000\",\"5\":\"155.5482\",\"6\":\"29.00000\",\"7\":\"1.224\",\"8\":\"32\",\"9\":\"1\",\"_rn_\":\"219\"},{\"1\":\"5\",\"2\":\"112.0000\",\"3\":\"66.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"37.80000\",\"7\":\"0.261\",\"8\":\"41\",\"9\":\"1\",\"_rn_\":\"220\"},{\"1\":\"0\",\"2\":\"177.0000\",\"3\":\"60.00000\",\"4\":\"29.00000\",\"5\":\"478.0000\",\"6\":\"34.60000\",\"7\":\"1.072\",\"8\":\"21\",\"9\":\"1\",\"_rn_\":\"221\"},{\"1\":\"2\",\"2\":\"158.0000\",\"3\":\"90.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"31.60000\",\"7\":\"0.805\",\"8\":\"66\",\"9\":\"1\",\"_rn_\":\"222\"},{\"1\":\"7\",\"2\":\"119.0000\",\"3\":\"72.40518\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"25.20000\",\"7\":\"0.209\",\"8\":\"37\",\"9\":\"0\",\"_rn_\":\"223\"},{\"1\":\"7\",\"2\":\"142.0000\",\"3\":\"60.00000\",\"4\":\"33.00000\",\"5\":\"190.0000\",\"6\":\"28.80000\",\"7\":\"0.687\",\"8\":\"61\",\"9\":\"0\",\"_rn_\":\"224\"},{\"1\":\"1\",\"2\":\"100.0000\",\"3\":\"66.00000\",\"4\":\"15.00000\",\"5\":\"56.0000\",\"6\":\"23.60000\",\"7\":\"0.666\",\"8\":\"26\",\"9\":\"0\",\"_rn_\":\"225\"},{\"1\":\"1\",\"2\":\"87.0000\",\"3\":\"78.00000\",\"4\":\"27.00000\",\"5\":\"32.0000\",\"6\":\"34.60000\",\"7\":\"0.101\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"226\"},{\"1\":\"0\",\"2\":\"101.0000\",\"3\":\"76.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"35.70000\",\"7\":\"0.198\",\"8\":\"26\",\"9\":\"0\",\"_rn_\":\"227\"},{\"1\":\"3\",\"2\":\"162.0000\",\"3\":\"52.00000\",\"4\":\"38.00000\",\"5\":\"155.5482\",\"6\":\"37.20000\",\"7\":\"0.652\",\"8\":\"24\",\"9\":\"1\",\"_rn_\":\"228\"},{\"1\":\"4\",\"2\":\"197.0000\",\"3\":\"70.00000\",\"4\":\"39.00000\",\"5\":\"744.0000\",\"6\":\"36.70000\",\"7\":\"2.329\",\"8\":\"31\",\"9\":\"0\",\"_rn_\":\"229\"},{\"1\":\"0\",\"2\":\"117.0000\",\"3\":\"80.00000\",\"4\":\"31.00000\",\"5\":\"53.0000\",\"6\":\"45.20000\",\"7\":\"0.089\",\"8\":\"24\",\"9\":\"0\",\"_rn_\":\"230\"},{\"1\":\"4\",\"2\":\"142.0000\",\"3\":\"86.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"44.00000\",\"7\":\"0.645\",\"8\":\"22\",\"9\":\"1\",\"_rn_\":\"231\"},{\"1\":\"6\",\"2\":\"134.0000\",\"3\":\"80.00000\",\"4\":\"37.00000\",\"5\":\"370.0000\",\"6\":\"46.20000\",\"7\":\"0.238\",\"8\":\"46\",\"9\":\"1\",\"_rn_\":\"232\"},{\"1\":\"1\",\"2\":\"79.0000\",\"3\":\"80.00000\",\"4\":\"25.00000\",\"5\":\"37.0000\",\"6\":\"25.40000\",\"7\":\"0.583\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"233\"},{\"1\":\"4\",\"2\":\"122.0000\",\"3\":\"68.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"35.00000\",\"7\":\"0.394\",\"8\":\"29\",\"9\":\"0\",\"_rn_\":\"234\"},{\"1\":\"3\",\"2\":\"74.0000\",\"3\":\"68.00000\",\"4\":\"28.00000\",\"5\":\"45.0000\",\"6\":\"29.70000\",\"7\":\"0.293\",\"8\":\"23\",\"9\":\"0\",\"_rn_\":\"235\"},{\"1\":\"4\",\"2\":\"171.0000\",\"3\":\"72.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"43.60000\",\"7\":\"0.479\",\"8\":\"26\",\"9\":\"1\",\"_rn_\":\"236\"},{\"1\":\"7\",\"2\":\"181.0000\",\"3\":\"84.00000\",\"4\":\"21.00000\",\"5\":\"192.0000\",\"6\":\"35.90000\",\"7\":\"0.586\",\"8\":\"51\",\"9\":\"1\",\"_rn_\":\"237\"},{\"1\":\"0\",\"2\":\"179.0000\",\"3\":\"90.00000\",\"4\":\"27.00000\",\"5\":\"155.5482\",\"6\":\"44.10000\",\"7\":\"0.686\",\"8\":\"23\",\"9\":\"1\",\"_rn_\":\"238\"},{\"1\":\"9\",\"2\":\"164.0000\",\"3\":\"84.00000\",\"4\":\"21.00000\",\"5\":\"155.5482\",\"6\":\"30.80000\",\"7\":\"0.831\",\"8\":\"32\",\"9\":\"1\",\"_rn_\":\"239\"},{\"1\":\"0\",\"2\":\"104.0000\",\"3\":\"76.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"18.40000\",\"7\":\"0.582\",\"8\":\"27\",\"9\":\"0\",\"_rn_\":\"240\"},{\"1\":\"1\",\"2\":\"91.0000\",\"3\":\"64.00000\",\"4\":\"24.00000\",\"5\":\"155.5482\",\"6\":\"29.20000\",\"7\":\"0.192\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"241\"},{\"1\":\"4\",\"2\":\"91.0000\",\"3\":\"70.00000\",\"4\":\"32.00000\",\"5\":\"88.0000\",\"6\":\"33.10000\",\"7\":\"0.446\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"242\"},{\"1\":\"3\",\"2\":\"139.0000\",\"3\":\"54.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"25.60000\",\"7\":\"0.402\",\"8\":\"22\",\"9\":\"1\",\"_rn_\":\"243\"},{\"1\":\"6\",\"2\":\"119.0000\",\"3\":\"50.00000\",\"4\":\"22.00000\",\"5\":\"176.0000\",\"6\":\"27.10000\",\"7\":\"1.318\",\"8\":\"33\",\"9\":\"1\",\"_rn_\":\"244\"},{\"1\":\"2\",\"2\":\"146.0000\",\"3\":\"76.00000\",\"4\":\"35.00000\",\"5\":\"194.0000\",\"6\":\"38.20000\",\"7\":\"0.329\",\"8\":\"29\",\"9\":\"0\",\"_rn_\":\"245\"},{\"1\":\"9\",\"2\":\"184.0000\",\"3\":\"85.00000\",\"4\":\"15.00000\",\"5\":\"155.5482\",\"6\":\"30.00000\",\"7\":\"1.213\",\"8\":\"49\",\"9\":\"1\",\"_rn_\":\"246\"},{\"1\":\"10\",\"2\":\"122.0000\",\"3\":\"68.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"31.20000\",\"7\":\"0.258\",\"8\":\"41\",\"9\":\"0\",\"_rn_\":\"247\"},{\"1\":\"0\",\"2\":\"165.0000\",\"3\":\"90.00000\",\"4\":\"33.00000\",\"5\":\"680.0000\",\"6\":\"52.30000\",\"7\":\"0.427\",\"8\":\"23\",\"9\":\"0\",\"_rn_\":\"248\"},{\"1\":\"9\",\"2\":\"124.0000\",\"3\":\"70.00000\",\"4\":\"33.00000\",\"5\":\"402.0000\",\"6\":\"35.40000\",\"7\":\"0.282\",\"8\":\"34\",\"9\":\"0\",\"_rn_\":\"249\"},{\"1\":\"1\",\"2\":\"111.0000\",\"3\":\"86.00000\",\"4\":\"19.00000\",\"5\":\"155.5482\",\"6\":\"30.10000\",\"7\":\"0.143\",\"8\":\"23\",\"9\":\"0\",\"_rn_\":\"250\"},{\"1\":\"9\",\"2\":\"106.0000\",\"3\":\"52.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"31.20000\",\"7\":\"0.380\",\"8\":\"42\",\"9\":\"0\",\"_rn_\":\"251\"},{\"1\":\"2\",\"2\":\"129.0000\",\"3\":\"84.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"28.00000\",\"7\":\"0.284\",\"8\":\"27\",\"9\":\"0\",\"_rn_\":\"252\"},{\"1\":\"2\",\"2\":\"90.0000\",\"3\":\"80.00000\",\"4\":\"14.00000\",\"5\":\"55.0000\",\"6\":\"24.40000\",\"7\":\"0.249\",\"8\":\"24\",\"9\":\"0\",\"_rn_\":\"253\"},{\"1\":\"0\",\"2\":\"86.0000\",\"3\":\"68.00000\",\"4\":\"32.00000\",\"5\":\"155.5482\",\"6\":\"35.80000\",\"7\":\"0.238\",\"8\":\"25\",\"9\":\"0\",\"_rn_\":\"254\"},{\"1\":\"12\",\"2\":\"92.0000\",\"3\":\"62.00000\",\"4\":\"7.00000\",\"5\":\"258.0000\",\"6\":\"27.60000\",\"7\":\"0.926\",\"8\":\"44\",\"9\":\"1\",\"_rn_\":\"255\"},{\"1\":\"1\",\"2\":\"113.0000\",\"3\":\"64.00000\",\"4\":\"35.00000\",\"5\":\"155.5482\",\"6\":\"33.60000\",\"7\":\"0.543\",\"8\":\"21\",\"9\":\"1\",\"_rn_\":\"256\"},{\"1\":\"3\",\"2\":\"111.0000\",\"3\":\"56.00000\",\"4\":\"39.00000\",\"5\":\"155.5482\",\"6\":\"30.10000\",\"7\":\"0.557\",\"8\":\"30\",\"9\":\"0\",\"_rn_\":\"257\"},{\"1\":\"2\",\"2\":\"114.0000\",\"3\":\"68.00000\",\"4\":\"22.00000\",\"5\":\"155.5482\",\"6\":\"28.70000\",\"7\":\"0.092\",\"8\":\"25\",\"9\":\"0\",\"_rn_\":\"258\"},{\"1\":\"1\",\"2\":\"193.0000\",\"3\":\"50.00000\",\"4\":\"16.00000\",\"5\":\"375.0000\",\"6\":\"25.90000\",\"7\":\"0.655\",\"8\":\"24\",\"9\":\"0\",\"_rn_\":\"259\"},{\"1\":\"11\",\"2\":\"155.0000\",\"3\":\"76.00000\",\"4\":\"28.00000\",\"5\":\"150.0000\",\"6\":\"33.30000\",\"7\":\"1.353\",\"8\":\"51\",\"9\":\"1\",\"_rn_\":\"260\"},{\"1\":\"3\",\"2\":\"191.0000\",\"3\":\"68.00000\",\"4\":\"15.00000\",\"5\":\"130.0000\",\"6\":\"30.90000\",\"7\":\"0.299\",\"8\":\"34\",\"9\":\"0\",\"_rn_\":\"261\"},{\"1\":\"3\",\"2\":\"141.0000\",\"3\":\"72.40518\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"30.00000\",\"7\":\"0.761\",\"8\":\"27\",\"9\":\"1\",\"_rn_\":\"262\"},{\"1\":\"4\",\"2\":\"95.0000\",\"3\":\"70.00000\",\"4\":\"32.00000\",\"5\":\"155.5482\",\"6\":\"32.10000\",\"7\":\"0.612\",\"8\":\"24\",\"9\":\"0\",\"_rn_\":\"263\"},{\"1\":\"3\",\"2\":\"142.0000\",\"3\":\"80.00000\",\"4\":\"15.00000\",\"5\":\"155.5482\",\"6\":\"32.40000\",\"7\":\"0.200\",\"8\":\"63\",\"9\":\"0\",\"_rn_\":\"264\"},{\"1\":\"4\",\"2\":\"123.0000\",\"3\":\"62.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"32.00000\",\"7\":\"0.226\",\"8\":\"35\",\"9\":\"1\",\"_rn_\":\"265\"},{\"1\":\"5\",\"2\":\"96.0000\",\"3\":\"74.00000\",\"4\":\"18.00000\",\"5\":\"67.0000\",\"6\":\"33.60000\",\"7\":\"0.997\",\"8\":\"43\",\"9\":\"0\",\"_rn_\":\"266\"},{\"1\":\"0\",\"2\":\"138.0000\",\"3\":\"72.40518\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"36.30000\",\"7\":\"0.933\",\"8\":\"25\",\"9\":\"1\",\"_rn_\":\"267\"},{\"1\":\"2\",\"2\":\"128.0000\",\"3\":\"64.00000\",\"4\":\"42.00000\",\"5\":\"155.5482\",\"6\":\"40.00000\",\"7\":\"1.101\",\"8\":\"24\",\"9\":\"0\",\"_rn_\":\"268\"},{\"1\":\"0\",\"2\":\"102.0000\",\"3\":\"52.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"25.10000\",\"7\":\"0.078\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"269\"},{\"1\":\"2\",\"2\":\"146.0000\",\"3\":\"72.40518\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"27.50000\",\"7\":\"0.240\",\"8\":\"28\",\"9\":\"1\",\"_rn_\":\"270\"},{\"1\":\"10\",\"2\":\"101.0000\",\"3\":\"86.00000\",\"4\":\"37.00000\",\"5\":\"155.5482\",\"6\":\"45.60000\",\"7\":\"1.136\",\"8\":\"38\",\"9\":\"1\",\"_rn_\":\"271\"},{\"1\":\"2\",\"2\":\"108.0000\",\"3\":\"62.00000\",\"4\":\"32.00000\",\"5\":\"56.0000\",\"6\":\"25.20000\",\"7\":\"0.128\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"272\"},{\"1\":\"3\",\"2\":\"122.0000\",\"3\":\"78.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"23.00000\",\"7\":\"0.254\",\"8\":\"40\",\"9\":\"0\",\"_rn_\":\"273\"},{\"1\":\"1\",\"2\":\"71.0000\",\"3\":\"78.00000\",\"4\":\"50.00000\",\"5\":\"45.0000\",\"6\":\"33.20000\",\"7\":\"0.422\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"274\"},{\"1\":\"13\",\"2\":\"106.0000\",\"3\":\"70.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"34.20000\",\"7\":\"0.251\",\"8\":\"52\",\"9\":\"0\",\"_rn_\":\"275\"},{\"1\":\"2\",\"2\":\"100.0000\",\"3\":\"70.00000\",\"4\":\"52.00000\",\"5\":\"57.0000\",\"6\":\"40.50000\",\"7\":\"0.677\",\"8\":\"25\",\"9\":\"0\",\"_rn_\":\"276\"},{\"1\":\"7\",\"2\":\"106.0000\",\"3\":\"60.00000\",\"4\":\"24.00000\",\"5\":\"155.5482\",\"6\":\"26.50000\",\"7\":\"0.296\",\"8\":\"29\",\"9\":\"1\",\"_rn_\":\"277\"},{\"1\":\"0\",\"2\":\"104.0000\",\"3\":\"64.00000\",\"4\":\"23.00000\",\"5\":\"116.0000\",\"6\":\"27.80000\",\"7\":\"0.454\",\"8\":\"23\",\"9\":\"0\",\"_rn_\":\"278\"},{\"1\":\"5\",\"2\":\"114.0000\",\"3\":\"74.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"24.90000\",\"7\":\"0.744\",\"8\":\"57\",\"9\":\"0\",\"_rn_\":\"279\"},{\"1\":\"2\",\"2\":\"108.0000\",\"3\":\"62.00000\",\"4\":\"10.00000\",\"5\":\"278.0000\",\"6\":\"25.30000\",\"7\":\"0.881\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"280\"},{\"1\":\"0\",\"2\":\"146.0000\",\"3\":\"70.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"37.90000\",\"7\":\"0.334\",\"8\":\"28\",\"9\":\"1\",\"_rn_\":\"281\"},{\"1\":\"10\",\"2\":\"129.0000\",\"3\":\"76.00000\",\"4\":\"28.00000\",\"5\":\"122.0000\",\"6\":\"35.90000\",\"7\":\"0.280\",\"8\":\"39\",\"9\":\"0\",\"_rn_\":\"282\"},{\"1\":\"7\",\"2\":\"133.0000\",\"3\":\"88.00000\",\"4\":\"15.00000\",\"5\":\"155.0000\",\"6\":\"32.40000\",\"7\":\"0.262\",\"8\":\"37\",\"9\":\"0\",\"_rn_\":\"283\"},{\"1\":\"7\",\"2\":\"161.0000\",\"3\":\"86.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"30.40000\",\"7\":\"0.165\",\"8\":\"47\",\"9\":\"1\",\"_rn_\":\"284\"},{\"1\":\"2\",\"2\":\"108.0000\",\"3\":\"80.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"27.00000\",\"7\":\"0.259\",\"8\":\"52\",\"9\":\"1\",\"_rn_\":\"285\"},{\"1\":\"7\",\"2\":\"136.0000\",\"3\":\"74.00000\",\"4\":\"26.00000\",\"5\":\"135.0000\",\"6\":\"26.00000\",\"7\":\"0.647\",\"8\":\"51\",\"9\":\"0\",\"_rn_\":\"286\"},{\"1\":\"5\",\"2\":\"155.0000\",\"3\":\"84.00000\",\"4\":\"44.00000\",\"5\":\"545.0000\",\"6\":\"38.70000\",\"7\":\"0.619\",\"8\":\"34\",\"9\":\"0\",\"_rn_\":\"287\"},{\"1\":\"1\",\"2\":\"119.0000\",\"3\":\"86.00000\",\"4\":\"39.00000\",\"5\":\"220.0000\",\"6\":\"45.60000\",\"7\":\"0.808\",\"8\":\"29\",\"9\":\"1\",\"_rn_\":\"288\"},{\"1\":\"4\",\"2\":\"96.0000\",\"3\":\"56.00000\",\"4\":\"17.00000\",\"5\":\"49.0000\",\"6\":\"20.80000\",\"7\":\"0.340\",\"8\":\"26\",\"9\":\"0\",\"_rn_\":\"289\"},{\"1\":\"5\",\"2\":\"108.0000\",\"3\":\"72.00000\",\"4\":\"43.00000\",\"5\":\"75.0000\",\"6\":\"36.10000\",\"7\":\"0.263\",\"8\":\"33\",\"9\":\"0\",\"_rn_\":\"290\"},{\"1\":\"0\",\"2\":\"78.0000\",\"3\":\"88.00000\",\"4\":\"29.00000\",\"5\":\"40.0000\",\"6\":\"36.90000\",\"7\":\"0.434\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"291\"},{\"1\":\"0\",\"2\":\"107.0000\",\"3\":\"62.00000\",\"4\":\"30.00000\",\"5\":\"74.0000\",\"6\":\"36.60000\",\"7\":\"0.757\",\"8\":\"25\",\"9\":\"1\",\"_rn_\":\"292\"},{\"1\":\"2\",\"2\":\"128.0000\",\"3\":\"78.00000\",\"4\":\"37.00000\",\"5\":\"182.0000\",\"6\":\"43.30000\",\"7\":\"1.224\",\"8\":\"31\",\"9\":\"1\",\"_rn_\":\"293\"},{\"1\":\"1\",\"2\":\"128.0000\",\"3\":\"48.00000\",\"4\":\"45.00000\",\"5\":\"194.0000\",\"6\":\"40.50000\",\"7\":\"0.613\",\"8\":\"24\",\"9\":\"1\",\"_rn_\":\"294\"},{\"1\":\"0\",\"2\":\"161.0000\",\"3\":\"50.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"21.90000\",\"7\":\"0.254\",\"8\":\"65\",\"9\":\"0\",\"_rn_\":\"295\"},{\"1\":\"6\",\"2\":\"151.0000\",\"3\":\"62.00000\",\"4\":\"31.00000\",\"5\":\"120.0000\",\"6\":\"35.50000\",\"7\":\"0.692\",\"8\":\"28\",\"9\":\"0\",\"_rn_\":\"296\"},{\"1\":\"2\",\"2\":\"146.0000\",\"3\":\"70.00000\",\"4\":\"38.00000\",\"5\":\"360.0000\",\"6\":\"28.00000\",\"7\":\"0.337\",\"8\":\"29\",\"9\":\"1\",\"_rn_\":\"297\"},{\"1\":\"0\",\"2\":\"126.0000\",\"3\":\"84.00000\",\"4\":\"29.00000\",\"5\":\"215.0000\",\"6\":\"30.70000\",\"7\":\"0.520\",\"8\":\"24\",\"9\":\"0\",\"_rn_\":\"298\"},{\"1\":\"14\",\"2\":\"100.0000\",\"3\":\"78.00000\",\"4\":\"25.00000\",\"5\":\"184.0000\",\"6\":\"36.60000\",\"7\":\"0.412\",\"8\":\"46\",\"9\":\"1\",\"_rn_\":\"299\"},{\"1\":\"8\",\"2\":\"112.0000\",\"3\":\"72.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"23.60000\",\"7\":\"0.840\",\"8\":\"58\",\"9\":\"0\",\"_rn_\":\"300\"},{\"1\":\"0\",\"2\":\"167.0000\",\"3\":\"72.40518\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"32.30000\",\"7\":\"0.839\",\"8\":\"30\",\"9\":\"1\",\"_rn_\":\"301\"},{\"1\":\"2\",\"2\":\"144.0000\",\"3\":\"58.00000\",\"4\":\"33.00000\",\"5\":\"135.0000\",\"6\":\"31.60000\",\"7\":\"0.422\",\"8\":\"25\",\"9\":\"1\",\"_rn_\":\"302\"},{\"1\":\"5\",\"2\":\"77.0000\",\"3\":\"82.00000\",\"4\":\"41.00000\",\"5\":\"42.0000\",\"6\":\"35.80000\",\"7\":\"0.156\",\"8\":\"35\",\"9\":\"0\",\"_rn_\":\"303\"},{\"1\":\"5\",\"2\":\"115.0000\",\"3\":\"98.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"52.90000\",\"7\":\"0.209\",\"8\":\"28\",\"9\":\"1\",\"_rn_\":\"304\"},{\"1\":\"3\",\"2\":\"150.0000\",\"3\":\"76.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"21.00000\",\"7\":\"0.207\",\"8\":\"37\",\"9\":\"0\",\"_rn_\":\"305\"},{\"1\":\"2\",\"2\":\"120.0000\",\"3\":\"76.00000\",\"4\":\"37.00000\",\"5\":\"105.0000\",\"6\":\"39.70000\",\"7\":\"0.215\",\"8\":\"29\",\"9\":\"0\",\"_rn_\":\"306\"},{\"1\":\"10\",\"2\":\"161.0000\",\"3\":\"68.00000\",\"4\":\"23.00000\",\"5\":\"132.0000\",\"6\":\"25.50000\",\"7\":\"0.326\",\"8\":\"47\",\"9\":\"1\",\"_rn_\":\"307\"},{\"1\":\"0\",\"2\":\"137.0000\",\"3\":\"68.00000\",\"4\":\"14.00000\",\"5\":\"148.0000\",\"6\":\"24.80000\",\"7\":\"0.143\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"308\"},{\"1\":\"0\",\"2\":\"128.0000\",\"3\":\"68.00000\",\"4\":\"19.00000\",\"5\":\"180.0000\",\"6\":\"30.50000\",\"7\":\"1.391\",\"8\":\"25\",\"9\":\"1\",\"_rn_\":\"309\"},{\"1\":\"2\",\"2\":\"124.0000\",\"3\":\"68.00000\",\"4\":\"28.00000\",\"5\":\"205.0000\",\"6\":\"32.90000\",\"7\":\"0.875\",\"8\":\"30\",\"9\":\"1\",\"_rn_\":\"310\"},{\"1\":\"6\",\"2\":\"80.0000\",\"3\":\"66.00000\",\"4\":\"30.00000\",\"5\":\"155.5482\",\"6\":\"26.20000\",\"7\":\"0.313\",\"8\":\"41\",\"9\":\"0\",\"_rn_\":\"311\"},{\"1\":\"0\",\"2\":\"106.0000\",\"3\":\"70.00000\",\"4\":\"37.00000\",\"5\":\"148.0000\",\"6\":\"39.40000\",\"7\":\"0.605\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"312\"},{\"1\":\"2\",\"2\":\"155.0000\",\"3\":\"74.00000\",\"4\":\"17.00000\",\"5\":\"96.0000\",\"6\":\"26.60000\",\"7\":\"0.433\",\"8\":\"27\",\"9\":\"1\",\"_rn_\":\"313\"},{\"1\":\"3\",\"2\":\"113.0000\",\"3\":\"50.00000\",\"4\":\"10.00000\",\"5\":\"85.0000\",\"6\":\"29.50000\",\"7\":\"0.626\",\"8\":\"25\",\"9\":\"0\",\"_rn_\":\"314\"},{\"1\":\"7\",\"2\":\"109.0000\",\"3\":\"80.00000\",\"4\":\"31.00000\",\"5\":\"155.5482\",\"6\":\"35.90000\",\"7\":\"1.127\",\"8\":\"43\",\"9\":\"1\",\"_rn_\":\"315\"},{\"1\":\"2\",\"2\":\"112.0000\",\"3\":\"68.00000\",\"4\":\"22.00000\",\"5\":\"94.0000\",\"6\":\"34.10000\",\"7\":\"0.315\",\"8\":\"26\",\"9\":\"0\",\"_rn_\":\"316\"},{\"1\":\"3\",\"2\":\"99.0000\",\"3\":\"80.00000\",\"4\":\"11.00000\",\"5\":\"64.0000\",\"6\":\"19.30000\",\"7\":\"0.284\",\"8\":\"30\",\"9\":\"0\",\"_rn_\":\"317\"},{\"1\":\"3\",\"2\":\"182.0000\",\"3\":\"74.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"30.50000\",\"7\":\"0.345\",\"8\":\"29\",\"9\":\"1\",\"_rn_\":\"318\"},{\"1\":\"3\",\"2\":\"115.0000\",\"3\":\"66.00000\",\"4\":\"39.00000\",\"5\":\"140.0000\",\"6\":\"38.10000\",\"7\":\"0.150\",\"8\":\"28\",\"9\":\"0\",\"_rn_\":\"319\"},{\"1\":\"6\",\"2\":\"194.0000\",\"3\":\"78.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"23.50000\",\"7\":\"0.129\",\"8\":\"59\",\"9\":\"1\",\"_rn_\":\"320\"},{\"1\":\"4\",\"2\":\"129.0000\",\"3\":\"60.00000\",\"4\":\"12.00000\",\"5\":\"231.0000\",\"6\":\"27.50000\",\"7\":\"0.527\",\"8\":\"31\",\"9\":\"0\",\"_rn_\":\"321\"},{\"1\":\"3\",\"2\":\"112.0000\",\"3\":\"74.00000\",\"4\":\"30.00000\",\"5\":\"155.5482\",\"6\":\"31.60000\",\"7\":\"0.197\",\"8\":\"25\",\"9\":\"1\",\"_rn_\":\"322\"},{\"1\":\"0\",\"2\":\"124.0000\",\"3\":\"70.00000\",\"4\":\"20.00000\",\"5\":\"155.5482\",\"6\":\"27.40000\",\"7\":\"0.254\",\"8\":\"36\",\"9\":\"1\",\"_rn_\":\"323\"},{\"1\":\"13\",\"2\":\"152.0000\",\"3\":\"90.00000\",\"4\":\"33.00000\",\"5\":\"29.0000\",\"6\":\"26.80000\",\"7\":\"0.731\",\"8\":\"43\",\"9\":\"1\",\"_rn_\":\"324\"},{\"1\":\"2\",\"2\":\"112.0000\",\"3\":\"75.00000\",\"4\":\"32.00000\",\"5\":\"155.5482\",\"6\":\"35.70000\",\"7\":\"0.148\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"325\"},{\"1\":\"1\",\"2\":\"157.0000\",\"3\":\"72.00000\",\"4\":\"21.00000\",\"5\":\"168.0000\",\"6\":\"25.60000\",\"7\":\"0.123\",\"8\":\"24\",\"9\":\"0\",\"_rn_\":\"326\"},{\"1\":\"1\",\"2\":\"122.0000\",\"3\":\"64.00000\",\"4\":\"32.00000\",\"5\":\"156.0000\",\"6\":\"35.10000\",\"7\":\"0.692\",\"8\":\"30\",\"9\":\"1\",\"_rn_\":\"327\"},{\"1\":\"10\",\"2\":\"179.0000\",\"3\":\"70.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"35.10000\",\"7\":\"0.200\",\"8\":\"37\",\"9\":\"0\",\"_rn_\":\"328\"},{\"1\":\"2\",\"2\":\"102.0000\",\"3\":\"86.00000\",\"4\":\"36.00000\",\"5\":\"120.0000\",\"6\":\"45.50000\",\"7\":\"0.127\",\"8\":\"23\",\"9\":\"1\",\"_rn_\":\"329\"},{\"1\":\"6\",\"2\":\"105.0000\",\"3\":\"70.00000\",\"4\":\"32.00000\",\"5\":\"68.0000\",\"6\":\"30.80000\",\"7\":\"0.122\",\"8\":\"37\",\"9\":\"0\",\"_rn_\":\"330\"},{\"1\":\"8\",\"2\":\"118.0000\",\"3\":\"72.00000\",\"4\":\"19.00000\",\"5\":\"155.5482\",\"6\":\"23.10000\",\"7\":\"1.476\",\"8\":\"46\",\"9\":\"0\",\"_rn_\":\"331\"},{\"1\":\"2\",\"2\":\"87.0000\",\"3\":\"58.00000\",\"4\":\"16.00000\",\"5\":\"52.0000\",\"6\":\"32.70000\",\"7\":\"0.166\",\"8\":\"25\",\"9\":\"0\",\"_rn_\":\"332\"},{\"1\":\"1\",\"2\":\"180.0000\",\"3\":\"72.40518\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"43.30000\",\"7\":\"0.282\",\"8\":\"41\",\"9\":\"1\",\"_rn_\":\"333\"},{\"1\":\"12\",\"2\":\"106.0000\",\"3\":\"80.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"23.60000\",\"7\":\"0.137\",\"8\":\"44\",\"9\":\"0\",\"_rn_\":\"334\"},{\"1\":\"1\",\"2\":\"95.0000\",\"3\":\"60.00000\",\"4\":\"18.00000\",\"5\":\"58.0000\",\"6\":\"23.90000\",\"7\":\"0.260\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"335\"},{\"1\":\"0\",\"2\":\"165.0000\",\"3\":\"76.00000\",\"4\":\"43.00000\",\"5\":\"255.0000\",\"6\":\"47.90000\",\"7\":\"0.259\",\"8\":\"26\",\"9\":\"0\",\"_rn_\":\"336\"},{\"1\":\"0\",\"2\":\"117.0000\",\"3\":\"72.40518\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"33.80000\",\"7\":\"0.932\",\"8\":\"44\",\"9\":\"0\",\"_rn_\":\"337\"},{\"1\":\"5\",\"2\":\"115.0000\",\"3\":\"76.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"31.20000\",\"7\":\"0.343\",\"8\":\"44\",\"9\":\"1\",\"_rn_\":\"338\"},{\"1\":\"9\",\"2\":\"152.0000\",\"3\":\"78.00000\",\"4\":\"34.00000\",\"5\":\"171.0000\",\"6\":\"34.20000\",\"7\":\"0.893\",\"8\":\"33\",\"9\":\"1\",\"_rn_\":\"339\"},{\"1\":\"7\",\"2\":\"178.0000\",\"3\":\"84.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"39.90000\",\"7\":\"0.331\",\"8\":\"41\",\"9\":\"1\",\"_rn_\":\"340\"},{\"1\":\"1\",\"2\":\"130.0000\",\"3\":\"70.00000\",\"4\":\"13.00000\",\"5\":\"105.0000\",\"6\":\"25.90000\",\"7\":\"0.472\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"341\"},{\"1\":\"1\",\"2\":\"95.0000\",\"3\":\"74.00000\",\"4\":\"21.00000\",\"5\":\"73.0000\",\"6\":\"25.90000\",\"7\":\"0.673\",\"8\":\"36\",\"9\":\"0\",\"_rn_\":\"342\"},{\"1\":\"1\",\"2\":\"121.6868\",\"3\":\"68.00000\",\"4\":\"35.00000\",\"5\":\"155.5482\",\"6\":\"32.00000\",\"7\":\"0.389\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"343\"},{\"1\":\"5\",\"2\":\"122.0000\",\"3\":\"86.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"34.70000\",\"7\":\"0.290\",\"8\":\"33\",\"9\":\"0\",\"_rn_\":\"344\"},{\"1\":\"8\",\"2\":\"95.0000\",\"3\":\"72.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"36.80000\",\"7\":\"0.485\",\"8\":\"57\",\"9\":\"0\",\"_rn_\":\"345\"},{\"1\":\"8\",\"2\":\"126.0000\",\"3\":\"88.00000\",\"4\":\"36.00000\",\"5\":\"108.0000\",\"6\":\"38.50000\",\"7\":\"0.349\",\"8\":\"49\",\"9\":\"0\",\"_rn_\":\"346\"},{\"1\":\"1\",\"2\":\"139.0000\",\"3\":\"46.00000\",\"4\":\"19.00000\",\"5\":\"83.0000\",\"6\":\"28.70000\",\"7\":\"0.654\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"347\"},{\"1\":\"3\",\"2\":\"116.0000\",\"3\":\"72.40518\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"23.50000\",\"7\":\"0.187\",\"8\":\"23\",\"9\":\"0\",\"_rn_\":\"348\"},{\"1\":\"3\",\"2\":\"99.0000\",\"3\":\"62.00000\",\"4\":\"19.00000\",\"5\":\"74.0000\",\"6\":\"21.80000\",\"7\":\"0.279\",\"8\":\"26\",\"9\":\"0\",\"_rn_\":\"349\"},{\"1\":\"5\",\"2\":\"121.6868\",\"3\":\"80.00000\",\"4\":\"32.00000\",\"5\":\"155.5482\",\"6\":\"41.00000\",\"7\":\"0.346\",\"8\":\"37\",\"9\":\"1\",\"_rn_\":\"350\"},{\"1\":\"4\",\"2\":\"92.0000\",\"3\":\"80.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"42.20000\",\"7\":\"0.237\",\"8\":\"29\",\"9\":\"0\",\"_rn_\":\"351\"},{\"1\":\"4\",\"2\":\"137.0000\",\"3\":\"84.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"31.20000\",\"7\":\"0.252\",\"8\":\"30\",\"9\":\"0\",\"_rn_\":\"352\"},{\"1\":\"3\",\"2\":\"61.0000\",\"3\":\"82.00000\",\"4\":\"28.00000\",\"5\":\"155.5482\",\"6\":\"34.40000\",\"7\":\"0.243\",\"8\":\"46\",\"9\":\"0\",\"_rn_\":\"353\"},{\"1\":\"1\",\"2\":\"90.0000\",\"3\":\"62.00000\",\"4\":\"12.00000\",\"5\":\"43.0000\",\"6\":\"27.20000\",\"7\":\"0.580\",\"8\":\"24\",\"9\":\"0\",\"_rn_\":\"354\"},{\"1\":\"3\",\"2\":\"90.0000\",\"3\":\"78.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"42.70000\",\"7\":\"0.559\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"355\"},{\"1\":\"9\",\"2\":\"165.0000\",\"3\":\"88.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"30.40000\",\"7\":\"0.302\",\"8\":\"49\",\"9\":\"1\",\"_rn_\":\"356\"},{\"1\":\"1\",\"2\":\"125.0000\",\"3\":\"50.00000\",\"4\":\"40.00000\",\"5\":\"167.0000\",\"6\":\"33.30000\",\"7\":\"0.962\",\"8\":\"28\",\"9\":\"1\",\"_rn_\":\"357\"},{\"1\":\"13\",\"2\":\"129.0000\",\"3\":\"72.40518\",\"4\":\"30.00000\",\"5\":\"155.5482\",\"6\":\"39.90000\",\"7\":\"0.569\",\"8\":\"44\",\"9\":\"1\",\"_rn_\":\"358\"},{\"1\":\"12\",\"2\":\"88.0000\",\"3\":\"74.00000\",\"4\":\"40.00000\",\"5\":\"54.0000\",\"6\":\"35.30000\",\"7\":\"0.378\",\"8\":\"48\",\"9\":\"0\",\"_rn_\":\"359\"},{\"1\":\"1\",\"2\":\"196.0000\",\"3\":\"76.00000\",\"4\":\"36.00000\",\"5\":\"249.0000\",\"6\":\"36.50000\",\"7\":\"0.875\",\"8\":\"29\",\"9\":\"1\",\"_rn_\":\"360\"},{\"1\":\"5\",\"2\":\"189.0000\",\"3\":\"64.00000\",\"4\":\"33.00000\",\"5\":\"325.0000\",\"6\":\"31.20000\",\"7\":\"0.583\",\"8\":\"29\",\"9\":\"1\",\"_rn_\":\"361\"},{\"1\":\"5\",\"2\":\"158.0000\",\"3\":\"70.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"29.80000\",\"7\":\"0.207\",\"8\":\"63\",\"9\":\"0\",\"_rn_\":\"362\"},{\"1\":\"5\",\"2\":\"103.0000\",\"3\":\"108.00000\",\"4\":\"37.00000\",\"5\":\"155.5482\",\"6\":\"39.20000\",\"7\":\"0.305\",\"8\":\"65\",\"9\":\"0\",\"_rn_\":\"363\"},{\"1\":\"4\",\"2\":\"146.0000\",\"3\":\"78.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"38.50000\",\"7\":\"0.520\",\"8\":\"67\",\"9\":\"1\",\"_rn_\":\"364\"},{\"1\":\"4\",\"2\":\"147.0000\",\"3\":\"74.00000\",\"4\":\"25.00000\",\"5\":\"293.0000\",\"6\":\"34.90000\",\"7\":\"0.385\",\"8\":\"30\",\"9\":\"0\",\"_rn_\":\"365\"},{\"1\":\"5\",\"2\":\"99.0000\",\"3\":\"54.00000\",\"4\":\"28.00000\",\"5\":\"83.0000\",\"6\":\"34.00000\",\"7\":\"0.499\",\"8\":\"30\",\"9\":\"0\",\"_rn_\":\"366\"},{\"1\":\"6\",\"2\":\"124.0000\",\"3\":\"72.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"27.60000\",\"7\":\"0.368\",\"8\":\"29\",\"9\":\"1\",\"_rn_\":\"367\"},{\"1\":\"0\",\"2\":\"101.0000\",\"3\":\"64.00000\",\"4\":\"17.00000\",\"5\":\"155.5482\",\"6\":\"21.00000\",\"7\":\"0.252\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"368\"},{\"1\":\"3\",\"2\":\"81.0000\",\"3\":\"86.00000\",\"4\":\"16.00000\",\"5\":\"66.0000\",\"6\":\"27.50000\",\"7\":\"0.306\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"369\"},{\"1\":\"1\",\"2\":\"133.0000\",\"3\":\"102.00000\",\"4\":\"28.00000\",\"5\":\"140.0000\",\"6\":\"32.80000\",\"7\":\"0.234\",\"8\":\"45\",\"9\":\"1\",\"_rn_\":\"370\"},{\"1\":\"3\",\"2\":\"173.0000\",\"3\":\"82.00000\",\"4\":\"48.00000\",\"5\":\"465.0000\",\"6\":\"38.40000\",\"7\":\"2.137\",\"8\":\"25\",\"9\":\"1\",\"_rn_\":\"371\"},{\"1\":\"0\",\"2\":\"118.0000\",\"3\":\"64.00000\",\"4\":\"23.00000\",\"5\":\"89.0000\",\"6\":\"32.45746\",\"7\":\"1.731\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"372\"},{\"1\":\"0\",\"2\":\"84.0000\",\"3\":\"64.00000\",\"4\":\"22.00000\",\"5\":\"66.0000\",\"6\":\"35.80000\",\"7\":\"0.545\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"373\"},{\"1\":\"2\",\"2\":\"105.0000\",\"3\":\"58.00000\",\"4\":\"40.00000\",\"5\":\"94.0000\",\"6\":\"34.90000\",\"7\":\"0.225\",\"8\":\"25\",\"9\":\"0\",\"_rn_\":\"374\"},{\"1\":\"2\",\"2\":\"122.0000\",\"3\":\"52.00000\",\"4\":\"43.00000\",\"5\":\"158.0000\",\"6\":\"36.20000\",\"7\":\"0.816\",\"8\":\"28\",\"9\":\"0\",\"_rn_\":\"375\"},{\"1\":\"12\",\"2\":\"140.0000\",\"3\":\"82.00000\",\"4\":\"43.00000\",\"5\":\"325.0000\",\"6\":\"39.20000\",\"7\":\"0.528\",\"8\":\"58\",\"9\":\"1\",\"_rn_\":\"376\"},{\"1\":\"0\",\"2\":\"98.0000\",\"3\":\"82.00000\",\"4\":\"15.00000\",\"5\":\"84.0000\",\"6\":\"25.20000\",\"7\":\"0.299\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"377\"},{\"1\":\"1\",\"2\":\"87.0000\",\"3\":\"60.00000\",\"4\":\"37.00000\",\"5\":\"75.0000\",\"6\":\"37.20000\",\"7\":\"0.509\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"378\"},{\"1\":\"4\",\"2\":\"156.0000\",\"3\":\"75.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"48.30000\",\"7\":\"0.238\",\"8\":\"32\",\"9\":\"1\",\"_rn_\":\"379\"},{\"1\":\"0\",\"2\":\"93.0000\",\"3\":\"100.00000\",\"4\":\"39.00000\",\"5\":\"72.0000\",\"6\":\"43.40000\",\"7\":\"1.021\",\"8\":\"35\",\"9\":\"0\",\"_rn_\":\"380\"},{\"1\":\"1\",\"2\":\"107.0000\",\"3\":\"72.00000\",\"4\":\"30.00000\",\"5\":\"82.0000\",\"6\":\"30.80000\",\"7\":\"0.821\",\"8\":\"24\",\"9\":\"0\",\"_rn_\":\"381\"},{\"1\":\"0\",\"2\":\"105.0000\",\"3\":\"68.00000\",\"4\":\"22.00000\",\"5\":\"155.5482\",\"6\":\"20.00000\",\"7\":\"0.236\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"382\"},{\"1\":\"1\",\"2\":\"109.0000\",\"3\":\"60.00000\",\"4\":\"8.00000\",\"5\":\"182.0000\",\"6\":\"25.40000\",\"7\":\"0.947\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"383\"},{\"1\":\"1\",\"2\":\"90.0000\",\"3\":\"62.00000\",\"4\":\"18.00000\",\"5\":\"59.0000\",\"6\":\"25.10000\",\"7\":\"1.268\",\"8\":\"25\",\"9\":\"0\",\"_rn_\":\"384\"},{\"1\":\"1\",\"2\":\"125.0000\",\"3\":\"70.00000\",\"4\":\"24.00000\",\"5\":\"110.0000\",\"6\":\"24.30000\",\"7\":\"0.221\",\"8\":\"25\",\"9\":\"0\",\"_rn_\":\"385\"},{\"1\":\"1\",\"2\":\"119.0000\",\"3\":\"54.00000\",\"4\":\"13.00000\",\"5\":\"50.0000\",\"6\":\"22.30000\",\"7\":\"0.205\",\"8\":\"24\",\"9\":\"0\",\"_rn_\":\"386\"},{\"1\":\"5\",\"2\":\"116.0000\",\"3\":\"74.00000\",\"4\":\"29.00000\",\"5\":\"155.5482\",\"6\":\"32.30000\",\"7\":\"0.660\",\"8\":\"35\",\"9\":\"1\",\"_rn_\":\"387\"},{\"1\":\"8\",\"2\":\"105.0000\",\"3\":\"100.00000\",\"4\":\"36.00000\",\"5\":\"155.5482\",\"6\":\"43.30000\",\"7\":\"0.239\",\"8\":\"45\",\"9\":\"1\",\"_rn_\":\"388\"},{\"1\":\"5\",\"2\":\"144.0000\",\"3\":\"82.00000\",\"4\":\"26.00000\",\"5\":\"285.0000\",\"6\":\"32.00000\",\"7\":\"0.452\",\"8\":\"58\",\"9\":\"1\",\"_rn_\":\"389\"},{\"1\":\"3\",\"2\":\"100.0000\",\"3\":\"68.00000\",\"4\":\"23.00000\",\"5\":\"81.0000\",\"6\":\"31.60000\",\"7\":\"0.949\",\"8\":\"28\",\"9\":\"0\",\"_rn_\":\"390\"},{\"1\":\"1\",\"2\":\"100.0000\",\"3\":\"66.00000\",\"4\":\"29.00000\",\"5\":\"196.0000\",\"6\":\"32.00000\",\"7\":\"0.444\",\"8\":\"42\",\"9\":\"0\",\"_rn_\":\"391\"},{\"1\":\"5\",\"2\":\"166.0000\",\"3\":\"76.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"45.70000\",\"7\":\"0.340\",\"8\":\"27\",\"9\":\"1\",\"_rn_\":\"392\"},{\"1\":\"1\",\"2\":\"131.0000\",\"3\":\"64.00000\",\"4\":\"14.00000\",\"5\":\"415.0000\",\"6\":\"23.70000\",\"7\":\"0.389\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"393\"},{\"1\":\"4\",\"2\":\"116.0000\",\"3\":\"72.00000\",\"4\":\"12.00000\",\"5\":\"87.0000\",\"6\":\"22.10000\",\"7\":\"0.463\",\"8\":\"37\",\"9\":\"0\",\"_rn_\":\"394\"},{\"1\":\"4\",\"2\":\"158.0000\",\"3\":\"78.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"32.90000\",\"7\":\"0.803\",\"8\":\"31\",\"9\":\"1\",\"_rn_\":\"395\"},{\"1\":\"2\",\"2\":\"127.0000\",\"3\":\"58.00000\",\"4\":\"24.00000\",\"5\":\"275.0000\",\"6\":\"27.70000\",\"7\":\"1.600\",\"8\":\"25\",\"9\":\"0\",\"_rn_\":\"396\"},{\"1\":\"3\",\"2\":\"96.0000\",\"3\":\"56.00000\",\"4\":\"34.00000\",\"5\":\"115.0000\",\"6\":\"24.70000\",\"7\":\"0.944\",\"8\":\"39\",\"9\":\"0\",\"_rn_\":\"397\"},{\"1\":\"0\",\"2\":\"131.0000\",\"3\":\"66.00000\",\"4\":\"40.00000\",\"5\":\"155.5482\",\"6\":\"34.30000\",\"7\":\"0.196\",\"8\":\"22\",\"9\":\"1\",\"_rn_\":\"398\"},{\"1\":\"3\",\"2\":\"82.0000\",\"3\":\"70.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"21.10000\",\"7\":\"0.389\",\"8\":\"25\",\"9\":\"0\",\"_rn_\":\"399\"},{\"1\":\"3\",\"2\":\"193.0000\",\"3\":\"70.00000\",\"4\":\"31.00000\",\"5\":\"155.5482\",\"6\":\"34.90000\",\"7\":\"0.241\",\"8\":\"25\",\"9\":\"1\",\"_rn_\":\"400\"},{\"1\":\"4\",\"2\":\"95.0000\",\"3\":\"64.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"32.00000\",\"7\":\"0.161\",\"8\":\"31\",\"9\":\"1\",\"_rn_\":\"401\"},{\"1\":\"6\",\"2\":\"137.0000\",\"3\":\"61.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"24.20000\",\"7\":\"0.151\",\"8\":\"55\",\"9\":\"0\",\"_rn_\":\"402\"},{\"1\":\"5\",\"2\":\"136.0000\",\"3\":\"84.00000\",\"4\":\"41.00000\",\"5\":\"88.0000\",\"6\":\"35.00000\",\"7\":\"0.286\",\"8\":\"35\",\"9\":\"1\",\"_rn_\":\"403\"},{\"1\":\"9\",\"2\":\"72.0000\",\"3\":\"78.00000\",\"4\":\"25.00000\",\"5\":\"155.5482\",\"6\":\"31.60000\",\"7\":\"0.280\",\"8\":\"38\",\"9\":\"0\",\"_rn_\":\"404\"},{\"1\":\"5\",\"2\":\"168.0000\",\"3\":\"64.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"32.90000\",\"7\":\"0.135\",\"8\":\"41\",\"9\":\"1\",\"_rn_\":\"405\"},{\"1\":\"2\",\"2\":\"123.0000\",\"3\":\"48.00000\",\"4\":\"32.00000\",\"5\":\"165.0000\",\"6\":\"42.10000\",\"7\":\"0.520\",\"8\":\"26\",\"9\":\"0\",\"_rn_\":\"406\"},{\"1\":\"4\",\"2\":\"115.0000\",\"3\":\"72.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"28.90000\",\"7\":\"0.376\",\"8\":\"46\",\"9\":\"1\",\"_rn_\":\"407\"},{\"1\":\"0\",\"2\":\"101.0000\",\"3\":\"62.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"21.90000\",\"7\":\"0.336\",\"8\":\"25\",\"9\":\"0\",\"_rn_\":\"408\"},{\"1\":\"8\",\"2\":\"197.0000\",\"3\":\"74.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"25.90000\",\"7\":\"1.191\",\"8\":\"39\",\"9\":\"1\",\"_rn_\":\"409\"},{\"1\":\"1\",\"2\":\"172.0000\",\"3\":\"68.00000\",\"4\":\"49.00000\",\"5\":\"579.0000\",\"6\":\"42.40000\",\"7\":\"0.702\",\"8\":\"28\",\"9\":\"1\",\"_rn_\":\"410\"},{\"1\":\"6\",\"2\":\"102.0000\",\"3\":\"90.00000\",\"4\":\"39.00000\",\"5\":\"155.5482\",\"6\":\"35.70000\",\"7\":\"0.674\",\"8\":\"28\",\"9\":\"0\",\"_rn_\":\"411\"},{\"1\":\"1\",\"2\":\"112.0000\",\"3\":\"72.00000\",\"4\":\"30.00000\",\"5\":\"176.0000\",\"6\":\"34.40000\",\"7\":\"0.528\",\"8\":\"25\",\"9\":\"0\",\"_rn_\":\"412\"},{\"1\":\"1\",\"2\":\"143.0000\",\"3\":\"84.00000\",\"4\":\"23.00000\",\"5\":\"310.0000\",\"6\":\"42.40000\",\"7\":\"1.076\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"413\"},{\"1\":\"1\",\"2\":\"143.0000\",\"3\":\"74.00000\",\"4\":\"22.00000\",\"5\":\"61.0000\",\"6\":\"26.20000\",\"7\":\"0.256\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"414\"},{\"1\":\"0\",\"2\":\"138.0000\",\"3\":\"60.00000\",\"4\":\"35.00000\",\"5\":\"167.0000\",\"6\":\"34.60000\",\"7\":\"0.534\",\"8\":\"21\",\"9\":\"1\",\"_rn_\":\"415\"},{\"1\":\"3\",\"2\":\"173.0000\",\"3\":\"84.00000\",\"4\":\"33.00000\",\"5\":\"474.0000\",\"6\":\"35.70000\",\"7\":\"0.258\",\"8\":\"22\",\"9\":\"1\",\"_rn_\":\"416\"},{\"1\":\"1\",\"2\":\"97.0000\",\"3\":\"68.00000\",\"4\":\"21.00000\",\"5\":\"155.5482\",\"6\":\"27.20000\",\"7\":\"1.095\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"417\"},{\"1\":\"4\",\"2\":\"144.0000\",\"3\":\"82.00000\",\"4\":\"32.00000\",\"5\":\"155.5482\",\"6\":\"38.50000\",\"7\":\"0.554\",\"8\":\"37\",\"9\":\"1\",\"_rn_\":\"418\"},{\"1\":\"1\",\"2\":\"83.0000\",\"3\":\"68.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"18.20000\",\"7\":\"0.624\",\"8\":\"27\",\"9\":\"0\",\"_rn_\":\"419\"},{\"1\":\"3\",\"2\":\"129.0000\",\"3\":\"64.00000\",\"4\":\"29.00000\",\"5\":\"115.0000\",\"6\":\"26.40000\",\"7\":\"0.219\",\"8\":\"28\",\"9\":\"1\",\"_rn_\":\"420\"},{\"1\":\"1\",\"2\":\"119.0000\",\"3\":\"88.00000\",\"4\":\"41.00000\",\"5\":\"170.0000\",\"6\":\"45.30000\",\"7\":\"0.507\",\"8\":\"26\",\"9\":\"0\",\"_rn_\":\"421\"},{\"1\":\"2\",\"2\":\"94.0000\",\"3\":\"68.00000\",\"4\":\"18.00000\",\"5\":\"76.0000\",\"6\":\"26.00000\",\"7\":\"0.561\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"422\"},{\"1\":\"0\",\"2\":\"102.0000\",\"3\":\"64.00000\",\"4\":\"46.00000\",\"5\":\"78.0000\",\"6\":\"40.60000\",\"7\":\"0.496\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"423\"},{\"1\":\"2\",\"2\":\"115.0000\",\"3\":\"64.00000\",\"4\":\"22.00000\",\"5\":\"155.5482\",\"6\":\"30.80000\",\"7\":\"0.421\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"424\"},{\"1\":\"8\",\"2\":\"151.0000\",\"3\":\"78.00000\",\"4\":\"32.00000\",\"5\":\"210.0000\",\"6\":\"42.90000\",\"7\":\"0.516\",\"8\":\"36\",\"9\":\"1\",\"_rn_\":\"425\"},{\"1\":\"4\",\"2\":\"184.0000\",\"3\":\"78.00000\",\"4\":\"39.00000\",\"5\":\"277.0000\",\"6\":\"37.00000\",\"7\":\"0.264\",\"8\":\"31\",\"9\":\"1\",\"_rn_\":\"426\"},{\"1\":\"0\",\"2\":\"94.0000\",\"3\":\"72.40518\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"32.45746\",\"7\":\"0.256\",\"8\":\"25\",\"9\":\"0\",\"_rn_\":\"427\"},{\"1\":\"1\",\"2\":\"181.0000\",\"3\":\"64.00000\",\"4\":\"30.00000\",\"5\":\"180.0000\",\"6\":\"34.10000\",\"7\":\"0.328\",\"8\":\"38\",\"9\":\"1\",\"_rn_\":\"428\"},{\"1\":\"0\",\"2\":\"135.0000\",\"3\":\"94.00000\",\"4\":\"46.00000\",\"5\":\"145.0000\",\"6\":\"40.60000\",\"7\":\"0.284\",\"8\":\"26\",\"9\":\"0\",\"_rn_\":\"429\"},{\"1\":\"1\",\"2\":\"95.0000\",\"3\":\"82.00000\",\"4\":\"25.00000\",\"5\":\"180.0000\",\"6\":\"35.00000\",\"7\":\"0.233\",\"8\":\"43\",\"9\":\"1\",\"_rn_\":\"430\"},{\"1\":\"2\",\"2\":\"99.0000\",\"3\":\"72.40518\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"22.20000\",\"7\":\"0.108\",\"8\":\"23\",\"9\":\"0\",\"_rn_\":\"431\"},{\"1\":\"3\",\"2\":\"89.0000\",\"3\":\"74.00000\",\"4\":\"16.00000\",\"5\":\"85.0000\",\"6\":\"30.40000\",\"7\":\"0.551\",\"8\":\"38\",\"9\":\"0\",\"_rn_\":\"432\"},{\"1\":\"1\",\"2\":\"80.0000\",\"3\":\"74.00000\",\"4\":\"11.00000\",\"5\":\"60.0000\",\"6\":\"30.00000\",\"7\":\"0.527\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"433\"},{\"1\":\"2\",\"2\":\"139.0000\",\"3\":\"75.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"25.60000\",\"7\":\"0.167\",\"8\":\"29\",\"9\":\"0\",\"_rn_\":\"434\"},{\"1\":\"1\",\"2\":\"90.0000\",\"3\":\"68.00000\",\"4\":\"8.00000\",\"5\":\"155.5482\",\"6\":\"24.50000\",\"7\":\"1.138\",\"8\":\"36\",\"9\":\"0\",\"_rn_\":\"435\"},{\"1\":\"0\",\"2\":\"141.0000\",\"3\":\"72.40518\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"42.40000\",\"7\":\"0.205\",\"8\":\"29\",\"9\":\"1\",\"_rn_\":\"436\"},{\"1\":\"12\",\"2\":\"140.0000\",\"3\":\"85.00000\",\"4\":\"33.00000\",\"5\":\"155.5482\",\"6\":\"37.40000\",\"7\":\"0.244\",\"8\":\"41\",\"9\":\"0\",\"_rn_\":\"437\"},{\"1\":\"5\",\"2\":\"147.0000\",\"3\":\"75.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"29.90000\",\"7\":\"0.434\",\"8\":\"28\",\"9\":\"0\",\"_rn_\":\"438\"},{\"1\":\"1\",\"2\":\"97.0000\",\"3\":\"70.00000\",\"4\":\"15.00000\",\"5\":\"155.5482\",\"6\":\"18.20000\",\"7\":\"0.147\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"439\"},{\"1\":\"6\",\"2\":\"107.0000\",\"3\":\"88.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"36.80000\",\"7\":\"0.727\",\"8\":\"31\",\"9\":\"0\",\"_rn_\":\"440\"},{\"1\":\"0\",\"2\":\"189.0000\",\"3\":\"104.00000\",\"4\":\"25.00000\",\"5\":\"155.5482\",\"6\":\"34.30000\",\"7\":\"0.435\",\"8\":\"41\",\"9\":\"1\",\"_rn_\":\"441\"},{\"1\":\"2\",\"2\":\"83.0000\",\"3\":\"66.00000\",\"4\":\"23.00000\",\"5\":\"50.0000\",\"6\":\"32.20000\",\"7\":\"0.497\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"442\"},{\"1\":\"4\",\"2\":\"117.0000\",\"3\":\"64.00000\",\"4\":\"27.00000\",\"5\":\"120.0000\",\"6\":\"33.20000\",\"7\":\"0.230\",\"8\":\"24\",\"9\":\"0\",\"_rn_\":\"443\"},{\"1\":\"8\",\"2\":\"108.0000\",\"3\":\"70.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"30.50000\",\"7\":\"0.955\",\"8\":\"33\",\"9\":\"1\",\"_rn_\":\"444\"},{\"1\":\"4\",\"2\":\"117.0000\",\"3\":\"62.00000\",\"4\":\"12.00000\",\"5\":\"155.5482\",\"6\":\"29.70000\",\"7\":\"0.380\",\"8\":\"30\",\"9\":\"1\",\"_rn_\":\"445\"},{\"1\":\"0\",\"2\":\"180.0000\",\"3\":\"78.00000\",\"4\":\"63.00000\",\"5\":\"14.0000\",\"6\":\"59.40000\",\"7\":\"2.420\",\"8\":\"25\",\"9\":\"1\",\"_rn_\":\"446\"},{\"1\":\"1\",\"2\":\"100.0000\",\"3\":\"72.00000\",\"4\":\"12.00000\",\"5\":\"70.0000\",\"6\":\"25.30000\",\"7\":\"0.658\",\"8\":\"28\",\"9\":\"0\",\"_rn_\":\"447\"},{\"1\":\"0\",\"2\":\"95.0000\",\"3\":\"80.00000\",\"4\":\"45.00000\",\"5\":\"92.0000\",\"6\":\"36.50000\",\"7\":\"0.330\",\"8\":\"26\",\"9\":\"0\",\"_rn_\":\"448\"},{\"1\":\"0\",\"2\":\"104.0000\",\"3\":\"64.00000\",\"4\":\"37.00000\",\"5\":\"64.0000\",\"6\":\"33.60000\",\"7\":\"0.510\",\"8\":\"22\",\"9\":\"1\",\"_rn_\":\"449\"},{\"1\":\"0\",\"2\":\"120.0000\",\"3\":\"74.00000\",\"4\":\"18.00000\",\"5\":\"63.0000\",\"6\":\"30.50000\",\"7\":\"0.285\",\"8\":\"26\",\"9\":\"0\",\"_rn_\":\"450\"},{\"1\":\"1\",\"2\":\"82.0000\",\"3\":\"64.00000\",\"4\":\"13.00000\",\"5\":\"95.0000\",\"6\":\"21.20000\",\"7\":\"0.415\",\"8\":\"23\",\"9\":\"0\",\"_rn_\":\"451\"},{\"1\":\"2\",\"2\":\"134.0000\",\"3\":\"70.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"28.90000\",\"7\":\"0.542\",\"8\":\"23\",\"9\":\"1\",\"_rn_\":\"452\"},{\"1\":\"0\",\"2\":\"91.0000\",\"3\":\"68.00000\",\"4\":\"32.00000\",\"5\":\"210.0000\",\"6\":\"39.90000\",\"7\":\"0.381\",\"8\":\"25\",\"9\":\"0\",\"_rn_\":\"453\"},{\"1\":\"2\",\"2\":\"119.0000\",\"3\":\"72.40518\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"19.60000\",\"7\":\"0.832\",\"8\":\"72\",\"9\":\"0\",\"_rn_\":\"454\"},{\"1\":\"2\",\"2\":\"100.0000\",\"3\":\"54.00000\",\"4\":\"28.00000\",\"5\":\"105.0000\",\"6\":\"37.80000\",\"7\":\"0.498\",\"8\":\"24\",\"9\":\"0\",\"_rn_\":\"455\"},{\"1\":\"14\",\"2\":\"175.0000\",\"3\":\"62.00000\",\"4\":\"30.00000\",\"5\":\"155.5482\",\"6\":\"33.60000\",\"7\":\"0.212\",\"8\":\"38\",\"9\":\"1\",\"_rn_\":\"456\"},{\"1\":\"1\",\"2\":\"135.0000\",\"3\":\"54.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"26.70000\",\"7\":\"0.687\",\"8\":\"62\",\"9\":\"0\",\"_rn_\":\"457\"},{\"1\":\"5\",\"2\":\"86.0000\",\"3\":\"68.00000\",\"4\":\"28.00000\",\"5\":\"71.0000\",\"6\":\"30.20000\",\"7\":\"0.364\",\"8\":\"24\",\"9\":\"0\",\"_rn_\":\"458\"},{\"1\":\"10\",\"2\":\"148.0000\",\"3\":\"84.00000\",\"4\":\"48.00000\",\"5\":\"237.0000\",\"6\":\"37.60000\",\"7\":\"1.001\",\"8\":\"51\",\"9\":\"1\",\"_rn_\":\"459\"},{\"1\":\"9\",\"2\":\"134.0000\",\"3\":\"74.00000\",\"4\":\"33.00000\",\"5\":\"60.0000\",\"6\":\"25.90000\",\"7\":\"0.460\",\"8\":\"81\",\"9\":\"0\",\"_rn_\":\"460\"},{\"1\":\"9\",\"2\":\"120.0000\",\"3\":\"72.00000\",\"4\":\"22.00000\",\"5\":\"56.0000\",\"6\":\"20.80000\",\"7\":\"0.733\",\"8\":\"48\",\"9\":\"0\",\"_rn_\":\"461\"},{\"1\":\"1\",\"2\":\"71.0000\",\"3\":\"62.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"21.80000\",\"7\":\"0.416\",\"8\":\"26\",\"9\":\"0\",\"_rn_\":\"462\"},{\"1\":\"8\",\"2\":\"74.0000\",\"3\":\"70.00000\",\"4\":\"40.00000\",\"5\":\"49.0000\",\"6\":\"35.30000\",\"7\":\"0.705\",\"8\":\"39\",\"9\":\"0\",\"_rn_\":\"463\"},{\"1\":\"5\",\"2\":\"88.0000\",\"3\":\"78.00000\",\"4\":\"30.00000\",\"5\":\"155.5482\",\"6\":\"27.60000\",\"7\":\"0.258\",\"8\":\"37\",\"9\":\"0\",\"_rn_\":\"464\"},{\"1\":\"10\",\"2\":\"115.0000\",\"3\":\"98.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"24.00000\",\"7\":\"1.022\",\"8\":\"34\",\"9\":\"0\",\"_rn_\":\"465\"},{\"1\":\"0\",\"2\":\"124.0000\",\"3\":\"56.00000\",\"4\":\"13.00000\",\"5\":\"105.0000\",\"6\":\"21.80000\",\"7\":\"0.452\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"466\"},{\"1\":\"0\",\"2\":\"74.0000\",\"3\":\"52.00000\",\"4\":\"10.00000\",\"5\":\"36.0000\",\"6\":\"27.80000\",\"7\":\"0.269\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"467\"},{\"1\":\"0\",\"2\":\"97.0000\",\"3\":\"64.00000\",\"4\":\"36.00000\",\"5\":\"100.0000\",\"6\":\"36.80000\",\"7\":\"0.600\",\"8\":\"25\",\"9\":\"0\",\"_rn_\":\"468\"},{\"1\":\"8\",\"2\":\"120.0000\",\"3\":\"72.40518\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"30.00000\",\"7\":\"0.183\",\"8\":\"38\",\"9\":\"1\",\"_rn_\":\"469\"},{\"1\":\"6\",\"2\":\"154.0000\",\"3\":\"78.00000\",\"4\":\"41.00000\",\"5\":\"140.0000\",\"6\":\"46.10000\",\"7\":\"0.571\",\"8\":\"27\",\"9\":\"0\",\"_rn_\":\"470\"},{\"1\":\"1\",\"2\":\"144.0000\",\"3\":\"82.00000\",\"4\":\"40.00000\",\"5\":\"155.5482\",\"6\":\"41.30000\",\"7\":\"0.607\",\"8\":\"28\",\"9\":\"0\",\"_rn_\":\"471\"},{\"1\":\"0\",\"2\":\"137.0000\",\"3\":\"70.00000\",\"4\":\"38.00000\",\"5\":\"155.5482\",\"6\":\"33.20000\",\"7\":\"0.170\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"472\"},{\"1\":\"0\",\"2\":\"119.0000\",\"3\":\"66.00000\",\"4\":\"27.00000\",\"5\":\"155.5482\",\"6\":\"38.80000\",\"7\":\"0.259\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"473\"},{\"1\":\"7\",\"2\":\"136.0000\",\"3\":\"90.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"29.90000\",\"7\":\"0.210\",\"8\":\"50\",\"9\":\"0\",\"_rn_\":\"474\"},{\"1\":\"4\",\"2\":\"114.0000\",\"3\":\"64.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"28.90000\",\"7\":\"0.126\",\"8\":\"24\",\"9\":\"0\",\"_rn_\":\"475\"},{\"1\":\"0\",\"2\":\"137.0000\",\"3\":\"84.00000\",\"4\":\"27.00000\",\"5\":\"155.5482\",\"6\":\"27.30000\",\"7\":\"0.231\",\"8\":\"59\",\"9\":\"0\",\"_rn_\":\"476\"},{\"1\":\"2\",\"2\":\"105.0000\",\"3\":\"80.00000\",\"4\":\"45.00000\",\"5\":\"191.0000\",\"6\":\"33.70000\",\"7\":\"0.711\",\"8\":\"29\",\"9\":\"1\",\"_rn_\":\"477\"},{\"1\":\"7\",\"2\":\"114.0000\",\"3\":\"76.00000\",\"4\":\"17.00000\",\"5\":\"110.0000\",\"6\":\"23.80000\",\"7\":\"0.466\",\"8\":\"31\",\"9\":\"0\",\"_rn_\":\"478\"},{\"1\":\"8\",\"2\":\"126.0000\",\"3\":\"74.00000\",\"4\":\"38.00000\",\"5\":\"75.0000\",\"6\":\"25.90000\",\"7\":\"0.162\",\"8\":\"39\",\"9\":\"0\",\"_rn_\":\"479\"},{\"1\":\"4\",\"2\":\"132.0000\",\"3\":\"86.00000\",\"4\":\"31.00000\",\"5\":\"155.5482\",\"6\":\"28.00000\",\"7\":\"0.419\",\"8\":\"63\",\"9\":\"0\",\"_rn_\":\"480\"},{\"1\":\"3\",\"2\":\"158.0000\",\"3\":\"70.00000\",\"4\":\"30.00000\",\"5\":\"328.0000\",\"6\":\"35.50000\",\"7\":\"0.344\",\"8\":\"35\",\"9\":\"1\",\"_rn_\":\"481\"},{\"1\":\"0\",\"2\":\"123.0000\",\"3\":\"88.00000\",\"4\":\"37.00000\",\"5\":\"155.5482\",\"6\":\"35.20000\",\"7\":\"0.197\",\"8\":\"29\",\"9\":\"0\",\"_rn_\":\"482\"},{\"1\":\"4\",\"2\":\"85.0000\",\"3\":\"58.00000\",\"4\":\"22.00000\",\"5\":\"49.0000\",\"6\":\"27.80000\",\"7\":\"0.306\",\"8\":\"28\",\"9\":\"0\",\"_rn_\":\"483\"},{\"1\":\"0\",\"2\":\"84.0000\",\"3\":\"82.00000\",\"4\":\"31.00000\",\"5\":\"125.0000\",\"6\":\"38.20000\",\"7\":\"0.233\",\"8\":\"23\",\"9\":\"0\",\"_rn_\":\"484\"},{\"1\":\"0\",\"2\":\"145.0000\",\"3\":\"72.40518\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"44.20000\",\"7\":\"0.630\",\"8\":\"31\",\"9\":\"1\",\"_rn_\":\"485\"},{\"1\":\"0\",\"2\":\"135.0000\",\"3\":\"68.00000\",\"4\":\"42.00000\",\"5\":\"250.0000\",\"6\":\"42.30000\",\"7\":\"0.365\",\"8\":\"24\",\"9\":\"1\",\"_rn_\":\"486\"},{\"1\":\"1\",\"2\":\"139.0000\",\"3\":\"62.00000\",\"4\":\"41.00000\",\"5\":\"480.0000\",\"6\":\"40.70000\",\"7\":\"0.536\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"487\"},{\"1\":\"0\",\"2\":\"173.0000\",\"3\":\"78.00000\",\"4\":\"32.00000\",\"5\":\"265.0000\",\"6\":\"46.50000\",\"7\":\"1.159\",\"8\":\"58\",\"9\":\"0\",\"_rn_\":\"488\"},{\"1\":\"4\",\"2\":\"99.0000\",\"3\":\"72.00000\",\"4\":\"17.00000\",\"5\":\"155.5482\",\"6\":\"25.60000\",\"7\":\"0.294\",\"8\":\"28\",\"9\":\"0\",\"_rn_\":\"489\"},{\"1\":\"8\",\"2\":\"194.0000\",\"3\":\"80.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"26.10000\",\"7\":\"0.551\",\"8\":\"67\",\"9\":\"0\",\"_rn_\":\"490\"},{\"1\":\"2\",\"2\":\"83.0000\",\"3\":\"65.00000\",\"4\":\"28.00000\",\"5\":\"66.0000\",\"6\":\"36.80000\",\"7\":\"0.629\",\"8\":\"24\",\"9\":\"0\",\"_rn_\":\"491\"},{\"1\":\"2\",\"2\":\"89.0000\",\"3\":\"90.00000\",\"4\":\"30.00000\",\"5\":\"155.5482\",\"6\":\"33.50000\",\"7\":\"0.292\",\"8\":\"42\",\"9\":\"0\",\"_rn_\":\"492\"},{\"1\":\"4\",\"2\":\"99.0000\",\"3\":\"68.00000\",\"4\":\"38.00000\",\"5\":\"155.5482\",\"6\":\"32.80000\",\"7\":\"0.145\",\"8\":\"33\",\"9\":\"0\",\"_rn_\":\"493\"},{\"1\":\"4\",\"2\":\"125.0000\",\"3\":\"70.00000\",\"4\":\"18.00000\",\"5\":\"122.0000\",\"6\":\"28.90000\",\"7\":\"1.144\",\"8\":\"45\",\"9\":\"1\",\"_rn_\":\"494\"},{\"1\":\"3\",\"2\":\"80.0000\",\"3\":\"72.40518\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"32.45746\",\"7\":\"0.174\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"495\"},{\"1\":\"6\",\"2\":\"166.0000\",\"3\":\"74.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"26.60000\",\"7\":\"0.304\",\"8\":\"66\",\"9\":\"0\",\"_rn_\":\"496\"},{\"1\":\"5\",\"2\":\"110.0000\",\"3\":\"68.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"26.00000\",\"7\":\"0.292\",\"8\":\"30\",\"9\":\"0\",\"_rn_\":\"497\"},{\"1\":\"2\",\"2\":\"81.0000\",\"3\":\"72.00000\",\"4\":\"15.00000\",\"5\":\"76.0000\",\"6\":\"30.10000\",\"7\":\"0.547\",\"8\":\"25\",\"9\":\"0\",\"_rn_\":\"498\"},{\"1\":\"7\",\"2\":\"195.0000\",\"3\":\"70.00000\",\"4\":\"33.00000\",\"5\":\"145.0000\",\"6\":\"25.10000\",\"7\":\"0.163\",\"8\":\"55\",\"9\":\"1\",\"_rn_\":\"499\"},{\"1\":\"6\",\"2\":\"154.0000\",\"3\":\"74.00000\",\"4\":\"32.00000\",\"5\":\"193.0000\",\"6\":\"29.30000\",\"7\":\"0.839\",\"8\":\"39\",\"9\":\"0\",\"_rn_\":\"500\"},{\"1\":\"2\",\"2\":\"117.0000\",\"3\":\"90.00000\",\"4\":\"19.00000\",\"5\":\"71.0000\",\"6\":\"25.20000\",\"7\":\"0.313\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"501\"},{\"1\":\"3\",\"2\":\"84.0000\",\"3\":\"72.00000\",\"4\":\"32.00000\",\"5\":\"155.5482\",\"6\":\"37.20000\",\"7\":\"0.267\",\"8\":\"28\",\"9\":\"0\",\"_rn_\":\"502\"},{\"1\":\"6\",\"2\":\"121.6868\",\"3\":\"68.00000\",\"4\":\"41.00000\",\"5\":\"155.5482\",\"6\":\"39.00000\",\"7\":\"0.727\",\"8\":\"41\",\"9\":\"1\",\"_rn_\":\"503\"},{\"1\":\"7\",\"2\":\"94.0000\",\"3\":\"64.00000\",\"4\":\"25.00000\",\"5\":\"79.0000\",\"6\":\"33.30000\",\"7\":\"0.738\",\"8\":\"41\",\"9\":\"0\",\"_rn_\":\"504\"},{\"1\":\"3\",\"2\":\"96.0000\",\"3\":\"78.00000\",\"4\":\"39.00000\",\"5\":\"155.5482\",\"6\":\"37.30000\",\"7\":\"0.238\",\"8\":\"40\",\"9\":\"0\",\"_rn_\":\"505\"},{\"1\":\"10\",\"2\":\"75.0000\",\"3\":\"82.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"33.30000\",\"7\":\"0.263\",\"8\":\"38\",\"9\":\"0\",\"_rn_\":\"506\"},{\"1\":\"0\",\"2\":\"180.0000\",\"3\":\"90.00000\",\"4\":\"26.00000\",\"5\":\"90.0000\",\"6\":\"36.50000\",\"7\":\"0.314\",\"8\":\"35\",\"9\":\"1\",\"_rn_\":\"507\"},{\"1\":\"1\",\"2\":\"130.0000\",\"3\":\"60.00000\",\"4\":\"23.00000\",\"5\":\"170.0000\",\"6\":\"28.60000\",\"7\":\"0.692\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"508\"},{\"1\":\"2\",\"2\":\"84.0000\",\"3\":\"50.00000\",\"4\":\"23.00000\",\"5\":\"76.0000\",\"6\":\"30.40000\",\"7\":\"0.968\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"509\"},{\"1\":\"8\",\"2\":\"120.0000\",\"3\":\"78.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"25.00000\",\"7\":\"0.409\",\"8\":\"64\",\"9\":\"0\",\"_rn_\":\"510\"},{\"1\":\"12\",\"2\":\"84.0000\",\"3\":\"72.00000\",\"4\":\"31.00000\",\"5\":\"155.5482\",\"6\":\"29.70000\",\"7\":\"0.297\",\"8\":\"46\",\"9\":\"1\",\"_rn_\":\"511\"},{\"1\":\"0\",\"2\":\"139.0000\",\"3\":\"62.00000\",\"4\":\"17.00000\",\"5\":\"210.0000\",\"6\":\"22.10000\",\"7\":\"0.207\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"512\"},{\"1\":\"9\",\"2\":\"91.0000\",\"3\":\"68.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"24.20000\",\"7\":\"0.200\",\"8\":\"58\",\"9\":\"0\",\"_rn_\":\"513\"},{\"1\":\"2\",\"2\":\"91.0000\",\"3\":\"62.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"27.30000\",\"7\":\"0.525\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"514\"},{\"1\":\"3\",\"2\":\"99.0000\",\"3\":\"54.00000\",\"4\":\"19.00000\",\"5\":\"86.0000\",\"6\":\"25.60000\",\"7\":\"0.154\",\"8\":\"24\",\"9\":\"0\",\"_rn_\":\"515\"},{\"1\":\"3\",\"2\":\"163.0000\",\"3\":\"70.00000\",\"4\":\"18.00000\",\"5\":\"105.0000\",\"6\":\"31.60000\",\"7\":\"0.268\",\"8\":\"28\",\"9\":\"1\",\"_rn_\":\"516\"},{\"1\":\"9\",\"2\":\"145.0000\",\"3\":\"88.00000\",\"4\":\"34.00000\",\"5\":\"165.0000\",\"6\":\"30.30000\",\"7\":\"0.771\",\"8\":\"53\",\"9\":\"1\",\"_rn_\":\"517\"},{\"1\":\"7\",\"2\":\"125.0000\",\"3\":\"86.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"37.60000\",\"7\":\"0.304\",\"8\":\"51\",\"9\":\"0\",\"_rn_\":\"518\"},{\"1\":\"13\",\"2\":\"76.0000\",\"3\":\"60.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"32.80000\",\"7\":\"0.180\",\"8\":\"41\",\"9\":\"0\",\"_rn_\":\"519\"},{\"1\":\"6\",\"2\":\"129.0000\",\"3\":\"90.00000\",\"4\":\"7.00000\",\"5\":\"326.0000\",\"6\":\"19.60000\",\"7\":\"0.582\",\"8\":\"60\",\"9\":\"0\",\"_rn_\":\"520\"},{\"1\":\"2\",\"2\":\"68.0000\",\"3\":\"70.00000\",\"4\":\"32.00000\",\"5\":\"66.0000\",\"6\":\"25.00000\",\"7\":\"0.187\",\"8\":\"25\",\"9\":\"0\",\"_rn_\":\"521\"},{\"1\":\"3\",\"2\":\"124.0000\",\"3\":\"80.00000\",\"4\":\"33.00000\",\"5\":\"130.0000\",\"6\":\"33.20000\",\"7\":\"0.305\",\"8\":\"26\",\"9\":\"0\",\"_rn_\":\"522\"},{\"1\":\"6\",\"2\":\"114.0000\",\"3\":\"72.40518\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"32.45746\",\"7\":\"0.189\",\"8\":\"26\",\"9\":\"0\",\"_rn_\":\"523\"},{\"1\":\"9\",\"2\":\"130.0000\",\"3\":\"70.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"34.20000\",\"7\":\"0.652\",\"8\":\"45\",\"9\":\"1\",\"_rn_\":\"524\"},{\"1\":\"3\",\"2\":\"125.0000\",\"3\":\"58.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"31.60000\",\"7\":\"0.151\",\"8\":\"24\",\"9\":\"0\",\"_rn_\":\"525\"},{\"1\":\"3\",\"2\":\"87.0000\",\"3\":\"60.00000\",\"4\":\"18.00000\",\"5\":\"155.5482\",\"6\":\"21.80000\",\"7\":\"0.444\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"526\"},{\"1\":\"1\",\"2\":\"97.0000\",\"3\":\"64.00000\",\"4\":\"19.00000\",\"5\":\"82.0000\",\"6\":\"18.20000\",\"7\":\"0.299\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"527\"},{\"1\":\"3\",\"2\":\"116.0000\",\"3\":\"74.00000\",\"4\":\"15.00000\",\"5\":\"105.0000\",\"6\":\"26.30000\",\"7\":\"0.107\",\"8\":\"24\",\"9\":\"0\",\"_rn_\":\"528\"},{\"1\":\"0\",\"2\":\"117.0000\",\"3\":\"66.00000\",\"4\":\"31.00000\",\"5\":\"188.0000\",\"6\":\"30.80000\",\"7\":\"0.493\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"529\"},{\"1\":\"0\",\"2\":\"111.0000\",\"3\":\"65.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"24.60000\",\"7\":\"0.660\",\"8\":\"31\",\"9\":\"0\",\"_rn_\":\"530\"},{\"1\":\"2\",\"2\":\"122.0000\",\"3\":\"60.00000\",\"4\":\"18.00000\",\"5\":\"106.0000\",\"6\":\"29.80000\",\"7\":\"0.717\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"531\"},{\"1\":\"0\",\"2\":\"107.0000\",\"3\":\"76.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"45.30000\",\"7\":\"0.686\",\"8\":\"24\",\"9\":\"0\",\"_rn_\":\"532\"},{\"1\":\"1\",\"2\":\"86.0000\",\"3\":\"66.00000\",\"4\":\"52.00000\",\"5\":\"65.0000\",\"6\":\"41.30000\",\"7\":\"0.917\",\"8\":\"29\",\"9\":\"0\",\"_rn_\":\"533\"},{\"1\":\"6\",\"2\":\"91.0000\",\"3\":\"72.40518\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"29.80000\",\"7\":\"0.501\",\"8\":\"31\",\"9\":\"0\",\"_rn_\":\"534\"},{\"1\":\"1\",\"2\":\"77.0000\",\"3\":\"56.00000\",\"4\":\"30.00000\",\"5\":\"56.0000\",\"6\":\"33.30000\",\"7\":\"1.251\",\"8\":\"24\",\"9\":\"0\",\"_rn_\":\"535\"},{\"1\":\"4\",\"2\":\"132.0000\",\"3\":\"72.40518\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"32.90000\",\"7\":\"0.302\",\"8\":\"23\",\"9\":\"1\",\"_rn_\":\"536\"},{\"1\":\"0\",\"2\":\"105.0000\",\"3\":\"90.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"29.60000\",\"7\":\"0.197\",\"8\":\"46\",\"9\":\"0\",\"_rn_\":\"537\"},{\"1\":\"0\",\"2\":\"57.0000\",\"3\":\"60.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"21.70000\",\"7\":\"0.735\",\"8\":\"67\",\"9\":\"0\",\"_rn_\":\"538\"},{\"1\":\"0\",\"2\":\"127.0000\",\"3\":\"80.00000\",\"4\":\"37.00000\",\"5\":\"210.0000\",\"6\":\"36.30000\",\"7\":\"0.804\",\"8\":\"23\",\"9\":\"0\",\"_rn_\":\"539\"},{\"1\":\"3\",\"2\":\"129.0000\",\"3\":\"92.00000\",\"4\":\"49.00000\",\"5\":\"155.0000\",\"6\":\"36.40000\",\"7\":\"0.968\",\"8\":\"32\",\"9\":\"1\",\"_rn_\":\"540\"},{\"1\":\"8\",\"2\":\"100.0000\",\"3\":\"74.00000\",\"4\":\"40.00000\",\"5\":\"215.0000\",\"6\":\"39.40000\",\"7\":\"0.661\",\"8\":\"43\",\"9\":\"1\",\"_rn_\":\"541\"},{\"1\":\"3\",\"2\":\"128.0000\",\"3\":\"72.00000\",\"4\":\"25.00000\",\"5\":\"190.0000\",\"6\":\"32.40000\",\"7\":\"0.549\",\"8\":\"27\",\"9\":\"1\",\"_rn_\":\"542\"},{\"1\":\"10\",\"2\":\"90.0000\",\"3\":\"85.00000\",\"4\":\"32.00000\",\"5\":\"155.5482\",\"6\":\"34.90000\",\"7\":\"0.825\",\"8\":\"56\",\"9\":\"1\",\"_rn_\":\"543\"},{\"1\":\"4\",\"2\":\"84.0000\",\"3\":\"90.00000\",\"4\":\"23.00000\",\"5\":\"56.0000\",\"6\":\"39.50000\",\"7\":\"0.159\",\"8\":\"25\",\"9\":\"0\",\"_rn_\":\"544\"},{\"1\":\"1\",\"2\":\"88.0000\",\"3\":\"78.00000\",\"4\":\"29.00000\",\"5\":\"76.0000\",\"6\":\"32.00000\",\"7\":\"0.365\",\"8\":\"29\",\"9\":\"0\",\"_rn_\":\"545\"},{\"1\":\"8\",\"2\":\"186.0000\",\"3\":\"90.00000\",\"4\":\"35.00000\",\"5\":\"225.0000\",\"6\":\"34.50000\",\"7\":\"0.423\",\"8\":\"37\",\"9\":\"1\",\"_rn_\":\"546\"},{\"1\":\"5\",\"2\":\"187.0000\",\"3\":\"76.00000\",\"4\":\"27.00000\",\"5\":\"207.0000\",\"6\":\"43.60000\",\"7\":\"1.034\",\"8\":\"53\",\"9\":\"1\",\"_rn_\":\"547\"},{\"1\":\"4\",\"2\":\"131.0000\",\"3\":\"68.00000\",\"4\":\"21.00000\",\"5\":\"166.0000\",\"6\":\"33.10000\",\"7\":\"0.160\",\"8\":\"28\",\"9\":\"0\",\"_rn_\":\"548\"},{\"1\":\"1\",\"2\":\"164.0000\",\"3\":\"82.00000\",\"4\":\"43.00000\",\"5\":\"67.0000\",\"6\":\"32.80000\",\"7\":\"0.341\",\"8\":\"50\",\"9\":\"0\",\"_rn_\":\"549\"},{\"1\":\"4\",\"2\":\"189.0000\",\"3\":\"110.00000\",\"4\":\"31.00000\",\"5\":\"155.5482\",\"6\":\"28.50000\",\"7\":\"0.680\",\"8\":\"37\",\"9\":\"0\",\"_rn_\":\"550\"},{\"1\":\"1\",\"2\":\"116.0000\",\"3\":\"70.00000\",\"4\":\"28.00000\",\"5\":\"155.5482\",\"6\":\"27.40000\",\"7\":\"0.204\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"551\"},{\"1\":\"3\",\"2\":\"84.0000\",\"3\":\"68.00000\",\"4\":\"30.00000\",\"5\":\"106.0000\",\"6\":\"31.90000\",\"7\":\"0.591\",\"8\":\"25\",\"9\":\"0\",\"_rn_\":\"552\"},{\"1\":\"6\",\"2\":\"114.0000\",\"3\":\"88.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"27.80000\",\"7\":\"0.247\",\"8\":\"66\",\"9\":\"0\",\"_rn_\":\"553\"},{\"1\":\"1\",\"2\":\"88.0000\",\"3\":\"62.00000\",\"4\":\"24.00000\",\"5\":\"44.0000\",\"6\":\"29.90000\",\"7\":\"0.422\",\"8\":\"23\",\"9\":\"0\",\"_rn_\":\"554\"},{\"1\":\"1\",\"2\":\"84.0000\",\"3\":\"64.00000\",\"4\":\"23.00000\",\"5\":\"115.0000\",\"6\":\"36.90000\",\"7\":\"0.471\",\"8\":\"28\",\"9\":\"0\",\"_rn_\":\"555\"},{\"1\":\"7\",\"2\":\"124.0000\",\"3\":\"70.00000\",\"4\":\"33.00000\",\"5\":\"215.0000\",\"6\":\"25.50000\",\"7\":\"0.161\",\"8\":\"37\",\"9\":\"0\",\"_rn_\":\"556\"},{\"1\":\"1\",\"2\":\"97.0000\",\"3\":\"70.00000\",\"4\":\"40.00000\",\"5\":\"155.5482\",\"6\":\"38.10000\",\"7\":\"0.218\",\"8\":\"30\",\"9\":\"0\",\"_rn_\":\"557\"},{\"1\":\"8\",\"2\":\"110.0000\",\"3\":\"76.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"27.80000\",\"7\":\"0.237\",\"8\":\"58\",\"9\":\"0\",\"_rn_\":\"558\"},{\"1\":\"11\",\"2\":\"103.0000\",\"3\":\"68.00000\",\"4\":\"40.00000\",\"5\":\"155.5482\",\"6\":\"46.20000\",\"7\":\"0.126\",\"8\":\"42\",\"9\":\"0\",\"_rn_\":\"559\"},{\"1\":\"11\",\"2\":\"85.0000\",\"3\":\"74.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"30.10000\",\"7\":\"0.300\",\"8\":\"35\",\"9\":\"0\",\"_rn_\":\"560\"},{\"1\":\"6\",\"2\":\"125.0000\",\"3\":\"76.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"33.80000\",\"7\":\"0.121\",\"8\":\"54\",\"9\":\"1\",\"_rn_\":\"561\"},{\"1\":\"0\",\"2\":\"198.0000\",\"3\":\"66.00000\",\"4\":\"32.00000\",\"5\":\"274.0000\",\"6\":\"41.30000\",\"7\":\"0.502\",\"8\":\"28\",\"9\":\"1\",\"_rn_\":\"562\"},{\"1\":\"1\",\"2\":\"87.0000\",\"3\":\"68.00000\",\"4\":\"34.00000\",\"5\":\"77.0000\",\"6\":\"37.60000\",\"7\":\"0.401\",\"8\":\"24\",\"9\":\"0\",\"_rn_\":\"563\"},{\"1\":\"6\",\"2\":\"99.0000\",\"3\":\"60.00000\",\"4\":\"19.00000\",\"5\":\"54.0000\",\"6\":\"26.90000\",\"7\":\"0.497\",\"8\":\"32\",\"9\":\"0\",\"_rn_\":\"564\"},{\"1\":\"0\",\"2\":\"91.0000\",\"3\":\"80.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"32.40000\",\"7\":\"0.601\",\"8\":\"27\",\"9\":\"0\",\"_rn_\":\"565\"},{\"1\":\"2\",\"2\":\"95.0000\",\"3\":\"54.00000\",\"4\":\"14.00000\",\"5\":\"88.0000\",\"6\":\"26.10000\",\"7\":\"0.748\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"566\"},{\"1\":\"1\",\"2\":\"99.0000\",\"3\":\"72.00000\",\"4\":\"30.00000\",\"5\":\"18.0000\",\"6\":\"38.60000\",\"7\":\"0.412\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"567\"},{\"1\":\"6\",\"2\":\"92.0000\",\"3\":\"62.00000\",\"4\":\"32.00000\",\"5\":\"126.0000\",\"6\":\"32.00000\",\"7\":\"0.085\",\"8\":\"46\",\"9\":\"0\",\"_rn_\":\"568\"},{\"1\":\"4\",\"2\":\"154.0000\",\"3\":\"72.00000\",\"4\":\"29.00000\",\"5\":\"126.0000\",\"6\":\"31.30000\",\"7\":\"0.338\",\"8\":\"37\",\"9\":\"0\",\"_rn_\":\"569\"},{\"1\":\"0\",\"2\":\"121.0000\",\"3\":\"66.00000\",\"4\":\"30.00000\",\"5\":\"165.0000\",\"6\":\"34.30000\",\"7\":\"0.203\",\"8\":\"33\",\"9\":\"1\",\"_rn_\":\"570\"},{\"1\":\"3\",\"2\":\"78.0000\",\"3\":\"70.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"32.50000\",\"7\":\"0.270\",\"8\":\"39\",\"9\":\"0\",\"_rn_\":\"571\"},{\"1\":\"2\",\"2\":\"130.0000\",\"3\":\"96.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"22.60000\",\"7\":\"0.268\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"572\"},{\"1\":\"3\",\"2\":\"111.0000\",\"3\":\"58.00000\",\"4\":\"31.00000\",\"5\":\"44.0000\",\"6\":\"29.50000\",\"7\":\"0.430\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"573\"},{\"1\":\"2\",\"2\":\"98.0000\",\"3\":\"60.00000\",\"4\":\"17.00000\",\"5\":\"120.0000\",\"6\":\"34.70000\",\"7\":\"0.198\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"574\"},{\"1\":\"1\",\"2\":\"143.0000\",\"3\":\"86.00000\",\"4\":\"30.00000\",\"5\":\"330.0000\",\"6\":\"30.10000\",\"7\":\"0.892\",\"8\":\"23\",\"9\":\"0\",\"_rn_\":\"575\"},{\"1\":\"1\",\"2\":\"119.0000\",\"3\":\"44.00000\",\"4\":\"47.00000\",\"5\":\"63.0000\",\"6\":\"35.50000\",\"7\":\"0.280\",\"8\":\"25\",\"9\":\"0\",\"_rn_\":\"576\"},{\"1\":\"6\",\"2\":\"108.0000\",\"3\":\"44.00000\",\"4\":\"20.00000\",\"5\":\"130.0000\",\"6\":\"24.00000\",\"7\":\"0.813\",\"8\":\"35\",\"9\":\"0\",\"_rn_\":\"577\"},{\"1\":\"2\",\"2\":\"118.0000\",\"3\":\"80.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"42.90000\",\"7\":\"0.693\",\"8\":\"21\",\"9\":\"1\",\"_rn_\":\"578\"},{\"1\":\"10\",\"2\":\"133.0000\",\"3\":\"68.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"27.00000\",\"7\":\"0.245\",\"8\":\"36\",\"9\":\"0\",\"_rn_\":\"579\"},{\"1\":\"2\",\"2\":\"197.0000\",\"3\":\"70.00000\",\"4\":\"99.00000\",\"5\":\"155.5482\",\"6\":\"34.70000\",\"7\":\"0.575\",\"8\":\"62\",\"9\":\"1\",\"_rn_\":\"580\"},{\"1\":\"0\",\"2\":\"151.0000\",\"3\":\"90.00000\",\"4\":\"46.00000\",\"5\":\"155.5482\",\"6\":\"42.10000\",\"7\":\"0.371\",\"8\":\"21\",\"9\":\"1\",\"_rn_\":\"581\"},{\"1\":\"6\",\"2\":\"109.0000\",\"3\":\"60.00000\",\"4\":\"27.00000\",\"5\":\"155.5482\",\"6\":\"25.00000\",\"7\":\"0.206\",\"8\":\"27\",\"9\":\"0\",\"_rn_\":\"582\"},{\"1\":\"12\",\"2\":\"121.0000\",\"3\":\"78.00000\",\"4\":\"17.00000\",\"5\":\"155.5482\",\"6\":\"26.50000\",\"7\":\"0.259\",\"8\":\"62\",\"9\":\"0\",\"_rn_\":\"583\"},{\"1\":\"8\",\"2\":\"100.0000\",\"3\":\"76.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"38.70000\",\"7\":\"0.190\",\"8\":\"42\",\"9\":\"0\",\"_rn_\":\"584\"},{\"1\":\"8\",\"2\":\"124.0000\",\"3\":\"76.00000\",\"4\":\"24.00000\",\"5\":\"600.0000\",\"6\":\"28.70000\",\"7\":\"0.687\",\"8\":\"52\",\"9\":\"1\",\"_rn_\":\"585\"},{\"1\":\"1\",\"2\":\"93.0000\",\"3\":\"56.00000\",\"4\":\"11.00000\",\"5\":\"155.5482\",\"6\":\"22.50000\",\"7\":\"0.417\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"586\"},{\"1\":\"8\",\"2\":\"143.0000\",\"3\":\"66.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"34.90000\",\"7\":\"0.129\",\"8\":\"41\",\"9\":\"1\",\"_rn_\":\"587\"},{\"1\":\"6\",\"2\":\"103.0000\",\"3\":\"66.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"24.30000\",\"7\":\"0.249\",\"8\":\"29\",\"9\":\"0\",\"_rn_\":\"588\"},{\"1\":\"3\",\"2\":\"176.0000\",\"3\":\"86.00000\",\"4\":\"27.00000\",\"5\":\"156.0000\",\"6\":\"33.30000\",\"7\":\"1.154\",\"8\":\"52\",\"9\":\"1\",\"_rn_\":\"589\"},{\"1\":\"0\",\"2\":\"73.0000\",\"3\":\"72.40518\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"21.10000\",\"7\":\"0.342\",\"8\":\"25\",\"9\":\"0\",\"_rn_\":\"590\"},{\"1\":\"11\",\"2\":\"111.0000\",\"3\":\"84.00000\",\"4\":\"40.00000\",\"5\":\"155.5482\",\"6\":\"46.80000\",\"7\":\"0.925\",\"8\":\"45\",\"9\":\"1\",\"_rn_\":\"591\"},{\"1\":\"2\",\"2\":\"112.0000\",\"3\":\"78.00000\",\"4\":\"50.00000\",\"5\":\"140.0000\",\"6\":\"39.40000\",\"7\":\"0.175\",\"8\":\"24\",\"9\":\"0\",\"_rn_\":\"592\"},{\"1\":\"3\",\"2\":\"132.0000\",\"3\":\"80.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"34.40000\",\"7\":\"0.402\",\"8\":\"44\",\"9\":\"1\",\"_rn_\":\"593\"},{\"1\":\"2\",\"2\":\"82.0000\",\"3\":\"52.00000\",\"4\":\"22.00000\",\"5\":\"115.0000\",\"6\":\"28.50000\",\"7\":\"1.699\",\"8\":\"25\",\"9\":\"0\",\"_rn_\":\"594\"},{\"1\":\"6\",\"2\":\"123.0000\",\"3\":\"72.00000\",\"4\":\"45.00000\",\"5\":\"230.0000\",\"6\":\"33.60000\",\"7\":\"0.733\",\"8\":\"34\",\"9\":\"0\",\"_rn_\":\"595\"},{\"1\":\"0\",\"2\":\"188.0000\",\"3\":\"82.00000\",\"4\":\"14.00000\",\"5\":\"185.0000\",\"6\":\"32.00000\",\"7\":\"0.682\",\"8\":\"22\",\"9\":\"1\",\"_rn_\":\"596\"},{\"1\":\"0\",\"2\":\"67.0000\",\"3\":\"76.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"45.30000\",\"7\":\"0.194\",\"8\":\"46\",\"9\":\"0\",\"_rn_\":\"597\"},{\"1\":\"1\",\"2\":\"89.0000\",\"3\":\"24.00000\",\"4\":\"19.00000\",\"5\":\"25.0000\",\"6\":\"27.80000\",\"7\":\"0.559\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"598\"},{\"1\":\"1\",\"2\":\"173.0000\",\"3\":\"74.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"36.80000\",\"7\":\"0.088\",\"8\":\"38\",\"9\":\"1\",\"_rn_\":\"599\"},{\"1\":\"1\",\"2\":\"109.0000\",\"3\":\"38.00000\",\"4\":\"18.00000\",\"5\":\"120.0000\",\"6\":\"23.10000\",\"7\":\"0.407\",\"8\":\"26\",\"9\":\"0\",\"_rn_\":\"600\"},{\"1\":\"1\",\"2\":\"108.0000\",\"3\":\"88.00000\",\"4\":\"19.00000\",\"5\":\"155.5482\",\"6\":\"27.10000\",\"7\":\"0.400\",\"8\":\"24\",\"9\":\"0\",\"_rn_\":\"601\"},{\"1\":\"6\",\"2\":\"96.0000\",\"3\":\"72.40518\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"23.70000\",\"7\":\"0.190\",\"8\":\"28\",\"9\":\"0\",\"_rn_\":\"602\"},{\"1\":\"1\",\"2\":\"124.0000\",\"3\":\"74.00000\",\"4\":\"36.00000\",\"5\":\"155.5482\",\"6\":\"27.80000\",\"7\":\"0.100\",\"8\":\"30\",\"9\":\"0\",\"_rn_\":\"603\"},{\"1\":\"7\",\"2\":\"150.0000\",\"3\":\"78.00000\",\"4\":\"29.00000\",\"5\":\"126.0000\",\"6\":\"35.20000\",\"7\":\"0.692\",\"8\":\"54\",\"9\":\"1\",\"_rn_\":\"604\"},{\"1\":\"4\",\"2\":\"183.0000\",\"3\":\"72.40518\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"28.40000\",\"7\":\"0.212\",\"8\":\"36\",\"9\":\"1\",\"_rn_\":\"605\"},{\"1\":\"1\",\"2\":\"124.0000\",\"3\":\"60.00000\",\"4\":\"32.00000\",\"5\":\"155.5482\",\"6\":\"35.80000\",\"7\":\"0.514\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"606\"},{\"1\":\"1\",\"2\":\"181.0000\",\"3\":\"78.00000\",\"4\":\"42.00000\",\"5\":\"293.0000\",\"6\":\"40.00000\",\"7\":\"1.258\",\"8\":\"22\",\"9\":\"1\",\"_rn_\":\"607\"},{\"1\":\"1\",\"2\":\"92.0000\",\"3\":\"62.00000\",\"4\":\"25.00000\",\"5\":\"41.0000\",\"6\":\"19.50000\",\"7\":\"0.482\",\"8\":\"25\",\"9\":\"0\",\"_rn_\":\"608\"},{\"1\":\"0\",\"2\":\"152.0000\",\"3\":\"82.00000\",\"4\":\"39.00000\",\"5\":\"272.0000\",\"6\":\"41.50000\",\"7\":\"0.270\",\"8\":\"27\",\"9\":\"0\",\"_rn_\":\"609\"},{\"1\":\"1\",\"2\":\"111.0000\",\"3\":\"62.00000\",\"4\":\"13.00000\",\"5\":\"182.0000\",\"6\":\"24.00000\",\"7\":\"0.138\",\"8\":\"23\",\"9\":\"0\",\"_rn_\":\"610\"},{\"1\":\"3\",\"2\":\"106.0000\",\"3\":\"54.00000\",\"4\":\"21.00000\",\"5\":\"158.0000\",\"6\":\"30.90000\",\"7\":\"0.292\",\"8\":\"24\",\"9\":\"0\",\"_rn_\":\"611\"},{\"1\":\"3\",\"2\":\"174.0000\",\"3\":\"58.00000\",\"4\":\"22.00000\",\"5\":\"194.0000\",\"6\":\"32.90000\",\"7\":\"0.593\",\"8\":\"36\",\"9\":\"1\",\"_rn_\":\"612\"},{\"1\":\"7\",\"2\":\"168.0000\",\"3\":\"88.00000\",\"4\":\"42.00000\",\"5\":\"321.0000\",\"6\":\"38.20000\",\"7\":\"0.787\",\"8\":\"40\",\"9\":\"1\",\"_rn_\":\"613\"},{\"1\":\"6\",\"2\":\"105.0000\",\"3\":\"80.00000\",\"4\":\"28.00000\",\"5\":\"155.5482\",\"6\":\"32.50000\",\"7\":\"0.878\",\"8\":\"26\",\"9\":\"0\",\"_rn_\":\"614\"},{\"1\":\"11\",\"2\":\"138.0000\",\"3\":\"74.00000\",\"4\":\"26.00000\",\"5\":\"144.0000\",\"6\":\"36.10000\",\"7\":\"0.557\",\"8\":\"50\",\"9\":\"1\",\"_rn_\":\"615\"},{\"1\":\"3\",\"2\":\"106.0000\",\"3\":\"72.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"25.80000\",\"7\":\"0.207\",\"8\":\"27\",\"9\":\"0\",\"_rn_\":\"616\"},{\"1\":\"6\",\"2\":\"117.0000\",\"3\":\"96.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"28.70000\",\"7\":\"0.157\",\"8\":\"30\",\"9\":\"0\",\"_rn_\":\"617\"},{\"1\":\"2\",\"2\":\"68.0000\",\"3\":\"62.00000\",\"4\":\"13.00000\",\"5\":\"15.0000\",\"6\":\"20.10000\",\"7\":\"0.257\",\"8\":\"23\",\"9\":\"0\",\"_rn_\":\"618\"},{\"1\":\"9\",\"2\":\"112.0000\",\"3\":\"82.00000\",\"4\":\"24.00000\",\"5\":\"155.5482\",\"6\":\"28.20000\",\"7\":\"1.282\",\"8\":\"50\",\"9\":\"1\",\"_rn_\":\"619\"},{\"1\":\"0\",\"2\":\"119.0000\",\"3\":\"72.40518\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"32.40000\",\"7\":\"0.141\",\"8\":\"24\",\"9\":\"1\",\"_rn_\":\"620\"},{\"1\":\"2\",\"2\":\"112.0000\",\"3\":\"86.00000\",\"4\":\"42.00000\",\"5\":\"160.0000\",\"6\":\"38.40000\",\"7\":\"0.246\",\"8\":\"28\",\"9\":\"0\",\"_rn_\":\"621\"},{\"1\":\"2\",\"2\":\"92.0000\",\"3\":\"76.00000\",\"4\":\"20.00000\",\"5\":\"155.5482\",\"6\":\"24.20000\",\"7\":\"1.698\",\"8\":\"28\",\"9\":\"0\",\"_rn_\":\"622\"},{\"1\":\"6\",\"2\":\"183.0000\",\"3\":\"94.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"40.80000\",\"7\":\"1.461\",\"8\":\"45\",\"9\":\"0\",\"_rn_\":\"623\"},{\"1\":\"0\",\"2\":\"94.0000\",\"3\":\"70.00000\",\"4\":\"27.00000\",\"5\":\"115.0000\",\"6\":\"43.50000\",\"7\":\"0.347\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"624\"},{\"1\":\"2\",\"2\":\"108.0000\",\"3\":\"64.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"30.80000\",\"7\":\"0.158\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"625\"},{\"1\":\"4\",\"2\":\"90.0000\",\"3\":\"88.00000\",\"4\":\"47.00000\",\"5\":\"54.0000\",\"6\":\"37.70000\",\"7\":\"0.362\",\"8\":\"29\",\"9\":\"0\",\"_rn_\":\"626\"},{\"1\":\"0\",\"2\":\"125.0000\",\"3\":\"68.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"24.70000\",\"7\":\"0.206\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"627\"},{\"1\":\"0\",\"2\":\"132.0000\",\"3\":\"78.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"32.40000\",\"7\":\"0.393\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"628\"},{\"1\":\"5\",\"2\":\"128.0000\",\"3\":\"80.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"34.60000\",\"7\":\"0.144\",\"8\":\"45\",\"9\":\"0\",\"_rn_\":\"629\"},{\"1\":\"4\",\"2\":\"94.0000\",\"3\":\"65.00000\",\"4\":\"22.00000\",\"5\":\"155.5482\",\"6\":\"24.70000\",\"7\":\"0.148\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"630\"},{\"1\":\"7\",\"2\":\"114.0000\",\"3\":\"64.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"27.40000\",\"7\":\"0.732\",\"8\":\"34\",\"9\":\"1\",\"_rn_\":\"631\"},{\"1\":\"0\",\"2\":\"102.0000\",\"3\":\"78.00000\",\"4\":\"40.00000\",\"5\":\"90.0000\",\"6\":\"34.50000\",\"7\":\"0.238\",\"8\":\"24\",\"9\":\"0\",\"_rn_\":\"632\"},{\"1\":\"2\",\"2\":\"111.0000\",\"3\":\"60.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"26.20000\",\"7\":\"0.343\",\"8\":\"23\",\"9\":\"0\",\"_rn_\":\"633\"},{\"1\":\"1\",\"2\":\"128.0000\",\"3\":\"82.00000\",\"4\":\"17.00000\",\"5\":\"183.0000\",\"6\":\"27.50000\",\"7\":\"0.115\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"634\"},{\"1\":\"10\",\"2\":\"92.0000\",\"3\":\"62.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"25.90000\",\"7\":\"0.167\",\"8\":\"31\",\"9\":\"0\",\"_rn_\":\"635\"},{\"1\":\"13\",\"2\":\"104.0000\",\"3\":\"72.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"31.20000\",\"7\":\"0.465\",\"8\":\"38\",\"9\":\"1\",\"_rn_\":\"636\"},{\"1\":\"5\",\"2\":\"104.0000\",\"3\":\"74.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"28.80000\",\"7\":\"0.153\",\"8\":\"48\",\"9\":\"0\",\"_rn_\":\"637\"},{\"1\":\"2\",\"2\":\"94.0000\",\"3\":\"76.00000\",\"4\":\"18.00000\",\"5\":\"66.0000\",\"6\":\"31.60000\",\"7\":\"0.649\",\"8\":\"23\",\"9\":\"0\",\"_rn_\":\"638\"},{\"1\":\"7\",\"2\":\"97.0000\",\"3\":\"76.00000\",\"4\":\"32.00000\",\"5\":\"91.0000\",\"6\":\"40.90000\",\"7\":\"0.871\",\"8\":\"32\",\"9\":\"1\",\"_rn_\":\"639\"},{\"1\":\"1\",\"2\":\"100.0000\",\"3\":\"74.00000\",\"4\":\"12.00000\",\"5\":\"46.0000\",\"6\":\"19.50000\",\"7\":\"0.149\",\"8\":\"28\",\"9\":\"0\",\"_rn_\":\"640\"},{\"1\":\"0\",\"2\":\"102.0000\",\"3\":\"86.00000\",\"4\":\"17.00000\",\"5\":\"105.0000\",\"6\":\"29.30000\",\"7\":\"0.695\",\"8\":\"27\",\"9\":\"0\",\"_rn_\":\"641\"},{\"1\":\"4\",\"2\":\"128.0000\",\"3\":\"70.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"34.30000\",\"7\":\"0.303\",\"8\":\"24\",\"9\":\"0\",\"_rn_\":\"642\"},{\"1\":\"6\",\"2\":\"147.0000\",\"3\":\"80.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"29.50000\",\"7\":\"0.178\",\"8\":\"50\",\"9\":\"1\",\"_rn_\":\"643\"},{\"1\":\"4\",\"2\":\"90.0000\",\"3\":\"72.40518\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"28.00000\",\"7\":\"0.610\",\"8\":\"31\",\"9\":\"0\",\"_rn_\":\"644\"},{\"1\":\"3\",\"2\":\"103.0000\",\"3\":\"72.00000\",\"4\":\"30.00000\",\"5\":\"152.0000\",\"6\":\"27.60000\",\"7\":\"0.730\",\"8\":\"27\",\"9\":\"0\",\"_rn_\":\"645\"},{\"1\":\"2\",\"2\":\"157.0000\",\"3\":\"74.00000\",\"4\":\"35.00000\",\"5\":\"440.0000\",\"6\":\"39.40000\",\"7\":\"0.134\",\"8\":\"30\",\"9\":\"0\",\"_rn_\":\"646\"},{\"1\":\"1\",\"2\":\"167.0000\",\"3\":\"74.00000\",\"4\":\"17.00000\",\"5\":\"144.0000\",\"6\":\"23.40000\",\"7\":\"0.447\",\"8\":\"33\",\"9\":\"1\",\"_rn_\":\"647\"},{\"1\":\"0\",\"2\":\"179.0000\",\"3\":\"50.00000\",\"4\":\"36.00000\",\"5\":\"159.0000\",\"6\":\"37.80000\",\"7\":\"0.455\",\"8\":\"22\",\"9\":\"1\",\"_rn_\":\"648\"},{\"1\":\"11\",\"2\":\"136.0000\",\"3\":\"84.00000\",\"4\":\"35.00000\",\"5\":\"130.0000\",\"6\":\"28.30000\",\"7\":\"0.260\",\"8\":\"42\",\"9\":\"1\",\"_rn_\":\"649\"},{\"1\":\"0\",\"2\":\"107.0000\",\"3\":\"60.00000\",\"4\":\"25.00000\",\"5\":\"155.5482\",\"6\":\"26.40000\",\"7\":\"0.133\",\"8\":\"23\",\"9\":\"0\",\"_rn_\":\"650\"},{\"1\":\"1\",\"2\":\"91.0000\",\"3\":\"54.00000\",\"4\":\"25.00000\",\"5\":\"100.0000\",\"6\":\"25.20000\",\"7\":\"0.234\",\"8\":\"23\",\"9\":\"0\",\"_rn_\":\"651\"},{\"1\":\"1\",\"2\":\"117.0000\",\"3\":\"60.00000\",\"4\":\"23.00000\",\"5\":\"106.0000\",\"6\":\"33.80000\",\"7\":\"0.466\",\"8\":\"27\",\"9\":\"0\",\"_rn_\":\"652\"},{\"1\":\"5\",\"2\":\"123.0000\",\"3\":\"74.00000\",\"4\":\"40.00000\",\"5\":\"77.0000\",\"6\":\"34.10000\",\"7\":\"0.269\",\"8\":\"28\",\"9\":\"0\",\"_rn_\":\"653\"},{\"1\":\"2\",\"2\":\"120.0000\",\"3\":\"54.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"26.80000\",\"7\":\"0.455\",\"8\":\"27\",\"9\":\"0\",\"_rn_\":\"654\"},{\"1\":\"1\",\"2\":\"106.0000\",\"3\":\"70.00000\",\"4\":\"28.00000\",\"5\":\"135.0000\",\"6\":\"34.20000\",\"7\":\"0.142\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"655\"},{\"1\":\"2\",\"2\":\"155.0000\",\"3\":\"52.00000\",\"4\":\"27.00000\",\"5\":\"540.0000\",\"6\":\"38.70000\",\"7\":\"0.240\",\"8\":\"25\",\"9\":\"1\",\"_rn_\":\"656\"},{\"1\":\"2\",\"2\":\"101.0000\",\"3\":\"58.00000\",\"4\":\"35.00000\",\"5\":\"90.0000\",\"6\":\"21.80000\",\"7\":\"0.155\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"657\"},{\"1\":\"1\",\"2\":\"120.0000\",\"3\":\"80.00000\",\"4\":\"48.00000\",\"5\":\"200.0000\",\"6\":\"38.90000\",\"7\":\"1.162\",\"8\":\"41\",\"9\":\"0\",\"_rn_\":\"658\"},{\"1\":\"11\",\"2\":\"127.0000\",\"3\":\"106.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"39.00000\",\"7\":\"0.190\",\"8\":\"51\",\"9\":\"0\",\"_rn_\":\"659\"},{\"1\":\"3\",\"2\":\"80.0000\",\"3\":\"82.00000\",\"4\":\"31.00000\",\"5\":\"70.0000\",\"6\":\"34.20000\",\"7\":\"1.292\",\"8\":\"27\",\"9\":\"1\",\"_rn_\":\"660\"},{\"1\":\"10\",\"2\":\"162.0000\",\"3\":\"84.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"27.70000\",\"7\":\"0.182\",\"8\":\"54\",\"9\":\"0\",\"_rn_\":\"661\"},{\"1\":\"1\",\"2\":\"199.0000\",\"3\":\"76.00000\",\"4\":\"43.00000\",\"5\":\"155.5482\",\"6\":\"42.90000\",\"7\":\"1.394\",\"8\":\"22\",\"9\":\"1\",\"_rn_\":\"662\"},{\"1\":\"8\",\"2\":\"167.0000\",\"3\":\"106.00000\",\"4\":\"46.00000\",\"5\":\"231.0000\",\"6\":\"37.60000\",\"7\":\"0.165\",\"8\":\"43\",\"9\":\"1\",\"_rn_\":\"663\"},{\"1\":\"9\",\"2\":\"145.0000\",\"3\":\"80.00000\",\"4\":\"46.00000\",\"5\":\"130.0000\",\"6\":\"37.90000\",\"7\":\"0.637\",\"8\":\"40\",\"9\":\"1\",\"_rn_\":\"664\"},{\"1\":\"6\",\"2\":\"115.0000\",\"3\":\"60.00000\",\"4\":\"39.00000\",\"5\":\"155.5482\",\"6\":\"33.70000\",\"7\":\"0.245\",\"8\":\"40\",\"9\":\"1\",\"_rn_\":\"665\"},{\"1\":\"1\",\"2\":\"112.0000\",\"3\":\"80.00000\",\"4\":\"45.00000\",\"5\":\"132.0000\",\"6\":\"34.80000\",\"7\":\"0.217\",\"8\":\"24\",\"9\":\"0\",\"_rn_\":\"666\"},{\"1\":\"4\",\"2\":\"145.0000\",\"3\":\"82.00000\",\"4\":\"18.00000\",\"5\":\"155.5482\",\"6\":\"32.50000\",\"7\":\"0.235\",\"8\":\"70\",\"9\":\"1\",\"_rn_\":\"667\"},{\"1\":\"10\",\"2\":\"111.0000\",\"3\":\"70.00000\",\"4\":\"27.00000\",\"5\":\"155.5482\",\"6\":\"27.50000\",\"7\":\"0.141\",\"8\":\"40\",\"9\":\"1\",\"_rn_\":\"668\"},{\"1\":\"6\",\"2\":\"98.0000\",\"3\":\"58.00000\",\"4\":\"33.00000\",\"5\":\"190.0000\",\"6\":\"34.00000\",\"7\":\"0.430\",\"8\":\"43\",\"9\":\"0\",\"_rn_\":\"669\"},{\"1\":\"9\",\"2\":\"154.0000\",\"3\":\"78.00000\",\"4\":\"30.00000\",\"5\":\"100.0000\",\"6\":\"30.90000\",\"7\":\"0.164\",\"8\":\"45\",\"9\":\"0\",\"_rn_\":\"670\"},{\"1\":\"6\",\"2\":\"165.0000\",\"3\":\"68.00000\",\"4\":\"26.00000\",\"5\":\"168.0000\",\"6\":\"33.60000\",\"7\":\"0.631\",\"8\":\"49\",\"9\":\"0\",\"_rn_\":\"671\"},{\"1\":\"1\",\"2\":\"99.0000\",\"3\":\"58.00000\",\"4\":\"10.00000\",\"5\":\"155.5482\",\"6\":\"25.40000\",\"7\":\"0.551\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"672\"},{\"1\":\"10\",\"2\":\"68.0000\",\"3\":\"106.00000\",\"4\":\"23.00000\",\"5\":\"49.0000\",\"6\":\"35.50000\",\"7\":\"0.285\",\"8\":\"47\",\"9\":\"0\",\"_rn_\":\"673\"},{\"1\":\"3\",\"2\":\"123.0000\",\"3\":\"100.00000\",\"4\":\"35.00000\",\"5\":\"240.0000\",\"6\":\"57.30000\",\"7\":\"0.880\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"674\"},{\"1\":\"8\",\"2\":\"91.0000\",\"3\":\"82.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"35.60000\",\"7\":\"0.587\",\"8\":\"68\",\"9\":\"0\",\"_rn_\":\"675\"},{\"1\":\"6\",\"2\":\"195.0000\",\"3\":\"70.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"30.90000\",\"7\":\"0.328\",\"8\":\"31\",\"9\":\"1\",\"_rn_\":\"676\"},{\"1\":\"9\",\"2\":\"156.0000\",\"3\":\"86.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"24.80000\",\"7\":\"0.230\",\"8\":\"53\",\"9\":\"1\",\"_rn_\":\"677\"},{\"1\":\"0\",\"2\":\"93.0000\",\"3\":\"60.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"35.30000\",\"7\":\"0.263\",\"8\":\"25\",\"9\":\"0\",\"_rn_\":\"678\"},{\"1\":\"3\",\"2\":\"121.0000\",\"3\":\"52.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"36.00000\",\"7\":\"0.127\",\"8\":\"25\",\"9\":\"1\",\"_rn_\":\"679\"},{\"1\":\"2\",\"2\":\"101.0000\",\"3\":\"58.00000\",\"4\":\"17.00000\",\"5\":\"265.0000\",\"6\":\"24.20000\",\"7\":\"0.614\",\"8\":\"23\",\"9\":\"0\",\"_rn_\":\"680\"},{\"1\":\"2\",\"2\":\"56.0000\",\"3\":\"56.00000\",\"4\":\"28.00000\",\"5\":\"45.0000\",\"6\":\"24.20000\",\"7\":\"0.332\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"681\"},{\"1\":\"0\",\"2\":\"162.0000\",\"3\":\"76.00000\",\"4\":\"36.00000\",\"5\":\"155.5482\",\"6\":\"49.60000\",\"7\":\"0.364\",\"8\":\"26\",\"9\":\"1\",\"_rn_\":\"682\"},{\"1\":\"0\",\"2\":\"95.0000\",\"3\":\"64.00000\",\"4\":\"39.00000\",\"5\":\"105.0000\",\"6\":\"44.60000\",\"7\":\"0.366\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"683\"},{\"1\":\"4\",\"2\":\"125.0000\",\"3\":\"80.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"32.30000\",\"7\":\"0.536\",\"8\":\"27\",\"9\":\"1\",\"_rn_\":\"684\"},{\"1\":\"5\",\"2\":\"136.0000\",\"3\":\"82.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"32.45746\",\"7\":\"0.640\",\"8\":\"69\",\"9\":\"0\",\"_rn_\":\"685\"},{\"1\":\"2\",\"2\":\"129.0000\",\"3\":\"74.00000\",\"4\":\"26.00000\",\"5\":\"205.0000\",\"6\":\"33.20000\",\"7\":\"0.591\",\"8\":\"25\",\"9\":\"0\",\"_rn_\":\"686\"},{\"1\":\"3\",\"2\":\"130.0000\",\"3\":\"64.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"23.10000\",\"7\":\"0.314\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"687\"},{\"1\":\"1\",\"2\":\"107.0000\",\"3\":\"50.00000\",\"4\":\"19.00000\",\"5\":\"155.5482\",\"6\":\"28.30000\",\"7\":\"0.181\",\"8\":\"29\",\"9\":\"0\",\"_rn_\":\"688\"},{\"1\":\"1\",\"2\":\"140.0000\",\"3\":\"74.00000\",\"4\":\"26.00000\",\"5\":\"180.0000\",\"6\":\"24.10000\",\"7\":\"0.828\",\"8\":\"23\",\"9\":\"0\",\"_rn_\":\"689\"},{\"1\":\"1\",\"2\":\"144.0000\",\"3\":\"82.00000\",\"4\":\"46.00000\",\"5\":\"180.0000\",\"6\":\"46.10000\",\"7\":\"0.335\",\"8\":\"46\",\"9\":\"1\",\"_rn_\":\"690\"},{\"1\":\"8\",\"2\":\"107.0000\",\"3\":\"80.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"24.60000\",\"7\":\"0.856\",\"8\":\"34\",\"9\":\"0\",\"_rn_\":\"691\"},{\"1\":\"13\",\"2\":\"158.0000\",\"3\":\"114.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"42.30000\",\"7\":\"0.257\",\"8\":\"44\",\"9\":\"1\",\"_rn_\":\"692\"},{\"1\":\"2\",\"2\":\"121.0000\",\"3\":\"70.00000\",\"4\":\"32.00000\",\"5\":\"95.0000\",\"6\":\"39.10000\",\"7\":\"0.886\",\"8\":\"23\",\"9\":\"0\",\"_rn_\":\"693\"},{\"1\":\"7\",\"2\":\"129.0000\",\"3\":\"68.00000\",\"4\":\"49.00000\",\"5\":\"125.0000\",\"6\":\"38.50000\",\"7\":\"0.439\",\"8\":\"43\",\"9\":\"1\",\"_rn_\":\"694\"},{\"1\":\"2\",\"2\":\"90.0000\",\"3\":\"60.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"23.50000\",\"7\":\"0.191\",\"8\":\"25\",\"9\":\"0\",\"_rn_\":\"695\"},{\"1\":\"7\",\"2\":\"142.0000\",\"3\":\"90.00000\",\"4\":\"24.00000\",\"5\":\"480.0000\",\"6\":\"30.40000\",\"7\":\"0.128\",\"8\":\"43\",\"9\":\"1\",\"_rn_\":\"696\"},{\"1\":\"3\",\"2\":\"169.0000\",\"3\":\"74.00000\",\"4\":\"19.00000\",\"5\":\"125.0000\",\"6\":\"29.90000\",\"7\":\"0.268\",\"8\":\"31\",\"9\":\"1\",\"_rn_\":\"697\"},{\"1\":\"0\",\"2\":\"99.0000\",\"3\":\"72.40518\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"25.00000\",\"7\":\"0.253\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"698\"},{\"1\":\"4\",\"2\":\"127.0000\",\"3\":\"88.00000\",\"4\":\"11.00000\",\"5\":\"155.0000\",\"6\":\"34.50000\",\"7\":\"0.598\",\"8\":\"28\",\"9\":\"0\",\"_rn_\":\"699\"},{\"1\":\"4\",\"2\":\"118.0000\",\"3\":\"70.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"44.50000\",\"7\":\"0.904\",\"8\":\"26\",\"9\":\"0\",\"_rn_\":\"700\"},{\"1\":\"2\",\"2\":\"122.0000\",\"3\":\"76.00000\",\"4\":\"27.00000\",\"5\":\"200.0000\",\"6\":\"35.90000\",\"7\":\"0.483\",\"8\":\"26\",\"9\":\"0\",\"_rn_\":\"701\"},{\"1\":\"6\",\"2\":\"125.0000\",\"3\":\"78.00000\",\"4\":\"31.00000\",\"5\":\"155.5482\",\"6\":\"27.60000\",\"7\":\"0.565\",\"8\":\"49\",\"9\":\"1\",\"_rn_\":\"702\"},{\"1\":\"1\",\"2\":\"168.0000\",\"3\":\"88.00000\",\"4\":\"29.00000\",\"5\":\"155.5482\",\"6\":\"35.00000\",\"7\":\"0.905\",\"8\":\"52\",\"9\":\"1\",\"_rn_\":\"703\"},{\"1\":\"2\",\"2\":\"129.0000\",\"3\":\"72.40518\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"38.50000\",\"7\":\"0.304\",\"8\":\"41\",\"9\":\"0\",\"_rn_\":\"704\"},{\"1\":\"4\",\"2\":\"110.0000\",\"3\":\"76.00000\",\"4\":\"20.00000\",\"5\":\"100.0000\",\"6\":\"28.40000\",\"7\":\"0.118\",\"8\":\"27\",\"9\":\"0\",\"_rn_\":\"705\"},{\"1\":\"6\",\"2\":\"80.0000\",\"3\":\"80.00000\",\"4\":\"36.00000\",\"5\":\"155.5482\",\"6\":\"39.80000\",\"7\":\"0.177\",\"8\":\"28\",\"9\":\"0\",\"_rn_\":\"706\"},{\"1\":\"10\",\"2\":\"115.0000\",\"3\":\"72.40518\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"32.45746\",\"7\":\"0.261\",\"8\":\"30\",\"9\":\"1\",\"_rn_\":\"707\"},{\"1\":\"2\",\"2\":\"127.0000\",\"3\":\"46.00000\",\"4\":\"21.00000\",\"5\":\"335.0000\",\"6\":\"34.40000\",\"7\":\"0.176\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"708\"},{\"1\":\"9\",\"2\":\"164.0000\",\"3\":\"78.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"32.80000\",\"7\":\"0.148\",\"8\":\"45\",\"9\":\"1\",\"_rn_\":\"709\"},{\"1\":\"2\",\"2\":\"93.0000\",\"3\":\"64.00000\",\"4\":\"32.00000\",\"5\":\"160.0000\",\"6\":\"38.00000\",\"7\":\"0.674\",\"8\":\"23\",\"9\":\"1\",\"_rn_\":\"710\"},{\"1\":\"3\",\"2\":\"158.0000\",\"3\":\"64.00000\",\"4\":\"13.00000\",\"5\":\"387.0000\",\"6\":\"31.20000\",\"7\":\"0.295\",\"8\":\"24\",\"9\":\"0\",\"_rn_\":\"711\"},{\"1\":\"5\",\"2\":\"126.0000\",\"3\":\"78.00000\",\"4\":\"27.00000\",\"5\":\"22.0000\",\"6\":\"29.60000\",\"7\":\"0.439\",\"8\":\"40\",\"9\":\"0\",\"_rn_\":\"712\"},{\"1\":\"10\",\"2\":\"129.0000\",\"3\":\"62.00000\",\"4\":\"36.00000\",\"5\":\"155.5482\",\"6\":\"41.20000\",\"7\":\"0.441\",\"8\":\"38\",\"9\":\"1\",\"_rn_\":\"713\"},{\"1\":\"0\",\"2\":\"134.0000\",\"3\":\"58.00000\",\"4\":\"20.00000\",\"5\":\"291.0000\",\"6\":\"26.40000\",\"7\":\"0.352\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"714\"},{\"1\":\"3\",\"2\":\"102.0000\",\"3\":\"74.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"29.50000\",\"7\":\"0.121\",\"8\":\"32\",\"9\":\"0\",\"_rn_\":\"715\"},{\"1\":\"7\",\"2\":\"187.0000\",\"3\":\"50.00000\",\"4\":\"33.00000\",\"5\":\"392.0000\",\"6\":\"33.90000\",\"7\":\"0.826\",\"8\":\"34\",\"9\":\"1\",\"_rn_\":\"716\"},{\"1\":\"3\",\"2\":\"173.0000\",\"3\":\"78.00000\",\"4\":\"39.00000\",\"5\":\"185.0000\",\"6\":\"33.80000\",\"7\":\"0.970\",\"8\":\"31\",\"9\":\"1\",\"_rn_\":\"717\"},{\"1\":\"10\",\"2\":\"94.0000\",\"3\":\"72.00000\",\"4\":\"18.00000\",\"5\":\"155.5482\",\"6\":\"23.10000\",\"7\":\"0.595\",\"8\":\"56\",\"9\":\"0\",\"_rn_\":\"718\"},{\"1\":\"1\",\"2\":\"108.0000\",\"3\":\"60.00000\",\"4\":\"46.00000\",\"5\":\"178.0000\",\"6\":\"35.50000\",\"7\":\"0.415\",\"8\":\"24\",\"9\":\"0\",\"_rn_\":\"719\"},{\"1\":\"5\",\"2\":\"97.0000\",\"3\":\"76.00000\",\"4\":\"27.00000\",\"5\":\"155.5482\",\"6\":\"35.60000\",\"7\":\"0.378\",\"8\":\"52\",\"9\":\"1\",\"_rn_\":\"720\"},{\"1\":\"4\",\"2\":\"83.0000\",\"3\":\"86.00000\",\"4\":\"19.00000\",\"5\":\"155.5482\",\"6\":\"29.30000\",\"7\":\"0.317\",\"8\":\"34\",\"9\":\"0\",\"_rn_\":\"721\"},{\"1\":\"1\",\"2\":\"114.0000\",\"3\":\"66.00000\",\"4\":\"36.00000\",\"5\":\"200.0000\",\"6\":\"38.10000\",\"7\":\"0.289\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"722\"},{\"1\":\"1\",\"2\":\"149.0000\",\"3\":\"68.00000\",\"4\":\"29.00000\",\"5\":\"127.0000\",\"6\":\"29.30000\",\"7\":\"0.349\",\"8\":\"42\",\"9\":\"1\",\"_rn_\":\"723\"},{\"1\":\"5\",\"2\":\"117.0000\",\"3\":\"86.00000\",\"4\":\"30.00000\",\"5\":\"105.0000\",\"6\":\"39.10000\",\"7\":\"0.251\",\"8\":\"42\",\"9\":\"0\",\"_rn_\":\"724\"},{\"1\":\"1\",\"2\":\"111.0000\",\"3\":\"94.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"32.80000\",\"7\":\"0.265\",\"8\":\"45\",\"9\":\"0\",\"_rn_\":\"725\"},{\"1\":\"4\",\"2\":\"112.0000\",\"3\":\"78.00000\",\"4\":\"40.00000\",\"5\":\"155.5482\",\"6\":\"39.40000\",\"7\":\"0.236\",\"8\":\"38\",\"9\":\"0\",\"_rn_\":\"726\"},{\"1\":\"1\",\"2\":\"116.0000\",\"3\":\"78.00000\",\"4\":\"29.00000\",\"5\":\"180.0000\",\"6\":\"36.10000\",\"7\":\"0.496\",\"8\":\"25\",\"9\":\"0\",\"_rn_\":\"727\"},{\"1\":\"0\",\"2\":\"141.0000\",\"3\":\"84.00000\",\"4\":\"26.00000\",\"5\":\"155.5482\",\"6\":\"32.40000\",\"7\":\"0.433\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"728\"},{\"1\":\"2\",\"2\":\"175.0000\",\"3\":\"88.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"22.90000\",\"7\":\"0.326\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"729\"},{\"1\":\"2\",\"2\":\"92.0000\",\"3\":\"52.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"30.10000\",\"7\":\"0.141\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"730\"},{\"1\":\"3\",\"2\":\"130.0000\",\"3\":\"78.00000\",\"4\":\"23.00000\",\"5\":\"79.0000\",\"6\":\"28.40000\",\"7\":\"0.323\",\"8\":\"34\",\"9\":\"1\",\"_rn_\":\"731\"},{\"1\":\"8\",\"2\":\"120.0000\",\"3\":\"86.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"28.40000\",\"7\":\"0.259\",\"8\":\"22\",\"9\":\"1\",\"_rn_\":\"732\"},{\"1\":\"2\",\"2\":\"174.0000\",\"3\":\"88.00000\",\"4\":\"37.00000\",\"5\":\"120.0000\",\"6\":\"44.50000\",\"7\":\"0.646\",\"8\":\"24\",\"9\":\"1\",\"_rn_\":\"733\"},{\"1\":\"2\",\"2\":\"106.0000\",\"3\":\"56.00000\",\"4\":\"27.00000\",\"5\":\"165.0000\",\"6\":\"29.00000\",\"7\":\"0.426\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"734\"},{\"1\":\"2\",\"2\":\"105.0000\",\"3\":\"75.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"23.30000\",\"7\":\"0.560\",\"8\":\"53\",\"9\":\"0\",\"_rn_\":\"735\"},{\"1\":\"4\",\"2\":\"95.0000\",\"3\":\"60.00000\",\"4\":\"32.00000\",\"5\":\"155.5482\",\"6\":\"35.40000\",\"7\":\"0.284\",\"8\":\"28\",\"9\":\"0\",\"_rn_\":\"736\"},{\"1\":\"0\",\"2\":\"126.0000\",\"3\":\"86.00000\",\"4\":\"27.00000\",\"5\":\"120.0000\",\"6\":\"27.40000\",\"7\":\"0.515\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"737\"},{\"1\":\"8\",\"2\":\"65.0000\",\"3\":\"72.00000\",\"4\":\"23.00000\",\"5\":\"155.5482\",\"6\":\"32.00000\",\"7\":\"0.600\",\"8\":\"42\",\"9\":\"0\",\"_rn_\":\"738\"},{\"1\":\"2\",\"2\":\"99.0000\",\"3\":\"60.00000\",\"4\":\"17.00000\",\"5\":\"160.0000\",\"6\":\"36.60000\",\"7\":\"0.453\",\"8\":\"21\",\"9\":\"0\",\"_rn_\":\"739\"},{\"1\":\"1\",\"2\":\"102.0000\",\"3\":\"74.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"39.50000\",\"7\":\"0.293\",\"8\":\"42\",\"9\":\"1\",\"_rn_\":\"740\"},{\"1\":\"11\",\"2\":\"120.0000\",\"3\":\"80.00000\",\"4\":\"37.00000\",\"5\":\"150.0000\",\"6\":\"42.30000\",\"7\":\"0.785\",\"8\":\"48\",\"9\":\"1\",\"_rn_\":\"741\"},{\"1\":\"3\",\"2\":\"102.0000\",\"3\":\"44.00000\",\"4\":\"20.00000\",\"5\":\"94.0000\",\"6\":\"30.80000\",\"7\":\"0.400\",\"8\":\"26\",\"9\":\"0\",\"_rn_\":\"742\"},{\"1\":\"1\",\"2\":\"109.0000\",\"3\":\"58.00000\",\"4\":\"18.00000\",\"5\":\"116.0000\",\"6\":\"28.50000\",\"7\":\"0.219\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"743\"},{\"1\":\"9\",\"2\":\"140.0000\",\"3\":\"94.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"32.70000\",\"7\":\"0.734\",\"8\":\"45\",\"9\":\"1\",\"_rn_\":\"744\"},{\"1\":\"13\",\"2\":\"153.0000\",\"3\":\"88.00000\",\"4\":\"37.00000\",\"5\":\"140.0000\",\"6\":\"40.60000\",\"7\":\"1.174\",\"8\":\"39\",\"9\":\"0\",\"_rn_\":\"745\"},{\"1\":\"12\",\"2\":\"100.0000\",\"3\":\"84.00000\",\"4\":\"33.00000\",\"5\":\"105.0000\",\"6\":\"30.00000\",\"7\":\"0.488\",\"8\":\"46\",\"9\":\"0\",\"_rn_\":\"746\"},{\"1\":\"1\",\"2\":\"147.0000\",\"3\":\"94.00000\",\"4\":\"41.00000\",\"5\":\"155.5482\",\"6\":\"49.30000\",\"7\":\"0.358\",\"8\":\"27\",\"9\":\"1\",\"_rn_\":\"747\"},{\"1\":\"1\",\"2\":\"81.0000\",\"3\":\"74.00000\",\"4\":\"41.00000\",\"5\":\"57.0000\",\"6\":\"46.30000\",\"7\":\"1.096\",\"8\":\"32\",\"9\":\"0\",\"_rn_\":\"748\"},{\"1\":\"3\",\"2\":\"187.0000\",\"3\":\"70.00000\",\"4\":\"22.00000\",\"5\":\"200.0000\",\"6\":\"36.40000\",\"7\":\"0.408\",\"8\":\"36\",\"9\":\"1\",\"_rn_\":\"749\"},{\"1\":\"6\",\"2\":\"162.0000\",\"3\":\"62.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"24.30000\",\"7\":\"0.178\",\"8\":\"50\",\"9\":\"1\",\"_rn_\":\"750\"},{\"1\":\"4\",\"2\":\"136.0000\",\"3\":\"70.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"31.20000\",\"7\":\"1.182\",\"8\":\"22\",\"9\":\"1\",\"_rn_\":\"751\"},{\"1\":\"1\",\"2\":\"121.0000\",\"3\":\"78.00000\",\"4\":\"39.00000\",\"5\":\"74.0000\",\"6\":\"39.00000\",\"7\":\"0.261\",\"8\":\"28\",\"9\":\"0\",\"_rn_\":\"752\"},{\"1\":\"3\",\"2\":\"108.0000\",\"3\":\"62.00000\",\"4\":\"24.00000\",\"5\":\"155.5482\",\"6\":\"26.00000\",\"7\":\"0.223\",\"8\":\"25\",\"9\":\"0\",\"_rn_\":\"753\"},{\"1\":\"0\",\"2\":\"181.0000\",\"3\":\"88.00000\",\"4\":\"44.00000\",\"5\":\"510.0000\",\"6\":\"43.30000\",\"7\":\"0.222\",\"8\":\"26\",\"9\":\"1\",\"_rn_\":\"754\"},{\"1\":\"8\",\"2\":\"154.0000\",\"3\":\"78.00000\",\"4\":\"32.00000\",\"5\":\"155.5482\",\"6\":\"32.40000\",\"7\":\"0.443\",\"8\":\"45\",\"9\":\"1\",\"_rn_\":\"755\"},{\"1\":\"1\",\"2\":\"128.0000\",\"3\":\"88.00000\",\"4\":\"39.00000\",\"5\":\"110.0000\",\"6\":\"36.50000\",\"7\":\"1.057\",\"8\":\"37\",\"9\":\"1\",\"_rn_\":\"756\"},{\"1\":\"7\",\"2\":\"137.0000\",\"3\":\"90.00000\",\"4\":\"41.00000\",\"5\":\"155.5482\",\"6\":\"32.00000\",\"7\":\"0.391\",\"8\":\"39\",\"9\":\"0\",\"_rn_\":\"757\"},{\"1\":\"0\",\"2\":\"123.0000\",\"3\":\"72.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"36.30000\",\"7\":\"0.258\",\"8\":\"52\",\"9\":\"1\",\"_rn_\":\"758\"},{\"1\":\"1\",\"2\":\"106.0000\",\"3\":\"76.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"37.50000\",\"7\":\"0.197\",\"8\":\"26\",\"9\":\"0\",\"_rn_\":\"759\"},{\"1\":\"6\",\"2\":\"190.0000\",\"3\":\"92.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"35.50000\",\"7\":\"0.278\",\"8\":\"66\",\"9\":\"1\",\"_rn_\":\"760\"},{\"1\":\"2\",\"2\":\"88.0000\",\"3\":\"58.00000\",\"4\":\"26.00000\",\"5\":\"16.0000\",\"6\":\"28.40000\",\"7\":\"0.766\",\"8\":\"22\",\"9\":\"0\",\"_rn_\":\"761\"},{\"1\":\"9\",\"2\":\"170.0000\",\"3\":\"74.00000\",\"4\":\"31.00000\",\"5\":\"155.5482\",\"6\":\"44.00000\",\"7\":\"0.403\",\"8\":\"43\",\"9\":\"1\",\"_rn_\":\"762\"},{\"1\":\"9\",\"2\":\"89.0000\",\"3\":\"62.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"22.50000\",\"7\":\"0.142\",\"8\":\"33\",\"9\":\"0\",\"_rn_\":\"763\"},{\"1\":\"10\",\"2\":\"101.0000\",\"3\":\"76.00000\",\"4\":\"48.00000\",\"5\":\"180.0000\",\"6\":\"32.90000\",\"7\":\"0.171\",\"8\":\"63\",\"9\":\"0\",\"_rn_\":\"764\"},{\"1\":\"2\",\"2\":\"122.0000\",\"3\":\"70.00000\",\"4\":\"27.00000\",\"5\":\"155.5482\",\"6\":\"36.80000\",\"7\":\"0.340\",\"8\":\"27\",\"9\":\"0\",\"_rn_\":\"765\"},{\"1\":\"5\",\"2\":\"121.0000\",\"3\":\"72.00000\",\"4\":\"23.00000\",\"5\":\"112.0000\",\"6\":\"26.20000\",\"7\":\"0.245\",\"8\":\"30\",\"9\":\"0\",\"_rn_\":\"766\"},{\"1\":\"1\",\"2\":\"126.0000\",\"3\":\"60.00000\",\"4\":\"29.15342\",\"5\":\"155.5482\",\"6\":\"30.10000\",\"7\":\"0.349\",\"8\":\"47\",\"9\":\"1\",\"_rn_\":\"767\"},{\"1\":\"1\",\"2\":\"93.0000\",\"3\":\"70.00000\",\"4\":\"31.00000\",\"5\":\"155.5482\",\"6\":\"30.40000\",\"7\":\"0.315\",\"8\":\"23\",\"9\":\"0\",\"_rn_\":\"768\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nna_counts <- colSums(is.na(diabetes))\nprint(na_counts)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n             Pregnancies                  Glucose            BloodPressure \n                       0                        0                        0 \n           SkinThickness                  Insulin                      BMI \n                       0                        0                        0 \nDiabetesPedigreeFunction                      Age                  Outcome \n                       0                        0                        0 \n```\n:::\n:::\n\nWe used omit.na() function to remove all rows with NA values in our dataframe. After using this function, we checked for total number of NA values in our dataframe to verify whether there are any NA values still left. We found that the total number of NA values are zero in all columns. By executing these actions, we successfully handled missing values and verified the completeness of our dataframe.\n\n\n# Analysis and Visualization\n\n## 1. What is the distribution of Glucose levels in the dataset? \n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(diabetes, aes(x=Glucose)) +\n  geom_histogram(binwidth=10, fill=\"#69b3a2\", color=\"#e9ecef\", alpha=0.9) +\n  labs(title=\"Distribution of Glucose levels\", x=\"Glucose Level\", y=\"Count\")\n```\n\n::: {.cell-output-display}\n![](final_project_MeghaJoseph_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\nI used a histogram to visualize the distribution of Glucose levels in the dataset, aiming to understand the spread of Glucose values across different ranges. The x-axis represents Glucose levels, while the y-axis represents the frequency or count of individuals within each range of Glucose levels.\n\nBy analyzing the histogram, it is evident that as the Glucose level increases, the count of occurrences also tends to increase. The highest count, around 150, is observed at a Glucose level of 110. However, beyond that point, as the Glucose level continues to rise, the count starts to decrease. This histogram provides valuable insights into the prevalence and distribution of Glucose levels within the dataset, enabling us to identify the most common glucose level.\n\n## 2. Is there a relationship between Age and Glucose levels?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# line graph\ndiabetes %>%\n  group_by(Age) %>%\n  summarise(AvgGlucose = mean(Glucose, na.rm=TRUE)) %>%\n  ggplot(aes(x=Age, y=AvgGlucose)) +\n  geom_line() +\n  labs(title=\"Average Glucose Level by Age\", x=\"Age\", y=\"Average Glucose Level\")\n```\n\n::: {.cell-output-display}\n![](final_project_MeghaJoseph_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\nI used a line graph to explore the relationship between age and average glucose levels in the dataset. The line graph helps us see how glucose levels change as people get older. By looking at the graph, we can see that the line represents the average glucose levels at different ages. If the line goes up as age increases, it means that average glucose levels tend to go up with age. On the other hand, if the line goes down, it means that average glucose levels decrease with age. A flat line means there is no clear relationship between age and glucose levels. I chose a line graph because it shows the continuous relationship between age and average glucose levels as it helps us spot any patterns, trends, or unusual points in how glucose levels change with age.\n\nFrom the line graph, we can see some unusual spikes or sudden changes in the line. These spikes might indicate some special age groups where glucose levels are significantly different from others or as outliners. We can also see that average glucose levels generally increase with age until around age 59, where they reach the highest point. After that, average glucose levels start to decrease. This suggests that there might be some age-related changes or factors contributing to higher glucose levels until age 59, but then the levels start to come down or stabilize as people get older. It could indicate a higher risk of elevated glucose levels or conditions like prediabetes or diabetes in the age group around 59.\n\n## 3. How does the average Blood Pressure vary with the number of Pregnancies? \n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate averages and counts\ndiabetes <- diabetes %>%\n  mutate(PregnanciesGroup = case_when(\n    Pregnancies <= 2 ~ \"0-2\",\n    Pregnancies > 2 & Pregnancies <= 5 ~ \"3-5\",\n    Pregnancies > 5 & Pregnancies <= 8 ~ \"6-8\",\n    Pregnancies > 8 ~ \"9+\"\n  ))\n\ndiabetes_summarised <- diabetes %>%\n  group_by(PregnanciesGroup) %>%\n  summarise(AvgBloodPressure = mean(BloodPressure, na.rm=TRUE), \n            Count = n())\n\n# Define color palette\nmy_colors <- c(\"#F8766D\", \"#7CAE00\", \"#00BFC4\", \"#C77CFF\")\n\n# Plot\nggplot(diabetes_summarised, aes(x=PregnanciesGroup, y=AvgBloodPressure, fill=PregnanciesGroup)) +\n  geom_col(show.legend = FALSE) +\n  scale_fill_manual(values = my_colors) +\n  geom_text(aes(label=Count), vjust=-0.3, size=3.5) +\n  labs(title=\"Average Blood Pressure by Pregnancy Group\", x=\"Pregnancies Group\", y=\"Average Blood Pressure\")\n```\n\n::: {.cell-output-display}\n![](final_project_MeghaJoseph_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\nI classified the data based on number of pregnancies into four different groups. Then based on each group, I compare the pregnancy group vs the Average Blood Pressure. The bar graph was chosen to visualize the relationship between the number of pregnancies and average Blood Pressure because it effectively represents categorical data and allows for easy comparison between different pregnancy groups. Here it represents the Average Blood Pressure in patients based on the number of pregnancies that we had. We specified different colors for every Pregnancy group using a vector which holds unique colors for each group. The count of each pregnancy group is labeled for each bar of the bar graph using the `label` argument.\n\nWe can observe that average Blood Pressure tends to increase as the number of pregnancies increases. The \"9+\" pregnancy group has the highest average Blood Pressure, while the \"0-2\" pregnancy group has the lowest. This suggests a positive association between the number of pregnancies and Blood Pressure levels.\n\nAdditionally, the counts of individuals within each pregnancy group are displayed on top of each bar, indicating the sample size for each group. The higher count in the \"0-2\" pregnancy group suggests that it is more common or represents a larger proportion of the population in the dataset. Conversely, the lower count in the \"9+\" pregnancy group implies that it is less common or represents a smaller proportion of the population.\n\n\n## 4. What is the relationship between BMI and Skin Thickness?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(diabetes, aes(x=BMI, y=SkinThickness)) +\n  geom_point(aes(color=factor(Outcome)), alpha=0.6) +\n  scale_color_discrete(name = \"Outcome\", labels = c(\"No Diabetes\", \"Diabetes\")) +\n  labs(title=\"Relationship between BMI and Skin Thickness\", x=\"BMI\", y=\"Skin Thickness\") +\n  theme_minimal() +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](final_project_MeghaJoseph_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\nHere the scatter plot effectively illustrates the relationship between BMI and Skin Thickness, considering the presence of diabetes. The scatter plot displays individual data points representing BMI and Skin Thickness measurements, with colors indicating diabetic status. By examining the plot, we can observe the following patterns: \n\n1. BMI and Diabetes: As BMI increases, there is a noticeable increase in the prevalence of diabetes. The scatter plot shows a higher concentration of data points labeled as \"Diabetes\" in the higher BMI range (30-50), suggesting that individuals with higher BMIs are more likely to have diabetes.\n\n2. Skin Thickness and Diabetes: Similarly, there is a positive correlation between Skin Thickness and the occurrence of diabetes. The scatter plot reveals a significant increase in the number of diabetes cases as Skin Thickness exceeds 25.\n\nThe choice of a scatter plot is appropriate for this analysis as it allows for the visualization of the relationship between two continuous variables (BMI and Skin Thickness) and incorporates the diabetic status as a categorical variable using color differentiation.\n\n## 5. Relationship between Blood Pressure and Age for those with and without diabetes\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndiabetes %>%\n  group_by(Age, Outcome) %>%\n  summarise(AvgBloodPressure = mean(BloodPressure, na.rm=TRUE)) %>%\n  ggplot(aes(x=Age, y=AvgBloodPressure, color=factor(Outcome), group=Outcome)) +\n  geom_line() +\n  geom_smooth() +\n  labs(title=\"Average Blood Pressure by Age and Outcome\", x=\"Age\", y=\"Average Blood Pressure\") +\n  scale_color_discrete(name = \"Outcome\", labels = c(\"No Diabetes\", \"Diabetes\")) +\n  theme_minimal() +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](final_project_MeghaJoseph_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\nThe following plot compares the average Blood Pressure at different ages for people with and without diabetes. It shows two lines, one for each group, connecting the average Blood Pressure data points.\nWe plot a line using the `geom_smooth()` function which compares Blood Pressure alongside patient Age grouped based on whether the patient tests positive for Diabetes or not. From the graph, we can observe that as there is not much effect of blood pressure on whether a person tests positive for diabetes during the early stages of his/her life. However, after around the age of 50, we notice that people who have tested positive for diabetes generally report higher blood presssure as opposed to people who are not diabetic.\n\n## 6. How does the distribution of BMI differ between those with different numbers of Pregnancies? Violin plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# violin plot\nggplot(diabetes, aes(x=PregnanciesGroup, y=BMI, fill=PregnanciesGroup)) +\n  geom_violin(draw_quantiles = c(0.25, 0.5, 0.75)) +\n  labs(title=\"Distribution of BMI by Pregnancies Group\", x=\"Pregnancies Group\", y=\"BMI\") +\n  scale_fill_discrete(name = \"Pregnancies Group\", labels = c(\"0-2\", \"3-5\", \"6-8\", \"9+\")) +\n  theme_minimal() +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](final_project_MeghaJoseph_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\nThe violin plot shows the distribution of BMI (Body Mass Index) among individuals with different numbers of pregnancies.\n\nThe tails of the violin plot display the minimum and maximum BMI values within each Pregnancy group. This allows us to see the range of BMI values for each group. However, it's important to note that there can be multiple minimum values within each group, which is why we do not have a tail for the minimum end.\n\nThe width of the violin plot represents the density or distribution of data points for each Pregnancy group. A wider section indicates a higher density of BMI values, while a narrower section suggests a lower density. This helps us understand how the BMI values are spread across each group. The center line within each violin represents the median BMI value for each Pregnancy group. It gives us a reference point to understand the central tendency of the BMI distribution within each group.\n\nIn summary, the violin plot is a helpful visualization that shows the range, density, and median BMI values for different pregnancy groups. It allows us to compare the distribution of BMI and identify potential differences among the groups.\n\nFrom the violin plots we get grouped based on each pregnancy group, although we see some very high BMI values in the `0-2` pregnancy group, the violin plots for all the other pregnancy groups are much thicker around the median indicating that there is a much higher count of people with high BMI in the other pregnancy groups even though the `0-2` group has some outliers.\n\n\n## 7. Relationship between Skin Thickness and Insulin levels using scatter plot\n\nThe following point graph compares individual patient's Skin Thickness measurements alongside their measured Insulin levels. We notice that the Insulin readings vary a lot for a certain value of skin thickness. When we use the `geom_smooth()` function, we notice that the overall trend indicates that the Insulin level is very similar for all values of Skin Thickness.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndiabetes %>%\n  ggplot(aes(x = SkinThickness)) +\n  geom_point(aes(y = Insulin)) +\n  geom_smooth(aes(y = Insulin))\n```\n\n::: {.cell-output-display}\n![](final_project_MeghaJoseph_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\nThe scatter plot shows the relationship between Skin Thickness and Insulin levels. The scattered dots represent individual measurements, where each dot represents a person's Skin Thickness and Insulin level. By looking at the dots, we can see how Skin Thickness and Insulin levels vary together.\n\nThe color of the dots represents the Skin Thickness value, ranging from blue to red. This helps us see the range of Skin Thickness values in the data. Looking at the scatter plot, we notice that Insulin levels vary a lot for a certain value of Skin Thickness. However, when we use the `geom_smooth()` function, we see that the overall trend indicates that Insulin levels are very similar for all values of Skin Thickness.\n\nIn summary, the scatter plot shows us how Skin Thickness and Insulin levels are related. We can see the overall trend that Insulin levels remain similar across different Skin Thickness values.\n\n# Conclusion\nIn the exploratory data analysis conducted, the factors influencing diabetes diagnosis in the Pima Indian population were investigated. The analysis focused on variables such as age, pregnancies, BMI, skin thickness, glucose levels, and insulin levels to gain insights into their relationships with the presence or absence of diabetes within this specific population.\n\nBy examining various visualizations, intriguing patterns and trends were identified. The distribution of glucose levels revealed a higher prevalence of higher levels in the dataset, with the highest count observed around 110 mg/dL. Furthermore, the line graph exploring the relationship between age and average glucose levels indicated a rise in average glucose levels with age until approximately 59, after which they started to decrease. These findings suggest the possibility of age-related factors influencing glucose levels among the Pima Indian population.\n\nMoreover, the analysis of average blood pressure by pregnancy group demonstrated that as the number of pregnancies increased, the average blood pressure tended to increase as well. This observation suggests a potential association between pregnancy and blood pressure levels in this population.\n\nOverall, this exploratory data analysis has provided valuable insights into the factors that influence the diagnosis of diabetes in the Pima Indian population. To gain a deeper understanding of these relationships and develop predictive models to identify individuals at risk of diabetes, further analysis and modeling can be conducted.\n\nHowever, it is crucial to acknowledge that this analysis is based on a specific dataset and population, and the findings may not be generalizable to other populations. Therefore, it is necessary to conduct further research and validation to establish robust conclusions and effectively inform healthcare interventions.\nI hope that this project will provide a template for future research in understanding the relationships between factors influencing diabetes diagnosis and other factors.\n\n# Bibliography\n\nPima Indians Diabetes Database : https://www.kaggle.com/datasets/uciml/pima-indians-diabetes-database.\n\nhttps://www.researchgate.net/publication/309679945_The_Study_of_Pima_Indian_Diabetes\n\nR Language as programming language\n\nThe R Graph Gallery-https://r-graph-gallery.com/",
    "supporting": [
      "final_project_MeghaJoseph_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}