{
  "hash": "b3bd9b4d6d349675004419d881f15557",
  "result": {
    "markdown": "---\ntitle: \"Final Project - History of International Futbol (Soccer)\"\nauthor: \"Shaunak Padhye\"\ndescription: \"Project\"\ndate: \"05/22/2023\"\nformat:\n  html:\n    toc: true\n    code-copy: true\n    code-tools: true\n    css: styles.css\ncategories:\n  - final_Project\n  - Shaunak Padhye\n  - International Soccer\neditor_options: \n  chunk_output_type: inline\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(summarytools)\nlibrary(zoo)\nlibrary(psych)\nlibrary(viridisLite)\nlibrary(plotly)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Introduction\n\nThe FIFA 2022 world cup saw some of the best soccer performances that we've ever seen, with Lionel Messi finally winning the most prestigious trophy in Soccer. It was a reminder as to why this sport is called the \"Beautiful Game\" and why so many people all over the world follow it. Soccer has a very rich history with experts saying that modern version began sometime during the 19th Century. This analysis aims to go over the history of International soccer and see what interesting inferences we can derive from the data. This analysis will begin with a brief introduction of the data and tidying of the data for the analysis. Then we will look at the following topics and try to answer a few questions:\n\n1) Home Advantage Analysis:\nThe dataset covers international games played from 1872 to 2022, allowing for an in-depth examination of the home advantage phenomenon. By analyzing team performances in home and away matches, I aim to identify the extent and significance of home advantage across different eras and regions.\n\n2) Impact of Major World Events on Soccer:\nI will explore the influence of major world events, such as wars and economic crises, on international soccer. By examining the dataset within the context of historical events, we can uncover how these factors have shaped the sport's development\n\n3) Analysis of Penalties:\nPenalties have been a major part of the sport and I will demonstrate the impact penalties have on a match.\n\n## Describe the data set\n\nDataser link:\nhttps://www.kaggle.com/datasets/martj42/international-football-results-from-1872-to-2017?select=results.csv\n\nFor this project, I will be working with 151 years of International Soccer history: Results and Goal scorers dataset. The International Soccer dataset has 2 files - \"results.csv\" and \"goalscorers.csv\". This dataset contains information about the International matches played from 1872 till 2023, and the players who scored the goals in these matches.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Reading the data\ngoalscorers <- read_csv(\"ShaunakPadhye_FinalProjectData/goalscorers.csv\")\nresults <- read_csv(\"ShaunakPadhye_FinalProjectData/results.csv\")\n```\n:::\n\n\nLets start by looking at the results dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Dimensions of results dataset\ndim(results)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 44557     9\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Glimpse into the results dataset\nstr(results)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nspc_tbl_ [44,557 × 9] (S3: spec_tbl_df/tbl_df/tbl/data.frame)\n $ date      : Date[1:44557], format: \"1872-11-30\" \"1873-03-08\" ...\n $ home_team : chr [1:44557] \"Scotland\" \"England\" \"Scotland\" \"England\" ...\n $ away_team : chr [1:44557] \"England\" \"Scotland\" \"England\" \"Scotland\" ...\n $ home_score: num [1:44557] 0 4 2 2 3 4 1 0 7 9 ...\n $ away_score: num [1:44557] 0 2 1 2 0 0 3 2 2 0 ...\n $ tournament: chr [1:44557] \"Friendly\" \"Friendly\" \"Friendly\" \"Friendly\" ...\n $ city      : chr [1:44557] \"Glasgow\" \"London\" \"Glasgow\" \"London\" ...\n $ country   : chr [1:44557] \"Scotland\" \"England\" \"Scotland\" \"England\" ...\n $ neutral   : logi [1:44557] FALSE FALSE FALSE FALSE FALSE FALSE ...\n - attr(*, \"spec\")=\n  .. cols(\n  ..   date = col_date(format = \"\"),\n  ..   home_team = col_character(),\n  ..   away_team = col_character(),\n  ..   home_score = col_double(),\n  ..   away_score = col_double(),\n  ..   tournament = col_character(),\n  ..   city = col_character(),\n  ..   country = col_character(),\n  ..   neutral = col_logical()\n  .. )\n - attr(*, \"problems\")=<externalptr> \n```\n:::\n:::\n\n\nWe can see that the results dataset contains 44557 rows, which means that we contain data about 44557 matches.\n\nThis dataset has 9 variables:\ndate - date of the match\nhome_team - the name of the home team (country)\naway_team - the name of the away team (country)\nhome_score - goals scored by the home team\naway_score - goals scored by the away team\ntournament - the name of the tournament\ncity - the city where the match was played\ncountry - the country where the match was played\nneutral - TRUE/FALSE, whether the match was played at a neutral venue\n\n\nNow, lets look at the Goal scorers data set.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Dimensions of goalscorers dataset\ndim(goalscorers)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 41008     8\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Glimpse into the results dataset\nstr(goalscorers)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nspc_tbl_ [41,008 × 8] (S3: spec_tbl_df/tbl_df/tbl/data.frame)\n $ date     : Date[1:41008], format: \"1916-07-02\" \"1916-07-02\" ...\n $ home_team: chr [1:41008] \"Chile\" \"Chile\" \"Chile\" \"Chile\" ...\n $ away_team: chr [1:41008] \"Uruguay\" \"Uruguay\" \"Uruguay\" \"Uruguay\" ...\n $ team     : chr [1:41008] \"Uruguay\" \"Uruguay\" \"Uruguay\" \"Uruguay\" ...\n $ scorer   : chr [1:41008] \"José Piendibene\" \"Isabelino Gradín\" \"Isabelino Gradín\" \"José Piendibene\" ...\n $ minute   : num [1:41008] 44 55 70 75 2 44 60 62 67 75 ...\n $ own_goal : logi [1:41008] FALSE FALSE FALSE FALSE FALSE FALSE ...\n $ penalty  : logi [1:41008] FALSE FALSE FALSE FALSE FALSE FALSE ...\n - attr(*, \"spec\")=\n  .. cols(\n  ..   date = col_date(format = \"\"),\n  ..   home_team = col_character(),\n  ..   away_team = col_character(),\n  ..   team = col_character(),\n  ..   scorer = col_character(),\n  ..   minute = col_double(),\n  ..   own_goal = col_logical(),\n  ..   penalty = col_logical()\n  .. )\n - attr(*, \"problems\")=<externalptr> \n```\n:::\n:::\n\n\nThe goal scorers dataset contains 41008 rows which suggests that 41008 goals were scored. This number is less than the number of games from the results dataset, which seems strange. We will explore this later in the analysis.\n\nThis dataset has 8 variables:\ndate - date of the match\nhome_team - the name of the home team (country)\naway_team - the name of the away team (country)\nteam - name of the team that scored the goal\nscorer - name of player who scored the goal\nown_goal - whether the goal was an own goal\npenalty - whether the goal was a penalty\n\n\n## Tidy Data and Mutate Variables (as needed)\n\nNow that we've looked at the datasets, lets check if it requires any tidying. We'll start by checking if the datasets contain any duplicated rows.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Checking for duplicates in results dataset\ndim(results[duplicated(results),])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0 9\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Checking for duplicates in goalscorers dataset\ndim(goalscorers[duplicated(goalscorers),])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 81  8\n```\n:::\n:::\n\nSeems like we have 81 duplicated rows in the goal scorers dataset. Lets check the duplicates to investigate.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Glimpse the duplicated rows in goalscorers dataset\nglimpse(goalscorers[duplicated(goalscorers),])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 81\nColumns: 8\n$ date      <date> 1963-11-26, 1963-11-28, 1963-11-28, 1965-03-14, 1968-01-16,…\n$ home_team <chr> \"Ghana\", \"Ethiopia\", \"Nigeria\", \"Suriname\", \"Congo\", \"Ghana\"…\n$ away_team <chr> \"Ethiopia\", \"Tunisia\", \"Sudan\", \"Trinidad and Tobago\", \"Ghan…\n$ team      <chr> \"Ghana\", \"Ethiopia\", \"Sudan\", \"Suriname\", \"Ghana\", \"Ghana\", …\n$ scorer    <chr> \"Edward Acquah\", \"Mengistu Worku\", \"Nasr Eddin Abbas\", \"Edmu…\n$ minute    <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …\n$ own_goal  <lgl> FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALS…\n$ penalty   <lgl> FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALS…\n```\n:::\n:::\n\nAs we can see, the minute variable shows NA for all the duplicates. This means that for these matches the minute at which the player scored was not recorded. Therefore, if a player scored more than once in these games, their entries in the row would be duplicated. This issue should go once we handle the NA values.\n\n\nLets start by checking NA values in the results dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Check if results dataset has NA values\nsum(is.na(results))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0\n```\n:::\n:::\n\n\nNow from the previous section we know that the goalscorers dataset contains NA values. Lets check how many NA values are present.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Check if goalscorers dataset has NA values\nsum(is.na(goalscorers))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 307\n```\n:::\n:::\n\n\nLets see what variables contain these NA values\n\n::: {.cell}\n\n```{.r .cell-code}\n# Checking NA values in each column\ncol <- colnames(goalscorers)\nfor (c in col){\n  print(paste0(\"NA values in \", c, \": \", sum(is.na(goalscorers[,c]))))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"NA values in date: 0\"\n[1] \"NA values in home_team: 0\"\n[1] \"NA values in away_team: 0\"\n[1] \"NA values in team: 0\"\n[1] \"NA values in scorer: 49\"\n[1] \"NA values in minute: 258\"\n[1] \"NA values in own_goal: 0\"\n[1] \"NA values in penalty: 0\"\n```\n:::\n:::\n\n\nFor the NA values in the minutes variable, we do not want to lose this data. For this reason we will replace the NA values with the mean of the minutes variable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Replacing NA values with mean value for minute column\ngoalscorers$minute <- na.aggregate(goalscorers$minute, FUN = mean)\n```\n:::\n\n\nSince for a few entries the scorer variable is empty we don't know who scored the goal. We can remove these rows from the dataset.\n\n::: {.cell}\n\n```{.r .cell-code}\n# Removing NA values from scorer column\ngoalscorers <- na.omit(goalscorers)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Checking if NA values removed successfully\nsum(is.na(goalscorers))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0\n```\n:::\n:::\n\nThe datasets have been cleaned and are ready for further processing.\n\n\nLets look at the variables in the results dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Columns in results dataset\ncolnames(results)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"date\"       \"home_team\"  \"away_team\"  \"home_score\" \"away_score\"\n[6] \"tournament\" \"city\"       \"country\"    \"neutral\"   \n```\n:::\n:::\n\nWe can see that we don't have a variable to tell us which team won the match. We will introduce a new variable called result for this purpose.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Adding result column in results dataset\nresults <- results %>%\n  mutate(result = case_when(\n    home_score > away_score ~ \"Home Team\",\n    home_score < away_score ~ \"Away Team\",\n    home_score == away_score ~ \"Draw\"\n  ))\nhead(results[, c(\"date\",\"home_team\",\"away_team\",\"home_score\",\"away_score\",\"result\")])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 6\n  date       home_team away_team home_score away_score result   \n  <date>     <chr>     <chr>          <dbl>      <dbl> <chr>    \n1 1872-11-30 Scotland  England            0          0 Draw     \n2 1873-03-08 England   Scotland           4          2 Home Team\n3 1874-03-07 Scotland  England            2          1 Home Team\n4 1875-03-06 England   Scotland           2          2 Draw     \n5 1876-03-04 Scotland  England            3          0 Home Team\n6 1876-03-25 Scotland  Wales              4          0 Home Team\n```\n:::\n:::\n\n\n## Descriptive Statistics\n\nI'll start by creating a summary of the results data sets using the summary function\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Summary of Results\nsummary(results)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      date             home_team          away_team           home_score    \n Min.   :1872-11-30   Length:44557       Length:44557       Min.   : 0.000  \n 1st Qu.:1979-06-29   Class :character   Class :character   1st Qu.: 1.000  \n Median :1999-04-28   Mode  :character   Mode  :character   Median : 1.000  \n Mean   :1992-08-13                                         Mean   : 1.739  \n 3rd Qu.:2011-06-04                                         3rd Qu.: 2.000  \n Max.   :2023-03-29                                         Max.   :31.000  \n   away_score      tournament            city             country         \n Min.   : 0.000   Length:44557       Length:44557       Length:44557      \n 1st Qu.: 0.000   Class :character   Class :character   Class :character  \n Median : 1.000   Mode  :character   Mode  :character   Mode  :character  \n Mean   : 1.178                                                           \n 3rd Qu.: 2.000                                                           \n Max.   :21.000                                                           \n  neutral           result         \n Mode :logical   Length:44557      \n FALSE:33480     Class :character  \n TRUE :11077     Mode  :character  \n                                   \n                                   \n                                   \n```\n:::\n:::\n\n\nThere are few interesting things to note from the above summary.\n\nThe first is that the first match in the data set was played on 30th November, 1872 and the latest match was played on 29th March, 2023.\n\nThe maximum number of goals scored by a Home Team is 31 and maximum goals scored by an Away Team is 21. These could be errors in the dataset or these matches could have had some extraordinary circumstances that allowed for such a feat.\n\nLets now look at the number of tournaments that have been occured in International soccer:\n\n::: {.cell}\n\n```{.r .cell-code}\n# Number of unique tournaments in results dataset\nlength(unique(results$tournament))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 142\n```\n:::\n:::\n\n\nThere is a wide variety of tournaments that have been played. Some of these tournaments might be region specific, some might be level specific. Qualifying tournamets such as World Cup Qualifiers are also counted.\n\nLets look at the distribution of the neutral variable using a bar chart.\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot for distribution of neutral variable\nggplot(results, aes(x = neutral)) +\n  geom_bar(fill = \"steelblue\") +\n  labs(title = \"Distribution of Matches on Neutral Grounds\",\n       x = \"Neutral Ground\",\n       y = \"Count\") +\n  theme_minimal() +\n  theme(plot.title = element_text(size = 16, face = \"bold\"),\n        axis.title = element_text(size = 12),\n        axis.text = element_text(size = 10))\n```\n\n::: {.cell-output-display}\n![](ShaunakPadhye_FinalProject_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\nAs we can see a small portion of the matches were played on neutral grounds and most of them were played either on the Home Team ground or the Away Team ground.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Summary of goalscorers dataset\nsummary(goalscorers)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      date             home_team          away_team             team          \n Min.   :1916-07-02   Length:40959       Length:40959       Length:40959      \n 1st Qu.:1985-10-30   Class :character   Class :character   Class :character  \n Median :2001-06-06   Mode  :character   Mode  :character   Mode  :character  \n Mean   :1996-09-29                                                           \n 3rd Qu.:2012-01-29                                                           \n Max.   :2022-12-18                                                           \n    scorer              minute        own_goal        penalty       \n Length:40959       Min.   :  1.00   Mode :logical   Mode :logical  \n Class :character   1st Qu.: 28.00   FALSE:40241     FALSE:38274    \n Mode  :character   Median : 51.00   TRUE :718       TRUE :2685     \n                    Mean   : 50.02                                  \n                    3rd Qu.: 73.00                                  \n                    Max.   :122.00                                  \n```\n:::\n:::\n\n\nFor this dataset, the minimum year in the date variable is 1916. This explains the discrepancy between the dimensions of the two datasets. This dataset does not contain the data of the goal scorers for matches from 1872 till 1916.\n\nNow, lets check the distribution of the minute variable to see at what minute in a match the most goals have been scored.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Compute the frequency of the continuous variable\nfrequency_data <- goalscorers %>%\n  group_by(minute) %>%\n  summarize(frequency = n())\n\n# Create a dataframe with the frequency data\nfrequency_df <- data.frame(\n  variable = frequency_data$minute,\n  frequency = frequency_data$frequency\n)\n\n# Create the line chart\nggplot(frequency_df, aes(x = variable, y = frequency)) +\n  geom_line(color = \"steelblue\", size = 1) +\n  labs(title = \"Goals scored per Minute\", x = \"Minute\", y = \"Number of Goals\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](ShaunakPadhye_FinalProject_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\n\nFrom the above plot we can see that we have two local maximas in the distribution. The first maxima occurs around the 45 minute mark which is when the first half in a soccer game ends. The second maxima occurs around the 90 minute mark, which is when a soccer match ends. This tells us that most goals are scored during critical sections in a match where the team might be in a make or break situation.\n\n## Visualization\n\n### Effect of Home Advantage\n\nNow we will look at whether playing on a Home ground gives an advantage to the Home Team.\n\nWe'll start by checking how many games have been played on a home ground rather than a neutral venue. This is controlled by the neutral variable in the results dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Number of games played on a home ground\ndim(results %>% \n  filter(neutral == FALSE))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 33480    10\n```\n:::\n:::\n\n\n\nA total of 33480 matches have been played on the home ground of a team rather than a neutral location.\n\nLets plot the distribution of wins for the result variable. This will allow us to see how many matches ended with the home team winning and how many for the away team and how many ended in a draw.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Distribution of result of match based for matches played on Home Ground\nresults %>% \n  filter(neutral == FALSE) %>% \n  group_by(date,home_team,away_team) %>%\n  ggplot(aes(x = result, fill = result)) +\n  geom_bar() +\n  labs(title = \"Results of matches played on Home Ground\", x = \"Result\", y = \"Count\") +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(size = 16, face = \"bold\"),\n    axis.title = element_text(size = 12),\n    axis.text = element_text(size = 10),\n    legend.title = element_blank(),\n    legend.text = element_text(size = 10)\n  )\n```\n\n::: {.cell-output-display}\n![](ShaunakPadhye_FinalProject_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\nHere we can see that a significant portion (over half) of the wins come from Home Teams when they're playing at their Home ground.\n\nWe'll plot the same graph for neutral locations.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Distribution of result of match based for matches played on neutral Ground\nresults %>% \n  filter(neutral == TRUE) %>% \n  group_by(date,home_team,away_team) %>%\n  ggplot(aes(x = result, fill = result)) +\n  geom_bar() +\n  labs(title = \"Results of matches played on Neutral Ground\", x = \"Result\", y = \"Count\") +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(size = 16, face = \"bold\"),\n    axis.title = element_text(size = 12),\n    axis.text = element_text(size = 10),\n    legend.title = element_blank(),\n    legend.text = element_text(size = 10)\n  )\n```\n\n::: {.cell-output-display}\n![](ShaunakPadhye_FinalProject_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\n\nThe difference between the number of wins for Home Team and Away Team is significantly less for matches played at a neutral venue.\n\nWe'll now check if this trend has been followed throughout various decades.\n\n::: {.cell}\n\n```{.r .cell-code}\n# Distribution of result by decade for matches played on Home ground\nresults %>%\n  filter(neutral == FALSE) %>%\n  mutate(decade = floor(year(date) / 10) * 10) %>%\n  group_by(decade, result) %>%\n  count() %>%\n  ggplot(aes(x = factor(decade), y = n, fill = result)) +\n  geom_bar(position = \"fill\", stat = \"identity\") +\n  labs(title = \"Distribution of Game Results by Decade\",\n       x = \"Decade\",\n       y = \"Proportion\") +\n  scale_fill_viridis_d(option = \"viridis\", begin = 0.1, end = 0.9) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](ShaunakPadhye_FinalProject_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n\n\nWe can see that a similar distribution has been observed over the decades. This is surprising as due to the ease of travel in the modern age, fans and supporters can travel to support their countries in International games. We would expect this distribution to slightly even out, but this doesn't seem to be the case.\n\nOne possible explanation for this is that the number of matches being played per decade has drastically increased as we can see in the graph below. Due to the sheer volume of games being played it is difficult for fans to go to all the matches their country is playing.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Number of games played per decade\nresults %>%\n  filter(neutral == FALSE) %>%\n  mutate(decade = floor(year(date) / 10) * 10) %>%\n  group_by(decade) %>%\n  count() %>%\n  ggplot(aes(x = factor(decade), y = n, fill = n)) +\n  geom_bar(stat = \"identity\") +\n  labs(title = \"Number of Games Played by Decade\",\n       x = \"Decade\",\n       y = \"Number of Games\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](ShaunakPadhye_FinalProject_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\n\nWe can check which teams have been most successful as the Home Team.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresults %>%\n  filter(result == \"Home Team\" & neutral == FALSE) %>%\n  group_by(home_team) %>%\n  summarize(total_wins = n()) %>%\n  arrange(desc(total_wins)) %>%\n  top_n(10) %>%\n  mutate(rank = dense_rank(desc(total_wins))) %>%\n  ggplot(aes(x = reorder(home_team, total_wins), y = total_wins, fill = rank)) +\n  geom_bar(stat = \"identity\") +\n  labs(title = \"Top 10 Countries with Most Wins as Home Team\",\n       x = \"Country\",\n       y = \"Total Wins\") +\n  scale_fill_gradientn(colors = viridisLite::viridis(n = 10, option = \"A\", begin = 0.2, end = 0.8)) +\n  theme_minimal() +\n  theme(plot.title = element_text(size = 16, face = \"bold\"),\n        axis.title = element_text(size = 12),\n        axis.text = element_text(size = 10),\n        axis.text.x = element_text(angle = 45, hjust = 1)) +\n  guides(fill = FALSE) +\n  coord_flip()\n```\n\n::: {.cell-output-display}\n![](ShaunakPadhye_FinalProject_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n\nFrom the above graph, we see a lot of expected countries, which have a very rich soccer culture such as England, Germany, France, Italy and Brazil. There are a few surprises as well such as Hungary and the United States.\n\nConversely, we can check which teams have been most successful as the Away Team.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresults %>%\n  filter(result == \"Away Team\" & neutral == FALSE) %>%\n  group_by(home_team) %>%\n  summarize(total_wins = n()) %>%\n  arrange(desc(total_wins)) %>%\n  top_n(10) %>%\n  mutate(rank = dense_rank(desc(total_wins))) %>%\n  ggplot(aes(x = reorder(home_team, total_wins), y = total_wins, fill = rank)) +\n  geom_bar(stat = \"identity\") +\n  labs(title = \"Top 10 Countries with Most Wins as Away Team\",\n       x = \"Country\",\n       y = \"Total Wins\") +\n  scale_fill_gradientn(colors = viridisLite::viridis(n = 10, option = \"A\", begin = 0.2, end = 0.8)) +\n  theme_minimal() +\n  theme(plot.title = element_text(size = 16, face = \"bold\"),\n        axis.title = element_text(size = 12),\n        axis.text = element_text(size = 10),\n        axis.text.x = element_text(angle = 45, hjust = 1)) +\n  guides(fill = FALSE) +\n  coord_flip()\n```\n\n::: {.cell-output-display}\n![](ShaunakPadhye_FinalProject_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n\n\nThese results are surprising as most of these countries aren't known for soccer. You might expect a country having more successful away record being one of the top ranked soccer nations but the result above disabuses us of this notion.\n\nWe can check the same result for matches played on neutral grounds. For this we will have to modify the results dataset. The teams playing in each match are split into two variables: Home Team and Away Team. Since we want to group by \"team\", we will need to pivot the home_team and away_team into a single variable called \"team\". This will allow us to group the data set by team.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresult_pivoted <- results %>%\n  pivot_longer(cols = c(home_team, away_team), names_to = \"team_type\", values_to = \"team\") %>%\n  mutate(team_type = ifelse(team_type == \"home_team\", \"Home Team\", \"Away Team\"))\nhead(result_pivoted[, c(\"date\",\"home_score\",\"away_score\",\"result\",\"team_type\",\"team\")])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 6\n  date       home_score away_score result    team_type team    \n  <date>          <dbl>      <dbl> <chr>     <chr>     <chr>   \n1 1872-11-30          0          0 Draw      Home Team Scotland\n2 1872-11-30          0          0 Draw      Away Team England \n3 1873-03-08          4          2 Home Team Home Team England \n4 1873-03-08          4          2 Home Team Away Team Scotland\n5 1874-03-07          2          1 Home Team Home Team Scotland\n6 1874-03-07          2          1 Home Team Away Team England \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nresult_pivoted %>%\n  filter(result == team_type & neutral == TRUE) %>%\n  group_by(team) %>%\n  summarize(total_wins = n()) %>%\n  arrange(desc(total_wins)) %>%\n  top_n(10) %>%\n  mutate(rank = dense_rank(desc(total_wins))) %>%\n  ggplot(aes(x = reorder(team, total_wins), y = total_wins, fill = rank)) +\n  geom_bar(stat = \"identity\") +\n  labs(title = \"Top 10 Countries with Most Wins on Neutral grounds\",\n       x = \"Country\",\n       y = \"Total Wins\") +\n  scale_fill_gradientn(colors = viridisLite::viridis(n = 10, option = \"A\", begin = 0.2, end = 0.8)) +\n  theme_minimal() +\n  theme(plot.title = element_text(size = 16, face = \"bold\"),\n        axis.title = element_text(size = 12),\n        axis.text = element_text(size = 10),\n        axis.text.x = element_text(angle = 45, hjust = 1)) +\n  guides(fill = FALSE) +\n  coord_flip()\n```\n\n::: {.cell-output-display}\n![](ShaunakPadhye_FinalProject_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n\nAgain we see a few expected countries and few unexpected ones. A possible explanation for countries like Iraq, Saudi Arabia, Indonesia is the political climate in these countries might have prevented them from playing matches at home. For this reason a neutral venue might have been arranged for all those game which might have otherwise been played at their home ground.\n\n### Impact of historical events\n\nNow we will investigate the impact of major world events on International Soccer.\n\nWe'll start by plotting a line chart for number of matches played per year over time.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresults %>%\n  group_by(year = lubridate::year(date)) %>%\n  summarize(matches = n()) %>%\n  filter(year < 2023) %>%\n  ggplot(aes(x = year, y = matches)) +\n  geom_line(color = \"steelblue\", size = 1) +\n  labs(title = \"Number of Matches Played per Year\", x = \"Year\", y = \"Matches\") +\n  scale_x_continuous(breaks = seq(1870, 2020, by = 10)) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](ShaunakPadhye_FinalProject_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n:::\n\n\nWe can see from the above graph that there is a general increasing trend in the number of matches played. We will divide the time frame into two parts 1872 to 1950 and 1950 to 2022. We are doing this to examine the trends with more focus.\n\nWe will start with examining the data from 1872 to 1950.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresults %>%\n  group_by(year = lubridate::year(date)) %>%\n  summarize(matches = n()) %>%\n  filter(year < 1950) %>%\n  ggplot(aes(x = year, y = matches)) +\n  geom_line(color = \"steelblue\", size = 1) +\n  labs(title = \"Number of Matches Played per Year\", x = \"Year\", y = \"Matches\") +\n  scale_x_continuous(breaks = seq(1870, 1950, by = 5)) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](ShaunakPadhye_FinalProject_files/figure-html/unnamed-chunk-33-1.png){width=672}\n:::\n:::\n\n\nIn the above graph, we can see that there are two significant dips in the number of matches being played. These dips (minima) correspond to the years when the two World Wars happened. As we'd expect the World Wars upset the entire balance in global geo-political situation and the number of soccer matches being played also decreased.\n\n\nSimilarly, we will check the trend for years 1950 to 2022.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresults %>%\n  group_by(year = lubridate::year(date)) %>%\n  summarize(matches = n()) %>%\n  filter(year > 1950 & year < 2023) %>%\n  ggplot(aes(x = year, y = matches)) +\n  geom_line(color = \"steelblue\", size = 1) +\n  labs(title = \"Number of Matches Played per Year\", x = \"Year\", y = \"Matches\") +\n  scale_x_continuous(breaks = seq(1950, 2022, by = 5)) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](ShaunakPadhye_FinalProject_files/figure-html/unnamed-chunk-34-1.png){width=672}\n:::\n:::\n\n\nWe can see a general increasing trend for the above graph. There are a lot of local maximas and minimas in this graph. The local maximas correspond to when most of the major International tournaments are played. For example, the World Cup is played every 4 years.\n\nWe see a massive decrease in the number of matches played for the year 2020. This is the year when the Covid 19 pandemic struck the world and everyone was forced to quarantine. As expected even soccer felt the ramifications of this.\n\nThe trend from years 1950 till 1980 is very erratic. These were the years when there was Cold War going on between the United States of America and Russia, which might be one of the reasons for that trend.\n\n### Analysis of Penalties\n\nFinally we will look at Penalties and see how they affect the game.\nPenalties are given to a team if they are fouled near the opponent's goal. The team then gets the opportunity to score goal from a certain distance with only the goal keeper in the way.\nPenalties are also used as deciders in case a match ends up as a draw.\n\nLets see which countries have been most successful at scoring penalties.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Group by and summarize goalscorers dataset to find out top 10 teams with most penalties\npenalty_analysis <- goalscorers %>%\n  filter(penalty == TRUE) %>%\n  group_by(team) %>%\n  summarize(total_penalties = n()) %>%\n  arrange(desc(total_penalties)) %>%\n  top_n(10)\n\n# Print the top 10 teams with the most penalties\nprint(penalty_analysis)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 10 × 2\n   team        total_penalties\n   <chr>                 <int>\n 1 Brazil                   64\n 2 Mexico                   60\n 3 Argentina                58\n 4 Netherlands              52\n 5 Spain                    52\n 6 Germany                  51\n 7 England                  50\n 8 Sweden                   50\n 9 Denmark                  47\n10 Uruguay                  46\n```\n:::\n\n```{.r .cell-code}\n# Create a bar chart of the top 10 teams with the most penalties\nggplot(penalty_analysis, aes(x = reorder(team, total_penalties), y = total_penalties)) +\n  geom_bar(stat = \"identity\", fill = \"steelblue\") +\n  labs(title = \"Top 10 Teams with the Most Penalties\",\n       x = \"Team\",\n       y = \"Total Penalties\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](ShaunakPadhye_FinalProject_files/figure-html/unnamed-chunk-35-1.png){width=672}\n:::\n:::\n\n\nNow we'll check how penalties affect the outcome of a game. For this analysis we will have to merge the results and the goalscorers datasets. This because the match outcome data is stored in the results dataset and the penalty data is stored in the goalscorers dataset.\nWe can uniquely identify a match based on the date and the two teams that played the game. We will join the two datasets using these three variables.\n\n::: {.cell}\n\n```{.r .cell-code}\n# Merging results and goalscorers datasets\nmerged_results <- merge(results,goalscorers , by = c(\"date\", \"home_team\", \"away_team\"))\nhead(merged_results)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        date home_team away_team home_score away_score   tournament\n1 1916-07-02     Chile   Uruguay          0          4 Copa América\n2 1916-07-02     Chile   Uruguay          0          4 Copa América\n3 1916-07-02     Chile   Uruguay          0          4 Copa América\n4 1916-07-02     Chile   Uruguay          0          4 Copa América\n5 1916-07-06 Argentina     Chile          6          1 Copa América\n6 1916-07-06 Argentina     Chile          6          1 Copa América\n          city   country neutral    result      team           scorer minute\n1 Buenos Aires Argentina    TRUE Away Team   Uruguay  José Piendibene     44\n2 Buenos Aires Argentina    TRUE Away Team   Uruguay Isabelino Gradín     55\n3 Buenos Aires Argentina    TRUE Away Team   Uruguay Isabelino Gradín     70\n4 Buenos Aires Argentina    TRUE Away Team   Uruguay  José Piendibene     75\n5 Buenos Aires Argentina   FALSE Home Team Argentina    Alberto Ohaco      2\n6 Buenos Aires Argentina   FALSE Home Team     Chile   Telésforo Báez     44\n  own_goal penalty\n1    FALSE   FALSE\n2    FALSE   FALSE\n3    FALSE   FALSE\n4    FALSE   FALSE\n5    FALSE   FALSE\n6    FALSE   FALSE\n```\n:::\n:::\n\n\nLets look at the impact of penalties on the outcome of matches.\n\nWe will calculate the number of games where the home team scored a penalty and won the game and the number of games where the home team scored a penalty but lost the game. Then we will create a pie chart to show the results.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Number of penalties scored by home team where Home team won the match\nhome_penalties <- merged_results %>%\n  filter(penalty & home_team == team & result == \"Home Team\") %>%\n  nrow()\nhome_penalties\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1237\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Number of penalties scored by home team where Away team won the match\nhome_penalties_l <- merged_results %>%\n  filter(penalty & home_team == team & result == \"Away Team\") %>%\n  nrow()\nhome_penalties_l\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 225\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Adding data to a dataframe\ndata <- data.frame(category = c(\"Wins with Penalty\", \"Losses with Penalty\"),\n                   count = c(home_penalties, home_penalties_l))\n\n# Creating the pie chart\nggplot(data, aes(x = \"\", y = count, fill = category)) +\n  geom_bar(width = 1, stat = \"identity\") +\n  coord_polar(theta = \"y\") +\n  labs(title = \"Penalties Distribution\",\n       fill = \"Category\",\n       x = NULL, y = NULL) +\n  theme_void() +\n  theme(plot.title = element_text(hjust = 0.5))\n```\n\n::: {.cell-output-display}\n![](ShaunakPadhye_FinalProject_files/figure-html/unnamed-chunk-39-1.png){width=672}\n:::\n:::\n\n\n\nAs we can see, matches where a team took a penalty, most likely that team ended up winning the match.\n\n## Conclusion and Reflection\n\nThe visualizations in the \"Home Advantage\" section provide validation that playing at a home ground does provide an advantage to the Home Team. However, I don't believe this is a bad thing. Fans of the sport are very passionate about the teams that they support and having their team play in their home ground allows these fans to show their support. At the same time these tournaments should be scheduled so that some teams aren't getting an unfair advantage in the overall tournament. It would be interesting to see how players individually are impacted by playing at home or away and if we could classify players accordingly.\n\nIn the second part of the analysis, I got the same results as expected. Soccer is majorly impacted by World events such as Wars and Pandemics. But the sport is also able to recover from this. As we can see the sport has grown a lot in 150 years. A similar analysis for a single country might be able to give us an insight on how the socio-political conditions there affect their participation in International Soccer.\n\nFinally, we did a brief analysis of penalties. We can surmise that penalties play a major role in deciding the outcome of games. There has been a lot of debate regarding alternatives to penalties to make the game more balanced. I believe that having the threat of giving away a penalty keeps the defenders of the teams in check as they risk losing a goal.\n\n## Bibliography\n\nInternational Soccer dataset:\nhttps://www.kaggle.com/datasets/martj42/international-football-results-from-1872-to-2017?select=results.csv\n\nHistory of Football (Soccer):\nhttps://www.footballhistory.org/\n\nKey events of the 20th century:\nhttps://en.wikipedia.org/wiki/Key_events_of_the_20th_century\n\nR Language as programming language\n\nWickham, H., & Grolemund, G. (2016). R for data science: Visualize, model, transform, tidy, and import data. OReilly Media.\n\nThe R Graph Gallery-https://r-graph-gallery.com/",
    "supporting": [
      "ShaunakPadhye_FinalProject_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}