{
  "hash": "be29fe2fb9d1d0f31ecd9f19c522986b",
  "result": {
    "markdown": "---\ntitle: \"Final Project Assignment #1: Justine Shakespeare\"\nauthor: \"Justine Shakespeare\"\ndescription: \"Project & Data Description\"\ndate: \"04/12/2023\"\nformat:\n  html:\n    df-print: paged\n    toc: true\n    code-copy: true\n    code-tools: true\n    css: styles.css\ncategories:\n  - final_Project_assignment_1\n  - final_project_data_description\n  - Justine Shakespeare\n  - Baby Names\neditor_options: \n  chunk_output_type: console\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Part 1. Introduction {#describe-the-data-sets}\n\nCompared to decisions around sleep, breastfeeding, schools and more, naming your baby may seem like one of more arbitrary and inconsequential choices a parent makes. But it is a deeply personal decision, laden with expectations, hopes, and even whimsy. Baby names may seem like an innocuous, fluffy data point, but they provide a fascinating window into the cultural trends and societal values of the United States at different points in time.\n\nMy interest in baby names and naming trends in the United States is personally motivated. The day we found out I was pregnant back in spring 2020 my husband suggested the name Oliver if we had a boy. I loved it, but found out soon enough that we weren't the only ones. In 2020, Oliver was the third most popular name given to baby boys in the United States.\n\nI thought back to my childhood in rural Vermont where four out of the 16 kids in my class in elementary school were named Chris. I did not want my son to be one of four Olivers in a classroom. While we tried to find alternative names, a friend suggested that while Oliver is a popular name now (as Chris was in the mid 1980s) the actual percentage of babies named Oliver is likely less, since the diversity of names has increased in recent times. When I came across this baby names data I knew I had to investigate this hypothesis.\n\nIn addition to answering this burning question, I will explore other patterns around name popularity, including which names have been the most popular during different time periods, and whether there is a cyclical nature to popularity for some names.\n\n#### The Data\n\nThe data I'll be analyzing was downloaded from the [Social Security Administration (SSA) website](https://www.ssa.gov/oact/babynames/limits.html). Much of this data is featured on the website, but is limited to just the top 1,000 names for each year and sex. The data I'll be working with here includes all of the names in their database, which are drawn from Social Security card applications. This data contains names of babies born in the United States from 1910 until 2021.\n\nSome additional notes about this data:\n\n-   The SSA states that before 1937 many people did not apply for a Social Security card, and so their names will not be reflected in the data.\n\n-   Records that did not include the state of birth, sex, and year of birth are not included in the data.\n\n-   In order to be included, names had to be at least 2 characters long.\n\n-   In order to protect the privacy of individuals, the SSA restricts this list to only names with at least 5 occurrences. They state in their accompanying documentation: \"If a name has less than 5 occurrences for a year of birth in any state, the sum of the state counts for that year will be less than the national count.\"\n\n-   Because name data are not edited there may be mistakes in the sex listed and entries such as \"Unknown\" and \"Baby\" have not been removed. In fact, there are 591 occurrences of \"Baby\" and 760 occurrences of \"Unknown\" listed as baby names in this data. Since these are not actual baby names, we will remove these during the data cleaning section below.\n\n-   The SSA did not combine similar names with different spelling. So names Caitlin, Caitlyn, Kaitlin, Kaitlyn, and other version are all listed separately. This should be considered a limitation since it may obscure the true popularity of names that can be spelling in different ways, such as Caitlin.\n\n#### Research Questions\n\n1.  What are the most popular names in a given state and year? What are the most popular names in a year (across all states)? What are the most popular names in the entire dataset (across all states and all years, 1910 to 2021)? Finally, what have been the most popular names for each generation?\n\n2.  Has there been a change over time in the proportion of babies who are named the most popular names? More specifically, is the name Oliver as popular now in the 2020s as Chris was in the 1980s?\n\n3.  Is there a cyclical nature to the popularity of some names? Are there some names that were popular in the early part of the 20th century that have regained popularity?\n\n4.  Are there certain states that could be considered trendsetters - did popular names become popular in certain states first?\n\n*I may not have time to explore the last two research questions (3 and 4) in full, but I'd like to do at least one of them.*\n\n## Part 2. Describe the data set(s) {#describe-the-data-sets-1}\n\nFirst, we'll read in the dataset and take a look at the data. This data was stored in 51 text files (one for each state, with an additional file for Washington D.C.), which I read into R using the `read_delim()` function. Since the column names were missing from these files, I added them in when reading in the data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nBabyNames <- read_delim(\n  c(\"~/601_Spring_2023/601_Spring_2023/posts/JustineShakespeare_FinalProjectData/AK.txt\", \"~/601_Spring_2023/601_Spring_2023/posts/JustineShakespeare_FinalProjectData/AL.txt\",\n\"~/601_Spring_2023/601_Spring_2023/posts/JustineShakespeare_FinalProjectData/AR.txt\", \"~/601_Spring_2023/601_Spring_2023/posts/JustineShakespeare_FinalProjectData/AZ.txt\",\n\"~/601_Spring_2023/601_Spring_2023/posts/JustineShakespeare_FinalProjectData/CA.txt\", \"~/601_Spring_2023/601_Spring_2023/posts/JustineShakespeare_FinalProjectData/CO.txt\",\n\"~/601_Spring_2023/601_Spring_2023/posts/JustineShakespeare_FinalProjectData/DC.txt\", \"~/601_Spring_2023/601_Spring_2023/posts/JustineShakespeare_FinalProjectData/DE.txt\",\n\"~/601_Spring_2023/601_Spring_2023/posts/JustineShakespeare_FinalProjectData/FL.txt\", \"~/601_Spring_2023/601_Spring_2023/posts/JustineShakespeare_FinalProjectData/GA.txt\",\n\"~/601_Spring_2023/601_Spring_2023/posts/JustineShakespeare_FinalProjectData/HI.txt\", \"~/601_Spring_2023/601_Spring_2023/posts/JustineShakespeare_FinalProjectData/IA.txt\",\n\"~/601_Spring_2023/601_Spring_2023/posts/JustineShakespeare_FinalProjectData/ID.txt\", \"~/601_Spring_2023/601_Spring_2023/posts/JustineShakespeare_FinalProjectData/IL.txt\",\n\"~/601_Spring_2023/601_Spring_2023/posts/JustineShakespeare_FinalProjectData/IN.txt\", \"~/601_Spring_2023/601_Spring_2023/posts/JustineShakespeare_FinalProjectData/KS.txt\",\n\"~/601_Spring_2023/601_Spring_2023/posts/JustineShakespeare_FinalProjectData/KY.txt\", \"~/601_Spring_2023/601_Spring_2023/posts/JustineShakespeare_FinalProjectData/CT.txt\",\n\"~/601_Spring_2023/601_Spring_2023/posts/JustineShakespeare_FinalProjectData/LA.txt\", \"~/601_Spring_2023/601_Spring_2023/posts/JustineShakespeare_FinalProjectData/NC.txt\",\n\"~/601_Spring_2023/601_Spring_2023/posts/JustineShakespeare_FinalProjectData/MA.txt\", \"~/601_Spring_2023/601_Spring_2023/posts/JustineShakespeare_FinalProjectData/ND.txt\",\n\"~/601_Spring_2023/601_Spring_2023/posts/JustineShakespeare_FinalProjectData/MD.txt\", \"~/601_Spring_2023/601_Spring_2023/posts/JustineShakespeare_FinalProjectData/NE.txt\",\n\"~/601_Spring_2023/601_Spring_2023/posts/JustineShakespeare_FinalProjectData/ME.txt\", \"~/601_Spring_2023/601_Spring_2023/posts/JustineShakespeare_FinalProjectData/NH.txt\",\n\"~/601_Spring_2023/601_Spring_2023/posts/JustineShakespeare_FinalProjectData/MI.txt\", \"~/601_Spring_2023/601_Spring_2023/posts/JustineShakespeare_FinalProjectData/NJ.txt\",\n\"~/601_Spring_2023/601_Spring_2023/posts/JustineShakespeare_FinalProjectData/MN.txt\", \"~/601_Spring_2023/601_Spring_2023/posts/JustineShakespeare_FinalProjectData/NM.txt\",\n\"~/601_Spring_2023/601_Spring_2023/posts/JustineShakespeare_FinalProjectData/MO.txt\", \"~/601_Spring_2023/601_Spring_2023/posts/JustineShakespeare_FinalProjectData/NV.txt\",\n\"~/601_Spring_2023/601_Spring_2023/posts/JustineShakespeare_FinalProjectData/MS.txt\", \"~/601_Spring_2023/601_Spring_2023/posts/JustineShakespeare_FinalProjectData/NY.txt\",\n\"~/601_Spring_2023/601_Spring_2023/posts/JustineShakespeare_FinalProjectData/MT.txt\", \"~/601_Spring_2023/601_Spring_2023/posts/JustineShakespeare_FinalProjectData/OH.txt\",\n\"~/601_Spring_2023/601_Spring_2023/posts/JustineShakespeare_FinalProjectData/OR.txt\", \"~/601_Spring_2023/601_Spring_2023/posts/JustineShakespeare_FinalProjectData/OK.txt\",\n\"~/601_Spring_2023/601_Spring_2023/posts/JustineShakespeare_FinalProjectData/PA.txt\", \"~/601_Spring_2023/601_Spring_2023/posts/JustineShakespeare_FinalProjectData/RI.txt\",\n\"~/601_Spring_2023/601_Spring_2023/posts/JustineShakespeare_FinalProjectData/SC.txt\", \"~/601_Spring_2023/601_Spring_2023/posts/JustineShakespeare_FinalProjectData/VA.txt\",\n\"~/601_Spring_2023/601_Spring_2023/posts/JustineShakespeare_FinalProjectData/SD.txt\", \"~/601_Spring_2023/601_Spring_2023/posts/JustineShakespeare_FinalProjectData/VT.txt\",\n\"~/601_Spring_2023/601_Spring_2023/posts/JustineShakespeare_FinalProjectData/TN.txt\", \"~/601_Spring_2023/601_Spring_2023/posts/JustineShakespeare_FinalProjectData/WA.txt\",\n\"~/601_Spring_2023/601_Spring_2023/posts/JustineShakespeare_FinalProjectData/TX.txt\", \"~/601_Spring_2023/601_Spring_2023/posts/JustineShakespeare_FinalProjectData/WI.txt\",\n\"~/601_Spring_2023/601_Spring_2023/posts/JustineShakespeare_FinalProjectData/UT.txt\", \"~/601_Spring_2023/601_Spring_2023/posts/JustineShakespeare_FinalProjectData/WV.txt\",\n\"~/601_Spring_2023/601_Spring_2023/posts/JustineShakespeare_FinalProjectData/WY.txt\"),\n                        delim = \",\", col_names = c(\"State\", \"Sex\", \"Year\", \"Name\", \"Occurrences\"))\n```\n:::\n\n\nNow that the data is loaded, let's take a closer look.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(BabyNames)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 6,311,504\nColumns: 5\n$ State       <chr> \"AK\", \"AK\", \"AK\", \"AK\", \"AK\", \"AK\", \"AK\", \"AK\", \"AK\", \"AK\"…\n$ Sex         <chr> \"F\", \"F\", \"F\", \"F\", \"F\", \"F\", \"F\", \"F\", \"F\", \"F\", \"F\", \"F\"…\n$ Year        <dbl> 1910, 1910, 1910, 1910, 1910, 1910, 1910, 1910, 1911, 1911…\n$ Name        <chr> \"Mary\", \"Annie\", \"Anna\", \"Margaret\", \"Helen\", \"Elsie\", \"Lu…\n$ Occurrences <dbl> 14, 12, 10, 8, 7, 6, 6, 5, 12, 7, 7, 6, 6, 6, 9, 8, 7, 7, …\n```\n:::\n:::\n\n\nEach case in this data represents a name given to a baby and the number of babies with that name in a given state, year, and sex. As noted above, this data includes all of the data reported to the Social Security Administration (except for baby names with less than 5 occurrences), and so it includes well over 6 million observations.\n\nWe will use all of the variables in this data frame, which are: Name, Year, State, Sex, and Occurrences. While the data is already pretty tidy, there are a few small changes we can make to make this data easier to use. Let's recode the values of the Sex variable so that \"F\" and \"M\" are spelled out. As noted in the introduction, there are some cases of \"Baby\" and \"Unknown\" in this data that are not actual baby names. We will remove those.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nBabyNames <- BabyNames %>% \n  mutate(Sex = recode(Sex, \"F\" = \"Female\", \"M\" = \"Male\"))\n\nBabyNames <- BabyNames %>% \n  filter(Name != \"Baby\" & Name != \"Unknown\")\n\nglimpse(BabyNames)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 6,310,153\nColumns: 5\n$ State       <chr> \"AK\", \"AK\", \"AK\", \"AK\", \"AK\", \"AK\", \"AK\", \"AK\", \"AK\", \"AK\"…\n$ Sex         <chr> \"Female\", \"Female\", \"Female\", \"Female\", \"Female\", \"Female\"…\n$ Year        <dbl> 1910, 1910, 1910, 1910, 1910, 1910, 1910, 1910, 1911, 1911…\n$ Name        <chr> \"Mary\", \"Annie\", \"Anna\", \"Margaret\", \"Helen\", \"Elsie\", \"Lu…\n$ Occurrences <dbl> 14, 12, 10, 8, 7, 6, 6, 5, 12, 7, 7, 6, 6, 6, 9, 8, 7, 7, …\n```\n:::\n:::\n\n\nThis brings our total observations from 6,311,504 to 6,310,153.\n\nNow let's take a closer look at the data. We'll use the `n_distinct()` functions to inspect the values in some of these variable, both to get a sense of our data and to double check that it doesn't need any additional cleaning. We can use `range()` to learn the years included in this data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_distinct(BabyNames$State)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 51\n```\n:::\n\n```{.r .cell-code}\nn_distinct(BabyNames$Sex)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2\n```\n:::\n\n```{.r .cell-code}\nrange(BabyNames$Year)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1910 2021\n```\n:::\n:::\n\n\nThe number of distinct values in the State and Sex column are what we'd expect (51 and 2, respectively), and the range function tells us that our data ranges from 1910 to 2021.\n\nLet's look at how many unique names there are in the data, by Sex.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nFemaleNames <- filter(BabyNames, Sex == \"Female\")\nn_distinct(FemaleNames$Name)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 21373\n```\n:::\n\n```{.r .cell-code}\nMaleNames <- filter(BabyNames, Sex == \"Male\")\nn_distinct(MaleNames$Name)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 14178\n```\n:::\n:::\n\n\nThere are significantly fewer unique names for males than there are for females in this data. Note this is not counting occurrences, but unique names.\n\nLet's take a closer look at the *occurrences* of baby names.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nBabyNames %>%\n  summarize(Min = min(Occurrences),\n            Mean = mean(Occurrences),\n            Median = median(Occurrences),\n            Max = max(Occurrences))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Min\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Mean\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Median\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Max\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"5\",\"2\":\"50.66567\",\"3\":\"12\",\"4\":\"10026\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nAs a reminder, this is looking at the occurrences listed in the data without any transformation - so this reflects the total occurrences for a single name, either female or male, in a given state, in a given year. So the max here represents a name that was named 10,026 in one state in one year for either male or female babies. We'll dig into this more when we get to the analysis.\n\nThe mean and median are quite low, especially when considered with the max number of occurrences. This indicates that there are many less popular names in the data.\n\n***ARE THERE OTHER DESCRIPTIVE STATISTICS I COULD INCLUDE FOR THIS DATA?***\n\n## Part 3. The Tentative Plan for Visualization {#the-tentative-plan-for-visualization}\n\nThe analysis and visualization that I will do for this project will be driven by my research questions. I'll need to create several additional variables in order to answer the research questions, including:\n\n-   **Sum_Occurrences** - this variable will be created in several different scenarios and will constitute different sums depending on the goal of the analysis at hand. This will enable summing occurrences across states, years in some cases, and even generations. It will be used for analysis with all of the research questions here.\n\n-   **Generation** - this variable will indicate the generation to which each year belongs. It will be used to perform analysis exploring the most popular names in a generation (research question #1).\n\n-   **Generation_Rank** - this variable will rank names based on the number of occurrences within a generation. This will be used in the analysis exploring the most popular names in a generation (research question #1).\n\n-   **Year_Rank** - this variable will rank names based on the number of occurrences within a year (across all states). It will be used in both the analysis exploring the change in proportion of popular names and the cyclical nature of popular names (research questions #2 and #3).\n\n-   **StateYear_Rank** - similar to the Year_Rank variable, this variable will rank names based on the number of occurrences within a year and within a state. It will be used for the analysis exploring whether certain states set naming trends (research question #4).\n\n-   **Proportion** - this variable is is created by dividing the sum of occurrences for one name across all states in a given year by the total occurrences of all names across all states in the same year. This will be used for analysis exploring how the proportion of popular names has changed over time (research question #2)\n\n### Visualizations\n\nEach research question will include a set of data visualizations:\n\n##### Research Question 1: What are the most popular names across a variety of categories (state and year, year, all time, generation)?\n\nFor this question I will use piping, `group_by()`, `summarize()` and other functions to pull the top 10 names in a given state in a given year by sex; in a given year across all states; in the entire dataset (so in all of 1910 until 2021); and finally in each generation. I am still brainstorming the best way to visualize this information (would be great to not just have a series of `head()` output lists), but I'm not totally sure yet. For the final part of this research question (most popular names in a generation) I will graph the popularity of each of the top names across the whold time period captured in the dataset, to give a visual sense of how those names have fluctuated in their popularity.\n\n##### Research Question 2: Has there been a change over time in the proportion of babies who are named the top ranking names?\n\nFor this question I will use piping, `group_by()`, `summarize()`, `pivot_wider()`, `full_join()` and other functions to create several new variables, including the Year_Rank and Proportion variable mentioned above. I will create two data frames (one for female names and one for male) that have variables that capture the ranking of each name in each year and the proportion of babies that have that name in given year. I will create a data visualization that charts the top 3 ranked names across time by proportion so that we can see whether the proportion of babies with the top ranked names changes over time.\n\n##### Research Question 3: Is there a cyclical nature to the popularity of some names?\n\nFor this question I will choose some names that were fairly popular early on (before 1950) and create graphs that show how their popularity has changed over time. I will aim to showcase only names that have had interesting changes in their popularity.\n\n##### Research Question 4: Are there certain states that could be considered trendsetters for baby names?\n\nBecause name trends began to shift more quickly after the Baby Boom Generation (see the Generation analysis in Research Question 1), the data for this question will be limited to just names from Generation X until the present. To explore this question I will first create the Year_Rank variable but for each individual state, so the popularity within states will be reflected in a new variables called StateYear_Rank. Then I will explore for a set of specific names when they were first ranked highly in the StateYear_Rank variable. I would like to showcase this in a visual but am not sure which would be best for this...\n\n\n*Below I have begun the analysis and visualization for research questions 1 and 2. This is still a work in progress...*\n\n\n::: panel-tabset\n## Research Question 1\n\nThis question has four parts:\n\n*a. What are the most popular names in a given state and year, by sex?*\n\n*b. What are the most popular names in a given year, across all states, by sex?*\n\n*c. What are the most popular names across the entire data - so in the United States from 1910 to 2021, by sex?*\n\n*d. What are the most popular names for each generation in the data (as defined by Pew Research Center)*\n\nFirst let's explore the most popular names in a given state and year, by sex (question 1.a).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Name given to the most babies in one year and in one state, female and male\nPopF_State <- BabyNames %>% \n  filter(Sex == \"Female\") %>%\n  arrange(desc(Occurrences))\nhead(PopF_State, n = 10)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"State\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Sex\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Year\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Name\"],\"name\":[4],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Occurrences\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"PA\",\"2\":\"Female\",\"3\":\"1918\",\"4\":\"Mary\",\"5\":\"8184\"},{\"1\":\"PA\",\"2\":\"Female\",\"3\":\"1917\",\"4\":\"Mary\",\"5\":\"7988\"},{\"1\":\"PA\",\"2\":\"Female\",\"3\":\"1915\",\"4\":\"Mary\",\"5\":\"7970\"},{\"1\":\"PA\",\"2\":\"Female\",\"3\":\"1921\",\"4\":\"Mary\",\"5\":\"7772\"},{\"1\":\"PA\",\"2\":\"Female\",\"3\":\"1916\",\"4\":\"Mary\",\"5\":\"7730\"},{\"1\":\"PA\",\"2\":\"Female\",\"3\":\"1920\",\"4\":\"Mary\",\"5\":\"7650\"},{\"1\":\"NY\",\"2\":\"Female\",\"3\":\"1947\",\"4\":\"Linda\",\"5\":\"7542\"},{\"1\":\"PA\",\"2\":\"Female\",\"3\":\"1919\",\"4\":\"Mary\",\"5\":\"7428\"},{\"1\":\"PA\",\"2\":\"Female\",\"3\":\"1922\",\"4\":\"Mary\",\"5\":\"7302\"},{\"1\":\"PA\",\"2\":\"Female\",\"3\":\"1924\",\"4\":\"Mary\",\"5\":\"7200\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nPopM_State <- BabyNames %>% \n  filter(Sex == \"Male\") %>%\n  arrange(desc(Occurrences))\nhead(PopM_State, n = 10)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"State\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Sex\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Year\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Name\"],\"name\":[4],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Occurrences\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"NY\",\"2\":\"Male\",\"3\":\"1947\",\"4\":\"Robert\",\"5\":\"10026\"},{\"1\":\"NY\",\"2\":\"Male\",\"3\":\"1947\",\"4\":\"John\",\"5\":\"9639\"},{\"1\":\"NY\",\"2\":\"Male\",\"3\":\"1946\",\"4\":\"Robert\",\"5\":\"9295\"},{\"1\":\"NY\",\"2\":\"Male\",\"3\":\"1963\",\"4\":\"Michael\",\"5\":\"9241\"},{\"1\":\"NY\",\"2\":\"Male\",\"3\":\"1952\",\"4\":\"Robert\",\"5\":\"9219\"},{\"1\":\"NY\",\"2\":\"Male\",\"3\":\"1958\",\"4\":\"Michael\",\"5\":\"9215\"},{\"1\":\"NY\",\"2\":\"Male\",\"3\":\"1957\",\"4\":\"Michael\",\"5\":\"9115\"},{\"1\":\"NY\",\"2\":\"Male\",\"3\":\"1953\",\"4\":\"Robert\",\"5\":\"9060\"},{\"1\":\"NY\",\"2\":\"Male\",\"3\":\"1961\",\"4\":\"Michael\",\"5\":\"9054\"},{\"1\":\"NY\",\"2\":\"Male\",\"3\":\"1951\",\"4\":\"Robert\",\"5\":\"9053\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nThe name given to the most baby girls in one state is **Mary**. 8,184 babies were named Mary in Pennsylvania in 1918. It is interesting to note that almost all of the highest occurrences of female names in this data were the name Mary in Pennsylvania. Only Linda broke this trend in New York in 1947, where 7,542 babies were named Linda. These rest of the occurrences in the top ten were all Mary and all happened between 1915 and 1924, suggesting that this name held a particularly strong appeal during this time period in Pennsylvania. It's interesting to consider what kind of cultural forces were influencing parents in Pennsylvania in the 1910s and 1920s that led them to name their daughters such a traditional and biblical name.\n\nThe name given to the most baby boys in one state is Robert in New York in 1947, where 10,026 boys were named Robert. All of the highest occurrences of male names were in New York and were dominated by Robert and Michael. Only John broke through this list in the same year as the top Robert occurrence - in 1947 9,639 boys were named John in New York. The highest occurrences of male names all happened between 1946 and 1963. It's interesting to consider how the post-war culture would have brought about a consolidation of more traditional male names.\n\nLet's explore the names with the most occurrences across all states in a given year (question 1.b)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Most popular name across all states in a year, female and male\nPopF_Year <- BabyNames %>% \n  filter(Sex == \"Female\") %>%\n  group_by(Year, Name) %>% \n  summarize(\"Sum_Occurrences\" = sum(Occurrences)) %>% \n  arrange(desc(Sum_Occurrences))\nhead(PopF_Year, n = 10)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Year\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Name\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Sum_Occurrences\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"1947\",\"2\":\"Linda\",\"3\":\"99693\"},{\"1\":\"1948\",\"2\":\"Linda\",\"3\":\"96212\"},{\"1\":\"1949\",\"2\":\"Linda\",\"3\":\"91019\"},{\"1\":\"1950\",\"2\":\"Linda\",\"3\":\"80431\"},{\"1\":\"1921\",\"2\":\"Mary\",\"3\":\"73985\"},{\"1\":\"1951\",\"2\":\"Linda\",\"3\":\"73977\"},{\"1\":\"1924\",\"2\":\"Mary\",\"3\":\"73535\"},{\"1\":\"1922\",\"2\":\"Mary\",\"3\":\"72177\"},{\"1\":\"1947\",\"2\":\"Mary\",\"3\":\"71684\"},{\"1\":\"1923\",\"2\":\"Mary\",\"3\":\"71635\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nPopM_Year <- BabyNames %>% \n  filter(Sex == \"Male\") %>%\n  group_by(Year, Name) %>% \n  summarize(\"Sum_Occurrences\" = sum(Occurrences)) %>% \n  arrange(desc(Sum_Occurrences))\nhead(PopM_Year, n = 10)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Year\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Name\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Sum_Occurrences\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"1947\",\"2\":\"James\",\"3\":\"94762\"},{\"1\":\"1957\",\"2\":\"Michael\",\"3\":\"92723\"},{\"1\":\"1947\",\"2\":\"Robert\",\"3\":\"91651\"},{\"1\":\"1956\",\"2\":\"Michael\",\"3\":\"90715\"},{\"1\":\"1958\",\"2\":\"Michael\",\"3\":\"90574\"},{\"1\":\"1948\",\"2\":\"James\",\"3\":\"88595\"},{\"1\":\"1954\",\"2\":\"Michael\",\"3\":\"88570\"},{\"1\":\"1955\",\"2\":\"Michael\",\"3\":\"88353\"},{\"1\":\"1947\",\"2\":\"John\",\"3\":\"88321\"},{\"1\":\"1946\",\"2\":\"James\",\"3\":\"87440\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nUnsurprisingly, we see some of the same names populating these lists. For female names, the year with the most occurrences of the same named was Linda in 1947, with 99,693 occurrences. In the three years that followed Linda remained the highest occurring name. This undoubtedly is related to the baby boom, a time when people were having unprecedented numbers of babies and, apparently, naming conventions were not particularly diverse. After Linda, Mary populated half of the names with the most occurrences, primarily from the 1920s.\n\nAmong the male names, James had the highest number of occurrences in 1947. The male list is dominated by names James, Michael, Robert, and John, primarily from the late 1940s and 1950s. Again this data reflects the trend of baby boomers and the lack of diversity in their naming choices.\n\nFinally, let's look at the names that have been the most popular in the United States across all states and all time recorded here (question 1.c).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nPopF <- BabyNames %>% \n  filter(Sex == \"Female\") %>%\n  group_by(Name) %>% \n  summarize(\"Sum_Occurrences\" = sum(Occurrences)) %>% \n  arrange(desc(Sum_Occurrences))\nhead(PopF, n = 10)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Name\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Sum_Occurrences\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Mary\",\"2\":\"3747982\"},{\"1\":\"Patricia\",\"2\":\"1569661\"},{\"1\":\"Elizabeth\",\"2\":\"1560365\"},{\"1\":\"Jennifer\",\"2\":\"1468240\"},{\"1\":\"Linda\",\"2\":\"1448868\"},{\"1\":\"Barbara\",\"2\":\"1425056\"},{\"1\":\"Margaret\",\"2\":\"1137587\"},{\"1\":\"Susan\",\"2\":\"1109965\"},{\"1\":\"Dorothy\",\"2\":\"1055071\"},{\"1\":\"Jessica\",\"2\":\"1045846\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nPopM <- BabyNames %>% \n  filter(Sex == \"Male\") %>%\n  group_by(Name) %>% \n  summarize(\"Sum_Occurrences\" = sum(Occurrences)) %>% \n  arrange(desc(Sum_Occurrences))\nhead(PopM, n = 10)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Name\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Sum_Occurrences\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"James\",\"2\":\"5035762\"},{\"1\":\"John\",\"2\":\"4895305\"},{\"1\":\"Robert\",\"2\":\"4747986\"},{\"1\":\"Michael\",\"2\":\"4379257\"},{\"1\":\"William\",\"2\":\"3929698\"},{\"1\":\"David\",\"2\":\"3623306\"},{\"1\":\"Joseph\",\"2\":\"2548904\"},{\"1\":\"Richard\",\"2\":\"2545613\"},{\"1\":\"Charles\",\"2\":\"2291897\"},{\"1\":\"Thomas\",\"2\":\"2265071\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nThis shows us the most popular names in the United States across all years and states. Mary is the most popular female name, with 3,747,982 baby girls from 1910 until 2021 named Mary. This is followed by Patricia, Elizabeth, and Jennifer. Surprisingly, even though Linda was in our top ten lists of most occurrences in a year and in a year in a particular state, Linda is only the 5th most popular name of all female baby names. This indicates that While Linda was the most popular during specific times, it did not have the same long-lasting, enduring popularity of the names higher on the list.\n\nJames is the most popular male name, with 5,035,762 baby boys named James from 1910 to 2021. This is followed by John, Robert, and Michael. Given the popularity of these names in the previous two lists, it's unsurprising to see these male names high on this list again.\n\nFinally, let's turn to the last part of our first research question and look at the most popular names of each generation.\n\nFirst let's create a new `Generations` variable where we will indicate which generation a particular case is from based on the year. We'll use the years specified by the [Pew Research Center](https://www.pewresearch.org/politics/2015/09/03/the-whys-and-hows-of-generations-research/) to define each generation. See [here](https://www.pewresearch.org/fact-tank/2019/01/17/where-millennials-end-and-generation-z-begins/) for the definitions of Generation Z and Generation Alpha.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nBabyNames_gen <- BabyNames %>% \n  mutate(\"Generation\" = case_when(\n    Year <= 1927 ~ \"Greatest Generation\",\n    Year >= 1928 & Year <= 1945 ~ \"Silent Generation\",\n    Year >= 1946 & Year <= 1964 ~ \"Baby Boom Generation\", \n    Year >= 1965 & Year <= 1980 ~ \"Generation X\", \n    Year >= 1981 & Year <= 1996 ~ \"Millennial Generation\", \n    Year >= 1997 & Year <= 2012 ~ \"Generation Z\", \n    Year >= 2013 ~ \"Generation Alpha\"))\n\n# Then let's find the total number of occurrences for each generation\nBabyNames_gen %>% \n  group_by(Generation) %>% \n  summarize(sum_by_gen = sum(Occurrences)) %>% \n  arrange(sum_by_gen)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Generation\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"sum_by_gen\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Generation Alpha\",\"2\":\"26924856\"},{\"1\":\"Greatest Generation\",\"2\":\"30822648\"},{\"1\":\"Silent Generation\",\"2\":\"38662947\"},{\"1\":\"Generation X\",\"2\":\"48645635\"},{\"1\":\"Generation Z\",\"2\":\"52028854\"},{\"1\":\"Millennial Generation\",\"2\":\"52892473\"},{\"1\":\"Baby Boom Generation\",\"2\":\"69730746\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nNow that we have our variable all set, let's take a look at the top five names (of each sex) for each generation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Greatest generation\nGreatestGenF <- BabyNames_gen %>% \n  filter(Generation == \"Greatest Generation\" & Sex == \"Female\") %>% \n  group_by(Name) %>% \n  summarize(Total_Occurrences = sum(Occurrences)) %>% \n  arrange(desc(Total_Occurrences))\nhead(GreatestGenF, n = 5)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Name\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Total_Occurrences\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Mary\",\"2\":\"1050012\"},{\"1\":\"Dorothy\",\"2\":\"511121\"},{\"1\":\"Helen\",\"2\":\"494637\"},{\"1\":\"Margaret\",\"2\":\"394736\"},{\"1\":\"Ruth\",\"2\":\"358290\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nGreatestGenM <- BabyNames_gen %>% \n  filter(Generation == \"Greatest Generation\" & Sex == \"Male\") %>% \n  group_by(Name) %>% \n  summarize(Total_Occurrences = sum(Occurrences)) %>% \n  arrange(desc(Total_Occurrences))\nhead(GreatestGenM, n = 5)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Name\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Total_Occurrences\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"John\",\"2\":\"834505\"},{\"1\":\"William\",\"2\":\"718491\"},{\"1\":\"Robert\",\"2\":\"695042\"},{\"1\":\"James\",\"2\":\"685493\"},{\"1\":\"Charles\",\"2\":\"410375\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\n# Silent generation\nSilentGenF <- BabyNames_gen %>% \n  filter(Generation == \"Silent Generation\" & Sex == \"Female\") %>% \n  group_by(Name) %>% \n  summarize(Total_Occurrences = sum(Occurrences)) %>% \n  arrange(desc(Total_Occurrences))\nhead(SilentGenF, n = 5)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Name\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Total_Occurrences\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Mary\",\"2\":\"1068809\"},{\"1\":\"Barbara\",\"2\":\"569219\"},{\"1\":\"Betty\",\"2\":\"497526\"},{\"1\":\"Patricia\",\"2\":\"467886\"},{\"1\":\"Shirley\",\"2\":\"361009\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nSilentGenM <- BabyNames_gen %>% \n  filter(Generation == \"Silent Generation\" & Sex == \"Male\") %>% \n  group_by(Name) %>% \n  summarize(Total_Occurrences = sum(Occurrences)) %>% \n  arrange(desc(Total_Occurrences))\nhead(SilentGenM, n = 5)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Name\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Total_Occurrences\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Robert\",\"2\":\"1124232\"},{\"1\":\"James\",\"2\":\"1090419\"},{\"1\":\"John\",\"2\":\"973784\"},{\"1\":\"William\",\"2\":\"819592\"},{\"1\":\"Richard\",\"2\":\"646992\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\n# Baby Boomers\nBoomerGenF <- BabyNames_gen %>% \n  filter(Generation == \"Baby Boom Generation\" & Sex == \"Female\") %>% \n  group_by(Name) %>% \n  summarize(Total_Occurrences = sum(Occurrences)) %>% \n  arrange(desc(Total_Occurrences))\nhead(BoomerGenF, n = 5)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Name\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Total_Occurrences\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Mary\",\"2\":\"1125403\"},{\"1\":\"Linda\",\"2\":\"1059697\"},{\"1\":\"Patricia\",\"2\":\"788679\"},{\"1\":\"Susan\",\"2\":\"749661\"},{\"1\":\"Barbara\",\"2\":\"631916\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nBoomerGenM <- BabyNames_gen %>% \n  filter(Generation == \"Baby Boom Generation\" & Sex == \"Male\") %>% \n  group_by(Name) %>% \n  summarize(Total_Occurrences = sum(Occurrences)) %>% \n  arrange(desc(Total_Occurrences))\nhead(BoomerGenM, n = 5)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Name\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Total_Occurrences\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"James\",\"2\":\"1571003\"},{\"1\":\"Robert\",\"2\":\"1530921\"},{\"1\":\"John\",\"2\":\"1525027\"},{\"1\":\"Michael\",\"2\":\"1464194\"},{\"1\":\"David\",\"2\":\"1395837\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\n# Generation X\nGenXF <- BabyNames_gen %>% \n  filter(Generation == \"Generation X\" & Sex == \"Female\") %>% \n  group_by(Name) %>% \n  summarize(Total_Occurrences = sum(Occurrences)) %>% \n  arrange(desc(Total_Occurrences))\nhead(GenXF, n = 5)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Name\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Total_Occurrences\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Jennifer\",\"2\":\"752348\"},{\"1\":\"Lisa\",\"2\":\"508542\"},{\"1\":\"Michelle\",\"2\":\"410001\"},{\"1\":\"Kimberly\",\"2\":\"406766\"},{\"1\":\"Melissa\",\"2\":\"372866\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nGenXM <- BabyNames_gen %>% \n  filter(Generation == \"Generation X\" & Sex == \"Male\") %>% \n  group_by(Name) %>% \n  summarize(Total_Occurrences = sum(Occurrences)) %>% \n  arrange(desc(Total_Occurrences))\nhead(GenXM, n = 5)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Name\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Total_Occurrences\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Michael\",\"2\":\"1186900\"},{\"1\":\"David\",\"2\":\"816309\"},{\"1\":\"James\",\"2\":\"799373\"},{\"1\":\"John\",\"2\":\"755949\"},{\"1\":\"Robert\",\"2\":\"726983\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\n# Millennial generation\nMilGenF <- BabyNames_gen %>% \n  filter(Generation == \"Millennial Generation\" & Sex == \"Female\") %>% \n  group_by(Name) %>% \n  summarize(Total_Occurrences = sum(Occurrences)) %>% \n  arrange(desc(Total_Occurrences))\nhead(MilGenF, n = 5)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Name\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Total_Occurrences\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Jessica\",\"2\":\"683082\"},{\"1\":\"Ashley\",\"2\":\"587805\"},{\"1\":\"Jennifer\",\"2\":\"497404\"},{\"1\":\"Amanda\",\"2\":\"492119\"},{\"1\":\"Sarah\",\"2\":\"411541\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nMilGenM <- BabyNames_gen %>% \n  filter(Generation == \"Millennial Generation\" & Sex == \"Male\") %>% \n  group_by(Name) %>% \n  summarize(Total_Occurrences = sum(Occurrences)) %>% \n  arrange(desc(Total_Occurrences))\nhead(MilGenM, n = 5)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Name\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Total_Occurrences\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Michael\",\"2\":\"949446\"},{\"1\":\"Christopher\",\"2\":\"784404\"},{\"1\":\"Matthew\",\"2\":\"679765\"},{\"1\":\"Joshua\",\"2\":\"606081\"},{\"1\":\"David\",\"2\":\"532410\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\n# Generation Z\nGenZF <- BabyNames_gen %>% \n  filter(Generation == \"Generation Z\" & Sex == \"Female\") %>% \n  group_by(Name) %>% \n  summarize(Total_Occurrences = sum(Occurrences)) %>% \n  arrange(desc(Total_Occurrences))\nhead(GenZF, n = 5)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Name\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Total_Occurrences\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Emily\",\"2\":\"344384\"},{\"1\":\"Madison\",\"2\":\"281202\"},{\"1\":\"Emma\",\"2\":\"268397\"},{\"1\":\"Hannah\",\"2\":\"240236\"},{\"1\":\"Olivia\",\"2\":\"239053\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nGenZM <- BabyNames_gen %>% \n  filter(Generation == \"Generation Z\" & Sex == \"Male\") %>% \n  group_by(Name) %>% \n  summarize(Total_Occurrences = sum(Occurrences)) %>% \n  arrange(desc(Total_Occurrences))\nhead(GenZM, n = 5)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Name\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Total_Occurrences\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Jacob\",\"2\":\"441104\"},{\"1\":\"Michael\",\"2\":\"409079\"},{\"1\":\"Joshua\",\"2\":\"357524\"},{\"1\":\"Matthew\",\"2\":\"356940\"},{\"1\":\"Christopher\",\"2\":\"324255\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\n# Generation alpha\nGenALPHAF <- BabyNames_gen %>% \n  filter(Generation == \"Generation Alpha\" & Sex == \"Female\") %>% \n  group_by(Name) %>% \n  summarize(Total_Occurrences = sum(Occurrences)) %>% \n  arrange(desc(Total_Occurrences))\nhead(GenALPHAF, n = 5)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Name\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Total_Occurrences\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Emma\",\"2\":\"168800\"},{\"1\":\"Olivia\",\"2\":\"168043\"},{\"1\":\"Sophia\",\"2\":\"141660\"},{\"1\":\"Ava\",\"2\":\"135124\"},{\"1\":\"Isabella\",\"2\":\"131729\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nGenALPHAM <- BabyNames_gen %>% \n  filter(Generation == \"Generation Alpha\" & Sex == \"Male\") %>% \n  group_by(Name) %>% \n  summarize(Total_Occurrences = sum(Occurrences)) %>% \n  arrange(desc(Total_Occurrences))\nhead(GenALPHAM, n = 5)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Name\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Total_Occurrences\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Liam\",\"2\":\"172661\"},{\"1\":\"Noah\",\"2\":\"169482\"},{\"1\":\"William\",\"2\":\"133164\"},{\"1\":\"James\",\"2\":\"123588\"},{\"1\":\"Mason\",\"2\":\"123486\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nIt's interesting to note that you see variation within female names earlier and more than in the male names. Mary is the most popular name for the first three generations here - the Greatest, Silent, and Baby Boomer generation. It's not until Generation X that Mary drops off, and then it's not even in the top five at all. In fact, none of the top five female names of the Baby Boomer generation show up in the top five female names for Generation X, but the top five male names of the Baby Boomer generation are all again in the top five for Generation X, they are just in a different order. The male names in general do not vary as widely or as early as the female names. Even Generation Alpha, where we see some significant variation among the top names, includes James, the most popular male name of all time in this dataset.\n\n#### Data visualization of the top ranked names in each generation\n\nLet's take a look at the top 5 names for each generation and then graph them to see how they have fared over the years.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# First we'll create a new data frame with a variable that ranks names by the generation (as opposed to year, which is how we will be using the min_rank() function for research question #2)\nGeneration_rank <- BabyNames_gen %>% \n  group_by(Generation, Sex, Name) %>% \n  summarize(SumGen_Occurrences = sum(Occurrences)) %>% \n  mutate(Gen_Rank = min_rank(desc(SumGen_Occurrences)))\n\nTop5_Gen <- filter(Generation_rank, Gen_Rank <= 5) # filter to just the top five names for each generation.\n\nunique(Top5_Gen$Name) # see which names are the top 5 of their generation. We'll pull from this list to create the vector that we will graph below.\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"Barbara\"     \"Linda\"       \"Mary\"        \"Patricia\"    \"Susan\"      \n [6] \"David\"       \"James\"       \"John\"        \"Michael\"     \"Robert\"     \n[11] \"Ava\"         \"Emma\"        \"Isabella\"    \"Olivia\"      \"Sophia\"     \n[16] \"Liam\"        \"Mason\"       \"Noah\"        \"William\"     \"Jennifer\"   \n[21] \"Kimberly\"    \"Lisa\"        \"Melissa\"     \"Michelle\"    \"Emily\"      \n[26] \"Hannah\"      \"Madison\"     \"Christopher\" \"Jacob\"       \"Joshua\"     \n[31] \"Matthew\"     \"Dorothy\"     \"Helen\"       \"Margaret\"    \"Ruth\"       \n[36] \"Charles\"     \"Amanda\"      \"Ashley\"      \"Jessica\"     \"Sarah\"      \n[41] \"Betty\"       \"Shirley\"     \"Richard\"    \n```\n:::\n\n```{.r .cell-code}\nTop5_Gen_graphF <- BabyNames %>%\n  filter(Name %in% c(\"Barbara\", \"Linda\", \"Mary\", \"Patricia\", \"Susan\", \"Ava\", \n                     \"Emma\", \"Isabella\", \"Olivia\", \"Sophia\", \"Jennifer\", \n                     \"Kimberly\", \"Lisa\", \"Melissa\", \"Michelle\", \"Emily\", \n                     \"Hannah\", \"Madison\", \"Dorothy\", \"Helen\",  \"Margaret\", \n                     \"Ruth\", \"Amanda\", \"Ashley\", \"Jessica\", \"Sarah\", \"Betty\", \n                     \"Shirley\")) %>%\n  group_by(Year, Name) %>% \n  summarize(\"sum\" = sum(Occurrences)) %>% \n  ggplot(aes(Year, sum, group = Name, color = Name)) + geom_line() +\n  labs(title = \"Top 5 Female Names of Each Generation\", x = \"Year\", y = \"Total Occurrences\")\nTop5_Gen_graphF\n```\n\n::: {.cell-output-display}\n![](JustineShakespeare_FinalProject_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n\n```{.r .cell-code}\nTop5_Gen_graphM <- BabyNames %>%\n  filter(Name %in% c(\"David\", \"James\", \"John\", \"Michael\", \"Robert\", \"Liam\", \n                     \"Mason\", \"Noah\", \"William\", \"Christopher\", \"Jacob\", \n                     \"Joshua\", \"Matthew\", \"Charles\", \"Richard\")) %>%\n  group_by(Year, Name) %>% \n  summarize(\"sum\" = sum(Occurrences)) %>% \n  ggplot(aes(Year, sum, group = Name, color = Name)) + geom_line() +\n  labs(title = \"Top 5 Male Names of Each Generation\", x = \"Year\", y = \"Total Occurrences\")\nTop5_Gen_graphM\n```\n\n::: {.cell-output-display}\n![](JustineShakespeare_FinalProject_files/figure-html/unnamed-chunk-13-2.png){width=672}\n:::\n:::\n\n\nBecause there are names that are in the top five of several different generations, each line here represents a distinct name and I did not group them by generation. You can see the pattern noted above in the graphs here: There are more total female names than male names and female names generally tend to rise and fall in popularity faster than male names, which remain steadily popular for long periods of time.\n\nAnother interesting thing to note in these graphs is that for both female and male names, the names that are highly ranked in more recent years have much shorter peaks. This will be explored further in research question #2.\n\n## Research Question 2\n\nThis question has two parts.\n\n*a. Has there been a change over time in the proportion of babies who are named the most popular names?*\n\n*b. Specifically, is the name Oliver as popular now in the 2020s, as Chris was in the 1980s?*\n\nIn order to explore our research question, let's create two additional variables.\n\nThe first will represent the rank of a name in a given year (separated by sex). We'll call that new variable \"Year_Rank\".\n\nThe second variable will represent the proportion of babies that have each name in a given year (separated by sex). We'll call that variable \"Proportion\".\n\n##### Creating the Year_Rank variable\n\nCreating these variables will involve several steps. We'll start by creating the Year_Rank variable by creating a new dataframe with a new variable \"Sum_Occurrences\" the sums the total occurrences for a name in a given year by sex.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Creates two new variables, Sum_Occurrences and Year_Rank. \nBabyNames_rank <- BabyNames %>% \n  group_by(Year, Sex, Name) %>% \n  summarize(\"Sum_Occurrences\" = sum(Occurrences)) %>% \n  mutate(Year_Rank = min_rank(desc(Sum_Occurrences)))\n\nhead(BabyNames_rank)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Year\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Sex\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Name\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Sum_Occurrences\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Year_Rank\"],\"name\":[5],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"1910\",\"2\":\"Female\",\"3\":\"Abbie\",\"4\":\"28\",\"5\":\"524\"},{\"1\":\"1910\",\"2\":\"Female\",\"3\":\"Ada\",\"4\":\"937\",\"5\":\"94\"},{\"1\":\"1910\",\"2\":\"Female\",\"3\":\"Adah\",\"4\":\"5\",\"5\":\"926\"},{\"1\":\"1910\",\"2\":\"Female\",\"3\":\"Adaline\",\"4\":\"7\",\"5\":\"819\"},{\"1\":\"1910\",\"2\":\"Female\",\"3\":\"Addie\",\"4\":\"448\",\"5\":\"157\"},{\"1\":\"1910\",\"2\":\"Female\",\"3\":\"Adela\",\"4\":\"22\",\"5\":\"566\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\n## WHAT KIND OF SANITY CHECK COULD I DO FOR THIS ?\n```\n:::\n\n\n##### Creating the Proportion variable\n\nIn order to come up with the Proportion variable, we'll need to do some additional transformation of the data. The Proportion variable is essentially the total occurrences of a name in a given year divided by the total occurrences of all names in that year. In order to get the total occurrences in a given year, we'll use the summarize function to create a new data frame and join it back to the original dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# This gives you the total occurrences of names in a given year. This data frame \n# is 224 observations because there are 112 years in this dataset and there are \n# two sexes for each year. \nBabyNames_year <- BabyNames %>% \n  group_by(Year, Sex) %>% \n  summarize(\"Total_names_p_year\" = sum(Occurrences))\n\nglimpse(BabyNames_year)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 224\nColumns: 3\nGroups: Year [112]\n$ Year               <dbl> 1910, 1910, 1911, 1911, 1912, 1912, 1913, 1913, 191…\n$ Sex                <chr> \"Female\", \"Male\", \"Female\", \"Male\", \"Female\", \"Male…\n$ Total_names_p_year <dbl> 352089, 164223, 372382, 193441, 504299, 383704, 566…\n```\n:::\n:::\n\n\nNext we'll use `pivot_wider()` to make it so that the values in the Sex variable are now variables themselves (Female and Male) with the total occurrences as the value.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nBabyNames_pw <- BabyNames_year %>% \n  pivot_wider(names_from = Sex, values_from = Total_names_p_year)\n\nhead(BabyNames_pw)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Year\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Female\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Male\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"1910\",\"2\":\"352089\",\"3\":\"164223\"},{\"1\":\"1911\",\"2\":\"372382\",\"3\":\"193441\"},{\"1\":\"1912\",\"2\":\"504299\",\"3\":\"383704\"},{\"1\":\"1913\",\"2\":\"566973\",\"3\":\"461606\"},{\"1\":\"1914\",\"2\":\"696907\",\"3\":\"596441\"},{\"1\":\"1915\",\"2\":\"908538\",\"3\":\"781455\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nglimpse(BabyNames_pw)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 112\nColumns: 3\nGroups: Year [112]\n$ Year   <dbl> 1910, 1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 192…\n$ Female <dbl> 352089, 372382, 504299, 566973, 696907, 908538, 965991, 1000424…\n$ Male   <dbl> 164223, 193441, 383704, 461606, 596441, 781455, 820519, 855249,…\n```\n:::\n:::\n\n\nNext we'll make a Proportion variable by dividing the total occurrences of a name in a given year by the total occurrences of *all* names in that year. We'll need to start by splitting both of the new data frames we just created by sex and then joining those data frames so that we have two data frames - one for male names and one for female names - that have the rank variable and the total names in a year variable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# first we need to separate the BabyNames_year data (which includes a new variable with the total occurrences of all names in a given year) by sex\nfemales_year <- select(BabyNames_pw, Year, \"Female_Total\" = Female)\nhead(females_year)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Year\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Female_Total\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"1910\",\"2\":\"352089\"},{\"1\":\"1911\",\"2\":\"372382\"},{\"1\":\"1912\",\"2\":\"504299\"},{\"1\":\"1913\",\"2\":\"566973\"},{\"1\":\"1914\",\"2\":\"696907\"},{\"1\":\"1915\",\"2\":\"908538\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nmales_year <- select(BabyNames_pw, Year, \"Male_Total\" = Male)\nhead(males_year)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Year\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Male_Total\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"1910\",\"2\":\"164223\"},{\"1\":\"1911\",\"2\":\"193441\"},{\"1\":\"1912\",\"2\":\"383704\"},{\"1\":\"1913\",\"2\":\"461606\"},{\"1\":\"1914\",\"2\":\"596441\"},{\"1\":\"1915\",\"2\":\"781455\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\n# then we need to separate the BabyNames_rank (which includes a new variable that ranks each name in a given year by occurrences) by sex\nfemales_rank <- BabyNames_rank %>% \n  filter(Sex == \"Female\")\nhead(females_rank)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Year\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Sex\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Name\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Sum_Occurrences\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Year_Rank\"],\"name\":[5],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"1910\",\"2\":\"Female\",\"3\":\"Abbie\",\"4\":\"28\",\"5\":\"524\"},{\"1\":\"1910\",\"2\":\"Female\",\"3\":\"Ada\",\"4\":\"937\",\"5\":\"94\"},{\"1\":\"1910\",\"2\":\"Female\",\"3\":\"Adah\",\"4\":\"5\",\"5\":\"926\"},{\"1\":\"1910\",\"2\":\"Female\",\"3\":\"Adaline\",\"4\":\"7\",\"5\":\"819\"},{\"1\":\"1910\",\"2\":\"Female\",\"3\":\"Addie\",\"4\":\"448\",\"5\":\"157\"},{\"1\":\"1910\",\"2\":\"Female\",\"3\":\"Adela\",\"4\":\"22\",\"5\":\"566\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nmales_rank <- BabyNames_rank %>% \n  filter(Sex == \"Male\")\nhead(males_rank)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Year\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Sex\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Name\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Sum_Occurrences\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Year_Rank\"],\"name\":[5],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"1910\",\"2\":\"Male\",\"3\":\"Aaron\",\"4\":\"111\",\"5\":\"185\"},{\"1\":\"1910\",\"2\":\"Male\",\"3\":\"Abe\",\"4\":\"31\",\"5\":\"311\"},{\"1\":\"1910\",\"2\":\"Male\",\"3\":\"Abner\",\"4\":\"12\",\"5\":\"440\"},{\"1\":\"1910\",\"2\":\"Male\",\"3\":\"Abraham\",\"4\":\"138\",\"5\":\"170\"},{\"1\":\"1910\",\"2\":\"Male\",\"3\":\"Abram\",\"4\":\"10\",\"5\":\"482\"},{\"1\":\"1910\",\"2\":\"Male\",\"3\":\"Adam\",\"4\":\"123\",\"5\":\"175\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\n# Then we join the datasets so that we have total occurences by year and sex for each name\nBabyNames_joinf <- full_join(females_rank, females_year, by = \"Year\")\nhead(BabyNames_joinf)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Year\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Sex\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Name\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Sum_Occurrences\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Year_Rank\"],\"name\":[5],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Female_Total\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"1910\",\"2\":\"Female\",\"3\":\"Abbie\",\"4\":\"28\",\"5\":\"524\",\"6\":\"352089\"},{\"1\":\"1910\",\"2\":\"Female\",\"3\":\"Ada\",\"4\":\"937\",\"5\":\"94\",\"6\":\"352089\"},{\"1\":\"1910\",\"2\":\"Female\",\"3\":\"Adah\",\"4\":\"5\",\"5\":\"926\",\"6\":\"352089\"},{\"1\":\"1910\",\"2\":\"Female\",\"3\":\"Adaline\",\"4\":\"7\",\"5\":\"819\",\"6\":\"352089\"},{\"1\":\"1910\",\"2\":\"Female\",\"3\":\"Addie\",\"4\":\"448\",\"5\":\"157\",\"6\":\"352089\"},{\"1\":\"1910\",\"2\":\"Female\",\"3\":\"Adela\",\"4\":\"22\",\"5\":\"566\",\"6\":\"352089\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nBabyNames_joinm <- full_join(males_rank, males_year, by = \"Year\")\nhead(BabyNames_joinm)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Year\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Sex\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Name\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Sum_Occurrences\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Year_Rank\"],\"name\":[5],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Male_Total\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"1910\",\"2\":\"Male\",\"3\":\"Aaron\",\"4\":\"111\",\"5\":\"185\",\"6\":\"164223\"},{\"1\":\"1910\",\"2\":\"Male\",\"3\":\"Abe\",\"4\":\"31\",\"5\":\"311\",\"6\":\"164223\"},{\"1\":\"1910\",\"2\":\"Male\",\"3\":\"Abner\",\"4\":\"12\",\"5\":\"440\",\"6\":\"164223\"},{\"1\":\"1910\",\"2\":\"Male\",\"3\":\"Abraham\",\"4\":\"138\",\"5\":\"170\",\"6\":\"164223\"},{\"1\":\"1910\",\"2\":\"Male\",\"3\":\"Abram\",\"4\":\"10\",\"5\":\"482\",\"6\":\"164223\"},{\"1\":\"1910\",\"2\":\"Male\",\"3\":\"Adam\",\"4\":\"123\",\"5\":\"175\",\"6\":\"164223\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\n# Create the proportion variables for the female and male data frames by dividing the sum of occurrences for each name by the total occurrences for that year\nBabyNames_F <- BabyNames_joinf %>% \n  select(Year, Name, Sum_Occurrences, Year_Rank, Female_Total) %>% \n  mutate(\"Proportion\" = Sum_Occurrences/Female_Total)\nhead(BabyNames_F)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Sex\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Year\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Name\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Sum_Occurrences\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Year_Rank\"],\"name\":[5],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Female_Total\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Proportion\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Female\",\"2\":\"1910\",\"3\":\"Abbie\",\"4\":\"28\",\"5\":\"524\",\"6\":\"352089\",\"7\":\"7.952535e-05\"},{\"1\":\"Female\",\"2\":\"1910\",\"3\":\"Ada\",\"4\":\"937\",\"5\":\"94\",\"6\":\"352089\",\"7\":\"2.661259e-03\"},{\"1\":\"Female\",\"2\":\"1910\",\"3\":\"Adah\",\"4\":\"5\",\"5\":\"926\",\"6\":\"352089\",\"7\":\"1.420095e-05\"},{\"1\":\"Female\",\"2\":\"1910\",\"3\":\"Adaline\",\"4\":\"7\",\"5\":\"819\",\"6\":\"352089\",\"7\":\"1.988134e-05\"},{\"1\":\"Female\",\"2\":\"1910\",\"3\":\"Addie\",\"4\":\"448\",\"5\":\"157\",\"6\":\"352089\",\"7\":\"1.272406e-03\"},{\"1\":\"Female\",\"2\":\"1910\",\"3\":\"Adela\",\"4\":\"22\",\"5\":\"566\",\"6\":\"352089\",\"7\":\"6.248420e-05\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nBabyNames_M <- BabyNames_joinm %>% \n  select(Year, Name, Sum_Occurrences, Year_Rank, Male_Total) %>% \n  mutate(\"Proportion\" = Sum_Occurrences/Male_Total)\nhead(BabyNames_M)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Sex\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Year\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Name\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Sum_Occurrences\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Year_Rank\"],\"name\":[5],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Male_Total\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Proportion\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Male\",\"2\":\"1910\",\"3\":\"Aaron\",\"4\":\"111\",\"5\":\"185\",\"6\":\"164223\",\"7\":\"6.759102e-04\"},{\"1\":\"Male\",\"2\":\"1910\",\"3\":\"Abe\",\"4\":\"31\",\"5\":\"311\",\"6\":\"164223\",\"7\":\"1.887677e-04\"},{\"1\":\"Male\",\"2\":\"1910\",\"3\":\"Abner\",\"4\":\"12\",\"5\":\"440\",\"6\":\"164223\",\"7\":\"7.307137e-05\"},{\"1\":\"Male\",\"2\":\"1910\",\"3\":\"Abraham\",\"4\":\"138\",\"5\":\"170\",\"6\":\"164223\",\"7\":\"8.403208e-04\"},{\"1\":\"Male\",\"2\":\"1910\",\"3\":\"Abram\",\"4\":\"10\",\"5\":\"482\",\"6\":\"164223\",\"7\":\"6.089281e-05\"},{\"1\":\"Male\",\"2\":\"1910\",\"3\":\"Adam\",\"4\":\"123\",\"5\":\"175\",\"6\":\"164223\",\"7\":\"7.489816e-04\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n#### Data visualization of the top ranked names\n\nI expect to iterate on this, but this is the first visualization that should get at research question #2: Has there been a change over time in the proportion of babies who are named the top ranking names?\n\nThis graph shows the top three ranked names and the proportion of babies with that name. Note that each line does not represent a specific name, but rather one of the top 3 ranked names for the given year.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolor_m_prop <- c(\"cyan4\", \"blue2\", \"deepskyblue\")\n\nBabyNames_M %>% \n  filter(Year_Rank <= 3) %>% \n  ggplot(aes(Year, Proportion, group = as.factor(Year_Rank), \n             colour = as.factor(Year_Rank))) +  \n  geom_line() +\n  scale_color_manual(values = color_m_prop) +\n  labs(title = \"Proportion of top three names each year\", \n       subtitle = \"In recent years, most popular names are a much smaller \n       proportion than the most popular names earlier in the 20th century\", \n       color = \"Name rank\")\n```\n\n::: {.cell-output-display}\n![](JustineShakespeare_FinalProject_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\nIs there a way to label some of the names on this graph? Is that possible even though the lines are from the variable \"Year_Rank\" and not \"Name\"? Ideally I'd like to display the Name value in some key spots on the graph.\n\n## Data Discrepancy\n\nAfter separating the data by sex and calculating the total occurrences of all names in a year, I noticed that there seems to be an especially large difference between the number of female and male baby names for each year. Since the occurrences count the total number of *babies* named and *not* the total number of distinct names, it seems odd that there would be such a large gap between the sexes.\n\nTo get a sense of the magnitude of this discrepancy I made a new variable that calculated the difference between the number of male baby names and female baby names each year and graphed it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create the new variable, difference, which calculates the difference between \n# the female and male total occurrences per year \ndifference <- BabyNames_pw %>% \n  mutate(\"Difference\" = Female - Male) %>% \n  mutate(\"Sex_Count_Comparison\" = case_when(\n    Difference > 0 ~ \"More female\",\n    Difference < 0 ~ \"More male\"))\n\nhead(difference)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Year\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Female\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Male\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Difference\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Sex_Count_Comparison\"],\"name\":[5],\"type\":[\"chr\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"1910\",\"2\":\"352089\",\"3\":\"164223\",\"4\":\"187866\",\"5\":\"More female\"},{\"1\":\"1911\",\"2\":\"372382\",\"3\":\"193441\",\"4\":\"178941\",\"5\":\"More female\"},{\"1\":\"1912\",\"2\":\"504299\",\"3\":\"383704\",\"4\":\"120595\",\"5\":\"More female\"},{\"1\":\"1913\",\"2\":\"566973\",\"3\":\"461606\",\"4\":\"105367\",\"5\":\"More female\"},{\"1\":\"1914\",\"2\":\"696907\",\"3\":\"596441\",\"4\":\"100466\",\"5\":\"More female\"},{\"1\":\"1915\",\"2\":\"908538\",\"3\":\"781455\",\"4\":\"127083\",\"5\":\"More female\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\ncolors <- c(\"darkturquoise\", \"darkorchid2\")  \n\n# graph it\ndifference %>% \n  ggplot(aes(Year, Difference, fill=Sex_Count_Comparison)) + \n  geom_col() + \n  scale_fill_manual(name = \"Count comparison\", values = colors) +\n  scale_y_continuous(labels = function(x) { paste0(x / 1000, \"k\")}) + \n  labs(title = \"Difference in female and male baby name occurences by year\", \n       subtitle = \"Note this is a count of occurences of names, not number of distinct \n       names. So this should reflect the population of babies born...??\", )\n```\n\n::: {.cell-output-display}\n![](JustineShakespeare_FinalProject_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\nThis is very strange - it seems unlikely that there were around 250,000 more boys born in the early 2000s and no one talked about it! Is this discrepancy related to some kind of limitations of the data? Could it possibly be evidence of an error I've made in my analysis and transformation so far?\n\n## Research Question 3\n\n*Is there a cyclical nature to the popularity of some names? Are there some names that were popular in the early part of the 20th century that have regained popularity?*\n\n## Research Question 4\n\n*Are there certain states that could be considered trendsetters - did popular names become popular in certain states first?*\n\n\n:::\n",
    "supporting": [
      "JustineShakespeare_FinalProject_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}