{
  "hash": "9881271e35d212197d92ff58eb1a45e1",
  "result": {
    "markdown": "---\ntitle: \"Challenge 2\"\nauthor: \"FNU Avinesh Krishnan\"\ndescription: \"Data wrangling: using group() and summarise()\"\ndate: \"05/15/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_2\n  - FNU Avinesh Krishnan\n  - FAOSTAT_livestock\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Challenge Overview\n\nToday's challenge is to\n\n1)  read in a data set, and describe the data using both words and any supporting information (e.g., tables, etc)\n2)  provide summary statistics for different interesting groups within the data, and interpret those statistics\n\n## Read in the Data\n\nRead in one (or more) of the following data sets, available in the `posts/_data` folder, using the correct R package and command.\n\n-   railroad\\*.csv or StateCounty2012.xls ⭐\n-   FAOstat\\*.csv or birds.csv ⭐⭐⭐\n-   hotel_bookings.csv ⭐⭐⭐⭐\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlivestockdata <-read_csv(\"~/Desktop/601_Spring_2023/posts/_data/FAOSTAT_livestock.csv\")\nview(livestockdata)\n```\n:::\n\n\nAdd any comments or documentation as needed. More challenging data may require additional code chunks and documentation.\n\n## Describe the data\n\nUsing a combination of words and results of R commands, can you provide a high level description of the data? Describe as efficiently as possible where/how the data was (likely) gathered, indicate the cases and variables (both the interpretation and any details you deem useful to the reader to fully understand your chosen data).\n\nThe dataset consists of information related to live animals in different countries. It includes the following cases and variables:\n\nEach row represents a specific case, providing details about live animal stocks in a particular country for a specific year.\nVariables:\nDomain Code: Code representing the domain of the data (e.g., QA for live animals).\nDomain: Domain of the data (e.g., Live Animals).\nArea Code: Code representing the specific area or country (e.g., 2 for Afghanistan).\nArea: Name of the area or country (e.g., Afghanistan).\nElement Code: Code representing the element of the data (e.g., 5111 for stocks).\nElement: Description of the element (e.g., Stocks).\nItem Code: Code representing the specific item or category (e.g., 1107 for asses).\nItem: Description of the item (e.g., Asses).\nYear Code: Code representing the year of the data (e.g., 1961).\nYear: Year of the data (e.g., 1961).\nUnit: Unit of measurement (e.g., Head).\nValue: Numeric value representing the quantity of live animals.\nFlag: Flag indicating additional information or data status (e.g., NA for missing data).\nFlag Description: Description of the flag (e.g., Official data or FAO estimate).\nThe data appears to be gathered from official sources, likely collected by the Food and Agriculture Organization (FAO) or a related organization. It provides insights into the stock levels of various live animals in different countries over multiple years.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(livestockdata)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 14\n  Domai…¹ Domain Area …² Area  Eleme…³ Element Item …⁴ Item  Year …⁵  Year Unit \n  <chr>   <chr>    <dbl> <chr>   <dbl> <chr>     <dbl> <chr>   <dbl> <dbl> <chr>\n1 QA      Live …       2 Afgh…    5111 Stocks     1107 Asses    1961  1961 Head \n2 QA      Live …       2 Afgh…    5111 Stocks     1107 Asses    1962  1962 Head \n3 QA      Live …       2 Afgh…    5111 Stocks     1107 Asses    1963  1963 Head \n4 QA      Live …       2 Afgh…    5111 Stocks     1107 Asses    1964  1964 Head \n5 QA      Live …       2 Afgh…    5111 Stocks     1107 Asses    1965  1965 Head \n6 QA      Live …       2 Afgh…    5111 Stocks     1107 Asses    1966  1966 Head \n# … with 3 more variables: Value <dbl>, Flag <chr>, `Flag Description` <chr>,\n#   and abbreviated variable names ¹​`Domain Code`, ²​`Area Code`,\n#   ³​`Element Code`, ⁴​`Item Code`, ⁵​`Year Code`\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(livestockdata)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nspc_tbl_ [82,116 × 14] (S3: spec_tbl_df/tbl_df/tbl/data.frame)\n $ Domain Code     : chr [1:82116] \"QA\" \"QA\" \"QA\" \"QA\" ...\n $ Domain          : chr [1:82116] \"Live Animals\" \"Live Animals\" \"Live Animals\" \"Live Animals\" ...\n $ Area Code       : num [1:82116] 2 2 2 2 2 2 2 2 2 2 ...\n $ Area            : chr [1:82116] \"Afghanistan\" \"Afghanistan\" \"Afghanistan\" \"Afghanistan\" ...\n $ Element Code    : num [1:82116] 5111 5111 5111 5111 5111 ...\n $ Element         : chr [1:82116] \"Stocks\" \"Stocks\" \"Stocks\" \"Stocks\" ...\n $ Item Code       : num [1:82116] 1107 1107 1107 1107 1107 ...\n $ Item            : chr [1:82116] \"Asses\" \"Asses\" \"Asses\" \"Asses\" ...\n $ Year Code       : num [1:82116] 1961 1962 1963 1964 1965 ...\n $ Year            : num [1:82116] 1961 1962 1963 1964 1965 ...\n $ Unit            : chr [1:82116] \"Head\" \"Head\" \"Head\" \"Head\" ...\n $ Value           : num [1:82116] 1300000 851850 1001112 1150000 1300000 ...\n $ Flag            : chr [1:82116] NA NA NA \"F\" ...\n $ Flag Description: chr [1:82116] \"Official data\" \"Official data\" \"Official data\" \"FAO estimate\" ...\n - attr(*, \"spec\")=\n  .. cols(\n  ..   `Domain Code` = col_character(),\n  ..   Domain = col_character(),\n  ..   `Area Code` = col_double(),\n  ..   Area = col_character(),\n  ..   `Element Code` = col_double(),\n  ..   Element = col_character(),\n  ..   `Item Code` = col_double(),\n  ..   Item = col_character(),\n  ..   `Year Code` = col_double(),\n  ..   Year = col_double(),\n  ..   Unit = col_character(),\n  ..   Value = col_double(),\n  ..   Flag = col_character(),\n  ..   `Flag Description` = col_character()\n  .. )\n - attr(*, \"problems\")=<externalptr> \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncolnames(livestockdata)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"Domain Code\"      \"Domain\"           \"Area Code\"        \"Area\"            \n [5] \"Element Code\"     \"Element\"          \"Item Code\"        \"Item\"            \n [9] \"Year Code\"        \"Year\"             \"Unit\"             \"Value\"           \n[13] \"Flag\"             \"Flag Description\"\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n livestockdata%>%\n  select(\"Domain\") %>%\n  distinct(.)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 1\n  Domain      \n  <chr>       \n1 Live Animals\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n livestockdata%>%\n  select(\"Element Code\") %>%\n  distinct(.)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 1\n  `Element Code`\n           <dbl>\n1           5111\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(livestockdata)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 82116    14\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmin(livestockdata$Year)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1961\n```\n:::\n\n```{.r .cell-code}\nmax(livestockdata$Year)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2018\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmin(livestockdata$`Area Code`)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1\n```\n:::\n\n```{.r .cell-code}\nmax(livestockdata$`Area Code`)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 5504\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(livestockdata)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Domain Code           Domain            Area Code          Area          \n Length:82116       Length:82116       Min.   :   1.0   Length:82116      \n Class :character   Class :character   1st Qu.:  73.0   Class :character  \n Mode  :character   Mode  :character   Median : 146.0   Mode  :character  \n                                       Mean   : 912.7                     \n                                       3rd Qu.: 221.0                     \n                                       Max.   :5504.0                     \n                                                                          \n  Element Code    Element            Item Code        Item          \n Min.   :5111   Length:82116       Min.   : 866   Length:82116      \n 1st Qu.:5111   Class :character   1st Qu.: 976   Class :character  \n Median :5111   Mode  :character   Median :1034   Mode  :character  \n Mean   :5111                      Mean   :1018                     \n 3rd Qu.:5111                      3rd Qu.:1096                     \n Max.   :5111                      Max.   :1126                     \n                                                                    \n   Year Code         Year          Unit               Value          \n Min.   :1961   Min.   :1961   Length:82116       Min.   :0.000e+00  \n 1st Qu.:1976   1st Qu.:1976   Class :character   1st Qu.:1.250e+04  \n Median :1991   Median :1991   Mode  :character   Median :2.247e+05  \n Mean   :1990   Mean   :1990                      Mean   :1.163e+07  \n 3rd Qu.:2005   3rd Qu.:2005                      3rd Qu.:2.377e+06  \n Max.   :2018   Max.   :2018                      Max.   :1.490e+09  \n                                                  NA's   :1301       \n     Flag           Flag Description  \n Length:82116       Length:82116      \n Class :character   Class :character  \n Mode  :character   Mode  :character  \n                                      \n                                      \n                                      \n                                      \n```\n:::\n:::\n\n\n\n\n## Provide Grouped Summary Statistics\n\nConduct some exploratory data analysis, using dplyr commands such as `group_by()`, `select()`, `filter()`, and `summarise()`. Find the central tendency (mean, median, mode) and dispersion (standard deviation, mix/max/quantile) for different subgroups within the data set.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlivestockdata %>% \n  group_by(Area) %>% \n  summarise(averge_value = mean(Value), Max_value=max(Value), Min_value=min(Value))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 253 × 4\n   Area                averge_value Max_value Min_value\n   <chr>                      <dbl>     <dbl>     <dbl>\n 1 Afghanistan             3597216.  21500000     20000\n 2 Africa                 78159910. 438110974    706338\n 3 Albania                      NA         NA        NA\n 4 Algeria                 2575444.  28693330      2000\n 5 American Samoa             5399.     14600        88\n 6 Americas               95795716. 522867113     66000\n 7 Angola                  1123117.   5044019       800\n 8 Antigua and Barbuda        7877.     36000       400\n 9 Argentina              12879607.  61053808     85198\n10 Armenia                  167587.   1000000        25\n# … with 243 more rows\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlivestockdata %>% \n  filter(Area == \"Africa\" | Area == \"Afghanistan\",Item == \"Camels\", Year == 1961)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 14\n  Domai…¹ Domain Area …² Area  Eleme…³ Element Item …⁴ Item  Year …⁵  Year Unit \n  <chr>   <chr>    <dbl> <chr>   <dbl> <chr>     <dbl> <chr>   <dbl> <dbl> <chr>\n1 QA      Live …       2 Afgh…    5111 Stocks     1126 Came…    1961  1961 Head \n2 QA      Live …    5100 Afri…    5111 Stocks     1126 Came…    1961  1961 Head \n# … with 3 more variables: Value <dbl>, Flag <chr>, `Flag Description` <chr>,\n#   and abbreviated variable names ¹​`Domain Code`, ²​`Area Code`,\n#   ³​`Element Code`, ⁴​`Item Code`, ⁵​`Year Code`\n```\n:::\n:::\n\n\nThere are two data points available for the above filter i.e for two areas.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSummary_Year <- na.omit(livestockdata) %>%\n  group_by(Year) %>%\n  summarize(\n    mean_Value = mean(Value, na.rm = TRUE),\n    median_Value = median(Value, na.rm = TRUE),\n    min_Value = min(Value, na.rm = TRUE),\n    max_Value = max(Value, na.rm = TRUE),\n    sd_Value = sd(Value, na.rm = TRUE),\n    var_Value = var(Value, na.rm = TRUE),\n    IQR_Value = IQR(Value, na.rm = TRUE)\n  )\nSummary_Year\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 58 × 8\n    Year mean_Value median_Value min_Value  max_Value  sd_Value var_Va…¹ IQR_V…²\n   <dbl>      <dbl>        <dbl>     <dbl>      <dbl>     <dbl>    <dbl>   <dbl>\n 1  1961  14080955.      129000         10  994268736 66803024.  4.46e15  2.14e6\n 2  1962  14085663.      130000         10  997193122 66008462.  4.36e15  2.01e6\n 3  1963  14568714.      154000         10  999696719 67268611.  4.53e15  2.49e6\n 4  1964  15101322.      160000         10 1013486149 68974136.  4.76e15  2.61e6\n 5  1965  15558689.      140000         10 1030878735 70820667.  5.02e15  2.75e6\n 6  1966  15481029.      155000         10 1040688491 72204592.  5.21e15  2.42e6\n 7  1967  15804831.      148000         10 1059154631 72456707.  5.25e15  2.54e6\n 8  1968  15526705.      105850         10 1074022618 72343610.  5.23e15  2.25e6\n 9  1969  15203756.      116412.        12 1080720926 71629580.  5.13e15  2.15e6\n10  1970  15475993.      103000         12 1081641464 72217288.  5.22e15  2.24e6\n# … with 48 more rows, and abbreviated variable names ¹​var_Value, ²​IQR_Value\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nSummary_Area <- na.omit(livestockdata) %>%\n  group_by(Area) %>%\n  summarize(\n    mean_Value = mean(Value, na.rm = TRUE),\n    median_Value = median(Value, na.rm = TRUE),\n    min_Value = min(Value, na.rm = TRUE),\n    max_Value = max(Value, na.rm = TRUE),\n    sd_Value = sd(Value, na.rm = TRUE),\n    var_Value = var(Value, na.rm = TRUE),\n    IQR_Value = IQR(Value, na.rm = TRUE)\n  )\nSummary_Area\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 240 × 8\n   Area                mean_Va…¹ media…² min_V…³ max_V…⁴ sd_Va…⁵ var_V…⁶ IQR_V…⁷\n   <chr>                   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>\n 1 Afghanistan          2571604.  4.1 e5   20000  1.96e7  4.69e6 2.20e13  2.46e6\n 2 Africa              78159910.  1.45e7  706338  4.38e8  1.08e8 1.17e16  1.49e8\n 3 Albania               181722.  5.5 e4      93  1.35e6  3.24e5 1.05e11  9.35e4\n 4 Algeria                22361.  5   e3    2000  7   e5  9.26e4 8.58e 9  1.5 e3\n 5 American Samoa          5858.  9.6 e3      95  1.46e4  5.35e3 2.86e 7  1.04e4\n 6 Americas            95795716.  3.22e7   66000  5.23e8  1.39e8 1.93e16  1.26e8\n 7 Angola                867412.  2.4 e5     800  5.04e6  1.28e6 1.63e12  1.17e6\n 8 Antigua and Barbuda     7426.  3   e3     400  3.6 e4  8.42e3 7.09e 7  1.1 e4\n 9 Argentina            3685037.  2.4 e6   88000  4.9 e7  8.14e6 6.63e13  3.52e6\n10 Armenia               330230.  3.83e4    6415  1   e6  4.11e5 1.69e11  5.95e5\n# … with 230 more rows, and abbreviated variable names ¹​mean_Value,\n#   ²​median_Value, ³​min_Value, ⁴​max_Value, ⁵​sd_Value, ⁶​var_Value, ⁷​IQR_Value\n```\n:::\n:::\n\n\nThe data spans a period from 1961 to 2018, indicating a long-term collection of data. The Element column contains only one distinct value, which is \"Stocks\". Similarly, the Element Code also has a single value, which is 5111. This suggests that the dataset focuses specifically on the stocks element. The Area Code ranges from 1 to 5504, indicating a wide range of areas or regions included in the dataset. The Value column exhibits a significant amount of variance, suggesting diverse numerical values for the specific element being measured.\n\n### Explain and Interpret\n\nBe sure to explain why you choose a specific group. Comment on the interpretation of any interesting differences between groups that you uncover. This section can be integrated with the exploratory data analysis, just be sure it is included.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}