{
  "hash": "43d59de32ba541e702165c411394bc56",
  "result": {
    "markdown": "---\ntitle: \"Challenge 2\"\nauthor: \"Prachiti Parkar\"\ndescription: \"Data wrangling and Data Sumarization to find statistics in data\"\ndate: \"03/08/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_2\n  - faostat\n  - faostat_livestock\n  - Prachiti Parkar\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Read in the Data\nI have selected faostat_livestock dataset to do my analysis on.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Importing the faostat_livestock dataset and reading them\nlibrary(readr)\ndata <-read_csv(\"_data/FAOSTAT_livestock.csv\")\n#Lets see the first 3 rows of the dataset\nhead(data, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 14\n  Domai…¹ Domain Area …² Area  Eleme…³ Element Item …⁴ Item  Year …⁵  Year Unit \n  <chr>   <chr>    <dbl> <chr>   <dbl> <chr>     <dbl> <chr>   <dbl> <dbl> <chr>\n1 QA      Live …       2 Afgh…    5111 Stocks     1107 Asses    1961  1961 Head \n2 QA      Live …       2 Afgh…    5111 Stocks     1107 Asses    1962  1962 Head \n3 QA      Live …       2 Afgh…    5111 Stocks     1107 Asses    1963  1963 Head \n# … with 3 more variables: Value <dbl>, Flag <chr>, `Flag Description` <chr>,\n#   and abbreviated variable names ¹​`Domain Code`, ²​`Area Code`,\n#   ³​`Element Code`, ⁴​`Item Code`, ⁵​`Year Code`\n```\n:::\n:::\n\n\n## Describe the data\n\nUsing R commands I am exploring the data and coming up with the description from the data.\n\nThere are total 82117 rows and 14 columns\nThe data ranges from year 1961 to 2018\n\n### Checking the variation in data for each column\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Check the variation in data for each column\nsummary(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Domain Code           Domain            Area Code          Area          \n Length:82116       Length:82116       Min.   :   1.0   Length:82116      \n Class :character   Class :character   1st Qu.:  73.0   Class :character  \n Mode  :character   Mode  :character   Median : 146.0   Mode  :character  \n                                       Mean   : 912.7                     \n                                       3rd Qu.: 221.0                     \n                                       Max.   :5504.0                     \n                                                                          \n  Element Code    Element            Item Code        Item          \n Min.   :5111   Length:82116       Min.   : 866   Length:82116      \n 1st Qu.:5111   Class :character   1st Qu.: 976   Class :character  \n Median :5111   Mode  :character   Median :1034   Mode  :character  \n Mean   :5111                      Mean   :1018                     \n 3rd Qu.:5111                      3rd Qu.:1096                     \n Max.   :5111                      Max.   :1126                     \n                                                                    \n   Year Code         Year          Unit               Value          \n Min.   :1961   Min.   :1961   Length:82116       Min.   :0.000e+00  \n 1st Qu.:1976   1st Qu.:1976   Class :character   1st Qu.:1.250e+04  \n Median :1991   Median :1991   Mode  :character   Median :2.247e+05  \n Mean   :1990   Mean   :1990                      Mean   :1.163e+07  \n 3rd Qu.:2005   3rd Qu.:2005                      3rd Qu.:2.377e+06  \n Max.   :2018   Max.   :2018                      Max.   :1.490e+09  \n                                                  NA's   :1301       \n     Flag           Flag Description  \n Length:82116       Length:82116      \n Class :character   Class :character  \n Mode  :character   Mode  :character  \n                                      \n                                      \n                                      \n                                      \n```\n:::\n:::\n\n\n## Provide Grouped Summary Statistics\n\nConducting  exploratory data analysis, using dplyr commands such as `group_by()`, `select()`, `filter()`, and `summarise()`.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#install.packages(\"dplyr\")\nlibrary(dplyr)\n```\n:::\n\n\nGrouping by the Area and finding the mean_value\n\n::: {.cell}\n\n```{.r .cell-code}\ndata %>% \n  group_by(Area) %>% \n  summarise(mean_value = mean(Value))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 253 × 2\n   Area                mean_value\n   <chr>                    <dbl>\n 1 Afghanistan           3597216.\n 2 Africa               78159910.\n 3 Albania                    NA \n 4 Algeria               2575444.\n 5 American Samoa           5399.\n 6 Americas             95795716.\n 7 Angola                1123117.\n 8 Antigua and Barbuda      7877.\n 9 Argentina            12879607.\n10 Armenia                167587.\n# … with 243 more rows\n```\n:::\n:::\n\n\nTable output by selecting Columns \"Area\", \"Year\", and \"Value\".\n\n::: {.cell}\n\n```{.r .cell-code}\ndata %>% \n  select(Area, Year, Value)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 82,116 × 3\n   Area         Year   Value\n   <chr>       <dbl>   <dbl>\n 1 Afghanistan  1961 1300000\n 2 Afghanistan  1962  851850\n 3 Afghanistan  1963 1001112\n 4 Afghanistan  1964 1150000\n 5 Afghanistan  1965 1300000\n 6 Afghanistan  1966 1200000\n 7 Afghanistan  1967 1200000\n 8 Afghanistan  1968 1328000\n 9 Afghanistan  1969 1250000\n10 Afghanistan  1970 1300000\n# … with 82,106 more rows\n```\n:::\n:::\n\n\nI wanted to check out how any data rows / points are available for Afghanistan and Ireland in the year of 1962 for the item Asses. There are 2 datapoints available.\n\n::: {.cell}\n\n```{.r .cell-code}\ndata %>% \n  filter(Area == \"Afghanistan\" | Area == \"Ireland\",Item == \"Asses\", Year == 1962)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 14\n  Domai…¹ Domain Area …² Area  Eleme…³ Element Item …⁴ Item  Year …⁵  Year Unit \n  <chr>   <chr>    <dbl> <chr>   <dbl> <chr>     <dbl> <chr>   <dbl> <dbl> <chr>\n1 QA      Live …       2 Afgh…    5111 Stocks     1107 Asses    1962  1962 Head \n2 QA      Live …     104 Irel…    5111 Stocks     1107 Asses    1962  1962 Head \n# … with 3 more variables: Value <dbl>, Flag <chr>, `Flag Description` <chr>,\n#   and abbreviated variable names ¹​`Domain Code`, ²​`Area Code`,\n#   ³​`Element Code`, ⁴​`Item Code`, ⁵​`Year Code`\n```\n:::\n:::\n\n\n\n## Table Value Statistics\nFind the central tendency (mean, median, mode) and dispersion (standard deviation, mix/max/quantile) for Value within the data set.\n\n::: {.cell}\n\n```{.r .cell-code}\n#deleting the rows with Null values\ndata2 <- na.omit(data)\n# Find the central tendency (mean, median, mode) and dispersion (standard deviation, mix/max/quantile) for different subgroups within the data set.\ndata2%>%\n  group_by(Year)%>%\n  summarize(mean.Value = mean(Value, na.rm = TRUE), median.Value = median(Value, na.rm = TRUE), min.Value = min(Value, na.rm = TRUE), max.Value = max(Value, na.rm = TRUE), sd.Value = sd(Value, na.rm = TRUE), var.Value = var(Value, na.rm = TRUE), IQR.Value = IQR(Value, na.rm = TRUE))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 58 × 8\n    Year mean.Value median.Value min.Value  max.Value  sd.Value var.Va…¹ IQR.V…²\n   <dbl>      <dbl>        <dbl>     <dbl>      <dbl>     <dbl>    <dbl>   <dbl>\n 1  1961  14080955.      129000         10  994268736 66803024.  4.46e15  2.14e6\n 2  1962  14085663.      130000         10  997193122 66008462.  4.36e15  2.01e6\n 3  1963  14568714.      154000         10  999696719 67268611.  4.53e15  2.49e6\n 4  1964  15101322.      160000         10 1013486149 68974136.  4.76e15  2.61e6\n 5  1965  15558689.      140000         10 1030878735 70820667.  5.02e15  2.75e6\n 6  1966  15481029.      155000         10 1040688491 72204592.  5.21e15  2.42e6\n 7  1967  15804831.      148000         10 1059154631 72456707.  5.25e15  2.54e6\n 8  1968  15526705.      105850         10 1074022618 72343610.  5.23e15  2.25e6\n 9  1969  15203756.      116412.        12 1080720926 71629580.  5.13e15  2.15e6\n10  1970  15475993.      103000         12 1081641464 72217288.  5.22e15  2.24e6\n# … with 48 more rows, and abbreviated variable names ¹​var.Value, ²​IQR.Value\n```\n:::\n:::\n\n\nSome Conclusion from seeing the data summary\n\n1. The Data is Collected from the year 1961 - 2018\n2. The Element column just has one value Stocks and the Element Code also has only 1 value - 5111\n3. The Area Code varies from 1 - 5504\n4. The Value Column has a lot of variance\n\nSome insights:\nThere is no need of both Year Code and Year, either can be used to save space\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}