{
  "hash": "9c3b4882e033d46171e9ed0744fd3dc3",
  "result": {
    "markdown": "---\ntitle: \"Challenge 1\"\nauthor: \"Maanusri Balasubramanian\"\ndescription: \"Reading in data and creating a post\"\ndate: \"05/03/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_1\n  - maanusri balasubramanian\n  - railroads\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Challenge Overview\n\nToday's challenge is to\n\n1)  read in a dataset, and\n\n2)  describe the dataset using both words and any supporting information (e.g., tables, etc)\n\n## Read in the Data\n\nRead in one (or more) of the following data sets, using the correct R package and command.\n\n-   railroad_2012_clean_county.csv ⭐\n-   birds.csv ⭐⭐\n-   FAOstat\\*.csv ⭐⭐\n-   wild_bird_data.xlsx ⭐⭐⭐\n-   StateCounty2012.xls ⭐⭐⭐⭐\n\nFind the `_data` folder, located inside the `posts` folder. Then you can read in the data, using either one of the `readr` standard tidy read commands, or a specialized package such as `readxl`.\n\nAdd any comments or documentation as needed. More challenging data sets may require additional code chunks and documentation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# loading the data\nrr <- read_csv(\"_data/railroad_2012_clean_county.csv\")\n\n# printing first 5 rows of the dataset\nhead(rr)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 3\n  state county               total_employees\n  <chr> <chr>                          <dbl>\n1 AE    APO                                2\n2 AK    ANCHORAGE                          7\n3 AK    FAIRBANKS NORTH STAR               2\n4 AK    JUNEAU                             3\n5 AK    MATANUSKA-SUSITNA                  2\n6 AK    SITKA                              1\n```\n:::\n:::\n\n\n## Describe the data\n\nUsing a combination of words and results of R commands, can you provide a high level description of the data? Describe as efficiently as possible where/how the data was (likely) gathered, indicate the cases and variables (both the interpretation and any details you deem useful to the reader to fully understand your chosen data).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# description of the dataset\nstr(rr)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nspc_tbl_ [2,930 × 3] (S3: spec_tbl_df/tbl_df/tbl/data.frame)\n $ state          : chr [1:2930] \"AE\" \"AK\" \"AK\" \"AK\" ...\n $ county         : chr [1:2930] \"APO\" \"ANCHORAGE\" \"FAIRBANKS NORTH STAR\" \"JUNEAU\" ...\n $ total_employees: num [1:2930] 2 7 2 3 2 1 88 102 143 1 ...\n - attr(*, \"spec\")=\n  .. cols(\n  ..   state = col_character(),\n  ..   county = col_character(),\n  ..   total_employees = col_double()\n  .. )\n - attr(*, \"problems\")=<externalptr> \n```\n:::\n\n```{.r .cell-code}\n# number of rows and columns in the dataset\ndim(rr)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2930    3\n```\n:::\n\n```{.r .cell-code}\n# column names\ncolnames(rr)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"state\"           \"county\"          \"total_employees\"\n```\n:::\n:::\n\n\nFrom the above commands we can see that \"railroad_2012_clean_county.csv\" gives us the count of employees working in various counties in each state for the railroad in 2012. There are a total of 2930 entries. Each row gives us information about the number of employees in a county in the state. There are 3 columns, namely: state, county and total_employees.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Summarizing the data with summary\nsummary(rr)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    state              county          total_employees  \n Length:2930        Length:2930        Min.   :   1.00  \n Class :character   Class :character   1st Qu.:   7.00  \n Mode  :character   Mode  :character   Median :  21.00  \n                                       Mean   :  87.18  \n                                       3rd Qu.:  65.00  \n                                       Max.   :8207.00  \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Arranging entries wrt total employees\narrange(rr, `total_employees`)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2,930 × 3\n   state county   total_employees\n   <chr> <chr>              <dbl>\n 1 AK    SITKA                  1\n 2 AL    BARBOUR                1\n 3 AL    HENRY                  1\n 4 AP    APO                    1\n 5 AR    NEWTON                 1\n 6 CA    MONO                   1\n 7 CO    BENT                   1\n 8 CO    CHEYENNE               1\n 9 CO    COSTILLA               1\n10 CO    DOLORES                1\n# ℹ 2,920 more rows\n```\n:::\n\n```{.r .cell-code}\n# Arranging entries wrt total employees in the descending order\narrange(rr, desc(`total_employees`))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2,930 × 3\n   state county           total_employees\n   <chr> <chr>                      <dbl>\n 1 IL    COOK                        8207\n 2 TX    TARRANT                     4235\n 3 NE    DOUGLAS                     3797\n 4 NY    SUFFOLK                     3685\n 5 VA    INDEPENDENT CITY            3249\n 6 FL    DUVAL                       3073\n 7 CA    SAN BERNARDINO              2888\n 8 CA    LOS ANGELES                 2545\n 9 TX    HARRIS                      2535\n10 NE    LINCOLN                     2289\n# ℹ 2,920 more rows\n```\n:::\n:::\n\nFrom the above result we know that the country 'COOK' in IL has the highest number of employees: 8207 and 1 is the minimum number of employees in any country (many counties have only 1 employee).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Grouping in terms of state to summarise\ngrouped_rr_state <- rr%>%\n  group_by(state)%>%\n  summarize(state_employees = sum(total_employees))%>%\n  arrange(desc(`state_employees`))\ngrouped_rr_state\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 53 × 2\n   state state_employees\n   <chr>           <dbl>\n 1 TX              19839\n 2 IL              19131\n 3 NY              17050\n 4 NE              13176\n 5 CA              13137\n 6 PA              12769\n 7 OH               9056\n 8 GA               8605\n 9 IN               8537\n10 MO               8419\n# ℹ 43 more rows\n```\n:::\n\n```{.r .cell-code}\ndim(grouped_rr_state)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 53  2\n```\n:::\n:::\n\nFrom the above results we know that TX has the highest number of rail road employees: 19839 and AP has the least number of employees: 1.\n\nAnd from the dimensions of grouped_rr_state, we know that there are 53 unique states in which rail road employees work.",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}