{
  "hash": "1ab270ab3e4bc80bede840b5f01e58f2",
  "result": {
    "markdown": "---\ntitle: \"Challenge 2\"\nauthor: \"Maanusri Balasubramanian\"\ndescription: \"Data wrangling: using group() and summarise()\"\ndate: \"05/03/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_2\n  - maanusri balasubramanian\n  - railroads\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Challenge Overview\n\nToday's challenge is to\n\n1)  read in a data set, and describe the data using both words and any supporting information (e.g., tables, etc)\n2)  provide summary statistics for different interesting groups within the data, and interpret those statistics\n\n## Read in the Data\n\nRead in one (or more) of the following data sets, available in the `posts/_data` folder, using the correct R package and command.\n\n-   railroad\\*.csv or StateCounty2012.xls ⭐\n-   FAOstat\\*.csv or birds.csv ⭐⭐⭐\n-   hotel_bookings.csv ⭐⭐⭐⭐\n\nAdd any comments or documentation as needed. More challenging data may require additional code chunks and documentation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# reading the CSV file\nrr <- read_csv(\"_data/railroad_2012_clean_county.csv\")\n```\n:::\n\n\n## Describe the data\n\nUsing a combination of words and results of R commands, can you provide a high level description of the data? Describe as efficiently as possible where/how the data was (likely) gathered, indicate the cases and variables (both the interpretation and any details you deem useful to the reader to fully understand your chosen data).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# printing number of rows and columns in the dataset\ndim(rr)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2930    3\n```\n:::\n\n```{.r .cell-code}\n# description of the dataset\nstr(rr)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nspc_tbl_ [2,930 × 3] (S3: spec_tbl_df/tbl_df/tbl/data.frame)\n $ state          : chr [1:2930] \"AE\" \"AK\" \"AK\" \"AK\" ...\n $ county         : chr [1:2930] \"APO\" \"ANCHORAGE\" \"FAIRBANKS NORTH STAR\" \"JUNEAU\" ...\n $ total_employees: num [1:2930] 2 7 2 3 2 1 88 102 143 1 ...\n - attr(*, \"spec\")=\n  .. cols(\n  ..   state = col_character(),\n  ..   county = col_character(),\n  ..   total_employees = col_double()\n  .. )\n - attr(*, \"problems\")=<externalptr> \n```\n:::\n:::\n\n\nFrom the above results, we know that the dataset has 2930 rows and 3 columns.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolnames(rr)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"state\"           \"county\"          \"total_employees\"\n```\n:::\n:::\n\n\nThe 3 columns in the dataset are: state, county and total_employees.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(rr)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 3\n  state county               total_employees\n  <chr> <chr>                          <dbl>\n1 AE    APO                                2\n2 AK    ANCHORAGE                          7\n3 AK    FAIRBANKS NORTH STAR               2\n4 AK    JUNEAU                             3\n5 AK    MATANUSKA-SUSITNA                  2\n6 AK    SITKA                              1\n```\n:::\n:::\n\nWe can infer that the dataset gives us the total number of railroad employees in a county in a state in 2012 from this.\n\n## Provide Grouped Summary Statistics\n\nConduct some exploratory data analysis, using dplyr commands such as `group_by()`, `select()`, `filter()`, and `summarise()`. Find the central tendency (mean, median, mode) and dispersion (standard deviation, mix/max/quantile) for different subgroups within the data set.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Count of unique states in the dataset\nstates <- select(rr, `state`)\n\n# library(\"dplyr\")\ncount(distinct(states))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 1\n      n\n  <int>\n1    53\n```\n:::\n:::\n\n\nTotal railroad employee information about 53 unique states is present in this dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# retrieving information of the county with the maximum number of railroad employees\nsummarize(rr, employee_count = max(total_employees), maxCounty = county[which.max(total_employees)])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 2\n  employee_count maxCounty\n           <dbl> <chr>    \n1           8207 COOK     \n```\n:::\n:::\n\nCOOK is the county with the maximum number of railroad employees (8207).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# retrieving information of the county with the maximum number of railroad employees\nreframe(rr, employee_count = min(total_employees), minCounty = county[which(total_employees == min(total_employees))])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 145 × 2\n   employee_count minCounty\n            <dbl> <chr>    \n 1              1 SITKA    \n 2              1 BARBOUR  \n 3              1 HENRY    \n 4              1 APO      \n 5              1 NEWTON   \n 6              1 MONO     \n 7              1 BENT     \n 8              1 CHEYENNE \n 9              1 COSTILLA \n10              1 DOLORES  \n# ℹ 135 more rows\n```\n:::\n:::\n\nFrom the above result, we know that there are 145 counties with only 1 railroad employee (which is the minimum employee count in any county).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Grouping in terms of state to summarise total_employees in each state and arranging accordingly\ngrouped_rr_state <- rr%>%\n  group_by(state)%>%\n  summarize(state_employees = sum(total_employees))%>%\n  arrange(desc(`state_employees`))\ngrouped_rr_state\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 53 × 2\n   state state_employees\n   <chr>           <dbl>\n 1 TX              19839\n 2 IL              19131\n 3 NY              17050\n 4 NE              13176\n 5 CA              13137\n 6 PA              12769\n 7 OH               9056\n 8 GA               8605\n 9 IN               8537\n10 MO               8419\n# ℹ 43 more rows\n```\n:::\n:::\n\nFrom the above results we know that TX has the highest number of rail road employees (19839) and AP has the least number of railroad employees (1).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Grouping in terms of state to summarise mean total_employees in each state wrt number of counties and arranging accordingly \ngrouped_rr_state_mean <- rr%>%\n  group_by(state)%>%\n  summarize(mean_state_employees = mean(total_employees))%>%\n  arrange(desc(`mean_state_employees`))\ngrouped_rr_state_mean\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 53 × 2\n   state mean_state_employees\n   <chr>                <dbl>\n 1 DE                    498.\n 2 NJ                    397.\n 3 CT                    324 \n 4 MA                    282.\n 5 NY                    280.\n 6 DC                    279 \n 7 CA                    239.\n 8 AZ                    210.\n 9 PA                    196.\n10 MD                    196.\n# ℹ 43 more rows\n```\n:::\n:::\n\nFrom the above results we know that DE has the highest mean number of rail road employees (498.33) and AP has the least mean number of railroad employees (1). That is in DE, the mean number of employees in each county is 498.33.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Grouping in terms of state to summarise median total_employees in each state wrt number of counties and arranging accordingly \ngrouped_rr_state_median <- rr%>%\n  group_by(state)%>%\n  summarize(median_state_employees = median(total_employees))%>%\n  arrange(desc(`median_state_employees`))\ngrouped_rr_state_median\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 53 × 2\n   state median_state_employees\n   <chr>                  <dbl>\n 1 NJ                      296 \n 2 DC                      279 \n 3 MA                      271 \n 4 DE                      158 \n 5 CT                      125 \n 6 MD                      108.\n 7 AZ                       94 \n 8 PA                       85 \n 9 NY                       71 \n10 CA                       61 \n# ℹ 43 more rows\n```\n:::\n:::\n\nFrom the above results we can infer the median number of railroad employees in each state wrt the counties in the state with employees.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Mode of entries - statewise i.e the state with the maximum number of counties with railroad employees\nrr %>%\n  count(state, sort=TRUE)%>%\n  slice(1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 2\n  state     n\n  <chr> <int>\n1 TX      221\n```\n:::\n:::\n\nWe are finding the mode of the number of counties in any state with the above command. We are counting the number of entries for a particular state, which gives us the number of counties in the state with railroad employees. We then find the state with the maximum number of entries (mode).\n\nWe know that TX has the highest number of counties with railroad employees. There are 221 counties in TX with railroad employees.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filtering the employee information of counties in TX\ntexas_counties <- filter(rr, state == 'TX')\ncount(texas_counties)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 1\n      n\n  <int>\n1   221\n```\n:::\n:::\n\nVerifying the number of counties in TX with the filter and count commands again. There are 221 counties as returned earlier.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Grouping in terms of state to summarise standard deviation of total_employees in each state wrt number of counties and arranging accordingly \ngrouped_rr_state_sd <- rr%>%\n  group_by(state)%>%\n  summarize(sd_state_employees = sd(total_employees))%>%\n  arrange(desc(`sd_state_employees`))\ngrouped_rr_state_sd\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 53 × 2\n   state sd_state_employees\n   <chr>              <dbl>\n 1 IL                  829.\n 2 DE                  674.\n 3 NY                  591.\n 4 CA                  549.\n 5 CT                  520.\n 6 NE                  512.\n 7 FL                  386.\n 8 TX                  350.\n 9 VA                  341.\n10 NJ                  338.\n# ℹ 43 more rows\n```\n:::\n:::\n\nFrom the above result, we rank the states according to the standard deviation of railroad employee count.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# grouping dataset based on the state\ngrouped_rr_state <- rr%>%\n  group_by(state)\n\n# summary of this subset gives us info like min, max, median, mean and quantiles\nsummary(grouped_rr_state)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    state              county          total_employees  \n Length:2930        Length:2930        Min.   :   1.00  \n Class :character   Class :character   1st Qu.:   7.00  \n Mode  :character   Mode  :character   Median :  21.00  \n                                       Mean   :  87.18  \n                                       3rd Qu.:  65.00  \n                                       Max.   :8207.00  \n```\n:::\n:::\n\nFrom the quartile distributions we can infer that lot of the states have less number of employees, i.e the distribution of employees state-wise is skewed.\n\n### Explain and Interpret\n\nBe sure to explain why you choose a specific group. Comment on the interpretation of any interesting differences between groups that you uncover. This section can be integrated with the exploratory data analysis, just be sure it is included.\n\nI chose this specific group to understand the distribution of railroad employees statewise. We can infer that there are railroad employees in 53 unique states, 'COOK' in IL is the county with the highest number of railroad employees (8207) and there are 145 counties with only 1 railroad employee. \n\nFrom this grouping analysis based on states, we got to know that TX has the highest number of rail road employees (19839) and AP has the least number of railroad employees (1). And DE has the highest mean number of rail road employees (498.33) and AP has the least mean number of railroad employees (1) in its counties. NJ is the state with the highest median of employees county-wise: 296. We also find that TX is the state with maximum number of entries (mode of number of entries), which is in-turn the number of counties. So TX is the state with the maximum number of counties, which is 221.   ",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}